# OpenBind-HIPPO

- **Target: XX01ZVNS2B**
- **Cycle: 02**

## Imports

In [25]:
%load_ext autoreload
%autoreload 2
import hippo
import mrich
from mrich import print
from pathlib import Path
from os import environ
import shutil
import molparse as mp
import pandas as pd

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

# Config

In [26]:
target_name = "XX01ZVNS2B"
target_dir = Path(environ["BULK"]) / "TARGETS" / target_name
cycle_name = "cycle_02"
cycle_dir = Path(cycle_name)
aligned_dir = target_dir / "aligned_files"

## Animal

In [27]:
animal = hippo.HIPPO(target_name, target_dir / f"{target_name}.sqlite")

 Creating HIPPO animal

name = XX01ZVNS2B

db_path = /opt/xchem-fragalysis-2/maxwin/BulkDock/TARGETS/XX01ZVNS2B/XX01ZVNS2B.sqlite

DEBUG: hippo.Database.__init__()

DEBUG: Database.path = /opt/xchem-fragalysis-2/maxwin/BulkDock/TARGETS/XX01ZVNS2B/XX01ZVNS2B.sqlite

DEBUG: hippo.Database.connect()

DEBUG: sqlite3.version='2.6.0'

 Success  Database connected @ /opt/xchem-fragalysis-2/maxwin/BulkDock/TARGETS/XX01ZVNS2B/XX01ZVNS2B.sqlite!

 Success  Initialised animal HIPPO("XX01ZVNS2B")!

## Syndirella inputs

Run syndirella on all ASAP structural hits, with self-referential inspiration

In [4]:
hits = animal.poses(tag="hits")
hits

poses tagged "hits": {P × 337}

In [5]:
hits.to_syndirella("cycle_02/syndirella/elabs/c2_elabs", separate=True)

out_key = c2_elabs

#poses = 337

DEBUG: querying...

Output()

DEBUG: adding inspiration column(s)

 Warning  337 poses have no reference. Setting to self!

['Z0490a' 'Z0844a' 'Z1682a' 'Z2048a' 'Z2971a' 'Z0051a' 'Z0089a' 'Z0101a'
 'Z0130a' 'Z0182b' 'Z0182a' 'Z0227a' 'Z0229a' 'Z0229b' 'Z0386a' 'Z0404a'
 'Z0422a' 'Z0425a' 'Z0429a' 'Z0435a' 'Z0455a' 'Z0465a' 'Z0472a' 'Z0553a'
 'Z0559a' 'Z0589a' 'Z0601a' 'Z0605a' 'Z0673a' 'Z0673b' 'Z0687a' 'Z0693a'
 'Z0701a' 'Z0709a' 'Z0719a' 'Z0727a' 'Z0772a' 'Z0773b' 'Z0773a' 'Z0777a'
 'Z0788b' 'Z0788c' 'Z0788a' 'Z0800a' 'Z0806a' 'Z0806b' 'Z0819a' 'Z0827a'
 'Z0846b' 'Z0846a' 'Z0852a' 'Z0875a' 'Z0884b' 'Z0884a' 'Z0904a' 'Z0917a'
 'Z0945a' 'Z0951a' 'Z0969a' 'Z0969b' 'Z0990b' 'Z0990a' 'Z1046a' 'Z1046b'
 'Z1098a' 'Z1234a' 'Z1237a' 'Z1261a' 'Z1265a' 'Z1271a' 'Z1274a' 'Z1288a'
 'Z1291a' 'Z1317a' 'Z1320a' 'Z1333a' 'Z1342a' 'Z1390a' 'Z1398a' 'Z1406a'
 'Z1413a' 'Z1451a' 'Z1470a' 'Z1495a' 'Z1596a' 'Z1597a' 'Z1664a' 'Z1667a'
 'Z1674a' 'Z1681a' 'Z1688a' 'Z1713a' 'Z1715a' 'Z1716a' 'Z1719a' 'Z1727a'
 'Z1728a' 'Z1729a' 'Z1730a' 'Z1731a' 'Z1743a' 'Z1745a' 'Z1750a' 'Z1752a'
 'Z1753a' 'Z1756a' 'Z1761a' 'Z1837a' 'Z1838a' 'Z2057a' 'Z2094a' 'Z2119a'
 'Z2126a' 'Z2135a' 'Z2217a' 'Z2235a' 'Z2262a' 'Z2439a' 'Z2500a' 'Z2992a'
 'Z3021a' 'Z3024a' 'Z3028a' 'Z3059a' 'Z3060a' 'Z3093a' 'Z3094a' 'Z3264a'
 'Z3394a' 'Z3397a' 'Z3400a' 'Z3432a' 'Z3439a' 'Z3440a' 'Z3441a' 'Z3452a'
 'Z3463a' 'Z3464a' 'Z3465a' 'Z3466a' 'Z3468a' 'Z3469a' 'Z3472a' 'Z3473a'
 'Z3476a' 'Z3477a' 'Z3480a' 'Z3485a' 'Z3486a' 'Z3487a' 'Z3489a' 'Z3495a'
 'Z3501a' 'Z3502a' 'Z3503a' 'Z3505a' 'Z3506a' 'Z3507a' 'Z3515a' 'Z3519a'
 'Z3522a' 'Z3527a' 'Z3545a' 'Z3546a' 'Z3548a' 'Z3553a' 'Z3556a' 'Z3559a'
 'Z3561a' 'Z3596a' 'Z3617a' 'Z3622a' 'Z3646a' 'Z3647a' 'Z3654a' 'Z3665a'
 'Z3673a' 'Z3677a' 'Z3680a' 'Z3685a' 'Z3689a' 'Z3691a' 'Z3696a' 'Z3699a'
 'Z3706a' 'Z3711a' 'Z3720a' 'Z3729a' 'Z3733a' 'Z3743a' 'Z3746a' 'Z3754a'
 'Z3758a' 'Z3767a' 'Z3769a' 'Z3774a' 'Z3790a' 'Z3792a' 'Z3799a' 'Z3802a'
 'Z3803a' 'Z3808a' 'Z3808b' 'Z3813a' 'Z3815a' 'Z3817a' 'Z3819a' 'Z3826a'
 'Z3830a' 'Z3831a' 'Z3833a' 'Z3834a' 'Z3837a' 'Z3842a' 'Z3850a' 'Z3856a'
 'Z3858a' 'Z3867a' 'Z3880a' 'Z3898a' 'Z3936a' 'Z3941a' 'Z3956a' 'Z3970a'
 'Z3980a' 'Z4008a' 'Z4017a' 'Z4019a' 'Z4020a' 'Z4025a' 'Z4031a' 'Z4039a'
 'Z4047a' 'Z4066a' 'Z4070a' 'Z4072a' 'Z4089a' 'Z4090a' 'Z4094a' 'Z4103a'
 'Z4104a' 'Z4114a' 'Z4117a' 'Z4118a' 'Z4120a' 'Z4125a' 'Z4131a' 'Z4132a'
 'Z4134a' 'Z4138a' 'Z4139a' 'Z4153a' 'Z4160a' 'Z4161a' 'Z4164a' 'Z4168a'
 'Z4169a' 'Z4178a' 'Z4179a' 'Z4194a' 'Z4198a' 'Z4200a' 'Z4204a' 'Z4206a'
 'Z4227a' 'Z4240a' 'Z4243a' 'Z4245a' 'Z4429a' 'Z4469a' 'Z4478a' 'Z4498a'
 'Z4756a' 'Z4811a' 'Z4816a' 'Z4827a' 'Z4838a' 'Z4849a' 'Z4855a' 'Z4857a'
 'Z4858a' 'Z4859a' 'Z4861a' 'Z4872a' 'Z4886a' 'Z4887a' 'Z4905a' 'Z4590a'
 'Z4926a' 'Z4931a' 'Z4942a' 'Z4944a' 'Z4951a' 'Z4954a' 'Z4959a' 'Z4959b'
 'Z4963a' 'Z4966a' 'Z4971a' 'Z4978a' 'Z4983a' 'Z4986a' 'Z4991a' 'Z4996a'
 'Z5002a' 'Z5003a' 'Z5010a' 'Z5011a' 'Z5017a' 'Z5020a' 'Z5027a' 'Z5029a'
 'Z5042a' 'Z5061a' 'Z5067a' 'Z5082a' 'Z5084a' 'Z5085a' 'Z5086a' 'Z5122a'
 'Z5124a' 'Z5136a' 'Z5139a' 'Z5148a' 'Z5171a' 'Z5197a' 'Z5200a' 'Z5211a'
 'Z5227a' 'Z5229a' 'Z5230a' 'Z5236a' 'Z5243a' 'Z5246a' 'Z5302a' 'Z5339a'
 'Z5348a']

 Warning  337 poses have no inspirations. Setting to self!

['Z0490a' 'Z0844a' 'Z1682a' 'Z2048a' 'Z2971a' 'Z0051a' 'Z0089a' 'Z0101a'
 'Z0130a' 'Z0182b' 'Z0182a' 'Z0227a' 'Z0229a' 'Z0229b' 'Z0386a' 'Z0404a'
 'Z0422a' 'Z0425a' 'Z0429a' 'Z0435a' 'Z0455a' 'Z0465a' 'Z0472a' 'Z0553a'
 'Z0559a' 'Z0589a' 'Z0601a' 'Z0605a' 'Z0673a' 'Z0673b' 'Z0687a' 'Z0693a'
 'Z0701a' 'Z0709a' 'Z0719a' 'Z0727a' 'Z0772a' 'Z0773b' 'Z0773a' 'Z0777a'
 'Z0788b' 'Z0788c' 'Z0788a' 'Z0800a' 'Z0806a' 'Z0806b' 'Z0819a' 'Z0827a'
 'Z0846b' 'Z0846a' 'Z0852a' 'Z0875a' 'Z0884b' 'Z0884a' 'Z0904a' 'Z0917a'
 'Z0945a' 'Z0951a' 'Z0969a' 'Z0969b' 'Z0990b' 'Z0990a' 'Z1046a' 'Z1046b'
 'Z1098a' 'Z1234a' 'Z1237a' 'Z1261a' 'Z1265a' 'Z1271a' 'Z1274a' 'Z1288a'
 'Z1291a' 'Z1317a' 'Z1320a' 'Z1333a' 'Z1342a' 'Z1390a' 'Z1398a' 'Z1406a'
 'Z1413a' 'Z1451a' 'Z1470a' 'Z1495a' 'Z1596a' 'Z1597a' 'Z1664a' 'Z1667a'
 'Z1674a' 'Z1681a' 'Z1688a' 'Z1713a' 'Z1715a' 'Z1716a' 'Z1719a' 'Z1727a'
 'Z1728a' 'Z1729a' 'Z1730a' 'Z1731a' 'Z1743a' 'Z1745a' 'Z1750a' 'Z1752a'
 'Z1753a' 'Z1756a' 'Z1761a' 'Z1837a' 'Z1838a' 'Z2057a' 'Z2094a' 'Z2119a'
 'Z2126a' 'Z2135a' 'Z2217a' 'Z2235a' 'Z2262a' 'Z2439a' 'Z2500a' 'Z2992a'
 'Z3021a' 'Z3024a' 'Z3028a' 'Z3059a' 'Z3060a' 'Z3093a' 'Z3094a' 'Z3264a'
 'Z3394a' 'Z3397a' 'Z3400a' 'Z3432a' 'Z3439a' 'Z3440a' 'Z3441a' 'Z3452a'
 'Z3463a' 'Z3464a' 'Z3465a' 'Z3466a' 'Z3468a' 'Z3469a' 'Z3472a' 'Z3473a'
 'Z3476a' 'Z3477a' 'Z3480a' 'Z3485a' 'Z3486a' 'Z3487a' 'Z3489a' 'Z3495a'
 'Z3501a' 'Z3502a' 'Z3503a' 'Z3505a' 'Z3506a' 'Z3507a' 'Z3515a' 'Z3519a'
 'Z3522a' 'Z3527a' 'Z3545a' 'Z3546a' 'Z3548a' 'Z3553a' 'Z3556a' 'Z3559a'
 'Z3561a' 'Z3596a' 'Z3617a' 'Z3622a' 'Z3646a' 'Z3647a' 'Z3654a' 'Z3665a'
 'Z3673a' 'Z3677a' 'Z3680a' 'Z3685a' 'Z3689a' 'Z3691a' 'Z3696a' 'Z3699a'
 'Z3706a' 'Z3711a' 'Z3720a' 'Z3729a' 'Z3733a' 'Z3743a' 'Z3746a' 'Z3754a'
 'Z3758a' 'Z3767a' 'Z3769a' 'Z3774a' 'Z3790a' 'Z3792a' 'Z3799a' 'Z3802a'
 'Z3803a' 'Z3808a' 'Z3808b' 'Z3813a' 'Z3815a' 'Z3817a' 'Z3819a' 'Z3826a'
 'Z3830a' 'Z3831a' 'Z3833a' 'Z3834a' 'Z3837a' 'Z3842a' 'Z3850a' 'Z3856a'
 'Z3858a' 'Z3867a' 'Z3880a' 'Z3898a' 'Z3936a' 'Z3941a' 'Z3956a' 'Z3970a'
 'Z3980a' 'Z4008a' 'Z4017a' 'Z4019a' 'Z4020a' 'Z4025a' 'Z4031a' 'Z4039a'
 'Z4047a' 'Z4066a' 'Z4070a' 'Z4072a' 'Z4089a' 'Z4090a' 'Z4094a' 'Z4103a'
 'Z4104a' 'Z4114a' 'Z4117a' 'Z4118a' 'Z4120a' 'Z4125a' 'Z4131a' 'Z4132a'
 'Z4134a' 'Z4138a' 'Z4139a' 'Z4153a' 'Z4160a' 'Z4161a' 'Z4164a' 'Z4168a'
 'Z4169a' 'Z4178a' 'Z4179a' 'Z4194a' 'Z4198a' 'Z4200a' 'Z4204a' 'Z4206a'
 'Z4227a' 'Z4240a' 'Z4243a' 'Z4245a' 'Z4429a' 'Z4469a' 'Z4478a' 'Z4498a'
 'Z4756a' 'Z4811a' 'Z4816a' 'Z4827a' 'Z4838a' 'Z4849a' 'Z4855a' 'Z4857a'
 'Z4858a' 'Z4859a' 'Z4861a' 'Z4872a' 'Z4886a' 'Z4887a' 'Z4905a' 'Z4590a'
 'Z4926a' 'Z4931a' 'Z4942a' 'Z4944a' 'Z4951a' 'Z4954a' 'Z4959a' 'Z4959b'
 'Z4963a' 'Z4966a' 'Z4971a' 'Z4978a' 'Z4983a' 'Z4986a' 'Z4991a' 'Z4996a'
 'Z5002a' 'Z5003a' 'Z5010a' 'Z5011a' 'Z5017a' 'Z5020a' 'Z5027a' 'Z5029a'
 'Z5042a' 'Z5061a' 'Z5067a' 'Z5082a' 'Z5084a' 'Z5085a' 'Z5086a' 'Z5122a'
 'Z5124a' 'Z5136a' 'Z5139a' 'Z5148a' 'Z5171a' 'Z5197a' 'Z5200a' 'Z5211a'
 'Z5227a' 'Z5229a' 'Z5230a' 'Z5236a' 'Z5243a' 'Z5246a' 'Z5302a' 'Z5339a'
 'Z5348a']

 DISK  Writing cycle_02/syndirella/elabs/templates...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z0490a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z0844a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z1682a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z2048a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z2971a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z0051a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z0089a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z0101a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z0130a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z0182b_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z0182a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z0227a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z0229a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z0229b_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z0386a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z0404a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z0422a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z0425a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z0429a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z0435a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z0455a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z0465a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z0472a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z0553a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z0559a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z0589a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z0601a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z0605a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z0673a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z0673b_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z0687a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z0693a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z0701a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z0709a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z0719a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z0727a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z0772a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z0773b_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z0773a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z0777a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z0788b_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z0788c_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z0788a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z0800a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z0806a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z0806b_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z0819a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z0827a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z0846b_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z0846a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z0852a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z0875a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z0884b_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z0884a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z0904a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z0917a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z0945a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z0951a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z0969a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z0969b_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z0990b_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z0990a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z1046a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z1046b_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z1098a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z1234a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z1237a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z1261a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z1265a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z1271a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z1274a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z1288a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z1291a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z1317a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z1320a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z1333a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z1342a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z1390a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z1398a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z1406a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z1413a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z1451a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z1470a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z1495a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z1596a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z1597a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z1664a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z1667a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z1674a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z1681a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z1688a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z1713a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z1715a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z1716a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z1719a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z1727a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z1728a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z1729a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z1730a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z1731a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z1743a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z1745a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z1750a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z1752a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z1753a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z1756a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z1761a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z1837a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z1838a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z2057a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z2094a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z2119a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z2126a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z2135a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z2217a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z2235a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z2262a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z2439a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z2500a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z2992a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z3021a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z3024a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z3028a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z3059a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z3060a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z3093a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z3094a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z3264a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z3394a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z3397a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z3400a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z3432a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z3439a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z3440a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z3441a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z3452a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z3463a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z3464a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z3465a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z3466a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z3468a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z3469a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z3472a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z3473a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z3476a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z3477a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z3480a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z3485a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z3486a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z3487a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z3489a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z3495a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z3501a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z3502a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z3503a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z3505a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z3506a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z3507a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z3515a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z3519a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z3522a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z3527a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z3545a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z3546a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z3548a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z3553a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z3556a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z3559a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z3561a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z3596a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z3617a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z3622a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z3646a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z3647a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z3654a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z3665a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z3673a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z3677a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z3680a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z3685a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z3689a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z3691a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z3696a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z3699a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z3706a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z3711a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z3720a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z3729a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z3733a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z3743a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z3746a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z3754a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z3758a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z3767a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z3769a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z3774a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z3790a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z3792a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z3799a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z3802a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z3803a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z3808a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z3808b_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z3813a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z3815a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z3817a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z3819a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z3826a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z3830a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z3831a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z3833a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z3834a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z3837a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z3842a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z3850a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z3856a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z3858a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z3867a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z3880a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z3898a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z3936a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z3941a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z3956a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z3970a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z3980a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z4008a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z4017a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z4019a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z4020a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z4025a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z4031a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z4039a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z4047a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z4066a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z4070a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z4072a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z4089a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z4090a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z4094a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z4103a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z4104a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z4114a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z4117a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z4118a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z4120a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z4125a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z4131a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z4132a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z4134a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z4138a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z4139a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z4153a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z4160a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z4161a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z4164a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z4168a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z4169a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z4178a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z4179a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z4194a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z4198a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z4200a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z4204a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z4206a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z4227a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z4240a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z4243a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z4245a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z4429a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z4469a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z4478a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z4498a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z4756a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z4811a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z4816a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z4827a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z4838a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z4849a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z4855a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z4857a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z4858a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z4859a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z4861a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z4872a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z4886a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z4887a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z4905a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z4590a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z4926a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z4931a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z4942a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z4944a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z4951a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z4954a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z4959a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z4959b_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z4963a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z4966a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z4971a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z4978a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z4983a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z4986a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z4991a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z4996a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z5002a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z5003a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z5010a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z5011a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z5017a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z5020a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z5027a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z5029a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z5042a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z5061a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z5067a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z5082a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z5084a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z5085a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z5086a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z5122a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z5124a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z5136a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z5139a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z5148a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z5171a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z5197a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z5200a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z5211a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z5227a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z5229a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z5230a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z5236a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z5243a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z5246a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z5302a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z5339a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/templates/Z5348a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z0490a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z0844a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z1682a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z2048a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z2971a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z0051a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z0089a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z0101a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z0130a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z0182b_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z0182a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z0227a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z0229a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z0229b_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z0386a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z0404a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z0422a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z0425a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z0429a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z0435a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z0455a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z0465a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z0472a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z0553a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z0559a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z0589a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z0601a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z0605a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z0673a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z0673b_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z0687a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z0693a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z0701a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z0709a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z0719a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z0727a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z0772a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z0773b_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z0773a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z0777a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z0788b_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z0788c_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z0788a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z0800a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z0806a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z0806b_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z0819a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z0827a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z0846b_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z0846a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z0852a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z0875a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z0884b_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z0884a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z0904a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z0917a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z0945a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z0951a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z0969a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z0969b_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z0990b_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z0990a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z1046a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z1046b_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z1098a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z1234a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z1237a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z1261a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z1265a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z1271a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z1274a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z1288a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z1291a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z1317a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z1320a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z1333a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z1342a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z1390a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z1398a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z1406a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z1413a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z1451a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z1470a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z1495a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z1596a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z1597a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z1664a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z1667a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z1674a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z1681a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z1688a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z1713a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z1715a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z1716a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z1719a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z1727a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z1728a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z1729a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z1730a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z1731a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z1743a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z1745a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z1750a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z1752a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z1753a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z1756a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z1761a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z1837a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z1838a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z2057a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z2094a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z2119a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z2126a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z2135a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z2217a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z2235a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z2262a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z2439a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z2500a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z2992a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z3021a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z3024a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z3028a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z3059a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z3060a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z3093a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z3094a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z3264a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z3394a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z3397a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z3400a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z3432a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z3439a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z3440a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z3441a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z3452a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z3463a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z3464a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z3465a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z3466a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z3468a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z3469a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z3472a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z3473a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z3476a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z3477a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z3480a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z3485a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z3486a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z3487a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z3489a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z3495a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z3501a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z3502a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z3503a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z3505a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z3506a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z3507a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z3515a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z3519a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z3522a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z3527a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z3545a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z3546a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z3548a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z3553a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z3556a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z3559a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z3561a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z3596a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z3617a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z3622a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z3646a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z3647a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z3654a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z3665a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z3673a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z3677a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z3680a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z3685a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z3689a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z3691a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z3696a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z3699a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z3706a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z3711a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z3720a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z3729a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z3733a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z3743a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z3746a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z3754a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z3758a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z3767a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z3769a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z3774a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z3790a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z3792a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z3799a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z3802a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z3803a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z3808a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z3808b_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z3813a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z3815a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z3817a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z3819a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z3826a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z3830a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z3831a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z3833a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z3834a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z3837a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z3842a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z3850a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z3856a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z3858a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z3867a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z3880a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z3898a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z3936a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z3941a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z3956a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z3970a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z3980a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z4008a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z4017a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z4019a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z4020a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z4025a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z4031a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z4039a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z4047a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z4066a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z4070a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z4072a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z4089a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z4090a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z4094a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z4103a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z4104a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z4114a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z4117a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z4118a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z4120a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z4125a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z4131a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z4132a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z4134a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z4138a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z4139a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z4153a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z4160a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z4161a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z4164a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z4168a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z4169a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z4178a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z4179a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z4194a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z4198a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z4200a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z4204a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z4206a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z4227a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z4240a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z4243a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z4245a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z4429a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z4469a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z4478a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z4498a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z4756a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z4811a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z4816a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z4827a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z4838a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z4849a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z4855a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z4857a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z4858a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z4859a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z4861a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z4872a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z4886a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z4887a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z4905a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z4590a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z4926a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z4931a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z4942a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z4944a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z4951a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z4954a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z4959a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z4959b_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z4963a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z4966a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z4971a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z4978a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z4983a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z4986a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z4991a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z4996a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z5002a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z5003a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z5010a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z5011a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z5017a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z5020a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z5027a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z5029a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z5042a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z5061a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z5067a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z5082a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z5084a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z5085a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z5086a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z5122a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z5124a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z5136a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z5139a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z5148a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z5171a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z5197a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z5200a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z5211a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z5227a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z5229a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z5230a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z5236a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z5243a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z5246a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z5302a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z5339a_syndirella_input.csv...

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_Z5348a_syndirella_input.csv...

DEBUG: querying...

Output()

 DISK  Writing cycle_02/syndirella/elabs/c2_elabs_syndirella_inspiration_hits.sdf...

,smiles,template,compound_set,hit1
id,,,,
1,CCn1cnc2ccccc21,Z0490a,c2_elabs_Z0490a,Z0490a
2,N#CCC1=N[C@@H]2CCCC[C@@H]2N1,Z0844a,c2_elabs_Z0844a,Z0844a
3,Nc1ccnc2c(OC(F)(F)F)cccc12,Z1682a,c2_elabs_Z1682a,Z1682a
4,CC(=O)N[C@@H](CCCN)C(=O)Nc1cccc2c(CO)cc(C)nc12,Z2048a,c2_elabs_Z2048a,Z2048a
5,O=c1[nH]ncn1C1CCN(Cc2c[nH]c3ccccc23)CC1,Z2971a,c2_elabs_Z2971a,Z2971a
...,...,...,...,...
333,O=C(Nc1ccc2c(c1)CNC2)c1cc(Cl)c2[nH]nc(N3CCOCC3...,Z5243a,c2_elabs_Z5243a,Z5243a
334,O=C(Nc1ccc2c(c1)CNC2)c1cc(Cl)c2[nH]c(NC3CNC3)n...,Z5246a,c2_elabs_Z5246a,Z5246a
335,O=C(Nc1ccc2c(c1)CNC2)c1cc(Cl)cc2c1cnn2[C@H]1CCNC1,Z5302a,c2_elabs_Z5302a,Z5302a
336,O=C(Nc1ccc(C2CNC2)cc1)c1cc(Cl)cc2c1cnn2C1CCOCC1,Z5339a,c2_elabs_Z5339a,Z5339a
337,CNCc1cccc(NC(=O)c2cc(Cl)cc3c2cnn3C2CNC2)c1,Z5348a,c2_elabs_Z5348a,Z5348a

## Load Syndirella Elabs

Check using below cells and then queue `c02b_load_elabs.py`

In [ ]:
output_root = cycle_dir / "syndirella/elabs/"
files = list(output_root.glob("*/*-*-?/*to_hippo*"))
len(files)

In [ ]:
%%time
scaffold = animal.poses["A4489b"].compound
df = animal.add_syndirella_elabs(files[0], scaffold_compound=scaffold, dry_run=True)
df

## Check Elabs

In [4]:
animal.tags.summary()

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━┓
┃ tag                                            ┃ num_compounds ┃ num_poses ┃ num_posed_compounds ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━┩
│ BAD count                                      │ 0             │ 337       │ 303                 │
│ BulkDock Fragalysis export                     │ 0             │ 5159      │ 4467                │
│ C1 85percent analogue                          │ 45            │ 0         │ 0                   │
│ C1 90percent analogue                          │ 15            │ 0         │ 0                   │
│ C1 95percent analogue                          │ 9             │ 0         │ 0                   │
│ C10 85percent analogue                         │ 30            │ 0         │ 0                   │
│ C10 90percent analogue                         │ 5             │ 0         │ 0                   │
│ C100 85percent analogue                        │ 1             │ 0         │ 0                   │
│ C103 85percent analogue                        │ 3             │ 0         │ 0                   │
│ C104 85percent analogue                        │ 2             │ 0         │ 0                   │
│ C105 85percent analogue                        │ 1             │ 0         │ 0                   │
│ C106 85percent analogue                        │ 4             │ 0         │ 0                   │
│ C107 85percent analogue                        │ 1             │ 0         │ 0                   │
│ C108 85percent analogue                        │ 122           │ 0         │ 0                   │
│ C108 90percent analogue                        │ 9             │ 0         │ 0                   │
│ C11 85percent analogue                         │ 16            │ 0         │ 0                   │
│ C11 90percent analogue                         │ 5             │ 0         │ 0                   │
│ C110 85percent analogue                        │ 12            │ 0         │ 0                   │
│ C110 90percent analogue                        │ 2             │ 0         │ 0                   │
│ C111 85percent analogue                        │ 1             │ 0         │ 0                   │
│ C114 85percent analogue                        │ 1             │ 0         │ 0                   │
│ C115 85percent analogue                        │ 3             │ 0         │ 0                   │
│ C118 85percent analogue                        │ 1             │ 0         │ 0                   │
│ C119 85percent analogue                        │ 1             │ 0         │ 0                   │
│ C121 85percent analogue                        │ 3             │ 0         │ 0                   │
│ C122 85percent analogue                        │ 1             │ 0         │ 0                   │
│ C123 85percent analogue                        │ 3             │ 0         │ 0                   │
│ C123 90percent analogue                        │ 1             │ 0         │ 0                   │
│ C124 85percent analogue                        │ 1             │ 0         │ 0                   │
│ C126 85percent analogue                        │ 1             │ 0         │ 0                   │
│ C127 85percent analogue                        │ 6             │ 0         │ 0                   │
│ C128 85percent analogue                        │ 2             │ 0         │ 0                   │
│ C129 85percent analogue                        │ 2             │ 0         │ 0                   │
│ C13 85percent analogue                         │ 15            │ 0         │ 0                   │
│ C13 90percent analogue                         │ 3             │ 0         │ 0                   │
│ C132 85percent analogue                        │ 3             │ 0         │ 0                   │
│ C134 85percent analogue                        │ 1             │ 0         │ 0                   │
│ C136 85percent analogue                        │ 3             │ 0         │ 0                   │
│ C139 85percent analogue                        │ 1             │ 0         │ 0                   │
│ C14 85percent analogue                         │ 40            │ 0         │ 0                   │
│ C14 90percent analogue                         │ 9             │ 0         │ 0                   │
│ C141 85percent analogue                        │ 1             │ 0         │ 0                   │
│ C144 85percent analogue                        │ 2             │ 0         │ 0                   │
│ C145 85percent analogue                        │ 6             │ 0         │ 0                   │
│ C149 85percent analogue                        │ 1             │ 0         │ 0                   │
│ C15 85percent analogue                         │ 6             │ 0         │ 0                   │
│ C15 90percent analogue                         │ 2             │ 0         │ 0                   │
│ C150 85percent analogue                        │ 16            │ 0         │ 0                   │
│ C151 85percent analogue                        │ 21            │ 0         │ 0                   │
│ C153 85percent analogue                        │ 5             │ 0         │ 0                   │
│ C159 85percent analogue                        │ 6             │ 0         │ 0                   │
│ C16 85percent analogue                         │ 52            │ 0         │ 0                   │
│ C16 90percent analogue                         │ 15            │ 0         │ 0                   │
│ C16 95percent analogue                         │ 6             │ 0         │ 0                   │
│ C161 85percent analogue                        │ 2             │ 0         │ 0                   │
│ C162 85percent analogue                        │ 3             │ 0         │ 0                   │
│ C168 85percent analogue                        │ 5             │ 0         │ 0                   │
│ C169 85percent analogue                        │ 2             │ 0         │ 0                   │
│ C169 90percent analogue                        │ 1             │ 0         │ 0                   │
│ C17 85percent analogue                         │ 15            │ 0         │ 0                   │
│ C17 90percent analogue                         │ 5             │ 0         │ 0                   │
│ C171 85percent analogue                        │ 14            │ 0         │ 0                   │
│ C171 90percent analogue                        │ 1             │ 0         │ 0                   │
│ C173 85percent analogue                        │ 12            │ 0         │ 0                   │
│ C175 85percent analogue                        │ 2             │ 0         │ 0                   │
│ C18 85percent analogue                         │ 13            │ 0         │ 0                   │
│ C18 90percent analogue                         │ 2             │ 0         │ 0                   │
│ C180 85percent analogue                        │ 1             │ 0         │ 0                   │
│ C181 85percent analogue                        │ 1             │ 0         │ 0                   │
│ C183 85percent analogue                        │ 9             │ 0         │ 0                   │
│ C185 85percent analogue                        │ 2             │ 0         │ 0                   │
│ C188 85percent analogue                        │ 1             │ 0         │ 0                   │
│ C19 85percent analogue                         │ 3             │ 0         │ 0                   │
│ C192 85percent analogue                        │ 4             │ 0         │ 0                   │
│ C193 85percent analogue                        │ 4             │ 0         │ 0                   │
│ C196 85percent analogue                        │ 4             │ 0         │ 0                   │
│ C198 85percent analogue                        │ 13            │ 0         │ 0                   │
│ C199 85percent analogue                        │ 2             │ 0         │ 0                   │
│ C20 85percent analogue                         │ 59            │ 0         │ 0                   │
│ C20 90percent analogue                         │ 13            │ 0         │ 0                   │
│ C204 85percent analogue                        │ 3             │ 0         │ 0                   │
│ C206 85percent analogue                        │ 2             │ 0         │ 0                   │
│ C209 85percent analogue                        │ 1             │ 0         │ 0                   │
│ C21 85percent analogue                         │ 20            │ 0         │ 0                   │
│ C21 90percent analogue                         │ 5             │ 0         │ 0                   │
│ C210 85percent analogue                        │ 1             │ 0         │ 0                   │
│ C211 85percent analogue                        │ 1             │ 0         │ 0                   │
│ C212 85percent analogue                        │ 3             │ 0         │ 0                   │
│ C213 85percent analogue                        │ 1             │ 0         │ 0                   │
│ C219 85percent analogue                        │ 4             │ 0         │ 0                   │
│ C22 85percent analogue                         │ 8             │ 0         │ 0                   │
│ C22 90percent analogue                         │ 4             │ 0         │ 0                   │
│ C22 95percent analogue                         │ 1             │ 0         │ 0                   │
│ C221 85percent analogue                        │ 2             │ 0         │ 0                   │
│ C223 85percent analogue                        │ 1             │ 0         │ 0                   │
│ C224 85percent analogue                        │ 1             │ 0         │ 0                   │
│ C228 85percent analogue                        │ 3             │ 0         │ 0                   │
│ C229 85percent analogue                        │ 1             │ 0         │ 0                   │
│ C23 85percent analogue                         │ 11            │ 0         │ 0                   │
│ C23 90percent analogue                         │ 1             │ 0         │ 0                   │
│ C230 85percent analogue                        │ 1             │ 0         │ 0                   │
│ C231 85percent analogue                        │ 1             │ 0         │ 0                   │
│ C232 85percent analogue                        │ 1             │ 0         │ 0                   │
│ C24 85percent analogue                         │ 2             │ 0         │ 0                   │
│ C24 90percent analogue                         │ 1             │ 0         │ 0                   │
│ C240 85percent analogue                        │ 1             │ 0         │ 0                   │
│ C246 85percent analogue                        │ 3             │ 0         │ 0                   │
│ C25 85percent analogue                         │ 32            │ 0         │ 0                   │
│ C25 90percent analogue                         │ 1             │ 0         │ 0                   │
│ C26 85percent analogue                         │ 9             │ 0         │ 0                   │
│ C26 90percent analogue                         │ 3             │ 0         │ 0                   │
│ C26 95percent analogue                         │ 1             │ 0         │ 0                   │
│ C262 85percent analogue                        │ 1             │ 0         │ 0                   │
│ C27 85percent analogue                         │ 5             │ 0         │ 0                   │
│ C272 85percent analogue                        │ 3             │ 0         │ 0                   │
│ C273 85percent analogue                        │ 1             │ 0         │ 0                   │
│ C277 85percent analogue                        │ 1             │ 0         │ 0                   │
│ C28 85percent analogue                         │ 31            │ 0         │ 0                   │
│ C28 90percent analogue                         │ 6             │ 0         │ 0                   │
│ C28 95percent analogue                         │ 1             │ 0         │ 0                   │
│ C286 85percent analogue                        │ 1             │ 0         │ 0                   │
│ C29 85percent analogue                         │ 2             │ 0         │ 0                   │
│ C29 90percent analogue                         │ 1             │ 0         │ 0                   │
│ C295 85percent analogue                        │ 1             │ 0         │ 0                   │
│ C296 85percent analogue                        │ 2             │ 0         │ 0                   │
│ C297 85percent analogue                        │ 1             │ 0         │ 0                   │
│ C3 85percent analogue                          │ 17            │ 0         │ 0                   │
│ C3 90percent analogue                          │ 5             │ 0         │ 0                   │
│ C30 85percent analogue                         │ 38            │ 0         │ 0                   │
│ C30 90percent analogue                         │ 16            │ 0         │ 0                   │
│ C30 95percent analogue                         │ 3             │ 0         │ 0                   │
│ C31 85percent analogue                         │ 26            │ 0         │ 0                   │
│ C31 90percent analogue                         │ 8             │ 0         │ 0                   │
│ C31 95percent analogue                         │ 3             │ 0         │ 0                   │
│ C32 85percent analogue                         │ 1             │ 0         │ 0                   │
│ C32 90percent analogue                         │ 1             │ 0         │ 0                   │
│ C33 85percent analogue                         │ 31            │ 0         │ 0                   │
│ C33 90percent analogue                         │ 3             │ 0         │ 0                   │
│ C33 95percent analogue                         │ 1             │ 0         │ 0                   │
│ C34 85percent analogue                         │ 10            │ 0         │ 0                   │
│ C34 90percent analogue                         │ 1             │ 0         │ 0                   │
│ C35 85percent analogue                         │ 31            │ 0         │ 0                   │
│ C35 90percent analogue                         │ 6             │ 0         │ 0                   │
│ C35 95percent analogue                         │ 1             │ 0         │ 0                   │
│ C36 85percent analogue                         │ 1             │ 0         │ 0                   │
│ C38 85percent analogue                         │ 2             │ 0         │ 0                   │
│ C39 85percent analogue                         │ 48            │ 0         │ 0                   │
│ C39 90percent analogue                         │ 10            │ 0         │ 0                   │
│ C40 85percent analogue                         │ 23            │ 0         │ 0                   │
│ C40 90percent analogue                         │ 10            │ 0         │ 0                   │
│ C40 95percent analogue                         │ 2             │ 0         │ 0                   │
│ C41 85percent analogue                         │ 36            │ 0         │ 0                   │
│ C41 90percent analogue                         │ 14            │ 0         │ 0                   │
│ C41 95percent analogue                         │ 4             │ 0         │ 0                   │
│ C42 85percent analogue                         │ 14            │ 0         │ 0                   │
│ C42 90percent analogue                         │ 5             │ 0         │ 0                   │
│ C43 85percent analogue                         │ 9             │ 0         │ 0                   │
│ C44 85percent analogue                         │ 1             │ 0         │ 0                   │
│ C45 85percent analogue                         │ 40            │ 0         │ 0                   │
│ C45 90percent analogue                         │ 2             │ 0         │ 0                   │
│ C46 85percent analogue                         │ 34            │ 0         │ 0                   │
│ C46 90percent analogue                         │ 4             │ 0         │ 0                   │
│ C47 85percent analogue                         │ 3             │ 0         │ 0                   │
│ C48 85percent analogue                         │ 17            │ 0         │ 0                   │
│ C48 90percent analogue                         │ 4             │ 0         │ 0                   │
│ C48 95percent analogue                         │ 1             │ 0         │ 0                   │
│ C49 85percent analogue                         │ 33            │ 0         │ 0                   │
│ C49 90percent analogue                         │ 10            │ 0         │ 0                   │
│ C49 95percent analogue                         │ 3             │ 0         │ 0                   │
│ C5 85percent analogue                          │ 1             │ 0         │ 0                   │
│ C50 85percent analogue                         │ 17            │ 0         │ 0                   │
│ C50 90percent analogue                         │ 3             │ 0         │ 0                   │
│ C50 95percent analogue                         │ 2             │ 0         │ 0                   │
│ C51 85percent analogue                         │ 33            │ 0         │ 0                   │
│ C51 90percent analogue                         │ 8             │ 0         │ 0                   │
│ C51 95percent analogue                         │ 3             │ 0         │ 0                   │
│ C52 85percent analogue                         │ 146           │ 0         │ 0                   │
│ C52 90percent analogue                         │ 10            │ 0         │ 0                   │
│ C52 95percent analogue                         │ 1             │ 0         │ 0                   │
│ C53 85percent analogue                         │ 15            │ 0         │ 0                   │
│ C54 85percent analogue                         │ 1             │ 0         │ 0                   │
│ C55 85percent analogue                         │ 5             │ 0         │ 0                   │
│ C56 85percent analogue                         │ 3             │ 0         │ 0                   │
│ C58 85percent analogue                         │ 2             │ 0         │ 0                   │
│ C6 85percent analogue                          │ 64            │ 0         │ 0                   │
│ C6 90percent analogue                          │ 14            │ 0         │ 0                   │
│ C6 95percent analogue                          │ 4             │ 0         │ 0                   │
│ C61 85percent analogue                         │ 1             │ 0         │ 0                   │
│ C63 85percent analogue                         │ 3             │ 0         │ 0                   │
│ C64 85percent analogue                         │ 8             │ 0         │ 0                   │
│ C65 85percent analogue                         │ 1             │ 0         │ 0                   │
│ C67 85percent analogue                         │ 1             │ 0         │ 0                   │
│ C69 85percent analogue                         │ 3             │ 0         │ 0                   │
│ C7 85percent analogue                          │ 32            │ 0         │ 0                   │
│ C7 90percent analogue                          │ 12            │ 0         │ 0                   │

In [4]:
hit_elabs = animal.compounds(tag="openbind_xx01zvns2b_c2_elabs")
hit_elabs

compounds tagged openbind_xx01zvns2b_c2_elabs: {C × 43671}

In [5]:
hit_elab_poses = animal.poses(tag="openbind_xx01zvns2b_c2_elabs")
hit_elab_poses

poses tagged "openbind_xx01zvns2b_c2_elabs": {P × 46652}

In [6]:
elaborated_hits = hit_elabs.scaffolds
elaborated_hits

{C × 114}

In [7]:
posed_elabs = hit_elabs.poses.compounds
posed_elabs

{C × 28224}

In [13]:
hit_elabs.write_smiles_csv("cycle_02/syndirella/elabs/openbind_xx01zvns2b_c2_elabs.csv")

 DISK  Writing cycle_02/syndirella/elabs/openbind_xx01zvns2b_c2_elabs.csv...

# sb.sh --job-name 'xx01zvns2b_c02_elabs_export' /opt/xchem-fragalysis-2/maxwin/slurm/run_python.sh -m bulkdock export XX01ZVNS2B openbind_xx01zvns2b_c2_elabs --no-posebusters --best-by-compound --no-subsites --require-outcome False

In [ ]:
hit_elab_poses.to_fragalysis("cycle_01/syndirella/elabs/openbind_xx01zvns2b_c2_elabs.sdf",
    method="openbind_xx01zvns2b_c2_elabs", 
    submitter_name="Max Winokan", 
    submitter_institution="DLS", 
    submitter_email="max.winokan@diamond.ac.uk",
    copy_reference_pdbs=True,
    metadata=False,
    tags=False,
    subsites=False,
)

## Routes to scaffolds

1. Export list of elaborated hits
2. Run syndirella just retro
3. Load routes back into HIPPO

In [8]:
elaborated_hit_poses = elaborated_hits.poses(tag="hits")
elaborated_hit_poses

{P × 118}

In [9]:
elaborated_hit_poses.to_syndirella("cycle_02/syndirella/retrosynthesis/openbind_xx01zvns2b_c2_elaborated_hits")

out_key = openbind_xx01zvns2b_c2_elaborated_hits

#poses = 118

DEBUG: querying...

Output()

DEBUG: adding inspiration column(s)

 Warning  118 poses have no reference. Setting to self!

['Z0051a' 'Z0101a' 'Z0130a' 'Z0673a' 'Z0673b' 'Z0719a' 'Z0777a' 'Z0846b'
 'Z0846a' 'Z0945a' 'Z1046a' 'Z1046b' 'Z1098a' 'Z1234a' 'Z1237a' 'Z1265a'
 'Z1271a' 'Z1274a' 'Z1320a' 'Z1342a' 'Z1398a' 'Z1495a' 'Z1597a' 'Z1715a'
 'Z1728a' 'Z1729a' 'Z1752a' 'Z1753a' 'Z2094a' 'Z2262a' 'Z2992a' 'Z3021a'
 'Z3024a' 'Z3028a' 'Z3059a' 'Z3060a' 'Z3093a' 'Z3094a' 'Z3264a' 'Z3400a'
 'Z3441a' 'Z3452a' 'Z3466a' 'Z3468a' 'Z3473a' 'Z3476a' 'Z3477a' 'Z3480a'
 'Z3485a' 'Z3495a' 'Z3501a' 'Z3502a' 'Z3503a' 'Z3507a' 'Z3519a' 'Z3522a'
 'Z3546a' 'Z3556a' 'Z3559a' 'Z3622a' 'Z3665a' 'Z3677a' 'Z3729a' 'Z3733a'
 'Z3746a' 'Z3758a' 'Z3792a' 'Z3799a' 'Z3813a' 'Z3817a' 'Z3831a' 'Z3834a'
 'Z3837a' 'Z3856a' 'Z3858a' 'Z3936a' 'Z3970a' 'Z4017a' 'Z4020a' 'Z4025a'
 'Z4103a' 'Z4117a' 'Z4125a' 'Z4161a' 'Z4178a' 'Z4198a' 'Z4245a' 'Z4756a'
 'Z4811a' 'Z4827a' 'Z4838a' 'Z4849a' 'Z4855a' 'Z4857a' 'Z4858a' 'Z4861a'
 'Z4872a' 'Z4886a' 'Z4887a' 'Z4905a' 'Z4590a' 'Z4959a' 'Z4959b' 'Z4963a'
 'Z4971a' 'Z5010a' 'Z5020a' 'Z5027a' 'Z5061a' 'Z5067a' 'Z5136a' 'Z5139a'
 'Z5171a' 'Z5197a' 'Z5200a' 'Z5229a' 'Z5339a' 'Z5348a']

 Warning  118 poses have no inspirations. Setting to self!

['Z0051a' 'Z0101a' 'Z0130a' 'Z0673a' 'Z0673b' 'Z0719a' 'Z0777a' 'Z0846b'
 'Z0846a' 'Z0945a' 'Z1046a' 'Z1046b' 'Z1098a' 'Z1234a' 'Z1237a' 'Z1265a'
 'Z1271a' 'Z1274a' 'Z1320a' 'Z1342a' 'Z1398a' 'Z1495a' 'Z1597a' 'Z1715a'
 'Z1728a' 'Z1729a' 'Z1752a' 'Z1753a' 'Z2094a' 'Z2262a' 'Z2992a' 'Z3021a'
 'Z3024a' 'Z3028a' 'Z3059a' 'Z3060a' 'Z3093a' 'Z3094a' 'Z3264a' 'Z3400a'
 'Z3441a' 'Z3452a' 'Z3466a' 'Z3468a' 'Z3473a' 'Z3476a' 'Z3477a' 'Z3480a'
 'Z3485a' 'Z3495a' 'Z3501a' 'Z3502a' 'Z3503a' 'Z3507a' 'Z3519a' 'Z3522a'
 'Z3546a' 'Z3556a' 'Z3559a' 'Z3622a' 'Z3665a' 'Z3677a' 'Z3729a' 'Z3733a'
 'Z3746a' 'Z3758a' 'Z3792a' 'Z3799a' 'Z3813a' 'Z3817a' 'Z3831a' 'Z3834a'
 'Z3837a' 'Z3856a' 'Z3858a' 'Z3936a' 'Z3970a' 'Z4017a' 'Z4020a' 'Z4025a'
 'Z4103a' 'Z4117a' 'Z4125a' 'Z4161a' 'Z4178a' 'Z4198a' 'Z4245a' 'Z4756a'
 'Z4811a' 'Z4827a' 'Z4838a' 'Z4849a' 'Z4855a' 'Z4857a' 'Z4858a' 'Z4861a'
 'Z4872a' 'Z4886a' 'Z4887a' 'Z4905a' 'Z4590a' 'Z4959a' 'Z4959b' 'Z4963a'
 'Z4971a' 'Z5010a' 'Z5020a' 'Z5027a' 'Z5061a' 'Z5067a' 'Z5136a' 'Z5139a'
 'Z5171a' 'Z5197a' 'Z5200a' 'Z5229a' 'Z5339a' 'Z5348a']

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/Z0051a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/Z0101a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/Z0130a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/Z0673a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/Z0673b_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/Z0719a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/Z0777a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/Z0846b_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/Z0846a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/Z0945a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/Z1046a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/Z1046b_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/Z1098a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/Z1234a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/Z1237a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/Z1265a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/Z1271a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/Z1274a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/Z1320a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/Z1342a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/Z1398a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/Z1495a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/Z1597a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/Z1715a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/Z1728a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/Z1729a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/Z1752a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/Z1753a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/Z2094a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/Z2262a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/Z2992a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/Z3021a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/Z3024a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/Z3028a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/Z3059a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/Z3060a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/Z3093a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/Z3094a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/Z3264a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/Z3400a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/Z3441a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/Z3452a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/Z3466a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/Z3468a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/Z3473a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/Z3476a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/Z3477a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/Z3480a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/Z3485a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/Z3495a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/Z3501a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/Z3502a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/Z3503a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/Z3507a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/Z3519a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/Z3522a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/Z3546a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/Z3556a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/Z3559a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/Z3622a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/Z3665a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/Z3677a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/Z3729a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/Z3733a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/Z3746a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/Z3758a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/Z3792a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/Z3799a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/Z3813a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/Z3817a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/Z3831a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/Z3834a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/Z3837a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/Z3856a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/Z3858a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/Z3936a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/Z3970a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/Z4017a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/Z4020a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/Z4025a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/Z4103a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/Z4117a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/Z4125a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/Z4161a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/Z4178a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/Z4198a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/Z4245a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/Z4756a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/Z4811a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/Z4827a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/Z4838a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/Z4849a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/Z4855a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/Z4857a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/Z4858a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/Z4861a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/Z4872a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/Z4886a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/Z4887a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/Z4905a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/Z4590a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/Z4959a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/Z4959b_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/Z4963a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/Z4971a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/Z5010a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/Z5020a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/Z5027a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/Z5061a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/Z5067a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/Z5136a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/Z5139a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/Z5171a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/Z5197a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/Z5200a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/Z5229a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/Z5339a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/Z5348a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/openbind_xx01zvns2b_c2_elaborated_hits_syndirella_input.csv...

DEBUG: querying...

Output()

 DISK  Writing
cycle_02/syndirella/retrosynthesis/openbind_xx01zvns2b_c2_elaborated_hits_syndirella_inspiration_hits.sdf...

,smiles,template,compound_set,hit1
id,,,,
6,COc1ccc2sc(N)nc2c1,Z0051a,openbind_xx01zvns2b_c2_elaborated_hits,Z0051a
8,CC(C)(CO)NC(=O)c1cccc(Cl)c1,Z0101a,openbind_xx01zvns2b_c2_elaborated_hits,Z0101a
9,CN1CCN(C(=O)c2ccc(F)c(F)c2)CC1,Z0130a,openbind_xx01zvns2b_c2_elaborated_hits,Z0130a
29,O=C1CC[C@@H](NC(=O)c2cscn2)CN1,Z0673a,openbind_xx01zvns2b_c2_elaborated_hits,Z0673a
30,O=C1CC[C@@H](NC(=O)c2cscn2)CN1,Z0673b,openbind_xx01zvns2b_c2_elaborated_hits,Z0673b
...,...,...,...,...
326,O=C(Nc1cc[nH]n1)c1cc(Cl)cc2c1cnn2C1CNC1,Z5197a,openbind_xx01zvns2b_c2_elaborated_hits,Z5197a
327,O=C(Nc1ccc2c(c1)CNC2)c1cc(F)cc(-c2cncs2)c1,Z5200a,openbind_xx01zvns2b_c2_elaborated_hits,Z5200a
330,O=C(Nc1ccc2c(c1)CNC2)c1cc(F)cc(-c2c[nH]c3ccccc...,Z5229a,openbind_xx01zvns2b_c2_elaborated_hits,Z5229a
336,O=C(Nc1ccc(C2CNC2)cc1)c1cc(Cl)cc2c1cnn2C1CCOCC1,Z5339a,openbind_xx01zvns2b_c2_elaborated_hits,Z5339a
337,CNCc1cccc(NC(=O)c2cc(Cl)cc3c2cnn3C2CNC2)c1,Z5348a,openbind_xx01zvns2b_c2_elaborated_hits,Z5348a

cd cycle_02/syndirella/retrosynthesis
sb --job-name "xx01zvns2b_c2_retro" --mem 16000 $HOME2/slurm/run_bash_with_conda.sh ../../../../scripts/run_syndirella_retro.sh

In [11]:
!mv cycle_02/syndirella/retrosynthesis/retrosynthesis/* cycle_02/syndirella/retrosynthesis/

In [12]:
animal.add_syndirella_routes(
    "cycle_02/syndirella/retrosynthesis/justretroquery_openbind_xx01zvns2b_c2_elaborated_hits_syndirella_input.pkl.gz", 
    CAR_only=False,
    check_chemistry=False,
)

Output()

0 0 0 N-nucleophilic_aromatic_substitution C6 "Z1201620232"

 Success  registered route 16283!

1 0 0 Amidation C8 "Z68299550"

 Success  registered route 16284!

2 0 0 Amidation C9 "Z57122377"

 Success  registered route 16285!

3 0 0 Amidation C27 "Z1102357527"

 Success  registered route 16286!

4 0 0 Amidation C27 "Z1102357527"

 Success  registered route 16287!

5 0 0 Amidation C27 "Z1102357527"

 Success  registered route 16288!

6 0 0 Amidation C27 "Z1102357527"

 Success  registered route 16289!

7 0 0 Sp3-sp2_Suzuki_coupling C32 "Z1203191681"

 Success  registered route 16290!

8 0 0 Buchwald-Hartwig_amination C36 "Z1272517105"

 Success  registered route 16291!

9 0 0 Nucleophilic_aromatic_substitution_(methylsulfone) C42 "Z1587220559"

 Success  registered route 16292!

10 0 0 Nucleophilic_aromatic_substitution_(methylsulfone) C42 "Z1587220559"

 Success  registered route 16293!

11 0 0 Nucleophilic_aromatic_substitution_(methylsulfone) C42 "Z1587220559"

 Success  registered route 16294!

12 0 0 Nucleophilic_aromatic_substitution_(methylsulfone) C42 "Z1587220559"

 Success  registered route 16295!

13 0 0 N-nucleophilic_aromatic_substitution C48 "Z228587394"

 Success  registered route 16296!

14 0 0 Amidation C52 "Z31735562"

 Success  registered route 16297!

15 0 0 Amidation C52 "Z31735562"

 Success  registered route 16298!

16 0 0 Amidation C52 "Z31735562"

 Success  registered route 16299!

17 0 0 Amidation C52 "Z31735562"

 Success  registered route 16300!

18 0 0 Amidation C53 "Z396117078"

 Success  registered route 16301!

19 0 0 Amidation C54 "ASAP-0014643-001"

 Success  registered route 16302!

20 0 0 Amidation C55 "ASAP-0014657-001"

 Success  registered route 16303!

21 0 0 Amidation C55 "ASAP-0014657-001"

 Success  registered route 16304!

22 0 0 Sp2-sp2_Suzuki_coupling C57 "ASAP-0014712-001"

 Success  registered route 16305!

23 0 0 Amidation C55 "ASAP-0014657-001"

 Success  registered route 16306!

24 0 0 Amidation C55 "ASAP-0014657-001"

 Success  registered route 16307!

25 0 0 Amidation C58 "ASAP-0014668-001"

 Success  registered route 16308!

26 0 0 Sp2-sp2_Suzuki_coupling C62 "ASAP-0014821-001"

 Success  registered route 16309!

27 0 0 Amidation C64 "ASAP-0014795-001"

 Success  registered route 16310!

28 0 0 Sp2-sp2_Suzuki_coupling C65 "ASAP-0014738-001"

 Success  registered route 16311!

29 0 0 Amidation C69 "ASAP-0014903-001"

 Success  registered route 16312!

30 0 0 Amidation C71 "ASAP-0014942-001"

 Success  registered route 16313!

31 0 0 Amidation C78 "MFP-0011741-001-001"

 Success  registered route 16314!

32 0 0 Amidation C82 "MFP-0012503-001-003"

 Success  registered route 16315!

33 0 0 Amidation C82 "MFP-0012503-001-003"

 Success  registered route 16316!

34 0 0 Chan-Lam_coupling_of_amides,_sulfonamides,_and_imides C83 "MFP-0012445-001-001"

 Success  registered route 16317!

35 0 0 Amidation C82 "MFP-0012503-001-003"

 Success  registered route 16318!

36 0 0 Amidation C82 "MFP-0012503-001-003"

 Success  registered route 16319!

37 0 0 Buchwald-Hartwig_amidation_with_amide-like_nucleophile C88 "3632-093-001"

 Success  registered route 16320!

38 0 0 Amidation C94 "ASAP-0015093-001"

 Success  registered route 16321!

39 0 0 Ugi_imidazole_synthesis C100 "ASAP-0015285-001"

 Success  registered route 16322!

40 0 0 Amidation C103 "ASAP-0017018-001"

 Success  registered route 16323!

41 0 0 Amidation C104 "ASAP-0017501-001"

 Success  registered route 16324!

42 0 0 Amidation C105 "ASAP-0017670-001"

 Success  registered route 16325!

43 0 0 Amidation C106 "ASAP-0017708-001"

 Success  registered route 16326!

44 0 0 Amidation C107 "ASAP-0020822-001"

 Success  registered route 16327!

45 0 0 Sp3-sp2_Suzuki_coupling C108 "ASAP-0017566-001"

 Success  registered route 16328!

46 0 0 Amidation C109 "ASAP-0022528-001"

 Success  registered route 16329!

47 0 0 Amidation C110 "ASAP-0022708-001"

 Success  registered route 16330!

48 0 0 Amidation C111 "ASAP-0027731-001"

 Success  registered route 16331!

49 0 0 Amidation C114 "ASAP-0029974-001"

 Success  registered route 16332!

50 0 0 Amidation C118 "ASAP-0029424-001"

 Warning  SMILES changed during compound registration: O=C(O)c1cc(F)cc2[nH]ncc12 --> O=C(O)c1cc(F)cc2n[nH]cc12!

 Success  registered route 16333!

51 0 0 Amidation C119 "ASAP-0029497-001"

 Success  registered route 16334!

52 0 0 Ester_amidation C123 "ASAP-0029796-001"

 Success  registered route 16335!

53 0 0 Amidation C124 "ASAP-0029926-001"

 Success  registered route 16336!

54 0 0 Amidation C127 "ASAP-0029795-001"

 Success  registered route 16337!

55 0 0 Ester_amidation C128 "ASAP-0029755-001"

 Success  registered route 16338!

56 0 0 Amidation C129 "ASAP-0029864-001"

 Success  registered route 16339!

57 0 0 Amidation C130 "ASAP-0029834-001"

 Success  registered route 16340!

58 0 0 Amidation C131 "ASAP-0029831-001"

 Success  registered route 16341!

59 0 0 Ester_amidation C135 "ASAP-0029879-001"

 Success  registered route 16342!

60 0 0 Amidation C136 "ASAP-0029876-001"

 Warning  SMILES changed during compound registration: O=C(O)c1cccc2nc(C(F)(F)F)[nH]c12 -->
O=C(O)c1cccc2[nH]c(C(F)(F)F)nc12!

 Success  registered route 16343!

61 0 0 Amidation C137 "ASAP-0029858-001"

 Warning  SMILES changed during compound registration: Cc1nc2c(C(=O)O)cc(Cl)cc2[nH]1 -->
Cc1nc2cc(Cl)cc(C(=O)O)c2[nH]1!

 Success  registered route 16344!

62 0 0 Amidation C138 "ASAP-0029875-001"

 Success  registered route 16345!

63 0 0 Formation_of_alpha_aminonitrile_from_aldehyde_or_ketone_-_Strecker_reaction C141 "ASAP-0029905-001"

 Success  registered route 16346!

64 0 0 Amidation C143 "ASAP-0029800-001"

 Warning  SMILES changed during compound registration: O=C(O)c1cc(Cl)nc2[nH]ccc12 --> O=C(O)c1cc(Cl)[nH]c2nccc1-2!

 Success  registered route 16347!

65 0 0 Amidation C144 "ASAP-0029829-001"

 Success  registered route 16348!

66 0 0 Amidation C147 "ASAP-0029640-001"

 Success  registered route 16349!

67 0 0 Amidation C150 "ASAP-0029569-001"

 Success  registered route 16350!

68 0 0 Amidation C151 "ASAP-0029687-001"

 Success  registered route 16351!

69 0 0 Amidation C155 "ASAP-0030082-001"

 Warning  SMILES changed during compound registration: O=C(O)c1cc(F)cc2[nH]c(-c3ccccc3)nc12 -->
O=C(O)c1cc(F)cc2nc(-c3ccccc3)[nH]c12!

 Success  registered route 16352!

70 0 0 Buchwald-Hartwig_amidation_with_amide-like_nucleophile C159 "ASAP-0036635-001"

 Success  registered route 16353!

71 0 0 Amidation C161 "ASAP-0029208-001"

 Success  registered route 16354!

72 0 0 Buchwald-Hartwig_amidation_with_amide-like_nucleophile C168 "ASAP-0029771-001"

 Success  registered route 16355!

73 0 0 Ester_amidation C169 "ASAP-0031455-001"

 Success  registered route 16356!

74 0 0 Amidation C171 "ASAP-0031792-001"

 Success  registered route 16357!

75 0 0 Amidation C173 "ASAP-0031795-001"

 Success  registered route 16358!

76 0 0 Amidation C178 "ASAP-0031515-001"

 Success  registered route 16359!

77 0 0 Amidation C178 "ASAP-0031515-001"

 Success  registered route 16360!

78 0 0 Amidation C179 "ASAP-0031633-001"

 Success  registered route 16361!

79 0 0 Amidation C183 "ASAP-0031598-001"

 Success  registered route 16362!

80 0 0 Amidation C185 "ASAP-0031730-001"

 Success  registered route 16363!

81 0 0 Amidation C189 "ASAP-0031594-001"

 Success  registered route 16364!

82 0 0 Amidation C178 "ASAP-0031515-001"

 Success  registered route 16365!

83 0 0 Amidation C178 "ASAP-0031515-001"

 Success  registered route 16366!

84 0 0 Amidation C191 "ASAP-0031709-001"

 Success  registered route 16367!

85 0 0 Amidation C193 "ASAP-0031524-001"

 Success  registered route 16368!

86 0 0 Amidation C194 "ASAP-0031556-001"

 Success  registered route 16369!

87 0 0 Amidation C198 "ASAP-0032355-001"

 Success  registered route 16370!

88 0 0 N-Boc_deprotection C201 "ASAP-0032510-001"

88 0 1 Amidation C202042 "LNJWNEMSBCVGDG-UHFFFAOYSA-N"

 Success  registered route 16371!

89 0 0 Amidation C204 "ASAP-0031534-001"

 Success  registered route 16372!

90 0 0 Amidation C206 "ASAP-0031665-001"

 Success  registered route 16373!

91 0 0 Amidation C207 "ASAP-0031809-001"

 Success  registered route 16374!

92 0 0 Amidation C217 "ASAP-0038114-001"

 Success  registered route 16375!

93 0 0 Sp3-sp2_Suzuki_coupling C219 "ASAP-0035317-001"

 Success  registered route 16376!

94 0 0 Amidation C221 "ASAP-0035426-001"

 Success  registered route 16377!

95 0 0 Amidation C228 "ASAP-0035372-001"

 Success  registered route 16378!

96 0 0 Amidation C232 "ASAP-0034407-001"

 Success  registered route 16379!

97 0 0 Amine_alkylation C235 "ASAP-0034470-001"

97 0 1 Amidation C202044 "FCQHQPKHNKABFY-UHFFFAOYSA-N"

 Success  registered route 16380!

98 0 0 Amidation C241 "ASAP-0032774-001"

 Success  registered route 16381!

99 0 0 Amidation C246 "ASAP-0037970-001"

 Success  registered route 16382!

100 0 0 Amidation C247 "ASAP-0038022-001"

 Success  registered route 16383!

101 0 0 Amidation C249 "ASAP-0038038-001"

 Success  registered route 16384!

102 0 0 N-Boc_deprotection C250 "ASAP-0038049-001"

102 0 1 Amidation C190933 "QTNAMOFGBRECML-UHFFFAOYSA-N"

 Success  registered route 16385!

103 0 0 N-Boc_deprotection C251 "ASAP-0038060-001"

103 0 1 Amidation C202046 "VMNVBSUPGHFQRS-UHFFFAOYSA-N"

 Success  registered route 16386!

104 0 0 Amine_alkylation C252 "ASAP-0038066-001"

104 0 1 Amidation C121787 "BLRLOQDKLOPWLB-UHFFFAOYSA-N"

 Success  registered route 16387!

105 0 0 Amine_alkylation C253 "ASAP-0038051-002"

105 0 1 Amidation C128268 "DVRUNMRULHDGJQ-UHFFFAOYSA-N"

 Success  registered route 16388!

106 0 0 N-Boc_deprotection C254 "ASAP-0038069-002"

106 0 1 Amidation C199004 "HZXCTPUWTQHXHZ-UHFFFAOYSA-N"

 Success  registered route 16389!

107 0 0 N-Boc_deprotection C256 "ASAP-0038072-001"

107 0 1 Amidation C197641 "PIGAZXWNADUVRM-UHFFFAOYSA-N"

 Success  registered route 16390!

108 0 0 Amine_alkylation C257 "ASAP-0038083-001"

108 0 1 Amidation C202047 "FAYSEGULSLHWIP-UHFFFAOYSA-N"

 Success  registered route 16391!

109 0 0 N-Boc_deprotection C258 "ASAP-0038097-001"

109 0 1 Amidation C196090 "PNCYSIJKMXYRBO-UHFFFAOYSA-N"

 Success  registered route 16392!

110 0 0 Amine_alkylation C259 "ASAP-0038098-001"

110 0 1 Amidation C202048 "TXVPJQNLGVZBKE-UHFFFAOYSA-N"

 Success  registered route 16393!

111 0 0 N-Boc_deprotection C260 "ASAP-0038116-001"

111 0 1 Amidation C202049 "BHCPSYRYXPLZOS-UHFFFAOYSA-N"

 Success  registered route 16394!

112 0 0 N-Boc_deprotection C261 "ASAP-0038785-001"

112 0 1 Amidation C190879 "PTSTXOUISUNPPC-UHFFFAOYSA-N"

 Success  registered route 16395!

113 0 0 Amidation C265 "ASAP-0038908-001"

 Success  registered route 16396!

114 0 0 Amidation C265 "ASAP-0038908-001"

 Success  registered route 16397!

115 0 0 Amidation C265 "ASAP-0038908-001"

 Success  registered route 16398!

116 0 0 Amidation C265 "ASAP-0038908-001"

 Success  registered route 16399!

117 0 0 Amidation C266 "ASAP-0037677-001"

 Success  registered route 16400!

118 0 0 Ester_amidation C268 "ASAP-0037673-001"

 Success  registered route 16401!

119 0 0 N-Boc_deprotection C276 "ASAP-0037781-001"

119 0 1 Amidation C196565 "FTSFHYKDPSKJQW-UHFFFAOYSA-N"

 Success  registered route 16402!

120 0 0 Amidation C279 "ASAP-0037787-001"

 Success  registered route 16403!

121 0 0 Amine_alkylation C280 "ASAP-0037758-001"

121 0 1 Amidation C124377 "YLVYWNVWHYKSMQ-UHFFFAOYSA-N"

 Success  registered route 16404!

122 0 0 Amidation C283 "ASAP-0038186-001"

 Success  registered route 16405!

123 0 0 Larock_indole_synthesis C284 "ASAP-0038138-001"

 Success  registered route 16406!

124 0 0 Sp2-sp2_Suzuki_coupling C289 "ASAP-0038900-001"

 Success  registered route 16407!

125 0 0 Sp2-sp2_Suzuki_coupling C290 "ASAP-0038986-001"

 Success  registered route 16408!

126 0 0 Sp2-sp2_Suzuki_coupling C290 "ASAP-0038986-001"

 Success  registered route 16409!

127 0 0 Sp2-sp2_Suzuki_coupling C290 "ASAP-0038986-001"

 Success  registered route 16410!

128 0 0 Sp2-sp2_Suzuki_coupling C290 "ASAP-0038986-001"

 Success  registered route 16411!

129 0 0 Amine_alkylation C292 "ASAP-0038813-001"

 Warning  SMILES changed during compound registration: O=C(Nc1cc[nH]n1)c1cc(Cl)cc2[nH]ncc12 -->
O=C(Nc1ccn[nH]1)c1cc(Cl)cc2[nH]ncc12!

129 0 1 Amidation C122161 "ZZOHAYGUYMHRFL-UHFFFAOYSA-N"

 Success  registered route 16412!

130 0 0 Sp2-sp2_Suzuki_coupling C293 "ASAP-0038849-001"

 Success  registered route 16413!

131 0 0 Sp2-sp2_Suzuki_coupling C296 "ASAP-0038895-001"

 Success  registered route 16414!

132 0 0 Amidation C302 "ASAP-0038481-001"

 Success  registered route 16415!

133 0 0 Amine_alkylation C303 "ASAP-0038426-001"

133 0 1 Amidation C202053 "BTHJOBOEZVIAMU-UHFFFAOYSA-N"

 Success  registered route 16416!

,smiles,template,compound_set,hit1,route0,route0_names,route0_CAR,route0_non_CAR,route1,route1_names,...,route2_CAR,route2_non_CAR,route3,route3_names,route3_CAR,route3_non_CAR,route4,route4_names,route4_CAR,route4_non_CAR
0,COc1ccc2sc(N)nc2c1,Z0051a,openbind_xx01zvns2b_c2_elaborated_hits,Z0051a,[{'name': 'N-nucleophilic_aromatic_substitutio...,[N-nucleophilic_aromatic_substitution],True,None,[{'name': 'O-Nucleophilic_aromatic_substitutio...,[O-Nucleophilic_aromatic_substitution_(methyls...,...,True,None,[{'name': 'N-nucleophilic_aromatic_substitutio...,[N-nucleophilic_aromatic_substitution],True,None,[{'name': 'N-nucleophilic_aromatic_substitutio...,[N-nucleophilic_aromatic_substitution],True,None
1,CC(C)(CO)NC(=O)c1cccc(Cl)c1,Z0101a,openbind_xx01zvns2b_c2_elaborated_hits,Z0101a,"[{'name': 'Amidation', 'reactantSmiles': ['O=C...",[Amidation],True,None,"[{'name': 'Sandmeyer_chlorination', 'reactantS...",[Sandmeyer_chlorination],...,False,[Ester_to_alcohol_reduction_(intermolecular)],"[{'name': 'Ozonolysis_(to_alcohol,_intermolecu...","[Ozonolysis_(to_alcohol,_intermolecular)]",False,"[Ozonolysis_(to_alcohol,_intermolecular)]",[{'name': 'Ester_to_alcohol_reduction_(intermo...,[Ester_to_alcohol_reduction_(intermolecular)],False,[Ester_to_alcohol_reduction_(intermolecular)]
2,CN1CCN(C(=O)c2ccc(F)c(F)c2)CC1,Z0130a,openbind_xx01zvns2b_c2_elaborated_hits,Z0130a,"[{'name': 'Amidation', 'reactantSmiles': ['O=C...",[Amidation],True,None,[{'name': 'Sp2-sp2_Negishi_coupling_(intermole...,[Sp2-sp2_Negishi_coupling_(intermolecular)],...,True,None,[{'name': 'Sp2-sp2_Negishi_coupling_(intermole...,[Sp2-sp2_Negishi_coupling_(intermolecular)],False,[Sp2-sp2_Negishi_coupling_(intermolecular)],"[{'name': 'Amide_Schotten-Baumann_with_amine',...",[Amide_Schotten-Baumann_with_amine],True,None
3,O=C1CC[C@@H](NC(=O)c2cscn2)CN1,Z0673a,openbind_xx01zvns2b_c2_elaborated_hits,Z0673a,"[{'name': 'Amidation', 'reactantSmiles': ['O=C...",[Amidation],True,None,"[{'name': 'Amide_Schotten-Baumann_with_amine',...",[Amide_Schotten-Baumann_with_amine],...,True,None,"[{'name': 'Ester_amidation', 'reactantSmiles':...",[Ester_amidation],True,None,"[{'name': 'Ester_amidation', 'reactantSmiles':...",[Ester_amidation],True,None
4,O=C1CC[C@@H](NC(=O)c2cscn2)CN1,Z0673a,openbind_xx01zvns2b_c2_elaborated_hits,Z0673a,"[{'name': 'Amidation', 'reactantSmiles': ['O=C...",[Amidation],True,None,"[{'name': 'Amide_Schotten-Baumann_with_amine',...",[Amide_Schotten-Baumann_with_amine],...,True,None,"[{'name': 'Ester_amidation', 'reactantSmiles':...",[Ester_amidation],True,None,"[{'name': 'Ester_amidation', 'reactantSmiles':...",[Ester_amidation],True,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
129,O=C(Nc1cc[nH]n1)c1cc(Cl)cc2c1cnn2C1CNC1,Z5197a,openbind_xx01zvns2b_c2_elaborated_hits,Z5197a,"[{'name': 'Amine_alkylation', 'reactantSmiles'...","[Amine_alkylation, Amidation]",False,[Amine_alkylation],"[{'name': 'Ester_amidation', 'reactantSmiles':...","[Ester_amidation, Amine_alkylation]",...,False,[Amine_alkylation],"[{'name': 'Amine_alkylation', 'reactantSmiles'...","[Amine_alkylation, Ester_amidation]",False,[Amine_alkylation],"[{'name': 'Amine_alkylation', 'reactantSmiles'...","[Amine_alkylation, Amidation]",False,[Amine_alkylation]
130,O=C(Nc1ccc2c(c1)CNC2)c1cc(F)cc(-c2cncs2)c1,Z5200a,openbind_xx01zvns2b_c2_elaborated_hits,Z5200a,"[{'name': 'Sp2-sp2_Suzuki_coupling', 'reactant...",[Sp2-sp2_Suzuki_coupling],False,[Sp2-sp2_Suzuki_coupling],"[{'name': 'Sp2-sp2_Suzuki_coupling', 'reactant...",[Sp2-sp2_Suzuki_coupling],...,True,None,"[{'name': 'Sp2-sp2_Suzuki_coupling', 'reactant...",[Sp2-sp2_Suzuki_coupling],False,[Sp2-sp2_Suzuki_coupling],"[{'name': 'Sp2-sp2_Suzuki_coupling', 'reactant...",[Sp2-sp2_Suzuki_coupling],False,[Sp2-sp2_Suzuki_coupling]
131,O=C(Nc1ccc2c(c1)CNC2)c1cc(F)cc(-c2c[nH]c3ccccc...,Z5229a,openbind_xx01zvns2b_c2_elaborated_hits,Z5229a,"[{'name': 'Sp2-sp2_Suzuki_coupling', 'reactant...",[Sp2-sp2_Suzuki_coupling],False,[Sp2-sp2_Suzuki_coupling],"[{'name': 'Sp2-sp2_Suzuki_coupling', 'reactant...",[Sp2-sp2_Suzuki_coupling],...,True,None,"[{'name': 'Sp2-sp2_Suzuki_coupling', 'reactant...",[Sp2-sp2_Suzuki_coupling],False,[Sp2-sp2_Suzuki_coupling],"[{'name': 'Sp2-sp2_Suzuki_coupling', 'reactant...",[Sp2-sp2_Suzuki_coupling],False,[Sp2-sp2_Suzuki_coupling]
132,O=C(Nc1ccc(C2CNC2)cc1)c1cc(Cl)cc2c1cnn2C1CCOCC1,Z5339a,openbind_xx01zvns2b_c2_elaborated_hits,Z5339a,"[{'name': 'Amidation', 'reactantSmiles': ['O=C...",[Amidation],True,None,"[{'name': 'Ester_amidation', 'reactantSmiles':...","[Ester_amidation, Mitsunobu_reaction_with_arom...",...,False,[Amine_alkylation],"[{'name': 'Amine_alkylation', 'reactantSmiles'...","[Amine_alkylation, Amidation]",False,[Amine_alkylation],"[{'name': 'Ester_amidation', 'reactantSmiles':...","[Ester_amidation, Amine_alkylation]",False,[Amine_alkylation]
133,CNCc1cccc(NC(=O)c2cc(Cl)cc3c2cnn3C2CNC2)c1,Z5348a,openbind_xx01zvns2b_c2_elaborated_hits,Z5348a,"[{'name': 'Amine_alkylation', 'reactantSmiles'...","[Amine_alkylation, Amidation]",False,[Amine_alkylation],"[{'name': 'Ester_amidation', 'reactantSmiles':...","[Ester_amidation, Amine_alkylation]",...,False,[Amine_alkylation],"[{'name': 'N-Boc_deprotection', 'reactantSmile...","[N-Boc_deprotection, Amidation]",True,None,"[{'name': 'Amine_alkylation', 'reactantSmiles'...","[Amine_alkylation, Amidation]",False,[Amine_alkylation]

In [13]:
animal.db.prune_duplicate_routes()

#routes = 15959

products with duplicate routes = 16

compound 119 has 2 duplicate routes

compound 137 has 2 duplicate routes

compound 173 has 2 duplicate routes

compound 171 has 2 duplicate routes

compound 189 has 2 duplicate routes

compound 193 has 2 duplicate routes

compound 268 has 2 duplicate routes

compound 128268 has 2 duplicate routes

compound 27 has 4 duplicate routes

compound 42 has 4 duplicate routes

compound 52 has 4 duplicate routes

compound 55 has 4 duplicate routes

compound 82 has 4 duplicate routes

compound 178 has 4 duplicate routes

compound 265 has 4 duplicate routes

compound 290 has 4 duplicate routes

 Success  Deleted 32 duplicate routes!

{16287,
 16288,
 16289,
 16293,
 16294,
 16295,
 16298,
 16299,
 16300,
 16304,
 16306,
 16307,
 16316,
 16318,
 16319,
 16334,
 16344,
 16357,
 16358,
 16360,
 16364,
 16365,
 16366,
 16368,
 16388,
 16397,
 16398,
 16399,
 16401,
 16409,
 16410,
 16411}

In [14]:
print(elaborated_hits)
hit_elab_routes = hippo.RouteSet.from_product_ids(animal.db, elaborated_hits.ids)
hit_elab_routes

{C × 114}

Output()

{Route × 108}

In [15]:
recipes = hippo.Recipe.from_compounds(elaborated_hits, use_routes=True, pick_cheapest=False)
len(recipes)

#compounds = 114

Output()

 Success  Found solution for compound=C6!

 Success  Found solution for compound=C8!

 Success  Found solution for compound=C9!

 Success  Found solution for compound=C27!

 Success  Found solution for compound=C32!

 Success  Found solution for compound=C36!

 Success  Found solution for compound=C42!

 Success  Found solution for compound=C48!

 Success  Found solution for compound=C52!

 Success  Found solution for compound=C53!

 Success  Found solution for compound=C54!

 Success  Found solution for compound=C55!

 Success  Found solution for compound=C57!

 Success  Found solution for compound=C58!

 Success  Found solution for compound=C62!

 Success  Found solution for compound=C64!

 Success  Found solution for compound=C65!

 Success  Found solution for compound=C69!

 Success  Found solution for compound=C71!

 Success  Found solution for compound=C78!

 Success  Found solution for compound=C82!

 Success  Found solution for compound=C83!

 Success  Found solution for compound=C88!

 Success  Found solution for compound=C94!

 Success  Found solution for compound=C100!

 Success  Found solution for compound=C103!

 Success  Found solution for compound=C104!

 Success  Found solution for compound=C105!

 Success  Found solution for compound=C106!

 Success  Found solution for compound=C107!

 Success  Found solution for compound=C108!

 Success  Found solution for compound=C109!

 Success  Found solution for compound=C110!

 Success  Found solution for compound=C111!

 Success  Found solution for compound=C114!

 Warning  Multiple solutions for compound=C118!

 Success  Found solution for compound=C119!

 Success  Found solution for compound=C123!

 Success  Found solution for compound=C124!

 Success  Found solution for compound=C127!

 Success  Found solution for compound=C128!

 Success  Found solution for compound=C129!

 Success  Found solution for compound=C130!

 Success  Found solution for compound=C131!

 Success  Found solution for compound=C135!

 Warning  Multiple solutions for compound=C136!

 Success  Found solution for compound=C137!

 Success  Found solution for compound=C138!

 Success  Found solution for compound=C141!

 Warning  Multiple solutions for compound=C143!

 Success  Found solution for compound=C144!

 Success  Found solution for compound=C147!

 Success  Found solution for compound=C150!

 Success  Found solution for compound=C151!

 Success  Found solution for compound=C155!

 Success  Found solution for compound=C159!

 Warning  Multiple solutions for compound=C161!

 Success  Found solution for compound=C168!

 Success  Found solution for compound=C169!

 Success  Found solution for compound=C171!

 Success  Found solution for compound=C173!

 Success  Found solution for compound=C178!

 Success  Found solution for compound=C179!

 Success  Found solution for compound=C183!

 Success  Found solution for compound=C185!

 Success  Found solution for compound=C189!

 Success  Found solution for compound=C191!

 Success  Found solution for compound=C193!

 Success  Found solution for compound=C194!

 Success  Found solution for compound=C198!

 ERROR  No routes to C201 "ASAP-0032510-001"!

 Success  Found solution for compound=C204!

 Success  Found solution for compound=C206!

 Success  Found solution for compound=C207!

 Success  Found solution for compound=C217!

 Success  Found solution for compound=C219!

 Success  Found solution for compound=C221!

 Success  Found solution for compound=C228!

 Success  Found solution for compound=C232!

 ERROR  No routes to C235 "ASAP-0034470-001"!

 Success  Found solution for compound=C241!

 Success  Found solution for compound=C246!

 Success  Found solution for compound=C247!

 Success  Found solution for compound=C249!

 ERROR  No routes to C250 "ASAP-0038049-001"!

 Success  Found solution for compound=C251!

 ERROR  No routes to C252 "ASAP-0038066-001"!

 Success  Found solution for compound=C253!

 ERROR  No routes to C254 "ASAP-0038069-002"!

 ERROR  No routes to C256 "ASAP-0038072-001"!

 ERROR  No routes to C257 "ASAP-0038083-001"!

 ERROR  No routes to C258 "ASAP-0038097-001"!

 ERROR  No routes to C259 "ASAP-0038098-001"!

 ERROR  No routes to C260 "ASAP-0038116-001"!

 ERROR  No routes to C261 "ASAP-0038785-001"!

 Success  Found solution for compound=C265!

 Warning  Multiple solutions for compound=C266!

 Success  Found solution for compound=C268!

 ERROR  No routes to C276 "ASAP-0037781-001"!

 Success  Found solution for compound=C279!

 ERROR  No routes to C280 "ASAP-0037758-001"!

 Success  Found solution for compound=C283!

 Success  Found solution for compound=C284!

 Success  Found solution for compound=C289!

 Success  Found solution for compound=C290!

 ERROR  No routes to C292 "ASAP-0038813-001"!

 Success  Found solution for compound=C293!

 Success  Found solution for compound=C296!

 Success  Found solution for compound=C302!

 ERROR  No routes to C303 "ASAP-0038426-001"!

 Success  Found solution for compound=C18613!

 Success  Found solution for compound=C18682!

 Success  Found solution for compound=C35751!

 Success  Found solution for compound=C39979!

Solving recipe combinations...

Output()

96

In [16]:
recipe = recipes[0]
recipe.write_json("cycle_02/syndirella/retrosynthesis/openbind_xx01zvns2b_c2_elaborated_hits_recipe.json")

 Warning  NULL Quote: 3.00mg of C121388!

 Warning  NULL Quote: 1.00mg of C202013!

 Warning  NULL Quote: 1.00mg of C202014!

 Warning  NULL Quote: 1.00mg of C202015!

 Warning  NULL Quote: 1.00mg of C202016!

 Warning  NULL Quote: 1.00mg of C202017!

 Warning  NULL Quote: 1.00mg of C202018!

 Warning  NULL Quote: 1.00mg of C202019!

 Warning  NULL Quote: 1.00mg of C202020!

 Warning  NULL Quote: 1.00mg of C202021!

 Warning  NULL Quote: 1.00mg of C202022!

 Warning  NULL Quote: 1.00mg of C161105!

 Warning  NULL Quote: 1.00mg of C202023!

 Warning  NULL Quote: 1.00mg of C202024!

 Warning  NULL Quote: 1.00mg of C175703!

 Warning  NULL Quote: 1.00mg of C202025!

 Warning  NULL Quote: 3.00mg of C123647!

 Warning  NULL Quote: 1.00mg of C202026!

 Warning  NULL Quote: 1.00mg of C123878!

 Warning  NULL Quote: 1.00mg of C202027!

 Warning  NULL Quote: 1.00mg of C202028!

 Warning  NULL Quote: 1.00mg of C121986!

 Warning  NULL Quote: 1.00mg of C130503!

 Warning  NULL Quote: 1.00mg of C202029!

 Warning  NULL Quote: 5.00mg of C162311!

 Warning  NULL Quote: 1.00mg of C202030!

 Warning  NULL Quote: 1.00mg of C123257!

 Warning  NULL Quote: 1.00mg of C202031!

 Warning  NULL Quote: 1.00mg of C181958!

 Warning  NULL Quote: 1.00mg of C202032!

 Warning  NULL Quote: 1.00mg of C202033!

 Warning  NULL Quote: 1.00mg of C202034!

 Warning  NULL Quote: 1.00mg of C118!

 Warning  NULL Quote: 1.00mg of C188888!

 Warning  NULL Quote: 1.00mg of C177709!

 Warning  NULL Quote: 1.00mg of C202035!

 Warning  NULL Quote: 1.00mg of C202036!

 Warning  NULL Quote: 1.00mg of C202037!

 Warning  NULL Quote: 1.00mg of C164508!

 Warning  NULL Quote: 1.00mg of C136!

 Warning  NULL Quote: 1.00mg of C121336!

 Warning  NULL Quote: 1.00mg of C202038!

 Warning  NULL Quote: 1.00mg of C190724!

 Warning  NULL Quote: 1.00mg of C202039!

 Warning  NULL Quote: 1.00mg of C202040!

 Warning  NULL Quote: 1.00mg of C177665!

 Warning  NULL Quote: 1.00mg of C130627!

 Warning  NULL Quote: 2.00mg of C121289!

 Warning  NULL Quote: 1.00mg of C202041!

 Warning  NULL Quote: 1.00mg of C190934!

 Warning  NULL Quote: 1.00mg of C122424!

 Warning  NULL Quote: 1.00mg of C121572!

 Warning  NULL Quote: 1.00mg of C199715!

 Warning  NULL Quote: 7.00mg of C121941!

 Warning  NULL Quote: 1.00mg of C124676!

 Warning  NULL Quote: 1.00mg of C202043!

 Warning  NULL Quote: 1.00mg of C32113!

 Warning  NULL Quote: 1.00mg of C190825!

 Warning  NULL Quote: 1.00mg of C202045!

 Warning  NULL Quote: 1.00mg of C251!

 Warning  NULL Quote: 1.00mg of C121412!

 Warning  NULL Quote: 1.00mg of C253!

 Warning  NULL Quote: 1.00mg of C165998!

 Warning  NULL Quote: 1.00mg of C121286!

 Warning  NULL Quote: 1.00mg of C196256!

 Warning  NULL Quote: 1.00mg of C202050!

 Warning  NULL Quote: 4.00mg of C124733!

 Warning  NULL Quote: 1.00mg of C202051!

 Warning  NULL Quote: 1.00mg of C202052!

 Warning  NULL Quote: 1.00mg of C121774!

 Warning  NULL Quote: 1.00mg of C165895!

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/xx01zvns2b/cycle_02/syndirella/retrosynthesis/openbind_xx01zvns2b_c2_
elaborated_hits_recipe.json...

In [17]:
recipe.write_CAR_csv("cycle_02/syndirella/retrosynthesis/openbind_xx01zvns2b_c2_elaborated_hits_recipe_CAR.csv")

DEBUG: Querying database for routes

DEBUG: Assembling route dictionary

DEBUG: Checking availability

Output()

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/xx01zvns2b/cycle_02/syndirella/retrosynthesis/openbind_xx01zvns2b_c2_
elaborated_hits_recipe_CAR_1steps.csv...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/xx01zvns2b/cycle_02/syndirella/retrosynthesis/openbind_xx01zvns2b_c2_
elaborated_hits_recipe_CAR_2steps.csv...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/xx01zvns2b/cycle_02/syndirella/retrosynthesis/openbind_xx01zvns2b_c2_
elaborated_hits_recipe_CAR.csv...

,target-names,no-steps,concentration-required-mM,amount-required-uL,batch-tag,reactant-1-1,reactant-2-1,reaction-product-smiles-1,reaction-name-1,reaction-recipe-1,reaction-groupby-column-1,reactant-1-2,reactant-2-2,reaction-product-smiles-2,reaction-name-2,reaction-recipe-2,reaction-groupby-column-2,reactant-3-1,reactant-4-1
0,C249,1,None,None,None,O=C(O)c1cc(Cl)cc2c1cnn2C1CNC1,Nc1ccc(F)cc1N1CCCC1=O,O=C(Nc1ccc(F)cc1N1CCCC1=O)c1cc(Cl)cc2c1cnn2C1CNC1,Amidation,None,None,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
1,C265,1,None,None,None,Nc1ccc2c(c1)CNC2,O=C(O)c1cc(F)cc(-c2cn[nH]c2)c1,O=C(Nc1ccc2c(c1)CNC2)c1cc(F)cc(-c2cn[nH]c2)c1,Amidation,None,None,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
2,C266,1,None,None,None,Nc1ccc2c(c1)CNC2,O=C(O)c1cc(Cl)cc2[nH]cnc12,O=C(Nc1ccc2c(c1)CNC2)c1cc(Cl)cc2[nH]cnc12,Amidation,None,None,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
3,C279,1,None,None,None,O=C(O)c1cc(Cl)cc2c1cnn2C1CNC1,Nc1ccc(C2CNC2)cc1,O=C(Nc1ccc(C2CNC2)cc1)c1cc(Cl)cc2c1cnn2C1CNC1,Amidation,None,None,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
4,C283,1,None,None,None,O=C(O)c1cc(Cl)cc2c1cnn2C1CNC1,Cc1cnc(N)cc1C,Cc1cnc(NC(=O)c2cc(Cl)cc3c2cnn3C2CNC2)cc1C,Amidation,None,None,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96,C268,1,None,None,None,Nc1ccc2c(c1)CNC2,COC(=O)c1cc(Cl)c2[nH]cc(C)c2c1,Cc1c[nH]c2c(Cl)cc(C(=O)Nc3ccc4c(c3)CNC4)cc12,Ester_amidation,None,None,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
97,C232,1,None,None,None,Nc1ccc2c(c1)CNC2,CN1CCC(c2n[nH]c3ccc(C(=O)O)cc23)CC1,CN1CCC(c2n[nH]c3ccc(C(=O)Nc4ccc5c(c4)CNC5)cc23...,Amidation,None,None,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
98,C39979,1,None,None,None,Nc1ccc2c(c1)CNC2=O,COC(=O)c1cc(Cl)c2[nH]cc(C)c2c1,Cc1c[nH]c2c(Cl)cc(C(=O)Nc3ccc4c(c3)CNC4=O)cc12,Ester_amidation,None,None,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
99,C246,1,None,None,None,O=C1Cc2cc(C(=O)O)ccc2N1,CN1Cc2ccc(N)cc2C1,CN1Cc2ccc(NC(=O)c3ccc4c(c3)CC(=O)N4)cc2C1,Amidation,None,None,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
100,C247,1,None,None,None,O=C(O)c1cc(Cl)cc2c1cnn2C1CNC1,Nc1ccc(N2CCCC2=O)c(F)c1,O=C(Nc1ccc(N2CCCC2=O)c(F)c1)c1cc(Cl)cc2c1cnn2C...,Amidation,None,None,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>

In [18]:
recipe.write_reactant_csv("cycle_02/syndirella/retrosynthesis/openbind_xx01zvns2b_c2_elaborated_hits_recipe_reactants.csv")

DEBUG: Querying database for routes

DEBUG: Assembling route dictionary

DEBUG: Checking availability

 DISK  Writing cycle_02/syndirella/retrosynthesis/openbind_xx01zvns2b_c2_elaborated_hits_recipe_reactants.csv...

In [22]:
pd.read_pickle("../a71ev2a/cycle_02/syndirella/retrosynthesis/justretroquery_openbind_a71ev2a_c2_elaborated_hits_syndirella_input.pkl.gz")

,smiles,template,compound_set,hit1,route0,route0_names,route0_CAR,route0_non_CAR,route1,route1_names,...,route2_CAR,route2_non_CAR,route3,route3_names,route3_CAR,route3_non_CAR,route4,route4_names,route4_CAR,route4_non_CAR
0,NC(=O)[C@H]1CCCN(C(=O)Cc2cccc3c2SCC3)C1,A5151a,openbind_a71ev2a_c2_elaborated_hits,A5151a,"[{'name': 'Amidation', 'reactantSmiles': ['O=C...",[Amidation],True,None,"[{'name': 'Alpha-arylation', 'reactantSmiles':...",[Alpha-arylation],...,False,[Alpha-arylation],"[{'name': 'Ester_amidation', 'reactantSmiles':...",[Ester_amidation],True,None,"[{'name': 'Ester_amidation', 'reactantSmiles':...",[Ester_amidation],True,None
1,CNC(=O)c1cn(C)c2ccccc12,A0451a,openbind_a71ev2a_c2_elaborated_hits,A0451a,"[{'name': 'Amidation', 'reactantSmiles': ['Cn1...",[Amidation],True,None,"[{'name': 'Amine_alkylation', 'reactantSmiles'...",[Amine_alkylation],...,False,"[Chan-Lam_coupling_of_amides,_sulfonamides,_an...",[{'name': 'Mitsunobu_reaction_with_aromatic_nh...,[Mitsunobu_reaction_with_aromatic_nh],False,[Mitsunobu_reaction_with_aromatic_nh],"[{'name': 'Amide_Schotten-Baumann_with_amine',...",[Amide_Schotten-Baumann_with_amine],True,None
2,CNC(=O)c1cn(C)c2ccccc12,A0451a,openbind_a71ev2a_c2_elaborated_hits,A0451a,"[{'name': 'Amidation', 'reactantSmiles': ['Cn1...",[Amidation],True,None,"[{'name': 'Amine_alkylation', 'reactantSmiles'...",[Amine_alkylation],...,False,"[Chan-Lam_coupling_of_amides,_sulfonamides,_an...",[{'name': 'Mitsunobu_reaction_with_aromatic_nh...,[Mitsunobu_reaction_with_aromatic_nh],False,[Mitsunobu_reaction_with_aromatic_nh],"[{'name': 'Amide_Schotten-Baumann_with_amine',...",[Amide_Schotten-Baumann_with_amine],True,None
3,COc1ccc2sc(N)nc2c1,A0514a,openbind_a71ev2a_c2_elaborated_hits,A0514a,[{'name': 'N-nucleophilic_aromatic_substitutio...,[N-nucleophilic_aromatic_substitution],True,None,[{'name': 'O-Nucleophilic_aromatic_substitutio...,[O-Nucleophilic_aromatic_substitution_(methyls...,...,True,None,[{'name': 'N-nucleophilic_aromatic_substitutio...,[N-nucleophilic_aromatic_substitution],True,None,[{'name': 'N-nucleophilic_aromatic_substitutio...,[N-nucleophilic_aromatic_substitution],True,None
4,COc1ccc2sc(N)nc2c1,A0514a,openbind_a71ev2a_c2_elaborated_hits,A0514a,[{'name': 'N-nucleophilic_aromatic_substitutio...,[N-nucleophilic_aromatic_substitution],True,None,[{'name': 'O-Nucleophilic_aromatic_substitutio...,[O-Nucleophilic_aromatic_substitution_(methyls...,...,True,None,[{'name': 'N-nucleophilic_aromatic_substitutio...,[N-nucleophilic_aromatic_substitution],True,None,[{'name': 'N-nucleophilic_aromatic_substitutio...,[N-nucleophilic_aromatic_substitution],True,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
402,CSc1ccc(Br)cc1CC(=O)N1CC[C@](O)(C(N)=O)C1,A5388a,openbind_a71ev2a_c2_elaborated_hits,A5388a,"[{'name': 'Amidation', 'reactantSmiles': ['NC(...",[Amidation],True,None,[{'name': 'S-nucleophilic_aromatic_substitutio...,[S-nucleophilic_aromatic_substitution],...,True,None,[{'name': 'S-nucleophilic_aromatic_substitutio...,[S-nucleophilic_aromatic_substitution],True,None,[{'name': 'Sp3-sp2_Macmillan_coupling_alcohol_...,[Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_h...,False,[Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_h...
403,CSc1ccc(N2CCOCC2)cc1NC(=O)N1CCC[C@H](C(N)=O)C1,A5598a,openbind_a71ev2a_c2_elaborated_hits,A5598a,"[{'name': 'Buchwald-Hartwig_amination', 'react...",[Buchwald-Hartwig_amination],True,None,"[{'name': 'Buchwald-Hartwig_amination', 'react...",[Buchwald-Hartwig_amination],...,True,None,"[{'name': 'Iodo_N-arylation', 'reactantSmiles'...","[Iodo_N-arylation, Buchwald-Hartwig_amination]",True,None,[{'name': 'Mitsunobu_reaction_with_amine_alcoh...,[Mitsunobu_reaction_with_amine_alcohol_and_thi...,True,None
404,CSc1ccc(N2CCOCC2)cc1NC(=O)N1CCC[C@H](C(N)=O)C1,A5598a,openbind_a71ev2a_c2_elaborated_hits,A5598a,"[{'name': 'Buchwald-Hartwig_amination', 'react...",[Buchwald-Hartwig_amination],True,None,"[{'name': 'Buchwald-Hartwig_amination', 'react...",[Buchwald-Hartwig_amination],...,True,None,"[{'name': 'Iodo_N-arylation', 'reactantSmiles'...","[Iodo_N-arylation, Buchwald-Hartwig_amination]",True,None,"[{'name': 'Formation_of_urea_from_two_amines',...","[Formation_of_urea_from_two_amines, S-nucleoph...",True,None
405,CSc1ccc(N2CCOCC2)cc1NC(=O)N1CCC[C@H](C(N)=O)C1,A5598b,openbind_a71ev2a_c2_elaborated_hits,A5598b,"[{'name': 'Buchwald-Hartwig_amination', 'react...",[Buchwald-Hartwig_amination],True,None,"[{'name': 'Buchwald-Hartwig_amination', 'react...",[Buchwald-Hartwig_amination],...,True,None,"[{'name': 'Iodo_N-arylation', 'reactantSmiles'...","[Iodo_N-arylation, Buchwald-Hartwig_amination]",True,None,[{'name': 'Mitsunobu_reaction_with_amine_alcoh...,[Mitsunobu_reaction_with_amine_alcohol_and_thi...,True,None
406,CSc1ccc(N2CCOCC2)cc1NC(=O)N1CCC[C@H](C(N)=O)C1,A5598b,openbind_a71ev2a_c2_elaborated_hits,A5598b,"[{'name': 'Buchwald-Hartwig_amination', 'react...",[Buchwald-Hartwig_amination],True,None,"[{'name': 'Buchwald-Hartwig_amination', 'react...",[Buchwald-Hartwig_amination],...,True,None,"[{'name': 'Iodo_N-arylation', 'reactantSmiles'...","[Iodo_N-arylation, Buchwald-Hartwig_amination]",True,None,"[{'name': 'Formation_of_urea_from_two_amines',...","[Formation_of_urea_from_two_amines, S-nucleoph...",True,None

## All elab reactants

In [23]:
bbdb = hippo.HIPPO("BB", "../../EnamineCatalogs/enamine_bb_hippo.sqlite")

 Creating HIPPO animal

name = BB

db_path = ../../EnamineCatalogs/enamine_bb_hippo.sqlite

DEBUG: hippo.Database.__init__()

DEBUG: Database.path = ../../EnamineCatalogs/enamine_bb_hippo.sqlite

DEBUG: hippo.Database.connect()

DEBUG: sqlite3.version='2.6.0'

 Success  Database connected @ ../../EnamineCatalogs/enamine_bb_hippo.sqlite!

 Success  Initialised animal HIPPO("BB")!

In [24]:
animal.quote_reactants(bbdb)

#compounds = 11570

Output()

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])c1cccc(Br)c1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])c1cccc(Br)c1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])c1cccc(Br)c1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])c1cccc(Br)c1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])c1cccc(Br)c1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])c1cccc(Br)c1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])c1cccc(Br)c1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])c1cccc(N)c1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])c1cccc(N)c1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])c1cccc(N)c1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])c1cccc(N)c1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])c1cccc(N)c1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])c1cccc(N)c1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])c1cccc(N)c1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])(N)c1nc2ccccc2[nH]1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])(N)c1nc2ccccc2[nH]1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])(N)c1nc2ccccc2[nH]1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])(N)c1nc2ccccc2[nH]1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])(N)c1nc2ccccc2[nH]1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])(N)c1nc2ccccc2[nH]1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])(N)c1nc2ccccc2[nH]1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])n1cc(N)cn1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])n1cc(N)cn1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])n1cc(N)cn1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])n1cc(N)cn1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])n1cc(N)cn1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])n1cc(N)cn1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])n1cc(N)cn1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])N1CCNCC1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])N1CCNCC1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])N1CCNCC1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])N1CCNCC1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])N1CCNCC1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])N1CCNCC1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])N1CCNCC1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NN!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NN!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NN!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NN!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])OCC(=O)O!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])OCC(=O)O!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])OCC(=O)O!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])OCC(=O)O!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])OCC(=O)O!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])OCC(=O)O!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])OCC(=O)O!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])Oc1ccc(N)cc1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])Oc1ccc(N)cc1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])Oc1ccc(N)cc1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])Oc1ccc(N)cc1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])Oc1ccc(N)cc1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])Oc1ccc(N)cc1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])Oc1ccc(N)cc1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])n1cc(Br)cn1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])n1cc(Br)cn1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])n1cc(Br)cn1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])n1cc(Br)cn1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])n1cc(Br)cn1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])n1cc(Br)cn1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])n1cc(Br)cn1!

 Warning  Isotope(s) in SMILES: [2H]c1ccc(Br)cc1!

 Warning  Isotope(s) in SMILES: [2H]c1ccc(Br)cc1!

 Warning  Isotope(s) in SMILES: [2H]c1ccc(Br)cc1!

 Warning  Isotope(s) in SMILES: [2H]c1ccc(Br)cc1!

 Warning  Isotope(s) in SMILES: [2H]c1ccc(Br)cc1!

 Warning  Isotope(s) in SMILES: [2H]c1ccc(Br)cc1!

 Warning  Isotope(s) in SMILES: [2H]c1ccc(Br)cc1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])OS(C)(=O)=O!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])OS(C)(=O)=O!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])OS(C)(=O)=O!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])OS(C)(=O)=O!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])OS(C)(=O)=O!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])OS(C)(=O)=O!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])OS(C)(=O)=O!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NCC(F)(F)F!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NCC(F)(F)F!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NCC(F)(F)F!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NCC(F)(F)F!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NCC(F)(F)F!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NCC(F)(F)F!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NCC(F)(F)F!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])Oc1ccccc1C=O!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])Oc1ccccc1C=O!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])Oc1ccccc1C=O!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])Oc1ccccc1C=O!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])Oc1ccccc1C=O!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])Oc1ccccc1C=O!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])Oc1ccccc1C=O!

 Warning  Isotope(s) in SMILES: [2H]c1cccc(Br)c1!

 Warning  Isotope(s) in SMILES: [2H]c1cccc(Br)c1!

 Warning  Isotope(s) in SMILES: [2H]c1cccc(Br)c1!

 Warning  Isotope(s) in SMILES: [2H]c1cccc(Br)c1!

 Warning  Isotope(s) in SMILES: [2H]c1cccc(Br)c1!

 Warning  Isotope(s) in SMILES: [2H]c1cccc(Br)c1!

 Warning  Isotope(s) in SMILES: [2H]c1cccc(Br)c1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NCC!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NCC!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NCC!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NCC!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NCC!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NCC!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NCC!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NCC(=O)OC!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NCC(=O)OC!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NCC(=O)OC!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NCC(=O)OC!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NCC(=O)OC!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NCC(=O)OC!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NCC(=O)OC!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NC(C)C!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NC(C)C!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NC(C)C!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NC(C)C!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NC(C)C!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NC(C)C!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NC(C)C!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])c1ccc(N)cc1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])c1ccc(N)cc1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])c1ccc(N)cc1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])c1ccc(N)cc1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])c1ccc(N)cc1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])c1ccc(N)cc1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])c1ccc(N)cc1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])(N)Cc1nc2ccccc2n1CCN(C)C!

 Warning  Isotope(s) in SMILES: [2H]C([2H])(N)Cc1nc2ccccc2n1CCN(C)C!

 Warning  Isotope(s) in SMILES: [2H]C([2H])(N)Cc1nc2ccccc2n1CCN(C)C!

 Warning  Isotope(s) in SMILES: [2H]C([2H])(N)Cc1nc2ccccc2n1CCN(C)C!

 Warning  Isotope(s) in SMILES: [2H]C([2H])(N)Cc1nc2ccccc2n1CCN(C)C!

 Warning  Isotope(s) in SMILES: [2H]C([2H])(N)Cc1nc2ccccc2n1CCN(C)C!

 Warning  Isotope(s) in SMILES: [2H]C([2H])(N)Cc1nc2ccccc2n1CCN(C)C!

 Warning  Isotope(s) in SMILES: [2H]c1c(Br)cnn1C!

 Warning  Isotope(s) in SMILES: [2H]c1c(Br)cnn1C!

 Warning  Isotope(s) in SMILES: [2H]c1c(Br)cnn1C!

 Warning  Isotope(s) in SMILES: [2H]c1c(Br)cnn1C!

 Warning  Isotope(s) in SMILES: [2H]c1c(Br)cnn1C!

 Warning  Isotope(s) in SMILES: [2H]c1c(Br)cnn1C!

 Warning  Isotope(s) in SMILES: [2H]c1c(Br)cnn1C!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NCC(=O)O!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NCC(=O)O!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NCC(=O)O!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NCC(=O)O!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NCC(=O)O!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NCC(=O)O!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NCC(=O)O!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])c1cccc(Br)c1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])c1cccc(Br)c1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])c1cccc(Br)c1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])c1cccc(Br)c1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])c1cccc(Br)c1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])c1cccc(Br)c1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])(N)c1nc2ccccc2[nH]1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])(N)c1nc2ccccc2[nH]1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])(N)c1nc2ccccc2[nH]1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])(N)c1nc2ccccc2[nH]1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])(N)c1nc2ccccc2[nH]1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])n1cc(N)cn1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])n1cc(N)cn1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])n1cc(N)cn1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])n1cc(N)cn1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])n1cc(N)cn1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])n1cc(N)cn1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])n1cc(N)cn1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])n1cc(N)cn1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NN!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NN!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NN!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NN!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NN!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])OCC(=O)O!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])OCC(=O)O!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])OCC(=O)O!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])OCC(=O)O!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])OCC(=O)O!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])OCC(=O)O!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])OCC(=O)O!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])OCC(=O)O!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])n1cc(Br)cn1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])n1cc(Br)cn1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])n1cc(Br)cn1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])n1cc(Br)cn1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])n1cc(Br)cn1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])n1cc(Br)cn1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])n1cc(Br)cn1!

 Warning  Isotope(s) in SMILES: [2H]c1ccc(Br)cc1!

 Warning  Isotope(s) in SMILES: [2H]c1ccc(Br)cc1!

 Warning  Isotope(s) in SMILES: [2H]c1ccc(Br)cc1!

 Warning  Isotope(s) in SMILES: [2H]c1ccc(Br)cc1!

 Warning  Isotope(s) in SMILES: [2H]c1ccc(Br)cc1!

 Warning  Isotope(s) in SMILES: [2H]c1ccc(Br)cc1!

 Warning  Isotope(s) in SMILES: [2H]c1ccc(Br)cc1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])OS(C)(=O)=O!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])OS(C)(=O)=O!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])OS(C)(=O)=O!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])OS(C)(=O)=O!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])OS(C)(=O)=O!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])OS(C)(=O)=O!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])OS(C)(=O)=O!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])OS(C)(=O)=O!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NCC(F)(F)F!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NCC(F)(F)F!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NCC(F)(F)F!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NCC(F)(F)F!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NCC(F)(F)F!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NCC(F)(F)F!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NCC(F)(F)F!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NCC(F)(F)F!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])Oc1ccccc1C=O!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])Oc1ccccc1C=O!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])Oc1ccccc1C=O!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])Oc1ccccc1C=O!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])Oc1ccccc1C=O!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])Oc1ccccc1C=O!

 Warning  Isotope(s) in SMILES: [2H]c1cccc(Br)c1!

 Warning  Isotope(s) in SMILES: [2H]c1cccc(Br)c1!

 Warning  Isotope(s) in SMILES: [2H]c1cccc(Br)c1!

 Warning  Isotope(s) in SMILES: [2H]c1cccc(Br)c1!

 Warning  Isotope(s) in SMILES: [2H]c1cccc(Br)c1!

 Warning  Isotope(s) in SMILES: [2H]c1cccc(Br)c1!

 Warning  Isotope(s) in SMILES: [2H]c1cccc(Br)c1!

 Warning  Isotope(s) in SMILES: [2H]c1cccc(Br)c1!

 Warning  Isotope(s) in SMILES: [2H]c1c(Br)cnn1C!

 Warning  Isotope(s) in SMILES: [2H]c1c(Br)cnn1C!

 Warning  Isotope(s) in SMILES: [2H]c1c(Br)cnn1C!

 Warning  Isotope(s) in SMILES: [2H]c1c(Br)cnn1C!

 Warning  Isotope(s) in SMILES: [2H]c1c(Br)cnn1C!

 Warning  Isotope(s) in SMILES: [2H]c1c(Br)cnn1C!

 Warning  Isotope(s) in SMILES: [2H]c1c(Br)cnn1C!

#new quotes = 55130

#quoted_compounds = 9683

#unquoted_compounds = 1887

sb --job-name "xx01zvns2b_c2_routes" $HOME2/slurm/run_python.sh c02d_routes.py

In [28]:
hit_elabs = animal.compounds(tag="openbind_xx01zvns2b_c2_elabs")
hit_elabs

compounds tagged openbind_xx01zvns2b_c2_elabs: {C × 43671}

In [29]:
routes = hippo.RouteSet.from_product_ids(animal.db, (hit_elabs.scaffolds + hit_elabs).ids)
routes

Output()

{Route × 40585}

In [30]:
routes.reactants

{C × 4129}

In [31]:
routes.reactants.write_smiles_csv("cycle_02/syndirella/elabs/openbind_xx01zvns2b_c2_elab_route_reactants.csv")

 DISK  Writing cycle_02/syndirella/elabs/openbind_xx01zvns2b_c2_elab_route_reactants.csv...

## Crystal Hit Analogues

Queue `c02c_hit_analogues.py`

In [14]:
animal.tags.summary()

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━┓
┃ tag                                            ┃ num_compounds ┃ num_poses ┃ num_posed_compounds ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━┩
│ BAD count                                      │ 0             │ 337       │ 303                 │
│ BulkDock Fragalysis export                     │ 0             │ 5159      │ 4467                │
│ C1 85percent analogue                          │ 45            │ 0         │ 0                   │
│ C1 90percent analogue                          │ 15            │ 0         │ 0                   │
│ C1 95percent analogue                          │ 9             │ 0         │ 0                   │
│ C10 85percent analogue                         │ 30            │ 0         │ 0                   │
│ C10 90percent analogue                         │ 5             │ 0         │ 0                   │
│ C100 85percent analogue                        │ 1             │ 0         │ 0                   │
│ C103 85percent analogue                        │ 3             │ 0         │ 0                   │
│ C104 85percent analogue                        │ 2             │ 0         │ 0                   │
│ C105 85percent analogue                        │ 1             │ 0         │ 0                   │
│ C106 85percent analogue                        │ 4             │ 0         │ 0                   │
│ C107 85percent analogue                        │ 1             │ 0         │ 0                   │
│ C108 85percent analogue                        │ 122           │ 0         │ 0                   │
│ C108 90percent analogue                        │ 9             │ 0         │ 0                   │
│ C11 85percent analogue                         │ 16            │ 0         │ 0                   │
│ C11 90percent analogue                         │ 5             │ 0         │ 0                   │
│ C110 85percent analogue                        │ 12            │ 0         │ 0                   │
│ C110 90percent analogue                        │ 2             │ 0         │ 0                   │
│ C111 85percent analogue                        │ 1             │ 0         │ 0                   │
│ C114 85percent analogue                        │ 1             │ 0         │ 0                   │
│ C115 85percent analogue                        │ 3             │ 0         │ 0                   │
│ C118 85percent analogue                        │ 1             │ 0         │ 0                   │
│ C119 85percent analogue                        │ 1             │ 0         │ 0                   │
│ C121 85percent analogue                        │ 3             │ 0         │ 0                   │
│ C122 85percent analogue                        │ 1             │ 0         │ 0                   │
│ C123 85percent analogue                        │ 3             │ 0         │ 0                   │
│ C123 90percent analogue                        │ 1             │ 0         │ 0                   │
│ C124 85percent analogue                        │ 1             │ 0         │ 0                   │
│ C126 85percent analogue                        │ 1             │ 0         │ 0                   │
│ C127 85percent analogue                        │ 6             │ 0         │ 0                   │
│ C128 85percent analogue                        │ 2             │ 0         │ 0                   │
│ C129 85percent analogue                        │ 2             │ 0         │ 0                   │
│ C13 85percent analogue                         │ 15            │ 0         │ 0                   │
│ C13 90percent analogue                         │ 3             │ 0         │ 0                   │
│ C132 85percent analogue                        │ 3             │ 0         │ 0                   │
│ C134 85percent analogue                        │ 1             │ 0         │ 0                   │
│ C136 85percent analogue                        │ 3             │ 0         │ 0                   │
│ C139 85percent analogue                        │ 1             │ 0         │ 0                   │
│ C14 85percent analogue                         │ 40            │ 0         │ 0                   │
│ C14 90percent analogue                         │ 9             │ 0         │ 0                   │
│ C141 85percent analogue                        │ 1             │ 0         │ 0                   │
│ C144 85percent analogue                        │ 2             │ 0         │ 0                   │
│ C145 85percent analogue                        │ 6             │ 0         │ 0                   │
│ C149 85percent analogue                        │ 1             │ 0         │ 0                   │
│ C15 85percent analogue                         │ 6             │ 0         │ 0                   │
│ C15 90percent analogue                         │ 2             │ 0         │ 0                   │
│ C150 85percent analogue                        │ 16            │ 0         │ 0                   │
│ C151 85percent analogue                        │ 21            │ 0         │ 0                   │
│ C153 85percent analogue                        │ 5             │ 0         │ 0                   │
│ C159 85percent analogue                        │ 6             │ 0         │ 0                   │
│ C16 85percent analogue                         │ 52            │ 0         │ 0                   │
│ C16 90percent analogue                         │ 15            │ 0         │ 0                   │
│ C16 95percent analogue                         │ 6             │ 0         │ 0                   │
│ C161 85percent analogue                        │ 2             │ 0         │ 0                   │
│ C162 85percent analogue                        │ 3             │ 0         │ 0                   │
│ C168 85percent analogue                        │ 5             │ 0         │ 0                   │
│ C169 85percent analogue                        │ 2             │ 0         │ 0                   │
│ C169 90percent analogue                        │ 1             │ 0         │ 0                   │
│ C17 85percent analogue                         │ 15            │ 0         │ 0                   │
│ C17 90percent analogue                         │ 5             │ 0         │ 0                   │
│ C171 85percent analogue                        │ 14            │ 0         │ 0                   │
│ C171 90percent analogue                        │ 1             │ 0         │ 0                   │
│ C173 85percent analogue                        │ 12            │ 0         │ 0                   │
│ C175 85percent analogue                        │ 2             │ 0         │ 0                   │
│ C18 85percent analogue                         │ 13            │ 0         │ 0                   │
│ C18 90percent analogue                         │ 2             │ 0         │ 0                   │
│ C180 85percent analogue                        │ 1             │ 0         │ 0                   │
│ C181 85percent analogue                        │ 1             │ 0         │ 0                   │
│ C183 85percent analogue                        │ 9             │ 0         │ 0                   │
│ C185 85percent analogue                        │ 2             │ 0         │ 0                   │
│ C188 85percent analogue                        │ 1             │ 0         │ 0                   │
│ C19 85percent analogue                         │ 3             │ 0         │ 0                   │
│ C192 85percent analogue                        │ 4             │ 0         │ 0                   │
│ C193 85percent analogue                        │ 4             │ 0         │ 0                   │
│ C196 85percent analogue                        │ 4             │ 0         │ 0                   │
│ C198 85percent analogue                        │ 13            │ 0         │ 0                   │
│ C199 85percent analogue                        │ 2             │ 0         │ 0                   │
│ C20 85percent analogue                         │ 59            │ 0         │ 0                   │
│ C20 90percent analogue                         │ 13            │ 0         │ 0                   │
│ C204 85percent analogue                        │ 3             │ 0         │ 0                   │
│ C206 85percent analogue                        │ 2             │ 0         │ 0                   │
│ C209 85percent analogue                        │ 1             │ 0         │ 0                   │
│ C21 85percent analogue                         │ 20            │ 0         │ 0                   │
│ C21 90percent analogue                         │ 5             │ 0         │ 0                   │
│ C210 85percent analogue                        │ 1             │ 0         │ 0                   │
│ C211 85percent analogue                        │ 1             │ 0         │ 0                   │
│ C212 85percent analogue                        │ 3             │ 0         │ 0                   │
│ C213 85percent analogue                        │ 1             │ 0         │ 0                   │
│ C219 85percent analogue                        │ 4             │ 0         │ 0                   │
│ C22 85percent analogue                         │ 8             │ 0         │ 0                   │
│ C22 90percent analogue                         │ 4             │ 0         │ 0                   │
│ C22 95percent analogue                         │ 1             │ 0         │ 0                   │
│ C221 85percent analogue                        │ 2             │ 0         │ 0                   │
│ C223 85percent analogue                        │ 1             │ 0         │ 0                   │
│ C224 85percent analogue                        │ 1             │ 0         │ 0                   │
│ C228 85percent analogue                        │ 3             │ 0         │ 0                   │
│ C229 85percent analogue                        │ 1             │ 0         │ 0                   │
│ C23 85percent analogue                         │ 11            │ 0         │ 0                   │
│ C23 90percent analogue                         │ 1             │ 0         │ 0                   │
│ C230 85percent analogue                        │ 1             │ 0         │ 0                   │
│ C231 85percent analogue                        │ 1             │ 0         │ 0                   │
│ C232 85percent analogue                        │ 1             │ 0         │ 0                   │
│ C24 85percent analogue                         │ 2             │ 0         │ 0                   │
│ C24 90percent analogue                         │ 1             │ 0         │ 0                   │
│ C240 85percent analogue                        │ 1             │ 0         │ 0                   │
│ C246 85percent analogue                        │ 3             │ 0         │ 0                   │
│ C25 85percent analogue                         │ 32            │ 0         │ 0                   │
│ C25 90percent analogue                         │ 1             │ 0         │ 0                   │
│ C26 85percent analogue                         │ 9             │ 0         │ 0                   │
│ C26 90percent analogue                         │ 3             │ 0         │ 0                   │
│ C26 95percent analogue                         │ 1             │ 0         │ 0                   │
│ C262 85percent analogue                        │ 1             │ 0         │ 0                   │
│ C27 85percent analogue                         │ 5             │ 0         │ 0                   │
│ C272 85percent analogue                        │ 3             │ 0         │ 0                   │
│ C273 85percent analogue                        │ 1             │ 0         │ 0                   │
│ C277 85percent analogue                        │ 1             │ 0         │ 0                   │
│ C28 85percent analogue                         │ 31            │ 0         │ 0                   │
│ C28 90percent analogue                         │ 6             │ 0         │ 0                   │
│ C28 95percent analogue                         │ 1             │ 0         │ 0                   │
│ C286 85percent analogue                        │ 1             │ 0         │ 0                   │
│ C29 85percent analogue                         │ 2             │ 0         │ 0                   │
│ C29 90percent analogue                         │ 1             │ 0         │ 0                   │
│ C295 85percent analogue                        │ 1             │ 0         │ 0                   │
│ C296 85percent analogue                        │ 2             │ 0         │ 0                   │
│ C297 85percent analogue                        │ 1             │ 0         │ 0                   │
│ C3 85percent analogue                          │ 17            │ 0         │ 0                   │
│ C3 90percent analogue                          │ 5             │ 0         │ 0                   │
│ C30 85percent analogue                         │ 38            │ 0         │ 0                   │
│ C30 90percent analogue                         │ 16            │ 0         │ 0                   │
│ C30 95percent analogue                         │ 3             │ 0         │ 0                   │
│ C31 85percent analogue                         │ 26            │ 0         │ 0                   │
│ C31 90percent analogue                         │ 8             │ 0         │ 0                   │
│ C31 95percent analogue                         │ 3             │ 0         │ 0                   │
│ C32 85percent analogue                         │ 1             │ 0         │ 0                   │
│ C32 90percent analogue                         │ 1             │ 0         │ 0                   │
│ C33 85percent analogue                         │ 31            │ 0         │ 0                   │
│ C33 90percent analogue                         │ 3             │ 0         │ 0                   │
│ C33 95percent analogue                         │ 1             │ 0         │ 0                   │
│ C34 85percent analogue                         │ 10            │ 0         │ 0                   │
│ C34 90percent analogue                         │ 1             │ 0         │ 0                   │
│ C35 85percent analogue                         │ 31            │ 0         │ 0                   │
│ C35 90percent analogue                         │ 6             │ 0         │ 0                   │
│ C35 95percent analogue                         │ 1             │ 0         │ 0                   │
│ C36 85percent analogue                         │ 1             │ 0         │ 0                   │
│ C38 85percent analogue                         │ 2             │ 0         │ 0                   │
│ C39 85percent analogue                         │ 48            │ 0         │ 0                   │
│ C39 90percent analogue                         │ 10            │ 0         │ 0                   │
│ C40 85percent analogue                         │ 23            │ 0         │ 0                   │
│ C40 90percent analogue                         │ 10            │ 0         │ 0                   │
│ C40 95percent analogue                         │ 2             │ 0         │ 0                   │
│ C41 85percent analogue                         │ 36            │ 0         │ 0                   │
│ C41 90percent analogue                         │ 14            │ 0         │ 0                   │
│ C41 95percent analogue                         │ 4             │ 0         │ 0                   │
│ C42 85percent analogue                         │ 14            │ 0         │ 0                   │
│ C42 90percent analogue                         │ 5             │ 0         │ 0                   │
│ C43 85percent analogue                         │ 9             │ 0         │ 0                   │
│ C44 85percent analogue                         │ 1             │ 0         │ 0                   │
│ C45 85percent analogue                         │ 40            │ 0         │ 0                   │
│ C45 90percent analogue                         │ 2             │ 0         │ 0                   │
│ C46 85percent analogue                         │ 34            │ 0         │ 0                   │
│ C46 90percent analogue                         │ 4             │ 0         │ 0                   │
│ C47 85percent analogue                         │ 3             │ 0         │ 0                   │
│ C48 85percent analogue                         │ 17            │ 0         │ 0                   │
│ C48 90percent analogue                         │ 4             │ 0         │ 0                   │
│ C48 95percent analogue                         │ 1             │ 0         │ 0                   │
│ C49 85percent analogue                         │ 33            │ 0         │ 0                   │
│ C49 90percent analogue                         │ 10            │ 0         │ 0                   │
│ C49 95percent analogue                         │ 3             │ 0         │ 0                   │
│ C5 85percent analogue                          │ 1             │ 0         │ 0                   │
│ C50 85percent analogue                         │ 17            │ 0         │ 0                   │
│ C50 90percent analogue                         │ 3             │ 0         │ 0                   │
│ C50 95percent analogue                         │ 2             │ 0         │ 0                   │
│ C51 85percent analogue                         │ 33            │ 0         │ 0                   │
│ C51 90percent analogue                         │ 8             │ 0         │ 0                   │
│ C51 95percent analogue                         │ 3             │ 0         │ 0                   │
│ C52 85percent analogue                         │ 146           │ 0         │ 0                   │
│ C52 90percent analogue                         │ 10            │ 0         │ 0                   │
│ C52 95percent analogue                         │ 1             │ 0         │ 0                   │
│ C53 85percent analogue                         │ 15            │ 0         │ 0                   │
│ C54 85percent analogue                         │ 1             │ 0         │ 0                   │
│ C55 85percent analogue                         │ 5             │ 0         │ 0                   │
│ C56 85percent analogue                         │ 3             │ 0         │ 0                   │
│ C58 85percent analogue                         │ 2             │ 0         │ 0                   │
│ C6 85percent analogue                          │ 64            │ 0         │ 0                   │
│ C6 90percent analogue                          │ 14            │ 0         │ 0                   │
│ C6 95percent analogue                          │ 4             │ 0         │ 0                   │
│ C61 85percent analogue                         │ 1             │ 0         │ 0                   │
│ C63 85percent analogue                         │ 3             │ 0         │ 0                   │
│ C64 85percent analogue                         │ 8             │ 0         │ 0                   │
│ C65 85percent analogue                         │ 1             │ 0         │ 0                   │
│ C67 85percent analogue                         │ 1             │ 0         │ 0                   │
│ C69 85percent analogue                         │ 3             │ 0         │ 0                   │
│ C7 85percent analogue                          │ 32            │ 0         │ 0                   │
│ C7 90percent analogue                          │ 12            │ 0         │ 0                   │

In [18]:
!mkdir cycle_02/analogues

In [19]:
animal.compounds(tag="openbind_xx01zvns2b_c2_hit_analogues_85percent").write_smiles_csv("cycle_02/analogues/openbind_xx01zvns2b_c2_hit_analogues_85percent.csv")

 DISK  Writing cycle_02/analogues/openbind_xx01zvns2b_c2_hit_analogues_85percent.csv...

In [20]:
animal.compounds(tag="openbind_xx01zvns2b_c2_hit_analogues_90percent").write_smiles_csv("cycle_02/analogues/openbind_xx01zvns2b_c2_hit_analogues_90percent.csv")

 DISK  Writing cycle_02/analogues/openbind_xx01zvns2b_c2_hit_analogues_90percent.csv...

In [21]:
animal.compounds(tag="openbind_xx01zvns2b_c2_hit_analogues_95percent").write_smiles_csv("cycle_02/analogues/openbind_xx01zvns2b_c2_hit_analogues_95percent.csv")

 DISK  Writing cycle_02/analogues/openbind_xx01zvns2b_c2_hit_analogues_95percent.csv...