# OpenBind-HIPPO

- **Target: D68EV3C**
- **Cycle: 01**

## Prep

- [ ] Generate, place, and export merges

## Imports

In [29]:
%load_ext autoreload
%autoreload 2
import hippo
import mrich
from mrich import print
from pathlib import Path
from os import environ
import shutil
import molparse as mp
from mocassin.mocassin import calculate_mocassin

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

# Config

In [2]:
target_name = "D68EV3C"
target_dir = Path(environ["BULK"]) / "TARGETS" / target_name
cycle_name = "cycle_01"
cycle_dir = Path(cycle_name)
aligned_dir = target_dir / "aligned_files"

## Animal

In [3]:
animal = hippo.HIPPO(target_name, target_dir / f"{target_name}.sqlite")

 Creating HIPPO animal

name = D68EV3C

db_path = /opt/xchem-fragalysis-2/maxwin/BulkDock/TARGETS/D68EV3C/D68EV3C.sqlite

DEBUG: hippo.Database.__init__()

DEBUG: Database.path = /opt/xchem-fragalysis-2/maxwin/BulkDock/TARGETS/D68EV3C/D68EV3C.sqlite

DEBUG: hippo.Database.connect()

DEBUG: sqlite3.version='2.6.0'

 Success  Database connected @ /opt/xchem-fragalysis-2/maxwin/BulkDock/TARGETS/D68EV3C/D68EV3C.sqlite!

 Success  Initialised animal HIPPO("D68EV3C")!

# Annotate Pockets (subsites)

Assign subsites from Canonical site definitions in metadata (for all experimental hits)

In [4]:
hits = animal.poses(tag="hits")
hits.set_subsites_from_metadata_field()

Assign subsites of derivatives based on inspiration subsites

In [5]:
animal.db.set_derivative_subsites()

Print a summary

In [7]:
hits.derivatives.subsite_summary();

┏━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━┓
┃ subsite            ┃ num_poses ┃
┡━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━┩
│ 2 - 7gon/B/201/1   │ 30851     │
│ 4 - 7gp7/A/201/1   │ 24751     │
│ 1 - 7gp9/A/201/1   │ 16346     │
│ 5 - B1120/A/308/1  │ 12889     │
│ 3 - 7gpw/B/202/1   │ 10420     │
│ 24 - 7gpz/B/201/1  │ 5031      │
│ 30 - 7gqr/B/201/1  │ 3351      │
│ 14 - 7go6/A/201/1  │ 3018      │
│ 10 - 7gq5/A/201/1  │ 2051      │
│ 8 - 7goa/A/201/1   │ 1735      │
│ 29 - 7gqn/A/202/1  │ 1627      │
│ 27 - 7gql/A/201/1  │ 1555      │
│ 13 - 7go5/A/201/1  │ 1385      │
│ 9 - 7gq1/B/202/1   │ 1382      │
│ 28 - 7gqn/A/201/1  │ 1357      │
│ 17 - 7gok/A/201/1  │ 1225      │
│ 11 - B0517/A/209/1 │ 875       │
│ 15 - 7gob/B/201/1  │ 18        │
│ 22 - 7gpw/A/201/1  │ 17        │
│ 6 - B0798/A/308/1  │ 11        │
│ 18 - 7gom/B/201/1  │ 7         │
│ 25 - 7gq1/A/201/1  │ 4         │
│ 23 - 7gpx/B/201/1  │ 4         │
│ 31 - B0878/A/309/1 │ 2         │
│ 7 - B1081/A/308/1  │ 2         │
│ 21 - 7gpv/B/201/1  │ 1         │
│ 20 - 7gp1/B/201/1  │ 1         │
└────────────────────┴───────────┘

# Tag Scaffolds

Tag your scaffolds, e.g. by their BulkDock export:

In [13]:
scaffold_poses = (
    animal.poses.get_by_metadata_substring_match("openbind_d68ev3c_c1_fragmenstein_1669J2U.sdf") + 
    animal.poses.get_by_metadata_substring_match("openbind_d68ev3c_c1_knitwork_pure_1669ISE.sdf") + 
    animal.poses.get_by_metadata_substring_match("openbind_d68ev3c_c1_knitwork_impure_1669BTJ.sdf")
)

scaffold_poses.add_tag("openbind_D68EV3C_01_scaffolds")
scaffold_poses

Tagged {P × 345} w/ "openbind_D68EV3C_01_scaffolds"

{P × 345}

In [15]:
scaffold_poses.subsite_summary();

┏━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━┓
┃ subsite            ┃ num_poses ┃
┡━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━┩
│ 2 - 7gon/B/201/1   │ 176       │
│ 1 - 7gp9/A/201/1   │ 111       │
│ 4 - 7gp7/A/201/1   │ 61        │
│ 5 - B1120/A/308/1  │ 42        │
│ 3 - 7gpw/B/202/1   │ 17        │
│ 11 - B0517/A/209/1 │ 14        │
│ 10 - 7gq5/A/201/1  │ 8         │
│ 30 - 7gqr/B/201/1  │ 8         │
│ 14 - 7go6/A/201/1  │ 5         │
│ 15 - 7gob/B/201/1  │ 2         │
│ 17 - 7gok/A/201/1  │ 1         │
│ 24 - 7gpz/B/201/1  │ 1         │
│ 25 - 7gq1/A/201/1  │ 1         │
│ 28 - 7gqn/A/201/1  │ 1         │
│ 29 - 7gqn/A/202/1  │ 1         │
└────────────────────┴───────────┘

# Prepare for Syndirella inputs

In [16]:
scaffold_poses.to_syndirella("cycle_01/syndirella/openbind_d68ev3c_c1_scaffolds")

 DISK  Writing cycle_01/syndirella/templates...

out_key = openbind_d68ev3c_c1_scaffolds

#poses = 345

Output()

 DISK  Writing cycle_01/syndirella/templates/7gp3-a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/7gqd-a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/7go7-a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/B0454b_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/7gov-a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/7go4-b_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/7gq5-b_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/7gpp-a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/7gow-a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/7gpq-a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/7gqa-a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/7go9-a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/7got-a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/7gpo-a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/7gq3-a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/openbind_d68ev3c_c1_scaffolds_syndirella_input.csv...

DEBUG: querying...

Output()

 DISK  Writing cycle_01/syndirella/openbind_d68ev3c_c1_scaffolds_syndirella_inspiration_hits.sdf...

,smiles,template,compound_set,hit1,hit2,hit3,hit4,hit5
0,OC(=NCCNc1cccc2nc(Cl)oc12)c1ccsc1,7gp3-a,openbind_d68ev3c_c1_scaffolds,7gqr-a,7gp7-a,NaN,NaN,NaN
1,NC(c1ccccc1)c1cccc(O)c1,7gp3-a,openbind_d68ev3c_c1_scaffolds,7gqb-a,7gp8-a,NaN,NaN,NaN
2,CCC1C(O)CC(F)C(F)C1C(N)c1ccccc1,7gp3-a,openbind_d68ev3c_c1_scaffolds,7gqb-a,7gpi-a,NaN,NaN,NaN
3,NC(c1ccccc1)C1CCCCC12CNC(O)CC2O,7gp3-a,openbind_d68ev3c_c1_scaffolds,7gqb-a,7go7-a,NaN,NaN,NaN
4,NC(c1ccccc1)c1ccccc1I,7gp3-a,openbind_d68ev3c_c1_scaffolds,7gqb-a,7go4-a,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
340,c1cc2c(cc1C1CCCNC1)CCCC2,7gq3-a,openbind_d68ev3c_c1_scaffolds,7gpc-a,7gpg-a,NaN,NaN,NaN
341,CCC(C)C(=O)NCC(=O)N1CCCC(CNC(=O)c2cc[nH]n2)C1,7gq3-a,openbind_d68ev3c_c1_scaffolds,7gpc-a,7gpg-a,NaN,NaN,NaN
342,CC(CNC(=O)C12CCC(CC1)O2)NC(=O)Cc1nccn1C,7gq3-a,openbind_d68ev3c_c1_scaffolds,7gpc-a,7gpg-a,NaN,NaN,NaN
343,O=C(CCc1ccc2ncsc2c1)N1CCN(c2ncc[nH]2)CC1,7gq3-a,openbind_d68ev3c_c1_scaffolds,7gpc-a,7gpg-a,NaN,NaN,NaN
344,CC(CNC1CCNC1=O)NC(=O)c1cccc2cc[nH]c12,7gq3-a,openbind_d68ev3c_c1_scaffolds,7gpc-a,7gpg-a,NaN,NaN,NaN

# Run syndirella

```
cd cycle_01/syndirella
sbatch --job-name "d68ev3c_c1_syndirella" --mem 16000 $HOME2/slurm/run_bash_with_conda.sh ../../../scripts/run_syndirella_retro.sh
```

In [18]:
animal.tags.rename("openbind_D68EV3C_01_scaffolds", "openbind_d68ev3c_c1_scaffolds")

In [26]:
animal.tags.unique

{'BAD count',
 'BulkDock Fragalysis export',
 'GOOD count',
 'MEDIOCRE count',
 'Main status',
 '[Other] iter1_frags',
 '[Other] upload_1 2025-02-11',
 'fragmenstein_placed',
 'hits',
 'openbind_d68ev3c_c1_fragmenstein',
 'openbind_d68ev3c_c1_knitwork_impure',
 'openbind_d68ev3c_c1_knitwork_pure',
 'openbind_d68ev3c_c1_scaffolds'}

In [52]:
animal.poses(tag="openbind_d68ev3c_c1_scaffolds")[1]

C1396->P235: "OXSCMJBFQDXPTM-UHFFFAOYSA-N"

In [53]:
pose = animal.P235
inspirations = pose.inspirations
pose, inspirations.names

(C1396->P235: "OXSCMJBFQDXPTM-UHFFFAOYSA-N",
 ['7gqb-a', '7gp8-a'])

In [54]:
calculate_mocassin(
    inspirations.mols, 
    pose.mol, 
    shape_score_mode="CustomTversky", 
    alpha=0.9, 
    beta=0.1
)

(0.528, 0.631, 0.424)

In [39]:
(pose + inspirations).draw()

In [55]:
(pose + inspirations).draw()

In [56]:
animal.db.backup()

 DISK  Writing /opt/xchem-fragalysis-2/maxwin/BulkDock/TARGETS/D68EV3C/D68EV3C_1AZTHZM.sqlite...

Output()

DEBUG: Copied 10000 of 141531 pages...

DEBUG: Copied 20000 of 141531 pages...

DEBUG: Copied 30000 of 141531 pages...

DEBUG: Copied 40000 of 141531 pages...

DEBUG: Copied 50000 of 141531 pages...

DEBUG: Copied 60000 of 141531 pages...

DEBUG: Copied 70000 of 141531 pages...

DEBUG: Copied 80000 of 141531 pages...

DEBUG: Copied 90000 of 141531 pages...

DEBUG: Copied 100000 of 141531 pages...

DEBUG: Copied 110000 of 141531 pages...

DEBUG: Copied 120000 of 141531 pages...

DEBUG: Copied 130000 of 141531 pages...

DEBUG: Copied 140000 of 141531 pages...

DEBUG: Copied 141531 of 141531 pages...

In [61]:
animal.add_syndirella_routes("cycle_01/syndirella/retrosynthesis/justretroquery_openbind_d68ev3c_c1_scaffolds_syndirella_input.pkl.gz", CAR_only=False)

0 0 0 Buchwald-Hartwig_amination C1366 "BJXKXVYPGPQTDR-UHFFFAOYSA-N"

 Success  registered route 230!

1 0 0 Petasis-borono_Mannich_reaction C1396 "OXSCMJBFQDXPTM-UHFFFAOYSA-N"

reactants =
[96981, 96982, 96983]

product = C1396 "OXSCMJBFQDXPTM-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Petasis-borono_Mannich_reaction!

1 1 0 Petasis-borono_Mannich_reaction C1396 "OXSCMJBFQDXPTM-UHFFFAOYSA-N"

reactants =
[96983, 96984, 96985]

product = C1396 "OXSCMJBFQDXPTM-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Petasis-borono_Mannich_reaction!

1 2 0 Methoxy_to_hydroxy_(aryl) C1396 "OXSCMJBFQDXPTM-UHFFFAOYSA-N"

reactants =
[96986]

product = C1396 "OXSCMJBFQDXPTM-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Methoxy_to_hydroxy_(aryl)!

1 3 0 Reductive_amination C1396 "OXSCMJBFQDXPTM-UHFFFAOYSA-N"

 Success  registered route 231!

3 0 0 Amine_alkylation C1415 "SAQAVPRVQJBJCH-UHFFFAOYSA-N"

reactants =
[96988]

product = C1415 "SAQAVPRVQJBJCH-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

3 1 0 Amine_alkylation C1415 "SAQAVPRVQJBJCH-UHFFFAOYSA-N"

reactants =
[96988]

product = C1415 "SAQAVPRVQJBJCH-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

3 2 0 Amine_alkylation C1415 "SAQAVPRVQJBJCH-UHFFFAOYSA-N"

reactants =
[96989]

product = C1415 "SAQAVPRVQJBJCH-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

3 3 0 Amine_alkylation C1415 "SAQAVPRVQJBJCH-UHFFFAOYSA-N"

reactants =
[96988]

product = C1415 "SAQAVPRVQJBJCH-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

3 4 0 Amine_alkylation C1415 "SAQAVPRVQJBJCH-UHFFFAOYSA-N"

reactants =
[96988]

product = C1415 "SAQAVPRVQJBJCH-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

4 0 0 Petasis-borono_Mannich_reaction C1418 "YACRXAUWVDSWQM-UHFFFAOYSA-N"

reactants =
[96981, 96983, 96990]

product = C1418 "YACRXAUWVDSWQM-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Petasis-borono_Mannich_reaction!

4 1 0 Petasis-borono_Mannich_reaction C1418 "YACRXAUWVDSWQM-UHFFFAOYSA-N"

reactants =
[96983, 96985, 96991]

product = C1418 "YACRXAUWVDSWQM-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Petasis-borono_Mannich_reaction!

4 2 0 Reductive_amination C1418 "YACRXAUWVDSWQM-UHFFFAOYSA-N"

 Success  registered route 232!

5 0 0 Buchwald-Hartwig_amination C1422 "SJCSSVLZFASSLN-UHFFFAOYSA-N"

 Success  registered route 233!

6 0 0 Buchwald-Hartwig_(thio)etherification C1430 "YIOLBBFTNHBTIE-UHFFFAOYSA-N"

reactants =
[1445, 96994]

product = C1430 "YIOLBBFTNHBTIE-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Buchwald-Hartwig_(thio)etherification!

6 1 0 Buchwald-Hartwig_amidation_with_amide-like_nucleophile C1430 "YIOLBBFTNHBTIE-UHFFFAOYSA-N"

 Success  registered route 234!

8 0 0 Iodo_N-arylation C1442 "PCBUMFIPUOURIZ-UHFFFAOYSA-N"

reactants =
[96996, 96997]

product = C1442 "PCBUMFIPUOURIZ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Iodo_N-arylation!

8 1 0 Buchwald-Hartwig_amidation_with_amide-like_nucleophile C1442 "PCBUMFIPUOURIZ-UHFFFAOYSA-N"

 Success  registered route 235!

9 0 0 Iodo_N-arylation C1445 "RIOMUJXIGYZENC-UHFFFAOYSA-N"

reactants =
[96996, 96999]

product = C1445 "RIOMUJXIGYZENC-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Iodo_N-arylation!

9 1 0 Sandmeyer_chlorination C1445 "RIOMUJXIGYZENC-UHFFFAOYSA-N"

reactants =
[1441]

product = C1445 "RIOMUJXIGYZENC-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sandmeyer_chlorination!

9 2 0 Buchwald-Hartwig_amidation_with_amide-like_nucleophile C1445 "RIOMUJXIGYZENC-UHFFFAOYSA-N"

 Success  registered route 236!

10 0 0 Ester_to_alcohol_reduction_(intermolecular) C1449 "AFSNCTCRJMBOIU-UHFFFAOYSA-N"

reactants =
[97001]

product = C1449 "AFSNCTCRJMBOIU-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Ester_to_alcohol_reduction_(intermolecular)!

10 1 0 Ester_to_alcohol_reduction_(intermolecular) C1449 "AFSNCTCRJMBOIU-UHFFFAOYSA-N"

reactants =
[97002]

product = C1449 "AFSNCTCRJMBOIU-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Ester_to_alcohol_reduction_(intermolecular)!

10 2 0 Iodo_N-arylation C1449 "AFSNCTCRJMBOIU-UHFFFAOYSA-N"

reactants =
[97003, 97004]

product = C1449 "AFSNCTCRJMBOIU-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Iodo_N-arylation!

10 3 0 Carboxylic_acid_to_alcohol_reduction C1449 "AFSNCTCRJMBOIU-UHFFFAOYSA-N"

reactants =
[97005]

product = C1449 "AFSNCTCRJMBOIU-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Carboxylic_acid_to_alcohol_reduction!

10 4 0 Buchwald-Hartwig_amidation_with_amide-like_nucleophile C1449 "AFSNCTCRJMBOIU-UHFFFAOYSA-N"

 Success  registered route 237!

11 0 0 Buchwald-Hartwig_amidation_with_amide-like_nucleophile C1452 "CSLDQGHMIXWCBB-UHFFFAOYSA-N"

 Success  registered route 238!

12 0 0 Buchwald-Hartwig_amination C1454 "BLTNZUIEECRNOY-UHFFFAOYSA-N"

 Success  registered route 239!

13 0 0 Buchwald-Hartwig_amidation_with_amide-like_nucleophile C1458 "RBRQTHJQCMIPIZ-UHFFFAOYSA-N"

 Success  registered route 240!

15 0 0 Friedel-Crafts_methylation C1552 "OXBOUCQJOFCRFX-UHFFFAOYSA-N"

reactants =
[97011]

product = C1552 "OXBOUCQJOFCRFX-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Friedel-Crafts_methylation!

15 1 0 Friedel-Crafts_methylation C1552 "OXBOUCQJOFCRFX-UHFFFAOYSA-N"

reactants =
[97011]

product = C1552 "OXBOUCQJOFCRFX-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Friedel-Crafts_methylation!

15 2 0 Friedel-Crafts_methylation C1552 "OXBOUCQJOFCRFX-UHFFFAOYSA-N"

reactants =
[97011]

product = C1552 "OXBOUCQJOFCRFX-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Friedel-Crafts_methylation!

15 3 0 Friedel-Crafts_methylation C1552 "OXBOUCQJOFCRFX-UHFFFAOYSA-N"

reactants =
[97011]

product = C1552 "OXBOUCQJOFCRFX-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Friedel-Crafts_methylation!

15 4 0 Friedel-Crafts_methylation C1552 "OXBOUCQJOFCRFX-UHFFFAOYSA-N"

reactants =
[97011]

product = C1552 "OXBOUCQJOFCRFX-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Friedel-Crafts_methylation!

17 0 0 Buchwald-Hartwig_amidation_with_amide-like_nucleophile C1565 "YKGLYKRWKJHQOZ-UHFFFAOYSA-N"

 Success  registered route 241!

20 0 0 Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide C1676 "KZJYGOFBWIXLCF-UHFFFAOYSA-N"

reactants =
[97014]

product = C1676 "KZJYGOFBWIXLCF-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide!

20 1 0 Imine_formation C1676 "KZJYGOFBWIXLCF-UHFFFAOYSA-N"

reactants =
[97015]

product = C1676 "KZJYGOFBWIXLCF-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Imine_formation!

20 2 0 Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide C1676 "KZJYGOFBWIXLCF-UHFFFAOYSA-N"

reactants =
[97014]

product = C1676 "KZJYGOFBWIXLCF-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide!

20 3 0 Imine_formation C1676 "KZJYGOFBWIXLCF-UHFFFAOYSA-N"

reactants =
[97015]

product = C1676 "KZJYGOFBWIXLCF-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Imine_formation!

20 4 0 Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide C1676 "KZJYGOFBWIXLCF-UHFFFAOYSA-N"

reactants =
[97014]

product = C1676 "KZJYGOFBWIXLCF-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide!

21 0 0 Grignard_addition_to_carbonyl C1775 "YCWZEBQPMKVRAJ-UHFFFAOYSA-N"

reactants =
[97016, 97017]

product = C1775 "YCWZEBQPMKVRAJ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Grignard_addition_to_carbonyl!

21 1 0 Grignard_addition_to_carbonyl C1775 "YCWZEBQPMKVRAJ-UHFFFAOYSA-N"

reactants =
[97016, 97018]

product = C1775 "YCWZEBQPMKVRAJ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Grignard_addition_to_carbonyl!

21 2 0 Methoxy_to_hydroxy_(aryl) C1775 "YCWZEBQPMKVRAJ-UHFFFAOYSA-N"

reactants =
[97019]

product = C1775 "YCWZEBQPMKVRAJ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Methoxy_to_hydroxy_(aryl)!

21 3 0 Grignard_addition_to_carbonyl C1775 "YCWZEBQPMKVRAJ-UHFFFAOYSA-N"

reactants =
[97020, 97021]

product = C1775 "YCWZEBQPMKVRAJ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Grignard_addition_to_carbonyl!

21 4 0 Grignard_addition_to_carbonyl C1775 "YCWZEBQPMKVRAJ-UHFFFAOYSA-N"

reactants =
[97021, 97022]

product = C1775 "YCWZEBQPMKVRAJ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Grignard_addition_to_carbonyl!

22 0 0 Ozonolysis_(intermolecular) C1778 "KPKNZFDDSLALLN-UHFFFAOYSA-N"

reactants =
[97023]

product = C1778 "KPKNZFDDSLALLN-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Ozonolysis_(intermolecular)!

22 1 0 Ester_hydrolysis_(alcohol_fragment) C1778 "KPKNZFDDSLALLN-UHFFFAOYSA-N"

reactants =
[97024]

product = C1778 "KPKNZFDDSLALLN-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Ester_hydrolysis_(alcohol_fragment)!

22 2 0 Ozonolysis_(intermolecular) C1778 "KPKNZFDDSLALLN-UHFFFAOYSA-N"

reactants =
[97025]

product = C1778 "KPKNZFDDSLALLN-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Ozonolysis_(intermolecular)!

22 3 0 Petasis-borono_Mannich_reaction C1778 "KPKNZFDDSLALLN-UHFFFAOYSA-N"

reactants =
[97026, 97027, 97028]

product = C1778 "KPKNZFDDSLALLN-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Petasis-borono_Mannich_reaction!

22 4 0 Ozonolysis_(intermolecular) C1778 "KPKNZFDDSLALLN-UHFFFAOYSA-N"

reactants =
[97023]

product = C1778 "KPKNZFDDSLALLN-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Ozonolysis_(intermolecular)!

23 0 0 Reductive_amination C1780 "CGBRBSYAYWOUQG-UHFFFAOYSA-N"

23 0 1 Reductive_amination C97030 "MEAFQRIZGHBQLK-UHFFFAOYSA-N"

 Success  registered route 242!

24 0 0 Hydroxy_to_fluoro C395 "FKWDUSSUZVTDPB-UHFFFAOYSA-N"

reactants =
[97032]

product = C395 "FKWDUSSUZVTDPB-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Hydroxy_to_fluoro!

24 1 0 Buchwald-Hartwig_(thio)etherification C395 "FKWDUSSUZVTDPB-UHFFFAOYSA-N"

reactants =
[97033, 97034]

product = C395 "FKWDUSSUZVTDPB-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Buchwald-Hartwig_(thio)etherification!

24 2 0 S-nucleophilic_aromatic_substitution C395 "FKWDUSSUZVTDPB-UHFFFAOYSA-N"

reactants =
[97035, 97036]

product = C395 "FKWDUSSUZVTDPB-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: S-nucleophilic_aromatic_substitution!

24 3 0 Buchwald-Hartwig_(thio)etherification C395 "FKWDUSSUZVTDPB-UHFFFAOYSA-N"

reactants =
[97033, 97037]

product = C395 "FKWDUSSUZVTDPB-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Buchwald-Hartwig_(thio)etherification!

24 4 0 Hydroxy_to_fluoro C395 "FKWDUSSUZVTDPB-UHFFFAOYSA-N"

reactants =
[97032]

product = C395 "FKWDUSSUZVTDPB-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Hydroxy_to_fluoro!

25 0 0 Iodo_N-arylation C411 "PJDLLYYAKUXSMG-UHFFFAOYSA-N"

reactants =
[97038, 97039]

product = C411 "PJDLLYYAKUXSMG-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Iodo_N-arylation!

25 1 0 Chan-Lam_coupling_(amination) C411 "PJDLLYYAKUXSMG-UHFFFAOYSA-N"

reactants =
[97038, 97040]

product = C411 "PJDLLYYAKUXSMG-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Chan-Lam_coupling_(amination)!

25 2 0 Buchwald-Hartwig_amination_with_aromatic_nh_intermolecular C411 "PJDLLYYAKUXSMG-UHFFFAOYSA-N"

reactants =
[97038, 97041]

product = C411 "PJDLLYYAKUXSMG-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Buchwald-Hartwig_amination_with_aromatic_nh_intermolecular!

25 3 0 Buchwald-Hartwig_amination_with_aromatic_nh_intermolecular C411 "PJDLLYYAKUXSMG-UHFFFAOYSA-N"

reactants =
[97038, 97042]

product = C411 "PJDLLYYAKUXSMG-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Buchwald-Hartwig_amination_with_aromatic_nh_intermolecular!

25 4 0 Buchwald-Hartwig_amination_with_aromatic_nh_intermolecular C411 "PJDLLYYAKUXSMG-UHFFFAOYSA-N"

reactants =
[97038, 97039]

product = C411 "PJDLLYYAKUXSMG-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Buchwald-Hartwig_amination_with_aromatic_nh_intermolecular!

26 0 0 Minisci_reaction_with_carboxylic_acid_(intermolecular) C587 "VDIVYEFHRIKYRC-UHFFFAOYSA-N"

reactants =
[124, 97043]

product = C587 "VDIVYEFHRIKYRC-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Minisci_reaction_with_carboxylic_acid_(intermolecular)!

26 1 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C587 "VDIVYEFHRIKYRC-UHFFFAOYSA-N"

26 1 1 Minisci_reaction_with_carboxylic_acid_(intermolecular) C97044 "JUKMNCBWZMULCQ-UHFFFAOYSA-N"

reactants =
[124, 97046]

product = C97044 "JUKMNCBWZMULCQ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Minisci_reaction_with_carboxylic_acid_(intermolecular)!

26 2 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C587 "VDIVYEFHRIKYRC-UHFFFAOYSA-N"

26 2 1 Minisci_reaction_with_carboxylic_acid_(intermolecular) C97047 "DYZKHXARTWBUJY-UHFFFAOYSA-N"

reactants =
[124, 97049]

product = C97047 "DYZKHXARTWBUJY-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Minisci_reaction_with_carboxylic_acid_(intermolecular)!

26 3 0 Minisci_reaction_with_carboxylic_acid_(intermolecular) C587 "VDIVYEFHRIKYRC-UHFFFAOYSA-N"

reactants =
[124, 97043]

product = C587 "VDIVYEFHRIKYRC-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Minisci_reaction_with_carboxylic_acid_(intermolecular)!

26 4 0 Amine_alkylation C587 "VDIVYEFHRIKYRC-UHFFFAOYSA-N"

reactants =
[97048, 97050]

product = C587 "VDIVYEFHRIKYRC-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

27 0 0 Formation_of_sulfonamide_from_halide_-_Shavnya_reaction C438 "TTWHSXRVHZJZCJ-UHFFFAOYSA-N"

reactants =
[245, 97051]

product = C438 "TTWHSXRVHZJZCJ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Formation_of_sulfonamide_from_halide_-_Shavnya_reaction!

27 1 0 Amidation C438 "TTWHSXRVHZJZCJ-UHFFFAOYSA-N"

27 1 1 Formation_of_sulfonamide_from_halide_-_Shavnya_reaction C97052 "LVCIYUDNLGWHMF-UHFFFAOYSA-N"

reactants =
[245, 97054]

product = C97052 "LVCIYUDNLGWHMF-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Formation_of_sulfonamide_from_halide_-_Shavnya_reaction!

27 2 0 Formation_of_sulfonamide_from_halide_-_Shavnya_reaction C438 "TTWHSXRVHZJZCJ-UHFFFAOYSA-N"

reactants =
[245, 97055]

product = C438 "TTWHSXRVHZJZCJ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Formation_of_sulfonamide_from_halide_-_Shavnya_reaction!

27 3 0 Formation_of_sulfonamide_from_halide_-_Shavnya_reaction C438 "TTWHSXRVHZJZCJ-UHFFFAOYSA-N"

reactants =
[245, 97051]

product = C438 "TTWHSXRVHZJZCJ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Formation_of_sulfonamide_from_halide_-_Shavnya_reaction!

27 4 0 Formation_of_sulfonamide_from_halide_-_Shavnya_reaction C438 "TTWHSXRVHZJZCJ-UHFFFAOYSA-N"

reactants =
[245, 97056]

product = C438 "TTWHSXRVHZJZCJ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Formation_of_sulfonamide_from_halide_-_Shavnya_reaction!

28 0 0 Methoxy_to_hydroxy_(aryl) C439 "DKBJQVKSNYTRLC-UHFFFAOYSA-N"

reactants =
[97057]

product = C439 "DKBJQVKSNYTRLC-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Methoxy_to_hydroxy_(aryl)!

28 1 0 Amine_alkylation C439 "DKBJQVKSNYTRLC-UHFFFAOYSA-N"

reactants =
[44, 97058]

product = C439 "DKBJQVKSNYTRLC-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

28 2 0 Amine_alkylation C439 "DKBJQVKSNYTRLC-UHFFFAOYSA-N"

reactants =
[44, 97058]

product = C439 "DKBJQVKSNYTRLC-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

28 3 0 Sandmeyer_hydroxylation C439 "DKBJQVKSNYTRLC-UHFFFAOYSA-N"

reactants =
[97059]

product = C439 "DKBJQVKSNYTRLC-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sandmeyer_hydroxylation!

28 4 0 Methoxy_to_hydroxy_(aryl) C439 "DKBJQVKSNYTRLC-UHFFFAOYSA-N"

reactants =
[97057]

product = C439 "DKBJQVKSNYTRLC-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Methoxy_to_hydroxy_(aryl)!

29 0 0 Alpha_alkylation_of_ester/amide C841 "ZGSHRYFGYGGLDJ-UHFFFAOYSA-N"

reactants =
[97060]

product = C841 "ZGSHRYFGYGGLDJ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ester/amide!

29 1 0 Alpha_alkylation_of_ketone C841 "ZGSHRYFGYGGLDJ-UHFFFAOYSA-N"

reactants =
[97061]

product = C841 "ZGSHRYFGYGGLDJ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ketone!

29 2 0 Alpha_alkylation_of_ester/amide C841 "ZGSHRYFGYGGLDJ-UHFFFAOYSA-N"

reactants =
[97060]

product = C841 "ZGSHRYFGYGGLDJ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ester/amide!

29 3 0 Alpha_alkylation_of_ketone C841 "ZGSHRYFGYGGLDJ-UHFFFAOYSA-N"

reactants =
[97062]

product = C841 "ZGSHRYFGYGGLDJ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ketone!

29 4 0 Alpha_alkylation_of_ester/amide C841 "ZGSHRYFGYGGLDJ-UHFFFAOYSA-N"

reactants =
[97063]

product = C841 "ZGSHRYFGYGGLDJ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ester/amide!

31 0 0 Minisci_reaction_with_carboxylic_acid_(intermolecular) C483 "QFATZQFTNFHUFK-UHFFFAOYSA-N"

reactants =
[97064, 97065]

product = C483 "QFATZQFTNFHUFK-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Minisci_reaction_with_carboxylic_acid_(intermolecular)!

31 1 0 Aromatic_iodination C483 "QFATZQFTNFHUFK-UHFFFAOYSA-N"

reactants =
[46]

product = C483 "QFATZQFTNFHUFK-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Aromatic_iodination!

31 2 0 Alpha_alkylation_of_ester/amide C483 "QFATZQFTNFHUFK-UHFFFAOYSA-N"

reactants =
[97066, 97067]

product = C483 "QFATZQFTNFHUFK-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ester/amide!

31 3 0 Conjugate_addition_of_organolithium_(Gilman_reagent) C483 "QFATZQFTNFHUFK-UHFFFAOYSA-N"

reactants =
[97068, 97069]

product = C483 "QFATZQFTNFHUFK-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Conjugate_addition_of_organolithium_(Gilman_reagent)!

31 4 0 Amidation C483 "QFATZQFTNFHUFK-UHFFFAOYSA-N"

 Success  registered route 243!

34 0 0 Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide C754 "IMUHHYAGOXNMDH-UHFFFAOYSA-N"

reactants =
[97072, 97073]

product = C754 "IMUHHYAGOXNMDH-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide!

34 1 0 Amine_alkylation C754 "IMUHHYAGOXNMDH-UHFFFAOYSA-N"

reactants =
[97074]

product = C754 "IMUHHYAGOXNMDH-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

34 2 0 Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide C754 "IMUHHYAGOXNMDH-UHFFFAOYSA-N"

reactants =
[97072, 97073]

product = C754 "IMUHHYAGOXNMDH-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide!

34 3 0 Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide C754 "IMUHHYAGOXNMDH-UHFFFAOYSA-N"

reactants =
[97072, 97073]

product = C754 "IMUHHYAGOXNMDH-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide!

34 4 0 Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide C754 "IMUHHYAGOXNMDH-UHFFFAOYSA-N"

reactants =
[97072, 97073]

product = C754 "IMUHHYAGOXNMDH-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide!

35 0 0 Paal-Knorr_pyrazole_synthesis C1330 "WOGARWOKNORZLW-UHFFFAOYSA-N"

reactants =
[97075, 97076]

product = C1330 "WOGARWOKNORZLW-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Paal-Knorr_pyrazole_synthesis!

35 1 0 Sp2-sp2_Negishi_coupling_(intermolecular) C1330 "WOGARWOKNORZLW-UHFFFAOYSA-N"

reactants =
[97077, 97078]

product = C1330 "WOGARWOKNORZLW-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sp2-sp2_Negishi_coupling_(intermolecular)!

35 2 0 Paal-Knorr_pyrazole_synthesis C1330 "WOGARWOKNORZLW-UHFFFAOYSA-N"

reactants =
[97075, 97076]

product = C1330 "WOGARWOKNORZLW-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Paal-Knorr_pyrazole_synthesis!

35 3 0 Paal-Knorr_pyrazole_synthesis C1330 "WOGARWOKNORZLW-UHFFFAOYSA-N"

reactants =
[97075, 97076]

product = C1330 "WOGARWOKNORZLW-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Paal-Knorr_pyrazole_synthesis!

35 4 0 Paal-Knorr_pyrazole_synthesis C1330 "WOGARWOKNORZLW-UHFFFAOYSA-N"

reactants =
[97075, 97076]

product = C1330 "WOGARWOKNORZLW-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Paal-Knorr_pyrazole_synthesis!

36 0 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C624 "AIJDEGVAPDMJJG-UHFFFAOYSA-N"

 Success  registered route 244!

38 0 0 Sonogashira_coupling C729 "FPOIQVPBSOEHCW-UHFFFAOYSA-N"

reactants =
[97081, 97082]

product = C729 "FPOIQVPBSOEHCW-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sonogashira_coupling!

38 1 0 Stille_coupling C729 "FPOIQVPBSOEHCW-UHFFFAOYSA-N"

reactants =
[97083, 97084]

product = C729 "FPOIQVPBSOEHCW-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Stille_coupling!

38 2 0 Stille_coupling C729 "FPOIQVPBSOEHCW-UHFFFAOYSA-N"

reactants =
[97081, 97084]

product = C729 "FPOIQVPBSOEHCW-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Stille_coupling!

38 3 0 Sonogashira_coupling C729 "FPOIQVPBSOEHCW-UHFFFAOYSA-N"

reactants =
[97082, 97083]

product = C729 "FPOIQVPBSOEHCW-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sonogashira_coupling!

38 4 0 Nucleophilic_aromatic_substitution_(alkyne) C729 "FPOIQVPBSOEHCW-UHFFFAOYSA-N"

reactants =
[97082, 97083]

product = C729 "FPOIQVPBSOEHCW-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Nucleophilic_aromatic_substitution_(alkyne)!

39 0 0 Sp3-sp2_Suzuki_coupling C793 "CMWGWJQLUUAIDS-UHFFFAOYSA-N"

 Success  registered route 245!

40 0 0 Buchwald-Hartwig_amination C654 "DWFJIPQLUTZMIQ-UHFFFAOYSA-N"

40 0 1 Chan-Lam_coupling_(amination) C97088 "MLGZMCPBFPHUMK-UHFFFAOYSA-N"

reactants =
[97089, 97090]

product = C97088 "MLGZMCPBFPHUMK-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Chan-Lam_coupling_(amination)!

40 1 0 Buchwald-Hartwig_amination C654 "DWFJIPQLUTZMIQ-UHFFFAOYSA-N"

40 1 1 Buchwald-Hartwig_amination C97088 "MLGZMCPBFPHUMK-UHFFFAOYSA-N"

40 1 2 Staudinger_reduction C97090 "ULCQLKLSKPUXQR-UHFFFAOYSA-N"

reactants =
[97092]

product = C97090 "ULCQLKLSKPUXQR-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Staudinger_reduction!

40 2 0 Buchwald-Hartwig_amination C654 "DWFJIPQLUTZMIQ-UHFFFAOYSA-N"

40 2 1 Buchwald-Hartwig_amination C97088 "MLGZMCPBFPHUMK-UHFFFAOYSA-N"

40 2 2 Staudinger_reduction C97090 "ULCQLKLSKPUXQR-UHFFFAOYSA-N"

 Warning  SMILES changed during compound registration: N#[N+][N-]C(F)F --> [N-]=[N+]=NC(F)F!

reactants =
[97092]

product = C97090 "ULCQLKLSKPUXQR-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Staudinger_reduction!

40 3 0 Buchwald-Hartwig_amination C654 "DWFJIPQLUTZMIQ-UHFFFAOYSA-N"

40 3 1 Chan-Lam_coupling_(amination) C97088 "MLGZMCPBFPHUMK-UHFFFAOYSA-N"

reactants =
[97089, 97090]

product = C97088 "MLGZMCPBFPHUMK-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Chan-Lam_coupling_(amination)!

40 4 0 Buchwald-Hartwig_amination C654 "DWFJIPQLUTZMIQ-UHFFFAOYSA-N"

40 4 1 Buchwald-Hartwig_amination C97088 "MLGZMCPBFPHUMK-UHFFFAOYSA-N"

40 4 2 Staudinger_reduction C97090 "ULCQLKLSKPUXQR-UHFFFAOYSA-N"

 Warning  SMILES changed during compound registration: N#[N+][N-]C(F)F --> [N-]=[N+]=NC(F)F!

reactants =
[97092]

product = C97090 "ULCQLKLSKPUXQR-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Staudinger_reduction!

41 0 0 Sp3-sp2_Suzuki_coupling C1026 "IZTDAONZCDDUEY-UHFFFAOYSA-N"

Traceback (most recent call last):
  File "/opt/xchem-fragalysis-2/maxwin/conda/envs/py312/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3577, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/tmp/ipykernel_29309/1041430512.py", line 1, in <module>
    animal.add_syndirella_routes("cycle_01/syndirella/retrosynthesis/justretroquery_openbind_d68ev3c_c1_scaffolds_syndirella_input.pkl.gz", CAR_only=False)
  File "/opt/xchem-fragalysis-2/maxwin/conda/envs/py312/lib/python3.12/site-packages/hippo/animal.py", line 1188, in add_syndirella_routes
    reactant = self.register_compound(smiles=reactant_s)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/xchem-fragalysis-2/maxwin/conda/envs/py312/lib/python3.12/site-packages/hippo/animal.py", line 1638, in register_compound
    return _return(compound, duplicate, return_compound, return_duplicate)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/xchem-fragalysis-2/maxwin/condaException ignored in: 'zmq.backend.cython._zmq.Frame.__del__'
Traceback (most recent call last):
  File "_zmq.py", line 160, in zmq.backend.cython._zmq._check_rc
/envs/py312/lib/python3.12/site-packages/hippo/animal.py", line 1587, in _return
    self.db.commit()
  File "/opt/xchem-fragalysis-2/maxwin/conda/envs/py312/lib/python3.12/site-packages/hippo/db.py", line 342, in commit
    self.connection.commit()
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "_zmq.py", line 160, in zmq.backend.cython._zmq._check_rc
KeyboardInterrupt
KeyboardInterrupt:

╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ in <module>:1                                                                                    │
│                                                                                                  │
│ ❱ 1 animal.add_syndirella_routes("cycle_01/syndirella/retrosynthesis/justretroquery_openbind     │
│   2                                                                                              │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │    aligned_dir = PosixPath('/opt/xchem-fragalysis-2/maxwin/BulkDock/TARGETS/D68EV3C/aligned… │ │
│ │         animal = HIPPO("D68EV3C")                                                            │ │
│ │      cycle_dir = PosixPath('cycle_01')                                                       │ │
│ │     cycle_name = 'cycle_01'                                                                  │ │
│ │        environ = environ({                                                                   │ │
│ │                  │   'HYDRA_LAUNCHER_EXTRA_ARGS': '--external-launcher',                     │ │
│ │                  │   'PRECURSOR': '/opt/xchem-fragalysis-2/maxwin/2A_Precursor_FFF',         │ │
│ │                  │   'MAMBA_ALWAYS_YES': 'yes',                                              │ │
│ │                  │   'CONDA_SHLVL': '1',                                                     │ │
│ │                  │   'LD_LIBRARY_PATH':                                                      │ │
│ │                  '/usr/local/cuda/compat:/opt/xchem-fragalysis-2/maxwin/conda/lib:/dls_sw/e… │ │
│ │                  │   'LS_COLORS':                                                            │ │
│ │                  'rs=0:di=38;5;33:ln=38;5;51:mh=00:pi=40;38;5;11:so=38;5;13:do=38;5;5:bd=48… │ │
│ │                  │   'CONDA_EXE': '/opt/xchem-fragalysis-2/maxwin/conda/bin/conda',          │ │
│ │                  │   'SLURM_NODEID': '0',                                                    │ │
│ │                  │   'SLURM_TASK_PID': '10034',                                              │ │
│ │                  │   'SSH_CONNECTION': '172.23.162.11 47758 172.23.176.6 22',                │ │
│ │                  │   ... +132                                                                │ │
│ │                  })                                                                          │ │
│ │           exit = <IPython.core.autocall.ZMQExitAutocall object at 0x7f0182fe73b0>            │ │
│ │    get_ipython = <bound method InteractiveShell.get_ipython of                               │ │
│ │                  <ipykernel.zmqshell.ZMQInteractiveShell object at 0x7f0182fe6de0>>          │ │
│ │          hippo = <module 'hippo' from                                                        │ │
│ │                  '/opt/xchem-fragalysis-2/maxwin/conda/envs/py312/lib/python3.12/site-packa… │ │
│ │           hits = poses tagged "hits": {P × 202}                                              │ │
│ │             In = [                                                                           │ │
│ │                  │   '',                                                                     │ │
│ │                  │   "get_ipython().run_line_magic('load_ext',                               │ │
│ │                  'autoreload')\nget_ipython().run_line_ma"+156,                              │ │
│ │                  │   'target_name = "D68EV3C"\ntarget_dir = Path(environ["BULK"]) /          │ │
│ │                  "TARGETS" / target_'+100,                                                   │ │
│ │                  │   'animal = hippo.HIPPO(target_name, target_dir /                         │ │
│ │                  f"{target_name}.sqlite")',                                                  │ │
│ │                  │   'hits =                                                                 │ │
│ │                  animal.poses(tag="hits")\nhits.set_subsites_from_metadata_field()',         │ │
│ │                  │   'animal.db.set_derivative_subsites()',                                  │ │
│ │                  │   'hits.derivatives.subsite_summary()',                                   │ │
│ │                  │   'hits.derivatives.subsite_summary();',                                  │ │
│ │                  │   'scaffold_poses = (\n                                                   │ │
│ │                  animal.poses.get_by_metadata_substring_match("openbind_D6'+315,             │ │
│ │                  │   'scaffold_poses = (\n                                                   │ │
│ │                  animal.poses.get_by_metadata_substring_match("openbindz_d'+316,             │ │
│ │                  │   ... +52                                                                 │ │
│ │                  ]                                                                           │ │
│ │   inspirations = {P × 2}                                                                     │ │
│ │       mocassin = <module 'mocassin' from                                                     │ │
│ │                  '/opt/xchem-fragalysis-2/maxwin/conda/envs/py312/lib/python3.12/site-packa… │ │
│ │             mp = <module 'molparse' from                                                     │ │
│ │                  '/opt/xchem-fragalysis-2/maxwin/conda/envs/py312/lib/python3.12/site-packa… │ │
│ │          mrich = <module 'mrich' from                                                        │ │
│ │                  '/opt/xchem-fragalysis-2/maxwin/conda/envs/py312/lib/python3.12/site-packa… │ │
│ │            Out = {                                                                           │ │
│ │                  │   6:                     num_poses                                        │ │
│ │                  subsite                                                                     │ │
│ │                  2 - 7gon/B/201/1        30851                                               │ │
│ │                  4 - 7gp7/A/201/1        24751                                               │ │
│ │                  1 - 7gp9/A/201/1        16346                                               │ │
│ │                  5 - B1120/A/308/1       12889                                               │ │
│ │                  3 - 7gpw/B/202/1        10420                                               │ │
│ │                  24 - 7gpz/B/201/1        5031                                               │ │
│ │                  30 - 7gqr/B/201/1        3351                                               │ │
│ │                  14 - 7go6/A/201/1        3018                                               │ │
│ │                  10 - 7gq5/A/201/1        2051                                               │ │
│ │                  8 - 7goa/A/201/1         1735                                               │ │
│ │                  29 - 7gqn/A/202/1        1627                                               │ │
│ │                  27 - 7gql/A/201/1        1555                                               │ │
│ │                  13 - 7go5/A/201/1        1385                                               │ │
│ │                  9 - 7gq1/B/202/1         1382                                               │ │
│ │                  28 - 7gqn/A/201/1        1357                                               │ │
│ │                  17 - 7gok/A/201/1        1225                                               │ │
│ │                  11 - B0517/A/209/1        875                                               │ │
│ │                  15 - 7gob/B/201/1          18                                               │ │
│ │                  22 - 7gpw/A/201/1          17                                               │ │
│ │                  6 - B0798/A/308/1          11                                               │ │
│ │                  18 - 7gom/B/201/1           7                                               │ │
│ │                  25 - 7gq1/A/201/1           4                                               │ │
│ │                  23 - 7gpx/B/201/1           4                                               │ │
│ │                  31 - B0878/A/309/1          2                                               │ │
│ │                  7 - B1081/A/308/1           2                                               │ │
│ │                  21 - 7gpv/B/201/1           1                                               │ │
│ │                  20 - 7gp1/B/201/1           1,                                              │ │
│ │                  │   12: {P × 345},                                                          │ │
│ │                  │   13: {P × 345},                                                          │ │
│ │                  │   14:                     num_poses                                       │ │
│ │                  subsite                                                                     │ │
│ │                  2 - 7gon/B/201/1          176                                               │ │
│ │                  1 - 7gp9/A/201/1          111                                               │ │
│ │                  4 - 7gp7/A/201/1           61                                               │ │
│ │                  5 - B1120/A/308/1          42                                               │ │
│ │                  3 - 7gpw/B/202/1           17                                               │ │
│ │                  11 - B0517/A/209/1         14                                               │ │
│ │                  10 - 7gq5/A/201/1           8                                               │ │
│ │                  30 - 7gqr/B/201/1           8                                               │ │
│ │                  14 - 7go6/A/201/1           5                                               │ │
│ │                  15 - 7gob/B/201/1           2                                               │ │
│ │                  17 - 7gok/A/201/1           1                                               │ │
│ │                  24 - 7gpz/B/201/1           1                                               │ │
│ │                  25 - 7gq1/A/201/1           1                                               │ │
│ │                  28 - 7gqn/A/201/1           1                                               │ │
│ │                  29 - 7gqn/A/202/1           1,                                              │ │
│ │                  │   16:                                             smiles template  \      │ │
│ │                  0                OC(=NCCNc1cccc2nc(Cl)oc12)c1ccsc1   7gp3-a                 │ │
│ │                  1                          NC(c1ccccc1)c1cccc(O)c1   7gp3-a                 │ │
│ │                  2                  CCC1C(O)CC(F)C(F)C1C(N)c1ccccc1   7gp3-a                 │ │
│ │                  3                  NC(c1ccccc1)C1CCCCC12CNC(O)CC2O   7gp3-a                 │ │
│ │                  4                            NC(c1ccccc1)c1ccccc1I   7gp3-a                 │ │
│ │                  ..                                             ...      ...                 │ │
│ │                  340                       c1cc2c(cc1C1CCCNC1)CCCC2   7gq3-a                 │ │
│ │                  341  CCC(C)C(=O)NCC(=O)N1CCCC(CNC(=O)c2cc[nH]n2)C1   7gq3-a                 │ │
│ │                  342        CC(CNC(=O)C12CCC(CC1)O2)NC(=O)Cc1nccn1C   7gq3-a                 │ │
│ │                  343       O=C(CCc1ccc2ncsc2c1)N1CCN(c2ncc[nH]2)CC1   7gq3-a                 │ │
│ │                  344          CC(CNC1CCNC1=O)NC(=O)c1cccc2cc[nH]c12   7gq3-a                 │ │
│ │                  │   │   │   │   │                                                           │ │
│ │                  │   │   │   │   │     compound_set    hit1    hit2 hit3 hit4 hit5           │ │
│ │                  0    openbind_d68ev3c_c1_scaffolds  7gqr-a  7gp7-a  NaN  NaN  NaN           │ │
│ │                  1    openbind_d68ev3c_c1_scaffolds  7gqb-a  7gp8-a  NaN  NaN  NaN           │ │
│ │                  2    openbind_d68ev3c_c1_scaffolds  7gqb-a  7gpi-a  NaN  NaN  NaN           │ │
│ │                  3    openbind_d68ev3c_c1_scaffolds  7gqb-a  7go7-a  NaN  NaN  NaN           │ │
│ │                  4    openbind_d68ev3c_c1_scaffolds  7gqb-a  7go4-a  NaN  NaN  NaN           │ │
│ │                  ..                             ...     ...     ...  ...  ...  ...           │ │
│ │                  340  openbind_d68ev3c_c1_scaffolds  7gpc-a  7gpg-a  NaN  NaN  NaN           │ │
│ │                  341  openbind_d68ev3c_c1_scaffolds  7gpc-a  7gpg-a  NaN  NaN  NaN           │ │
│ │                  342  openbind_d68ev3c_c1_scaffolds  7gpc-a  7gpg-a  NaN  NaN  NaN           │ │
│ │                  343  openbind_d68ev3c_c1_scaffolds  7gpc-a  7gpg-a  NaN  NaN  NaN           │ │
│ │                  344  openbind_d68ev3c_c1_scaffolds  7gpc-a  7gpg-a  NaN  NaN  NaN           │ │
│ │                                                                                              │ │
│ │                  [345 rows x 8 columns],                                                     │ │
│ │                  │   19: {                                                                   │ │
│ │                  │   │   'openbind_d68ev3c_c1_knitwork_pure',                                │ │
│ │                  │   │   'BulkDock Fragalysis export',                                       │ │
│ │                  │   │   'openbind_d68ev3c_c1_fragmenstein',                                 │ │
│ │                  │   │   '[Other] upload_1 2025-02-11',                                      │ │
│ │                  │   │   'openbind_d68ev3c_c1_scaffolds',                                    │ │
│ │                  │   │   '[Other] iter1_frags',                                              │ │
│ │                  │   │   'GOOD count',                                                       │ │
│ │                  │   │   'Main status',                                                      │ │
│ │                  │   │   'MEDIOCRE count',                                                   │ │
│ │                  │   │   'openbind_d68ev3c_c1_knitwork_impure',                              │ │
│ │                  │   │   ... +4                                                              │ │
│ │                  │   },                                                                      │ │
│ │                  │   20: poses tagged "openbind_D68EV3C_01_scaffolds": {P × 345},            │ │
│ │                  │   21: poses tagged "openbind_d68ev3c_c1_scaffolds": {P × 345},            │ │
│ │                  │   23: poses tagged "openbind_d68ev3c_c1_scaffolds": {P × 345},            │ │
│ │                  │   24: poses tagged "openbind_D68EV3C_01_scaffolds": {P × 345},            │ │
│ │                  │   ... +24                                                                 │ │
│ │                  }                                                                           │ │
│ │           pose = C1396->P235: "OXSCMJBFQDXPTM-UHFFFAOYSA-N"                                  │ │
│ │           quit = <IPython.core.autocall.ZMQExitAutocall object at 0x7f0182fe73b0>            │ │
│ │ scaffold_poses = {P × 345}                                                                   │ │
│ │         shutil = <module 'shutil' from                                                       │ │
│ │                  '/opt/xchem-fragalysis-2/maxwin/conda/envs/py312/lib/python3.12/shutil.py'> │ │
│ │            sql = '\nUPDATE OR IGNORE tag\nSET tag_name = ?2\nWHERE tag_name = ?1;\n'         │ │
│ │     target_dir = PosixPath('/opt/xchem-fragalysis-2/maxwin/BulkDock/TARGETS/D68EV3C')        │ │
│ │    target_name = 'D68EV3C'                                                                   │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                                  │
│ /opt/xchem-fragalysis-2/maxwin/conda/envs/py312/lib/python3.12/site-packages/hippo/animal.py:118 │
│ 8 in add_syndirella_routes                                                                       │
│                                                                                                  │
│   1185 │   │   │   │   │   │                                                                     │
│   1186 │   │   │   │   │   │   rs = []                                                           │
│   1187 │   │   │   │   │   │   for reactant_s in reaction["reactantSmiles"]:                     │
│ ❱ 1188 │   │   │   │   │   │   │   reactant = self.register_compound(smiles=reactant_s)          │
│   1189 │   │   │   │   │   │   │   rs.append(reactant.id)                                        │
│   1190 │   │   │   │   │   │                                                                     │
│   1191 │   │   │   │   │   │   # register the reaction                                           │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │        CAR_only = False                                                                      │ │
│ │ check_chemistry = True                                                                       │ │
│ │            comp = C1026 "IZTDAONZCDDUEY-UHFFFAOYSA-N"                                        │ │
│ │               d = {                                                                          │ │
│ │                   │   'smiles': 'CC1(C)OC(=O)c2c(cc(O)c(Br)c2CCNS(=O)(=O)c2ccns2)O1',        │ │
│ │                   │   'template': '7gqd-a',                                                  │ │
│ │                   │   'compound_set': 'openbind_d68ev3c_c1_scaffolds',                       │ │
│ │                   │   'hit1': '7gq1-a',                                                      │ │
│ │                   │   'hit2': '7gp0-a',                                                      │ │
│ │                   │   'hit3': nan,                                                           │ │
│ │                   │   'hit4': nan,                                                           │ │
│ │                   │   'hit5': nan,                                                           │ │
│ │                   │   'route0': [                                                            │ │
│ │                   │   │   {                                                                  │ │
│ │                   │   │   │   'name': 'Sp3-sp2_Suzuki_coupling',                             │ │
│ │                   │   │   │   'reactantSmiles': [                                            │ │
│ │                   │   │   │   │   'CC1(C)OC(=O)c2c(cc(O)c(Br)c2I)O1',                        │ │
│ │                   │   │   │   │   'CC1(C)OB(CCNS(=O)(=O)c2ccns2)OC1(C)C'                     │ │
│ │                   │   │   │   ],                                                             │ │
│ │                   │   │   │   'productSmiles':                                               │ │
│ │                   'CC1(C)OC(=O)c2c(cc(O)c(Br)c2CCNS(=O)(=O)c2ccns2)O1'                       │ │
│ │                   │   │   },                                                                 │ │
│ │                   │   │   {                                                                  │ │

In [62]:
animal.db.prune_duplicate_routes()

#routes = 245

products with duplicate routes = 16

compound 1366 has 4 duplicate routes

compound 1396 has 4 duplicate routes

compound 1418 has 4 duplicate routes

compound 1422 has 4 duplicate routes

compound 1430 has 4 duplicate routes

compound 1442 has 4 duplicate routes

compound 1445 has 4 duplicate routes

compound 1449 has 4 duplicate routes

compound 1452 has 4 duplicate routes

compound 1454 has 4 duplicate routes

compound 1458 has 4 duplicate routes

compound 1565 has 4 duplicate routes

compound 97030 has 3 duplicate routes

compound 483 has 2 duplicate routes

compound 624 has 2 duplicate routes

compound 793 has 2 duplicate routes

 Success  Deleted 41 duplicate routes!

{205,
 206,
 207,
 208,
 209,
 210,
 211,
 212,
 213,
 214,
 215,
 216,
 217,
 218,
 219,
 220,
 221,
 222,
 223,
 224,
 225,
 226,
 227,
 228,
 229,
 230,
 231,
 232,
 233,
 234,
 235,
 236,
 237,
 238,
 239,
 240,
 241,
 242,
 243,
 244,
 245}

In [65]:
cset = animal.poses(tag="openbind_d68ev3c_c1_scaffolds").compounds
cset.add_tag("openbind_d68ev3c_c1_scaffolds")

Tagged {C × 345} w/ "openbind_d68ev3c_c1_scaffolds"

In [70]:
recipe = hippo.Recipe.from_compounds(cset, use_routes=True, pick_cheapest=False, pick_first=True)

#compounds = 345

Output()

 ERROR  No routes to C92 "FVZQEVNJWREWHU-UHFFFAOYSA-N"!

 ERROR  No routes to C157 "KDBFWFCMBXFUNH-UHFFFAOYSA-N"!

 ERROR  No routes to C158 "OALQTJJGTBIUQJ-UHFFFAOYSA-N"!

 ERROR  No routes to C159 "ZDQDZRHGVOSIRW-UHFFFAOYSA-N"!

 ERROR  No routes to C163 "XAAOQRDMNIFOQN-UHFFFAOYSA-N"!

 ERROR  No routes to C164 "OCGRGNJVXOAUJK-UHFFFAOYSA-N"!

 ERROR  No routes to C170 "QIDOCGRTYZUKQH-UHFFFAOYSA-N"!

 ERROR  No routes to C181 "UUMMUIZAOWDWTD-UHFFFAOYSA-N"!

 ERROR  No routes to C207 "ULHMPWPKRSVYDD-UHFFFAOYSA-N"!

 ERROR  No routes to C226 "ZIFVEAFJKKVTCL-UHFFFAOYSA-N"!

 ERROR  No routes to C239 "CXDLYSMXLHPFPT-UHFFFAOYSA-N"!

 ERROR  No routes to C243 "GINQBQFQOUDQDN-UHFFFAOYSA-N"!

 ERROR  No routes to C346 "SSJUKEVLNSCPSU-UHFFFAOYSA-N"!

 ERROR  No routes to C395 "FKWDUSSUZVTDPB-UHFFFAOYSA-N"!

 ERROR  No routes to C411 "PJDLLYYAKUXSMG-UHFFFAOYSA-N"!

 ERROR  No routes to C438 "TTWHSXRVHZJZCJ-UHFFFAOYSA-N"!

 ERROR  No routes to C439 "DKBJQVKSNYTRLC-UHFFFAOYSA-N"!

 ERROR  No routes to C507 "IDHQHYZTVBNVEM-UHFFFAOYSA-N"!

 ERROR  No routes to C528 "KPPATRVOAXYCOE-UHFFFAOYSA-N"!

 ERROR  No routes to C587 "VDIVYEFHRIKYRC-UHFFFAOYSA-N"!

 ERROR  No routes to C604 "WFENYVKBPQAOOK-UHFFFAOYSA-N"!

 ERROR  No routes to C605 "CNKKVOAKALIQAJ-UHFFFAOYSA-N"!

 ERROR  No routes to C620 "RSGUTJQENBKADA-UHFFFAOYSA-N"!

 ERROR  No routes to C629 "FXZBYDNKISGMQQ-UHFFFAOYSA-N"!

 ERROR  No routes to C641 "DPNQQQYQPPIZRC-UHFFFAOYSA-N"!

 ERROR  No routes to C654 "DWFJIPQLUTZMIQ-UHFFFAOYSA-N"!

 ERROR  No routes to C666 "CSOZCVMTTZZLRS-UHFFFAOYSA-N"!

 ERROR  No routes to C714 "XFXFHXNZHFMXRC-UHFFFAOYSA-N"!

 ERROR  No routes to C729 "FPOIQVPBSOEHCW-UHFFFAOYSA-N"!

 ERROR  No routes to C754 "IMUHHYAGOXNMDH-UHFFFAOYSA-N"!

 ERROR  No routes to C787 "QNEQWENHQHGYGQ-UHFFFAOYSA-N"!

 ERROR  No routes to C841 "ZGSHRYFGYGGLDJ-UHFFFAOYSA-N"!

 ERROR  No routes to C1026 "IZTDAONZCDDUEY-UHFFFAOYSA-N"!

 ERROR  No routes to C1057 "VSLABPNNNJOEGF-UHFFFAOYSA-N"!

 ERROR  No routes to C1065 "QPFMOOAXWTYAJX-UHFFFAOYSA-N"!

 ERROR  No routes to C1120 "DHTQYGHLOPXGFU-UHFFFAOYSA-N"!

 ERROR  No routes to C1140 "UGGVYPVGSADXJX-UHFFFAOYSA-N"!

 ERROR  No routes to C1145 "ZQJWJBJFKYIAQA-UHFFFAOYSA-N"!

 ERROR  No routes to C1260 "IUFZDERRNZKGNV-UHFFFAOYSA-N"!

 ERROR  No routes to C1294 "XKWDGMMHYXZUCN-UHFFFAOYSA-N"!

 ERROR  No routes to C1330 "WOGARWOKNORZLW-UHFFFAOYSA-N"!

 ERROR  No routes to C1358 "APUVCQGARNVGCS-UHFFFAOYSA-N"!

 ERROR  No routes to C1413 "VMPNWKROZBMPNO-UHFFFAOYSA-N"!

 ERROR  No routes to C1415 "SAQAVPRVQJBJCH-UHFFFAOYSA-N"!

 ERROR  No routes to C1550 "YPEANAMPJRKIQM-UHFFFAOYSA-N"!

 ERROR  No routes to C1552 "OXBOUCQJOFCRFX-UHFFFAOYSA-N"!

 ERROR  No routes to C1560 "BVXKUVCDXHJECV-UHFFFAOYSA-N"!

 ERROR  No routes to C1624 "VARLVDFTNYDJMC-UHFFFAOYSA-N"!

 ERROR  No routes to C1632 "MFUIOSQSBPZWTL-UHFFFAOYSA-N"!

 ERROR  No routes to C1676 "KZJYGOFBWIXLCF-UHFFFAOYSA-N"!

 ERROR  No routes to C1775 "YCWZEBQPMKVRAJ-UHFFFAOYSA-N"!

 ERROR  No routes to C1778 "KPKNZFDDSLALLN-UHFFFAOYSA-N"!

 ERROR  No routes to C1780 "CGBRBSYAYWOUQG-UHFFFAOYSA-N"!

 ERROR  No routes to C2740 "CBCPQDXJTGJQGF-UHFFFAOYSA-N"!

 ERROR  No routes to C2984 "ZXGDWYDKENXYKW-UHFFFAOYSA-N"!

 ERROR  No routes to C3094 "OPFJSUYURHLHHI-UHFFFAOYSA-N"!

 ERROR  No routes to C3101 "GJMHTIANTOHAPN-UHFFFAOYSA-N"!

 ERROR  No routes to C3113 "PNVWLQBJDBHDMC-UHFFFAOYSA-N"!

 ERROR  No routes to C3169 "YIZNHWQTEOQSJI-UHFFFAOYSA-N"!

 ERROR  No routes to C3254 "ADFZCUDMTLCMGP-UHFFFAOYSA-N"!

 ERROR  No routes to C3272 "UGUAILAXRAZYQR-UHFFFAOYSA-N"!

 ERROR  No routes to C3278 "HCXAWXRVDIHUCW-UHFFFAOYSA-N"!

 ERROR  No routes to C3279 "GOCYIWAPQIBLGD-UHFFFAOYSA-N"!

 ERROR  No routes to C3290 "GMTQMXAHSAWPFE-UHFFFAOYSA-N"!

 ERROR  No routes to C3316 "HHKGRDDYWWYCKB-UHFFFAOYSA-N"!

 ERROR  No routes to C3329 "HUTXYZBSCSECEI-UHFFFAOYSA-N"!

 ERROR  No routes to C3330 "JALPTGRPJRCTTO-UHFFFAOYSA-N"!

 ERROR  No routes to C3333 "ZTBUFBCEPOXSJP-UHFFFAOYSA-N"!

 ERROR  No routes to C3335 "FSUDUNSUPCXSJT-UHFFFAOYSA-N"!

 ERROR  No routes to C3338 "WOXZZJBZVWHGAC-UHFFFAOYSA-N"!

 ERROR  No routes to C3363 "OEQQPOURFDBALJ-UHFFFAOYSA-N"!

 ERROR  No routes to C3530 "QGEIOIIYGMZVIM-UHFFFAOYSA-N"!

 ERROR  No routes to C3562 "LJDJWLIBMTWRMY-UHFFFAOYSA-N"!

 ERROR  No routes to C3689 "KGPMGOMPDIDNHP-UHFFFAOYSA-N"!

 ERROR  No routes to C3698 "VEDVSPPIDXAVBQ-UHFFFAOYSA-N"!

 ERROR  No routes to C3715 "RFUDZDZLGWTUJE-UHFFFAOYSA-N"!

 ERROR  No routes to C3726 "WEHWLKAJVTZUFD-UHFFFAOYSA-N"!

 ERROR  No routes to C3730 "NGFNKELXAMTNHT-UHFFFAOYSA-N"!

 ERROR  No routes to C3731 "UCTZVMKIVANZFW-UHFFFAOYSA-N"!

 ERROR  No routes to C3771 "FPPIZHXQRJINDQ-UHFFFAOYSA-N"!

 ERROR  No routes to C3774 "MBOQPCNPJLMJSB-UHFFFAOYSA-N"!

 ERROR  No routes to C3809 "HRODOPFFJAXBLJ-UHFFFAOYSA-N"!

 ERROR  No routes to C3833 "XRJKXMOAKHZIHH-UHFFFAOYSA-N"!

 ERROR  No routes to C3838 "ZQRKEFALIPPHPN-UHFFFAOYSA-N"!

 ERROR  No routes to C3839 "PCRFJDYQFBPTTF-UHFFFAOYSA-N"!

 ERROR  No routes to C3842 "HFIRPCZXCMKVSI-UHFFFAOYSA-N"!

 ERROR  No routes to C3848 "XEZZCURYARAAPP-UHFFFAOYSA-N"!

 ERROR  No routes to C3852 "WNOFTNRAQFWLEH-UHFFFAOYSA-N"!

 ERROR  No routes to C3909 "JLQGQAAXENSHAE-UHFFFAOYSA-N"!

 ERROR  No routes to C3937 "LCSVMWAETLBEOW-UHFFFAOYSA-N"!

 ERROR  No routes to C3938 "RQNQMCFRIMCOFE-UHFFFAOYSA-N"!

 ERROR  No routes to C3986 "ZBZOMXXYZDZQCA-UHFFFAOYSA-N"!

 ERROR  No routes to C3998 "DJALVGSNTLLXML-UHFFFAOYSA-N"!

 ERROR  No routes to C4028 "PVIRLSPJORGMSQ-UHFFFAOYSA-N"!

 ERROR  No routes to C4029 "CTWPYFRJQJZSGU-UHFFFAOYSA-N"!

 ERROR  No routes to C4030 "CJTVOFQSMDSAQV-UHFFFAOYSA-N"!

 ERROR  No routes to C4103 "YTUMQXHFIOZXPN-UHFFFAOYSA-N"!

 ERROR  No routes to C4112 "IUYPQQXTGKMMMW-UHFFFAOYSA-N"!

 ERROR  No routes to C4119 "MJVQYZUVOMAMAA-UHFFFAOYSA-N"!

 ERROR  No routes to C4125 "SXDMHWVCSAQMOE-UHFFFAOYSA-N"!

 ERROR  No routes to C4129 "ILCMXEZHVXJEPI-UHFFFAOYSA-N"!

 ERROR  No routes to C4172 "ITBGIXOVWKMXRA-UHFFFAOYSA-N"!

 ERROR  No routes to C4204 "RLJUVMUBUPLMSW-UHFFFAOYSA-N"!

 ERROR  No routes to C4205 "WQVHMKUZTQFVHV-UHFFFAOYSA-N"!

 ERROR  No routes to C4208 "WCQMFAYQSLVMDE-UHFFFAOYSA-N"!

 ERROR  No routes to C4215 "GKEIVHGNIDXPLH-UHFFFAOYSA-N"!

 ERROR  No routes to C4230 "UBFRGARCRUFNQH-UHFFFAOYSA-N"!

 ERROR  No routes to C4236 "YWUZODYUFNQTET-UHFFFAOYSA-N"!

 ERROR  No routes to C4238 "OMYBOPMNOHWIDB-UHFFFAOYSA-N"!

 ERROR  No routes to C4257 "MVGWYBLLPKQETD-UHFFFAOYSA-N"!

 ERROR  No routes to C4266 "WRDFEIVUTXUBBU-UHFFFAOYSA-N"!

 ERROR  No routes to C4276 "DEAABERLIYOGSS-UHFFFAOYSA-N"!

 ERROR  No routes to C4293 "IWVZQESOJJWOPR-UHFFFAOYSA-N"!

 ERROR  No routes to C4297 "MYBRTELVIPBTHT-UHFFFAOYSA-N"!

 ERROR  No routes to C4305 "RAWKTIYUUMGONY-UHFFFAOYSA-N"!

 ERROR  No routes to C4328 "XARZUABJGNNAIR-UHFFFAOYSA-N"!

 ERROR  No routes to C4343 "IELYVEIWJLORIZ-UHFFFAOYSA-N"!

 ERROR  No routes to C4345 "VADFIGYFCGXXGU-UHFFFAOYSA-N"!

 ERROR  No routes to C4383 "WBVHPSFFKXXELN-UHFFFAOYSA-N"!

 ERROR  No routes to C4410 "ACYDIHQXUQNKTJ-UHFFFAOYSA-N"!

 ERROR  No routes to C4412 "PPXHIRPMLNNBCT-UHFFFAOYSA-N"!

 ERROR  No routes to C4446 "HCVUBEHKWLZQLZ-UHFFFAOYSA-N"!

 ERROR  No routes to C4458 "UMGAPARYCDRRNG-UHFFFAOYSA-N"!

 ERROR  No routes to C4489 "POUCBJXKPZLTEG-UHFFFAOYSA-N"!

 ERROR  No routes to C4495 "VUKNEHXBXKHFEF-UHFFFAOYSA-N"!

 ERROR  No routes to C4547 "QQWLMGGFHQKROE-UHFFFAOYSA-N"!

 ERROR  No routes to C6451 "HORVLCLBPBSEJI-UHFFFAOYSA-N"!

 ERROR  No routes to C17100 "DTOYEFDZWGQVIN-UHFFFAOYSA-N"!

 ERROR  No routes to C20147 "JFDUEAZJBLLFTI-UHFFFAOYSA-N"!

 ERROR  No routes to C23144 "HMJNJSYWGBZZGV-UHFFFAOYSA-N"!

 ERROR  No routes to C28511 "CRGFPNRSOTUXCK-UHFFFAOYSA-N"!

 ERROR  No routes to C29009 "YRMKFHALKIIQFI-UHFFFAOYSA-N"!

 ERROR  No routes to C30057 "ZKJNTCRRFGCENV-UHFFFAOYSA-N"!

 ERROR  No routes to C37765 "HKYKKFNCDPWLTB-UHFFFAOYSA-N"!

 ERROR  No routes to C39468 "PSVYRMZTACVYGH-UHFFFAOYSA-N"!

 ERROR  No routes to C47024 "BLOGGAJNIGIFFQ-UHFFFAOYSA-N"!

 ERROR  No routes to C47477 "JRFBSFPYJLBLKE-UHFFFAOYSA-N"!

 ERROR  No routes to C49683 "AYWQGUHSLKGFBJ-UHFFFAOYSA-N"!

 ERROR  No routes to C51983 "XFTRKDBFUQIIIQ-UHFFFAOYSA-N"!

 ERROR  No routes to C52064 "TWUYPGQORWIICO-UHFFFAOYSA-N"!

 ERROR  No routes to C57308 "DTUXGVQWDHQFID-UHFFFAOYSA-N"!

 ERROR  No routes to C59257 "UPVPFNWKHHCIKS-UHFFFAOYSA-N"!

 ERROR  No routes to C62195 "WQHAXWVTINCHDN-UHFFFAOYSA-N"!

 ERROR  No routes to C64666 "QLANIMZLODOYJU-UHFFFAOYSA-N"!

 ERROR  No routes to C76708 "ZTCUYYQHEBEGRG-UHFFFAOYSA-N"!

Solving recipe combinations...

Output()

In [76]:
recipe.write_json("cycle_01/syndirella/retrosynthesis/openbind_d68ev3c_c1_scaffolds.json")

 Warning  NULL Quote: 1.00mg of C97034!

 Warning  NULL Quote: 1.00mg of C97354!

 Warning  NULL Quote: 8.00mg of C96983!

 Warning  NULL Quote: 1.00mg of C97512!

 Warning  NULL Quote: 1.00mg of C97070!

 Warning  NULL Quote: 1.00mg of C97071!

 Warning  NULL Quote: 1.00mg of C97079!

 Warning  NULL Quote: 1.00mg of C97080!

 Warning  NULL Quote: 1.00mg of C97163!

 Warning  NULL Quote: 1.00mg of C97085!

 Warning  NULL Quote: 1.00mg of C97086!

 Warning  NULL Quote: 1.00mg of C97177!

 Warning  NULL Quote: 1.00mg of C97178!

 Warning  NULL Quote: 1.00mg of C96979!

 Warning  NULL Quote: 1.00mg of C96980!

 Warning  NULL Quote: 1.00mg of C96987!

 Warning  NULL Quote: 1.00mg of C96992!

 Warning  NULL Quote: 1.00mg of C96993!

 Warning  NULL Quote: 1.00mg of C96995!

 Warning  NULL Quote: 4.00mg of C96996!

 Warning  NULL Quote: 1.00mg of C96998!

 Warning  NULL Quote: 1.00mg of C97000!

 Warning  NULL Quote: 1.00mg of C97004!

 Warning  NULL Quote: 1.00mg of C97006!

 Warning  NULL Quote: 1.00mg of C97007!

 Warning  NULL Quote: 1.00mg of C97008!

 Warning  NULL Quote: 2.00mg of C97009!

 Warning  NULL Quote: 1.00mg of C97010!

 Warning  NULL Quote: 1.00mg of C97012!

 Warning  NULL Quote: 1.00mg of C97013!

 Warning  NULL Quote: 1.00mg of C97247!

 Warning  NULL Quote: 2.00mg of C97144!

 Warning  NULL Quote: 1.00mg of C97179!

 Warning  NULL Quote: 1.00mg of C97186!

 Warning  NULL Quote: 1.00mg of C97188!

 Warning  NULL Quote: 2.00mg of C97189!

 Warning  NULL Quote: 1.00mg of C97190!

 Warning  NULL Quote: 1.00mg of C97191!

 Warning  NULL Quote: 1.00mg of C97197!

 Warning  NULL Quote: 1.00mg of C97201!

 Warning  NULL Quote: 1.00mg of C97209!

 Warning  NULL Quote: 1.00mg of C97211!

 Warning  NULL Quote: 2.00mg of C97673!

 Warning  NULL Quote: 1.00mg of C97692!

 Warning  NULL Quote: 1.00mg of C97612!

 Warning  NULL Quote: 1.00mg of C97613!

 Warning  NULL Quote: 2.00mg of C97569!

 Warning  NULL Quote: 1.00mg of C97696!

 Warning  NULL Quote: 1.00mg of C97554!

 Warning  NULL Quote: 1.00mg of C97555!

 Warning  NULL Quote: 1.00mg of C97665!

 Warning  NULL Quote: 1.00mg of C97666!

 Warning  NULL Quote: 1.00mg of C97614!

 Warning  NULL Quote: 1.00mg of C97615!

 Warning  NULL Quote: 3.00mg of C97674!

 Warning  NULL Quote: 1.00mg of C97687!

 Warning  NULL Quote: 3.00mg of C97579!

 Warning  NULL Quote: 1.00mg of C97686!

 Warning  NULL Quote: 2.00mg of C97945!

 Warning  NULL Quote: 1.00mg of C97962!

 Warning  NULL Quote: 1.00mg of C97837!

 Warning  NULL Quote: 1.00mg of C97838!

 Warning  NULL Quote: 1.00mg of C6362!

 Warning  NULL Quote: 1.00mg of C97625!

 Warning  NULL Quote: 1.00mg of C97667!

 Warning  NULL Quote: 1.00mg of C97668!

 Warning  NULL Quote: 1.00mg of C97697!

 Warning  NULL Quote: 1.00mg of C97602!

 Warning  NULL Quote: 1.00mg of C97603!

 Warning  NULL Quote: 1.00mg of C97647!

 Warning  NULL Quote: 2.00mg of C97648!

 Warning  NULL Quote: 1.00mg of C97794!

 Warning  NULL Quote: 1.00mg of C97795!

 Warning  NULL Quote: 1.00mg of C97928!

 Warning  NULL Quote: 1.00mg of C97929!

 Warning  NULL Quote: 2.00mg of C97688!

 Warning  NULL Quote: 1.00mg of C97689!

 Warning  NULL Quote: 1.00mg of C97722!

 Warning  NULL Quote: 1.00mg of C97723!

 Warning  NULL Quote: 1.00mg of C97921!

 Warning  NULL Quote: 1.00mg of C97922!

 Warning  NULL Quote: 1.00mg of C97961!

 Warning  NULL Quote: 1.00mg of C97552!

 Warning  NULL Quote: 1.00mg of C97553!

 Warning  NULL Quote: 1.00mg of C94916!

 Warning  NULL Quote: 1.00mg of C97656!

 Warning  NULL Quote: 2.00mg of C97573!

 Warning  NULL Quote: 1.00mg of C97852!

 Warning  NULL Quote: 1.00mg of C97965!

 Warning  NULL Quote: 1.00mg of C97966!

 Warning  NULL Quote: 8.00mg of C97655!

 Warning  NULL Quote: 1.00mg of C97817!

 Warning  NULL Quote: 1.00mg of C97571!

 Warning  NULL Quote: 1.00mg of C97572!

 Warning  NULL Quote: 1.00mg of C97546!

 Warning  NULL Quote: 1.00mg of C97547!

 Warning  NULL Quote: 1.00mg of C97626!

 Warning  NULL Quote: 1.00mg of C97627!

 Warning  NULL Quote: 1.00mg of C97724!

 Warning  NULL Quote: 1.00mg of C97725!

 Warning  NULL Quote: 1.00mg of C97610!

 Warning  NULL Quote: 1.00mg of C97611!

 Warning  NULL Quote: 1.00mg of C97544!

 Warning  NULL Quote: 1.00mg of C97545!

 Warning  NULL Quote: 1.00mg of C97592!

 Warning  NULL Quote: 1.00mg of C97593!

 Warning  NULL Quote: 1.00mg of C14572!

 Warning  NULL Quote: 1.00mg of C97560!

 Warning  NULL Quote: 1.00mg of C97556!

 Warning  NULL Quote: 1.00mg of C97557!

 Warning  NULL Quote: 1.00mg of C97744!

 Warning  NULL Quote: 2.00mg of C97637!

 Warning  NULL Quote: 1.00mg of C97953!

 Warning  NULL Quote: 1.00mg of C97580!

 Warning  NULL Quote: 1.00mg of C97932!

 Warning  NULL Quote: 1.00mg of C97933!

 Warning  NULL Quote: 1.00mg of C97604!

 Warning  NULL Quote: 1.00mg of C97605!

 Warning  NULL Quote: 1.00mg of C4934!

 Warning  NULL Quote: 2.00mg of C97562!

 Warning  NULL Quote: 1.00mg of C97649!

 Warning  NULL Quote: 1.00mg of C97700!

 Warning  NULL Quote: 1.00mg of C97628!

 Warning  NULL Quote: 1.00mg of C97629!

 Warning  NULL Quote: 1.00mg of C97707!

 Warning  NULL Quote: 1.00mg of C97708!

 Warning  NULL Quote: 1.00mg of C97782!

 Warning  NULL Quote: 1.00mg of C97783!

 Warning  NULL Quote: 1.00mg of C97671!

 Warning  NULL Quote: 1.00mg of C97672!

 Warning  NULL Quote: 2.00mg of C97765!

 Warning  NULL Quote: 1.00mg of C97766!

 Warning  NULL Quote: 1.00mg of C97718!

 Warning  NULL Quote: 1.00mg of C97719!

 Warning  NULL Quote: 1.00mg of C97693!

 Warning  NULL Quote: 1.00mg of C97694!

 Warning  NULL Quote: 1.00mg of C97849!

 Warning  NULL Quote: 1.00mg of C97850!

 Warning  NULL Quote: 1.00mg of C43156!

 Warning  NULL Quote: 1.00mg of C97636!

 Warning  NULL Quote: 1.00mg of C97883!

 Warning  NULL Quote: 1.00mg of C97884!

 Warning  NULL Quote: 1.00mg of C97575!

 Warning  NULL Quote: 1.00mg of C97576!

 Warning  NULL Quote: 1.00mg of C97776!

 Warning  NULL Quote: 1.00mg of C97777!

 Warning  NULL Quote: 1.00mg of C97680!

 Warning  NULL Quote: 1.00mg of C97681!

 Warning  NULL Quote: 2.00mg of C97677!

 Warning  NULL Quote: 1.00mg of C97812!

 Warning  NULL Quote: 1.00mg of C97586!

 Warning  NULL Quote: 1.00mg of C97587!

 Warning  NULL Quote: 1.00mg of C97563!

 Warning  NULL Quote: 1.00mg of C97564!

 Warning  NULL Quote: 1.00mg of C97825!

 Warning  NULL Quote: 1.00mg of C97826!

 Warning  NULL Quote: 1.00mg of C97608!

 Warning  NULL Quote: 1.00mg of C97609!

 Warning  NULL Quote: 1.00mg of C97570!

 Warning  NULL Quote: 1.00mg of C97590!

 Warning  NULL Quote: 2.00mg of C97591!

 Warning  NULL Quote: 1.00mg of C97581!

 Warning  NULL Quote: 1.00mg of C97582!

 Warning  NULL Quote: 1.00mg of C97541!

 Warning  NULL Quote: 1.00mg of C97542!

 Warning  NULL Quote: 1.00mg of C97659!

 Warning  NULL Quote: 1.00mg of C97577!

 Warning  NULL Quote: 1.00mg of C97578!

 Warning  NULL Quote: 1.00mg of C97558!

 Warning  NULL Quote: 1.00mg of C97559!

 Warning  NULL Quote: 1.00mg of C97772!

 Warning  NULL Quote: 1.00mg of C97773!

 Warning  NULL Quote: 3.00mg of C97645!

 Warning  NULL Quote: 1.00mg of C97769!

 Warning  NULL Quote: 2.00mg of C97679!

 Warning  NULL Quote: 1.00mg of C97646!

 Warning  NULL Quote: 1.00mg of C97630!

 Warning  NULL Quote: 1.00mg of C97631!

 Warning  NULL Quote: 1.00mg of C97565!

 Warning  NULL Quote: 1.00mg of C97566!

 Warning  NULL Quote: 1.00mg of C97574!

 Warning  NULL Quote: 1.00mg of C97923!

 Warning  NULL Quote: 1.00mg of C97924!

 Warning  NULL Quote: 1.00mg of C97682!

 Warning  NULL Quote: 1.00mg of C97683!

 Warning  NULL Quote: 1.00mg of C97548!

 Warning  NULL Quote: 2.00mg of C97549!

 Warning  NULL Quote: 1.00mg of C97881!

 Warning  NULL Quote: 1.00mg of C97882!

 Warning  NULL Quote: 1.00mg of C97926!

 Warning  NULL Quote: 1.00mg of C97927!

 Warning  NULL Quote: 1.00mg of C97902!

 Warning  NULL Quote: 1.00mg of C97942!

 Warning  NULL Quote: 1.00mg of C97943!

 Warning  NULL Quote: 1.00mg of C97650!

 Warning  NULL Quote: 2.00mg of C97651!

 Warning  NULL Quote: 1.00mg of C17719!

 Warning  NULL Quote: 1.00mg of C97732!

 Warning  NULL Quote: 1.00mg of C26471!

 Warning  NULL Quote: 1.00mg of C97585!

 Warning  NULL Quote: 1.00mg of C97770!

 Warning  NULL Quote: 1.00mg of C97771!

 Warning  NULL Quote: 1.00mg of C49444!

 Warning  NULL Quote: 1.00mg of C97985!

 Warning  NULL Quote: 1.00mg of C97798!

 Warning  NULL Quote: 1.00mg of C97799!

 Warning  NULL Quote: 1.00mg of C97583!

 Warning  NULL Quote: 1.00mg of C97584!

 Warning  NULL Quote: 1.00mg of C5865!

 Warning  NULL Quote: 1.00mg of C97695!

 Warning  NULL Quote: 1.00mg of C97588!

 Warning  NULL Quote: 1.00mg of C97589!

 Warning  NULL Quote: 1.00mg of C97698!

 Warning  NULL Quote: 1.00mg of C97699!

 Warning  NULL Quote: 1.00mg of C97790!

 Warning  NULL Quote: 1.00mg of C97791!

 Warning  NULL Quote: 1.00mg of C97981!

 Warning  NULL Quote: 1.00mg of C97982!

 Warning  NULL Quote: 1.00mg of C97786!

 Warning  NULL Quote: 1.00mg of C97954!

 Warning  NULL Quote: 1.00mg of C97550!

 Warning  NULL Quote: 1.00mg of C97551!

 Warning  NULL Quote: 1.00mg of C97717!

 Warning  NULL Quote: 1.00mg of C38115!

 Warning  NULL Quote: 1.00mg of C97543!

 Warning  NULL Quote: 1.00mg of C97845!

 Warning  NULL Quote: 1.00mg of C97872!

 Warning  NULL Quote: 1.00mg of C97873!

 Warning  NULL Quote: 1.00mg of C97669!

 Warning  NULL Quote: 1.00mg of C97670!

 Warning  NULL Quote: 1.00mg of C97561!

 Warning  NULL Quote: 1.00mg of C97567!

 Warning  NULL Quote: 1.00mg of C97568!

 Warning  NULL Quote: 1.00mg of C26626!

 Warning  NULL Quote: 1.00mg of C97887!

 Warning  NULL Quote: 1.00mg of C97778!

 Warning  NULL Quote: 1.00mg of C97779!

 Warning  NULL Quote: 2.00mg of C97813!

 Warning  NULL Quote: 1.00mg of C97878!

 Warning  NULL Quote: 1.00mg of C97814!

 Warning  NULL Quote: 1.00mg of C97874!

 Warning  NULL Quote: 1.00mg of C97875!

 Warning  NULL Quote: 1.00mg of C97976!

 Warning  NULL Quote: 1.00mg of C97977!

 Warning  NULL Quote: 1.00mg of C97918!

 Warning  NULL Quote: 1.00mg of C97919!

 Warning  NULL Quote: 1.00mg of C97864!

 Warning  NULL Quote: 1.00mg of C97865!

 Warning  NULL Quote: 1.00mg of C97952!

 Warning  NULL Quote: 1.00mg of C97876!

 Warning  NULL Quote: 1.00mg of C97877!

 Warning  NULL Quote: 1.00mg of C97944!

 Warning  NULL Quote: 1.00mg of C97493!

 Warning  NULL Quote: 1.00mg of C97853!

 Warning  NULL Quote: 1.00mg of C97846!

 Warning  NULL Quote: 1.00mg of C97847!

 Warning  NULL Quote: 1.00mg of C97950!

 Warning  NULL Quote: 1.00mg of C97951!

 Warning  NULL Quote: 1.00mg of C97980!

 Warning  NULL Quote: 1.00mg of C97911!

 Warning  NULL Quote: 1.00mg of C97912!

 Warning  NULL Quote: 1.00mg of C97931!

 Warning  NULL Quote: 1.00mg of C97983!

 Warning  NULL Quote: 1.00mg of C97984!

 Warning  NULL Quote: 2.00mg of C97746!

 Warning  NULL Quote: 1.00mg of C97917!

 Warning  NULL Quote: 1.00mg of C97841!

 Warning  NULL Quote: 1.00mg of C97842!

 Warning  NULL Quote: 1.00mg of C97879!

 Warning  NULL Quote: 1.00mg of C97880!

 Warning  NULL Quote: 1.00mg of C97906!

 Warning  NULL Quote: 1.00mg of C97908!

 Warning  NULL Quote: 2.00mg of C97792!

 Warning  NULL Quote: 1.00mg of C97909!

 Warning  NULL Quote: 1.00mg of C97815!

 Warning  NULL Quote: 1.00mg of C97816!

 Warning  NULL Quote: 2.00mg of C97893!

 Warning  NULL Quote: 1.00mg of C97975!

 Warning  NULL Quote: 1.00mg of C97967!

 Warning  NULL Quote: 1.00mg of C97968!

 Warning  NULL Quote: 1.00mg of C97946!

 Warning  NULL Quote: 1.00mg of C97947!

 Warning  NULL Quote: 1.00mg of C97747!

 Warning  NULL Quote: 1.00mg of C97748!

 Warning  NULL Quote: 2.00mg of C97851!

 Warning  NULL Quote: 1.00mg of C97862!

 Warning  NULL Quote: 1.00mg of C97767!

 Warning  NULL Quote: 1.00mg of C97768!

 Warning  NULL Quote: 1.00mg of C97920!

 Warning  NULL Quote: 1.00mg of C97885!

 Warning  NULL Quote: 1.00mg of C97886!

 Warning  NULL Quote: 1.00mg of C97317!

 Warning  NULL Quote: 1.00mg of C97848!

 Warning  NULL Quote: 1.00mg of C97793!

 Warning  NULL Quote: 1.00mg of C97963!

 Warning  NULL Quote: 1.00mg of C97964!

 Warning  NULL Quote: 1.00mg of C97638!

 Warning  NULL Quote: 1.00mg of C97894!

 Warning  NULL Quote: 1.00mg of C97788!

 Warning  NULL Quote: 1.00mg of C97789!

 Warning  NULL Quote: 3.00mg of C97733!

 Warning  NULL Quote: 1.00mg of C97930!

 Warning  NULL Quote: 1.00mg of C97937!

 Warning  NULL Quote: 1.00mg of C97938!

 Warning  NULL Quote: 1.00mg of C97819!

 Warning  NULL Quote: 1.00mg of C97822!

 Warning  NULL Quote: 2.00mg of C97735!

 Warning  NULL Quote: 1.00mg of C97736!

 Warning  NULL Quote: 1.00mg of C97925!

 Warning  NULL Quote: 1.00mg of C83280!

 Warning  NULL Quote: 1.00mg of C97863!

 Warning  NULL Quote: 1.00mg of C97986!

 Warning  NULL Quote: 1.00mg of C97987!

 Warning  NULL Quote: 1.00mg of C97774!

 Warning  NULL Quote: 1.00mg of C97775!

 Warning  NULL Quote: 1.00mg of C97796!

 Warning  NULL Quote: 1.00mg of C97797!

 Warning  NULL Quote: 1.00mg of C97737!

 Warning  NULL Quote: 1.00mg of C97738!

 Warning  NULL Quote: 1.00mg of C97787!

 Warning  NULL Quote: 1.00mg of C97939!

 Warning  NULL Quote: 1.00mg of C97940!

 Warning  NULL Quote: 1.00mg of C97734!

 Warning  NULL Quote: 1.00mg of C97745!

 Warning  NULL Quote: 1.00mg of C97684!

 Warning  NULL Quote: 1.00mg of C97685!

 Warning  NULL Quote: 1.00mg of C68492!

 Warning  NULL Quote: 1.00mg of C97632!

 Warning  NULL Quote: 1.00mg of C97643!

 Warning  NULL Quote: 1.00mg of C97644!

 Warning  NULL Quote: 1.00mg of C97633!

 Warning  NULL Quote: 1.00mg of C97634!

 Warning  NULL Quote: 1.00mg of C97860!

 Warning  NULL Quote: 1.00mg of C97861!

 Warning  NULL Quote: 1.00mg of C97839!

 Warning  NULL Quote: 1.00mg of C97840!

 Warning  NULL Quote: 1.00mg of C97843!

 Warning  NULL Quote: 1.00mg of C97844!

 Warning  NULL Quote: 1.00mg of C48348!

 Warning  NULL Quote: 1.00mg of C97934!

 Warning  NULL Quote: 1.00mg of C97948!

 Warning  NULL Quote: 1.00mg of C97949!

 Warning  NULL Quote: 1.00mg of C97935!

 Warning  NULL Quote: 1.00mg of C97936!

 Warning  NULL Quote: 1.00mg of C97751!

 Warning  NULL Quote: 1.00mg of C97752!

 Warning  NULL Quote: 1.00mg of C97690!

 Warning  NULL Quote: 1.00mg of C97691!

 Warning  NULL Quote: 1.00mg of C97675!

 Warning  NULL Quote: 1.00mg of C97676!

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/d68ev3c/cycle_01/syndirella/retrosynthesis/openbind_d68ev3c_c1_scaffo
lds...

In [77]:
recipe.write_CAR_csv("cycle_01/syndirella/retrosynthesis/openbind_d68ev3c_c1_scaffolds.csv")

DEBUG: Querying database for routes

DEBUG: Assembling route dictionary

DEBUG: Checking availability

Output()

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/d68ev3c/cycle_01/syndirella/retrosynthesis/openbind_d68ev3c_c1_scaffo
lds_1steps.csv...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/d68ev3c/cycle_01/syndirella/retrosynthesis/openbind_d68ev3c_c1_scaffo
lds.csv...

,target-names,no-steps,concentration-required-mM,amount-required-uL,batch-tag,reactant-1-1,reactant-2-1,reaction-product-smiles-1,reaction-name-1,reaction-recipe-1,reaction-groupby-column-1
0,C1366,1,None,None,None,NCCN=C(O)c1ccsc1,Clc1nc2cccc(Cl)c2o1,OC(=NCCNc1cccc2nc(Cl)oc12)c1ccsc1,Buchwald-Hartwig_amination,None,None
1,C1396,1,None,None,None,N,O=C(c1ccccc1)c1cccc(O)c1,NC(c1ccccc1)c1cccc(O)c1,Reductive_amination,None,None
2,C1418,1,None,None,None,N,O=C(c1ccccc1)c1ccccc1I,NC(c1ccccc1)c1ccccc1I,Reductive_amination,None,None
3,C1422,1,None,None,None,N,NC(c1ccccc1)c1ccccc1Br,Nc1ccccc1C(N)c1ccccc1,Buchwald-Hartwig_amination,None,None
4,C1430,1,None,None,None,Oc1cccc(Br)c1,CC1=NNC(=O)C1,CC1=NN(c2cccc(O)c2)C(=O)C1,Buchwald-Hartwig_amidation_with_amide-like_nuc...,None,None
...,...,...,...,...,...,...,...,...,...,...,...
195,C49675,1,None,None,None,CC1(C)OB(C2CCCNC2)OC1(C)C,Clc1ccc2c(c1)CCCC2,c1cc2c(cc1C1CCCNC1)CCCC2,Sp3-sp2_Suzuki_coupling,None,None
196,C35601,1,None,None,None,O=C(NCC1CCCNC1)c1cc[nH]n1,CCC(C)C(=O)NCC(=O)O,CCC(C)C(=O)NCC(=O)N1CCCC(CNC(=O)c2cc[nH]n2)C1,Amidation,None,None
197,C51482,1,None,None,None,Cn1ccnc1CC(=O)O,CC(N)CNC(=O)C12CCC(CC1)O2,CC(CNC(=O)C12CCC(CC1)O2)NC(=O)Cc1nccn1C,Amidation,None,None
198,C32763,1,None,None,None,c1c[nH]c(N2CCNCC2)n1,O=C(O)CCc1ccc2ncsc2c1,O=C(CCc1ccc2ncsc2c1)N1CCN(c2ncc[nH]2)CC1,Amidation,None,None
199,C63365,1,None,None,None,NC1CCNC1=O,CC(CO)NC(=O)c1cccc2cc[nH]c12,CC(CNC1CCNC1=O)NC(=O)c1cccc2cc[nH]c12,Mitsunobu_reaction_with_amine_alcohol_and_thio...,None,None