# OpenBind-HIPPO

- **Target: D68EV3C**
- **Cycle: 01**

## Prep

- [ ] Generate, place, and export merges

## Imports

In [1]:
%load_ext autoreload
%autoreload 2
import hippo
import mrich
from mrich import print
from pathlib import Path
from os import environ
import shutil
import molparse as mp
from mocassin.mocassin import calculate_mocassin

# Config

In [2]:
target_name = "D68EV3C"
target_dir = Path(environ["BULK"]) / "TARGETS" / target_name
cycle_name = "cycle_01"
cycle_dir = Path(cycle_name)
aligned_dir = target_dir / "aligned_files"

## Animal

In [3]:
animal = hippo.HIPPO(target_name, target_dir / f"{target_name}.sqlite")

 Creating HIPPO animal

name = D68EV3C

db_path = /opt/xchem-fragalysis-2/maxwin/BulkDock/TARGETS/D68EV3C/D68EV3C.sqlite

DEBUG: hippo.Database.__init__()

DEBUG: Database.path = /opt/xchem-fragalysis-2/maxwin/BulkDock/TARGETS/D68EV3C/D68EV3C.sqlite

DEBUG: hippo.Database.connect()

DEBUG: sqlite3.version='2.6.0'

 Success  Database connected @ /opt/xchem-fragalysis-2/maxwin/BulkDock/TARGETS/D68EV3C/D68EV3C.sqlite!

 Success  Initialised animal HIPPO("D68EV3C")!

# Annotate Pockets (subsites)

Assign subsites from Canonical site definitions in metadata (for all experimental hits)

In [4]:
hits = animal.poses(tag="hits")
hits.set_subsites_from_metadata_field()

Assign subsites of derivatives based on inspiration subsites

In [5]:
animal.db.set_derivative_subsites()

Print a summary

In [7]:
hits.derivatives.subsite_summary();

┏━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━┓
┃ subsite            ┃ num_poses ┃
┡━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━┩
│ 2 - 7gon/B/201/1   │ 30851     │
│ 4 - 7gp7/A/201/1   │ 24751     │
│ 1 - 7gp9/A/201/1   │ 16346     │
│ 5 - B1120/A/308/1  │ 12889     │
│ 3 - 7gpw/B/202/1   │ 10420     │
│ 24 - 7gpz/B/201/1  │ 5031      │
│ 30 - 7gqr/B/201/1  │ 3351      │
│ 14 - 7go6/A/201/1  │ 3018      │
│ 10 - 7gq5/A/201/1  │ 2051      │
│ 8 - 7goa/A/201/1   │ 1735      │
│ 29 - 7gqn/A/202/1  │ 1627      │
│ 27 - 7gql/A/201/1  │ 1555      │
│ 13 - 7go5/A/201/1  │ 1385      │
│ 9 - 7gq1/B/202/1   │ 1382      │
│ 28 - 7gqn/A/201/1  │ 1357      │
│ 17 - 7gok/A/201/1  │ 1225      │
│ 11 - B0517/A/209/1 │ 875       │
│ 15 - 7gob/B/201/1  │ 18        │
│ 22 - 7gpw/A/201/1  │ 17        │
│ 6 - B0798/A/308/1  │ 11        │
│ 18 - 7gom/B/201/1  │ 7         │
│ 25 - 7gq1/A/201/1  │ 4         │
│ 23 - 7gpx/B/201/1  │ 4         │
│ 31 - B0878/A/309/1 │ 2         │
│ 7 - B1081/A/308/1  │ 2         │
│ 21 - 7gpv/B/201/1  │ 1         │
│ 20 - 7gp1/B/201/1  │ 1         │
└────────────────────┴───────────┘

# Tag Scaffolds

Tag your scaffolds, e.g. by their BulkDock export:

In [13]:
scaffold_poses = (
    animal.poses.get_by_metadata_substring_match("openbind_d68ev3c_c1_fragmenstein_1669J2U.sdf") + 
    animal.poses.get_by_metadata_substring_match("openbind_d68ev3c_c1_knitwork_pure_1669ISE.sdf") + 
    animal.poses.get_by_metadata_substring_match("openbind_d68ev3c_c1_knitwork_impure_1669BTJ.sdf")
)

scaffold_poses.add_tag("openbind_D68EV3C_01_scaffolds")
scaffold_poses

Tagged {P × 345} w/ "openbind_D68EV3C_01_scaffolds"

{P × 345}

In [15]:
scaffold_poses.subsite_summary();

┏━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━┓
┃ subsite            ┃ num_poses ┃
┡━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━┩
│ 2 - 7gon/B/201/1   │ 176       │
│ 1 - 7gp9/A/201/1   │ 111       │
│ 4 - 7gp7/A/201/1   │ 61        │
│ 5 - B1120/A/308/1  │ 42        │
│ 3 - 7gpw/B/202/1   │ 17        │
│ 11 - B0517/A/209/1 │ 14        │
│ 10 - 7gq5/A/201/1  │ 8         │
│ 30 - 7gqr/B/201/1  │ 8         │
│ 14 - 7go6/A/201/1  │ 5         │
│ 15 - 7gob/B/201/1  │ 2         │
│ 17 - 7gok/A/201/1  │ 1         │
│ 24 - 7gpz/B/201/1  │ 1         │
│ 25 - 7gq1/A/201/1  │ 1         │
│ 28 - 7gqn/A/201/1  │ 1         │
│ 29 - 7gqn/A/202/1  │ 1         │
└────────────────────┴───────────┘

# Prepare for Syndirella inputs

In [16]:
scaffold_poses.to_syndirella("cycle_01/syndirella/openbind_d68ev3c_c1_scaffolds")

 DISK  Writing cycle_01/syndirella/templates...

out_key = openbind_d68ev3c_c1_scaffolds

#poses = 345

Output()

 DISK  Writing cycle_01/syndirella/templates/7gp3-a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/7gqd-a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/7go7-a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/B0454b_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/7gov-a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/7go4-b_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/7gq5-b_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/7gpp-a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/7gow-a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/7gpq-a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/7gqa-a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/7go9-a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/7got-a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/7gpo-a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/7gq3-a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/openbind_d68ev3c_c1_scaffolds_syndirella_input.csv...

DEBUG: querying...

Output()

 DISK  Writing cycle_01/syndirella/openbind_d68ev3c_c1_scaffolds_syndirella_inspiration_hits.sdf...

,smiles,template,compound_set,hit1,hit2,hit3,hit4,hit5
0,OC(=NCCNc1cccc2nc(Cl)oc12)c1ccsc1,7gp3-a,openbind_d68ev3c_c1_scaffolds,7gqr-a,7gp7-a,NaN,NaN,NaN
1,NC(c1ccccc1)c1cccc(O)c1,7gp3-a,openbind_d68ev3c_c1_scaffolds,7gqb-a,7gp8-a,NaN,NaN,NaN
2,CCC1C(O)CC(F)C(F)C1C(N)c1ccccc1,7gp3-a,openbind_d68ev3c_c1_scaffolds,7gqb-a,7gpi-a,NaN,NaN,NaN
3,NC(c1ccccc1)C1CCCCC12CNC(O)CC2O,7gp3-a,openbind_d68ev3c_c1_scaffolds,7gqb-a,7go7-a,NaN,NaN,NaN
4,NC(c1ccccc1)c1ccccc1I,7gp3-a,openbind_d68ev3c_c1_scaffolds,7gqb-a,7go4-a,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
340,c1cc2c(cc1C1CCCNC1)CCCC2,7gq3-a,openbind_d68ev3c_c1_scaffolds,7gpc-a,7gpg-a,NaN,NaN,NaN
341,CCC(C)C(=O)NCC(=O)N1CCCC(CNC(=O)c2cc[nH]n2)C1,7gq3-a,openbind_d68ev3c_c1_scaffolds,7gpc-a,7gpg-a,NaN,NaN,NaN
342,CC(CNC(=O)C12CCC(CC1)O2)NC(=O)Cc1nccn1C,7gq3-a,openbind_d68ev3c_c1_scaffolds,7gpc-a,7gpg-a,NaN,NaN,NaN
343,O=C(CCc1ccc2ncsc2c1)N1CCN(c2ncc[nH]2)CC1,7gq3-a,openbind_d68ev3c_c1_scaffolds,7gpc-a,7gpg-a,NaN,NaN,NaN
344,CC(CNC1CCNC1=O)NC(=O)c1cccc2cc[nH]c12,7gq3-a,openbind_d68ev3c_c1_scaffolds,7gpc-a,7gpg-a,NaN,NaN,NaN

# Run syndirella

```
cd cycle_01/syndirella
sbatch --job-name "d68ev3c_c1_syndirella" --mem 16000 $HOME2/slurm/run_bash_with_conda.sh ../../../scripts/run_syndirella_retro.sh
```

## Mocassin Sandbox

In [18]:
animal.tags.rename("openbind_D68EV3C_01_scaffolds", "openbind_d68ev3c_c1_scaffolds")

In [26]:
animal.tags.unique

{'BAD count',
 'BulkDock Fragalysis export',
 'GOOD count',
 'MEDIOCRE count',
 'Main status',
 '[Other] iter1_frags',
 '[Other] upload_1 2025-02-11',
 'fragmenstein_placed',
 'hits',
 'openbind_d68ev3c_c1_fragmenstein',
 'openbind_d68ev3c_c1_knitwork_impure',
 'openbind_d68ev3c_c1_knitwork_pure',
 'openbind_d68ev3c_c1_scaffolds'}

In [52]:
animal.poses(tag="openbind_d68ev3c_c1_scaffolds")[1]

C1396->P235: "OXSCMJBFQDXPTM-UHFFFAOYSA-N"

In [53]:
pose = animal.P235
inspirations = pose.inspirations
pose, inspirations.names

(C1396->P235: "OXSCMJBFQDXPTM-UHFFFAOYSA-N",
 ['7gqb-a', '7gp8-a'])

In [54]:
calculate_mocassin(
    inspirations.mols, 
    pose.mol, 
    shape_score_mode="CustomTversky", 
    alpha=0.9, 
    beta=0.1
)

(0.528, 0.631, 0.424)

In [39]:
(pose + inspirations).draw()

In [55]:
(pose + inspirations).draw()

In [56]:
animal.db.backup()

 DISK  Writing /opt/xchem-fragalysis-2/maxwin/BulkDock/TARGETS/D68EV3C/D68EV3C_1AZTHZM.sqlite...

Output()

DEBUG: Copied 10000 of 141531 pages...

DEBUG: Copied 20000 of 141531 pages...

DEBUG: Copied 30000 of 141531 pages...

DEBUG: Copied 40000 of 141531 pages...

DEBUG: Copied 50000 of 141531 pages...

DEBUG: Copied 60000 of 141531 pages...

DEBUG: Copied 70000 of 141531 pages...

DEBUG: Copied 80000 of 141531 pages...

DEBUG: Copied 90000 of 141531 pages...

DEBUG: Copied 100000 of 141531 pages...

DEBUG: Copied 110000 of 141531 pages...

DEBUG: Copied 120000 of 141531 pages...

DEBUG: Copied 130000 of 141531 pages...

DEBUG: Copied 140000 of 141531 pages...

DEBUG: Copied 141531 of 141531 pages...

## Load Syndirella Routes

In [5]:
animal.add_syndirella_routes(
    "cycle_01/syndirella/retrosynthesis/justretroquery_openbind_d68ev3c_c1_scaffolds_syndirella_input.pkl.gz", 
    CAR_only=False, 
    check_chemistry=False,
)

Output()

0 0 0 Buchwald-Hartwig_amination C1366 "BJXKXVYPGPQTDR-UHFFFAOYSA-N"

 Success  registered route 1!

1 0 0 Petasis-borono_Mannich_reaction C1396 "OXSCMJBFQDXPTM-UHFFFAOYSA-N"

 Success  registered route 2!

3 0 0 Amine_alkylation C1415 "SAQAVPRVQJBJCH-UHFFFAOYSA-N"

3 0 1 Nitrile_to_amine_(LAH) C96988 "PXUKGVNHBGVIKM-UHFFFAOYSA-N"

3 0 2 Aldol_addition_(nitrile) C97988 "IAWVJQGLLIKGOC-UHFFFAOYSA-N"

3 0 3 Chlorination_of_alcohol C97989 "QECGQYNUIPTKPE-UHFFFAOYSA-N"

 Success  registered route 3!

4 0 0 Petasis-borono_Mannich_reaction C1418 "YACRXAUWVDSWQM-UHFFFAOYSA-N"

 Success  registered route 4!

5 0 0 Buchwald-Hartwig_amination C1422 "SJCSSVLZFASSLN-UHFFFAOYSA-N"

 Success  registered route 5!

6 0 0 Buchwald-Hartwig_(thio)etherification C1430 "YIOLBBFTNHBTIE-UHFFFAOYSA-N"

 Success  registered route 6!

8 0 0 Iodo_N-arylation C1442 "PCBUMFIPUOURIZ-UHFFFAOYSA-N"

 Success  registered route 7!

9 0 0 Iodo_N-arylation C1445 "RIOMUJXIGYZENC-UHFFFAOYSA-N"

 Success  registered route 8!

10 0 0 Ester_to_alcohol_reduction_(intermolecular) C1449 "AFSNCTCRJMBOIU-UHFFFAOYSA-N"

 Success  registered route 9!

11 0 0 Buchwald-Hartwig_amidation_with_amide-like_nucleophile C1452 "CSLDQGHMIXWCBB-UHFFFAOYSA-N"

 Success  registered route 10!

12 0 0 Buchwald-Hartwig_amination C1454 "BLTNZUIEECRNOY-UHFFFAOYSA-N"

 Success  registered route 11!

13 0 0 Buchwald-Hartwig_amidation_with_amide-like_nucleophile C1458 "RBRQTHJQCMIPIZ-UHFFFAOYSA-N"

 Success  registered route 12!

15 0 0 Friedel-Crafts_methylation C1552 "OXBOUCQJOFCRFX-UHFFFAOYSA-N"

15 0 1 Formation_of_sulfonamide_from_halide_-_Shavnya_reaction C97011 "PKCXSTDEHDSQCM-UHFFFAOYSA-N"

 Success  registered route 13!

17 0 0 Buchwald-Hartwig_amidation_with_amide-like_nucleophile C1565 "YKGLYKRWKJHQOZ-UHFFFAOYSA-N"

 Success  registered route 14!

20 0 0 Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide C1676 "KZJYGOFBWIXLCF-UHFFFAOYSA-N"

20 0 1 Imine_formation C97014 "AFNMLZMINRNBKT-UHFFFAOYSA-N"

20 0 2 Stille_coupling C97995 "ZETGLXYBSZKDKS-UHFFFAOYSA-N"

20 0 3 Aryl_halide_to_stannane C97996 "STHXYRBFHOEIDL-UHFFFAOYSA-N"

20 0 4 Riley_oxidation C97997 "HUNJASVANIPDJB-UHFFFAOYSA-N"

 Success  registered route 15!

21 0 0 Grignard_addition_to_carbonyl C1775 "YCWZEBQPMKVRAJ-UHFFFAOYSA-N"

 Success  registered route 16!

22 0 0 Ozonolysis_(intermolecular) C1778 "KPKNZFDDSLALLN-UHFFFAOYSA-N"

22 0 1 Petasis-borono_Mannich_reaction C97023 "WDJNGINBZJPVQQ-UHFFFAOYSA-N"

 Success  registered route 17!

23 0 0 Reductive_amination C1780 "CGBRBSYAYWOUQG-UHFFFAOYSA-N"

23 0 1 Reductive_amination C97030 "MEAFQRIZGHBQLK-UHFFFAOYSA-N"

 Success  registered route 18!

24 0 0 Hydroxy_to_fluoro C395 "FKWDUSSUZVTDPB-UHFFFAOYSA-N"

24 0 1 Formation_of_hydantoin_from_aldehyde_or_ketone_-_Bucherer-Bergs_reaction C97032
"PLBQPSWWEOTDTP-UHFFFAOYSA-N"

24 0 2 S-nucleophilic_aromatic_substitution C98002 "QFOPUVNLQRRFMC-UHFFFAOYSA-N"

 Success  registered route 19!

25 0 0 Iodo_N-arylation C411 "PJDLLYYAKUXSMG-UHFFFAOYSA-N"

 Success  registered route 20!

26 0 0 Minisci_reaction_with_carboxylic_acid_(intermolecular) C587 "VDIVYEFHRIKYRC-UHFFFAOYSA-N"

26 0 1 Amidation C124 "NJGXKVVNPAPYKZ-UHFFFAOYSA-N"

26 0 2 Amine_alkylation C97043 "RMWBZXHWCYVREO-UHFFFAOYSA-N"

 Success  registered route 21!

27 0 0 Formation_of_sulfonamide_from_halide_-_Shavnya_reaction C438 "TTWHSXRVHZJZCJ-UHFFFAOYSA-N"

27 0 1 Amidation C97051 "YQUOEEJHKVYRRY-UHFFFAOYSA-N"

 Success  registered route 22!

28 0 0 Methoxy_to_hydroxy_(aryl) C439 "DKBJQVKSNYTRLC-UHFFFAOYSA-N"

28 0 1 Amine_alkylation C97057 "WIRIWFMCTNDGOW-UHFFFAOYSA-N"

28 0 2 Sulfonamide_Schotten-Baumann_with_amine_(intermolecular) C98006 "SZQWENQUQZAURD-UHFFFAOYSA-N"

 Success  registered route 23!

29 0 0 Alpha_alkylation_of_ester/amide C841 "ZGSHRYFGYGGLDJ-UHFFFAOYSA-N"

29 0 1 Alpha_alkylation_of_ketone C97060 "BDZNJEIKNQDLCT-UHFFFAOYSA-N"

29 0 2 Alpha_alkylation_of_ketone C98010 "WPIXRUTUUDOFOP-UHFFFAOYSA-N"

29 0 3 Ozonolysis_(intermolecular) C98012 "VIRRJAVLBFUODJ-UHFFFAOYSA-N"

 Success  registered route 24!

31 0 0 Minisci_reaction_with_carboxylic_acid_(intermolecular) C483 "QFATZQFTNFHUFK-UHFFFAOYSA-N"

 Success  registered route 25!

34 0 0 Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide C754 "IMUHHYAGOXNMDH-UHFFFAOYSA-N"

34 0 1 Ester_hydrolysis_(alcohol_fragment) C97072 "GSPOYGSFSOXEQG-UHFFFAOYSA-N"

34 0 2 Amine_alkylation C97073 "SXOATVYWTHAZAE-UHFFFAOYSA-N"

34 0 3 Knorr_pyrrole_synthesis C98015 "GBSGIECZBSKOPD-UHFFFAOYSA-N"

34 0 4 Reductive_amination C98017 "VQKNMBGFJKLHEF-UHFFFAOYSA-N"

 Success  registered route 26!

35 0 0 Paal-Knorr_pyrazole_synthesis C1330 "WOGARWOKNORZLW-UHFFFAOYSA-N"

35 0 1 Claisen_condensation C97076 "BTQRNEQIBGUKIG-UHFFFAOYSA-N"

35 0 2 Chan-Lam_coupling_(amination) C98019 "FJBOJOJVLXSLJK-UHFFFAOYSA-N"

 Success  registered route 27!

36 0 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C624 "AIJDEGVAPDMJJG-UHFFFAOYSA-N"

 Success  registered route 28!

38 0 0 Sonogashira_coupling C729 "FPOIQVPBSOEHCW-UHFFFAOYSA-N"

38 0 1 Aromatic_iodination C97081 "YTXNMBFEYJXEPF-UHFFFAOYSA-N"

 Success  registered route 29!

39 0 0 Sp3-sp2_Suzuki_coupling C793 "CMWGWJQLUUAIDS-UHFFFAOYSA-N"

 Success  registered route 30!

40 0 0 Buchwald-Hartwig_amination C654 "DWFJIPQLUTZMIQ-UHFFFAOYSA-N"

40 0 1 Chan-Lam_coupling_(amination) C97088 "MLGZMCPBFPHUMK-UHFFFAOYSA-N"

40 0 2 Staudinger_reduction C97090 "ULCQLKLSKPUXQR-UHFFFAOYSA-N"

 Warning  SMILES changed during compound registration: N#[N+][N-]C(F)F --> [N-]=[N+]=NC(F)F!

 Success  registered route 31!

41 0 0 Sp3-sp2_Suzuki_coupling C1026 "IZTDAONZCDDUEY-UHFFFAOYSA-N"

41 0 1 Aromatic_iodination C97094 "HQYSSXCVLKHSEE-UHFFFAOYSA-N"

41 0 2 Formation_of_sulfonamide_from_halide_-_Shavnya_reaction C97095 "JPBHQPWZFCSZBI-UHFFFAOYSA-N"

 Success  registered route 32!

42 0 0 N-nucleophilic_aromatic_substitution C666 "CSOZCVMTTZZLRS-UHFFFAOYSA-N"

42 0 1 Williamson_ether_synthesis C97101 "JUPGAJLVTBMQRQ-UHFFFAOYSA-N"

42 0 2 Sandmeyer_hydroxylation C97102 "HNBYUYBNKDCFRF-UHFFFAOYSA-N"

 Success  registered route 33!

43 0 0 Haloform_reaction C787 "QNEQWENHQHGYGQ-UHFFFAOYSA-N"

43 0 1 Friedel-Crafts_methylation C97109 "ZDZXNMVLKUYBKX-UHFFFAOYSA-N"

 Success  registered route 34!

44 0 0 Alpha-arylation C507 "IDHQHYZTVBNVEM-UHFFFAOYSA-N"

 Success  registered route 35!

45 0 0 Minisci_reaction_with_carboxylic_acid_(intermolecular) C1260 "IUFZDERRNZKGNV-UHFFFAOYSA-N"

 Success  registered route 36!

47 0 0 Sp3-sp2_Macmillan_coupling_with_bromide_(intermolecular) C605 "CNKKVOAKALIQAJ-UHFFFAOYSA-N"

47 0 1 Stille_coupling C97131 "FOFJMLZESKIAMT-UHFFFAOYSA-N"

47 0 2 Nucleophilic_substitution_with_imine C98025 "WLEPTPWFFYRQSC-UHFFFAOYSA-N"

47 0 3 Pinner_amidine_synthesis_(step_1) C98027 "BUKFVHFHVSPGOL-UHFFFAOYSA-N"

47 0 4 Friedel-Crafts_methylation C98026 "XNOUJDNNPYCEPP-UHFFFAOYSA-N"

47 0 5 Heck_reaction_(intermolecular) C97132 "VCUYAIWJZYGFAW-UHFFFAOYSA-N"

 Success  registered route 37!

48 0 0 Minisci_reaction_with_carboxylic_acid_(intermolecular) C620 "RSGUTJQENBKADA-UHFFFAOYSA-N"

48 0 1 Amidation C97143 "SXPYJJSERIZKPC-UHFFFAOYSA-N"

 Success  registered route 38!

49 0 0 Amidation C1358 "APUVCQGARNVGCS-UHFFFAOYSA-N"

49 0 1 Bartoli_indole_synthesis C97150 "ZCXIMEGDLKVALA-UHFFFAOYSA-N"

49 0 2 Formation_of_Grignard C97152 "CXMWKWGTTZGXQH-UHFFFAOYSA-M"

49 0 3 Williamson_ether_synthesis C97153 "NDLVNWBQYCNHQM-UHFFFAOYSA-N"

 Success  registered route 39!

50 0 0 Ester_amidation C730 "FNLQDVXHDNFXIY-UHFFFAOYSA-N"

 Success  registered route 40!

52 0 0 S-nucleophilic_aromatic_substitution C1145 "ZQJWJBJFKYIAQA-UHFFFAOYSA-N"

52 0 1 Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide C97164 "HXIPVRDWKLWVOD-UHFFFAOYSA-N"

52 0 2 Sandmeyer_bromination C98037 "RUYSRIAINUBOPU-UHFFFAOYSA-N"

52 0 3 Aldehyde/ketone_to_alcohol_reduction C97168 "KTWZSHPMFXPXCN-UHFFFAOYSA-N"

52 0 4 Mannich_reaction C98039 "DJVPQRAHAPGBOU-UHFFFAOYSA-N"

 Success  registered route 41!

53 0 0 Benzylic_deprotonation-alkylation_(pyridine) C1294 "XKWDGMMHYXZUCN-UHFFFAOYSA-N"

 Success  registered route 42!

54 0 0 N-nucleophilic_aromatic_substitution C1111 "OSRDSXBOKMKPSY-UHFFFAOYSA-N"

 Success  registered route 43!

58 0 0 Buchwald-Hartwig_amidation_with_amide-like_nucleophile C3167 "NREZOBUFQPMPJW-UHFFFAOYSA-N"

 Success  registered route 44!

59 0 0 Ester_to_alcohol_reduction_(intermolecular) C3169 "YIZNHWQTEOQSJI-UHFFFAOYSA-N"

59 0 1 Buchwald-Hartwig_(thio)etherification C97180 "UFZCCOVLZDCMCZ-UHFFFAOYSA-N"

59 0 2 Phillips_benzimidazole_condensation_(from_acid_chloride) C98040 "XHTAWEVKJNTVMR-UHFFFAOYSA-N"

 Success  registered route 45!

60 0 0 Ester_to_alcohol_reduction_(intermolecular) C3182 "MNVCHPJTTIQNDF-UHFFFAOYSA-N"

 Success  registered route 46!

62 0 0 Amide_to_amine_reduction C3194 "WFMJSZYQNJOHPI-UHFFFAOYSA-N"

 Success  registered route 47!

63 0 0 Sp3-sp2_Suzuki_coupling C3200 "XUAHHRYFRFINEZ-UHFFFAOYSA-N"

 Success  registered route 48!

64 0 0 Imidazole_C-2_conjugate_addition C3254 "ADFZCUDMTLCMGP-UHFFFAOYSA-N"

64 0 1 Ethenyl_to_formyl C97193 "RAANAHCZQHEMOZ-UHFFFAOYSA-N"

64 0 2 Heck_reaction_(intermolecular) C98043 "QUTQNRBMFBOPTF-UHFFFAOYSA-N"

 Success  registered route 49!

65 0 0 Iodo_N-arylation C3255 "FZRJATGRAXKHCI-UHFFFAOYSA-N"

65 0 1 Sandmeyer_iodination C97196 "FESBKNZQLVXSML-UHFFFAOYSA-N"

 Success  registered route 50!

66 0 0 Nucleophilic_aromatic_substitution_(cyanide) C714 "XFXFHXNZHFMXRC-UHFFFAOYSA-N"

66 0 1 Aromatic_chlorination C1057 "VSLABPNNNJOEGF-UHFFFAOYSA-N"

 Success  registered route 51!

67 0 0 Aromatic_chlorination C1057 "VSLABPNNNJOEGF-UHFFFAOYSA-N"

 Success  registered route 52!

72 0 0 NHK_reaction C3326 "GLHABTWKWNOIDB-UHFFFAOYSA-N"

 Success  registered route 53!

73 0 0 NHK_reaction C3327 "IDCYNCSSGZMFHA-UHFFFAOYSA-N"

 Success  registered route 54!

74 0 0 Amine_alkylation C3329 "HUTXYZBSCSECEI-UHFFFAOYSA-N"

74 0 1 Buchwald-Hartwig_(thio)etherification C97213 "HVHLCTGRICCRDJ-UHFFFAOYSA-N"

 Success  registered route 55!

75 0 0 Petasis-borono_Mannich_reaction C3330 "JALPTGRPJRCTTO-UHFFFAOYSA-N"

 Success  registered route 56!

76 0 0 Aldehyde/ketone_to_alcohol_reduction C92 "FVZQEVNJWREWHU-UHFFFAOYSA-N"

 Success  registered route 57!

77 0 0 NHK_reaction C3333 "ZTBUFBCEPOXSJP-UHFFFAOYSA-N"

77 0 1 Sandmeyer_hydroxylation C97226 "NZURVILCUUARPO-UHFFFAOYSA-N"

77 0 2 Sp3-sp2_Suzuki_coupling C98048 "ACUGSLQMNCAIAG-UHFFFAOYSA-N"

 Success  registered route 58!

78 0 0 Amine_alkylation C3335 "FSUDUNSUPCXSJT-UHFFFAOYSA-N"

78 0 1 Hydrogenation_of_pyridine C97234 "DESKAOZFPKXAPR-UHFFFAOYSA-N"

78 0 2 Minisci_reaction_with_carboxylic_acid_(intermolecular) C98050 "WHDFFHXLSANJPM-UHFFFAOYSA-N"

 Success  registered route 59!

79 0 0 Ester_hydrolysis_(carboxylate_fragment) C3338 "WOXZZJBZVWHGAC-UHFFFAOYSA-N"

79 0 1 Aldol_addition_carbonyl C97240 "PXRJGELLIJHGDB-UHFFFAOYSA-N"

 Success  registered route 60!

80 0 0 NHK_reaction C2986 "KBENTXAFILHOIM-UHFFFAOYSA-N"

 Success  registered route 61!

81 0 0 Grignard_addition_to_carbonyl C3363 "OEQQPOURFDBALJ-UHFFFAOYSA-N"

81 0 1 Ester_amidation C97248 "ASDCNGYRMPHZII-UHFFFAOYSA-N"

 Success  registered route 62!

82 0 0 Formation_of_urea_from_two_amines C1140 "UGGVYPVGSADXJX-UHFFFAOYSA-N"

82 0 1 Aziridine_+_amine_coupling C97254 "BXQQTYGNUSJJGU-UHFFFAOYSA-N"

 Success  registered route 63!

84 0 0 NHK_reaction C3562 "LJDJWLIBMTWRMY-UHFFFAOYSA-N"

 Success  registered route 64!

86 0 0 Amine_alkylation C3698 "VEDVSPPIDXAVBQ-UHFFFAOYSA-N"

86 0 1 Minisci_reaction_with_carboxylic_acid_(intermolecular) C97266 "NPAMJYMNTUNGAT-UHFFFAOYSA-N"

86 0 2 Alpha_alkylation_of_ester/amide C98057 "DZZAJLUONUHNPD-UHFFFAOYSA-N"

86 0 3 Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide C98059 "CJKXLQLNFNTRJU-UHFFFAOYSA-N"

 Success  registered route 65!

87 0 0 Sp2-sp2_Suzuki_coupling C3715 "RFUDZDZLGWTUJE-UHFFFAOYSA-N"

87 0 1 N-nucleophilic_aromatic_substitution C97267 "XHRNJFACWNKIIJ-UHFFFAOYSA-N"

87 0 2 Aromatic_bromination C97269 "BJQNADDSBMWIOV-UHFFFAOYSA-N"

 Success  registered route 66!

88 0 0 S-nucleophilic_aromatic_substitution C3726 "WEHWLKAJVTZUFD-UHFFFAOYSA-N"

88 0 1 Aromatic_iodination C97281 "UWJQTWXIPJRDLU-UHFFFAOYSA-N"

 Success  registered route 67!

89 0 0 Sulfonamide_Schotten-Baumann_with_amine_(intermolecular) C3730 "NGFNKELXAMTNHT-UHFFFAOYSA-N"

89 0 1 Reductive_amination C97288 "ROSPJMVPJLMTJI-UHFFFAOYSA-N"

89 0 2 Vilsmeier-Haack_formylation C98062 "MDIBYZFPKZWGLA-UHFFFAOYSA-N"

 Success  registered route 68!

90 0 0 Formation_of_sulfonamide_from_halide_-_Shavnya_reaction C3731 "UCTZVMKIVANZFW-UHFFFAOYSA-N"

90 0 1 Reductive_amination C97288 "ROSPJMVPJLMTJI-UHFFFAOYSA-N"

90 0 2 Vilsmeier-Haack_formylation C98062 "MDIBYZFPKZWGLA-UHFFFAOYSA-N"

 Success  registered route 69!

93 0 0 Sulfonamide_Schotten-Baumann_with_amine_(intermolecular) C3833 "XRJKXMOAKHZIHH-UHFFFAOYSA-N"

93 0 1 Reductive_amination C97294 "VQPUKWITTJQEOF-UHFFFAOYSA-N"

93 0 2 Vilsmeier-Haack_formylation C98064 "VCRDXDCKARYVFB-UHFFFAOYSA-N"

 Success  registered route 70!

94 0 0 Sulfonamide_Schotten-Baumann_with_amine_(intermolecular) C3838 "ZQRKEFALIPPHPN-UHFFFAOYSA-N"

94 0 1 Reductive_amination C97294 "VQPUKWITTJQEOF-UHFFFAOYSA-N"

94 0 2 Vilsmeier-Haack_formylation C98064 "VCRDXDCKARYVFB-UHFFFAOYSA-N"

 Success  registered route 71!

95 0 0 Formation_of_sulfonamide_from_halide_-_Shavnya_reaction C3839 "PCRFJDYQFBPTTF-UHFFFAOYSA-N"

95 0 1 Reductive_amination C97294 "VQPUKWITTJQEOF-UHFFFAOYSA-N"

95 0 2 Vilsmeier-Haack_formylation C98064 "VCRDXDCKARYVFB-UHFFFAOYSA-N"

 Success  registered route 72!

98 0 0 Sp2-sp2_Suzuki_coupling C3848 "XEZZCURYARAAPP-UHFFFAOYSA-N"

98 0 1 Grignard_addition_to_isocyanate_(intermolecular) C97303 "YJUGIPJQKSLFES-UHFFFAOYSA-N"

98 0 2 Formation_of_Grignard C97306 "WFSDGTONNQLIPY-UHFFFAOYSA-M"

98 0 3 Aromatic_bromination C97286 "BCAYJRHRLIXBHF-UHFFFAOYSA-N"

 Success  registered route 73!

99 0 0 Formation_of_sulfonamide_from_halide_-_Shavnya_reaction C3852 "WNOFTNRAQFWLEH-UHFFFAOYSA-N"

99 0 1 Aromatic_bromination C97316 "AAAVLMOFWQRRBA-UHFFFAOYSA-N"

 Success  registered route 74!

101 0 0 Sp2-sp2_Suzuki_coupling C3937 "LCSVMWAETLBEOW-UHFFFAOYSA-N"

101 0 1 S-nucleophilic_aromatic_substitution C97319 "JDWIWMGWOLCRBQ-UHFFFAOYSA-N"

101 0 2 Aromatic_bromination C97284 "HUOWCRXKJQJTJV-UHFFFAOYSA-N"

 Success  registered route 75!

102 0 0 Buchwald-Hartwig_amination C3938 "RQNQMCFRIMCOFE-UHFFFAOYSA-N"

102 0 1 Aromatic_bromination C97326 "XKIDNYBGRSUVCF-UHFFFAOYSA-N"

102 0 2 Sp2-sp2_Suzuki_coupling C110 "CKVYAEVDVNCGJD-UHFFFAOYSA-N"

 Success  registered route 76!

104 0 0 Haloform_reaction C3986 "ZBZOMXXYZDZQCA-UHFFFAOYSA-N"

104 0 1 Friedel-Crafts_acylation C97330 "HXZMCQWHGIAGGG-UHFFFAOYSA-N"

104 0 2 Friedel-Crafts_methylation C98065 "HGDQHIZQYHAGKI-UHFFFAOYSA-N"

 Success  registered route 77!

105 0 0 S-nucleophilic_aromatic_substitution C2740 "CBCPQDXJTGJQGF-UHFFFAOYSA-N"

105 0 1 Williamson_ether_synthesis C97336 "PKTCRXCBCRNCSE-UHFFFAOYSA-N"

105 0 2 Williamson_ether_synthesis C98067 "NYFSBVVWFAVPAE-UHFFFAOYSA-N"

105 0 3 Buchwald-Hartwig_(thio)etherification C98068 "DPZQQSNBBWXQHC-UHFFFAOYSA-N"

 Success  registered route 78!

106 0 0 Elimination_reaction C3998 "DJALVGSNTLLXML-UHFFFAOYSA-N"

106 0 1 Amine_alkylation C97340 "SCWBDWWAGPMKLM-UHFFFAOYSA-N"

106 0 2 Formation_of_urea_from_two_amines C98071 "RGCDEQWPGWGICU-UHFFFAOYSA-N"

 Success  registered route 79!

107 0 0 Formation_of_sulfonamide_from_halide_-_Shavnya_reaction C4028 "PVIRLSPJORGMSQ-UHFFFAOYSA-N"

107 0 1 Amine_alkylation C97341 "IDZJNFYMYJWKFR-UHFFFAOYSA-N"

 Success  registered route 80!

108 0 0 Sulfonamide_Schotten-Baumann_with_amine_(intermolecular) C4029 "CTWPYFRJQJZSGU-UHFFFAOYSA-N"

108 0 1 Amine_alkylation C97341 "IDZJNFYMYJWKFR-UHFFFAOYSA-N"

 Success  registered route 81!

109 0 0 Sulfonamide_Schotten-Baumann_with_amine_(intermolecular) C4030 "CJTVOFQSMDSAQV-UHFFFAOYSA-N"

109 0 1 Amine_alkylation C97341 "IDZJNFYMYJWKFR-UHFFFAOYSA-N"

 Success  registered route 82!

112 0 0 Buchwald-Hartwig_amidation_with_amide-like_nucleophile C117 "YWAUSXIRKVBYLY-UHFFFAOYSA-N"

 Success  registered route 83!

114 0 0 Formation_of_sulfonamide_from_halide_-_Shavnya_reaction C4129 "ILCMXEZHVXJEPI-UHFFFAOYSA-N"

114 0 1 Buchwald-Hartwig_amidation_with_amide-like_nucleophile C97355 "DNKSPTGECMBGGG-UHFFFAOYSA-N"

114 0 2 Aromatic_iodination C97359 "FWXGHHWKGLBOFT-UHFFFAOYSA-N"

 Success  registered route 84!

115 0 0 Formation_of_sulfonamide_from_halide_-_Shavnya_reaction C4125 "SXDMHWVCSAQMOE-UHFFFAOYSA-N"

115 0 1 Reductive_amination C97360 "JIZZQTVYRBDPAZ-UHFFFAOYSA-N"

115 0 2 Alpha_alkylation_of_aldehyde C98076 "PTZLCMBSWFDABS-UHFFFAOYSA-N"

 Success  registered route 85!

116 0 0 Buchwald-Hartwig_amidation_with_amide-like_nucleophile C4172 "ITBGIXOVWKMXRA-UHFFFAOYSA-N"

116 0 1 Amine_alkylation C97362 "FKGBBHXRRCWXRA-UHFFFAOYSA-N"

 Success  registered route 86!

117 0 0 Reductive_amination C4204 "RLJUVMUBUPLMSW-UHFFFAOYSA-N"

117 0 1 S-nucleophilic_aromatic_substitution C97370 "CNJPHFMOSPJPTR-UHFFFAOYSA-N"

117 0 2 Aromatic_iodination C97372 "SGRMEKDBFXWIQV-UHFFFAOYSA-N"

 Success  registered route 87!

118 0 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C4205 "WQVHMKUZTQFVHV-UHFFFAOYSA-N"

 Warning  SMILES changed during compound registration: NCc1nnc(-c2ccccc2)[nH]1 --> NCc1n[nH]c(-c2ccccc2)n1!

118 0 1 NHK_reaction C97379 "RBGKOXVGQSDIJX-UHFFFAOYSA-N"

118 0 2 Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide C97380 "GBTXMNSRVVYUDE-UHFFFAOYSA-N"

 Success  registered route 88!

119 0 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C4208 "WCQMFAYQSLVMDE-UHFFFAOYSA-N"

 Warning  SMILES changed during compound registration: NCc1nnc(-c2ccccc2)[nH]1 --> NCc1n[nH]c(-c2ccccc2)n1!

119 0 1 NHK_reaction C97386 "JPUXHNRVLKHHDQ-UHFFFAOYSA-N"

119 0 2 Formation_of_sulfonamide_from_halide_-_Shavnya_reaction C97387 "UIVJOUIBLRDFOH-UHFFFAOYSA-N"

 Success  registered route 89!

120 0 0 Amine_alkylation C4215 "GKEIVHGNIDXPLH-UHFFFAOYSA-N"

120 0 1 Amine_alkylation C97390 "KZOCFJJOSKFUDA-UHFFFAOYSA-N"

120 0 2 Sulfonamide_Schotten-Baumann_with_NH_groups_in_aromatic_rings C98082 "CUNNODYJSQIWBJ-UHFFFAOYSA-N"

 Warning  SMILES changed during compound registration: BrCc1nc(-c2ccccc2)n[nH]1 --> BrCc1n[nH]c(-c2ccccc2)n1!

120 0 3 Friedel-Crafts_methylation C97391 "OGRSWFGIIPVAHH-UHFFFAOYSA-N"

120 0 4 Appel_iodination C98084 "DYLPLQQVCAZHIQ-UHFFFAOYSA-N"

 Success  registered route 90!

123 0 0 Amine_alkylation C4238 "OMYBOPMNOHWIDB-UHFFFAOYSA-N"

123 0 1 Sp2-sp2_Suzuki_coupling C97395 "SOQLWMMZODPVOP-UHFFFAOYSA-N"

123 0 2 Buchwald-Hartwig_(thio)etherification C98086 "YFWSLSGNUMVWLA-UHFFFAOYSA-N"

123 0 3 Aromatic_iodination C98088 "RBEHLZIKLMVXCC-UHFFFAOYSA-N"

 Success  registered route 91!

125 0 0 S-nucleophilic_aromatic_substitution C4266 "WRDFEIVUTXUBBU-UHFFFAOYSA-N"

125 0 1 Formation_of_sulfonamide_from_halide_-_Shavnya_reaction C97400 "BBRSIRUSQUCBGT-UHFFFAOYSA-N"

125 0 2 Aromatic_iodination C97359 "FWXGHHWKGLBOFT-UHFFFAOYSA-N"

 Success  registered route 92!

126 0 0 S-nucleophilic_aromatic_substitution C4276 "DEAABERLIYOGSS-UHFFFAOYSA-N"

126 0 1 Aromatic_bromination C97403 "AJMCIFUYCFZIFP-UHFFFAOYSA-N"

 Success  registered route 93!

127 0 0 Chan-Lam_coupling_(amination) C4293 "IWVZQESOJJWOPR-UHFFFAOYSA-N"

127 0 1 N-nucleophilic_aromatic_substitution C97405 "YQBAFMMUDBLKOH-UHFFFAOYSA-N"

127 0 2 Aromatic_iodination C98088 "RBEHLZIKLMVXCC-UHFFFAOYSA-N"

 Success  registered route 94!

129 0 0 Formation_of_sulfonamide_from_halide_-_Shavnya_reaction C4305 "RAWKTIYUUMGONY-UHFFFAOYSA-N"

129 0 1 N-nucleophilic_aromatic_substitution C97417 "BVKPMXLLXHZCFL-UHFFFAOYSA-N"

129 0 2 Aromatic_iodination C97359 "FWXGHHWKGLBOFT-UHFFFAOYSA-N"

 Success  registered route 95!

130 0 0 Buchwald-Hartwig_amidation_with_amide-like_nucleophile C4343 "IELYVEIWJLORIZ-UHFFFAOYSA-N"

130 0 1 Sulfonamide_Schotten-Baumann_with_amine_(intermolecular) C97419 "VNUSOIBTTAHJRI-UHFFFAOYSA-N"

130 0 2 Aromatic_iodination C97359 "FWXGHHWKGLBOFT-UHFFFAOYSA-N"

 Success  registered route 96!

131 0 0 Sulfonamide_Schotten-Baumann_with_amine_(intermolecular) C4345 "VADFIGYFCGXXGU-UHFFFAOYSA-N"

131 0 1 Sp3-sp2_Suzuki_coupling C97427 "XBQNGAQRGYBPRW-UHFFFAOYSA-N"

131 0 2 Buchwald-Hartwig_amidation_with_amide-like_nucleophile C97432 "KBSPKDXQEQHFFX-UHFFFAOYSA-N"

 Success  registered route 97!

133 0 0 Amide_to_amine_reduction C4383 "WBVHPSFFKXXELN-UHFFFAOYSA-N"

133 0 1 Van_Leusen_oxazole_synthesis C97435 "VMSJUHGJOWXVQS-UHFFFAOYSA-N"

133 0 2 Amidation C97440 "GQPPPDHURGTSPN-UHFFFAOYSA-N"

133 0 3 Ester_hydrolysis_(carboxylate_fragment) C98092 "UXLPLDFUOWGKEQ-UHFFFAOYSA-N"

133 0 4 Amidation C98091 "IRBABSOSPYEEOL-UHFFFAOYSA-N"

133 0 5 Formation_of_sulfonamide_from_halide_-_Shavnya_reaction C98094 "SIPTVNWMIRXKON-UHFFFAOYSA-N"

 Success  registered route 98!

134 0 0 N-nucleophilic_aromatic_substitution C4410 "ACYDIHQXUQNKTJ-UHFFFAOYSA-N"

134 0 1 Nucleophilic_substitution_with_imine C97444 "OAARQSQUKNPCNZ-UHFFFAOYSA-N"

134 0 2 Formation_of_sulfonamide_from_halide_-_Shavnya_reaction C97445 "GVBOYAWZGINNNX-UHFFFAOYSA-N"

134 0 3 Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide C98097 "AECSOZPEYLSNGL-UHFFFAOYSA-N"

134 0 4 Nitrile_to_amidine C97446 "MTMBGHOKQVFRTC-UHFFFAOYSA-N"

 Success  registered route 99!

135 0 0 Ester_amidation C4412 "PPXHIRPMLNNBCT-UHFFFAOYSA-N"

135 0 1 Minisci_reaction_with_carboxylic_acid_(intermolecular) C97452 "HWINZBIKDLWRIP-UHFFFAOYSA-N"

135 0 2 N-nucleophilic_aromatic_substitution C97454 "ADGJEVOILUGSOX-UHFFFAOYSA-N"

135 0 3 Mannich_reaction C98101 "RVSBNDKQZLTTEJ-UHFFFAOYSA-N"

135 0 4 Aromatic_chlorination C98102 "KMKINZVUBCHTOI-UHFFFAOYSA-N"

 Success  registered route 100!

137 0 0 Sp2-sp2_Negishi_coupling_(intermolecular) C4458 "UMGAPARYCDRRNG-UHFFFAOYSA-N"

137 0 1 Nucleophilic_substitution_with_imine C97464 "MAYNDBXNSQBLTG-UHFFFAOYSA-N"

137 0 2 N-nucleophilic_aromatic_substitution C97474 "XWHCGRFLNQXJKF-UHFFFAOYSA-N"

137 0 3 Aromatic_bromination C97269 "BJQNADDSBMWIOV-UHFFFAOYSA-N"

137 0 4 N-nucleophilic_aromatic_substitution C97475 "CATMRTBJUFMJJK-UHFFFAOYSA-N"

137 0 5 Nitrile_to_amidine C97446 "MTMBGHOKQVFRTC-UHFFFAOYSA-N"

 Success  registered route 101!

138 0 0 Formation_of_sulfonamide_from_halide_-_Shavnya_reaction C4489 "POUCBJXKPZLTEG-UHFFFAOYSA-N"

138 0 1 Sp3-sp2_Suzuki_coupling C97476 "GGKUEQGNKGMALN-UHFFFAOYSA-N"

138 0 2 Aromatic_iodination C98106 "QWDFIPUUPMXBKQ-UHFFFAOYSA-N"

138 0 3 Formation_of_urea_from_two_amines C126 "JRIYYXNYNZMFKZ-UHFFFAOYSA-N"

 Success  registered route 102!

139 0 0 Formation_of_sulfonamide_from_halide_-_Shavnya_reaction C4495 "VUKNEHXBXKHFEF-UHFFFAOYSA-N"

139 0 1 Sp3-sp2_Suzuki_coupling C97476 "GGKUEQGNKGMALN-UHFFFAOYSA-N"

139 0 2 Aromatic_iodination C98106 "QWDFIPUUPMXBKQ-UHFFFAOYSA-N"

139 0 3 Formation_of_urea_from_two_amines C126 "JRIYYXNYNZMFKZ-UHFFFAOYSA-N"

 Success  registered route 103!

140 0 0 Hydrolysis_of_magnesium_alkylthiolate C4547 "QQWLMGGFHQKROE-UHFFFAOYSA-N"

140 0 1 Synthesis_of_magnesium_alkylthiolate C97489 "BDXPTPLXBNTJFJ-UHFFFAOYSA-N"

140 0 2 Formation_of_Grignard C98107 "GQHIIFOWVCAAGR-UHFFFAOYSA-M"

 Success  registered route 104!

141 0 0 Minisci_reaction_with_carboxylic_acid_(intermolecular) C157 "KDBFWFCMBXFUNH-UHFFFAOYSA-N"

 Success  registered route 105!

142 0 0 Buchwald-Hartwig_amidation_with_amide-like_nucleophile C158 "OALQTJJGTBIUQJ-UHFFFAOYSA-N"

142 0 1 Reductive_amination C97506 "OAYAQAPCGAACBK-UHFFFAOYSA-N"

142 0 2 Formation_of_sulfonamide_from_halide_-_Shavnya_reaction C197 "OBGNNZZOUNWWLM-UHFFFAOYSA-N"

 Success  registered route 106!

144 0 0 Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide C163 "XAAOQRDMNIFOQN-UHFFFAOYSA-N"

 Success  registered route 107!

148 0 0 Formation_of_sulfonamide_from_halide_-_Shavnya_reaction C197 "OBGNNZZOUNWWLM-UHFFFAOYSA-N"

 Success  registered route 108!

150 0 0 N-nucleophilic_aromatic_substitution C239 "CXDLYSMXLHPFPT-UHFFFAOYSA-N"

150 0 1 Imidazole_C-2_alkylation C97525 "TZEXVABBICJQQR-UHFFFAOYSA-N"

150 0 2 Nucleophilic_aromatic_substitution_(alcohol,_phenol,_water) C97527 "XHEHAGWMCVNHEP-UHFFFAOYSA-N"

 Success  registered route 109!

152 0 0 Sp3-sp2_Suzuki_coupling C346 "SSJUKEVLNSCPSU-UHFFFAOYSA-N"

152 0 1 Minisci_reaction_with_carboxylic_acid_(intermolecular) C97531 "BTXHLHDILIHTLT-UHFFFAOYSA-N"

 Success  registered route 110!

153 0 0 Amidation C27587 "OWTVZZFAFKORNP-UHFFFAOYSA-N"

 Success  registered route 111!

154 0 0 Amidation C38140 "RWUKOLGDMALOQO-UHFFFAOYSA-N"

 Success  registered route 112!

155 0 0 Amidation C13421 "HHHNVBZJLAYLQA-UHFFFAOYSA-N"

 Success  registered route 113!

156 0 0 Reductive_amination C12434 "MLRDTHRNFDTJJY-UHFFFAOYSA-N"

 Success  registered route 114!

157 0 0 Reductive_amination C29828 "XWKCECDBYULGHF-UHFFFAOYSA-N"

 Success  registered route 115!

158 0 0 Sp3-sp2_Suzuki_coupling C36757 "ZXFRWGYHBMNIKG-UHFFFAOYSA-N"

 Success  registered route 116!

159 0 0 Amidation C10168 "NTSCIJOQEQIATB-UHFFFAOYSA-N"

 Success  registered route 117!

160 0 0 Steglich_esterification C6030 "VRJHLGYSHOFCDM-UHFFFAOYSA-N"

 Success  registered route 118!

161 0 0 Amidation C15003 "JVTFMYWHXPNHQI-UHFFFAOYSA-N"

 Success  registered route 119!

162 0 0 Amidation C28354 "KQVLYLSRXSWQAR-UHFFFAOYSA-N"

 Success  registered route 120!

163 0 0 N-nucleophilic_aromatic_substitution C14644 "TWMJAZPBFWPAAN-UHFFFAOYSA-N"

 Success  registered route 121!

164 0 0 Amidation C39995 "IMUHSIQXGFCQLZ-UHFFFAOYSA-N"

 Success  registered route 122!

165 0 0 Amidation C24602 "BACMMQHXHKLNBI-UHFFFAOYSA-N"

 Success  registered route 123!

166 0 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C28548 "YLDNMDNNLFJXHA-UHFFFAOYSA-N"

167 0 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C40157 "SGTXZOGNTFYLPW-UHFFFAOYSA-N"

 Success  registered route 125!

168 0 0 Amidation C25561 "AXSSNRVOLIIDNT-UHFFFAOYSA-N"

 Success  registered route 126!

169 0 0 Formation_of_urea_from_two_amines C12064 "HHQSLAHJPDLFCQ-UHFFFAOYSA-N"

 Success  registered route 127!

170 0 0 Amidation C28736 "YPCGPPLGVNMWRB-UHFFFAOYSA-N"

 Success  registered route 128!

171 0 0 Amidation C22874 "WQMXWYLOMDHROI-UHFFFAOYSA-N"

 Success  registered route 129!

172 0 0 Amidation C27867 "DNZBRVOJVZFQMT-UHFFFAOYSA-N"

 Success  registered route 130!

173 0 0 Amidation C15381 "QZHILJCBKXPZQP-UHFFFAOYSA-N"

 Success  registered route 131!

174 0 0 Amidation C27243 "DZWSAAIELUYSMJ-UHFFFAOYSA-N"

 Success  registered route 132!

175 0 0 Amidation C33290 "GOXZBHUQMBZJKD-UHFFFAOYSA-N"

 Success  registered route 133!

176 0 0 Amidation C32037 "XWXITZUCHFLYJU-UHFFFAOYSA-N"

 Success  registered route 134!

177 0 0 Amidation C24504 "LMCRJHYUVLYHJS-UHFFFAOYSA-N"

 Success  registered route 135!

178 0 0 Amidation C33707 "ZNQVUPVHILGFBE-UHFFFAOYSA-N"

 Success  registered route 136!

179 0 0 Amidation C26446 "OIQPXRVFWCSDJK-UHFFFAOYSA-N"

 Success  registered route 137!

180 0 0 N-nucleophilic_aromatic_substitution C14395 "POBLIQQWZCLEBG-UHFFFAOYSA-N"

 Success  registered route 138!

181 0 0 Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide C20147 "JFDUEAZJBLLFTI-UHFFFAOYSA-N"

 Success  registered route 139!

182 0 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C8615 "XKRJXVAYWCSYOF-UHFFFAOYSA-N"

 Success  registered route 140!

183 0 0 Amidation C16691 "QXBJPJAGEYKGFB-UHFFFAOYSA-N"

 Success  registered route 141!

184 0 0 Petasis-borono_Mannich_reaction C25412 "FQGGMTBVNIKLCQ-UHFFFAOYSA-N"

 Success  registered route 142!

185 0 0 Amidation C12873 "PDEDAXUEKHBRAY-UHFFFAOYSA-N"

 Success  registered route 143!

186 0 0 Reductive_amination C5010 "WYZBNBVUTXHZAX-UHFFFAOYSA-N"

 Success  registered route 144!

187 0 0 Amidation C6392 "CAKKAVCBHWACIY-UHFFFAOYSA-N"

 Success  registered route 145!

188 0 0 Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide C29009 "YRMKFHALKIIQFI-UHFFFAOYSA-N"

 Success  registered route 146!

189 0 0 Formation_of_urea_from_two_amines C7931 "KEOQHHKVDKQUHJ-UHFFFAOYSA-N"

 Success  registered route 147!

190 0 0 Amidation C12802 "ZYBCBNXEYXUYED-UHFFFAOYSA-N"

 Success  registered route 148!

191 0 0 Amidation C19520 "GYHUITJVEAWABQ-UHFFFAOYSA-N"

 Success  registered route 149!

192 0 0 Amidation C28536 "CZMPATPIHCNNPE-UHFFFAOYSA-N"

 Success  registered route 150!

193 0 0 Reductive_amination C74593 "FLGWIYRXPJARPG-UHFFFAOYSA-N"

 Success  registered route 151!

194 0 0 Amidation C75727 "YJOSDLXJSAVZAF-UHFFFAOYSA-N"

 Success  registered route 152!

195 0 0 Isocyanate_to_urea C22769 "UNRCOQHGSNLNCV-UHFFFAOYSA-N"

 Success  registered route 153!

196 0 0 Amidation C58294 "HZYHCKDMFITQJT-UHFFFAOYSA-N"

 Success  registered route 154!

197 0 0 Amine_alkylation C75318 "HHXKAULJATZKPA-UHFFFAOYSA-N"

 Success  registered route 155!

198 0 0 Amidation C28399 "GWVSZEBOCYDTBF-UHFFFAOYSA-N"

 Success  registered route 156!

199 0 0 N-nucleophilic_aromatic_substitution C8782 "BMKNKTHZRUDFQF-UHFFFAOYSA-N"

 Success  registered route 157!

200 0 0 Formation_of_urea_from_two_amines C17118 "LADCPSOZUNUHBR-UHFFFAOYSA-N"

 Success  registered route 158!

201 0 0 Amidation C30528 "USRACHNLXBHGCU-UHFFFAOYSA-N"

 Success  registered route 159!

202 0 0 Amidation C30057 "ZKJNTCRRFGCENV-UHFFFAOYSA-N"

202 0 1 Amidation C97652 "OTCILVDBEAFOPP-UHFFFAOYSA-N"

 Success  registered route 160!

203 0 0 Amidation C50965 "CKBWZUAYXMDOCV-UHFFFAOYSA-N"

 Success  registered route 161!

204 0 0 Amidation C10267 "SHPMSFNBTWJEDO-UHFFFAOYSA-N"

 Success  registered route 162!

205 0 0 Petasis-borono_Mannich_reaction C27662 "QNOKDKCXNOEKGL-UHFFFAOYSA-N"

 Success  registered route 163!

206 0 0 NHK_reaction C37765 "HKYKKFNCDPWLTB-UHFFFAOYSA-N"

 Success  registered route 164!

207 0 0 Amidation C6391 "ZYNGLGVMCYSXCP-UHFFFAOYSA-N"

 Success  registered route 165!

208 0 0 Amidation C8130 "JCMJOKGHFJUQBC-UHFFFAOYSA-N"

 Success  registered route 166!

209 0 0 Amidation C39494 "SODFRNXLUTTZQZ-UHFFFAOYSA-N"

 Success  registered route 167!

210 0 0 Reductive_amination C20165 "VECBEHPTGMGLHE-UHFFFAOYSA-N"

 Success  registered route 168!

211 0 0 Amidation C10158 "IPINBGIVFQRAAI-UHFFFAOYSA-N"

 Success  registered route 169!

212 0 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C95401 "JLILQXGIRUVTPA-UHFFFAOYSA-N"

 Success  registered route 170!

213 0 0 Pinner_reaction_(carboxylate_ester) C28397 "HKVXCIZGIFMHFL-UHFFFAOYSA-N"

 Success  registered route 171!

214 0 0 Sp2-sp2_Suzuki_coupling C24299 "HCGXSTZDESADRB-UHFFFAOYSA-N"

 Success  registered route 172!

215 0 0 Formation_of_urea_from_two_amines C28938 "DJKYGOXCJXVGSV-UHFFFAOYSA-N"

 Success  registered route 173!

216 0 0 Amidation C70501 "ZQBFJYVZXVSNPU-UHFFFAOYSA-N"

 Success  registered route 174!

217 0 0 Amidation C6668 "IUWFFCKRUAOHAM-UHFFFAOYSA-N"

 Success  registered route 175!

218 0 0 Amidation C6519 "DCPFSFWYTJNDGE-UHFFFAOYSA-N"

 Success  registered route 176!

219 0 0 Amidation C9337 "ZJQAWOMBIJARFG-UHFFFAOYSA-N"

 Success  registered route 177!

220 0 0 Amidation C90248 "WJHYFXLWJVIYPI-UHFFFAOYSA-N"

 Success  registered route 178!

221 0 0 Amidation C4740 "AEYIOYHTKWTWSL-UHFFFAOYSA-N"

 Success  registered route 179!

222 0 0 Amidation C22085 "GJPSFNOQTCLMQQ-UHFFFAOYSA-N"

 Success  registered route 180!

223 0 0 Formation_of_urea_from_two_amines C33499 "GUOGRLKQAHKULF-UHFFFAOYSA-N"

 Success  registered route 181!

224 0 0 Amidation C5200 "UZAPWJTVILDXAV-UHFFFAOYSA-N"

 Success  registered route 182!

225 0 0 Amidation C8561 "CCGYIEKQNJSWHR-UHFFFAOYSA-N"

 Success  registered route 183!

226 0 0 Amidation C33797 "OLTBLWNFDHBSDA-UHFFFAOYSA-N"

 Success  registered route 184!

227 0 0 Amidation C17133 "XVNUXCQBOAYXJT-UHFFFAOYSA-N"

 Success  registered route 185!

228 0 0 Claisen_condensation_(nitrile) C39468 "PSVYRMZTACVYGH-UHFFFAOYSA-N"

 Success  registered route 186!

229 0 0 Amidation C19986 "IUWQMRRVPYAJSI-UHFFFAOYSA-N"

 Success  registered route 187!

230 0 0 Amine_alkylation C6451 "HORVLCLBPBSEJI-UHFFFAOYSA-N"

 Success  registered route 188!

231 0 0 Amidation C37006 "AFUQERIZGDUNOW-UHFFFAOYSA-N"

 Success  registered route 189!

232 0 0 Reductive_amination C21933 "KVXPRPRHIKRWQK-UHFFFAOYSA-N"

 Success  registered route 190!

233 0 0 Chan-Lam_coupling_of_amides,_sulfonamides,_and_imides C9408 "IMOJQXLXOZLHGE-UHFFFAOYSA-N"

 Success  registered route 191!

234 0 0 Amidation C12821 "STZCBEQONYKHOQ-UHFFFAOYSA-N"

 Success  registered route 192!

235 0 0 1,2,4-Triazole_synthesis_from_carboxylic_acid,_amidine,_and_hydrazine C17100 "DTOYEFDZWGQVIN-UHFFFAOYSA-N"

 Success  registered route 193!

236 0 0 Amidation C65808 "AMTQEHICTHPCOY-UHFFFAOYSA-N"

 Success  registered route 194!

237 0 0 Amidation C60663 "NVMHLWXPBDILNL-UHFFFAOYSA-N"

 Success  registered route 195!

238 0 0 Amidation C64715 "CFLUZAJXXJSKQD-UHFFFAOYSA-N"

 Success  registered route 196!

239 0 0 Amine_alkylation C15259 "JUMOLFANWQYULP-UHFFFAOYSA-N"

 Success  registered route 197!

240 0 0 Amidation C67927 "VSQHCBLGWFINIK-UHFFFAOYSA-N"

 Success  registered route 198!

241 0 0 Steglich_esterification C55917 "IMTKWFPVQAOPKV-UHFFFAOYSA-N"

 Success  registered route 199!

242 0 0 Nucleophilic_substitution_with_thiol C84677 "QPRVTBJLRYLMQX-UHFFFAOYSA-N"

 Success  registered route 200!

243 0 0 Heck_reaction_(intermolecular) C64666 "QLANIMZLODOYJU-UHFFFAOYSA-N"

 Success  registered route 201!

244 0 0 Formation_of_sulfonamide_from_halide_-_Shavnya_reaction C52064 "TWUYPGQORWIICO-UHFFFAOYSA-N"

 Success  registered route 202!

245 0 0 Sp3-sp2_Suzuki_coupling C20704 "CJSMBSPCAQFIGB-UHFFFAOYSA-N"

 Success  registered route 203!

246 0 0 Amidation C56349 "IGBKDKSVCMPWNY-UHFFFAOYSA-N"

 Success  registered route 204!

247 0 0 Amidation C28382 "FFVUVUGMIAXFQL-UHFFFAOYSA-N"

 Success  registered route 205!

248 0 0 Amidation C32354 "VEPAAUANNYSNBE-UHFFFAOYSA-N"

 Success  registered route 206!

249 0 0 Reductive_amination C28379 "VZHJGLWWMHSCBE-UHFFFAOYSA-N"

 Success  registered route 207!

250 0 0 Amidation C63571 "HLRNLSXDCVKTEN-UHFFFAOYSA-N"

 Success  registered route 208!

251 0 0 Amidation C22925 "QZSHTQBMYDQFEM-UHFFFAOYSA-N"

 Success  registered route 209!

252 0 0 Amidation C46293 "JVPFAMUYWOOIGX-UHFFFAOYSA-N"

 Success  registered route 210!

253 0 0 Imine_formation C20035 "VMLWQKURQSPMDX-UHFFFAOYSA-N"

 Success  registered route 211!

254 0 0 Amidation C36373 "MJWUGDOZEHHAGH-UHFFFAOYSA-N"

 Success  registered route 212!

255 0 0 Pinner_reaction_(carboxylate_ester) C65227 "LSBFLPXDYJFKSX-UHFFFAOYSA-N"

 Success  registered route 213!

256 0 0 Reductive_amination C58538 "OUGSTIBRCIEVJE-UHFFFAOYSA-N"

 Success  registered route 214!

257 0 0 Amidation C35558 "INOPOZQFLHAKEA-UHFFFAOYSA-N"

 Success  registered route 215!

258 0 0 Amidation C57354 "VAVNRWQONNXPLK-UHFFFAOYSA-N"

 Success  registered route 216!

259 0 0 Amidation C8797 "VHRDLUIKGGHYOJ-UHFFFAOYSA-N"

 Success  registered route 217!

260 0 0 Amidation C63572 "AXBQOMXKAYOIPL-UHFFFAOYSA-N"

 Success  registered route 218!

261 0 0 Amidation C32774 "VYKRXCKPYISALT-UHFFFAOYSA-N"

 Success  registered route 219!

262 0 0 N-Bn_deprotection C47024 "BLOGGAJNIGIFFQ-UHFFFAOYSA-N"

262 0 1 Amide_to_amine_reduction C97800 "MGDRMHLSUMEJPL-UHFFFAOYSA-N"

 Success  registered route 220!

263 0 0 Grignard_addition_to_carbonyl C62195 "WQHAXWVTINCHDN-UHFFFAOYSA-N"

 Success  registered route 221!

264 0 0 Haloform_reaction C24471 "RDNKLFBMGRSECG-UHFFFAOYSA-N"

 Success  registered route 222!

265 0 0 Amidation C46391 "YGERXUZXZXKXRJ-UHFFFAOYSA-N"

 Success  registered route 223!

266 0 0 Amidation C54771 "MEDHARBJPODMAY-UHFFFAOYSA-N"

 Success  registered route 224!

267 0 0 Amidation C10625 "AHIBHNADHAPWSO-UHFFFAOYSA-N"

 Success  registered route 225!

268 0 0 Amine_alkylation C59879 "VVYLRGQOYCMJKY-UHFFFAOYSA-N"

 Success  registered route 226!

269 0 0 Van_Leusen_imidazole_synthesis C25215 "UAWXRJPBGZDMHL-UHFFFAOYSA-N"

 Success  registered route 227!

270 0 0 Formation_of_sulfonamide_from_boronic_and_amine C51983 "XFTRKDBFUQIIIQ-UHFFFAOYSA-N"

 Success  registered route 228!

271 0 0 Alpha_alkylation_of_ester/amide C23144 "HMJNJSYWGBZZGV-UHFFFAOYSA-N"

 Success  registered route 229!

272 0 0 N-nucleophilic_aromatic_substitution C7644 "CYATXDDGJVSDCH-UHFFFAOYSA-N"

 Success  registered route 230!

273 0 0 Reductive_amination C76789 "HISBRGNRILPBSU-UHFFFAOYSA-N"

 Success  registered route 231!

274 0 0 Amidation C51935 "CFOWWXOXQGPMHY-UHFFFAOYSA-N"

 Success  registered route 232!

275 0 0 Amidation C79165 "NMVRSGFSPAGCSQ-UHFFFAOYSA-N"

 Success  registered route 233!

276 0 0 Amidation C38446 "XSEWTAWPLGARCA-UHFFFAOYSA-N"

 Success  registered route 234!

277 0 0 Amidation C48981 "KANYLPDXMFUDGH-UHFFFAOYSA-N"

 Success  registered route 235!

278 0 0 Formation_of_urea_from_two_amines C56761 "WLZUJRZLYFHANU-UHFFFAOYSA-N"

 Success  registered route 236!

279 0 0 Amidation C22289 "LWJBURPJBDIWHN-UHFFFAOYSA-N"

 Success  registered route 237!

280 0 0 Amidation C73145 "VJMIDHGOZHSEDG-UHFFFAOYSA-N"

 Success  registered route 238!

281 0 0 Amidation C10608 "KPBMRSFRQGKODS-UHFFFAOYSA-N"

 Success  registered route 239!

282 0 0 Sp2-sp2_Suzuki_coupling C48494 "MPSBFLLDTHQKOR-UHFFFAOYSA-N"

 Success  registered route 240!

283 0 0 Reductive_amination C49683 "AYWQGUHSLKGFBJ-UHFFFAOYSA-N"

 Success  registered route 241!

284 0 0 Amidation C76545 "DDTJSGKPKOVDSU-UHFFFAOYSA-N"

 Success  registered route 242!

285 0 0 Amidation C56038 "BOTVXLQCDHVHAJ-UHFFFAOYSA-N"

 Success  registered route 243!

286 0 0 Ester_amidation C60920 "HTMKAMYINHNGAT-UHFFFAOYSA-N"

 Success  registered route 244!

287 0 0 Sp3-sp2_Suzuki_coupling C47435 "HTVHCXWQVWWBFD-UHFFFAOYSA-N"

 Success  registered route 245!

288 0 0 Benzylic_deprotonation-alkylation_(pyridine) C76708 "ZTCUYYQHEBEGRG-UHFFFAOYSA-N"

 Success  registered route 246!

289 0 0 Amidation C38631 "BVEWYMNMZJLUGB-UHFFFAOYSA-N"

 Success  registered route 247!

290 0 0 Reductive_amination C46521 "BVKNSWAVEYMORN-UHFFFAOYSA-N"

 Success  registered route 248!

291 0 0 Amidation C48391 "CUDCWVSGLJETTJ-UHFFFAOYSA-N"

 Success  registered route 249!

292 0 0 Amidation C46386 "HQTWHNXFFFVQTQ-UHFFFAOYSA-N"

 Success  registered route 250!

293 0 0 Ester_amidation C52439 "XEUAQBNZLSUSAG-UHFFFAOYSA-N"

 Success  registered route 251!

294 0 0 Amidation C30056 "HMVFDBKGXTZIQO-UHFFFAOYSA-N"

 Success  registered route 252!

295 0 0 Reductive_amination C22807 "YDILJCHOARNOGJ-UHFFFAOYSA-N"

 Success  registered route 253!

296 0 0 Ester_amidation C60777 "SEJYXQRAUAQKOO-UHFFFAOYSA-N"

 Success  registered route 254!

297 0 0 Alpha_alkylation_of_ester/amide C56757 "HNKCGTWDDZCSAS-UHFFFAOYSA-N"

 Success  registered route 255!

298 0 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C45106 "MZSOXVZAYDDKJP-UHFFFAOYSA-N"

 Success  registered route 256!

299 0 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C47477 "JRFBSFPYJLBLKE-UHFFFAOYSA-N"

 Success  registered route 257!

300 0 0 Amidation C58499 "FHBUSQCSXUMBCH-UHFFFAOYSA-N"

 Success  registered route 258!

301 0 0 Benzimidazole_synthesis_(diamine_+_aldehyde) C59257 "UPVPFNWKHHCIKS-UHFFFAOYSA-N"

 Success  registered route 259!

302 0 0 N-nucleophilic_aromatic_substitution C16736 "PLVVZPFDHLNBFC-UHFFFAOYSA-N"

 Success  registered route 260!

303 0 0 Amidation C30273 "HZSCMLUQIPFLRL-UHFFFAOYSA-N"

 Success  registered route 261!

304 0 0 Formation_of_sulfonamide_from_halide_-_Shavnya_reaction C52888 "GHOZVLCUQHHXPO-UHFFFAOYSA-N"

 Success  registered route 262!

305 0 0 Steglich_esterification C54502 "ZLMPNDQGPYVCLR-UHFFFAOYSA-N"

 Success  registered route 263!

306 0 0 Isocyanate_to_urea C50489 "HLBBAIMXSOMJLL-UHFFFAOYSA-N"

 Success  registered route 264!

307 0 0 Iodo_N-arylation C51861 "CYKWDBWKKGRPJQ-UHFFFAOYSA-N"

 Success  registered route 265!

308 0 0 Amidation C47228 "MIPRSWGTMJTQTA-UHFFFAOYSA-N"

 Success  registered route 266!

309 0 0 Reductive_amination C56667 "GJHIKUSDBDHXNS-UHFFFAOYSA-N"

 Success  registered route 267!

310 0 0 Amidation C9941 "NMGCHAPQFVYQDE-UHFFFAOYSA-N"

 Success  registered route 268!

311 0 0 N-nucleophilic_aromatic_substitution C31678 "ZSCPYEQQTSRAEW-UHFFFAOYSA-N"

 Success  registered route 269!

312 0 0 Amidation C28783 "CFEURGIEXKEWOQ-UHFFFAOYSA-N"

 Success  registered route 270!

313 0 0 Formation_of_urea_from_two_amines C60665 "VFKTYUMVUIBRPG-UHFFFAOYSA-N"

 Success  registered route 271!

314 0 0 Amidation C30265 "XSRXGMUGZYCKQU-UHFFFAOYSA-N"

 Success  registered route 272!

315 0 0 Formation_of_urea_from_two_amines C8896 "DWXFIWMBCQPSKZ-UHFFFAOYSA-N"

 Success  registered route 273!

316 0 0 Amidation C59056 "KXBDVAURFIPJRW-UHFFFAOYSA-N"

 Success  registered route 274!

317 0 0 Amidation C50961 "UGPTYTFYCRAORV-UHFFFAOYSA-N"

 Success  registered route 275!

318 0 0 Amidation C15762 "SAPWDUDYSPXPKC-UHFFFAOYSA-N"

 Success  registered route 276!

319 0 0 Formation_of_urea_from_two_amines C81324 "CDKSOTGZRXMGNQ-UHFFFAOYSA-N"

 Success  registered route 277!

320 0 0 Amidation C84049 "RGGRDGXDORGAOO-UHFFFAOYSA-N"

 Success  registered route 278!

321 0 0 Amidation C59662 "CTROOXARLGSBET-UHFFFAOYSA-N"

 Success  registered route 279!

322 0 0 Amidation C65802 "OKTZSEGXTZJCTM-UHFFFAOYSA-N"

 Success  registered route 280!

323 0 0 Amine_alkylation C30350 "FQRXTCCFXFSOPJ-UHFFFAOYSA-N"

 Success  registered route 281!

324 0 0 Amidation C48399 "UWVOQVCKLYTECW-UHFFFAOYSA-N"

 Success  registered route 282!

325 0 0 Sp2-sp2_Suzuki_coupling C55785 "IVXYRQXNWSBHCM-UHFFFAOYSA-N"

 Success  registered route 283!

326 0 0 Reductive_amination C82192 "ZZQXOQMUWVJTQM-UHFFFAOYSA-N"

 Success  registered route 284!

327 0 0 Amidation C49240 "OQVMECVQLJBPSY-UHFFFAOYSA-N"

 Success  registered route 285!

328 0 0 Amidation C47727 "KBYWMZPGWHLXQB-UHFFFAOYSA-N"

 Success  registered route 286!

329 0 0 Amidation C15320 "BULTUWPSNNDDDR-UHFFFAOYSA-N"

 Success  registered route 287!

330 0 0 Amidation C36756 "LNWLAHSBGZRGGL-UHFFFAOYSA-N"

 Success  registered route 288!

331 0 0 Alpha_alkylation_of_ester/amide C57308 "DTUXGVQWDHQFID-UHFFFAOYSA-N"

 Success  registered route 289!

332 0 0 Amidation C10038 "YMISOSHVSVVEFC-UHFFFAOYSA-N"

 Success  registered route 290!

333 0 0 Formation_of_urea_from_two_amines C7379 "KPSBRSOPAKLMDT-UHFFFAOYSA-N"

 Success  registered route 291!

334 0 0 Amidation C58027 "MGMVXOYBSGBRGY-UHFFFAOYSA-N"

 Success  registered route 292!

335 0 0 Amidation C10619 "AYPZUCGQRPWDNB-UHFFFAOYSA-N"

 Success  registered route 293!

336 0 0 Reductive_amination C55308 "CLFNSDAWADFRPN-UHFFFAOYSA-N"

 Success  registered route 294!

337 0 0 Formation_of_sulfonamide_from_halide_-_Shavnya_reaction C28511 "CRGFPNRSOTUXCK-UHFFFAOYSA-N"

 Success  registered route 295!

338 0 0 Amidation C55202 "XTCCIJDBZXWBCY-UHFFFAOYSA-N"

 Success  registered route 296!

339 0 0 Amidation C46835 "REILJIISVWWDTA-UHFFFAOYSA-N"

 Success  registered route 297!

340 0 0 Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide C49675 "CZHDEAACYDIYOD-UHFFFAOYSA-N"

 Success  registered route 298!

341 0 0 Amidation C35601 "ZYKZERAGYHXJIN-UHFFFAOYSA-N"

 Success  registered route 299!

342 0 0 Amidation C51482 "RZUWUCVWLQVQDU-UHFFFAOYSA-N"

 Success  registered route 300!

343 0 0 Amidation C32763 "HLOXHEMSADMCEB-UHFFFAOYSA-N"

 Success  registered route 301!

344 0 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C63365 "CEDDENXUUINPDU-UHFFFAOYSA-N"

 Success  registered route 302!

,smiles,template,compound_set,hit1,hit2,hit3,hit4,hit5,route0,route0_names,...,route2_CAR,route2_non_CAR,route3,route3_names,route3_CAR,route3_non_CAR,route4,route4_names,route4_CAR,route4_non_CAR
0,OC(=NCCNc1cccc2nc(Cl)oc12)c1ccsc1,7gp3-a,openbind_d68ev3c_c1_scaffolds,7gqr-a,7gp7-a,NaN,NaN,NaN,"[{'name': 'Buchwald-Hartwig_amination', 'react...",[Buchwald-Hartwig_amination],...,True,None,"[{'name': 'Amine_alkylation', 'reactantSmiles'...",[Amine_alkylation],False,[Amine_alkylation],"[{'name': 'Buchwald-Hartwig_amination', 'react...",[Buchwald-Hartwig_amination],True,None
1,NC(c1ccccc1)c1cccc(O)c1,7gp3-a,openbind_d68ev3c_c1_scaffolds,7gqb-a,7gp8-a,NaN,NaN,NaN,"[{'name': 'Petasis-borono_Mannich_reaction', '...",[Petasis-borono_Mannich_reaction],...,False,[Methoxy_to_hydroxy_(aryl)],"[{'name': 'Reductive_amination', 'reactantSmil...",[Reductive_amination],True,None,"[{'name': 'Petasis-borono_Mannich_reaction', '...",[Petasis-borono_Mannich_reaction],False,[Petasis-borono_Mannich_reaction]
2,CCC1C(O)CC(F)C(F)C1C(N)c1ccccc1,7gp3-a,openbind_d68ev3c_c1_scaffolds,7gqb-a,7gpi-a,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NC(c1ccccc1)C1CCCCC12CNC(O)CC2O,7gp3-a,openbind_d68ev3c_c1_scaffolds,7gqb-a,7go7-a,NaN,NaN,NaN,"[{'name': 'Amine_alkylation', 'reactantSmiles'...","[Amine_alkylation, Nitrile_to_amine_(LAH), Ald...",...,False,"[Amine_alkylation, Nitrile_to_amine_(LAH), Ald...","[{'name': 'Amine_alkylation', 'reactantSmiles'...","[Amine_alkylation, Nitrile_to_amine_(LAH), Ald...",False,"[Amine_alkylation, Nitrile_to_amine_(LAH), Ald...","[{'name': 'Amine_alkylation', 'reactantSmiles'...","[Amine_alkylation, Nitrile_to_amine_(LAH), Ald...",False,"[Amine_alkylation, Nitrile_to_amine_(LAH), Ald..."
4,NC(c1ccccc1)c1ccccc1I,7gp3-a,openbind_d68ev3c_c1_scaffolds,7gqb-a,7go4-a,NaN,NaN,NaN,"[{'name': 'Petasis-borono_Mannich_reaction', '...",[Petasis-borono_Mannich_reaction],...,True,None,"[{'name': 'Amine_alkylation', 'reactantSmiles'...",[Amine_alkylation],False,[Amine_alkylation],"[{'name': 'Petasis-borono_Mannich_reaction', '...",[Petasis-borono_Mannich_reaction],False,[Petasis-borono_Mannich_reaction]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
340,c1cc2c(cc1C1CCCNC1)CCCC2,7gq3-a,openbind_d68ev3c_c1_scaffolds,7gpc-a,7gpg-a,NaN,NaN,NaN,[{'name': 'Sp3-sp2_Macmillan_coupling_alcohol_...,[Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_h...,...,False,[Sp3-sp2_Suzuki_coupling],"[{'name': 'Sp3-sp2_Suzuki_coupling', 'reactant...",[Sp3-sp2_Suzuki_coupling],False,[Sp3-sp2_Suzuki_coupling],"[{'name': 'Sp3-sp2_Suzuki_coupling', 'reactant...",[Sp3-sp2_Suzuki_coupling],False,[Sp3-sp2_Suzuki_coupling]
341,CCC(C)C(=O)NCC(=O)N1CCCC(CNC(=O)c2cc[nH]n2)C1,7gq3-a,openbind_d68ev3c_c1_scaffolds,7gpc-a,7gpg-a,NaN,NaN,NaN,"[{'name': 'Amidation', 'reactantSmiles': ['O=C...",[Amidation],...,True,None,"[{'name': 'Alpha_alkylation_of_ester/amide', '...",[Alpha_alkylation_of_ester/amide],True,None,"[{'name': 'Amidation', 'reactantSmiles': ['O=C...","[Amidation, Amidation]",True,None
342,CC(CNC(=O)C12CCC(CC1)O2)NC(=O)Cc1nccn1C,7gq3-a,openbind_d68ev3c_c1_scaffolds,7gpc-a,7gpg-a,NaN,NaN,NaN,"[{'name': 'Amidation', 'reactantSmiles': ['Cn1...",[Amidation],...,True,None,"[{'name': 'Aziridine_+_amine_coupling', 'react...","[Aziridine_+_amine_coupling, Amidation]",False,[Aziridine_+_amine_coupling],"[{'name': 'Ester_amidation', 'reactantSmiles':...",[Ester_amidation],True,None
343,O=C(CCc1ccc2ncsc2c1)N1CCN(c2ncc[nH]2)CC1,7gq3-a,openbind_d68ev3c_c1_scaffolds,7gpc-a,7gpg-a,NaN,NaN,NaN,"[{'name': 'Amidation', 'reactantSmiles': ['c1c...",[Amidation],...,False,[Sp3-sp2_Macmillan_coupling_with_bromide_(inte...,"[{'name': 'Alpha_alkylation_of_ester/amide', '...",[Alpha_alkylation_of_ester/amide],True,None,"[{'name': 'Ester_amidation', 'reactantSmiles':...",[Ester_amidation],True,None
344,CC(CNC1CCNC1=O)NC(=O)c1cccc2cc[nH]c12,7gq3-a,openbind_d68ev3c_c1_scaffolds,7gpc-a,7gpg-a,NaN,NaN,NaN,[{'name': 'Mitsunobu_reaction_with_amine_alcoh...,[Mitsunobu_reaction_with_amine_alcohol_and_thi...,...,False,[Aziridine_+_amine_coupling],"[{'name': 'Amide_to_amine_reduction', 'reactan...","[Amide_to_amine_reduction, Amidation]",False,[Amide_to_amine_reduction],"[{'name': 'Amidation', 'reactantSmiles': ['O=C...",[Amidation],True,None

In [6]:
animal.db.prune_duplicate_routes()

#routes = 302

products with duplicate routes = 0

 Success  No duplicate routes found!

In [8]:
cset = animal.poses(tag="openbind_d68ev3c_c1_scaffolds").compounds
cset.add_tag("openbind_d68ev3c_c1_scaffolds")

Tagged {C × 345} w/ "openbind_d68ev3c_c1_scaffolds"

In [9]:
recipe = hippo.Recipe.from_compounds(cset, use_routes=True, pick_cheapest=False, pick_first=True)

#compounds = 345

Output()

 ERROR  No routes to C158 "OALQTJJGTBIUQJ-UHFFFAOYSA-N"!

 ERROR  No routes to C159 "ZDQDZRHGVOSIRW-UHFFFAOYSA-N"!

 ERROR  No routes to C164 "OCGRGNJVXOAUJK-UHFFFAOYSA-N"!

 ERROR  No routes to C170 "QIDOCGRTYZUKQH-UHFFFAOYSA-N"!

 ERROR  No routes to C181 "UUMMUIZAOWDWTD-UHFFFAOYSA-N"!

 Warning  Multiple solutions for compound=C197!

 ERROR  No routes to C207 "ULHMPWPKRSVYDD-UHFFFAOYSA-N"!

 ERROR  No routes to C226 "ZIFVEAFJKKVTCL-UHFFFAOYSA-N"!

 ERROR  No routes to C239 "CXDLYSMXLHPFPT-UHFFFAOYSA-N"!

 ERROR  No routes to C243 "GINQBQFQOUDQDN-UHFFFAOYSA-N"!

 ERROR  No routes to C346 "SSJUKEVLNSCPSU-UHFFFAOYSA-N"!

 ERROR  No routes to C395 "FKWDUSSUZVTDPB-UHFFFAOYSA-N"!

 ERROR  No routes to C438 "TTWHSXRVHZJZCJ-UHFFFAOYSA-N"!

 ERROR  No routes to C439 "DKBJQVKSNYTRLC-UHFFFAOYSA-N"!

 ERROR  No routes to C528 "KPPATRVOAXYCOE-UHFFFAOYSA-N"!

 ERROR  No routes to C587 "VDIVYEFHRIKYRC-UHFFFAOYSA-N"!

 ERROR  No routes to C604 "WFENYVKBPQAOOK-UHFFFAOYSA-N"!

 ERROR  No routes to C605 "CNKKVOAKALIQAJ-UHFFFAOYSA-N"!

 ERROR  No routes to C620 "RSGUTJQENBKADA-UHFFFAOYSA-N"!

 ERROR  No routes to C629 "FXZBYDNKISGMQQ-UHFFFAOYSA-N"!

 ERROR  No routes to C641 "DPNQQQYQPPIZRC-UHFFFAOYSA-N"!

 ERROR  No routes to C654 "DWFJIPQLUTZMIQ-UHFFFAOYSA-N"!

 ERROR  No routes to C666 "CSOZCVMTTZZLRS-UHFFFAOYSA-N"!

 ERROR  No routes to C714 "XFXFHXNZHFMXRC-UHFFFAOYSA-N"!

 ERROR  No routes to C729 "FPOIQVPBSOEHCW-UHFFFAOYSA-N"!

 ERROR  No routes to C754 "IMUHHYAGOXNMDH-UHFFFAOYSA-N"!

 ERROR  No routes to C787 "QNEQWENHQHGYGQ-UHFFFAOYSA-N"!

 ERROR  No routes to C841 "ZGSHRYFGYGGLDJ-UHFFFAOYSA-N"!

 ERROR  No routes to C1026 "IZTDAONZCDDUEY-UHFFFAOYSA-N"!

 Warning  Multiple solutions for compound=C1057!

 ERROR  No routes to C1065 "QPFMOOAXWTYAJX-UHFFFAOYSA-N"!

 ERROR  No routes to C1120 "DHTQYGHLOPXGFU-UHFFFAOYSA-N"!

 ERROR  No routes to C1140 "UGGVYPVGSADXJX-UHFFFAOYSA-N"!

 ERROR  No routes to C1145 "ZQJWJBJFKYIAQA-UHFFFAOYSA-N"!

 ERROR  No routes to C1330 "WOGARWOKNORZLW-UHFFFAOYSA-N"!

 ERROR  No routes to C1358 "APUVCQGARNVGCS-UHFFFAOYSA-N"!

 ERROR  No routes to C1413 "VMPNWKROZBMPNO-UHFFFAOYSA-N"!

 ERROR  No routes to C1415 "SAQAVPRVQJBJCH-UHFFFAOYSA-N"!

 ERROR  No routes to C1550 "YPEANAMPJRKIQM-UHFFFAOYSA-N"!

 ERROR  No routes to C1552 "OXBOUCQJOFCRFX-UHFFFAOYSA-N"!

 ERROR  No routes to C1560 "BVXKUVCDXHJECV-UHFFFAOYSA-N"!

 ERROR  No routes to C1624 "VARLVDFTNYDJMC-UHFFFAOYSA-N"!

 ERROR  No routes to C1632 "MFUIOSQSBPZWTL-UHFFFAOYSA-N"!

 ERROR  No routes to C1676 "KZJYGOFBWIXLCF-UHFFFAOYSA-N"!

 ERROR  No routes to C1778 "KPKNZFDDSLALLN-UHFFFAOYSA-N"!

 ERROR  No routes to C1780 "CGBRBSYAYWOUQG-UHFFFAOYSA-N"!

 ERROR  No routes to C2740 "CBCPQDXJTGJQGF-UHFFFAOYSA-N"!

 ERROR  No routes to C2984 "ZXGDWYDKENXYKW-UHFFFAOYSA-N"!

 ERROR  No routes to C3094 "OPFJSUYURHLHHI-UHFFFAOYSA-N"!

 ERROR  No routes to C3101 "GJMHTIANTOHAPN-UHFFFAOYSA-N"!

 ERROR  No routes to C3113 "PNVWLQBJDBHDMC-UHFFFAOYSA-N"!

 ERROR  No routes to C3169 "YIZNHWQTEOQSJI-UHFFFAOYSA-N"!

 ERROR  No routes to C3254 "ADFZCUDMTLCMGP-UHFFFAOYSA-N"!

 ERROR  No routes to C3255 "FZRJATGRAXKHCI-UHFFFAOYSA-N"!

 ERROR  No routes to C3272 "UGUAILAXRAZYQR-UHFFFAOYSA-N"!

 ERROR  No routes to C3278 "HCXAWXRVDIHUCW-UHFFFAOYSA-N"!

 ERROR  No routes to C3279 "GOCYIWAPQIBLGD-UHFFFAOYSA-N"!

 ERROR  No routes to C3290 "GMTQMXAHSAWPFE-UHFFFAOYSA-N"!

 ERROR  No routes to C3316 "HHKGRDDYWWYCKB-UHFFFAOYSA-N"!

 ERROR  No routes to C3329 "HUTXYZBSCSECEI-UHFFFAOYSA-N"!

 ERROR  No routes to C3333 "ZTBUFBCEPOXSJP-UHFFFAOYSA-N"!

 ERROR  No routes to C3335 "FSUDUNSUPCXSJT-UHFFFAOYSA-N"!

 ERROR  No routes to C3338 "WOXZZJBZVWHGAC-UHFFFAOYSA-N"!

 ERROR  No routes to C3363 "OEQQPOURFDBALJ-UHFFFAOYSA-N"!

 ERROR  No routes to C3530 "QGEIOIIYGMZVIM-UHFFFAOYSA-N"!

 ERROR  No routes to C3689 "KGPMGOMPDIDNHP-UHFFFAOYSA-N"!

 ERROR  No routes to C3698 "VEDVSPPIDXAVBQ-UHFFFAOYSA-N"!

 ERROR  No routes to C3715 "RFUDZDZLGWTUJE-UHFFFAOYSA-N"!

 ERROR  No routes to C3726 "WEHWLKAJVTZUFD-UHFFFAOYSA-N"!

 ERROR  No routes to C3730 "NGFNKELXAMTNHT-UHFFFAOYSA-N"!

 ERROR  No routes to C3731 "UCTZVMKIVANZFW-UHFFFAOYSA-N"!

 ERROR  No routes to C3771 "FPPIZHXQRJINDQ-UHFFFAOYSA-N"!

 ERROR  No routes to C3774 "MBOQPCNPJLMJSB-UHFFFAOYSA-N"!

 ERROR  No routes to C3809 "HRODOPFFJAXBLJ-UHFFFAOYSA-N"!

 ERROR  No routes to C3833 "XRJKXMOAKHZIHH-UHFFFAOYSA-N"!

 ERROR  No routes to C3838 "ZQRKEFALIPPHPN-UHFFFAOYSA-N"!

 ERROR  No routes to C3839 "PCRFJDYQFBPTTF-UHFFFAOYSA-N"!

 ERROR  No routes to C3842 "HFIRPCZXCMKVSI-UHFFFAOYSA-N"!

 ERROR  No routes to C3848 "XEZZCURYARAAPP-UHFFFAOYSA-N"!

 ERROR  No routes to C3852 "WNOFTNRAQFWLEH-UHFFFAOYSA-N"!

 ERROR  No routes to C3909 "JLQGQAAXENSHAE-UHFFFAOYSA-N"!

 ERROR  No routes to C3937 "LCSVMWAETLBEOW-UHFFFAOYSA-N"!

 ERROR  No routes to C3938 "RQNQMCFRIMCOFE-UHFFFAOYSA-N"!

 ERROR  No routes to C3986 "ZBZOMXXYZDZQCA-UHFFFAOYSA-N"!

 ERROR  No routes to C3998 "DJALVGSNTLLXML-UHFFFAOYSA-N"!

 ERROR  No routes to C4028 "PVIRLSPJORGMSQ-UHFFFAOYSA-N"!

 ERROR  No routes to C4029 "CTWPYFRJQJZSGU-UHFFFAOYSA-N"!

 ERROR  No routes to C4030 "CJTVOFQSMDSAQV-UHFFFAOYSA-N"!

 ERROR  No routes to C4103 "YTUMQXHFIOZXPN-UHFFFAOYSA-N"!

 ERROR  No routes to C4112 "IUYPQQXTGKMMMW-UHFFFAOYSA-N"!

 ERROR  No routes to C4119 "MJVQYZUVOMAMAA-UHFFFAOYSA-N"!

 ERROR  No routes to C4125 "SXDMHWVCSAQMOE-UHFFFAOYSA-N"!

 ERROR  No routes to C4129 "ILCMXEZHVXJEPI-UHFFFAOYSA-N"!

 ERROR  No routes to C4172 "ITBGIXOVWKMXRA-UHFFFAOYSA-N"!

 ERROR  No routes to C4204 "RLJUVMUBUPLMSW-UHFFFAOYSA-N"!

 ERROR  No routes to C4205 "WQVHMKUZTQFVHV-UHFFFAOYSA-N"!

 ERROR  No routes to C4208 "WCQMFAYQSLVMDE-UHFFFAOYSA-N"!

 ERROR  No routes to C4215 "GKEIVHGNIDXPLH-UHFFFAOYSA-N"!

 ERROR  No routes to C4230 "UBFRGARCRUFNQH-UHFFFAOYSA-N"!

 ERROR  No routes to C4236 "YWUZODYUFNQTET-UHFFFAOYSA-N"!

 ERROR  No routes to C4238 "OMYBOPMNOHWIDB-UHFFFAOYSA-N"!

 ERROR  No routes to C4257 "MVGWYBLLPKQETD-UHFFFAOYSA-N"!

 ERROR  No routes to C4266 "WRDFEIVUTXUBBU-UHFFFAOYSA-N"!

 ERROR  No routes to C4276 "DEAABERLIYOGSS-UHFFFAOYSA-N"!

 ERROR  No routes to C4293 "IWVZQESOJJWOPR-UHFFFAOYSA-N"!

 ERROR  No routes to C4297 "MYBRTELVIPBTHT-UHFFFAOYSA-N"!

 ERROR  No routes to C4305 "RAWKTIYUUMGONY-UHFFFAOYSA-N"!

 ERROR  No routes to C4328 "XARZUABJGNNAIR-UHFFFAOYSA-N"!

 ERROR  No routes to C4343 "IELYVEIWJLORIZ-UHFFFAOYSA-N"!

 ERROR  No routes to C4345 "VADFIGYFCGXXGU-UHFFFAOYSA-N"!

 ERROR  No routes to C4383 "WBVHPSFFKXXELN-UHFFFAOYSA-N"!

 ERROR  No routes to C4410 "ACYDIHQXUQNKTJ-UHFFFAOYSA-N"!

 ERROR  No routes to C4412 "PPXHIRPMLNNBCT-UHFFFAOYSA-N"!

 ERROR  No routes to C4446 "HCVUBEHKWLZQLZ-UHFFFAOYSA-N"!

 ERROR  No routes to C4458 "UMGAPARYCDRRNG-UHFFFAOYSA-N"!

 ERROR  No routes to C4489 "POUCBJXKPZLTEG-UHFFFAOYSA-N"!

 ERROR  No routes to C4495 "VUKNEHXBXKHFEF-UHFFFAOYSA-N"!

 ERROR  No routes to C4547 "QQWLMGGFHQKROE-UHFFFAOYSA-N"!

 ERROR  No routes to C30057 "ZKJNTCRRFGCENV-UHFFFAOYSA-N"!

 ERROR  No routes to C47024 "BLOGGAJNIGIFFQ-UHFFFAOYSA-N"!

Solving recipe combinations...

Output()

In [10]:
recipe.write_json("cycle_01/syndirella/retrosynthesis/openbind_d68ev3c_c1_scaffolds.json")

 Warning  NULL Quote: 1.00mg of C97224!

 Warning  NULL Quote: 1.00mg of C97034!

 Warning  NULL Quote: 1.00mg of C97354!

 Warning  NULL Quote: 1.00mg of C97496!

 Warning  NULL Quote: 1.00mg of C97497!

 Warning  NULL Quote: 1.00mg of C97516!

 Warning  NULL Quote: 1.00mg of C97517!

 Warning  NULL Quote: 1.00mg of C167!

 Warning  NULL Quote: 1.00mg of C197!

 Warning  NULL Quote: 1.00mg of C97506!

 Warning  NULL Quote: 1.00mg of C97507!

 Warning  NULL Quote: 1.00mg of C97508!

 Warning  NULL Quote: 1.00mg of C97509!

 Warning  NULL Quote: 1.00mg of C97038!

 Warning  NULL Quote: 1.00mg of C97039!

 Warning  NULL Quote: 1.00mg of C97064!

 Warning  NULL Quote: 1.00mg of C97065!

 Warning  NULL Quote: 1.00mg of C97112!

 Warning  NULL Quote: 1.00mg of C97113!

 Warning  NULL Quote: 1.00mg of C97079!

 Warning  NULL Quote: 1.00mg of C97080!

 Warning  NULL Quote: 6.00mg of C96983!

 Warning  NULL Quote: 1.00mg of C97163!

 Warning  NULL Quote: 1.00mg of C97085!

 Warning  NULL Quote: 1.00mg of C97086!

 Warning  NULL Quote: 1.00mg of C88!

 Warning  NULL Quote: 1.00mg of C1057!

 Warning  NULL Quote: 1.00mg of C97177!

 Warning  NULL Quote: 1.00mg of C97178!

 Warning  NULL Quote: 1.00mg of C97121!

 Warning  NULL Quote: 1.00mg of C97122!

 Warning  NULL Quote: 1.00mg of C97170!

 Warning  NULL Quote: 1.00mg of C97171!

 Warning  NULL Quote: 1.00mg of C96979!

 Warning  NULL Quote: 1.00mg of C96980!

 Warning  NULL Quote: 2.00mg of C96981!

 Warning  NULL Quote: 1.00mg of C96982!

 Warning  NULL Quote: 1.00mg of C96990!

 Warning  NULL Quote: 1.00mg of C96993!

 Warning  NULL Quote: 1.00mg of C1445!

 Warning  NULL Quote: 1.00mg of C96994!

 Warning  NULL Quote: 3.00mg of C96996!

 Warning  NULL Quote: 1.00mg of C96997!

 Warning  NULL Quote: 1.00mg of C96999!

 Warning  NULL Quote: 1.00mg of C97001!

 Warning  NULL Quote: 1.00mg of C97007!

 Warning  NULL Quote: 1.00mg of C97008!

 Warning  NULL Quote: 1.00mg of C97009!

 Warning  NULL Quote: 1.00mg of C97010!

 Warning  NULL Quote: 1.00mg of C97012!

 Warning  NULL Quote: 1.00mg of C97013!

 Warning  NULL Quote: 1.00mg of C97016!

 Warning  NULL Quote: 1.00mg of C97017!

 Warning  NULL Quote: 6.00mg of C97208!

 Warning  NULL Quote: 1.00mg of C97246!

 Warning  NULL Quote: 1.00mg of C97144!

 Warning  NULL Quote: 1.00mg of C97179!

 Warning  NULL Quote: 1.00mg of C97185!

 Warning  NULL Quote: 1.00mg of C97187!

 Warning  NULL Quote: 1.00mg of C97190!

 Warning  NULL Quote: 1.00mg of C97191!

 Warning  NULL Quote: 1.00mg of C97207!

 Warning  NULL Quote: 1.00mg of C97210!

 Warning  NULL Quote: 1.00mg of C97216!

 Warning  NULL Quote: 1.00mg of C97217!

 Warning  NULL Quote: 1.00mg of C97218!

 Warning  NULL Quote: 1.00mg of C97262!

 Warning  NULL Quote: 2.00mg of C97673!

 Warning  NULL Quote: 1.00mg of C97692!

 Warning  NULL Quote: 1.00mg of C97612!

 Warning  NULL Quote: 1.00mg of C97613!

 Warning  NULL Quote: 2.00mg of C97569!

 Warning  NULL Quote: 1.00mg of C97696!

 Warning  NULL Quote: 1.00mg of C97554!

 Warning  NULL Quote: 1.00mg of C97555!

 Warning  NULL Quote: 1.00mg of C97665!

 Warning  NULL Quote: 1.00mg of C97666!

 Warning  NULL Quote: 1.00mg of C97614!

 Warning  NULL Quote: 1.00mg of C97615!

 Warning  NULL Quote: 2.00mg of C97634!

 Warning  NULL Quote: 1.00mg of C97709!

 Warning  NULL Quote: 3.00mg of C97674!

 Warning  NULL Quote: 1.00mg of C97687!

 Warning  NULL Quote: 3.00mg of C97579!

 Warning  NULL Quote: 1.00mg of C97686!

 Warning  NULL Quote: 2.00mg of C97945!

 Warning  NULL Quote: 1.00mg of C97962!

 Warning  NULL Quote: 1.00mg of C97837!

 Warning  NULL Quote: 1.00mg of C97838!

 Warning  NULL Quote: 1.00mg of C6362!

 Warning  NULL Quote: 1.00mg of C97625!

 Warning  NULL Quote: 1.00mg of C97667!

 Warning  NULL Quote: 1.00mg of C97668!

 Warning  NULL Quote: 1.00mg of C97697!

 Warning  NULL Quote: 1.00mg of C97602!

 Warning  NULL Quote: 1.00mg of C97603!

 Warning  NULL Quote: 1.00mg of C97647!

 Warning  NULL Quote: 2.00mg of C97648!

 Warning  NULL Quote: 1.00mg of C97794!

 Warning  NULL Quote: 1.00mg of C97795!

 Warning  NULL Quote: 1.00mg of C97928!

 Warning  NULL Quote: 1.00mg of C97929!

 Warning  NULL Quote: 2.00mg of C97688!

 Warning  NULL Quote: 1.00mg of C97689!

 Warning  NULL Quote: 1.00mg of C97720!

 Warning  NULL Quote: 1.00mg of C97721!

 Warning  NULL Quote: 1.00mg of C97921!

 Warning  NULL Quote: 1.00mg of C97922!

 Warning  NULL Quote: 1.00mg of C97961!

 Warning  NULL Quote: 1.00mg of C97552!

 Warning  NULL Quote: 1.00mg of C97553!

 Warning  NULL Quote: 1.00mg of C94916!

 Warning  NULL Quote: 1.00mg of C97656!

 Warning  NULL Quote: 2.00mg of C97573!

 Warning  NULL Quote: 1.00mg of C97852!

 Warning  NULL Quote: 1.00mg of C97965!

 Warning  NULL Quote: 1.00mg of C97966!

 Warning  NULL Quote: 8.00mg of C97655!

 Warning  NULL Quote: 1.00mg of C97817!

 Warning  NULL Quote: 1.00mg of C97571!

 Warning  NULL Quote: 1.00mg of C97572!

 Warning  NULL Quote: 1.00mg of C97546!

 Warning  NULL Quote: 1.00mg of C97547!

 Warning  NULL Quote: 1.00mg of C97626!

 Warning  NULL Quote: 1.00mg of C97627!

 Warning  NULL Quote: 1.00mg of C97724!

 Warning  NULL Quote: 1.00mg of C97725!

 Warning  NULL Quote: 1.00mg of C97610!

 Warning  NULL Quote: 1.00mg of C97611!

 Warning  NULL Quote: 1.00mg of C97544!

 Warning  NULL Quote: 1.00mg of C97545!

 Warning  NULL Quote: 1.00mg of C97592!

 Warning  NULL Quote: 1.00mg of C97593!

 Warning  NULL Quote: 1.00mg of C14572!

 Warning  NULL Quote: 1.00mg of C97560!

 Warning  NULL Quote: 1.00mg of C97556!

 Warning  NULL Quote: 1.00mg of C97557!

 Warning  NULL Quote: 1.00mg of C97739!

 Warning  NULL Quote: 1.00mg of C97740!

 Warning  NULL Quote: 2.00mg of C97637!

 Warning  NULL Quote: 1.00mg of C97953!

 Warning  NULL Quote: 1.00mg of C97580!

 Warning  NULL Quote: 1.00mg of C97932!

 Warning  NULL Quote: 1.00mg of C97933!

 Warning  NULL Quote: 1.00mg of C97604!

 Warning  NULL Quote: 1.00mg of C97605!

 Warning  NULL Quote: 1.00mg of C4934!

 Warning  NULL Quote: 1.00mg of C97726!

 Warning  NULL Quote: 1.00mg of C97727!

 Warning  NULL Quote: 1.00mg of C97728!

 Warning  NULL Quote: 2.00mg of C97562!

 Warning  NULL Quote: 1.00mg of C97649!

 Warning  NULL Quote: 1.00mg of C97700!

 Warning  NULL Quote: 1.00mg of C97628!

 Warning  NULL Quote: 1.00mg of C97629!

 Warning  NULL Quote: 1.00mg of C97707!

 Warning  NULL Quote: 1.00mg of C97708!

 Warning  NULL Quote: 1.00mg of C97780!

 Warning  NULL Quote: 1.00mg of C97781!

 Warning  NULL Quote: 1.00mg of C97594!

 Warning  NULL Quote: 1.00mg of C97595!

 Warning  NULL Quote: 1.00mg of C97671!

 Warning  NULL Quote: 1.00mg of C97672!

 Warning  NULL Quote: 1.00mg of C97765!

 Warning  NULL Quote: 1.00mg of C97766!

 Warning  NULL Quote: 1.00mg of C97718!

 Warning  NULL Quote: 1.00mg of C97719!

 Warning  NULL Quote: 1.00mg of C97693!

 Warning  NULL Quote: 1.00mg of C97694!

 Warning  NULL Quote: 1.00mg of C97849!

 Warning  NULL Quote: 1.00mg of C97850!

 Warning  NULL Quote: 1.00mg of C43156!

 Warning  NULL Quote: 1.00mg of C97635!

 Warning  NULL Quote: 1.00mg of C97883!

 Warning  NULL Quote: 1.00mg of C97884!

 Warning  NULL Quote: 1.00mg of C97575!

 Warning  NULL Quote: 1.00mg of C97576!

 Warning  NULL Quote: 1.00mg of C97776!

 Warning  NULL Quote: 1.00mg of C97777!

 Warning  NULL Quote: 1.00mg of C97597!

 Warning  NULL Quote: 1.00mg of C97833!

 Warning  NULL Quote: 1.00mg of C97680!

 Warning  NULL Quote: 1.00mg of C97681!

 Warning  NULL Quote: 2.00mg of C97677!

 Warning  NULL Quote: 1.00mg of C97810!

 Warning  NULL Quote: 1.00mg of C97586!

 Warning  NULL Quote: 1.00mg of C97587!

 Warning  NULL Quote: 1.00mg of C97563!

 Warning  NULL Quote: 1.00mg of C97564!

 Warning  NULL Quote: 1.00mg of C97823!

 Warning  NULL Quote: 1.00mg of C97824!

 Warning  NULL Quote: 1.00mg of C97126!

 Warning  NULL Quote: 1.00mg of C97606!

 Warning  NULL Quote: 1.00mg of C97607!

 Warning  NULL Quote: 1.00mg of C97570!

 Warning  NULL Quote: 1.00mg of C97590!

 Warning  NULL Quote: 2.00mg of C97591!

 Warning  NULL Quote: 1.00mg of C97581!

 Warning  NULL Quote: 1.00mg of C97582!

 Warning  NULL Quote: 1.00mg of C97541!

 Warning  NULL Quote: 1.00mg of C97542!

 Warning  NULL Quote: 1.00mg of C97657!

 Warning  NULL Quote: 1.00mg of C97658!

 Warning  NULL Quote: 1.00mg of C97577!

 Warning  NULL Quote: 1.00mg of C97578!

 Warning  NULL Quote: 1.00mg of C97558!

 Warning  NULL Quote: 1.00mg of C97559!

 Warning  NULL Quote: 1.00mg of C97772!

 Warning  NULL Quote: 1.00mg of C97773!

 Warning  NULL Quote: 3.00mg of C97645!

 Warning  NULL Quote: 1.00mg of C97769!

 Warning  NULL Quote: 2.00mg of C97678!

 Warning  NULL Quote: 1.00mg of C97646!

 Warning  NULL Quote: 1.00mg of C97969!

 Warning  NULL Quote: 1.00mg of C97970!

 Warning  NULL Quote: 1.00mg of C97630!

 Warning  NULL Quote: 1.00mg of C97631!

 Warning  NULL Quote: 1.00mg of C97565!

 Warning  NULL Quote: 1.00mg of C97566!

 Warning  NULL Quote: 1.00mg of C97574!

 Warning  NULL Quote: 1.00mg of C97923!

 Warning  NULL Quote: 1.00mg of C97924!

 Warning  NULL Quote: 1.00mg of C97682!

 Warning  NULL Quote: 1.00mg of C97683!

 Warning  NULL Quote: 1.00mg of C97222!

 Warning  NULL Quote: 1.00mg of C97616!

 Warning  NULL Quote: 1.00mg of C97548!

 Warning  NULL Quote: 2.00mg of C97549!

 Warning  NULL Quote: 1.00mg of C97881!

 Warning  NULL Quote: 1.00mg of C97882!

 Warning  NULL Quote: 1.00mg of C97926!

 Warning  NULL Quote: 1.00mg of C97927!

 Warning  NULL Quote: 1.00mg of C97902!

 Warning  NULL Quote: 1.00mg of C15307!

 Warning  NULL Quote: 1.00mg of C97941!

 Warning  NULL Quote: 1.00mg of C97650!

 Warning  NULL Quote: 2.00mg of C97651!

 Warning  NULL Quote: 1.00mg of C17719!

 Warning  NULL Quote: 1.00mg of C97732!

 Warning  NULL Quote: 1.00mg of C26471!

 Warning  NULL Quote: 1.00mg of C97585!

 Warning  NULL Quote: 1.00mg of C97770!

 Warning  NULL Quote: 1.00mg of C97771!

 Warning  NULL Quote: 1.00mg of C49444!

 Warning  NULL Quote: 1.00mg of C97985!

 Warning  NULL Quote: 1.00mg of C97798!

 Warning  NULL Quote: 1.00mg of C97799!

 Warning  NULL Quote: 1.00mg of C97583!

 Warning  NULL Quote: 1.00mg of C97584!

 Warning  NULL Quote: 1.00mg of C5865!

 Warning  NULL Quote: 1.00mg of C97695!

 Warning  NULL Quote: 1.00mg of C97588!

 Warning  NULL Quote: 1.00mg of C97589!

 Warning  NULL Quote: 1.00mg of C97698!

 Warning  NULL Quote: 1.00mg of C97699!

 Warning  NULL Quote: 1.00mg of C97790!

 Warning  NULL Quote: 1.00mg of C97791!

 Warning  NULL Quote: 1.00mg of C97981!

 Warning  NULL Quote: 1.00mg of C97982!

 Warning  NULL Quote: 1.00mg of C97786!

 Warning  NULL Quote: 1.00mg of C97954!

 Warning  NULL Quote: 1.00mg of C97550!

 Warning  NULL Quote: 1.00mg of C97551!

 Warning  NULL Quote: 1.00mg of C97717!

 Warning  NULL Quote: 1.00mg of C97660!

 Warning  NULL Quote: 1.00mg of C38115!

 Warning  NULL Quote: 1.00mg of C97543!

 Warning  NULL Quote: 1.00mg of C97845!

 Warning  NULL Quote: 1.00mg of C97872!

 Warning  NULL Quote: 1.00mg of C97873!

 Warning  NULL Quote: 1.00mg of C97701!

 Warning  NULL Quote: 1.00mg of C97702!

 Warning  NULL Quote: 1.00mg of C97669!

 Warning  NULL Quote: 1.00mg of C97670!

 Warning  NULL Quote: 1.00mg of C97561!

 Warning  NULL Quote: 1.00mg of C97567!

 Warning  NULL Quote: 1.00mg of C97568!

 Warning  NULL Quote: 1.00mg of C26626!

 Warning  NULL Quote: 1.00mg of C97887!

 Warning  NULL Quote: 1.00mg of C97778!

 Warning  NULL Quote: 1.00mg of C97779!

 Warning  NULL Quote: 2.00mg of C97813!

 Warning  NULL Quote: 1.00mg of C97878!

 Warning  NULL Quote: 1.00mg of C97814!

 Warning  NULL Quote: 1.00mg of C97874!

 Warning  NULL Quote: 1.00mg of C97875!

 Warning  NULL Quote: 1.00mg of C97976!

 Warning  NULL Quote: 1.00mg of C97977!

 Warning  NULL Quote: 1.00mg of C97918!

 Warning  NULL Quote: 1.00mg of C97919!

 Warning  NULL Quote: 1.00mg of C97864!

 Warning  NULL Quote: 1.00mg of C97865!

 Warning  NULL Quote: 1.00mg of C97888!

 Warning  NULL Quote: 1.00mg of C97952!

 Warning  NULL Quote: 1.00mg of C97876!

 Warning  NULL Quote: 1.00mg of C97877!

 Warning  NULL Quote: 1.00mg of C97944!

 Warning  NULL Quote: 1.00mg of C97493!

 Warning  NULL Quote: 1.00mg of C97853!

 Warning  NULL Quote: 1.00mg of C97846!

 Warning  NULL Quote: 1.00mg of C97847!

 Warning  NULL Quote: 1.00mg of C97950!

 Warning  NULL Quote: 1.00mg of C97951!

 Warning  NULL Quote: 1.00mg of C97978!

 Warning  NULL Quote: 1.00mg of C97979!

 Warning  NULL Quote: 1.00mg of C97854!

 Warning  NULL Quote: 1.00mg of C97910!

 Warning  NULL Quote: 1.00mg of C97911!

 Warning  NULL Quote: 1.00mg of C97931!

 Warning  NULL Quote: 1.00mg of C97983!

 Warning  NULL Quote: 1.00mg of C97984!

 Warning  NULL Quote: 1.00mg of C97913!

 Warning  NULL Quote: 1.00mg of C97914!

 Warning  NULL Quote: 1.00mg of C97841!

 Warning  NULL Quote: 1.00mg of C97842!

 Warning  NULL Quote: 1.00mg of C97827!

 Warning  NULL Quote: 1.00mg of C97828!

 Warning  NULL Quote: 1.00mg of C97759!

 Warning  NULL Quote: 1.00mg of C97760!

 Warning  NULL Quote: 1.00mg of C97879!

 Warning  NULL Quote: 1.00mg of C97880!

 Warning  NULL Quote: 1.00mg of C97903!

 Warning  NULL Quote: 1.00mg of C97904!

 Warning  NULL Quote: 2.00mg of C97792!

 Warning  NULL Quote: 1.00mg of C97909!

 Warning  NULL Quote: 1.00mg of C97815!

 Warning  NULL Quote: 1.00mg of C97816!

 Warning  NULL Quote: 2.00mg of C97893!

 Warning  NULL Quote: 1.00mg of C97975!

 Warning  NULL Quote: 1.00mg of C97967!

 Warning  NULL Quote: 1.00mg of C97968!

 Warning  NULL Quote: 1.00mg of C97946!

 Warning  NULL Quote: 1.00mg of C97947!

 Warning  NULL Quote: 1.00mg of C97747!

 Warning  NULL Quote: 1.00mg of C97748!

 Warning  NULL Quote: 2.00mg of C97851!

 Warning  NULL Quote: 1.00mg of C97862!

 Warning  NULL Quote: 1.00mg of C97767!

 Warning  NULL Quote: 1.00mg of C97768!

 Warning  NULL Quote: 1.00mg of C97920!

 Warning  NULL Quote: 1.00mg of C63053!

 Warning  NULL Quote: 1.00mg of C97869!

 Warning  NULL Quote: 1.00mg of C97317!

 Warning  NULL Quote: 1.00mg of C97848!

 Warning  NULL Quote: 1.00mg of C97955!

 Warning  NULL Quote: 1.00mg of C97956!

 Warning  NULL Quote: 1.00mg of C97793!

 Warning  NULL Quote: 1.00mg of C97963!

 Warning  NULL Quote: 1.00mg of C97964!

 Warning  NULL Quote: 1.00mg of C97638!

 Warning  NULL Quote: 1.00mg of C97894!

 Warning  NULL Quote: 1.00mg of C97788!

 Warning  NULL Quote: 1.00mg of C97789!

 Warning  NULL Quote: 3.00mg of C97733!

 Warning  NULL Quote: 1.00mg of C97930!

 Warning  NULL Quote: 1.00mg of C97895!

 Warning  NULL Quote: 1.00mg of C97896!

 Warning  NULL Quote: 1.00mg of C97937!

 Warning  NULL Quote: 1.00mg of C97938!

 Warning  NULL Quote: 1.00mg of C97818!

 Warning  NULL Quote: 1.00mg of C97819!

 Warning  NULL Quote: 2.00mg of C97735!

 Warning  NULL Quote: 1.00mg of C97736!

 Warning  NULL Quote: 1.00mg of C97925!

 Warning  NULL Quote: 1.00mg of C83280!

 Warning  NULL Quote: 1.00mg of C97863!

 Warning  NULL Quote: 1.00mg of C97806!

 Warning  NULL Quote: 1.00mg of C97986!

 Warning  NULL Quote: 1.00mg of C97987!

 Warning  NULL Quote: 1.00mg of C97774!

 Warning  NULL Quote: 1.00mg of C97775!

 Warning  NULL Quote: 1.00mg of C97796!

 Warning  NULL Quote: 1.00mg of C97797!

 Warning  NULL Quote: 1.00mg of C97753!

 Warning  NULL Quote: 1.00mg of C97754!

 Warning  NULL Quote: 1.00mg of C97737!

 Warning  NULL Quote: 1.00mg of C97738!

 Warning  NULL Quote: 1.00mg of C97787!

 Warning  NULL Quote: 1.00mg of C97939!

 Warning  NULL Quote: 1.00mg of C97940!

 Warning  NULL Quote: 1.00mg of C97734!

 Warning  NULL Quote: 1.00mg of C97745!

 Warning  NULL Quote: 1.00mg of C97746!

 Warning  NULL Quote: 1.00mg of C97684!

 Warning  NULL Quote: 1.00mg of C97685!

 Warning  NULL Quote: 1.00mg of C68492!

 Warning  NULL Quote: 1.00mg of C97189!

 Warning  NULL Quote: 1.00mg of C97632!

 Warning  NULL Quote: 1.00mg of C97639!

 Warning  NULL Quote: 1.00mg of C97640!

 Warning  NULL Quote: 1.00mg of C97633!

 Warning  NULL Quote: 1.00mg of C97860!

 Warning  NULL Quote: 1.00mg of C97861!

 Warning  NULL Quote: 1.00mg of C97866!

 Warning  NULL Quote: 1.00mg of C97867!

 Warning  NULL Quote: 1.00mg of C97839!

 Warning  NULL Quote: 1.00mg of C97840!

 Warning  NULL Quote: 1.00mg of C97843!

 Warning  NULL Quote: 1.00mg of C97844!

 Warning  NULL Quote: 1.00mg of C48348!

 Warning  NULL Quote: 1.00mg of C97934!

 Warning  NULL Quote: 1.00mg of C97948!

 Warning  NULL Quote: 1.00mg of C97949!

 Warning  NULL Quote: 1.00mg of C97935!

 Warning  NULL Quote: 1.00mg of C97936!

 Warning  NULL Quote: 1.00mg of C97749!

 Warning  NULL Quote: 1.00mg of C97750!

 Warning  NULL Quote: 1.00mg of C97690!

 Warning  NULL Quote: 1.00mg of C97691!

 Warning  NULL Quote: 1.00mg of C97675!

 Warning  NULL Quote: 1.00mg of C97676!

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/d68ev3c/cycle_01/syndirella/retrosynthesis/openbind_d68ev3c_c1_scaffo
lds.json...

In [12]:
recipe.write_CAR_csv("cycle_01/syndirella/retrosynthesis/openbind_d68ev3c_c1_scaffolds.csv")

DEBUG: Querying database for routes

DEBUG: Assembling route dictionary

DEBUG: Checking availability

Output()

 Warning  More than two reactants for reaction=R2: C96981 + C96982 + C96983 -> C1396 via
Petasis-borono_Mannich_reaction!

 Warning  More than two reactants for reaction=R7: C96981 + C96983 + C96990 -> C1418 via
Petasis-borono_Mannich_reaction!

 Warning  More than two reactants for reaction=R109: C97216 + C97217 + C97218 -> C3330 via
Petasis-borono_Mannich_reaction!

 Warning  More than two reactants for reaction=R281: C97126 + C97606 + C97607 -> C25412 via
Petasis-borono_Mannich_reaction!

 Warning  More than two reactants for reaction=R333: C97726 + C97727 + C97728 -> C17100 via
1,2,4-Triazole_synthesis_from_carboxylic_acid,_amidine,_and_hydrazine!

 Warning  More than two reactants for reaction=R368: C96983 + C97823 + C97824 -> C25215 via
Van_Leusen_imidazole_synthesis!

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/d68ev3c/cycle_01/syndirella/retrosynthesis/openbind_d68ev3c_c1_scaffo
lds_1steps.csv...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/d68ev3c/cycle_01/syndirella/retrosynthesis/openbind_d68ev3c_c1_scaffo
lds_2steps.csv...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/d68ev3c/cycle_01/syndirella/retrosynthesis/openbind_d68ev3c_c1_scaffo
lds_3steps.csv...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/d68ev3c/cycle_01/syndirella/retrosynthesis/openbind_d68ev3c_c1_scaffo
lds.csv...

,target-names,no-steps,concentration-required-mM,amount-required-uL,batch-tag,reactant-1-1,reactant-2-1,reaction-product-smiles-1,reaction-name-1,reaction-recipe-1,...,reaction-product-smiles-2,reaction-name-2,reaction-recipe-2,reaction-groupby-column-2,reactant-1-3,reactant-2-3,reaction-product-smiles-3,reaction-name-3,reaction-recipe-3,reaction-groupby-column-3
0,C1366,1,None,None,None,NCCN=C(O)c1ccsc1,Clc1nc2cccc(Cl)c2o1,OC(=NCCNc1cccc2nc(Cl)oc12)c1ccsc1,Buchwald-Hartwig_amination,None,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
1,C1396,1,None,None,None,OB(O)c1ccccc1,O=Cc1cccc(O)c1,NC(c1ccccc1)c1cccc(O)c1,Petasis-borono_Mannich_reaction,None,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
2,C1418,1,None,None,None,OB(O)c1ccccc1,N,NC(c1ccccc1)c1ccccc1I,Petasis-borono_Mannich_reaction,None,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
3,C1422,1,None,None,None,N,NC(c1ccccc1)c1ccccc1Br,Nc1ccccc1C(N)c1ccccc1,Buchwald-Hartwig_amination,None,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
4,C1430,1,None,None,None,CC1=NN(c2cccc(Cl)c2)C(=O)C1,O,CC1=NN(c2cccc(O)c2)C(=O)C1,Buchwald-Hartwig_(thio)etherification,None,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
223,C49675,1,None,None,None,OC1CCCNC1,Brc1ccc2c(c1)CCCC2,c1cc2c(cc1C1CCCNC1)CCCC2,Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_ha...,None,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
224,C35601,1,None,None,None,O=C(NCC1CCCNC1)c1cc[nH]n1,CCC(C)C(=O)NCC(=O)O,CCC(C)C(=O)NCC(=O)N1CCCC(CNC(=O)c2cc[nH]n2)C1,Amidation,None,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
225,C51482,1,None,None,None,Cn1ccnc1CC(=O)O,CC(N)CNC(=O)C12CCC(CC1)O2,CC(CNC(=O)C12CCC(CC1)O2)NC(=O)Cc1nccn1C,Amidation,None,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
226,C32763,1,None,None,None,c1c[nH]c(N2CCNCC2)n1,O=C(O)CCc1ccc2ncsc2c1,O=C(CCc1ccc2ncsc2c1)N1CCN(c2ncc[nH]2)CC1,Amidation,None,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
227,C63365,1,None,None,None,NC1CCNC1=O,CC(CO)NC(=O)c1cccc2cc[nH]c12,CC(CNC1CCNC1=O)NC(=O)c1cccc2cc[nH]c12,Mitsunobu_reaction_with_amine_alcohol_and_thio...,None,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>

In [4]:
animal.db.delete_reactions()

## Count raw merge smiles

In [17]:
import pandas as pd

In [18]:
df = pd.read_csv("cycle_01/fragmenstein/fragmenstein_bulkdock_input.csv")
print(len(df))
print(len(df.drop_duplicates(subset=["smiles"])))

6356

4829

In [19]:
df = pd.read_csv("cycle_01/knitwork/knitwork_pure.csv")
print(len(df))
print(len(df.drop_duplicates(subset=["smiles"])))

268518

58416

In [20]:
df = pd.read_csv("cycle_01/knitwork/knitwork_impure.csv")
print(len(df))
print(len(df.drop_duplicates(subset=["smiles"])))

285885

43631

In [21]:
animal.P1.posebusters()

True