# OpenBind-HIPPO

- **Target: A71EV2A**
- **Cycle: 01**

## Prep

- [ ] Generate, place, and export merges

## Imports

In [1]:
%load_ext autoreload
%autoreload 2
import hippo
import mrich
from mrich import print
from pathlib import Path
from os import environ
import shutil
import molparse as mp

# Config

In [2]:
target_name = "A71EV2A"
target_dir = Path(environ["BULK"]) / "TARGETS" / target_name
cycle_name = "cycle_01"
cycle_dir = Path(cycle_name)
aligned_dir = target_dir / "aligned_files"

## Animal

In [3]:
animal = hippo.HIPPO(target_name, target_dir / f"{target_name}.sqlite")

 Creating HIPPO animal

name = A71EV2A

db_path = /opt/xchem-fragalysis-2/maxwin/BulkDock/TARGETS/A71EV2A/A71EV2A.sqlite

DEBUG: hippo.Database.__init__()

DEBUG: Database.path = /opt/xchem-fragalysis-2/maxwin/BulkDock/TARGETS/A71EV2A/A71EV2A.sqlite

DEBUG: hippo.Database.connect()

DEBUG: sqlite3.version='2.6.0'

 Success  Database connected @ /opt/xchem-fragalysis-2/maxwin/BulkDock/TARGETS/A71EV2A/A71EV2A.sqlite!

 Success  Initialised animal HIPPO("A71EV2A")!

# Annotate Pockets (subsites)

Assign subsites from Canonical site definitions in metadata (for all experimental hits)

In [7]:
hits = animal.poses(tag="hits")
hits.set_subsites_from_metadata_field()

Assign subsites of derivatives based on inspiration subsites

In [6]:
animal.db.set_derivative_subsites()

Print a summary

In [9]:
hits.derivatives.subsite_summary()

┏━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━┓
┃ subsite            ┃ num_poses ┃
┡━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━┩
│ 1 - Active Site    │ 468573    │
│ 3 - A0541/A/147/1  │ 45665     │
│ 5 - A3181/A/202/1  │ 44195     │
│ 2 - A3977/A/202/1  │ 34805     │
│ 6 - A0486/A/147/1  │ 34135     │
│ 4 - A0525/A/246/1  │ 14904     │
│ 15 - A1068/A/246/1 │ 8928      │
│ 17 - A1081/A/201/1 │ 5281      │
│ 10 - A0900/A/147/1 │ 18        │
│ 9 - A0432/A/147/1  │ 10        │
│ 14 - A0554/A/147/1 │ 8         │
│ 13 - A0412/A/147/1 │ 5         │
│ 16 - A1068/A/302/1 │ 5         │
│ 8 - A0517/A/147/1  │ 5         │
│ 7 - A0488/A/147/1  │ 3         │
└────────────────────┴───────────┘

# Tag Scaffolds

Tag your scaffolds, e.g. by their BulkDock export:

In [10]:
scaffold_poses = (
    animal.poses.get_by_metadata_substring_match("openbind_a71ev2a_c1_fragmenstein_165VU4J.sdf") + 
    animal.poses.get_by_metadata_substring_match("openbind_a71ev2a_c1_knitwork_pure_165VWF8.sdf") + 
    animal.poses.get_by_metadata_substring_match("openbind_a71ev2a_c1_knitwork_impure_165VXJF.sdf")
)

scaffold_poses.add_tag("openbind_a71ev2a_c1_scaffolds")

Tagged {P × 1518} w/ "openbind_a71ev2a_c1_scaffolds"

In [11]:
scaffold_poses.subsite_summary()

┏━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━┓
┃ subsite            ┃ num_poses ┃
┡━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━┩
│ 1 - Active Site    │ 1431      │
│ 6 - A0486/A/147/1  │ 79        │
│ 5 - A3181/A/202/1  │ 73        │
│ 3 - A0541/A/147/1  │ 62        │
│ 2 - A3977/A/202/1  │ 44        │
│ 17 - A1081/A/201/1 │ 30        │
│ 4 - A0525/A/246/1  │ 16        │
└────────────────────┴───────────┘

# Prepare for Syndirella inputs

In [20]:
scaffold_poses.to_syndirella("cycle_01/syndirella/openbind_a71ev2a_c1_scaffolds")

 DISK  Writing cycle_01/syndirella/templates...

out_key = openbind_a71ev2a_c1_scaffolds

#poses = 1518

Output()

 DISK  Writing cycle_01/syndirella/templates/A5666a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/A0207a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/A0922a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/A2290a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/A3191a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/A3305a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/A3483a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/A3685a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/A3849a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/A3992b_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/A4202b_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/A4315a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/A4344a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/A4214a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/A4415a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/A4456b_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/A4526a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/A4580b_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/A4673a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/A4721a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/A4791a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/A4840a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/A4883a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/A4963a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/A4954a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/A5081b_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/A5213a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/A5288a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/A5424b_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/A5544a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/A1180a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/A3890a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/A1146a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/A5079b_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/A1140a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/A0528b_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/A4586a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/A0309a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/A0514b_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/A0239a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/A0556a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/A1293a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/A2629a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/A3897a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/A0541a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/A1779a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/A3623a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/A0428a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/A4445a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/A4311a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/A3436a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/A4461a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/A4333a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/A1776a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/A5036a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/A3977b_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/A3706b_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/A0469a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/A4029a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/A1445a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/A5079a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/A4746a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/A1778a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/A3564a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/A1145a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/A3181b_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/A0473a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/A0341a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/A5427a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/A4386a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/A4031a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/A4742a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/A0586a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/A4351a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/A5036b_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/A0875a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/A4806a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/A4012a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/A0525a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/A3392a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/openbind_a71ev2a_c1_scaffolds_syndirella_input.csv...

╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ in <module>:1                                                                                    │
│                                                                                                  │
│ ❱ 1 scaffold_poses.to_syndirella("cycle_01/syndirella/openbind_a71ev2a_c1_scaffolds")            │
│   2                                                                                              │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │    aligned_dir = PosixPath('/opt/xchem-fragalysis-2/maxwin/BulkDock/TARGETS/A71EV2A/aligned… │ │
│ │         animal = HIPPO("A71EV2A")                                                            │ │
│ │      cycle_dir = PosixPath('cycle_01')                                                       │ │
│ │     cycle_name = 'cycle_01'                                                                  │ │
│ │        environ = environ({                                                                   │ │
│ │                  │   'HYDRA_LAUNCHER_EXTRA_ARGS': '--external-launcher',                     │ │
│ │                  │   'PRECURSOR': '/opt/xchem-fragalysis-2/maxwin/2A_Precursor_FFF',         │ │
│ │                  │   'MAMBA_ALWAYS_YES': 'yes',                                              │ │
│ │                  │   'CONDA_SHLVL': '1',                                                     │ │
│ │                  │   'LD_LIBRARY_PATH':                                                      │ │
│ │                  '/usr/local/cuda/compat:/opt/xchem-fragalysis-2/maxwin/conda/lib:/dls_sw/e… │ │
│ │                  │   'LS_COLORS':                                                            │ │
│ │                  'rs=0:di=38;5;33:ln=38;5;51:mh=00:pi=40;38;5;11:so=38;5;13:do=38;5;5:bd=48… │ │
│ │                  │   'CONDA_EXE': '/opt/xchem-fragalysis-2/maxwin/conda/bin/conda',          │ │
│ │                  │   'SLURM_NODEID': '0',                                                    │ │
│ │                  │   'SLURM_TASK_PID': '10034',                                              │ │
│ │                  │   'SSH_CONNECTION': '172.23.162.11 47758 172.23.176.6 22',                │ │
│ │                  │   ... +132                                                                │ │
│ │                  })                                                                          │ │
│ │           exit = <IPython.core.autocall.ZMQExitAutocall object at 0x7f4ce0a04ce0>            │ │
│ │    get_ipython = <bound method InteractiveShell.get_ipython of                               │ │
│ │                  <ipykernel.zmqshell.ZMQInteractiveShell object at 0x7f4cbfdd94f0>>          │ │
│ │          hippo = <module 'hippo' from                                                        │ │
│ │                  '/opt/xchem-fragalysis-2/maxwin/conda/envs/py312/lib/python3.12/site-packa… │ │
│ │           hits = poses tagged "hits": {P × 645}                                              │ │
│ │             In = [                                                                           │ │
│ │                  │   '',                                                                     │ │
│ │                  │   'animal.db.set_derivative_subsites()',                                  │ │
│ │                  │   'animal = hippo.HIPPO(target_name, target_dir /                         │ │
│ │                  f"{target_name}.sqlite")',                                                  │ │
│ │                  │   "get_ipython().run_line_magic('load_ext',                               │ │
│ │                  'autoreload')\nget_ipython().run_line_ma"+156,                              │ │
│ │                  │   'target_name = "A71EV2A"\ntarget_dir = Path(environ["BULK"]) /          │ │
│ │                  "TARGETS" / target_'+100,                                                   │ │
│ │                  │   'animal = hippo.HIPPO(target_name, target_dir /                         │ │
│ │                  f"{target_name}.sqlite")',                                                  │ │
│ │                  │   'animal.db.set_derivative_subsites()',                                  │ │
│ │                  │   'hits =                                                                 │ │
│ │                  animal.poses(tag="hits")\nhits.set_subsites_from_metadata_field()',         │ │
│ │                  │   'hits.derivatives',                                                     │ │
│ │                  │   'hits.derivatives.subsite_summary()',                                   │ │
│ │                  │   ... +11                                                                 │ │
│ │                  ]                                                                           │ │
│ │             mp = <module 'molparse' from                                                     │ │
│ │                  '/opt/xchem-fragalysis-2/maxwin/conda/envs/py312/lib/python3.12/site-packa… │ │
│ │          mrich = <module 'mrich' from                                                        │ │
│ │                  '/opt/xchem-fragalysis-2/maxwin/conda/envs/py312/lib/python3.12/site-packa… │ │
│ │            Out = {                                                                           │ │
│ │                  │   8: derivatives of poses tagged "hits": {P × 645}: {P × 495627},         │ │
│ │                  │   13: '02'                                                                │ │
│ │                  }                                                                           │ │
│ │           quit = <IPython.core.autocall.ZMQExitAutocall object at 0x7f4ce0a04ce0>            │ │
│ │ scaffold_poses = {P × 1518}                                                                  │ │
│ │         shutil = <module 'shutil' from                                                       │ │
│ │                  '/opt/xchem-fragalysis-2/maxwin/conda/envs/py312/lib/python3.12/shutil.py'> │ │
│ │     target_dir = PosixPath('/opt/xchem-fragalysis-2/maxwin/BulkDock/TARGETS/A71EV2A')        │ │
│ │    target_name = 'A71EV2A'                                                                   │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                                  │
│ /opt/xchem-fragalysis-2/maxwin/conda/envs/py312/lib/python3.12/site-packages/hippo/pset.py:2305  │
│ in to_syndirella                                                                                 │
│                                                                                                  │
│   2302 │   │   inspirations = PoseSet(self.db, pset_inspirations)                                │
│   2303 │   │                                                                                     │
│   2304 │   │   sdf_name = out_dir / f"{out_key}_syndirella_inspiration_hits.sdf"                 │
│ ❱ 2305 │   │   inspirations.write_sdf(                                                           │
│   2306 │   │   │   sdf_name,                                                                     │
│   2307 │   │   │   inspirations=False,                                                           │
│   2308 │   │   │   tags=False,                                                                   │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │              comp = C8142 "UZXQDRCHBFTVHG-UHFFFAOYSA-N"                                      │ │
│ │          csv_name = PosixPath('cycle_01/syndirella/openbind_a71ev2a_c1_scaffolds_syndirella… │ │
│ │                 d = {                                                                        │ │
│ │                     │   'smiles': 'CC(=O)CC(O)C1CCCNC1',                                     │ │
│ │                     │   'template': 'A3897a',                                                │ │
│ │                     │   'compound_set': 'openbind_a71ev2a_c1_scaffolds',                     │ │
│ │                     │   'hit1': 'A0719a',                                                    │ │
│ │                     │   'hit2': 'A3509a'                                                     │ │
│ │                     }                                                                        │ │
│ │              data = [                                                                        │ │
│ │                     │   {                                                                    │ │
│ │                     │   │   'smiles': 'O=C(Cc1cocn1)Nc1ccc2c(c1)C(F)CC2',                    │ │
│ │                     │   │   'template': 'A5666a',                                            │ │
│ │                     │   │   'compound_set': 'openbind_a71ev2a_c1_scaffolds',                 │ │
│ │                     │   │   'hit1': 'A5151a',                                                │ │
│ │                     │   │   'hit2': 'A5512a'                                                 │ │
│ │                     │   },                                                                   │ │
│ │                     │   {                                                                    │ │
│ │                     │   │   'smiles': 'Cc1ccc(C(O)(C=O)NCc2cocn2)c2[nH]ccc12',               │ │
│ │                     │   │   'template': 'A5666a',                                            │ │
│ │                     │   │   'compound_set': 'openbind_a71ev2a_c1_scaffolds',                 │ │
│ │                     │   │   'hit1': 'A0487a',                                                │ │
│ │                     │   │   'hit2': 'A4940a'                                                 │ │
│ │                     │   },                                                                   │ │
│ │                     │   {                                                                    │ │
│ │                     │   │   'smiles': 'COc1ccc(C(C)=O)cc1-c1n[nH]cc1CN',                     │ │
│ │                     │   │   'template': 'A5666a',                                            │ │
│ │                     │   │   'compound_set': 'openbind_a71ev2a_c1_scaffolds',                 │ │
│ │                     │   │   'hit1': 'A0501a',                                                │ │
│ │                     │   │   'hit2': 'A4456a'                                                 │ │
│ │                     │   },                                                                   │ │
│ │                     │   {                                                                    │ │
│ │                     │   │   'smiles': 'CNNc1ccccc1-c1n[nH]c(C)c1CO',                         │ │
│ │                     │   │   'template': 'A5666a',                                            │ │
│ │                     │   │   'compound_set': 'openbind_a71ev2a_c1_scaffolds',                 │ │
│ │                     │   │   'hit1': 'A0501a',                                                │ │
│ │                     │   │   'hit2': 'A4524a'                                                 │ │
│ │                     │   },                                                                   │ │
│ │                     │   {                                                                    │ │
│ │                     │   │   'smiles':                                                        │ │
│ │                     'CN1CCc2cc(F)c(OC(=O)N3CCCC(C(N)=O)C3)cc2C1CCOc1ccc(CNCc2ccc(C#N)cc2)cc… │ │
│ │                     │   │   'template': 'A5666a',                                            │ │
│ │                     │   │   'compound_set': 'openbind_a71ev2a_c1_scaffolds',                 │ │
│ │                     │   │   'hit1': 'A0501b',                                                │ │
│ │                     │   │   'hit2': 'A4214a',                                                │ │
│ │                     │   │   'hit3': 'A4214b'                                                 │ │
│ │                     │   },                                                                   │ │
│ │                     │   {                                                                    │ │
│ │                     │   │   'smiles': 'NC(=O)C1CCCN(C(=O)NC2CN(CS)NC23CCCC2(CCC2)N3)C1',     │ │
│ │                     │   │   'template': 'A5666a',                                            │ │
│ │                     │   │   'compound_set': 'openbind_a71ev2a_c1_scaffolds',                 │ │
│ │                     │   │   'hit1': 'A0514a',                                                │ │
│ │                     │   │   'hit2': 'A4310a'                                                 │ │
│ │                     │   },                                                                   │ │
│ │                     │   {                                                                    │ │
│ │                     │   │   'smiles': 'COC(=O)c1cc(C)ncc1N(C)N',                             │ │
│ │                     │   │   'template': 'A5666a',                                            │ │
│ │                     │   │   'compound_set': 'openbind_a71ev2a_c1_scaffolds',                 │ │
│ │                     │   │   'hit1': 'A0514a',                                                │ │
│ │                     │   │   'hit2': 'A4331a'                                                 │ │
│ │                     │   },                                                                   │ │
│ │                     │   {                                                                    │ │
│ │                     │   │   'smiles': 'CCNCc1ccc(OC=O)cn1',                                  │ │
│ │                     │   │   'template': 'A5666a',                                            │ │
│ │                     │   │   'compound_set': 'openbind_a71ev2a_c1_scaffolds',                 │ │
│ │                     │   │   'hit1': 'A0514a',                                                │ │
│ │                     │   │   'hit2': 'A4346a'                                                 │ │
│ │                     │   },                                                                   │ │
│ │                     │   {                                                                    │ │
│ │                     │   │   'smiles': 'COC(=O)c1ccncc1N',                                    │ │
│ │                     │   │   'template': 'A5666a',                                            │ │
│ │                     │   │   'compound_set': 'openbind_a71ev2a_c1_scaffolds',                 │ │
│ │                     │   │   'hit1': 'A0514a',                                                │ │
│ │                     │   │   'hit2': 'A4368a'                                                 │ │
│ │                     │   },                                                                   │ │
│ │                     │   {                                                                    │ │
│ │                     │   │   'smiles': 'CC1CCC(C(N)=O)CN1C(=O)Nc1cn(CS)nc1C(=O)NC1CCC1',      │ │
│ │                     │   │   'template': 'A5666a',                                            │ │
│ │                     │   │   'compound_set': 'openbind_a71ev2a_c1_scaffolds',                 │ │
│ │                     │   │   'hit1': 'A0528a',                                                │ │
│ │                     │   │   'hit2': 'A3940a'                                                 │ │
│ │                     │   },                                                                   │ │
│ │                     │   ... +1508                                                            │ │
│ │                     ]                                                                        │ │
│ │                df = │   │   │   │   │   │   │   │   │   │   │   │    smiles template  \      │ │
│ │                     0                      O=C(Cc1cocn1)Nc1ccc2c(c1)C(F)CC2   A5666a         │ │
│ │                     1                 Cc1ccc(C(O)(C=O)NCc2cocn2)c2[nH]ccc12   A5666a         │ │
│ │                     2                       COc1ccc(C(C)=O)cc1-c1n[nH]cc1CN   A5666a         │ │
│ │                     3                           CNNc1ccccc1-c1n[nH]c(C)c1CO   A5666a         │ │
│ │                     4     CN1CCc2cc(F)c(OC(=O)N3CCCC(C(N)=O)C3)cc2C1CCOc...   A5666a         │ │
│ │                     ...                                                 ...      ...         │ │
│ │                     1513                                 c1cc(-c2ncco2)ccn1   A3897a         │ │
│ │                     1514               O=C(NCCc1cc[nH]n1)c1ccnc(-n2ccnc2)c1   A3897a         │ │
│ │                     1515                       C1CCC(c2nc3c([nH]2)CCCC3)NC1   A3897a         │ │
│ │                     1516                       C1CC(c2nc3c([nH]2)CCSC3)CCN1   A3897a         │ │
│ │                     1517                                CC(=O)CC(O)C1CCCNC1   A3897a         │ │
│ │                     │   │   │   │   │                                                        │ │
│ │                     │   │   │   │   │      compound_set    hit1    hit2    hit3 hit4 hit5    │ │
│ │                     hit6  \                                                                  │ │
│ │                     0     openbind_a71ev2a_c1_scaffolds  A5151a  A5512a     NaN  NaN  NaN    │ │
│ │                     NaN                                                                      │ │
│ │                     1     openbind_a71ev2a_c1_scaffolds  A0487a  A4940a     NaN  NaN  NaN    │ │
│ │                     NaN                                                                      │ │
│ │                     2     openbind_a71ev2a_c1_scaffolds  A0501a  A4456a     NaN  NaN  NaN    │ │
│ │                     NaN                                                                      │ │
│ │                     3     openbind_a71ev2a_c1_scaffolds  A0501a  A4524a     NaN  NaN  NaN    │ │
│ │                     NaN                                                                      │ │
│ │                     4     openbind_a71ev2a_c1_scaffolds  A0501b  A4214a  A4214b  NaN  NaN    │ │
│ │                     NaN                                                                      │ │
│ │                     ...                             ...     ...     ...     ...  ...  ...    │ │
│ │                     ...                                                                      │ │
│ │                     1513  openbind_a71ev2a_c1_scaffolds  A0556a  A3435a     NaN  NaN  NaN    │ │
│ │                     NaN                                                                      │ │
│ │                     1514  openbind_a71ev2a_c1_scaffolds  A0556a  A3435a     NaN  NaN  NaN    │ │
│ │                     NaN                                                                      │ │
│ │                     1515  openbind_a71ev2a_c1_scaffolds  A3371a  A3706a     NaN  NaN  NaN    │ │
│ │                     NaN                                                                      │ │
│ │                     1516  openbind_a71ev2a_c1_scaffolds  A3371a  A3706a     NaN  NaN  NaN    │ │
│ │                     NaN                                                                      │ │
│ │                     1517  openbind_a71ev2a_c1_scaffolds  A0719a  A3509a     NaN  NaN  NaN    │ │

# Run syndirella

```
cd cycle_01/syndirella
sbatch --job-name "a71ev2a_syndirella" --mem 16000 $HOME2/slurm/run_bash_with_conda.sh ../../../scripts/run_syndirella_retro.sh
```

## Read In Syndirella Retro Output

In [40]:
!pwd

/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a

In [8]:
animal.db.backup()

 DISK  Writing /opt/xchem-fragalysis-2/maxwin/BulkDock/TARGETS/A71EV2A/A71EV2A_1AZTHU8.sqlite...

DEBUG: Copied 10000 of 575384 pages...

Output()

DEBUG: Copied 20000 of 575384 pages...

DEBUG: Copied 30000 of 575384 pages...

DEBUG: Copied 40000 of 575384 pages...

DEBUG: Copied 50000 of 575384 pages...

DEBUG: Copied 60000 of 575384 pages...

DEBUG: Copied 70000 of 575384 pages...

DEBUG: Copied 80000 of 575384 pages...

DEBUG: Copied 90000 of 575384 pages...

DEBUG: Copied 100000 of 575384 pages...

DEBUG: Copied 110000 of 575384 pages...

DEBUG: Copied 120000 of 575384 pages...

DEBUG: Copied 130000 of 575384 pages...

DEBUG: Copied 140000 of 575384 pages...

DEBUG: Copied 150000 of 575384 pages...

DEBUG: Copied 160000 of 575384 pages...

DEBUG: Copied 170000 of 575384 pages...

DEBUG: Copied 180000 of 575384 pages...

DEBUG: Copied 190000 of 575384 pages...

DEBUG: Copied 200000 of 575384 pages...

DEBUG: Copied 210000 of 575384 pages...

DEBUG: Copied 220000 of 575384 pages...

DEBUG: Copied 230000 of 575384 pages...

DEBUG: Copied 240000 of 575384 pages...

DEBUG: Copied 250000 of 575384 pages...

DEBUG: Copied 260000 of 575384 pages...

DEBUG: Copied 270000 of 575384 pages...

DEBUG: Copied 280000 of 575384 pages...

DEBUG: Copied 290000 of 575384 pages...

DEBUG: Copied 300000 of 575384 pages...

DEBUG: Copied 310000 of 575384 pages...

DEBUG: Copied 320000 of 575384 pages...

DEBUG: Copied 330000 of 575384 pages...

DEBUG: Copied 340000 of 575384 pages...

DEBUG: Copied 350000 of 575384 pages...

DEBUG: Copied 360000 of 575384 pages...

DEBUG: Copied 370000 of 575384 pages...

DEBUG: Copied 380000 of 575384 pages...

DEBUG: Copied 390000 of 575384 pages...

DEBUG: Copied 400000 of 575384 pages...

DEBUG: Copied 410000 of 575384 pages...

DEBUG: Copied 420000 of 575384 pages...

DEBUG: Copied 430000 of 575384 pages...

DEBUG: Copied 440000 of 575384 pages...

DEBUG: Copied 450000 of 575384 pages...

DEBUG: Copied 460000 of 575384 pages...

DEBUG: Copied 470000 of 575384 pages...

DEBUG: Copied 480000 of 575384 pages...

DEBUG: Copied 490000 of 575384 pages...

DEBUG: Copied 500000 of 575384 pages...

DEBUG: Copied 510000 of 575384 pages...

DEBUG: Copied 520000 of 575384 pages...

DEBUG: Copied 530000 of 575384 pages...

DEBUG: Copied 540000 of 575384 pages...

DEBUG: Copied 550000 of 575384 pages...

DEBUG: Copied 560000 of 575384 pages...

DEBUG: Copied 570000 of 575384 pages...

DEBUG: Copied 575384 of 575384 pages...

In [7]:
animal.reactions

all reactions: {R × 0}

In [6]:
animal.db.delete_reactions()

In [9]:
animal.add_syndirella_routes("cycle_01/syndirella/retrosynthesis/justretroquery_openbind_a71ev2a_c1_scaffolds_syndirella_input.pkl.gz", CAR_only=False)

0 0 0 Hydroxy_to_fluoro C139485 "DJFOQNYEAKBIRI-UHFFFAOYSA-N"

reactants =
[283086]

product = C139485 "DJFOQNYEAKBIRI-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Hydroxy_to_fluoro!

0 1 0 Amidation C139485 "DJFOQNYEAKBIRI-UHFFFAOYSA-N"

 Success  registered route 1!

1 0 0 Grignard_addition_to_carbonyl C143369 "FRGSBTNMALVKIX-UHFFFAOYSA-N"

reactants =
[283087, 283088]

product = C143369 "FRGSBTNMALVKIX-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Grignard_addition_to_carbonyl!

1 1 0 Reductive_amination C143369 "FRGSBTNMALVKIX-UHFFFAOYSA-N"

1 1 1 Grignard_addition_to_carbonyl C283090 "WGYFLCFFZKPIJG-UHFFFAOYSA-N"

reactants =
[283091, 283092]

product = C283090 "WGYFLCFFZKPIJG-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Grignard_addition_to_carbonyl!

1 2 0 Grignard_addition_to_carbonyl C143369 "FRGSBTNMALVKIX-UHFFFAOYSA-N"

reactants =
[283087, 283092]

product = C143369 "FRGSBTNMALVKIX-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Grignard_addition_to_carbonyl!

1 3 0 Reductive_amination C143369 "FRGSBTNMALVKIX-UHFFFAOYSA-N"

1 3 1 Grignard_addition_to_carbonyl C283090 "WGYFLCFFZKPIJG-UHFFFAOYSA-N"

reactants =
[283088, 283091]

product = C283090 "WGYFLCFFZKPIJG-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Grignard_addition_to_carbonyl!

1 4 0 Amine_alkylation C143369 "FRGSBTNMALVKIX-UHFFFAOYSA-N"

reactants =
[283090, 283093]

product = C143369 "FRGSBTNMALVKIX-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

2 0 0 Sp2-sp2_Suzuki_coupling C140978 "GTEDGOGNLVTJAH-UHFFFAOYSA-N"

 Success  registered route 2!

3 0 0 Sp2-sp2_Suzuki_coupling C140988 "SMJQGBYWPCXPDR-UHFFFAOYSA-N"

 Success  registered route 3!

4 0 0 Amine_alkylation C142584 "HOYKQAJNZZTFNB-UHFFFAOYSA-N"

reactants =
[283098, 283099]

product = C142584 "HOYKQAJNZZTFNB-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

4 1 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C142584 "HOYKQAJNZZTFNB-UHFFFAOYSA-N"

4 1 1 Formation_of_carbamate_from_amine_and_alcohol C283101 "UAGGEYPXVLLQDM-UHFFFAOYSA-N"

reactants =
[202220, 283102]

product = C283101 "UAGGEYPXVLLQDM-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Formation_of_carbamate_from_amine_and_alcohol!

4 2 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C142584 "HOYKQAJNZZTFNB-UHFFFAOYSA-N"

4 2 1 Formation_of_carbamate_from_amine_and_alcohol C283103 "PCFSROPXJNHWAU-UHFFFAOYSA-N"

reactants =
[202220, 283104]

product = C283103 "PCFSROPXJNHWAU-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Formation_of_carbamate_from_amine_and_alcohol!

4 3 0 Amine_alkylation C142584 "HOYKQAJNZZTFNB-UHFFFAOYSA-N"

reactants =
[283101, 283105]

product = C142584 "HOYKQAJNZZTFNB-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

4 4 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C142584 "HOYKQAJNZZTFNB-UHFFFAOYSA-N"

4 4 1 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C283103 "PCFSROPXJNHWAU-UHFFFAOYSA-N"

4 4 2 Williamson_ether_synthesis C283106 "SJOXAVXODHGNJI-UHFFFAOYSA-N"

4 4 3 Formation_of_carbamate_from_amine_and_alcohol C283108 "IISPPGLNHUXYLP-UHFFFAOYSA-N"

reactants =
[202220, 283109]

product = C283108 "IISPPGLNHUXYLP-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Formation_of_carbamate_from_amine_and_alcohol!

6 0 0 N-nucleophilic_aromatic_substitution C141599 "VTHWZLJENYHQED-UHFFFAOYSA-N"

 Success  registered route 4!

7 0 0 Haloform_reaction C141610 "BVTGRELWAPFAGZ-UHFFFAOYSA-N"

reactants =
[283110, 283111]

product = C141610 "BVTGRELWAPFAGZ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Haloform_reaction!

7 1 0 Amine_alkylation C141610 "BVTGRELWAPFAGZ-UHFFFAOYSA-N"

reactants =
[283112, 283113]

product = C141610 "BVTGRELWAPFAGZ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

7 2 0 Minisci_reaction_with_carboxylic_acid_(intermolecular) C141610 "BVTGRELWAPFAGZ-UHFFFAOYSA-N"

reactants =
[282911, 282912]

product = C141610 "BVTGRELWAPFAGZ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Minisci_reaction_with_carboxylic_acid_(intermolecular)!

7 3 0 Amine_alkylation C141610 "BVTGRELWAPFAGZ-UHFFFAOYSA-N"

reactants =
[282993, 283112]

product = C141610 "BVTGRELWAPFAGZ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

7 4 0 Amine_alkylation C141610 "BVTGRELWAPFAGZ-UHFFFAOYSA-N"

reactants =
[283112, 283114]

product = C141610 "BVTGRELWAPFAGZ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

8 0 0 Steglich_esterification C15 "XLQIGLBALJNHKR-UHFFFAOYSA-N"

 Success  registered route 5!

9 0 0 Iodo_N-arylation C143262 "RSZCATFBIKXLMR-UHFFFAOYSA-N"

reactants =
[283115, 283116]

product = C143262 "RSZCATFBIKXLMR-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Iodo_N-arylation!

9 1 0 Buchwald-Hartwig_amidation_with_amide-like_nucleophile C143262 "RSZCATFBIKXLMR-UHFFFAOYSA-N"

9 1 1 Amine_alkylation C283117 "RHVMMVCBMYLGJR-UHFFFAOYSA-N"

reactants =
[283118, 283119]

product = C283117 "RHVMMVCBMYLGJR-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

9 2 0 Iodo_N-arylation C143262 "RSZCATFBIKXLMR-UHFFFAOYSA-N"

reactants =
[283115, 283116]

product = C143262 "RSZCATFBIKXLMR-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Iodo_N-arylation!

9 3 0 Amine_alkylation C143262 "RSZCATFBIKXLMR-UHFFFAOYSA-N"

reactants =
[283120, 283121]

product = C143262 "RSZCATFBIKXLMR-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

9 4 0 Buchwald-Hartwig_amidation_with_amide-like_nucleophile C143262 "RSZCATFBIKXLMR-UHFFFAOYSA-N"

9 4 1 Amine_alkylation C283115 "XVBAYEOFMLWTME-UHFFFAOYSA-N"

reactants =
[283120, 283122]

product = C283115 "XVBAYEOFMLWTME-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

11 0 0 Amine_alkylation C223813 "MHXVSXRGCZAGOU-UHFFFAOYSA-N"

reactants =
[283123, 283124]

product = C223813 "MHXVSXRGCZAGOU-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

11 1 0 Amine_alkylation C223813 "MHXVSXRGCZAGOU-UHFFFAOYSA-N"

reactants =
[283124, 283125]

product = C223813 "MHXVSXRGCZAGOU-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

11 2 0 Amine_alkylation C223813 "MHXVSXRGCZAGOU-UHFFFAOYSA-N"

reactants =
[283124, 283126]

product = C223813 "MHXVSXRGCZAGOU-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

11 3 0 Amine_alkylation C223813 "MHXVSXRGCZAGOU-UHFFFAOYSA-N"

reactants =
[283124, 283127]

product = C223813 "MHXVSXRGCZAGOU-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

11 4 0 Amine_alkylation C223813 "MHXVSXRGCZAGOU-UHFFFAOYSA-N"

reactants =
[283124, 283128]

product = C223813 "MHXVSXRGCZAGOU-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

12 0 0 Amide_to_amine_reduction C223849 "VZZNLCQRSIUYQV-UHFFFAOYSA-N"

reactants =
[283129]

product = C223849 "VZZNLCQRSIUYQV-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amide_to_amine_reduction!

12 1 0 N-Ac_deprotection C223849 "VZZNLCQRSIUYQV-UHFFFAOYSA-N"

reactants =
[283130]

product = C223849 "VZZNLCQRSIUYQV-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: N-Ac_deprotection!

12 2 0 Amide_to_amine_reduction C223849 "VZZNLCQRSIUYQV-UHFFFAOYSA-N"

reactants =
[283131]

product = C223849 "VZZNLCQRSIUYQV-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amide_to_amine_reduction!

12 3 0 Buchwald-Hartwig_amination C223849 "VZZNLCQRSIUYQV-UHFFFAOYSA-N"

12 4 0 Nitrile_to_amine_(LAH) C223849 "VZZNLCQRSIUYQV-UHFFFAOYSA-N"

reactants =
[283133]

product = C223849 "VZZNLCQRSIUYQV-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Nitrile_to_amine_(LAH)!

13 0 0 N-Phth_deprotection C223851 "LUMZHBRJYVSBCU-UHFFFAOYSA-N"

reactants =
[283134]

product = C223851 "LUMZHBRJYVSBCU-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: N-Phth_deprotection!

13 1 0 Nitrile_to_amine_(LAH) C223851 "LUMZHBRJYVSBCU-UHFFFAOYSA-N"

reactants =
[283135]

product = C223851 "LUMZHBRJYVSBCU-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Nitrile_to_amine_(LAH)!

13 2 0 Amine_alkylation C223851 "LUMZHBRJYVSBCU-UHFFFAOYSA-N"

reactants =
[282920, 283136]

product = C223851 "LUMZHBRJYVSBCU-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

13 3 0 N-Phth_deprotection C223851 "LUMZHBRJYVSBCU-UHFFFAOYSA-N"

reactants =
[283134]

product = C223851 "LUMZHBRJYVSBCU-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: N-Phth_deprotection!

13 4 0 Nitrile_to_amine_(LAH) C223851 "LUMZHBRJYVSBCU-UHFFFAOYSA-N"

reactants =
[283135]

product = C223851 "LUMZHBRJYVSBCU-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Nitrile_to_amine_(LAH)!

14 0 0 Buchwald-Hartwig_(thio)etherification C223863 "GFLLQDRPUXMCNL-UHFFFAOYSA-N"

reactants =
[283137, 283138]

product = C223863 "GFLLQDRPUXMCNL-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Buchwald-Hartwig_(thio)etherification!

14 1 0 Buchwald-Hartwig_(thio)etherification C223863 "GFLLQDRPUXMCNL-UHFFFAOYSA-N"

reactants =
[283138, 283139]

product = C223863 "GFLLQDRPUXMCNL-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Buchwald-Hartwig_(thio)etherification!

14 2 0 Minisci_reaction_with_carboxylic_acid_(intermolecular) C223863 "GFLLQDRPUXMCNL-UHFFFAOYSA-N"

reactants =
[282925, 283140]

product = C223863 "GFLLQDRPUXMCNL-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Minisci_reaction_with_carboxylic_acid_(intermolecular)!

14 3 0 Buchwald-Hartwig_(thio)etherification C223863 "GFLLQDRPUXMCNL-UHFFFAOYSA-N"

reactants =
[283138, 283139]

product = C223863 "GFLLQDRPUXMCNL-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Buchwald-Hartwig_(thio)etherification!

14 4 0 Friedel-Crafts_methylation C223863 "GFLLQDRPUXMCNL-UHFFFAOYSA-N"

reactants =
[283140]

product = C223863 "GFLLQDRPUXMCNL-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Friedel-Crafts_methylation!

15 0 0 Amidation C223867 "QMYIEUIBLQHGOH-UHFFFAOYSA-N"

15 0 1 Amidation C282916 "RMMAIEAOZXUGGA-UHFFFAOYSA-N"

 Success  registered route 6!

16 0 0 Minisci_reaction_with_carboxylic_acid_(intermolecular) C223876 "JFQKISFLWIGOGM-UHFFFAOYSA-N"

reactants =
[41, 282919]

product = C223876 "JFQKISFLWIGOGM-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Minisci_reaction_with_carboxylic_acid_(intermolecular)!

16 1 0 Sulfonamide_Schotten-Baumann_with_amine_(intermolecular) C223876 "JFQKISFLWIGOGM-UHFFFAOYSA-N"

reactants =
[282920, 282921]

product = C223876 "JFQKISFLWIGOGM-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sulfonamide_Schotten-Baumann_with_amine_(intermolecular)!

16 2 0 Amidation C223876 "JFQKISFLWIGOGM-UHFFFAOYSA-N"

16 2 1 Minisci_reaction_with_carboxylic_acid_(intermolecular) C282922 "XLBQRKQYQVZGNW-UHFFFAOYSA-N"

reactants =
[282919, 282923]

product = C282922 "XLBQRKQYQVZGNW-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Minisci_reaction_with_carboxylic_acid_(intermolecular)!

16 3 0 Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide C223876 "JFQKISFLWIGOGM-UHFFFAOYSA-N"

reactants =
[283141, 283142]

product = C223876 "JFQKISFLWIGOGM-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide!

16 4 0 Minisci_reaction_with_carboxylic_acid_(intermolecular) C223876 "JFQKISFLWIGOGM-UHFFFAOYSA-N"

reactants =
[282924, 282925]

product = C223876 "JFQKISFLWIGOGM-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Minisci_reaction_with_carboxylic_acid_(intermolecular)!

18 0 0 Sp3-sp2_Suzuki_coupling C223890 "GEFQHGIGKICAEA-UHFFFAOYSA-N"

18 0 1 N-nucleophilic_aromatic_substitution C283143 "BSSBOXFSGMLEOR-UHFFFAOYSA-N"

18 0 2 Alpha_alkylation_of_ketone C283145 "KEQHSLJAPSLWSN-UHFFFAOYSA-N"

reactants =
[283146, 283147]

product = C283145 "KEQHSLJAPSLWSN-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ketone!

18 1 0 Sp3-sp2_Suzuki_coupling C223890 "GEFQHGIGKICAEA-UHFFFAOYSA-N"

18 1 1 Alpha_alkylation_of_ketone C283148 "ZWUCAWVWMHGFBJ-UHFFFAOYSA-N"

reactants =
[283149, 283150]

product = C283148 "ZWUCAWVWMHGFBJ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ketone!

18 2 0 Minisci_reaction_with_carboxylic_acid_(intermolecular) C223890 "GEFQHGIGKICAEA-UHFFFAOYSA-N"

reactants =
[283151, 283152]

product = C223890 "GEFQHGIGKICAEA-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Minisci_reaction_with_carboxylic_acid_(intermolecular)!

18 3 0 Alpha_alkylation_of_ketone C223890 "GEFQHGIGKICAEA-UHFFFAOYSA-N"

reactants =
[283153, 283154]

product = C223890 "GEFQHGIGKICAEA-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ketone!

18 4 0 NHK_reaction C223890 "GEFQHGIGKICAEA-UHFFFAOYSA-N"

reactants =
[283155, 283156]

product = C223890 "GEFQHGIGKICAEA-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: NHK_reaction!

19 0 0 Imine_formation C140626 "WVCRQGVMFRYXPW-UHFFFAOYSA-N"

reactants =
[283157]

product = C140626 "WVCRQGVMFRYXPW-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Imine_formation!

19 1 0 Imine_formation C140626 "WVCRQGVMFRYXPW-UHFFFAOYSA-N"

reactants =
[283157]

product = C140626 "WVCRQGVMFRYXPW-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Imine_formation!

19 2 0 Imine_formation C140626 "WVCRQGVMFRYXPW-UHFFFAOYSA-N"

reactants =
[283157]

product = C140626 "WVCRQGVMFRYXPW-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Imine_formation!

19 3 0 Imine_formation C140626 "WVCRQGVMFRYXPW-UHFFFAOYSA-N"

reactants =
[283157]

product = C140626 "WVCRQGVMFRYXPW-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Imine_formation!

19 4 0 Imine_formation C140626 "WVCRQGVMFRYXPW-UHFFFAOYSA-N"

reactants =
[283157]

product = C140626 "WVCRQGVMFRYXPW-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Imine_formation!

20 0 0 Petasis-borono_Mannich_reaction C224261 "ISCVVQNSXGDQLC-UHFFFAOYSA-N"

reactants =
[283158, 283159, 283160]

product = C224261 "ISCVVQNSXGDQLC-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Petasis-borono_Mannich_reaction!

20 1 0 Petasis-borono_Mannich_reaction C224261 "ISCVVQNSXGDQLC-UHFFFAOYSA-N"

reactants =
[283159, 283160, 283161]

product = C224261 "ISCVVQNSXGDQLC-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Petasis-borono_Mannich_reaction!

20 2 0 Formation_of_sulfonamide_from_halide_-_Shavnya_reaction C224261 "ISCVVQNSXGDQLC-UHFFFAOYSA-N"

reactants =
[282993, 283162]

product = C224261 "ISCVVQNSXGDQLC-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Formation_of_sulfonamide_from_halide_-_Shavnya_reaction!

20 3 0 Corey-House_synthesis_(intermolecular) C224261 "ISCVVQNSXGDQLC-UHFFFAOYSA-N"

reactants =
[283163, 283164]

product = C224261 "ISCVVQNSXGDQLC-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Corey-House_synthesis_(intermolecular)!

20 4 0 Formation_of_sulfonamide_from_halide_-_Shavnya_reaction C224261 "ISCVVQNSXGDQLC-UHFFFAOYSA-N"

reactants =
[283162, 283165]

product = C224261 "ISCVVQNSXGDQLC-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Formation_of_sulfonamide_from_halide_-_Shavnya_reaction!

22 0 0 Amidation C224459 "FQRZQBJCBUZPFL-UHFFFAOYSA-N"

22 0 1 Formation_of_sulfonamide_from_halide_-_Shavnya_reaction C283167 "CODOEKCKHMFCDU-UHFFFAOYSA-N"

reactants =
[282993, 283168]

product = C283167 "CODOEKCKHMFCDU-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Formation_of_sulfonamide_from_halide_-_Shavnya_reaction!

22 1 0 Formation_of_sulfonamide_from_halide_-_Shavnya_reaction C224459 "FQRZQBJCBUZPFL-UHFFFAOYSA-N"

reactants =
[283165, 283169]

product = C224459 "FQRZQBJCBUZPFL-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Formation_of_sulfonamide_from_halide_-_Shavnya_reaction!

22 2 0 Ester_amidation C224459 "FQRZQBJCBUZPFL-UHFFFAOYSA-N"

22 2 1 Formation_of_sulfonamide_from_halide_-_Shavnya_reaction C283170 "RXRHWHPDHNKSBT-UHFFFAOYSA-N"

reactants =
[283114, 283171]

product = C283170 "RXRHWHPDHNKSBT-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Formation_of_sulfonamide_from_halide_-_Shavnya_reaction!

22 3 0 Amidation C224459 "FQRZQBJCBUZPFL-UHFFFAOYSA-N"

22 3 1 Formation_of_sulfonamide_from_halide_-_Shavnya_reaction C283167 "CODOEKCKHMFCDU-UHFFFAOYSA-N"

reactants =
[283165, 283168]

product = C283167 "CODOEKCKHMFCDU-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Formation_of_sulfonamide_from_halide_-_Shavnya_reaction!

22 4 0 Amidation C224459 "FQRZQBJCBUZPFL-UHFFFAOYSA-N"

22 4 1 Formation_of_sulfonamide_from_halide_-_Shavnya_reaction C283167 "CODOEKCKHMFCDU-UHFFFAOYSA-N"

reactants =
[283114, 283168]

product = C283167 "CODOEKCKHMFCDU-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Formation_of_sulfonamide_from_halide_-_Shavnya_reaction!

23 0 0 N-nucleophilic_aromatic_substitution C224597 "QQECAXFDBXEVIN-UHFFFAOYSA-N"

 Success  registered route 7!

25 0 0 Reductive_amination C224826 "RMGPEBAHBGDSEW-UHFFFAOYSA-N"

 Success  registered route 8!

26 0 0 Alpha_alkylation_of_ketone C224908 "UVHVGUBWEQMBKH-UHFFFAOYSA-N"

reactants =
[283172, 283173]

product = C224908 "UVHVGUBWEQMBKH-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ketone!

26 1 0 Aryl_halide_to_aniline C224908 "UVHVGUBWEQMBKH-UHFFFAOYSA-N"

reactants =
[283174]

product = C224908 "UVHVGUBWEQMBKH-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Aryl_halide_to_aniline!

26 2 0 Conjugate_addition_of_organolithium_(Gilman_reagent) C224908 "UVHVGUBWEQMBKH-UHFFFAOYSA-N"

reactants =
[283175, 283176]

product = C224908 "UVHVGUBWEQMBKH-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Conjugate_addition_of_organolithium_(Gilman_reagent)!

26 3 0 Alpha_alkylation_of_ketone C224908 "UVHVGUBWEQMBKH-UHFFFAOYSA-N"

reactants =
[283173, 283177]

product = C224908 "UVHVGUBWEQMBKH-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ketone!

26 4 0 Conjugate_addition_of_Grignard_(Gilman_reagents) C224908 "UVHVGUBWEQMBKH-UHFFFAOYSA-N"

reactants =
[283176, 283178]

product = C224908 "UVHVGUBWEQMBKH-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Conjugate_addition_of_Grignard_(Gilman_reagents)!

27 0 0 Buchwald-Hartwig_amidation_with_amide-like_nucleophile C225591 "VBSRSIBHLLKMRD-UHFFFAOYSA-N"

27 0 1 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C282930 "RCRCIWHZUBGRFR-UHFFFAOYSA-N"

 Success  registered route 9!

28 0 0 Grignard_addition_to_carbonyl C225528 "RHLCJNOASWSNMI-UHFFFAOYSA-N"

reactants =
[52, 283179]

product = C225528 "RHLCJNOASWSNMI-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Grignard_addition_to_carbonyl!

28 1 0 Grignard_addition_to_carbonyl C225528 "RHLCJNOASWSNMI-UHFFFAOYSA-N"

reactants =
[283180, 283181]

product = C225528 "RHLCJNOASWSNMI-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Grignard_addition_to_carbonyl!

28 2 0 Grignard_addition_to_carbonyl C225528 "RHLCJNOASWSNMI-UHFFFAOYSA-N"

reactants =
[283180, 283182]

product = C225528 "RHLCJNOASWSNMI-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Grignard_addition_to_carbonyl!

28 3 0 Grignard_addition_to_carbonyl C225528 "RHLCJNOASWSNMI-UHFFFAOYSA-N"

reactants =
[283180, 283183]

product = C225528 "RHLCJNOASWSNMI-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Grignard_addition_to_carbonyl!

28 4 0 Grignard_addition_to_carbonyl C225528 "RHLCJNOASWSNMI-UHFFFAOYSA-N"

reactants =
[52, 283184]

product = C225528 "RHLCJNOASWSNMI-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Grignard_addition_to_carbonyl!

29 0 0 Buchwald-Hartwig_(thio)etherification C226551 "NIPJUCNGLLJJFA-UHFFFAOYSA-N"

reactants =
[283185, 283186]

product = C226551 "NIPJUCNGLLJJFA-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Buchwald-Hartwig_(thio)etherification!

29 1 0 Sandmeyer_hydroxylation C226551 "NIPJUCNGLLJJFA-UHFFFAOYSA-N"

reactants =
[283187]

product = C226551 "NIPJUCNGLLJJFA-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sandmeyer_hydroxylation!

29 2 0 Buchwald-Hartwig_(thio)etherification C226551 "NIPJUCNGLLJJFA-UHFFFAOYSA-N"

reactants =
[283185, 283188]

product = C226551 "NIPJUCNGLLJJFA-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Buchwald-Hartwig_(thio)etherification!

29 3 0 Nucleophilic_aromatic_substitution_(alcohol,_phenol,_water) C226551 "NIPJUCNGLLJJFA-UHFFFAOYSA-N"

reactants =
[283185, 283188]

product = C226551 "NIPJUCNGLLJJFA-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Nucleophilic_aromatic_substitution_(alcohol,_phenol,_water)!

29 4 0 Methoxy_to_hydroxy_(aryl) C226551 "NIPJUCNGLLJJFA-UHFFFAOYSA-N"

reactants =
[283189]

product = C226551 "NIPJUCNGLLJJFA-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Methoxy_to_hydroxy_(aryl)!

30 0 0 Ester_amidation C226563 "NQUKOMUTPJKZKK-UHFFFAOYSA-N"

30 1 0 Amine_alkylation C226563 "NQUKOMUTPJKZKK-UHFFFAOYSA-N"

reactants =
[283191]

product = C226563 "NQUKOMUTPJKZKK-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

30 2 0 Amine_alkylation C226563 "NQUKOMUTPJKZKK-UHFFFAOYSA-N"

reactants =
[283192]

product = C226563 "NQUKOMUTPJKZKK-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

30 3 0 Amine_alkylation C226563 "NQUKOMUTPJKZKK-UHFFFAOYSA-N"

reactants =
[283193]

product = C226563 "NQUKOMUTPJKZKK-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

30 4 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C226563 "NQUKOMUTPJKZKK-UHFFFAOYSA-N"

30 4 1 Ester_amidation C283194 "WVYUUCSIARMELG-UHFFFAOYSA-N"

31 0 0 Sp3-sp2_Suzuki_coupling C193943 "XCYJPXQACVEIOS-UHFFFAOYSA-N"

 Success  registered route 10!

32 0 0 Sp3-sp2_Suzuki_coupling C270367 "KVOJUNAPEGTLGD-UHFFFAOYSA-N"

 Success  registered route 11!

33 0 0 Amidation C272449 "JHOVMKNPAZUPKC-UHFFFAOYSA-N"

33 0 1 Ketone/aldehyde_chlorination C283200 "ZWVHNXLYGRSBOS-UHFFFAOYSA-N"

reactants =
[283202]

product = C283200 "ZWVHNXLYGRSBOS-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Ketone/aldehyde_chlorination!

33 1 0 Amidation C272449 "JHOVMKNPAZUPKC-UHFFFAOYSA-N"

33 1 1 Ester_hydrolysis_(carboxylate_fragment) C283200 "ZWVHNXLYGRSBOS-UHFFFAOYSA-N"

reactants =
[283203]

product = C283200 "ZWVHNXLYGRSBOS-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Ester_hydrolysis_(carboxylate_fragment)!

33 2 0 Amidation C272449 "JHOVMKNPAZUPKC-UHFFFAOYSA-N"

33 2 1 Ketone/aldehyde_chlorination C283204 "FTGJTLLKVRMZPO-UHFFFAOYSA-N"

reactants =
[283206]

product = C283204 "FTGJTLLKVRMZPO-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Ketone/aldehyde_chlorination!

33 3 0 Amidation C272449 "JHOVMKNPAZUPKC-UHFFFAOYSA-N"

33 3 1 Ketone/aldehyde_chlorination C283200 "ZWVHNXLYGRSBOS-UHFFFAOYSA-N"

reactants =
[283202]

product = C283200 "ZWVHNXLYGRSBOS-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Ketone/aldehyde_chlorination!

33 4 0 Amidation C272449 "JHOVMKNPAZUPKC-UHFFFAOYSA-N"

33 4 1 Ester_hydrolysis_(carboxylate_fragment) C283200 "ZWVHNXLYGRSBOS-UHFFFAOYSA-N"

reactants =
[283207]

product = C283200 "ZWVHNXLYGRSBOS-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Ester_hydrolysis_(carboxylate_fragment)!

34 0 0 Amine_alkylation C272450 "CZQKOPHNVUQSNW-UHFFFAOYSA-N"

reactants =
[283120, 283208]

product = C272450 "CZQKOPHNVUQSNW-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

34 1 0 Amine_alkylation C272450 "CZQKOPHNVUQSNW-UHFFFAOYSA-N"

reactants =
[283118, 283208]

product = C272450 "CZQKOPHNVUQSNW-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

34 2 0 Amine_alkylation C272450 "CZQKOPHNVUQSNW-UHFFFAOYSA-N"

reactants =
[283120, 283208]

product = C272450 "CZQKOPHNVUQSNW-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

34 3 0 Amine_alkylation C272450 "CZQKOPHNVUQSNW-UHFFFAOYSA-N"

reactants =
[283118, 283208]

product = C272450 "CZQKOPHNVUQSNW-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

34 4 0 Amine_alkylation C272450 "CZQKOPHNVUQSNW-UHFFFAOYSA-N"

reactants =
[283118, 283208]

product = C272450 "CZQKOPHNVUQSNW-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

35 0 0 Amine_alkylation C272452 "LXSYKFPSDCVOLS-UHFFFAOYSA-N"

reactants =
[283118, 283209]

product = C272452 "LXSYKFPSDCVOLS-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

35 1 0 Amine_alkylation C272452 "LXSYKFPSDCVOLS-UHFFFAOYSA-N"

reactants =
[283120, 283209]

product = C272452 "LXSYKFPSDCVOLS-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

35 2 0 Ketone/aldehyde_chlorination C272452 "LXSYKFPSDCVOLS-UHFFFAOYSA-N"

reactants =
[283210]

product = C272452 "LXSYKFPSDCVOLS-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Ketone/aldehyde_chlorination!

35 3 0 Amine_alkylation C272452 "LXSYKFPSDCVOLS-UHFFFAOYSA-N"

reactants =
[283120, 283209]

product = C272452 "LXSYKFPSDCVOLS-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

35 4 0 Amine_alkylation C272452 "LXSYKFPSDCVOLS-UHFFFAOYSA-N"

reactants =
[283120, 283209]

product = C272452 "LXSYKFPSDCVOLS-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

36 0 0 Ester_amidation C272454 "VAFKCTIAOFBPGI-UHFFFAOYSA-N"

36 0 1 Hydroxy_to_fluoro C283211 "WZWHABJWZDTLJH-UHFFFAOYSA-N"

reactants =
[283212]

product = C283211 "WZWHABJWZDTLJH-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Hydroxy_to_fluoro!

36 1 0 Tebbe-Petasis_olefination C272454 "VAFKCTIAOFBPGI-UHFFFAOYSA-N"

reactants =
[283213]

product = C272454 "VAFKCTIAOFBPGI-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Tebbe-Petasis_olefination!

36 2 0 Alpha_alkylation_of_ester/amide C272454 "VAFKCTIAOFBPGI-UHFFFAOYSA-N"

reactants =
[283214]

product = C272454 "VAFKCTIAOFBPGI-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ester/amide!

36 3 0 Alpha_alkylation_of_ester/amide C272454 "VAFKCTIAOFBPGI-UHFFFAOYSA-N"

reactants =
[283215]

product = C272454 "VAFKCTIAOFBPGI-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ester/amide!

36 4 0 Tebbe-Petasis_olefination C272454 "VAFKCTIAOFBPGI-UHFFFAOYSA-N"

reactants =
[283213]

product = C272454 "VAFKCTIAOFBPGI-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Tebbe-Petasis_olefination!

37 0 0 Tebbe-Petasis_olefination C272236 "BQSDEPIXYSTHIQ-UHFFFAOYSA-N"

reactants =
[283216]

product = C272236 "BQSDEPIXYSTHIQ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Tebbe-Petasis_olefination!

37 1 0 Tebbe-Petasis_olefination C272236 "BQSDEPIXYSTHIQ-UHFFFAOYSA-N"

reactants =
[283216]

product = C272236 "BQSDEPIXYSTHIQ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Tebbe-Petasis_olefination!

37 2 0 Tebbe-Petasis_olefination C272236 "BQSDEPIXYSTHIQ-UHFFFAOYSA-N"

reactants =
[283216]

product = C272236 "BQSDEPIXYSTHIQ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Tebbe-Petasis_olefination!

37 3 0 Tebbe-Petasis_olefination C272236 "BQSDEPIXYSTHIQ-UHFFFAOYSA-N"

reactants =
[283216]

product = C272236 "BQSDEPIXYSTHIQ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Tebbe-Petasis_olefination!

37 4 0 Tebbe-Petasis_olefination C272236 "BQSDEPIXYSTHIQ-UHFFFAOYSA-N"

reactants =
[283216]

product = C272236 "BQSDEPIXYSTHIQ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Tebbe-Petasis_olefination!

38 0 0 Tebbe-Petasis_olefination C272482 "LNZDVQSHYXFPSN-UHFFFAOYSA-N"

reactants =
[283217]

product = C272482 "LNZDVQSHYXFPSN-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Tebbe-Petasis_olefination!

38 1 0 Amidation C272482 "LNZDVQSHYXFPSN-UHFFFAOYSA-N"

38 1 1 Tebbe-Petasis_olefination C283218 "DYHFTAAXPVBYRO-UHFFFAOYSA-N"

reactants =
[283219]

product = C283218 "DYHFTAAXPVBYRO-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Tebbe-Petasis_olefination!

38 2 0 Ester_amidation C272482 "LNZDVQSHYXFPSN-UHFFFAOYSA-N"

38 3 0 Tebbe-Petasis_olefination C272482 "LNZDVQSHYXFPSN-UHFFFAOYSA-N"

reactants =
[283217]

product = C272482 "LNZDVQSHYXFPSN-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Tebbe-Petasis_olefination!

38 4 0 Tebbe-Petasis_olefination C272482 "LNZDVQSHYXFPSN-UHFFFAOYSA-N"

reactants =
[283217]

product = C272482 "LNZDVQSHYXFPSN-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Tebbe-Petasis_olefination!

39 0 0 Tebbe-Petasis_olefination C272530 "QXQZOHKAPUDTNY-UHFFFAOYSA-N"

reactants =
[283221]

product = C272530 "QXQZOHKAPUDTNY-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Tebbe-Petasis_olefination!

39 1 0 Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide C272530 "QXQZOHKAPUDTNY-UHFFFAOYSA-N"

reactants =
[283222, 283223]

product = C272530 "QXQZOHKAPUDTNY-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide!

39 2 0 Nucleophilic_substitution_with_imine C272530 "QXQZOHKAPUDTNY-UHFFFAOYSA-N"

reactants =
[283114, 283224]

product = C272530 "QXQZOHKAPUDTNY-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Nucleophilic_substitution_with_imine!

39 3 0 Nucleophilic_substitution_with_imine C272530 "QXQZOHKAPUDTNY-UHFFFAOYSA-N"

reactants =
[283224, 283225]

product = C272530 "QXQZOHKAPUDTNY-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Nucleophilic_substitution_with_imine!

39 4 0 Nucleophilic_substitution_with_imine C272530 "QXQZOHKAPUDTNY-UHFFFAOYSA-N"

reactants =
[283224, 283225]

product = C272530 "QXQZOHKAPUDTNY-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Nucleophilic_substitution_with_imine!

40 0 0 Stille_coupling C272543 "WQAUBMDSLQUNTO-UHFFFAOYSA-N"

reactants =
[283226, 283227]

product = C272543 "WQAUBMDSLQUNTO-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Stille_coupling!

40 1 0 Sonogashira_coupling C272543 "WQAUBMDSLQUNTO-UHFFFAOYSA-N"

reactants =
[283226, 283228]

product = C272543 "WQAUBMDSLQUNTO-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sonogashira_coupling!

40 2 0 Sonogashira_coupling C272543 "WQAUBMDSLQUNTO-UHFFFAOYSA-N"

reactants =
[283226, 283228]

product = C272543 "WQAUBMDSLQUNTO-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sonogashira_coupling!

40 3 0 Stille_coupling C272543 "WQAUBMDSLQUNTO-UHFFFAOYSA-N"

reactants =
[283226, 283227]

product = C272543 "WQAUBMDSLQUNTO-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Stille_coupling!

40 4 0 Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide C272543 "WQAUBMDSLQUNTO-UHFFFAOYSA-N"

reactants =
[283229, 283230]

product = C272543 "WQAUBMDSLQUNTO-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide!

42 0 0 Tebbe-Petasis_olefination C272559 "OVSZTICLVOBVDF-UHFFFAOYSA-N"

reactants =
[283231]

product = C272559 "OVSZTICLVOBVDF-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Tebbe-Petasis_olefination!

42 1 0 Heck_reaction_(intermolecular) C272559 "OVSZTICLVOBVDF-UHFFFAOYSA-N"

reactants =
[283232, 283233]

product = C272559 "OVSZTICLVOBVDF-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Heck_reaction_(intermolecular)!

42 2 0 Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide C272559 "OVSZTICLVOBVDF-UHFFFAOYSA-N"

reactants =
[283234]

product = C272559 "OVSZTICLVOBVDF-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide!

42 3 0 Amidation C272559 "OVSZTICLVOBVDF-UHFFFAOYSA-N"

42 4 0 Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide C272559 "OVSZTICLVOBVDF-UHFFFAOYSA-N"

reactants =
[283234]

product = C272559 "OVSZTICLVOBVDF-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide!

43 0 0 Amidation C272859 "IEZGWHODQGSBRD-UHFFFAOYSA-N"

43 0 1 Amine_alkylation C283236 "YEQAXQICQSVSNP-UHFFFAOYSA-N"

reactants =
[283238, 283239]

product = C283236 "YEQAXQICQSVSNP-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

43 1 0 Sp2-sp2_Suzuki_coupling C272859 "IEZGWHODQGSBRD-UHFFFAOYSA-N"

43 1 1 Amine_alkylation C283241 "PCTBVXNRUPIBFQ-UHFFFAOYSA-N"

reactants =
[283242, 283243]

product = C283241 "PCTBVXNRUPIBFQ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

43 2 0 Buchwald-Hartwig_amidation_with_amide-like_nucleophile C272859 "IEZGWHODQGSBRD-UHFFFAOYSA-N"

43 2 1 Amine_alkylation C283244 "GPPLEJUVUNEWBY-UHFFFAOYSA-N"

reactants =
[283238, 283246]

product = C283244 "GPPLEJUVUNEWBY-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

43 3 0 Amidation C272859 "IEZGWHODQGSBRD-UHFFFAOYSA-N"

43 3 1 Amine_alkylation C283236 "YEQAXQICQSVSNP-UHFFFAOYSA-N"

reactants =
[283238, 283247]

product = C283236 "YEQAXQICQSVSNP-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

43 4 0 Amidation C272859 "IEZGWHODQGSBRD-UHFFFAOYSA-N"

43 4 1 Amine_alkylation C283236 "YEQAXQICQSVSNP-UHFFFAOYSA-N"

reactants =
[283238, 283239]

product = C283236 "YEQAXQICQSVSNP-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

46 0 0 Buchwald-Hartwig_amination C204757 "QBTJBIZQBLWTHK-UHFFFAOYSA-N"

46 0 1 Ester_amidation C282935 "ZQESYXXFUYDADO-UHFFFAOYSA-N"

46 1 0 Buchwald-Hartwig_amination C204757 "QBTJBIZQBLWTHK-UHFFFAOYSA-N"

46 1 1 Ester_amidation C282938 "HZARROWWWNMWPZ-UHFFFAOYSA-N"

46 2 0 Buchwald-Hartwig_amination C204757 "QBTJBIZQBLWTHK-UHFFFAOYSA-N"

46 2 1 Aromatic_iodination C283248 "OZWIYPOMRVKAHQ-UHFFFAOYSA-N"

reactants =
[283249]

product = C283248 "OZWIYPOMRVKAHQ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Aromatic_iodination!

46 3 0 Buchwald-Hartwig_amination C204757 "QBTJBIZQBLWTHK-UHFFFAOYSA-N"

46 3 1 Buchwald-Hartwig_(thio)etherification C282935 "ZQESYXXFUYDADO-UHFFFAOYSA-N"

reactants =
[283185, 283250]

product = C282935 "ZQESYXXFUYDADO-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Buchwald-Hartwig_(thio)etherification!

46 4 0 Buchwald-Hartwig_amination C204757 "QBTJBIZQBLWTHK-UHFFFAOYSA-N"

46 4 1 Aromatic_iodination C283248 "OZWIYPOMRVKAHQ-UHFFFAOYSA-N"

reactants =
[283249]

product = C283248 "OZWIYPOMRVKAHQ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Aromatic_iodination!

47 0 0 Reductive_amination C204759 "HFYNVCDYDDENBP-UHFFFAOYSA-N"

47 0 1 Imine_reduction_to_amine C228293 "FVCHDJBQSPQZRF-UHFFFAOYSA-N"

reactants =
[283252]

product = C228293 "FVCHDJBQSPQZRF-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Imine_reduction_to_amine!

47 1 0 Amine_alkylation C204759 "HFYNVCDYDDENBP-UHFFFAOYSA-N"

reactants =
[228293, 283253]

product = C204759 "HFYNVCDYDDENBP-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

47 2 0 Amine_alkylation C204759 "HFYNVCDYDDENBP-UHFFFAOYSA-N"

reactants =
[228293, 283254]

product = C204759 "HFYNVCDYDDENBP-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

47 3 0 Amine_alkylation C204759 "HFYNVCDYDDENBP-UHFFFAOYSA-N"

reactants =
[228293, 283255]

product = C204759 "HFYNVCDYDDENBP-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

47 4 0 Amine_alkylation C204759 "HFYNVCDYDDENBP-UHFFFAOYSA-N"

reactants =
[228293, 283256]

product = C204759 "HFYNVCDYDDENBP-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

48 0 0 Buchwald-Hartwig_amination C204769 "BULUSAUFSRPROH-UHFFFAOYSA-N"

 Success  registered route 12!

49 0 0 Amidation C204781 "GJSLUQQORYADDA-UHFFFAOYSA-N"

 Success  registered route 13!

50 0 0 Amidation C107 "ONGQCMNCDUWDOR-UHFFFAOYSA-N"

 Success  registered route 14!

51 0 0 Amidation C205051 "HGBAQJNRTBXKBY-UHFFFAOYSA-N"

 Success  registered route 15!

52 0 0 Amidation C205067 "IUKJWGRXOODHIO-UHFFFAOYSA-N"

 Success  registered route 16!

53 0 0 Amide_Schotten-Baumann_with_amine C209253 "XULPWVWELPOSEM-UHFFFAOYSA-N"

 Success  registered route 17!

54 0 0 Amidation C205099 "KJVZFMFVRBZFOP-UHFFFAOYSA-N"

 Success  registered route 18!

55 0 0 Amine_alkylation C205071 "PERMOVIPLPJQEI-UHFFFAOYSA-N"

reactants =
[282944, 283257]

product = C205071 "PERMOVIPLPJQEI-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

55 1 0 Amine_alkylation C205071 "PERMOVIPLPJQEI-UHFFFAOYSA-N"

reactants =
[282944, 283257]

product = C205071 "PERMOVIPLPJQEI-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

55 2 0 Chan-Lam_coupling_(amination) C205071 "PERMOVIPLPJQEI-UHFFFAOYSA-N"

reactants =
[283258, 283259]

product = C205071 "PERMOVIPLPJQEI-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Chan-Lam_coupling_(amination)!

55 3 0 Amine_alkylation C205071 "PERMOVIPLPJQEI-UHFFFAOYSA-N"

reactants =
[282944, 283257]

product = C205071 "PERMOVIPLPJQEI-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

55 4 0 N-Boc_deprotection C205071 "PERMOVIPLPJQEI-UHFFFAOYSA-N"

55 4 1 Amine_alkylation C283260 "NYNGVOJICOLIOP-UHFFFAOYSA-N"

reactants =
[283257, 283261]

product = C283260 "NYNGVOJICOLIOP-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

56 0 0 Amide_to_amine_reduction C206012 "CSWNYLMUJIALAZ-UHFFFAOYSA-N"

reactants =
[283262]

product = C206012 "CSWNYLMUJIALAZ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amide_to_amine_reduction!

56 1 0 Petasis-borono_Mannich_reaction C206012 "CSWNYLMUJIALAZ-UHFFFAOYSA-N"

reactants =
[282920, 283263, 283264]

product = C206012 "CSWNYLMUJIALAZ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Petasis-borono_Mannich_reaction!

56 2 0 Amide_to_amine_reduction C206012 "CSWNYLMUJIALAZ-UHFFFAOYSA-N"

reactants =
[283262]

product = C206012 "CSWNYLMUJIALAZ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amide_to_amine_reduction!

56 3 0 Amide_to_amine_reduction C206012 "CSWNYLMUJIALAZ-UHFFFAOYSA-N"

reactants =
[283262]

product = C206012 "CSWNYLMUJIALAZ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amide_to_amine_reduction!

56 4 0 Amide_to_amine_reduction C206012 "CSWNYLMUJIALAZ-UHFFFAOYSA-N"

reactants =
[283262]

product = C206012 "CSWNYLMUJIALAZ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amide_to_amine_reduction!

57 0 0 Amine_alkylation C205207 "WKJLQQPDUXOUMP-UHFFFAOYSA-N"

reactants =
[283265]

product = C205207 "WKJLQQPDUXOUMP-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

57 1 0 Amine_alkylation C205207 "WKJLQQPDUXOUMP-UHFFFAOYSA-N"

reactants =
[283266]

product = C205207 "WKJLQQPDUXOUMP-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

57 2 0 Amine_alkylation C205207 "WKJLQQPDUXOUMP-UHFFFAOYSA-N"

reactants =
[283265]

product = C205207 "WKJLQQPDUXOUMP-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

57 3 0 Amine_alkylation C205207 "WKJLQQPDUXOUMP-UHFFFAOYSA-N"

reactants =
[283265]

product = C205207 "WKJLQQPDUXOUMP-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

57 4 0 Amine_alkylation C205207 "WKJLQQPDUXOUMP-UHFFFAOYSA-N"

reactants =
[283265]

product = C205207 "WKJLQQPDUXOUMP-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

58 0 0 Reductive_amination C208022 "SQVAQLLFWWHIAM-UHFFFAOYSA-N"

58 0 1 Alpha_alkylation_of_ketone C283267 "OLQDRNGUNGHAMV-UHFFFAOYSA-N"

reactants =
[283268, 283269]

product = C283267 "OLQDRNGUNGHAMV-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ketone!

58 1 0 Ester_to_alcohol_reduction_(intermolecular) C208022 "SQVAQLLFWWHIAM-UHFFFAOYSA-N"

reactants =
[283270]

product = C208022 "SQVAQLLFWWHIAM-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Ester_to_alcohol_reduction_(intermolecular)!

58 2 0 Reductive_amination C208022 "SQVAQLLFWWHIAM-UHFFFAOYSA-N"

58 2 1 Aldol_addition_carbonyl C283267 "OLQDRNGUNGHAMV-UHFFFAOYSA-N"

reactants =
[283156, 283269]

product = C283267 "OLQDRNGUNGHAMV-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Aldol_addition_carbonyl!

58 3 0 Reductive_amination C208022 "SQVAQLLFWWHIAM-UHFFFAOYSA-N"

58 3 1 Aldol_addition_carbonyl C283267 "OLQDRNGUNGHAMV-UHFFFAOYSA-N"

reactants =
[283156, 283269]

product = C283267 "OLQDRNGUNGHAMV-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Aldol_addition_carbonyl!

58 4 0 Reductive_amination C208022 "SQVAQLLFWWHIAM-UHFFFAOYSA-N"

58 4 1 Alpha_alkylation_of_ketone C283267 "OLQDRNGUNGHAMV-UHFFFAOYSA-N"

reactants =
[283268, 283269]

product = C283267 "OLQDRNGUNGHAMV-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ketone!

60 0 0 Reductive_amination C205673 "WZIRMQBHPLNZSO-UHFFFAOYSA-N"

60 0 1 Buchwald-Hartwig_amination C283272 "XMHPEHNPHDALLY-UHFFFAOYSA-N"

60 0 2 Amine_alkylation C283273 "LTCDMTRTGJRTIL-UHFFFAOYSA-N"

reactants =
[282920, 283275]

product = C283273 "LTCDMTRTGJRTIL-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

60 1 0 Reductive_amination C205673 "WZIRMQBHPLNZSO-UHFFFAOYSA-N"

60 1 1 Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide C283272 "XMHPEHNPHDALLY-UHFFFAOYSA-N"

reactants =
[282914, 283276]

product = C283272 "XMHPEHNPHDALLY-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide!

60 2 0 N-nucleophilic_aromatic_substitution C205673 "WZIRMQBHPLNZSO-UHFFFAOYSA-N"

60 2 1 Amine_alkylation C283277 "ZXYPUELRDRQOOP-UHFFFAOYSA-N"

reactants =
[282920, 283278]

product = C283277 "ZXYPUELRDRQOOP-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

60 3 0 Reductive_amination C205673 "WZIRMQBHPLNZSO-UHFFFAOYSA-N"

60 3 1 N-nucleophilic_aromatic_substitution C283272 "XMHPEHNPHDALLY-UHFFFAOYSA-N"

60 3 2 Amine_alkylation C283273 "LTCDMTRTGJRTIL-UHFFFAOYSA-N"

reactants =
[282920, 283275]

product = C283273 "LTCDMTRTGJRTIL-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

60 4 0 Amine_alkylation C205673 "WZIRMQBHPLNZSO-UHFFFAOYSA-N"

reactants =
[283279, 283280]

product = C205673 "WZIRMQBHPLNZSO-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

62 0 0 Reductive_amination C206766 "FDHGUCPWMSEFHX-UHFFFAOYSA-N"

 Success  registered route 19!

64 0 0 Larock_indole_synthesis C207965 "MJVUMUCHXJIYSQ-UHFFFAOYSA-N"

reactants =
[283281, 283282]

product = C207965 "MJVUMUCHXJIYSQ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Larock_indole_synthesis!

64 1 0 Larock_indole_synthesis C207965 "MJVUMUCHXJIYSQ-UHFFFAOYSA-N"

reactants =
[283281, 283282]

product = C207965 "MJVUMUCHXJIYSQ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Larock_indole_synthesis!

64 2 0 Larock_indole_synthesis C207965 "MJVUMUCHXJIYSQ-UHFFFAOYSA-N"

reactants =
[283281, 283282]

product = C207965 "MJVUMUCHXJIYSQ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Larock_indole_synthesis!

64 3 0 N-nucleophilic_aromatic_substitution C207965 "MJVUMUCHXJIYSQ-UHFFFAOYSA-N"

64 3 1 Larock_indole_synthesis C283283 "UBQCGHPKTHXWKL-UHFFFAOYSA-N"

reactants =
[283282, 283284]

product = C283283 "UBQCGHPKTHXWKL-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Larock_indole_synthesis!

64 4 0 Larock_indole_synthesis C207965 "MJVUMUCHXJIYSQ-UHFFFAOYSA-N"

reactants =
[283281, 283282]

product = C207965 "MJVUMUCHXJIYSQ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Larock_indole_synthesis!

65 0 0 Grignard_addition_to_carbonyl C207977 "DMZINGXWJCZRBU-UHFFFAOYSA-N"

reactants =
[283285, 283286]

product = C207977 "DMZINGXWJCZRBU-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Grignard_addition_to_carbonyl!

65 1 0 Grignard_addition_to_carbonyl C207977 "DMZINGXWJCZRBU-UHFFFAOYSA-N"

reactants =
[283285, 283287]

product = C207977 "DMZINGXWJCZRBU-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Grignard_addition_to_carbonyl!

65 2 0 Grignard_addition_to_carbonyl C207977 "DMZINGXWJCZRBU-UHFFFAOYSA-N"

reactants =
[283285, 283286]

product = C207977 "DMZINGXWJCZRBU-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Grignard_addition_to_carbonyl!

65 3 0 Grignard_addition_to_carbonyl C207977 "DMZINGXWJCZRBU-UHFFFAOYSA-N"

reactants =
[283285, 283287]

product = C207977 "DMZINGXWJCZRBU-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Grignard_addition_to_carbonyl!

65 4 0 Grignard_addition_to_carbonyl C207977 "DMZINGXWJCZRBU-UHFFFAOYSA-N"

reactants =
[283285, 283286]

product = C207977 "DMZINGXWJCZRBU-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Grignard_addition_to_carbonyl!

66 0 0 Petasis-borono_Mannich_reaction C208797 "XXOQUOORJDYPRS-UHFFFAOYSA-N"

reactants =
[282920, 283288, 283289]

product = C208797 "XXOQUOORJDYPRS-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Petasis-borono_Mannich_reaction!

66 1 0 Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide C208797 "XXOQUOORJDYPRS-UHFFFAOYSA-N"

reactants =
[282914, 283290]

product = C208797 "XXOQUOORJDYPRS-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide!

66 2 0 Ozonolysis_(to_alcohol,_intermolecular) C208797 "XXOQUOORJDYPRS-UHFFFAOYSA-N"

reactants =
[283291]

product = C208797 "XXOQUOORJDYPRS-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Ozonolysis_(to_alcohol,_intermolecular)!

66 3 0 Carboxylic_acid_to_alcohol_reduction C208797 "XXOQUOORJDYPRS-UHFFFAOYSA-N"

reactants =
[283292]

product = C208797 "XXOQUOORJDYPRS-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Carboxylic_acid_to_alcohol_reduction!

66 4 0 Petasis-borono_Mannich_reaction C208797 "XXOQUOORJDYPRS-UHFFFAOYSA-N"

reactants =
[282920, 283288, 283293]

product = C208797 "XXOQUOORJDYPRS-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Petasis-borono_Mannich_reaction!

68 0 0 Thioether_to_sulfone C206128 "VVPKDBSEKFTDKW-UHFFFAOYSA-N"

reactants =
[283294]

product = C206128 "VVPKDBSEKFTDKW-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Thioether_to_sulfone!

68 1 0 Thioether_to_sulfone C206128 "VVPKDBSEKFTDKW-UHFFFAOYSA-N"

reactants =
[283294]

product = C206128 "VVPKDBSEKFTDKW-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Thioether_to_sulfone!

68 2 0 Thioether_to_sulfone C206128 "VVPKDBSEKFTDKW-UHFFFAOYSA-N"

reactants =
[283294]

product = C206128 "VVPKDBSEKFTDKW-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Thioether_to_sulfone!

68 3 0 Thioether_to_sulfone C206128 "VVPKDBSEKFTDKW-UHFFFAOYSA-N"

reactants =
[283294]

product = C206128 "VVPKDBSEKFTDKW-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Thioether_to_sulfone!

68 4 0 Thioether_to_sulfone C206128 "VVPKDBSEKFTDKW-UHFFFAOYSA-N"

reactants =
[283294]

product = C206128 "VVPKDBSEKFTDKW-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Thioether_to_sulfone!

69 0 0 Amidation C205775 "GRQIJMFMPOTAPA-UHFFFAOYSA-N"

 Success  registered route 20!

70 0 0 Imine_reduction_to_amine C209279 "DBUQYLDMMGGVTB-UHFFFAOYSA-N"

reactants =
[283295]

product = C209279 "DBUQYLDMMGGVTB-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Imine_reduction_to_amine!

70 1 0 Amine_alkylation C209279 "DBUQYLDMMGGVTB-UHFFFAOYSA-N"

reactants =
[283296, 283297]

product = C209279 "DBUQYLDMMGGVTB-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

70 2 0 Grignard_addition_to_carbonyl C209279 "DBUQYLDMMGGVTB-UHFFFAOYSA-N"

reactants =
[147067, 283298]

product = C209279 "DBUQYLDMMGGVTB-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Grignard_addition_to_carbonyl!

70 3 0 Imine_reduction_to_amine C209279 "DBUQYLDMMGGVTB-UHFFFAOYSA-N"

reactants =
[283295]

product = C209279 "DBUQYLDMMGGVTB-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Imine_reduction_to_amine!

70 4 0 Grignard_addition_to_epoxide C209279 "DBUQYLDMMGGVTB-UHFFFAOYSA-N"

reactants =
[283299, 283300]

product = C209279 "DBUQYLDMMGGVTB-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Grignard_addition_to_epoxide!

71 0 0 Amidation C209218 "RCJWHSZLGRRVMM-UHFFFAOYSA-N"

 Success  registered route 21!

72 0 0 Amidation C209837 "XIBNVKKKKOBXOR-UHFFFAOYSA-N"

 Success  registered route 22!

75 0 0 Reductive_amination C209458 "DEAYEWLCXYHNPI-UHFFFAOYSA-N"

75 0 1 Imine_reduction_to_amine C228293 "FVCHDJBQSPQZRF-UHFFFAOYSA-N"

reactants =
[283252]

product = C228293 "FVCHDJBQSPQZRF-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Imine_reduction_to_amine!

75 1 0 Reductive_amination C209458 "DEAYEWLCXYHNPI-UHFFFAOYSA-N"

75 1 1 Imine_reduction_to_amine C283301 "WFWNWADAJNUGEP-UHFFFAOYSA-N"

reactants =
[283302]

product = C283301 "WFWNWADAJNUGEP-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Imine_reduction_to_amine!

75 2 0 Amine_alkylation C209458 "DEAYEWLCXYHNPI-UHFFFAOYSA-N"

reactants =
[228293, 283303]

product = C209458 "DEAYEWLCXYHNPI-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

75 3 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C209458 "DEAYEWLCXYHNPI-UHFFFAOYSA-N"

75 3 1 Imine_reduction_to_amine C228293 "FVCHDJBQSPQZRF-UHFFFAOYSA-N"

reactants =
[283252]

product = C228293 "FVCHDJBQSPQZRF-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Imine_reduction_to_amine!

75 4 0 Amine_alkylation C209458 "DEAYEWLCXYHNPI-UHFFFAOYSA-N"

reactants =
[228293, 283114]

product = C209458 "DEAYEWLCXYHNPI-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

76 0 0 Amidation C209478 "DMXCSEIOVCLCAJ-UHFFFAOYSA-N"

 Success  registered route 23!

77 0 0 Stille_coupling C209486 "HYGHYRLZACCXQI-UHFFFAOYSA-N"

reactants =
[283305, 283306]

product = C209486 "HYGHYRLZACCXQI-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Stille_coupling!

77 1 0 Ester_amidation C209486 "HYGHYRLZACCXQI-UHFFFAOYSA-N"

77 2 0 Amidation C209486 "HYGHYRLZACCXQI-UHFFFAOYSA-N"

77 2 1 Sp2-sp2_Suzuki_coupling C283308 "RQHRBLCSFFBNDU-UHFFFAOYSA-N"

 Success  registered route 24!

78 0 0 Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide C248595 "OWKLMJNPJZKEQM-UHFFFAOYSA-N"

reactants =
[283311]

product = C248595 "OWKLMJNPJZKEQM-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide!

78 1 0 Ester_amidation C248595 "OWKLMJNPJZKEQM-UHFFFAOYSA-N"

78 2 0 Ester_amidation C248595 "OWKLMJNPJZKEQM-UHFFFAOYSA-N"

78 3 0 Ester_amidation C248595 "OWKLMJNPJZKEQM-UHFFFAOYSA-N"

78 4 0 Ester_amidation C248595 "OWKLMJNPJZKEQM-UHFFFAOYSA-N"

79 0 0 Reductive_amination C250249 "HSQWIPMJMKOJQO-UHFFFAOYSA-N"

 Success  registered route 25!

80 0 0 Nucleophilic_substitution_with_imine C250497 "KJWDXNNRMHUODX-UHFFFAOYSA-N"

reactants =
[283316, 283317]

product = C250497 "KJWDXNNRMHUODX-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Nucleophilic_substitution_with_imine!

80 1 0 Minisci_reaction_with_carboxylic_acid_(intermolecular) C250497 "KJWDXNNRMHUODX-UHFFFAOYSA-N"

reactants =
[283318, 283319]

product = C250497 "KJWDXNNRMHUODX-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Minisci_reaction_with_carboxylic_acid_(intermolecular)!

80 2 0 Nucleophilic_substitution_with_imine C250497 "KJWDXNNRMHUODX-UHFFFAOYSA-N"

reactants =
[283316, 283317]

product = C250497 "KJWDXNNRMHUODX-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Nucleophilic_substitution_with_imine!

80 3 0 Nucleophilic_substitution_with_imine C250497 "KJWDXNNRMHUODX-UHFFFAOYSA-N"

reactants =
[283316, 283320]

product = C250497 "KJWDXNNRMHUODX-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Nucleophilic_substitution_with_imine!

80 4 0 Nucleophilic_substitution_with_imine C250497 "KJWDXNNRMHUODX-UHFFFAOYSA-N"

reactants =
[283316, 283320]

product = C250497 "KJWDXNNRMHUODX-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Nucleophilic_substitution_with_imine!

81 0 0 Amidation C250878 "CPCIPUAOQZTFDH-UHFFFAOYSA-N"

81 1 0 Ester_amidation C250878 "CPCIPUAOQZTFDH-UHFFFAOYSA-N"

81 2 0 Ester_amidation C250878 "CPCIPUAOQZTFDH-UHFFFAOYSA-N"

81 3 0 Reductive_amination C250878 "CPCIPUAOQZTFDH-UHFFFAOYSA-N"

81 4 0 Ester_amidation C250878 "CPCIPUAOQZTFDH-UHFFFAOYSA-N"

82 0 0 Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide C250918 "CTVIJEWCBJAHCI-UHFFFAOYSA-N"

reactants =
[283325]

product = C250918 "CTVIJEWCBJAHCI-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide!

82 1 0 Sp3-sp2_Suzuki_coupling C250918 "CTVIJEWCBJAHCI-UHFFFAOYSA-N"

82 1 1 Grignard_addition_to_carbonyl C283326 "JVUPZURGYZSOFY-UHFFFAOYSA-N"

reactants =
[283327, 283328]

product = C283326 "JVUPZURGYZSOFY-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Grignard_addition_to_carbonyl!

82 2 0 Sp3-sp2_Suzuki_coupling C250918 "CTVIJEWCBJAHCI-UHFFFAOYSA-N"

82 2 1 Grignard_addition_to_carbonyl C283329 "OLNDLQZTXADEKK-UHFFFAOYSA-N"

reactants =
[283330, 283331]

product = C283329 "OLNDLQZTXADEKK-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Grignard_addition_to_carbonyl!

82 3 0 Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide C250918 "CTVIJEWCBJAHCI-UHFFFAOYSA-N"

reactants =
[283325]

product = C250918 "CTVIJEWCBJAHCI-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide!

82 4 0 Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide C250918 "CTVIJEWCBJAHCI-UHFFFAOYSA-N"

reactants =
[283332, 283333]

product = C250918 "CTVIJEWCBJAHCI-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide!

87 0 0 Amine_alkylation C263137 "ISIXDZMQJHSUKE-UHFFFAOYSA-N"

reactants =
[283334, 283335]

product = C263137 "ISIXDZMQJHSUKE-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

87 1 0 Amide_to_amine_reduction C263137 "ISIXDZMQJHSUKE-UHFFFAOYSA-N"

reactants =
[283336]

product = C263137 "ISIXDZMQJHSUKE-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amide_to_amine_reduction!

87 2 0 Reductive_amination C263137 "ISIXDZMQJHSUKE-UHFFFAOYSA-N"

87 2 1 Vilsmeier-Haack_formylation C283337 "QRPPOYOHDLKBTG-UHFFFAOYSA-N"

reactants =
[283338, 283339]

product = C283337 "QRPPOYOHDLKBTG-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Vilsmeier-Haack_formylation!

87 3 0 Amide_to_amine_reduction C263137 "ISIXDZMQJHSUKE-UHFFFAOYSA-N"

reactants =
[283336]

product = C263137 "ISIXDZMQJHSUKE-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amide_to_amine_reduction!

87 4 0 Amine_alkylation C263137 "ISIXDZMQJHSUKE-UHFFFAOYSA-N"

reactants =
[283335, 283340]

product = C263137 "ISIXDZMQJHSUKE-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

88 0 0 Amidation C207759 "WEZNMCCECZERHN-UHFFFAOYSA-N"

88 0 1 Buchwald-Hartwig_amination C282958 "NGDHLAXYVVTRSU-UHFFFAOYSA-N"

 Success  registered route 26!

89 0 0 Buchwald-Hartwig_amidation_with_amide-like_nucleophile C264290 "GPNKYXTWBNHZPT-UHFFFAOYSA-N"

89 0 1 N-acylation_of_amide C138686 "FYXHBQCWFRWHBD-UHFFFAOYSA-N"

reactants =
[173295, 283342]

product = C138686 "FYXHBQCWFRWHBD-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: N-acylation_of_amide!

89 1 0 Alpha_alkylation_of_ester/amide C264290 "GPNKYXTWBNHZPT-UHFFFAOYSA-N"

reactants =
[283343]

product = C264290 "GPNKYXTWBNHZPT-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ester/amide!

89 2 0 Alpha_alkylation_of_ester/amide C264290 "GPNKYXTWBNHZPT-UHFFFAOYSA-N"

reactants =
[283344]

product = C264290 "GPNKYXTWBNHZPT-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ester/amide!

89 3 0 Alpha_alkylation_of_ester/amide C264290 "GPNKYXTWBNHZPT-UHFFFAOYSA-N"

reactants =
[283345]

product = C264290 "GPNKYXTWBNHZPT-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ester/amide!

89 4 0 Alpha_alkylation_of_ester/amide C264290 "GPNKYXTWBNHZPT-UHFFFAOYSA-N"

reactants =
[283343]

product = C264290 "GPNKYXTWBNHZPT-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ester/amide!

91 0 0 Alpha_alkylation_of_ester/amide C164254 "KFFAPYJDDXEIJM-UHFFFAOYSA-N"

reactants =
[282961]

product = C164254 "KFFAPYJDDXEIJM-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ester/amide!

91 1 0 Alpha_alkylation_of_ester/amide C164254 "KFFAPYJDDXEIJM-UHFFFAOYSA-N"

reactants =
[282962]

product = C164254 "KFFAPYJDDXEIJM-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ester/amide!

91 2 0 Alpha_alkylation_of_ester/amide C164254 "KFFAPYJDDXEIJM-UHFFFAOYSA-N"

reactants =
[282963]

product = C164254 "KFFAPYJDDXEIJM-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ester/amide!

91 3 0 Alpha_alkylation_of_ester/amide C164254 "KFFAPYJDDXEIJM-UHFFFAOYSA-N"

reactants =
[282962]

product = C164254 "KFFAPYJDDXEIJM-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ester/amide!

91 4 0 Alpha_alkylation_of_ester/amide C164254 "KFFAPYJDDXEIJM-UHFFFAOYSA-N"

reactants =
[282962]

product = C164254 "KFFAPYJDDXEIJM-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ester/amide!

92 0 0 Iodo_N-arylation C264587 "DGJUFCWDGCHNHJ-UHFFFAOYSA-N"

reactants =
[138541, 283346]

product = C264587 "DGJUFCWDGCHNHJ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Iodo_N-arylation!

92 1 0 Formation_of_urea_from_two_amines C264587 "DGJUFCWDGCHNHJ-UHFFFAOYSA-N"

92 1 1 Grignard_addition_to_carbonyl C283347 "PFPIRUMIORKDBU-UHFFFAOYSA-N"

reactants =
[283348, 283349]

product = C283347 "PFPIRUMIORKDBU-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Grignard_addition_to_carbonyl!

92 2 0 Buchwald-Hartwig_amidation_with_amide-like_nucleophile C264587 "DGJUFCWDGCHNHJ-UHFFFAOYSA-N"

92 2 1 Grignard_addition_to_carbonyl C283350 "DHHFFSRPMPWXNJ-UHFFFAOYSA-N"

reactants =
[283349, 283351]

product = C283350 "DHHFFSRPMPWXNJ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Grignard_addition_to_carbonyl!

92 3 0 Iodo_N-arylation C264587 "DGJUFCWDGCHNHJ-UHFFFAOYSA-N"

reactants =
[138541, 283346]

product = C264587 "DGJUFCWDGCHNHJ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Iodo_N-arylation!

92 4 0 Buchwald-Hartwig_amidation_with_amide-like_nucleophile C264587 "DGJUFCWDGCHNHJ-UHFFFAOYSA-N"

92 4 1 Grignard_addition_to_carbonyl C283346 "NIFULVVRRWKGND-UHFFFAOYSA-N"

reactants =
[283352, 283353]

product = C283346 "NIFULVVRRWKGND-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Grignard_addition_to_carbonyl!

95 0 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C189983 "HWXYDZKCQZODDY-UHFFFAOYSA-N"

95 0 1 Amidation C283354 "ZENPCQFYBJWAIX-UHFFFAOYSA-N"

95 0 2 Aldehyde/ketone_to_alcohol_reduction C283355 "UNWSRBYWBWAQDF-UHFFFAOYSA-N"

reactants =
[283356]

product = C283355 "UNWSRBYWBWAQDF-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Aldehyde/ketone_to_alcohol_reduction!

95 1 0 Ozonolysis_(intermolecular) C189983 "HWXYDZKCQZODDY-UHFFFAOYSA-N"

reactants =
[283357]

product = C189983 "HWXYDZKCQZODDY-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Ozonolysis_(intermolecular)!

95 2 0 Swern_oxidation C189983 "HWXYDZKCQZODDY-UHFFFAOYSA-N"

reactants =
[283358]

product = C189983 "HWXYDZKCQZODDY-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Swern_oxidation!

95 3 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C189983 "HWXYDZKCQZODDY-UHFFFAOYSA-N"

95 3 1 Aldehyde/ketone_to_alcohol_reduction C283354 "ZENPCQFYBJWAIX-UHFFFAOYSA-N"

reactants =
[283359]

product = C283354 "ZENPCQFYBJWAIX-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Aldehyde/ketone_to_alcohol_reduction!

95 4 0 Amidation C189983 "HWXYDZKCQZODDY-UHFFFAOYSA-N"

95 4 1 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C283360 "VJNVLUOYWWUXFQ-UHFFFAOYSA-N"

95 4 2 Aldehyde/ketone_to_alcohol_reduction C283355 "UNWSRBYWBWAQDF-UHFFFAOYSA-N"

reactants =
[283356]

product = C283355 "UNWSRBYWBWAQDF-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Aldehyde/ketone_to_alcohol_reduction!

96 0 0 Amidation C266892 "MHJINKMDGLJYJH-UHFFFAOYSA-N"

 Success  registered route 27!

97 0 0 Amidation C264727 "FDGRSYLWCHGFJP-UHFFFAOYSA-N"

 Success  registered route 28!

98 0 0 Amidation C138541 "QHSCXGMDNOKEGD-UHFFFAOYSA-N"

 Success  registered route 29!

99 0 0 Amidation C178840 "JTCJLGZQLBXCSL-UHFFFAOYSA-N"

99 1 0 Ester_amidation C178840 "JTCJLGZQLBXCSL-UHFFFAOYSA-N"

99 2 0 Mannich_reaction C178840 "JTCJLGZQLBXCSL-UHFFFAOYSA-N"

reactants =
[283363]

product = C178840 "JTCJLGZQLBXCSL-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Mannich_reaction!

99 3 0 Amidation C178840 "JTCJLGZQLBXCSL-UHFFFAOYSA-N"

99 4 0 Mannich_reaction C178840 "JTCJLGZQLBXCSL-UHFFFAOYSA-N"

reactants =
[283363]

product = C178840 "JTCJLGZQLBXCSL-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Mannich_reaction!

105 0 0 Alpha-arylation C263060 "ZBXRXFNVZOUTEP-UHFFFAOYSA-N"

reactants =
[139290, 283364]

product = C263060 "ZBXRXFNVZOUTEP-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha-arylation!

105 1 0 Friedel-Crafts_methylation C263060 "ZBXRXFNVZOUTEP-UHFFFAOYSA-N"

reactants =
[283365]

product = C263060 "ZBXRXFNVZOUTEP-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Friedel-Crafts_methylation!

105 2 0 Ester_amidation C263060 "ZBXRXFNVZOUTEP-UHFFFAOYSA-N"

105 3 0 Corey-House_synthesis_(intermolecular) C263060 "ZBXRXFNVZOUTEP-UHFFFAOYSA-N"

reactants =
[283367, 283368]

product = C263060 "ZBXRXFNVZOUTEP-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Corey-House_synthesis_(intermolecular)!

105 4 0 Buchwald-Hartwig_amination C263060 "ZBXRXFNVZOUTEP-UHFFFAOYSA-N"

105 4 1 Ester_amidation C283369 "BZHYJYAZZMMRDZ-UHFFFAOYSA-N"

106 0 0 Alpha_alkylation_of_ester/amide C267601 "UMYBGOBPHOVEQB-UHFFFAOYSA-N"

reactants =
[283371]

product = C267601 "UMYBGOBPHOVEQB-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ester/amide!

106 1 0 Alpha_alkylation_of_ester/amide C267601 "UMYBGOBPHOVEQB-UHFFFAOYSA-N"

reactants =
[283372]

product = C267601 "UMYBGOBPHOVEQB-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ester/amide!

106 2 0 Alpha_alkylation_of_ester/amide C267601 "UMYBGOBPHOVEQB-UHFFFAOYSA-N"

reactants =
[283373]

product = C267601 "UMYBGOBPHOVEQB-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ester/amide!

106 3 0 Alpha_alkylation_of_ester/amide C267601 "UMYBGOBPHOVEQB-UHFFFAOYSA-N"

reactants =
[283371]

product = C267601 "UMYBGOBPHOVEQB-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ester/amide!

106 4 0 Alpha_alkylation_of_ester/amide C267601 "UMYBGOBPHOVEQB-UHFFFAOYSA-N"

reactants =
[283371]

product = C267601 "UMYBGOBPHOVEQB-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ester/amide!

109 0 0 Petasis-borono_Mannich_reaction C192018 "PVWWIGZYJBKIAA-UHFFFAOYSA-N"

reactants =
[282967, 283374, 283375]

product = C192018 "PVWWIGZYJBKIAA-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Petasis-borono_Mannich_reaction!

109 1 0 Amine_alkylation C192018 "PVWWIGZYJBKIAA-UHFFFAOYSA-N"

reactants =
[283123, 283376]

product = C192018 "PVWWIGZYJBKIAA-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

109 2 0 Alkyne_TMS_deprotection C192018 "PVWWIGZYJBKIAA-UHFFFAOYSA-N"

reactants =
[283377]

product = C192018 "PVWWIGZYJBKIAA-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alkyne_TMS_deprotection!

109 3 0 Sp3-sp2_Suzuki_coupling C192018 "PVWWIGZYJBKIAA-UHFFFAOYSA-N"

109 3 1 Petasis-borono_Mannich_reaction C283378 "FUKLRHYUNHQYJM-UHFFFAOYSA-N"

reactants =
[283374, 283375, 283380]

product = C283378 "FUKLRHYUNHQYJM-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Petasis-borono_Mannich_reaction!

109 4 0 Reductive_amination C192018 "PVWWIGZYJBKIAA-UHFFFAOYSA-N"

 Success  registered route 30!

111 0 0 Amidation C211420 "KINPTNKBZKLBEK-UHFFFAOYSA-N"

 Success  registered route 31!

114 0 0 Isocyanate_to_urea C264563 "QYCKRLPOQMCSGI-UHFFFAOYSA-N"

reactants =
[202220, 283381]

product = C264563 "QYCKRLPOQMCSGI-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Isocyanate_to_urea!

114 1 0 Iodo_N-arylation C264563 "QYCKRLPOQMCSGI-UHFFFAOYSA-N"

reactants =
[138541, 282971]

product = C264563 "QYCKRLPOQMCSGI-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Iodo_N-arylation!

114 2 0 Formation_of_urea_from_two_amines C264563 "QYCKRLPOQMCSGI-UHFFFAOYSA-N"

 Success  registered route 32!

115 0 0 Amidation C176894 "PSIYEGSIAUUUKH-UHFFFAOYSA-N"

 Success  registered route 33!

117 0 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C193826 "FNNHSCZUTYNJDJ-UHFFFAOYSA-N"

117 0 1 Aldehyde/ketone_to_alcohol_reduction C283382 "DVBQPLWXZXWLPP-UHFFFAOYSA-N"

reactants =
[283383]

product = C283382 "DVBQPLWXZXWLPP-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Aldehyde/ketone_to_alcohol_reduction!

117 1 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C193826 "FNNHSCZUTYNJDJ-UHFFFAOYSA-N"

117 1 1 Aldehyde/ketone_to_alcohol_reduction C283382 "DVBQPLWXZXWLPP-UHFFFAOYSA-N"

reactants =
[283383]

product = C283382 "DVBQPLWXZXWLPP-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Aldehyde/ketone_to_alcohol_reduction!

117 2 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C193826 "FNNHSCZUTYNJDJ-UHFFFAOYSA-N"

117 2 1 Aldehyde/ketone_to_alcohol_reduction C283382 "DVBQPLWXZXWLPP-UHFFFAOYSA-N"

reactants =
[283383]

product = C283382 "DVBQPLWXZXWLPP-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Aldehyde/ketone_to_alcohol_reduction!

117 3 0 Methylation_of_alcohol C193826 "FNNHSCZUTYNJDJ-UHFFFAOYSA-N"

reactants =
[283382]

product = C193826 "FNNHSCZUTYNJDJ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Methylation_of_alcohol!

117 4 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C193826 "FNNHSCZUTYNJDJ-UHFFFAOYSA-N"

117 4 1 Aldehyde/ketone_to_alcohol_reduction C283382 "DVBQPLWXZXWLPP-UHFFFAOYSA-N"

reactants =
[283383]

product = C283382 "DVBQPLWXZXWLPP-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Aldehyde/ketone_to_alcohol_reduction!

119 0 0 Amine_alkylation C192498 "XEWCIHXKBKXNHS-UHFFFAOYSA-N"

reactants =
[283243, 283384]

product = C192498 "XEWCIHXKBKXNHS-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

119 1 0 Amine_alkylation C192498 "XEWCIHXKBKXNHS-UHFFFAOYSA-N"

reactants =
[283243, 283385]

product = C192498 "XEWCIHXKBKXNHS-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

119 2 0 Amine_alkylation C192498 "XEWCIHXKBKXNHS-UHFFFAOYSA-N"

reactants =
[283243, 283386]

product = C192498 "XEWCIHXKBKXNHS-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

119 3 0 Amine_alkylation C192498 "XEWCIHXKBKXNHS-UHFFFAOYSA-N"

reactants =
[283243, 283384]

product = C192498 "XEWCIHXKBKXNHS-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

119 4 0 Amine_alkylation C192498 "XEWCIHXKBKXNHS-UHFFFAOYSA-N"

reactants =
[283243, 283384]

product = C192498 "XEWCIHXKBKXNHS-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

120 0 0 Alpha-arylation C166559 "FTPLNKSHYLFOCK-UHFFFAOYSA-N"

reactants =
[283387]

product = C166559 "FTPLNKSHYLFOCK-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha-arylation!

120 1 0 Alpha_alkylation_of_ester/amide C166559 "FTPLNKSHYLFOCK-UHFFFAOYSA-N"

reactants =
[283388, 283389]

product = C166559 "FTPLNKSHYLFOCK-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ester/amide!

120 2 0 Ester_amidation C166559 "FTPLNKSHYLFOCK-UHFFFAOYSA-N"

120 2 1 Alpha-arylation C283390 "TTXMJGHUTUHCTF-UHFFFAOYSA-N"

reactants =
[283391]

product = C283390 "TTXMJGHUTUHCTF-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha-arylation!

120 3 0 Alpha-arylation C166559 "FTPLNKSHYLFOCK-UHFFFAOYSA-N"

reactants =
[283387]

product = C166559 "FTPLNKSHYLFOCK-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha-arylation!

120 4 0 Ester_amidation C166559 "FTPLNKSHYLFOCK-UHFFFAOYSA-N"

121 0 0 Ester_amidation C193333 "GYHNELMRIHFZDX-UHFFFAOYSA-N"

121 1 0 Ester_amidation C193333 "GYHNELMRIHFZDX-UHFFFAOYSA-N"

121 2 0 Amidation C193333 "GYHNELMRIHFZDX-UHFFFAOYSA-N"

121 2 1 Alpha_alkylation_of_ester/amide C282977 "WFBPMYOTYMINLN-UHFFFAOYSA-N"

reactants =
[282978]

product = C282977 "WFBPMYOTYMINLN-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ester/amide!

121 3 0 Ester_amidation C193333 "GYHNELMRIHFZDX-UHFFFAOYSA-N"

121 3 1 Alpha_alkylation_of_ester/amide C282979 "CUXSRYWBDJFTFD-UHFFFAOYSA-N"

reactants =
[282980]

product = C282979 "CUXSRYWBDJFTFD-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ester/amide!

121 4 0 Alpha_alkylation_of_ester/amide C193333 "GYHNELMRIHFZDX-UHFFFAOYSA-N"

reactants =
[282981]

product = C193333 "GYHNELMRIHFZDX-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ester/amide!

122 0 0 Amidation C195109 "KLIJUPNPMOMPIT-UHFFFAOYSA-N"

 Success  registered route 34!

126 0 0 Buchwald-Hartwig_(thio)etherification C280132 "YWPKEXDUKMIEPU-UHFFFAOYSA-N"

reactants =
[283393, 283394]

product = C280132 "YWPKEXDUKMIEPU-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Buchwald-Hartwig_(thio)etherification!

126 1 0 Buchwald-Hartwig_(thio)etherification C280132 "YWPKEXDUKMIEPU-UHFFFAOYSA-N"

reactants =
[283393, 283394]

product = C280132 "YWPKEXDUKMIEPU-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Buchwald-Hartwig_(thio)etherification!

126 2 0 Buchwald-Hartwig_(thio)etherification C280132 "YWPKEXDUKMIEPU-UHFFFAOYSA-N"

reactants =
[283393, 283394]

product = C280132 "YWPKEXDUKMIEPU-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Buchwald-Hartwig_(thio)etherification!

126 3 0 Buchwald-Hartwig_(thio)etherification C280132 "YWPKEXDUKMIEPU-UHFFFAOYSA-N"

reactants =
[283393, 283395]

product = C280132 "YWPKEXDUKMIEPU-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Buchwald-Hartwig_(thio)etherification!

126 4 0 Buchwald-Hartwig_(thio)etherification C280132 "YWPKEXDUKMIEPU-UHFFFAOYSA-N"

reactants =
[283393, 283395]

product = C280132 "YWPKEXDUKMIEPU-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Buchwald-Hartwig_(thio)etherification!

127 0 0 Amine_alkylation C280144 "TXMSFQQPVYLOJC-UHFFFAOYSA-N"

reactants =
[283396, 283397]

product = C280144 "TXMSFQQPVYLOJC-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

127 1 0 Chan-Lam_coupling_of_amides,_sulfonamides,_and_imides C280144 "TXMSFQQPVYLOJC-UHFFFAOYSA-N"

reactants =
[282931, 283398]

product = C280144 "TXMSFQQPVYLOJC-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Chan-Lam_coupling_of_amides,_sulfonamides,_and_imides!

127 2 0 Amine_alkylation C280144 "TXMSFQQPVYLOJC-UHFFFAOYSA-N"

reactants =
[283397, 283399]

product = C280144 "TXMSFQQPVYLOJC-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

127 3 0 Buchwald-Hartwig_amidation_with_amide-like_nucleophile C280144 "TXMSFQQPVYLOJC-UHFFFAOYSA-N"

127 3 1 Amine_alkylation C283400 "CDDVDAXKCPXDOK-UHFFFAOYSA-N"

reactants =
[283396, 283401]

product = C283400 "CDDVDAXKCPXDOK-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

127 4 0 Buchwald-Hartwig_amidation_with_amide-like_nucleophile C280144 "TXMSFQQPVYLOJC-UHFFFAOYSA-N"

127 4 1 Amine_alkylation C283402 "WVPXDFXYLZOUIH-UHFFFAOYSA-N"

reactants =
[283403, 283404]

product = C283402 "WVPXDFXYLZOUIH-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

139 0 0 NHK_reaction C177719 "WECSMDFTHCGFKA-UHFFFAOYSA-N"

reactants =
[283405, 283406]

product = C177719 "WECSMDFTHCGFKA-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: NHK_reaction!

139 1 0 NHK_reaction C177719 "WECSMDFTHCGFKA-UHFFFAOYSA-N"

reactants =
[283111, 283407]

product = C177719 "WECSMDFTHCGFKA-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: NHK_reaction!

139 2 0 Grignard_addition_to_carbonyl C177719 "WECSMDFTHCGFKA-UHFFFAOYSA-N"

reactants =
[283408, 283409]

product = C177719 "WECSMDFTHCGFKA-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Grignard_addition_to_carbonyl!

139 3 0 Grignard_addition_to_carbonyl C177719 "WECSMDFTHCGFKA-UHFFFAOYSA-N"

reactants =
[283349, 283410]

product = C177719 "WECSMDFTHCGFKA-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Grignard_addition_to_carbonyl!

139 4 0 NHK_reaction C177719 "WECSMDFTHCGFKA-UHFFFAOYSA-N"

reactants =
[283111, 283411]

product = C177719 "WECSMDFTHCGFKA-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: NHK_reaction!

142 0 0 Amidation C160667 "MLUYARBKPLLQGO-UHFFFAOYSA-N"

142 0 1 Reductive_amination C283412 "FBNVECSFMPOEGE-UHFFFAOYSA-N"

142 0 2 Alpha_alkylation_of_ketone C283413 "LKYPRSREKAGEKM-UHFFFAOYSA-N"

reactants =
[283415, 283416]

product = C283413 "LKYPRSREKAGEKM-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ketone!

142 1 0 Reductive_amination C160667 "MLUYARBKPLLQGO-UHFFFAOYSA-N"

142 1 1 Alpha_alkylation_of_ketone C283417 "YGSRQHIKGZETDR-UHFFFAOYSA-N"

reactants =
[283418, 283419]

product = C283417 "YGSRQHIKGZETDR-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ketone!

142 2 0 Amidation C160667 "MLUYARBKPLLQGO-UHFFFAOYSA-N"

142 2 1 Reductive_amination C283412 "FBNVECSFMPOEGE-UHFFFAOYSA-N"

142 2 2 Alpha_alkylation_of_ketone C283413 "LKYPRSREKAGEKM-UHFFFAOYSA-N"

reactants =
[283415, 283420]

product = C283413 "LKYPRSREKAGEKM-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ketone!

142 3 0 Amidation C160667 "MLUYARBKPLLQGO-UHFFFAOYSA-N"

142 3 1 Reductive_amination C283412 "FBNVECSFMPOEGE-UHFFFAOYSA-N"

142 3 2 Alpha_alkylation_of_ketone C283413 "LKYPRSREKAGEKM-UHFFFAOYSA-N"

reactants =
[283415, 283419]

product = C283413 "LKYPRSREKAGEKM-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ketone!

142 4 0 Reductive_amination C160667 "MLUYARBKPLLQGO-UHFFFAOYSA-N"

142 4 1 Amidation C283417 "YGSRQHIKGZETDR-UHFFFAOYSA-N"

142 4 2 Alpha_alkylation_of_ketone C283413 "LKYPRSREKAGEKM-UHFFFAOYSA-N"

reactants =
[283415, 283416]

product = C283413 "LKYPRSREKAGEKM-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ketone!

144 0 0 Iodo_N-arylation C160793 "BQNACJRNYISVSZ-UHFFFAOYSA-N"

reactants =
[138541, 283421]

product = C160793 "BQNACJRNYISVSZ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Iodo_N-arylation!

144 1 0 Buchwald-Hartwig_amidation_with_amide-like_nucleophile C160793 "BQNACJRNYISVSZ-UHFFFAOYSA-N"

144 1 1 Amine_alkylation C283422 "QNUBVZLWMODUAY-UHFFFAOYSA-N"

reactants =
[283126, 283423]

product = C283422 "QNUBVZLWMODUAY-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

144 2 0 Buchwald-Hartwig_amidation_with_amide-like_nucleophile C160793 "BQNACJRNYISVSZ-UHFFFAOYSA-N"

144 2 1 Amine_alkylation C283424 "ZEPZTLXPIGOFSP-UHFFFAOYSA-N"

reactants =
[283123, 283425]

product = C283424 "ZEPZTLXPIGOFSP-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

144 3 0 Iodo_N-arylation C160793 "BQNACJRNYISVSZ-UHFFFAOYSA-N"

reactants =
[138541, 283421]

product = C160793 "BQNACJRNYISVSZ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Iodo_N-arylation!

144 4 0 Iodo_N-arylation C160793 "BQNACJRNYISVSZ-UHFFFAOYSA-N"

reactants =
[138541, 283421]

product = C160793 "BQNACJRNYISVSZ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Iodo_N-arylation!

145 0 0 Buchwald-Hartwig_amidation_with_amide-like_nucleophile C159094 "YVPORMJUNHFFRP-UHFFFAOYSA-N"

145 0 1 Amidation C176936 "GFHLFLFRWWDWPS-UHFFFAOYSA-N"

 Success  registered route 35!

146 0 0 N-Boc_deprotection C155988 "VMAHPGKKKWPAJU-UHFFFAOYSA-N"

146 0 1 Corey-House_synthesis_(intermolecular) C283426 "GQFLLDWFKDDEAA-UHFFFAOYSA-N"

reactants =
[283427, 283428]

product = C283426 "GQFLLDWFKDDEAA-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Corey-House_synthesis_(intermolecular)!

146 1 0 Corey-House_synthesis_(intermolecular) C155988 "VMAHPGKKKWPAJU-UHFFFAOYSA-N"

reactants =
[283427, 283429]

product = C155988 "VMAHPGKKKWPAJU-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Corey-House_synthesis_(intermolecular)!

146 2 0 N-Boc_deprotection C155988 "VMAHPGKKKWPAJU-UHFFFAOYSA-N"

146 2 1 Corey-House_synthesis_(intermolecular) C283426 "GQFLLDWFKDDEAA-UHFFFAOYSA-N"

reactants =
[283427, 283428]

product = C283426 "GQFLLDWFKDDEAA-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Corey-House_synthesis_(intermolecular)!

146 3 0 Corey-House_synthesis_(intermolecular) C155988 "VMAHPGKKKWPAJU-UHFFFAOYSA-N"

reactants =
[283427, 283429]

product = C155988 "VMAHPGKKKWPAJU-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Corey-House_synthesis_(intermolecular)!

146 4 0 N-Boc_deprotection C155988 "VMAHPGKKKWPAJU-UHFFFAOYSA-N"

146 4 1 Corey-House_synthesis_(intermolecular) C283426 "GQFLLDWFKDDEAA-UHFFFAOYSA-N"

reactants =
[283427, 283428]

product = C283426 "GQFLLDWFKDDEAA-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Corey-House_synthesis_(intermolecular)!

147 0 0 Hydrogenation_of_pyridine C160224 "VMRRETVEFLYQLB-UHFFFAOYSA-N"

reactants =
[283430]

product = C160224 "VMRRETVEFLYQLB-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Hydrogenation_of_pyridine!

147 1 0 Hydrogenation_of_pyridine C160224 "VMRRETVEFLYQLB-UHFFFAOYSA-N"

reactants =
[283430]

product = C160224 "VMRRETVEFLYQLB-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Hydrogenation_of_pyridine!

147 2 0 Hydrogenation_of_pyridine C160224 "VMRRETVEFLYQLB-UHFFFAOYSA-N"

reactants =
[283430]

product = C160224 "VMRRETVEFLYQLB-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Hydrogenation_of_pyridine!

147 3 0 Hydrogenation_of_pyridine C160224 "VMRRETVEFLYQLB-UHFFFAOYSA-N"

reactants =
[283430]

product = C160224 "VMRRETVEFLYQLB-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Hydrogenation_of_pyridine!

147 4 0 Hydrogenation_of_pyridine C160224 "VMRRETVEFLYQLB-UHFFFAOYSA-N"

reactants =
[283430]

product = C160224 "VMRRETVEFLYQLB-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Hydrogenation_of_pyridine!

149 0 0 Amidation C161860 "UWUWVBJAARDSSL-UHFFFAOYSA-N"

 Success  registered route 36!

156 0 0 Sp3-sp2_Suzuki_coupling C236405 "PNIRUYFAVYSKGX-UHFFFAOYSA-N"

156 0 1 Amine_alkylation C283431 "HXWJUMPBKRAQOE-UHFFFAOYSA-N"

reactants =
[283432, 283433]

product = C283431 "HXWJUMPBKRAQOE-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

156 1 0 Sp3-sp2_Suzuki_coupling C236405 "PNIRUYFAVYSKGX-UHFFFAOYSA-N"

156 1 1 Amine_alkylation C283431 "HXWJUMPBKRAQOE-UHFFFAOYSA-N"

reactants =
[283432, 283434]

product = C283431 "HXWJUMPBKRAQOE-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

156 2 0 Amine_alkylation C236405 "PNIRUYFAVYSKGX-UHFFFAOYSA-N"

reactants =
[283435]

product = C236405 "PNIRUYFAVYSKGX-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

156 3 0 Sp3-sp2_Suzuki_coupling C236405 "PNIRUYFAVYSKGX-UHFFFAOYSA-N"

156 3 1 Amine_alkylation C283431 "HXWJUMPBKRAQOE-UHFFFAOYSA-N"

reactants =
[283432, 283433]

product = C283431 "HXWJUMPBKRAQOE-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

156 4 0 N-nucleophilic_aromatic_substitution C236405 "PNIRUYFAVYSKGX-UHFFFAOYSA-N"

159 0 0 Alpha_alkylation_of_ketone C215084 "PBUVVEGHRQRWFC-UHFFFAOYSA-N"

reactants =
[283437, 283438]

product = C215084 "PBUVVEGHRQRWFC-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ketone!

159 1 0 Williamson_ether_synthesis C215084 "PBUVVEGHRQRWFC-UHFFFAOYSA-N"

159 1 1 Alpha_alkylation_of_ketone C283439 "QRVWFKJUWIIIDN-UHFFFAOYSA-N"

reactants =
[283440, 283441]

product = C283439 "QRVWFKJUWIIIDN-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ketone!

159 2 0 Alpha-arylation C215084 "PBUVVEGHRQRWFC-UHFFFAOYSA-N"

reactants =
[283442, 283443]

product = C215084 "PBUVVEGHRQRWFC-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha-arylation!

159 3 0 Oxa-Michael_addition C215084 "PBUVVEGHRQRWFC-UHFFFAOYSA-N"

reactants =
[283444]

product = C215084 "PBUVVEGHRQRWFC-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Oxa-Michael_addition!

159 4 0 Williamson_ether_synthesis C215084 "PBUVVEGHRQRWFC-UHFFFAOYSA-N"

160 0 0 Corey-House_synthesis_(intermolecular) C216188 "UVRVNMDNGVIBGM-UHFFFAOYSA-N"

reactants =
[189853, 283163]

product = C216188 "UVRVNMDNGVIBGM-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Corey-House_synthesis_(intermolecular)!

160 1 0 Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide C216188 "UVRVNMDNGVIBGM-UHFFFAOYSA-N"

reactants =
[283446]

product = C216188 "UVRVNMDNGVIBGM-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide!

160 2 0 Alkene_hydrogenation_(unconjugated) C216188 "UVRVNMDNGVIBGM-UHFFFAOYSA-N"

reactants =
[283447]

product = C216188 "UVRVNMDNGVIBGM-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alkene_hydrogenation_(unconjugated)!

160 3 0 Friedel-Crafts_methylation C216188 "UVRVNMDNGVIBGM-UHFFFAOYSA-N"

reactants =
[140710]

product = C216188 "UVRVNMDNGVIBGM-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Friedel-Crafts_methylation!

160 4 0 Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide C216188 "UVRVNMDNGVIBGM-UHFFFAOYSA-N"

reactants =
[283448]

product = C216188 "UVRVNMDNGVIBGM-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide!

161 0 0 Alkene_hydrogenation_(unconjugated) C216355 "HYQPAIHEMGSSJO-UHFFFAOYSA-N"

reactants =
[283449]

product = C216355 "HYQPAIHEMGSSJO-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alkene_hydrogenation_(unconjugated)!

161 1 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C216355 "HYQPAIHEMGSSJO-UHFFFAOYSA-N"

161 2 0 Swern_oxidation C216355 "HYQPAIHEMGSSJO-UHFFFAOYSA-N"

reactants =
[283451]

product = C216355 "HYQPAIHEMGSSJO-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Swern_oxidation!

161 3 0 Sp3-sp2_Macmillan_coupling_with_chloride_(intermolecular) C216355 "HYQPAIHEMGSSJO-UHFFFAOYSA-N"

reactants =
[283452, 283453]

product = C216355 "HYQPAIHEMGSSJO-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sp3-sp2_Macmillan_coupling_with_chloride_(intermolecular)!

161 4 0 Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide C216355 "HYQPAIHEMGSSJO-UHFFFAOYSA-N"

reactants =
[283454, 283455]

product = C216355 "HYQPAIHEMGSSJO-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide!

162 0 0 Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide C216357 "HUSFWJZEUFNZSQ-UHFFFAOYSA-N"

reactants =
[283456]

product = C216357 "HUSFWJZEUFNZSQ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide!

162 1 0 Sp3-sp2_Macmillan_coupling_with_chloride_(intermolecular) C216357 "HUSFWJZEUFNZSQ-UHFFFAOYSA-N"

reactants =
[283457]

product = C216357 "HUSFWJZEUFNZSQ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sp3-sp2_Macmillan_coupling_with_chloride_(intermolecular)!

162 2 0 Sp3-sp2_Macmillan_coupling_with_bromide_(intermolecular) C216357 "HUSFWJZEUFNZSQ-UHFFFAOYSA-N"

reactants =
[283458]

product = C216357 "HUSFWJZEUFNZSQ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sp3-sp2_Macmillan_coupling_with_bromide_(intermolecular)!

162 3 0 Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide C216357 "HUSFWJZEUFNZSQ-UHFFFAOYSA-N"

reactants =
[283456]

product = C216357 "HUSFWJZEUFNZSQ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide!

162 4 0 Sp3-sp2_Macmillan_coupling_with_chloride_(intermolecular) C216357 "HUSFWJZEUFNZSQ-UHFFFAOYSA-N"

reactants =
[283457]

product = C216357 "HUSFWJZEUFNZSQ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sp3-sp2_Macmillan_coupling_with_chloride_(intermolecular)!

163 0 0 Alkene_hydrogenation_(unconjugated) C216360 "LMIJHJCABBMJTL-UHFFFAOYSA-N"

reactants =
[283459]

product = C216360 "LMIJHJCABBMJTL-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alkene_hydrogenation_(unconjugated)!

163 1 0 Alkene_hydrogenation_(unconjugated) C216360 "LMIJHJCABBMJTL-UHFFFAOYSA-N"

reactants =
[283459]

product = C216360 "LMIJHJCABBMJTL-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alkene_hydrogenation_(unconjugated)!

163 2 0 Alkene_hydrogenation_(unconjugated) C216360 "LMIJHJCABBMJTL-UHFFFAOYSA-N"

reactants =
[283459]

product = C216360 "LMIJHJCABBMJTL-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alkene_hydrogenation_(unconjugated)!

163 3 0 Alkene_hydrogenation_(unconjugated) C216360 "LMIJHJCABBMJTL-UHFFFAOYSA-N"

reactants =
[283459]

product = C216360 "LMIJHJCABBMJTL-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alkene_hydrogenation_(unconjugated)!

163 4 0 Alkene_hydrogenation_(unconjugated) C216360 "LMIJHJCABBMJTL-UHFFFAOYSA-N"

reactants =
[283459]

product = C216360 "LMIJHJCABBMJTL-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alkene_hydrogenation_(unconjugated)!

164 0 0 Ring_closing_metathesis C216367 "CCWJSDMCVYJGGM-UHFFFAOYSA-N"

reactants =
[283460]

product = C216367 "CCWJSDMCVYJGGM-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Ring_closing_metathesis!

164 1 0 Ring_closing_metathesis C216367 "CCWJSDMCVYJGGM-UHFFFAOYSA-N"

reactants =
[283461]

product = C216367 "CCWJSDMCVYJGGM-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Ring_closing_metathesis!

164 2 0 Heck_reaction_(intermolecular) C216367 "CCWJSDMCVYJGGM-UHFFFAOYSA-N"

reactants =
[283462, 283463]

product = C216367 "CCWJSDMCVYJGGM-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Heck_reaction_(intermolecular)!

164 3 0 Ring_closing_metathesis C216367 "CCWJSDMCVYJGGM-UHFFFAOYSA-N"

reactants =
[283464]

product = C216367 "CCWJSDMCVYJGGM-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Ring_closing_metathesis!

164 4 0 Ring_closing_metathesis C216367 "CCWJSDMCVYJGGM-UHFFFAOYSA-N"

reactants =
[283465]

product = C216367 "CCWJSDMCVYJGGM-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Ring_closing_metathesis!

166 0 0 Sp3-sp2_Suzuki_coupling C216415 "IAGKFRITHIIXME-UHFFFAOYSA-N"

166 1 0 Williamson_ether_synthesis C216415 "IAGKFRITHIIXME-UHFFFAOYSA-N"

166 2 0 Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide C216415 "IAGKFRITHIIXME-UHFFFAOYSA-N"

reactants =
[283468]

product = C216415 "IAGKFRITHIIXME-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide!

166 3 0 Williamson_ether_synthesis C216415 "IAGKFRITHIIXME-UHFFFAOYSA-N"

166 4 0 Sp3-sp2_Suzuki_coupling C216415 "IAGKFRITHIIXME-UHFFFAOYSA-N"

168 0 0 Grignard_addition_to_carbonyl C216439 "SSIXCXGUESZBGS-UHFFFAOYSA-N"

reactants =
[216293, 283471]

product = C216439 "SSIXCXGUESZBGS-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Grignard_addition_to_carbonyl!

168 1 0 Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide C216439 "SSIXCXGUESZBGS-UHFFFAOYSA-N"

reactants =
[283472, 283473]

product = C216439 "SSIXCXGUESZBGS-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide!

168 2 0 Sp3-sp2_Suzuki_coupling C216439 "SSIXCXGUESZBGS-UHFFFAOYSA-N"

168 2 1 Grignard_addition_to_carbonyl C283474 "FXCWSWNZWNQJMX-UHFFFAOYSA-N"

reactants =
[216293, 283476]

product = C283474 "FXCWSWNZWNQJMX-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Grignard_addition_to_carbonyl!

168 3 0 Grignard_addition_to_carbonyl C216439 "SSIXCXGUESZBGS-UHFFFAOYSA-N"

reactants =
[216293, 283471]

product = C216439 "SSIXCXGUESZBGS-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Grignard_addition_to_carbonyl!

168 4 0 Sp3-sp2_Macmillan_coupling_with_bromide_(intermolecular) C216439 "SSIXCXGUESZBGS-UHFFFAOYSA-N"

reactants =
[283473, 283477]

product = C216439 "SSIXCXGUESZBGS-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sp3-sp2_Macmillan_coupling_with_bromide_(intermolecular)!

172 0 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C216480 "WTRKRXUSBNGMEC-UHFFFAOYSA-N"

172 0 1 Alpha_alkylation_of_ketone C283479 "GQCRRYTYEOSBLF-UHFFFAOYSA-N"

reactants =
[283480]

product = C283479 "GQCRRYTYEOSBLF-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ketone!

172 1 0 Swern_oxidation C216480 "WTRKRXUSBNGMEC-UHFFFAOYSA-N"

reactants =
[283481]

product = C216480 "WTRKRXUSBNGMEC-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Swern_oxidation!

172 2 0 Amine_alkylation C216480 "WTRKRXUSBNGMEC-UHFFFAOYSA-N"

reactants =
[283478, 283482]

product = C216480 "WTRKRXUSBNGMEC-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

172 3 0 Amine_alkylation C216480 "WTRKRXUSBNGMEC-UHFFFAOYSA-N"

reactants =
[283478, 283482]

product = C216480 "WTRKRXUSBNGMEC-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

172 4 0 Amine_alkylation C216480 "WTRKRXUSBNGMEC-UHFFFAOYSA-N"

reactants =
[283478, 283483]

product = C216480 "WTRKRXUSBNGMEC-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

173 0 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C216299 "FDXLNKBSSMKNST-UHFFFAOYSA-N"

173 1 0 Sp3-sp2_Macmillan_coupling_with_chloride_(intermolecular) C216299 "FDXLNKBSSMKNST-UHFFFAOYSA-N"

reactants =
[283452, 283485]

product = C216299 "FDXLNKBSSMKNST-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sp3-sp2_Macmillan_coupling_with_chloride_(intermolecular)!

173 2 0 Alpha_alkylation_of_ketone C216299 "FDXLNKBSSMKNST-UHFFFAOYSA-N"

reactants =
[283486]

product = C216299 "FDXLNKBSSMKNST-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ketone!

173 3 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C216299 "FDXLNKBSSMKNST-UHFFFAOYSA-N"

173 4 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C216299 "FDXLNKBSSMKNST-UHFFFAOYSA-N"

174 0 0 Sp3-sp2_Macmillan_coupling_with_bromide_(intermolecular) C216506 "WIXMSLLRVUTSKV-UHFFFAOYSA-N"

reactants =
[283454, 283487]

product = C216506 "WIXMSLLRVUTSKV-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sp3-sp2_Macmillan_coupling_with_bromide_(intermolecular)!

174 1 0 Alpha_alkylation_of_ketone C216506 "WIXMSLLRVUTSKV-UHFFFAOYSA-N"

reactants =
[283488]

product = C216506 "WIXMSLLRVUTSKV-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ketone!

174 2 0 Sp3-sp2_Macmillan_coupling_with_chloride_(intermolecular) C216506 "WIXMSLLRVUTSKV-UHFFFAOYSA-N"

reactants =
[283452, 283489]

product = C216506 "WIXMSLLRVUTSKV-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sp3-sp2_Macmillan_coupling_with_chloride_(intermolecular)!

174 3 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C216506 "WIXMSLLRVUTSKV-UHFFFAOYSA-N"

174 4 0 Sp3-sp2_Macmillan_coupling_with_chloride_(intermolecular) C216506 "WIXMSLLRVUTSKV-UHFFFAOYSA-N"

reactants =
[283452, 283489]

product = C216506 "WIXMSLLRVUTSKV-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sp3-sp2_Macmillan_coupling_with_chloride_(intermolecular)!

177 0 0 Ring_closing_metathesis C216499 "PEXDTKOHQKGDOE-UHFFFAOYSA-N"

reactants =
[283491]

product = C216499 "PEXDTKOHQKGDOE-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Ring_closing_metathesis!

177 1 0 Ring_closing_metathesis C216499 "PEXDTKOHQKGDOE-UHFFFAOYSA-N"

reactants =
[283492]

product = C216499 "PEXDTKOHQKGDOE-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Ring_closing_metathesis!

177 2 0 Ring_closing_metathesis C216499 "PEXDTKOHQKGDOE-UHFFFAOYSA-N"

reactants =
[283492]

product = C216499 "PEXDTKOHQKGDOE-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Ring_closing_metathesis!

177 3 0 Ring_closing_metathesis C216499 "PEXDTKOHQKGDOE-UHFFFAOYSA-N"

reactants =
[283491]

product = C216499 "PEXDTKOHQKGDOE-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Ring_closing_metathesis!

177 4 0 Ring_closing_metathesis C216499 "PEXDTKOHQKGDOE-UHFFFAOYSA-N"

reactants =
[283491]

product = C216499 "PEXDTKOHQKGDOE-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Ring_closing_metathesis!

178 0 0 Alpha_alkylation_of_ketone C216542 "YQZSZCNVDYPABN-UHFFFAOYSA-N"

reactants =
[283493]

product = C216542 "YQZSZCNVDYPABN-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ketone!

178 1 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C216542 "YQZSZCNVDYPABN-UHFFFAOYSA-N"

178 2 0 Alpha_alkylation_of_ketone C216542 "YQZSZCNVDYPABN-UHFFFAOYSA-N"

reactants =
[283495]

product = C216542 "YQZSZCNVDYPABN-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ketone!

178 3 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C216542 "YQZSZCNVDYPABN-UHFFFAOYSA-N"

178 4 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C216542 "YQZSZCNVDYPABN-UHFFFAOYSA-N"

179 0 0 Alpha_alkylation_of_ester/amide C216552 "SBEYKMJRSWNDJO-UHFFFAOYSA-N"

reactants =
[282987, 282988]

product = C216552 "SBEYKMJRSWNDJO-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ester/amide!

179 1 0 Swern_oxidation C216552 "SBEYKMJRSWNDJO-UHFFFAOYSA-N"

reactants =
[283496]

product = C216552 "SBEYKMJRSWNDJO-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Swern_oxidation!

179 2 0 Alpha_alkylation_of_ester/amide C216552 "SBEYKMJRSWNDJO-UHFFFAOYSA-N"

reactants =
[282988, 283497]

product = C216552 "SBEYKMJRSWNDJO-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ester/amide!

179 3 0 Swern_oxidation C216552 "SBEYKMJRSWNDJO-UHFFFAOYSA-N"

reactants =
[283496]

product = C216552 "SBEYKMJRSWNDJO-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Swern_oxidation!

179 4 0 Alpha_alkylation_of_ester/amide C216552 "SBEYKMJRSWNDJO-UHFFFAOYSA-N"

reactants =
[282987, 282988]

product = C216552 "SBEYKMJRSWNDJO-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ester/amide!

181 0 0 Benzylic_deprotonation-alkylation_(pyridine) C216729 "ACGAOFJUNQSDGT-UHFFFAOYSA-N"

reactants =
[283498]

product = C216729 "ACGAOFJUNQSDGT-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Benzylic_deprotonation-alkylation_(pyridine)!

181 1 0 Benzylic_deprotonation-alkylation_(pyridine) C216729 "ACGAOFJUNQSDGT-UHFFFAOYSA-N"

reactants =
[283499]

product = C216729 "ACGAOFJUNQSDGT-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Benzylic_deprotonation-alkylation_(pyridine)!

181 2 0 Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide C216729 "ACGAOFJUNQSDGT-UHFFFAOYSA-N"

reactants =
[283500, 283501]

product = C216729 "ACGAOFJUNQSDGT-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide!

181 3 0 Benzylic_deprotonation-alkylation_(pyridine) C216729 "ACGAOFJUNQSDGT-UHFFFAOYSA-N"

reactants =
[283498]

product = C216729 "ACGAOFJUNQSDGT-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Benzylic_deprotonation-alkylation_(pyridine)!

181 4 0 Benzylic_deprotonation-alkylation_(pyridine) C216729 "ACGAOFJUNQSDGT-UHFFFAOYSA-N"

reactants =
[283499]

product = C216729 "ACGAOFJUNQSDGT-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Benzylic_deprotonation-alkylation_(pyridine)!

182 0 0 Williamson_ether_synthesis C179963 "DBUJFULDVAZULB-UHFFFAOYSA-N"

 Success  registered route 37!

187 0 0 Amidation C203259 "FCAAAVKQVZHQHC-UHFFFAOYSA-N"

 Success  registered route 38!

188 0 0 Amine_alkylation C261944 "GOJVKZFYKWKGEI-UHFFFAOYSA-N"

reactants =
[283502]

product = C261944 "GOJVKZFYKWKGEI-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

188 1 0 Friedel-Crafts_methylation C261944 "GOJVKZFYKWKGEI-UHFFFAOYSA-N"

reactants =
[283503]

product = C261944 "GOJVKZFYKWKGEI-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Friedel-Crafts_methylation!

188 2 0 Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide C261944 "GOJVKZFYKWKGEI-UHFFFAOYSA-N"

reactants =
[282914, 283504]

product = C261944 "GOJVKZFYKWKGEI-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide!

188 3 0 Amine_alkylation C261944 "GOJVKZFYKWKGEI-UHFFFAOYSA-N"

reactants =
[283505]

product = C261944 "GOJVKZFYKWKGEI-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

188 4 0 Appel_bromination C261944 "GOJVKZFYKWKGEI-UHFFFAOYSA-N"

reactants =
[283506]

product = C261944 "GOJVKZFYKWKGEI-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Appel_bromination!

189 0 0 Amidation C155426 "BUDYDGJIWBAUAH-UHFFFAOYSA-N"

 Success  registered route 39!

192 0 0 Grignard_addition_to_carbonyl C154866 "KSWWLSZWNYUPKN-UHFFFAOYSA-N"

reactants =
[139000, 283507]

product = C154866 "KSWWLSZWNYUPKN-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Grignard_addition_to_carbonyl!

192 1 0 Amidation C154866 "KSWWLSZWNYUPKN-UHFFFAOYSA-N"

192 1 1 Grignard_addition_to_carbonyl C283508 "QEFOYRAYCVXGPU-UHFFFAOYSA-N"

reactants =
[283507, 283509]

product = C283508 "QEFOYRAYCVXGPU-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Grignard_addition_to_carbonyl!

192 2 0 Alpha_alkylation_of_ester/amide C154866 "KSWWLSZWNYUPKN-UHFFFAOYSA-N"

reactants =
[283510]

product = C154866 "KSWWLSZWNYUPKN-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ester/amide!

192 3 0 Grignard_addition_to_carbonyl C154866 "KSWWLSZWNYUPKN-UHFFFAOYSA-N"

reactants =
[139000, 283507]

product = C154866 "KSWWLSZWNYUPKN-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Grignard_addition_to_carbonyl!

192 4 0 Carboxylic_acid_to_primary_amide C154866 "KSWWLSZWNYUPKN-UHFFFAOYSA-N"

reactants =
[283508]

product = C154866 "KSWWLSZWNYUPKN-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Carboxylic_acid_to_primary_amide!

194 0 0 Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide C145049 "KECOMYVRALMHPG-UHFFFAOYSA-N"

reactants =
[283511]

product = C145049 "KECOMYVRALMHPG-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide!

194 1 0 Sp3-sp2_Suzuki_coupling C145049 "KECOMYVRALMHPG-UHFFFAOYSA-N"

194 1 1 Grignard_addition_to_carbonyl C283512 "QVEYRGIGNGHFBJ-UHFFFAOYSA-N"

reactants =
[283513, 283514]

product = C283512 "QVEYRGIGNGHFBJ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Grignard_addition_to_carbonyl!

194 2 0 Sp3-sp2_Suzuki_coupling C145049 "KECOMYVRALMHPG-UHFFFAOYSA-N"

194 3 0 Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide C145049 "KECOMYVRALMHPG-UHFFFAOYSA-N"

reactants =
[283511]

product = C145049 "KECOMYVRALMHPG-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide!

194 4 0 Sp3-sp2_Suzuki_coupling C145049 "KECOMYVRALMHPG-UHFFFAOYSA-N"

195 0 0 Nucleophilic_substitution_with_thiol C145578 "AQAMQMSGSHVYSE-UHFFFAOYSA-N"

reactants =
[283517]

product = C145578 "AQAMQMSGSHVYSE-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Nucleophilic_substitution_with_thiol!

195 1 0 Buchwald-Hartwig_(thio)etherification C145578 "AQAMQMSGSHVYSE-UHFFFAOYSA-N"

reactants =
[283518]

product = C145578 "AQAMQMSGSHVYSE-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Buchwald-Hartwig_(thio)etherification!

195 2 0 Buchwald-Hartwig_(thio)etherification C145578 "AQAMQMSGSHVYSE-UHFFFAOYSA-N"

reactants =
[283519]

product = C145578 "AQAMQMSGSHVYSE-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Buchwald-Hartwig_(thio)etherification!

195 3 0 Buchwald-Hartwig_(thio)etherification C145578 "AQAMQMSGSHVYSE-UHFFFAOYSA-N"

reactants =
[283520]

product = C145578 "AQAMQMSGSHVYSE-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Buchwald-Hartwig_(thio)etherification!

195 4 0 Buchwald-Hartwig_(thio)etherification C145578 "AQAMQMSGSHVYSE-UHFFFAOYSA-N"

reactants =
[283519]

product = C145578 "AQAMQMSGSHVYSE-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Buchwald-Hartwig_(thio)etherification!

197 0 0 Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide C145809 "UWQPEPKLQMYNPZ-UHFFFAOYSA-N"

reactants =
[283521]

product = C145809 "UWQPEPKLQMYNPZ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide!

197 1 0 Sp3-sp2_Suzuki_coupling C145809 "UWQPEPKLQMYNPZ-UHFFFAOYSA-N"

197 2 0 Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide C145809 "UWQPEPKLQMYNPZ-UHFFFAOYSA-N"

reactants =
[283521]

product = C145809 "UWQPEPKLQMYNPZ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide!

197 3 0 Sp3-sp2_Suzuki_coupling C145809 "UWQPEPKLQMYNPZ-UHFFFAOYSA-N"

197 3 1 Grignard_addition_to_carbonyl C283523 "XWLLYMRHDSSVHX-UHFFFAOYSA-N"

reactants =
[283514, 283524]

product = C283523 "XWLLYMRHDSSVHX-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Grignard_addition_to_carbonyl!

197 4 0 Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide C145809 "UWQPEPKLQMYNPZ-UHFFFAOYSA-N"

reactants =
[283521]

product = C145809 "UWQPEPKLQMYNPZ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide!

199 0 0 Alpha_alkylation_of_ketone C145902 "SLPHMEGNVKINDS-UHFFFAOYSA-N"

reactants =
[283525]

product = C145902 "SLPHMEGNVKINDS-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ketone!

199 1 0 Alpha_alkylation_of_ketone C145902 "SLPHMEGNVKINDS-UHFFFAOYSA-N"

reactants =
[283526]

product = C145902 "SLPHMEGNVKINDS-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ketone!

199 2 0 Alpha_alkylation_of_ketone C145902 "SLPHMEGNVKINDS-UHFFFAOYSA-N"

reactants =
[283527]

product = C145902 "SLPHMEGNVKINDS-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ketone!

199 3 0 Alpha_alkylation_of_ketone C145902 "SLPHMEGNVKINDS-UHFFFAOYSA-N"

reactants =
[283525]

product = C145902 "SLPHMEGNVKINDS-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ketone!

199 4 0 Alpha_alkylation_of_ketone C145902 "SLPHMEGNVKINDS-UHFFFAOYSA-N"

reactants =
[283525]

product = C145902 "SLPHMEGNVKINDS-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ketone!

202 0 0 Imidazole_C-2_addition_to_ketone/aldehyde C146040 "SCDNAKOYMIYAQA-UHFFFAOYSA-N"

reactants =
[283528, 283529]

product = C146040 "SCDNAKOYMIYAQA-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Imidazole_C-2_addition_to_ketone/aldehyde!

202 1 0 Grignard_addition_to_carbonyl C146040 "SCDNAKOYMIYAQA-UHFFFAOYSA-N"

reactants =
[283530, 283531]

product = C146040 "SCDNAKOYMIYAQA-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Grignard_addition_to_carbonyl!

202 2 0 Imidazole_C-2_addition_to_ketone/aldehyde C146040 "SCDNAKOYMIYAQA-UHFFFAOYSA-N"

reactants =
[283528, 283529]

product = C146040 "SCDNAKOYMIYAQA-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Imidazole_C-2_addition_to_ketone/aldehyde!

202 3 0 Grignard_addition_to_carbonyl C146040 "SCDNAKOYMIYAQA-UHFFFAOYSA-N"

reactants =
[283530, 283532]

product = C146040 "SCDNAKOYMIYAQA-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Grignard_addition_to_carbonyl!

202 4 0 Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide C146040 "SCDNAKOYMIYAQA-UHFFFAOYSA-N"

reactants =
[282914, 283533]

product = C146040 "SCDNAKOYMIYAQA-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide!

203 0 0 Claisen_condensation C146186 "GHLNUKUVXIIUDH-UHFFFAOYSA-N"

reactants =
[283534]

product = C146186 "GHLNUKUVXIIUDH-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Claisen_condensation!

203 1 0 Claisen_condensation C146186 "GHLNUKUVXIIUDH-UHFFFAOYSA-N"

reactants =
[283535]

product = C146186 "GHLNUKUVXIIUDH-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Claisen_condensation!

203 2 0 Amidation C146186 "GHLNUKUVXIIUDH-UHFFFAOYSA-N"

203 3 0 Amidation C146186 "GHLNUKUVXIIUDH-UHFFFAOYSA-N"

203 4 0 Claisen_condensation C146186 "GHLNUKUVXIIUDH-UHFFFAOYSA-N"

reactants =
[283534]

product = C146186 "GHLNUKUVXIIUDH-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Claisen_condensation!

206 0 0 Amide_to_amine_reduction C146746 "UFMKQVZXEYBDBD-UHFFFAOYSA-N"

reactants =
[283537]

product = C146746 "UFMKQVZXEYBDBD-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amide_to_amine_reduction!

206 1 0 Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide C146746 "UFMKQVZXEYBDBD-UHFFFAOYSA-N"

reactants =
[283538]

product = C146746 "UFMKQVZXEYBDBD-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide!

206 2 0 Amide_to_amine_reduction C146746 "UFMKQVZXEYBDBD-UHFFFAOYSA-N"

reactants =
[283537]

product = C146746 "UFMKQVZXEYBDBD-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amide_to_amine_reduction!

206 3 0 Amine_alkylation C146746 "UFMKQVZXEYBDBD-UHFFFAOYSA-N"

reactants =
[283123, 283539]

product = C146746 "UFMKQVZXEYBDBD-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

206 4 0 Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide C146746 "UFMKQVZXEYBDBD-UHFFFAOYSA-N"

reactants =
[283538]

product = C146746 "UFMKQVZXEYBDBD-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide!

216 0 0 Williamson_ether_synthesis C148261 "QDCKVDNVBDQFNM-UHFFFAOYSA-N"

 Success  registered route 40!

218 0 0 Ring_closing_metathesis C181196 "OAZGZFZJSHMQAF-UHFFFAOYSA-N"

reactants =
[283540]

product = C181196 "OAZGZFZJSHMQAF-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Ring_closing_metathesis!

218 1 0 Ring_closing_metathesis C181196 "OAZGZFZJSHMQAF-UHFFFAOYSA-N"

reactants =
[283541]

product = C181196 "OAZGZFZJSHMQAF-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Ring_closing_metathesis!

218 2 0 Sp2-sp2_Suzuki_coupling C181196 "OAZGZFZJSHMQAF-UHFFFAOYSA-N"

218 2 1 Ring_closing_metathesis C283542 "MREKDLATUILSBR-UHFFFAOYSA-N"

reactants =
[283544]

product = C283542 "MREKDLATUILSBR-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Ring_closing_metathesis!

218 3 0 S-nucleophilic_aromatic_substitution C181196 "OAZGZFZJSHMQAF-UHFFFAOYSA-N"

reactants =
[282996, 283545]

product = C181196 "OAZGZFZJSHMQAF-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: S-nucleophilic_aromatic_substitution!

218 4 0 Sp2-sp2_Suzuki_coupling C181196 "OAZGZFZJSHMQAF-UHFFFAOYSA-N"

218 4 1 Ring_closing_metathesis C283546 "ZFYYQFYNIARMOT-UHFFFAOYSA-N"

reactants =
[283548]

product = C283546 "ZFYYQFYNIARMOT-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Ring_closing_metathesis!

219 0 0 Ring_closing_metathesis C181214 "XBUJMKISRHCTDR-UHFFFAOYSA-N"

reactants =
[283549]

product = C181214 "XBUJMKISRHCTDR-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Ring_closing_metathesis!

219 1 0 Ring_closing_metathesis C181214 "XBUJMKISRHCTDR-UHFFFAOYSA-N"

reactants =
[283550]

product = C181214 "XBUJMKISRHCTDR-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Ring_closing_metathesis!

219 2 0 Ring_closing_metathesis C181214 "XBUJMKISRHCTDR-UHFFFAOYSA-N"

reactants =
[283549]

product = C181214 "XBUJMKISRHCTDR-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Ring_closing_metathesis!

219 3 0 Ring_closing_metathesis C181214 "XBUJMKISRHCTDR-UHFFFAOYSA-N"

reactants =
[283549]

product = C181214 "XBUJMKISRHCTDR-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Ring_closing_metathesis!

219 4 0 Ring_closing_metathesis C181214 "XBUJMKISRHCTDR-UHFFFAOYSA-N"

reactants =
[283549]

product = C181214 "XBUJMKISRHCTDR-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Ring_closing_metathesis!

229 0 0 Claisen_condensation C181317 "PSFZHIZHBUGQQO-UHFFFAOYSA-N"

reactants =
[283551]

product = C181317 "PSFZHIZHBUGQQO-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Claisen_condensation!

229 1 0 Claisen_condensation C181317 "PSFZHIZHBUGQQO-UHFFFAOYSA-N"

reactants =
[283552]

product = C181317 "PSFZHIZHBUGQQO-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Claisen_condensation!

229 2 0 Amidation C181317 "PSFZHIZHBUGQQO-UHFFFAOYSA-N"

229 3 0 Claisen_condensation C181317 "PSFZHIZHBUGQQO-UHFFFAOYSA-N"

reactants =
[283551]

product = C181317 "PSFZHIZHBUGQQO-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Claisen_condensation!

229 4 0 Claisen_condensation C181317 "PSFZHIZHBUGQQO-UHFFFAOYSA-N"

reactants =
[283552]

product = C181317 "PSFZHIZHBUGQQO-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Claisen_condensation!

231 0 0 Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide C181320 "IKIOITOSBVZGHJ-UHFFFAOYSA-N"

reactants =
[283554]

product = C181320 "IKIOITOSBVZGHJ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide!

231 1 0 Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide C181320 "IKIOITOSBVZGHJ-UHFFFAOYSA-N"

reactants =
[283554]

product = C181320 "IKIOITOSBVZGHJ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide!

231 2 0 Sp3-sp2_Suzuki_coupling C181320 "IKIOITOSBVZGHJ-UHFFFAOYSA-N"

231 3 0 Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide C181320 "IKIOITOSBVZGHJ-UHFFFAOYSA-N"

reactants =
[283554]

product = C181320 "IKIOITOSBVZGHJ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide!

231 4 0 Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide C181320 "IKIOITOSBVZGHJ-UHFFFAOYSA-N"

reactants =
[283554]

product = C181320 "IKIOITOSBVZGHJ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide!

232 0 0 Hydrolysis_of_magnesium_alkylthiolate C181344 "XAWSNWWGAIHPIO-UHFFFAOYSA-N"

reactants =
[283556]

product = C181344 "XAWSNWWGAIHPIO-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Hydrolysis_of_magnesium_alkylthiolate!

232 1 0 Hydrolysis_of_magnesium_alkylthiolate C181344 "XAWSNWWGAIHPIO-UHFFFAOYSA-N"

reactants =
[283557]

product = C181344 "XAWSNWWGAIHPIO-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Hydrolysis_of_magnesium_alkylthiolate!

232 2 0 Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide C181344 "XAWSNWWGAIHPIO-UHFFFAOYSA-N"

reactants =
[282914, 283558]

product = C181344 "XAWSNWWGAIHPIO-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide!

232 3 0 Hydrolysis_of_magnesium_alkylthiolate C181344 "XAWSNWWGAIHPIO-UHFFFAOYSA-N"

reactants =
[283559]

product = C181344 "XAWSNWWGAIHPIO-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Hydrolysis_of_magnesium_alkylthiolate!

232 4 0 Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide C181344 "XAWSNWWGAIHPIO-UHFFFAOYSA-N"

reactants =
[282914, 283558]

product = C181344 "XAWSNWWGAIHPIO-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide!

233 0 0 Sp3-sp2_Macmillan_coupling_with_chloride_(intermolecular) C181372 "FYJSPFYXYVMCOE-UHFFFAOYSA-N"

reactants =
[283560]

product = C181372 "FYJSPFYXYVMCOE-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sp3-sp2_Macmillan_coupling_with_chloride_(intermolecular)!

233 1 0 Sp3-sp2_Macmillan_coupling_with_bromide_(intermolecular) C181372 "FYJSPFYXYVMCOE-UHFFFAOYSA-N"

reactants =
[283561]

product = C181372 "FYJSPFYXYVMCOE-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sp3-sp2_Macmillan_coupling_with_bromide_(intermolecular)!

233 2 0 Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide C181372 "FYJSPFYXYVMCOE-UHFFFAOYSA-N"

reactants =
[283562]

product = C181372 "FYJSPFYXYVMCOE-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide!

233 3 0 Sp3-sp2_Macmillan_coupling_with_bromide_(intermolecular) C181372 "FYJSPFYXYVMCOE-UHFFFAOYSA-N"

reactants =
[283561]

product = C181372 "FYJSPFYXYVMCOE-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sp3-sp2_Macmillan_coupling_with_bromide_(intermolecular)!

233 4 0 Sp3-sp2_Macmillan_coupling_with_bromide_(intermolecular) C181372 "FYJSPFYXYVMCOE-UHFFFAOYSA-N"

reactants =
[283561]

product = C181372 "FYJSPFYXYVMCOE-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sp3-sp2_Macmillan_coupling_with_bromide_(intermolecular)!

237 0 0 NHK_reaction C181440 "HRAPKXFSNLPORY-UHFFFAOYSA-N"

reactants =
[283563, 283564]

product = C181440 "HRAPKXFSNLPORY-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: NHK_reaction!

237 1 0 S-nucleophilic_aromatic_substitution C181440 "HRAPKXFSNLPORY-UHFFFAOYSA-N"

reactants =
[282996, 283565]

product = C181440 "HRAPKXFSNLPORY-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: S-nucleophilic_aromatic_substitution!

237 2 0 Riley_oxidation C181440 "HRAPKXFSNLPORY-UHFFFAOYSA-N"

reactants =
[283566]

product = C181440 "HRAPKXFSNLPORY-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Riley_oxidation!

237 3 0 Buchwald-Hartwig_(thio)etherification C181440 "HRAPKXFSNLPORY-UHFFFAOYSA-N"

reactants =
[282996, 283567]

product = C181440 "HRAPKXFSNLPORY-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Buchwald-Hartwig_(thio)etherification!

237 4 0 Buchwald-Hartwig_(thio)etherification C181440 "HRAPKXFSNLPORY-UHFFFAOYSA-N"

reactants =
[282996, 283568]

product = C181440 "HRAPKXFSNLPORY-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Buchwald-Hartwig_(thio)etherification!

242 0 0 Sp3-sp2_Macmillan_coupling_with_chloride_(intermolecular) C181958 "OGXOPRLPVWVISU-UHFFFAOYSA-N"

reactants =
[283569, 283570]

product = C181958 "OGXOPRLPVWVISU-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sp3-sp2_Macmillan_coupling_with_chloride_(intermolecular)!

242 1 0 Sp3-sp2_Macmillan_coupling_with_chloride_(intermolecular) C181958 "OGXOPRLPVWVISU-UHFFFAOYSA-N"

reactants =
[283569, 283570]

product = C181958 "OGXOPRLPVWVISU-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sp3-sp2_Macmillan_coupling_with_chloride_(intermolecular)!

242 2 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C181958 "OGXOPRLPVWVISU-UHFFFAOYSA-N"

242 3 0 Sp3-sp2_Macmillan_coupling_with_chloride_(intermolecular) C181958 "OGXOPRLPVWVISU-UHFFFAOYSA-N"

reactants =
[283569, 283570]

product = C181958 "OGXOPRLPVWVISU-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sp3-sp2_Macmillan_coupling_with_chloride_(intermolecular)!

242 4 0 Sp3-sp2_Macmillan_coupling_with_chloride_(intermolecular) C181958 "OGXOPRLPVWVISU-UHFFFAOYSA-N"

reactants =
[283569, 283570]

product = C181958 "OGXOPRLPVWVISU-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sp3-sp2_Macmillan_coupling_with_chloride_(intermolecular)!

243 0 0 S-nucleophilic_aromatic_substitution C181906 "GAIGGVYAGRLFMC-UHFFFAOYSA-N"

reactants =
[282995, 282996]

product = C181906 "GAIGGVYAGRLFMC-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: S-nucleophilic_aromatic_substitution!

243 1 0 S-nucleophilic_aromatic_substitution C181906 "GAIGGVYAGRLFMC-UHFFFAOYSA-N"

reactants =
[282996, 282997]

product = C181906 "GAIGGVYAGRLFMC-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: S-nucleophilic_aromatic_substitution!

243 2 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C181906 "GAIGGVYAGRLFMC-UHFFFAOYSA-N"

243 3 0 S-nucleophilic_aromatic_substitution C181906 "GAIGGVYAGRLFMC-UHFFFAOYSA-N"

reactants =
[282996, 282998]

product = C181906 "GAIGGVYAGRLFMC-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: S-nucleophilic_aromatic_substitution!

243 4 0 S-nucleophilic_aromatic_substitution C181906 "GAIGGVYAGRLFMC-UHFFFAOYSA-N"

reactants =
[282996, 282997]

product = C181906 "GAIGGVYAGRLFMC-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: S-nucleophilic_aromatic_substitution!

245 0 0 Heck_reaction_(intermolecular) C182001 "RXUNDRBYKCAMQB-UHFFFAOYSA-N"

reactants =
[283573, 283574]

product = C182001 "RXUNDRBYKCAMQB-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Heck_reaction_(intermolecular)!

245 1 0 Heck_reaction_(intermolecular) C182001 "RXUNDRBYKCAMQB-UHFFFAOYSA-N"

reactants =
[283573, 283575]

product = C182001 "RXUNDRBYKCAMQB-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Heck_reaction_(intermolecular)!

245 2 0 Heck_reaction_(intermolecular) C182001 "RXUNDRBYKCAMQB-UHFFFAOYSA-N"

reactants =
[283573, 283574]

product = C182001 "RXUNDRBYKCAMQB-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Heck_reaction_(intermolecular)!

245 3 0 Heck_reaction_(intermolecular) C182001 "RXUNDRBYKCAMQB-UHFFFAOYSA-N"

reactants =
[283573, 283575]

product = C182001 "RXUNDRBYKCAMQB-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Heck_reaction_(intermolecular)!

245 4 0 Ring_closing_metathesis C182001 "RXUNDRBYKCAMQB-UHFFFAOYSA-N"

reactants =
[283576]

product = C182001 "RXUNDRBYKCAMQB-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Ring_closing_metathesis!

246 0 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C182105 "IEGLJRXZWZHGQG-UHFFFAOYSA-N"

246 1 0 Sp3-sp2_Macmillan_coupling_with_chloride_(intermolecular) C182105 "IEGLJRXZWZHGQG-UHFFFAOYSA-N"

reactants =
[283485, 283578]

product = C182105 "IEGLJRXZWZHGQG-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sp3-sp2_Macmillan_coupling_with_chloride_(intermolecular)!

246 2 0 Alpha_alkylation_of_ketone C182105 "IEGLJRXZWZHGQG-UHFFFAOYSA-N"

reactants =
[283579]

product = C182105 "IEGLJRXZWZHGQG-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ketone!

246 3 0 Sp3-sp2_Macmillan_coupling_with_bromide_(intermolecular) C182105 "IEGLJRXZWZHGQG-UHFFFAOYSA-N"

reactants =
[283580, 283581]

product = C182105 "IEGLJRXZWZHGQG-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sp3-sp2_Macmillan_coupling_with_bromide_(intermolecular)!

246 4 0 Mannich_reaction C182105 "IEGLJRXZWZHGQG-UHFFFAOYSA-N"

reactants =
[283582]

product = C182105 "IEGLJRXZWZHGQG-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Mannich_reaction!

247 0 0 Sp3-sp2_Macmillan_coupling_with_chloride_(intermolecular) C182109 "BSVXJKRMERDWGF-UHFFFAOYSA-N"

reactants =
[283569, 283583]

product = C182109 "BSVXJKRMERDWGF-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sp3-sp2_Macmillan_coupling_with_chloride_(intermolecular)!

247 1 0 Sp3-sp2_Macmillan_coupling_with_chloride_(intermolecular) C182109 "BSVXJKRMERDWGF-UHFFFAOYSA-N"

reactants =
[283569, 283583]

product = C182109 "BSVXJKRMERDWGF-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sp3-sp2_Macmillan_coupling_with_chloride_(intermolecular)!

247 2 0 Sp3-sp2_Macmillan_coupling_with_chloride_(intermolecular) C182109 "BSVXJKRMERDWGF-UHFFFAOYSA-N"

reactants =
[283569, 283583]

product = C182109 "BSVXJKRMERDWGF-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sp3-sp2_Macmillan_coupling_with_chloride_(intermolecular)!

247 3 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C182109 "BSVXJKRMERDWGF-UHFFFAOYSA-N"

247 4 0 Sp3-sp2_Macmillan_coupling_with_chloride_(intermolecular) C182109 "BSVXJKRMERDWGF-UHFFFAOYSA-N"

reactants =
[283569, 283583]

product = C182109 "BSVXJKRMERDWGF-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sp3-sp2_Macmillan_coupling_with_chloride_(intermolecular)!

248 0 0 Reductive_amination C182121 "SNNKCQMKKUBBPN-UHFFFAOYSA-N"

248 1 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C182121 "SNNKCQMKKUBBPN-UHFFFAOYSA-N"

248 2 0 Amine_alkylation C182121 "SNNKCQMKKUBBPN-UHFFFAOYSA-N"

reactants =
[283587]

product = C182121 "SNNKCQMKKUBBPN-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

248 3 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C182121 "SNNKCQMKKUBBPN-UHFFFAOYSA-N"

248 4 0 Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide C182121 "SNNKCQMKKUBBPN-UHFFFAOYSA-N"

reactants =
[283588, 283589]

product = C182121 "SNNKCQMKKUBBPN-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide!

249 0 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C182125 "JFTIVCICNQOZAI-UHFFFAOYSA-N"

249 1 0 Sp3-sp2_Macmillan_coupling_with_chloride_(intermolecular) C182125 "JFTIVCICNQOZAI-UHFFFAOYSA-N"

reactants =
[283569, 283591]

product = C182125 "JFTIVCICNQOZAI-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sp3-sp2_Macmillan_coupling_with_chloride_(intermolecular)!

249 2 0 Sp3-sp2_Macmillan_coupling_with_bromide_(intermolecular) C182125 "JFTIVCICNQOZAI-UHFFFAOYSA-N"

reactants =
[283592, 283593]

product = C182125 "JFTIVCICNQOZAI-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sp3-sp2_Macmillan_coupling_with_bromide_(intermolecular)!

249 3 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C182125 "JFTIVCICNQOZAI-UHFFFAOYSA-N"

249 4 0 Sp3-sp2_Macmillan_coupling_with_chloride_(intermolecular) C182125 "JFTIVCICNQOZAI-UHFFFAOYSA-N"

reactants =
[283569, 283591]

product = C182125 "JFTIVCICNQOZAI-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sp3-sp2_Macmillan_coupling_with_chloride_(intermolecular)!

250 0 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C182163 "KGEGNRYOTDGQLV-UHFFFAOYSA-N"

250 1 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C182163 "KGEGNRYOTDGQLV-UHFFFAOYSA-N"

250 2 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C182163 "KGEGNRYOTDGQLV-UHFFFAOYSA-N"

250 3 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C182163 "KGEGNRYOTDGQLV-UHFFFAOYSA-N"

250 4 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C182163 "KGEGNRYOTDGQLV-UHFFFAOYSA-N"

251 0 0 Alpha_alkylation_of_ketone C182169 "RUKKUCYHUKCBDF-UHFFFAOYSA-N"

reactants =
[283595, 283596]

product = C182169 "RUKKUCYHUKCBDF-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ketone!

251 1 0 Alpha_alkylation_of_ketone C182169 "RUKKUCYHUKCBDF-UHFFFAOYSA-N"

reactants =
[283596, 283597]

product = C182169 "RUKKUCYHUKCBDF-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ketone!

251 2 0 Alpha_alkylation_of_ketone C182169 "RUKKUCYHUKCBDF-UHFFFAOYSA-N"

reactants =
[283596, 283598]

product = C182169 "RUKKUCYHUKCBDF-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ketone!

251 3 0 Alpha_alkylation_of_ketone C182169 "RUKKUCYHUKCBDF-UHFFFAOYSA-N"

reactants =
[283127, 283599]

product = C182169 "RUKKUCYHUKCBDF-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ketone!

251 4 0 Ethenyl_to_formyl C182169 "RUKKUCYHUKCBDF-UHFFFAOYSA-N"

reactants =
[283600]

product = C182169 "RUKKUCYHUKCBDF-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Ethenyl_to_formyl!

252 0 0 Amine_alkylation C182134 "WNWPBURIRJZWDB-UHFFFAOYSA-N"

reactants =
[283601]

product = C182134 "WNWPBURIRJZWDB-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

252 1 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C182134 "WNWPBURIRJZWDB-UHFFFAOYSA-N"

252 2 0 S-nucleophilic_aromatic_substitution C182134 "WNWPBURIRJZWDB-UHFFFAOYSA-N"

reactants =
[282996, 283603]

product = C182134 "WNWPBURIRJZWDB-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: S-nucleophilic_aromatic_substitution!

252 3 0 S-nucleophilic_aromatic_substitution C182134 "WNWPBURIRJZWDB-UHFFFAOYSA-N"

reactants =
[282996, 283604]

product = C182134 "WNWPBURIRJZWDB-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: S-nucleophilic_aromatic_substitution!

252 4 0 S-nucleophilic_aromatic_substitution C182134 "WNWPBURIRJZWDB-UHFFFAOYSA-N"

reactants =
[282996, 283605]

product = C182134 "WNWPBURIRJZWDB-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: S-nucleophilic_aromatic_substitution!

253 0 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C182181 "QBIWCRLJRSIZFF-UHFFFAOYSA-N"

253 1 0 S-nucleophilic_aromatic_substitution C182181 "QBIWCRLJRSIZFF-UHFFFAOYSA-N"

reactants =
[282996, 283607]

product = C182181 "QBIWCRLJRSIZFF-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: S-nucleophilic_aromatic_substitution!

253 2 0 S-nucleophilic_aromatic_substitution C182181 "QBIWCRLJRSIZFF-UHFFFAOYSA-N"

reactants =
[282996, 283607]

product = C182181 "QBIWCRLJRSIZFF-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: S-nucleophilic_aromatic_substitution!

253 3 0 S-nucleophilic_aromatic_substitution C182181 "QBIWCRLJRSIZFF-UHFFFAOYSA-N"

reactants =
[282996, 283607]

product = C182181 "QBIWCRLJRSIZFF-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: S-nucleophilic_aromatic_substitution!

253 4 0 S-nucleophilic_aromatic_substitution C182181 "QBIWCRLJRSIZFF-UHFFFAOYSA-N"

reactants =
[282996, 283607]

product = C182181 "QBIWCRLJRSIZFF-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: S-nucleophilic_aromatic_substitution!

254 0 0 Amine_alkylation C182188 "BLNUXUYGSMWJHQ-UHFFFAOYSA-N"

reactants =
[283608]

product = C182188 "BLNUXUYGSMWJHQ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

254 1 0 Amine_alkylation C182188 "BLNUXUYGSMWJHQ-UHFFFAOYSA-N"

reactants =
[283609]

product = C182188 "BLNUXUYGSMWJHQ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

254 2 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C182188 "BLNUXUYGSMWJHQ-UHFFFAOYSA-N"

254 3 0 Amine_alkylation C182188 "BLNUXUYGSMWJHQ-UHFFFAOYSA-N"

reactants =
[283609]

product = C182188 "BLNUXUYGSMWJHQ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

254 4 0 Amine_alkylation C182188 "BLNUXUYGSMWJHQ-UHFFFAOYSA-N"

reactants =
[283609]

product = C182188 "BLNUXUYGSMWJHQ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

255 0 0 S-nucleophilic_aromatic_substitution C181935 "AFWCNCDEVDPSGG-UHFFFAOYSA-N"

reactants =
[282996, 283611]

product = C181935 "AFWCNCDEVDPSGG-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: S-nucleophilic_aromatic_substitution!

255 1 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C181935 "AFWCNCDEVDPSGG-UHFFFAOYSA-N"

255 2 0 S-nucleophilic_aromatic_substitution C181935 "AFWCNCDEVDPSGG-UHFFFAOYSA-N"

reactants =
[282996, 283613]

product = C181935 "AFWCNCDEVDPSGG-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: S-nucleophilic_aromatic_substitution!

255 3 0 Amine_alkylation C181935 "AFWCNCDEVDPSGG-UHFFFAOYSA-N"

reactants =
[283614]

product = C181935 "AFWCNCDEVDPSGG-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

255 4 0 Alpha_alkylation_of_ketone C181935 "AFWCNCDEVDPSGG-UHFFFAOYSA-N"

reactants =
[283615]

product = C181935 "AFWCNCDEVDPSGG-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ketone!

256 0 0 S-nucleophilic_aromatic_substitution C182197 "BPTFCRKOVTZCQF-UHFFFAOYSA-N"

reactants =
[282996, 283616]

product = C182197 "BPTFCRKOVTZCQF-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: S-nucleophilic_aromatic_substitution!

256 1 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C182197 "BPTFCRKOVTZCQF-UHFFFAOYSA-N"

256 2 0 Stille_coupling C182197 "BPTFCRKOVTZCQF-UHFFFAOYSA-N"

reactants =
[182121, 283227]

product = C182197 "BPTFCRKOVTZCQF-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Stille_coupling!

256 3 0 S-nucleophilic_aromatic_substitution C182197 "BPTFCRKOVTZCQF-UHFFFAOYSA-N"

reactants =
[282996, 283616]

product = C182197 "BPTFCRKOVTZCQF-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: S-nucleophilic_aromatic_substitution!

256 4 0 S-nucleophilic_aromatic_substitution C182197 "BPTFCRKOVTZCQF-UHFFFAOYSA-N"

reactants =
[282996, 283616]

product = C182197 "BPTFCRKOVTZCQF-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: S-nucleophilic_aromatic_substitution!

257 0 0 Hydrolysis_of_magnesium_alkylthiolate C182207 "WMUUVFWDNLHIJJ-UHFFFAOYSA-N"

reactants =
[283618]

product = C182207 "WMUUVFWDNLHIJJ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Hydrolysis_of_magnesium_alkylthiolate!

257 1 0 Hydrolysis_of_magnesium_alkylthiolate C182207 "WMUUVFWDNLHIJJ-UHFFFAOYSA-N"

reactants =
[283619]

product = C182207 "WMUUVFWDNLHIJJ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Hydrolysis_of_magnesium_alkylthiolate!

257 2 0 Hydrolysis_of_magnesium_alkylthiolate C182207 "WMUUVFWDNLHIJJ-UHFFFAOYSA-N"

reactants =
[283620]

product = C182207 "WMUUVFWDNLHIJJ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Hydrolysis_of_magnesium_alkylthiolate!

257 3 0 O-TBS_deprotection C182207 "WMUUVFWDNLHIJJ-UHFFFAOYSA-N"

reactants =
[283621]

product = C182207 "WMUUVFWDNLHIJJ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: O-TBS_deprotection!

257 4 0 Ozonolysis_(to_alcohol,_intermolecular) C182207 "WMUUVFWDNLHIJJ-UHFFFAOYSA-N"

reactants =
[283622]

product = C182207 "WMUUVFWDNLHIJJ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Ozonolysis_(to_alcohol,_intermolecular)!

260 0 0 Sp3-sp2_Macmillan_coupling_with_bromide_(intermolecular) C211238 "UROBGGNSTLIPEU-UHFFFAOYSA-N"

reactants =
[283623]

product = C211238 "UROBGGNSTLIPEU-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sp3-sp2_Macmillan_coupling_with_bromide_(intermolecular)!

260 1 0 Larock_indole_synthesis C211238 "UROBGGNSTLIPEU-UHFFFAOYSA-N"

reactants =
[283624]

product = C211238 "UROBGGNSTLIPEU-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Larock_indole_synthesis!

260 2 0 Sp3-sp2_Macmillan_coupling_with_chloride_(intermolecular) C211238 "UROBGGNSTLIPEU-UHFFFAOYSA-N"

reactants =
[283625]

product = C211238 "UROBGGNSTLIPEU-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sp3-sp2_Macmillan_coupling_with_chloride_(intermolecular)!

260 3 0 Larock_indole_synthesis C211238 "UROBGGNSTLIPEU-UHFFFAOYSA-N"

reactants =
[283624]

product = C211238 "UROBGGNSTLIPEU-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Larock_indole_synthesis!

260 4 0 Larock_indole_synthesis C211238 "UROBGGNSTLIPEU-UHFFFAOYSA-N"

reactants =
[283624]

product = C211238 "UROBGGNSTLIPEU-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Larock_indole_synthesis!

264 0 0 Amine_alkylation C214698 "TVYXXSMKKFSTDL-UHFFFAOYSA-N"

reactants =
[282910, 283626]

product = C214698 "TVYXXSMKKFSTDL-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

264 1 0 Amide_to_amine_reduction C214698 "TVYXXSMKKFSTDL-UHFFFAOYSA-N"

reactants =
[283627]

product = C214698 "TVYXXSMKKFSTDL-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amide_to_amine_reduction!

264 2 0 Amine_alkylation C214698 "TVYXXSMKKFSTDL-UHFFFAOYSA-N"

reactants =
[282910, 283628]

product = C214698 "TVYXXSMKKFSTDL-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

264 3 0 Amine_alkylation C214698 "TVYXXSMKKFSTDL-UHFFFAOYSA-N"

reactants =
[282910, 283629]

product = C214698 "TVYXXSMKKFSTDL-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

264 4 0 Amine_alkylation C214698 "TVYXXSMKKFSTDL-UHFFFAOYSA-N"

reactants =
[282910, 283630]

product = C214698 "TVYXXSMKKFSTDL-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

268 0 0 Buchwald-Hartwig_amidation_with_amide-like_nucleophile C252325 "JWUDNWNUFKEQFE-UHFFFAOYSA-N"

268 1 0 Amidation C252325 "JWUDNWNUFKEQFE-UHFFFAOYSA-N"

268 1 1 Sulfonamide_Schotten-Baumann_with_amine_(intermolecular) C283632 "LEJYRUVLBQCOPP-UHFFFAOYSA-N"

reactants =
[283633, 283634]

product = C283632 "LEJYRUVLBQCOPP-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sulfonamide_Schotten-Baumann_with_amine_(intermolecular)!

268 2 0 Buchwald-Hartwig_amidation_with_amide-like_nucleophile C252325 "JWUDNWNUFKEQFE-UHFFFAOYSA-N"

268 3 0 Amidation C252325 "JWUDNWNUFKEQFE-UHFFFAOYSA-N"

268 3 1 Buchwald-Hartwig_amidation_with_amide-like_nucleophile C283632 "LEJYRUVLBQCOPP-UHFFFAOYSA-N"

268 4 0 Ester_amidation C252325 "JWUDNWNUFKEQFE-UHFFFAOYSA-N"

268 4 1 Sulfonamide_Schotten-Baumann_with_amine_(intermolecular) C283637 "QFQQBRPYQGTDGS-UHFFFAOYSA-N"

reactants =
[283634, 283638]

product = C283637 "QFQQBRPYQGTDGS-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sulfonamide_Schotten-Baumann_with_amine_(intermolecular)!

271 0 0 Grignard_addition_to_carbonyl C254303 "HVXHFWAWXOENKE-UHFFFAOYSA-N"

reactants =
[283639, 283640]

product = C254303 "HVXHFWAWXOENKE-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Grignard_addition_to_carbonyl!

271 1 0 Alpha_alkylation_of_ester/amide C254303 "HVXHFWAWXOENKE-UHFFFAOYSA-N"

reactants =
[283641]

product = C254303 "HVXHFWAWXOENKE-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ester/amide!

271 2 0 Alpha_alkylation_of_ester/amide C254303 "HVXHFWAWXOENKE-UHFFFAOYSA-N"

reactants =
[283642]

product = C254303 "HVXHFWAWXOENKE-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ester/amide!

271 3 0 Grignard_addition_to_carbonyl C254303 "HVXHFWAWXOENKE-UHFFFAOYSA-N"

reactants =
[283639, 283640]

product = C254303 "HVXHFWAWXOENKE-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Grignard_addition_to_carbonyl!

271 4 0 Enolate_conjugate_addition C254303 "HVXHFWAWXOENKE-UHFFFAOYSA-N"

reactants =
[283643]

product = C254303 "HVXHFWAWXOENKE-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Enolate_conjugate_addition!

273 0 0 Buchwald-Hartwig_amination C168335 "QYPHKTUDALALPC-UHFFFAOYSA-N"

273 0 1 Amidation C282999 "WLZWMDCXPZGGJR-UHFFFAOYSA-N"

273 0 2 Alpha_alkylation_of_ester/amide C283000 "AVBWDXQWYUBHBP-UHFFFAOYSA-N"

reactants =
[276, 283003]

product = C283000 "AVBWDXQWYUBHBP-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ester/amide!

273 1 0 N-nucleophilic_aromatic_substitution C168335 "QYPHKTUDALALPC-UHFFFAOYSA-N"

273 1 1 Ester_amidation C282999 "WLZWMDCXPZGGJR-UHFFFAOYSA-N"

273 1 2 Alpha_alkylation_of_ester/amide C283000 "AVBWDXQWYUBHBP-UHFFFAOYSA-N"

reactants =
[276, 283005]

product = C283000 "AVBWDXQWYUBHBP-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ester/amide!

273 2 0 N-nucleophilic_aromatic_substitution C168335 "QYPHKTUDALALPC-UHFFFAOYSA-N"

273 2 1 Ester_amidation C282999 "WLZWMDCXPZGGJR-UHFFFAOYSA-N"

273 2 2 Alpha_alkylation_of_ester/amide C283000 "AVBWDXQWYUBHBP-UHFFFAOYSA-N"

reactants =
[276, 283003]

product = C283000 "AVBWDXQWYUBHBP-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ester/amide!

273 3 0 Buchwald-Hartwig_amination C168335 "QYPHKTUDALALPC-UHFFFAOYSA-N"

273 3 1 Ester_amidation C282999 "WLZWMDCXPZGGJR-UHFFFAOYSA-N"

273 3 2 Alpha_alkylation_of_ester/amide C283000 "AVBWDXQWYUBHBP-UHFFFAOYSA-N"

reactants =
[276, 283005]

product = C283000 "AVBWDXQWYUBHBP-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ester/amide!

273 4 0 Alpha-arylation C168335 "QYPHKTUDALALPC-UHFFFAOYSA-N"

reactants =
[167679, 283644]

product = C168335 "QYPHKTUDALALPC-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha-arylation!

274 0 0 Amidation C169562 "DOTHXRCBGJFSGT-UHFFFAOYSA-N"

274 0 1 Hydrogenation_of_pyridine C283646 "RGGUIHXXUSOYSL-UHFFFAOYSA-N"

 Warning  SMILES changed during compound registration: NC(=O)c1ccc(O)nc1 --> NC(=O)c1ccc(=O)[nH]c1!

reactants =
[21271]

product = C283646 "RGGUIHXXUSOYSL-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Hydrogenation_of_pyridine!

274 1 0 Ester_amidation C169562 "DOTHXRCBGJFSGT-UHFFFAOYSA-N"

274 1 1 Hydrogenation_of_pyridine C283646 "RGGUIHXXUSOYSL-UHFFFAOYSA-N"

 Warning  SMILES changed during compound registration: NC(=O)c1ccc(O)nc1 --> NC(=O)c1ccc(=O)[nH]c1!

reactants =
[21271]

product = C283646 "RGGUIHXXUSOYSL-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Hydrogenation_of_pyridine!

274 2 0 Ester_amidation C169562 "DOTHXRCBGJFSGT-UHFFFAOYSA-N"

274 2 1 Amidation C283648 "PTAOVMMFKZKPHL-UHFFFAOYSA-N"

274 2 2 Hydrogenation_of_pyridine C283649 "VVYUCPWQCLVGFG-UHFFFAOYSA-N"

reactants =
[283650]

product = C283649 "VVYUCPWQCLVGFG-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Hydrogenation_of_pyridine!

274 3 0 Ester_amidation C169562 "DOTHXRCBGJFSGT-UHFFFAOYSA-N"

274 3 1 Hydrogenation_of_pyridine C283646 "RGGUIHXXUSOYSL-UHFFFAOYSA-N"

 Warning  SMILES changed during compound registration: NC(=O)c1ccc(O)nc1 --> NC(=O)c1ccc(=O)[nH]c1!

reactants =
[21271]

product = C283646 "RGGUIHXXUSOYSL-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Hydrogenation_of_pyridine!

274 4 0 Ester_amidation C169562 "DOTHXRCBGJFSGT-UHFFFAOYSA-N"

284 0 0 Amidation C276709 "ARBXKTTXCOPQPM-UHFFFAOYSA-N"

284 0 1 Grignard_addition_to_carbonyl C283653 "VGEOYVUWOOPOJH-UHFFFAOYSA-N"

reactants =
[283509, 283654]

product = C283653 "VGEOYVUWOOPOJH-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Grignard_addition_to_carbonyl!

284 1 0 Alpha_alkylation_of_ester/amide C276709 "ARBXKTTXCOPQPM-UHFFFAOYSA-N"

reactants =
[283655]

product = C276709 "ARBXKTTXCOPQPM-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ester/amide!

284 2 0 Grignard_addition_to_carbonyl C276709 "ARBXKTTXCOPQPM-UHFFFAOYSA-N"

reactants =
[283640, 283654]

product = C276709 "ARBXKTTXCOPQPM-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Grignard_addition_to_carbonyl!

284 3 0 Alpha_alkylation_of_ester/amide C276709 "ARBXKTTXCOPQPM-UHFFFAOYSA-N"

reactants =
[283656]

product = C276709 "ARBXKTTXCOPQPM-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ester/amide!

284 4 0 Mannich_reaction C276709 "ARBXKTTXCOPQPM-UHFFFAOYSA-N"

reactants =
[283657]

product = C276709 "ARBXKTTXCOPQPM-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Mannich_reaction!

287 0 0 N-Ac_deprotection C277954 "PUPGQZFKQUNUEK-UHFFFAOYSA-N"

reactants =
[283658]

product = C277954 "PUPGQZFKQUNUEK-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: N-Ac_deprotection!

287 1 0 N-Ac_deprotection C277954 "PUPGQZFKQUNUEK-UHFFFAOYSA-N"

reactants =
[283658]

product = C277954 "PUPGQZFKQUNUEK-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: N-Ac_deprotection!

287 2 0 N-Ac_deprotection C277954 "PUPGQZFKQUNUEK-UHFFFAOYSA-N"

reactants =
[283658]

product = C277954 "PUPGQZFKQUNUEK-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: N-Ac_deprotection!

287 3 0 N-Ac_deprotection C277954 "PUPGQZFKQUNUEK-UHFFFAOYSA-N"

reactants =
[283658]

product = C277954 "PUPGQZFKQUNUEK-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: N-Ac_deprotection!

287 4 0 N-Ac_deprotection C277954 "PUPGQZFKQUNUEK-UHFFFAOYSA-N"

reactants =
[283658]

product = C277954 "PUPGQZFKQUNUEK-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: N-Ac_deprotection!

288 0 0 Corey-House_synthesis_(intermolecular) C242679 "QOPZJBUCVFBGAX-UHFFFAOYSA-N"

reactants =
[283659, 283660]

product = C242679 "QOPZJBUCVFBGAX-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Corey-House_synthesis_(intermolecular)!

288 1 0 Amine_alkylation C242679 "QOPZJBUCVFBGAX-UHFFFAOYSA-N"

reactants =
[282910, 283661]

product = C242679 "QOPZJBUCVFBGAX-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

288 2 0 Corey-House_synthesis_(intermolecular) C242679 "QOPZJBUCVFBGAX-UHFFFAOYSA-N"

reactants =
[283662, 283663]

product = C242679 "QOPZJBUCVFBGAX-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Corey-House_synthesis_(intermolecular)!

288 3 0 Corey-House_synthesis_(intermolecular) C242679 "QOPZJBUCVFBGAX-UHFFFAOYSA-N"

reactants =
[283664, 283665]

product = C242679 "QOPZJBUCVFBGAX-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Corey-House_synthesis_(intermolecular)!

288 4 0 Corey-House_synthesis_(intermolecular) C242679 "QOPZJBUCVFBGAX-UHFFFAOYSA-N"

reactants =
[283662, 283666]

product = C242679 "QOPZJBUCVFBGAX-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Corey-House_synthesis_(intermolecular)!

295 0 0 Ester_amidation C197218 "WJNYPPPXBFUKQL-UHFFFAOYSA-N"

295 1 0 Ester_ammonolysis C197218 "WJNYPPPXBFUKQL-UHFFFAOYSA-N"

reactants =
[283667]

product = C197218 "WJNYPPPXBFUKQL-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Ester_ammonolysis!

295 2 0 Ester_ammonolysis C197218 "WJNYPPPXBFUKQL-UHFFFAOYSA-N"

reactants =
[283667]

product = C197218 "WJNYPPPXBFUKQL-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Ester_ammonolysis!

295 3 0 Ester_amidation C197218 "WJNYPPPXBFUKQL-UHFFFAOYSA-N"

295 4 0 Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide C197218 "WJNYPPPXBFUKQL-UHFFFAOYSA-N"

reactants =
[283668]

product = C197218 "WJNYPPPXBFUKQL-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide!

296 0 0 Alpha_alkylation_of_ester/amide C230890 "AZEOFDDNIYRHDU-UHFFFAOYSA-N"

reactants =
[283669]

product = C230890 "AZEOFDDNIYRHDU-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ester/amide!

296 1 0 Amidation C230890 "AZEOFDDNIYRHDU-UHFFFAOYSA-N"

296 1 1 Ugi_reaction C283670 "RUDZOOKCRJZREA-UHFFFAOYSA-N"

reactants =
[283671, 283672, 283673]

product = C283670 "RUDZOOKCRJZREA-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Ugi_reaction!

296 2 0 Ugi_reaction C230890 "AZEOFDDNIYRHDU-UHFFFAOYSA-N"

reactants =
[283671, 283673, 283674]

product = C230890 "AZEOFDDNIYRHDU-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Ugi_reaction!

296 3 0 Ugi_reaction C230890 "AZEOFDDNIYRHDU-UHFFFAOYSA-N"

reactants =
[283671, 283673, 283674]

product = C230890 "AZEOFDDNIYRHDU-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Ugi_reaction!

296 4 0 Ugi_reaction C230890 "AZEOFDDNIYRHDU-UHFFFAOYSA-N"

reactants =
[283671, 283673, 283674]

product = C230890 "AZEOFDDNIYRHDU-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Ugi_reaction!

297 0 0 Sp2-sp2_Suzuki_coupling C231412 "QUQJXZGKMPTGAK-UHFFFAOYSA-N"

297 0 1 Corey-House_synthesis_(intermolecular) C283675 "VZGXZFANIISPRR-UHFFFAOYSA-N"

reactants =
[283677, 283678]

product = C283675 "VZGXZFANIISPRR-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Corey-House_synthesis_(intermolecular)!

297 1 0 Corey-House_synthesis_(intermolecular) C231412 "QUQJXZGKMPTGAK-UHFFFAOYSA-N"

reactants =
[283679, 283680]

product = C231412 "QUQJXZGKMPTGAK-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Corey-House_synthesis_(intermolecular)!

297 2 0 Stille_coupling C231412 "QUQJXZGKMPTGAK-UHFFFAOYSA-N"

reactants =
[283675, 283681]

product = C231412 "QUQJXZGKMPTGAK-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Stille_coupling!

297 3 0 Sp2-sp2_Negishi_coupling_(intermolecular) C231412 "QUQJXZGKMPTGAK-UHFFFAOYSA-N"

reactants =
[283675, 283682]

product = C231412 "QUQJXZGKMPTGAK-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sp2-sp2_Negishi_coupling_(intermolecular)!

297 4 0 Corey-House_synthesis_(intermolecular) C231412 "QUQJXZGKMPTGAK-UHFFFAOYSA-N"

reactants =
[283679, 283683]

product = C231412 "QUQJXZGKMPTGAK-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Corey-House_synthesis_(intermolecular)!

298 0 0 Alpha_alkylation_of_sulphones C255845 "CPWFSKJMEDRRBR-UHFFFAOYSA-N"

reactants =
[283684, 283685]

product = C255845 "CPWFSKJMEDRRBR-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_sulphones!

298 1 0 Alpha_alkylation_of_sulphones C255845 "CPWFSKJMEDRRBR-UHFFFAOYSA-N"

reactants =
[283685, 283686]

product = C255845 "CPWFSKJMEDRRBR-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_sulphones!

298 2 0 Alpha_alkylation_of_sulphones C255845 "CPWFSKJMEDRRBR-UHFFFAOYSA-N"

reactants =
[283127, 283687]

product = C255845 "CPWFSKJMEDRRBR-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_sulphones!

298 3 0 Alpha_alkylation_of_sulphones C255845 "CPWFSKJMEDRRBR-UHFFFAOYSA-N"

reactants =
[283128, 283687]

product = C255845 "CPWFSKJMEDRRBR-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_sulphones!

298 4 0 Alpha_alkylation_of_sulphones C255845 "CPWFSKJMEDRRBR-UHFFFAOYSA-N"

reactants =
[283280, 283687]

product = C255845 "CPWFSKJMEDRRBR-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_sulphones!

299 0 0 Corey-House_synthesis_(intermolecular) C256490 "RPDFRSKJKOQCIT-UHFFFAOYSA-N"

reactants =
[283688, 283689]

product = C256490 "RPDFRSKJKOQCIT-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Corey-House_synthesis_(intermolecular)!

299 1 0 Corey-House_synthesis_(intermolecular) C256490 "RPDFRSKJKOQCIT-UHFFFAOYSA-N"

reactants =
[283688, 283690]

product = C256490 "RPDFRSKJKOQCIT-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Corey-House_synthesis_(intermolecular)!

299 2 0 Corey-House_synthesis_(intermolecular) C256490 "RPDFRSKJKOQCIT-UHFFFAOYSA-N"

reactants =
[283688, 283691]

product = C256490 "RPDFRSKJKOQCIT-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Corey-House_synthesis_(intermolecular)!

299 3 0 Corey-House_synthesis_(intermolecular) C256490 "RPDFRSKJKOQCIT-UHFFFAOYSA-N"

reactants =
[283692, 283693]

product = C256490 "RPDFRSKJKOQCIT-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Corey-House_synthesis_(intermolecular)!

299 4 0 Corey-House_synthesis_(intermolecular) C256490 "RPDFRSKJKOQCIT-UHFFFAOYSA-N"

reactants =
[283694, 283695]

product = C256490 "RPDFRSKJKOQCIT-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Corey-House_synthesis_(intermolecular)!

300 0 0 Sp3-sp2_Macmillan_coupling_with_bromide_(intermolecular) C256517 "QPUYECUOLPXSFR-UHFFFAOYSA-N"

reactants =
[283280, 283696]

product = C256517 "QPUYECUOLPXSFR-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sp3-sp2_Macmillan_coupling_with_bromide_(intermolecular)!

300 1 0 Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide C256517 "QPUYECUOLPXSFR-UHFFFAOYSA-N"

reactants =
[282914, 283696]

product = C256517 "QPUYECUOLPXSFR-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide!

300 2 0 Friedel-Crafts_methylation C256517 "QPUYECUOLPXSFR-UHFFFAOYSA-N"

reactants =
[283697]

product = C256517 "QPUYECUOLPXSFR-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Friedel-Crafts_methylation!

300 3 0 Corey-House_synthesis_(intermolecular) C256517 "QPUYECUOLPXSFR-UHFFFAOYSA-N"

reactants =
[283128, 283698]

product = C256517 "QPUYECUOLPXSFR-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Corey-House_synthesis_(intermolecular)!

300 4 0 Corey-House_synthesis_(intermolecular) C256517 "QPUYECUOLPXSFR-UHFFFAOYSA-N"

reactants =
[283128, 283698]

product = C256517 "QPUYECUOLPXSFR-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Corey-House_synthesis_(intermolecular)!

302 0 0 Sp2-sp2_Suzuki_coupling C256575 "POSUBGQGUWKMGE-UHFFFAOYSA-N"

302 0 1 Sp3-sp2_Suzuki_coupling C283699 "RIKJWLGFIOPLBT-UHFFFAOYSA-N"

 Success  registered route 41!

303 0 0 Alpha_alkylation_of_aldehyde C257314 "UXHKPKPTEJXYTA-UHFFFAOYSA-N"

reactants =
[283702]

product = C257314 "UXHKPKPTEJXYTA-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_aldehyde!

303 1 0 Buchwald-Hartwig_(thio)etherification C257314 "UXHKPKPTEJXYTA-UHFFFAOYSA-N"

reactants =
[282996, 283703]

product = C257314 "UXHKPKPTEJXYTA-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Buchwald-Hartwig_(thio)etherification!

303 2 0 Buchwald-Hartwig_(thio)etherification C257314 "UXHKPKPTEJXYTA-UHFFFAOYSA-N"

reactants =
[282996, 283704]

product = C257314 "UXHKPKPTEJXYTA-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Buchwald-Hartwig_(thio)etherification!

303 3 0 Nucleophilic_substitution_with_thiol C257314 "UXHKPKPTEJXYTA-UHFFFAOYSA-N"

reactants =
[282996, 283705]

product = C257314 "UXHKPKPTEJXYTA-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Nucleophilic_substitution_with_thiol!

303 4 0 Buchwald-Hartwig_(thio)etherification C257314 "UXHKPKPTEJXYTA-UHFFFAOYSA-N"

reactants =
[282996, 283704]

product = C257314 "UXHKPKPTEJXYTA-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Buchwald-Hartwig_(thio)etherification!

308 0 0 Hydrolysis_of_magnesium_alkylthiolate C151891 "AJHJYWCUIVFJRP-UHFFFAOYSA-N"

reactants =
[283706]

product = C151891 "AJHJYWCUIVFJRP-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Hydrolysis_of_magnesium_alkylthiolate!

308 1 0 Hydrolysis_of_magnesium_alkylthiolate C151891 "AJHJYWCUIVFJRP-UHFFFAOYSA-N"

reactants =
[283707]

product = C151891 "AJHJYWCUIVFJRP-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Hydrolysis_of_magnesium_alkylthiolate!

308 2 0 Corey-House_synthesis_(intermolecular) C151891 "AJHJYWCUIVFJRP-UHFFFAOYSA-N"

reactants =
[283368, 283708]

product = C151891 "AJHJYWCUIVFJRP-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Corey-House_synthesis_(intermolecular)!

308 3 0 Hydrolysis_of_magnesium_alkylthiolate C151891 "AJHJYWCUIVFJRP-UHFFFAOYSA-N"

reactants =
[283709]

product = C151891 "AJHJYWCUIVFJRP-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Hydrolysis_of_magnesium_alkylthiolate!

308 4 0 Hydrolysis_of_magnesium_alkylthiolate C151891 "AJHJYWCUIVFJRP-UHFFFAOYSA-N"

reactants =
[283707]

product = C151891 "AJHJYWCUIVFJRP-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Hydrolysis_of_magnesium_alkylthiolate!

309 0 0 Amidation C99664 "HFLHXSXUCRDIDV-UHFFFAOYSA-N"

 Success  registered route 42!

310 0 0 Amidation C48074 "XDBQWQWEVJPNBV-UHFFFAOYSA-N"

 Success  registered route 43!

311 0 0 Formation_of_urea_from_two_amines C47239 "QZMIVAQLNCUJAN-UHFFFAOYSA-N"

311 1 0 Aziridine_+_amine_coupling C47239 "QZMIVAQLNCUJAN-UHFFFAOYSA-N"

reactants =
[283710, 283711]

product = C47239 "QZMIVAQLNCUJAN-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Aziridine_+_amine_coupling!

311 2 0 Formation_of_urea_from_two_amines C47239 "QZMIVAQLNCUJAN-UHFFFAOYSA-N"

311 3 0 N-Boc_deprotection C47239 "QZMIVAQLNCUJAN-UHFFFAOYSA-N"

311 3 1 Amide_to_amine_reduction C283712 "RYCIGFTYXOIQNX-UHFFFAOYSA-N"

reactants =
[283713]

product = C283712 "RYCIGFTYXOIQNX-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amide_to_amine_reduction!

311 4 0 Amide_to_amine_reduction C47239 "QZMIVAQLNCUJAN-UHFFFAOYSA-N"

reactants =
[283714]

product = C47239 "QZMIVAQLNCUJAN-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amide_to_amine_reduction!

312 0 0 Formation_of_urea_from_two_amines C50543 "CXUYUFRBAKGUHD-UHFFFAOYSA-N"

 Success  registered route 44!

313 0 0 Sulfonamide_Schotten-Baumann_with_amine_(intermolecular) C125028 "GKRPCXYDRCZNEJ-UHFFFAOYSA-N"

reactants =
[283012, 283013]

product = C125028 "GKRPCXYDRCZNEJ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sulfonamide_Schotten-Baumann_with_amine_(intermolecular)!

313 1 0 Formation_of_sulfonamide_from_halide_-_Shavnya_reaction C125028 "GKRPCXYDRCZNEJ-UHFFFAOYSA-N"

reactants =
[283013, 283715]

product = C125028 "GKRPCXYDRCZNEJ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Formation_of_sulfonamide_from_halide_-_Shavnya_reaction!

313 2 0 Formation_of_sulfonamide_from_halide_-_Shavnya_reaction C125028 "GKRPCXYDRCZNEJ-UHFFFAOYSA-N"

reactants =
[283013, 283716]

product = C125028 "GKRPCXYDRCZNEJ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Formation_of_sulfonamide_from_halide_-_Shavnya_reaction!

313 3 0 Sulfonamide_Schotten-Baumann_with_amine_(intermolecular) C125028 "GKRPCXYDRCZNEJ-UHFFFAOYSA-N"

reactants =
[283013, 283014]

product = C125028 "GKRPCXYDRCZNEJ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sulfonamide_Schotten-Baumann_with_amine_(intermolecular)!

313 4 0 Amine_alkylation C125028 "GKRPCXYDRCZNEJ-UHFFFAOYSA-N"

reactants =
[283717, 283718]

product = C125028 "GKRPCXYDRCZNEJ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

314 0 0 Chan-Lam_coupling_of_amides,_sulfonamides,_and_imides C51269 "NHKSKEKGNRBSQB-UHFFFAOYSA-N"

reactants =
[283719, 283720]

product = C51269 "NHKSKEKGNRBSQB-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Chan-Lam_coupling_of_amides,_sulfonamides,_and_imides!

314 1 0 Chan-Lam_coupling_of_amides,_sulfonamides,_and_imides C51269 "NHKSKEKGNRBSQB-UHFFFAOYSA-N"

reactants =
[283259, 283721]

product = C51269 "NHKSKEKGNRBSQB-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Chan-Lam_coupling_of_amides,_sulfonamides,_and_imides!

314 2 0 Amidation C51269 "NHKSKEKGNRBSQB-UHFFFAOYSA-N"

 Success  registered route 45!

315 0 0 Amidation C118932 "RQGLZHKMFNDMSH-UHFFFAOYSA-N"

 Success  registered route 46!

316 0 0 Amidation C55900 "AUFDHAWKPJKIFW-UHFFFAOYSA-N"

 Success  registered route 47!

317 0 0 Amidation C132547 "KBKFCGYHNXKBGD-UHFFFAOYSA-N"

 Success  registered route 48!

318 0 0 Amidation C53753 "MPUTVVNRSHICME-UHFFFAOYSA-N"

 Success  registered route 49!

319 0 0 Amidation C53845 "IWAUSDKULMXZBG-UHFFFAOYSA-N"

 Success  registered route 50!

320 0 0 Amidation C50771 "DERWPRAMEWIASL-UHFFFAOYSA-N"

 Success  registered route 51!

321 0 0 Amidation C55108 "GCVSXZYUPXGABM-UHFFFAOYSA-N"

 Success  registered route 52!

322 0 0 Amidation C52055 "OOQQOYYILDTRKK-UHFFFAOYSA-N"

 Success  registered route 53!

323 0 0 N-nucleophilic_aromatic_substitution C48060 "SADILTYBWIPMCP-UHFFFAOYSA-N"

 Success  registered route 54!

324 0 0 Amidation C52315 "DRFIGHDMHNBPNI-UHFFFAOYSA-N"

 Success  registered route 55!

325 0 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C46014 "IASQNHULNRESLR-UHFFFAOYSA-N"

 Success  registered route 56!

326 0 0 Amidation C53040 "XDRXTMXRRKPSOB-UHFFFAOYSA-N"

 Success  registered route 57!

327 0 0 Amidation C114736 "PNWBUTYUCZZJJG-UHFFFAOYSA-N"

 Success  registered route 58!

328 0 0 Amidation C47019 "BMJHPSVXCNOHQF-UHFFFAOYSA-N"

 Success  registered route 59!

329 0 0 Chan-Lam_coupling_of_amides,_sulfonamides,_and_imides C96278 "NCVNEKNWZFVLLU-UHFFFAOYSA-N"

reactants =
[283045, 283722]

product = C96278 "NCVNEKNWZFVLLU-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Chan-Lam_coupling_of_amides,_sulfonamides,_and_imides!

329 1 0 Amidation C96278 "NCVNEKNWZFVLLU-UHFFFAOYSA-N"

329 1 1 Iodo_N-arylation C283041 "JZIXTRKNTSJDCX-UHFFFAOYSA-N"

reactants =
[283043, 283044]

product = C283041 "JZIXTRKNTSJDCX-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Iodo_N-arylation!

329 2 0 Ester_amidation C96278 "NCVNEKNWZFVLLU-UHFFFAOYSA-N"

329 2 1 Nucleophilic_aromatic_substitution_(methylsulfone) C283041 "JZIXTRKNTSJDCX-UHFFFAOYSA-N"

reactants =
[283043, 283724]

product = C283041 "JZIXTRKNTSJDCX-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Nucleophilic_aromatic_substitution_(methylsulfone)!

329 3 0 Buchwald-Hartwig_amidation_with_amide-like_nucleophile C96278 "NCVNEKNWZFVLLU-UHFFFAOYSA-N"

 Success  registered route 60!

330 0 0 Amidation C51690 "HIPQRAVJSVNPNW-UHFFFAOYSA-N"

 Success  registered route 61!

331 0 0 Amidation C46618 "VSXISTKWWYBVFB-UHFFFAOYSA-N"

 Success  registered route 62!

332 0 0 Amidation C47002 "RVJZPQWJVCMQJG-UHFFFAOYSA-N"

 Success  registered route 63!

333 0 0 Amidation C75387 "RVAWSFXUAFVMPF-UHFFFAOYSA-N"

 Success  registered route 64!

334 0 0 Formation_of_urea_from_two_amines C106576 "FQWFLXFNFAHVSP-UHFFFAOYSA-N"

 Success  registered route 65!

335 0 0 Amidation C48061 "ACFDSVWQCUCXCX-UHFFFAOYSA-N"

 Success  registered route 66!

336 0 0 Formation_of_urea_from_two_amines C51476 "AKYURMVRRSEXJK-UHFFFAOYSA-N"

 Success  registered route 67!

337 0 0 Amidation C53713 "RJDKANFIVPITIR-UHFFFAOYSA-N"

 Success  registered route 68!

338 0 0 Amidation C66331 "IHLYYSVXTFTBPP-UHFFFAOYSA-N"

 Success  registered route 69!

339 0 0 Chan-Lam_coupling_(amination) C4093 "OMOCVUPRTIPABZ-UHFFFAOYSA-N"

reactants =
[283064, 283065]

product = C4093 "OMOCVUPRTIPABZ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Chan-Lam_coupling_(amination)!

339 1 0 Debus-Radziszewski_imidazole_synthesis C4093 "OMOCVUPRTIPABZ-UHFFFAOYSA-N"

reactants =
[283725, 283726]

product = C4093 "OMOCVUPRTIPABZ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Debus-Radziszewski_imidazole_synthesis!

339 2 0 N-nucleophilic_aromatic_substitution C4093 "OMOCVUPRTIPABZ-UHFFFAOYSA-N"

 Success  registered route 70!

340 0 0 Amidation C13618 "LAWDOCROZLLCBL-UHFFFAOYSA-N"

 Success  registered route 71!

341 0 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C51896 "VPSJRYBKMAUUSC-UHFFFAOYSA-N"

 Success  registered route 72!

342 0 0 Amidation C53762 "UMSVOSGNJDZBKA-UHFFFAOYSA-N"

 Success  registered route 73!

343 0 0 Buchwald-Hartwig_(thio)etherification C77791 "DIUMSFGKZNZUAS-UHFFFAOYSA-N"

reactants =
[283073, 283727]

product = C77791 "DIUMSFGKZNZUAS-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Buchwald-Hartwig_(thio)etherification!

343 1 0 Buchwald-Hartwig_(thio)etherification C77791 "DIUMSFGKZNZUAS-UHFFFAOYSA-N"

reactants =
[283073, 283728]

product = C77791 "DIUMSFGKZNZUAS-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Buchwald-Hartwig_(thio)etherification!

343 2 0 Buchwald-Hartwig_(thio)etherification C77791 "DIUMSFGKZNZUAS-UHFFFAOYSA-N"

reactants =
[283073, 283729]

product = C77791 "DIUMSFGKZNZUAS-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Buchwald-Hartwig_(thio)etherification!

343 3 0 S-nucleophilic_aromatic_substitution C77791 "DIUMSFGKZNZUAS-UHFFFAOYSA-N"

reactants =
[283073, 283074]

product = C77791 "DIUMSFGKZNZUAS-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: S-nucleophilic_aromatic_substitution!

343 4 0 Buchwald-Hartwig_(thio)etherification C77791 "DIUMSFGKZNZUAS-UHFFFAOYSA-N"

reactants =
[283073, 283730]

product = C77791 "DIUMSFGKZNZUAS-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Buchwald-Hartwig_(thio)etherification!

344 0 0 Amidation C45975 "CEMUYZQUYWHICQ-UHFFFAOYSA-N"

 Success  registered route 74!

345 0 0 Ester_amidation C51448 "COFDIZZNQGQPRY-UHFFFAOYSA-N"

 Success  registered route 75!

346 0 0 Amidation C57322 "AKSNBUPFDFKHMM-UHFFFAOYSA-N"

 Success  registered route 76!

347 0 0 Amidation C61947 "AOQUYKRGVSCMIY-UHFFFAOYSA-N"

 Success  registered route 77!

348 0 0 Amidation C3735 "ZPJZDVARGNTQTH-UHFFFAOYSA-N"

 Success  registered route 78!

349 0 0 Amidation C41201 "PWNWGEJUGNEAPQ-UHFFFAOYSA-N"

 Success  registered route 79!

350 0 0 Ester_amidation C47635 "LAHXOKLNMJHBTG-UHFFFAOYSA-N"

 Success  registered route 80!

351 0 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C45979 "LLUOFVPUDREFGO-UHFFFAOYSA-N"

 Success  registered route 81!

352 0 0 Passerini_reaction C53411 "HLUHSVZNKBAJRE-UHFFFAOYSA-N"

reactants =
[283156, 283734, 283735]

product = C53411 "HLUHSVZNKBAJRE-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Passerini_reaction!

352 1 0 Amidation C53411 "HLUHSVZNKBAJRE-UHFFFAOYSA-N"

 Success  registered route 82!

353 0 0 Amidation C65382 "MZDGATSJXWUBEN-UHFFFAOYSA-N"

 Success  registered route 83!

354 0 0 Amidation C52108 "AZNSWSRGOHBTSU-UHFFFAOYSA-N"

 Success  registered route 84!

355 0 0 Amidation C48415 "IHYLMDBZOJESMS-UHFFFAOYSA-N"

 Success  registered route 85!

356 0 0 Amidation C48493 "KGOROLBWDGQCPO-UHFFFAOYSA-N"

 Success  registered route 86!

357 0 0 Amidation C51536 "YSKAKYHCRXBUPZ-UHFFFAOYSA-N"

 Success  registered route 87!

358 0 0 Amidation C65392 "VJAJBTQOYAJDPL-UHFFFAOYSA-N"

 Success  registered route 88!

359 0 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C47082 "LUJUPDFZVKGRPH-UHFFFAOYSA-N"

 Success  registered route 89!

360 0 0 TEMPO_oxidation C31470 "GODMAJBOTXASKT-UHFFFAOYSA-N"

reactants =
[283751]

product = C31470 "GODMAJBOTXASKT-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: TEMPO_oxidation!

360 1 0 Alpha_alkylation_of_aldehyde C31470 "GODMAJBOTXASKT-UHFFFAOYSA-N"

reactants =
[283111, 283752]

product = C31470 "GODMAJBOTXASKT-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_aldehyde!

360 2 0 Swern_oxidation C31470 "GODMAJBOTXASKT-UHFFFAOYSA-N"

reactants =
[283751]

product = C31470 "GODMAJBOTXASKT-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Swern_oxidation!

360 3 0 Mannich_reaction C31470 "GODMAJBOTXASKT-UHFFFAOYSA-N"

reactants =
[283111, 283753]

product = C31470 "GODMAJBOTXASKT-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Mannich_reaction!

360 4 0 Alpha_alkylation_of_aldehyde C31470 "GODMAJBOTXASKT-UHFFFAOYSA-N"

reactants =
[283111, 283754]

product = C31470 "GODMAJBOTXASKT-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_aldehyde!

361 0 0 Van_Leusen_imidazole_synthesis C6296 "UYOZDXASYOYYCF-UHFFFAOYSA-N"

reactants =
[283156, 283755, 283756]

product = C6296 "UYOZDXASYOYYCF-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Van_Leusen_imidazole_synthesis!

361 1 0 Amine_alkylation C6296 "UYOZDXASYOYYCF-UHFFFAOYSA-N"

reactants =
[283757, 283758]

product = C6296 "UYOZDXASYOYYCF-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

361 2 0 Amine_alkylation C6296 "UYOZDXASYOYYCF-UHFFFAOYSA-N"

reactants =
[283757, 283759]

product = C6296 "UYOZDXASYOYYCF-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

361 3 0 Amine_alkylation C6296 "UYOZDXASYOYYCF-UHFFFAOYSA-N"

reactants =
[283757, 283760]

product = C6296 "UYOZDXASYOYYCF-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

361 4 0 Amine_alkylation C6296 "UYOZDXASYOYYCF-UHFFFAOYSA-N"

reactants =
[283757, 283761]

product = C6296 "UYOZDXASYOYYCF-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

362 0 0 Sp2-sp2_Suzuki_coupling C58912 "WYHWZNDJHHPUFV-UHFFFAOYSA-N"

362 0 1 Minisci_reaction_with_carboxylic_acid_(intermolecular) C283762 "ZRYJXFULZYDOAZ-UHFFFAOYSA-N"

reactants =
[283764, 283765]

product = C283762 "ZRYJXFULZYDOAZ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Minisci_reaction_with_carboxylic_acid_(intermolecular)!

362 1 0 Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide C58912 "WYHWZNDJHHPUFV-UHFFFAOYSA-N"

reactants =
[87, 283766]

product = C58912 "WYHWZNDJHHPUFV-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide!

362 2 0 Sp2-sp2_Suzuki_coupling C58912 "WYHWZNDJHHPUFV-UHFFFAOYSA-N"

362 2 1 Minisci_reaction_with_carboxylic_acid_(intermolecular) C283768 "RFYPMLUHYINESU-UHFFFAOYSA-N"

reactants =
[283764, 283769]

product = C283768 "RFYPMLUHYINESU-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Minisci_reaction_with_carboxylic_acid_(intermolecular)!

362 3 0 Stille_coupling C58912 "WYHWZNDJHHPUFV-UHFFFAOYSA-N"

reactants =
[283762, 283770]

product = C58912 "WYHWZNDJHHPUFV-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Stille_coupling!

362 4 0 Sp2-sp2_Suzuki_coupling C58912 "WYHWZNDJHHPUFV-UHFFFAOYSA-N"

362 4 1 Minisci_reaction_with_carboxylic_acid_(intermolecular) C283768 "RFYPMLUHYINESU-UHFFFAOYSA-N"

reactants =
[283764, 283769]

product = C283768 "RFYPMLUHYINESU-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Minisci_reaction_with_carboxylic_acid_(intermolecular)!

363 0 0 Amidation C49901 "ARHWMQQRHMNSLN-UHFFFAOYSA-N"

 Success  registered route 90!

364 0 0 Amidation C50940 "GQSJCPRFXMQJKB-UHFFFAOYSA-N"

 Success  registered route 91!

365 0 0 Amidation C50851 "GEFPGABNNYEEAW-UHFFFAOYSA-N"

 Success  registered route 92!

366 0 0 Amidation C16361 "ZZPZYEPSKIPXIU-UHFFFAOYSA-N"

 Success  registered route 93!

367 0 0 Amidation C16361 "ZZPZYEPSKIPXIU-UHFFFAOYSA-N"

 Success  registered route 94!

368 0 0 Amidation C70596 "BQGWDOQDBRNDPW-UHFFFAOYSA-N"

 Success  registered route 95!

369 0 0 Amidation C53777 "VXPPOOOFALPUBZ-UHFFFAOYSA-N"

 Success  registered route 96!

370 0 0 Sulfonamide_Schotten-Baumann_with_amine_(intermolecular) C76574 "TZXZNVJKNDRZQE-UHFFFAOYSA-N"

reactants =
[283782, 283783]

product = C76574 "TZXZNVJKNDRZQE-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sulfonamide_Schotten-Baumann_with_amine_(intermolecular)!

370 1 0 Sulfonamide_Schotten-Baumann_with_amine_(intermolecular) C76574 "TZXZNVJKNDRZQE-UHFFFAOYSA-N"

reactants =
[283783, 283784]

product = C76574 "TZXZNVJKNDRZQE-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sulfonamide_Schotten-Baumann_with_amine_(intermolecular)!

370 2 0 Formation_of_sulfonamide_from_halide_-_Shavnya_reaction C76574 "TZXZNVJKNDRZQE-UHFFFAOYSA-N"

reactants =
[283783, 283785]

product = C76574 "TZXZNVJKNDRZQE-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Formation_of_sulfonamide_from_halide_-_Shavnya_reaction!

370 3 0 Formation_of_sulfonamide_from_halide_-_Shavnya_reaction C76574 "TZXZNVJKNDRZQE-UHFFFAOYSA-N"

reactants =
[283783, 283786]

product = C76574 "TZXZNVJKNDRZQE-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Formation_of_sulfonamide_from_halide_-_Shavnya_reaction!

370 4 0 Nucleophilic_aromatic_substitution_(alcohol,_phenol,_water) C76574 "TZXZNVJKNDRZQE-UHFFFAOYSA-N"

reactants =
[282914, 283787]

product = C76574 "TZXZNVJKNDRZQE-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Nucleophilic_aromatic_substitution_(alcohol,_phenol,_water)!

371 0 0 Reductive_amination C45878 "ZSXTWNYTZPYIOF-UHFFFAOYSA-N"

 Success  registered route 97!

372 0 0 Amidation C76291 "HLGWOCDYUXZSIL-UHFFFAOYSA-N"

 Success  registered route 98!

373 0 0 Amidation C79400 "SYIPTBSODVTYNX-UHFFFAOYSA-N"

 Success  registered route 99!

374 0 0 Formation_of_urea_from_two_amines C50246 "AGWJYAALTRFIFA-UHFFFAOYSA-N"

 Success  registered route 100!

375 0 0 Amidation C48099 "CYXFROYLOHDBPB-UHFFFAOYSA-N"

 Success  registered route 101!

376 0 0 Amidation C47038 "QXILYQDWBQFOGE-UHFFFAOYSA-N"

 Success  registered route 102!

377 0 0 Amidation C62872 "QYUCNRDAJOKRPK-UHFFFAOYSA-N"

 Success  registered route 103!

378 0 0 Ester_amidation C38721 "XOTFNADYVUYIDE-UHFFFAOYSA-N"

378 1 0 Alpha_alkylation_of_ester/amide C38721 "XOTFNADYVUYIDE-UHFFFAOYSA-N"

reactants =
[283802, 283803]

product = C38721 "XOTFNADYVUYIDE-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ester/amide!

378 2 0 Amidation C38721 "XOTFNADYVUYIDE-UHFFFAOYSA-N"

378 2 1 Alpha_alkylation_of_ester/amide C283804 "KVEOOEYBZQKPCO-UHFFFAOYSA-N"

reactants =
[283805, 283806]

product = C283804 "KVEOOEYBZQKPCO-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ester/amide!

378 3 0 Amidation C38721 "XOTFNADYVUYIDE-UHFFFAOYSA-N"

378 3 1 Amidation C283804 "KVEOOEYBZQKPCO-UHFFFAOYSA-N"

 Success  registered route 104!

379 0 0 Amine_alkylation C46503 "FQPQQAXCJVPZKB-UHFFFAOYSA-N"

reactants =
[283809, 283810]

product = C46503 "FQPQQAXCJVPZKB-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

379 1 0 N-nucleophilic_aromatic_substitution C46503 "FQPQQAXCJVPZKB-UHFFFAOYSA-N"

 Success  registered route 105!

380 0 0 Buchwald-Hartwig_amination_with_aromatic_nh_intermolecular C58344 "OHHKZZFRRXZMSR-UHFFFAOYSA-N"

reactants =
[283812, 283813]

product = C58344 "OHHKZZFRRXZMSR-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Buchwald-Hartwig_amination_with_aromatic_nh_intermolecular!

380 1 0 N-nucleophilic_aromatic_substitution C58344 "OHHKZZFRRXZMSR-UHFFFAOYSA-N"

 Success  registered route 106!

381 0 0 Petasis-borono_Mannich_reaction C97404 "FZJDHRNIVCAVDC-UHFFFAOYSA-N"

reactants =
[283111, 283815, 283816]

product = C97404 "FZJDHRNIVCAVDC-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Petasis-borono_Mannich_reaction!

381 1 0 Amine_alkylation C97404 "FZJDHRNIVCAVDC-UHFFFAOYSA-N"

reactants =
[283817, 283818]

product = C97404 "FZJDHRNIVCAVDC-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

381 2 0 Reductive_amination C97404 "FZJDHRNIVCAVDC-UHFFFAOYSA-N"

 Success  registered route 107!

382 0 0 Amidation C48528 "GQPALOGPMKZAID-UHFFFAOYSA-N"

 Success  registered route 108!

383 0 0 Amidation C51900 "LDYJYHQEZNWGPU-UHFFFAOYSA-N"

 Success  registered route 109!

384 0 0 Amidation C96113 "KUFKNJXJTDVHJC-UHFFFAOYSA-N"

 Success  registered route 110!

385 0 0 Amidation C118923 "YFAQFICQNGNQSS-UHFFFAOYSA-N"

 Success  registered route 111!

386 0 0 Isocyanate_to_urea C78261 "XPFGRKQWKIHVAC-UHFFFAOYSA-N"

reactants =
[283828, 283829]

product = C78261 "XPFGRKQWKIHVAC-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Isocyanate_to_urea!

386 1 0 Formation_of_urea_from_two_amines C78261 "XPFGRKQWKIHVAC-UHFFFAOYSA-N"

 Success  registered route 112!

387 0 0 Mitsunobu_aryl_ether_synthesis C64717 "SPKYROZOTIZKDR-UHFFFAOYSA-N"

reactants =
[283304, 283831]

product = C64717 "SPKYROZOTIZKDR-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Mitsunobu_aryl_ether_synthesis!

387 1 0 Williamson_ether_synthesis C64717 "SPKYROZOTIZKDR-UHFFFAOYSA-N"

 Success  registered route 113!

388 0 0 Amidation C78532 "DYSLDIFRQOYSOW-UHFFFAOYSA-N"

 Success  registered route 114!

389 0 0 Amidation C43009 "KPTSUQKOCKVBNL-UHFFFAOYSA-N"

 Success  registered route 115!

390 0 0 Formation_of_urea_from_two_amines C45769 "LHENNTRPFOOADT-UHFFFAOYSA-N"

 Success  registered route 116!

391 0 0 Amidation C48114 "DPEGMWUZRPHHNE-UHFFFAOYSA-N"

 Success  registered route 117!

392 0 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C50224 "JWOBBCBWIOGWLH-UHFFFAOYSA-N"

 Success  registered route 118!

393 0 0 Amidation C50761 "FTCITYYSQNDUFP-UHFFFAOYSA-N"

 Success  registered route 119!

394 0 0 Amidation C3682 "QWVLYQDYSGRLDZ-UHFFFAOYSA-N"

 Success  registered route 120!

395 0 0 Amidation C58974 "LHSJJHNLOFSIIV-UHFFFAOYSA-N"

 Success  registered route 121!

396 0 0 Amidation C55828 "CXKCEZSQRXABEZ-UHFFFAOYSA-N"

 Success  registered route 122!

397 0 0 Amine_alkylation C128372 "AEAKCWJGPKNEGI-UHFFFAOYSA-N"

reactants =
[12081, 283845]

product = C128372 "AEAKCWJGPKNEGI-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

397 1 0 Amide_to_amine_reduction C128372 "AEAKCWJGPKNEGI-UHFFFAOYSA-N"

reactants =
[128371]

product = C128372 "AEAKCWJGPKNEGI-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amide_to_amine_reduction!

397 2 0 Amine_alkylation C128372 "AEAKCWJGPKNEGI-UHFFFAOYSA-N"

reactants =
[12081, 283846]

product = C128372 "AEAKCWJGPKNEGI-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

397 3 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C128372 "AEAKCWJGPKNEGI-UHFFFAOYSA-N"

 Success  registered route 123!

398 0 0 Alpha_alkylation_of_ketone C73290 "AAOYCWPUIVHARW-UHFFFAOYSA-N"

reactants =
[283848, 283849]

product = C73290 "AAOYCWPUIVHARW-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ketone!

398 1 0 Alpha_alkylation_of_ketone C73290 "AAOYCWPUIVHARW-UHFFFAOYSA-N"

reactants =
[283848, 283850]

product = C73290 "AAOYCWPUIVHARW-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ketone!

398 2 0 Alpha_alkylation_of_ketone C73290 "AAOYCWPUIVHARW-UHFFFAOYSA-N"

reactants =
[283848, 283851]

product = C73290 "AAOYCWPUIVHARW-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ketone!

398 3 0 N-nucleophilic_aromatic_substitution C73290 "AAOYCWPUIVHARW-UHFFFAOYSA-N"

398 3 1 Alpha_alkylation_of_ketone C283852 "VZJYZDLIYYLKKY-UHFFFAOYSA-N"

reactants =
[283851, 283853]

product = C283852 "VZJYZDLIYYLKKY-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ketone!

398 4 0 N-Boc_deprotection C73290 "AAOYCWPUIVHARW-UHFFFAOYSA-N"

 Success  registered route 124!

399 0 0 Hydrogenation_of_pyridine C46480 "PYKGBZNJSJEWFO-UHFFFAOYSA-N"

reactants =
[283855]

product = C46480 "PYKGBZNJSJEWFO-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Hydrogenation_of_pyridine!

399 1 0 N-Ac_deprotection C46480 "PYKGBZNJSJEWFO-UHFFFAOYSA-N"

reactants =
[283856]

product = C46480 "PYKGBZNJSJEWFO-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: N-Ac_deprotection!

399 2 0 N-Cbz_deprotection C46480 "PYKGBZNJSJEWFO-UHFFFAOYSA-N"

reactants =
[283857]

product = C46480 "PYKGBZNJSJEWFO-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: N-Cbz_deprotection!

399 3 0 N-Boc_deprotection C46480 "PYKGBZNJSJEWFO-UHFFFAOYSA-N"

399 3 1 Sp3-sp2_Macmillan_coupling_with_chloride_(intermolecular) C283858 "TUDFDPUMGOJWMO-UHFFFAOYSA-N"

reactants =
[283859, 283860]

product = C283858 "TUDFDPUMGOJWMO-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sp3-sp2_Macmillan_coupling_with_chloride_(intermolecular)!

399 4 0 Sp3-sp2_Suzuki_coupling C46480 "PYKGBZNJSJEWFO-UHFFFAOYSA-N"

399 4 1 N-Ac_deprotection C283862 "OOADUXPFWDTAJA-UHFFFAOYSA-N"

reactants =
[283863]

product = C283862 "OOADUXPFWDTAJA-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: N-Ac_deprotection!

400 0 0 Reductive_amination C47320 "PWXDIHDWBIALIW-UHFFFAOYSA-N"

 Success  registered route 125!

401 0 0 Amidation C67457 "FUQCTTAKZLEMGE-UHFFFAOYSA-N"

 Success  registered route 126!

402 0 0 Amidation C46417 "MXEULFHAOAPIGP-UHFFFAOYSA-N"

 Success  registered route 127!

403 0 0 Amidation C46917 "ZLOLAODFQAPVFD-UHFFFAOYSA-N"

 Success  registered route 128!

404 0 0 Amidation C46631 "ZSCBHMTXZYVXEQ-UHFFFAOYSA-N"

 Success  registered route 129!

405 0 0 Petasis-borono_Mannich_reaction C50844 "KBLKPVYLXZHJGK-UHFFFAOYSA-N"

reactants =
[283111, 283871, 283872]

product = C50844 "KBLKPVYLXZHJGK-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Petasis-borono_Mannich_reaction!

405 1 0 Reductive_amination C50844 "KBLKPVYLXZHJGK-UHFFFAOYSA-N"

 Success  registered route 130!

406 0 0 Reductive_amination C68883 "DVJLCXBUKZNXHF-UHFFFAOYSA-N"

 Success  registered route 131!

407 0 0 Amidation C124499 "YAGIQJGUZXILLT-UHFFFAOYSA-N"

 Success  registered route 132!

408 0 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C47965 "JCRRANDBLAFJJV-UHFFFAOYSA-N"

 Success  registered route 133!

409 0 0 Amidation C96564 "DANVHOXOMCKSFM-UHFFFAOYSA-N"

 Success  registered route 134!

410 0 0 Amidation C50577 "WQPLYSTUHBUNOX-UHFFFAOYSA-N"

 Success  registered route 135!

411 0 0 Minisci_reaction_with_carboxylic_acid_(intermolecular) C51842 "CVBHTHVPQGKGJL-UHFFFAOYSA-N"

reactants =
[283881, 283882]

product = C51842 "CVBHTHVPQGKGJL-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Minisci_reaction_with_carboxylic_acid_(intermolecular)!

411 1 0 Sp3-sp2_Suzuki_coupling C51842 "CVBHTHVPQGKGJL-UHFFFAOYSA-N"

411 1 1 Ethenyl_to_formyl C283884 "VBFATZIKZUMLMJ-UHFFFAOYSA-N"

reactants =
[283885]

product = C283884 "VBFATZIKZUMLMJ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Ethenyl_to_formyl!

411 2 0 Acetal_deprotection C51842 "CVBHTHVPQGKGJL-UHFFFAOYSA-N"

reactants =
[283886]

product = C51842 "CVBHTHVPQGKGJL-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Acetal_deprotection!

411 3 0 TEMPO_oxidation C51842 "CVBHTHVPQGKGJL-UHFFFAOYSA-N"

reactants =
[283887]

product = C51842 "CVBHTHVPQGKGJL-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: TEMPO_oxidation!

411 4 0 Acetal_deprotection C51842 "CVBHTHVPQGKGJL-UHFFFAOYSA-N"

reactants =
[283888]

product = C51842 "CVBHTHVPQGKGJL-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Acetal_deprotection!

412 0 0 Reductive_amination C72837 "LHWDWDRIRYSRET-UHFFFAOYSA-N"

 Success  registered route 136!

413 0 0 N-nucleophilic_aromatic_substitution C59001 "FYTAAIVGKFAKKH-UHFFFAOYSA-N"

 Success  registered route 137!

414 0 0 Amidation C69067 "IOHXAAWNYVLFEF-UHFFFAOYSA-N"

 Success  registered route 138!

415 0 0 Amidation C135020 "HFDOTTQMGPTQDU-UHFFFAOYSA-N"

 Success  registered route 139!

416 0 0 Amidation C60938 "IAFIUIBPUCFPHK-UHFFFAOYSA-N"

 Success  registered route 140!

417 0 0 Formation_of_urea_from_two_amines C53746 "UKXGLWDFUDFURM-UHFFFAOYSA-N"

 Success  registered route 141!

418 0 0 Amidation C46989 "GUZPTPUPXMQGEW-UHFFFAOYSA-N"

 Success  registered route 142!

419 0 0 Amidation C77581 "QMWIEGHYOIRDQB-UHFFFAOYSA-N"

 Success  registered route 143!

420 0 0 Amidation C50934 "QHJYNEFJLIJZEI-UHFFFAOYSA-N"

 Success  registered route 144!

421 0 0 Amidation C134972 "LXFPHGKSVKIPAM-UHFFFAOYSA-N"

 Success  registered route 145!

422 0 0 Amidation C46563 "QTXYAPLSYSHZLH-UHFFFAOYSA-N"

 Success  registered route 146!

423 0 0 Amidation C45675 "UQXXRJNOVZBMSS-UHFFFAOYSA-N"

 Success  registered route 147!

424 0 0 Sp3-sp2_Suzuki_coupling C2648 "ISGNTNSLKCLYPY-UHFFFAOYSA-N"

 Success  registered route 148!

425 0 0 Amidation C45999 "OLVAHZCAPPDKML-UHFFFAOYSA-N"

 Success  registered route 149!

426 0 0 Amidation C46630 "BWJOVYDSIAZYNE-UHFFFAOYSA-N"

 Success  registered route 150!

427 0 0 Amidation C49327 "BJSRYGJAQHXCPG-UHFFFAOYSA-N"

 Success  registered route 151!

428 0 0 Amidation C67150 "FWAPTJLEEQMNPP-UHFFFAOYSA-N"

 Success  registered route 152!

429 0 0 Formation_of_urea_from_two_amines C63643 "LAVJEXPQSPEZFW-UHFFFAOYSA-N"

 Success  registered route 153!

430 0 0 Formation_of_urea_from_two_amines C49166 "QCQBHQXHEXHOGW-UHFFFAOYSA-N"

 Success  registered route 154!

431 0 0 Formation_of_urea_from_two_amines C65117 "WWDQZLGXDWUCRA-UHFFFAOYSA-N"

 Success  registered route 155!

432 0 0 Amidation C46587 "XILXUAMRBXUOIG-UHFFFAOYSA-N"

 Success  registered route 156!

433 0 0 Amidation C13655 "CUEVYSRYKCNYRY-UHFFFAOYSA-N"

 Success  registered route 157!

434 0 0 Amidation C56901 "KULRAFWNQJXNOH-UHFFFAOYSA-N"

 Success  registered route 158!

435 0 0 N-nucleophilic_aromatic_substitution C51495 "GFDFFRLXIZNDDL-UHFFFAOYSA-N"

 Success  registered route 159!

436 0 0 Amidation C102839 "XZIKUBYEVMCBKL-UHFFFAOYSA-N"

 Success  registered route 160!

437 0 0 Amidation C57140 "ZUHBPFRFPPEFBP-UHFFFAOYSA-N"

 Success  registered route 161!

438 0 0 Amidation C40538 "NPOXOZWYVHTEHK-UHFFFAOYSA-N"

 Success  registered route 162!

439 0 0 Amidation C50865 "FSKMWAXPTGYBAB-UHFFFAOYSA-N"

 Success  registered route 163!

440 0 0 Ugi_reaction_split C8079 "BGYVPCNSURXTSF-UHFFFAOYSA-N"

reactants =
[283156, 283928, 283929]

product = C8079 "BGYVPCNSURXTSF-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Ugi_reaction_split!

440 1 0 Ester_amidation C8079 "BGYVPCNSURXTSF-UHFFFAOYSA-N"

 Success  registered route 164!

441 0 0 Formation_of_sulfonamide_from_halide_-_Shavnya_reaction C51268 "IYQGGEDPMPIKFJ-UHFFFAOYSA-N"

reactants =
[283758, 283932]

product = C51268 "IYQGGEDPMPIKFJ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Formation_of_sulfonamide_from_halide_-_Shavnya_reaction!

441 1 0 Formation_of_sulfonamide_from_halide_-_Shavnya_reaction C51268 "IYQGGEDPMPIKFJ-UHFFFAOYSA-N"

reactants =
[283759, 283932]

product = C51268 "IYQGGEDPMPIKFJ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Formation_of_sulfonamide_from_halide_-_Shavnya_reaction!

441 2 0 Formation_of_sulfonamide_from_halide_-_Shavnya_reaction C51268 "IYQGGEDPMPIKFJ-UHFFFAOYSA-N"

reactants =
[283761, 283932]

product = C51268 "IYQGGEDPMPIKFJ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Formation_of_sulfonamide_from_halide_-_Shavnya_reaction!

441 3 0 N-Boc_deprotection C51268 "IYQGGEDPMPIKFJ-UHFFFAOYSA-N"

 Success  registered route 165!

442 0 0 N-nucleophilic_aromatic_substitution C48106 "NVVHARBSTPILPF-UHFFFAOYSA-N"

 Success  registered route 166!

443 0 0 Ugi_reaction C98884 "GANHUCHPQYNYPW-UHFFFAOYSA-N"

reactants =
[283936, 283937, 283938, 283939]

product = C98884 "GANHUCHPQYNYPW-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Ugi_reaction!

443 1 0 Alpha_alkylation_of_ester/amide C98884 "GANHUCHPQYNYPW-UHFFFAOYSA-N"

reactants =
[98897, 283127]

product = C98884 "GANHUCHPQYNYPW-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ester/amide!

443 2 0 Alpha_alkylation_of_ester/amide C98884 "GANHUCHPQYNYPW-UHFFFAOYSA-N"

reactants =
[98897, 283280]

product = C98884 "GANHUCHPQYNYPW-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ester/amide!

443 3 0 Alpha_alkylation_of_ester/amide C98884 "GANHUCHPQYNYPW-UHFFFAOYSA-N"

reactants =
[98897, 283128]

product = C98884 "GANHUCHPQYNYPW-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ester/amide!

443 4 0 Corey-House_synthesis_(intermolecular) C98884 "GANHUCHPQYNYPW-UHFFFAOYSA-N"

reactants =
[283940, 283941]

product = C98884 "GANHUCHPQYNYPW-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Corey-House_synthesis_(intermolecular)!

444 0 0 Amidation C53866 "LZSDVVWDNGTYCM-UHFFFAOYSA-N"

 Success  registered route 167!

445 0 0 Amidation C48513 "REJJTMAGDYDVGV-UHFFFAOYSA-N"

 Success  registered route 168!

446 0 0 Amidation C60642 "APTDDJHCLKZSQW-UHFFFAOYSA-N"

 Success  registered route 169!

447 0 0 Amidation C67126 "VBOWZCAKGFDBNA-UHFFFAOYSA-N"

 Success  registered route 170!

448 0 0 Amidation C28111 "XCWVUVAVUJWFCW-UHFFFAOYSA-N"

 Success  registered route 171!

449 0 0 Amidation C97354 "XFJSHQDMGLUATN-UHFFFAOYSA-N"

 Success  registered route 172!

450 0 0 Amidation C49991 "XMBXZMQOVGUTTG-UHFFFAOYSA-N"

 Success  registered route 173!

451 0 0 Amidation C48546 "QNLCPYNLKHRGGT-UHFFFAOYSA-N"

 Success  registered route 174!

452 0 0 Amidation C46492 "DPROWOJPCAHSLR-UHFFFAOYSA-N"

 Success  registered route 175!

453 0 0 Formation_of_urea_from_two_amines C46960 "HZQGVMFRCXKOBL-UHFFFAOYSA-N"

 Success  registered route 176!

454 0 0 Formation_of_urea_from_two_amines C48055 "NBCOLWIEDFDBPP-UHFFFAOYSA-N"

 Success  registered route 177!

455 0 0 Formation_of_urea_from_two_amines C48630 "ATBDAIGFBNCITP-UHFFFAOYSA-N"

 Success  registered route 178!

456 0 0 Amidation C41168 "RBXTZVLYSUIEGL-UHFFFAOYSA-N"

 Success  registered route 179!

457 0 0 Amidation C48056 "SXJFQBSZDASCMN-UHFFFAOYSA-N"

 Success  registered route 180!

458 0 0 Amidation C119620 "VYESCFQDWYETRW-UHFFFAOYSA-N"

 Success  registered route 181!

459 0 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C119723 "BUFNXCVHZNVGON-UHFFFAOYSA-N"

 Success  registered route 182!

460 0 0 Isocyanate_to_urea C66135 "HVAHNKDDJIROCW-UHFFFAOYSA-N"

reactants =
[283968, 283969]

product = C66135 "HVAHNKDDJIROCW-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Isocyanate_to_urea!

460 1 0 Formation_of_urea_from_two_amines C66135 "HVAHNKDDJIROCW-UHFFFAOYSA-N"

 Success  registered route 183!

461 0 0 Pinner_reaction_(carboxylate_ester) C120944 "TVIVKSZHVBUWMY-UHFFFAOYSA-N"

reactants =
[120956, 283304]

product = C120944 "TVIVKSZHVBUWMY-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Pinner_reaction_(carboxylate_ester)!

461 1 0 Alpha_alkylation_of_ester/amide C120944 "TVIVKSZHVBUWMY-UHFFFAOYSA-N"

reactants =
[283971]

product = C120944 "TVIVKSZHVBUWMY-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ester/amide!

461 2 0 Alpha_alkylation_of_ester/amide C120944 "TVIVKSZHVBUWMY-UHFFFAOYSA-N"

reactants =
[283972]

product = C120944 "TVIVKSZHVBUWMY-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ester/amide!

461 3 0 Alpha_alkylation_of_ester/amide C120944 "TVIVKSZHVBUWMY-UHFFFAOYSA-N"

reactants =
[283972]

product = C120944 "TVIVKSZHVBUWMY-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ester/amide!

461 4 0 Imine_formation C120944 "TVIVKSZHVBUWMY-UHFFFAOYSA-N"

reactants =
[283973]

product = C120944 "TVIVKSZHVBUWMY-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Imine_formation!

462 0 0 Ester_amidation C64811 "CFGXRPXLHNPYEB-UHFFFAOYSA-N"

462 1 0 Buchwald-Hartwig_amidation_with_amide-like_nucleophile C64811 "CFGXRPXLHNPYEB-UHFFFAOYSA-N"

 Success  registered route 184!

463 0 0 Petasis-borono_Mannich_reaction C52416 "CTFJRCJMDOHUDJ-UHFFFAOYSA-N"

reactants =
[7678, 283978, 283979]

product = C52416 "CTFJRCJMDOHUDJ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Petasis-borono_Mannich_reaction!

463 1 0 Formation_of_sulfonamide_from_halide_-_Shavnya_reaction C52416 "CTFJRCJMDOHUDJ-UHFFFAOYSA-N"

reactants =
[283980, 283981]

product = C52416 "CTFJRCJMDOHUDJ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Formation_of_sulfonamide_from_halide_-_Shavnya_reaction!

463 2 0 Formation_of_sulfonamide_from_halide_-_Shavnya_reaction C52416 "CTFJRCJMDOHUDJ-UHFFFAOYSA-N"

reactants =
[283980, 283982]

product = C52416 "CTFJRCJMDOHUDJ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Formation_of_sulfonamide_from_halide_-_Shavnya_reaction!

463 3 0 Formation_of_sulfonamide_from_halide_-_Shavnya_reaction C52416 "CTFJRCJMDOHUDJ-UHFFFAOYSA-N"

reactants =
[283980, 283983]

product = C52416 "CTFJRCJMDOHUDJ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Formation_of_sulfonamide_from_halide_-_Shavnya_reaction!

463 4 0 Sulfonamide_Schotten-Baumann_with_amine_(intermolecular) C52416 "CTFJRCJMDOHUDJ-UHFFFAOYSA-N"

reactants =
[283980, 283984]

product = C52416 "CTFJRCJMDOHUDJ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sulfonamide_Schotten-Baumann_with_amine_(intermolecular)!

464 0 0 Amine_alkylation C52375 "PBWKBAOPCODYPW-UHFFFAOYSA-N"

reactants =
[5169, 283985]

product = C52375 "PBWKBAOPCODYPW-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

464 1 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C52375 "PBWKBAOPCODYPW-UHFFFAOYSA-N"

 Success  registered route 185!

465 0 0 Amidation C104894 "RBNSWXUVCCJWGP-UHFFFAOYSA-N"

 Success  registered route 186!

466 0 0 Amidation C53750 "UDHNRVXHVXPDPQ-UHFFFAOYSA-N"

 Success  registered route 187!

467 0 0 Formation_of_sulfonamide_from_halide_-_Shavnya_reaction C52408 "QGEQCOIPUBEYKU-UHFFFAOYSA-N"

reactants =
[283990, 283991]

product = C52408 "QGEQCOIPUBEYKU-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Formation_of_sulfonamide_from_halide_-_Shavnya_reaction!

467 1 0 Buchwald-Hartwig_amidation_with_amide-like_nucleophile C52408 "QGEQCOIPUBEYKU-UHFFFAOYSA-N"

 Success  registered route 188!

468 0 0 Iodo_N-arylation C53625 "MRFSLWKYICIDAF-UHFFFAOYSA-N"

reactants =
[283993, 283994]

product = C53625 "MRFSLWKYICIDAF-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Iodo_N-arylation!

468 1 0 Formation_of_urea_from_two_amines C53625 "MRFSLWKYICIDAF-UHFFFAOYSA-N"

 Success  registered route 189!

469 0 0 Amidation C3809 "RPRHXEYBWVZIEC-UHFFFAOYSA-N"

 Success  registered route 190!

470 0 0 Amidation C48539 "CKCILQQJPFHCBG-UHFFFAOYSA-N"

 Success  registered route 191!

471 0 0 Amine_alkylation C51256 "DRJGGQZLWYEHNT-UHFFFAOYSA-N"

reactants =
[283810, 283998]

product = C51256 "DRJGGQZLWYEHNT-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

471 1 0 Amine_alkylation C51256 "DRJGGQZLWYEHNT-UHFFFAOYSA-N"

reactants =
[283998, 283999]

product = C51256 "DRJGGQZLWYEHNT-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

471 2 0 Amine_alkylation C51256 "DRJGGQZLWYEHNT-UHFFFAOYSA-N"

reactants =
[283998, 284000]

product = C51256 "DRJGGQZLWYEHNT-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

471 3 0 N-Boc_deprotection C51256 "DRJGGQZLWYEHNT-UHFFFAOYSA-N"

 Success  registered route 192!

472 0 0 Steglich_esterification C104497 "GNAHZGVSELLNGY-UHFFFAOYSA-N"

 Success  registered route 193!

473 0 0 Steglich_esterification C47021 "XBCUCSHTTYKLFQ-UHFFFAOYSA-N"

 Success  registered route 194!

474 0 0 Amidation C48652 "GOZNAOOIESXJOY-UHFFFAOYSA-N"

 Success  registered route 195!

475 0 0 Amidation C49171 "KQQACZGRTAQEIS-UHFFFAOYSA-N"

 Success  registered route 196!

476 0 0 Amidation C59004 "KUBMOMKAUGJXEF-UHFFFAOYSA-N"

 Success  registered route 197!

477 0 0 Amidation C7211 "MZJBBXTUYNVWJM-UHFFFAOYSA-N"

 Success  registered route 198!

478 0 0 N-nucleophilic_aromatic_substitution C27143 "HMQRCRGWWKHSOQ-UHFFFAOYSA-N"

 Success  registered route 199!

479 0 0 Amidation C122137 "CDHYUFIFKQHMBX-UHFFFAOYSA-N"

 Success  registered route 200!

480 0 0 Amidation C75326 "DXYSIYGLUVEQHU-UHFFFAOYSA-N"

 Success  registered route 201!

481 0 0 Amidation C74188 "LPMIQRKPJGOMRG-UHFFFAOYSA-N"

 Success  registered route 202!

482 0 0 Nucleophilic_substitution_with_thiol C55819 "VHVSAXROEBTQDV-UHFFFAOYSA-N"

reactants =
[284020, 284021]

product = C55819 "VHVSAXROEBTQDV-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Nucleophilic_substitution_with_thiol!

482 1 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C55819 "VHVSAXROEBTQDV-UHFFFAOYSA-N"

 Success  registered route 203!

483 0 0 Amidation C65008 "HKLVJOPELRROKJ-UHFFFAOYSA-N"

 Success  registered route 204!

484 0 0 Amidation C14132 "YPDKDGPFUNQBCH-UHFFFAOYSA-N"

 Success  registered route 205!

485 0 0 Formation_of_urea_from_two_amines C106545 "XFLRGLNKSUBAIU-UHFFFAOYSA-N"

 Success  registered route 206!

486 0 0 Amidation C50569 "RILULXWKHGGBSE-UHFFFAOYSA-N"

 Success  registered route 207!

487 0 0 Amidation C124015 "XIOYKRXGPYNPFZ-UHFFFAOYSA-N"

 Success  registered route 208!

488 0 0 Reductive_amination C42918 "LTOUESXDKSJFOU-UHFFFAOYSA-N"

 Success  registered route 209!

489 0 0 Amidation C49748 "YZQNRVOHGUHPKI-UHFFFAOYSA-N"

 Success  registered route 210!

490 0 0 Formation_of_urea_from_two_amines C52583 "DLHJBIDRLSJSTJ-UHFFFAOYSA-N"

 Success  registered route 211!

491 0 0 Amine_alkylation C58943 "RVENREFGGYUNIA-UHFFFAOYSA-N"

reactants =
[284035, 284036]

product = C58943 "RVENREFGGYUNIA-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

491 1 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C58943 "RVENREFGGYUNIA-UHFFFAOYSA-N"

 Success  registered route 212!

492 0 0 Amine_alkylation C46025 "BVLLTLFJWFLOHJ-UHFFFAOYSA-N"

reactants =
[284039, 284040]

product = C46025 "BVLLTLFJWFLOHJ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

492 1 0 N-Ac_deprotection C46025 "BVLLTLFJWFLOHJ-UHFFFAOYSA-N"

reactants =
[284041]

product = C46025 "BVLLTLFJWFLOHJ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: N-Ac_deprotection!

492 2 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C46025 "BVLLTLFJWFLOHJ-UHFFFAOYSA-N"

492 3 0 N-Ac_deprotection C46025 "BVLLTLFJWFLOHJ-UHFFFAOYSA-N"

reactants =
[284041]

product = C46025 "BVLLTLFJWFLOHJ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: N-Ac_deprotection!

492 4 0 Amine_alkylation C46025 "BVLLTLFJWFLOHJ-UHFFFAOYSA-N"

reactants =
[31939, 284040]

product = C46025 "BVLLTLFJWFLOHJ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

493 0 0 Amidation C55754 "GMCQQOLNFQNWLY-UHFFFAOYSA-N"

 Success  registered route 213!

494 0 0 Amine_alkylation C56319 "HWMWQVREGFTJLC-UHFFFAOYSA-N"

reactants =
[284045, 284046]

product = C56319 "HWMWQVREGFTJLC-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

494 1 0 N-nucleophilic_aromatic_substitution C56319 "HWMWQVREGFTJLC-UHFFFAOYSA-N"

 Success  registered route 214!

495 0 0 Amidation C49767 "MDKJRJCQKQXIAA-UHFFFAOYSA-N"

 Success  registered route 215!

496 0 0 Amidation C54984 "IYBHUXYKLJVDAB-UHFFFAOYSA-N"

 Success  registered route 216!

497 0 0 Formation_of_urea_from_two_amines C47045 "YCRGSBIGVVKPPN-UHFFFAOYSA-N"

 Success  registered route 217!

498 0 0 Amidation C50555 "GTAWTVGQTNAEFZ-UHFFFAOYSA-N"

 Success  registered route 218!

499 0 0 Amidation C57585 "LHYZZOLVXFMPSN-UHFFFAOYSA-N"

 Success  registered route 219!

500 0 0 Amidation C124666 "YPQHHFKDRTWIRH-UHFFFAOYSA-N"

 Success  registered route 220!

501 0 0 Amidation C45922 "SPNZKICKJJLOLD-UHFFFAOYSA-N"

 Success  registered route 221!

502 0 0 Formation_of_urea_from_two_amines C124674 "ARLQJSHPRHVDLE-UHFFFAOYSA-N"

 Success  registered route 222!

503 0 0 Amidation C124752 "YPSWQHNOQUDWBB-UHFFFAOYSA-N"

 Success  registered route 223!

504 0 0 Formation_of_urea_from_two_amines C46519 "PCOYOLXCWOQMAP-UHFFFAOYSA-N"

 Success  registered route 224!

505 0 0 Formation_of_urea_from_two_amines C46525 "KACSHWFKVMPBNN-UHFFFAOYSA-N"

 Success  registered route 225!

506 0 0 Ester_amidation C53709 "AEYMWTWOISXUPC-UHFFFAOYSA-N"

 Success  registered route 226!

507 0 0 Amidation C125044 "GXFRUHCYWOLZOD-UHFFFAOYSA-N"

 Success  registered route 227!

508 0 0 Amidation C39918 "FLOGMMPAFYOKFI-UHFFFAOYSA-N"

 Success  registered route 228!

509 0 0 Amine_alkylation C56328 "DWFKNXQXPRRFIK-UHFFFAOYSA-N"

reactants =
[284071, 284072]

product = C56328 "DWFKNXQXPRRFIK-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

509 1 0 Chan-Lam_coupling_(amination) C56328 "DWFKNXQXPRRFIK-UHFFFAOYSA-N"

reactants =
[284047, 284073]

product = C56328 "DWFKNXQXPRRFIK-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Chan-Lam_coupling_(amination)!

509 2 0 N-nucleophilic_aromatic_substitution C56328 "DWFKNXQXPRRFIK-UHFFFAOYSA-N"

 Success  registered route 229!

510 0 0 Nucleophilic_substitution_with_thiol C45746 "INIOVHDPBHGSSA-UHFFFAOYSA-N"

reactants =
[284075, 284076]

product = C45746 "INIOVHDPBHGSSA-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Nucleophilic_substitution_with_thiol!

510 1 0 Nucleophilic_substitution_with_thioamide C45746 "INIOVHDPBHGSSA-UHFFFAOYSA-N"

 Warning  SMILES changed during compound registration: O=c1c2ccccc2[nH]c(=S)n1-c1ccccc1 -->
O=c1c2ccccc2nc(S)n1-c1ccccc1!

reactants =
[284075, 284077]

product = C45746 "INIOVHDPBHGSSA-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Nucleophilic_substitution_with_thioamide!

510 2 0 Ester_amidation C45746 "INIOVHDPBHGSSA-UHFFFAOYSA-N"

510 3 0 Nucleophilic_substitution_with_thiol C45746 "INIOVHDPBHGSSA-UHFFFAOYSA-N"

reactants =
[284075, 284077]

product = C45746 "INIOVHDPBHGSSA-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Nucleophilic_substitution_with_thiol!

510 4 0 Nucleophilic_substitution_with_thioamide C45746 "INIOVHDPBHGSSA-UHFFFAOYSA-N"

 Warning  SMILES changed during compound registration: O=c1c2ccccc2[nH]c(=S)n1-c1ccccc1 -->
O=c1c2ccccc2nc(S)n1-c1ccccc1!

reactants =
[284075, 284076]

product = C45746 "INIOVHDPBHGSSA-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Nucleophilic_substitution_with_thioamide!

511 0 0 Formation_of_sulfonamide_from_halide_-_Shavnya_reaction C52406 "SPHUOMUWTFJILN-UHFFFAOYSA-N"

reactants =
[283990, 284079]

product = C52406 "SPHUOMUWTFJILN-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Formation_of_sulfonamide_from_halide_-_Shavnya_reaction!

511 1 0 Buchwald-Hartwig_amidation_with_amide-like_nucleophile C52406 "SPHUOMUWTFJILN-UHFFFAOYSA-N"

 Success  registered route 230!

512 0 0 Nucleophilic_substitution_with_thiol C45737 "BYVLLCRZBAXVSG-UHFFFAOYSA-N"

reactants =
[284077, 284081]

product = C45737 "BYVLLCRZBAXVSG-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Nucleophilic_substitution_with_thiol!

512 1 0 Nucleophilic_substitution_with_thioamide C45737 "BYVLLCRZBAXVSG-UHFFFAOYSA-N"

 Warning  SMILES changed during compound registration: CN(C)c1n[nH]c(=S)s1 --> CN(C)c1nnc(S)s1!

reactants =
[284076, 284081]

product = C45737 "BYVLLCRZBAXVSG-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Nucleophilic_substitution_with_thioamide!

512 2 0 Ester_amidation C45737 "BYVLLCRZBAXVSG-UHFFFAOYSA-N"

 Success  registered route 231!

513 0 0 Chan-Lam_coupling_(amination) C63895 "WJNGKPOBVKGESA-UHFFFAOYSA-N"

reactants =
[283919, 284083]

product = C63895 "WJNGKPOBVKGESA-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Chan-Lam_coupling_(amination)!

513 1 0 Amine_alkylation C63895 "WJNGKPOBVKGESA-UHFFFAOYSA-N"

reactants =
[284084, 284085]

product = C63895 "WJNGKPOBVKGESA-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

513 2 0 N-nucleophilic_aromatic_substitution C63895 "WJNGKPOBVKGESA-UHFFFAOYSA-N"

 Success  registered route 232!

514 0 0 Isocyanate_to_urea C49222 "YTMNIWJWKYPQRC-UHFFFAOYSA-N"

reactants =
[284087, 284088]

product = C49222 "YTMNIWJWKYPQRC-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Isocyanate_to_urea!

514 1 0 Formation_of_urea_from_two_amines C49222 "YTMNIWJWKYPQRC-UHFFFAOYSA-N"

 Success  registered route 233!

515 0 0 Amidation C124652 "HKXZWNGJYYWBSS-UHFFFAOYSA-N"

 Success  registered route 234!

516 0 0 N-Boc_deprotection C2619 "IKNFMHZKPYNCLN-UHFFFAOYSA-N"

 Success  registered route 235!

517 0 0 Amine_alkylation C46024 "GCNBWOGZRKAZBP-UHFFFAOYSA-N"

reactants =
[284039, 284093]

product = C46024 "GCNBWOGZRKAZBP-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

517 1 0 Ethenyl_to_formyl C46024 "GCNBWOGZRKAZBP-UHFFFAOYSA-N"

reactants =
[284094]

product = C46024 "GCNBWOGZRKAZBP-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Ethenyl_to_formyl!

517 2 0 N-nucleophilic_aromatic_substitution C46024 "GCNBWOGZRKAZBP-UHFFFAOYSA-N"

517 3 0 N-Ac_deprotection C46024 "GCNBWOGZRKAZBP-UHFFFAOYSA-N"

reactants =
[284096]

product = C46024 "GCNBWOGZRKAZBP-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: N-Ac_deprotection!

517 4 0 Sp3-sp2_Macmillan_coupling_with_chloride_(intermolecular) C46024 "GCNBWOGZRKAZBP-UHFFFAOYSA-N"

reactants =
[284097]

product = C46024 "GCNBWOGZRKAZBP-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sp3-sp2_Macmillan_coupling_with_chloride_(intermolecular)!

518 0 0 Amidation C49904 "GEQKRUDQJJRSJX-UHFFFAOYSA-N"

 Success  registered route 236!

519 0 0 Amine_alkylation C65365 "KEVJLIOFDCEABV-UHFFFAOYSA-N"

reactants =
[284098, 284099]

product = C65365 "KEVJLIOFDCEABV-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

519 1 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C65365 "KEVJLIOFDCEABV-UHFFFAOYSA-N"

 Success  registered route 237!

520 0 0 Amidation C47091 "FBFBYAKCUCMEEP-UHFFFAOYSA-N"

 Success  registered route 238!

521 0 0 Amidation C16352 "OUQAMUZFPAKLSU-UHFFFAOYSA-N"

 Success  registered route 239!

522 0 0 Amine_alkylation C46353 "RUAMWEYLOLJYGA-UHFFFAOYSA-N"

reactants =
[283761, 284104]

product = C46353 "RUAMWEYLOLJYGA-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

522 1 0 Amine_alkylation C46353 "RUAMWEYLOLJYGA-UHFFFAOYSA-N"

reactants =
[283756, 284105]

product = C46353 "RUAMWEYLOLJYGA-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

522 2 0 Amine_alkylation C46353 "RUAMWEYLOLJYGA-UHFFFAOYSA-N"

reactants =
[283760, 284104]

product = C46353 "RUAMWEYLOLJYGA-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

522 3 0 Reductive_amination C46353 "RUAMWEYLOLJYGA-UHFFFAOYSA-N"

 Success  registered route 240!

523 0 0 Amidation C48069 "NZLKTHSNCGTXSD-UHFFFAOYSA-N"

 Success  registered route 241!

524 0 0 Amidation C54393 "RQFUKMGDFNPBCK-UHFFFAOYSA-N"

 Success  registered route 242!

525 0 0 Amidation C62954 "AKDZJBVQXJPRAV-UHFFFAOYSA-N"

 Success  registered route 243!

526 0 0 Amidation C62780 "ACNOULRBXOAPRM-UHFFFAOYSA-N"

 Success  registered route 244!

527 0 0 Ester_amidation C47626 "TVPOKXROJNSOOF-UHFFFAOYSA-N"

 Success  registered route 245!

528 0 0 Sulfonamide_Schotten-Baumann_with_amine_(intermolecular) C60696 "PBRDYGOIOPNLNB-UHFFFAOYSA-N"

reactants =
[284115, 284116]

product = C60696 "PBRDYGOIOPNLNB-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sulfonamide_Schotten-Baumann_with_amine_(intermolecular)!

528 1 0 Formation_of_sulfonamide_from_halide_-_Shavnya_reaction C60696 "PBRDYGOIOPNLNB-UHFFFAOYSA-N"

reactants =
[284116, 284117]

product = C60696 "PBRDYGOIOPNLNB-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Formation_of_sulfonamide_from_halide_-_Shavnya_reaction!

528 2 0 Formation_of_sulfonamide_from_halide_-_Shavnya_reaction C60696 "PBRDYGOIOPNLNB-UHFFFAOYSA-N"

reactants =
[284116, 284118]

product = C60696 "PBRDYGOIOPNLNB-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Formation_of_sulfonamide_from_halide_-_Shavnya_reaction!

528 3 0 Formation_of_sulfonamide_from_halide_-_Shavnya_reaction C60696 "PBRDYGOIOPNLNB-UHFFFAOYSA-N"

reactants =
[284116, 284119]

product = C60696 "PBRDYGOIOPNLNB-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Formation_of_sulfonamide_from_halide_-_Shavnya_reaction!

528 4 0 Sulfonamide_Schotten-Baumann_with_amine_(intermolecular) C60696 "PBRDYGOIOPNLNB-UHFFFAOYSA-N"

reactants =
[284116, 284120]

product = C60696 "PBRDYGOIOPNLNB-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sulfonamide_Schotten-Baumann_with_amine_(intermolecular)!

529 0 0 Amidation C48075 "FLFOERJJQTUYPD-UHFFFAOYSA-N"

 Success  registered route 246!

530 0 0 N-nucleophilic_aromatic_substitution C53748 "NVPORXZYZSHULI-UHFFFAOYSA-N"

 Success  registered route 247!

531 0 0 Reductive_amination C54541 "HGBPIRBOCLLQLU-UHFFFAOYSA-N"

 Success  registered route 248!

532 0 0 Alpha_alkylation_of_aldehyde C50895 "KXNWFIJPGUQQKJ-UHFFFAOYSA-N"

reactants =
[284126, 284127]

product = C50895 "KXNWFIJPGUQQKJ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_aldehyde!

532 1 0 Alpha_alkylation_of_aldehyde C50895 "KXNWFIJPGUQQKJ-UHFFFAOYSA-N"

reactants =
[283280, 284128]

product = C50895 "KXNWFIJPGUQQKJ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_aldehyde!

532 2 0 Swern_oxidation C50895 "KXNWFIJPGUQQKJ-UHFFFAOYSA-N"

reactants =
[284129]

product = C50895 "KXNWFIJPGUQQKJ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Swern_oxidation!

532 3 0 Alpha_alkylation_of_aldehyde C50895 "KXNWFIJPGUQQKJ-UHFFFAOYSA-N"

reactants =
[284126, 284130]

product = C50895 "KXNWFIJPGUQQKJ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_aldehyde!

532 4 0 TEMPO_oxidation C50895 "KXNWFIJPGUQQKJ-UHFFFAOYSA-N"

reactants =
[284129]

product = C50895 "KXNWFIJPGUQQKJ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: TEMPO_oxidation!

533 0 0 Formation_of_urea_from_two_amines C69436 "YQYGMTNHNASFKA-UHFFFAOYSA-N"

 Success  registered route 249!

534 0 0 Formation_of_urea_from_two_amines C46719 "SZOSSGYASKCMRR-UHFFFAOYSA-N"

 Success  registered route 250!

535 0 0 Sp3-sp2_Suzuki_coupling C7530 "KLDGENGYOLDCCH-UHFFFAOYSA-N"

 Success  registered route 251!

536 0 0 Amidation C9170 "UQSQEAQGOCUNCL-UHFFFAOYSA-N"

 Success  registered route 252!

537 0 0 Amidation C72020 "CPYSPBMOERNONI-UHFFFAOYSA-N"

 Success  registered route 253!

538 0 0 Amidation C76437 "JGPKGUGWSKQTMA-UHFFFAOYSA-N"

 Success  registered route 254!

539 0 0 Amine_alkylation C9559 "BERWHPCSSUZEII-UHFFFAOYSA-N"

reactants =
[283595, 284139]

product = C9559 "BERWHPCSSUZEII-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

539 1 0 Alpha_alkylation_of_aldehyde C9559 "BERWHPCSSUZEII-UHFFFAOYSA-N"

reactants =
[283111, 284140]

product = C9559 "BERWHPCSSUZEII-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_aldehyde!

539 2 0 Amine_alkylation C9559 "BERWHPCSSUZEII-UHFFFAOYSA-N"

reactants =
[283597, 284139]

product = C9559 "BERWHPCSSUZEII-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

539 3 0 TEMPO_oxidation C9559 "BERWHPCSSUZEII-UHFFFAOYSA-N"

reactants =
[284141]

product = C9559 "BERWHPCSSUZEII-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: TEMPO_oxidation!

539 4 0 Amine_alkylation C9559 "BERWHPCSSUZEII-UHFFFAOYSA-N"

reactants =
[283598, 284139]

product = C9559 "BERWHPCSSUZEII-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

540 0 0 Steglich_esterification C45718 "BRPFDWXEIDBRLV-UHFFFAOYSA-N"

 Success  registered route 255!

541 0 0 Amine_alkylation C50994 "WQRDHQBSZVIGIO-UHFFFAOYSA-N"

reactants =
[3756, 284144]

product = C50994 "WQRDHQBSZVIGIO-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

541 1 0 Amine_alkylation C50994 "WQRDHQBSZVIGIO-UHFFFAOYSA-N"

reactants =
[3756, 284145]

product = C50994 "WQRDHQBSZVIGIO-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

541 2 0 Sp3-sp2_Suzuki_coupling C50994 "WQRDHQBSZVIGIO-UHFFFAOYSA-N"

 Success  registered route 256!

542 0 0 Amidation C55674 "OGJPIWQWEMAAMH-UHFFFAOYSA-N"

 Success  registered route 257!

543 0 0 Amidation C76407 "ROHRNSVGYBRSRF-UHFFFAOYSA-N"

 Success  registered route 258!

544 0 0 Amidation C59983 "XOUMUYAEIAMCIP-UHFFFAOYSA-N"

 Success  registered route 259!

545 0 0 Imidazole_C-2_alkylation C46656 "AMVABLYBMIDGRH-UHFFFAOYSA-N"

reactants =
[6296, 284151]

product = C46656 "AMVABLYBMIDGRH-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Imidazole_C-2_alkylation!

545 1 0 Amine_alkylation C46656 "AMVABLYBMIDGRH-UHFFFAOYSA-N"

reactants =
[283758, 284152]

product = C46656 "AMVABLYBMIDGRH-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

545 2 0 Imidazole_C-2_alkylation C46656 "AMVABLYBMIDGRH-UHFFFAOYSA-N"

reactants =
[6296, 284153]

product = C46656 "AMVABLYBMIDGRH-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Imidazole_C-2_alkylation!

545 3 0 Amine_alkylation C46656 "AMVABLYBMIDGRH-UHFFFAOYSA-N"

reactants =
[283761, 284152]

product = C46656 "AMVABLYBMIDGRH-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

545 4 0 Imidazole_C-2_alkylation C46656 "AMVABLYBMIDGRH-UHFFFAOYSA-N"

reactants =
[6296, 284154]

product = C46656 "AMVABLYBMIDGRH-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Imidazole_C-2_alkylation!

546 0 0 Formation_of_urea_from_two_amines C50998 "WKBRMGXSMGHJIB-UHFFFAOYSA-N"

 Success  registered route 260!

547 0 0 Amidation C78609 "VRSHMDURHCTYSQ-UHFFFAOYSA-N"

 Success  registered route 261!

548 0 0 1,2,4-Oxadiazole_synthesis_(amidoxime_+_carboxylate) C46489 "SZIVMHZNNDPTLC-UHFFFAOYSA-N"

reactants =
[284157, 284158]

product = C46489 "SZIVMHZNNDPTLC-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: 1,2,4-Oxadiazole_synthesis_(amidoxime_+_carboxylate)!

548 1 0 1,2,4-Oxadiazole_synthesis_(nitrile_+_carboxylic_acid) C46489 "SZIVMHZNNDPTLC-UHFFFAOYSA-N"

reactants =
[284157, 284159]

product = C46489 "SZIVMHZNNDPTLC-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: 1,2,4-Oxadiazole_synthesis_(nitrile_+_carboxylic_acid)!

548 2 0 Minisci_reaction_with_carboxylic_acid_(intermolecular) C46489 "SZIVMHZNNDPTLC-UHFFFAOYSA-N"

reactants =
[284160, 284161]

product = C46489 "SZIVMHZNNDPTLC-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Minisci_reaction_with_carboxylic_acid_(intermolecular)!

548 3 0 1,2,4-Oxadiazole_synthesis_(amidoxime_+_carboxylate) C46489 "SZIVMHZNNDPTLC-UHFFFAOYSA-N"

reactants =
[284158, 284162]

product = C46489 "SZIVMHZNNDPTLC-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: 1,2,4-Oxadiazole_synthesis_(amidoxime_+_carboxylate)!

548 4 0 N-Ac_deprotection C46489 "SZIVMHZNNDPTLC-UHFFFAOYSA-N"

reactants =
[284163]

product = C46489 "SZIVMHZNNDPTLC-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: N-Ac_deprotection!

549 0 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C47143 "FGSGQPZOSTVLEH-UHFFFAOYSA-N"

 Success  registered route 262!

550 0 0 Amidation C52296 "GKINGEPBNWSYJT-UHFFFAOYSA-N"

 Success  registered route 263!

551 0 0 Nucleophilic_substitution_with_thiol C45760 "YZUDVCSNWGWELH-UHFFFAOYSA-N"

reactants =
[284077, 284168]

product = C45760 "YZUDVCSNWGWELH-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Nucleophilic_substitution_with_thiol!

551 1 0 Nucleophilic_substitution_with_thiol C45760 "YZUDVCSNWGWELH-UHFFFAOYSA-N"

reactants =
[284076, 284168]

product = C45760 "YZUDVCSNWGWELH-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Nucleophilic_substitution_with_thiol!

551 2 0 Ester_amidation C45760 "YZUDVCSNWGWELH-UHFFFAOYSA-N"

 Success  registered route 264!

552 0 0 Formation_of_sulfonamide_from_halide_-_Shavnya_reaction C51171 "SBSIUJKZMODQOZ-UHFFFAOYSA-N"

reactants =
[283810, 284170]

product = C51171 "SBSIUJKZMODQOZ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Formation_of_sulfonamide_from_halide_-_Shavnya_reaction!

552 1 0 Formation_of_sulfonamide_from_halide_-_Shavnya_reaction C51171 "SBSIUJKZMODQOZ-UHFFFAOYSA-N"

reactants =
[283999, 284170]

product = C51171 "SBSIUJKZMODQOZ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Formation_of_sulfonamide_from_halide_-_Shavnya_reaction!

552 2 0 Formation_of_sulfonamide_from_halide_-_Shavnya_reaction C51171 "SBSIUJKZMODQOZ-UHFFFAOYSA-N"

reactants =
[284000, 284170]

product = C51171 "SBSIUJKZMODQOZ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Formation_of_sulfonamide_from_halide_-_Shavnya_reaction!

552 3 0 Petasis-borono_Mannich_reaction C51171 "SBSIUJKZMODQOZ-UHFFFAOYSA-N"

reactants =
[283111, 284171, 284172]

product = C51171 "SBSIUJKZMODQOZ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Petasis-borono_Mannich_reaction!

552 4 0 Minisci_reaction_with_carboxylic_acid_(intermolecular) C51171 "SBSIUJKZMODQOZ-UHFFFAOYSA-N"

reactants =
[284173, 284174]

product = C51171 "SBSIUJKZMODQOZ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Minisci_reaction_with_carboxylic_acid_(intermolecular)!

553 0 0 N-nucleophilic_aromatic_substitution C17161 "VJYRZHQTAWWYSA-UHFFFAOYSA-N"

 Success  registered route 265!

554 0 0 S-nucleophilic_aromatic_substitution C45943 "NAKUARJYTXIAKL-UHFFFAOYSA-N"

reactants =
[284014, 284175]

product = C45943 "NAKUARJYTXIAKL-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: S-nucleophilic_aromatic_substitution!

554 1 0 S-nucleophilic_aromatic_substitution C45943 "NAKUARJYTXIAKL-UHFFFAOYSA-N"

reactants =
[284175, 284176]

product = C45943 "NAKUARJYTXIAKL-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: S-nucleophilic_aromatic_substitution!

554 2 0 Buchwald-Hartwig_(thio)etherification C45943 "NAKUARJYTXIAKL-UHFFFAOYSA-N"

reactants =
[284014, 284175]

product = C45943 "NAKUARJYTXIAKL-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Buchwald-Hartwig_(thio)etherification!

554 3 0 Buchwald-Hartwig_(thio)etherification C45943 "NAKUARJYTXIAKL-UHFFFAOYSA-N"

reactants =
[284175, 284176]

product = C45943 "NAKUARJYTXIAKL-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Buchwald-Hartwig_(thio)etherification!

554 4 0 S-nucleophilic_aromatic_substitution C45943 "NAKUARJYTXIAKL-UHFFFAOYSA-N"

reactants =
[284177, 284178]

product = C45943 "NAKUARJYTXIAKL-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: S-nucleophilic_aromatic_substitution!

555 0 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C95588 "HVSNCLWSDCNDJH-UHFFFAOYSA-N"

 Success  registered route 266!

556 0 0 Amidation C65555 "YJLJMKADNGNFEP-UHFFFAOYSA-N"

 Success  registered route 267!

557 0 0 Amidation C53759 "XUNSVHLTAIMYCN-UHFFFAOYSA-N"

 Success  registered route 268!

558 0 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C47450 "MSQPPJKTFQIHMR-UHFFFAOYSA-N"

 Success  registered route 269!

559 0 0 Amidation C72495 "QFWXRMWUAHTJTN-UHFFFAOYSA-N"

 Success  registered route 270!

560 0 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C52333 "KEJHVZLIZINKME-UHFFFAOYSA-N"

 Success  registered route 271!

561 0 0 Amidation C50277 "GSWNPYWEZMISHZ-UHFFFAOYSA-N"

 Success  registered route 272!

562 0 0 Amidation C28114 "IUKQROOWIYQEAX-UHFFFAOYSA-N"

 Success  registered route 273!

563 0 0 Amidation C45749 "CFQKQNUEMBXROS-UHFFFAOYSA-N"

 Success  registered route 274!

564 0 0 Buchwald-Hartwig_amination C45909 "DMMWSHAZVFYQCP-UHFFFAOYSA-N"

 Success  registered route 275!

565 0 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C46644 "ZMLNPERFMPNMTQ-UHFFFAOYSA-N"

 Success  registered route 276!

566 0 0 Amidation C50954 "BLIHSGRIXMRDOE-UHFFFAOYSA-N"

 Success  registered route 277!

567 0 0 Amidation C55684 "XPJXWZTUMKSLEF-UHFFFAOYSA-N"

 Success  registered route 278!

568 0 0 Amidation C50179 "JRWNVUPFKXEMMQ-UHFFFAOYSA-N"

 Success  registered route 279!

569 0 0 Reductive_amination C98152 "VZPBIZGIEVBAAL-UHFFFAOYSA-N"

 Success  registered route 280!

570 0 0 Amidation C47396 "YLTDZWFXEQMEQY-UHFFFAOYSA-N"

 Success  registered route 281!

571 0 0 Amidation C50784 "OZOCKCQNPSVVFB-UHFFFAOYSA-N"

 Success  registered route 282!

572 0 0 Amidation C46779 "JJWFKWAOMFMQRZ-UHFFFAOYSA-N"

 Success  registered route 283!

573 0 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C55076 "OHXVFTFJECSKFY-UHFFFAOYSA-N"

 Success  registered route 284!

574 0 0 Amidation C16370 "ABUSFKREGHFGSP-UHFFFAOYSA-N"

 Success  registered route 285!

575 0 0 Formation_of_urea_from_two_amines C46399 "NZLDTOKBIBVWEI-UHFFFAOYSA-N"

 Success  registered route 286!

576 0 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C53771 "TWONAIHJDMPRBM-UHFFFAOYSA-N"

 Success  registered route 287!

577 0 0 Amine_alkylation C47934 "AVYIYQMLMSVDAX-UHFFFAOYSA-N"

reactants =
[283032, 284209]

product = C47934 "AVYIYQMLMSVDAX-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

577 1 0 Amine_alkylation C47934 "AVYIYQMLMSVDAX-UHFFFAOYSA-N"

reactants =
[87854, 283032]

product = C47934 "AVYIYQMLMSVDAX-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

577 2 0 Amidation C47934 "AVYIYQMLMSVDAX-UHFFFAOYSA-N"

 Success  registered route 288!

578 0 0 Amidation C81434 "NHFWFEZEXIIBII-UHFFFAOYSA-N"

 Success  registered route 289!

579 0 0 Amidation C45810 "AWLHCXVUPILPTN-UHFFFAOYSA-N"

 Success  registered route 290!

580 0 0 Steglich_esterification C35473 "PLOYGMMNBYFGSF-UHFFFAOYSA-N"

 Success  registered route 291!

581 0 0 Amidation C101781 "ASBBGKVVIBZBJN-UHFFFAOYSA-N"

 Success  registered route 292!

582 0 0 Amine_alkylation C46470 "NEWYPLQNQDROOI-UHFFFAOYSA-N"

reactants =
[283761, 284045]

product = C46470 "NEWYPLQNQDROOI-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

582 1 0 N-nucleophilic_aromatic_substitution C46470 "NEWYPLQNQDROOI-UHFFFAOYSA-N"

 Success  registered route 293!

583 0 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C47013 "FRZNABRJHVHFJE-UHFFFAOYSA-N"

 Success  registered route 294!

584 0 0 Alpha_alkylation_of_ester/amide C56915 "OTMGIRLBTFICTQ-UHFFFAOYSA-N"

reactants =
[284218, 284219]

product = C56915 "OTMGIRLBTFICTQ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ester/amide!

584 1 0 Alpha_alkylation_of_ester/amide C56915 "OTMGIRLBTFICTQ-UHFFFAOYSA-N"

reactants =
[284219, 284220]

product = C56915 "OTMGIRLBTFICTQ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ester/amide!

584 2 0 Amidation C56915 "OTMGIRLBTFICTQ-UHFFFAOYSA-N"

 Success  registered route 295!

585 0 0 Amidation C40498 "NYRUPEKHZSORRF-UHFFFAOYSA-N"

 Success  registered route 296!

586 0 0 N-nucleophilic_aromatic_substitution C35439 "BAUHVGNDLBNYPF-UHFFFAOYSA-N"

 Success  registered route 297!

587 0 0 Amidation C26549 "QEUQYOFEBBDDHZ-UHFFFAOYSA-N"

 Success  registered route 298!

588 0 0 Reductive_amination C102808 "MZJWMOJDYRPWCV-UHFFFAOYSA-N"

 Success  registered route 299!

589 0 0 Amidation C51493 "PQANNCWYAKKWKR-UHFFFAOYSA-N"

 Success  registered route 300!

590 0 0 Formation_of_urea_from_two_amines C55892 "WDXPCDIQYNQRBP-UHFFFAOYSA-N"

 Success  registered route 301!

591 0 0 Amidation C46065 "WTVLMOGGYBHAKC-UHFFFAOYSA-N"

 Success  registered route 302!

592 0 0 Sulfonamide_Schotten-Baumann_with_amine_(intermolecular) C45987 "YTXBRSZQZDSVHR-UHFFFAOYSA-N"

reactants =
[45790, 284230]

product = C45987 "YTXBRSZQZDSVHR-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sulfonamide_Schotten-Baumann_with_amine_(intermolecular)!

592 1 0 Sulfonamide_Schotten-Baumann_with_amine_(intermolecular) C45987 "YTXBRSZQZDSVHR-UHFFFAOYSA-N"

reactants =
[45790, 284231]

product = C45987 "YTXBRSZQZDSVHR-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sulfonamide_Schotten-Baumann_with_amine_(intermolecular)!

592 2 0 Formation_of_sulfonamide_from_halide_-_Shavnya_reaction C45987 "YTXBRSZQZDSVHR-UHFFFAOYSA-N"

reactants =
[284232, 284233]

product = C45987 "YTXBRSZQZDSVHR-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Formation_of_sulfonamide_from_halide_-_Shavnya_reaction!

592 3 0 Sulfonamide_Schotten-Baumann_with_amine_(intermolecular) C45987 "YTXBRSZQZDSVHR-UHFFFAOYSA-N"

reactants =
[284232, 284234]

product = C45987 "YTXBRSZQZDSVHR-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sulfonamide_Schotten-Baumann_with_amine_(intermolecular)!

592 4 0 Formation_of_sulfonamide_from_halide_-_Shavnya_reaction C45987 "YTXBRSZQZDSVHR-UHFFFAOYSA-N"

reactants =
[284232, 284235]

product = C45987 "YTXBRSZQZDSVHR-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Formation_of_sulfonamide_from_halide_-_Shavnya_reaction!

593 0 0 Amidation C51490 "MJMCOCNIQIOMAD-UHFFFAOYSA-N"

 Success  registered route 303!

594 0 0 Amidation C35612 "QUWCTZUWOPCIPH-UHFFFAOYSA-N"

 Success  registered route 304!

595 0 0 Amidation C21631 "AERCOVUKSAMYCJ-UHFFFAOYSA-N"

 Success  registered route 305!

596 0 0 Buchwald-Hartwig_amination C46544 "QFIAQCXWMHUYLP-UHFFFAOYSA-N"

 Success  registered route 306!

597 0 0 Amidation C54511 "AGNKHDPFSMAPGP-UHFFFAOYSA-N"

 Success  registered route 307!

598 0 0 Amidation C46596 "IGUBAEGLTUZHCE-UHFFFAOYSA-N"

 Success  registered route 308!

599 0 0 Amidation C99297 "UAGGKQWASMNBKS-UHFFFAOYSA-N"

 Success  registered route 309!

600 0 0 Amidation C79153 "ISLLNGYBDHENHK-UHFFFAOYSA-N"

 Success  registered route 310!

601 0 0 Formation_of_urea_from_two_amines C47020 "GXDXQSSPAOBTRI-UHFFFAOYSA-N"

 Success  registered route 311!

602 0 0 Amidation C54609 "YTDDXKFXAHOBOJ-UHFFFAOYSA-N"

 Success  registered route 312!

603 0 0 Amidation C46745 "CGTYQSSIZNKAKB-UHFFFAOYSA-N"

 Success  registered route 313!

604 0 0 Sp2-sp2_Suzuki_coupling C48173 "IHQQJGYNMPUAJX-UHFFFAOYSA-N"

 Success  registered route 314!

605 0 0 Amidation C50765 "STCJHBJZJQTPAK-UHFFFAOYSA-N"

 Success  registered route 315!

606 0 0 Amidation C45621 "FJYQDPPMQZVULE-UHFFFAOYSA-N"

 Success  registered route 316!

607 0 0 Amidation C73035 "BZZOYINXFCNSHF-UHFFFAOYSA-N"

 Success  registered route 317!

608 0 0 Sp3-sp2_Suzuki_coupling C48047 "BRBPGGIIQVBPSB-UHFFFAOYSA-N"

 Success  registered route 318!

609 0 0 Amidation C45868 "GUNFXNUZCJVVCQ-UHFFFAOYSA-N"

 Success  registered route 319!

610 0 0 Amidation C45401 "IYSNRKWEWIPQJO-UHFFFAOYSA-N"

 Success  registered route 320!

611 0 0 Alpha_alkylation_of_aldehyde C53933 "QATXJWMNVCBKJS-UHFFFAOYSA-N"

reactants =
[283127, 284261]

product = C53933 "QATXJWMNVCBKJS-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_aldehyde!

611 1 0 Ethenyl_to_formyl C53933 "QATXJWMNVCBKJS-UHFFFAOYSA-N"

reactants =
[284262]

product = C53933 "QATXJWMNVCBKJS-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Ethenyl_to_formyl!

611 2 0 Minisci_reaction_with_carboxylic_acid_(intermolecular) C53933 "QATXJWMNVCBKJS-UHFFFAOYSA-N"

reactants =
[282925, 284263]

product = C53933 "QATXJWMNVCBKJS-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Minisci_reaction_with_carboxylic_acid_(intermolecular)!

611 3 0 TEMPO_oxidation C53933 "QATXJWMNVCBKJS-UHFFFAOYSA-N"

reactants =
[284264]

product = C53933 "QATXJWMNVCBKJS-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: TEMPO_oxidation!

611 4 0 Acetal_deprotection C53933 "QATXJWMNVCBKJS-UHFFFAOYSA-N"

reactants =
[284265]

product = C53933 "QATXJWMNVCBKJS-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Acetal_deprotection!

612 0 0 Formation_of_urea_from_two_amines C71025 "GDWHZKUVFYWLOX-UHFFFAOYSA-N"

 Success  registered route 321!

613 0 0 Sp3-sp2_Suzuki_coupling C47050 "UUXRWAXHJKIKLF-UHFFFAOYSA-N"

613 1 0 Sp3-sp2_Suzuki_coupling C47050 "UUXRWAXHJKIKLF-UHFFFAOYSA-N"

613 1 1 Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide C284269 "SATHVJHHTRKTSR-UHFFFAOYSA-N"

reactants =
[284270, 284271]

product = C284269 "SATHVJHHTRKTSR-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide!

613 2 0 Sp3-sp2_Suzuki_coupling C47050 "UUXRWAXHJKIKLF-UHFFFAOYSA-N"

613 2 1 Sp3-sp2_Suzuki_coupling C284272 "TUMPQXGPWDYKPQ-UHFFFAOYSA-N"

 Success  registered route 322!

614 0 0 1,2,4-Oxadiazole_synthesis_(amidoxime_+_carboxylate) C53958 "WCIIHXGCHJLLNO-UHFFFAOYSA-N"

reactants =
[284275, 284276]

product = C53958 "WCIIHXGCHJLLNO-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: 1,2,4-Oxadiazole_synthesis_(amidoxime_+_carboxylate)!

614 1 0 1,2,4-Oxadiazole_synthesis_(nitrile_+_carboxylic_acid) C53958 "WCIIHXGCHJLLNO-UHFFFAOYSA-N"

reactants =
[284276, 284277]

product = C53958 "WCIIHXGCHJLLNO-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: 1,2,4-Oxadiazole_synthesis_(nitrile_+_carboxylic_acid)!

614 2 0 1,2,4-Oxadiazole_synthesis_(amidoxime_+_carboxylate) C53958 "WCIIHXGCHJLLNO-UHFFFAOYSA-N"

reactants =
[284275, 284278]

product = C53958 "WCIIHXGCHJLLNO-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: 1,2,4-Oxadiazole_synthesis_(amidoxime_+_carboxylate)!

614 3 0 Amidation C53958 "WCIIHXGCHJLLNO-UHFFFAOYSA-N"

 Success  registered route 323!

615 0 0 Amidation C56036 "RNMKDQJFKQUPLR-UHFFFAOYSA-N"

 Success  registered route 324!

616 0 0 Amidation C46686 "QYLPLGFXGKSQBO-UHFFFAOYSA-N"

 Success  registered route 325!

617 0 0 Amidation C48529 "ADNXPKLKFSZSFL-UHFFFAOYSA-N"

 Success  registered route 326!

618 0 0 Formation_of_urea_from_two_amines C63712 "USNXQARUIFIATO-UHFFFAOYSA-N"

 Success  registered route 327!

619 0 0 Formation_of_urea_from_two_amines C70623 "XYEZCRBOLJWWSO-UHFFFAOYSA-N"

 Success  registered route 328!

620 0 0 Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide C97238 "INEPPSBQJWJDAN-UHFFFAOYSA-N"

reactants =
[284286, 284287]

product = C97238 "INEPPSBQJWJDAN-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide!

620 1 0 Ozonolysis_(intermolecular) C97238 "INEPPSBQJWJDAN-UHFFFAOYSA-N"

reactants =
[284288]

product = C97238 "INEPPSBQJWJDAN-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Ozonolysis_(intermolecular)!

620 2 0 Ozonolysis_(intermolecular) C97238 "INEPPSBQJWJDAN-UHFFFAOYSA-N"

reactants =
[284289]

product = C97238 "INEPPSBQJWJDAN-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Ozonolysis_(intermolecular)!

620 3 0 Acetal_deprotection C97238 "INEPPSBQJWJDAN-UHFFFAOYSA-N"

reactants =
[284290]

product = C97238 "INEPPSBQJWJDAN-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Acetal_deprotection!

620 4 0 Sandmeyer_bromination C97238 "INEPPSBQJWJDAN-UHFFFAOYSA-N"

reactants =
[284291]

product = C97238 "INEPPSBQJWJDAN-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sandmeyer_bromination!

621 0 0 Formation_of_urea_from_two_amines C46913 "UDUDCRVNWVAVQA-UHFFFAOYSA-N"

 Success  registered route 329!

622 0 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C50199 "DRFSJOZQKRDYMQ-UHFFFAOYSA-N"

 Success  registered route 330!

623 0 0 Formation_of_urea_from_two_amines C46715 "DIRAOWPNSMQXKI-UHFFFAOYSA-N"

 Success  registered route 331!

624 0 0 Steglich_esterification C48752 "UKZBPLZISFOGHM-UHFFFAOYSA-N"

 Success  registered route 332!

625 0 0 Amidation C75046 "SBHQGIHIWSVJJD-UHFFFAOYSA-N"

 Success  registered route 333!

626 0 0 Amidation C75041 "CIXBAERDBPDAKY-UHFFFAOYSA-N"

 Success  registered route 334!

627 0 0 Amidation C32955 "FIQGWCSDZCNMCO-UHFFFAOYSA-N"

 Success  registered route 335!

628 0 0 Amidation C74534 "RVXODQUPALHEDR-UHFFFAOYSA-N"

 Success  registered route 336!

629 0 0 Formation_of_urea_from_two_amines C47226 "DLCSXKSRGUYCLO-UHFFFAOYSA-N"

629 1 0 Aziridine_+_amine_coupling C47226 "DLCSXKSRGUYCLO-UHFFFAOYSA-N"

reactants =
[283711, 284305]

product = C47226 "DLCSXKSRGUYCLO-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Aziridine_+_amine_coupling!

629 2 0 N-Boc_deprotection C47226 "DLCSXKSRGUYCLO-UHFFFAOYSA-N"

629 2 1 Formation_of_urea_from_two_amines C284306 "VZYKKDUGNXZWKH-UHFFFAOYSA-N"

629 3 0 Amine_alkylation C47226 "DLCSXKSRGUYCLO-UHFFFAOYSA-N"

reactants =
[283123, 284308]

product = C47226 "DLCSXKSRGUYCLO-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

629 4 0 N-Cbz_deprotection C47226 "DLCSXKSRGUYCLO-UHFFFAOYSA-N"

reactants =
[284309]

product = C47226 "DLCSXKSRGUYCLO-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: N-Cbz_deprotection!

630 0 0 Amidation C22252 "IBDCOPOSACUADV-UHFFFAOYSA-N"

 Success  registered route 337!

631 0 0 Formation_of_sulfonamide_from_halide_-_Shavnya_reaction C51172 "GBIVHNMPUDCSBY-UHFFFAOYSA-N"

reactants =
[283810, 284312]

product = C51172 "GBIVHNMPUDCSBY-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Formation_of_sulfonamide_from_halide_-_Shavnya_reaction!

631 1 0 Formation_of_sulfonamide_from_halide_-_Shavnya_reaction C51172 "GBIVHNMPUDCSBY-UHFFFAOYSA-N"

reactants =
[283999, 284312]

product = C51172 "GBIVHNMPUDCSBY-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Formation_of_sulfonamide_from_halide_-_Shavnya_reaction!

631 2 0 Formation_of_sulfonamide_from_halide_-_Shavnya_reaction C51172 "GBIVHNMPUDCSBY-UHFFFAOYSA-N"

reactants =
[284000, 284312]

product = C51172 "GBIVHNMPUDCSBY-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Formation_of_sulfonamide_from_halide_-_Shavnya_reaction!

631 3 0 N-Boc_deprotection C51172 "GBIVHNMPUDCSBY-UHFFFAOYSA-N"

631 3 1 Formation_of_sulfonamide_from_halide_-_Shavnya_reaction C284313 "ASZCSHXVUIMUGH-UHFFFAOYSA-N"

reactants =
[284312, 284314]

product = C284313 "ASZCSHXVUIMUGH-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Formation_of_sulfonamide_from_halide_-_Shavnya_reaction!

631 4 0 N-Ac_deprotection C51172 "GBIVHNMPUDCSBY-UHFFFAOYSA-N"

reactants =
[284315]

product = C51172 "GBIVHNMPUDCSBY-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: N-Ac_deprotection!

632 0 0 Minisci_reaction_with_carboxylic_acid_(intermolecular) C54009 "XTXBBFCZAMJCJV-UHFFFAOYSA-N"

reactants =
[3671, 284316]

product = C54009 "XTXBBFCZAMJCJV-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Minisci_reaction_with_carboxylic_acid_(intermolecular)!

632 1 0 Formation_of_urea_from_two_amines C54009 "XTXBBFCZAMJCJV-UHFFFAOYSA-N"

 Success  registered route 338!

633 0 0 Amidation C116664 "BESYEBIXTNPBCZ-UHFFFAOYSA-N"

 Success  registered route 339!

634 0 0 Amidation C68683 "IZLSOQIKOWDXOQ-UHFFFAOYSA-N"

 Success  registered route 340!

635 0 0 Amidation C50927 "ABTJDCJBWSBSRN-UHFFFAOYSA-N"

 Success  registered route 341!

636 0 0 Amidation C47059 "HZAWDDKMHSREJD-UHFFFAOYSA-N"

 Success  registered route 342!

637 0 0 Formation_of_sulfonamide_from_boronic_and_amine C72578 "SXFYONIWVSYCIM-UHFFFAOYSA-N"

reactants =
[283055, 284324]

product = C72578 "SXFYONIWVSYCIM-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Formation_of_sulfonamide_from_boronic_and_amine!

637 1 0 Chan-Lam_coupling_of_amides,_sulfonamides,_and_imides C72578 "SXFYONIWVSYCIM-UHFFFAOYSA-N"

reactants =
[284325, 284326]

product = C72578 "SXFYONIWVSYCIM-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Chan-Lam_coupling_of_amides,_sulfonamides,_and_imides!

637 2 0 Buchwald-Hartwig_amidation_with_amide-like_nucleophile C72578 "SXFYONIWVSYCIM-UHFFFAOYSA-N"

 Success  registered route 343!

638 0 0 Amidation C50560 "ZSWDRRMBFQDNKX-UHFFFAOYSA-N"

 Success  registered route 344!

639 0 0 Amidation C69028 "YKKKROMSHYNZCM-UHFFFAOYSA-N"

 Success  registered route 345!

640 0 0 Amidation C51887 "OCFILOCKSPCUCJ-UHFFFAOYSA-N"

 Success  registered route 346!

641 0 0 N-Boc_deprotection C3758 "JNOYHGAZDBVHEM-UHFFFAOYSA-N"

 Success  registered route 347!

642 0 0 N-nucleophilic_aromatic_substitution C119126 "ILSBGNWDUMTPAG-UHFFFAOYSA-N"

 Success  registered route 348!

643 0 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C59009 "OHLKROUFFQSMCC-UHFFFAOYSA-N"

 Success  registered route 349!

644 0 0 Amidation C99744 "GYQUKRQTKVBWNS-UHFFFAOYSA-N"

 Success  registered route 350!

645 0 0 Amidation C50959 "YMLRBUYADBIVPV-UHFFFAOYSA-N"

 Success  registered route 351!

646 0 0 Amidation C45686 "OJGYGWNQLWVYCV-UHFFFAOYSA-N"

 Success  registered route 352!

647 0 0 Alpha_alkylation_of_ester/amide C46510 "YFUCQHARYKGGDT-UHFFFAOYSA-N"

reactants =
[284342, 284343]

product = C46510 "YFUCQHARYKGGDT-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ester/amide!

647 1 0 Amidation C46510 "YFUCQHARYKGGDT-UHFFFAOYSA-N"

647 1 1 Amidation C284344 "BBSYXIZVNQIMEE-UHFFFAOYSA-N"

 Success  registered route 353!

648 0 0 Amidation C17664 "ACSYWMFGDGOESG-UHFFFAOYSA-N"

 Success  registered route 354!

649 0 0 Amidation C18489 "VFKNZSCHZMQTED-UHFFFAOYSA-N"

 Success  registered route 355!

650 0 0 Amidation C46019 "SWXAVEIWNZULFS-UHFFFAOYSA-N"

 Success  registered route 356!

651 0 0 Amidation C46081 "CMXCFLAPBZHWHG-UHFFFAOYSA-N"

 Success  registered route 357!

652 0 0 Amidation C48684 "PRAKSTQMHOCJPE-UHFFFAOYSA-N"

 Success  registered route 358!

653 0 0 Stille_coupling C49548 "USFYQCKGTJDZSY-UHFFFAOYSA-N"

reactants =
[284354, 284355]

product = C49548 "USFYQCKGTJDZSY-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Stille_coupling!

653 1 0 Amidation C49548 "USFYQCKGTJDZSY-UHFFFAOYSA-N"

 Success  registered route 359!

654 0 0 Amidation C45698 "AZXXRKXZDHOYLM-UHFFFAOYSA-N"

 Success  registered route 360!

655 0 0 Formation_of_urea_from_two_amines C48641 "HWVWLXJFARWMTE-UHFFFAOYSA-N"

 Success  registered route 361!

656 0 0 Amidation C54290 "HQGYPUCPEKYMFA-UHFFFAOYSA-N"

 Success  registered route 362!

657 0 0 Amine_alkylation C46545 "NFJAZBLUEKNGGI-UHFFFAOYSA-N"

reactants =
[284362, 284363]

product = C46545 "NFJAZBLUEKNGGI-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

657 1 0 Buchwald-Hartwig_amination C46545 "NFJAZBLUEKNGGI-UHFFFAOYSA-N"

 Success  registered route 363!

658 0 0 Ester_amidation C45947 "IIPXDYCSPRLGJU-UHFFFAOYSA-N"

 Success  registered route 364!

659 0 0 Reductive_amination C46327 "UEVJLQLOPDVOAR-UHFFFAOYSA-N"

 Success  registered route 365!

660 0 0 Amidation C97204 "FNHYNFVWJDXWDE-UHFFFAOYSA-N"

 Success  registered route 366!

661 0 0 Amidation C49818 "OLDSNDJYHCNLFD-UHFFFAOYSA-N"

 Success  registered route 367!

662 0 0 Amidation C9529 "PEDGVMFOGXYVTC-UHFFFAOYSA-N"

 Success  registered route 368!

663 0 0 Ester_amidation C59022 "BFNJPRDSFVMZDA-UHFFFAOYSA-N"

 Success  registered route 369!

664 0 0 Amine_alkylation C48646 "LKENARBUOFSVNC-UHFFFAOYSA-N"

reactants =
[284371, 284372]

product = C48646 "LKENARBUOFSVNC-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

664 1 0 Reductive_amination C48646 "LKENARBUOFSVNC-UHFFFAOYSA-N"

 Success  registered route 370!

665 0 0 Amidation C80825 "AQAKSQZHWPPYOI-UHFFFAOYSA-N"

 Success  registered route 371!

666 0 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C47453 "DIPNTWZPFZFZLY-UHFFFAOYSA-N"

 Success  registered route 372!

667 0 0 Amidation C105126 "JJKPNZIAVNEQFY-UHFFFAOYSA-N"

 Success  registered route 373!

668 0 0 Amidation C55396 "XQFDTTICYWSLGR-UHFFFAOYSA-N"

 Success  registered route 374!

669 0 0 Sulfonamide_Schotten-Baumann_with_amine_(intermolecular) C72721 "LYKXFHHASTVORN-UHFFFAOYSA-N"

reactants =
[283836, 284379]

product = C72721 "LYKXFHHASTVORN-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sulfonamide_Schotten-Baumann_with_amine_(intermolecular)!

669 1 0 Sulfonamide_Schotten-Baumann_with_amine_(intermolecular) C72721 "LYKXFHHASTVORN-UHFFFAOYSA-N"

reactants =
[283836, 284380]

product = C72721 "LYKXFHHASTVORN-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sulfonamide_Schotten-Baumann_with_amine_(intermolecular)!

669 2 0 Buchwald-Hartwig_amidation_with_amide-like_nucleophile C72721 "LYKXFHHASTVORN-UHFFFAOYSA-N"

669 3 0 Sulfonamide_Schotten-Baumann_with_amine_(intermolecular) C72721 "LYKXFHHASTVORN-UHFFFAOYSA-N"

reactants =
[283965, 284382]

product = C72721 "LYKXFHHASTVORN-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sulfonamide_Schotten-Baumann_with_amine_(intermolecular)!

669 4 0 Sulfonamide_Schotten-Baumann_with_amine_(intermolecular) C72721 "LYKXFHHASTVORN-UHFFFAOYSA-N"

reactants =
[283965, 284383]

product = C72721 "LYKXFHHASTVORN-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sulfonamide_Schotten-Baumann_with_amine_(intermolecular)!

670 0 0 Buchwald-Hartwig_amination C45903 "QGVOJAWYYQCOKY-UHFFFAOYSA-N"

 Success  registered route 375!

671 0 0 Amidation C45756 "VOCNZKAZPJNZLB-UHFFFAOYSA-N"

 Success  registered route 376!

672 0 0 Amidation C129526 "JRIXZBVWMSAORN-UHFFFAOYSA-N"

 Success  registered route 377!

673 0 0 Amidation C129593 "KRFRNBXJSXYDDU-UHFFFAOYSA-N"

 Success  registered route 378!

674 0 0 Amine_alkylation C69074 "UJUZDCBLGJJXRQ-UHFFFAOYSA-N"

reactants =
[283965, 284039]

product = C69074 "UJUZDCBLGJJXRQ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

674 1 0 Ethenyl_to_formyl C69074 "UJUZDCBLGJJXRQ-UHFFFAOYSA-N"

reactants =
[284390]

product = C69074 "UJUZDCBLGJJXRQ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Ethenyl_to_formyl!

674 2 0 Swern_oxidation C69074 "UJUZDCBLGJJXRQ-UHFFFAOYSA-N"

reactants =
[284391]

product = C69074 "UJUZDCBLGJJXRQ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Swern_oxidation!

674 3 0 N-Ac_deprotection C69074 "UJUZDCBLGJJXRQ-UHFFFAOYSA-N"

reactants =
[284392]

product = C69074 "UJUZDCBLGJJXRQ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: N-Ac_deprotection!

674 4 0 Ozonolysis_(intermolecular) C69074 "UJUZDCBLGJJXRQ-UHFFFAOYSA-N"

reactants =
[284390]

product = C69074 "UJUZDCBLGJJXRQ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Ozonolysis_(intermolecular)!

675 0 0 Buchwald-Hartwig_(thio)etherification C51875 "UZTGHTCNTUSHGZ-UHFFFAOYSA-N"

reactants =
[282914, 284393]

product = C51875 "UZTGHTCNTUSHGZ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Buchwald-Hartwig_(thio)etherification!

675 1 0 Nucleophilic_aromatic_substitution_(alcohol,_phenol,_water) C51875 "UZTGHTCNTUSHGZ-UHFFFAOYSA-N"

reactants =
[282914, 284393]

product = C51875 "UZTGHTCNTUSHGZ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Nucleophilic_aromatic_substitution_(alcohol,_phenol,_water)!

675 2 0 Acetal_deprotection C51875 "UZTGHTCNTUSHGZ-UHFFFAOYSA-N"

reactants =
[284394]

product = C51875 "UZTGHTCNTUSHGZ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Acetal_deprotection!

675 3 0 Ethenyl_to_formyl C51875 "UZTGHTCNTUSHGZ-UHFFFAOYSA-N"

reactants =
[284395]

product = C51875 "UZTGHTCNTUSHGZ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Ethenyl_to_formyl!

675 4 0 Alpha_alkylation_of_aldehyde C51875 "UZTGHTCNTUSHGZ-UHFFFAOYSA-N"

reactants =
[283127, 284396]

product = C51875 "UZTGHTCNTUSHGZ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_aldehyde!

676 0 0 Amidation C74411 "BPSGCGHAXUTQSM-UHFFFAOYSA-N"

 Success  registered route 379!

677 0 0 N-nucleophilic_aromatic_substitution C50762 "OGTRECUNLRMNFU-UHFFFAOYSA-N"

 Success  registered route 380!

678 0 0 Amidation C66538 "ZIEZQKTWDSPKJB-UHFFFAOYSA-N"

 Success  registered route 381!

679 0 0 N-nucleophilic_aromatic_substitution C50711 "BVUAKSYIXAEYKA-UHFFFAOYSA-N"

 Success  registered route 382!

680 0 0 Reductive_amination C47371 "BYIBJOZHQLWVOG-UHFFFAOYSA-N"

 Success  registered route 383!

681 0 0 Amidation C75048 "DBYAVWKCAUZJRJ-UHFFFAOYSA-N"

 Success  registered route 384!

682 0 0 Amidation C51543 "DRKHZHCOCRWYTL-UHFFFAOYSA-N"

 Warning  SMILES changed during compound registration: c1cc(C2CCNCC2)[nH]n1 --> c1cc(C2CCNCC2)n[nH]1!

 Success  registered route 385!

683 0 0 Amidation C69262 "SOJMYQQECXDIRN-UHFFFAOYSA-N"

 Success  registered route 386!

684 0 0 Amidation C87625 "FUASHUQWJFTJQN-UHFFFAOYSA-N"

 Success  registered route 387!

685 0 0 Amidation C64592 "VAGNKVBSAUXXJB-UHFFFAOYSA-N"

 Success  registered route 388!

686 0 0 1,2,4-Oxadiazole_synthesis_(nitrile_+_carboxylic_acid) C29898 "BGICKWFMKMWXKW-UHFFFAOYSA-N"

reactants =
[284410, 284411]

product = C29898 "BGICKWFMKMWXKW-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: 1,2,4-Oxadiazole_synthesis_(nitrile_+_carboxylic_acid)!

686 1 0 Minisci_reaction_with_carboxylic_acid_(intermolecular) C29898 "BGICKWFMKMWXKW-UHFFFAOYSA-N"

reactants =
[284412, 284413]

product = C29898 "BGICKWFMKMWXKW-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Minisci_reaction_with_carboxylic_acid_(intermolecular)!

686 2 0 Minisci_reaction_with_carboxylic_acid_(intermolecular) C29898 "BGICKWFMKMWXKW-UHFFFAOYSA-N"

reactants =
[284414, 284415]

product = C29898 "BGICKWFMKMWXKW-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Minisci_reaction_with_carboxylic_acid_(intermolecular)!

686 3 0 Benzylic_deprotonation-alkylation_(pyridine) C29898 "BGICKWFMKMWXKW-UHFFFAOYSA-N"

reactants =
[284416]

product = C29898 "BGICKWFMKMWXKW-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Benzylic_deprotonation-alkylation_(pyridine)!

686 4 0 1,2,4-Oxadiazole_synthesis_(amidoxime_+_carboxylate) C29898 "BGICKWFMKMWXKW-UHFFFAOYSA-N"

reactants =
[284417, 284418]

product = C29898 "BGICKWFMKMWXKW-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: 1,2,4-Oxadiazole_synthesis_(amidoxime_+_carboxylate)!

687 0 0 Amidation C107313 "RZWXIWQSDZYYOP-UHFFFAOYSA-N"

 Success  registered route 389!

688 0 0 Amine_alkylation C46497 "NHTIISPGTDJACN-UHFFFAOYSA-N"

reactants =
[283760, 283914]

product = C46497 "NHTIISPGTDJACN-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

688 1 0 Chan-Lam_coupling_(amination) C46497 "NHTIISPGTDJACN-UHFFFAOYSA-N"

reactants =
[284421, 284422]

product = C46497 "NHTIISPGTDJACN-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Chan-Lam_coupling_(amination)!

688 2 0 Amine_alkylation C46497 "NHTIISPGTDJACN-UHFFFAOYSA-N"

reactants =
[283759, 283914]

product = C46497 "NHTIISPGTDJACN-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

688 3 0 N-nucleophilic_aromatic_substitution C46497 "NHTIISPGTDJACN-UHFFFAOYSA-N"

 Success  registered route 390!

689 0 0 Amidation C45845 "MLATWPCEIWLAON-UHFFFAOYSA-N"

 Success  registered route 391!

690 0 0 Formation_of_urea_from_two_amines C45801 "FFOQKKOHSFRDDO-UHFFFAOYSA-N"

 Success  registered route 392!

691 0 0 Amidation C70091 "WCZFMVGDBUJSBO-UHFFFAOYSA-N"

 Success  registered route 393!

692 0 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C102932 "YBCNZGDJWJHKOC-UHFFFAOYSA-N"

 Success  registered route 394!

693 0 0 Amidation C48665 "CLFZGCHMMMECHQ-UHFFFAOYSA-N"

 Success  registered route 395!

694 0 0 Ugi_reaction C2016 "DPASSUYVTHZQDV-UHFFFAOYSA-N"

reactants =
[282920, 283671, 284430, 284431]

product = C2016 "DPASSUYVTHZQDV-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Ugi_reaction!

694 1 0 Ester_amidation C2016 "DPASSUYVTHZQDV-UHFFFAOYSA-N"

 Success  registered route 396!

695 0 0 Sp2-sp2_Suzuki_coupling C5573 "IIGFTWKBMUCFTB-UHFFFAOYSA-N"

 Success  registered route 397!

696 0 0 Amidation C65430 "DJBDVHCYEQULCD-UHFFFAOYSA-N"

 Warning  SMILES changed during compound registration: CC(NC(=O)c1cc[nH]n1)C1CNC1 --> CC(NC(=O)c1ccn[nH]1)C1CNC1!

 Success  registered route 398!

697 0 0 Amidation C47627 "CYCQGJXZRZHMOH-UHFFFAOYSA-N"

 Success  registered route 399!

698 0 0 Amine_alkylation C111024 "XAUYAWPMDBLCMB-UHFFFAOYSA-N"

reactants =
[284438, 284439]

product = C111024 "XAUYAWPMDBLCMB-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

698 1 0 Amine_alkylation C111024 "XAUYAWPMDBLCMB-UHFFFAOYSA-N"

reactants =
[284439, 284440]

product = C111024 "XAUYAWPMDBLCMB-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

698 2 0 Amidation C111024 "XAUYAWPMDBLCMB-UHFFFAOYSA-N"

 Success  registered route 400!

699 0 0 Sp2-sp2_Suzuki_coupling C55545 "DNVWCQWVHHGFQV-UHFFFAOYSA-N"

 Success  registered route 401!

700 0 0 Amidation C49927 "LQIMRROOJIHJNB-UHFFFAOYSA-N"

 Success  registered route 402!

701 0 0 Amidation C55679 "ATVGHXZGBSIHPD-UHFFFAOYSA-N"

 Success  registered route 403!

702 0 0 Amidation C76428 "SITKYFMZVGCCEF-UHFFFAOYSA-N"

 Success  registered route 404!

703 0 0 Formation_of_urea_from_two_amines C45694 "NGVCFPVLGXTFRC-UHFFFAOYSA-N"

 Success  registered route 405!

704 0 0 Reductive_amination C53636 "VXAIHVZBABPCQF-UHFFFAOYSA-N"

 Success  registered route 406!

705 0 0 Chan-Lam_coupling_of_amides,_sulfonamides,_and_imides C45663 "IOEZZLDHRHKNLW-UHFFFAOYSA-N"

reactants =
[284451, 284452]

product = C45663 "IOEZZLDHRHKNLW-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Chan-Lam_coupling_of_amides,_sulfonamides,_and_imides!

705 1 0 Amidation C45663 "IOEZZLDHRHKNLW-UHFFFAOYSA-N"

 Success  registered route 407!

706 0 0 Van_Leusen_imidazole_synthesis C1851 "WHQNOBWFVDSYOK-UHFFFAOYSA-N"

reactants =
[283156, 283755, 284454]

product = C1851 "WHQNOBWFVDSYOK-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Van_Leusen_imidazole_synthesis!

706 1 0 Amine_alkylation C1851 "WHQNOBWFVDSYOK-UHFFFAOYSA-N"

reactants =
[283757, 284455]

product = C1851 "WHQNOBWFVDSYOK-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

706 2 0 Amine_alkylation C1851 "WHQNOBWFVDSYOK-UHFFFAOYSA-N"

reactants =
[283757, 284456]

product = C1851 "WHQNOBWFVDSYOK-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

706 3 0 Amine_alkylation C1851 "WHQNOBWFVDSYOK-UHFFFAOYSA-N"

reactants =
[283757, 284457]

product = C1851 "WHQNOBWFVDSYOK-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

706 4 0 Amine_alkylation C1851 "WHQNOBWFVDSYOK-UHFFFAOYSA-N"

reactants =
[283757, 284458]

product = C1851 "WHQNOBWFVDSYOK-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

707 0 0 Amidation C8070 "QHQMGDZLEKICDZ-UHFFFAOYSA-N"

 Success  registered route 408!

708 0 0 Amidation C19827 "ORSASUAYDTUOGY-UHFFFAOYSA-N"

 Success  registered route 409!

709 0 0 Amidation C11207 "IZIDSOYGYYEPPV-UHFFFAOYSA-N"

 Success  registered route 410!

710 0 0 Chan-Lam_coupling_(amination) C6106 "DOUSOOUXCFRQSM-UHFFFAOYSA-N"

reactants =
[284325, 284464]

product = C6106 "DOUSOOUXCFRQSM-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Chan-Lam_coupling_(amination)!

710 1 0 Buchwald-Hartwig_amination C6106 "DOUSOOUXCFRQSM-UHFFFAOYSA-N"

 Success  registered route 411!

711 0 0 Amidation C31645 "NWHFPHZJXUAAAQ-UHFFFAOYSA-N"

 Success  registered route 412!

712 0 0 Amine_alkylation C2541 "BKHKIOXROMQUPK-UHFFFAOYSA-N"

reactants =
[284468, 284469]

product = C2541 "BKHKIOXROMQUPK-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

712 1 0 Riley_oxidation C2541 "BKHKIOXROMQUPK-UHFFFAOYSA-N"

reactants =
[284470]

product = C2541 "BKHKIOXROMQUPK-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Riley_oxidation!

712 2 0 Amine_alkylation C2541 "BKHKIOXROMQUPK-UHFFFAOYSA-N"

reactants =
[284469, 284471]

product = C2541 "BKHKIOXROMQUPK-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

712 3 0 Riley_oxidation C2541 "BKHKIOXROMQUPK-UHFFFAOYSA-N"

reactants =
[284470]

product = C2541 "BKHKIOXROMQUPK-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Riley_oxidation!

712 4 0 Amine_alkylation C2541 "BKHKIOXROMQUPK-UHFFFAOYSA-N"

reactants =
[284468, 284469]

product = C2541 "BKHKIOXROMQUPK-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

713 0 0 Amidation C3778 "AGEDTVGYDAKPRV-UHFFFAOYSA-N"

 Success  registered route 413!

714 0 0 Alpha_alkylation_of_ester/amide C5948 "YJBQQPKNCOBFQV-UHFFFAOYSA-N"

reactants =
[283127, 284473]

product = C5948 "YJBQQPKNCOBFQV-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ester/amide!

714 1 0 Amidation C5948 "YJBQQPKNCOBFQV-UHFFFAOYSA-N"

 Success  registered route 414!

715 0 0 Ester_amidation C29671 "NTHBIXDORUIWBD-UHFFFAOYSA-N"

715 1 0 Ester_amidation C29671 "NTHBIXDORUIWBD-UHFFFAOYSA-N"

 Success  registered route 415!

716 0 0 Buchwald-Hartwig_(thio)etherification C66949 "IKAMDUKMYVVAKK-UHFFFAOYSA-N"

reactants =
[284478, 284479]

product = C66949 "IKAMDUKMYVVAKK-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Buchwald-Hartwig_(thio)etherification!

716 1 0 Buchwald-Hartwig_(thio)etherification C66949 "IKAMDUKMYVVAKK-UHFFFAOYSA-N"

reactants =
[284478, 284480]

product = C66949 "IKAMDUKMYVVAKK-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Buchwald-Hartwig_(thio)etherification!

716 2 0 Buchwald-Hartwig_(thio)etherification C66949 "IKAMDUKMYVVAKK-UHFFFAOYSA-N"

reactants =
[284478, 284481]

product = C66949 "IKAMDUKMYVVAKK-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Buchwald-Hartwig_(thio)etherification!

716 3 0 S-nucleophilic_aromatic_substitution C66949 "IKAMDUKMYVVAKK-UHFFFAOYSA-N"

reactants =
[284478, 284482]

product = C66949 "IKAMDUKMYVVAKK-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: S-nucleophilic_aromatic_substitution!

716 4 0 S-nucleophilic_aromatic_substitution C66949 "IKAMDUKMYVVAKK-UHFFFAOYSA-N"

reactants =
[284478, 284480]

product = C66949 "IKAMDUKMYVVAKK-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: S-nucleophilic_aromatic_substitution!

717 0 0 S-nucleophilic_aromatic_substitution C66955 "CMZOTFOSHDWTHE-UHFFFAOYSA-N"

reactants =
[284478, 284483]

product = C66955 "CMZOTFOSHDWTHE-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: S-nucleophilic_aromatic_substitution!

717 1 0 S-nucleophilic_aromatic_substitution C66955 "CMZOTFOSHDWTHE-UHFFFAOYSA-N"

reactants =
[284478, 284484]

product = C66955 "CMZOTFOSHDWTHE-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: S-nucleophilic_aromatic_substitution!

717 2 0 Buchwald-Hartwig_(thio)etherification C66955 "CMZOTFOSHDWTHE-UHFFFAOYSA-N"

reactants =
[284478, 284484]

product = C66955 "CMZOTFOSHDWTHE-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Buchwald-Hartwig_(thio)etherification!

717 3 0 Buchwald-Hartwig_(thio)etherification C66955 "CMZOTFOSHDWTHE-UHFFFAOYSA-N"

reactants =
[284478, 284483]

product = C66955 "CMZOTFOSHDWTHE-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Buchwald-Hartwig_(thio)etherification!

717 4 0 Ester_hydrolysis_(carboxylate_fragment) C66955 "CMZOTFOSHDWTHE-UHFFFAOYSA-N"

reactants =
[284485]

product = C66955 "CMZOTFOSHDWTHE-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Ester_hydrolysis_(carboxylate_fragment)!

718 0 0 Sp2-sp2_Suzuki_coupling C131861 "VIWGUSXHUZQJLO-UHFFFAOYSA-N"

 Success  registered route 416!

719 0 0 Sulfonamide_Schotten-Baumann_with_amine_(intermolecular) C7634 "RXBXROWIEPMBRV-UHFFFAOYSA-N"

reactants =
[284488, 284489]

product = C7634 "RXBXROWIEPMBRV-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sulfonamide_Schotten-Baumann_with_amine_(intermolecular)!

719 1 0 Formation_of_sulfonamide_from_halide_-_Shavnya_reaction C7634 "RXBXROWIEPMBRV-UHFFFAOYSA-N"

reactants =
[284488, 284490]

product = C7634 "RXBXROWIEPMBRV-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Formation_of_sulfonamide_from_halide_-_Shavnya_reaction!

719 2 0 Formation_of_sulfonamide_from_halide_-_Shavnya_reaction C7634 "RXBXROWIEPMBRV-UHFFFAOYSA-N"

reactants =
[284488, 284491]

product = C7634 "RXBXROWIEPMBRV-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Formation_of_sulfonamide_from_halide_-_Shavnya_reaction!

719 3 0 Formation_of_sulfonamide_from_halide_-_Shavnya_reaction C7634 "RXBXROWIEPMBRV-UHFFFAOYSA-N"

reactants =
[284079, 284488]

product = C7634 "RXBXROWIEPMBRV-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Formation_of_sulfonamide_from_halide_-_Shavnya_reaction!

719 4 0 Sulfonamide_Schotten-Baumann_with_amine_(intermolecular) C7634 "RXBXROWIEPMBRV-UHFFFAOYSA-N"

reactants =
[284488, 284492]

product = C7634 "RXBXROWIEPMBRV-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sulfonamide_Schotten-Baumann_with_amine_(intermolecular)!

720 0 0 Amine_alkylation C6248 "NXJYTRXEEROFOS-UHFFFAOYSA-N"

reactants =
[284493]

product = C6248 "NXJYTRXEEROFOS-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

720 1 0 Amine_alkylation C6248 "NXJYTRXEEROFOS-UHFFFAOYSA-N"

reactants =
[284494]

product = C6248 "NXJYTRXEEROFOS-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

720 2 0 Amine_alkylation C6248 "NXJYTRXEEROFOS-UHFFFAOYSA-N"

reactants =
[284493]

product = C6248 "NXJYTRXEEROFOS-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

720 3 0 Amine_alkylation C6248 "NXJYTRXEEROFOS-UHFFFAOYSA-N"

reactants =
[284494]

product = C6248 "NXJYTRXEEROFOS-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

720 4 0 Amine_alkylation C6248 "NXJYTRXEEROFOS-UHFFFAOYSA-N"

reactants =
[284493]

product = C6248 "NXJYTRXEEROFOS-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

721 0 0 Amidation C1120 "PCPXIHBDOBZPNO-UHFFFAOYSA-N"

 Success  registered route 417!

722 0 0 Petasis-borono_Mannich_reaction C686 "SAIOTEOVHAXKQN-UHFFFAOYSA-N"

reactants =
[283111, 284486, 284497]

product = C686 "SAIOTEOVHAXKQN-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Petasis-borono_Mannich_reaction!

722 1 0 Reductive_amination C686 "SAIOTEOVHAXKQN-UHFFFAOYSA-N"

 Success  registered route 418!

723 0 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C2396 "KQFUVIPQGHKRPL-UHFFFAOYSA-N"

 Success  registered route 419!

724 0 0 Ester_amidation C29678 "VOTQTKPUGDWATD-UHFFFAOYSA-N"

724 1 0 Ester_amidation C29678 "VOTQTKPUGDWATD-UHFFFAOYSA-N"

 Success  registered route 420!

725 0 0 Amidation C27712 "GDQVYSCIVDEKLE-UHFFFAOYSA-N"

 Success  registered route 421!

726 0 0 Chan-Lam_coupling_(amination) C6091 "COBZFPMMXCEFIL-UHFFFAOYSA-N"

reactants =
[284503, 284504]

product = C6091 "COBZFPMMXCEFIL-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Chan-Lam_coupling_(amination)!

726 1 0 Buchwald-Hartwig_amination C6091 "COBZFPMMXCEFIL-UHFFFAOYSA-N"

 Success  registered route 422!

727 0 0 Amidation C13816 "YLJSCEDYXYHCFH-UHFFFAOYSA-N"

 Success  registered route 423!

728 0 0 Ester_amidation C29694 "OAMNIYGWLQGWFH-UHFFFAOYSA-N"

728 1 0 Alpha_alkylation_of_ester/amide C29694 "OAMNIYGWLQGWFH-UHFFFAOYSA-N"

reactants =
[284509, 284510]

product = C29694 "OAMNIYGWLQGWFH-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ester/amide!

728 2 0 Ester_amidation C29694 "OAMNIYGWLQGWFH-UHFFFAOYSA-N"

 Success  registered route 424!

729 0 0 Nucleophilic_aromatic_substitution_(methylsulfone) C6108 "SBOGVGGESDHHSA-UHFFFAOYSA-N"

reactants =
[283965, 284511]

product = C6108 "SBOGVGGESDHHSA-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Nucleophilic_aromatic_substitution_(methylsulfone)!

729 1 0 Buchwald-Hartwig_amination C6108 "SBOGVGGESDHHSA-UHFFFAOYSA-N"

 Success  registered route 425!

730 0 0 Amidation C32227 "AIHZEWPQJWAUAF-UHFFFAOYSA-N"

 Success  registered route 426!

731 0 0 Amidation C31798 "AYUAFHQJYXDAKG-UHFFFAOYSA-N"

 Success  registered route 427!

732 0 0 Amidation C41442 "MXKVMTZMLDJXBU-UHFFFAOYSA-N"

 Success  registered route 428!

733 0 0 Amidation C6060 "CBBQZDXGIJWOCE-UHFFFAOYSA-N"

 Success  registered route 429!

734 0 0 Formation_of_sulfonamide_from_halide_-_Shavnya_reaction C7599 "UXAXKRNZNZXPTI-UHFFFAOYSA-N"

reactants =
[284490, 284521]

product = C7599 "UXAXKRNZNZXPTI-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Formation_of_sulfonamide_from_halide_-_Shavnya_reaction!

734 1 0 Formation_of_sulfonamide_from_halide_-_Shavnya_reaction C7599 "UXAXKRNZNZXPTI-UHFFFAOYSA-N"

reactants =
[284079, 284521]

product = C7599 "UXAXKRNZNZXPTI-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Formation_of_sulfonamide_from_halide_-_Shavnya_reaction!

734 2 0 Formation_of_sulfonamide_from_halide_-_Shavnya_reaction C7599 "UXAXKRNZNZXPTI-UHFFFAOYSA-N"

reactants =
[284491, 284521]

product = C7599 "UXAXKRNZNZXPTI-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Formation_of_sulfonamide_from_halide_-_Shavnya_reaction!

734 3 0 Corey-House_synthesis_(intermolecular) C7599 "UXAXKRNZNZXPTI-UHFFFAOYSA-N"

reactants =
[283163, 284522]

product = C7599 "UXAXKRNZNZXPTI-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Corey-House_synthesis_(intermolecular)!

734 4 0 Corey-House_synthesis_(intermolecular) C7599 "UXAXKRNZNZXPTI-UHFFFAOYSA-N"

reactants =
[283163, 284523]

product = C7599 "UXAXKRNZNZXPTI-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Corey-House_synthesis_(intermolecular)!

735 0 0 Amidation C8470 "XMYOBLGSEFSZPI-UHFFFAOYSA-N"

 Success  registered route 430!

736 0 0 Mitsunobu_aryl_ether_synthesis C8912 "QLWADYUBFZPSNX-UHFFFAOYSA-N"

reactants =
[284526, 284527]

product = C8912 "QLWADYUBFZPSNX-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Mitsunobu_aryl_ether_synthesis!

736 1 0 N-Boc_deprotection C8912 "QLWADYUBFZPSNX-UHFFFAOYSA-N"

736 1 1 Mitsunobu_aryl_ether_synthesis C284528 "SHVPBSPCFIGILR-UHFFFAOYSA-N"

reactants =
[284526, 284529]

product = C284528 "SHVPBSPCFIGILR-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Mitsunobu_aryl_ether_synthesis!

736 2 0 N-Boc_deprotection C8912 "QLWADYUBFZPSNX-UHFFFAOYSA-N"

736 2 1 Mitsunobu_aryl_ether_synthesis C284530 "CACZDZCOBUERPL-UHFFFAOYSA-N"

reactants =
[284527, 284531]

product = C284530 "CACZDZCOBUERPL-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Mitsunobu_aryl_ether_synthesis!

736 3 0 Quinoline_pyridine_hydrogenation C8912 "QLWADYUBFZPSNX-UHFFFAOYSA-N"

reactants =
[284532]

product = C8912 "QLWADYUBFZPSNX-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Quinoline_pyridine_hydrogenation!

736 4 0 Amide_to_amine_reduction C8912 "QLWADYUBFZPSNX-UHFFFAOYSA-N"

reactants =
[284533]

product = C8912 "QLWADYUBFZPSNX-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amide_to_amine_reduction!

737 0 0 Amidation C525 "JORZCDFDZUSFGH-UHFFFAOYSA-N"

 Success  registered route 431!

738 0 0 Sp3-sp2_Suzuki_coupling C14093 "SINRWOHZHXCYHE-UHFFFAOYSA-N"

 Success  registered route 432!

739 0 0 Amidation C38436 "JICXCXXASDPJKV-UHFFFAOYSA-N"

 Success  registered route 433!

740 0 0 Amidation C10284 "DJZJZIVHKYRBPY-UHFFFAOYSA-N"

 Success  registered route 434!

741 0 0 Amidation C18032 "XZDJAODRDBHFTF-UHFFFAOYSA-N"

 Success  registered route 435!

742 0 0 Amidation C3775 "INAHVQSNTWKORJ-UHFFFAOYSA-N"

 Success  registered route 436!

743 0 0 Amidation C6013 "ZBXBLXXYJIHBMH-UHFFFAOYSA-N"

 Success  registered route 437!

744 0 0 N-Boc_deprotection C2609 "KGAKJVPCKUCLKV-UHFFFAOYSA-N"

 Success  registered route 438!

745 0 0 Amidation C6170 "MTBPSJNSQYHQEE-UHFFFAOYSA-N"

 Success  registered route 439!

746 0 0 Alpha_alkylation_of_ester/amide C14936 "TYVKHTBDVKDANR-UHFFFAOYSA-N"

reactants =
[14914, 284545]

product = C14936 "TYVKHTBDVKDANR-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ester/amide!

746 1 0 Amidation C14936 "TYVKHTBDVKDANR-UHFFFAOYSA-N"

746 1 1 Alpha_alkylation_of_ester/amide C284546 "FQHHRDUQIXXABY-UHFFFAOYSA-N"

reactants =
[284547, 284548]

product = C284546 "FQHHRDUQIXXABY-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ester/amide!

746 2 0 Alpha_alkylation_of_ester/amide C14936 "TYVKHTBDVKDANR-UHFFFAOYSA-N"

reactants =
[14914, 284549]

product = C14936 "TYVKHTBDVKDANR-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ester/amide!

746 3 0 Alpha_alkylation_of_ester/amide C14936 "TYVKHTBDVKDANR-UHFFFAOYSA-N"

reactants =
[14914, 284547]

product = C14936 "TYVKHTBDVKDANR-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ester/amide!

746 4 0 Amidation C14936 "TYVKHTBDVKDANR-UHFFFAOYSA-N"

 Success  registered route 440!

747 0 0 Sp2-sp2_Suzuki_coupling C43497 "FUNCVLSABIHRON-UHFFFAOYSA-N"

 Success  registered route 441!

748 0 0 Pinner_reaction_(carboxylate_ester) C5648 "HCFLACFMBGGTGN-UHFFFAOYSA-N"

reactants =
[284554, 284555]

product = C5648 "HCFLACFMBGGTGN-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Pinner_reaction_(carboxylate_ester)!

748 1 0 Haloform_reaction C5648 "HCFLACFMBGGTGN-UHFFFAOYSA-N"

reactants =
[284554, 284556]

product = C5648 "HCFLACFMBGGTGN-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Haloform_reaction!

748 2 0 Steglich_esterification C5648 "HCFLACFMBGGTGN-UHFFFAOYSA-N"

 Success  registered route 442!

749 0 0 Amidation C3501 "YEVKEYTWDZTQPG-UHFFFAOYSA-N"

 Success  registered route 443!

750 0 0 N-nucleophilic_aromatic_substitution C86322 "HXGBIHXJNUTVEU-UHFFFAOYSA-N"

 Success  registered route 444!

751 0 0 Amidation C1402 "MEPCMNAIXFKGGU-UHFFFAOYSA-N"

 Success  registered route 445!

752 0 0 Amidation C7155 "JBBGRUAMKVJKBX-UHFFFAOYSA-N"

 Success  registered route 446!

753 0 0 Amidation C17682 "BVGBDOZXIVOWDC-UHFFFAOYSA-N"

 Success  registered route 447!

754 0 0 Benzylic_deprotonation-alkylation_(pyridine) C973 "UERDZVKTYWOYRH-UHFFFAOYSA-N"

reactants =
[284565, 284566]

product = C973 "UERDZVKTYWOYRH-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Benzylic_deprotonation-alkylation_(pyridine)!

754 1 0 Benzylic_deprotonation-alkylation_(pyridine) C973 "UERDZVKTYWOYRH-UHFFFAOYSA-N"

reactants =
[284566, 284567]

product = C973 "UERDZVKTYWOYRH-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Benzylic_deprotonation-alkylation_(pyridine)!

754 2 0 Benzylic_deprotonation-alkylation_(pyridine) C973 "UERDZVKTYWOYRH-UHFFFAOYSA-N"

reactants =
[284566, 284568]

product = C973 "UERDZVKTYWOYRH-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Benzylic_deprotonation-alkylation_(pyridine)!

754 3 0 Sp3-sp2_Macmillan_coupling_with_bromide_(intermolecular) C973 "UERDZVKTYWOYRH-UHFFFAOYSA-N"

reactants =
[284569, 284570]

product = C973 "UERDZVKTYWOYRH-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sp3-sp2_Macmillan_coupling_with_bromide_(intermolecular)!

754 4 0 Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide C973 "UERDZVKTYWOYRH-UHFFFAOYSA-N"

reactants =
[284569, 284571]

product = C973 "UERDZVKTYWOYRH-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide!

755 0 0 Amidation C27254 "BVTPDBRQZWYODH-UHFFFAOYSA-N"

 Success  registered route 448!

756 0 0 Amidation C137292 "VEAOSVDTZUAADO-UHFFFAOYSA-N"

 Success  registered route 449!

757 0 0 Amidation C7469 "ZJUWFSGBSHLZFO-UHFFFAOYSA-N"

 Success  registered route 450!

758 0 0 Alpha_alkylation_of_ester/amide C15823 "DPUSSHZYAUIWGW-UHFFFAOYSA-N"

reactants =
[284577, 284578]

product = C15823 "DPUSSHZYAUIWGW-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ester/amide!

758 1 0 Alpha_alkylation_of_ester/amide C15823 "DPUSSHZYAUIWGW-UHFFFAOYSA-N"

reactants =
[284577, 284579]

product = C15823 "DPUSSHZYAUIWGW-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ester/amide!

758 2 0 Alpha_alkylation_of_ester/amide C15823 "DPUSSHZYAUIWGW-UHFFFAOYSA-N"

reactants =
[284577, 284580]

product = C15823 "DPUSSHZYAUIWGW-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ester/amide!

758 3 0 Beckmann_rearrangement C15823 "DPUSSHZYAUIWGW-UHFFFAOYSA-N"

reactants =
[284581]

product = C15823 "DPUSSHZYAUIWGW-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Beckmann_rearrangement!

758 4 0 Alpha_alkylation_of_ester/amide C15823 "DPUSSHZYAUIWGW-UHFFFAOYSA-N"

reactants =
[284582]

product = C15823 "DPUSSHZYAUIWGW-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ester/amide!

759 0 0 Sp3-sp2_Suzuki_coupling C6528 "IGFLHWNYLMXGMG-UHFFFAOYSA-N"

 Success  registered route 451!

760 0 0 Amidation C16512 "PGILFXQYSGPPJO-UHFFFAOYSA-N"

 Success  registered route 452!

761 0 0 Amidation C31046 "JBQKPGDVXBNGRB-UHFFFAOYSA-N"

 Success  registered route 453!

762 0 0 Amidation C16616 "IIPNYHKMPRUJNY-UHFFFAOYSA-N"

 Success  registered route 454!

763 0 0 Amidation C4708 "ISSFEYHUURQIMN-UHFFFAOYSA-N"

 Success  registered route 455!

764 0 0 Amidation C8425 "YIPVAMALDHWMTF-UHFFFAOYSA-N"

 Success  registered route 456!

765 0 0 Amidation C16607 "MLBVNWMSZZUEEK-UHFFFAOYSA-N"

 Success  registered route 457!

766 0 0 Amidation C94391 "GMNUJJZGAJDXFW-UHFFFAOYSA-N"

766 0 1 Amidation C284596 "BVMRIWAXTXVZJU-UHFFFAOYSA-N"

 Success  registered route 458!

767 0 0 Amidation C137405 "GKXYBOZHRPWQMF-UHFFFAOYSA-N"

 Success  registered route 459!

768 0 0 Imine_reduction_to_amine C6259 "BELIZRHOJQZKIU-UHFFFAOYSA-N"

reactants =
[718]

product = C6259 "BELIZRHOJQZKIU-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Imine_reduction_to_amine!

768 1 0 Reductive_amination C6259 "BELIZRHOJQZKIU-UHFFFAOYSA-N"

768 2 0 Petasis-borono_Mannich_reaction C6259 "BELIZRHOJQZKIU-UHFFFAOYSA-N"

reactants =
[284601, 284602]

product = C6259 "BELIZRHOJQZKIU-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Petasis-borono_Mannich_reaction!

768 3 0 N-Boc_deprotection C6259 "BELIZRHOJQZKIU-UHFFFAOYSA-N"

 Success  registered route 460!

769 0 0 Amidation C137594 "UOUIWTUESXXDBU-UHFFFAOYSA-N"

 Success  registered route 461!

770 0 0 Sp3-sp2_Suzuki_coupling C1791 "RJKAJKWADMVNQR-UHFFFAOYSA-N"

 Success  registered route 462!

771 0 0 Corey-House_synthesis_(intermolecular) C20070 "CLRMICGDIZHILI-UHFFFAOYSA-N"

reactants =
[284607, 284608]

product = C20070 "CLRMICGDIZHILI-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Corey-House_synthesis_(intermolecular)!

771 1 0 Amidation C20070 "CLRMICGDIZHILI-UHFFFAOYSA-N"

771 2 0 Corey-House_synthesis_(intermolecular) C20070 "CLRMICGDIZHILI-UHFFFAOYSA-N"

reactants =
[284607, 284610]

product = C20070 "CLRMICGDIZHILI-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Corey-House_synthesis_(intermolecular)!

771 3 0 Formation_of_carbamate_from_amine_and_alcohol C20070 "CLRMICGDIZHILI-UHFFFAOYSA-N"

reactants =
[284611, 284612]

product = C20070 "CLRMICGDIZHILI-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Formation_of_carbamate_from_amine_and_alcohol!

771 4 0 Corey-House_synthesis_(intermolecular) C20070 "CLRMICGDIZHILI-UHFFFAOYSA-N"

reactants =
[283163, 284613]

product = C20070 "CLRMICGDIZHILI-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Corey-House_synthesis_(intermolecular)!

772 0 0 Amidation C7166 "AVOIXSQDOULTDX-UHFFFAOYSA-N"

 Success  registered route 463!

773 0 0 Amidation C7163 "IZSOYUYGRQMQRH-UHFFFAOYSA-N"

 Success  registered route 464!

774 0 0 Amidation C25407 "ICJOJHQESJORQW-UHFFFAOYSA-N"

 Success  registered route 465!

775 0 0 Amidation C3425 "QLOQFBVXSCYUGU-UHFFFAOYSA-N"

 Success  registered route 466!

776 0 0 Formation_of_urea_from_two_amines C6688 "OKPCGXCBARQEEC-UHFFFAOYSA-N"

 Success  registered route 467!

777 0 0 Amine_alkylation C4801 "LGOSQMUDZURGMS-UHFFFAOYSA-N"

reactants =
[284139, 284622]

product = C4801 "LGOSQMUDZURGMS-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

777 1 0 Amine_alkylation C4801 "LGOSQMUDZURGMS-UHFFFAOYSA-N"

reactants =
[284139, 284623]

product = C4801 "LGOSQMUDZURGMS-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

777 2 0 Amine_alkylation C4801 "LGOSQMUDZURGMS-UHFFFAOYSA-N"

reactants =
[284139, 284624]

product = C4801 "LGOSQMUDZURGMS-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

777 3 0 Elimination_reaction C4801 "LGOSQMUDZURGMS-UHFFFAOYSA-N"

reactants =
[284625]

product = C4801 "LGOSQMUDZURGMS-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Elimination_reaction!

777 4 0 Amine_alkylation C4801 "LGOSQMUDZURGMS-UHFFFAOYSA-N"

reactants =
[284139, 284626]

product = C4801 "LGOSQMUDZURGMS-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

778 0 0 Isocyanate_to_urea C12392 "ZQPQFOMHEKOXNL-UHFFFAOYSA-N"

reactants =
[284627, 284628]

product = C12392 "ZQPQFOMHEKOXNL-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Isocyanate_to_urea!

778 1 0 Formation_of_urea_from_two_amines C12392 "ZQPQFOMHEKOXNL-UHFFFAOYSA-N"

 Success  registered route 468!

779 0 0 Alpha_alkylation_of_ketone C18178 "YSYAKSZYKZXPDR-UHFFFAOYSA-N"

reactants =
[18206, 284630]

product = C18178 "YSYAKSZYKZXPDR-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ketone!

779 1 0 Conjugate_addition_of_Grignard_(Gilman_reagents) C18178 "YSYAKSZYKZXPDR-UHFFFAOYSA-N"

reactants =
[284631, 284632]

product = C18178 "YSYAKSZYKZXPDR-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Conjugate_addition_of_Grignard_(Gilman_reagents)!

779 2 0 Alpha_alkylation_of_ketone C18178 "YSYAKSZYKZXPDR-UHFFFAOYSA-N"

reactants =
[18206, 284633]

product = C18178 "YSYAKSZYKZXPDR-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ketone!

779 3 0 Swern_oxidation C18178 "YSYAKSZYKZXPDR-UHFFFAOYSA-N"

reactants =
[284634]

product = C18178 "YSYAKSZYKZXPDR-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Swern_oxidation!

779 4 0 Alkyne_to_alkane_hydrogenation C18178 "YSYAKSZYKZXPDR-UHFFFAOYSA-N"

reactants =
[284635]

product = C18178 "YSYAKSZYKZXPDR-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alkyne_to_alkane_hydrogenation!

780 0 0 Amidation C7467 "UICBVSXZBKLTCN-UHFFFAOYSA-N"

 Success  registered route 469!

781 0 0 Ester_Schotten-Baumann C15058 "OHSAREOUZZCQAJ-UHFFFAOYSA-N"

reactants =
[284638, 284639]

product = C15058 "OHSAREOUZZCQAJ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Ester_Schotten-Baumann!

781 1 0 Formation_of_carbamate_from_amine_and_alcohol C15058 "OHSAREOUZZCQAJ-UHFFFAOYSA-N"

reactants =
[284638, 284640]

product = C15058 "OHSAREOUZZCQAJ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Formation_of_carbamate_from_amine_and_alcohol!

781 2 0 Minisci_reaction_with_carboxylic_acid_(intermolecular) C15058 "OHSAREOUZZCQAJ-UHFFFAOYSA-N"

reactants =
[283318, 284641]

product = C15058 "OHSAREOUZZCQAJ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Minisci_reaction_with_carboxylic_acid_(intermolecular)!

781 3 0 Pinner_reaction_(carboxylate_ester) C15058 "OHSAREOUZZCQAJ-UHFFFAOYSA-N"

reactants =
[284638, 284642]

product = C15058 "OHSAREOUZZCQAJ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Pinner_reaction_(carboxylate_ester)!

781 4 0 Amide_to_nitrile C15058 "OHSAREOUZZCQAJ-UHFFFAOYSA-N"

reactants =
[284643]

product = C15058 "OHSAREOUZZCQAJ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amide_to_nitrile!

782 0 0 Amidation C6003 "NBQUOSUMIDGENX-UHFFFAOYSA-N"

 Success  registered route 470!

783 0 0 Isocyanate_to_urea C12390 "TVRSJPQUTNYHJL-UHFFFAOYSA-N"

reactants =
[284627, 284645]

product = C12390 "TVRSJPQUTNYHJL-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Isocyanate_to_urea!

783 1 0 Formation_of_urea_from_two_amines C12390 "TVRSJPQUTNYHJL-UHFFFAOYSA-N"

 Success  registered route 471!

784 0 0 Alpha_alkylation_of_ketone C2421 "MZDOVACAPIIERT-UHFFFAOYSA-N"

reactants =
[283810, 284646]

product = C2421 "MZDOVACAPIIERT-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ketone!

784 1 0 Alpha_alkylation_of_ketone C2421 "MZDOVACAPIIERT-UHFFFAOYSA-N"

reactants =
[284000, 284646]

product = C2421 "MZDOVACAPIIERT-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ketone!

784 2 0 Alpha_alkylation_of_ketone C2421 "MZDOVACAPIIERT-UHFFFAOYSA-N"

reactants =
[283999, 284646]

product = C2421 "MZDOVACAPIIERT-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ketone!

784 3 0 Alkyne_to_alkane_hydrogenation C2421 "MZDOVACAPIIERT-UHFFFAOYSA-N"

reactants =
[284647]

product = C2421 "MZDOVACAPIIERT-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alkyne_to_alkane_hydrogenation!

784 4 0 Ethenyl_to_formyl C2421 "MZDOVACAPIIERT-UHFFFAOYSA-N"

reactants =
[284648]

product = C2421 "MZDOVACAPIIERT-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Ethenyl_to_formyl!

785 0 0 Amide_to_amine_reduction C7492 "GKUFWTQUJZVHEF-UHFFFAOYSA-N"

reactants =
[284649]

product = C7492 "GKUFWTQUJZVHEF-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amide_to_amine_reduction!

785 1 0 Corey-House_synthesis_(intermolecular) C7492 "GKUFWTQUJZVHEF-UHFFFAOYSA-N"

reactants =
[284607, 284650]

product = C7492 "GKUFWTQUJZVHEF-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Corey-House_synthesis_(intermolecular)!

785 2 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C7492 "GKUFWTQUJZVHEF-UHFFFAOYSA-N"

 Success  registered route 472!

786 0 0 Amidation C1335 "ASXOQFKVRDSSQV-UHFFFAOYSA-N"

 Success  registered route 473!

787 0 0 Amidation C4120 "SCEDCLAZUHAAQO-UHFFFAOYSA-N"

 Success  registered route 474!

788 0 0 N-nucleophilic_aromatic_substitution C733 "TVAYLIZZNFTQFK-UHFFFAOYSA-N"

 Success  registered route 475!

789 0 0 Amidation C8861 "MKTBAFXTCUWNBK-UHFFFAOYSA-N"

 Success  registered route 476!

790 0 0 Reductive_amination C20719 "XPVXHOUETPQGLE-UHFFFAOYSA-N"

 Success  registered route 477!

791 0 0 Amidation C92303 "OKTSLPRUODZUGE-UHFFFAOYSA-N"

 Success  registered route 478!

792 0 0 Formation_of_urea_from_two_amines C2911 "NCEQHOKEWKRXIV-UHFFFAOYSA-N"

 Success  registered route 479!

793 0 0 Sp3-sp2_Suzuki_coupling C1786 "JXWMKEUIJSXMCW-UHFFFAOYSA-N"

 Success  registered route 480!

794 0 0 Alpha_alkylation_of_ester/amide C11116 "WBRPYRDSULUSNM-UHFFFAOYSA-N"

reactants =
[284140, 284663]

product = C11116 "WBRPYRDSULUSNM-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ester/amide!

794 1 0 Alpha_alkylation_of_ester/amide C11116 "WBRPYRDSULUSNM-UHFFFAOYSA-N"

reactants =
[284663, 284664]

product = C11116 "WBRPYRDSULUSNM-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ester/amide!

794 2 0 Amidation C11116 "WBRPYRDSULUSNM-UHFFFAOYSA-N"

794 2 1 Amidation C284666 "HDGUTVUPJMEKEZ-UHFFFAOYSA-N"

 Success  registered route 481!

795 0 0 Amidation C8041 "NFLBITXMLRACJJ-UHFFFAOYSA-N"

 Success  registered route 482!

796 0 0 Amidation C12499 "BCDQTWFBHRJQBJ-UHFFFAOYSA-N"

 Success  registered route 483!

797 0 0 Amidation C8808 "SKSIURWSBHFBHM-UHFFFAOYSA-N"

 Success  registered route 484!

798 0 0 Amidation C13230 "MHHNFZZOJRSSDX-UHFFFAOYSA-N"

 Success  registered route 485!

799 0 0 Amidation C14131 "UGKZNMVPXYTRAP-UHFFFAOYSA-N"

 Success  registered route 486!

800 0 0 Amidation C137590 "OCOAFNKPMGWDGK-UHFFFAOYSA-N"

 Success  registered route 487!

801 0 0 Chan-Lam_coupling_(amination) C717 "NALJDFTWWSKAFR-UHFFFAOYSA-N"

reactants =
[283978, 284678]

product = C717 "NALJDFTWWSKAFR-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Chan-Lam_coupling_(amination)!

801 1 0 Buchwald-Hartwig_amination C717 "NALJDFTWWSKAFR-UHFFFAOYSA-N"

 Success  registered route 488!

802 0 0 Amidation C2655 "KPRRPMPYWRBBFE-UHFFFAOYSA-N"

 Success  registered route 489!

803 0 0 Reductive_amination C24158 "NGTVSTSCMVXIID-UHFFFAOYSA-N"

 Success  registered route 490!

804 0 0 Reductive_amination C39011 "FVYPBJNBOMUKIB-UHFFFAOYSA-N"

 Success  registered route 491!

805 0 0 Amidation C5967 "LSUAPJGZXMGFQN-UHFFFAOYSA-N"

 Success  registered route 492!

806 0 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C6187 "FUFCTZFRZVSXTB-UHFFFAOYSA-N"

 Success  registered route 493!

807 0 0 Amidation C10379 "MRPNTPLWNNFLQF-UHFFFAOYSA-N"

 Success  registered route 494!

808 0 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C92873 "GMRFHKBAYYYVFF-UHFFFAOYSA-N"

 Success  registered route 495!

809 0 0 Sulfonamide_Schotten-Baumann_with_amine_(intermolecular) C82633 "OSQOBRFFSJVYOU-UHFFFAOYSA-N"

reactants =
[284691, 284692]

product = C82633 "OSQOBRFFSJVYOU-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sulfonamide_Schotten-Baumann_with_amine_(intermolecular)!

809 1 0 Sulfonamide_Schotten-Baumann_with_amine_(intermolecular) C82633 "OSQOBRFFSJVYOU-UHFFFAOYSA-N"

reactants =
[284691, 284693]

product = C82633 "OSQOBRFFSJVYOU-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sulfonamide_Schotten-Baumann_with_amine_(intermolecular)!

809 2 0 Nucleophilic_substitution_with_nitrile C82633 "OSQOBRFFSJVYOU-UHFFFAOYSA-N"

reactants =
[284694]

product = C82633 "OSQOBRFFSJVYOU-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Nucleophilic_substitution_with_nitrile!

809 3 0 Nucleophilic_substitution_with_nitrile C82633 "OSQOBRFFSJVYOU-UHFFFAOYSA-N"

reactants =
[284695]

product = C82633 "OSQOBRFFSJVYOU-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Nucleophilic_substitution_with_nitrile!

809 4 0 Nucleophilic_substitution_with_nitrile C82633 "OSQOBRFFSJVYOU-UHFFFAOYSA-N"

reactants =
[284696]

product = C82633 "OSQOBRFFSJVYOU-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Nucleophilic_substitution_with_nitrile!

810 0 0 N-Boc_deprotection C4764 "CJXLGMYFPUVARV-UHFFFAOYSA-N"

 Success  registered route 496!

811 0 0 Amidation C7520 "WVOIPXNGWQBXDQ-UHFFFAOYSA-N"

 Success  registered route 497!

812 0 0 Amine_alkylation C34336 "QJWWGHKEHQNEQY-UHFFFAOYSA-N"

reactants =
[284700, 284701]

product = C34336 "QJWWGHKEHQNEQY-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

812 1 0 Mannich_reaction C34336 "QJWWGHKEHQNEQY-UHFFFAOYSA-N"

reactants =
[29275, 284700]

product = C34336 "QJWWGHKEHQNEQY-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Mannich_reaction!

812 2 0 Amine_alkylation C34336 "QJWWGHKEHQNEQY-UHFFFAOYSA-N"

reactants =
[284700, 284702]

product = C34336 "QJWWGHKEHQNEQY-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

812 3 0 Ester_amidation C34336 "QJWWGHKEHQNEQY-UHFFFAOYSA-N"

812 3 1 Reductive_amination C284703 "CYRVYVKNBGZSML-UHFFFAOYSA-N"

 Success  registered route 498!

813 0 0 Mannich_reaction C18943 "YUJANCLQKWVXAZ-UHFFFAOYSA-N"

reactants =
[283111, 284705]

product = C18943 "YUJANCLQKWVXAZ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Mannich_reaction!

813 1 0 Ethenyl_to_formyl C18943 "YUJANCLQKWVXAZ-UHFFFAOYSA-N"

reactants =
[284706]

product = C18943 "YUJANCLQKWVXAZ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Ethenyl_to_formyl!

813 2 0 Ozonolysis_(intermolecular) C18943 "YUJANCLQKWVXAZ-UHFFFAOYSA-N"

reactants =
[284706]

product = C18943 "YUJANCLQKWVXAZ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Ozonolysis_(intermolecular)!

813 3 0 Alpha_alkylation_of_aldehyde C18943 "YUJANCLQKWVXAZ-UHFFFAOYSA-N"

reactants =
[283111, 284707]

product = C18943 "YUJANCLQKWVXAZ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_aldehyde!

813 4 0 Ozonolysis_(intermolecular) C18943 "YUJANCLQKWVXAZ-UHFFFAOYSA-N"

reactants =
[284708]

product = C18943 "YUJANCLQKWVXAZ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Ozonolysis_(intermolecular)!

814 0 0 Nucleophilic_substitution_with_thioamide C6038 "GOLAEVZHHBNYFC-UHFFFAOYSA-N"

reactants =
[284709, 284710]

product = C6038 "GOLAEVZHHBNYFC-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Nucleophilic_substitution_with_thioamide!

814 1 0 Nucleophilic_substitution_with_thiol C6038 "GOLAEVZHHBNYFC-UHFFFAOYSA-N"

 Warning  SMILES changed during compound registration: Sc1nnc(N2CCOCC2)s1 --> S=c1[nH]nc(N2CCOCC2)s1!

reactants =
[284709, 284710]

product = C6038 "GOLAEVZHHBNYFC-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Nucleophilic_substitution_with_thiol!

814 2 0 Alpha_alkylation_of_ketone C6038 "GOLAEVZHHBNYFC-UHFFFAOYSA-N"

reactants =
[283280, 284711]

product = C6038 "GOLAEVZHHBNYFC-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ketone!

814 3 0 Alpha_alkylation_of_ketone C6038 "GOLAEVZHHBNYFC-UHFFFAOYSA-N"

reactants =
[283127, 284711]

product = C6038 "GOLAEVZHHBNYFC-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ketone!

814 4 0 Alpha_alkylation_of_ketone C6038 "GOLAEVZHHBNYFC-UHFFFAOYSA-N"

reactants =
[283128, 284711]

product = C6038 "GOLAEVZHHBNYFC-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ketone!

815 0 0 Amidation C2124 "IIGXHTIDEPJZDV-UHFFFAOYSA-N"

 Success  registered route 499!

816 0 0 Stille_coupling C11982 "FIVHXQGGXYYQJB-UHFFFAOYSA-N"

reactants =
[284712, 284713]

product = C11982 "FIVHXQGGXYYQJB-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Stille_coupling!

816 1 0 Sp2-sp2_Suzuki_coupling C11982 "FIVHXQGGXYYQJB-UHFFFAOYSA-N"

 Success  registered route 500!

817 0 0 Amidation C33638 "GZMCLAHOGOMNFO-UHFFFAOYSA-N"

817 0 1 Amidation C284716 "XYKWXTIJAVRDEW-UHFFFAOYSA-N"

 Success  registered route 501!

818 0 0 Formation_of_sulfonamide_from_boronic_and_amine C35059 "ZXIQETDVUZSVBJ-UHFFFAOYSA-N"

reactants =
[4754, 284719]

product = C35059 "ZXIQETDVUZSVBJ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Formation_of_sulfonamide_from_boronic_and_amine!

818 1 0 Formation_of_sulfonamide_from_halide_-_Shavnya_reaction C35059 "ZXIQETDVUZSVBJ-UHFFFAOYSA-N"

reactants =
[4754, 284720]

product = C35059 "ZXIQETDVUZSVBJ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Formation_of_sulfonamide_from_halide_-_Shavnya_reaction!

818 2 0 Formation_of_sulfonamide_from_halide_-_Shavnya_reaction C35059 "ZXIQETDVUZSVBJ-UHFFFAOYSA-N"

reactants =
[4754, 284721]

product = C35059 "ZXIQETDVUZSVBJ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Formation_of_sulfonamide_from_halide_-_Shavnya_reaction!

818 3 0 Formation_of_sulfonamide_from_halide_-_Shavnya_reaction C35059 "ZXIQETDVUZSVBJ-UHFFFAOYSA-N"

reactants =
[4754, 284722]

product = C35059 "ZXIQETDVUZSVBJ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Formation_of_sulfonamide_from_halide_-_Shavnya_reaction!

818 4 0 Sulfonamide_Schotten-Baumann_with_amine_(intermolecular) C35059 "ZXIQETDVUZSVBJ-UHFFFAOYSA-N"

reactants =
[4754, 284723]

product = C35059 "ZXIQETDVUZSVBJ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sulfonamide_Schotten-Baumann_with_amine_(intermolecular)!

819 0 0 Amidation C130294 "HVLXCUMSINBNKL-UHFFFAOYSA-N"

 Success  registered route 502!

820 0 0 Petasis-borono_Mannich_reaction C55269 "OORBTWFKCNWGNJ-UHFFFAOYSA-N"

reactants =
[282920, 283064, 284725]

product = C55269 "OORBTWFKCNWGNJ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Petasis-borono_Mannich_reaction!

820 1 0 Petasis-borono_Mannich_reaction C55269 "OORBTWFKCNWGNJ-UHFFFAOYSA-N"

reactants =
[282920, 284726, 284727]

product = C55269 "OORBTWFKCNWGNJ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Petasis-borono_Mannich_reaction!

820 2 0 Petasis-borono_Mannich_reaction C55269 "OORBTWFKCNWGNJ-UHFFFAOYSA-N"

reactants =
[282920, 284727, 284728]

product = C55269 "OORBTWFKCNWGNJ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Petasis-borono_Mannich_reaction!

820 3 0 Minisci_reaction_with_carboxylic_acid_(intermolecular) C55269 "OORBTWFKCNWGNJ-UHFFFAOYSA-N"

reactants =
[283757, 284729]

product = C55269 "OORBTWFKCNWGNJ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Minisci_reaction_with_carboxylic_acid_(intermolecular)!

820 4 0 Reductive_amination C55269 "OORBTWFKCNWGNJ-UHFFFAOYSA-N"

 Success  registered route 503!

821 0 0 Amidation C3807 "ULRPMLDUMSAKFM-UHFFFAOYSA-N"

 Success  registered route 504!

822 0 0 Minisci_reaction_with_carboxylic_acid_(intermolecular) C1823 "WERCHVXXXMTJME-UHFFFAOYSA-N"

reactants =
[283318, 284732]

product = C1823 "WERCHVXXXMTJME-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Minisci_reaction_with_carboxylic_acid_(intermolecular)!

822 1 0 Hydrogenation_of_pyridine C1823 "WERCHVXXXMTJME-UHFFFAOYSA-N"

reactants =
[3654]

product = C1823 "WERCHVXXXMTJME-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Hydrogenation_of_pyridine!

822 2 0 Petasis-borono_Mannich_reaction C1823 "WERCHVXXXMTJME-UHFFFAOYSA-N"

reactants =
[284421, 284733]

product = C1823 "WERCHVXXXMTJME-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Petasis-borono_Mannich_reaction!

822 3 0 N-Boc_deprotection C1823 "WERCHVXXXMTJME-UHFFFAOYSA-N"

 Success  registered route 505!

823 0 0 Buchwald-Hartwig_amination C1169 "CGHAWODWSBOPHV-UHFFFAOYSA-N"

 Success  registered route 506!

824 0 0 Petasis-borono_Mannich_reaction C1803 "JTKBNXRWTLWVNM-UHFFFAOYSA-N"

reactants =
[284733, 284736]

product = C1803 "JTKBNXRWTLWVNM-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Petasis-borono_Mannich_reaction!

824 1 0 Hydrogenation_of_pyridine C1803 "JTKBNXRWTLWVNM-UHFFFAOYSA-N"

reactants =
[3662]

product = C1803 "JTKBNXRWTLWVNM-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Hydrogenation_of_pyridine!

824 2 0 N-Boc_deprotection C1803 "JTKBNXRWTLWVNM-UHFFFAOYSA-N"

 Success  registered route 507!

825 0 0 Amidation C21091 "UPVSFXPIZJMBGP-UHFFFAOYSA-N"

 Success  registered route 508!

826 0 0 Formation_of_urea_from_two_amines C8920 "GXLWWRPCSDKINQ-UHFFFAOYSA-N"

 Success  registered route 509!

827 0 0 N-Boc_deprotection C4746 "MHSGZEFYVKSBLF-UHFFFAOYSA-N"

 Success  registered route 510!

828 0 0 Amidation C20105 "ZUCKYOCXPYNNQW-UHFFFAOYSA-N"

 Success  registered route 511!

829 0 0 Sp3-sp2_Macmillan_coupling_with_bromide_(intermolecular) C18941 "GHTQJYVHMYLSOL-UHFFFAOYSA-N"

reactants =
[284743, 284744]

product = C18941 "GHTQJYVHMYLSOL-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sp3-sp2_Macmillan_coupling_with_bromide_(intermolecular)!

829 1 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C18941 "GHTQJYVHMYLSOL-UHFFFAOYSA-N"

829 1 1 NHK_reaction C284745 "XCLYOYCYVJSXLE-UHFFFAOYSA-N"

reactants =
[283156, 284746]

product = C284745 "XCLYOYCYVJSXLE-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: NHK_reaction!

829 2 0 Williamson_ether_synthesis C18941 "GHTQJYVHMYLSOL-UHFFFAOYSA-N"

 Success  registered route 512!

830 0 0 N-nucleophilic_aromatic_substitution C18492 "IWXAZUGAFBIABQ-UHFFFAOYSA-N"

 Success  registered route 513!

831 0 0 Reductive_amination C5654 "MIJXJNKYRJUUNZ-UHFFFAOYSA-N"

 Success  registered route 514!

832 0 0 Formation_of_urea_from_two_amines C22202 "OBYODZPHMWOBDT-UHFFFAOYSA-N"

 Success  registered route 515!

833 0 0 Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide C6268 "YFEHDHGTUJUJKX-UHFFFAOYSA-N"

reactants =
[284178, 284753]

product = C6268 "YFEHDHGTUJUJKX-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide!

833 1 0 Amine_alkylation C6268 "YFEHDHGTUJUJKX-UHFFFAOYSA-N"

reactants =
[284754]

product = C6268 "YFEHDHGTUJUJKX-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

833 2 0 Amine_alkylation C6268 "YFEHDHGTUJUJKX-UHFFFAOYSA-N"

reactants =
[284755]

product = C6268 "YFEHDHGTUJUJKX-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

833 3 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C6268 "YFEHDHGTUJUJKX-UHFFFAOYSA-N"

833 4 0 Amine_alkylation C6268 "YFEHDHGTUJUJKX-UHFFFAOYSA-N"

reactants =
[284757]

product = C6268 "YFEHDHGTUJUJKX-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

834 0 0 Formation_of_urea_from_two_amines C129989 "ILKJWDJJINULLS-UHFFFAOYSA-N"

 Success  registered route 516!

835 0 0 Amidation C10831 "LAVULZBUGIJAIW-UHFFFAOYSA-N"

 Success  registered route 517!

836 0 0 Amidation C8973 "QEVCNVOOKXMKLD-UHFFFAOYSA-N"

 Success  registered route 518!

837 0 0 Amidation C85352 "QWJIGENMFCZKMW-UHFFFAOYSA-N"

 Success  registered route 519!

838 0 0 Amidation C94799 "UTSSZZOTMTVFDK-UHFFFAOYSA-N"

 Success  registered route 520!

839 0 0 Amidation C13838 "IZSCHRLXBICVLQ-UHFFFAOYSA-N"

 Success  registered route 521!

840 0 0 Amidation C1391 "RQFZEASXPNBDLI-UHFFFAOYSA-N"

 Success  registered route 522!

841 0 0 N-nucleophilic_aromatic_substitution C27720 "ADVKSLWFNRLRGX-UHFFFAOYSA-N"

 Success  registered route 523!

842 0 0 Amine_alkylation C798 "XNMOBDIPLKKDMN-UHFFFAOYSA-N"

reactants =
[283760, 284771]

product = C798 "XNMOBDIPLKKDMN-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

842 1 0 Amine_alkylation C798 "XNMOBDIPLKKDMN-UHFFFAOYSA-N"

reactants =
[283759, 284771]

product = C798 "XNMOBDIPLKKDMN-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

842 2 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C798 "XNMOBDIPLKKDMN-UHFFFAOYSA-N"

 Success  registered route 524!

843 0 0 Amidation C36705 "ONRWVJVKMVEFCF-UHFFFAOYSA-N"

 Success  registered route 525!

844 0 0 Amidation C9079 "YGPKMENKUMLTBY-UHFFFAOYSA-N"

 Success  registered route 526!

845 0 0 Amidation C4820 "IVEXCVXFXPPGNY-UHFFFAOYSA-N"

 Success  registered route 527!

846 0 0 Petasis-borono_Mannich_reaction C15053 "GIUVSXLAIVLOML-UHFFFAOYSA-N"

reactants =
[284126, 284421, 284779]

product = C15053 "GIUVSXLAIVLOML-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Petasis-borono_Mannich_reaction!

846 1 0 Formation_of_sulfonamide_from_halide_-_Shavnya_reaction C15053 "GIUVSXLAIVLOML-UHFFFAOYSA-N"

reactants =
[284780, 284781]

product = C15053 "GIUVSXLAIVLOML-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Formation_of_sulfonamide_from_halide_-_Shavnya_reaction!

846 2 0 Formation_of_sulfonamide_from_halide_-_Shavnya_reaction C15053 "GIUVSXLAIVLOML-UHFFFAOYSA-N"

reactants =
[284781, 284782]

product = C15053 "GIUVSXLAIVLOML-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Formation_of_sulfonamide_from_halide_-_Shavnya_reaction!

846 3 0 Sulfonamide_Schotten-Baumann_with_amine_(intermolecular) C15053 "GIUVSXLAIVLOML-UHFFFAOYSA-N"

reactants =
[284781, 284783]

product = C15053 "GIUVSXLAIVLOML-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sulfonamide_Schotten-Baumann_with_amine_(intermolecular)!

846 4 0 Formation_of_sulfonamide_from_halide_-_Shavnya_reaction C15053 "GIUVSXLAIVLOML-UHFFFAOYSA-N"

reactants =
[284781, 284784]

product = C15053 "GIUVSXLAIVLOML-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Formation_of_sulfonamide_from_halide_-_Shavnya_reaction!

847 0 0 Buchwald-Hartwig_amination C1257 "DETFJAMYSPHHBK-UHFFFAOYSA-N"

 Success  registered route 528!

848 0 0 Sulfonamide_Schotten-Baumann_with_amine_(intermolecular) C15036 "LJZIXTIXXJIVMZ-UHFFFAOYSA-N"

reactants =
[284786, 284787]

product = C15036 "LJZIXTIXXJIVMZ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sulfonamide_Schotten-Baumann_with_amine_(intermolecular)!

848 1 0 Sulfonamide_Schotten-Baumann_with_amine_(intermolecular) C15036 "LJZIXTIXXJIVMZ-UHFFFAOYSA-N"

reactants =
[284787, 284788]

product = C15036 "LJZIXTIXXJIVMZ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sulfonamide_Schotten-Baumann_with_amine_(intermolecular)!

848 2 0 Formation_of_sulfonamide_from_halide_-_Shavnya_reaction C15036 "LJZIXTIXXJIVMZ-UHFFFAOYSA-N"

reactants =
[283814, 284787]

product = C15036 "LJZIXTIXXJIVMZ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Formation_of_sulfonamide_from_halide_-_Shavnya_reaction!

848 3 0 Formation_of_sulfonamide_from_halide_-_Shavnya_reaction C15036 "LJZIXTIXXJIVMZ-UHFFFAOYSA-N"

reactants =
[284787, 284789]

product = C15036 "LJZIXTIXXJIVMZ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Formation_of_sulfonamide_from_halide_-_Shavnya_reaction!

848 4 0 Formation_of_sulfonamide_from_halide_-_Shavnya_reaction C15036 "LJZIXTIXXJIVMZ-UHFFFAOYSA-N"

reactants =
[284787, 284790]

product = C15036 "LJZIXTIXXJIVMZ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Formation_of_sulfonamide_from_halide_-_Shavnya_reaction!

849 0 0 Amidation C7185 "KHYQSBBCZQEPEA-UHFFFAOYSA-N"

 Success  registered route 529!

850 0 0 Amidation C8165 "SEVSZWOINVGPQI-UHFFFAOYSA-N"

 Success  registered route 530!

851 0 0 Amidation C27907 "QYTMWYMZVFYJAW-UHFFFAOYSA-N"

 Success  registered route 531!

852 0 0 Amidation C10333 "MLNMURZXNDQHPB-UHFFFAOYSA-N"

 Success  registered route 532!

853 0 0 Amidation C87026 "CWSPXHPREHEYCE-UHFFFAOYSA-N"

 Success  registered route 533!

854 0 0 Amine_alkylation C5168 "DSRVXZMXCPNZDO-UHFFFAOYSA-N"

reactants =
[283758, 283965]

product = C5168 "DSRVXZMXCPNZDO-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

854 1 0 Amine_alkylation C5168 "DSRVXZMXCPNZDO-UHFFFAOYSA-N"

reactants =
[283759, 283965]

product = C5168 "DSRVXZMXCPNZDO-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

854 2 0 Amine_alkylation C5168 "DSRVXZMXCPNZDO-UHFFFAOYSA-N"

reactants =
[283760, 283965]

product = C5168 "DSRVXZMXCPNZDO-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

854 3 0 Amine_alkylation C5168 "DSRVXZMXCPNZDO-UHFFFAOYSA-N"

reactants =
[283761, 283965]

product = C5168 "DSRVXZMXCPNZDO-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

854 4 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C5168 "DSRVXZMXCPNZDO-UHFFFAOYSA-N"

 Success  registered route 534!

855 0 0 1,2,4-Oxadiazole_synthesis_(nitrile_+_carboxylic_acid) C27906 "SGWHFDPWZAGZRG-UHFFFAOYSA-N"

reactants =
[284798, 284799]

product = C27906 "SGWHFDPWZAGZRG-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: 1,2,4-Oxadiazole_synthesis_(nitrile_+_carboxylic_acid)!

855 1 0 1,2,4-Oxadiazole_synthesis_(amidoxime_+_carboxylate) C27906 "SGWHFDPWZAGZRG-UHFFFAOYSA-N"

reactants =
[284800, 284801]

product = C27906 "SGWHFDPWZAGZRG-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: 1,2,4-Oxadiazole_synthesis_(amidoxime_+_carboxylate)!

855 2 0 1,2,4-Oxadiazole_synthesis_(amidoxime_+_carboxylate) C27906 "SGWHFDPWZAGZRG-UHFFFAOYSA-N"

reactants =
[284800, 284802]

product = C27906 "SGWHFDPWZAGZRG-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: 1,2,4-Oxadiazole_synthesis_(amidoxime_+_carboxylate)!

855 3 0 1,2,4-Oxadiazole_synthesis_(amidoxime_+_carboxylate) C27906 "SGWHFDPWZAGZRG-UHFFFAOYSA-N"

reactants =
[284798, 284800]

product = C27906 "SGWHFDPWZAGZRG-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: 1,2,4-Oxadiazole_synthesis_(amidoxime_+_carboxylate)!

855 4 0 N-Boc_deprotection C27906 "SGWHFDPWZAGZRG-UHFFFAOYSA-N"

855 4 1 1,2,4-Oxadiazole_synthesis_(amidoxime_+_carboxylate) C284803 "MLVLWRZVCFVELA-UHFFFAOYSA-N"

reactants =
[284802, 284804]

product = C284803 "MLVLWRZVCFVELA-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: 1,2,4-Oxadiazole_synthesis_(amidoxime_+_carboxylate)!

856 0 0 Amidation C20947 "OTUZIMGZAJGPTD-UHFFFAOYSA-N"

 Success  registered route 535!

857 0 0 Amidation C15351 "YWXZMUQGZGJALN-UHFFFAOYSA-N"

 Success  registered route 536!

858 0 0 Amidation C7605 "GHIJXTOSIYSZBD-UHFFFAOYSA-N"

 Success  registered route 537!

859 0 0 Alpha_alkylation_of_ester/amide C1328 "QEAIPLSLYLEHLE-UHFFFAOYSA-N"

reactants =
[78, 284809]

product = C1328 "QEAIPLSLYLEHLE-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ester/amide!

859 1 0 Amidation C1328 "QEAIPLSLYLEHLE-UHFFFAOYSA-N"

 Success  registered route 538!

860 0 0 Amidation C13612 "NOLYSQFICWENKE-UHFFFAOYSA-N"

 Success  registered route 539!

861 0 0 Amidation C24648 "XEWCFUUENPDOSL-UHFFFAOYSA-N"

 Success  registered route 540!

862 0 0 Sp2-sp2_Suzuki_coupling C6282 "ORBZHPMIKIFVPF-UHFFFAOYSA-N"

 Success  registered route 541!

863 0 0 Amidation C3842 "PLIIAKFRJSUEBR-UHFFFAOYSA-N"

 Success  registered route 542!

864 0 0 Nucleophilic_substitution_with_thioamide C31893 "FKUJMGDPPLMJGR-UHFFFAOYSA-N"

reactants =
[284077, 284817]

product = C31893 "FKUJMGDPPLMJGR-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Nucleophilic_substitution_with_thioamide!

864 1 0 Nucleophilic_substitution_with_thiol C31893 "FKUJMGDPPLMJGR-UHFFFAOYSA-N"

 Warning  SMILES changed during compound registration: COCc1nnc(S)s1 --> COCc1n[nH]c(=S)s1!

reactants =
[284076, 284817]

product = C31893 "FKUJMGDPPLMJGR-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Nucleophilic_substitution_with_thiol!

864 2 0 Nucleophilic_substitution_with_thiol C31893 "FKUJMGDPPLMJGR-UHFFFAOYSA-N"

 Warning  SMILES changed during compound registration: COCc1nnc(S)s1 --> COCc1n[nH]c(=S)s1!

reactants =
[284077, 284817]

product = C31893 "FKUJMGDPPLMJGR-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Nucleophilic_substitution_with_thiol!

864 3 0 Nucleophilic_substitution_with_thioamide C31893 "FKUJMGDPPLMJGR-UHFFFAOYSA-N"

reactants =
[284076, 284817]

product = C31893 "FKUJMGDPPLMJGR-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Nucleophilic_substitution_with_thioamide!

864 4 0 Amidation C31893 "FKUJMGDPPLMJGR-UHFFFAOYSA-N"

 Success  registered route 543!

865 0 0 Chan-Lam_coupling_(amination) C2636 "VLTCJSKEHQAUTL-UHFFFAOYSA-N"

reactants =
[283065, 284819]

product = C2636 "VLTCJSKEHQAUTL-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Chan-Lam_coupling_(amination)!

865 1 0 Amine_alkylation C2636 "VLTCJSKEHQAUTL-UHFFFAOYSA-N"

reactants =
[284820]

product = C2636 "VLTCJSKEHQAUTL-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

865 2 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C2636 "VLTCJSKEHQAUTL-UHFFFAOYSA-N"

865 3 0 Amine_alkylation C2636 "VLTCJSKEHQAUTL-UHFFFAOYSA-N"

reactants =
[284822]

product = C2636 "VLTCJSKEHQAUTL-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

865 4 0 Amine_alkylation C2636 "VLTCJSKEHQAUTL-UHFFFAOYSA-N"

reactants =
[284823]

product = C2636 "VLTCJSKEHQAUTL-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

866 0 0 Amidation C28383 "PVHTYTCVYUNLLL-UHFFFAOYSA-N"

 Success  registered route 544!

867 0 0 Amidation C7169 "YIILFKIQHWPXAG-UHFFFAOYSA-N"

 Success  registered route 545!

868 0 0 Sulfonamide_Schotten-Baumann_with_amine_(intermolecular) C7673 "FEWUTFMHYWVVGO-UHFFFAOYSA-N"

reactants =
[284489, 284826]

product = C7673 "FEWUTFMHYWVVGO-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sulfonamide_Schotten-Baumann_with_amine_(intermolecular)!

868 1 0 Formation_of_sulfonamide_from_halide_-_Shavnya_reaction C7673 "FEWUTFMHYWVVGO-UHFFFAOYSA-N"

reactants =
[284490, 284826]

product = C7673 "FEWUTFMHYWVVGO-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Formation_of_sulfonamide_from_halide_-_Shavnya_reaction!

868 2 0 Formation_of_sulfonamide_from_halide_-_Shavnya_reaction C7673 "FEWUTFMHYWVVGO-UHFFFAOYSA-N"

reactants =
[284491, 284826]

product = C7673 "FEWUTFMHYWVVGO-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Formation_of_sulfonamide_from_halide_-_Shavnya_reaction!

868 3 0 Formation_of_sulfonamide_from_halide_-_Shavnya_reaction C7673 "FEWUTFMHYWVVGO-UHFFFAOYSA-N"

reactants =
[284079, 284826]

product = C7673 "FEWUTFMHYWVVGO-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Formation_of_sulfonamide_from_halide_-_Shavnya_reaction!

868 4 0 Sulfonamide_Schotten-Baumann_with_amine_(intermolecular) C7673 "FEWUTFMHYWVVGO-UHFFFAOYSA-N"

reactants =
[284492, 284826]

product = C7673 "FEWUTFMHYWVVGO-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sulfonamide_Schotten-Baumann_with_amine_(intermolecular)!

869 0 0 Amidation C2652 "XANBFXMPGDEVBY-UHFFFAOYSA-N"

 Success  registered route 546!

870 0 0 Amidation C1318 "AXOVECJXLBLXBH-UHFFFAOYSA-N"

 Success  registered route 547!

871 0 0 Amidation C3826 "QENDPRIYXYIRHV-UHFFFAOYSA-N"

 Success  registered route 548!

872 0 0 Amidation C92775 "WYQDXWYIGKTVHX-UHFFFAOYSA-N"

 Success  registered route 549!

873 0 0 Amidation C9910 "AQHJQVUQKSJLJN-UHFFFAOYSA-N"

 Success  registered route 550!

874 0 0 Amine_alkylation C805 "QZNTZLREQHIPTH-UHFFFAOYSA-N"

reactants =
[283759, 284833]

product = C805 "QZNTZLREQHIPTH-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

874 1 0 Amine_alkylation C805 "QZNTZLREQHIPTH-UHFFFAOYSA-N"

reactants =
[283761, 284833]

product = C805 "QZNTZLREQHIPTH-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

874 2 0 Amine_alkylation C805 "QZNTZLREQHIPTH-UHFFFAOYSA-N"

reactants =
[283758, 284833]

product = C805 "QZNTZLREQHIPTH-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

874 3 0 Amine_alkylation C805 "QZNTZLREQHIPTH-UHFFFAOYSA-N"

reactants =
[283760, 284833]

product = C805 "QZNTZLREQHIPTH-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

874 4 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C805 "QZNTZLREQHIPTH-UHFFFAOYSA-N"

 Success  registered route 551!

875 0 0 Petasis-borono_Mannich_reaction C4545 "JSYRTCNAAWDFHA-UHFFFAOYSA-N"

reactants =
[284602, 284834]

product = C4545 "JSYRTCNAAWDFHA-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Petasis-borono_Mannich_reaction!

875 1 0 Petasis-borono_Mannich_reaction C4545 "JSYRTCNAAWDFHA-UHFFFAOYSA-N"

reactants =
[284602, 284835]

product = C4545 "JSYRTCNAAWDFHA-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Petasis-borono_Mannich_reaction!

875 2 0 Amine_alkylation C4545 "JSYRTCNAAWDFHA-UHFFFAOYSA-N"

reactants =
[284836]

product = C4545 "JSYRTCNAAWDFHA-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

875 3 0 Reductive_amination C4545 "JSYRTCNAAWDFHA-UHFFFAOYSA-N"

875 4 0 Amine_alkylation C4545 "JSYRTCNAAWDFHA-UHFFFAOYSA-N"

reactants =
[284838]

product = C4545 "JSYRTCNAAWDFHA-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

876 0 0 Reductive_amination C88601 "GHUWQZDUXFABRG-UHFFFAOYSA-N"

 Success  registered route 552!

877 0 0 Formation_of_urea_from_two_amines C6181 "KPKROVRQPATTCI-UHFFFAOYSA-N"

 Success  registered route 553!

878 0 0 Amidation C38623 "KQFIZQJHMHSRJU-UHFFFAOYSA-N"

 Success  registered route 554!

879 0 0 Amidation C33929 "RQPYZWIDBNQYDN-UHFFFAOYSA-N"

 Success  registered route 555!

880 0 0 Amidation C5358 "PLKRCIBWWXFPQS-UHFFFAOYSA-N"

 Success  registered route 556!

881 0 0 Amidation C8052 "BYSVFNXGWBOSLW-UHFFFAOYSA-N"

 Success  registered route 557!

882 0 0 Amidation C8468 "RDBFNHFBDWYSQG-UHFFFAOYSA-N"

 Success  registered route 558!

883 0 0 Amidation C8923 "TZNQIOOJWDMLNH-UHFFFAOYSA-N"

 Success  registered route 559!

884 0 0 Amidation C28778 "IKGWEUPIBZYKCX-UHFFFAOYSA-N"

 Success  registered route 560!

885 0 0 Amidation C533 "CUBOAIJARPZGGJ-UHFFFAOYSA-N"

 Success  registered route 561!

886 0 0 Amidation C5691 "BWURFTTURAXDKM-UHFFFAOYSA-N"

 Success  registered route 562!

887 0 0 Formation_of_urea_from_two_amines C16890 "KTRXBMCRTROOIW-UHFFFAOYSA-N"

 Success  registered route 563!

888 0 0 Amidation C27893 "BZLSGPYVTJTSHN-UHFFFAOYSA-N"

 Success  registered route 564!

889 0 0 Amidation C93118 "OKCDMJXQKQAOBD-UHFFFAOYSA-N"

 Success  registered route 565!

890 0 0 Amidation C14951 "WNSGNWHGSWFAHB-UHFFFAOYSA-N"

 Success  registered route 566!

891 0 0 Amidation C31471 "HWNMIYOIZLOAOJ-UHFFFAOYSA-N"

 Success  registered route 567!

892 0 0 Amidation C4560 "BSZJDRPOJAAOSY-UHFFFAOYSA-N"

 Success  registered route 568!

893 0 0 Amidation C10821 "GPNVFMKKUMJBLG-UHFFFAOYSA-N"

 Success  registered route 569!

894 0 0 Carboxylic_acid_+_hydrazine_condensation C9575 "DDAYMZHBOWJNFK-UHFFFAOYSA-N"

reactants =
[284276, 284861]

product = C9575 "DDAYMZHBOWJNFK-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Carboxylic_acid_+_hydrazine_condensation!

894 1 0 Amidation C9575 "DDAYMZHBOWJNFK-UHFFFAOYSA-N"

 Success  registered route 570!

895 0 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C12439 "FKTAAXVJSFCNDC-UHFFFAOYSA-N"

 Success  registered route 571!

896 0 0 Amidation C6343 "MTFCVKLEKLKXNT-UHFFFAOYSA-N"

 Success  registered route 572!

897 0 0 Amidation C9132 "IXXWILBFBCPULP-UHFFFAOYSA-N"

 Success  registered route 573!

898 0 0 Sp3-sp2_Suzuki_coupling C8889 "UKIYNEQFJFUCIO-UHFFFAOYSA-N"

 Success  registered route 574!

899 0 0 Reductive_amination C875 "PLRNRTQFDDEAPK-UHFFFAOYSA-N"

 Success  registered route 575!

900 0 0 Amidation C12144 "WRGUXZFLVPHPPA-UHFFFAOYSA-N"

 Success  registered route 576!

901 0 0 Steglich_esterification C5288 "DCWKGBWLMWJEGU-UHFFFAOYSA-N"

 Success  registered route 577!

902 0 0 Alpha_alkylation_of_ketone C4645 "JHPLEUYNZYOKAC-UHFFFAOYSA-N"

reactants =
[283280, 284876]

product = C4645 "JHPLEUYNZYOKAC-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ketone!

902 1 0 N-Boc_deprotection C4645 "JHPLEUYNZYOKAC-UHFFFAOYSA-N"

 Success  registered route 578!

903 0 0 Amidation C3782 "QBKDTAGNELZKNO-UHFFFAOYSA-N"

 Success  registered route 579!

904 0 0 Ester_amidation C23517 "KKPJMJAAGWYOGV-UHFFFAOYSA-N"

 Success  registered route 580!

905 0 0 Amidation C34811 "UWXVEDCEWYGTRJ-UHFFFAOYSA-N"

 Success  registered route 581!

906 0 0 Amidation C15735 "HDCUDRUHFXHSNY-UHFFFAOYSA-N"

 Success  registered route 582!

907 0 0 Amidation C21158 "AJLXANOZRCJDLS-UHFFFAOYSA-N"

 Success  registered route 583!

908 0 0 Amidation C14078 "NBHXHSMIGQMUER-UHFFFAOYSA-N"

 Success  registered route 584!

909 0 0 Formation_of_urea_from_two_amines C84544 "FYRXYDPVISKWNM-UHFFFAOYSA-N"

 Success  registered route 585!

910 0 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C2400 "RAJZPRJBARPLQW-UHFFFAOYSA-N"

 Success  registered route 586!

911 0 0 Amine_alkylation C4528 "BGXAVSVRYXHJHI-UHFFFAOYSA-N"

reactants =
[284889, 284890]

product = C4528 "BGXAVSVRYXHJHI-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

911 1 0 Amine_alkylation C4528 "BGXAVSVRYXHJHI-UHFFFAOYSA-N"

reactants =
[284889, 284891]

product = C4528 "BGXAVSVRYXHJHI-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

911 2 0 Amine_alkylation C4528 "BGXAVSVRYXHJHI-UHFFFAOYSA-N"

reactants =
[284889, 284892]

product = C4528 "BGXAVSVRYXHJHI-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

911 3 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C4528 "BGXAVSVRYXHJHI-UHFFFAOYSA-N"

 Success  registered route 587!

912 0 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C7891 "BVORABRUVNAGOD-UHFFFAOYSA-N"

912 1 0 Amidation C7891 "BVORABRUVNAGOD-UHFFFAOYSA-N"

912 1 1 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C284895 "CPNFHOZZUPCAFI-UHFFFAOYSA-N"

 Success  registered route 588!

913 0 0 Amidation C10535 "XJPJCIMCDCBUDM-UHFFFAOYSA-N"

 Success  registered route 589!

914 0 0 Amidation C27676 "UILMKCCWNFQJCT-UHFFFAOYSA-N"

 Success  registered route 590!

915 0 0 Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide C1811 "KQPUFQLGSXQISW-UHFFFAOYSA-N"

reactants =
[284772, 284900]

product = C1811 "KQPUFQLGSXQISW-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide!

915 1 0 Sp3-sp2_Suzuki_coupling C1811 "KQPUFQLGSXQISW-UHFFFAOYSA-N"

 Success  registered route 591!

916 0 0 Amine_alkylation C2390 "GRCPKGYTKXKWFK-UHFFFAOYSA-N"

reactants =
[283999, 284901]

product = C2390 "GRCPKGYTKXKWFK-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

916 1 0 Amine_alkylation C2390 "GRCPKGYTKXKWFK-UHFFFAOYSA-N"

reactants =
[283810, 284901]

product = C2390 "GRCPKGYTKXKWFK-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

916 2 0 Amine_alkylation C2390 "GRCPKGYTKXKWFK-UHFFFAOYSA-N"

reactants =
[284000, 284901]

product = C2390 "GRCPKGYTKXKWFK-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

916 3 0 Amide_to_amine_reduction C2390 "GRCPKGYTKXKWFK-UHFFFAOYSA-N"

reactants =
[284902]

product = C2390 "GRCPKGYTKXKWFK-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amide_to_amine_reduction!

916 4 0 Amine_alkylation C2390 "GRCPKGYTKXKWFK-UHFFFAOYSA-N"

reactants =
[284901, 284903]

product = C2390 "GRCPKGYTKXKWFK-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

917 0 0 Amidation C1361 "AQILHIUWLDOOHJ-UHFFFAOYSA-N"

 Success  registered route 592!

918 0 0 TEMPO_oxidation C4701 "FINIGGNJPQFVOX-UHFFFAOYSA-N"

reactants =
[284906]

product = C4701 "FINIGGNJPQFVOX-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: TEMPO_oxidation!

918 1 0 Ozonolysis_(intermolecular) C4701 "FINIGGNJPQFVOX-UHFFFAOYSA-N"

reactants =
[284907]

product = C4701 "FINIGGNJPQFVOX-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Ozonolysis_(intermolecular)!

918 2 0 Swern_oxidation C4701 "FINIGGNJPQFVOX-UHFFFAOYSA-N"

reactants =
[284906]

product = C4701 "FINIGGNJPQFVOX-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Swern_oxidation!

918 3 0 Ozonolysis_(intermolecular) C4701 "FINIGGNJPQFVOX-UHFFFAOYSA-N"

reactants =
[284908]

product = C4701 "FINIGGNJPQFVOX-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Ozonolysis_(intermolecular)!

918 4 0 Alpha_alkylation_of_aldehyde C4701 "FINIGGNJPQFVOX-UHFFFAOYSA-N"

reactants =
[283127, 284909]

product = C4701 "FINIGGNJPQFVOX-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_aldehyde!

919 0 0 Amidation C8168 "CTCJLPKYTZKXTA-UHFFFAOYSA-N"

 Success  registered route 593!

920 0 0 Amidation C1417 "DCZHFEWOJXEGST-UHFFFAOYSA-N"

 Success  registered route 594!

921 0 0 Reductive_amination C5378 "BPVACFSEVJXOJC-UHFFFAOYSA-N"

921 1 0 Amide_to_amine_reduction C5378 "BPVACFSEVJXOJC-UHFFFAOYSA-N"

reactants =
[284914]

product = C5378 "BPVACFSEVJXOJC-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amide_to_amine_reduction!

921 2 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C5378 "BPVACFSEVJXOJC-UHFFFAOYSA-N"

921 3 0 Alkene_hydrogenation_(unconjugated) C5378 "BPVACFSEVJXOJC-UHFFFAOYSA-N"

reactants =
[284916]

product = C5378 "BPVACFSEVJXOJC-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alkene_hydrogenation_(unconjugated)!

921 4 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C5378 "BPVACFSEVJXOJC-UHFFFAOYSA-N"

922 0 0 Sp3-sp2_Suzuki_coupling C11486 "FXEFZOMVZBBFDP-UHFFFAOYSA-N"

 Success  registered route 595!

923 0 0 Amidation C26238 "YKUFSMANTRFFSS-UHFFFAOYSA-N"

 Success  registered route 596!

924 0 0 Alpha_alkylation_of_nitriles C19998 "HKXVWCTZHQLBNW-UHFFFAOYSA-N"

reactants =
[283280, 284919]

product = C19998 "HKXVWCTZHQLBNW-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_nitriles!

924 1 0 Formation_of_(thio)hydantoin_from_amine_and_alpha_amino_acid_ester C19998 "HKXVWCTZHQLBNW-UHFFFAOYSA-N"

reactants =
[284920, 284921]

product = C19998 "HKXVWCTZHQLBNW-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Formation_of_(thio)hydantoin_from_amine_and_alpha_amino_acid_ester!

924 2 0 Alpha_alkylation_of_nitriles C19998 "HKXVWCTZHQLBNW-UHFFFAOYSA-N"

reactants =
[283127, 284919]

product = C19998 "HKXVWCTZHQLBNW-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_nitriles!

924 3 0 Alpha_alkylation_of_nitriles C19998 "HKXVWCTZHQLBNW-UHFFFAOYSA-N"

reactants =
[283128, 284919]

product = C19998 "HKXVWCTZHQLBNW-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_nitriles!

924 4 0 Formation_of_(thio)hydantoin_from_amine_and_alpha_amino_acid_ester C19998 "HKXVWCTZHQLBNW-UHFFFAOYSA-N"

reactants =
[284920, 284921]

product = C19998 "HKXVWCTZHQLBNW-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Formation_of_(thio)hydantoin_from_amine_and_alpha_amino_acid_ester!

925 0 0 Amidation C22516 "WUAFTAWKKQKQSG-UHFFFAOYSA-N"

 Success  registered route 597!

926 0 0 Amidation C12016 "XPWBZSZXWGFDON-UHFFFAOYSA-N"

 Success  registered route 598!

927 0 0 Amidation C94714 "JSVZKTIWBIRABG-UHFFFAOYSA-N"

 Success  registered route 599!

928 0 0 Formation_of_urea_from_two_amines C84541 "JYRQIYXJRADILA-UHFFFAOYSA-N"

 Success  registered route 600!

929 0 0 Amidation C82401 "CBVFQNPUAAYSLD-UHFFFAOYSA-N"

 Success  registered route 601!

930 0 0 Minisci_reaction_with_carboxylic_acid_(intermolecular) C7393 "XZMDXLGITMJJAR-UHFFFAOYSA-N"

reactants =
[284929, 284930]

product = C7393 "XZMDXLGITMJJAR-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Minisci_reaction_with_carboxylic_acid_(intermolecular)!

930 1 0 Petasis-borono_Mannich_reaction C7393 "XZMDXLGITMJJAR-UHFFFAOYSA-N"

reactants =
[284602, 284931]

product = C7393 "XZMDXLGITMJJAR-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Petasis-borono_Mannich_reaction!

930 2 0 Amine_alkylation C7393 "XZMDXLGITMJJAR-UHFFFAOYSA-N"

reactants =
[284932]

product = C7393 "XZMDXLGITMJJAR-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

930 3 0 N-Boc_deprotection C7393 "XZMDXLGITMJJAR-UHFFFAOYSA-N"

 Success  registered route 602!

931 0 0 Amidation C21167 "NKBIUPWOQPIFKU-UHFFFAOYSA-N"

 Success  registered route 603!

932 0 0 Amidation C91081 "AJZMAQJSZWQBTD-UHFFFAOYSA-N"

 Success  registered route 604!

933 0 0 N-nucleophilic_aromatic_substitution C12411 "GOIIBLCLDRWXDI-UHFFFAOYSA-N"

 Success  registered route 605!

934 0 0 Amidation C1419 "BYXOCXSSHQOHSD-UHFFFAOYSA-N"

 Success  registered route 606!

935 0 0 Amidation C7147 "ZRXPCXKVGFOFRK-UHFFFAOYSA-N"

 Success  registered route 607!

936 0 0 N-Boc_deprotection C1877 "JUJYNCPRVMVRCV-UHFFFAOYSA-N"

 Success  registered route 608!

937 0 0 Amidation C10215 "FPIYKYLQFSMPTN-UHFFFAOYSA-N"

 Success  registered route 609!

938 0 0 Amidation C4291 "AJQNPQKWWJKQFB-UHFFFAOYSA-N"

 Success  registered route 610!

939 0 0 Amidation C9987 "MQHOJDGABPALRL-UHFFFAOYSA-N"

 Success  registered route 611!

940 0 0 Hydrogenation_of_pyridine C6051 "YDZVKAFTNJTLSL-UHFFFAOYSA-N"

reactants =
[284949]

product = C6051 "YDZVKAFTNJTLSL-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Hydrogenation_of_pyridine!

940 1 0 N-Boc_deprotection C6051 "YDZVKAFTNJTLSL-UHFFFAOYSA-N"

 Success  registered route 612!

941 0 0 Amidation C8437 "HNEOZDURNOEMOY-UHFFFAOYSA-N"

 Success  registered route 613!

942 0 0 Amidation C9817 "QFOVZMCLJFNOLH-UHFFFAOYSA-N"

 Success  registered route 614!

943 0 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C4710 "SUDOFTVBCPEFQK-UHFFFAOYSA-N"

 Success  registered route 615!

944 0 0 Amidation C3516 "FIHUVLYGVBEHSM-UHFFFAOYSA-N"

 Success  registered route 616!

945 0 0 Amide_Schotten-Baumann_with_amine C15029 "OCFFTUGEJZIYTH-UHFFFAOYSA-N"

945 0 1 Carboxylic_acid_to_acid_chloride C284957 "QFZYRYDAWXHSFT-UHFFFAOYSA-N"

reactants =
[284831]

product = C284957 "QFZYRYDAWXHSFT-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Carboxylic_acid_to_acid_chloride!

945 1 0 Ketone/aldehyde_to_difluoro C15029 "OCFFTUGEJZIYTH-UHFFFAOYSA-N"

reactants =
[284958]

product = C15029 "OCFFTUGEJZIYTH-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Ketone/aldehyde_to_difluoro!

945 2 0 Alpha_alkylation_of_ester/amide C15029 "OCFFTUGEJZIYTH-UHFFFAOYSA-N"

reactants =
[284959, 284960]

product = C15029 "OCFFTUGEJZIYTH-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ester/amide!

945 3 0 Alpha_alkylation_of_ester/amide C15029 "OCFFTUGEJZIYTH-UHFFFAOYSA-N"

reactants =
[284960, 284961]

product = C15029 "OCFFTUGEJZIYTH-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ester/amide!

945 4 0 Alpha_alkylation_of_ester/amide C15029 "OCFFTUGEJZIYTH-UHFFFAOYSA-N"

reactants =
[284960, 284962]

product = C15029 "OCFFTUGEJZIYTH-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ester/amide!

946 0 0 Iodo_N-arylation C22809 "LDZSMRRPHYMGJB-UHFFFAOYSA-N"

reactants =
[284963, 284964]

product = C22809 "LDZSMRRPHYMGJB-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Iodo_N-arylation!

946 1 0 Corey-House_synthesis_(intermolecular) C22809 "LDZSMRRPHYMGJB-UHFFFAOYSA-N"

reactants =
[284607, 284965]

product = C22809 "LDZSMRRPHYMGJB-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Corey-House_synthesis_(intermolecular)!

946 2 0 Amidation C22809 "LDZSMRRPHYMGJB-UHFFFAOYSA-N"

 Success  registered route 617!

947 0 0 Amidation C36659 "BMGQAPYAWGCTSL-UHFFFAOYSA-N"

 Success  registered route 618!

948 0 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C2378 "ZWZHRYGYRLXIEQ-UHFFFAOYSA-N"

 Success  registered route 619!

949 0 0 Buchwald-Hartwig_amination C12945 "ZIPKJCBHPHJSDG-UHFFFAOYSA-N"

 Success  registered route 620!

950 0 0 Amidation C34425 "DKGPPHBODADFID-UHFFFAOYSA-N"

 Success  registered route 621!

951 0 0 Amidation C37776 "TXLFUDQYNGTYGY-UHFFFAOYSA-N"

 Success  registered route 622!

952 0 0 Alpha_alkylation_of_ester/amide C10783 "DXNJQCFHVKJTJF-UHFFFAOYSA-N"

reactants =
[284977, 284978]

product = C10783 "DXNJQCFHVKJTJF-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ester/amide!

952 1 0 Amidation C10783 "DXNJQCFHVKJTJF-UHFFFAOYSA-N"

 Success  registered route 623!

953 0 0 Amine_alkylation C2530 "GPGBQKMPCMYFLT-UHFFFAOYSA-N"

reactants =
[284707, 284981]

product = C2530 "GPGBQKMPCMYFLT-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

953 1 0 Chan-Lam_coupling_(amination) C2530 "GPGBQKMPCMYFLT-UHFFFAOYSA-N"

reactants =
[283965, 284982]

product = C2530 "GPGBQKMPCMYFLT-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Chan-Lam_coupling_(amination)!

953 2 0 Amine_alkylation C2530 "GPGBQKMPCMYFLT-UHFFFAOYSA-N"

reactants =
[284981, 284983]

product = C2530 "GPGBQKMPCMYFLT-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

953 3 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C2530 "GPGBQKMPCMYFLT-UHFFFAOYSA-N"

953 3 1 Amine_alkylation C284985 "WYWMKUFXSILPOS-UHFFFAOYSA-N"

reactants =
[282937, 284707]

product = C284985 "WYWMKUFXSILPOS-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

953 4 0 Chan-Lam_coupling_(amination) C2530 "GPGBQKMPCMYFLT-UHFFFAOYSA-N"

reactants =
[283259, 284986]

product = C2530 "GPGBQKMPCMYFLT-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Chan-Lam_coupling_(amination)!

954 0 0 Amidation C29365 "VMRRPEUPZRWAAJ-UHFFFAOYSA-N"

 Success  registered route 624!

955 0 0 Amidation C20158 "QVJOVVVVXHHADP-UHFFFAOYSA-N"

 Success  registered route 625!

956 0 0 Amidation C31914 "ULOXUOOKQMHPDW-UHFFFAOYSA-N"

 Success  registered route 626!

957 0 0 Formation_of_urea_from_two_amines C33243 "ZTMHRCWTNSPQGN-UHFFFAOYSA-N"

 Success  registered route 627!

958 0 0 Sonogashira_coupling C765 "GHIFOCYQWCGZBT-UHFFFAOYSA-N"

reactants =
[283228, 284993]

product = C765 "GHIFOCYQWCGZBT-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sonogashira_coupling!

958 1 0 Wittig_reaction C765 "GHIFOCYQWCGZBT-UHFFFAOYSA-N"

reactants =
[284994, 284995]

product = C765 "GHIFOCYQWCGZBT-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Wittig_reaction!

958 2 0 Stille_coupling C765 "GHIFOCYQWCGZBT-UHFFFAOYSA-N"

reactants =
[283227, 284993]

product = C765 "GHIFOCYQWCGZBT-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Stille_coupling!

958 3 0 Alkyne_TMS_deprotection C765 "GHIFOCYQWCGZBT-UHFFFAOYSA-N"

reactants =
[284996]

product = C765 "GHIFOCYQWCGZBT-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alkyne_TMS_deprotection!

958 4 0 Horner-Wadsworth-Emmons_reaction C765 "GHIFOCYQWCGZBT-UHFFFAOYSA-N"

reactants =
[284994, 284997]

product = C765 "GHIFOCYQWCGZBT-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Horner-Wadsworth-Emmons_reaction!

959 0 0 Sp3-sp2_Macmillan_coupling_with_bromide_(intermolecular) C6116 "NUWLOKGYWJWIQU-UHFFFAOYSA-N"

reactants =
[284998]

product = C6116 "NUWLOKGYWJWIQU-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sp3-sp2_Macmillan_coupling_with_bromide_(intermolecular)!

959 1 0 Sp3-sp2_Macmillan_coupling_with_chloride_(intermolecular) C6116 "NUWLOKGYWJWIQU-UHFFFAOYSA-N"

reactants =
[284999]

product = C6116 "NUWLOKGYWJWIQU-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sp3-sp2_Macmillan_coupling_with_chloride_(intermolecular)!

959 2 0 Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide C6116 "NUWLOKGYWJWIQU-UHFFFAOYSA-N"

reactants =
[285000]

product = C6116 "NUWLOKGYWJWIQU-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide!

959 3 0 Buchwald-Hartwig_amination C6116 "NUWLOKGYWJWIQU-UHFFFAOYSA-N"

959 4 0 Buchwald-Hartwig_amination C6116 "NUWLOKGYWJWIQU-UHFFFAOYSA-N"

960 0 0 Hydrolysis_of_enol_ether C10419 "VABKMYCWOFANPU-UHFFFAOYSA-N"

reactants =
[285003]

product = C10419 "VABKMYCWOFANPU-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Hydrolysis_of_enol_ether!

960 1 0 Hydrolysis_of_enol_ether C10419 "VABKMYCWOFANPU-UHFFFAOYSA-N"

reactants =
[285004]

product = C10419 "VABKMYCWOFANPU-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Hydrolysis_of_enol_ether!

960 2 0 Hydrolysis_of_enol_ether C10419 "VABKMYCWOFANPU-UHFFFAOYSA-N"

reactants =
[285003]

product = C10419 "VABKMYCWOFANPU-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Hydrolysis_of_enol_ether!

960 3 0 Hydrolysis_of_enol_ether C10419 "VABKMYCWOFANPU-UHFFFAOYSA-N"

reactants =
[285004]

product = C10419 "VABKMYCWOFANPU-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Hydrolysis_of_enol_ether!

960 4 0 Sandmeyer_bromination C10419 "VABKMYCWOFANPU-UHFFFAOYSA-N"

reactants =
[285005]

product = C10419 "VABKMYCWOFANPU-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sandmeyer_bromination!

961 0 0 Amidation C5954 "RTIJVGZLLDAVEL-UHFFFAOYSA-N"

 Success  registered route 628!

962 0 0 TEMPO_oxidation C4666 "NRPARTHTHRTTMK-UHFFFAOYSA-N"

reactants =
[285006]

product = C4666 "NRPARTHTHRTTMK-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: TEMPO_oxidation!

962 1 0 Swern_oxidation C4666 "NRPARTHTHRTTMK-UHFFFAOYSA-N"

reactants =
[285006]

product = C4666 "NRPARTHTHRTTMK-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Swern_oxidation!

962 2 0 Ozonolysis_(intermolecular) C4666 "NRPARTHTHRTTMK-UHFFFAOYSA-N"

reactants =
[285007]

product = C4666 "NRPARTHTHRTTMK-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Ozonolysis_(intermolecular)!

962 3 0 Alpha_alkylation_of_aldehyde C4666 "NRPARTHTHRTTMK-UHFFFAOYSA-N"

reactants =
[283280, 285008]

product = C4666 "NRPARTHTHRTTMK-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_aldehyde!

962 4 0 Periodate_cleavage_(intermolecular) C4666 "NRPARTHTHRTTMK-UHFFFAOYSA-N"

reactants =
[285009]

product = C4666 "NRPARTHTHRTTMK-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Periodate_cleavage_(intermolecular)!

963 0 0 Amidation C4928 "FCRUNMPWXPNPMG-UHFFFAOYSA-N"

 Success  registered route 629!

964 0 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C5393 "GCDRJSAGWFOAHE-UHFFFAOYSA-N"

964 1 0 Simmons-Smith_reaction C5393 "GCDRJSAGWFOAHE-UHFFFAOYSA-N"

reactants =
[285013]

product = C5393 "GCDRJSAGWFOAHE-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Simmons-Smith_reaction!

964 2 0 Reductive_amination C5393 "GCDRJSAGWFOAHE-UHFFFAOYSA-N"

964 3 0 Reductive_amination C5393 "GCDRJSAGWFOAHE-UHFFFAOYSA-N"

964 4 0 Reductive_amination C5393 "GCDRJSAGWFOAHE-UHFFFAOYSA-N"

965 0 0 Amidation C5359 "BPAGEGOWFQURHS-UHFFFAOYSA-N"

 Success  registered route 630!

966 0 0 Ketone_from_acid_chloride_(Gilman_reagent,_intermolecular) C2382 "OLHKVAHFSOVKNO-UHFFFAOYSA-N"

reactants =
[285017, 285018]

product = C2382 "OLHKVAHFSOVKNO-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Ketone_from_acid_chloride_(Gilman_reagent,_intermolecular)!

966 1 0 Ethenyl_to_formyl C2382 "OLHKVAHFSOVKNO-UHFFFAOYSA-N"

reactants =
[285019]

product = C2382 "OLHKVAHFSOVKNO-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Ethenyl_to_formyl!

966 2 0 Conjugate_addition_of_organolithium_(Gilman_reagent) C2382 "OLHKVAHFSOVKNO-UHFFFAOYSA-N"

reactants =
[283163, 285020]

product = C2382 "OLHKVAHFSOVKNO-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Conjugate_addition_of_organolithium_(Gilman_reagent)!

966 3 0 Alpha_alkylation_of_ketone C2382 "OLHKVAHFSOVKNO-UHFFFAOYSA-N"

reactants =
[285021, 285022]

product = C2382 "OLHKVAHFSOVKNO-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ketone!

966 4 0 Swern_oxidation C2382 "OLHKVAHFSOVKNO-UHFFFAOYSA-N"

reactants =
[285023]

product = C2382 "OLHKVAHFSOVKNO-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Swern_oxidation!

967 0 0 Buchwald-Hartwig_(thio)etherification C14605 "RAHVMMANICHALQ-UHFFFAOYSA-N"

reactants =
[285024, 285025]

product = C14605 "RAHVMMANICHALQ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Buchwald-Hartwig_(thio)etherification!

967 1 0 Formation_of_urea_from_two_amines C14605 "RAHVMMANICHALQ-UHFFFAOYSA-N"

 Success  registered route 631!

968 0 0 Sulfonamide_Schotten-Baumann_with_amine_(intermolecular) C2063 "ZGUIGBFPAXLLGR-UHFFFAOYSA-N"

reactants =
[283032, 285028]

product = C2063 "ZGUIGBFPAXLLGR-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sulfonamide_Schotten-Baumann_with_amine_(intermolecular)!

968 1 0 Sulfonamide_Schotten-Baumann_with_amine_(intermolecular) C2063 "ZGUIGBFPAXLLGR-UHFFFAOYSA-N"

reactants =
[283032, 285029]

product = C2063 "ZGUIGBFPAXLLGR-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sulfonamide_Schotten-Baumann_with_amine_(intermolecular)!

968 2 0 Formation_of_sulfonamide_from_halide_-_Shavnya_reaction C2063 "ZGUIGBFPAXLLGR-UHFFFAOYSA-N"

reactants =
[283032, 285030]

product = C2063 "ZGUIGBFPAXLLGR-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Formation_of_sulfonamide_from_halide_-_Shavnya_reaction!

968 3 0 Formation_of_sulfonamide_from_boronic_and_amine C2063 "ZGUIGBFPAXLLGR-UHFFFAOYSA-N"

reactants =
[283032, 285031]

product = C2063 "ZGUIGBFPAXLLGR-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Formation_of_sulfonamide_from_boronic_and_amine!

968 4 0 Formation_of_sulfonamide_from_halide_-_Shavnya_reaction C2063 "ZGUIGBFPAXLLGR-UHFFFAOYSA-N"

reactants =
[283032, 285032]

product = C2063 "ZGUIGBFPAXLLGR-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Formation_of_sulfonamide_from_halide_-_Shavnya_reaction!

969 0 0 Amide_to_amine_reduction C9825 "VIDKADKMWCUVEQ-UHFFFAOYSA-N"

reactants =
[285033]

product = C9825 "VIDKADKMWCUVEQ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amide_to_amine_reduction!

970 0 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C8882 "JPWQZFKBNRFGNF-UHFFFAOYSA-N"

 Success  registered route 632!

971 0 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C20148 "GPLKGJZEUOGKRW-UHFFFAOYSA-N"

 Success  registered route 633!

972 0 0 Sulfonamide_Schotten-Baumann_with_amine_(intermolecular) C7653 "NCZWCIZJDPQWNM-UHFFFAOYSA-N"

reactants =
[284489, 285036]

product = C7653 "NCZWCIZJDPQWNM-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sulfonamide_Schotten-Baumann_with_amine_(intermolecular)!

972 1 0 Formation_of_sulfonamide_from_halide_-_Shavnya_reaction C7653 "NCZWCIZJDPQWNM-UHFFFAOYSA-N"

reactants =
[284490, 285036]

product = C7653 "NCZWCIZJDPQWNM-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Formation_of_sulfonamide_from_halide_-_Shavnya_reaction!

972 2 0 Formation_of_sulfonamide_from_halide_-_Shavnya_reaction C7653 "NCZWCIZJDPQWNM-UHFFFAOYSA-N"

reactants =
[284491, 285036]

product = C7653 "NCZWCIZJDPQWNM-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Formation_of_sulfonamide_from_halide_-_Shavnya_reaction!

972 3 0 Formation_of_sulfonamide_from_halide_-_Shavnya_reaction C7653 "NCZWCIZJDPQWNM-UHFFFAOYSA-N"

reactants =
[284079, 285036]

product = C7653 "NCZWCIZJDPQWNM-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Formation_of_sulfonamide_from_halide_-_Shavnya_reaction!

972 4 0 Sulfonamide_Schotten-Baumann_with_amine_(intermolecular) C7653 "NCZWCIZJDPQWNM-UHFFFAOYSA-N"

reactants =
[284492, 285036]

product = C7653 "NCZWCIZJDPQWNM-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sulfonamide_Schotten-Baumann_with_amine_(intermolecular)!

973 0 0 Amidation C7524 "GLYWQGPQWRVUJF-UHFFFAOYSA-N"

 Success  registered route 634!

974 0 0 Hydrogenation_of_pyridine C8585 "BRFFCOVLYYYHTQ-UHFFFAOYSA-N"

 Warning  SMILES changed during compound registration: O=C1CNC(c2cccnc2)=N1 --> O=C1CN=C(c2cccnc2)N1!

reactants =
[14055]

product = C8585 "BRFFCOVLYYYHTQ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Hydrogenation_of_pyridine!

974 1 0 Hydrolysis_of_enol_ether C8585 "BRFFCOVLYYYHTQ-UHFFFAOYSA-N"

reactants =
[285039]

product = C8585 "BRFFCOVLYYYHTQ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Hydrolysis_of_enol_ether!

974 2 0 Hydrolysis_of_enol_ether C8585 "BRFFCOVLYYYHTQ-UHFFFAOYSA-N"

reactants =
[285040]

product = C8585 "BRFFCOVLYYYHTQ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Hydrolysis_of_enol_ether!

974 3 0 N-Tosyl_deprotection C8585 "BRFFCOVLYYYHTQ-UHFFFAOYSA-N"

reactants =
[285041]

product = C8585 "BRFFCOVLYYYHTQ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: N-Tosyl_deprotection!

974 4 0 N-Boc_deprotection C8585 "BRFFCOVLYYYHTQ-UHFFFAOYSA-N"

974 4 1 Hydrolysis_of_enol_ether C285042 "ABMFVNFOVPYPHS-UHFFFAOYSA-N"

reactants =
[285043]

product = C285042 "ABMFVNFOVPYPHS-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Hydrolysis_of_enol_ether!

975 0 0 Amidation C32018 "KFBTYOFOIPCZQH-UHFFFAOYSA-N"

 Success  registered route 635!

976 0 0 Ozonolysis_(intermolecular) C18925 "VAWUEFSAMKXCBU-UHFFFAOYSA-N"

reactants =
[285045]

product = C18925 "VAWUEFSAMKXCBU-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Ozonolysis_(intermolecular)!

976 1 0 Ozonolysis_(intermolecular) C18925 "VAWUEFSAMKXCBU-UHFFFAOYSA-N"

reactants =
[285046]

product = C18925 "VAWUEFSAMKXCBU-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Ozonolysis_(intermolecular)!

976 2 0 Ozonolysis_(intermolecular) C18925 "VAWUEFSAMKXCBU-UHFFFAOYSA-N"

reactants =
[285047]

product = C18925 "VAWUEFSAMKXCBU-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Ozonolysis_(intermolecular)!

976 3 0 Ozonolysis_(intermolecular) C18925 "VAWUEFSAMKXCBU-UHFFFAOYSA-N"

reactants =
[285048]

product = C18925 "VAWUEFSAMKXCBU-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Ozonolysis_(intermolecular)!

976 4 0 Ozonolysis_(intermolecular) C18925 "VAWUEFSAMKXCBU-UHFFFAOYSA-N"

reactants =
[285049]

product = C18925 "VAWUEFSAMKXCBU-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Ozonolysis_(intermolecular)!

977 0 0 Sp3-sp2_Macmillan_coupling_with_bromide_(intermolecular) C9548 "PVLRSSNEEAZVOH-UHFFFAOYSA-N"

reactants =
[283598, 285050]

product = C9548 "PVLRSSNEEAZVOH-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sp3-sp2_Macmillan_coupling_with_bromide_(intermolecular)!

977 1 0 Alpha_alkylation_of_aldehyde C9548 "PVLRSSNEEAZVOH-UHFFFAOYSA-N"

reactants =
[283111, 285051]

product = C9548 "PVLRSSNEEAZVOH-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_aldehyde!

977 2 0 Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide C9548 "PVLRSSNEEAZVOH-UHFFFAOYSA-N"

reactants =
[284286, 285050]

product = C9548 "PVLRSSNEEAZVOH-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide!

977 3 0 TEMPO_oxidation C9548 "PVLRSSNEEAZVOH-UHFFFAOYSA-N"

reactants =
[285052]

product = C9548 "PVLRSSNEEAZVOH-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: TEMPO_oxidation!

977 4 0 Swern_oxidation C9548 "PVLRSSNEEAZVOH-UHFFFAOYSA-N"

reactants =
[285052]

product = C9548 "PVLRSSNEEAZVOH-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Swern_oxidation!

978 0 0 Amidation C7132 "ZYQQDEPLJNFLEF-UHFFFAOYSA-N"

 Success  registered route 636!

979 0 0 Stille_coupling C9539 "ZHAZHKPVEROFLH-UHFFFAOYSA-N"

reactants =
[284354, 285054]

product = C9539 "ZHAZHKPVEROFLH-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Stille_coupling!

979 1 0 Ketone_from_acid_chloride_(Gilman_reagent,_intermolecular) C9539 "ZHAZHKPVEROFLH-UHFFFAOYSA-N"

reactants =
[284607, 285055]

product = C9539 "ZHAZHKPVEROFLH-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Ketone_from_acid_chloride_(Gilman_reagent,_intermolecular)!

979 2 0 Sp2-sp2_Negishi_coupling_(intermolecular) C9539 "ZHAZHKPVEROFLH-UHFFFAOYSA-N"

reactants =
[285056, 285057]

product = C9539 "ZHAZHKPVEROFLH-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sp2-sp2_Negishi_coupling_(intermolecular)!

979 3 0 Stille_coupling C9539 "ZHAZHKPVEROFLH-UHFFFAOYSA-N"

reactants =
[285056, 285058]

product = C9539 "ZHAZHKPVEROFLH-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Stille_coupling!

979 4 0 Stille_coupling C9539 "ZHAZHKPVEROFLH-UHFFFAOYSA-N"

reactants =
[285054, 285058]

product = C9539 "ZHAZHKPVEROFLH-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Stille_coupling!

980 0 0 Ester_amidation C5945 "WKDSMLUYURMGRK-UHFFFAOYSA-N"

980 1 0 N-Ac_deprotection C5945 "WKDSMLUYURMGRK-UHFFFAOYSA-N"

reactants =
[285060]

product = C5945 "WKDSMLUYURMGRK-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: N-Ac_deprotection!

980 2 0 Ester_amidation C5945 "WKDSMLUYURMGRK-UHFFFAOYSA-N"

 Success  registered route 637!

981 0 0 Amidation C5642 "QHGGWPPDZUPZIG-UHFFFAOYSA-N"

 Success  registered route 638!

982 0 0 Hydroxy_to_fluoro C25792 "IMNXQIZMBRQERC-UHFFFAOYSA-N"

reactants =
[285063]

product = C25792 "IMNXQIZMBRQERC-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Hydroxy_to_fluoro!

982 1 0 N-Boc_deprotection C25792 "IMNXQIZMBRQERC-UHFFFAOYSA-N"

982 1 1 Hydroxy_to_fluoro C285064 "BGAMXMDYZDLIQD-UHFFFAOYSA-N"

reactants =
[285065]

product = C285064 "BGAMXMDYZDLIQD-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Hydroxy_to_fluoro!

982 2 0 Alkene_hydrogenation_(unconjugated) C25792 "IMNXQIZMBRQERC-UHFFFAOYSA-N"

reactants =
[285066]

product = C25792 "IMNXQIZMBRQERC-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alkene_hydrogenation_(unconjugated)!

982 3 0 N-Cbz_deprotection C25792 "IMNXQIZMBRQERC-UHFFFAOYSA-N"

reactants =
[285067]

product = C25792 "IMNXQIZMBRQERC-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: N-Cbz_deprotection!

982 4 0 N-Fmoc_deprotection C25792 "IMNXQIZMBRQERC-UHFFFAOYSA-N"

reactants =
[285068]

product = C25792 "IMNXQIZMBRQERC-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: N-Fmoc_deprotection!

983 0 0 Amidation C10832 "XNDSEHCZSDWHNY-UHFFFAOYSA-N"

 Success  registered route 639!

984 0 0 Amidation C32383 "YZSYVMJRAIIIQD-UHFFFAOYSA-N"

 Success  registered route 640!

985 0 0 Hydrogenation_of_benzene C20648 "ROOFZUAQKFMYKH-UHFFFAOYSA-N"

reactants =
[285071]

product = C20648 "ROOFZUAQKFMYKH-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Hydrogenation_of_benzene!

985 1 0 Amidation C20648 "ROOFZUAQKFMYKH-UHFFFAOYSA-N"

985 1 1 Copper-catalyzed_1,3-azide-alkyne_Huisgen_cycloaddition C285072 "WRLJNQUFRWDKAG-UHFFFAOYSA-N"

reactants =
[285073, 285074]

product = C285072 "WRLJNQUFRWDKAG-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Copper-catalyzed_1,3-azide-alkyne_Huisgen_cycloaddition!

985 2 0 Amine_alkylation C20648 "ROOFZUAQKFMYKH-UHFFFAOYSA-N"

reactants =
[285075, 285076]

product = C20648 "ROOFZUAQKFMYKH-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

985 3 0 Copper-catalyzed_1,3-azide-alkyne_Huisgen_cycloaddition C20648 "ROOFZUAQKFMYKH-UHFFFAOYSA-N"

reactants =
[285074, 285077]

product = C20648 "ROOFZUAQKFMYKH-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Copper-catalyzed_1,3-azide-alkyne_Huisgen_cycloaddition!

985 4 0 Beckmann_rearrangement C20648 "ROOFZUAQKFMYKH-UHFFFAOYSA-N"

reactants =
[285078]

product = C20648 "ROOFZUAQKFMYKH-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Beckmann_rearrangement!

986 0 0 Formation_of_urea_from_two_amines C10686 "OVGXOABIOXLLGL-UHFFFAOYSA-N"

 Success  registered route 641!

987 0 0 Amidation C1384 "BYDQDZLINGKUEV-UHFFFAOYSA-N"

 Success  registered route 642!

988 0 0 Amidation C7067 "WYVCMIYBKYUXJW-UHFFFAOYSA-N"

 Success  registered route 643!

989 0 0 Minisci_reaction_with_carboxylic_acid_(intermolecular) C14773 "MIZHWJKJFPMAHV-UHFFFAOYSA-N"

reactants =
[283318, 285083]

product = C14773 "MIZHWJKJFPMAHV-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Minisci_reaction_with_carboxylic_acid_(intermolecular)!

989 1 0 Swern_oxidation C14773 "MIZHWJKJFPMAHV-UHFFFAOYSA-N"

reactants =
[285084]

product = C14773 "MIZHWJKJFPMAHV-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Swern_oxidation!

989 2 0 Oxa-Michael_addition C14773 "MIZHWJKJFPMAHV-UHFFFAOYSA-N"

reactants =
[285085]

product = C14773 "MIZHWJKJFPMAHV-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Oxa-Michael_addition!

989 3 0 Dess-Martin_oxidation C14773 "MIZHWJKJFPMAHV-UHFFFAOYSA-N"

reactants =
[285084]

product = C14773 "MIZHWJKJFPMAHV-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Dess-Martin_oxidation!

989 4 0 Ozonolysis_(intermolecular) C14773 "MIZHWJKJFPMAHV-UHFFFAOYSA-N"

reactants =
[285086]

product = C14773 "MIZHWJKJFPMAHV-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Ozonolysis_(intermolecular)!

990 0 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C9822 "OTKRQPFMRSSARE-UHFFFAOYSA-N"

 Success  registered route 644!

991 0 0 Amidation C1685 "DWCBDTDREZNSGU-UHFFFAOYSA-N"

 Success  registered route 645!

992 0 0 Nucleophilic_substitution_with_thiol C10527 "REXDXSHVJSWRIX-UHFFFAOYSA-N"

reactants =
[285091, 285092]

product = C10527 "REXDXSHVJSWRIX-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Nucleophilic_substitution_with_thiol!

992 1 0 Nucleophilic_substitution_with_thioamide C10527 "REXDXSHVJSWRIX-UHFFFAOYSA-N"

 Warning  SMILES changed during compound registration: NC(=O)CSc1n[nH]c(=S)s1 --> NC(=O)CSc1nnc(S)s1!

reactants =
[285091, 285093]

product = C10527 "REXDXSHVJSWRIX-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Nucleophilic_substitution_with_thioamide!

992 2 0 Nucleophilic_substitution_with_thiol C10527 "REXDXSHVJSWRIX-UHFFFAOYSA-N"

reactants =
[285091, 285093]

product = C10527 "REXDXSHVJSWRIX-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Nucleophilic_substitution_with_thiol!

992 3 0 Nucleophilic_substitution_with_thioamide C10527 "REXDXSHVJSWRIX-UHFFFAOYSA-N"

 Warning  SMILES changed during compound registration: NC(=O)CSc1n[nH]c(=S)s1 --> NC(=O)CSc1nnc(S)s1!

reactants =
[285091, 285092]

product = C10527 "REXDXSHVJSWRIX-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Nucleophilic_substitution_with_thioamide!

992 4 0 Alpha_alkylation_of_ester/amide C10527 "REXDXSHVJSWRIX-UHFFFAOYSA-N"

reactants =
[283127, 285094]

product = C10527 "REXDXSHVJSWRIX-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ester/amide!

993 0 0 Amidation C10854 "GTOHXODIXBECHG-UHFFFAOYSA-N"

 Success  registered route 646!

994 0 0 Sp2-sp2_Suzuki_coupling C4781 "JGHMMIULJFZDBA-UHFFFAOYSA-N"

 Success  registered route 647!

995 0 0 Reductive_amination C7499 "PUIPAYFHRQTOOJ-UHFFFAOYSA-N"

 Success  registered route 648!

996 0 0 Amine_alkylation C795 "JVDTWAMFTGWSKS-UHFFFAOYSA-N"

reactants =
[284504, 284510]

product = C795 "JVDTWAMFTGWSKS-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

996 1 0 Amine_alkylation C795 "JVDTWAMFTGWSKS-UHFFFAOYSA-N"

reactants =
[284504, 285099]

product = C795 "JVDTWAMFTGWSKS-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

996 2 0 Amine_alkylation C795 "JVDTWAMFTGWSKS-UHFFFAOYSA-N"

reactants =
[284504, 285100]

product = C795 "JVDTWAMFTGWSKS-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

996 3 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C795 "JVDTWAMFTGWSKS-UHFFFAOYSA-N"

 Success  registered route 649!

997 0 0 Amidation C1406 "ZHEXKJJYJURADK-UHFFFAOYSA-N"

 Success  registered route 650!

998 0 0 Amidation C6064 "UEVNEQDSWATJMO-UHFFFAOYSA-N"

 Success  registered route 651!

999 0 0 Amidation C3900 "CKUSNPGQZQJLGY-UHFFFAOYSA-N"

 Success  registered route 652!

1000 0 0 Amidation C15654 "AQXSEQFJAMXZOT-UHFFFAOYSA-N"

 Success  registered route 653!

1001 0 0 Isocyanate_to_urea C10683 "FDTBFBNGCRTYIH-UHFFFAOYSA-N"

reactants =
[285080, 285107]

product = C10683 "FDTBFBNGCRTYIH-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Isocyanate_to_urea!

1001 1 0 Formation_of_urea_from_two_amines C10683 "FDTBFBNGCRTYIH-UHFFFAOYSA-N"

 Success  registered route 654!

1002 0 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C5363 "NPDDPCJWLVZMCA-UHFFFAOYSA-N"

1002 1 0 Reductive_amination C5363 "NPDDPCJWLVZMCA-UHFFFAOYSA-N"

1002 2 0 Reductive_amination C5363 "NPDDPCJWLVZMCA-UHFFFAOYSA-N"

1002 3 0 Amine_alkylation C5363 "NPDDPCJWLVZMCA-UHFFFAOYSA-N"

reactants =
[285111]

product = C5363 "NPDDPCJWLVZMCA-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

1002 4 0 Reductive_amination C5363 "NPDDPCJWLVZMCA-UHFFFAOYSA-N"

1003 0 0 Amidation C7819 "TVNFUCRFFLGUGI-UHFFFAOYSA-N"

 Success  registered route 655!

1004 0 0 Amidation C10847 "IERXOVUPWKOWSK-UHFFFAOYSA-N"

 Success  registered route 656!

1005 0 0 Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide C6286 "ANSXQAALPGNGJP-UHFFFAOYSA-N"

reactants =
[284537, 284753]

product = C6286 "ANSXQAALPGNGJP-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide!

1005 1 0 Amine_alkylation C6286 "ANSXQAALPGNGJP-UHFFFAOYSA-N"

reactants =
[285114]

product = C6286 "ANSXQAALPGNGJP-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

1005 2 0 Amine_alkylation C6286 "ANSXQAALPGNGJP-UHFFFAOYSA-N"

reactants =
[285115]

product = C6286 "ANSXQAALPGNGJP-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

1005 3 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C6286 "ANSXQAALPGNGJP-UHFFFAOYSA-N"

1005 4 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C6286 "ANSXQAALPGNGJP-UHFFFAOYSA-N"

1006 0 0 Amidation C11204 "FXORYDYYSQMRDK-UHFFFAOYSA-N"

 Success  registered route 657!

1007 0 0 Amidation C11605 "LCCXSDXPWBGFAI-UHFFFAOYSA-N"

 Success  registered route 658!

1008 0 0 Amidation C7529 "FFAXPTHKURGIBP-UHFFFAOYSA-N"

 Success  registered route 659!

1009 0 0 Chlorination_of_alcohol C23812 "AYNLZEGPVWLBPE-UHFFFAOYSA-N"

reactants =
[285122]

product = C23812 "AYNLZEGPVWLBPE-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Chlorination_of_alcohol!

1009 1 0 Amidation C23812 "AYNLZEGPVWLBPE-UHFFFAOYSA-N"

 Success  registered route 660!

1010 0 0 Sp3-sp2_Suzuki_coupling C6258 "KVNQCSIGNRPHHM-UHFFFAOYSA-N"

 Success  registered route 661!

1011 0 0 Amidation C39872 "KOQQXKYWQMMEBA-UHFFFAOYSA-N"

 Success  registered route 662!

1012 0 0 Amidation C40659 "UTNOHUVGODOWSF-UHFFFAOYSA-N"

 Success  registered route 663!

1013 0 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C32012 "PFPNMXGZZXVBGJ-UHFFFAOYSA-N"

 Success  registered route 664!

1014 0 0 Amidation C7104 "PHEZTEPOSWGUSQ-UHFFFAOYSA-N"

 Success  registered route 665!

1015 0 0 Amidation C17883 "PJDNNFWSTSASFT-UHFFFAOYSA-N"

 Success  registered route 666!

1016 0 0 Amidation C7839 "HJVFTZYOPBWDAT-UHFFFAOYSA-N"

 Success  registered route 667!

1017 0 0 Chan-Lam_coupling_of_amides,_sulfonamides,_and_imides C4080 "GSETXYYFSRYMOU-UHFFFAOYSA-N"

reactants =
[283259, 285131]

product = C4080 "GSETXYYFSRYMOU-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Chan-Lam_coupling_of_amides,_sulfonamides,_and_imides!

1017 1 0 Mannich_reaction C4080 "GSETXYYFSRYMOU-UHFFFAOYSA-N"

reactants =
[285132, 285133]

product = C4080 "GSETXYYFSRYMOU-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Mannich_reaction!

1017 2 0 Amidation C4080 "GSETXYYFSRYMOU-UHFFFAOYSA-N"

1017 2 1 Amidation C285135 "SCQVUSDTMFWRGB-UHFFFAOYSA-N"

 Success  registered route 668!

1018 0 0 Amidation C9976 "YNVJQHLIXVUGMB-UHFFFAOYSA-N"

 Success  registered route 669!

1019 0 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C2897 "GZBXXUHFYNAKIR-UHFFFAOYSA-N"

 Success  registered route 670!

1020 0 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C18185 "ZVYACGZLRYTKSB-UHFFFAOYSA-N"

 Success  registered route 671!

1021 0 0 Buchwald-Hartwig_amination C12979 "DJUNTQQNFNJVRB-UHFFFAOYSA-N"

 Success  registered route 672!

1022 0 0 Amine_alkylation C2040 "NVQPTGDZIZQWGQ-UHFFFAOYSA-N"

reactants =
[283760, 285142]

product = C2040 "NVQPTGDZIZQWGQ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

1022 1 0 Amine_alkylation C2040 "NVQPTGDZIZQWGQ-UHFFFAOYSA-N"

reactants =
[283761, 285142]

product = C2040 "NVQPTGDZIZQWGQ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

1022 2 0 Amine_alkylation C2040 "NVQPTGDZIZQWGQ-UHFFFAOYSA-N"

reactants =
[283758, 285142]

product = C2040 "NVQPTGDZIZQWGQ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

1022 3 0 Amine_alkylation C2040 "NVQPTGDZIZQWGQ-UHFFFAOYSA-N"

reactants =
[283759, 285142]

product = C2040 "NVQPTGDZIZQWGQ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

1022 4 0 Amine_alkylation C2040 "NVQPTGDZIZQWGQ-UHFFFAOYSA-N"

reactants =
[285142, 285143]

product = C2040 "NVQPTGDZIZQWGQ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

1023 0 0 Amidation C24830 "IJHPSABDUDUHER-UHFFFAOYSA-N"

 Success  registered route 673!

1024 0 0 Amidation C5962 "NVJZJVXTLOAEJS-UHFFFAOYSA-N"

 Success  registered route 674!

1025 0 0 Amidation C4100 "AYBAPWWBZFMAJL-UHFFFAOYSA-N"

 Success  registered route 675!

1026 0 0 Amidation C10784 "WRGJLDZMMZTWSM-UHFFFAOYSA-N"

 Success  registered route 676!

1027 0 0 Formation_of_urea_from_two_amines C1509 "PYHYHSZBLFIGJJ-UHFFFAOYSA-N"

 Success  registered route 677!

1028 0 0 Isocyanate_to_urea C5539 "JCTAJWPEQHCFMI-UHFFFAOYSA-N"

reactants =
[285149, 285150]

product = C5539 "JCTAJWPEQHCFMI-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Isocyanate_to_urea!

1028 1 0 Formation_of_urea_from_two_amines C5539 "JCTAJWPEQHCFMI-UHFFFAOYSA-N"

 Success  registered route 678!

1029 0 0 Alpha_alkylation_of_ketone C18173 "AYEOHXFBHHOWPD-UHFFFAOYSA-N"

reactants =
[18206, 285151]

product = C18173 "AYEOHXFBHHOWPD-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ketone!

1029 1 0 Friedel-Crafts_acylation C18173 "AYEOHXFBHHOWPD-UHFFFAOYSA-N"

reactants =
[284139, 285152]

product = C18173 "AYEOHXFBHHOWPD-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Friedel-Crafts_acylation!

1029 2 0 Alpha_alkylation_of_ketone C18173 "AYEOHXFBHHOWPD-UHFFFAOYSA-N"

reactants =
[18206, 285153]

product = C18173 "AYEOHXFBHHOWPD-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ketone!

1029 3 0 Alpha_alkylation_of_ketone C18173 "AYEOHXFBHHOWPD-UHFFFAOYSA-N"

reactants =
[18206, 285154]

product = C18173 "AYEOHXFBHHOWPD-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ketone!

1029 4 0 Conjugate_addition_of_Grignard_(Gilman_reagents) C18173 "AYEOHXFBHHOWPD-UHFFFAOYSA-N"

reactants =
[284632, 285155]

product = C18173 "AYEOHXFBHHOWPD-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Conjugate_addition_of_Grignard_(Gilman_reagents)!

1030 0 0 Alpha_alkylation_of_nitriles C8145 "IFQJCHDGIKNYJR-UHFFFAOYSA-N"

reactants =
[285156, 285157]

product = C8145 "IFQJCHDGIKNYJR-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_nitriles!

1030 1 0 Alpha_alkylation_of_nitriles C8145 "IFQJCHDGIKNYJR-UHFFFAOYSA-N"

reactants =
[285156, 285158]

product = C8145 "IFQJCHDGIKNYJR-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_nitriles!

1030 2 0 Formation_of_carbamate_from_amine_and_alcohol C8145 "IFQJCHDGIKNYJR-UHFFFAOYSA-N"

reactants =
[284612, 285159]

product = C8145 "IFQJCHDGIKNYJR-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Formation_of_carbamate_from_amine_and_alcohol!

1030 3 0 Alpha_alkylation_of_nitriles C8145 "IFQJCHDGIKNYJR-UHFFFAOYSA-N"

reactants =
[283127, 285160]

product = C8145 "IFQJCHDGIKNYJR-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_nitriles!

1030 4 0 Alpha_alkylation_of_nitriles C8145 "IFQJCHDGIKNYJR-UHFFFAOYSA-N"

reactants =
[283280, 285160]

product = C8145 "IFQJCHDGIKNYJR-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_nitriles!

1031 0 0 Steglich_esterification C42149 "TZTAWMMMGCPPTP-UHFFFAOYSA-N"

 Success  registered route 679!

1032 0 0 Amidation C31998 "TZIRKKPJSKSKFV-UHFFFAOYSA-N"

 Success  registered route 680!

1033 0 0 Formation_of_sulfonamide_from_halide_-_Shavnya_reaction C7655 "OLNCYPXEOMYYNS-UHFFFAOYSA-N"

reactants =
[284490, 285165]

product = C7655 "OLNCYPXEOMYYNS-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Formation_of_sulfonamide_from_halide_-_Shavnya_reaction!

1033 1 0 Formation_of_sulfonamide_from_halide_-_Shavnya_reaction C7655 "OLNCYPXEOMYYNS-UHFFFAOYSA-N"

reactants =
[284079, 285165]

product = C7655 "OLNCYPXEOMYYNS-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Formation_of_sulfonamide_from_halide_-_Shavnya_reaction!

1033 2 0 Sulfonamide_Schotten-Baumann_with_amine_(intermolecular) C7655 "OLNCYPXEOMYYNS-UHFFFAOYSA-N"

reactants =
[284489, 285165]

product = C7655 "OLNCYPXEOMYYNS-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sulfonamide_Schotten-Baumann_with_amine_(intermolecular)!

1033 3 0 Formation_of_sulfonamide_from_halide_-_Shavnya_reaction C7655 "OLNCYPXEOMYYNS-UHFFFAOYSA-N"

reactants =
[284491, 285165]

product = C7655 "OLNCYPXEOMYYNS-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Formation_of_sulfonamide_from_halide_-_Shavnya_reaction!

1033 4 0 Sulfonamide_Schotten-Baumann_with_amine_(intermolecular) C7655 "OLNCYPXEOMYYNS-UHFFFAOYSA-N"

reactants =
[284492, 285165]

product = C7655 "OLNCYPXEOMYYNS-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sulfonamide_Schotten-Baumann_with_amine_(intermolecular)!

1034 0 0 Nucleophilic_substitution_with_thiol C13648 "AJANJNXHNMDIHZ-UHFFFAOYSA-N"

reactants =
[285166, 285167]

product = C13648 "AJANJNXHNMDIHZ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Nucleophilic_substitution_with_thiol!

1034 1 0 Nucleophilic_substitution_with_thiol C13648 "AJANJNXHNMDIHZ-UHFFFAOYSA-N"

reactants =
[285166, 285168]

product = C13648 "AJANJNXHNMDIHZ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Nucleophilic_substitution_with_thiol!

1034 2 0 Alpha_alkylation_of_ketone C13648 "AJANJNXHNMDIHZ-UHFFFAOYSA-N"

reactants =
[283280, 285169]

product = C13648 "AJANJNXHNMDIHZ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ketone!

1034 3 0 Alpha_alkylation_of_ketone C13648 "AJANJNXHNMDIHZ-UHFFFAOYSA-N"

reactants =
[283127, 285169]

product = C13648 "AJANJNXHNMDIHZ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ketone!

1034 4 0 Nucleophilic_substitution_with_thiol C13648 "AJANJNXHNMDIHZ-UHFFFAOYSA-N"

reactants =
[285166, 285170]

product = C13648 "AJANJNXHNMDIHZ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Nucleophilic_substitution_with_thiol!

1035 0 0 Formation_of_urea_from_two_amines C40316 "JLLXGDVGXITSBH-UHFFFAOYSA-N"

 Success  registered route 681!

1036 0 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C5407 "DVLVUUCTVLQLBO-UHFFFAOYSA-N"

1036 1 0 Alkene_hydrogenation_(unconjugated) C5407 "DVLVUUCTVLQLBO-UHFFFAOYSA-N"

reactants =
[285174]

product = C5407 "DVLVUUCTVLQLBO-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alkene_hydrogenation_(unconjugated)!

1036 2 0 Alkene_hydrogenation_(unconjugated) C5407 "DVLVUUCTVLQLBO-UHFFFAOYSA-N"

reactants =
[285175]

product = C5407 "DVLVUUCTVLQLBO-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alkene_hydrogenation_(unconjugated)!

1036 3 0 Amide_to_amine_reduction C5407 "DVLVUUCTVLQLBO-UHFFFAOYSA-N"

reactants =
[9223]

product = C5407 "DVLVUUCTVLQLBO-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amide_to_amine_reduction!

1036 4 0 Amide_to_amine_reduction C5407 "DVLVUUCTVLQLBO-UHFFFAOYSA-N"

reactants =
[9228]

product = C5407 "DVLVUUCTVLQLBO-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amide_to_amine_reduction!

1037 0 0 Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide C6050 "TWMBIPLWGSZODL-UHFFFAOYSA-N"

reactants =
[285176]

product = C6050 "TWMBIPLWGSZODL-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide!

1037 1 0 N-Boc_deprotection C6050 "TWMBIPLWGSZODL-UHFFFAOYSA-N"

 Success  registered route 682!

1038 0 0 Sp3-sp2_Suzuki_coupling C1807 "ZGJPKOODEIMJSO-UHFFFAOYSA-N"

 Success  registered route 683!

1039 0 0 Amidation C11248 "WZIGSCUCYLFSGJ-UHFFFAOYSA-N"

 Success  registered route 684!

1040 0 0 Amidation C40319 "WFPMJUJXZODHSD-UHFFFAOYSA-N"

 Success  registered route 685!

1041 0 0 Amidation C3470 "FXGFNCCXOGIGTL-UHFFFAOYSA-N"

 Success  registered route 686!

1042 0 0 Amidation C4684 "UIVUJIQVOXNKGD-UHFFFAOYSA-N"

 Success  registered route 687!

1043 0 0 Amidation C12356 "RZWWAVWMGNUJKM-UHFFFAOYSA-N"

 Success  registered route 688!

1044 0 0 Amidation C30433 "ICXYMBBPUHNCID-UHFFFAOYSA-N"

 Success  registered route 689!

1045 0 0 Williamson_ether_synthesis C43016 "CYHXIECXBFJELE-UHFFFAOYSA-N"

 Success  registered route 690!

1046 0 0 Amidation C7182 "IBTBUYIARLWWHM-UHFFFAOYSA-N"

 Success  registered route 691!

1047 0 0 Amine_alkylation C5396 "WEQDPGNEWZPZRD-UHFFFAOYSA-N"

reactants =
[284456, 285190]

product = C5396 "WEQDPGNEWZPZRD-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

1047 1 0 Amine_alkylation C5396 "WEQDPGNEWZPZRD-UHFFFAOYSA-N"

reactants =
[284455, 285190]

product = C5396 "WEQDPGNEWZPZRD-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

1047 2 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C5396 "WEQDPGNEWZPZRD-UHFFFAOYSA-N"

 Success  registered route 692!

1048 0 0 Alpha_alkylation_of_ketone C2416 "QLHWJOTYGUXPGV-UHFFFAOYSA-N"

reactants =
[282993, 285192]

product = C2416 "QLHWJOTYGUXPGV-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ketone!

1048 1 0 Alpha_alkylation_of_ketone C2416 "QLHWJOTYGUXPGV-UHFFFAOYSA-N"

reactants =
[283165, 285192]

product = C2416 "QLHWJOTYGUXPGV-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ketone!

1048 2 0 Alpha_alkylation_of_ketone C2416 "QLHWJOTYGUXPGV-UHFFFAOYSA-N"

reactants =
[283114, 285192]

product = C2416 "QLHWJOTYGUXPGV-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ketone!

1048 3 0 Alpha_alkylation_of_ketone C2416 "QLHWJOTYGUXPGV-UHFFFAOYSA-N"

reactants =
[285193]

product = C2416 "QLHWJOTYGUXPGV-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ketone!

1048 4 0 Alpha_alkylation_of_ketone C2416 "QLHWJOTYGUXPGV-UHFFFAOYSA-N"

reactants =
[285194]

product = C2416 "QLHWJOTYGUXPGV-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ketone!

1049 0 0 N-nucleophilic_aromatic_substitution C7443 "KVIFGEJVMMIWBY-UHFFFAOYSA-N"

 Success  registered route 693!

1050 0 0 Amidation C12352 "OEOUTLNRPVGOPE-UHFFFAOYSA-N"

 Success  registered route 694!

1051 0 0 Formation_of_sulfonamide_from_halide_-_Shavnya_reaction C7587 "ZWKQUCJFDUBTGP-UHFFFAOYSA-N"

reactants =
[284454, 284490]

product = C7587 "ZWKQUCJFDUBTGP-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Formation_of_sulfonamide_from_halide_-_Shavnya_reaction!

1051 1 0 Aziridine_+_amine_coupling C7587 "ZWKQUCJFDUBTGP-UHFFFAOYSA-N"

reactants =
[284080, 285198]

product = C7587 "ZWKQUCJFDUBTGP-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Aziridine_+_amine_coupling!

1051 2 0 Formation_of_sulfonamide_from_halide_-_Shavnya_reaction C7587 "ZWKQUCJFDUBTGP-UHFFFAOYSA-N"

reactants =
[284079, 284454]

product = C7587 "ZWKQUCJFDUBTGP-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Formation_of_sulfonamide_from_halide_-_Shavnya_reaction!

1051 3 0 Formation_of_sulfonamide_from_halide_-_Shavnya_reaction C7587 "ZWKQUCJFDUBTGP-UHFFFAOYSA-N"

reactants =
[284454, 284491]

product = C7587 "ZWKQUCJFDUBTGP-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Formation_of_sulfonamide_from_halide_-_Shavnya_reaction!

1051 4 0 Corey-House_synthesis_(intermolecular) C7587 "ZWKQUCJFDUBTGP-UHFFFAOYSA-N"

reactants =
[284607, 285199]

product = C7587 "ZWKQUCJFDUBTGP-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Corey-House_synthesis_(intermolecular)!

1052 0 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C2409 "PFPJWHGWJHUTES-UHFFFAOYSA-N"

 Success  registered route 695!

1053 0 0 Amidation C8484 "YCCKCVPWORBAJK-UHFFFAOYSA-N"

 Success  registered route 696!

1054 0 0 Formation_of_sulfonamide_from_halide_-_Shavnya_reaction C498 "BVXIXHZBAAESKN-UHFFFAOYSA-N"

reactants =
[284721, 285203]

product = C498 "BVXIXHZBAAESKN-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Formation_of_sulfonamide_from_halide_-_Shavnya_reaction!

1054 1 0 Formation_of_sulfonamide_from_halide_-_Shavnya_reaction C498 "BVXIXHZBAAESKN-UHFFFAOYSA-N"

reactants =
[284720, 285203]

product = C498 "BVXIXHZBAAESKN-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Formation_of_sulfonamide_from_halide_-_Shavnya_reaction!

1054 2 0 Formation_of_sulfonamide_from_halide_-_Shavnya_reaction C498 "BVXIXHZBAAESKN-UHFFFAOYSA-N"

reactants =
[284722, 285203]

product = C498 "BVXIXHZBAAESKN-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Formation_of_sulfonamide_from_halide_-_Shavnya_reaction!

1054 3 0 N-Boc_deprotection C498 "BVXIXHZBAAESKN-UHFFFAOYSA-N"

1054 3 1 Sulfonamide_Schotten-Baumann_with_amine_(intermolecular) C285204 "HUMHLIGBYFSDQG-UHFFFAOYSA-N"

reactants =
[284723, 285205]

product = C285204 "HUMHLIGBYFSDQG-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sulfonamide_Schotten-Baumann_with_amine_(intermolecular)!

1054 4 0 N-Boc_deprotection C498 "BVXIXHZBAAESKN-UHFFFAOYSA-N"

1054 4 1 Formation_of_sulfonamide_from_halide_-_Shavnya_reaction C285204 "HUMHLIGBYFSDQG-UHFFFAOYSA-N"

reactants =
[284721, 285205]

product = C285204 "HUMHLIGBYFSDQG-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Formation_of_sulfonamide_from_halide_-_Shavnya_reaction!

1055 0 0 Alpha_alkylation_of_ketone C4670 "VLIIKHOBTSPATL-UHFFFAOYSA-N"

reactants =
[285206]

product = C4670 "VLIIKHOBTSPATL-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ketone!

1055 1 0 Alpha_alkylation_of_ketone C4670 "VLIIKHOBTSPATL-UHFFFAOYSA-N"

reactants =
[285207]

product = C4670 "VLIIKHOBTSPATL-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ketone!

1055 2 0 Alpha_alkylation_of_ketone C4670 "VLIIKHOBTSPATL-UHFFFAOYSA-N"

reactants =
[283280, 285208]

product = C4670 "VLIIKHOBTSPATL-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ketone!

1055 3 0 Alpha_alkylation_of_ketone C4670 "VLIIKHOBTSPATL-UHFFFAOYSA-N"

reactants =
[285209]

product = C4670 "VLIIKHOBTSPATL-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ketone!

1055 4 0 Alpha_alkylation_of_ketone C4670 "VLIIKHOBTSPATL-UHFFFAOYSA-N"

reactants =
[285206]

product = C4670 "VLIIKHOBTSPATL-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ketone!

1056 0 0 Amidation C1682 "WPHZCKRFPCKMPN-UHFFFAOYSA-N"

 Success  registered route 697!

1057 0 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C2617 "BFAIKMGDZZASRD-UHFFFAOYSA-N"

 Success  registered route 698!

1058 0 0 Amidation C26592 "ZHAMFANYGUBSHC-UHFFFAOYSA-N"

 Success  registered route 699!

1059 0 0 Amidation C8054 "IXMDEIPJYFZEHY-UHFFFAOYSA-N"

 Success  registered route 700!

1060 0 0 Amine_alkylation C5397 "ULBBXWVIXXPSOD-UHFFFAOYSA-N"

reactants =
[283965, 285215]

product = C5397 "ULBBXWVIXXPSOD-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

1060 1 0 Amine_alkylation C5397 "ULBBXWVIXXPSOD-UHFFFAOYSA-N"

reactants =
[283965, 284809]

product = C5397 "ULBBXWVIXXPSOD-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

1060 2 0 Amine_alkylation C5397 "ULBBXWVIXXPSOD-UHFFFAOYSA-N"

reactants =
[283965, 285216]

product = C5397 "ULBBXWVIXXPSOD-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

1060 3 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C5397 "ULBBXWVIXXPSOD-UHFFFAOYSA-N"

 Success  registered route 701!

1061 0 0 Amidation C21294 "UGSIBURWRIDDTK-UHFFFAOYSA-N"

 Success  registered route 702!

1062 0 0 Amidation C8866 "SATYTGVRESMOJT-UHFFFAOYSA-N"

 Success  registered route 703!

1063 0 0 Formation_of_1,3-dithiolanes C722 "AXNCOQBNSRCGQR-UHFFFAOYSA-N"

reactants =
[285221]

product = C722 "AXNCOQBNSRCGQR-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Formation_of_1,3-dithiolanes!

1063 1 0 Nucleophilic_substitution_with_thiol C722 "AXNCOQBNSRCGQR-UHFFFAOYSA-N"

reactants =
[285222]

product = C722 "AXNCOQBNSRCGQR-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Nucleophilic_substitution_with_thiol!

1063 2 0 Corey-House_synthesis_(intermolecular) C722 "AXNCOQBNSRCGQR-UHFFFAOYSA-N"

reactants =
[285223, 285224]

product = C722 "AXNCOQBNSRCGQR-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Corey-House_synthesis_(intermolecular)!

1063 3 0 Nucleophilic_substitution_with_thiol C722 "AXNCOQBNSRCGQR-UHFFFAOYSA-N"

reactants =
[285225]

product = C722 "AXNCOQBNSRCGQR-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Nucleophilic_substitution_with_thiol!

1063 4 0 Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide C722 "AXNCOQBNSRCGQR-UHFFFAOYSA-N"

reactants =
[284789, 285226]

product = C722 "AXNCOQBNSRCGQR-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide!

1064 0 0 Formation_of_urea_from_two_amines C44440 "RVXGWTPTIOJIRD-UHFFFAOYSA-N"

 Success  registered route 704!

1065 0 0 Steglich_esterification C31867 "YZDMAFVUISHMFV-UHFFFAOYSA-N"

 Success  registered route 705!

1066 0 0 Amidation C8059 "OEOCKEJGVCIITQ-UHFFFAOYSA-N"

 Success  registered route 706!

1067 0 0 Amidation C1602 "WCJVNOFYGXYGFG-UHFFFAOYSA-N"

 Success  registered route 707!

1068 0 0 Alpha_alkylation_of_ketone C2407 "ZHKWVPSCOFOVKQ-UHFFFAOYSA-N"

reactants =
[284510, 285232]

product = C2407 "ZHKWVPSCOFOVKQ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ketone!

1068 1 0 N-Boc_deprotection C2407 "ZHKWVPSCOFOVKQ-UHFFFAOYSA-N"

 Success  registered route 708!

1069 0 0 Amidation C26601 "VUSCGEMVKVOGIF-UHFFFAOYSA-N"

 Success  registered route 709!

1070 0 0 Amidation C16455 "RMEDOQBOVLJYDX-UHFFFAOYSA-N"

 Success  registered route 710!

1071 0 0 Amidation C15985 "BPUIRSFWYLCZDK-UHFFFAOYSA-N"

 Success  registered route 711!

1072 0 0 Nucleophilic_substitution_with_thioamide C10627 "YFNRJWQADGKRAX-UHFFFAOYSA-N"

reactants =
[285238, 285239]

product = C10627 "YFNRJWQADGKRAX-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Nucleophilic_substitution_with_thioamide!

1072 1 0 Nucleophilic_substitution_with_thiol C10627 "YFNRJWQADGKRAX-UHFFFAOYSA-N"

 Warning  SMILES changed during compound registration: Sc1ncco1 --> S=c1[nH]cco1!

reactants =
[285238, 285240]

product = C10627 "YFNRJWQADGKRAX-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Nucleophilic_substitution_with_thiol!

1072 2 0 Nucleophilic_substitution_with_thioamide C10627 "YFNRJWQADGKRAX-UHFFFAOYSA-N"

reactants =
[285238, 285240]

product = C10627 "YFNRJWQADGKRAX-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Nucleophilic_substitution_with_thioamide!

1072 3 0 Nucleophilic_substitution_with_thiol C10627 "YFNRJWQADGKRAX-UHFFFAOYSA-N"

 Warning  SMILES changed during compound registration: Sc1ncco1 --> S=c1[nH]cco1!

reactants =
[285238, 285239]

product = C10627 "YFNRJWQADGKRAX-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Nucleophilic_substitution_with_thiol!

1072 4 0 Nucleophilic_substitution_with_thioamide C10627 "YFNRJWQADGKRAX-UHFFFAOYSA-N"

reactants =
[285238, 285241]

product = C10627 "YFNRJWQADGKRAX-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Nucleophilic_substitution_with_thioamide!

1073 0 0 Nucleophilic_substitution_with_thioamide C31899 "JNIRJKWCZGUUML-UHFFFAOYSA-N"

reactants =
[285242, 285243]

product = C31899 "JNIRJKWCZGUUML-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Nucleophilic_substitution_with_thioamide!

1073 1 0 Ester_amidation C31899 "JNIRJKWCZGUUML-UHFFFAOYSA-N"

 Success  registered route 712!

1074 0 0 Steglich_esterification C13918 "FZXVNLASEWYDBT-UHFFFAOYSA-N"

 Success  registered route 713!

1075 0 0 Amidation C30751 "ILEMUDAQJVYUBR-UHFFFAOYSA-N"

 Success  registered route 714!

1076 0 0 Amidation C2306 "KYJVTOFXJSRGMR-UHFFFAOYSA-N"

 Success  registered route 715!

1077 0 0 Ester_amidation C10439 "OOKCZDOQBFPXBA-UHFFFAOYSA-N"

 Success  registered route 716!

1078 0 0 Reductive_amination C82705 "IMAPXTOLBMFUCR-UHFFFAOYSA-N"

 Success  registered route 717!

1079 0 0 Steglich_esterification C678 "JMKABZRQVLZKMP-UHFFFAOYSA-N"

 Success  registered route 718!

1080 0 0 Amidation C22847 "UWKMOLXBPRPLBM-UHFFFAOYSA-N"

 Success  registered route 719!

1081 0 0 Amidation C9975 "QLSUFWUEOGJURT-UHFFFAOYSA-N"

 Success  registered route 720!

1082 0 0 Amidation C13863 "OOBPFSHUNCZUBY-UHFFFAOYSA-N"

 Success  registered route 721!

1083 0 0 Amidation C8416 "IEDUUXRRBWHCQW-UHFFFAOYSA-N"

 Success  registered route 722!

1084 0 0 Ester_amidation C6131 "LXVIPPHHTAYJIW-UHFFFAOYSA-N"

 Success  registered route 723!

1085 0 0 Amidation C1382 "VURFZHBQCFSQNK-UHFFFAOYSA-N"

 Success  registered route 724!

1086 0 0 Amidation C1401 "OEFMQFVOHCBHLP-UHFFFAOYSA-N"

 Success  registered route 725!

1087 0 0 Amidation C3788 "HEZOJSXHYOLCRB-UHFFFAOYSA-N"

 Success  registered route 726!

1088 0 0 Amidation C6658 "NFHSLKKDIQNRKX-UHFFFAOYSA-N"

 Success  registered route 727!

1089 0 0 Swern_oxidation C10400 "CMUPJBQGBXLKHY-UHFFFAOYSA-N"

reactants =
[285266]

product = C10400 "CMUPJBQGBXLKHY-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Swern_oxidation!

1089 1 0 Reductive_amination C10400 "CMUPJBQGBXLKHY-UHFFFAOYSA-N"

1089 2 0 Buchwald-Hartwig_amination C10400 "CMUPJBQGBXLKHY-UHFFFAOYSA-N"

1089 3 0 Krapcho_decarboxylation C10400 "CMUPJBQGBXLKHY-UHFFFAOYSA-N"

reactants =
[285269]

product = C10400 "CMUPJBQGBXLKHY-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Krapcho_decarboxylation!

1089 4 0 Alpha_alkylation_of_ketone C10400 "CMUPJBQGBXLKHY-UHFFFAOYSA-N"

reactants =
[285270, 285271]

product = C10400 "CMUPJBQGBXLKHY-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ketone!

1090 0 0 Amidation C2073 "BNTNXENXQWHSKP-UHFFFAOYSA-N"

 Success  registered route 728!

1091 0 0 Amidation C28573 "QUJOMQBGHHSWRI-UHFFFAOYSA-N"

 Success  registered route 729!

1092 0 0 Petasis-borono_Mannich_reaction C1281 "GFYOTNKFYIETKD-UHFFFAOYSA-N"

reactants =
[285276, 285277]

product = C1281 "GFYOTNKFYIETKD-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Petasis-borono_Mannich_reaction!

1092 1 0 Sp3-sp2_Suzuki_coupling C1281 "GFYOTNKFYIETKD-UHFFFAOYSA-N"

1092 2 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C1281 "GFYOTNKFYIETKD-UHFFFAOYSA-N"

1092 3 0 Reductive_amination C1281 "GFYOTNKFYIETKD-UHFFFAOYSA-N"

1092 4 0 Sp3-sp2_Suzuki_coupling C1281 "GFYOTNKFYIETKD-UHFFFAOYSA-N"

1093 0 0 Amidation C15352 "LIVRICROYPTWRS-UHFFFAOYSA-N"

 Success  registered route 730!

1094 0 0 Buchwald-Hartwig_amination C6100 "ZUVLOAOUUWQFOU-UHFFFAOYSA-N"

 Success  registered route 731!

1095 0 0 Sp3-sp2_Suzuki_coupling C4756 "MSOXWHJHAGZIKH-UHFFFAOYSA-N"

 Success  registered route 732!

1096 0 0 Amidation C82527 "GHOYRUSNPCRDIR-UHFFFAOYSA-N"

 Success  registered route 733!

1097 0 0 Amidation C15476 "USRDLWXXPHNKBB-UHFFFAOYSA-N"

 Success  registered route 734!

1098 0 0 Amidation C10874 "ITCVEUCTWLRDPC-UHFFFAOYSA-N"

 Success  registered route 735!

1099 0 0 Amidation C5997 "BIBIWDDCLSQUGA-UHFFFAOYSA-N"

 Success  registered route 736!

1100 0 0 Amidation C899 "FZVASHCIYDDMFL-UHFFFAOYSA-N"

 Success  registered route 737!

1101 0 0 Amidation C6632 "XXCNYTHYAPNDQY-UHFFFAOYSA-N"

 Success  registered route 738!

1102 0 0 Hydrogenation_of_benzene C6093 "LEXQPYMCTMZRQM-UHFFFAOYSA-N"

reactants =
[285294]

product = C6093 "LEXQPYMCTMZRQM-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Hydrogenation_of_benzene!

1102 1 0 Sp3-sp2_Macmillan_coupling_with_bromide_(intermolecular) C6093 "LEXQPYMCTMZRQM-UHFFFAOYSA-N"

reactants =
[285295]

product = C6093 "LEXQPYMCTMZRQM-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sp3-sp2_Macmillan_coupling_with_bromide_(intermolecular)!

1102 2 0 Sp3-sp2_Macmillan_coupling_with_chloride_(intermolecular) C6093 "LEXQPYMCTMZRQM-UHFFFAOYSA-N"

reactants =
[285296]

product = C6093 "LEXQPYMCTMZRQM-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sp3-sp2_Macmillan_coupling_with_chloride_(intermolecular)!

1102 3 0 Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide C6093 "LEXQPYMCTMZRQM-UHFFFAOYSA-N"

reactants =
[285297]

product = C6093 "LEXQPYMCTMZRQM-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide!

1102 4 0 Reductive_amination C6093 "LEXQPYMCTMZRQM-UHFFFAOYSA-N"

1103 0 0 Amidation C15402 "HGUKBOHHMVWXGD-UHFFFAOYSA-N"

 Success  registered route 739!

1104 0 0 Amidation C1603 "YUGVDPXJICVPLB-UHFFFAOYSA-N"

 Success  registered route 740!

1105 0 0 Amidation C3542 "OTENLVGMSKIYLZ-UHFFFAOYSA-N"

 Success  registered route 741!

1106 0 0 Amidation C1360 "QNCXQWQUBKXTSX-UHFFFAOYSA-N"

 Success  registered route 742!

1107 0 0 Amidation C947 "ZUUHCJUCTFFCMF-UHFFFAOYSA-N"

 Success  registered route 743!

1108 0 0 Amidation C83456 "YSMNEIYXJLPLOA-UHFFFAOYSA-N"

 Success  registered route 744!

1109 0 0 Passerini_reaction C20634 "YAKIUUAPXQUGEU-UHFFFAOYSA-N"

reactants =
[283156, 285305, 285306]

product = C20634 "YAKIUUAPXQUGEU-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Passerini_reaction!

1109 1 0 Ester_amidation C20634 "YAKIUUAPXQUGEU-UHFFFAOYSA-N"

1109 2 0 Pinner_reaction_(carboxylate_ester) C20634 "YAKIUUAPXQUGEU-UHFFFAOYSA-N"

reactants =
[285309, 285310]

product = C20634 "YAKIUUAPXQUGEU-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Pinner_reaction_(carboxylate_ester)!

1109 3 0 Amidation C20634 "YAKIUUAPXQUGEU-UHFFFAOYSA-N"

 Success  registered route 745!

1110 0 0 N-Cbz_deprotection C8146 "QNWXUKIQSJVNRS-UHFFFAOYSA-N"

reactants =
[285312]

product = C8146 "QNWXUKIQSJVNRS-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: N-Cbz_deprotection!

1110 1 0 Hydrogenation_of_pyridine C8146 "QNWXUKIQSJVNRS-UHFFFAOYSA-N"

reactants =
[285313]

product = C8146 "QNWXUKIQSJVNRS-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Hydrogenation_of_pyridine!

1110 2 0 Amide_to_amine_reduction C8146 "QNWXUKIQSJVNRS-UHFFFAOYSA-N"

reactants =
[285314]

product = C8146 "QNWXUKIQSJVNRS-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amide_to_amine_reduction!

1110 3 0 N-Boc_deprotection C8146 "QNWXUKIQSJVNRS-UHFFFAOYSA-N"

1110 3 1 Sulfonamide_Schotten-Baumann_with_amine_(intermolecular) C285315 "BFNHTXDALLFMHS-UHFFFAOYSA-N"

reactants =
[285316, 285317]

product = C285315 "BFNHTXDALLFMHS-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sulfonamide_Schotten-Baumann_with_amine_(intermolecular)!

1110 4 0 N-Fmoc_deprotection C8146 "QNWXUKIQSJVNRS-UHFFFAOYSA-N"

reactants =
[285318]

product = C8146 "QNWXUKIQSJVNRS-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: N-Fmoc_deprotection!

1111 0 0 Amidation C85390 "SAYPJXMWJADRCE-UHFFFAOYSA-N"

 Success  registered route 746!

1112 0 0 Amine_alkylation C5638 "MCFMRUUMBUBRGV-UHFFFAOYSA-N"

reactants =
[12, 285321]

product = C5638 "MCFMRUUMBUBRGV-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

1112 1 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C5638 "MCFMRUUMBUBRGV-UHFFFAOYSA-N"

 Success  registered route 747!

1113 0 0 Sp3-sp2_Macmillan_coupling_with_chloride_(intermolecular) C14499 "BYVHTZLWXASNFG-UHFFFAOYSA-N"

reactants =
[285323]

product = C14499 "BYVHTZLWXASNFG-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sp3-sp2_Macmillan_coupling_with_chloride_(intermolecular)!

1113 1 0 Sp3-sp2_Macmillan_coupling_with_bromide_(intermolecular) C14499 "BYVHTZLWXASNFG-UHFFFAOYSA-N"

reactants =
[285324]

product = C14499 "BYVHTZLWXASNFG-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sp3-sp2_Macmillan_coupling_with_bromide_(intermolecular)!

1113 2 0 Sp3-sp2_Macmillan_coupling_with_chloride_(intermolecular) C14499 "BYVHTZLWXASNFG-UHFFFAOYSA-N"

reactants =
[285323]

product = C14499 "BYVHTZLWXASNFG-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sp3-sp2_Macmillan_coupling_with_chloride_(intermolecular)!

1113 3 0 Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide C14499 "BYVHTZLWXASNFG-UHFFFAOYSA-N"

reactants =
[285325]

product = C14499 "BYVHTZLWXASNFG-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide!

1113 4 0 Sp3-sp2_Macmillan_coupling_with_bromide_(intermolecular) C14499 "BYVHTZLWXASNFG-UHFFFAOYSA-N"

reactants =
[285324]

product = C14499 "BYVHTZLWXASNFG-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sp3-sp2_Macmillan_coupling_with_bromide_(intermolecular)!

1114 0 0 Alpha_alkylation_of_ester/amide C1305 "WPLGLYZQTMZENA-UHFFFAOYSA-N"

reactants =
[284046, 285326]

product = C1305 "WPLGLYZQTMZENA-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ester/amide!

1114 1 0 Amidation C1305 "WPLGLYZQTMZENA-UHFFFAOYSA-N"

 Success  registered route 748!

1115 0 0 Amidation C39794 "MVAWIACTJXPSAP-UHFFFAOYSA-N"

 Success  registered route 749!

1116 0 0 Amidation C15069 "KNQXNDJGVDPOSN-UHFFFAOYSA-N"

 Success  registered route 750!

1117 0 0 Amidation C7115 "UGMVKJPKQZMZKU-UHFFFAOYSA-N"

 Success  registered route 751!

1118 0 0 Amidation C32415 "ROBQLCHSXQDWEG-UHFFFAOYSA-N"

 Success  registered route 752!

1119 0 0 Amidation C1142 "JWMDCIUJPJCIMA-UHFFFAOYSA-N"

 Success  registered route 753!

1120 0 0 Amidation C14910 "ZNTOHSLRMARLLO-UHFFFAOYSA-N"

 Success  registered route 754!

1121 0 0 Hydroxy_to_fluoro C2413 "YNRBPEHVWJFOKW-UHFFFAOYSA-N"

reactants =
[285337]

product = C2413 "YNRBPEHVWJFOKW-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Hydroxy_to_fluoro!

1121 1 0 N-Boc_deprotection C2413 "YNRBPEHVWJFOKW-UHFFFAOYSA-N"

1121 1 1 Hydroxy_to_fluoro C285338 "VPVFFWQDRMRDJD-UHFFFAOYSA-N"

reactants =
[285339]

product = C285338 "VPVFFWQDRMRDJD-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Hydroxy_to_fluoro!

1121 2 0 Amide_to_amine_reduction C2413 "YNRBPEHVWJFOKW-UHFFFAOYSA-N"

reactants =
[285340]

product = C2413 "YNRBPEHVWJFOKW-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amide_to_amine_reduction!

1121 3 0 N-TFA_deprotection C2413 "YNRBPEHVWJFOKW-UHFFFAOYSA-N"

reactants =
[285341]

product = C2413 "YNRBPEHVWJFOKW-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: N-TFA_deprotection!

1121 4 0 N-Tosyl_deprotection C2413 "YNRBPEHVWJFOKW-UHFFFAOYSA-N"

reactants =
[285342]

product = C2413 "YNRBPEHVWJFOKW-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: N-Tosyl_deprotection!

1122 0 0 Amidation C8876 "ZGJROAZBUZCTHO-UHFFFAOYSA-N"

 Success  registered route 755!

1123 0 0 Amidation C4769 "URQCIPKMHTUWBP-UHFFFAOYSA-N"

 Success  registered route 756!

1124 0 0 Formation_of_sulfonamide_from_halide_-_Shavnya_reaction C7596 "HMFFHCKOIQTSMA-UHFFFAOYSA-N"

reactants =
[284490, 284698]

product = C7596 "HMFFHCKOIQTSMA-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Formation_of_sulfonamide_from_halide_-_Shavnya_reaction!

1124 1 0 Formation_of_sulfonamide_from_halide_-_Shavnya_reaction C7596 "HMFFHCKOIQTSMA-UHFFFAOYSA-N"

reactants =
[284079, 284698]

product = C7596 "HMFFHCKOIQTSMA-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Formation_of_sulfonamide_from_halide_-_Shavnya_reaction!

1124 2 0 Formation_of_sulfonamide_from_halide_-_Shavnya_reaction C7596 "HMFFHCKOIQTSMA-UHFFFAOYSA-N"

reactants =
[284491, 284698]

product = C7596 "HMFFHCKOIQTSMA-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Formation_of_sulfonamide_from_halide_-_Shavnya_reaction!

1124 3 0 Corey-House_synthesis_(intermolecular) C7596 "HMFFHCKOIQTSMA-UHFFFAOYSA-N"

reactants =
[284607, 285346]

product = C7596 "HMFFHCKOIQTSMA-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Corey-House_synthesis_(intermolecular)!

1124 4 0 Corey-House_synthesis_(intermolecular) C7596 "HMFFHCKOIQTSMA-UHFFFAOYSA-N"

reactants =
[284607, 285347]

product = C7596 "HMFFHCKOIQTSMA-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Corey-House_synthesis_(intermolecular)!

1125 0 0 Mannich_reaction C3419 "OBYGXQCROQSNDR-UHFFFAOYSA-N"

reactants =
[285132, 285348]

product = C3419 "OBYGXQCROQSNDR-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Mannich_reaction!

1125 1 0 Amidation C3419 "OBYGXQCROQSNDR-UHFFFAOYSA-N"

 Success  registered route 757!

1126 0 0 Amidation C84716 "BGLQMBYCJQNPGY-UHFFFAOYSA-N"

 Success  registered route 758!

1127 0 0 Amidation C8426 "JRLTZXBVYPPMPH-UHFFFAOYSA-N"

 Success  registered route 759!

1128 0 0 Amidation C18433 "NDFBKSVVKUASCT-UHFFFAOYSA-N"

 Success  registered route 760!

1129 0 0 Amidation C2365 "AOQJBHHWKYZXFO-UHFFFAOYSA-N"

1129 0 1 Amidation C285353 "PATIEKXWSXORFG-UHFFFAOYSA-N"

 Success  registered route 761!

1130 0 0 Amidation C10575 "GFTCXYDTVIIUSE-UHFFFAOYSA-N"

 Success  registered route 762!

1131 0 0 Amidation C5151 "AKWDCTOUIAETMB-UHFFFAOYSA-N"

 Success  registered route 763!

1132 0 0 Amidation C35516 "ZCLPDSDKUWWASP-UHFFFAOYSA-N"

 Success  registered route 764!

1133 0 0 Amidation C79657 "DURBHPZRTCPDPC-UHFFFAOYSA-N"

 Success  registered route 765!

1134 0 0 Sp3-sp2_Macmillan_coupling_with_bromide_(intermolecular) C7455 "BUOXSSFHPANDGR-UHFFFAOYSA-N"

reactants =
[285360, 285361]

product = C7455 "BUOXSSFHPANDGR-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sp3-sp2_Macmillan_coupling_with_bromide_(intermolecular)!

1134 1 0 Van_Leusen_oxazole_synthesis C7455 "BUOXSSFHPANDGR-UHFFFAOYSA-N"

reactants =
[283755, 285362]

product = C7455 "BUOXSSFHPANDGR-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Van_Leusen_oxazole_synthesis!

1134 2 0 Sp3-sp2_Suzuki_coupling C7455 "BUOXSSFHPANDGR-UHFFFAOYSA-N"

 Success  registered route 766!

1135 0 0 Sp2-sp2_Suzuki_coupling C82790 "WGPOVBVNNQSGMO-UHFFFAOYSA-N"

 Success  registered route 767!

1136 0 0 Petasis-borono_Mannich_reaction C5666 "UMKQGKPJZAJAOK-UHFFFAOYSA-N"

reactants =
[283111, 283722, 285367]

product = C5666 "UMKQGKPJZAJAOK-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Petasis-borono_Mannich_reaction!

1136 1 0 Amine_alkylation C5666 "UMKQGKPJZAJAOK-UHFFFAOYSA-N"

reactants =
[285368, 285369]

product = C5666 "UMKQGKPJZAJAOK-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

1136 2 0 Reductive_amination C5666 "UMKQGKPJZAJAOK-UHFFFAOYSA-N"

 Success  registered route 768!

1137 0 0 Amidation C1366 "AZDQXSSEMYQDTA-UHFFFAOYSA-N"

 Success  registered route 769!

1138 0 0 Amidation C14701 "DZZJAVFDEJKWKN-UHFFFAOYSA-N"

 Success  registered route 770!

1139 0 0 Amidation C5958 "JHIZANCYCGQYNV-UHFFFAOYSA-N"

 Success  registered route 771!

1140 0 0 Reductive_amination C41445 "TTZBCFDUPZCDLF-UHFFFAOYSA-N"

 Success  registered route 772!

1141 0 0 Reductive_amination C9826 "TVKHXLKOZGSFPX-UHFFFAOYSA-N"

 Success  registered route 773!

1142 0 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C6036 "JAFBAXAMVALFBL-UHFFFAOYSA-N"

 Success  registered route 774!

1143 0 0 Amidation C1349 "FGJOWJHHEOWVGK-UHFFFAOYSA-N"

 Success  registered route 775!

1144 0 0 Sp3-sp2_Suzuki_coupling C31965 "IHIYXEORUGHWBE-UHFFFAOYSA-N"

1144 1 0 Swern_oxidation C31965 "IHIYXEORUGHWBE-UHFFFAOYSA-N"

reactants =
[285381]

product = C31965 "IHIYXEORUGHWBE-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Swern_oxidation!

1144 2 0 Buchwald-Hartwig_amination C31965 "IHIYXEORUGHWBE-UHFFFAOYSA-N"

1144 3 0 Alpha_alkylation_of_ketone C31965 "IHIYXEORUGHWBE-UHFFFAOYSA-N"

reactants =
[283280, 285383]

product = C31965 "IHIYXEORUGHWBE-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ketone!

1144 4 0 N-Boc_deprotection C31965 "IHIYXEORUGHWBE-UHFFFAOYSA-N"

 Success  registered route 776!

1145 0 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C2631 "MDGFSWJANWKXMW-UHFFFAOYSA-N"

 Success  registered route 777!

1146 0 0 Amidation C9840 "BMFYZDOZZIDDSD-UHFFFAOYSA-N"

 Success  registered route 778!

1147 0 0 Amidation C33915 "ZJMRYSAATNYSCO-UHFFFAOYSA-N"

 Success  registered route 779!

1148 0 0 Amidation C1359 "REBHPYHCNJHMBG-UHFFFAOYSA-N"

 Success  registered route 780!

1149 0 0 Sp3-sp2_Suzuki_coupling C12023 "BGTHUWNKRWKQLH-UHFFFAOYSA-N"

 Success  registered route 781!

1150 0 0 Amidation C8031 "KPKZQXXJAPWOPZ-UHFFFAOYSA-N"

 Success  registered route 782!

1151 0 0 Isocyanate_to_urea C43738 "OLOCMQZJQFEPLN-UHFFFAOYSA-N"

reactants =
[285391, 285392]

product = C43738 "OLOCMQZJQFEPLN-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Isocyanate_to_urea!

1151 1 0 Formation_of_urea_from_two_amines C43738 "OLOCMQZJQFEPLN-UHFFFAOYSA-N"

 Success  registered route 783!

1152 0 0 Amidation C8874 "QEGXPACMNFTTCL-UHFFFAOYSA-N"

 Success  registered route 784!

1153 0 0 Amidation C2344 "REDBGCCRMBTLLG-UHFFFAOYSA-N"

 Success  registered route 785!

1154 0 0 Amidation C5444 "FCBNDCMPKDFMCI-UHFFFAOYSA-N"

 Success  registered route 786!

1155 0 0 Amine_alkylation C8853 "HMWULAZTFKYULC-UHFFFAOYSA-N"

reactants =
[283761, 284243]

product = C8853 "HMWULAZTFKYULC-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

1155 1 0 Amine_alkylation C8853 "HMWULAZTFKYULC-UHFFFAOYSA-N"

reactants =
[283758, 284243]

product = C8853 "HMWULAZTFKYULC-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

1155 2 0 Amine_alkylation C8853 "HMWULAZTFKYULC-UHFFFAOYSA-N"

reactants =
[283759, 284243]

product = C8853 "HMWULAZTFKYULC-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

1155 3 0 Amine_alkylation C8853 "HMWULAZTFKYULC-UHFFFAOYSA-N"

reactants =
[283760, 284243]

product = C8853 "HMWULAZTFKYULC-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

1155 4 0 Reductive_amination C8853 "HMWULAZTFKYULC-UHFFFAOYSA-N"

 Success  registered route 787!

1156 0 0 Corey-House_synthesis_(intermolecular) C9904 "UCRHKGUMOXDCDY-UHFFFAOYSA-N"

reactants =
[285399, 285400]

product = C9904 "UCRHKGUMOXDCDY-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Corey-House_synthesis_(intermolecular)!

1156 1 0 Amine_alkylation C9904 "UCRHKGUMOXDCDY-UHFFFAOYSA-N"

reactants =
[283965, 285401]

product = C9904 "UCRHKGUMOXDCDY-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

1156 2 0 Corey-House_synthesis_(intermolecular) C9904 "UCRHKGUMOXDCDY-UHFFFAOYSA-N"

reactants =
[285399, 285400]

product = C9904 "UCRHKGUMOXDCDY-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Corey-House_synthesis_(intermolecular)!

1156 3 0 Amine_alkylation C9904 "UCRHKGUMOXDCDY-UHFFFAOYSA-N"

reactants =
[283965, 285402]

product = C9904 "UCRHKGUMOXDCDY-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

1156 4 0 Corey-House_synthesis_(intermolecular) C9904 "UCRHKGUMOXDCDY-UHFFFAOYSA-N"

reactants =
[285399, 285400]

product = C9904 "UCRHKGUMOXDCDY-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Corey-House_synthesis_(intermolecular)!

1157 0 0 Sp3-sp2_Suzuki_coupling C3260 "WYESEHOBLJZBFR-UHFFFAOYSA-N"

 Success  registered route 788!

1158 0 0 Sp3-sp2_Suzuki_coupling C3300 "ZSLFMECWUGWMJH-UHFFFAOYSA-N"

 Success  registered route 789!

1159 0 0 Steglich_esterification C5645 "FDDRMMFQTUMLQU-UHFFFAOYSA-N"

 Success  registered route 790!

1160 0 0 Amidation C2404 "MZHCZVDDNWLPPV-UHFFFAOYSA-N"

 Success  registered route 791!

1161 0 0 Aziridine_+_amine_coupling C7461 "AIXXEJFHVOHRFJ-UHFFFAOYSA-N"

reactants =
[285407, 285408]

product = C7461 "AIXXEJFHVOHRFJ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Aziridine_+_amine_coupling!

1161 1 0 Amidation C7461 "AIXXEJFHVOHRFJ-UHFFFAOYSA-N"

 Success  registered route 792!

1162 0 0 N-nucleophilic_aromatic_substitution C712 "YOAMNICQXAJQJO-UHFFFAOYSA-N"

 Success  registered route 793!

1163 0 0 Amidation C10704 "CYLXWSNDBHUDSS-UHFFFAOYSA-N"

 Success  registered route 794!

1164 0 0 Amidation C16329 "YGPOMGOFWDKROT-UHFFFAOYSA-N"

 Warning  SMILES changed during compound registration: CC(NC(=O)c1cc[nH]n1)C1CNC1 --> CC(NC(=O)c1ccn[nH]1)C1CNC1!

 Success  registered route 795!

1165 0 0 Amidation C29152 "RHLZBBZPBAUQBC-UHFFFAOYSA-N"

 Success  registered route 796!

1166 0 0 Amidation C22223 "ZFTJJBVPUXZCMY-UHFFFAOYSA-N"

 Success  registered route 797!

1167 0 0 Amidation C9207 "RHQJYRUFYUHRDN-UHFFFAOYSA-N"

1167 1 0 Ester_amidation C9207 "RHQJYRUFYUHRDN-UHFFFAOYSA-N"

1167 2 0 Ester_amidation C9207 "RHQJYRUFYUHRDN-UHFFFAOYSA-N"

1167 3 0 Krapcho_decarboxylation C9207 "RHQJYRUFYUHRDN-UHFFFAOYSA-N"

reactants =
[285419]

product = C9207 "RHQJYRUFYUHRDN-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Krapcho_decarboxylation!

1167 4 0 Krapcho_decarboxylation C9207 "RHQJYRUFYUHRDN-UHFFFAOYSA-N"

reactants =
[285420]

product = C9207 "RHQJYRUFYUHRDN-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Krapcho_decarboxylation!

1168 0 0 Formation_of_urea_from_two_amines C8906 "WSZYMCQJXAPKIF-UHFFFAOYSA-N"

 Success  registered route 798!

1169 0 0 Sp3-sp2_Suzuki_coupling C2514 "OBMSQRRNSRJRBN-UHFFFAOYSA-N"

 Success  registered route 799!

1170 0 0 Ester_amidation C1238 "GFCHJLUTXGTXAR-UHFFFAOYSA-N"

 Success  registered route 800!

1171 0 0 Amidation C7825 "HWPXHJBEHCQNEL-UHFFFAOYSA-N"

 Success  registered route 801!

1172 0 0 Amidation C934 "UQJVNWDNXJUWRQ-UHFFFAOYSA-N"

 Success  registered route 802!

1173 0 0 Formation_of_urea_from_two_amines C1455 "ILAOIAQOAHWDBJ-UHFFFAOYSA-N"

 Success  registered route 803!

1174 0 0 Minisci_reaction_with_carboxylic_acid_(intermolecular) C6276 "FOELTRWJVGYBGD-UHFFFAOYSA-N"

reactants =
[283318, 285429]

product = C6276 "FOELTRWJVGYBGD-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Minisci_reaction_with_carboxylic_acid_(intermolecular)!

1174 1 0 Amine_alkylation C6276 "FOELTRWJVGYBGD-UHFFFAOYSA-N"

reactants =
[285430]

product = C6276 "FOELTRWJVGYBGD-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

1174 2 0 Ring_closing_metathesis C6276 "FOELTRWJVGYBGD-UHFFFAOYSA-N"

reactants =
[285431]

product = C6276 "FOELTRWJVGYBGD-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Ring_closing_metathesis!

1174 3 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C6276 "FOELTRWJVGYBGD-UHFFFAOYSA-N"

1174 4 0 N-Boc_deprotection C6276 "FOELTRWJVGYBGD-UHFFFAOYSA-N"

1174 4 1 Minisci_reaction_with_carboxylic_acid_(intermolecular) C285433 "DTWYMWBOKARGMR-UHFFFAOYSA-N"

reactants =
[283318, 285434]

product = C285433 "DTWYMWBOKARGMR-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Minisci_reaction_with_carboxylic_acid_(intermolecular)!

1175 0 0 Amidation C20940 "DRKPVRIBDAVVDE-UHFFFAOYSA-N"

 Success  registered route 804!

1176 0 0 Amidation C6066 "VSZVJPLKYBCKOO-UHFFFAOYSA-N"

 Success  registered route 805!

1177 0 0 Hydroxy_to_fluoro C10320 "BUCJQHMDCWUKLE-UHFFFAOYSA-N"

reactants =
[285438]

product = C10320 "BUCJQHMDCWUKLE-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Hydroxy_to_fluoro!

1177 1 0 N-Ac_deprotection C10320 "BUCJQHMDCWUKLE-UHFFFAOYSA-N"

reactants =
[285439]

product = C10320 "BUCJQHMDCWUKLE-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: N-Ac_deprotection!

1177 2 0 N-Cbz_deprotection C10320 "BUCJQHMDCWUKLE-UHFFFAOYSA-N"

reactants =
[285440]

product = C10320 "BUCJQHMDCWUKLE-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: N-Cbz_deprotection!

1177 3 0 Corey-House_synthesis_(intermolecular) C10320 "BUCJQHMDCWUKLE-UHFFFAOYSA-N"

reactants =
[285441, 285442]

product = C10320 "BUCJQHMDCWUKLE-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Corey-House_synthesis_(intermolecular)!

1177 4 0 N-Boc_deprotection C10320 "BUCJQHMDCWUKLE-UHFFFAOYSA-N"

1177 4 1 Hydroxy_to_fluoro C285443 "FFCXNGKAGNZSGV-UHFFFAOYSA-N"

reactants =
[285444]

product = C285443 "FFCXNGKAGNZSGV-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Hydroxy_to_fluoro!

1178 0 0 Amidation C21077 "DCTJOWXNIBHWEL-UHFFFAOYSA-N"

 Success  registered route 806!

1179 0 0 Amidation C13624 "ZQFYEICALXCDIF-UHFFFAOYSA-N"

 Success  registered route 807!

1180 0 0 Amidation C1338 "SJYNETFQBPJTBE-UHFFFAOYSA-N"

 Success  registered route 808!

1181 0 0 Amidation C8604 "RNMVOHQXDNXOGF-UHFFFAOYSA-N"

 Success  registered route 809!

1182 0 0 Amidation C23130 "UGZOXRFYKLKGPI-UHFFFAOYSA-N"

 Success  registered route 810!

1183 0 0 Sulfonamide_Schotten-Baumann_with_amine_(intermolecular) C7644 "FQPSGVBYUDGJAR-UHFFFAOYSA-N"

reactants =
[284489, 285450]

product = C7644 "FQPSGVBYUDGJAR-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sulfonamide_Schotten-Baumann_with_amine_(intermolecular)!

1183 1 0 Formation_of_sulfonamide_from_halide_-_Shavnya_reaction C7644 "FQPSGVBYUDGJAR-UHFFFAOYSA-N"

reactants =
[284490, 285450]

product = C7644 "FQPSGVBYUDGJAR-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Formation_of_sulfonamide_from_halide_-_Shavnya_reaction!

1183 2 0 Formation_of_sulfonamide_from_halide_-_Shavnya_reaction C7644 "FQPSGVBYUDGJAR-UHFFFAOYSA-N"

reactants =
[284491, 285450]

product = C7644 "FQPSGVBYUDGJAR-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Formation_of_sulfonamide_from_halide_-_Shavnya_reaction!

1183 3 0 Formation_of_sulfonamide_from_halide_-_Shavnya_reaction C7644 "FQPSGVBYUDGJAR-UHFFFAOYSA-N"

reactants =
[284079, 285450]

product = C7644 "FQPSGVBYUDGJAR-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Formation_of_sulfonamide_from_halide_-_Shavnya_reaction!

1183 4 0 Sulfonamide_Schotten-Baumann_with_amine_(intermolecular) C7644 "FQPSGVBYUDGJAR-UHFFFAOYSA-N"

reactants =
[284492, 285450]

product = C7644 "FQPSGVBYUDGJAR-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sulfonamide_Schotten-Baumann_with_amine_(intermolecular)!

1184 0 0 Amidation C7170 "VYSLTJZGYMQXGZ-UHFFFAOYSA-N"

 Success  registered route 811!

1185 0 0 Formation_of_sulfonamide_from_halide_-_Shavnya_reaction C7592 "XNDMHKZPZBSGFI-UHFFFAOYSA-N"

reactants =
[284490, 285452]

product = C7592 "XNDMHKZPZBSGFI-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Formation_of_sulfonamide_from_halide_-_Shavnya_reaction!

1185 1 0 Formation_of_sulfonamide_from_halide_-_Shavnya_reaction C7592 "XNDMHKZPZBSGFI-UHFFFAOYSA-N"

reactants =
[284079, 285452]

product = C7592 "XNDMHKZPZBSGFI-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Formation_of_sulfonamide_from_halide_-_Shavnya_reaction!

1185 2 0 Formation_of_sulfonamide_from_halide_-_Shavnya_reaction C7592 "XNDMHKZPZBSGFI-UHFFFAOYSA-N"

reactants =
[284491, 285452]

product = C7592 "XNDMHKZPZBSGFI-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Formation_of_sulfonamide_from_halide_-_Shavnya_reaction!

1185 3 0 Corey-House_synthesis_(intermolecular) C7592 "XNDMHKZPZBSGFI-UHFFFAOYSA-N"

reactants =
[284607, 285453]

product = C7592 "XNDMHKZPZBSGFI-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Corey-House_synthesis_(intermolecular)!

1185 4 0 Corey-House_synthesis_(intermolecular) C7592 "XNDMHKZPZBSGFI-UHFFFAOYSA-N"

reactants =
[284607, 285454]

product = C7592 "XNDMHKZPZBSGFI-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Corey-House_synthesis_(intermolecular)!

1186 0 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C7642 "JIBIHHYZANIHBI-UHFFFAOYSA-N"

 Success  registered route 812!

1187 0 0 Alpha_alkylation_of_aldehyde C4693 "QLEQENYLQKJYBV-UHFFFAOYSA-N"

reactants =
[283111, 285456]

product = C4693 "QLEQENYLQKJYBV-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_aldehyde!

1187 1 0 Alpha_alkylation_of_aldehyde C4693 "QLEQENYLQKJYBV-UHFFFAOYSA-N"

reactants =
[283111, 285457]

product = C4693 "QLEQENYLQKJYBV-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_aldehyde!

1187 2 0 Swern_oxidation C4693 "QLEQENYLQKJYBV-UHFFFAOYSA-N"

reactants =
[285458]

product = C4693 "QLEQENYLQKJYBV-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Swern_oxidation!

1187 3 0 Periodate_cleavage_(intermolecular) C4693 "QLEQENYLQKJYBV-UHFFFAOYSA-N"

reactants =
[285459]

product = C4693 "QLEQENYLQKJYBV-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Periodate_cleavage_(intermolecular)!

1187 4 0 TEMPO_oxidation C4693 "QLEQENYLQKJYBV-UHFFFAOYSA-N"

reactants =
[285458]

product = C4693 "QLEQENYLQKJYBV-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: TEMPO_oxidation!

1188 0 0 Sp3-sp2_Macmillan_coupling_with_bromide_(intermolecular) C7229 "LUOQOSYKLXGGAL-UHFFFAOYSA-N"

reactants =
[285460, 285461]

product = C7229 "LUOQOSYKLXGGAL-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sp3-sp2_Macmillan_coupling_with_bromide_(intermolecular)!

1188 1 0 Alpha_alkylation_of_ester/amide C7229 "LUOQOSYKLXGGAL-UHFFFAOYSA-N"

reactants =
[285462, 285463]

product = C7229 "LUOQOSYKLXGGAL-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ester/amide!

1188 2 0 Alpha_alkylation_of_ester/amide C7229 "LUOQOSYKLXGGAL-UHFFFAOYSA-N"

reactants =
[285462, 285464]

product = C7229 "LUOQOSYKLXGGAL-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ester/amide!

1188 3 0 Amidation C7229 "LUOQOSYKLXGGAL-UHFFFAOYSA-N"

 Success  registered route 813!

1189 0 0 Amine_alkylation C8846 "VIZQUAMFAFOSLS-UHFFFAOYSA-N"

reactants =
[285467]

product = C8846 "VIZQUAMFAFOSLS-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

1189 1 0 Elimination_reaction C8846 "VIZQUAMFAFOSLS-UHFFFAOYSA-N"

reactants =
[285468]

product = C8846 "VIZQUAMFAFOSLS-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Elimination_reaction!

1189 2 0 Ring_closing_metathesis C8846 "VIZQUAMFAFOSLS-UHFFFAOYSA-N"

reactants =
[285469]

product = C8846 "VIZQUAMFAFOSLS-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Ring_closing_metathesis!

1189 3 0 Ring_closing_metathesis C8846 "VIZQUAMFAFOSLS-UHFFFAOYSA-N"

reactants =
[285470]

product = C8846 "VIZQUAMFAFOSLS-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Ring_closing_metathesis!

1189 4 0 Amine_alkylation C8846 "VIZQUAMFAFOSLS-UHFFFAOYSA-N"

reactants =
[285471]

product = C8846 "VIZQUAMFAFOSLS-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

1190 0 0 Amidation C18151 "KSBHXPKVWQLEFJ-UHFFFAOYSA-N"

 Success  registered route 814!

1191 0 0 Formation_of_sulfonamide_from_halide_-_Shavnya_reaction C12320 "YFCVSAJHUPTKJW-UHFFFAOYSA-N"

reactants =
[284490, 285473]

product = C12320 "YFCVSAJHUPTKJW-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Formation_of_sulfonamide_from_halide_-_Shavnya_reaction!

1191 1 0 Chan-Lam_coupling_of_amides,_sulfonamides,_and_imides C12320 "YFCVSAJHUPTKJW-UHFFFAOYSA-N"

reactants =
[284080, 285474]

product = C12320 "YFCVSAJHUPTKJW-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Chan-Lam_coupling_of_amides,_sulfonamides,_and_imides!

1191 2 0 Formation_of_sulfonamide_from_halide_-_Shavnya_reaction C12320 "YFCVSAJHUPTKJW-UHFFFAOYSA-N"

reactants =
[284491, 285473]

product = C12320 "YFCVSAJHUPTKJW-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Formation_of_sulfonamide_from_halide_-_Shavnya_reaction!

1191 3 0 Buchwald-Hartwig_amidation_with_amide-like_nucleophile C12320 "YFCVSAJHUPTKJW-UHFFFAOYSA-N"

 Success  registered route 815!

1192 0 0 Amidation C9783 "DCIDXVFUCNBFDV-UHFFFAOYSA-N"

 Success  registered route 816!

1193 0 0 Amidation C9801 "JJTOBGQZAVXZPQ-UHFFFAOYSA-N"

 Success  registered route 817!

1194 0 0 Amidation C8857 "XGCYOVHIYMBSNK-UHFFFAOYSA-N"

 Success  registered route 818!

1195 0 0 Ester_amidation C8929 "GUENUKMUPWZNRC-UHFFFAOYSA-N"

1195 1 0 Ester_amidation C8929 "GUENUKMUPWZNRC-UHFFFAOYSA-N"

 Success  registered route 819!

1196 0 0 Ester_amidation C29686 "ADCBIDCUFYHYHT-UHFFFAOYSA-N"

1196 1 0 Ester_amidation C29686 "ADCBIDCUFYHYHT-UHFFFAOYSA-N"

 Success  registered route 820!

1197 0 0 Nucleophilic_substitution_with_thioamide C6027 "HISKBNLAAGHDBQ-UHFFFAOYSA-N"

reactants =
[285482, 285483]

product = C6027 "HISKBNLAAGHDBQ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Nucleophilic_substitution_with_thioamide!

1197 1 0 Amidation C6027 "HISKBNLAAGHDBQ-UHFFFAOYSA-N"

 Success  registered route 821!

1198 0 0 Oxazole_synthesis C6510 "GKFRYZROBLFNAX-UHFFFAOYSA-N"

reactants =
[285486]

product = C6510 "GKFRYZROBLFNAX-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Oxazole_synthesis!

1198 1 0 Petasis-borono_Mannich_reaction C6510 "GKFRYZROBLFNAX-UHFFFAOYSA-N"

reactants =
[285487, 285488]

product = C6510 "GKFRYZROBLFNAX-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Petasis-borono_Mannich_reaction!

1198 2 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C6510 "GKFRYZROBLFNAX-UHFFFAOYSA-N"

1198 3 0 N-Boc_deprotection C6510 "GKFRYZROBLFNAX-UHFFFAOYSA-N"

1198 3 1 Oxazole_synthesis C285490 "ZABJVYBPQXLTJY-UHFFFAOYSA-N"

reactants =
[285491]

product = C285490 "ZABJVYBPQXLTJY-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Oxazole_synthesis!

1198 4 0 Amide_to_amine_reduction C6510 "GKFRYZROBLFNAX-UHFFFAOYSA-N"

reactants =
[285492]

product = C6510 "GKFRYZROBLFNAX-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amide_to_amine_reduction!

1199 0 0 Amidation C1399 "HXJSUAIOIMKJMI-UHFFFAOYSA-N"

 Success  registered route 822!

1200 0 0 Amidation C21083 "YCXUBEVMZITSJB-UHFFFAOYSA-N"

 Success  registered route 823!

1201 0 0 Pinner_reaction_(carboxylate_ester) C27042 "SRBFBJJNWAODEI-UHFFFAOYSA-N"

reactants =
[285495, 285496]

product = C27042 "SRBFBJJNWAODEI-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Pinner_reaction_(carboxylate_ester)!

1201 1 0 Steglich_esterification C27042 "SRBFBJJNWAODEI-UHFFFAOYSA-N"

 Success  registered route 824!

1202 0 0 Ester_amidation C28490 "FEMUIDDNNZKUSG-UHFFFAOYSA-N"

 Success  registered route 825!

1203 0 0 Amidation C8760 "CTZSCWGDEJRQJB-UHFFFAOYSA-N"

 Success  registered route 826!

1204 0 0 Amine_alkylation C2403 "BLPQLXCUNUOCSN-UHFFFAOYSA-N"

reactants =
[285501, 285502]

product = C2403 "BLPQLXCUNUOCSN-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

1204 1 0 Amine_alkylation C2403 "BLPQLXCUNUOCSN-UHFFFAOYSA-N"

reactants =
[285502, 285503]

product = C2403 "BLPQLXCUNUOCSN-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

1204 2 0 Amine_alkylation C2403 "BLPQLXCUNUOCSN-UHFFFAOYSA-N"

reactants =
[285502, 285504]

product = C2403 "BLPQLXCUNUOCSN-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

1204 3 0 Aziridine_+_amine_coupling C2403 "BLPQLXCUNUOCSN-UHFFFAOYSA-N"

reactants =
[285502, 285505]

product = C2403 "BLPQLXCUNUOCSN-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Aziridine_+_amine_coupling!

1204 4 0 Amine_alkylation C2403 "BLPQLXCUNUOCSN-UHFFFAOYSA-N"

reactants =
[285502, 285506]

product = C2403 "BLPQLXCUNUOCSN-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

1205 0 0 Amidation C4570 "ZPPAONKPBQFBHG-UHFFFAOYSA-N"

 Success  registered route 827!

1206 0 0 Amidation C25347 "VAYQUYQSWAUBAD-UHFFFAOYSA-N"

 Success  registered route 828!

1207 0 0 Amine_alkylation C5169 "ZHYYBDZASCMDMP-UHFFFAOYSA-N"

reactants =
[284475, 284510]

product = C5169 "ZHYYBDZASCMDMP-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

1207 1 0 N-Boc_deprotection C5169 "ZHYYBDZASCMDMP-UHFFFAOYSA-N"

 Success  registered route 829!

1208 0 0 Amidation C20140 "KKLAVPWGXVYYKK-UHFFFAOYSA-N"

 Success  registered route 830!

1209 0 0 Aziridine_+_amine_coupling C2474 "CCZWIXDZBGEKGT-UHFFFAOYSA-N"

reactants =
[284705, 285198]

product = C2474 "CCZWIXDZBGEKGT-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Aziridine_+_amine_coupling!

1209 1 0 Buchwald-Hartwig_amidation_with_amide-like_nucleophile C2474 "CCZWIXDZBGEKGT-UHFFFAOYSA-N"

1209 2 0 N-Boc_deprotection C2474 "CCZWIXDZBGEKGT-UHFFFAOYSA-N"

 Success  registered route 831!

1210 0 0 Hydroxy_to_fluoro C2410 "XHBNPKKACABHBA-UHFFFAOYSA-N"

reactants =
[285514]

product = C2410 "XHBNPKKACABHBA-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Hydroxy_to_fluoro!

1210 1 0 Hydrogenation_of_pyridine C2410 "XHBNPKKACABHBA-UHFFFAOYSA-N"

reactants =
[285515]

product = C2410 "XHBNPKKACABHBA-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Hydrogenation_of_pyridine!

1210 2 0 Corey-House_synthesis_(intermolecular) C2410 "XHBNPKKACABHBA-UHFFFAOYSA-N"

reactants =
[285516, 285517]

product = C2410 "XHBNPKKACABHBA-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Corey-House_synthesis_(intermolecular)!

1210 3 0 N-Boc_deprotection C2410 "XHBNPKKACABHBA-UHFFFAOYSA-N"

1210 3 1 Hydroxy_to_fluoro C285518 "MWPXVCXWDFOMLI-UHFFFAOYSA-N"

reactants =
[285519]

product = C285518 "MWPXVCXWDFOMLI-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Hydroxy_to_fluoro!

1210 4 0 Hydrogenation_of_pyridine C2410 "XHBNPKKACABHBA-UHFFFAOYSA-N"

reactants =
[285515]

product = C2410 "XHBNPKKACABHBA-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Hydrogenation_of_pyridine!

1211 0 0 Amidation C10519 "FKANEGWUQJTCRE-UHFFFAOYSA-N"

1211 0 1 Amidation C285520 "HXEQNEMHAQXSFA-UHFFFAOYSA-N"

 Success  registered route 832!

1212 0 0 Amidation C20970 "CPOAYBILPJRGSY-UHFFFAOYSA-N"

 Success  registered route 833!

1213 0 0 Amidation C3863 "JTEJVNYAELMDNE-UHFFFAOYSA-N"

 Success  registered route 834!

1214 0 0 Steglich_esterification C27189 "HASBCQSXHBUGKF-UHFFFAOYSA-N"

 Success  registered route 835!

1215 0 0 Alpha_alkylation_of_ketone C21569 "VGRJTUCBCKJLAN-UHFFFAOYSA-N"

reactants =
[283280, 285524]

product = C21569 "VGRJTUCBCKJLAN-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ketone!

1215 1 0 Minisci_reaction_with_carboxylic_acid_(intermolecular) C21569 "VGRJTUCBCKJLAN-UHFFFAOYSA-N"

reactants =
[285525, 285526]

product = C21569 "VGRJTUCBCKJLAN-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Minisci_reaction_with_carboxylic_acid_(intermolecular)!

1215 2 0 Ethenyl_to_formyl C21569 "VGRJTUCBCKJLAN-UHFFFAOYSA-N"

reactants =
[285527]

product = C21569 "VGRJTUCBCKJLAN-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Ethenyl_to_formyl!

1215 3 0 Alpha_alkylation_of_ketone C21569 "VGRJTUCBCKJLAN-UHFFFAOYSA-N"

reactants =
[283128, 285524]

product = C21569 "VGRJTUCBCKJLAN-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ketone!

1215 4 0 Alpha_alkylation_of_ketone C21569 "VGRJTUCBCKJLAN-UHFFFAOYSA-N"

reactants =
[283127, 285524]

product = C21569 "VGRJTUCBCKJLAN-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ketone!

1216 0 0 Formation_of_urea_from_two_amines C1403 "AYFIZZAEOIDREF-UHFFFAOYSA-N"

 Success  registered route 836!

1217 0 0 Alpha_alkylation_of_ester/amide C29720 "CLLVVLWRAOVKKD-UHFFFAOYSA-N"

reactants =
[285529, 285530]

product = C29720 "CLLVVLWRAOVKKD-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ester/amide!

1217 1 0 Alpha_alkylation_of_ester/amide C29720 "CLLVVLWRAOVKKD-UHFFFAOYSA-N"

reactants =
[285530, 285531]

product = C29720 "CLLVVLWRAOVKKD-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ester/amide!

1217 2 0 Amide_Schotten-Baumann_with_amine C29720 "CLLVVLWRAOVKKD-UHFFFAOYSA-N"

 Success  registered route 837!

1218 0 0 Amidation C7419 "NETFXXUKTZUOOD-UHFFFAOYSA-N"

 Success  registered route 838!

1219 0 0 Amidation C8485 "AHRHQIZZBXAYPC-UHFFFAOYSA-N"

 Success  registered route 839!

1220 0 0 Amidation C8952 "GQBDKUUPQMEZIN-UHFFFAOYSA-N"

 Success  registered route 840!

1221 0 0 Nucleophilic_substitution_with_thiol C6034 "XLSHTFUPRUSZEF-UHFFFAOYSA-N"

reactants =
[285483, 285538]

product = C6034 "XLSHTFUPRUSZEF-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Nucleophilic_substitution_with_thiol!

1221 1 0 Ester_amidation C6034 "XLSHTFUPRUSZEF-UHFFFAOYSA-N"

1221 2 0 Alpha_alkylation_of_ester/amide C6034 "XLSHTFUPRUSZEF-UHFFFAOYSA-N"

reactants =
[283127, 285540]

product = C6034 "XLSHTFUPRUSZEF-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ester/amide!

1221 3 0 Nucleophilic_substitution_with_thioamide C6034 "XLSHTFUPRUSZEF-UHFFFAOYSA-N"

 Warning  SMILES changed during compound registration: Nc1n[nH]c(=S)s1 --> Nc1nnc(S)s1!

reactants =
[285483, 285538]

product = C6034 "XLSHTFUPRUSZEF-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Nucleophilic_substitution_with_thioamide!

1221 4 0 Amidation C6034 "XLSHTFUPRUSZEF-UHFFFAOYSA-N"

 Success  registered route 841!

1222 0 0 Nucleophilic_substitution_with_thiol C1132 "BGMXVHWUBCMRIH-UHFFFAOYSA-N"

reactants =
[285187, 285542]

product = C1132 "BGMXVHWUBCMRIH-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Nucleophilic_substitution_with_thiol!

1222 1 0 Ester_amidation C1132 "BGMXVHWUBCMRIH-UHFFFAOYSA-N"

1222 2 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C1132 "BGMXVHWUBCMRIH-UHFFFAOYSA-N"

 Success  registered route 842!

1223 0 0 Amidation C29440 "MQWQJMQDCPGAHX-UHFFFAOYSA-N"

 Success  registered route 843!

1224 0 0 Amidation C1414 "YASWEVOWOCSSRH-UHFFFAOYSA-N"

 Success  registered route 844!

1225 0 0 Amidation C9982 "CDOCJOQYVNDDOB-UHFFFAOYSA-N"

 Success  registered route 845!

1226 0 0 Amidation C7466 "CNXDKPPPZXXLRJ-UHFFFAOYSA-N"

 Success  registered route 846!

1227 0 0 Alpha_alkylation_of_ketone C11231 "PZDAOJKGMJJGDC-UHFFFAOYSA-N"

reactants =
[285551, 285552]

product = C11231 "PZDAOJKGMJJGDC-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ketone!

1227 1 0 Alpha-arylation C11231 "PZDAOJKGMJJGDC-UHFFFAOYSA-N"

reactants =
[284178, 285553]

product = C11231 "PZDAOJKGMJJGDC-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha-arylation!

1227 2 0 Alpha_alkylation_of_ketone C11231 "PZDAOJKGMJJGDC-UHFFFAOYSA-N"

reactants =
[285552, 285554]

product = C11231 "PZDAOJKGMJJGDC-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ketone!

1227 3 0 Alpha-arylation C11231 "PZDAOJKGMJJGDC-UHFFFAOYSA-N"

reactants =
[285553, 285555]

product = C11231 "PZDAOJKGMJJGDC-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha-arylation!

1227 4 0 Alpha_alkylation_of_ketone C11231 "PZDAOJKGMJJGDC-UHFFFAOYSA-N"

reactants =
[285552, 285556]

product = C11231 "PZDAOJKGMJJGDC-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ketone!

1228 0 0 Amine_alkylation C8841 "RFEZRTLYXHCHBF-UHFFFAOYSA-N"

reactants =
[283761, 285557]

product = C8841 "RFEZRTLYXHCHBF-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

1228 1 0 Amine_alkylation C8841 "RFEZRTLYXHCHBF-UHFFFAOYSA-N"

reactants =
[283758, 285557]

product = C8841 "RFEZRTLYXHCHBF-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

1228 2 0 Amine_alkylation C8841 "RFEZRTLYXHCHBF-UHFFFAOYSA-N"

reactants =
[283759, 285557]

product = C8841 "RFEZRTLYXHCHBF-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

1228 3 0 Amine_alkylation C8841 "RFEZRTLYXHCHBF-UHFFFAOYSA-N"

reactants =
[283760, 285557]

product = C8841 "RFEZRTLYXHCHBF-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

1228 4 0 Reductive_amination C8841 "RFEZRTLYXHCHBF-UHFFFAOYSA-N"

 Success  registered route 847!

1229 0 0 Amidation C1386 "ZRDHPXNIJIQHOP-UHFFFAOYSA-N"

 Success  registered route 848!

1230 0 0 Sulfonamide_Schotten-Baumann_with_amine_(intermolecular) C29031 "QFZBMJQUWWNYIL-UHFFFAOYSA-N"

reactants =
[285559, 285560]

product = C29031 "QFZBMJQUWWNYIL-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sulfonamide_Schotten-Baumann_with_amine_(intermolecular)!

1230 1 0 Formation_of_sulfonamide_from_halide_-_Shavnya_reaction C29031 "QFZBMJQUWWNYIL-UHFFFAOYSA-N"

reactants =
[285560, 285561]

product = C29031 "QFZBMJQUWWNYIL-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Formation_of_sulfonamide_from_halide_-_Shavnya_reaction!

1230 2 0 Sulfonamide_Schotten-Baumann_with_amine_(intermolecular) C29031 "QFZBMJQUWWNYIL-UHFFFAOYSA-N"

reactants =
[285560, 285562]

product = C29031 "QFZBMJQUWWNYIL-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sulfonamide_Schotten-Baumann_with_amine_(intermolecular)!

1230 3 0 Minisci_reaction_with_carboxylic_acid_(intermolecular) C29031 "QFZBMJQUWWNYIL-UHFFFAOYSA-N"

reactants =
[285563, 285564]

product = C29031 "QFZBMJQUWWNYIL-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Minisci_reaction_with_carboxylic_acid_(intermolecular)!

1230 4 0 Formation_of_sulfonamide_from_halide_-_Shavnya_reaction C29031 "QFZBMJQUWWNYIL-UHFFFAOYSA-N"

reactants =
[285560, 285565]

product = C29031 "QFZBMJQUWWNYIL-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Formation_of_sulfonamide_from_halide_-_Shavnya_reaction!

1231 0 0 Formation_of_urea_from_two_amines C14594 "BDYCYAQORNKNIO-UHFFFAOYSA-N"

 Success  registered route 849!

1232 0 0 Amidation C1304 "KVVWFFVCOKKVCV-UHFFFAOYSA-N"

 Success  registered route 850!

1233 0 0 Nucleophilic_substitution_with_thiol C6773 "PIQMDRWGSNHVCK-UHFFFAOYSA-N"

reactants =
[285568]

product = C6773 "PIQMDRWGSNHVCK-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Nucleophilic_substitution_with_thiol!

1233 1 0 Nucleophilic_substitution_with_thiol C6773 "PIQMDRWGSNHVCK-UHFFFAOYSA-N"

reactants =
[285569]

product = C6773 "PIQMDRWGSNHVCK-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Nucleophilic_substitution_with_thiol!

1233 2 0 Amine_alkylation C6773 "PIQMDRWGSNHVCK-UHFFFAOYSA-N"

reactants =
[285570]

product = C6773 "PIQMDRWGSNHVCK-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

1233 3 0 Nucleophilic_substitution_with_thiol C6773 "PIQMDRWGSNHVCK-UHFFFAOYSA-N"

reactants =
[285571]

product = C6773 "PIQMDRWGSNHVCK-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Nucleophilic_substitution_with_thiol!

1233 4 0 Reductive_amination C6773 "PIQMDRWGSNHVCK-UHFFFAOYSA-N"

1234 0 0 Chan-Lam_coupling_(amination) C6812 "WZRAVWCMDRGDQR-UHFFFAOYSA-N"

reactants =
[283965, 285573]

product = C6812 "WZRAVWCMDRGDQR-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Chan-Lam_coupling_(amination)!

1234 1 0 N-nucleophilic_aromatic_substitution C6812 "WZRAVWCMDRGDQR-UHFFFAOYSA-N"

 Success  registered route 851!

1235 0 0 Heck_reaction_(intermolecular) C10650 "OHATYSATAWMYKE-UHFFFAOYSA-N"

reactants =
[283126, 285575]

product = C10650 "OHATYSATAWMYKE-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Heck_reaction_(intermolecular)!

1235 1 0 Sp3-sp2_Suzuki_coupling C10650 "OHATYSATAWMYKE-UHFFFAOYSA-N"

1235 1 1 Aldol_condensation C285577 "IHBJNGJYRDMOQX-UHFFFAOYSA-N"

reactants =
[283111, 285578]

product = C285577 "IHBJNGJYRDMOQX-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Aldol_condensation!

1235 2 0 Stille_coupling C10650 "OHATYSATAWMYKE-UHFFFAOYSA-N"

reactants =
[285579, 285580]

product = C10650 "OHATYSATAWMYKE-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Stille_coupling!

1235 3 0 Heck_reaction_(intermolecular) C10650 "OHATYSATAWMYKE-UHFFFAOYSA-N"

reactants =
[283225, 285581]

product = C10650 "OHATYSATAWMYKE-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Heck_reaction_(intermolecular)!

1235 4 0 Minisci_reaction_with_carboxylic_acid_(intermolecular) C10650 "OHATYSATAWMYKE-UHFFFAOYSA-N"

reactants =
[284929, 285582]

product = C10650 "OHATYSATAWMYKE-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Minisci_reaction_with_carboxylic_acid_(intermolecular)!

1236 0 0 Amidation C1394 "WLNDFJQVFATSKU-UHFFFAOYSA-N"

 Success  registered route 852!

1237 0 0 Sulfonamide_Schotten-Baumann_with_amine_(intermolecular) C7479 "FDJUGHGTFDESJB-UHFFFAOYSA-N"

reactants =
[285585, 285586]

product = C7479 "FDJUGHGTFDESJB-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sulfonamide_Schotten-Baumann_with_amine_(intermolecular)!

1237 1 0 Hydrogenation_of_benzene C7479 "FDJUGHGTFDESJB-UHFFFAOYSA-N"

reactants =
[285587]

product = C7479 "FDJUGHGTFDESJB-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Hydrogenation_of_benzene!

1237 2 0 Sp3-sp2_Suzuki_coupling C7479 "FDJUGHGTFDESJB-UHFFFAOYSA-N"

1237 2 1 Aromatic_bromination C285588 "NWMWNNGFZYTBJX-UHFFFAOYSA-N"

reactants =
[285589]

product = C285588 "NWMWNNGFZYTBJX-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Aromatic_bromination!

1237 3 0 Sp3-sp2_Suzuki_coupling C7479 "FDJUGHGTFDESJB-UHFFFAOYSA-N"

1237 3 1 Aromatic_iodination C285590 "MYSYLEPIFCWBDD-UHFFFAOYSA-N"

reactants =
[285589]

product = C285590 "MYSYLEPIFCWBDD-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Aromatic_iodination!

1237 4 0 N-PMB_deprotection C7479 "FDJUGHGTFDESJB-UHFFFAOYSA-N"

reactants =
[285591]

product = C7479 "FDJUGHGTFDESJB-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: N-PMB_deprotection!

1238 0 0 NHK_reaction C15051 "MHXYYYOIIYIRRP-UHFFFAOYSA-N"

reactants =
[285592, 285593]

product = C15051 "MHXYYYOIIYIRRP-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: NHK_reaction!

1238 1 0 Minisci_reaction_with_carboxylic_acid_(intermolecular) C15051 "MHXYYYOIIYIRRP-UHFFFAOYSA-N"

reactants =
[283318, 285594]

product = C15051 "MHXYYYOIIYIRRP-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Minisci_reaction_with_carboxylic_acid_(intermolecular)!

1238 2 0 Alpha_alkylation_of_ketone C15051 "MHXYYYOIIYIRRP-UHFFFAOYSA-N"

reactants =
[283127, 285595]

product = C15051 "MHXYYYOIIYIRRP-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ketone!

1238 3 0 NHK_reaction C15051 "MHXYYYOIIYIRRP-UHFFFAOYSA-N"

reactants =
[284178, 285593]

product = C15051 "MHXYYYOIIYIRRP-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: NHK_reaction!

1238 4 0 NHK_reaction C15051 "MHXYYYOIIYIRRP-UHFFFAOYSA-N"

reactants =
[285555, 285593]

product = C15051 "MHXYYYOIIYIRRP-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: NHK_reaction!

1239 0 0 Amidation C13878 "QXBXKJNMGXBAQW-UHFFFAOYSA-N"

 Success  registered route 853!

1240 0 0 Aziridine_+_amine_coupling C8132 "OHYSAQUMFUOGOB-UHFFFAOYSA-N"

reactants =
[285505, 285597]

product = C8132 "OHYSAQUMFUOGOB-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Aziridine_+_amine_coupling!

1240 1 0 N-Fmoc_deprotection C8132 "OHYSAQUMFUOGOB-UHFFFAOYSA-N"

reactants =
[285598]

product = C8132 "OHYSAQUMFUOGOB-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: N-Fmoc_deprotection!

1240 2 0 N-Cbz_deprotection C8132 "OHYSAQUMFUOGOB-UHFFFAOYSA-N"

reactants =
[285599]

product = C8132 "OHYSAQUMFUOGOB-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: N-Cbz_deprotection!

1240 3 0 N-Boc_deprotection C8132 "OHYSAQUMFUOGOB-UHFFFAOYSA-N"

 Success  registered route 854!

1241 0 0 Amine_alkylation C6280 "VQRXHIVVUXYAFH-UHFFFAOYSA-N"

reactants =
[285601]

product = C6280 "VQRXHIVVUXYAFH-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

1241 1 0 Amine_alkylation C6280 "VQRXHIVVUXYAFH-UHFFFAOYSA-N"

reactants =
[285602]

product = C6280 "VQRXHIVVUXYAFH-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

1241 2 0 Reductive_amination C6280 "VQRXHIVVUXYAFH-UHFFFAOYSA-N"

1241 3 0 Nucleophilic_substitution_with_thiol C6280 "VQRXHIVVUXYAFH-UHFFFAOYSA-N"

reactants =
[285604]

product = C6280 "VQRXHIVVUXYAFH-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Nucleophilic_substitution_with_thiol!

1241 4 0 Amine_alkylation C6280 "VQRXHIVVUXYAFH-UHFFFAOYSA-N"

reactants =
[285605]

product = C6280 "VQRXHIVVUXYAFH-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

1242 0 0 Formation_of_sulfonamide_from_halide_-_Shavnya_reaction C9179 "TXZMGEIPDXEFES-UHFFFAOYSA-N"

reactants =
[285606, 285607]

product = C9179 "TXZMGEIPDXEFES-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Formation_of_sulfonamide_from_halide_-_Shavnya_reaction!

1242 1 0 Formation_of_sulfonamide_from_halide_-_Shavnya_reaction C9179 "TXZMGEIPDXEFES-UHFFFAOYSA-N"

reactants =
[285607, 285608]

product = C9179 "TXZMGEIPDXEFES-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Formation_of_sulfonamide_from_halide_-_Shavnya_reaction!

1242 2 0 Formation_of_sulfonamide_from_halide_-_Shavnya_reaction C9179 "TXZMGEIPDXEFES-UHFFFAOYSA-N"

reactants =
[285607, 285609]

product = C9179 "TXZMGEIPDXEFES-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Formation_of_sulfonamide_from_halide_-_Shavnya_reaction!

1242 3 0 N-Boc_deprotection C9179 "TXZMGEIPDXEFES-UHFFFAOYSA-N"

 Success  registered route 855!

1243 0 0 Carboxylic_acid_+_hydrazine_condensation C961 "CLKVTKUYRZLTQV-UHFFFAOYSA-N"

reactants =
[285611, 285612]

product = C961 "CLKVTKUYRZLTQV-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Carboxylic_acid_+_hydrazine_condensation!

1243 1 0 Ester_amidation C961 "CLKVTKUYRZLTQV-UHFFFAOYSA-N"

 Success  registered route 856!

1244 0 0 Amidation C1002 "XZXXEYWXKJBZSC-UHFFFAOYSA-N"

 Success  registered route 857!

1245 0 0 N-nucleophilic_aromatic_substitution C3919 "KMXPQZZEYXRUBR-UHFFFAOYSA-N"

 Success  registered route 858!

1246 0 0 Stille_coupling C4175 "IMBLIAFPKKGXAI-UHFFFAOYSA-N"

reactants =
[285579, 285617]

product = C4175 "IMBLIAFPKKGXAI-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Stille_coupling!

1246 1 0 Sp2-sp2_Suzuki_coupling C4175 "IMBLIAFPKKGXAI-UHFFFAOYSA-N"

 Success  registered route 859!

1247 0 0 Amidation C35792 "ATECCOVAGPARCV-UHFFFAOYSA-N"

 Success  registered route 860!

1248 0 0 Amidation C22039 "PYOGJXOXCOUBHM-UHFFFAOYSA-N"

 Success  registered route 861!

1249 0 0 Appel_bromination C9393 "WYAUXRZNPDFNGB-UHFFFAOYSA-N"

reactants =
[285624]

product = C9393 "WYAUXRZNPDFNGB-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Appel_bromination!

1249 1 0 Sulfonamide_Schotten-Baumann_with_amine_(intermolecular) C9393 "WYAUXRZNPDFNGB-UHFFFAOYSA-N"

reactants =
[284379, 285625]

product = C9393 "WYAUXRZNPDFNGB-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sulfonamide_Schotten-Baumann_with_amine_(intermolecular)!

1249 2 0 Sulfonamide_Schotten-Baumann_with_amine_(intermolecular) C9393 "WYAUXRZNPDFNGB-UHFFFAOYSA-N"

reactants =
[284380, 285625]

product = C9393 "WYAUXRZNPDFNGB-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sulfonamide_Schotten-Baumann_with_amine_(intermolecular)!

1249 3 0 Alkene_hydrogenation_(unconjugated) C9393 "WYAUXRZNPDFNGB-UHFFFAOYSA-N"

reactants =
[285626]

product = C9393 "WYAUXRZNPDFNGB-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alkene_hydrogenation_(unconjugated)!

1249 4 0 Alkyne_to_alkane_hydrogenation C9393 "WYAUXRZNPDFNGB-UHFFFAOYSA-N"

reactants =
[285627]

product = C9393 "WYAUXRZNPDFNGB-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alkyne_to_alkane_hydrogenation!

1250 0 0 Amidation C28016 "VNNGVJKCEHEFDX-UHFFFAOYSA-N"

 Success  registered route 862!

1251 0 0 Alpha_alkylation_of_ester/amide C4809 "LHBRDYHDWDKHLQ-UHFFFAOYSA-N"

reactants =
[285500, 285629]

product = C4809 "LHBRDYHDWDKHLQ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ester/amide!

1251 1 0 Alpha_alkylation_of_ester/amide C4809 "LHBRDYHDWDKHLQ-UHFFFAOYSA-N"

reactants =
[285500, 285630]

product = C4809 "LHBRDYHDWDKHLQ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ester/amide!

1251 2 0 Alpha_alkylation_of_ester/amide C4809 "LHBRDYHDWDKHLQ-UHFFFAOYSA-N"

reactants =
[285500, 285631]

product = C4809 "LHBRDYHDWDKHLQ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ester/amide!

1251 3 0 Alpha_alkylation_of_ester/amide C4809 "LHBRDYHDWDKHLQ-UHFFFAOYSA-N"

reactants =
[283127, 285632]

product = C4809 "LHBRDYHDWDKHLQ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ester/amide!

1251 4 0 Ester_hydrolysis_(carboxylate_fragment) C4809 "LHBRDYHDWDKHLQ-UHFFFAOYSA-N"

reactants =
[285633]

product = C4809 "LHBRDYHDWDKHLQ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Ester_hydrolysis_(carboxylate_fragment)!

1252 0 0 Amidation C21997 "FKUQYJCHXNTLRM-UHFFFAOYSA-N"

 Success  registered route 863!

1253 0 0 Simmons-Smith_reaction C10158 "FJTKEURQIPWLEI-UHFFFAOYSA-N"

reactants =
[10144]

product = C10158 "FJTKEURQIPWLEI-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Simmons-Smith_reaction!

1253 1 0 Formation_of_urea_from_two_amines C10158 "FJTKEURQIPWLEI-UHFFFAOYSA-N"

1253 2 0 Amide_to_amine_reduction C10158 "FJTKEURQIPWLEI-UHFFFAOYSA-N"

reactants =
[285636]

product = C10158 "FJTKEURQIPWLEI-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amide_to_amine_reduction!

1253 3 0 N-Bn_deprotection C10158 "FJTKEURQIPWLEI-UHFFFAOYSA-N"

1253 3 1 Amide_to_amine_reduction C285637 "UXDOLYOQBODJBE-UHFFFAOYSA-N"

reactants =
[285638]

product = C285637 "UXDOLYOQBODJBE-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amide_to_amine_reduction!

1253 4 0 N-Bn_deprotection C10158 "FJTKEURQIPWLEI-UHFFFAOYSA-N"

1253 4 1 Formation_of_urea_from_two_amines C285639 "GSMDNSIFJLGMEB-UHFFFAOYSA-N"

1254 0 0 Sp3-sp2_Suzuki_coupling C1799 "TYJWRLDKTXVLTC-UHFFFAOYSA-N"

 Success  registered route 864!

1255 0 0 Amidation C8891 "GFQVOONUDCSYCR-UHFFFAOYSA-N"

 Success  registered route 865!

1256 0 0 Heck_reaction_(intermolecular) C20946 "YQOYVOMTPHOFRP-UHFFFAOYSA-N"

reactants =
[283126, 285642]

product = C20946 "YQOYVOMTPHOFRP-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Heck_reaction_(intermolecular)!

1256 1 0 Amidation C20946 "YQOYVOMTPHOFRP-UHFFFAOYSA-N"

 Success  registered route 866!

1257 0 0 Sp3-sp2_Suzuki_coupling C1109 "XPBCDWNBSRTCDV-UHFFFAOYSA-N"

 Success  registered route 867!

1258 0 0 Amine_alkylation C5394 "RYAINGBGWASFKK-UHFFFAOYSA-N"

reactants =
[284456, 284464]

product = C5394 "RYAINGBGWASFKK-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

1258 1 0 Amine_alkylation C5394 "RYAINGBGWASFKK-UHFFFAOYSA-N"

reactants =
[284455, 284464]

product = C5394 "RYAINGBGWASFKK-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

1258 2 0 Amine_alkylation C5394 "RYAINGBGWASFKK-UHFFFAOYSA-N"

reactants =
[284457, 284464]

product = C5394 "RYAINGBGWASFKK-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

1258 3 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C5394 "RYAINGBGWASFKK-UHFFFAOYSA-N"

 Success  registered route 868!

1259 0 0 Amidation C21168 "FKMAEMGSWVNCKY-UHFFFAOYSA-N"

 Success  registered route 869!

1260 0 0 Amidation C13661 "XFTRGEJLGGFFLL-UHFFFAOYSA-N"

 Success  registered route 870!

1261 0 0 Aziridine_+_amine_coupling C2503 "ASMMGLVTGJDGEB-UHFFFAOYSA-N"

reactants =
[285198, 285646]

product = C2503 "ASMMGLVTGJDGEB-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Aziridine_+_amine_coupling!

1261 1 0 Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide C2503 "ASMMGLVTGJDGEB-UHFFFAOYSA-N"

reactants =
[282914, 285647]

product = C2503 "ASMMGLVTGJDGEB-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide!

1261 2 0 Amidation C2503 "ASMMGLVTGJDGEB-UHFFFAOYSA-N"

1261 3 0 Amidation C2503 "ASMMGLVTGJDGEB-UHFFFAOYSA-N"

1261 4 0 Buchwald-Hartwig_amidation_with_amide-like_nucleophile C2503 "ASMMGLVTGJDGEB-UHFFFAOYSA-N"

1262 0 0 Alpha_alkylation_of_ketone C8131 "VZVGFJIPTVRBAH-UHFFFAOYSA-N"

reactants =
[284510, 285650]

product = C8131 "VZVGFJIPTVRBAH-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ketone!

1262 1 0 N-Boc_deprotection C8131 "VZVGFJIPTVRBAH-UHFFFAOYSA-N"

 Success  registered route 871!

1263 0 0 Nucleophilic_substitution_with_thioamide C13681 "YQLMJTHUYFOGIH-UHFFFAOYSA-N"

reactants =
[285652, 285653]

product = C13681 "YQLMJTHUYFOGIH-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Nucleophilic_substitution_with_thioamide!

1263 1 0 Nucleophilic_substitution_with_thiol C13681 "YQLMJTHUYFOGIH-UHFFFAOYSA-N"

 Warning  SMILES changed during compound registration: Sc1nccs1 --> S=c1[nH]ccs1!

reactants =
[285652, 285654]

product = C13681 "YQLMJTHUYFOGIH-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Nucleophilic_substitution_with_thiol!

1263 2 0 Nucleophilic_substitution_with_thioamide C13681 "YQLMJTHUYFOGIH-UHFFFAOYSA-N"

reactants =
[285652, 285654]

product = C13681 "YQLMJTHUYFOGIH-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Nucleophilic_substitution_with_thioamide!

1263 3 0 Nucleophilic_substitution_with_thiol C13681 "YQLMJTHUYFOGIH-UHFFFAOYSA-N"

 Warning  SMILES changed during compound registration: Sc1nccs1 --> S=c1[nH]ccs1!

reactants =
[285652, 285653]

product = C13681 "YQLMJTHUYFOGIH-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Nucleophilic_substitution_with_thiol!

1263 4 0 Amidation C13681 "YQLMJTHUYFOGIH-UHFFFAOYSA-N"

 Success  registered route 872!

1264 0 0 Amidation C34794 "VDTHFFGZXLSRON-UHFFFAOYSA-N"

 Success  registered route 873!

1265 0 0 Amidation C33363 "WGYSJYZCOQJSGJ-UHFFFAOYSA-N"

 Success  registered route 874!

1266 0 0 Amidation C5959 "ODTPIPWYWNRRDZ-UHFFFAOYSA-N"

 Success  registered route 875!

1267 0 0 Amidation C13045 "BODYQHRQNOBDAC-UHFFFAOYSA-N"

 Success  registered route 876!

1268 0 0 Amidation C2487 "LWUPXCRKWPNRJC-UHFFFAOYSA-N"

1268 1 0 Amidation C2487 "LWUPXCRKWPNRJC-UHFFFAOYSA-N"

1268 2 0 Amidation C2487 "LWUPXCRKWPNRJC-UHFFFAOYSA-N"

1268 3 0 Amidation C2487 "LWUPXCRKWPNRJC-UHFFFAOYSA-N"

1268 4 0 N-Fmoc_deprotection C2487 "LWUPXCRKWPNRJC-UHFFFAOYSA-N"

reactants =
[285662]

product = C2487 "LWUPXCRKWPNRJC-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: N-Fmoc_deprotection!

1269 0 0 Reductive_amination C82666 "GWGHKZDVFZVLKE-UHFFFAOYSA-N"

 Success  registered route 877!

1270 0 0 Amidation C13636 "OORLBSFUVZGRGR-UHFFFAOYSA-N"

 Success  registered route 878!

1271 0 0 Amidation C10690 "FCBYOGTWIGJNNJ-UHFFFAOYSA-N"

 Success  registered route 879!

1272 0 0 Amine_alkylation C2123 "WUBOLPOQHKSMNV-UHFFFAOYSA-N"

reactants =
[1869, 285668]

product = C2123 "WUBOLPOQHKSMNV-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

1272 1 0 Amine_alkylation C2123 "WUBOLPOQHKSMNV-UHFFFAOYSA-N"

reactants =
[1869, 285669]

product = C2123 "WUBOLPOQHKSMNV-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

1272 2 0 Alpha_alkylation_of_ketone C2123 "WUBOLPOQHKSMNV-UHFFFAOYSA-N"

reactants =
[283128, 285670]

product = C2123 "WUBOLPOQHKSMNV-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ketone!

1272 3 0 Alpha_alkylation_of_ketone C2123 "WUBOLPOQHKSMNV-UHFFFAOYSA-N"

reactants =
[283127, 285670]

product = C2123 "WUBOLPOQHKSMNV-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ketone!

1272 4 0 Sp3-sp2_Suzuki_coupling C2123 "WUBOLPOQHKSMNV-UHFFFAOYSA-N"

1272 4 1 Amine_alkylation C285671 "SGYHKVKWLPEXCA-UHFFFAOYSA-N"

reactants =
[284257, 285668]

product = C285671 "SGYHKVKWLPEXCA-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

1273 0 0 Formation_of_sulfonamide_from_halide_-_Shavnya_reaction C86181 "POMAHRVANROYCT-UHFFFAOYSA-N"

reactants =
[283785, 285672]

product = C86181 "POMAHRVANROYCT-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Formation_of_sulfonamide_from_halide_-_Shavnya_reaction!

1273 1 0 Sulfonamide_Schotten-Baumann_with_amine_(intermolecular) C86181 "POMAHRVANROYCT-UHFFFAOYSA-N"

reactants =
[283782, 285672]

product = C86181 "POMAHRVANROYCT-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sulfonamide_Schotten-Baumann_with_amine_(intermolecular)!

1273 2 0 Sulfonamide_Schotten-Baumann_with_amine_(intermolecular) C86181 "POMAHRVANROYCT-UHFFFAOYSA-N"

reactants =
[283784, 285672]

product = C86181 "POMAHRVANROYCT-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sulfonamide_Schotten-Baumann_with_amine_(intermolecular)!

1273 3 0 Formation_of_sulfonamide_from_halide_-_Shavnya_reaction C86181 "POMAHRVANROYCT-UHFFFAOYSA-N"

reactants =
[283786, 285672]

product = C86181 "POMAHRVANROYCT-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Formation_of_sulfonamide_from_halide_-_Shavnya_reaction!

1273 4 0 Formation_of_sulfonamide_from_halide_-_Shavnya_reaction C86181 "POMAHRVANROYCT-UHFFFAOYSA-N"

reactants =
[285672, 285673]

product = C86181 "POMAHRVANROYCT-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Formation_of_sulfonamide_from_halide_-_Shavnya_reaction!

1275 0 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C5404 "JPQPMWWMNLJLFA-UHFFFAOYSA-N"

1275 1 0 Reductive_amination C5404 "JPQPMWWMNLJLFA-UHFFFAOYSA-N"

1275 2 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C5404 "JPQPMWWMNLJLFA-UHFFFAOYSA-N"

1275 3 0 Simmons-Smith_reaction C5404 "JPQPMWWMNLJLFA-UHFFFAOYSA-N"

reactants =
[285677]

product = C5404 "JPQPMWWMNLJLFA-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Simmons-Smith_reaction!

1275 4 0 Amine_alkylation C5404 "JPQPMWWMNLJLFA-UHFFFAOYSA-N"

reactants =
[285678]

product = C5404 "JPQPMWWMNLJLFA-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

1276 0 0 Reductive_amination C82412 "UYZNFIDKOOLBFF-UHFFFAOYSA-N"

 Success  registered route 880!

1277 0 0 Amide_Schotten-Baumann_with_amine C86222 "HZKRCMBVUHIKHS-UHFFFAOYSA-N"

1277 0 1 Carboxylic_acid_to_acid_chloride C285681 "HSNFKKGOEAEDEH-UHFFFAOYSA-N"

reactants =
[285683]

product = C285681 "HSNFKKGOEAEDEH-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Carboxylic_acid_to_acid_chloride!

1277 1 0 Corey-House_synthesis_(intermolecular) C86222 "HZKRCMBVUHIKHS-UHFFFAOYSA-N"

reactants =
[285684, 285685]

product = C86222 "HZKRCMBVUHIKHS-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Corey-House_synthesis_(intermolecular)!

1277 2 0 Friedel-Crafts_methylation C86222 "HZKRCMBVUHIKHS-UHFFFAOYSA-N"

reactants =
[285686]

product = C86222 "HZKRCMBVUHIKHS-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Friedel-Crafts_methylation!

1277 3 0 Corey-House_synthesis_(intermolecular) C86222 "HZKRCMBVUHIKHS-UHFFFAOYSA-N"

reactants =
[285684, 285687]

product = C86222 "HZKRCMBVUHIKHS-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Corey-House_synthesis_(intermolecular)!

1277 4 0 Corey-House_synthesis_(intermolecular) C86222 "HZKRCMBVUHIKHS-UHFFFAOYSA-N"

reactants =
[285684, 285688]

product = C86222 "HZKRCMBVUHIKHS-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Corey-House_synthesis_(intermolecular)!

1278 0 0 Steglich_esterification C91439 "TYDVZPFYBLQFDI-UHFFFAOYSA-N"

 Success  registered route 881!

1279 0 0 Amidation C17086 "MFVZOPZOZQGRRS-UHFFFAOYSA-N"

 Success  registered route 882!

1280 0 0 Amidation C9566 "WQQLBSLYPKFCKZ-UHFFFAOYSA-N"

 Success  registered route 883!

1281 0 0 N-nucleophilic_aromatic_substitution C15184 "UDMHBJKMQVXFEZ-UHFFFAOYSA-N"

 Success  registered route 884!

1282 0 0 Nucleophilic_substitution_with_thiol C6035 "SXQLOIUOKJFCTE-UHFFFAOYSA-N"

reactants =
[285538, 285695]

product = C6035 "SXQLOIUOKJFCTE-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Nucleophilic_substitution_with_thiol!

1282 1 0 Nucleophilic_substitution_with_thioamide C6035 "SXQLOIUOKJFCTE-UHFFFAOYSA-N"

 Warning  SMILES changed during compound registration: Nc1n[nH]c(=S)s1 --> Nc1nnc(S)s1!

reactants =
[285538, 285696]

product = C6035 "SXQLOIUOKJFCTE-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Nucleophilic_substitution_with_thioamide!

1282 2 0 Ester_amidation C6035 "SXQLOIUOKJFCTE-UHFFFAOYSA-N"

1282 3 0 Nucleophilic_substitution_with_thiol C6035 "SXQLOIUOKJFCTE-UHFFFAOYSA-N"

reactants =
[285538, 285696]

product = C6035 "SXQLOIUOKJFCTE-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Nucleophilic_substitution_with_thiol!

1282 4 0 N-Bn_deprotection C6035 "SXQLOIUOKJFCTE-UHFFFAOYSA-N"

 Success  registered route 885!

1283 0 0 Baeyer-Villiger_oxidation C3119 "FGJMRRSNHUUVNO-UHFFFAOYSA-N"

reactants =
[285698]

product = C3119 "FGJMRRSNHUUVNO-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Baeyer-Villiger_oxidation!

1283 1 0 Conjugate_addition_of_Grignard_(Gilman_reagents) C3119 "FGJMRRSNHUUVNO-UHFFFAOYSA-N"

reactants =
[285699, 285700]

product = C3119 "FGJMRRSNHUUVNO-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Conjugate_addition_of_Grignard_(Gilman_reagents)!

1283 2 0 N-Cbz_deprotection C3119 "FGJMRRSNHUUVNO-UHFFFAOYSA-N"

reactants =
[285701]

product = C3119 "FGJMRRSNHUUVNO-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: N-Cbz_deprotection!

1283 3 0 N-Boc_deprotection C3119 "FGJMRRSNHUUVNO-UHFFFAOYSA-N"

 Success  registered route 886!

1284 0 0 Amidation C10549 "QLCVGBHOPHCWJD-UHFFFAOYSA-N"

 Success  registered route 887!

1285 0 0 Amidation C1375 "NWUVTHIOIUIXCU-UHFFFAOYSA-N"

 Success  registered route 888!

1286 0 0 Amine_alkylation C759 "OLVLBHADGADCLT-UHFFFAOYSA-N"

reactants =
[283760, 285705]

product = C759 "OLVLBHADGADCLT-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

1286 1 0 Amine_alkylation C759 "OLVLBHADGADCLT-UHFFFAOYSA-N"

reactants =
[283759, 285705]

product = C759 "OLVLBHADGADCLT-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

1286 2 0 Amine_alkylation C759 "OLVLBHADGADCLT-UHFFFAOYSA-N"

reactants =
[283758, 285705]

product = C759 "OLVLBHADGADCLT-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

1286 3 0 Amine_alkylation C759 "OLVLBHADGADCLT-UHFFFAOYSA-N"

reactants =
[283761, 285705]

product = C759 "OLVLBHADGADCLT-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

1286 4 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C759 "OLVLBHADGADCLT-UHFFFAOYSA-N"

 Success  registered route 889!

1287 0 0 Amidation C7139 "NUBNQKVFZUNLSK-UHFFFAOYSA-N"

 Success  registered route 890!

1288 0 0 Amidation C1883 "KCHUUQFYYOTEQS-UHFFFAOYSA-N"

 Success  registered route 891!

1289 0 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C11851 "LLBDRWNYPBEFLX-UHFFFAOYSA-N"

 Success  registered route 892!

1290 0 0 N-Boc_deprotection C6044 "ZSANGZPGNFVAPL-UHFFFAOYSA-N"

 Success  registered route 893!

1291 0 0 Alpha_alkylation_of_aldehyde C15052 "HXNOWCAYKFJUHZ-UHFFFAOYSA-N"

reactants =
[283127, 285712]

product = C15052 "HXNOWCAYKFJUHZ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_aldehyde!

1291 1 0 Acetal_deprotection C15052 "HXNOWCAYKFJUHZ-UHFFFAOYSA-N"

reactants =
[285713]

product = C15052 "HXNOWCAYKFJUHZ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Acetal_deprotection!

1291 2 0 Alpha_alkylation_of_aldehyde C15052 "HXNOWCAYKFJUHZ-UHFFFAOYSA-N"

reactants =
[283280, 285712]

product = C15052 "HXNOWCAYKFJUHZ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_aldehyde!

1291 3 0 Alpha_alkylation_of_ketone C15052 "HXNOWCAYKFJUHZ-UHFFFAOYSA-N"

reactants =
[283127, 285712]

product = C15052 "HXNOWCAYKFJUHZ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ketone!

1291 4 0 Alpha_alkylation_of_ketone C15052 "HXNOWCAYKFJUHZ-UHFFFAOYSA-N"

reactants =
[283280, 285712]

product = C15052 "HXNOWCAYKFJUHZ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ketone!

1292 0 0 Amidation C4118 "JXTZNDLJXPZAEM-UHFFFAOYSA-N"

 Success  registered route 894!

1293 0 0 Amidation C14136 "GLKOPRGBSIQCBP-UHFFFAOYSA-N"

 Success  registered route 895!

1294 0 0 Sulfonamide_Schotten-Baumann_with_amine_(intermolecular) C40896 "NRWGAZDGIQPBJK-UHFFFAOYSA-N"

reactants =
[283919, 285717]

product = C40896 "NRWGAZDGIQPBJK-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sulfonamide_Schotten-Baumann_with_amine_(intermolecular)!

1294 1 0 Sulfonamide_Schotten-Baumann_with_amine_(intermolecular) C40896 "NRWGAZDGIQPBJK-UHFFFAOYSA-N"

reactants =
[283919, 285718]

product = C40896 "NRWGAZDGIQPBJK-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sulfonamide_Schotten-Baumann_with_amine_(intermolecular)!

1294 2 0 Heck_reaction_(intermolecular) C40896 "NRWGAZDGIQPBJK-UHFFFAOYSA-N"

reactants =
[285719, 285720]

product = C40896 "NRWGAZDGIQPBJK-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Heck_reaction_(intermolecular)!

1294 3 0 Heck_reaction_(intermolecular) C40896 "NRWGAZDGIQPBJK-UHFFFAOYSA-N"

reactants =
[285720, 285721]

product = C40896 "NRWGAZDGIQPBJK-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Heck_reaction_(intermolecular)!

1294 4 0 Heck_reaction_(intermolecular) C40896 "NRWGAZDGIQPBJK-UHFFFAOYSA-N"

reactants =
[285720, 285722]

product = C40896 "NRWGAZDGIQPBJK-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Heck_reaction_(intermolecular)!

1295 0 0 Steglich_esterification C20308 "HJXNHEVQRCOAHH-UHFFFAOYSA-N"

 Success  registered route 896!

1296 0 0 Amidation C11833 "KRQYBBCCQUVOQQ-UHFFFAOYSA-N"

 Success  registered route 897!

1297 0 0 Sp3-sp2_Macmillan_coupling_with_chloride_(intermolecular) C40856 "DFDDAHMVJZQNIS-UHFFFAOYSA-N"

reactants =
[285727, 285728]

product = C40856 "DFDDAHMVJZQNIS-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sp3-sp2_Macmillan_coupling_with_chloride_(intermolecular)!

1297 1 0 Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide C40856 "DFDDAHMVJZQNIS-UHFFFAOYSA-N"

reactants =
[285196, 285729]

product = C40856 "DFDDAHMVJZQNIS-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide!

1297 2 0 Grignard_addition_to_carbonyl C40856 "DFDDAHMVJZQNIS-UHFFFAOYSA-N"

reactants =
[285730, 285731]

product = C40856 "DFDDAHMVJZQNIS-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Grignard_addition_to_carbonyl!

1297 3 0 Grignard_addition_to_epoxide C40856 "DFDDAHMVJZQNIS-UHFFFAOYSA-N"

reactants =
[285732, 285733]

product = C40856 "DFDDAHMVJZQNIS-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Grignard_addition_to_epoxide!

1297 4 0 Grignard_addition_to_carbonyl C40856 "DFDDAHMVJZQNIS-UHFFFAOYSA-N"

reactants =
[285731, 285734]

product = C40856 "DFDDAHMVJZQNIS-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Grignard_addition_to_carbonyl!

1298 0 0 Amidation C7141 "RPYFJMJVSOYEFT-UHFFFAOYSA-N"

 Success  registered route 898!

1299 0 0 Amidation C1357 "IBUVLDQWYDBITO-UHFFFAOYSA-N"

 Success  registered route 899!

1300 0 0 Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide C1814 "CFGUFSRARCDEJB-UHFFFAOYSA-N"

reactants =
[284772, 285737]

product = C1814 "CFGUFSRARCDEJB-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide!

1300 1 0 Sp3-sp2_Suzuki_coupling C1814 "CFGUFSRARCDEJB-UHFFFAOYSA-N"

 Success  registered route 900!

1301 0 0 N-nucleophilic_aromatic_substitution C540 "GYLBIGBYLJSRMM-UHFFFAOYSA-N"

 Success  registered route 901!

1302 0 0 Amidation C16846 "VIUGNCAMDRTQJK-UHFFFAOYSA-N"

 Success  registered route 902!

1303 0 0 Amidation C5949 "JSOLCRWBOHDHLA-UHFFFAOYSA-N"

 Success  registered route 903!

1304 0 0 N-nucleophilic_aromatic_substitution C35886 "AFJPCOIBOPEZRQ-UHFFFAOYSA-N"

 Success  registered route 904!

1305 0 0 Amidation C532 "SOLMNNBILPZOSX-UHFFFAOYSA-N"

 Success  registered route 905!

1306 0 0 Amidation C15494 "YLJPPWLVJABBLI-UHFFFAOYSA-N"

 Success  registered route 906!

1307 0 0 Amidation C15471 "CPAZNKHVDOFCMV-UHFFFAOYSA-N"

 Success  registered route 907!

1308 0 0 Amidation C13067 "DRDOJMCYICGXFL-UHFFFAOYSA-N"

 Success  registered route 908!

1309 0 0 Iodo_N-arylation C32616 "BIIVMCIDBUMVDU-UHFFFAOYSA-N"

reactants =
[285746, 285747]

product = C32616 "BIIVMCIDBUMVDU-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Iodo_N-arylation!

1309 1 0 Amidation C32616 "BIIVMCIDBUMVDU-UHFFFAOYSA-N"

 Success  registered route 909!

1310 0 0 Hydrogenation_of_pyridine C787 "WOKNKIOABYEMDE-UHFFFAOYSA-N"

reactants =
[285749]

product = C787 "WOKNKIOABYEMDE-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Hydrogenation_of_pyridine!

1310 1 0 Corey-House_synthesis_(intermolecular) C787 "WOKNKIOABYEMDE-UHFFFAOYSA-N"

reactants =
[285750, 285751]

product = C787 "WOKNKIOABYEMDE-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Corey-House_synthesis_(intermolecular)!

1310 2 0 Hydrogenation_of_pyridine C787 "WOKNKIOABYEMDE-UHFFFAOYSA-N"

reactants =
[285749]

product = C787 "WOKNKIOABYEMDE-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Hydrogenation_of_pyridine!

1310 3 0 Corey-House_synthesis_(intermolecular) C787 "WOKNKIOABYEMDE-UHFFFAOYSA-N"

reactants =
[283759, 285752]

product = C787 "WOKNKIOABYEMDE-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Corey-House_synthesis_(intermolecular)!

1310 4 0 Simmons-Smith_reaction C787 "WOKNKIOABYEMDE-UHFFFAOYSA-N"

reactants =
[285753]

product = C787 "WOKNKIOABYEMDE-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Simmons-Smith_reaction!

1311 0 0 Amidation C7188 "GYBDNCZJKSYHSE-UHFFFAOYSA-N"

 Success  registered route 910!

1312 0 0 Amidation C11631 "QVLGSSQYZVYUGJ-UHFFFAOYSA-N"

 Success  registered route 911!

1313 0 0 Amidation C10551 "CKCGJIQEJLLOHK-UHFFFAOYSA-N"

 Success  registered route 912!

1314 0 0 Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide C91922 "VKCFWKQFXUVIIM-UHFFFAOYSA-N"

reactants =
[282914, 285757]

product = C91922 "VKCFWKQFXUVIIM-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide!

1314 1 0 Buchwald-Hartwig_amidation_with_amide-like_nucleophile C91922 "VKCFWKQFXUVIIM-UHFFFAOYSA-N"

 Success  registered route 913!

1315 0 0 Amidation C43172 "ZNJBUCCMBIUDOR-UHFFFAOYSA-N"

 Warning  SMILES changed during compound registration: NCc1c[nH]cn1 --> NCc1cnc[nH]1!

 Success  registered route 914!

1316 0 0 Amidation C17988 "YDXIBDJDTVMVDS-UHFFFAOYSA-N"

 Success  registered route 915!

1317 0 0 Amidation C16894 "NPIYBZYEPOASSM-UHFFFAOYSA-N"

 Success  registered route 916!

1318 0 0 Reductive_amination C7512 "WKWSTPQELFYSBR-UHFFFAOYSA-N"

 Success  registered route 917!

1319 0 0 Sp3-sp2_Suzuki_coupling C4805 "LZCWESDQKOJPRL-UHFFFAOYSA-N"

 Success  registered route 918!

1320 0 0 Amidation C5313 "BSIJAQBIVQHURV-UHFFFAOYSA-N"

 Success  registered route 919!

1321 0 0 Amidation C38131 "BRBJVKBLSPYJTQ-UHFFFAOYSA-N"

 Success  registered route 920!

1322 0 0 Amidation C7149 "SBCUWSBVVFFXMM-UHFFFAOYSA-N"

 Success  registered route 921!

1323 0 0 Alpha_alkylation_of_ketone C13570 "OSHPMDKWLAXVLW-UHFFFAOYSA-N"

reactants =
[285770, 285771]

product = C13570 "OSHPMDKWLAXVLW-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ketone!

1323 1 0 Conjugate_addition_of_Grignard_(Gilman_reagents) C13570 "OSHPMDKWLAXVLW-UHFFFAOYSA-N"

reactants =
[285772, 285773]

product = C13570 "OSHPMDKWLAXVLW-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Conjugate_addition_of_Grignard_(Gilman_reagents)!

1323 2 0 Alpha_alkylation_of_ketone C13570 "OSHPMDKWLAXVLW-UHFFFAOYSA-N"

reactants =
[285771, 285774]

product = C13570 "OSHPMDKWLAXVLW-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ketone!

1323 3 0 Alpha_alkylation_of_ketone C13570 "OSHPMDKWLAXVLW-UHFFFAOYSA-N"

reactants =
[285771, 285775]

product = C13570 "OSHPMDKWLAXVLW-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ketone!

1323 4 0 Conjugate_addition_of_organolithium_(Gilman_reagent) C13570 "OSHPMDKWLAXVLW-UHFFFAOYSA-N"

reactants =
[285684, 285773]

product = C13570 "OSHPMDKWLAXVLW-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Conjugate_addition_of_organolithium_(Gilman_reagent)!

1324 0 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C11216 "UNJDLWREQAMHBE-UHFFFAOYSA-N"

 Success  registered route 922!

1325 0 0 Amine_alkylation C4766 "RFJGYVZIVNNSCI-UHFFFAOYSA-N"

reactants =
[284139, 285778]

product = C4766 "RFJGYVZIVNNSCI-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

1325 1 0 Paal-Knorr_pyrazole_synthesis C4766 "RFJGYVZIVNNSCI-UHFFFAOYSA-N"

reactants =
[285779, 285780]

product = C4766 "RFJGYVZIVNNSCI-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Paal-Knorr_pyrazole_synthesis!

1325 2 0 N-Boc_deprotection C4766 "RFJGYVZIVNNSCI-UHFFFAOYSA-N"

 Success  registered route 923!

1326 0 0 Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide C2044 "ZCDJYTCOFFVDFA-UHFFFAOYSA-N"

reactants =
[284772, 285030]

product = C2044 "ZCDJYTCOFFVDFA-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide!

1326 1 0 Sp3-sp2_Suzuki_coupling C2044 "ZCDJYTCOFFVDFA-UHFFFAOYSA-N"

 Success  registered route 924!

1327 0 0 Ester_amidation C7417 "UHCYCFVXMGQYLA-UHFFFAOYSA-N"

1327 1 0 Amidation C7417 "UHCYCFVXMGQYLA-UHFFFAOYSA-N"

 Success  registered route 925!

1328 0 0 Amine_alkylation C12946 "OMEWLDYIFBMQQV-UHFFFAOYSA-N"

reactants =
[285785, 285786]

product = C12946 "OMEWLDYIFBMQQV-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

1328 1 0 Buchwald-Hartwig_amination C12946 "OMEWLDYIFBMQQV-UHFFFAOYSA-N"

 Success  registered route 926!

1329 0 0 Amidation C25127 "VMVJFLKGCWCHKW-UHFFFAOYSA-N"

 Success  registered route 927!

1330 0 0 Amidation C10845 "QHXZCCYDVDNOIS-UHFFFAOYSA-N"

 Success  registered route 928!

1331 0 0 Amidation C23295 "UQGFVTTVRVRYFR-UHFFFAOYSA-N"

 Success  registered route 929!

1332 0 0 Amidation C25702 "VLNCLLLQZBZMCZ-UHFFFAOYSA-N"

 Success  registered route 930!

1333 0 0 Amidation C1719 "CQSLSCYKXAPOGE-UHFFFAOYSA-N"

 Success  registered route 931!

1334 0 0 Sulfonamide_Schotten-Baumann_with_amine_(intermolecular) C7660 "NEEWPLZUMQNHBI-UHFFFAOYSA-N"

reactants =
[284489, 285794]

product = C7660 "NEEWPLZUMQNHBI-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sulfonamide_Schotten-Baumann_with_amine_(intermolecular)!

1334 1 0 Formation_of_sulfonamide_from_halide_-_Shavnya_reaction C7660 "NEEWPLZUMQNHBI-UHFFFAOYSA-N"

reactants =
[284490, 285794]

product = C7660 "NEEWPLZUMQNHBI-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Formation_of_sulfonamide_from_halide_-_Shavnya_reaction!

1334 2 0 Formation_of_sulfonamide_from_halide_-_Shavnya_reaction C7660 "NEEWPLZUMQNHBI-UHFFFAOYSA-N"

reactants =
[284079, 285794]

product = C7660 "NEEWPLZUMQNHBI-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Formation_of_sulfonamide_from_halide_-_Shavnya_reaction!

1334 3 0 Formation_of_sulfonamide_from_halide_-_Shavnya_reaction C7660 "NEEWPLZUMQNHBI-UHFFFAOYSA-N"

reactants =
[284491, 285794]

product = C7660 "NEEWPLZUMQNHBI-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Formation_of_sulfonamide_from_halide_-_Shavnya_reaction!

1334 4 0 Sulfonamide_Schotten-Baumann_with_amine_(intermolecular) C7660 "NEEWPLZUMQNHBI-UHFFFAOYSA-N"

reactants =
[284492, 285794]

product = C7660 "NEEWPLZUMQNHBI-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sulfonamide_Schotten-Baumann_with_amine_(intermolecular)!

1335 0 0 Amine_alkylation C43550 "ZBXDTHJRDBKMNJ-UHFFFAOYSA-N"

reactants =
[285795, 285796]

product = C43550 "ZBXDTHJRDBKMNJ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

1335 1 0 Amidation C43550 "ZBXDTHJRDBKMNJ-UHFFFAOYSA-N"

 Success  registered route 932!

1336 0 0 Aryl_halide_to_aniline C20907 "XNZBNQSOCXCBBB-UHFFFAOYSA-N"

reactants =
[285799]

product = C20907 "XNZBNQSOCXCBBB-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Aryl_halide_to_aniline!

1336 1 0 Amidation C20907 "XNZBNQSOCXCBBB-UHFFFAOYSA-N"

 Success  registered route 933!

1337 0 0 Amine_alkylation C760 "VJCYTBKJYKZSPV-UHFFFAOYSA-N"

reactants =
[285099, 285802]

product = C760 "VJCYTBKJYKZSPV-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

1337 1 0 Amine_alkylation C760 "VJCYTBKJYKZSPV-UHFFFAOYSA-N"

reactants =
[285802, 285803]

product = C760 "VJCYTBKJYKZSPV-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

1337 2 0 Amine_alkylation C760 "VJCYTBKJYKZSPV-UHFFFAOYSA-N"

reactants =
[284510, 285802]

product = C760 "VJCYTBKJYKZSPV-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

1337 3 0 Amine_alkylation C760 "VJCYTBKJYKZSPV-UHFFFAOYSA-N"

reactants =
[285100, 285802]

product = C760 "VJCYTBKJYKZSPV-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

1337 4 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C760 "VJCYTBKJYKZSPV-UHFFFAOYSA-N"

 Success  registered route 934!

1338 0 0 Alpha_alkylation_of_aldehyde C17612 "HUQKWYASCUHDLP-UHFFFAOYSA-N"

reactants =
[283280, 285804]

product = C17612 "HUQKWYASCUHDLP-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_aldehyde!

1338 1 0 Robinson-Gabriel_imidazole_synthesis_(with_amide_NH) C17612 "HUQKWYASCUHDLP-UHFFFAOYSA-N"

reactants =
[285805, 285806]

product = C17612 "HUQKWYASCUHDLP-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Robinson-Gabriel_imidazole_synthesis_(with_amide_NH)!

1338 2 0 Alpha_alkylation_of_aldehyde C17612 "HUQKWYASCUHDLP-UHFFFAOYSA-N"

reactants =
[283127, 285804]

product = C17612 "HUQKWYASCUHDLP-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_aldehyde!

1338 3 0 Ethenyl_to_formyl C17612 "HUQKWYASCUHDLP-UHFFFAOYSA-N"

reactants =
[285807]

product = C17612 "HUQKWYASCUHDLP-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Ethenyl_to_formyl!

1338 4 0 TEMPO_oxidation C17612 "HUQKWYASCUHDLP-UHFFFAOYSA-N"

reactants =
[285808]

product = C17612 "HUQKWYASCUHDLP-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: TEMPO_oxidation!

1339 0 0 Sp2-sp2_Negishi_coupling_(intermolecular) C6610 "QMSHCDDWKOOQIQ-UHFFFAOYSA-N"

reactants =
[285809, 285810]

product = C6610 "QMSHCDDWKOOQIQ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sp2-sp2_Negishi_coupling_(intermolecular)!

1339 1 0 Hantzsch_thiazole_synthesis C6610 "QMSHCDDWKOOQIQ-UHFFFAOYSA-N"

reactants =
[285811, 285812]

product = C6610 "QMSHCDDWKOOQIQ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Hantzsch_thiazole_synthesis!

1339 2 0 Sp2-sp2_Suzuki_coupling C6610 "QMSHCDDWKOOQIQ-UHFFFAOYSA-N"

 Success  registered route 935!

1340 0 0 Ester_amidation C92920 "IZKZLQCBDVJIRW-UHFFFAOYSA-N"

 Success  registered route 936!

1341 0 0 Amidation C28323 "XRCDSEZPXYCOLD-UHFFFAOYSA-N"

 Success  registered route 937!

1342 0 0 Reductive_amination C92925 "DVPZBLCJPRLATH-UHFFFAOYSA-N"

 Success  registered route 938!

1343 0 0 Alpha_alkylation_of_ketone C4658 "HWBLWNNWIGXBNO-UHFFFAOYSA-N"

reactants =
[283280, 285819]

product = C4658 "HWBLWNNWIGXBNO-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ketone!

1343 1 0 Alpha_alkylation_of_ketone C4658 "HWBLWNNWIGXBNO-UHFFFAOYSA-N"

reactants =
[285820]

product = C4658 "HWBLWNNWIGXBNO-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ketone!

1343 2 0 N-Boc_deprotection C4658 "HWBLWNNWIGXBNO-UHFFFAOYSA-N"

 Success  registered route 939!

1344 0 0 1,2,4-Oxadiazole_synthesis_(amidoxime_+_carboxylate) C18114 "UHISTFBIGPGRMK-UHFFFAOYSA-N"

reactants =
[285822, 285823]

product = C18114 "UHISTFBIGPGRMK-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: 1,2,4-Oxadiazole_synthesis_(amidoxime_+_carboxylate)!

1344 1 0 1,2,4-Oxadiazole_synthesis_(amidoxime_+_carboxylate) C18114 "UHISTFBIGPGRMK-UHFFFAOYSA-N"

reactants =
[285823, 285824]

product = C18114 "UHISTFBIGPGRMK-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: 1,2,4-Oxadiazole_synthesis_(amidoxime_+_carboxylate)!

1344 2 0 1,2,4-Oxadiazole_synthesis_(nitrile_+_carboxylic_acid) C18114 "UHISTFBIGPGRMK-UHFFFAOYSA-N"

reactants =
[285822, 285825]

product = C18114 "UHISTFBIGPGRMK-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: 1,2,4-Oxadiazole_synthesis_(nitrile_+_carboxylic_acid)!

1344 3 0 1,2,4-Oxadiazole_synthesis_(amidoxime_+_carboxylate) C18114 "UHISTFBIGPGRMK-UHFFFAOYSA-N"

reactants =
[285823, 285826]

product = C18114 "UHISTFBIGPGRMK-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: 1,2,4-Oxadiazole_synthesis_(amidoxime_+_carboxylate)!

1344 4 0 Chan-Lam_coupling_(amination) C18114 "UHISTFBIGPGRMK-UHFFFAOYSA-N"

reactants =
[283259, 285827]

product = C18114 "UHISTFBIGPGRMK-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Chan-Lam_coupling_(amination)!

1345 0 0 Amidation C22220 "LDOKSSWQCPKARK-UHFFFAOYSA-N"

 Success  registered route 940!

1346 0 0 Amidation C13262 "ZKAJGRJFQFGLLL-UHFFFAOYSA-N"

 Success  registered route 941!

1347 0 0 Nucleophilic_substitution_with_thiol C8064 "BNWUDFFUSWDMML-UHFFFAOYSA-N"

reactants =
[285829, 285830]

product = C8064 "BNWUDFFUSWDMML-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Nucleophilic_substitution_with_thiol!

1347 1 0 Alpha_alkylation_of_ester/amide C8064 "BNWUDFFUSWDMML-UHFFFAOYSA-N"

reactants =
[285021, 285831]

product = C8064 "BNWUDFFUSWDMML-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ester/amide!

1347 2 0 Ester_amidation C8064 "BNWUDFFUSWDMML-UHFFFAOYSA-N"

 Success  registered route 942!

1348 0 0 Amidation C4774 "PYBOZBRLIMDYOY-UHFFFAOYSA-N"

 Success  registered route 943!

1349 0 0 Amidation C5356 "TXUZFYUKGKNOMI-UHFFFAOYSA-N"

 Success  registered route 944!

1350 0 0 Chan-Lam_coupling_of_amides,_sulfonamides,_and_imides C31916 "QUEIHHGXYURJMF-UHFFFAOYSA-N"

reactants =
[283259, 285835]

product = C31916 "QUEIHHGXYURJMF-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Chan-Lam_coupling_of_amides,_sulfonamides,_and_imides!

1350 1 0 Amidation C31916 "QUEIHHGXYURJMF-UHFFFAOYSA-N"

 Success  registered route 945!

1351 0 0 Amine_alkylation C2616 "HPDGQSVLUHUNOU-UHFFFAOYSA-N"

reactants =
[285838]

product = C2616 "HPDGQSVLUHUNOU-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

1351 1 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C2616 "HPDGQSVLUHUNOU-UHFFFAOYSA-N"

1351 2 0 Amine_alkylation C2616 "HPDGQSVLUHUNOU-UHFFFAOYSA-N"

reactants =
[285840]

product = C2616 "HPDGQSVLUHUNOU-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

1351 3 0 Amine_alkylation C2616 "HPDGQSVLUHUNOU-UHFFFAOYSA-N"

reactants =
[285841]

product = C2616 "HPDGQSVLUHUNOU-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

1351 4 0 Amide_to_amine_reduction C2616 "HPDGQSVLUHUNOU-UHFFFAOYSA-N"

reactants =
[26520]

product = C2616 "HPDGQSVLUHUNOU-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amide_to_amine_reduction!

1352 0 0 Amidation C13635 "DSHXVVHRVRWWBZ-UHFFFAOYSA-N"

 Success  registered route 946!

1353 0 0 Amidation C22036 "IXOANNXJRWRLSD-UHFFFAOYSA-N"

 Success  registered route 947!

1354 0 0 Nucleophilic_substitution_with_thiol C31930 "RBPJKPBEDYIOQL-UHFFFAOYSA-N"

reactants =
[285845, 285846]

product = C31930 "RBPJKPBEDYIOQL-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Nucleophilic_substitution_with_thiol!

1354 1 0 Nucleophilic_substitution_with_thiol C31930 "RBPJKPBEDYIOQL-UHFFFAOYSA-N"

reactants =
[285845, 285847]

product = C31930 "RBPJKPBEDYIOQL-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Nucleophilic_substitution_with_thiol!

1354 2 0 Amine_alkylation C31930 "RBPJKPBEDYIOQL-UHFFFAOYSA-N"

reactants =
[285848, 285849]

product = C31930 "RBPJKPBEDYIOQL-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

1354 3 0 Amine_alkylation C31930 "RBPJKPBEDYIOQL-UHFFFAOYSA-N"

reactants =
[285849, 285850]

product = C31930 "RBPJKPBEDYIOQL-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

1354 4 0 Amine_alkylation C31930 "RBPJKPBEDYIOQL-UHFFFAOYSA-N"

reactants =
[285849, 285851]

product = C31930 "RBPJKPBEDYIOQL-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

1355 0 0 Amine_alkylation C2536 "OKSDMMSSFWTMDL-UHFFFAOYSA-N"

reactants =
[284542, 285852]

product = C2536 "OKSDMMSSFWTMDL-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

1355 1 0 Elimination_reaction C2536 "OKSDMMSSFWTMDL-UHFFFAOYSA-N"

reactants =
[285853]

product = C2536 "OKSDMMSSFWTMDL-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Elimination_reaction!

1355 2 0 Amine_alkylation C2536 "OKSDMMSSFWTMDL-UHFFFAOYSA-N"

reactants =
[284542, 285854]

product = C2536 "OKSDMMSSFWTMDL-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

1355 3 0 Elimination_reaction C2536 "OKSDMMSSFWTMDL-UHFFFAOYSA-N"

reactants =
[285855]

product = C2536 "OKSDMMSSFWTMDL-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Elimination_reaction!

1355 4 0 Elimination_reaction C2536 "OKSDMMSSFWTMDL-UHFFFAOYSA-N"

reactants =
[285856]

product = C2536 "OKSDMMSSFWTMDL-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Elimination_reaction!

1356 0 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C5401 "MWSDBUDWLOMHAE-UHFFFAOYSA-N"

1356 1 0 Simmons-Smith_reaction C5401 "MWSDBUDWLOMHAE-UHFFFAOYSA-N"

reactants =
[5399]

product = C5401 "MWSDBUDWLOMHAE-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Simmons-Smith_reaction!

1356 2 0 Reductive_amination C5401 "MWSDBUDWLOMHAE-UHFFFAOYSA-N"

1356 3 0 Corey-House_synthesis_(intermolecular) C5401 "MWSDBUDWLOMHAE-UHFFFAOYSA-N"

reactants =
[285751, 285859]

product = C5401 "MWSDBUDWLOMHAE-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Corey-House_synthesis_(intermolecular)!

1356 4 0 Amine_alkylation C5401 "MWSDBUDWLOMHAE-UHFFFAOYSA-N"

reactants =
[285860]

product = C5401 "MWSDBUDWLOMHAE-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

1357 0 0 Sp2-sp2_Suzuki_coupling C3732 "ZXOXPYYAVFDCDK-UHFFFAOYSA-N"

 Success  registered route 948!

1358 0 0 Amidation C94229 "UGODLXNSYTXUEC-UHFFFAOYSA-N"

 Success  registered route 949!

1359 0 0 Ozonolysis_(intermolecular) C8903 "UKLVECSDHSHYKS-UHFFFAOYSA-N"

reactants =
[285864]

product = C8903 "UKLVECSDHSHYKS-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Ozonolysis_(intermolecular)!

1359 1 0 N-Ac_deprotection C8903 "UKLVECSDHSHYKS-UHFFFAOYSA-N"

reactants =
[285865]

product = C8903 "UKLVECSDHSHYKS-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: N-Ac_deprotection!

1359 2 0 Ozonolysis_(intermolecular) C8903 "UKLVECSDHSHYKS-UHFFFAOYSA-N"

reactants =
[285864]

product = C8903 "UKLVECSDHSHYKS-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Ozonolysis_(intermolecular)!

1359 3 0 Amine_alkylation C8903 "UKLVECSDHSHYKS-UHFFFAOYSA-N"

reactants =
[283065, 285866]

product = C8903 "UKLVECSDHSHYKS-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

1359 4 0 Amine_alkylation C8903 "UKLVECSDHSHYKS-UHFFFAOYSA-N"

reactants =
[283065, 285867]

product = C8903 "UKLVECSDHSHYKS-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

1360 0 0 Amidation C1353 "LOUAUNMHZDTLHZ-UHFFFAOYSA-N"

 Success  registered route 950!

1361 0 0 Buchwald-Hartwig_amination C4546 "JCJVPBFEEQLMPB-UHFFFAOYSA-N"

 Success  registered route 951!

1362 0 0 Formation_of_urea_from_two_amines C14073 "XGNYIJRUPNCYBP-UHFFFAOYSA-N"

 Success  registered route 952!

1363 0 0 Van_Leusen_imidazole_synthesis C1841 "VEMKUJOKEUNKTH-UHFFFAOYSA-N"

reactants =
[283156, 283755, 285871]

product = C1841 "VEMKUJOKEUNKTH-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Van_Leusen_imidazole_synthesis!

1363 1 0 Amine_alkylation C1841 "VEMKUJOKEUNKTH-UHFFFAOYSA-N"

reactants =
[283757, 285872]

product = C1841 "VEMKUJOKEUNKTH-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

1363 2 0 N-Boc_deprotection C1841 "VEMKUJOKEUNKTH-UHFFFAOYSA-N"

 Success  registered route 953!

1364 0 0 Amidation C6001 "WWTKBVZCSYFAEN-UHFFFAOYSA-N"

 Success  registered route 954!

1365 0 0 Steglich_esterification C29374 "LVVJGEHAZDHVAF-UHFFFAOYSA-N"

 Success  registered route 955!

1366 0 0 Amidation C87747 "VAVVBUAZZDYRRD-UHFFFAOYSA-N"

 Success  registered route 956!

1367 0 0 Chan-Lam_coupling_(amination) C6254 "LCEGRNJGQNNSKF-UHFFFAOYSA-N"

reactants =
[284601, 285876]

product = C6254 "LCEGRNJGQNNSKF-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Chan-Lam_coupling_(amination)!

1367 1 0 Buchwald-Hartwig_amination C6254 "LCEGRNJGQNNSKF-UHFFFAOYSA-N"

 Success  registered route 957!

1368 0 0 Amidation C4572 "ATACZHSZICCATA-UHFFFAOYSA-N"

 Success  registered route 958!

1369 0 0 Amidation C16798 "RRTBNFKCVDLBIR-UHFFFAOYSA-N"

 Success  registered route 959!

1370 0 0 Formation_of_sulfonamide_from_halide_-_Shavnya_reaction C12436 "DUYGGZWMEYALFM-UHFFFAOYSA-N"

reactants =
[284266, 285879]

product = C12436 "DUYGGZWMEYALFM-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Formation_of_sulfonamide_from_halide_-_Shavnya_reaction!

1370 1 0 Formation_of_sulfonamide_from_halide_-_Shavnya_reaction C12436 "DUYGGZWMEYALFM-UHFFFAOYSA-N"

reactants =
[284266, 285880]

product = C12436 "DUYGGZWMEYALFM-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Formation_of_sulfonamide_from_halide_-_Shavnya_reaction!

1370 2 0 Formation_of_sulfonamide_from_halide_-_Shavnya_reaction C12436 "DUYGGZWMEYALFM-UHFFFAOYSA-N"

reactants =
[284266, 284512]

product = C12436 "DUYGGZWMEYALFM-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Formation_of_sulfonamide_from_halide_-_Shavnya_reaction!

1370 3 0 Formation_of_sulfonamide_from_boronic_and_amine C12436 "DUYGGZWMEYALFM-UHFFFAOYSA-N"

reactants =
[284266, 285881]

product = C12436 "DUYGGZWMEYALFM-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Formation_of_sulfonamide_from_boronic_and_amine!

1370 4 0 Chan-Lam_coupling_of_amides,_sulfonamides,_and_imides C12436 "DUYGGZWMEYALFM-UHFFFAOYSA-N"

reactants =
[283259, 285882]

product = C12436 "DUYGGZWMEYALFM-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Chan-Lam_coupling_of_amides,_sulfonamides,_and_imides!

1371 0 0 Reductive_amination C15324 "IXLQNKZHEBQVQI-UHFFFAOYSA-N"

 Success  registered route 960!

1372 0 0 Amidation C4102 "IQWZYMQRGQLZOU-UHFFFAOYSA-N"

 Success  registered route 961!

1373 0 0 Amidation C3511 "GFAIQXCMYIWPBA-UHFFFAOYSA-N"

 Success  registered route 962!

1374 0 0 Amidation C15369 "PFGLLURXEHPOCK-UHFFFAOYSA-N"

 Success  registered route 963!

1375 0 0 Amidation C12140 "IFWHXWDSJNOWHX-UHFFFAOYSA-N"

 Success  registered route 964!

1376 0 0 Amidation C5284 "ANGWTGNRJJVGJX-UHFFFAOYSA-N"

 Success  registered route 965!

1377 0 0 Amidation C12512 "CNWCZZAACSBMEQ-UHFFFAOYSA-N"

 Success  registered route 966!

1378 0 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C6122 "PRRYMKYLPMALBW-UHFFFAOYSA-N"

1378 1 0 Amide_to_amine_reduction C6122 "PRRYMKYLPMALBW-UHFFFAOYSA-N"

reactants =
[285891]

product = C6122 "PRRYMKYLPMALBW-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amide_to_amine_reduction!

1378 2 0 Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide C6122 "PRRYMKYLPMALBW-UHFFFAOYSA-N"

reactants =
[285892]

product = C6122 "PRRYMKYLPMALBW-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide!

1378 3 0 Reductive_amination C6122 "PRRYMKYLPMALBW-UHFFFAOYSA-N"

1378 4 0 Buchwald-Hartwig_amination C6122 "PRRYMKYLPMALBW-UHFFFAOYSA-N"

1379 0 0 Sp3-sp2_Macmillan_coupling_with_bromide_(intermolecular) C9551 "TUJBPBYAHMFXCP-UHFFFAOYSA-N"

reactants =
[283598, 285895]

product = C9551 "TUJBPBYAHMFXCP-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sp3-sp2_Macmillan_coupling_with_bromide_(intermolecular)!

1379 1 0 Sp3-sp2_Macmillan_coupling_with_chloride_(intermolecular) C9551 "TUJBPBYAHMFXCP-UHFFFAOYSA-N"

reactants =
[283595, 285896]

product = C9551 "TUJBPBYAHMFXCP-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sp3-sp2_Macmillan_coupling_with_chloride_(intermolecular)!

1379 2 0 Minisci_reaction_with_carboxylic_acid_(intermolecular) C9551 "TUJBPBYAHMFXCP-UHFFFAOYSA-N"

reactants =
[285897, 285898]

product = C9551 "TUJBPBYAHMFXCP-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Minisci_reaction_with_carboxylic_acid_(intermolecular)!

1379 3 0 Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide C9551 "TUJBPBYAHMFXCP-UHFFFAOYSA-N"

reactants =
[284286, 285895]

product = C9551 "TUJBPBYAHMFXCP-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide!

1379 4 0 Alpha_alkylation_of_aldehyde C9551 "TUJBPBYAHMFXCP-UHFFFAOYSA-N"

reactants =
[283111, 285899]

product = C9551 "TUJBPBYAHMFXCP-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_aldehyde!

1380 0 0 Amidation C7845 "JDNYYFHSMGZRFL-UHFFFAOYSA-N"

 Success  registered route 967!

1381 0 0 Ugi_reaction C1287 "QKDZKLODHGSJHY-UHFFFAOYSA-N"

reactants =
[282920, 283042, 285901, 285902]

product = C1287 "QKDZKLODHGSJHY-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Ugi_reaction!

1381 1 0 Ester_amidation C1287 "QKDZKLODHGSJHY-UHFFFAOYSA-N"

 Success  registered route 968!

1382 0 0 Aziridine_+_amine_coupling C9362 "JJHKJZKHZJQZCI-UHFFFAOYSA-N"

reactants =
[285198, 285904]

product = C9362 "JJHKJZKHZJQZCI-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Aziridine_+_amine_coupling!

1382 1 0 Amidation C9362 "JJHKJZKHZJQZCI-UHFFFAOYSA-N"

1382 1 1 Aziridine_+_amine_coupling C285905 "WHVAYDLSHNKCQS-UHFFFAOYSA-N"

reactants =
[285198, 285907]

product = C285905 "WHVAYDLSHNKCQS-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Aziridine_+_amine_coupling!

1382 2 0 Amidation C9362 "JJHKJZKHZJQZCI-UHFFFAOYSA-N"

 Success  registered route 969!

1383 0 0 Friedel-Crafts_acylation C10634 "TXAALMFVFUTAOP-UHFFFAOYSA-N"

reactants =
[284929, 285910]

product = C10634 "TXAALMFVFUTAOP-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Friedel-Crafts_acylation!

1383 1 0 Ketone_from_acid_chloride_(Gilman_reagent,_intermolecular) C10634 "TXAALMFVFUTAOP-UHFFFAOYSA-N"

reactants =
[285911, 285912]

product = C10634 "TXAALMFVFUTAOP-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Ketone_from_acid_chloride_(Gilman_reagent,_intermolecular)!

1383 2 0 Swern_oxidation C10634 "TXAALMFVFUTAOP-UHFFFAOYSA-N"

reactants =
[285913]

product = C10634 "TXAALMFVFUTAOP-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Swern_oxidation!

1383 3 0 Dess-Martin_oxidation C10634 "TXAALMFVFUTAOP-UHFFFAOYSA-N"

reactants =
[285913]

product = C10634 "TXAALMFVFUTAOP-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Dess-Martin_oxidation!

1383 4 0 Hydrolysis_of_enol_ether C10634 "TXAALMFVFUTAOP-UHFFFAOYSA-N"

reactants =
[285914]

product = C10634 "TXAALMFVFUTAOP-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Hydrolysis_of_enol_ether!

1384 0 0 Amidation C3504 "RWEBVRKWAUWERV-UHFFFAOYSA-N"

 Success  registered route 970!

1385 0 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C9126 "SYHGTEQZJUIFDX-UHFFFAOYSA-N"

 Success  registered route 971!

1386 0 0 Formation_of_urea_from_two_amines C3532 "RCYHJILZPFRWLW-UHFFFAOYSA-N"

 Success  registered route 972!

1387 0 0 Amidation C20145 "GYZAOFILUIIAKQ-UHFFFAOYSA-N"

 Success  registered route 973!

1388 0 0 N-Boc_deprotection C9376 "FWKKRHSZSZHMCS-UHFFFAOYSA-N"

 Success  registered route 974!

1389 0 0 Amidation C6132 "DQQDJWRXBCMXIH-UHFFFAOYSA-N"

 Success  registered route 975!

1390 0 0 Amidation C13629 "WQDYLJGBYWAYGW-UHFFFAOYSA-N"

 Success  registered route 976!

1391 0 0 Amidation C7092 "JPZZIQFEUYXBCW-UHFFFAOYSA-N"

 Success  registered route 977!

1392 0 0 Amidation C7116 "RTPIGKAAQCUSFW-UHFFFAOYSA-N"

 Success  registered route 978!

1393 0 0 Amidation C20058 "JQBYUAVAPLZUQX-UHFFFAOYSA-N"

 Success  registered route 979!

1394 0 0 Formation_of_urea_from_two_amines C6083 "SMFBGIJWOIHSTQ-UHFFFAOYSA-N"

 Success  registered route 980!

1395 0 0 Amidation C27918 "IBVLOOXRGBJCHW-UHFFFAOYSA-N"

 Success  registered route 981!

1396 0 0 Amidation C3827 "OJPVDAKSEAPTQE-UHFFFAOYSA-N"

 Success  registered route 982!

1397 0 0 Amidation C4812 "VLOGXOWERDMVRP-UHFFFAOYSA-N"

 Success  registered route 983!

1398 0 0 Hydrogenation_of_pyridine C2628 "NILYFVLXUNTUTG-UHFFFAOYSA-N"

reactants =
[6259]

product = C2628 "NILYFVLXUNTUTG-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Hydrogenation_of_pyridine!

1398 1 0 Imine_reduction_to_amine C2628 "NILYFVLXUNTUTG-UHFFFAOYSA-N"

reactants =
[285928]

product = C2628 "NILYFVLXUNTUTG-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Imine_reduction_to_amine!

1398 2 0 N-TFA_deprotection C2628 "NILYFVLXUNTUTG-UHFFFAOYSA-N"

reactants =
[285929]

product = C2628 "NILYFVLXUNTUTG-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: N-TFA_deprotection!

1398 3 0 Reductive_amination C2628 "NILYFVLXUNTUTG-UHFFFAOYSA-N"

1398 4 0 N-Boc_deprotection C2628 "NILYFVLXUNTUTG-UHFFFAOYSA-N"

1398 4 1 Hydrogenation_of_pyridine C285931 "UEFGARPPKJDIJQ-UHFFFAOYSA-N"

reactants =
[284603]

product = C285931 "UEFGARPPKJDIJQ-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Hydrogenation_of_pyridine!

1399 0 0 Amidation C4095 "MFZCMMKAORBXOZ-UHFFFAOYSA-N"

 Success  registered route 984!

1400 0 0 Amidation C1613 "LQRJFVLGKSJEGN-UHFFFAOYSA-N"

 Success  registered route 985!

1401 0 0 Carboxylic_acid_+_hydrazine_condensation C35844 "AWDDJZCLAJFCAI-UHFFFAOYSA-N"

reactants =
[283904, 285935]

product = C35844 "AWDDJZCLAJFCAI-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Carboxylic_acid_+_hydrazine_condensation!

1401 1 0 Amidation C35844 "AWDDJZCLAJFCAI-UHFFFAOYSA-N"

 Success  registered route 986!

1402 0 0 Alpha_alkylation_of_ketone C2388 "WCQICRGOXXDKIA-UHFFFAOYSA-N"

reactants =
[283759, 284646]

product = C2388 "WCQICRGOXXDKIA-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ketone!

1402 1 0 Alpha_alkylation_of_ketone C2388 "WCQICRGOXXDKIA-UHFFFAOYSA-N"

reactants =
[283758, 284646]

product = C2388 "WCQICRGOXXDKIA-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ketone!

1402 2 0 Alpha_alkylation_of_ketone C2388 "WCQICRGOXXDKIA-UHFFFAOYSA-N"

reactants =
[283761, 284646]

product = C2388 "WCQICRGOXXDKIA-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ketone!

1402 3 0 Ethenyl_to_formyl C2388 "WCQICRGOXXDKIA-UHFFFAOYSA-N"

reactants =
[285936]

product = C2388 "WCQICRGOXXDKIA-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Ethenyl_to_formyl!

1402 4 0 N-Boc_deprotection C2388 "WCQICRGOXXDKIA-UHFFFAOYSA-N"

 Success  registered route 987!

1403 0 0 Amine_alkylation C9590 "NSDGADWCIGGTNK-UHFFFAOYSA-N"

reactants =
[285938, 285939]

product = C9590 "NSDGADWCIGGTNK-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

1403 1 0 Amide_to_amine_reduction C9590 "NSDGADWCIGGTNK-UHFFFAOYSA-N"

reactants =
[285940]

product = C9590 "NSDGADWCIGGTNK-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amide_to_amine_reduction!

1403 2 0 Amine_alkylation C9590 "NSDGADWCIGGTNK-UHFFFAOYSA-N"

reactants =
[285941, 285942]

product = C9590 "NSDGADWCIGGTNK-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

1403 3 0 Amine_alkylation C9590 "NSDGADWCIGGTNK-UHFFFAOYSA-N"

reactants =
[285939, 285943]

product = C9590 "NSDGADWCIGGTNK-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

1403 4 0 Amine_alkylation C9590 "NSDGADWCIGGTNK-UHFFFAOYSA-N"

reactants =
[285153, 285941]

product = C9590 "NSDGADWCIGGTNK-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

1404 0 0 Amidation C10829 "YVLAVJGZJRKIEO-UHFFFAOYSA-N"

 Success  registered route 988!

1405 0 0 Amidation C8445 "NQGNDAMYFAXCMF-UHFFFAOYSA-N"

 Success  registered route 989!

1406 0 0 Sp2-sp2_Suzuki_coupling C6095 "CJKOILGHLOVXNN-UHFFFAOYSA-N"

 Success  registered route 990!

1407 0 0 Amidation C8457 "AEIDFRMVQVHORR-UHFFFAOYSA-N"

 Success  registered route 991!

1408 0 0 Amidation C10574 "YHYKEJKTQQPYIL-UHFFFAOYSA-N"

 Success  registered route 992!

1409 0 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C20144 "AOLCLQJMUNNQFC-UHFFFAOYSA-N"

 Success  registered route 993!

1410 0 0 Amidation C9522 "NCZRZHLAOIEOQJ-UHFFFAOYSA-N"

 Success  registered route 994!

1411 0 0 Amidation C3473 "FJKFFRDIVHDZAT-UHFFFAOYSA-N"

 Success  registered route 995!

1412 0 0 Amidation C7045 "KGGJPHPTENSXJT-UHFFFAOYSA-N"

 Success  registered route 996!

1413 0 0 Formation_of_urea_from_two_amines C10681 "LRTLCHQEZXDGPD-UHFFFAOYSA-N"

 Success  registered route 997!

1414 0 0 Amidation C21624 "NXHRTCNOEDZCPH-UHFFFAOYSA-N"

 Success  registered route 998!

1415 0 0 Amidation C7041 "SCPSUPJJEYGKII-UHFFFAOYSA-N"

 Success  registered route 999!

1416 0 0 Sp3-sp2_Suzuki_coupling C758 "GITLVNUSBOZLGB-UHFFFAOYSA-N"

 Success  registered route 1000!

1417 0 0 Amidation C7140 "WMMQWHGSTLBODB-UHFFFAOYSA-N"

 Success  registered route 1001!

1418 0 0 Amidation C39173 "STBXFODHUIMPAQ-UHFFFAOYSA-N"

 Success  registered route 1002!

1419 0 0 Buchwald-Hartwig_amination C1192 "GIKLQBAMNJOQJI-UHFFFAOYSA-N"

 Success  registered route 1003!

1420 0 0 Amidation C4096 "ALNNKLRFJSRBFH-UHFFFAOYSA-N"

 Success  registered route 1004!

1421 0 0 Amidation C1392 "OLRBJBOVACWGSV-UHFFFAOYSA-N"

 Success  registered route 1005!

1422 0 0 Amidation C10571 "GEZPFGWIPNSGAO-UHFFFAOYSA-N"

 Success  registered route 1006!

1423 0 0 Chan-Lam_coupling_(amination) C736 "AJEUJXWLOADTKA-UHFFFAOYSA-N"

reactants =
[283065, 283978]

product = C736 "AJEUJXWLOADTKA-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Chan-Lam_coupling_(amination)!

1423 1 0 N-nucleophilic_aromatic_substitution C736 "AJEUJXWLOADTKA-UHFFFAOYSA-N"

 Success  registered route 1007!

1424 0 0 Formation_of_carbamate_from_amine_and_alcohol C34673 "XHJOMYXOFNVJDG-UHFFFAOYSA-N"

reactants =
[284612, 285967]

product = C34673 "XHJOMYXOFNVJDG-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Formation_of_carbamate_from_amine_and_alcohol!

1424 1 0 Amidation C34673 "XHJOMYXOFNVJDG-UHFFFAOYSA-N"

1424 2 0 Barton_deoxygenation_(secondary) C34673 "XHJOMYXOFNVJDG-UHFFFAOYSA-N"

reactants =
[285969]

product = C34673 "XHJOMYXOFNVJDG-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Barton_deoxygenation_(secondary)!

1424 3 0 N-Boc_protection_of_aliphatic_amines C34673 "XHJOMYXOFNVJDG-UHFFFAOYSA-N"

reactants =
[285967]

product = C34673 "XHJOMYXOFNVJDG-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: N-Boc_protection_of_aliphatic_amines!

1424 4 0 Ester_amidation C34673 "XHJOMYXOFNVJDG-UHFFFAOYSA-N"

1425 0 0 Amidation C1413 "DXSIWZMPELQDJX-UHFFFAOYSA-N"

 Success  registered route 1008!

1426 0 0 Amidation C29426 "PSEWAHCXXIBCFD-UHFFFAOYSA-N"

 Success  registered route 1009!

1427 0 0 Amidation C10567 "KRIKUQAZPILDPI-UHFFFAOYSA-N"

 Success  registered route 1010!

1428 0 0 N-nucleophilic_aromatic_substitution C4106 "UZZGPWHIXVWDFZ-UHFFFAOYSA-N"

 Success  registered route 1011!

1429 0 0 Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide C4752 "RGEDMRQLXNWHGH-UHFFFAOYSA-N"

reactants =
[284117, 285972]

product = C4752 "RGEDMRQLXNWHGH-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide!

1429 1 0 Sp3-sp2_Suzuki_coupling C4752 "RGEDMRQLXNWHGH-UHFFFAOYSA-N"

 Success  registered route 1012!

1430 0 0 Sp2-sp2_Suzuki_coupling C31957 "ZLIGEXAOTFMWIY-UHFFFAOYSA-N"

 Success  registered route 1013!

1431 0 0 Amidation C5996 "SBMHKWRHORHXQA-UHFFFAOYSA-N"

 Success  registered route 1014!

1432 0 0 Amidation C1322 "CEMHLKLHGFCDOP-UHFFFAOYSA-N"

 Success  registered route 1015!

1433 0 0 Amidation C10869 "PXFWFYMNCCXQPY-UHFFFAOYSA-N"

 Success  registered route 1016!

1434 0 0 Alpha_alkylation_of_ketone C11184 "RWLBYOFXTWUWOG-UHFFFAOYSA-N"

reactants =
[285976, 285977]

product = C11184 "RWLBYOFXTWUWOG-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ketone!

1434 1 0 Conjugate_addition_of_Grignard_(Gilman_reagents) C11184 "RWLBYOFXTWUWOG-UHFFFAOYSA-N"

reactants =
[285978, 285979]

product = C11184 "RWLBYOFXTWUWOG-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Conjugate_addition_of_Grignard_(Gilman_reagents)!

1434 2 0 Alpha_alkylation_of_ketone C11184 "RWLBYOFXTWUWOG-UHFFFAOYSA-N"

reactants =
[285976, 285980]

product = C11184 "RWLBYOFXTWUWOG-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ketone!

1434 3 0 Alpha_alkylation_of_ketone C11184 "RWLBYOFXTWUWOG-UHFFFAOYSA-N"

reactants =
[285976, 285981]

product = C11184 "RWLBYOFXTWUWOG-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ketone!

1434 4 0 Stille_coupling C11184 "RWLBYOFXTWUWOG-UHFFFAOYSA-N"

reactants =
[284354, 285982]

product = C11184 "RWLBYOFXTWUWOG-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Stille_coupling!

1435 0 0 Amidation C36823 "BNFWVHFVEZCPPF-UHFFFAOYSA-N"

 Success  registered route 1017!

1436 0 0 Amidation C2081 "PLNOJQJYNMYLML-UHFFFAOYSA-N"

 Success  registered route 1018!

1437 0 0 Amidation C29673 "JMSLYWOGHLUQQG-UHFFFAOYSA-N"

 Success  registered route 1019!

1438 0 0 Amidation C12270 "JDXDXEWAEPMSSN-UHFFFAOYSA-N"

 Success  registered route 1020!

1439 0 0 Amidation C1311 "ZJOXVMDCMBYBRX-UHFFFAOYSA-N"

 Success  registered route 1021!

1440 0 0 Amidation C14060 "UWPFTRXOTWJPHV-UHFFFAOYSA-N"

 Success  registered route 1022!

1441 0 0 Amidation C1526 "KRMYACDXSNMVGI-UHFFFAOYSA-N"

 Success  registered route 1023!

1442 0 0 Buchwald-Hartwig_amination C6123 "CPIBTNTZBHUDNS-UHFFFAOYSA-N"

1442 1 0 Amide_to_amine_reduction C6123 "CPIBTNTZBHUDNS-UHFFFAOYSA-N"

reactants =
[285991]

product = C6123 "CPIBTNTZBHUDNS-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amide_to_amine_reduction!

1442 2 0 Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide C6123 "CPIBTNTZBHUDNS-UHFFFAOYSA-N"

reactants =
[285992]

product = C6123 "CPIBTNTZBHUDNS-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide!

1442 3 0 Amine_alkylation C6123 "CPIBTNTZBHUDNS-UHFFFAOYSA-N"

reactants =
[285993]

product = C6123 "CPIBTNTZBHUDNS-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

1442 4 0 Buchwald-Hartwig_amination C6123 "CPIBTNTZBHUDNS-UHFFFAOYSA-N"

1443 0 0 Ester_amidation C29675 "VPRZTSOJFRBNDG-UHFFFAOYSA-N"

1443 1 0 Ester_amidation C29675 "VPRZTSOJFRBNDG-UHFFFAOYSA-N"

 Success  registered route 1024!

1444 0 0 Amidation C6021 "JKCAOPGWMBQAQI-UHFFFAOYSA-N"

 Success  registered route 1025!

1445 0 0 Amidation C33613 "PSPORJXVCMZQLN-UHFFFAOYSA-N"

 Success  registered route 1026!

1446 0 0 Amidation C29655 "KAWBAAHMUIIUOI-UHFFFAOYSA-N"

 Success  registered route 1027!

1447 0 0 Amine_alkylation C11209 "BTBDFXKRKUXPIR-UHFFFAOYSA-N"

reactants =
[285999, 286000]

product = C11209 "BTBDFXKRKUXPIR-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

1447 1 0 Amine_alkylation C11209 "BTBDFXKRKUXPIR-UHFFFAOYSA-N"

reactants =
[286000, 286001]

product = C11209 "BTBDFXKRKUXPIR-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

1447 2 0 Amine_alkylation C11209 "BTBDFXKRKUXPIR-UHFFFAOYSA-N"

reactants =
[286000, 286002]

product = C11209 "BTBDFXKRKUXPIR-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

1447 3 0 Amine_alkylation C11209 "BTBDFXKRKUXPIR-UHFFFAOYSA-N"

reactants =
[286000, 286003]

product = C11209 "BTBDFXKRKUXPIR-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

1447 4 0 Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide C11209 "BTBDFXKRKUXPIR-UHFFFAOYSA-N"

reactants =
[284178, 286004]

product = C11209 "BTBDFXKRKUXPIR-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide!

1448 0 0 Amidation C21032 "LUVPXWSUDOENCR-UHFFFAOYSA-N"

 Success  registered route 1028!

1449 0 0 Amidation C29667 "SPUMQZRDWYQOSZ-UHFFFAOYSA-N"

 Success  registered route 1029!

1450 0 0 Amidation C3817 "MUQXCGYUEZQXBU-UHFFFAOYSA-N"

 Success  registered route 1030!

1451 0 0 Amidation C8878 "BRFFIYADVJLQLC-UHFFFAOYSA-N"

 Success  registered route 1031!

1452 0 0 Amidation C4256 "JEOYIGKKGPMNOF-UHFFFAOYSA-N"

 Success  registered route 1032!

1453 0 0 Formation_of_urea_from_two_amines C12403 "CVVQZKTUYHICCC-UHFFFAOYSA-N"

 Success  registered route 1033!

1454 0 0 Riley_oxidation C2479 "RAFCYCDJOWOOAS-UHFFFAOYSA-N"

reactants =
[286009]

product = C2479 "RAFCYCDJOWOOAS-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Riley_oxidation!

1454 1 0 Buchwald-Hartwig_amidation_with_amide-like_nucleophile C2479 "RAFCYCDJOWOOAS-UHFFFAOYSA-N"

1454 2 0 N-Boc_deprotection C2479 "RAFCYCDJOWOOAS-UHFFFAOYSA-N"

 Success  registered route 1034!

1455 0 0 Amidation C22011 "VKVCIQZOMHUULA-UHFFFAOYSA-N"

 Success  registered route 1035!

1456 0 0 Amidation C11987 "JCQQJJVJANIEDC-UHFFFAOYSA-N"

 Success  registered route 1036!

1457 0 0 Amidation C1373 "HPZYIMYCTDBYEK-UHFFFAOYSA-N"

 Success  registered route 1037!

1458 0 0 Amidation C2418 "YKFCDWMBODQRLV-UHFFFAOYSA-N"

 Success  registered route 1038!

1459 0 0 Amidation C29842 "JTMLSSUHXRBMOA-UHFFFAOYSA-N"

 Success  registered route 1039!

1460 0 0 Amidation C11989 "LTXRWJYJSXHLHR-UHFFFAOYSA-N"

 Success  registered route 1040!

1461 0 0 Amidation C1418 "GSFKQOAHRINDLP-UHFFFAOYSA-N"

 Success  registered route 1041!

1462 0 0 Formation_of_urea_from_two_amines C5452 "ARNGBMWSRMXYCL-UHFFFAOYSA-N"

 Success  registered route 1042!

1463 0 0 Steglich_esterification C12012 "RTQXTGWAIMKSIN-UHFFFAOYSA-N"

 Success  registered route 1043!

1464 0 0 Minisci_reaction_with_carboxylic_acid_(intermolecular) C15060 "WTLZXJJEXLVAHW-UHFFFAOYSA-N"

reactants =
[283318, 286023]

product = C15060 "WTLZXJJEXLVAHW-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Minisci_reaction_with_carboxylic_acid_(intermolecular)!

1464 1 0 Formation_of_carbamate_from_amine_and_alcohol C15060 "WTLZXJJEXLVAHW-UHFFFAOYSA-N"

reactants =
[283304, 286024]

product = C15060 "WTLZXJJEXLVAHW-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Formation_of_carbamate_from_amine_and_alcohol!

1464 2 0 Ester_Schotten-Baumann C15060 "WTLZXJJEXLVAHW-UHFFFAOYSA-N"

reactants =
[283304, 286025]

product = C15060 "WTLZXJJEXLVAHW-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Ester_Schotten-Baumann!

1464 3 0 Amide_to_amine_reduction C15060 "WTLZXJJEXLVAHW-UHFFFAOYSA-N"

reactants =
[286026]

product = C15060 "WTLZXJJEXLVAHW-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amide_to_amine_reduction!

1464 4 0 Amide_to_amine_reduction C15060 "WTLZXJJEXLVAHW-UHFFFAOYSA-N"

reactants =
[286026]

product = C15060 "WTLZXJJEXLVAHW-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amide_to_amine_reduction!

1465 0 0 1,2,4-Oxadiazole_synthesis_(nitrile_+_carboxylic_acid) C39108 "NJZWNPRAQMACTE-UHFFFAOYSA-N"

reactants =
[283820, 286027]

product = C39108 "NJZWNPRAQMACTE-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: 1,2,4-Oxadiazole_synthesis_(nitrile_+_carboxylic_acid)!

1465 1 0 Sp2-sp2_Suzuki_coupling C39108 "NJZWNPRAQMACTE-UHFFFAOYSA-N"

1465 1 1 Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide C286029 "OWTYNKYHLUXBAN-UHFFFAOYSA-N"

reactants =
[284117, 286030]

product = C286029 "OWTYNKYHLUXBAN-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide!

1465 2 0 1,2,4-Oxadiazole_synthesis_(amidoxime_+_carboxylate) C39108 "NJZWNPRAQMACTE-UHFFFAOYSA-N"

reactants =
[286031, 286032]

product = C39108 "NJZWNPRAQMACTE-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: 1,2,4-Oxadiazole_synthesis_(amidoxime_+_carboxylate)!

1465 3 0 Minisci_reaction_with_carboxylic_acid_(intermolecular) C39108 "NJZWNPRAQMACTE-UHFFFAOYSA-N"

reactants =
[283820, 286033]

product = C39108 "NJZWNPRAQMACTE-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Minisci_reaction_with_carboxylic_acid_(intermolecular)!

1465 4 0 1,2,4-Oxadiazole_synthesis_(amidoxime_+_carboxylate) C39108 "NJZWNPRAQMACTE-UHFFFAOYSA-N"

reactants =
[286031, 286034]

product = C39108 "NJZWNPRAQMACTE-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: 1,2,4-Oxadiazole_synthesis_(amidoxime_+_carboxylate)!

1466 0 0 Hydroxy_to_fluoro C2375 "GOSRQBSVGZRPLI-UHFFFAOYSA-N"

reactants =
[286035]

product = C2375 "GOSRQBSVGZRPLI-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Hydroxy_to_fluoro!

1466 1 0 Tebbe-Petasis_olefination C2375 "GOSRQBSVGZRPLI-UHFFFAOYSA-N"

reactants =
[286036]

product = C2375 "GOSRQBSVGZRPLI-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Tebbe-Petasis_olefination!

1466 2 0 N-Boc_deprotection C2375 "GOSRQBSVGZRPLI-UHFFFAOYSA-N"

1466 2 1 Hydroxy_to_fluoro C286037 "MITZDCSIHPMXJG-UHFFFAOYSA-N"

reactants =
[286038]

product = C286037 "MITZDCSIHPMXJG-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Hydroxy_to_fluoro!

1466 3 0 Tebbe-Petasis_olefination C2375 "GOSRQBSVGZRPLI-UHFFFAOYSA-N"

reactants =
[286036]

product = C2375 "GOSRQBSVGZRPLI-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Tebbe-Petasis_olefination!

1466 4 0 Tebbe-Petasis_olefination C2375 "GOSRQBSVGZRPLI-UHFFFAOYSA-N"

reactants =
[286036]

product = C2375 "GOSRQBSVGZRPLI-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Tebbe-Petasis_olefination!

1467 0 0 Amidation C9322 "GDXDBEIGTXDPSA-UHFFFAOYSA-N"

 Success  registered route 1044!

1468 0 0 Buchwald-Hartwig_(thio)etherification C2531 "LSKCKISVBNXGCT-UHFFFAOYSA-N"

reactants =
[283304, 286041]

product = C2531 "LSKCKISVBNXGCT-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Buchwald-Hartwig_(thio)etherification!

1468 1 0 Buchwald-Hartwig_(thio)etherification C2531 "LSKCKISVBNXGCT-UHFFFAOYSA-N"

reactants =
[283304, 286042]

product = C2531 "LSKCKISVBNXGCT-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Buchwald-Hartwig_(thio)etherification!

1468 2 0 Nucleophilic_aromatic_substitution_(alcohol,_phenol,_water) C2531 "LSKCKISVBNXGCT-UHFFFAOYSA-N"

reactants =
[283304, 286041]

product = C2531 "LSKCKISVBNXGCT-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Nucleophilic_aromatic_substitution_(alcohol,_phenol,_water)!

1468 3 0 Mitsunobu_aryl_ether_synthesis C2531 "LSKCKISVBNXGCT-UHFFFAOYSA-N"

reactants =
[283304, 286043]

product = C2531 "LSKCKISVBNXGCT-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Mitsunobu_aryl_ether_synthesis!

1468 4 0 Mitsunobu_aryl_ether_synthesis C2531 "LSKCKISVBNXGCT-UHFFFAOYSA-N"

reactants =
[283304, 286043]

product = C2531 "LSKCKISVBNXGCT-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Mitsunobu_aryl_ether_synthesis!

1469 0 0 Alpha_alkylation_of_sulphones C1446 "CQUDLYKHYNSNKN-UHFFFAOYSA-N"

reactants =
[1442, 283127]

product = C1446 "CQUDLYKHYNSNKN-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_sulphones!

1469 1 0 Alpha_alkylation_of_sulphones C1446 "CQUDLYKHYNSNKN-UHFFFAOYSA-N"

reactants =
[1442, 283128]

product = C1446 "CQUDLYKHYNSNKN-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_sulphones!

1469 2 0 Alpha_alkylation_of_sulphones C1446 "CQUDLYKHYNSNKN-UHFFFAOYSA-N"

reactants =
[1442, 283280]

product = C1446 "CQUDLYKHYNSNKN-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_sulphones!

1469 3 0 Paal-Knorr_pyrazole_synthesis C1446 "CQUDLYKHYNSNKN-UHFFFAOYSA-N"

reactants =
[285779, 286044]

product = C1446 "CQUDLYKHYNSNKN-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Paal-Knorr_pyrazole_synthesis!

1469 4 0 Thioether_to_sulfone C1446 "CQUDLYKHYNSNKN-UHFFFAOYSA-N"

reactants =
[286045]

product = C1446 "CQUDLYKHYNSNKN-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Thioether_to_sulfone!

1470 0 0 Corey-House_synthesis_(intermolecular) C5412 "ZMWSPLIMPYHVRD-UHFFFAOYSA-N"

reactants =
[284456, 285752]

product = C5412 "ZMWSPLIMPYHVRD-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Corey-House_synthesis_(intermolecular)!

1470 1 0 Corey-House_synthesis_(intermolecular) C5412 "ZMWSPLIMPYHVRD-UHFFFAOYSA-N"

reactants =
[285751, 286046]

product = C5412 "ZMWSPLIMPYHVRD-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Corey-House_synthesis_(intermolecular)!

1470 2 0 Corey-House_synthesis_(intermolecular) C5412 "ZMWSPLIMPYHVRD-UHFFFAOYSA-N"

reactants =
[284457, 285752]

product = C5412 "ZMWSPLIMPYHVRD-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Corey-House_synthesis_(intermolecular)!

1470 3 0 Corey-House_synthesis_(intermolecular) C5412 "ZMWSPLIMPYHVRD-UHFFFAOYSA-N"

reactants =
[284455, 285752]

product = C5412 "ZMWSPLIMPYHVRD-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Corey-House_synthesis_(intermolecular)!

1470 4 0 Corey-House_synthesis_(intermolecular) C5412 "ZMWSPLIMPYHVRD-UHFFFAOYSA-N"

reactants =
[285751, 286046]

product = C5412 "ZMWSPLIMPYHVRD-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Corey-House_synthesis_(intermolecular)!

1471 0 0 Amidation C6603 "GCAKZJRFFNZIMB-UHFFFAOYSA-N"

 Success  registered route 1045!

1472 0 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C7674 "FVNJSOWLEHGULL-UHFFFAOYSA-N"

 Success  registered route 1046!

1473 0 0 Amidation C872 "DCPARYBUYLWDFA-UHFFFAOYSA-N"

 Success  registered route 1047!

1474 0 0 Ethenyl_to_formyl C8144 "CZSVMTMCGSPTJV-UHFFFAOYSA-N"

reactants =
[286050]

product = C8144 "CZSVMTMCGSPTJV-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Ethenyl_to_formyl!

1474 1 0 Aldehyde/ketone_to_alcohol_reduction C8144 "CZSVMTMCGSPTJV-UHFFFAOYSA-N"

reactants =
[286051]

product = C8144 "CZSVMTMCGSPTJV-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Aldehyde/ketone_to_alcohol_reduction!

1474 2 0 Alpha_alkylation_of_ketone C8144 "CZSVMTMCGSPTJV-UHFFFAOYSA-N"

reactants =
[286052, 286053]

product = C8144 "CZSVMTMCGSPTJV-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ketone!

1474 3 0 Alpha_alkylation_of_ketone C8144 "CZSVMTMCGSPTJV-UHFFFAOYSA-N"

reactants =
[286052, 286054]

product = C8144 "CZSVMTMCGSPTJV-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ketone!

1474 4 0 Ozonolysis_(intermolecular) C8144 "CZSVMTMCGSPTJV-UHFFFAOYSA-N"

reactants =
[286050]

product = C8144 "CZSVMTMCGSPTJV-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Ozonolysis_(intermolecular)!

1475 0 0 Amine_alkylation C8152 "CQGFXNLTTLLTME-UHFFFAOYSA-N"

reactants =
[283065, 286055]

product = C8152 "CQGFXNLTTLLTME-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

1475 1 0 Alpha_alkylation_of_ester/amide C8152 "CQGFXNLTTLLTME-UHFFFAOYSA-N"

reactants =
[286056, 286057]

product = C8152 "CQGFXNLTTLLTME-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ester/amide!

1475 2 0 Amine_alkylation C8152 "CQGFXNLTTLLTME-UHFFFAOYSA-N"

reactants =
[283065, 286058]

product = C8152 "CQGFXNLTTLLTME-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

1475 3 0 Mannich_reaction C8152 "CQGFXNLTTLLTME-UHFFFAOYSA-N"

reactants =
[283065, 286057]

product = C8152 "CQGFXNLTTLLTME-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Mannich_reaction!

1475 4 0 Alpha_alkylation_of_ester/amide C8152 "CQGFXNLTTLLTME-UHFFFAOYSA-N"

reactants =
[286057, 286059]

product = C8152 "CQGFXNLTTLLTME-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ester/amide!

1476 0 0 Amidation C83786 "YVEDCTAHRCLMTN-UHFFFAOYSA-N"

 Success  registered route 1048!

1477 0 0 Amidation C21087 "NLTCJEMUNHLQBH-UHFFFAOYSA-N"

 Warning  SMILES changed during compound registration: c1cc(C2CCNC2)[nH]n1 --> c1cc(C2CCNC2)n[nH]1!

 Success  registered route 1049!

1478 0 0 Alpha_alkylation_of_ketone C11213 "ABFQQZLULDEORM-UHFFFAOYSA-N"

reactants =
[286061, 286062]

product = C11213 "ABFQQZLULDEORM-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ketone!

1478 1 0 Alpha_alkylation_of_ketone C11213 "ABFQQZLULDEORM-UHFFFAOYSA-N"

reactants =
[286063, 286064]

product = C11213 "ABFQQZLULDEORM-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ketone!

1478 2 0 Alpha_alkylation_of_ketone C11213 "ABFQQZLULDEORM-UHFFFAOYSA-N"

reactants =
[285021, 286062]

product = C11213 "ABFQQZLULDEORM-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ketone!

1478 3 0 Alpha_alkylation_of_ketone C11213 "ABFQQZLULDEORM-UHFFFAOYSA-N"

reactants =
[286062, 286065]

product = C11213 "ABFQQZLULDEORM-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ketone!

1478 4 0 Alpha_alkylation_of_ketone C11213 "ABFQQZLULDEORM-UHFFFAOYSA-N"

reactants =
[286064, 286066]

product = C11213 "ABFQQZLULDEORM-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ketone!

1479 0 0 1,2,4-Oxadiazole_synthesis_(nitrile_+_carboxylic_acid) C936 "ADJXGRRNYYGIST-UHFFFAOYSA-N"

reactants =
[284799, 286067]

product = C936 "ADJXGRRNYYGIST-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: 1,2,4-Oxadiazole_synthesis_(nitrile_+_carboxylic_acid)!

1479 1 0 Minisci_reaction_with_carboxylic_acid_(intermolecular) C936 "ADJXGRRNYYGIST-UHFFFAOYSA-N"

reactants =
[286067, 286068]

product = C936 "ADJXGRRNYYGIST-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Minisci_reaction_with_carboxylic_acid_(intermolecular)!

1479 2 0 1,2,4-Oxadiazole_synthesis_(amidoxime_+_carboxylate) C936 "ADJXGRRNYYGIST-UHFFFAOYSA-N"

reactants =
[284800, 286067]

product = C936 "ADJXGRRNYYGIST-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: 1,2,4-Oxadiazole_synthesis_(amidoxime_+_carboxylate)!

1479 3 0 Sp2-sp2_Negishi_coupling_(intermolecular) C936 "ADJXGRRNYYGIST-UHFFFAOYSA-N"

reactants =
[286069, 286070]

product = C936 "ADJXGRRNYYGIST-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sp2-sp2_Negishi_coupling_(intermolecular)!

1479 4 0 1,2,4-Oxadiazole_synthesis_(amidoxime_+_carboxylate) C936 "ADJXGRRNYYGIST-UHFFFAOYSA-N"

reactants =
[284800, 286071]

product = C936 "ADJXGRRNYYGIST-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: 1,2,4-Oxadiazole_synthesis_(amidoxime_+_carboxylate)!

1480 0 0 Alpha_alkylation_of_ketone C9352 "NZCPRRIBNYPZPE-UHFFFAOYSA-N"

reactants =
[283280, 286072]

product = C9352 "NZCPRRIBNYPZPE-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ketone!

1480 1 0 N-Boc_deprotection C9352 "NZCPRRIBNYPZPE-UHFFFAOYSA-N"

 Success  registered route 1050!

1481 0 0 Amidation C8035 "TYSPFWQJQMFSNU-UHFFFAOYSA-N"

 Success  registered route 1051!

1482 0 0 Pinner_reaction_(carboxylate_ester) C1447 "OMXQSZKGPNAOCE-UHFFFAOYSA-N"

reactants =
[286076, 286077]

product = C1447 "OMXQSZKGPNAOCE-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Pinner_reaction_(carboxylate_ester)!

1482 1 0 Steglich_esterification C1447 "OMXQSZKGPNAOCE-UHFFFAOYSA-N"

 Success  registered route 1052!

1483 0 0 Formation_of_sulfonamide_from_halide_-_Shavnya_reaction C8159 "YKFFHGCNYWTCOY-UHFFFAOYSA-N"

reactants =
[283077, 286061]

product = C8159 "YKFFHGCNYWTCOY-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Formation_of_sulfonamide_from_halide_-_Shavnya_reaction!

1483 1 0 Formation_of_sulfonamide_from_halide_-_Shavnya_reaction C8159 "YKFFHGCNYWTCOY-UHFFFAOYSA-N"

reactants =
[283077, 285021]

product = C8159 "YKFFHGCNYWTCOY-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Formation_of_sulfonamide_from_halide_-_Shavnya_reaction!

1483 2 0 Formation_of_sulfonamide_from_halide_-_Shavnya_reaction C8159 "YKFFHGCNYWTCOY-UHFFFAOYSA-N"

reactants =
[283077, 286065]

product = C8159 "YKFFHGCNYWTCOY-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Formation_of_sulfonamide_from_halide_-_Shavnya_reaction!

1483 3 0 N-Boc_deprotection C8159 "YKFFHGCNYWTCOY-UHFFFAOYSA-N"

 Success  registered route 1053!

1484 0 0 Sp3-sp2_Macmillan_coupling_with_bromide_(intermolecular) C7230 "OWOZFTOSAOYWMO-UHFFFAOYSA-N"

reactants =
[286080, 286081]

product = C7230 "OWOZFTOSAOYWMO-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sp3-sp2_Macmillan_coupling_with_bromide_(intermolecular)!

1484 1 0 Alpha_alkylation_of_ester/amide C7230 "OWOZFTOSAOYWMO-UHFFFAOYSA-N"

reactants =
[14914, 286082]

product = C7230 "OWOZFTOSAOYWMO-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ester/amide!

1484 2 0 Alpha_alkylation_of_ester/amide C7230 "OWOZFTOSAOYWMO-UHFFFAOYSA-N"

reactants =
[14914, 286083]

product = C7230 "OWOZFTOSAOYWMO-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ester/amide!

1484 3 0 Alpha_alkylation_of_ester/amide C7230 "OWOZFTOSAOYWMO-UHFFFAOYSA-N"

reactants =
[283127, 286084]

product = C7230 "OWOZFTOSAOYWMO-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ester/amide!

1484 4 0 Alpha_alkylation_of_ester/amide C7230 "OWOZFTOSAOYWMO-UHFFFAOYSA-N"

reactants =
[283280, 286084]

product = C7230 "OWOZFTOSAOYWMO-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ester/amide!

1485 0 0 Amidation C901 "DAXDOXZPNQGVDA-UHFFFAOYSA-N"

 Success  registered route 1054!

1486 0 0 Amidation C8486 "NNLIRPSRTSJYLQ-UHFFFAOYSA-N"

 Success  registered route 1055!

1487 0 0 Reductive_amination C53105 "WYTLJIODCWWXCM-UHFFFAOYSA-N"

 Success  registered route 1056!

1488 0 0 Amidation C5289 "UENQPBXXWCZQQQ-UHFFFAOYSA-N"

 Success  registered route 1057!

1489 0 0 Formation_of_urea_from_two_amines C1404 "NLXFVKOJESFEML-UHFFFAOYSA-N"

 Success  registered route 1058!

1490 0 0 Imine_formation C38598 "FHBGUWZYHVFIEX-UHFFFAOYSA-N"

reactants =
[285098, 286092]

product = C38598 "FHBGUWZYHVFIEX-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Imine_formation!

1490 1 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C38598 "FHBGUWZYHVFIEX-UHFFFAOYSA-N"

1490 1 1 Imine_formation C286093 "GUNGIZPVZACYCB-UHFFFAOYSA-N"

reactants =
[286092, 286094]

product = C286093 "GUNGIZPVZACYCB-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Imine_formation!

1490 2 0 Williamson_ether_synthesis C38598 "FHBGUWZYHVFIEX-UHFFFAOYSA-N"

1490 2 1 Imine_formation C286095 "RUZDUCXWUNHEFR-UHFFFAOYSA-N"

reactants =
[286092, 286096]

product = C286095 "RUZDUCXWUNHEFR-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Imine_formation!

1490 3 0 Methylation_of_alcohol C38598 "FHBGUWZYHVFIEX-UHFFFAOYSA-N"

reactants =
[286093]

product = C38598 "FHBGUWZYHVFIEX-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Methylation_of_alcohol!

1490 4 0 Amidation C38598 "FHBGUWZYHVFIEX-UHFFFAOYSA-N"

1491 0 0 Sp3-sp2_Suzuki_coupling C25770 "FMCDEJOHQRDQTM-UHFFFAOYSA-N"

 Success  registered route 1059!

1492 0 0 Amidation C89709 "XRENEVZHQOBHPU-UHFFFAOYSA-N"

 Success  registered route 1060!

1493 0 0 Amidation C15998 "TUCJJOTTXFGEGV-UHFFFAOYSA-N"

 Success  registered route 1061!

1494 0 0 Imidazole_C-2_alkylation C2060 "BZGNUPUTGOBVRA-UHFFFAOYSA-N"

reactants =
[285803, 286102]

product = C2060 "BZGNUPUTGOBVRA-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Imidazole_C-2_alkylation!

1494 1 0 Imidazole_C-2_alkylation C2060 "BZGNUPUTGOBVRA-UHFFFAOYSA-N"

reactants =
[284510, 286102]

product = C2060 "BZGNUPUTGOBVRA-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Imidazole_C-2_alkylation!

1494 2 0 Imidazole_C-2_alkylation C2060 "BZGNUPUTGOBVRA-UHFFFAOYSA-N"

reactants =
[285099, 286102]

product = C2060 "BZGNUPUTGOBVRA-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Imidazole_C-2_alkylation!

1494 3 0 Minisci_reaction_with_carboxylic_acid_(intermolecular) C2060 "BZGNUPUTGOBVRA-UHFFFAOYSA-N"

reactants =
[284544, 286102]

product = C2060 "BZGNUPUTGOBVRA-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Minisci_reaction_with_carboxylic_acid_(intermolecular)!

1494 4 0 Sp3-sp2_Suzuki_coupling C2060 "BZGNUPUTGOBVRA-UHFFFAOYSA-N"

 Success  registered route 1062!

1495 0 0 Amidation C3768 "AHFGKFFBSVWUBY-UHFFFAOYSA-N"

 Success  registered route 1063!

1496 0 0 Alpha_alkylation_of_ketone C4665 "VSJBYJHPGLAONM-UHFFFAOYSA-N"

reactants =
[286107]

product = C4665 "VSJBYJHPGLAONM-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ketone!

1496 1 0 Alpha_alkylation_of_ketone C4665 "VSJBYJHPGLAONM-UHFFFAOYSA-N"

reactants =
[283280, 286108]

product = C4665 "VSJBYJHPGLAONM-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ketone!

1496 2 0 Alpha_alkylation_of_ketone C4665 "VSJBYJHPGLAONM-UHFFFAOYSA-N"

reactants =
[286107]

product = C4665 "VSJBYJHPGLAONM-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ketone!

1496 3 0 N-Boc_deprotection C4665 "VSJBYJHPGLAONM-UHFFFAOYSA-N"

 Success  registered route 1064!

1497 0 0 Formation_of_urea_from_two_amines C10335 "OTLOOYMQZJZQNU-UHFFFAOYSA-N"

 Success  registered route 1065!

1498 0 0 Amidation C7181 "YQLHABXLGQDQAK-UHFFFAOYSA-N"

 Success  registered route 1066!

1499 0 0 Sulfonamide_Schotten-Baumann_with_amine_(intermolecular) C8160 "NPUASWGUMOGUOD-UHFFFAOYSA-N"

reactants =
[285558, 286111]

product = C8160 "NPUASWGUMOGUOD-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sulfonamide_Schotten-Baumann_with_amine_(intermolecular)!

1499 1 0 Sulfonamide_Schotten-Baumann_with_amine_(intermolecular) C8160 "NPUASWGUMOGUOD-UHFFFAOYSA-N"

reactants =
[283065, 286112]

product = C8160 "NPUASWGUMOGUOD-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sulfonamide_Schotten-Baumann_with_amine_(intermolecular)!

1499 2 0 Sulfonamide_Schotten-Baumann_with_amine_(intermolecular) C8160 "NPUASWGUMOGUOD-UHFFFAOYSA-N"

reactants =
[285558, 286113]

product = C8160 "NPUASWGUMOGUOD-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sulfonamide_Schotten-Baumann_with_amine_(intermolecular)!

1499 3 0 Amide_to_amine_reduction C8160 "NPUASWGUMOGUOD-UHFFFAOYSA-N"

reactants =
[286114]

product = C8160 "NPUASWGUMOGUOD-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amide_to_amine_reduction!

1499 4 0 Alkene_hydrogenation_(unconjugated) C8160 "NPUASWGUMOGUOD-UHFFFAOYSA-N"

reactants =
[286115]

product = C8160 "NPUASWGUMOGUOD-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alkene_hydrogenation_(unconjugated)!

1500 0 0 Amidation C9219 "ZIEANTSEZNDOIT-UHFFFAOYSA-N"

1500 1 0 Ester_amidation C9219 "ZIEANTSEZNDOIT-UHFFFAOYSA-N"

1500 2 0 Ester_amidation C9219 "ZIEANTSEZNDOIT-UHFFFAOYSA-N"

1500 3 0 Beckmann_rearrangement C9219 "ZIEANTSEZNDOIT-UHFFFAOYSA-N"

reactants =
[286119]

product = C9219 "ZIEANTSEZNDOIT-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Beckmann_rearrangement!

1500 4 0 Ester_amidation C9219 "ZIEANTSEZNDOIT-UHFFFAOYSA-N"

1501 0 0 Amidation C7420 "SFWHGSYKQXAWJE-UHFFFAOYSA-N"

 Success  registered route 1067!

1502 0 0 Amidation C3796 "LCTNYMQLEGMDNQ-UHFFFAOYSA-N"

 Success  registered route 1068!

1503 0 0 Amidation C32214 "FYGXQHWPDXQZJW-UHFFFAOYSA-N"

 Success  registered route 1069!

1504 0 0 Reductive_amination C4724 "GMKJOMOIOGJQHB-UHFFFAOYSA-N"

 Success  registered route 1070!

1505 0 0 Amine_alkylation C2537 "SCARXBJLFBDDOC-UHFFFAOYSA-N"

reactants =
[285150, 285852]

product = C2537 "SCARXBJLFBDDOC-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

1505 1 0 Amine_alkylation C2537 "SCARXBJLFBDDOC-UHFFFAOYSA-N"

reactants =
[285150, 285854]

product = C2537 "SCARXBJLFBDDOC-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

1505 2 0 Buchwald-Hartwig_amidation_with_amide-like_nucleophile C2537 "SCARXBJLFBDDOC-UHFFFAOYSA-N"

1505 3 0 Wittig_reaction C2537 "SCARXBJLFBDDOC-UHFFFAOYSA-N"

reactants =
[286125, 286126]

product = C2537 "SCARXBJLFBDDOC-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Wittig_reaction!

1505 4 0 Amine_alkylation C2537 "SCARXBJLFBDDOC-UHFFFAOYSA-N"

reactants =
[285150, 285854]

product = C2537 "SCARXBJLFBDDOC-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Amine_alkylation!

1506 0 0 Amidation C684 "SZDLHMXCGWCAQL-UHFFFAOYSA-N"

 Success  registered route 1071!

1507 0 0 Amidation C4586 "RMNLILARQBZGID-UHFFFAOYSA-N"

 Success  registered route 1072!

1508 0 0 Amidation C4036 "YUUBMJABYAMHEQ-UHFFFAOYSA-N"

 Success  registered route 1073!

1509 0 0 Formation_of_sulfonamide_from_halide_-_Shavnya_reaction C7625 "KCJHWNBJYBCBFO-UHFFFAOYSA-N"

reactants =
[286131, 286132]

product = C7625 "KCJHWNBJYBCBFO-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Formation_of_sulfonamide_from_halide_-_Shavnya_reaction!

1509 1 0 Formation_of_sulfonamide_from_halide_-_Shavnya_reaction C7625 "KCJHWNBJYBCBFO-UHFFFAOYSA-N"

reactants =
[286132, 286133]

product = C7625 "KCJHWNBJYBCBFO-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Formation_of_sulfonamide_from_halide_-_Shavnya_reaction!

1509 2 0 Formation_of_sulfonamide_from_halide_-_Shavnya_reaction C7625 "KCJHWNBJYBCBFO-UHFFFAOYSA-N"

reactants =
[286132, 286134]

product = C7625 "KCJHWNBJYBCBFO-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Formation_of_sulfonamide_from_halide_-_Shavnya_reaction!

1509 3 0 Chan-Lam_coupling_of_amides,_sulfonamides,_and_imides C7625 "KCJHWNBJYBCBFO-UHFFFAOYSA-N"

reactants =
[75731, 283861]

product = C7625 "KCJHWNBJYBCBFO-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Chan-Lam_coupling_of_amides,_sulfonamides,_and_imides!

1509 4 0 Simmons-Smith_reaction C7625 "KCJHWNBJYBCBFO-UHFFFAOYSA-N"

reactants =
[286135]

product = C7625 "KCJHWNBJYBCBFO-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Simmons-Smith_reaction!

1510 0 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C8502 "RJQPPZGWNZQLTO-UHFFFAOYSA-N"

 Success  registered route 1074!

1511 0 0 Amidation C16768 "ALJLPWDQYMWXDZ-UHFFFAOYSA-N"

 Success  registered route 1075!

1512 0 0 Sulfonamide_Schotten-Baumann_with_amine_(intermolecular) C8155 "QQLANTWMZZICGE-UHFFFAOYSA-N"

reactants =
[286111, 286140]

product = C8155 "QQLANTWMZZICGE-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sulfonamide_Schotten-Baumann_with_amine_(intermolecular)!

1512 1 0 Sp2-sp2_Suzuki_coupling C8155 "QQLANTWMZZICGE-UHFFFAOYSA-N"

 Success  registered route 1076!

1513 0 0 Alpha_alkylation_of_ketone C4732 "OVNCGQSYSSYBPO-UHFFFAOYSA-N"

reactants =
[283280, 286143]

product = C4732 "OVNCGQSYSSYBPO-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ketone!

1513 1 0 Alpha_alkylation_of_ketone C4732 "OVNCGQSYSSYBPO-UHFFFAOYSA-N"

reactants =
[283127, 286143]

product = C4732 "OVNCGQSYSSYBPO-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ketone!

1513 2 0 Alpha_alkylation_of_ketone C4732 "OVNCGQSYSSYBPO-UHFFFAOYSA-N"

reactants =
[283128, 286143]

product = C4732 "OVNCGQSYSSYBPO-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Alpha_alkylation_of_ketone!

1513 3 0 Ketone_from_acid_chloride_(Gilman_reagent,_intermolecular) C4732 "OVNCGQSYSSYBPO-UHFFFAOYSA-N"

reactants =
[284607, 286144]

product = C4732 "OVNCGQSYSSYBPO-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Ketone_from_acid_chloride_(Gilman_reagent,_intermolecular)!

1513 4 0 Ozonolysis_(intermolecular) C4732 "OVNCGQSYSSYBPO-UHFFFAOYSA-N"

reactants =
[286145]

product = C4732 "OVNCGQSYSSYBPO-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Ozonolysis_(intermolecular)!

1514 0 0 Sp2-sp2_Suzuki_coupling C3665 "GXLZMUSLZZNHNL-UHFFFAOYSA-N"

1514 1 0 Sp2-sp2_Suzuki_coupling C3665 "GXLZMUSLZZNHNL-UHFFFAOYSA-N"

 Success  registered route 1077!

1515 0 0 Amidation C16361 "ZZPZYEPSKIPXIU-UHFFFAOYSA-N"

 Success  registered route 1078!

1516 0 0 Amidation C16361 "ZZPZYEPSKIPXIU-UHFFFAOYSA-N"

 Success  registered route 1079!

1517 0 0 Minisci_reaction_with_carboxylic_acid_(intermolecular) C2086 "SKVGOPZVGGOSKI-UHFFFAOYSA-N"

reactants =
[284732, 285142]

product = C2086 "SKVGOPZVGGOSKI-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Minisci_reaction_with_carboxylic_acid_(intermolecular)!

1517 1 0 Debus-Radziszewski_imidazole_synthesis C2086 "SKVGOPZVGGOSKI-UHFFFAOYSA-N"

reactants =
[286148, 286149]

product = C2086 "SKVGOPZVGGOSKI-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Debus-Radziszewski_imidazole_synthesis!

1517 2 0 Hydrogenation_of_pyridine C2086 "SKVGOPZVGGOSKI-UHFFFAOYSA-N"

reactants =
[286150]

product = C2086 "SKVGOPZVGGOSKI-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Hydrogenation_of_pyridine!

1517 3 0 N-Tosyl_deprotection C2086 "SKVGOPZVGGOSKI-UHFFFAOYSA-N"

reactants =
[286151]

product = C2086 "SKVGOPZVGGOSKI-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: N-Tosyl_deprotection!

1517 4 0 N-Ac_deprotection C2086 "SKVGOPZVGGOSKI-UHFFFAOYSA-N"

reactants =
[286152]

product = C2086 "SKVGOPZVGGOSKI-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: N-Ac_deprotection!

1518 0 0 Sp3-sp2_Suzuki_coupling C2091 "XNTLIZRLNRAQQY-UHFFFAOYSA-N"

1518 0 1 Sandmeyer_iodination C286153 "KVDVCOCXJVWCCY-UHFFFAOYSA-N"

reactants =
[286154]

product = C286153 "KVDVCOCXJVWCCY-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sandmeyer_iodination!

1518 1 0 Sp3-sp2_Suzuki_coupling C2091 "XNTLIZRLNRAQQY-UHFFFAOYSA-N"

1518 1 1 Sandmeyer_bromination C286155 "GHCXCBRZRJVNND-UHFFFAOYSA-N"

reactants =
[286154]

product = C286155 "GHCXCBRZRJVNND-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sandmeyer_bromination!

1518 2 0 Robinson-Gabriel_imidazole_synthesis_(with_amide_NH) C2091 "XNTLIZRLNRAQQY-UHFFFAOYSA-N"

reactants =
[282920, 286156]

product = C2091 "XNTLIZRLNRAQQY-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Robinson-Gabriel_imidazole_synthesis_(with_amide_NH)!

1518 3 0 Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide C2091 "XNTLIZRLNRAQQY-UHFFFAOYSA-N"

reactants =
[285101, 286155]

product = C2091 "XNTLIZRLNRAQQY-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide!

1518 4 0 Sp3-sp2_Suzuki_coupling C2091 "XNTLIZRLNRAQQY-UHFFFAOYSA-N"

1518 4 1 Sandmeyer_iodination C286153 "KVDVCOCXJVWCCY-UHFFFAOYSA-N"

reactants =
[286154]

product = C286153 "KVDVCOCXJVWCCY-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Sandmeyer_iodination!

1519 0 0 Aldol_addition_carbonyl C8142 "UZXQDRCHBFTVHG-UHFFFAOYSA-N"

reactants =
[283939, 284030]

product = C8142 "UZXQDRCHBFTVHG-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Aldol_addition_carbonyl!

1519 1 0 Conjugate_addition_of_Grignard_(Gilman_reagents) C8142 "UZXQDRCHBFTVHG-UHFFFAOYSA-N"

reactants =
[286157, 286158]

product = C8142 "UZXQDRCHBFTVHG-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Conjugate_addition_of_Grignard_(Gilman_reagents)!

1519 2 0 Wacker-Tsuji_oxidation_(terminal_alkene) C8142 "UZXQDRCHBFTVHG-UHFFFAOYSA-N"

reactants =
[286159]

product = C8142 "UZXQDRCHBFTVHG-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Wacker-Tsuji_oxidation_(terminal_alkene)!

1519 3 0 Ethenyl_to_formyl C8142 "UZXQDRCHBFTVHG-UHFFFAOYSA-N"

reactants =
[286160]

product = C8142 "UZXQDRCHBFTVHG-UHFFFAOYSA-N"

 Warning  Skipping unsupported chemistry: Ethenyl_to_formyl!

1519 4 0 N-Boc_deprotection C8142 "UZXQDRCHBFTVHG-UHFFFAOYSA-N"

 Success  registered route 1080!

,smiles,template,compound_set,hit1,hit2,hit3,hit4,hit5,hit6,hit7,...,route2_CAR,route2_non_CAR,route3,route3_names,route3_CAR,route3_non_CAR,route4,route4_names,route4_CAR,route4_non_CAR
0,O=C(Cc1cocn1)Nc1ccc2c(c1)C(F)CC2,A5666a,openbind_a71ev2a_c1_scaffolds,A5151a,A5512a,NaN,NaN,NaN,NaN,NaN,...,True,None,"[{'name': 'Ester_amidation', 'reactantSmiles':...",[Ester_amidation],True,None,[{'name': 'Sp3-sp2_Macmillan_coupling_alcohol_...,[Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_h...,False,[Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_h...
1,Cc1ccc(C(O)(C=O)NCc2cocn2)c2[nH]ccc12,A5666a,openbind_a71ev2a_c1_scaffolds,A0487a,A4940a,NaN,NaN,NaN,NaN,NaN,...,False,"[Grignard_addition_to_carbonyl, Formation_of_G...","[{'name': 'Reductive_amination', 'reactantSmil...","[Reductive_amination, Grignard_addition_to_car...",False,"[Grignard_addition_to_carbonyl, Formation_of_G...","[{'name': 'Amine_alkylation', 'reactantSmiles'...","[Amine_alkylation, Grignard_addition_to_carbon...",False,"[Amine_alkylation, Grignard_addition_to_carbon..."
2,COc1ccc(C(C)=O)cc1-c1n[nH]cc1CN,A5666a,openbind_a71ev2a_c1_scaffolds,A0501a,A4456a,NaN,NaN,NaN,NaN,NaN,...,False,[Sp2-sp2_Suzuki_coupling],"[{'name': 'Sp2-sp2_Suzuki_coupling', 'reactant...",[Sp2-sp2_Suzuki_coupling],False,[Sp2-sp2_Suzuki_coupling],"[{'name': 'Reductive_amination', 'reactantSmil...","[Reductive_amination, Sp2-sp2_Suzuki_coupling]",False,[Sp2-sp2_Suzuki_coupling]
3,CNNc1ccccc1-c1n[nH]c(C)c1CO,A5666a,openbind_a71ev2a_c1_scaffolds,A0501a,A4524a,NaN,NaN,NaN,NaN,NaN,...,False,"[Sp2-sp2_Suzuki_coupling, NHK_reaction, Amine_...","[{'name': 'Sp2-sp2_Suzuki_coupling', 'reactant...","[Sp2-sp2_Suzuki_coupling, Amine_alkylation]",False,"[Sp2-sp2_Suzuki_coupling, Amine_alkylation]","[{'name': 'Sp2-sp2_Suzuki_coupling', 'reactant...","[Sp2-sp2_Suzuki_coupling, Amine_alkylation]",False,"[Sp2-sp2_Suzuki_coupling, Amine_alkylation]"
4,CN1CCc2cc(F)c(OC(=O)N3CCCC(C(N)=O)C3)cc2C1CCOc...,A5666a,openbind_a71ev2a_c1_scaffolds,A0501b,A4214a,A4214b,NaN,NaN,NaN,NaN,...,False,[Formation_of_carbamate_from_amine_and_alcohol],"[{'name': 'Amine_alkylation', 'reactantSmiles'...","[Amine_alkylation, Williamson_ether_synthesis,...",False,"[Amine_alkylation, Formation_of_carbamate_from...",[{'name': 'Mitsunobu_reaction_with_amine_alcoh...,[Mitsunobu_reaction_with_amine_alcohol_and_thi...,False,[Formation_of_carbamate_from_amine_and_alcohol]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1515,O=C(NCCc1cc[nH]n1)c1ccnc(-n2ccnc2)c1,A3897a,openbind_a71ev2a_c1_scaffolds,A0556a,A3435a,NaN,NaN,NaN,NaN,NaN,...,True,None,"[{'name': 'Ester_amidation', 'reactantSmiles':...",[Ester_amidation],True,None,"[{'name': 'Ester_amidation', 'reactantSmiles':...",[Ester_amidation],True,None
1516,O=C(NCCc1cc[nH]n1)c1ccnc(-n2ccnc2)c1,A3897a,openbind_a71ev2a_c1_scaffolds,A0556a,A3435a,NaN,NaN,NaN,NaN,NaN,...,True,None,"[{'name': 'Ester_amidation', 'reactantSmiles':...",[Ester_amidation],True,None,"[{'name': 'Ester_amidation', 'reactantSmiles':...",[Ester_amidation],True,None
1517,C1CCC(c2nc3c([nH]2)CCCC3)NC1,A3897a,openbind_a71ev2a_c1_scaffolds,A3371a,A3706a,NaN,NaN,NaN,NaN,NaN,...,False,[Hydrogenation_of_pyridine],"[{'name': 'N-Tosyl_deprotection', 'reactantSmi...","[N-Tosyl_deprotection, Minisci_reaction_with_c...",False,[N-Tosyl_deprotection],"[{'name': 'N-Ac_deprotection', 'reactantSmiles...","[N-Ac_deprotection, Minisci_reaction_with_carb...",False,[N-Ac_deprotection]
1518,C1CC(c2nc3c([nH]2)CCSC3)CCN1,A3897a,openbind_a71ev2a_c1_scaffolds,A3371a,A3706a,NaN,NaN,NaN,NaN,NaN,...,False,[Robinson-Gabriel_imidazole_synthesis_(with_am...,[{'name': 'Sp3-sp2_Macmillan_coupling_alcohol_...,[Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_h...,False,[Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_h...,"[{'name': 'Sp3-sp2_Suzuki_coupling', 'reactant...","[Sp3-sp2_Suzuki_coupling, Sandmeyer_iodination]",False,"[Sp3-sp2_Suzuki_coupling, Sandmeyer_iodination]"
1519,CC(=O)CC(O)C1CCCNC1,A3897a,openbind_a71ev2a_c1_scaffolds,A0719a,A3509a,NaN,NaN,NaN,NaN,NaN,...,False,[Wacker-Tsuji_oxidation_(terminal_alkene)],"[{'name': 'Ethenyl_to_formyl', 'reactantSmiles...",[Ethenyl_to_formyl],False,[Ethenyl_to_formyl],"[{'name': 'N-Boc_deprotection', 'reactantSmile...",[N-Boc_deprotection],True,None

In [10]:
animal.db.prune_duplicate_routes()

#routes = 1080

products with duplicate routes = 1

compound 16361 has 4 duplicate routes

 Success  Deleted 3 duplicate routes!

{94, 1078, 1079}

In [11]:
cset = animal.poses(tag="openbind_a71ev2a_c1_scaffolds").compounds
cset.add_tag("openbind_a71ev2a_c1_scaffolds")

Tagged {C × 1517} w/ "openbind_a71ev2a_c1_scaffolds"

In [12]:
recipe = hippo.Recipe.from_compounds(cset, use_routes=True, pick_cheapest=False, pick_first=True)

#compounds = 1517

Output()

 ERROR  No routes to C498 "BVXIXHZBAAESKN-UHFFFAOYSA-N"!

 ERROR  No routes to C722 "AXNCOQBNSRCGQR-UHFFFAOYSA-N"!

 ERROR  No routes to C748 "JNUOHHGXTGSVRF-UHFFFAOYSA-N"!

 ERROR  No routes to C765 "GHIFOCYQWCGZBT-UHFFFAOYSA-N"!

 ERROR  No routes to C787 "WOKNKIOABYEMDE-UHFFFAOYSA-N"!

 ERROR  No routes to C936 "ADJXGRRNYYGIST-UHFFFAOYSA-N"!

 ERROR  No routes to C973 "UERDZVKTYWOYRH-UHFFFAOYSA-N"!

 ERROR  No routes to C1281 "GFYOTNKFYIETKD-UHFFFAOYSA-N"!

 ERROR  No routes to C1446 "CQUDLYKHYNSNKN-UHFFFAOYSA-N"!

 ERROR  No routes to C1851 "WHQNOBWFVDSYOK-UHFFFAOYSA-N"!

 ERROR  No routes to C2040 "NVQPTGDZIZQWGQ-UHFFFAOYSA-N"!

 ERROR  No routes to C2063 "ZGUIGBFPAXLLGR-UHFFFAOYSA-N"!

 ERROR  No routes to C2086 "SKVGOPZVGGOSKI-UHFFFAOYSA-N"!

 ERROR  No routes to C2091 "XNTLIZRLNRAQQY-UHFFFAOYSA-N"!

 ERROR  No routes to C2123 "WUBOLPOQHKSMNV-UHFFFAOYSA-N"!

 ERROR  No routes to C2365 "AOQJBHHWKYZXFO-UHFFFAOYSA-N"!

 ERROR  No routes to C2375 "GOSRQBSVGZRPLI-UHFFFAOYSA-N"!

 ERROR  No routes to C2382 "OLHKVAHFSOVKNO-UHFFFAOYSA-N"!

 ERROR  No routes to C2390 "GRCPKGYTKXKWFK-UHFFFAOYSA-N"!

 ERROR  No routes to C2403 "BLPQLXCUNUOCSN-UHFFFAOYSA-N"!

 ERROR  No routes to C2410 "XHBNPKKACABHBA-UHFFFAOYSA-N"!

 ERROR  No routes to C2413 "YNRBPEHVWJFOKW-UHFFFAOYSA-N"!

 ERROR  No routes to C2416 "QLHWJOTYGUXPGV-UHFFFAOYSA-N"!

 ERROR  No routes to C2421 "MZDOVACAPIIERT-UHFFFAOYSA-N"!

 ERROR  No routes to C2487 "LWUPXCRKWPNRJC-UHFFFAOYSA-N"!

 ERROR  No routes to C2503 "ASMMGLVTGJDGEB-UHFFFAOYSA-N"!

 ERROR  No routes to C2530 "GPGBQKMPCMYFLT-UHFFFAOYSA-N"!

 ERROR  No routes to C2531 "LSKCKISVBNXGCT-UHFFFAOYSA-N"!

 ERROR  No routes to C2536 "OKSDMMSSFWTMDL-UHFFFAOYSA-N"!

 ERROR  No routes to C2537 "SCARXBJLFBDDOC-UHFFFAOYSA-N"!

 ERROR  No routes to C2541 "BKHKIOXROMQUPK-UHFFFAOYSA-N"!

 ERROR  No routes to C2616 "HPDGQSVLUHUNOU-UHFFFAOYSA-N"!

 ERROR  No routes to C2628 "NILYFVLXUNTUTG-UHFFFAOYSA-N"!

 ERROR  No routes to C2636 "VLTCJSKEHQAUTL-UHFFFAOYSA-N"!

 ERROR  No routes to C4080 "GSETXYYFSRYMOU-UHFFFAOYSA-N"!

 ERROR  No routes to C4545 "JSYRTCNAAWDFHA-UHFFFAOYSA-N"!

 ERROR  No routes to C4666 "NRPARTHTHRTTMK-UHFFFAOYSA-N"!

 ERROR  No routes to C4670 "VLIIKHOBTSPATL-UHFFFAOYSA-N"!

 ERROR  No routes to C4693 "QLEQENYLQKJYBV-UHFFFAOYSA-N"!

 ERROR  No routes to C4701 "FINIGGNJPQFVOX-UHFFFAOYSA-N"!

 ERROR  No routes to C4732 "OVNCGQSYSSYBPO-UHFFFAOYSA-N"!

 ERROR  No routes to C4801 "LGOSQMUDZURGMS-UHFFFAOYSA-N"!

 ERROR  No routes to C4809 "LHBRDYHDWDKHLQ-UHFFFAOYSA-N"!

 ERROR  No routes to C5363 "NPDDPCJWLVZMCA-UHFFFAOYSA-N"!

 ERROR  No routes to C5378 "BPVACFSEVJXOJC-UHFFFAOYSA-N"!

 ERROR  No routes to C5393 "GCDRJSAGWFOAHE-UHFFFAOYSA-N"!

 ERROR  No routes to C5401 "MWSDBUDWLOMHAE-UHFFFAOYSA-N"!

 ERROR  No routes to C5404 "JPQPMWWMNLJLFA-UHFFFAOYSA-N"!

 ERROR  No routes to C5407 "DVLVUUCTVLQLBO-UHFFFAOYSA-N"!

 ERROR  No routes to C5412 "ZMWSPLIMPYHVRD-UHFFFAOYSA-N"!

 ERROR  No routes to C6038 "GOLAEVZHHBNYFC-UHFFFAOYSA-N"!

 ERROR  No routes to C6093 "LEXQPYMCTMZRQM-UHFFFAOYSA-N"!

 ERROR  No routes to C6116 "NUWLOKGYWJWIQU-UHFFFAOYSA-N"!

 ERROR  No routes to C6122 "PRRYMKYLPMALBW-UHFFFAOYSA-N"!

 ERROR  No routes to C6123 "CPIBTNTZBHUDNS-UHFFFAOYSA-N"!

 ERROR  No routes to C6248 "NXJYTRXEEROFOS-UHFFFAOYSA-N"!

 ERROR  No routes to C6268 "YFEHDHGTUJUJKX-UHFFFAOYSA-N"!

 ERROR  No routes to C6276 "FOELTRWJVGYBGD-UHFFFAOYSA-N"!

 ERROR  No routes to C6280 "VQRXHIVVUXYAFH-UHFFFAOYSA-N"!

 ERROR  No routes to C6286 "ANSXQAALPGNGJP-UHFFFAOYSA-N"!

 ERROR  No routes to C6296 "UYOZDXASYOYYCF-UHFFFAOYSA-N"!

 ERROR  No routes to C6510 "GKFRYZROBLFNAX-UHFFFAOYSA-N"!

 ERROR  No routes to C6773 "PIQMDRWGSNHVCK-UHFFFAOYSA-N"!

 ERROR  No routes to C7230 "OWOZFTOSAOYWMO-UHFFFAOYSA-N"!

 ERROR  No routes to C7479 "FDJUGHGTFDESJB-UHFFFAOYSA-N"!

 ERROR  No routes to C7587 "ZWKQUCJFDUBTGP-UHFFFAOYSA-N"!

 ERROR  No routes to C7592 "XNDMHKZPZBSGFI-UHFFFAOYSA-N"!

 ERROR  No routes to C7596 "HMFFHCKOIQTSMA-UHFFFAOYSA-N"!

 ERROR  No routes to C7599 "UXAXKRNZNZXPTI-UHFFFAOYSA-N"!

 ERROR  No routes to C7625 "KCJHWNBJYBCBFO-UHFFFAOYSA-N"!

 ERROR  No routes to C7634 "RXBXROWIEPMBRV-UHFFFAOYSA-N"!

 ERROR  No routes to C7644 "FQPSGVBYUDGJAR-UHFFFAOYSA-N"!

 ERROR  No routes to C7653 "NCZWCIZJDPQWNM-UHFFFAOYSA-N"!

 ERROR  No routes to C7655 "OLNCYPXEOMYYNS-UHFFFAOYSA-N"!

 ERROR  No routes to C7660 "NEEWPLZUMQNHBI-UHFFFAOYSA-N"!

 ERROR  No routes to C7673 "FEWUTFMHYWVVGO-UHFFFAOYSA-N"!

 ERROR  No routes to C7891 "BVORABRUVNAGOD-UHFFFAOYSA-N"!

 ERROR  No routes to C8144 "CZSVMTMCGSPTJV-UHFFFAOYSA-N"!

 ERROR  No routes to C8145 "IFQJCHDGIKNYJR-UHFFFAOYSA-N"!

 ERROR  No routes to C8146 "QNWXUKIQSJVNRS-UHFFFAOYSA-N"!

 ERROR  No routes to C8152 "CQGFXNLTTLLTME-UHFFFAOYSA-N"!

 ERROR  No routes to C8160 "NPUASWGUMOGUOD-UHFFFAOYSA-N"!

 ERROR  No routes to C8585 "BRFFCOVLYYYHTQ-UHFFFAOYSA-N"!

 ERROR  No routes to C8846 "VIZQUAMFAFOSLS-UHFFFAOYSA-N"!

 ERROR  No routes to C8903 "UKLVECSDHSHYKS-UHFFFAOYSA-N"!

 ERROR  No routes to C8912 "QLWADYUBFZPSNX-UHFFFAOYSA-N"!

 ERROR  No routes to C9207 "RHQJYRUFYUHRDN-UHFFFAOYSA-N"!

 ERROR  No routes to C9219 "ZIEANTSEZNDOIT-UHFFFAOYSA-N"!

 ERROR  No routes to C9393 "WYAUXRZNPDFNGB-UHFFFAOYSA-N"!

 ERROR  No routes to C9539 "ZHAZHKPVEROFLH-UHFFFAOYSA-N"!

 ERROR  No routes to C9548 "PVLRSSNEEAZVOH-UHFFFAOYSA-N"!

 ERROR  No routes to C9551 "TUJBPBYAHMFXCP-UHFFFAOYSA-N"!

 ERROR  No routes to C9559 "BERWHPCSSUZEII-UHFFFAOYSA-N"!

 ERROR  No routes to C9590 "NSDGADWCIGGTNK-UHFFFAOYSA-N"!

 ERROR  No routes to C9825 "VIDKADKMWCUVEQ-UHFFFAOYSA-N"!

 ERROR  No routes to C9904 "UCRHKGUMOXDCDY-UHFFFAOYSA-N"!

 ERROR  No routes to C10158 "FJTKEURQIPWLEI-UHFFFAOYSA-N"!

 ERROR  No routes to C10320 "BUCJQHMDCWUKLE-UHFFFAOYSA-N"!

 ERROR  No routes to C10400 "CMUPJBQGBXLKHY-UHFFFAOYSA-N"!

 ERROR  No routes to C10419 "VABKMYCWOFANPU-UHFFFAOYSA-N"!

 ERROR  No routes to C10519 "FKANEGWUQJTCRE-UHFFFAOYSA-N"!

 ERROR  No routes to C10527 "REXDXSHVJSWRIX-UHFFFAOYSA-N"!

 ERROR  No routes to C10627 "YFNRJWQADGKRAX-UHFFFAOYSA-N"!

 ERROR  No routes to C10634 "TXAALMFVFUTAOP-UHFFFAOYSA-N"!

 ERROR  No routes to C10650 "OHATYSATAWMYKE-UHFFFAOYSA-N"!

 ERROR  No routes to C11116 "WBRPYRDSULUSNM-UHFFFAOYSA-N"!

 ERROR  No routes to C11184 "RWLBYOFXTWUWOG-UHFFFAOYSA-N"!

 ERROR  No routes to C11209 "BTBDFXKRKUXPIR-UHFFFAOYSA-N"!

 ERROR  No routes to C11213 "ABFQQZLULDEORM-UHFFFAOYSA-N"!

 ERROR  No routes to C11231 "PZDAOJKGMJJGDC-UHFFFAOYSA-N"!

 ERROR  No routes to C12436 "DUYGGZWMEYALFM-UHFFFAOYSA-N"!

 ERROR  No routes to C13570 "OSHPMDKWLAXVLW-UHFFFAOYSA-N"!

 ERROR  No routes to C13648 "AJANJNXHNMDIHZ-UHFFFAOYSA-N"!

 ERROR  No routes to C14499 "BYVHTZLWXASNFG-UHFFFAOYSA-N"!

 ERROR  No routes to C14773 "MIZHWJKJFPMAHV-UHFFFAOYSA-N"!

 ERROR  No routes to C15029 "OCFFTUGEJZIYTH-UHFFFAOYSA-N"!

 ERROR  No routes to C15036 "LJZIXTIXXJIVMZ-UHFFFAOYSA-N"!

 ERROR  No routes to C15051 "MHXYYYOIIYIRRP-UHFFFAOYSA-N"!

 ERROR  No routes to C15052 "HXNOWCAYKFJUHZ-UHFFFAOYSA-N"!

 ERROR  No routes to C15053 "GIUVSXLAIVLOML-UHFFFAOYSA-N"!

 ERROR  No routes to C15058 "OHSAREOUZZCQAJ-UHFFFAOYSA-N"!

 ERROR  No routes to C15060 "WTLZXJJEXLVAHW-UHFFFAOYSA-N"!

 ERROR  No routes to C15823 "DPUSSHZYAUIWGW-UHFFFAOYSA-N"!

 ERROR  No routes to C17612 "HUQKWYASCUHDLP-UHFFFAOYSA-N"!

 ERROR  No routes to C18114 "UHISTFBIGPGRMK-UHFFFAOYSA-N"!

 ERROR  No routes to C18173 "AYEOHXFBHHOWPD-UHFFFAOYSA-N"!

 ERROR  No routes to C18178 "YSYAKSZYKZXPDR-UHFFFAOYSA-N"!

 ERROR  No routes to C18925 "VAWUEFSAMKXCBU-UHFFFAOYSA-N"!

 ERROR  No routes to C18943 "YUJANCLQKWVXAZ-UHFFFAOYSA-N"!

 ERROR  No routes to C19998 "HKXVWCTZHQLBNW-UHFFFAOYSA-N"!

 ERROR  No routes to C20070 "CLRMICGDIZHILI-UHFFFAOYSA-N"!

 ERROR  No routes to C20648 "ROOFZUAQKFMYKH-UHFFFAOYSA-N"!

 ERROR  No routes to C21569 "VGRJTUCBCKJLAN-UHFFFAOYSA-N"!

 ERROR  No routes to C25792 "IMNXQIZMBRQERC-UHFFFAOYSA-N"!

 ERROR  No routes to C27906 "SGWHFDPWZAGZRG-UHFFFAOYSA-N"!

 ERROR  No routes to C29031 "QFZBMJQUWWNYIL-UHFFFAOYSA-N"!

 ERROR  No routes to C29898 "BGICKWFMKMWXKW-UHFFFAOYSA-N"!

 ERROR  No routes to C31470 "GODMAJBOTXASKT-UHFFFAOYSA-N"!

 ERROR  No routes to C31930 "RBPJKPBEDYIOQL-UHFFFAOYSA-N"!

 ERROR  No routes to C33638 "GZMCLAHOGOMNFO-UHFFFAOYSA-N"!

 ERROR  No routes to C34336 "QJWWGHKEHQNEQY-UHFFFAOYSA-N"!

 ERROR  No routes to C34673 "XHJOMYXOFNVJDG-UHFFFAOYSA-N"!

 ERROR  No routes to C35059 "ZXIQETDVUZSVBJ-UHFFFAOYSA-N"!

 ERROR  No routes to C38598 "FHBGUWZYHVFIEX-UHFFFAOYSA-N"!

 ERROR  No routes to C38721 "XOTFNADYVUYIDE-UHFFFAOYSA-N"!

 ERROR  No routes to C39108 "NJZWNPRAQMACTE-UHFFFAOYSA-N"!

 ERROR  No routes to C40856 "DFDDAHMVJZQNIS-UHFFFAOYSA-N"!

 ERROR  No routes to C40896 "NRWGAZDGIQPBJK-UHFFFAOYSA-N"!

 ERROR  No routes to C45746 "INIOVHDPBHGSSA-UHFFFAOYSA-N"!

 ERROR  No routes to C45943 "NAKUARJYTXIAKL-UHFFFAOYSA-N"!

 ERROR  No routes to C45987 "YTXBRSZQZDSVHR-UHFFFAOYSA-N"!

 ERROR  No routes to C46024 "GCNBWOGZRKAZBP-UHFFFAOYSA-N"!

 ERROR  No routes to C46025 "BVLLTLFJWFLOHJ-UHFFFAOYSA-N"!

 ERROR  No routes to C46480 "PYKGBZNJSJEWFO-UHFFFAOYSA-N"!

 ERROR  No routes to C46489 "SZIVMHZNNDPTLC-UHFFFAOYSA-N"!

 ERROR  No routes to C46510 "YFUCQHARYKGGDT-UHFFFAOYSA-N"!

 ERROR  No routes to C46656 "AMVABLYBMIDGRH-UHFFFAOYSA-N"!

 ERROR  No routes to C47050 "UUXRWAXHJKIKLF-UHFFFAOYSA-N"!

 ERROR  No routes to C47226 "DLCSXKSRGUYCLO-UHFFFAOYSA-N"!

 ERROR  No routes to C47239 "QZMIVAQLNCUJAN-UHFFFAOYSA-N"!

 ERROR  No routes to C50895 "KXNWFIJPGUQQKJ-UHFFFAOYSA-N"!

 ERROR  No routes to C51171 "SBSIUJKZMODQOZ-UHFFFAOYSA-N"!

 ERROR  No routes to C51172 "GBIVHNMPUDCSBY-UHFFFAOYSA-N"!

 ERROR  No routes to C51842 "CVBHTHVPQGKGJL-UHFFFAOYSA-N"!

 ERROR  No routes to C51875 "UZTGHTCNTUSHGZ-UHFFFAOYSA-N"!

 ERROR  No routes to C52416 "CTFJRCJMDOHUDJ-UHFFFAOYSA-N"!

 ERROR  No routes to C53933 "QATXJWMNVCBKJS-UHFFFAOYSA-N"!

 ERROR  No routes to C58912 "WYHWZNDJHHPUFV-UHFFFAOYSA-N"!

 ERROR  No routes to C60696 "PBRDYGOIOPNLNB-UHFFFAOYSA-N"!

 ERROR  No routes to C66949 "IKAMDUKMYVVAKK-UHFFFAOYSA-N"!

 ERROR  No routes to C66955 "CMZOTFOSHDWTHE-UHFFFAOYSA-N"!

 ERROR  No routes to C69074 "UJUZDCBLGJJXRQ-UHFFFAOYSA-N"!

 ERROR  No routes to C72721 "LYKXFHHASTVORN-UHFFFAOYSA-N"!

 ERROR  No routes to C76574 "TZXZNVJKNDRZQE-UHFFFAOYSA-N"!

 ERROR  No routes to C77791 "DIUMSFGKZNZUAS-UHFFFAOYSA-N"!

 ERROR  No routes to C82633 "OSQOBRFFSJVYOU-UHFFFAOYSA-N"!

 ERROR  No routes to C86181 "POMAHRVANROYCT-UHFFFAOYSA-N"!

 ERROR  No routes to C86222 "HZKRCMBVUHIKHS-UHFFFAOYSA-N"!

 ERROR  No routes to C94391 "GMNUJJZGAJDXFW-UHFFFAOYSA-N"!

 ERROR  No routes to C97238 "INEPPSBQJWJDAN-UHFFFAOYSA-N"!

 ERROR  No routes to C98884 "GANHUCHPQYNYPW-UHFFFAOYSA-N"!

 ERROR  No routes to C120944 "TVIVKSZHVBUWMY-UHFFFAOYSA-N"!

 ERROR  No routes to C125028 "GKRPCXYDRCZNEJ-UHFFFAOYSA-N"!

 ERROR  No routes to C140626 "WVCRQGVMFRYXPW-UHFFFAOYSA-N"!

 ERROR  No routes to C141610 "BVTGRELWAPFAGZ-UHFFFAOYSA-N"!

 ERROR  No routes to C142584 "HOYKQAJNZZTFNB-UHFFFAOYSA-N"!

 ERROR  No routes to C142646 "DNEDAFNARQGQSP-UHFFFAOYSA-N"!

 ERROR  No routes to C143244 "ZEPXNXKIOCFIQN-UHFFFAOYSA-N"!

 ERROR  No routes to C143262 "RSZCATFBIKXLMR-UHFFFAOYSA-N"!

 ERROR  No routes to C143369 "FRGSBTNMALVKIX-UHFFFAOYSA-N"!

 ERROR  No routes to C145049 "KECOMYVRALMHPG-UHFFFAOYSA-N"!

 ERROR  No routes to C145578 "AQAMQMSGSHVYSE-UHFFFAOYSA-N"!

 ERROR  No routes to C145634 "FBZZLTFHUFQKNB-UHFFFAOYSA-N"!

 ERROR  No routes to C145809 "UWQPEPKLQMYNPZ-UHFFFAOYSA-N"!

 ERROR  No routes to C145866 "FTILCHVAIXWVQH-UHFFFAOYSA-N"!

 ERROR  No routes to C145902 "SLPHMEGNVKINDS-UHFFFAOYSA-N"!

 ERROR  No routes to C145928 "CNSOMSHDFFGNBW-UHFFFAOYSA-N"!

 ERROR  No routes to C145997 "DQTZBOLCJXAMAV-UHFFFAOYSA-N"!

 ERROR  No routes to C146040 "SCDNAKOYMIYAQA-UHFFFAOYSA-N"!

 ERROR  No routes to C146049 "ZDZJGSQEJNBHGY-UHFFFAOYSA-N"!

 ERROR  No routes to C146186 "GHLNUKUVXIIUDH-UHFFFAOYSA-N"!

 ERROR  No routes to C146205 "NHNMNMCQXGGKAG-UHFFFAOYSA-N"!

 ERROR  No routes to C146309 "MHQFRAYZEAVYBY-UHFFFAOYSA-N"!

 ERROR  No routes to C146731 "GMHGBJOLLBFRHA-UHFFFAOYSA-N"!

 ERROR  No routes to C146746 "UFMKQVZXEYBDBD-UHFFFAOYSA-N"!

 ERROR  No routes to C146754 "QBLLUUIRPYYVNF-UHFFFAOYSA-N"!

 ERROR  No routes to C146932 "MCFJGPMGCQZSPL-UHFFFAOYSA-N"!

 ERROR  No routes to C146975 "PZOIXPIGHIWADF-UHFFFAOYSA-N"!

 ERROR  No routes to C146980 "DGNULVMAHZSAPG-UHFFFAOYSA-N"!

 ERROR  No routes to C146994 "SDHZANYRAZLTEC-UHFFFAOYSA-N"!

 ERROR  No routes to C147247 "XUMJFNBFJWTOOR-UHFFFAOYSA-N"!

 ERROR  No routes to C147248 "SDACINWTWMUFBU-UHFFFAOYSA-N"!

 ERROR  No routes to C147255 "KEBCBYAFIMRJNC-UHFFFAOYSA-N"!

 ERROR  No routes to C151234 "WIUNUEFYQJMMSD-UHFFFAOYSA-N"!

 ERROR  No routes to C151519 "BVAHRGRTNGLSFN-UHFFFAOYSA-N"!

 ERROR  No routes to C151891 "AJHJYWCUIVFJRP-UHFFFAOYSA-N"!

 ERROR  No routes to C152685 "ATEYTNCUIPHQQY-UHFFFAOYSA-N"!

 ERROR  No routes to C154866 "KSWWLSZWNYUPKN-UHFFFAOYSA-N"!

 ERROR  No routes to C155423 "FWVFIZNNHNBUSS-UHFFFAOYSA-N"!

 ERROR  No routes to C155615 "KFEZRMLQHAZDEN-UHFFFAOYSA-N"!

 ERROR  No routes to C155988 "VMAHPGKKKWPAJU-UHFFFAOYSA-N"!

 ERROR  No routes to C157476 "KWOAKLTZEAWRKW-UHFFFAOYSA-N"!

 ERROR  No routes to C159094 "YVPORMJUNHFFRP-UHFFFAOYSA-N"!

 ERROR  No routes to C160224 "VMRRETVEFLYQLB-UHFFFAOYSA-N"!

 ERROR  No routes to C160667 "MLUYARBKPLLQGO-UHFFFAOYSA-N"!

 ERROR  No routes to C160793 "BQNACJRNYISVSZ-UHFFFAOYSA-N"!

 ERROR  No routes to C162058 "QTGYCYOMZYQVEP-UHFFFAOYSA-N"!

 ERROR  No routes to C164254 "KFFAPYJDDXEIJM-UHFFFAOYSA-N"!

 ERROR  No routes to C166112 "JXIXYIVPOTVUHE-UHFFFAOYSA-N"!

 ERROR  No routes to C166354 "HXJSQBOPYILTPT-UHFFFAOYSA-N"!

 ERROR  No routes to C166559 "FTPLNKSHYLFOCK-UHFFFAOYSA-N"!

 ERROR  No routes to C168335 "QYPHKTUDALALPC-UHFFFAOYSA-N"!

 ERROR  No routes to C169562 "DOTHXRCBGJFSGT-UHFFFAOYSA-N"!

 ERROR  No routes to C170684 "FATHSFMKTKOIKO-UHFFFAOYSA-N"!

 ERROR  No routes to C171574 "FUTGFDLGXKNCMV-UHFFFAOYSA-N"!

 ERROR  No routes to C171861 "DYCQCBXGYZVPKZ-UHFFFAOYSA-N"!

 ERROR  No routes to C177719 "WECSMDFTHCGFKA-UHFFFAOYSA-N"!

 ERROR  No routes to C178840 "JTCJLGZQLBXCSL-UHFFFAOYSA-N"!

 ERROR  No routes to C179389 "RLOZHVQZKVTLPH-UHFFFAOYSA-N"!

 ERROR  No routes to C180463 "XPWAJQFGOMMBQE-UHFFFAOYSA-N"!

 ERROR  No routes to C181196 "OAZGZFZJSHMQAF-UHFFFAOYSA-N"!

 ERROR  No routes to C181214 "XBUJMKISRHCTDR-UHFFFAOYSA-N"!

 ERROR  No routes to C181219 "YINOIWFULAQOLY-UHFFFAOYSA-N"!

 ERROR  No routes to C181232 "NHXUVFLIZLDSSZ-UHFFFAOYSA-N"!

 ERROR  No routes to C181248 "JXGWKTGHPXMKHC-UHFFFAOYSA-N"!

 ERROR  No routes to C181267 "HENXKPUZOUQMOO-UHFFFAOYSA-N"!

 ERROR  No routes to C181280 "SBCSSJJDLUIWJO-UHFFFAOYSA-N"!

 ERROR  No routes to C181298 "RCSDJPHGQZWBKU-UHFFFAOYSA-N"!

 ERROR  No routes to C181304 "IHTQCZLWKVCOSP-UHFFFAOYSA-N"!

 ERROR  No routes to C181314 "RZZOPLWGHOACNB-UHFFFAOYSA-N"!

 ERROR  No routes to C181316 "SPVYDJGENJIVBR-UHFFFAOYSA-N"!

 ERROR  No routes to C181317 "PSFZHIZHBUGQQO-UHFFFAOYSA-N"!

 ERROR  No routes to C181318 "ZOFDXDPWBKSIDB-UHFFFAOYSA-N"!

 ERROR  No routes to C181320 "IKIOITOSBVZGHJ-UHFFFAOYSA-N"!

 ERROR  No routes to C181344 "XAWSNWWGAIHPIO-UHFFFAOYSA-N"!

 ERROR  No routes to C181372 "FYJSPFYXYVMCOE-UHFFFAOYSA-N"!

 ERROR  No routes to C181421 "BBCCSNBROVPFPM-UHFFFAOYSA-N"!

 ERROR  No routes to C181432 "CGLRTFOBKGPTSK-UHFFFAOYSA-N"!

 ERROR  No routes to C181440 "HRAPKXFSNLPORY-UHFFFAOYSA-N"!

 ERROR  No routes to C181441 "DBXWMQHMKJRNCH-UHFFFAOYSA-N"!

 ERROR  No routes to C181443 "BFSPLYFWEGSEAT-UHFFFAOYSA-N"!

 ERROR  No routes to C181448 "QEUPNUUCFFBVFI-UHFFFAOYSA-N"!

 ERROR  No routes to C181450 "OKFLGWJNFLHFIS-UHFFFAOYSA-N"!

 ERROR  No routes to C181906 "GAIGGVYAGRLFMC-UHFFFAOYSA-N"!

 ERROR  No routes to C181935 "AFWCNCDEVDPSGG-UHFFFAOYSA-N"!

 ERROR  No routes to C181958 "OGXOPRLPVWVISU-UHFFFAOYSA-N"!

 ERROR  No routes to C181990 "WCLFIFLHTPCLFC-UHFFFAOYSA-N"!

 ERROR  No routes to C182001 "RXUNDRBYKCAMQB-UHFFFAOYSA-N"!

 ERROR  No routes to C182105 "IEGLJRXZWZHGQG-UHFFFAOYSA-N"!

 ERROR  No routes to C182109 "BSVXJKRMERDWGF-UHFFFAOYSA-N"!

 ERROR  No routes to C182121 "SNNKCQMKKUBBPN-UHFFFAOYSA-N"!

 ERROR  No routes to C182125 "JFTIVCICNQOZAI-UHFFFAOYSA-N"!

 ERROR  No routes to C182134 "WNWPBURIRJZWDB-UHFFFAOYSA-N"!

 ERROR  No routes to C182163 "KGEGNRYOTDGQLV-UHFFFAOYSA-N"!

 ERROR  No routes to C182169 "RUKKUCYHUKCBDF-UHFFFAOYSA-N"!

 ERROR  No routes to C182181 "QBIWCRLJRSIZFF-UHFFFAOYSA-N"!

 ERROR  No routes to C182188 "BLNUXUYGSMWJHQ-UHFFFAOYSA-N"!

 ERROR  No routes to C182197 "BPTFCRKOVTZCQF-UHFFFAOYSA-N"!

 ERROR  No routes to C182207 "WMUUVFWDNLHIJJ-UHFFFAOYSA-N"!

 ERROR  No routes to C189983 "HWXYDZKCQZODDY-UHFFFAOYSA-N"!

 ERROR  No routes to C191001 "IKIXKFUOGRZPFW-UHFFFAOYSA-N"!

 ERROR  No routes to C191305 "ZKVDGUXVNAFIAR-UHFFFAOYSA-N"!

 ERROR  No routes to C192498 "XEWCIHXKBKXNHS-UHFFFAOYSA-N"!

 ERROR  No routes to C192757 "ICWVNBYGDBEEPQ-UHFFFAOYSA-N"!

 ERROR  No routes to C193306 "HEQRNUOIDXZIGG-UHFFFAOYSA-N"!

 ERROR  No routes to C193333 "GYHNELMRIHFZDX-UHFFFAOYSA-N"!

 ERROR  No routes to C193826 "FNNHSCZUTYNJDJ-UHFFFAOYSA-N"!

 ERROR  No routes to C195891 "DKZDUCVJXRXBBA-UHFFFAOYSA-N"!

 ERROR  No routes to C196558 "AGRJYFIWFUELBQ-UHFFFAOYSA-N"!

 ERROR  No routes to C196587 "RSGIPRSFTBBUPQ-UHFFFAOYSA-N"!

 ERROR  No routes to C197218 "WJNYPPPXBFUKQL-UHFFFAOYSA-N"!

 ERROR  No routes to C197752 "YVJXSLHMEKVBFH-UHFFFAOYSA-N"!

 ERROR  No routes to C200198 "UFZNLUDRLZMRGQ-UHFFFAOYSA-N"!

 ERROR  No routes to C202528 "VATPZTFVYWQJBN-UHFFFAOYSA-N"!

 ERROR  No routes to C202534 "VGTLZTLJNDMVPQ-UHFFFAOYSA-N"!

 ERROR  No routes to C204752 "CGZRVGDEPBQRLK-UHFFFAOYSA-N"!

 ERROR  No routes to C204757 "QBTJBIZQBLWTHK-UHFFFAOYSA-N"!

 ERROR  No routes to C204759 "HFYNVCDYDDENBP-UHFFFAOYSA-N"!

 ERROR  No routes to C205071 "PERMOVIPLPJQEI-UHFFFAOYSA-N"!

 ERROR  No routes to C205207 "WKJLQQPDUXOUMP-UHFFFAOYSA-N"!

 ERROR  No routes to C205350 "HLRUMDYTHLCPPG-UHFFFAOYSA-N"!

 ERROR  No routes to C205673 "WZIRMQBHPLNZSO-UHFFFAOYSA-N"!

 ERROR  No routes to C205735 "LOKPWBJATUOXAV-UHFFFAOYSA-N"!

 ERROR  No routes to C206012 "CSWNYLMUJIALAZ-UHFFFAOYSA-N"!

 ERROR  No routes to C206128 "VVPKDBSEKFTDKW-UHFFFAOYSA-N"!

 ERROR  No routes to C206533 "NRGXOCHABHARIE-UHFFFAOYSA-N"!

 ERROR  No routes to C207208 "ZXAAHBZIJXGKJX-UHFFFAOYSA-N"!

 ERROR  No routes to C207670 "XCSATHHEPNRICZ-UHFFFAOYSA-N"!

 ERROR  No routes to C207759 "WEZNMCCECZERHN-UHFFFAOYSA-N"!

 ERROR  No routes to C207965 "MJVUMUCHXJIYSQ-UHFFFAOYSA-N"!

 ERROR  No routes to C207977 "DMZINGXWJCZRBU-UHFFFAOYSA-N"!

 ERROR  No routes to C208022 "SQVAQLLFWWHIAM-UHFFFAOYSA-N"!

 ERROR  No routes to C208797 "XXOQUOORJDYPRS-UHFFFAOYSA-N"!

 ERROR  No routes to C209071 "SHCZOYKQYIWQDJ-UHFFFAOYSA-N"!

 ERROR  No routes to C209279 "DBUQYLDMMGGVTB-UHFFFAOYSA-N"!

 ERROR  No routes to C209410 "UBDMMFNGJKAPAH-UHFFFAOYSA-N"!

 ERROR  No routes to C209458 "DEAYEWLCXYHNPI-UHFFFAOYSA-N"!

 ERROR  No routes to C209486 "HYGHYRLZACCXQI-UHFFFAOYSA-N"!

 ERROR  No routes to C210967 "HOAFIQOISFJLKG-UHFFFAOYSA-N"!

 ERROR  No routes to C211146 "JBIVGESMOMEDMX-UHFFFAOYSA-N"!

 ERROR  No routes to C211238 "UROBGGNSTLIPEU-UHFFFAOYSA-N"!

 ERROR  No routes to C211275 "PHCFYPBLYITEAW-UHFFFAOYSA-N"!

 ERROR  No routes to C212430 "GVQWSGJJFCFIRY-UHFFFAOYSA-N"!

 ERROR  No routes to C212571 "YAHDGFSPRXLONS-UHFFFAOYSA-N"!

 ERROR  No routes to C214698 "TVYXXSMKKFSTDL-UHFFFAOYSA-N"!

 ERROR  No routes to C215084 "PBUVVEGHRQRWFC-UHFFFAOYSA-N"!

 ERROR  No routes to C216188 "UVRVNMDNGVIBGM-UHFFFAOYSA-N"!

 ERROR  No routes to C216299 "FDXLNKBSSMKNST-UHFFFAOYSA-N"!

 ERROR  No routes to C216355 "HYQPAIHEMGSSJO-UHFFFAOYSA-N"!

 ERROR  No routes to C216357 "HUSFWJZEUFNZSQ-UHFFFAOYSA-N"!

 ERROR  No routes to C216360 "LMIJHJCABBMJTL-UHFFFAOYSA-N"!

 ERROR  No routes to C216367 "CCWJSDMCVYJGGM-UHFFFAOYSA-N"!

 ERROR  No routes to C216410 "IKWWRZYFLJJNNK-UHFFFAOYSA-N"!

 ERROR  No routes to C216415 "IAGKFRITHIIXME-UHFFFAOYSA-N"!

 ERROR  No routes to C216425 "RBHQQCSUMMRMLY-UHFFFAOYSA-N"!

 ERROR  No routes to C216439 "SSIXCXGUESZBGS-UHFFFAOYSA-N"!

 ERROR  No routes to C216451 "LQBJAPHXNZQIIP-UHFFFAOYSA-N"!

 ERROR  No routes to C216457 "CWFACJFDGIQBOC-UHFFFAOYSA-N"!

 ERROR  No routes to C216462 "DFGQYCVFJBLSQT-UHFFFAOYSA-N"!

 ERROR  No routes to C216480 "WTRKRXUSBNGMEC-UHFFFAOYSA-N"!

 ERROR  No routes to C216499 "PEXDTKOHQKGDOE-UHFFFAOYSA-N"!

 ERROR  No routes to C216506 "WIXMSLLRVUTSKV-UHFFFAOYSA-N"!

 ERROR  No routes to C216533 "LGXXYENZZFJPOF-UHFFFAOYSA-N"!

 ERROR  No routes to C216534 "FTBJVCNAHRURQU-UHFFFAOYSA-N"!

 ERROR  No routes to C216542 "YQZSZCNVDYPABN-UHFFFAOYSA-N"!

 ERROR  No routes to C216552 "SBEYKMJRSWNDJO-UHFFFAOYSA-N"!

 ERROR  No routes to C216553 "ZAAUKUZMBDWRIB-UHFFFAOYSA-N"!

 ERROR  No routes to C216729 "ACGAOFJUNQSDGT-UHFFFAOYSA-N"!

 ERROR  No routes to C221199 "DSTCSFXWPPZMMG-UHFFFAOYSA-N"!

 ERROR  No routes to C221321 "STZMCMOCSSQOIY-UHFFFAOYSA-N"!

 ERROR  No routes to C221713 "ZDVGWIGLQNXIPC-UHFFFAOYSA-N"!

 ERROR  No routes to C223813 "MHXVSXRGCZAGOU-UHFFFAOYSA-N"!

 ERROR  No routes to C223849 "VZZNLCQRSIUYQV-UHFFFAOYSA-N"!

 ERROR  No routes to C223851 "LUMZHBRJYVSBCU-UHFFFAOYSA-N"!

 ERROR  No routes to C223863 "GFLLQDRPUXMCNL-UHFFFAOYSA-N"!

 ERROR  No routes to C223867 "QMYIEUIBLQHGOH-UHFFFAOYSA-N"!

 ERROR  No routes to C223876 "JFQKISFLWIGOGM-UHFFFAOYSA-N"!

 ERROR  No routes to C223886 "SSGZMYWLRNLFOE-UHFFFAOYSA-N"!

 ERROR  No routes to C223890 "GEFQHGIGKICAEA-UHFFFAOYSA-N"!

 ERROR  No routes to C224261 "ISCVVQNSXGDQLC-UHFFFAOYSA-N"!

 ERROR  No routes to C224274 "CTSOVUWPVNQORE-UHFFFAOYSA-N"!

 ERROR  No routes to C224459 "FQRZQBJCBUZPFL-UHFFFAOYSA-N"!

 ERROR  No routes to C224908 "UVHVGUBWEQMBKH-UHFFFAOYSA-N"!

 ERROR  No routes to C225528 "RHLCJNOASWSNMI-UHFFFAOYSA-N"!

 ERROR  No routes to C225591 "VBSRSIBHLLKMRD-UHFFFAOYSA-N"!

 ERROR  No routes to C226288 "DGEPUJVYPZIWMK-UHFFFAOYSA-N"!

 ERROR  No routes to C226551 "NIPJUCNGLLJJFA-UHFFFAOYSA-N"!

 ERROR  No routes to C226563 "NQUKOMUTPJKZKK-UHFFFAOYSA-N"!

 ERROR  No routes to C230890 "AZEOFDDNIYRHDU-UHFFFAOYSA-N"!

 ERROR  No routes to C231412 "QUQJXZGKMPTGAK-UHFFFAOYSA-N"!

 ERROR  No routes to C233495 "SZTVCGMPBPILDP-UHFFFAOYSA-N"!

 ERROR  No routes to C234801 "HOUBJEFMWZBNIN-UHFFFAOYSA-N"!

 ERROR  No routes to C236405 "PNIRUYFAVYSKGX-UHFFFAOYSA-N"!

 ERROR  No routes to C236572 "BNBYMHAFKGTQRL-UHFFFAOYSA-N"!

 ERROR  No routes to C237665 "ZOCGKLDDWFFWQE-UHFFFAOYSA-N"!

 ERROR  No routes to C238995 "LGZDDTPAQWOQRS-UHFFFAOYSA-N"!

 ERROR  No routes to C239025 "VFBUMSUYWJXJKD-UHFFFAOYSA-N"!

 ERROR  No routes to C239119 "CKEHPFRKAUOUOY-UHFFFAOYSA-N"!

 ERROR  No routes to C242679 "QOPZJBUCVFBGAX-UHFFFAOYSA-N"!

 ERROR  No routes to C244966 "QFWNWXWQRXYKOP-UHFFFAOYSA-N"!

 ERROR  No routes to C245300 "PRXPYPJGLWYXFD-UHFFFAOYSA-N"!

 ERROR  No routes to C248595 "OWKLMJNPJZKEQM-UHFFFAOYSA-N"!

 ERROR  No routes to C250497 "KJWDXNNRMHUODX-UHFFFAOYSA-N"!

 ERROR  No routes to C250878 "CPCIPUAOQZTFDH-UHFFFAOYSA-N"!

 ERROR  No routes to C250918 "CTVIJEWCBJAHCI-UHFFFAOYSA-N"!

 ERROR  No routes to C251069 "SSDPPQDNKQWKPY-UHFFFAOYSA-N"!

 ERROR  No routes to C251192 "PAKQMAVEDUZSJL-UHFFFAOYSA-N"!

 ERROR  No routes to C251213 "AYQMAJNLGGPHMJ-UHFFFAOYSA-N"!

 ERROR  No routes to C251960 "DMHSYRWRIUSZDL-UHFFFAOYSA-N"!

 ERROR  No routes to C252240 "PTIYRSDWVOKDRE-UHFFFAOYSA-N"!

 ERROR  No routes to C252281 "HHBIGVBGHAUBND-UHFFFAOYSA-N"!

 ERROR  No routes to C252325 "JWUDNWNUFKEQFE-UHFFFAOYSA-N"!

 ERROR  No routes to C254258 "PZSONJUKUXLUAJ-UHFFFAOYSA-N"!

 ERROR  No routes to C254303 "HVXHFWAWXOENKE-UHFFFAOYSA-N"!

 ERROR  No routes to C255845 "CPWFSKJMEDRRBR-UHFFFAOYSA-N"!

 ERROR  No routes to C256490 "RPDFRSKJKOQCIT-UHFFFAOYSA-N"!

 ERROR  No routes to C256517 "QPUYECUOLPXSFR-UHFFFAOYSA-N"!

 ERROR  No routes to C256535 "JBOZGUXJXYOBFI-UHFFFAOYSA-N"!

 ERROR  No routes to C256575 "POSUBGQGUWKMGE-UHFFFAOYSA-N"!

 ERROR  No routes to C257314 "UXHKPKPTEJXYTA-UHFFFAOYSA-N"!

 ERROR  No routes to C258167 "GHHHFUBRGPPHPF-UHFFFAOYSA-N"!

 ERROR  No routes to C258565 "YMLYXJKQZYKRTB-UHFFFAOYSA-N"!

 ERROR  No routes to C261944 "GOJVKZFYKWKGEI-UHFFFAOYSA-N"!

 ERROR  No routes to C263008 "DBZQESMMSHHCLU-UHFFFAOYSA-N"!

 ERROR  No routes to C263060 "ZBXRXFNVZOUTEP-UHFFFAOYSA-N"!

 ERROR  No routes to C263137 "ISIXDZMQJHSUKE-UHFFFAOYSA-N"!

 ERROR  No routes to C263490 "AVKHALQBENFZAB-UHFFFAOYSA-N"!

 ERROR  No routes to C263574 "QHUMGTXLPWWSGK-UHFFFAOYSA-N"!

 ERROR  No routes to C264290 "GPNKYXTWBNHZPT-UHFFFAOYSA-N"!

 ERROR  No routes to C264587 "DGJUFCWDGCHNHJ-UHFFFAOYSA-N"!

 ERROR  No routes to C264844 "BUXRHGQNVCOJAV-UHFFFAOYSA-N"!

 ERROR  No routes to C265269 "MRPHOJGAONEVOP-UHFFFAOYSA-N"!

 ERROR  No routes to C265528 "GVLDBCFRTQTATH-UHFFFAOYSA-N"!

 ERROR  No routes to C265627 "AMUKTQNSOMQCIB-UHFFFAOYSA-N"!

 ERROR  No routes to C265803 "LLEPNXKBNOKORR-UHFFFAOYSA-N"!

 ERROR  No routes to C265924 "ZFHNXAYAVKXHKP-UHFFFAOYSA-N"!

 ERROR  No routes to C266276 "UWWHWRPPZMJAIQ-UHFFFAOYSA-N"!

 ERROR  No routes to C266929 "XBEQBBOLHOEXMN-UHFFFAOYSA-N"!

 ERROR  No routes to C267601 "UMYBGOBPHOVEQB-UHFFFAOYSA-N"!

 ERROR  No routes to C267809 "WITUBHADCVVDIK-UHFFFAOYSA-N"!

 ERROR  No routes to C268179 "VKMBNOAFHYYANK-UHFFFAOYSA-N"!

 ERROR  No routes to C272236 "BQSDEPIXYSTHIQ-UHFFFAOYSA-N"!

 ERROR  No routes to C272449 "JHOVMKNPAZUPKC-UHFFFAOYSA-N"!

 ERROR  No routes to C272450 "CZQKOPHNVUQSNW-UHFFFAOYSA-N"!

 ERROR  No routes to C272452 "LXSYKFPSDCVOLS-UHFFFAOYSA-N"!

 ERROR  No routes to C272454 "VAFKCTIAOFBPGI-UHFFFAOYSA-N"!

 ERROR  No routes to C272482 "LNZDVQSHYXFPSN-UHFFFAOYSA-N"!

 ERROR  No routes to C272530 "QXQZOHKAPUDTNY-UHFFFAOYSA-N"!

 ERROR  No routes to C272543 "WQAUBMDSLQUNTO-UHFFFAOYSA-N"!

 ERROR  No routes to C272548 "PZXXIRBXKHKWTF-UHFFFAOYSA-N"!

 ERROR  No routes to C272559 "OVSZTICLVOBVDF-UHFFFAOYSA-N"!

 ERROR  No routes to C272859 "IEZGWHODQGSBRD-UHFFFAOYSA-N"!

 ERROR  No routes to C272877 "PLZILBKPHDDFAT-UHFFFAOYSA-N"!

 ERROR  No routes to C274746 "DGOQEBJTDGIOJZ-UHFFFAOYSA-N"!

 ERROR  No routes to C274747 "PRRHPJGGAIEJHT-UHFFFAOYSA-N"!

 ERROR  No routes to C275059 "MXSLUNSBFKLXMH-UHFFFAOYSA-N"!

 ERROR  No routes to C275086 "BVYHAKCOTPOKAQ-UHFFFAOYSA-N"!

 ERROR  No routes to C275125 "BSFNWEBLPBDYQC-UHFFFAOYSA-N"!

 ERROR  No routes to C275136 "PERWCHKMRHFFHJ-UHFFFAOYSA-N"!

 ERROR  No routes to C275281 "JSYSWGOJEAQZOD-UHFFFAOYSA-N"!

 ERROR  No routes to C275319 "LSQFWTMMCIXCRS-UHFFFAOYSA-N"!

 ERROR  No routes to C275852 "IZMVXIGAIUHYCX-UHFFFAOYSA-N"!

 ERROR  No routes to C276709 "ARBXKTTXCOPQPM-UHFFFAOYSA-N"!

 ERROR  No routes to C277938 "XOJJSEPTUFNDJN-UHFFFAOYSA-N"!

 ERROR  No routes to C277954 "PUPGQZFKQUNUEK-UHFFFAOYSA-N"!

 ERROR  No routes to C279399 "COCQDOCTWRSQRV-UHFFFAOYSA-N"!

 ERROR  No routes to C280132 "YWPKEXDUKMIEPU-UHFFFAOYSA-N"!

 ERROR  No routes to C280144 "TXMSFQQPVYLOJC-UHFFFAOYSA-N"!

 ERROR  No routes to C281589 "LLYQZULXQHKWJM-UHFFFAOYSA-N"!

 ERROR  No routes to C281613 "HGTOZLYKKRRHCA-UHFFFAOYSA-N"!

 ERROR  No routes to C281688 "BFUASKILTZIVFE-UHFFFAOYSA-N"!

 ERROR  No routes to C281724 "UDRXOMVTXMZERG-UHFFFAOYSA-N"!

 ERROR  No routes to C281810 "IKWXEOHVJKYNLH-UHFFFAOYSA-N"!

 ERROR  No routes to C281819 "RRXPKPIXQXLJJA-UHFFFAOYSA-N"!

 ERROR  No routes to C281832 "YBNDHSOAPPIZOW-UHFFFAOYSA-N"!

 ERROR  No routes to C281841 "GMQJBEZLPWHVRH-UHFFFAOYSA-N"!

Solving recipe combinations...

Output()

In [13]:
recipe.write_json("cycle_01/syndirella/retrosynthesis/openbind_a71ev2a_c1_scaffolds.json")

 Warning  NULL Quote: 1.00mg of C282913!

 Warning  NULL Quote: 8.00mg of C282914!

 Warning  NULL Quote: 3.00mg of C282932!

 Warning  NULL Quote: 3.00mg of C282943!

 Warning  NULL Quote: 1.00mg of C284534!

 Warning  NULL Quote: 1.00mg of C284535!

 Warning  NULL Quote: 2.00mg of C6241!

 Warning  NULL Quote: 1.00mg of C285742!

 Warning  NULL Quote: 1.00mg of C6221!

 Warning  NULL Quote: 1.00mg of C284850!

 Warning  NULL Quote: 2.00mg of C284749!

 Warning  NULL Quote: 3.00mg of C284554!

 Warning  NULL Quote: 1.00mg of C285253!

 Warning  NULL Quote: 1.00mg of C286127!

 Warning  NULL Quote: 1.00mg of C286128!

 Warning  NULL Quote: 1.00mg of C284497!

 Warning  NULL Quote: 1.00mg of C284498!

 Warning  NULL Quote: 6.00mg of C284654!

 Warning  NULL Quote: 1.00mg of C285410!

 Warning  NULL Quote: 1.00mg of C284178!

 Warning  NULL Quote: 3.00mg of C284678!

 Warning  NULL Quote: 2.00mg of C284655!

 Warning  NULL Quote: 17.00mg of C283065!

 Warning  NULL Quote: 1.00mg of C284993!

 Warning  NULL Quote: 2.00mg of C285390!

 Warning  NULL Quote: 4.00mg of C284772!

 Warning  NULL Quote: 1.00mg of C285705!

 Warning  NULL Quote: 2.00mg of C285101!

 Warning  NULL Quote: 1.00mg of C285802!

 Warning  NULL Quote: 2.00mg of C284504!

 Warning  NULL Quote: 1.00mg of C284771!

 Warning  NULL Quote: 1.00mg of C284833!

 Warning  NULL Quote: 1.00mg of C286048!

 Warning  NULL Quote: 1.00mg of C286049!

 Warning  NULL Quote: 1.00mg of C284871!

 Warning  NULL Quote: 1.00mg of C284872!

 Warning  NULL Quote: 2.00mg of C285290!

 Warning  NULL Quote: 1.00mg of C285291!

 Warning  NULL Quote: 1.00mg of C286085!

 Warning  NULL Quote: 2.00mg of C285327!

 Warning  NULL Quote: 2.00mg of C285427!

 Warning  NULL Quote: 2.00mg of C283799!

 Warning  NULL Quote: 1.00mg of C285303!

 Warning  NULL Quote: 1.00mg of C285612!

 Warning  NULL Quote: 1.00mg of C285613!

 Warning  NULL Quote: 1.00mg of C285614!

 Warning  NULL Quote: 1.00mg of C285615!

 Warning  NULL Quote: 5.00mg of C284257!

 Warning  NULL Quote: 1.00mg of C285644!

 Warning  NULL Quote: 1.00mg of C284495!

 Warning  NULL Quote: 1.00mg of C284496!

 Warning  NULL Quote: 1.00mg of C285542!

 Warning  NULL Quote: 1.00mg of C285545!

 Warning  NULL Quote: 1.00mg of C284930!

 Warning  NULL Quote: 1.00mg of C285334!

 Warning  NULL Quote: 1.00mg of C274784!

 Warning  NULL Quote: 2.00mg of C284735!

 Warning  NULL Quote: 1.00mg of C285962!

 Warning  NULL Quote: 1.00mg of C285423!

 Warning  NULL Quote: 1.00mg of C285424!

 Warning  NULL Quote: 7.00mg of C283965!

 Warning  NULL Quote: 1.00mg of C284785!

 Warning  NULL Quote: 1.00mg of C283723!

 Warning  NULL Quote: 1.00mg of C285903!

 Warning  NULL Quote: 7.00mg of C283314!

 Warning  NULL Quote: 1.00mg of C285567!

 Warning  NULL Quote: 2.00mg of C284016!

 Warning  NULL Quote: 4.00mg of C284302!

 Warning  NULL Quote: 1.00mg of C284827!

 Warning  NULL Quote: 8.00mg of C284054!

 Warning  NULL Quote: 4.00mg of C285378!

 Warning  NULL Quote: 1.00mg of C284810!

 Warning  NULL Quote: 1.00mg of C284652!

 Warning  NULL Quote: 1.00mg of C285447!

 Warning  NULL Quote: 1.00mg of C285448!

 Warning  NULL Quote: 1.00mg of C285379!

 Warning  NULL Quote: 1.00mg of C285868!

 Warning  NULL Quote: 1.00mg of C285736!

 Warning  NULL Quote: 2.00mg of C284904!

 Warning  NULL Quote: 1.00mg of C285388!

 Warning  NULL Quote: 1.00mg of C285302!

 Warning  NULL Quote: 1.00mg of C284905!

 Warning  NULL Quote: 1.00mg of C285370!

 Warning  NULL Quote: 1.00mg of C286014!

 Warning  NULL Quote: 1.00mg of C286015!

 Warning  NULL Quote: 4.00mg of C283077!

 Warning  NULL Quote: 1.00mg of C285704!

 Warning  NULL Quote: 5.00mg of C284795!

 Warning  NULL Quote: 1.00mg of C285260!

 Warning  NULL Quote: 5.00mg of C283929!

 Warning  NULL Quote: 1.00mg of C285081!

 Warning  NULL Quote: 2.00mg of C284770!

 Warning  NULL Quote: 1.00mg of C285558!

 Warning  NULL Quote: 2.00mg of C284769!

 Warning  NULL Quote: 1.00mg of C285965!

 Warning  NULL Quote: 1.00mg of C285966!

 Warning  NULL Quote: 1.00mg of C285583!

 Warning  NULL Quote: 1.00mg of C285584!

 Warning  NULL Quote: 1.00mg of C285493!

 Warning  NULL Quote: 1.00mg of C285261!

 Warning  NULL Quote: 6.00mg of C283796!

 Warning  NULL Quote: 1.00mg of C284562!

 Warning  NULL Quote: 1.00mg of C285528!

 Warning  NULL Quote: 1.00mg of C286091!

 Warning  NULL Quote: 1.00mg of C284732!

 Warning  NULL Quote: 1.00mg of C285102!

 Warning  NULL Quote: 3.00mg of C282976!

 Warning  NULL Quote: 2.00mg of C284544!

 Warning  NULL Quote: 3.00mg of C284865!

 Warning  NULL Quote: 1.00mg of C284911!

 Warning  NULL Quote: 1.00mg of C284912!

 Warning  NULL Quote: 4.00mg of C284939!

 Warning  NULL Quote: 1.00mg of C286019!

 Warning  NULL Quote: 1.00mg of C284940!

 Warning  NULL Quote: 1.00mg of C286076!

 Warning  NULL Quote: 1.00mg of C286078!

 Warning  NULL Quote: 3.00mg of C284138!

 Warning  NULL Quote: 1.00mg of C285428!

 Warning  NULL Quote: 1.00mg of C285148!

 Warning  NULL Quote: 1.00mg of C285988!

 Warning  NULL Quote: 1.00mg of C285989!

 Warning  NULL Quote: 3.00mg of C283060!

 Warning  NULL Quote: 1.00mg of C285231!

 Warning  NULL Quote: 2.00mg of C283841!

 Warning  NULL Quote: 1.00mg of C285300!

 Warning  NULL Quote: 1.00mg of C285933!

 Warning  NULL Quote: 1.00mg of C285934!

 Warning  NULL Quote: 1.00mg of C285210!

 Warning  NULL Quote: 1.00mg of C285211!

 Warning  NULL Quote: 1.00mg of C285089!

 Warning  NULL Quote: 5.00mg of C285090!

 Warning  NULL Quote: 1.00mg of C285793!

 Warning  NULL Quote: 1.00mg of C284662!

 Warning  NULL Quote: 1.00mg of C284606!

 Warning  NULL Quote: 9.00mg of C283907!

 Warning  NULL Quote: 1.00mg of C285641!

 Warning  NULL Quote: 1.00mg of C284737!

 Warning  NULL Quote: 1.00mg of C285178!

 Warning  NULL Quote: 1.00mg of C284900!

 Warning  NULL Quote: 1.00mg of C285737!

 Warning  NULL Quote: 1.00mg of C284734!

 Warning  NULL Quote: 1.00mg of C285873!

 Warning  NULL Quote: 1.00mg of C284943!

 Warning  NULL Quote: 2.00mg of C285707!

 Warning  NULL Quote: 1.00mg of C285708!

 Warning  NULL Quote: 1.00mg of C284432!

 Warning  NULL Quote: 1.00mg of C284433!

 Warning  NULL Quote: 2.00mg of C284869!

 Warning  NULL Quote: 1.00mg of C285032!

 Warning  NULL Quote: 1.00mg of C286103!

 Warning  NULL Quote: 1.00mg of C286104!

 Warning  NULL Quote: 1.00mg of C285272!

 Warning  NULL Quote: 1.00mg of C285273!

 Warning  NULL Quote: 6.00mg of C284165!

 Warning  NULL Quote: 2.00mg of C285760!

 Warning  NULL Quote: 3.00mg of C284346!

 Warning  NULL Quote: 2.00mg of C284310!

 Warning  NULL Quote: 1.00mg of C285248!

 Warning  NULL Quote: 1.00mg of C285395!

 Warning  NULL Quote: 1.00mg of C285396!

 Warning  NULL Quote: 1.00mg of C284969!

 Warning  NULL Quote: 1.00mg of C284970!

 Warning  NULL Quote: 1.00mg of C285937!

 Warning  NULL Quote: 1.00mg of C284499!

 Warning  NULL Quote: 1.00mg of C284888!

 Warning  NULL Quote: 3.00mg of C283732!

 Warning  NULL Quote: 1.00mg of C285406!

 Warning  NULL Quote: 1.00mg of C285233!

 Warning  NULL Quote: 1.00mg of C285200!

 Warning  NULL Quote: 1.00mg of C285201!

 Warning  NULL Quote: 8.00mg of C284637!

 Warning  NULL Quote: 1.00mg of C286016!

 Warning  NULL Quote: 1.00mg of C285513!

 Warning  NULL Quote: 1.00mg of C286011!

 Warning  NULL Quote: 1.00mg of C285421!

 Warning  NULL Quote: 1.00mg of C285422!

 Warning  NULL Quote: 1.00mg of C284543!

 Warning  NULL Quote: 1.00mg of C285212!

 Warning  NULL Quote: 1.00mg of C284092!

 Warning  NULL Quote: 1.00mg of C285385!

 Warning  NULL Quote: 1.00mg of C283906!

 Warning  NULL Quote: 4.00mg of C283063!

 Warning  NULL Quote: 1.00mg of C284679!

 Warning  NULL Quote: 1.00mg of C284680!

 Warning  NULL Quote: 1.00mg of C285138!

 Warning  NULL Quote: 11.00mg of C283032!

 Warning  NULL Quote: 1.00mg of C284661!

 Warning  NULL Quote: 1.00mg of C285702!

 Warning  NULL Quote: 1.00mg of C285403!

 Warning  NULL Quote: 1.00mg of C285404!

 Warning  NULL Quote: 4.00mg of C284619!

 Warning  NULL Quote: 1.00mg of C285349!

 Warning  NULL Quote: 1.00mg of C284618!

 Warning  NULL Quote: 1.00mg of C285181!

 Warning  NULL Quote: 1.00mg of C285182!

 Warning  NULL Quote: 1.00mg of C285953!

 Warning  NULL Quote: 1.00mg of C285954!

 Warning  NULL Quote: 1.00mg of C284558!

 Warning  NULL Quote: 1.00mg of C284559!

 Warning  NULL Quote: 1.00mg of C285915!

 Warning  NULL Quote: 1.00mg of C285916!

 Warning  NULL Quote: 1.00mg of C284415!

 Warning  NULL Quote: 1.00mg of C285886!

 Warning  NULL Quote: 1.00mg of C284954!

 Warning  NULL Quote: 1.00mg of C284955!

 Warning  NULL Quote: 1.00mg of C285919!

 Warning  NULL Quote: 1.00mg of C285920!

 Warning  NULL Quote: 1.00mg of C285301!

 Warning  NULL Quote: 2.00mg of C284435!

 Warning  NULL Quote: 2.00mg of C285618!

 Warning  NULL Quote: 4.00mg of C283057!

 Warning  NULL Quote: 3.00mg of C283840!

 Warning  NULL Quote: 1.00mg of C285861!

 Warning  NULL Quote: 1.00mg of C283082!

 Warning  NULL Quote: 1.00mg of C283083!

 Warning  NULL Quote: 1.00mg of C284331!

 Warning  NULL Quote: 1.00mg of C286105!

 Warning  NULL Quote: 1.00mg of C286106!

 Warning  NULL Quote: 2.00mg of C283026!

 Warning  NULL Quote: 4.00mg of C284056!

 Warning  NULL Quote: 1.00mg of C284472!

 Warning  NULL Quote: 2.00mg of C284437!

 Warning  NULL Quote: 1.00mg of C285262!

 Warning  NULL Quote: 1.00mg of C285263!

 Warning  NULL Quote: 5.00mg of C283924!

 Warning  NULL Quote: 1.00mg of C286121!

 Warning  NULL Quote: 1.00mg of C284730!

 Warning  NULL Quote: 2.00mg of C284731!

 Warning  NULL Quote: 6.00mg of C283820!

 Warning  NULL Quote: 1.00mg of C283995!

 Warning  NULL Quote: 1.00mg of C286006!

 Warning  NULL Quote: 1.00mg of C284828!

 Warning  NULL Quote: 3.00mg of C283058!

 Warning  NULL Quote: 1.00mg of C284815!

 Warning  NULL Quote: 1.00mg of C284816!

 Warning  NULL Quote: 2.00mg of C283837!

 Warning  NULL Quote: 2.00mg of C284851!

 Warning  NULL Quote: 1.00mg of C285104!

 Warning  NULL Quote: 1.00mg of C285105!

 Warning  NULL Quote: 3.00mg of C283935!

 Warning  NULL Quote: 1.00mg of C285616!

 Warning  NULL Quote: 1.00mg of C286130!

 Warning  NULL Quote: 1.00mg of C283066!

 Warning  NULL Quote: 1.00mg of C285932!

 Warning  NULL Quote: 1.00mg of C285963!

 Warning  NULL Quote: 1.00mg of C285964!

 Warning  NULL Quote: 3.00mg of C284195!

 Warning  NULL Quote: 1.00mg of C285885!

 Warning  NULL Quote: 2.00mg of C284401!

 Warning  NULL Quote: 1.00mg of C285971!

 Warning  NULL Quote: 1.00mg of C285714!

 Warning  NULL Quote: 1.00mg of C285715!

 Warning  NULL Quote: 1.00mg of C1871!

 Warning  NULL Quote: 1.00mg of C284653!

 Warning  NULL Quote: 1.00mg of C285619!

 Warning  NULL Quote: 2.00mg of C285394!

 Warning  NULL Quote: 3.00mg of C284945!

 Warning  NULL Quote: 1.00mg of C284946!

 Warning  NULL Quote: 1.00mg of C284893!

 Warning  NULL Quote: 4.00mg of C284685!

 Warning  NULL Quote: 1.00mg of C285869!

 Warning  NULL Quote: 1.00mg of C284858!

 Warning  NULL Quote: 1.00mg of C284859!

 Warning  NULL Quote: 1.00mg of C285507!

 Warning  NULL Quote: 2.00mg of C285508!

 Warning  NULL Quote: 2.00mg of C285723!

 Warning  NULL Quote: 1.00mg of C285877!

 Warning  NULL Quote: 1.00mg of C286129!

 Warning  NULL Quote: 1.00mg of C284877!

 Warning  NULL Quote: 1.00mg of C285821!

 Warning  NULL Quote: 1.00mg of C286109!

 Warning  NULL Quote: 4.00mg of C284550!

 Warning  NULL Quote: 1.00mg of C285183!

 Warning  NULL Quote: 1.00mg of C284590!

 Warning  NULL Quote: 1.00mg of C284286!

 Warning  NULL Quote: 1.00mg of C285779!

 Warning  NULL Quote: 1.00mg of C284740!

 Warning  NULL Quote: 1.00mg of C284118!

 Warning  NULL Quote: 1.00mg of C285973!

 Warning  NULL Quote: 1.00mg of C285283!

 Warning  NULL Quote: 1.00mg of C285284!

 Warning  NULL Quote: 1.00mg of C284697!

 Warning  NULL Quote: 1.00mg of C285781!

 Warning  NULL Quote: 4.00mg of C284937!

 Warning  NULL Quote: 1.00mg of C285345!

 Warning  NULL Quote: 1.00mg of C285833!

 Warning  NULL Quote: 1.00mg of C285096!

 Warning  NULL Quote: 1.00mg of C285097!

 Warning  NULL Quote: 1.00mg of C284117!

 Warning  NULL Quote: 1.00mg of C285765!

 Warning  NULL Quote: 1.00mg of C285927!

 Warning  NULL Quote: 2.00mg of C284777!

 Warning  NULL Quote: 1.00mg of C284778!

 Warning  NULL Quote: 2.00mg of C285010!

 Warning  NULL Quote: 1.00mg of C285011!

 Warning  NULL Quote: 1.00mg of C285356!

 Warning  NULL Quote: 1.00mg of C285510!

 Warning  NULL Quote: 3.00mg of C284875!

 Warning  NULL Quote: 1.00mg of C284874!

 Warning  NULL Quote: 1.00mg of C286089!

 Warning  NULL Quote: 1.00mg of C286090!

 Warning  NULL Quote: 1.00mg of C285766!

 Warning  NULL Quote: 1.00mg of C285767!

 Warning  NULL Quote: 4.00mg of C284844!

 Warning  NULL Quote: 1.00mg of C285834!

 Warning  NULL Quote: 1.00mg of C284843!

 Warning  NULL Quote: 1.00mg of C285016!

 Warning  NULL Quote: 4.00mg of C284464!

 Warning  NULL Quote: 3.00mg of C285191!

 Warning  NULL Quote: 1.00mg of C285190!

 Warning  NULL Quote: 2.00mg of C285217!

 Warning  NULL Quote: 1.00mg of C285397!

 Warning  NULL Quote: 1.00mg of C285398!

 Warning  NULL Quote: 1.00mg of C286020!

 Warning  NULL Quote: 1.00mg of C286021!

 Warning  NULL Quote: 1.00mg of C285150!

 Warning  NULL Quote: 1.00mg of C284434!

 Warning  NULL Quote: 1.00mg of C285322!

 Warning  NULL Quote: 3.00mg of C283921!

 Warning  NULL Quote: 1.00mg of C285062!

 Warning  NULL Quote: 1.00mg of C285405!

 Warning  NULL Quote: 1.00mg of C284557!

 Warning  NULL Quote: 1.00mg of C284750!

 Warning  NULL Quote: 1.00mg of C284751!

 Warning  NULL Quote: 1.00mg of C12688!

 Warning  NULL Quote: 1.00mg of C285367!

 Warning  NULL Quote: 3.00mg of C282925!

 Warning  NULL Quote: 5.00mg of C284475!

 Warning  NULL Quote: 1.00mg of C285061!

 Warning  NULL Quote: 1.00mg of C284474!

 Warning  NULL Quote: 1.00mg of C285740!

 Warning  NULL Quote: 13.00mg of C283068!

 Warning  NULL Quote: 2.00mg of C285373!

 Warning  NULL Quote: 1.00mg of C285146!

 Warning  NULL Quote: 1.00mg of C284684!

 Warning  NULL Quote: 9.00mg of C283835!

 Warning  NULL Quote: 3.00mg of C285485!

 Warning  NULL Quote: 1.00mg of C284644!

 Warning  NULL Quote: 1.00mg of C284542!

 Warning  NULL Quote: 2.00mg of C285996!

 Warning  NULL Quote: 1.00mg of C285484!

 Warning  NULL Quote: 1.00mg of C285541!

 Warning  NULL Quote: 1.00mg of C285697!

 Warning  NULL Quote: 1.00mg of C6035!

 Warning  NULL Quote: 1.00mg of C285377!

 Warning  NULL Quote: 1.00mg of C285711!

 Warning  NULL Quote: 1.00mg of C285177!

 Warning  NULL Quote: 1.00mg of C284950!

 Warning  NULL Quote: 2.00mg of C284519!

 Warning  NULL Quote: 1.00mg of C284520!

 Warning  NULL Quote: 2.00mg of C285053!

 Warning  NULL Quote: 3.00mg of C285103!

 Warning  NULL Quote: 1.00mg of C285437!

 Warning  NULL Quote: 3.00mg of C284232!

 Warning  NULL Quote: 2.00mg of C284505!

 Warning  NULL Quote: 1.00mg of C285946!

 Warning  NULL Quote: 2.00mg of C284512!

 Warning  NULL Quote: 1.00mg of C284465!

 Warning  NULL Quote: 1.00mg of C285258!

 Warning  NULL Quote: 1.00mg of C285259!

 Warning  NULL Quote: 1.00mg of C285923!

 Warning  NULL Quote: 5.00mg of C283930!

 Warning  NULL Quote: 3.00mg of C284698!

 Warning  NULL Quote: 1.00mg of C284686!

 Warning  NULL Quote: 1.00mg of C284687!

 Warning  NULL Quote: 4.00mg of C283814!

 Warning  NULL Quote: 1.00mg of C285876!

 Warning  NULL Quote: 1.00mg of C284603!

 Warning  NULL Quote: 1.00mg of C284814!

 Warning  NULL Quote: 1.00mg of C284866!

 Warning  NULL Quote: 1.00mg of C284583!

 Warning  NULL Quote: 2.00mg of C284584!

 Warning  NULL Quote: 2.00mg of C283051!

 Warning  NULL Quote: 1.00mg of C286047!

 Warning  NULL Quote: 1.00mg of C285809!

 Warning  NULL Quote: 1.00mg of C285813!

 Warning  NULL Quote: 1.00mg of C285292!

 Warning  NULL Quote: 1.00mg of C285293!

 Warning  NULL Quote: 1.00mg of C285264!

 Warning  NULL Quote: 1.00mg of C285265!

 Warning  NULL Quote: 1.00mg of C284620!

 Warning  NULL Quote: 1.00mg of C284621!

 Warning  NULL Quote: 1.00mg of C285574!

 Warning  NULL Quote: 2.00mg of C285038!

 Warning  NULL Quote: 1.00mg of C285958!

 Warning  NULL Quote: 4.00mg of C284063!

 Warning  NULL Quote: 1.00mg of C285955!

 Warning  NULL Quote: 2.00mg of C284551!

 Warning  NULL Quote: 1.00mg of C285082!

 Warning  NULL Quote: 1.00mg of C5322!

 Warning  NULL Quote: 4.00mg of C284301!

 Warning  NULL Quote: 2.00mg of C284763!

 Warning  NULL Quote: 2.00mg of C285331!

 Warning  NULL Quote: 3.00mg of C284773!

 Warning  NULL Quote: 22.00mg of C283237!

 Warning  NULL Quote: 1.00mg of C285706!

 Warning  NULL Quote: 1.00mg of C285959!

 Warning  NULL Quote: 1.00mg of C285735!

 Warning  NULL Quote: 1.00mg of C284941!

 Warning  NULL Quote: 1.00mg of C284942!

 Warning  NULL Quote: 1.00mg of C285769!

 Warning  NULL Quote: 3.00mg of C7133!

 Warning  NULL Quote: 1.00mg of C284563!

 Warning  NULL Quote: 1.00mg of C284615!

 Warning  NULL Quote: 1.00mg of C284614!

 Warning  NULL Quote: 1.00mg of C284825!

 Warning  NULL Quote: 1.00mg of C285451!

 Warning  NULL Quote: 1.00mg of C286110!

 Warning  NULL Quote: 1.00mg of C285189!

 Warning  NULL Quote: 1.00mg of C284791!

 Warning  NULL Quote: 1.00mg of C285754!

 Warning  NULL Quote: 1.00mg of C284011!

 Warning  NULL Quote: 2.00mg of C284012!

 Warning  NULL Quote: 1.00mg of C285465!

 Warning  NULL Quote: 1.00mg of C285466!

 Warning  NULL Quote: 1.00mg of C284933!

 Warning  NULL Quote: 1.00mg of C285783!

 Warning  NULL Quote: 1.00mg of C285784!

 Warning  NULL Quote: 1.00mg of C285534!

 Warning  NULL Quote: 1.00mg of C285535!

 Warning  NULL Quote: 2.00mg of C284244!

 Warning  NULL Quote: 2.00mg of C284459!

 Warning  NULL Quote: 1.00mg of C285195!

 Warning  NULL Quote: 2.00mg of C285196!

 Warning  NULL Quote: 1.00mg of C285363!

 Warning  NULL Quote: 1.00mg of C285364!

 Warning  NULL Quote: 1.00mg of C285409!

 Warning  NULL Quote: 1.00mg of C285550!

 Warning  NULL Quote: 1.00mg of C284636!

 Warning  NULL Quote: 1.00mg of C284575!

 Warning  NULL Quote: 1.00mg of C284576!

 Warning  NULL Quote: 1.00mg of C284651!

 Warning  NULL Quote: 1.00mg of C285098!

 Warning  NULL Quote: 1.00mg of C285763!

 Warning  NULL Quote: 1.00mg of C285764!

 Warning  NULL Quote: 2.00mg of C284699!

 Warning  NULL Quote: 2.00mg of C285037!

 Warning  NULL Quote: 1.00mg of C285121!

 Warning  NULL Quote: 3.00mg of C7596!

 Warning  NULL Quote: 2.00mg of C284808!

 Warning  NULL Quote: 2.00mg of C285455!

 Warning  NULL Quote: 4.00mg of C283743!

 Warning  NULL Quote: 1.00mg of C285112!

 Warning  NULL Quote: 2.00mg of C285425!

 Warning  NULL Quote: 1.00mg of C285426!

 Warning  NULL Quote: 1.00mg of C285129!

 Warning  NULL Quote: 2.00mg of C285130!

 Warning  NULL Quote: 1.00mg of C285900!

 Warning  NULL Quote: 4.00mg of C284845!

 Warning  NULL Quote: 1.00mg of C284921!

 Warning  NULL Quote: 1.00mg of C286074!

 Warning  NULL Quote: 1.00mg of C286075!

 Warning  NULL Quote: 2.00mg of C284669!

 Warning  NULL Quote: 2.00mg of C284670!

 Warning  NULL Quote: 1.00mg of C284846!

 Warning  NULL Quote: 4.00mg of C284006!

 Warning  NULL Quote: 1.00mg of C285214!

 Warning  NULL Quote: 1.00mg of C285230!

 Warning  NULL Quote: 1.00mg of C283938!

 Warning  NULL Quote: 1.00mg of C285832!

 Warning  NULL Quote: 1.00mg of C284460!

 Warning  NULL Quote: 1.00mg of C283931!

 Warning  NULL Quote: 1.00mg of C285651!

 Warning  NULL Quote: 1.00mg of C285600!

 Warning  NULL Quote: 1.00mg of C286161!

 Warning  NULL Quote: 1.00mg of C286141!

 Warning  NULL Quote: 1.00mg of C286142!

 Warning  NULL Quote: 1.00mg of C286079!

 Warning  NULL Quote: 2.00mg of C284133!

 Warning  NULL Quote: 1.00mg of C284792!

 Warning  NULL Quote: 1.00mg of C284910!

 Warning  NULL Quote: 1.00mg of C284715!

 Warning  NULL Quote: 1.00mg of C285257!

 Warning  NULL Quote: 13.00mg of C284591!

 Warning  NULL Quote: 1.00mg of C284592!

 Warning  NULL Quote: 1.00mg of C285351!

 Warning  NULL Quote: 1.00mg of C284951!

 Warning  NULL Quote: 1.00mg of C285945!

 Warning  NULL Quote: 1.00mg of C285947!

 Warning  NULL Quote: 5.00mg of C284524!

 Warning  NULL Quote: 1.00mg of C284847!

 Warning  NULL Quote: 1.00mg of C284525!

 Warning  NULL Quote: 1.00mg of C285202!

 Warning  NULL Quote: 1.00mg of C285536!

 Warning  NULL Quote: 1.00mg of C286086!

 Warning  NULL Quote: 1.00mg of C286136!

 Warning  NULL Quote: 1.00mg of C286137!

 Warning  NULL Quote: 4.00mg of C284027!

 Warning  NULL Quote: 4.00mg of C284572!

 Warning  NULL Quote: 1.00mg of C285500!

 Warning  NULL Quote: 1.00mg of C284672!

 Warning  NULL Quote: 1.00mg of C284673!

 Warning  NULL Quote: 3.00mg of C284124!

 Warning  NULL Quote: 1.00mg of C285557!

 Warning  NULL Quote: 2.00mg of C284243!

 Warning  NULL Quote: 1.00mg of C285478!

 Warning  NULL Quote: 1.00mg of C284656!

 Warning  NULL Quote: 1.00mg of C284657!

 Warning  NULL Quote: 2.00mg of C283954!

 Warning  NULL Quote: 1.00mg of C285220!

 Warning  NULL Quote: 1.00mg of C285343!

 Warning  NULL Quote: 2.00mg of C285344!

 Warning  NULL Quote: 1.00mg of C286007!

 Warning  NULL Quote: 2.00mg of C284196!

 Warning  NULL Quote: 1.00mg of C285034!

 Warning  NULL Quote: 1.00mg of C284870!

 Warning  NULL Quote: 1.00mg of C284798!

 Warning  NULL Quote: 1.00mg of C284040!

 Warning  NULL Quote: 3.00mg of C284739!

 Warning  NULL Quote: 3.00mg of C284793!

 Warning  NULL Quote: 1.00mg of C284848!

 Warning  NULL Quote: 2.00mg of C284842!

 Warning  NULL Quote: 1.00mg of C285480!

 Warning  NULL Quote: 1.00mg of C285537!

 Warning  NULL Quote: 2.00mg of C284762!

 Warning  NULL Quote: 1.00mg of C284775!

 Warning  NULL Quote: 1.00mg of C284776!

 Warning  NULL Quote: 1.00mg of C285917!

 Warning  NULL Quote: 1.00mg of C285918!

 Warning  NULL Quote: 1.00mg of C284867!

 Warning  NULL Quote: 1.00mg of C284868!

 Warning  NULL Quote: 1.00mg of C284134!

 Warning  NULL Quote: 1.00mg of C285610!

 Warning  NULL Quote: 1.00mg of C286039!

 Warning  NULL Quote: 1.00mg of C286040!

 Warning  NULL Quote: 1.00mg of C286073!

 Warning  NULL Quote: 1.00mg of C285908!

 Warning  NULL Quote: 1.00mg of C285909!

 Warning  NULL Quote: 1.00mg of C285922!

 Warning  NULL Quote: 1.00mg of C1873!

 Warning  NULL Quote: 1.00mg of C285952!

 Warning  NULL Quote: 5.00mg of C283151!

 Warning  NULL Quote: 1.00mg of C284368!

 Warning  NULL Quote: 1.00mg of C285692!

 Warning  NULL Quote: 1.00mg of C285693!

 Warning  NULL Quote: 1.00mg of C284862!

 Warning  NULL Quote: 5.00mg of C282917!

 Warning  NULL Quote: 1.00mg of C285476!

 Warning  NULL Quote: 1.00mg of C285477!

 Warning  NULL Quote: 1.00mg of C284952!

 Warning  NULL Quote: 1.00mg of C284953!

 Warning  NULL Quote: 1.00mg of C285087!

 Warning  NULL Quote: 1.00mg of C285088!

 Warning  NULL Quote: 1.00mg of C285375!

 Warning  NULL Quote: 1.00mg of C285376!

 Warning  NULL Quote: 1.00mg of C285386!

 Warning  NULL Quote: 1.00mg of C284831!

 Warning  NULL Quote: 1.00mg of C284832!

 Warning  NULL Quote: 2.00mg of C284548!

 Warning  NULL Quote: 1.00mg of C285137!

 Warning  NULL Quote: 1.00mg of C285548!

 Warning  NULL Quote: 1.00mg of C285549!

 Warning  NULL Quote: 1.00mg of C284947!

 Warning  NULL Quote: 1.00mg of C284948!

 Warning  NULL Quote: 6.00mg of C283867!

 Warning  NULL Quote: 1.00mg of C284944!

 Warning  NULL Quote: 1.00mg of C284796!

 Warning  NULL Quote: 2.00mg of C284852!

 Warning  NULL Quote: 1.00mg of C284688!

 Warning  NULL Quote: 1.00mg of C284689!

 Warning  NULL Quote: 1.00mg of C285249!

 Warning  NULL Quote: 1.00mg of C285250!

 Warning  NULL Quote: 1.00mg of C284897!

 Warning  NULL Quote: 2.00mg of C65033!

 Warning  NULL Quote: 1.00mg of C285703!

 Warning  NULL Quote: 1.00mg of C285756!

 Warning  NULL Quote: 1.00mg of C22696!

 Warning  NULL Quote: 1.00mg of C5710!

 Warning  NULL Quote: 1.00mg of C285948!

 Warning  NULL Quote: 1.00mg of C285949!

 Warning  NULL Quote: 2.00mg of C283832!

 Warning  NULL Quote: 1.00mg of C285355!

 Warning  NULL Quote: 3.00mg of C285080!

 Warning  NULL Quote: 1.00mg of C285956!

 Warning  NULL Quote: 1.00mg of C285108!

 Warning  NULL Quote: 1.00mg of C285079!

 Warning  NULL Quote: 1.00mg of C285666!

 Warning  NULL Quote: 1.00mg of C285667!

 Warning  NULL Quote: 1.00mg of C285411!

 Warning  NULL Quote: 1.00mg of C284979!

 Warning  NULL Quote: 1.00mg of C284980!

 Warning  NULL Quote: 1.00mg of C285147!

 Warning  NULL Quote: 4.00mg of C284760!

 Warning  NULL Quote: 1.00mg of C284860!

 Warning  NULL Quote: 1.00mg of C285944!

 Warning  NULL Quote: 1.00mg of C284761!

 Warning  NULL Quote: 5.00mg of C283896!

 Warning  NULL Quote: 1.00mg of C285069!

 Warning  NULL Quote: 1.00mg of C285790!

 Warning  NULL Quote: 1.00mg of C285113!

 Warning  NULL Quote: 1.00mg of C285095!

 Warning  NULL Quote: 2.00mg of C284388!

 Warning  NULL Quote: 1.00mg of C285975!

 Warning  NULL Quote: 1.00mg of C285288!

 Warning  NULL Quote: 1.00mg of C285289!

 Warning  NULL Quote: 1.00mg of C285118!

 Warning  NULL Quote: 2.00mg of C283914!

 Warning  NULL Quote: 1.00mg of C284463!

 Warning  NULL Quote: 1.00mg of C285776!

 Warning  NULL Quote: 1.00mg of C285777!

 Warning  NULL Quote: 1.00mg of C285179!

 Warning  NULL Quote: 1.00mg of C284918!

 Warning  NULL Quote: 1.00mg of C285119!

 Warning  NULL Quote: 1.00mg of C285120!

 Warning  NULL Quote: 2.00mg of C284188!

 Warning  NULL Quote: 1.00mg of C285755!

 Warning  NULL Quote: 1.00mg of C285725!

 Warning  NULL Quote: 1.00mg of C285726!

 Warning  NULL Quote: 1.00mg of C285709!

 Warning  NULL Quote: 1.00mg of C285710!

 Warning  NULL Quote: 1.00mg of C284712!

 Warning  NULL Quote: 1.00mg of C284714!

 Warning  NULL Quote: 1.00mg of C286013!

 Warning  NULL Quote: 1.00mg of C286018!

 Warning  NULL Quote: 1.00mg of C286022!

 Warning  NULL Quote: 1.00mg of C284924!

 Warning  NULL Quote: 1.00mg of C285389!

 Warning  NULL Quote: 2.00mg of C284586!

 Warning  NULL Quote: 1.00mg of C285888!

 Warning  NULL Quote: 1.00mg of C284873!

 Warning  NULL Quote: 1.00mg of C285986!

 Warning  NULL Quote: 1.00mg of C285987!

 Warning  NULL Quote: 2.00mg of C284080!

 Warning  NULL Quote: 1.00mg of C285475!

 Warning  NULL Quote: 1.00mg of C285197!

 Warning  NULL Quote: 1.00mg of C285184!

 Warning  NULL Quote: 2.00mg of C284629!

 Warning  NULL Quote: 1.00mg of C284645!

 Warning  NULL Quote: 1.00mg of C284628!

 Warning  NULL Quote: 2.00mg of C284363!

 Warning  NULL Quote: 1.00mg of C286008!

 Warning  NULL Quote: 4.00mg of C284240!

 Warning  NULL Quote: 1.00mg of C284938!

 Warning  NULL Quote: 1.00mg of C284863!

 Warning  NULL Quote: 1.00mg of C284864!

 Warning  NULL Quote: 1.00mg of C46461!

 Warning  NULL Quote: 1.00mg of C284671!

 Warning  NULL Quote: 1.00mg of C285889!

 Warning  NULL Quote: 1.00mg of C284971!

 Warning  NULL Quote: 1.00mg of C284972!

 Warning  NULL Quote: 1.00mg of C285787!

 Warning  NULL Quote: 1.00mg of C285788!

 Warning  NULL Quote: 1.00mg of C285140!

 Warning  NULL Quote: 1.00mg of C285141!

 Warning  NULL Quote: 1.00mg of C285659!

 Warning  NULL Quote: 1.00mg of C285660!

 Warning  NULL Quote: 1.00mg of C285745!

 Warning  NULL Quote: 1.00mg of C284674!

 Warning  NULL Quote: 2.00mg of C284112!

 Warning  NULL Quote: 1.00mg of C284811!

 Warning  NULL Quote: 1.00mg of C283067!

 Warning  NULL Quote: 1.00mg of C285446!

 Warning  NULL Quote: 1.00mg of C285924!

 Warning  NULL Quote: 1.00mg of C285842!

 Warning  NULL Quote: 1.00mg of C285665!

 Warning  NULL Quote: 1.00mg of C283917!

 Warning  NULL Quote: 1.00mg of C6519!

 Warning  NULL Quote: 1.00mg of C285655!

 Warning  NULL Quote: 1.00mg of C285656!

 Warning  NULL Quote: 1.00mg of C284506!

 Warning  NULL Quote: 1.00mg of C284507!

 Warning  NULL Quote: 3.00mg of C284768!

 Warning  NULL Quote: 2.00mg of C284239!

 Warning  NULL Quote: 1.00mg of C285256!

 Warning  NULL Quote: 1.00mg of C285596!

 Warning  NULL Quote: 2.00mg of C285246!

 Warning  NULL Quote: 1.00mg of C285247!

 Warning  NULL Quote: 2.00mg of C285275!

 Warning  NULL Quote: 1.00mg of C285870!

 Warning  NULL Quote: 2.00mg of C284377!

 Warning  NULL Quote: 2.00mg of C284885!

 Warning  NULL Quote: 1.00mg of C284536!

 Warning  NULL Quote: 1.00mg of C284537!

 Warning  NULL Quote: 1.00mg of C284675!

 Warning  NULL Quote: 1.00mg of C284024!

 Warning  NULL Quote: 1.00mg of C285716!

 Warning  NULL Quote: 2.00mg of C285027!

 Warning  NULL Quote: 1.00mg of C285566!

 Warning  NULL Quote: 1.00mg of C285026!

 Warning  NULL Quote: 1.00mg of C285371!

 Warning  NULL Quote: 1.00mg of C285372!

 Warning  NULL Quote: 1.00mg of C285335!

 Warning  NULL Quote: 1.00mg of C285336!

 Warning  NULL Quote: 2.00mg of C284251!

 Warning  NULL Quote: 1.00mg of C285330!

 Warning  NULL Quote: 1.00mg of C284139!

 Warning  NULL Quote: 1.00mg of C285694!

 Warning  NULL Quote: 1.00mg of C285883!

 Warning  NULL Quote: 1.00mg of C285884!

 Warning  NULL Quote: 1.00mg of C284807!

 Warning  NULL Quote: 1.00mg of C285282!

 Warning  NULL Quote: 1.00mg of C285887!

 Warning  NULL Quote: 1.00mg of C285299!

 Warning  NULL Quote: 1.00mg of C285744!

 Warning  NULL Quote: 1.00mg of C285287!

 Warning  NULL Quote: 1.00mg of C285743!

 Warning  NULL Quote: 1.00mg of C285106!

 Warning  NULL Quote: 2.00mg of C284758!

 Warning  NULL Quote: 1.00mg of C284882!

 Warning  NULL Quote: 2.00mg of C284136!

 Warning  NULL Quote: 1.00mg of C285237!

 Warning  NULL Quote: 2.00mg of C283970!

 Warning  NULL Quote: 1.00mg of C286101!

 Warning  NULL Quote: 2.00mg of C95371!

 Warning  NULL Quote: 1.00mg of C285412!

 Warning  NULL Quote: 1.00mg of C284103!

 Warning  NULL Quote: 1.00mg of C283776!

 Warning  NULL Quote: 1.00mg of C283777!

 Warning  NULL Quote: 5.00mg of C283996!

 Warning  NULL Quote: 1.00mg of C284206!

 Warning  NULL Quote: 1.00mg of C285235!

 Warning  NULL Quote: 1.00mg of C285236!

 Warning  NULL Quote: 2.00mg of C283880!

 Warning  NULL Quote: 1.00mg of C284585!

 Warning  NULL Quote: 1.00mg of C284593!

 Warning  NULL Quote: 1.00mg of C284594!

 Warning  NULL Quote: 1.00mg of C284588!

 Warning  NULL Quote: 1.00mg of C284589!

 Warning  NULL Quote: 1.00mg of C286138!

 Warning  NULL Quote: 1.00mg of C286139!

 Warning  NULL Quote: 1.00mg of C285878!

 Warning  NULL Quote: 1.00mg of C285738!

 Warning  NULL Quote: 1.00mg of C285739!

 Warning  NULL Quote: 1.00mg of C284691!

 Warning  NULL Quote: 2.00mg of C284259!

 Warning  NULL Quote: 1.00mg of C285762!

 Warning  NULL Quote: 1.00mg of C285690!

 Warning  NULL Quote: 1.00mg of C285691!

 Warning  NULL Quote: 1.00mg of C48047!

 Warning  NULL Quote: 1.00mg of C284347!

 Warning  NULL Quote: 1.00mg of C284564!

 Warning  NULL Quote: 7.00mg of C283756!

 Warning  NULL Quote: 1.00mg of C285761!

 Warning  NULL Quote: 1.00mg of C284540!

 Warning  NULL Quote: 2.00mg of C284541!

 Warning  NULL Quote: 1.00mg of C285472!

 Warning  NULL Quote: 1.00mg of C285139!

 Warning  NULL Quote: 1.00mg of C285352!

 Warning  NULL Quote: 1.00mg of C6247!

 Warning  NULL Quote: 1.00mg of C284348!

 Warning  NULL Quote: 1.00mg of C284748!

 Warning  NULL Quote: 1.00mg of C284747!

 Warning  NULL Quote: 1.00mg of C284461!

 Warning  NULL Quote: 1.00mg of C284462!

 Warning  NULL Quote: 1.00mg of C285925!

 Warning  NULL Quote: 1.00mg of C285926!

 Warning  NULL Quote: 2.00mg of C284741!

 Warning  NULL Quote: 1.00mg of C284742!

 Warning  NULL Quote: 1.00mg of C285511!

 Warning  NULL Quote: 1.00mg of C285950!

 Warning  NULL Quote: 1.00mg of C285951!

 Warning  NULL Quote: 2.00mg of C284853!

 Warning  NULL Quote: 1.00mg of C285921!

 Warning  NULL Quote: 2.00mg of C284065!

 Warning  NULL Quote: 1.00mg of C285035!

 Warning  NULL Quote: 1.00mg of C284989!

 Warning  NULL Quote: 1.00mg of C285724!

 Warning  NULL Quote: 1.00mg of C285307!

 Warning  NULL Quote: 1.00mg of C285311!

 Warning  NULL Quote: 1.00mg of C284658!

 Warning  NULL Quote: 1.00mg of C285800!

 Warning  NULL Quote: 1.00mg of C285801!

 Warning  NULL Quote: 1.00mg of C285435!

 Warning  NULL Quote: 1.00mg of C285436!

 Warning  NULL Quote: 2.00mg of C284412!

 Warning  NULL Quote: 1.00mg of C285643!

 Warning  NULL Quote: 1.00mg of C284805!

 Warning  NULL Quote: 1.00mg of C284806!

 Warning  NULL Quote: 1.00mg of C286005!

 Warning  NULL Quote: 1.00mg of C4746!

 Warning  NULL Quote: 1.00mg of C285445!

 Warning  NULL Quote: 1.00mg of C285494!

 Warning  NULL Quote: 1.00mg of C4759!

 Warning  NULL Quote: 1.00mg of C4765!

 Warning  NULL Quote: 1.00mg of C284738!

 Warning  NULL Quote: 1.00mg of C284883!

 Warning  NULL Quote: 1.00mg of C284884!

 Warning  NULL Quote: 2.00mg of C284934!

 Warning  NULL Quote: 1.00mg of C284935!

 Warning  NULL Quote: 1.00mg of C285645!

 Warning  NULL Quote: 1.00mg of C285218!

 Warning  NULL Quote: 1.00mg of C285219!

 Warning  NULL Quote: 1.00mg of C285957!

 Warning  NULL Quote: 1.00mg of C284237!

 Warning  NULL Quote: 1.00mg of C284238!

 Warning  NULL Quote: 1.00mg of C285634!

 Warning  NULL Quote: 2.00mg of C285843!

 Warning  NULL Quote: 1.00mg of C286012!

 Warning  NULL Quote: 1.00mg of C285844!

 Warning  NULL Quote: 1.00mg of C285622!

 Warning  NULL Quote: 1.00mg of C285623!

 Warning  NULL Quote: 2.00mg of C284409!

 Warning  NULL Quote: 1.00mg of C284752!

 Warning  NULL Quote: 2.00mg of C285414!

 Warning  NULL Quote: 1.00mg of C285828!

 Warning  NULL Quote: 1.00mg of C285415!

 Warning  NULL Quote: 1.00mg of C284311!

 Warning  NULL Quote: 1.00mg of C284922!

 Warning  NULL Quote: 1.00mg of C284923!

 Warning  NULL Quote: 1.00mg of C284966!

 Warning  NULL Quote: 1.00mg of C284967!

 Warning  NULL Quote: 1.00mg of C285254!

 Warning  NULL Quote: 2.00mg of C285255!

 Warning  NULL Quote: 1.00mg of C285449!

 Warning  NULL Quote: 4.00mg of C283795!

 Warning  NULL Quote: 1.00mg of C284878!

 Warning  NULL Quote: 1.00mg of C284879!

 Warning  NULL Quote: 2.00mg of C283893!

 Warning  NULL Quote: 1.00mg of C285123!

 Warning  NULL Quote: 1.00mg of C283156!

 Warning  NULL Quote: 1.00mg of C284681!

 Warning  NULL Quote: 2.00mg of C284812!

 Warning  NULL Quote: 1.00mg of C284813!

 Warning  NULL Quote: 1.00mg of C285144!

 Warning  NULL Quote: 1.00mg of C285145!

 Warning  NULL Quote: 1.00mg of C285789!

 Warning  NULL Quote: 1.00mg of C285509!

 Warning  NULL Quote: 1.00mg of C284616!

 Warning  NULL Quote: 1.00mg of C284617!

 Warning  NULL Quote: 1.00mg of C285791!

 Warning  NULL Quote: 1.00mg of C285792!

 Warning  NULL Quote: 1.00mg of C285576!

 Warning  NULL Quote: 1.00mg of C286098!

 Warning  NULL Quote: 1.00mg of C284454!

 Warning  NULL Quote: 2.00mg of C284015!

 Warning  NULL Quote: 1.00mg of C284225!

 Warning  NULL Quote: 1.00mg of C285213!

 Warning  NULL Quote: 3.00mg of C283875!

 Warning  NULL Quote: 1.00mg of C285234!

 Warning  NULL Quote: 1.00mg of C285495!

 Warning  NULL Quote: 1.00mg of C285497!

 Warning  NULL Quote: 1.00mg of C284013!

 Warning  NULL Quote: 3.00mg of C284014!

 Warning  NULL Quote: 1.00mg of C285522!

 Warning  NULL Quote: 1.00mg of C285523!

 Warning  NULL Quote: 1.00mg of C284573!

 Warning  NULL Quote: 1.00mg of C284898!

 Warning  NULL Quote: 1.00mg of C284899!

 Warning  NULL Quote: 1.00mg of C284501!

 Warning  NULL Quote: 1.00mg of C284502!

 Warning  NULL Quote: 1.00mg of C1877!

 Warning  NULL Quote: 1.00mg of C25769!

 Warning  NULL Quote: 1.00mg of C284794!

 Warning  NULL Quote: 2.00mg of C285161!

 Warning  NULL Quote: 1.00mg of C285628!

 Warning  NULL Quote: 1.00mg of C283948!

 Warning  NULL Quote: 1.00mg of C283949!

 Warning  NULL Quote: 1.00mg of C284189!

 Warning  NULL Quote: 2.00mg of C284026!

 Warning  NULL Quote: 1.00mg of C285816!

 Warning  NULL Quote: 1.00mg of C284824!

 Warning  NULL Quote: 1.00mg of C285498!

 Warning  NULL Quote: 1.00mg of C285499!

 Warning  NULL Quote: 1.00mg of C285274!

 Warning  NULL Quote: 1.00mg of C11912!

 Warning  NULL Quote: 1.00mg of C284849!

 Warning  NULL Quote: 1.00mg of C285413!

 Warning  NULL Quote: 1.00mg of C284987!

 Warning  NULL Quote: 1.00mg of C284988!

 Warning  NULL Quote: 1.00mg of C285874!

 Warning  NULL Quote: 1.00mg of C285875!

 Warning  NULL Quote: 2.00mg of C283038!

 Warning  NULL Quote: 1.00mg of C285546!

 Warning  NULL Quote: 1.00mg of C285547!

 Warning  NULL Quote: 1.00mg of C285998!

 Warning  NULL Quote: 1.00mg of C284488!

 Warning  NULL Quote: 2.00mg of C285984!

 Warning  NULL Quote: 6.00mg of C284114!

 Warning  NULL Quote: 1.00mg of C284476!

 Warning  NULL Quote: 1.00mg of C285985!

 Warning  NULL Quote: 1.00mg of C285995!

 Warning  NULL Quote: 1.00mg of C284500!

 Warning  NULL Quote: 1.00mg of C285481!

 Warning  NULL Quote: 1.00mg of C284508!

 Warning  NULL Quote: 1.00mg of C285532!

 Warning  NULL Quote: 1.00mg of C285533!

 Warning  NULL Quote: 1.00mg of C10288!

 Warning  NULL Quote: 1.00mg of C286017!

 Warning  NULL Quote: 1.00mg of C285185!

 Warning  NULL Quote: 1.00mg of C285186!

 Warning  NULL Quote: 1.00mg of C22714!

 Warning  NULL Quote: 1.00mg of C284587!

 Warning  NULL Quote: 1.00mg of C284856!

 Warning  NULL Quote: 1.00mg of C284857!

 Warning  NULL Quote: 1.00mg of C284466!

 Warning  NULL Quote: 1.00mg of C284467!

 Warning  NULL Quote: 1.00mg of C284515!

 Warning  NULL Quote: 1.00mg of C284516!

 Warning  NULL Quote: 3.00mg of C283790!

 Warning  NULL Quote: 1.00mg of C285229!

 Warning  NULL Quote: 1.00mg of C284818!

 Warning  NULL Quote: 1.00mg of C285244!

 Warning  NULL Quote: 1.00mg of C285245!

 Warning  NULL Quote: 1.00mg of C284990!

 Warning  NULL Quote: 1.00mg of C285836!

 Warning  NULL Quote: 1.00mg of C285837!

 Warning  NULL Quote: 1.00mg of C285617!

 Warning  NULL Quote: 1.00mg of C285974!

 Warning  NULL Quote: 1.00mg of C285384!

 Warning  NULL Quote: 1.00mg of C285163!

 Warning  NULL Quote: 1.00mg of C285164!

 Warning  NULL Quote: 1.00mg of C285127!

 Warning  NULL Quote: 1.00mg of C285128!

 Warning  NULL Quote: 1.00mg of C285044!

 Warning  NULL Quote: 1.00mg of C286122!

 Warning  NULL Quote: 1.00mg of C286123!

 Warning  NULL Quote: 1.00mg of C284513!

 Warning  NULL Quote: 1.00mg of C284514!

 Warning  NULL Quote: 1.00mg of C285070!

 Warning  NULL Quote: 1.00mg of C285332!

 Warning  NULL Quote: 1.00mg of C285333!

 Warning  NULL Quote: 1.00mg of C285748!

 Warning  NULL Quote: 5.00mg of C283078!

 Warning  NULL Quote: 1.00mg of C284991!

 Warning  NULL Quote: 1.00mg of C284992!

 Warning  NULL Quote: 1.00mg of C285657!

 Warning  NULL Quote: 1.00mg of C285658!

 Warning  NULL Quote: 2.00mg of C284142!

 Warning  NULL Quote: 1.00mg of C285997!

 Warning  NULL Quote: 1.00mg of C285387!

 Warning  NULL Quote: 1.00mg of C284973!

 Warning  NULL Quote: 1.00mg of C284974!

 Warning  NULL Quote: 1.00mg of C73235!

 Warning  NULL Quote: 2.00mg of C283007!

 Warning  NULL Quote: 1.00mg of C284880!

 Warning  NULL Quote: 1.00mg of C284881!

 Warning  NULL Quote: 1.00mg of C284223!

 Warning  NULL Quote: 1.00mg of C284224!

 Warning  NULL Quote: 1.00mg of C284215!

 Warning  NULL Quote: 1.00mg of C284216!

 Warning  NULL Quote: 1.00mg of C285357!

 Warning  NULL Quote: 1.00mg of C284236!

 Warning  NULL Quote: 1.00mg of C285620!

 Warning  NULL Quote: 1.00mg of C285621!

 Warning  NULL Quote: 2.00mg of C283904!

 Warning  NULL Quote: 1.00mg of C285935!

 Warning  NULL Quote: 1.00mg of C285741!

 Warning  NULL Quote: 2.00mg of C284212!

 Warning  NULL Quote: 1.00mg of C284968!

 Warning  NULL Quote: 1.00mg of C284774!

 Warning  NULL Quote: 1.00mg of C285983!

 Warning  NULL Quote: 1.00mg of C284975!

 Warning  NULL Quote: 1.00mg of C284976!

 Warning  NULL Quote: 1.00mg of C285768!

 Warning  NULL Quote: 1.00mg of C284538!

 Warning  NULL Quote: 1.00mg of C284539!

 Warning  NULL Quote: 1.00mg of C284841!

 Warning  NULL Quote: 1.00mg of C284682!

 Warning  NULL Quote: 1.00mg of C284683!

 Warning  NULL Quote: 1.00mg of C285960!

 Warning  NULL Quote: 1.00mg of C285961!

 Warning  NULL Quote: 1.00mg of C285328!

 Warning  NULL Quote: 1.00mg of C285329!

 Warning  NULL Quote: 1.00mg of C285124!

 Warning  NULL Quote: 1.00mg of C285125!

 Warning  NULL Quote: 1.00mg of C284069!

 Warning  NULL Quote: 1.00mg of C284070!

 Warning  NULL Quote: 1.00mg of C285171!

 Warning  NULL Quote: 1.00mg of C285172!

 Warning  NULL Quote: 1.00mg of C285180!

 Warning  NULL Quote: 1.00mg of C284222!

 Warning  NULL Quote: 1.00mg of C283925!

 Warning  NULL Quote: 1.00mg of C3543!

 Warning  NULL Quote: 1.00mg of C285126!

 Warning  NULL Quote: 1.00mg of C283961!

 Warning  NULL Quote: 1.00mg of C283962!

 Warning  NULL Quote: 1.00mg of C283084!

 Warning  NULL Quote: 1.00mg of C283085!

 Warning  NULL Quote: 1.00mg of C284517!

 Warning  NULL Quote: 1.00mg of C284518!

 Warning  NULL Quote: 1.00mg of C282937!

 Warning  NULL Quote: 1.00mg of C285374!

 Warning  NULL Quote: 1.00mg of C285162!

 Warning  NULL Quote: 2.00mg of C284030!

 Warning  NULL Quote: 1.00mg of C284031!

 Warning  NULL Quote: 1.00mg of C283834!

 Warning  NULL Quote: 1.00mg of C285187!

 Warning  NULL Quote: 1.00mg of C285188!

 Warning  NULL Quote: 1.00mg of C285759!

 Warning  NULL Quote: 1.00mg of C284552!

 Warning  NULL Quote: 1.00mg of C284553!

 Warning  NULL Quote: 1.00mg of C285797!

 Warning  NULL Quote: 1.00mg of C285798!

 Warning  NULL Quote: 1.00mg of C285392!

 Warning  NULL Quote: 1.00mg of C285393!

 Warning  NULL Quote: 1.00mg of C285227!

 Warning  NULL Quote: 1.00mg of C285228!

 Warning  NULL Quote: 1.00mg of C284260!

 Warning  NULL Quote: 1.00mg of C284453!

 Warning  NULL Quote: 1.00mg of C283905!

 Warning  NULL Quote: 1.00mg of C284340!

 Warning  NULL Quote: 1.00mg of C284341!

 Warning  NULL Quote: 1.00mg of C284449!

 Warning  NULL Quote: 4.00mg of C283027!

 Warning  NULL Quote: 1.00mg of C284358!

 Warning  NULL Quote: 1.00mg of C284143!

 Warning  NULL Quote: 1.00mg of C284082!

 Warning  NULL Quote: 1.00mg of C284190!

 Warning  NULL Quote: 1.00mg of C284385!

 Warning  NULL Quote: 1.00mg of C284169!

 Warning  NULL Quote: 1.00mg of C283836!

 Warning  NULL Quote: 1.00mg of C284213!

 Warning  NULL Quote: 1.00mg of C284214!

 Warning  NULL Quote: 1.00mg of C284424!

 Warning  NULL Quote: 1.00mg of C284425!

 Warning  NULL Quote: 3.00mg of C284043!

 Warning  NULL Quote: 1.00mg of C284258!

 Warning  NULL Quote: 2.00mg of C283788!

 Warning  NULL Quote: 1.00mg of C283789!

 Warning  NULL Quote: 1.00mg of C284384!

 Warning  NULL Quote: 1.00mg of C284191!

 Warning  NULL Quote: 2.00mg of C284058!

 Warning  NULL Quote: 1.00mg of C284364!

 Warning  NULL Quote: 2.00mg of C45790!

 Warning  NULL Quote: 1.00mg of C283075!

 Warning  NULL Quote: 1.00mg of C283733!

 Warning  NULL Quote: 5.00mg of C283053!

 Warning  NULL Quote: 1.00mg of C283908!

 Warning  NULL Quote: 1.00mg of C2607!

 Warning  NULL Quote: 1.00mg of C283034!

 Warning  NULL Quote: 1.00mg of C284349!

 Warning  NULL Quote: 1.00mg of C284229!

 Warning  NULL Quote: 1.00mg of C284350!

 Warning  NULL Quote: 1.00mg of C284351!

 Warning  NULL Quote: 1.00mg of C284104!

 Warning  NULL Quote: 1.00mg of C12703!

 Warning  NULL Quote: 1.00mg of C284207!

 Warning  NULL Quote: 1.00mg of C283868!

 Warning  NULL Quote: 2.00mg of C284048!

 Warning  NULL Quote: 1.00mg of C283955!

 Warning  NULL Quote: 1.00mg of C284422!

 Warning  NULL Quote: 1.00mg of C284423!

 Warning  NULL Quote: 2.00mg of C283811!

 Warning  NULL Quote: 1.00mg of C284062!

 Warning  NULL Quote: 1.00mg of C284064!

 Warning  NULL Quote: 2.00mg of C283039!

 Warning  NULL Quote: 1.00mg of C2619!

 Warning  NULL Quote: 1.00mg of C283903!

 Warning  NULL Quote: 1.00mg of C283916!

 Warning  NULL Quote: 1.00mg of C284242!

 Warning  NULL Quote: 2.00mg of C283049!

 Warning  NULL Quote: 1.00mg of C283050!

 Warning  NULL Quote: 1.00mg of C283909!

 Warning  NULL Quote: 1.00mg of C283870!

 Warning  NULL Quote: 1.00mg of C284192!

 Warning  NULL Quote: 1.00mg of C284193!

 Warning  NULL Quote: 1.00mg of C284280!

 Warning  NULL Quote: 1.00mg of C284281!

 Warning  NULL Quote: 1.00mg of C284294!

 Warning  NULL Quote: 1.00mg of C284295!

 Warning  NULL Quote: 1.00mg of C284132!

 Warning  NULL Quote: 1.00mg of C284252!

 Warning  NULL Quote: 2.00mg of C284203!

 Warning  NULL Quote: 1.00mg of C284204!

 Warning  NULL Quote: 2.00mg of C283956!

 Warning  NULL Quote: 1.00mg of C284292!

 Warning  NULL Quote: 1.00mg of C283869!

 Warning  NULL Quote: 1.00mg of C283957!

 Warning  NULL Quote: 2.00mg of C283772!

 Warning  NULL Quote: 2.00mg of C283898!

 Warning  NULL Quote: 1.00mg of C283052!

 Warning  NULL Quote: 1.00mg of C182088!

 Warning  NULL Quote: 3.00mg of C284184!

 Warning  NULL Quote: 1.00mg of C283040!

 Warning  NULL Quote: 1.00mg of C284247!

 Warning  NULL Quote: 1.00mg of C284248!

 Warning  NULL Quote: 1.00mg of C284004!

 Warning  NULL Quote: 1.00mg of C284005!

 Warning  NULL Quote: 1.00mg of C283797!

 Warning  NULL Quote: 1.00mg of C283798!

 Warning  NULL Quote: 1.00mg of C284052!

 Warning  NULL Quote: 1.00mg of C284323!

 Warning  NULL Quote: 1.00mg of C283749!

 Warning  NULL Quote: 3.00mg of C283750!

 Warning  NULL Quote: 1.00mg of C284101!

 Warning  NULL Quote: 1.00mg of C284102!

 Warning  NULL Quote: 1.00mg of C284164!

 Warning  NULL Quote: 1.00mg of C283864!

 Warning  NULL Quote: 1.00mg of C283865!

 Warning  NULL Quote: 1.00mg of C284402!

 Warning  NULL Quote: 1.00mg of C284200!

 Warning  NULL Quote: 1.00mg of C284201!

 Warning  NULL Quote: 2.00mg of C284205!

 Warning  NULL Quote: 1.00mg of C284436!

 Warning  NULL Quote: 1.00mg of C283731!

 Warning  NULL Quote: 1.00mg of C284210!

 Warning  NULL Quote: 1.00mg of C283877!

 Warning  NULL Quote: 1.00mg of C283878!

 Warning  NULL Quote: 1.00mg of C283958!

 Warning  NULL Quote: 1.00mg of C283963!

 Warning  NULL Quote: 1.00mg of C283031!

 Warning  NULL Quote: 1.00mg of C284106!

 Warning  NULL Quote: 1.00mg of C284107!

 Warning  NULL Quote: 1.00mg of C283008!

 Warning  NULL Quote: 1.00mg of C284121!

 Warning  NULL Quote: 1.00mg of C284122!

 Warning  NULL Quote: 1.00mg of C283934!

 Warning  NULL Quote: 1.00mg of C48159!

 Warning  NULL Quote: 1.00mg of C284253!

 Warning  NULL Quote: 1.00mg of C283741!

 Warning  NULL Quote: 1.00mg of C283742!

 Warning  NULL Quote: 1.00mg of C283744!

 Warning  NULL Quote: 1.00mg of C283943!

 Warning  NULL Quote: 1.00mg of C283821!

 Warning  NULL Quote: 1.00mg of C284282!

 Warning  NULL Quote: 1.00mg of C283997!

 Warning  NULL Quote: 1.00mg of C283959!

 Warning  NULL Quote: 2.00mg of C283960!

 Warning  NULL Quote: 1.00mg of C284359!

 Warning  NULL Quote: 1.00mg of C284373!

 Warning  NULL Quote: 1.00mg of C284374!

 Warning  NULL Quote: 1.00mg of C284007!

 Warning  NULL Quote: 1.00mg of C284428!

 Warning  NULL Quote: 1.00mg of C284429!

 Warning  NULL Quote: 1.00mg of C284352!

 Warning  NULL Quote: 1.00mg of C284353!

 Warning  NULL Quote: 1.00mg of C284296!

 Warning  NULL Quote: 1.00mg of C284297!

 Warning  NULL Quote: 1.00mg of C5719!

 Warning  NULL Quote: 1.00mg of C283913!

 Warning  NULL Quote: 1.00mg of C284008!

 Warning  NULL Quote: 1.00mg of C284009!

 Warning  NULL Quote: 1.00mg of C284087!

 Warning  NULL Quote: 1.00mg of C284089!

 Warning  NULL Quote: 6.00mg of C283025!

 Warning  NULL Quote: 1.00mg of C283910!

 Warning  NULL Quote: 1.00mg of C284356!

 Warning  NULL Quote: 1.00mg of C284357!

 Warning  NULL Quote: 3.00mg of C283866!

 Warning  NULL Quote: 1.00mg of C284032!

 Warning  NULL Quote: 1.00mg of C284049!

 Warning  NULL Quote: 2.00mg of C283047!

 Warning  NULL Quote: 1.00mg of C284367!

 Warning  NULL Quote: 2.00mg of C283771!

 Warning  NULL Quote: 1.00mg of C284445!

 Warning  NULL Quote: 1.00mg of C284446!

 Warning  NULL Quote: 1.00mg of C283952!

 Warning  NULL Quote: 1.00mg of C283953!

 Warning  NULL Quote: 1.00mg of C284197!

 Warning  NULL Quote: 1.00mg of C284198!

 Warning  NULL Quote: 1.00mg of C284293!

 Warning  NULL Quote: 2.00mg of C5512!

 Warning  NULL Quote: 1.00mg of C283838!

 Warning  NULL Quote: 1.00mg of C283794!

 Warning  NULL Quote: 1.00mg of C284187!

 Warning  NULL Quote: 1.00mg of C283010!

 Warning  NULL Quote: 1.00mg of C283011!

 Warning  NULL Quote: 1.00mg of C284053!

 Warning  NULL Quote: 1.00mg of C284328!

 Warning  NULL Quote: 1.00mg of C1830!

 Warning  NULL Quote: 1.00mg of C283839!

 Warning  NULL Quote: 1.00mg of C284398!

 Warning  NULL Quote: 1.00mg of C284254!

 Warning  NULL Quote: 1.00mg of C284202!

 Warning  NULL Quote: 1.00mg of C12679!

 Warning  NULL Quote: 1.00mg of C283872!

 Warning  NULL Quote: 2.00mg of C283080!

 Warning  NULL Quote: 1.00mg of C283775!

 Warning  NULL Quote: 2.00mg of C283926!

 Warning  NULL Quote: 1.00mg of C283927!

 Warning  NULL Quote: 4.00mg of C283774!

 Warning  NULL Quote: 1.00mg of C284322!

 Warning  NULL Quote: 1.00mg of C283900!

 Warning  NULL Quote: 1.00mg of C283773!

 Warning  NULL Quote: 1.00mg of C284194!

 Warning  NULL Quote: 1.00mg of C284338!

 Warning  NULL Quote: 1.00mg of C284339!

 Warning  NULL Quote: 1.00mg of C284146!

 Warning  NULL Quote: 1.00mg of C284155!

 Warning  NULL Quote: 1.00mg of C284001!

 Warning  NULL Quote: 1.00mg of C283933!

 Warning  NULL Quote: 1.00mg of C283015!

 Warning  NULL Quote: 1.00mg of C283016!

 Warning  NULL Quote: 1.00mg of C283076!

 Warning  NULL Quote: 1.00mg of C283059!

 Warning  NULL Quote: 2.00mg of C284226!

 Warning  NULL Quote: 2.00mg of C283071!

 Warning  NULL Quote: 2.00mg of C283919!

 Warning  NULL Quote: 1.00mg of C283920!

 Warning  NULL Quote: 1.00mg of C283745!

 Warning  NULL Quote: 1.00mg of C283746!

 Warning  NULL Quote: 1.00mg of C3760!

 Warning  NULL Quote: 1.00mg of C284404!

 Warning  NULL Quote: 1.00mg of C283048!

 Warning  NULL Quote: 2.00mg of C283947!

 Warning  NULL Quote: 1.00mg of C284330!

 Warning  NULL Quote: 1.00mg of C283069!

 Warning  NULL Quote: 1.00mg of C283070!

 Warning  NULL Quote: 1.00mg of C283822!

 Warning  NULL Quote: 1.00mg of C283823!

 Warning  NULL Quote: 1.00mg of C283029!

 Warning  NULL Quote: 1.00mg of C283030!

 Warning  NULL Quote: 1.00mg of C17441!

 Warning  NULL Quote: 2.00mg of C283740!

 Warning  NULL Quote: 1.00mg of C284166!

 Warning  NULL Quote: 1.00mg of C284167!

 Warning  NULL Quote: 1.00mg of C5336!

 Warning  NULL Quote: 1.00mg of C283033!

 Warning  NULL Quote: 1.00mg of C284186!

 Warning  NULL Quote: 1.00mg of C283986!

 Warning  NULL Quote: 1.00mg of C283987!

 Warning  NULL Quote: 2.00mg of C283992!

 Warning  NULL Quote: 1.00mg of C63!

 Warning  NULL Quote: 1.00mg of C284033!

 Warning  NULL Quote: 1.00mg of C284034!

 Warning  NULL Quote: 1.00mg of C283035!

 Warning  NULL Quote: 1.00mg of C283036!

 Warning  NULL Quote: 1.00mg of C286087!

 Warning  NULL Quote: 1.00mg of C286088!

 Warning  NULL Quote: 1.00mg of C283736!

 Warning  NULL Quote: 1.00mg of C283737!

 Warning  NULL Quote: 1.00mg of C70!

 Warning  NULL Quote: 1.00mg of C284450!

 Warning  NULL Quote: 1.00mg of C284066!

 Warning  NULL Quote: 1.00mg of C4675!

 Warning  NULL Quote: 1.00mg of C283061!

 Warning  NULL Quote: 4.00mg of C2611!

 Warning  NULL Quote: 1.00mg of C283897!

 Warning  NULL Quote: 1.00mg of C284123!

 Warning  NULL Quote: 1.00mg of C283989!

 Warning  NULL Quote: 1.00mg of C283023!

 Warning  NULL Quote: 1.00mg of C284183!

 Warning  NULL Quote: 1.00mg of C283072!

 Warning  NULL Quote: 1.00mg of C284208!

 Warning  NULL Quote: 1.00mg of C283780!

 Warning  NULL Quote: 1.00mg of C283781!

 Warning  NULL Quote: 1.00mg of C53833!

 Warning  NULL Quote: 1.00mg of C283024!

 Warning  NULL Quote: 1.00mg of C283942!

 Warning  NULL Quote: 1.00mg of C46662!

 Warning  NULL Quote: 1.00mg of C284317!

 Warning  NULL Quote: 1.00mg of C284318!

 Warning  NULL Quote: 1.00mg of C284360!

 Warning  NULL Quote: 1.00mg of C284361!

 Warning  NULL Quote: 1.00mg of C284108!

 Warning  NULL Quote: 2.00mg of C284109!

 Warning  NULL Quote: 1.00mg of C284241!

 Warning  NULL Quote: 1.00mg of C284125!

 Warning  NULL Quote: 1.00mg of C284249!

 Warning  NULL Quote: 1.00mg of C284250!

 Warning  NULL Quote: 1.00mg of C284050!

 Warning  NULL Quote: 1.00mg of C284051!

 Warning  NULL Quote: 1.00mg of C7948!

 Warning  NULL Quote: 1.00mg of C283028!

 Warning  NULL Quote: 1.00mg of C55278!

 Warning  NULL Quote: 2.00mg of C282920!

 Warning  NULL Quote: 1.00mg of C284378!

 Warning  NULL Quote: 1.00mg of C284443!

 Warning  NULL Quote: 1.00mg of C284444!

 Warning  NULL Quote: 1.00mg of C6296!

 Warning  NULL Quote: 1.00mg of C284147!

 Warning  NULL Quote: 1.00mg of C284044!

 Warning  NULL Quote: 1.00mg of C284022!

 Warning  NULL Quote: 1.00mg of C283843!

 Warning  NULL Quote: 1.00mg of C283844!

 Warning  NULL Quote: 1.00mg of C284227!

 Warning  NULL Quote: 1.00mg of C284228!

 Warning  NULL Quote: 1.00mg of C283019!

 Warning  NULL Quote: 1.00mg of C283020!

 Warning  NULL Quote: 1.00mg of C284279!

 Warning  NULL Quote: 2.00mg of C284047!

 Warning  NULL Quote: 1.00mg of C284074!

 Warning  NULL Quote: 1.00mg of C283918!

 Warning  NULL Quote: 1.00mg of C284221!

 Warning  NULL Quote: 1.00mg of C283923!

 Warning  NULL Quote: 1.00mg of C283079!

 Warning  NULL Quote: 1.00mg of C284055!

 Warning  NULL Quote: 1.00mg of C283813!

 Warning  NULL Quote: 1.00mg of C284037!

 Warning  NULL Quote: 1.00mg of C284038!

 Warning  NULL Quote: 1.00mg of C283842!

 Warning  NULL Quote: 2.00mg of C1796!

 Warning  NULL Quote: 1.00mg of C283891!

 Warning  NULL Quote: 1.00mg of C284010!

 Warning  NULL Quote: 1.00mg of C284334!

 Warning  NULL Quote: 1.00mg of C284335!

 Warning  NULL Quote: 1.00mg of C284369!

 Warning  NULL Quote: 1.00mg of C284370!

 Warning  NULL Quote: 1.00mg of C284149!

 Warning  NULL Quote: 1.00mg of C284150!

 Warning  NULL Quote: 1.00mg of C283944!

 Warning  NULL Quote: 1.00mg of C283945!

 Warning  NULL Quote: 1.00mg of C283895!

 Warning  NULL Quote: 1.00mg of C283081!

 Warning  NULL Quote: 1.00mg of C284113!

 Warning  NULL Quote: 1.00mg of C6752!

 Warning  NULL Quote: 1.00mg of C284110!

 Warning  NULL Quote: 1.00mg of C284111!

 Warning  NULL Quote: 1.00mg of C283911!

 Warning  NULL Quote: 1.00mg of C283912!

 Warning  NULL Quote: 1.00mg of C284283!

 Warning  NULL Quote: 1.00mg of C284284!

 Warning  NULL Quote: 1.00mg of C284086!

 Warning  NULL Quote: 1.00mg of C284408!

 Warning  NULL Quote: 1.00mg of C283165!

 Warning  NULL Quote: 1.00mg of C283831!

 Warning  NULL Quote: 1.00mg of C283976!

 Warning  NULL Quote: 1.00mg of C283977!

 Warning  NULL Quote: 1.00mg of C284023!

 Warning  NULL Quote: 1.00mg of C283915!

 Warning  NULL Quote: 1.00mg of C284099!

 Warning  NULL Quote: 1.00mg of C284100!

 Warning  NULL Quote: 1.00mg of C283738!

 Warning  NULL Quote: 1.00mg of C283739!

 Warning  NULL Quote: 1.00mg of C283747!

 Warning  NULL Quote: 1.00mg of C283748!

 Warning  NULL Quote: 1.00mg of C284181!

 Warning  NULL Quote: 1.00mg of C284182!

 Warning  NULL Quote: 1.00mg of C283969!

 Warning  NULL Quote: 1.00mg of C283062!

 Warning  NULL Quote: 1.00mg of C284399!

 Warning  NULL Quote: 1.00mg of C284400!

 Warning  NULL Quote: 1.00mg of C283946!

 Warning  NULL Quote: 3.00mg of C283017!

 Warning  NULL Quote: 1.00mg of C284320!

 Warning  NULL Quote: 1.00mg of C284321!

 Warning  NULL Quote: 1.00mg of C283873!

 Warning  NULL Quote: 1.00mg of C283874!

 Warning  NULL Quote: 2.00mg of C284091!

 Warning  NULL Quote: 1.00mg of C284329!

 Warning  NULL Quote: 1.00mg of C283892!

 Warning  NULL Quote: 1.00mg of C284405!

 Warning  NULL Quote: 1.00mg of C284406!

 Warning  NULL Quote: 1.00mg of C284131!

 Warning  NULL Quote: 1.00mg of C284426!

 Warning  NULL Quote: 1.00mg of C283778!

 Warning  NULL Quote: 1.00mg of C283779!

 Warning  NULL Quote: 1.00mg of C284285!

 Warning  NULL Quote: 1.00mg of C284266!

 Warning  NULL Quote: 1.00mg of C284267!

 Warning  NULL Quote: 1.00mg of C284135!

 Warning  NULL Quote: 1.00mg of C284185!

 Warning  NULL Quote: 1.00mg of C284326!

 Warning  NULL Quote: 1.00mg of C284327!

 Warning  NULL Quote: 1.00mg of C283889!

 Warning  NULL Quote: 1.00mg of C283890!

 Warning  NULL Quote: 1.00mg of C284255!

 Warning  NULL Quote: 1.00mg of C284256!

 Warning  NULL Quote: 1.00mg of C283854!

 Warning  NULL Quote: 2.00mg of C3451!

 Warning  NULL Quote: 1.00mg of C284019!

 Warning  NULL Quote: 1.00mg of C284397!

 Warning  NULL Quote: 1.00mg of C284303!

 Warning  NULL Quote: 1.00mg of C284300!

 Warning  NULL Quote: 1.00mg of C284298!

 Warning  NULL Quote: 1.00mg of C284299!

 Warning  NULL Quote: 1.00mg of C284403!

 Warning  NULL Quote: 1.00mg of C284017!

 Warning  NULL Quote: 2.00mg of C284018!

 Warning  NULL Quote: 1.00mg of C283054!

 Warning  NULL Quote: 1.00mg of C283791!

 Warning  NULL Quote: 1.00mg of C9152!

 Warning  NULL Quote: 1.00mg of C284148!

 Warning  NULL Quote: 1.00mg of C284447!

 Warning  NULL Quote: 1.00mg of C284448!

 Warning  NULL Quote: 1.00mg of C284137!

 Warning  NULL Quote: 1.00mg of C77571!

 Warning  NULL Quote: 1.00mg of C283899!

 Warning  NULL Quote: 1.00mg of C283829!

 Warning  NULL Quote: 2.00mg of C283830!

 Warning  NULL Quote: 1.00mg of C283833!

 Warning  NULL Quote: 1.00mg of C284156!

 Warning  NULL Quote: 1.00mg of C284245!

 Warning  NULL Quote: 1.00mg of C284246!

 Warning  NULL Quote: 1.00mg of C283792!

 Warning  NULL Quote: 1.00mg of C283793!

 Warning  NULL Quote: 1.00mg of C285358!

 Warning  NULL Quote: 1.00mg of C285359!

 Warning  NULL Quote: 1.00mg of C284375!

 Warning  NULL Quote: 1.00mg of C284211!

 Warning  NULL Quote: 1.00mg of C284927!

 Warning  NULL Quote: 1.00mg of C284928!

 Warning  NULL Quote: 1.00mg of C285679!

 Warning  NULL Quote: 1.00mg of C285680!

 Warning  NULL Quote: 1.00mg of C285285!

 Warning  NULL Quote: 1.00mg of C285286!

 Warning  NULL Quote: 1.00mg of C285663!

 Warning  NULL Quote: 1.00mg of C285664!

 Warning  NULL Quote: 1.00mg of C285251!

 Warning  NULL Quote: 1.00mg of C285252!

 Warning  NULL Quote: 1.00mg of C285365!

 Warning  NULL Quote: 1.00mg of C285366!

 Warning  NULL Quote: 1.00mg of C285304!

 Warning  NULL Quote: 1.00mg of C286060!

 Warning  NULL Quote: 2.00mg of C284886!

 Warning  NULL Quote: 1.00mg of C284926!

 Warning  NULL Quote: 1.00mg of C284887!

 Warning  NULL Quote: 1.00mg of C8567!

 Warning  NULL Quote: 1.00mg of C285350!

 Warning  NULL Quote: 1.00mg of C284764!

 Warning  NULL Quote: 1.00mg of C284765!

 Warning  NULL Quote: 1.00mg of C285319!

 Warning  NULL Quote: 1.00mg of C285320!

 Warning  NULL Quote: 1.00mg of C284560!

 Warning  NULL Quote: 1.00mg of C284561!

 Warning  NULL Quote: 1.00mg of C284797!

 Warning  NULL Quote: 1.00mg of C284407!

 Warning  NULL Quote: 1.00mg of C284839!

 Warning  NULL Quote: 1.00mg of C284840!

 Warning  NULL Quote: 1.00mg of C286099!

 Warning  NULL Quote: 1.00mg of C286100!

 Warning  NULL Quote: 1.00mg of C284936!

 Warning  NULL Quote: 1.00mg of C285689!

 Warning  NULL Quote: 1.00mg of C285758!

 Warning  NULL Quote: 1.00mg of C284659!

 Warning  NULL Quote: 1.00mg of C284660!

 Warning  NULL Quote: 1.00mg of C284829!

 Warning  NULL Quote: 1.00mg of C284830!

 Warning  NULL Quote: 2.00mg of C283847!

 Warning  NULL Quote: 1.00mg of C284690!

 Warning  NULL Quote: 1.00mg of C285814!

 Warning  NULL Quote: 1.00mg of C285815!

 Warning  NULL Quote: 1.00mg of C285817!

 Warning  NULL Quote: 1.00mg of C285818!

 Warning  NULL Quote: 1.00mg of C284854!

 Warning  NULL Quote: 1.00mg of C284855!

 Warning  NULL Quote: 1.00mg of C285862!

 Warning  NULL Quote: 1.00mg of C285863!

 Warning  NULL Quote: 1.00mg of C284925!

 Warning  NULL Quote: 1.00mg of C284766!

 Warning  NULL Quote: 1.00mg of C284767!

 Warning  NULL Quote: 1.00mg of C284179!

 Warning  NULL Quote: 1.00mg of C284180!

 Warning  NULL Quote: 1.00mg of C283824!

 Warning  NULL Quote: 1.00mg of C283825!

 Warning  NULL Quote: 1.00mg of C283045!

 Warning  NULL Quote: 1.00mg of C283046!

 Warning  NULL Quote: 1.00mg of C283879!

 Warning  NULL Quote: 1.00mg of C284365!

 Warning  NULL Quote: 1.00mg of C284366!

 Warning  NULL Quote: 1.00mg of C283950!

 Warning  NULL Quote: 1.00mg of C283951!

 Warning  NULL Quote: 1.00mg of C283816!

 Warning  NULL Quote: 1.00mg of C283819!

 Warning  NULL Quote: 1.00mg of C1493!

 Warning  NULL Quote: 1.00mg of C284199!

 Warning  NULL Quote: 2.00mg of C282907!

 Warning  NULL Quote: 1.00mg of C283006!

 Warning  NULL Quote: 1.00mg of C284336!

 Warning  NULL Quote: 1.00mg of C284337!

 Warning  NULL Quote: 1.00mg of C284217!

 Warning  NULL Quote: 1.00mg of C12667!

 Warning  NULL Quote: 2.00mg of C284059!

 Warning  NULL Quote: 1.00mg of C283922!

 Warning  NULL Quote: 1.00mg of C102928!

 Warning  NULL Quote: 1.00mg of C284427!

 Warning  NULL Quote: 1.00mg of C284002!

 Warning  NULL Quote: 1.00mg of C284003!

 Warning  NULL Quote: 1.00mg of C283988!

 Warning  NULL Quote: 1.00mg of C284376!

 Warning  NULL Quote: 1.00mg of C284025!

 Warning  NULL Quote: 1.00mg of C283055!

 Warning  NULL Quote: 1.00mg of C283056!

 Warning  NULL Quote: 1.00mg of C284419!

 Warning  NULL Quote: 1.00mg of C284420!

 Warning  NULL Quote: 1.00mg of C284441!

 Warning  NULL Quote: 1.00mg of C284442!

 Warning  NULL Quote: 1.00mg of C283037!

 Warning  NULL Quote: 1.00mg of C284319!

 Warning  NULL Quote: 1.00mg of C283826!

 Warning  NULL Quote: 1.00mg of C283827!

 Warning  NULL Quote: 1.00mg of C283018!

 Warning  NULL Quote: 1.00mg of C284332!

 Warning  NULL Quote: 1.00mg of C284333!

 Warning  NULL Quote: 1.00mg of C283964!

 Warning  NULL Quote: 1.00mg of C283966!

 Warning  NULL Quote: 1.00mg of C283967!

 Warning  NULL Quote: 1.00mg of C284028!

 Warning  NULL Quote: 1.00mg of C284029!

 Warning  NULL Quote: 1.00mg of C283876!

 Warning  NULL Quote: 1.00mg of C284090!

 Warning  NULL Quote: 1.00mg of C284057!

 Warning  NULL Quote: 1.00mg of C284060!

 Warning  NULL Quote: 1.00mg of C284061!

 Warning  NULL Quote: 1.00mg of C284067!

 Warning  NULL Quote: 1.00mg of C284068!

 Warning  NULL Quote: 1.00mg of C12081!

 Warning  NULL Quote: 1.00mg of C284386!

 Warning  NULL Quote: 1.00mg of C284387!

 Warning  NULL Quote: 1.00mg of C284389!

 Warning  NULL Quote: 1.00mg of C284759!

 Warning  NULL Quote: 1.00mg of C284724!

 Warning  NULL Quote: 1.00mg of C284486!

 Warning  NULL Quote: 1.00mg of C284487!

 Warning  NULL Quote: 1.00mg of C283021!

 Warning  NULL Quote: 1.00mg of C283022!

 Warning  NULL Quote: 1.00mg of C283901!

 Warning  NULL Quote: 1.00mg of C283902!

 Warning  NULL Quote: 1.00mg of C283894!

 Warning  NULL Quote: 1.00mg of C284574!

 Warning  NULL Quote: 1.00mg of C284598!

 Warning  NULL Quote: 1.00mg of C284599!

 Warning  NULL Quote: 1.00mg of C284676!

 Warning  NULL Quote: 1.00mg of C284677!

 Warning  NULL Quote: 1.00mg of C284604!

 Warning  NULL Quote: 1.00mg of C284605!

 Warning  NULL Quote: 1.00mg of C282966!

 Warning  NULL Quote: 1.00mg of C282908!

 Warning  NULL Quote: 1.00mg of C283094!

 Warning  NULL Quote: 1.00mg of C283095!

 Warning  NULL Quote: 1.00mg of C283096!

 Warning  NULL Quote: 1.00mg of C283097!

 Warning  NULL Quote: 1.00mg of C282909!

 Warning  NULL Quote: 1.00mg of C282910!

 Warning  NULL Quote: 1.00mg of C282993!

 Warning  NULL Quote: 1.00mg of C282994!

 Warning  NULL Quote: 1.00mg of C282991!

 Warning  NULL Quote: 1.00mg of C282992!

 Warning  NULL Quote: 1.00mg of C282985!

 Warning  NULL Quote: 1.00mg of C282986!

 Warning  NULL Quote: 3.00mg of C202220!

 Warning  NULL Quote: 1.00mg of C282973!

 Warning  NULL Quote: 1.00mg of C282989!

 Warning  NULL Quote: 1.00mg of C282967!

 Warning  NULL Quote: 1.00mg of C282968!

 Warning  NULL Quote: 1.00mg of C283196!

 Warning  NULL Quote: 1.00mg of C283197!

 Warning  NULL Quote: 1.00mg of C282982!

 Warning  NULL Quote: 1.00mg of C282990!

 Warning  NULL Quote: 1.00mg of C282940!

 Warning  NULL Quote: 1.00mg of C282941!

 Warning  NULL Quote: 1.00mg of C282942!

 Warning  NULL Quote: 3.00mg of C282944!

 Warning  NULL Quote: 1.00mg of C282945!

 Warning  NULL Quote: 3.00mg of C282946!

 Warning  NULL Quote: 1.00mg of C282949!

 Warning  NULL Quote: 3.00mg of C282952!

 Warning  NULL Quote: 1.00mg of C282950!

 Warning  NULL Quote: 1.00mg of C282951!

 Warning  NULL Quote: 1.00mg of C282953!

 Warning  NULL Quote: 1.00mg of C282947!

 Warning  NULL Quote: 1.00mg of C282948!

 Warning  NULL Quote: 1.00mg of C282955!

 Warning  NULL Quote: 1.00mg of C197048!

 Warning  NULL Quote: 1.00mg of C282954!

 Warning  NULL Quote: 1.00mg of C282969!

 Warning  NULL Quote: 1.00mg of C282970!

 Warning  NULL Quote: 1.00mg of C282926!

 Warning  NULL Quote: 1.00mg of C282927!

 Warning  NULL Quote: 1.00mg of C282928!

 Warning  NULL Quote: 1.00mg of C282929!

 Warning  NULL Quote: 1.00mg of C282956!

 Warning  NULL Quote: 1.00mg of C282957!

 Warning  NULL Quote: 1.00mg of C282972!

 Warning  NULL Quote: 1.00mg of C282965!

 Warning  NULL Quote: 1.00mg of C282964!

 Warning  NULL Quote: 1.00mg of C283198!

 Warning  NULL Quote: 1.00mg of C283199!

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/syndirella/retrosynthesis/openbind_a71ev2a_c1_scaffo
lds.json...

In [14]:
recipe.write_CAR_csv("cycle_01/syndirella/retrosynthesis/openbind_a71ev2a_c1_scaffolds.csv")

DEBUG: Querying database for routes

DEBUG: Assembling route dictionary

DEBUG: Checking availability

Output()

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/syndirella/retrosynthesis/openbind_a71ev2a_c1_scaffo
lds_1steps.csv...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/syndirella/retrosynthesis/openbind_a71ev2a_c1_scaffo
lds.csv...

,target-names,no-steps,concentration-required-mM,amount-required-uL,batch-tag,reactant-1-1,reactant-2-1,reaction-product-smiles-1,reaction-name-1,reaction-recipe-1,reaction-groupby-column-1
0,C139485,1,None,None,None,O=C(O)Cc1cocn1,Nc1ccc2c(c1)C(F)CC2,O=C(Cc1cocn1)Nc1ccc2c(c1)C(F)CC2,Amidation,None,None
1,C140978,1,None,None,None,NCc1c[nH]nc1Br,COc1ccc(C(C)=O)cc1B1OC(C)(C)C(C)(C)O1,COc1ccc(C(C)=O)cc1-c1n[nH]cc1CN,Sp2-sp2_Suzuki_coupling,None,None
2,C140988,1,None,None,None,Cc1[nH]nc(B2OC(C)(C)C(C)(C)O2)c1CO,CNNc1ccccc1Br,CNNc1ccccc1-c1n[nH]c(C)c1CO,Sp2-sp2_Suzuki_coupling,None,None
3,C141599,1,None,None,None,COC(=O)c1cc(C)ncc1Br,CNN,COC(=O)c1cc(C)ncc1N(C)N,N-nucleophilic_aromatic_substitution,None,None
4,C15,1,None,None,None,Nc1cnccc1C(=O)O,CO,COC(=O)c1ccncc1N,Steglich_esterification,None,None
...,...,...,...,...,...,...,...,...,...,...,...
1055,C8502,1,None,None,None,O=C1Cc2c(C(=O)N3CCCC(O)C3)ccnc2N1,COC(C)CN,COC(C)CNC1CCCN(C(=O)c2ccnc3c2CC(=O)N3)C1,Mitsunobu_reaction_with_amine_alcohol_and_thio...,None,None
1056,C16768,1,None,None,None,CNCC1CCN(C(=O)CCCF)C1,CC(C)(C(=O)O)c1ccns1,CN(CC1CCN(C(=O)CCCF)C1)C(=O)C(C)(C)c1ccns1,Amidation,None,None
1057,C8155,1,None,None,None,O=S(=O)(NCC=CBr)N1CCCCC1,CC=CB1OC(C)(C)C(C)(C)O1,CC=CC=CCNS(=O)(=O)N1CCCCC1,Sp2-sp2_Suzuki_coupling,None,None
1058,C3665,1,None,None,None,CC1(C)OB(c2ccncc2)OC1(C)C,Ic1ncco1,c1cc(-c2ncco2)ccn1,Sp2-sp2_Suzuki_coupling,None,None
1059,C8142,1,None,None,None,CC(=O)CC(O)C1CCCN(C(=O)OC(C)(C)C)C1,<NA>,CC(=O)CC(O)C1CCCNC1,N-Boc_deprotection,None,None