# OpenBind-HIPPO

- **Target: A71EV2A**
- **Cycle: 01**

## Prep

- [ ] Generate, place, and export merges

## Imports

In [39]:
%load_ext autoreload
%autoreload 2
import hippo
import mrich
from mrich import print
from pathlib import Path
from os import environ
import shutil
import molparse as mp
import pandas as pd
import re
from mocassin.mocassin import calculate_mocassin_tversky

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

# Config

In [3]:
target_name = "A71EV2A"
target_dir = Path(environ["BULK"]) / "TARGETS" / target_name
cycle_name = "cycle_01"
cycle_dir = Path(cycle_name)
aligned_dir = target_dir / "aligned_files"

## Animal

In [5]:
animal = hippo.HIPPO(target_name, target_dir / f"{target_name}.sqlite")

 Creating HIPPO animal

name = A71EV2A

db_path = /opt/xchem-fragalysis-2/maxwin/BulkDock/TARGETS/A71EV2A/A71EV2A.sqlite

DEBUG: hippo.Database.__init__()

DEBUG: Database.path = /opt/xchem-fragalysis-2/maxwin/BulkDock/TARGETS/A71EV2A/A71EV2A.sqlite

DEBUG: hippo.Database.connect()

DEBUG: sqlite3.version='2.6.0'

 Success  Database connected @ /opt/xchem-fragalysis-2/maxwin/BulkDock/TARGETS/A71EV2A/A71EV2A.sqlite!

Output()

SQLite Database was locked, retrying...

 Success  Initialised animal HIPPO("A71EV2A")!

# Annotate Pockets (subsites)

Assign subsites from Canonical site definitions in metadata (for all experimental hits)

In [7]:
hits = animal.poses(tag="hits")
hits.set_subsites_from_metadata_field()

Assign subsites of derivatives based on inspiration subsites

In [6]:
animal.db.set_derivative_subsites()

Print a summary

In [9]:
hits.derivatives.subsite_summary()

┏━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━┓
┃ subsite            ┃ num_poses ┃
┡━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━┩
│ 1 - Active Site    │ 468573    │
│ 3 - A0541/A/147/1  │ 45665     │
│ 5 - A3181/A/202/1  │ 44195     │
│ 2 - A3977/A/202/1  │ 34805     │
│ 6 - A0486/A/147/1  │ 34135     │
│ 4 - A0525/A/246/1  │ 14904     │
│ 15 - A1068/A/246/1 │ 8928      │
│ 17 - A1081/A/201/1 │ 5281      │
│ 10 - A0900/A/147/1 │ 18        │
│ 9 - A0432/A/147/1  │ 10        │
│ 14 - A0554/A/147/1 │ 8         │
│ 13 - A0412/A/147/1 │ 5         │
│ 16 - A1068/A/302/1 │ 5         │
│ 8 - A0517/A/147/1  │ 5         │
│ 7 - A0488/A/147/1  │ 3         │
└────────────────────┴───────────┘

# Tag Scaffolds

Tag your scaffolds, e.g. by their BulkDock export:

In [10]:
scaffold_poses = (
    animal.poses.get_by_metadata_substring_match("openbind_a71ev2a_c1_fragmenstein_165VU4J.sdf") + 
    animal.poses.get_by_metadata_substring_match("openbind_a71ev2a_c1_knitwork_pure_165VWF8.sdf") + 
    animal.poses.get_by_metadata_substring_match("openbind_a71ev2a_c1_knitwork_impure_165VXJF.sdf")
)

scaffold_poses.add_tag("openbind_a71ev2a_c1_scaffolds")

Tagged {P × 1518} w/ "openbind_a71ev2a_c1_scaffolds"

In [11]:
scaffold_poses.subsite_summary()

┏━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━┓
┃ subsite            ┃ num_poses ┃
┡━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━┩
│ 1 - Active Site    │ 1431      │
│ 6 - A0486/A/147/1  │ 79        │
│ 5 - A3181/A/202/1  │ 73        │
│ 3 - A0541/A/147/1  │ 62        │
│ 2 - A3977/A/202/1  │ 44        │
│ 17 - A1081/A/201/1 │ 30        │
│ 4 - A0525/A/246/1  │ 16        │
└────────────────────┴───────────┘

# Prepare for Syndirella inputs

In [20]:
scaffold_poses.to_syndirella("cycle_01/syndirella/openbind_a71ev2a_c1_scaffolds")

 DISK  Writing cycle_01/syndirella/templates...

out_key = openbind_a71ev2a_c1_scaffolds

#poses = 1518

Output()

 DISK  Writing cycle_01/syndirella/templates/A5666a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/A0207a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/A0922a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/A2290a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/A3191a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/A3305a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/A3483a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/A3685a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/A3849a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/A3992b_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/A4202b_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/A4315a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/A4344a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/A4214a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/A4415a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/A4456b_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/A4526a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/A4580b_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/A4673a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/A4721a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/A4791a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/A4840a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/A4883a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/A4963a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/A4954a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/A5081b_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/A5213a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/A5288a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/A5424b_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/A5544a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/A1180a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/A3890a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/A1146a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/A5079b_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/A1140a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/A0528b_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/A4586a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/A0309a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/A0514b_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/A0239a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/A0556a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/A1293a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/A2629a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/A3897a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/A0541a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/A1779a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/A3623a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/A0428a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/A4445a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/A4311a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/A3436a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/A4461a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/A4333a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/A1776a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/A5036a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/A3977b_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/A3706b_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/A0469a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/A4029a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/A1445a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/A5079a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/A4746a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/A1778a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/A3564a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/A1145a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/A3181b_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/A0473a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/A0341a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/A5427a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/A4386a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/A4031a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/A4742a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/A0586a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/A4351a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/A5036b_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/A0875a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/A4806a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/A4012a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/A0525a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/templates/A3392a_apo-desolv.pdb...

 DISK  Writing cycle_01/syndirella/openbind_a71ev2a_c1_scaffolds_syndirella_input.csv...

╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ in <module>:1                                                                                    │
│                                                                                                  │
│ ❱ 1 scaffold_poses.to_syndirella("cycle_01/syndirella/openbind_a71ev2a_c1_scaffolds")            │
│   2                                                                                              │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │    aligned_dir = PosixPath('/opt/xchem-fragalysis-2/maxwin/BulkDock/TARGETS/A71EV2A/aligned… │ │
│ │         animal = HIPPO("A71EV2A")                                                            │ │
│ │      cycle_dir = PosixPath('cycle_01')                                                       │ │
│ │     cycle_name = 'cycle_01'                                                                  │ │
│ │        environ = environ({                                                                   │ │
│ │                  │   'HYDRA_LAUNCHER_EXTRA_ARGS': '--external-launcher',                     │ │
│ │                  │   'PRECURSOR': '/opt/xchem-fragalysis-2/maxwin/2A_Precursor_FFF',         │ │
│ │                  │   'MAMBA_ALWAYS_YES': 'yes',                                              │ │
│ │                  │   'CONDA_SHLVL': '1',                                                     │ │
│ │                  │   'LD_LIBRARY_PATH':                                                      │ │
│ │                  '/usr/local/cuda/compat:/opt/xchem-fragalysis-2/maxwin/conda/lib:/dls_sw/e… │ │
│ │                  │   'LS_COLORS':                                                            │ │
│ │                  'rs=0:di=38;5;33:ln=38;5;51:mh=00:pi=40;38;5;11:so=38;5;13:do=38;5;5:bd=48… │ │
│ │                  │   'CONDA_EXE': '/opt/xchem-fragalysis-2/maxwin/conda/bin/conda',          │ │
│ │                  │   'SLURM_NODEID': '0',                                                    │ │
│ │                  │   'SLURM_TASK_PID': '10034',                                              │ │
│ │                  │   'SSH_CONNECTION': '172.23.162.11 47758 172.23.176.6 22',                │ │
│ │                  │   ... +132                                                                │ │
│ │                  })                                                                          │ │
│ │           exit = <IPython.core.autocall.ZMQExitAutocall object at 0x7f4ce0a04ce0>            │ │
│ │    get_ipython = <bound method InteractiveShell.get_ipython of                               │ │
│ │                  <ipykernel.zmqshell.ZMQInteractiveShell object at 0x7f4cbfdd94f0>>          │ │
│ │          hippo = <module 'hippo' from                                                        │ │
│ │                  '/opt/xchem-fragalysis-2/maxwin/conda/envs/py312/lib/python3.12/site-packa… │ │
│ │           hits = poses tagged "hits": {P × 645}                                              │ │
│ │             In = [                                                                           │ │
│ │                  │   '',                                                                     │ │
│ │                  │   'animal.db.set_derivative_subsites()',                                  │ │
│ │                  │   'animal = hippo.HIPPO(target_name, target_dir /                         │ │
│ │                  f"{target_name}.sqlite")',                                                  │ │
│ │                  │   "get_ipython().run_line_magic('load_ext',                               │ │
│ │                  'autoreload')\nget_ipython().run_line_ma"+156,                              │ │
│ │                  │   'target_name = "A71EV2A"\ntarget_dir = Path(environ["BULK"]) /          │ │
│ │                  "TARGETS" / target_'+100,                                                   │ │
│ │                  │   'animal = hippo.HIPPO(target_name, target_dir /                         │ │
│ │                  f"{target_name}.sqlite")',                                                  │ │
│ │                  │   'animal.db.set_derivative_subsites()',                                  │ │
│ │                  │   'hits =                                                                 │ │
│ │                  animal.poses(tag="hits")\nhits.set_subsites_from_metadata_field()',         │ │
│ │                  │   'hits.derivatives',                                                     │ │
│ │                  │   'hits.derivatives.subsite_summary()',                                   │ │
│ │                  │   ... +11                                                                 │ │
│ │                  ]                                                                           │ │
│ │             mp = <module 'molparse' from                                                     │ │
│ │                  '/opt/xchem-fragalysis-2/maxwin/conda/envs/py312/lib/python3.12/site-packa… │ │
│ │          mrich = <module 'mrich' from                                                        │ │
│ │                  '/opt/xchem-fragalysis-2/maxwin/conda/envs/py312/lib/python3.12/site-packa… │ │
│ │            Out = {                                                                           │ │
│ │                  │   8: derivatives of poses tagged "hits": {P × 645}: {P × 495627},         │ │
│ │                  │   13: '02'                                                                │ │
│ │                  }                                                                           │ │
│ │           quit = <IPython.core.autocall.ZMQExitAutocall object at 0x7f4ce0a04ce0>            │ │
│ │ scaffold_poses = {P × 1518}                                                                  │ │
│ │         shutil = <module 'shutil' from                                                       │ │
│ │                  '/opt/xchem-fragalysis-2/maxwin/conda/envs/py312/lib/python3.12/shutil.py'> │ │
│ │     target_dir = PosixPath('/opt/xchem-fragalysis-2/maxwin/BulkDock/TARGETS/A71EV2A')        │ │
│ │    target_name = 'A71EV2A'                                                                   │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                                  │
│ /opt/xchem-fragalysis-2/maxwin/conda/envs/py312/lib/python3.12/site-packages/hippo/pset.py:2305  │
│ in to_syndirella                                                                                 │
│                                                                                                  │
│   2302 │   │   inspirations = PoseSet(self.db, pset_inspirations)                                │
│   2303 │   │                                                                                     │
│   2304 │   │   sdf_name = out_dir / f"{out_key}_syndirella_inspiration_hits.sdf"                 │
│ ❱ 2305 │   │   inspirations.write_sdf(                                                           │
│   2306 │   │   │   sdf_name,                                                                     │
│   2307 │   │   │   inspirations=False,                                                           │
│   2308 │   │   │   tags=False,                                                                   │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │              comp = C8142 "UZXQDRCHBFTVHG-UHFFFAOYSA-N"                                      │ │
│ │          csv_name = PosixPath('cycle_01/syndirella/openbind_a71ev2a_c1_scaffolds_syndirella… │ │
│ │                 d = {                                                                        │ │
│ │                     │   'smiles': 'CC(=O)CC(O)C1CCCNC1',                                     │ │
│ │                     │   'template': 'A3897a',                                                │ │
│ │                     │   'compound_set': 'openbind_a71ev2a_c1_scaffolds',                     │ │
│ │                     │   'hit1': 'A0719a',                                                    │ │
│ │                     │   'hit2': 'A3509a'                                                     │ │
│ │                     }                                                                        │ │
│ │              data = [                                                                        │ │
│ │                     │   {                                                                    │ │
│ │                     │   │   'smiles': 'O=C(Cc1cocn1)Nc1ccc2c(c1)C(F)CC2',                    │ │
│ │                     │   │   'template': 'A5666a',                                            │ │
│ │                     │   │   'compound_set': 'openbind_a71ev2a_c1_scaffolds',                 │ │
│ │                     │   │   'hit1': 'A5151a',                                                │ │
│ │                     │   │   'hit2': 'A5512a'                                                 │ │
│ │                     │   },                                                                   │ │
│ │                     │   {                                                                    │ │
│ │                     │   │   'smiles': 'Cc1ccc(C(O)(C=O)NCc2cocn2)c2[nH]ccc12',               │ │
│ │                     │   │   'template': 'A5666a',                                            │ │
│ │                     │   │   'compound_set': 'openbind_a71ev2a_c1_scaffolds',                 │ │
│ │                     │   │   'hit1': 'A0487a',                                                │ │
│ │                     │   │   'hit2': 'A4940a'                                                 │ │
│ │                     │   },                                                                   │ │
│ │                     │   {                                                                    │ │
│ │                     │   │   'smiles': 'COc1ccc(C(C)=O)cc1-c1n[nH]cc1CN',                     │ │
│ │                     │   │   'template': 'A5666a',                                            │ │
│ │                     │   │   'compound_set': 'openbind_a71ev2a_c1_scaffolds',                 │ │
│ │                     │   │   'hit1': 'A0501a',                                                │ │
│ │                     │   │   'hit2': 'A4456a'                                                 │ │
│ │                     │   },                                                                   │ │
│ │                     │   {                                                                    │ │
│ │                     │   │   'smiles': 'CNNc1ccccc1-c1n[nH]c(C)c1CO',                         │ │
│ │                     │   │   'template': 'A5666a',                                            │ │
│ │                     │   │   'compound_set': 'openbind_a71ev2a_c1_scaffolds',                 │ │
│ │                     │   │   'hit1': 'A0501a',                                                │ │
│ │                     │   │   'hit2': 'A4524a'                                                 │ │
│ │                     │   },                                                                   │ │
│ │                     │   {                                                                    │ │
│ │                     │   │   'smiles':                                                        │ │
│ │                     'CN1CCc2cc(F)c(OC(=O)N3CCCC(C(N)=O)C3)cc2C1CCOc1ccc(CNCc2ccc(C#N)cc2)cc… │ │
│ │                     │   │   'template': 'A5666a',                                            │ │
│ │                     │   │   'compound_set': 'openbind_a71ev2a_c1_scaffolds',                 │ │
│ │                     │   │   'hit1': 'A0501b',                                                │ │
│ │                     │   │   'hit2': 'A4214a',                                                │ │
│ │                     │   │   'hit3': 'A4214b'                                                 │ │
│ │                     │   },                                                                   │ │
│ │                     │   {                                                                    │ │
│ │                     │   │   'smiles': 'NC(=O)C1CCCN(C(=O)NC2CN(CS)NC23CCCC2(CCC2)N3)C1',     │ │
│ │                     │   │   'template': 'A5666a',                                            │ │
│ │                     │   │   'compound_set': 'openbind_a71ev2a_c1_scaffolds',                 │ │
│ │                     │   │   'hit1': 'A0514a',                                                │ │
│ │                     │   │   'hit2': 'A4310a'                                                 │ │
│ │                     │   },                                                                   │ │
│ │                     │   {                                                                    │ │
│ │                     │   │   'smiles': 'COC(=O)c1cc(C)ncc1N(C)N',                             │ │
│ │                     │   │   'template': 'A5666a',                                            │ │
│ │                     │   │   'compound_set': 'openbind_a71ev2a_c1_scaffolds',                 │ │
│ │                     │   │   'hit1': 'A0514a',                                                │ │
│ │                     │   │   'hit2': 'A4331a'                                                 │ │
│ │                     │   },                                                                   │ │
│ │                     │   {                                                                    │ │
│ │                     │   │   'smiles': 'CCNCc1ccc(OC=O)cn1',                                  │ │
│ │                     │   │   'template': 'A5666a',                                            │ │
│ │                     │   │   'compound_set': 'openbind_a71ev2a_c1_scaffolds',                 │ │
│ │                     │   │   'hit1': 'A0514a',                                                │ │
│ │                     │   │   'hit2': 'A4346a'                                                 │ │
│ │                     │   },                                                                   │ │
│ │                     │   {                                                                    │ │
│ │                     │   │   'smiles': 'COC(=O)c1ccncc1N',                                    │ │
│ │                     │   │   'template': 'A5666a',                                            │ │
│ │                     │   │   'compound_set': 'openbind_a71ev2a_c1_scaffolds',                 │ │
│ │                     │   │   'hit1': 'A0514a',                                                │ │
│ │                     │   │   'hit2': 'A4368a'                                                 │ │
│ │                     │   },                                                                   │ │
│ │                     │   {                                                                    │ │
│ │                     │   │   'smiles': 'CC1CCC(C(N)=O)CN1C(=O)Nc1cn(CS)nc1C(=O)NC1CCC1',      │ │
│ │                     │   │   'template': 'A5666a',                                            │ │
│ │                     │   │   'compound_set': 'openbind_a71ev2a_c1_scaffolds',                 │ │
│ │                     │   │   'hit1': 'A0528a',                                                │ │
│ │                     │   │   'hit2': 'A3940a'                                                 │ │
│ │                     │   },                                                                   │ │
│ │                     │   ... +1508                                                            │ │
│ │                     ]                                                                        │ │
│ │                df = │   │   │   │   │   │   │   │   │   │   │   │    smiles template  \      │ │
│ │                     0                      O=C(Cc1cocn1)Nc1ccc2c(c1)C(F)CC2   A5666a         │ │
│ │                     1                 Cc1ccc(C(O)(C=O)NCc2cocn2)c2[nH]ccc12   A5666a         │ │
│ │                     2                       COc1ccc(C(C)=O)cc1-c1n[nH]cc1CN   A5666a         │ │
│ │                     3                           CNNc1ccccc1-c1n[nH]c(C)c1CO   A5666a         │ │
│ │                     4     CN1CCc2cc(F)c(OC(=O)N3CCCC(C(N)=O)C3)cc2C1CCOc...   A5666a         │ │
│ │                     ...                                                 ...      ...         │ │
│ │                     1513                                 c1cc(-c2ncco2)ccn1   A3897a         │ │
│ │                     1514               O=C(NCCc1cc[nH]n1)c1ccnc(-n2ccnc2)c1   A3897a         │ │
│ │                     1515                       C1CCC(c2nc3c([nH]2)CCCC3)NC1   A3897a         │ │
│ │                     1516                       C1CC(c2nc3c([nH]2)CCSC3)CCN1   A3897a         │ │
│ │                     1517                                CC(=O)CC(O)C1CCCNC1   A3897a         │ │
│ │                     │   │   │   │   │                                                        │ │
│ │                     │   │   │   │   │      compound_set    hit1    hit2    hit3 hit4 hit5    │ │
│ │                     hit6  \                                                                  │ │
│ │                     0     openbind_a71ev2a_c1_scaffolds  A5151a  A5512a     NaN  NaN  NaN    │ │
│ │                     NaN                                                                      │ │
│ │                     1     openbind_a71ev2a_c1_scaffolds  A0487a  A4940a     NaN  NaN  NaN    │ │
│ │                     NaN                                                                      │ │
│ │                     2     openbind_a71ev2a_c1_scaffolds  A0501a  A4456a     NaN  NaN  NaN    │ │
│ │                     NaN                                                                      │ │
│ │                     3     openbind_a71ev2a_c1_scaffolds  A0501a  A4524a     NaN  NaN  NaN    │ │
│ │                     NaN                                                                      │ │
│ │                     4     openbind_a71ev2a_c1_scaffolds  A0501b  A4214a  A4214b  NaN  NaN    │ │
│ │                     NaN                                                                      │ │
│ │                     ...                             ...     ...     ...     ...  ...  ...    │ │
│ │                     ...                                                                      │ │
│ │                     1513  openbind_a71ev2a_c1_scaffolds  A0556a  A3435a     NaN  NaN  NaN    │ │
│ │                     NaN                                                                      │ │
│ │                     1514  openbind_a71ev2a_c1_scaffolds  A0556a  A3435a     NaN  NaN  NaN    │ │
│ │                     NaN                                                                      │ │
│ │                     1515  openbind_a71ev2a_c1_scaffolds  A3371a  A3706a     NaN  NaN  NaN    │ │
│ │                     NaN                                                                      │ │
│ │                     1516  openbind_a71ev2a_c1_scaffolds  A3371a  A3706a     NaN  NaN  NaN    │ │
│ │                     NaN                                                                      │ │
│ │                     1517  openbind_a71ev2a_c1_scaffolds  A0719a  A3509a     NaN  NaN  NaN    │ │

# Run syndirella

```
cd cycle_01/syndirella
sbatch --job-name "a71ev2a_syndirella" --mem 16000 $HOME2/slurm/run_bash_with_conda.sh ../../../scripts/run_syndirella_retro.sh
```

## Read In Syndirella Retro Output

In [4]:
animal.db.delete_reactions()

In [5]:
animal.add_syndirella_routes(
    "cycle_01/syndirella/retrosynthesis/justretroquery_openbind_a71ev2a_c1_scaffolds_syndirella_input.pkl.gz", 
    CAR_only=False,
    check_chemistry=False,
)

Output()

0 0 0 Hydroxy_to_fluoro C139485 "DJFOQNYEAKBIRI-UHFFFAOYSA-N"

 Success  registered route 1!

1 0 0 Grignard_addition_to_carbonyl C143369 "FRGSBTNMALVKIX-UHFFFAOYSA-N"

1 0 1 Amidation C283087 "XFGWPZJRFKMEOF-UHFFFAOYSA-N"

1 0 2 Formation_of_Grignard C283088 "DWHMFASYRYHNPE-UHFFFAOYSA-M"

 Success  registered route 2!

2 0 0 Sp2-sp2_Suzuki_coupling C140978 "GTEDGOGNLVTJAH-UHFFFAOYSA-N"

 Success  registered route 3!

3 0 0 Sp2-sp2_Suzuki_coupling C140988 "SMJQGBYWPCXPDR-UHFFFAOYSA-N"

 Success  registered route 4!

4 0 0 Amine_alkylation C142584 "HOYKQAJNZZTFNB-UHFFFAOYSA-N"

4 0 1 Williamson_ether_synthesis C283099 "HFIDWISNKIHYSZ-UHFFFAOYSA-N"

4 0 2 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C286165 "CVWAFYQELLHYCS-UHFFFAOYSA-N"

4 0 3 Formation_of_carbamate_from_amine_and_alcohol C283108 "IISPPGLNHUXYLP-UHFFFAOYSA-N"

 Success  registered route 5!

6 0 0 N-nucleophilic_aromatic_substitution C141599 "VTHWZLJENYHQED-UHFFFAOYSA-N"

 Success  registered route 6!

7 0 0 Haloform_reaction C141610 "BVTGRELWAPFAGZ-UHFFFAOYSA-N"

 Success  registered route 7!

8 0 0 Steglich_esterification C15 "XLQIGLBALJNHKR-UHFFFAOYSA-N"

 Success  registered route 8!

9 0 0 Iodo_N-arylation C143262 "RSZCATFBIKXLMR-UHFFFAOYSA-N"

9 0 1 Amine_alkylation C283115 "XVBAYEOFMLWTME-UHFFFAOYSA-N"

 Success  registered route 9!

11 0 0 Amine_alkylation C223813 "MHXVSXRGCZAGOU-UHFFFAOYSA-N"

 Success  registered route 10!

12 0 0 Amide_to_amine_reduction C223849 "VZZNLCQRSIUYQV-UHFFFAOYSA-N"

 Success  registered route 11!

13 0 0 N-Phth_deprotection C223851 "LUMZHBRJYVSBCU-UHFFFAOYSA-N"

13 0 1 Thioester_from_alcohol_+_acid_chloride C283134 "HJLTWDFBWHNXHP-UHFFFAOYSA-N"

13 0 2 Amine_alkylation C286167 "OVQICMXRTSDTKM-UHFFFAOYSA-N"

13 0 3 Chlorination_of_alcohol C286168 "OSZIKGUEICTIAC-UHFFFAOYSA-N"

 Success  registered route 12!

14 0 0 Buchwald-Hartwig_(thio)etherification C223863 "GFLLQDRPUXMCNL-UHFFFAOYSA-N"

 Success  registered route 13!

15 0 0 Amidation C223867 "QMYIEUIBLQHGOH-UHFFFAOYSA-N"

15 0 1 Amidation C282916 "RMMAIEAOZXUGGA-UHFFFAOYSA-N"

 Success  registered route 14!

16 0 0 Minisci_reaction_with_carboxylic_acid_(intermolecular) C223876 "JFQKISFLWIGOGM-UHFFFAOYSA-N"

 Success  registered route 15!

18 0 0 Sp3-sp2_Suzuki_coupling C223890 "GEFQHGIGKICAEA-UHFFFAOYSA-N"

18 0 1 N-nucleophilic_aromatic_substitution C283143 "BSSBOXFSGMLEOR-UHFFFAOYSA-N"

18 0 2 Alpha_alkylation_of_ketone C283145 "KEQHSLJAPSLWSN-UHFFFAOYSA-N"

18 0 3 Alpha_alkylation_of_ketone C283147 "SMZJGHVCCPIKBA-UHFFFAOYSA-N"

 Success  registered route 16!

19 0 0 Imine_formation C140626 "WVCRQGVMFRYXPW-UHFFFAOYSA-N"

19 0 1 Claisen_condensation C283157 "USKPHQGTXYMAAK-UHFFFAOYSA-N"

19 0 2 Corey-House_synthesis_(intermolecular) C286171 "HOTUSZBYZKJZHT-UHFFFAOYSA-N"

19 0 3 Sonogashira_coupling C286172 "QDENAMHCDUBUGS-UHFFFAOYSA-N"

 Success  registered route 17!

20 0 0 Petasis-borono_Mannich_reaction C224261 "ISCVVQNSXGDQLC-UHFFFAOYSA-N"

 Success  registered route 18!

22 0 0 Amidation C224459 "FQRZQBJCBUZPFL-UHFFFAOYSA-N"

22 0 1 Formation_of_sulfonamide_from_halide_-_Shavnya_reaction C283167 "CODOEKCKHMFCDU-UHFFFAOYSA-N"

 Success  registered route 19!

23 0 0 N-nucleophilic_aromatic_substitution C224597 "QQECAXFDBXEVIN-UHFFFAOYSA-N"

 Success  registered route 20!

25 0 0 Reductive_amination C224826 "RMGPEBAHBGDSEW-UHFFFAOYSA-N"

 Success  registered route 21!

26 0 0 Alpha_alkylation_of_ketone C224908 "UVHVGUBWEQMBKH-UHFFFAOYSA-N"

 Success  registered route 22!

27 0 0 Buchwald-Hartwig_amidation_with_amide-like_nucleophile C225591 "VBSRSIBHLLKMRD-UHFFFAOYSA-N"

27 0 1 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C282930 "RCRCIWHZUBGRFR-UHFFFAOYSA-N"

 Success  registered route 23!

28 0 0 Grignard_addition_to_carbonyl C225528 "RHLCJNOASWSNMI-UHFFFAOYSA-N"

28 0 1 Formation_of_Grignard C283179 "XCLQYSYFFHHBRL-UHFFFAOYSA-M"

 Success  registered route 24!

29 0 0 Buchwald-Hartwig_(thio)etherification C226551 "NIPJUCNGLLJJFA-UHFFFAOYSA-N"

 Success  registered route 25!

30 0 0 Ester_amidation C226563 "NQUKOMUTPJKZKK-UHFFFAOYSA-N"

30 0 1 Hydrogenation_of_pyridine C283190 "AKVSKDFGTRQIRI-UHFFFAOYSA-N"

 Success  registered route 26!

31 0 0 Sp3-sp2_Suzuki_coupling C193943 "XCYJPXQACVEIOS-UHFFFAOYSA-N"

 Success  registered route 27!

32 0 0 Sp3-sp2_Suzuki_coupling C270367 "KVOJUNAPEGTLGD-UHFFFAOYSA-N"

 Success  registered route 28!

33 0 0 Amidation C272449 "JHOVMKNPAZUPKC-UHFFFAOYSA-N"

33 0 1 Ketone/aldehyde_chlorination C283200 "ZWVHNXLYGRSBOS-UHFFFAOYSA-N"

33 0 2 Hydrogenation_of_pyridine C283202 "BQNPUFQHIUCRNB-UHFFFAOYSA-N"

 Success  registered route 29!

34 0 0 Amine_alkylation C272450 "CZQKOPHNVUQSNW-UHFFFAOYSA-N"

34 0 1 Chlorination_of_alcohol C283208 "PYYZNPQDGDWEAI-UHFFFAOYSA-N"

34 0 2 Formation_of_urea_from_two_amines C286179 "LBWFSDPWYPPIIC-UHFFFAOYSA-N"

34 0 3 Hydrogenation_of_pyridine C286180 "DJHSIZCHDFBGGN-UHFFFAOYSA-N"

34 0 4 Ester_amidation C286181 "QGSFDZZTGKKDEI-UHFFFAOYSA-N"

 Success  registered route 30!

35 0 0 Amine_alkylation C272452 "LXSYKFPSDCVOLS-UHFFFAOYSA-N"

35 0 1 Ketone/aldehyde_chlorination C283209 "QIJYVROSWHILSJ-UHFFFAOYSA-N"

35 0 2 Ester_amidation C286185 "YBYIATWDAWZPNQ-UHFFFAOYSA-N"

35 0 3 Amidation C286181 "QGSFDZZTGKKDEI-UHFFFAOYSA-N"

35 0 4 Hydroxy_to_fluoro C286186 "DEKMVMVCQYWUJM-UHFFFAOYSA-N"

 Success  registered route 31!

36 0 0 Ester_amidation C272454 "VAFKCTIAOFBPGI-UHFFFAOYSA-N"

36 0 1 Hydroxy_to_fluoro C283211 "WZWHABJWZDTLJH-UHFFFAOYSA-N"

36 0 2 NHK_reaction C283212 "SABFPHUKCUSQBT-UHFFFAOYSA-N"

 Success  registered route 32!

37 0 0 Tebbe-Petasis_olefination C272236 "BQSDEPIXYSTHIQ-UHFFFAOYSA-N"

37 0 1 Carboxylic_acid_to_primary_amide C283216 "DAVYOTSZXWPLBF-UHFFFAOYSA-N"

37 0 2 Amidation C286191 "SDWQWPHCWPITNC-UHFFFAOYSA-N"

 Success  registered route 33!

38 0 0 Tebbe-Petasis_olefination C272482 "LNZDVQSHYXFPSN-UHFFFAOYSA-N"

38 0 1 Amidation C283217 "IIIXKMXAGPIAJI-UHFFFAOYSA-N"

38 0 2 Hydrogenation_of_pyridine C283219 "FXXLOZQTSLULCT-UHFFFAOYSA-N"

 Success  registered route 34!

39 0 0 Tebbe-Petasis_olefination C272530 "QXQZOHKAPUDTNY-UHFFFAOYSA-N"

39 0 1 Amidation C283221 "XLOOCPVYWZXIPT-UHFFFAOYSA-N"

39 0 2 Hydrogenation_of_pyridine C286194 "AKSJIMHLQSJEOF-UHFFFAOYSA-N"

39 0 3 Aziridine_+_amine_coupling C286195 "RDSCJDHGTVOKFY-UHFFFAOYSA-N"

39 0 4 Petasis-borono_Mannich_reaction C286197 "BHBPOZKLVWZIMN-UHFFFAOYSA-N"

39 0 5 Nucleophilic_substitution_with_imine C286198 "LOZPMNDAMNCIBB-UHFFFAOYSA-N"

 Success  registered route 35!

40 0 0 Stille_coupling C272543 "WQAUBMDSLQUNTO-UHFFFAOYSA-N"

40 0 1 Tebbe-Petasis_olefination C283226 "AIOHRTGNHLZXEN-UHFFFAOYSA-N"

40 0 2 Amidation C286202 "HNELSTNIUNONHB-UHFFFAOYSA-N"

40 0 3 Carboxylic_acid_to_primary_amide C286194 "AKSJIMHLQSJEOF-UHFFFAOYSA-N"

40 0 4 Amidation C286203 "JMOUXHIEVKJBIN-UHFFFAOYSA-N"

 Success  registered route 36!

42 0 0 Tebbe-Petasis_olefination C272559 "OVSZTICLVOBVDF-UHFFFAOYSA-N"

42 0 1 Amidation C283231 "WGRATXLXTRJCCZ-UHFFFAOYSA-N"

42 0 2 Ugi_reaction C286205 "HXNPKGRAACFVLK-UHFFFAOYSA-N"

42 0 3 Formation_of_isocyanides_from_alcohols C286206 "NHXLGGKBNMNGOE-UHFFFAOYSA-N"

42 0 4 Alpha_alkylation_of_ester/amide C286207 "QHZLFRLSRITILC-UHFFFAOYSA-N"

42 0 5 Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide C286208 "YKQCFCURKPXXLB-UHFFFAOYSA-N"

 Success  registered route 37!

43 0 0 Amidation C272859 "IEZGWHODQGSBRD-UHFFFAOYSA-N"

43 0 1 Amine_alkylation C283236 "YEQAXQICQSVSNP-UHFFFAOYSA-N"

43 0 2 Sp2-sp2_Suzuki_coupling C283238 "NITQGRDHBKHRCH-UHFFFAOYSA-N"

43 0 3 Amine_alkylation C283239 "BSICWWBSKXFBNL-UHFFFAOYSA-N"

 Success  registered route 38!

46 0 0 Buchwald-Hartwig_amination C204757 "QBTJBIZQBLWTHK-UHFFFAOYSA-N"

46 0 1 Ester_amidation C282935 "ZQESYXXFUYDADO-UHFFFAOYSA-N"

 Success  registered route 39!

47 0 0 Reductive_amination C204759 "HFYNVCDYDDENBP-UHFFFAOYSA-N"

47 0 1 Imine_reduction_to_amine C228293 "FVCHDJBQSPQZRF-UHFFFAOYSA-N"

47 0 2 Nucleophilic_substitution_with_imine C283252 "FZVLICIPHDTVGX-UHFFFAOYSA-N"

 Success  registered route 40!

48 0 0 Buchwald-Hartwig_amination C204769 "BULUSAUFSRPROH-UHFFFAOYSA-N"

 Success  registered route 41!

49 0 0 Amidation C204781 "GJSLUQQORYADDA-UHFFFAOYSA-N"

 Success  registered route 42!

50 0 0 Amidation C107 "ONGQCMNCDUWDOR-UHFFFAOYSA-N"

 Success  registered route 43!

51 0 0 Amidation C205051 "HGBAQJNRTBXKBY-UHFFFAOYSA-N"

 Success  registered route 44!

52 0 0 Amidation C205067 "IUKJWGRXOODHIO-UHFFFAOYSA-N"

 Success  registered route 45!

53 0 0 Amide_Schotten-Baumann_with_amine C209253 "XULPWVWELPOSEM-UHFFFAOYSA-N"

 Success  registered route 46!

54 0 0 Amidation C205099 "KJVZFMFVRBZFOP-UHFFFAOYSA-N"

 Success  registered route 47!

55 0 0 Amine_alkylation C205071 "PERMOVIPLPJQEI-UHFFFAOYSA-N"

55 0 1 Corey-House_synthesis_(intermolecular) C283257 "MDLNRUUGQHOPOY-UHFFFAOYSA-N"

55 0 2 Synthesis_of_organolithium C286218 "BBAHBXNVTHCCRC-UHFFFAOYSA-N"

 Success  registered route 48!

56 0 0 Amide_to_amine_reduction C206012 "CSWNYLMUJIALAZ-UHFFFAOYSA-N"

56 0 1 Petasis-borono_Mannich_reaction C283262 "RHBGIFRKIOFPQE-UHFFFAOYSA-N"

56 0 2 Amidation C286221 "JFBJTRAFHXLUBD-UHFFFAOYSA-N"

 Success  registered route 49!

57 0 0 Amine_alkylation C205207 "WKJLQQPDUXOUMP-UHFFFAOYSA-N"

57 0 1 Corey-House_synthesis_(intermolecular) C283265 "PZIPBDMWJBXVGG-UHFFFAOYSA-N"

57 0 2 Synthesis_of_organolithium C286223 "IAFFKEMFMPLBEH-UHFFFAOYSA-N"

57 0 3 Amine_alkylation C286225 "PBIFUZRQKMOWOZ-UHFFFAOYSA-N"

57 0 4 Appel_iodination C286224 "XOQKUUIWXBIFBX-UHFFFAOYSA-N"

 Success  registered route 50!

58 0 0 Reductive_amination C208022 "SQVAQLLFWWHIAM-UHFFFAOYSA-N"

58 0 1 Alpha_alkylation_of_ketone C283267 "OLQDRNGUNGHAMV-UHFFFAOYSA-N"

58 0 2 Alpha_alkylation_of_ketone C283269 "XCQQJNSHIQLRHC-UHFFFAOYSA-N"

 Success  registered route 51!

60 0 0 Reductive_amination C205673 "WZIRMQBHPLNZSO-UHFFFAOYSA-N"

60 0 1 Buchwald-Hartwig_amination C283272 "XMHPEHNPHDALLY-UHFFFAOYSA-N"

60 0 2 Amine_alkylation C283273 "LTCDMTRTGJRTIL-UHFFFAOYSA-N"

 Success  registered route 52!

62 0 0 Reductive_amination C206766 "FDHGUCPWMSEFHX-UHFFFAOYSA-N"

 Success  registered route 53!

64 0 0 Larock_indole_synthesis C207965 "MJVUMUCHXJIYSQ-UHFFFAOYSA-N"

64 0 1 Buchwald-Hartwig_amination C283281 "UUPKMMFKNPMVII-UHFFFAOYSA-N"

 Success  registered route 54!

65 0 0 Grignard_addition_to_carbonyl C207977 "DMZINGXWJCZRBU-UHFFFAOYSA-N"

65 0 1 Larock_indole_synthesis C283286 "QSKVFNBZRTZHBE-UHFFFAOYSA-M"

65 0 2 Formation_of_Grignard C286230 "SGPZLWJGKRBAHL-UHFFFAOYSA-M"

65 0 3 Amine_alkylation C286231 "MCEWXINRYUOMHX-UHFFFAOYSA-N"

65 0 4 Williamson_ether_synthesis C286233 "YVUNYDHALPBAAH-UHFFFAOYSA-N"

 Success  registered route 55!

66 0 0 Petasis-borono_Mannich_reaction C208797 "XXOQUOORJDYPRS-UHFFFAOYSA-N"

66 0 1 Carboxylic_acid_to_alcohol_reduction C283288 "PNHNCXMMTZZZQD-UHFFFAOYSA-N"

66 0 2 Bromo_to_boronic_acid C283289 "UELMUNSHWYJZSL-UHFFFAOYSA-N"

 Success  registered route 56!

68 0 0 Thioether_to_sulfone C206128 "VVPKDBSEKFTDKW-UHFFFAOYSA-N"

68 0 1 Buchwald-Hartwig_(thio)etherification C283294 "WTCGPFZVMHRHQV-UHFFFAOYSA-N"

 Success  registered route 57!

69 0 0 Amidation C205775 "GRQIJMFMPOTAPA-UHFFFAOYSA-N"

 Success  registered route 58!

70 0 0 Imine_reduction_to_amine C209279 "DBUQYLDMMGGVTB-UHFFFAOYSA-N"

70 0 1 Amine_alkylation C283295 "MULKQPALTBJAMU-UHFFFAOYSA-N"

70 0 2 Grignard_addition_to_carbonyl C286239 "SFMFGHFZQAGLHC-UHFFFAOYSA-N"

70 0 3 Formation_of_Grignard C286242 "FEWOKFYKUCEHON-UHFFFAOYSA-M"

 Success  registered route 59!

71 0 0 Amidation C209218 "RCJWHSZLGRRVMM-UHFFFAOYSA-N"

 Success  registered route 60!

72 0 0 Amidation C209837 "XIBNVKKKKOBXOR-UHFFFAOYSA-N"

 Success  registered route 61!

75 0 0 Reductive_amination C209458 "DEAYEWLCXYHNPI-UHFFFAOYSA-N"

75 0 1 Imine_reduction_to_amine C228293 "FVCHDJBQSPQZRF-UHFFFAOYSA-N"

75 0 2 Nucleophilic_substitution_with_imine C283252 "FZVLICIPHDTVGX-UHFFFAOYSA-N"

 Success  registered route 62!

76 0 0 Amidation C209478 "DMXCSEIOVCLCAJ-UHFFFAOYSA-N"

 Success  registered route 63!

77 0 0 Stille_coupling C209486 "HYGHYRLZACCXQI-UHFFFAOYSA-N"

77 0 1 Amidation C283305 "KJVZIHLYQWJMDD-UHFFFAOYSA-N"

 Success  registered route 64!

78 0 0 Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide C248595 "OWKLMJNPJZKEQM-UHFFFAOYSA-N"

78 0 1 Ester_amidation C283311 "WEOCMNSLQYRUFW-UHFFFAOYSA-N"

78 0 2 Amidation C286244 "PGLOLIWCPXNBLT-UHFFFAOYSA-N"

 Success  registered route 65!

79 0 0 Reductive_amination C250249 "HSQWIPMJMKOJQO-UHFFFAOYSA-N"

 Success  registered route 66!

80 0 0 Nucleophilic_substitution_with_imine C250497 "KJWDXNNRMHUODX-UHFFFAOYSA-N"

80 0 1 Minisci_reaction_with_carboxylic_acid_(intermolecular) C283316 "DMAHKEDVMJBRLU-UHFFFAOYSA-N"

80 0 2 Mannich_reaction C286247 "NRAYOVMNJSDLCW-UHFFFAOYSA-N"

80 0 3 N-Boc_deprotection C283317 "LSWNCJXCSDICED-UHFFFAOYSA-N"

 Success  registered route 67!

81 0 0 Amidation C250878 "CPCIPUAOQZTFDH-UHFFFAOYSA-N"

81 0 1 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C283321 "IOKVORVQPGDZTJ-UHFFFAOYSA-N"

81 0 2 Nucleophilic_aromatic_substitution_(alcohol,_phenol,_water) C286250 "LUFUJJBJYVRPFY-UHFFFAOYSA-N"

81 0 3 Grignard_addition_to_carbonyl C286251 "XXHCKOWMEQZGEH-UHFFFAOYSA-N"

81 0 4 Formation_of_Grignard C286255 "WVPAEFCONHIDRR-UHFFFAOYSA-M"

 Success  registered route 68!

82 0 0 Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide C250918 "CTVIJEWCBJAHCI-UHFFFAOYSA-N"

82 0 1 Grignard_addition_to_carbonyl C283325 "NGTLZBSYMBFTQE-UHFFFAOYSA-N"

82 0 2 Formation_of_Grignard C286256 "JUCIILFFYLBLRU-UHFFFAOYSA-M"

82 0 3 Ester_amidation C283330 "KKOUPOILNUEYOQ-UHFFFAOYSA-N"

 Success  registered route 69!

87 0 0 Amine_alkylation C263137 "ISIXDZMQJHSUKE-UHFFFAOYSA-N"

87 0 1 Buchwald-Hartwig_amination C283335 "VZKYPBXIBZDQDV-UHFFFAOYSA-N"

87 0 2 Buchwald-Hartwig_(thio)etherification C286260 "FEONTZICQBPJCT-UHFFFAOYSA-N"

 Success  registered route 70!

88 0 0 Amidation C207759 "WEZNMCCECZERHN-UHFFFAOYSA-N"

88 0 1 Buchwald-Hartwig_amination C282958 "NGDHLAXYVVTRSU-UHFFFAOYSA-N"

 Success  registered route 71!

89 0 0 Buchwald-Hartwig_amidation_with_amide-like_nucleophile C264290 "GPNKYXTWBNHZPT-UHFFFAOYSA-N"

89 0 1 N-acylation_of_amide C138686 "FYXHBQCWFRWHBD-UHFFFAOYSA-N"

 Success  registered route 72!

91 0 0 Alpha_alkylation_of_ester/amide C164254 "KFFAPYJDDXEIJM-UHFFFAOYSA-N"

91 0 1 Amidation C282961 "GQDABIFAALJAGR-UHFFFAOYSA-N"

91 0 2 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C286264 "VONFCYALIFVXKC-UHFFFAOYSA-N"

 Success  registered route 73!

92 0 0 Iodo_N-arylation C264587 "DGJUFCWDGCHNHJ-UHFFFAOYSA-N"

92 0 1 Grignard_addition_to_carbonyl C283346 "NIFULVVRRWKGND-UHFFFAOYSA-N"

 Success  registered route 74!

95 0 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C189983 "HWXYDZKCQZODDY-UHFFFAOYSA-N"

95 0 1 Amidation C283354 "ZENPCQFYBJWAIX-UHFFFAOYSA-N"

95 0 2 Aldehyde/ketone_to_alcohol_reduction C283355 "UNWSRBYWBWAQDF-UHFFFAOYSA-N"

 Success  registered route 75!

96 0 0 Amidation C266892 "MHJINKMDGLJYJH-UHFFFAOYSA-N"

 Success  registered route 76!

97 0 0 Amidation C264727 "FDGRSYLWCHGFJP-UHFFFAOYSA-N"

 Success  registered route 77!

98 0 0 Amidation C138541 "QHSCXGMDNOKEGD-UHFFFAOYSA-N"

 Success  registered route 78!

99 0 0 Amidation C178840 "JTCJLGZQLBXCSL-UHFFFAOYSA-N"

99 0 1 Reductive_amination C283361 "JYTPUSMVHYTSOM-UHFFFAOYSA-N"

99 0 2 Vilsmeier-Haack_formylation C286268 "LUGWXOBVVBINCO-UHFFFAOYSA-N"

 Success  registered route 79!

105 0 0 Alpha-arylation C263060 "ZBXRXFNVZOUTEP-UHFFFAOYSA-N"

105 0 1 Buchwald-Hartwig_amination C283364 "IXDCUWKPSAFYJR-UHFFFAOYSA-N"

 Success  registered route 80!

106 0 0 Alpha_alkylation_of_ester/amide C267601 "UMYBGOBPHOVEQB-UHFFFAOYSA-N"

106 0 1 Thiophene_C-2_alkylation C283371 "ZIJWDQKHJIGPEO-UHFFFAOYSA-N"

 Success  registered route 81!

109 0 0 Petasis-borono_Mannich_reaction C192018 "PVWWIGZYJBKIAA-UHFFFAOYSA-N"

 Success  registered route 82!

111 0 0 Amidation C211420 "KINPTNKBZKLBEK-UHFFFAOYSA-N"

 Success  registered route 83!

114 0 0 Isocyanate_to_urea C264563 "QYCKRLPOQMCSGI-UHFFFAOYSA-N"

 Success  registered route 84!

115 0 0 Amidation C176894 "PSIYEGSIAUUUKH-UHFFFAOYSA-N"

 Success  registered route 85!

117 0 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C193826 "FNNHSCZUTYNJDJ-UHFFFAOYSA-N"

117 0 1 Aldehyde/ketone_to_alcohol_reduction C283382 "DVBQPLWXZXWLPP-UHFFFAOYSA-N"

117 0 2 Alpha_alkylation_of_ketone C283383 "GKGGVNGAJOYTCY-UHFFFAOYSA-N"

 Success  registered route 86!

119 0 0 Amine_alkylation C192498 "XEWCIHXKBKXNHS-UHFFFAOYSA-N"

119 0 1 Nucleophilic_substitution_with_imine C283384 "AEPSORLKUUGMMX-UHFFFAOYSA-N"

119 0 2 Amidation C283243 "UGSTZLLFSCALOZ-UHFFFAOYSA-N"

 Success  registered route 87!

120 0 0 Alpha-arylation C166559 "FTPLNKSHYLFOCK-UHFFFAOYSA-N"

120 0 1 Ester_amidation C283387 "DXDDQIIIJUKHBR-UHFFFAOYSA-N"

120 0 2 Benzylic_deprotonation-alkylation_(pyridine) C286276 "STXVORWLKFXUFS-UHFFFAOYSA-N"

120 0 3 Friedel-Crafts_methylation C286277 "UZJVOVUTXUQWCO-UHFFFAOYSA-N"

 Success  registered route 88!

121 0 0 Ester_amidation C193333 "GYHNELMRIHFZDX-UHFFFAOYSA-N"

121 0 1 Alpha_alkylation_of_ester/amide C282974 "FIVCQXBJJCGVEM-UHFFFAOYSA-N"

121 0 2 Alpha_alkylation_of_ester/amide C286280 "GUQADPMWZFWGAO-UHFFFAOYSA-N"

 Success  registered route 89!

122 0 0 Amidation C195109 "KLIJUPNPMOMPIT-UHFFFAOYSA-N"

 Success  registered route 90!

126 0 0 Buchwald-Hartwig_(thio)etherification C280132 "YWPKEXDUKMIEPU-UHFFFAOYSA-N"

126 0 1 NHK_reaction C283393 "NOYGETUSBFRJFE-UHFFFAOYSA-N"

 Success  registered route 91!

127 0 0 Amine_alkylation C280144 "TXMSFQQPVYLOJC-UHFFFAOYSA-N"

127 0 1 Buchwald-Hartwig_amination_with_hydrazine C283397 "RYZWOOBEWLEVCN-UHFFFAOYSA-N"

 Success  registered route 92!

139 0 0 NHK_reaction C177719 "WECSMDFTHCGFKA-UHFFFAOYSA-N"

 Success  registered route 93!

142 0 0 Amidation C160667 "MLUYARBKPLLQGO-UHFFFAOYSA-N"

142 0 1 Reductive_amination C283412 "FBNVECSFMPOEGE-UHFFFAOYSA-N"

142 0 2 Alpha_alkylation_of_ketone C283413 "LKYPRSREKAGEKM-UHFFFAOYSA-N"

 Success  registered route 94!

144 0 0 Iodo_N-arylation C160793 "BQNACJRNYISVSZ-UHFFFAOYSA-N"

144 0 1 Chan-Lam_coupling_(amination) C283421 "HFOQHUYZMRDHJF-UHFFFAOYSA-N"

144 0 2 Fischer_indole_synthesis C286286 "FOSNYWYNMSMVQT-UHFFFAOYSA-N"

 Success  registered route 95!

145 0 0 Buchwald-Hartwig_amidation_with_amide-like_nucleophile C159094 "YVPORMJUNHFFRP-UHFFFAOYSA-N"

145 0 1 Amidation C176936 "GFHLFLFRWWDWPS-UHFFFAOYSA-N"

 Success  registered route 96!

146 0 0 N-Boc_deprotection C155988 "VMAHPGKKKWPAJU-UHFFFAOYSA-N"

146 0 1 Corey-House_synthesis_(intermolecular) C283426 "GQFLLDWFKDDEAA-UHFFFAOYSA-N"

146 0 2 Synthesis_of_organolithium C283427 "IGCKVOUYIUHUIG-UHFFFAOYSA-N"

146 0 3 Alpha_alkylation_of_ester/amide C283428 "XTLFJNDMWKOEPS-UHFFFAOYSA-N"

 Success  registered route 97!

147 0 0 Hydrogenation_of_pyridine C160224 "VMRRETVEFLYQLB-UHFFFAOYSA-N"

147 0 1 Sp3-sp2_Macmillan_coupling_with_bromide_(intermolecular) C283430 "UGPPEEZBJHKSJU-UHFFFAOYSA-N"

147 0 2 Formation_of_sulfone_from_halide_-_Shavnya_reaction C286290 "GYVHVYQZUWNKKZ-UHFFFAOYSA-N"

 Success  registered route 98!

149 0 0 Amidation C161860 "UWUWVBJAARDSSL-UHFFFAOYSA-N"

 Success  registered route 99!

156 0 0 Sp3-sp2_Suzuki_coupling C236405 "PNIRUYFAVYSKGX-UHFFFAOYSA-N"

156 0 1 Amine_alkylation C283431 "HXWJUMPBKRAQOE-UHFFFAOYSA-N"

156 0 2 Grignard_addition_to_carbonyl C283433 "HRFPUFBTMAGORD-UHFFFAOYSA-N"

156 0 3 N-acylation_of_amide C286292 "AKJDPJUMQCTXDP-UHFFFAOYSA-N"

156 0 4 Formation_of_Grignard C286293 "CRPMWSKJKOVBCI-UHFFFAOYSA-M"

 Success  registered route 100!

159 0 0 Alpha_alkylation_of_ketone C215084 "PBUVVEGHRQRWFC-UHFFFAOYSA-N"

 Success  registered route 101!

160 0 0 Corey-House_synthesis_(intermolecular) C216188 "UVRVNMDNGVIBGM-UHFFFAOYSA-N"

 Success  registered route 102!

161 0 0 Alkene_hydrogenation_(unconjugated) C216355 "HYQPAIHEMGSSJO-UHFFFAOYSA-N"

161 0 1 Amine_alkylation C283449 "UNUDBBUSTFLKII-UHFFFAOYSA-N"

161 0 2 Heck_reaction_(intermolecular) C286295 "LGZFMOVWHCAYBE-UHFFFAOYSA-N"

 Success  registered route 103!

162 0 0 Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide C216357 "HUSFWJZEUFNZSQ-UHFFFAOYSA-N"

162 0 1 Grignard_addition_to_carbonyl C283456 "NCQPRVSFLHSOMA-UHFFFAOYSA-N"

162 0 2 Amidation C286298 "KGIOUGGPFZFTFV-UHFFFAOYSA-N"

162 0 3 Formation_of_Grignard C286299 "TYLHJCAXRFHECU-UHFFFAOYSA-M"

 Success  registered route 104!

163 0 0 Alkene_hydrogenation_(unconjugated) C216360 "LMIJHJCABBMJTL-UHFFFAOYSA-N"

163 0 1 Amine_alkylation C283459 "PCGCUMRRZPFLTK-UHFFFAOYSA-N"

163 0 2 Heck_reaction_(intermolecular) C286302 "ATBMRABQVICZRH-UHFFFAOYSA-N"

163 0 3 Sp2-sp2_Suzuki_coupling C286303 "QZHHGVUECWPUQF-UHFFFAOYSA-N"

 Success  registered route 105!

164 0 0 Ring_closing_metathesis C216367 "CCWJSDMCVYJGGM-UHFFFAOYSA-N"

164 0 1 Amidation C283460 "XBSDYCFDQONNEY-UHFFFAOYSA-N"

164 0 2 Petasis-borono_Mannich_reaction C286306 "MMCIOGYIJXODRT-UHFFFAOYSA-N"

164 0 3 Alpha_alkylation_of_ketone C286308 "MAGIOQWJZFCHRW-UHFFFAOYSA-N"

 Success  registered route 106!

166 0 0 Sp3-sp2_Suzuki_coupling C216415 "IAGKFRITHIIXME-UHFFFAOYSA-N"

166 0 1 Grignard_addition_to_carbonyl C283466 "WQWGXMVGBWMZKS-UHFFFAOYSA-N"

166 0 2 Amidation C286311 "VZKLUMJLQZOLID-UHFFFAOYSA-N"

166 0 3 Buchwald-Hartwig_(thio)etherification C286312 "NODVXZXWZDLMNB-UHFFFAOYSA-M"

166 0 4 O-THP_deprotection C286315 "TXAHINUTLSEMHS-UHFFFAOYSA-M"

 Success  registered route 107!

168 0 0 Grignard_addition_to_carbonyl C216439 "SSIXCXGUESZBGS-UHFFFAOYSA-N"

168 0 1 Sp3-sp2_Suzuki_coupling C283471 "AMSOVNPREXJNDO-UHFFFAOYSA-M"

168 0 2 Formation_of_Grignard C286317 "PZHYZPQUNQEOQO-UHFFFAOYSA-M"

168 0 3 Ester_hydrolysis_(alcohol_fragment) C216293 "FCKICGFRHXVQFJ-UHFFFAOYSA-N"

 Success  registered route 108!

172 0 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C216480 "WTRKRXUSBNGMEC-UHFFFAOYSA-N"

172 0 1 Alpha_alkylation_of_ketone C283479 "GQCRRYTYEOSBLF-UHFFFAOYSA-N"

172 0 2 Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide C283480 "QYJMREDMDLQIDB-UHFFFAOYSA-N"

 Success  registered route 109!

173 0 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C216299 "FDXLNKBSSMKNST-UHFFFAOYSA-N"

173 0 1 Alpha_alkylation_of_ketone C283484 "LIJSCXVHFAVSHE-UHFFFAOYSA-N"

173 0 2 Reductive_amination C286322 "JZKBZSGVTYORRF-UHFFFAOYSA-N"

173 0 3 Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide C286323 "BSYIIZFECRFZTB-UHFFFAOYSA-N"

 Success  registered route 110!

174 0 0 Sp3-sp2_Macmillan_coupling_with_bromide_(intermolecular) C216506 "WIXMSLLRVUTSKV-UHFFFAOYSA-N"

174 0 1 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C283487 "HYCDHNRKWMNLRP-UHFFFAOYSA-N"

174 0 2 Reductive_amination C286325 "ILAJIBVEXGSEJM-UHFFFAOYSA-N"

174 0 3 Alpha_alkylation_of_ketone C286327 "NQPVSKCMYZOATM-UHFFFAOYSA-N"

 Success  registered route 111!

177 0 0 Ring_closing_metathesis C216499 "PEXDTKOHQKGDOE-UHFFFAOYSA-N"

177 0 1 Amidation C283491 "MWPXBVYAHXKWGX-UHFFFAOYSA-N"

177 0 2 Petasis-borono_Mannich_reaction C286306 "MMCIOGYIJXODRT-UHFFFAOYSA-N"

177 0 3 Alpha_alkylation_of_ketone C286308 "MAGIOQWJZFCHRW-UHFFFAOYSA-N"

 Success  registered route 112!

178 0 0 Alpha_alkylation_of_ketone C216542 "YQZSZCNVDYPABN-UHFFFAOYSA-N"

178 0 1 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C283493 "GZAWKUOAZAOXFO-UHFFFAOYSA-N"

178 0 2 Reductive_amination C286330 "IDVNDYTXGMSXRS-UHFFFAOYSA-N"

178 0 3 Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide C286331 "VPUDJNVNAAMZDZ-UHFFFAOYSA-N"

 Success  registered route 113!

179 0 0 Alpha_alkylation_of_ester/amide C216552 "SBEYKMJRSWNDJO-UHFFFAOYSA-N"

179 0 1 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C282988 "YSNIUNWQUHMQIN-UHFFFAOYSA-N"

 Success  registered route 114!

181 0 0 Benzylic_deprotonation-alkylation_(pyridine) C216729 "ACGAOFJUNQSDGT-UHFFFAOYSA-N"

181 0 1 Amidation C283498 "AILNMVQRDOBUBV-UHFFFAOYSA-N"

 Success  registered route 115!

182 0 0 Williamson_ether_synthesis C179963 "DBUJFULDVAZULB-UHFFFAOYSA-N"

 Success  registered route 116!

187 0 0 Amidation C203259 "FCAAAVKQVZHQHC-UHFFFAOYSA-N"

 Success  registered route 117!

188 0 0 Amine_alkylation C261944 "GOJVKZFYKWKGEI-UHFFFAOYSA-N"

188 0 1 Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide C283502 "FKTOPCOFRQUAFP-UHFFFAOYSA-N"

 Success  registered route 118!

189 0 0 Amidation C155426 "BUDYDGJIWBAUAH-UHFFFAOYSA-N"

 Success  registered route 119!

192 0 0 Grignard_addition_to_carbonyl C154866 "KSWWLSZWNYUPKN-UHFFFAOYSA-N"

192 0 1 Formation_of_Grignard C283507 "DICOAEFXRQKMCY-UHFFFAOYSA-M"

192 0 2 N-acylation_of_amide C139000 "XZYUVRTZFHARDT-UHFFFAOYSA-N"

 Success  registered route 120!

194 0 0 Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide C145049 "KECOMYVRALMHPG-UHFFFAOYSA-N"

194 0 1 Grignard_addition_to_carbonyl C283511 "YAVDJAKXYLDSPI-UHFFFAOYSA-N"

194 0 2 Amine_alkylation C286342 "GBNWIEWBXLDIIX-UHFFFAOYSA-M"

194 0 3 Formation_of_Grignard C286343 "CZFFVMLSGKTWBW-UHFFFAOYSA-M"

 Success  registered route 121!

195 0 0 Nucleophilic_substitution_with_thiol C145578 "AQAMQMSGSHVYSE-UHFFFAOYSA-N"

195 0 1 Alpha_alkylation_of_aldehyde C283517 "GQVUTQCGPSNJIE-UHFFFAOYSA-N"

 Success  registered route 122!

197 0 0 Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide C145809 "UWQPEPKLQMYNPZ-UHFFFAOYSA-N"

197 0 1 Grignard_addition_to_carbonyl C283521 "QTQPZKRAJNCNQN-UHFFFAOYSA-N"

197 0 2 Amine_alkylation C286349 "LHPKCKMEJRBQQL-UHFFFAOYSA-M"

197 0 3 Formation_of_Grignard C286343 "CZFFVMLSGKTWBW-UHFFFAOYSA-M"

 Success  registered route 123!

199 0 0 Alpha_alkylation_of_ketone C145902 "SLPHMEGNVKINDS-UHFFFAOYSA-N"

199 0 1 Swern_oxidation C283525 "MVCNXXIPHHFMBW-UHFFFAOYSA-N"

199 0 2 Amidation C286351 "DXNHEPUKASTDQT-UHFFFAOYSA-N"

199 0 3 Alpha_alkylation_of_ester/amide C286353 "RNOVUJCSJKDJKM-UHFFFAOYSA-N"

 Success  registered route 124!

202 0 0 Imidazole_C-2_addition_to_ketone/aldehyde C146040 "SCDNAKOYMIYAQA-UHFFFAOYSA-N"

202 0 1 Amidation C283529 "VBKBXIFUEXTJOV-UHFFFAOYSA-N"

 Success  registered route 125!

203 0 0 Claisen_condensation C146186 "GHLNUKUVXIIUDH-UHFFFAOYSA-N"

203 0 1 Amidation C283534 "PPQMHXLRNNQEPU-UHFFFAOYSA-N"

203 0 2 Hydrogenation_of_pyridine C286357 "VYQVLCCCXSIFMP-UHFFFAOYSA-N"

 Success  registered route 126!

206 0 0 Amide_to_amine_reduction C146746 "UFMKQVZXEYBDBD-UHFFFAOYSA-N"

206 0 1 Carboxylic_acid_+_hydrazine_condensation C283537 "GCDFDEBNNSGGAL-UHFFFAOYSA-N"

206 0 2 Grignard_addition_to_carbonyl C286359 "RXMYFQZYPOBBIG-UHFFFAOYSA-N"

 Success  registered route 127!

216 0 0 Williamson_ether_synthesis C148261 "QDCKVDNVBDQFNM-UHFFFAOYSA-N"

218 0 0 Ring_closing_metathesis C181196 "OAZGZFZJSHMQAF-UHFFFAOYSA-N"

218 0 1 NHK_reaction C283540 "LCNBNGMHOGXAHJ-UHFFFAOYSA-N"

218 0 2 Amidation C286364 "HHVXONILONQXMW-UHFFFAOYSA-N"

218 0 3 Sp2-sp2_Suzuki_coupling C286366 "XUGDIKWFPQFJSE-UHFFFAOYSA-N"

 Success  registered route 129!

219 0 0 Ring_closing_metathesis C181214 "XBUJMKISRHCTDR-UHFFFAOYSA-N"

219 0 1 Amidation C283549 "SUMYYHFAEKSGFA-UHFFFAOYSA-N"

219 0 2 Sp2-sp2_Suzuki_coupling C286368 "JJQLQMROBXQQLP-UHFFFAOYSA-N"

219 0 3 NHK_reaction C286369 "NVTXNXTWIVAZPM-UHFFFAOYSA-N"

219 0 4 Sandmeyer_iodination C286371 "BDSLPGWTZUXTCM-UHFFFAOYSA-N"

 Success  registered route 130!

229 0 0 Claisen_condensation C181317 "PSFZHIZHBUGQQO-UHFFFAOYSA-N"

229 0 1 Amidation C283551 "NQMNWPHEYCYGDL-UHFFFAOYSA-N"

229 0 2 NHK_reaction C286374 "WYHVVDBCYGOENG-UHFFFAOYSA-N"

 Success  registered route 131!

231 0 0 Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide C181320 "IKIOITOSBVZGHJ-UHFFFAOYSA-N"

231 0 1 Grignard_addition_to_carbonyl C283554 "VWNPGYSGODJSJF-UHFFFAOYSA-N"

231 0 2 Amine_alkylation C286342 "GBNWIEWBXLDIIX-UHFFFAOYSA-M"

231 0 3 Formation_of_Grignard C286343 "CZFFVMLSGKTWBW-UHFFFAOYSA-M"

 Success  registered route 132!

232 0 0 Hydrolysis_of_magnesium_alkylthiolate C181344 "XAWSNWWGAIHPIO-UHFFFAOYSA-N"

232 0 1 Synthesis_of_magnesium_alkylthiolate C283556 "ZYYUBGCJNMBCAT-UHFFFAOYSA-M"

 Success  registered route 133!

233 0 0 Sp3-sp2_Macmillan_coupling_with_chloride_(intermolecular) C181372 "FYJSPFYXYVMCOE-UHFFFAOYSA-N"

233 0 1 Grignard_addition_to_carbonyl C283560 "BECIVOBXFMEJSS-UHFFFAOYSA-N"

233 0 2 Ester_amidation C286378 "PGNGPGAKNUMYSF-UHFFFAOYSA-N"

 Success  registered route 134!

237 0 0 NHK_reaction C181440 "HRAPKXFSNLPORY-UHFFFAOYSA-N"

237 0 1 Aromatic_bromination C283563 "KJKIGPWKSWEYJC-UHFFFAOYSA-N"

237 0 2 Amide_Schotten-Baumann_with_amine C283564 "FRXPKTBMYPFGQK-UHFFFAOYSA-N"

237 0 3 Friedel-Crafts_acylation C286382 "GQOSZXAVAIBQCB-UHFFFAOYSA-N"

 Success  registered route 135!

242 0 0 Sp3-sp2_Macmillan_coupling_with_chloride_(intermolecular) C181958 "OGXOPRLPVWVISU-UHFFFAOYSA-N"

242 0 1 Reductive_amination C283569 "KAOAKWULOWJFCW-UHFFFAOYSA-N"

242 0 2 Reductive_amination C286385 "BTRAHUCIOUMQGX-UHFFFAOYSA-N"

 Success  registered route 136!

243 0 0 S-nucleophilic_aromatic_substitution C181906 "GAIGGVYAGRLFMC-UHFFFAOYSA-N"

243 0 1 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C282995 "GQHGYDBRXOZKNP-UHFFFAOYSA-N"

243 0 2 Reductive_amination C286388 "PGNCUUDWEKGMSY-UHFFFAOYSA-N"

 Success  registered route 137!

245 0 0 Heck_reaction_(intermolecular) C182001 "RXUNDRBYKCAMQB-UHFFFAOYSA-N"

245 0 1 Amidation C283573 "LZLZEVAGQFZWOA-UHFFFAOYSA-N"

245 0 2 Horner-Wadsworth-Emmons_reaction C286391 "SQFKYPGNFPQFDD-UHFFFAOYSA-N"

245 0 3 TEMPO_oxidation C286392 "UIGBRZDENSDXMU-UHFFFAOYSA-N"

 Success  registered route 138!

246 0 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C182105 "IEGLJRXZWZHGQG-UHFFFAOYSA-N"

246 0 1 Amine_alkylation C283577 "URBZQXCALHNBBX-UHFFFAOYSA-N"

246 0 2 Alpha_alkylation_of_ketone C286395 "BUIOAPJKFZWONE-UHFFFAOYSA-N"

246 0 3 Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide C286396 "KQKLRWLBQATSEF-UHFFFAOYSA-N"

247 0 0 Sp3-sp2_Macmillan_coupling_with_chloride_(intermolecular) C182109 "BSVXJKRMERDWGF-UHFFFAOYSA-N"

247 0 1 Reductive_amination C283569 "KAOAKWULOWJFCW-UHFFFAOYSA-N"

247 0 2 Reductive_amination C286385 "BTRAHUCIOUMQGX-UHFFFAOYSA-N"

 Success  registered route 140!

248 0 0 Reductive_amination C182121 "SNNKCQMKKUBBPN-UHFFFAOYSA-N"

248 0 1 Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide C283585 "GUNUSEKJZKNRAF-UHFFFAOYSA-N"

248 0 2 Reductive_amination C286398 "KYCZXBXAKHQYDA-UHFFFAOYSA-N"

 Success  registered route 141!

249 0 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C182125 "JFTIVCICNQOZAI-UHFFFAOYSA-N"

249 0 1 Ozonolysis_(to_alcohol,_intramolecular) C283590 "KJVAMRSRUZMWST-UHFFFAOYSA-N"

249 0 2 Reductive_amination C286399 "RKBWPQZTVLVZEV-UHFFFAOYSA-N"

249 0 3 Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide C286400 "AQJVYBDHILDMLE-UHFFFAOYSA-N"

 Success  registered route 142!

250 0 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C182163 "KGEGNRYOTDGQLV-UHFFFAOYSA-N"

250 0 1 Alpha_alkylation_of_ketone C283594 "PFAIMTIVFDKMPF-UHFFFAOYSA-N"

250 0 2 Reductive_amination C286401 "WJADEOXZUNNWFY-UHFFFAOYSA-N"

250 0 3 Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide C286402 "REOXVNIRCHPPCG-UHFFFAOYSA-N"

 Success  registered route 143!

251 0 0 Alpha_alkylation_of_ketone C182169 "RUKKUCYHUKCBDF-UHFFFAOYSA-N"

 Success  registered route 144!

252 0 0 Amine_alkylation C182134 "WNWPBURIRJZWDB-UHFFFAOYSA-N"

252 0 1 S-nucleophilic_aromatic_substitution C283601 "IHGMZMVMBPDWHR-UHFFFAOYSA-N"

252 0 2 Reductive_amination C286403 "QVLWMMNURYCHLP-UHFFFAOYSA-N"

252 0 3 Alpha_alkylation_of_aldehyde C286404 "LMKIGPSXIQIUQU-UHFFFAOYSA-N"

 Success  registered route 145!

253 0 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C182181 "QBIWCRLJRSIZFF-UHFFFAOYSA-N"

253 0 1 Reductive_amination C283606 "OINLYFOMQCQYLN-UHFFFAOYSA-N"

253 0 2 Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide C286407 "RMTCGMOGZGHYMC-UHFFFAOYSA-N"

253 0 3 S-nucleophilic_aromatic_substitution C286408 "FGECQHWYFPWMKA-UHFFFAOYSA-N"

 Success  registered route 146!

254 0 0 Amine_alkylation C182188 "BLNUXUYGSMWJHQ-UHFFFAOYSA-N"

254 0 1 Reductive_amination C283608 "GMEIQYAVCOYYHB-UHFFFAOYSA-N"

254 0 2 Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide C286410 "KHLHDZRIBKDBIE-UHFFFAOYSA-N"

254 0 3 Alpha_alkylation_of_aldehyde C286404 "LMKIGPSXIQIUQU-UHFFFAOYSA-N"

 Success  registered route 147!

255 0 0 S-nucleophilic_aromatic_substitution C181935 "AFWCNCDEVDPSGG-UHFFFAOYSA-N"

255 0 1 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C283611 "MXTNGURZHBYXPJ-UHFFFAOYSA-N"

255 0 2 Reductive_amination C286412 "CIFMJQQOHGIBKW-UHFFFAOYSA-N"

255 0 3 Alpha_alkylation_of_ketone C286413 "NPLOMTSUWSPWLD-UHFFFAOYSA-N"

 Success  registered route 148!

256 0 0 S-nucleophilic_aromatic_substitution C182197 "BPTFCRKOVTZCQF-UHFFFAOYSA-N"

256 0 1 Sp3-sp2_Macmillan_coupling_with_chloride_(intermolecular) C283616 "NWEPAQQXHACVGU-UHFFFAOYSA-N"

256 0 2 Reductive_amination C283569 "KAOAKWULOWJFCW-UHFFFAOYSA-N"

256 0 3 Reductive_amination C286385 "BTRAHUCIOUMQGX-UHFFFAOYSA-N"

 Success  registered route 149!

257 0 0 Hydrolysis_of_magnesium_alkylthiolate C182207 "WMUUVFWDNLHIJJ-UHFFFAOYSA-N"

257 0 1 Synthesis_of_magnesium_alkylthiolate C283618 "GJWHCFSHMQMWPK-UHFFFAOYSA-M"

 Success  registered route 150!

260 0 0 Sp3-sp2_Macmillan_coupling_with_bromide_(intermolecular) C211238 "UROBGGNSTLIPEU-UHFFFAOYSA-N"

260 0 1 Larock_indole_synthesis C283623 "QBRMHXQRJOMKJD-UHFFFAOYSA-N"

260 0 2 Grignard_addition_to_carbonyl C286415 "FPZVOPUIFCSIKZ-UHFFFAOYSA-N"

260 0 3 N-acylation_of_amide C286417 "QGLUNNXAKXPGAK-UHFFFAOYSA-N"

260 0 4 Formation_of_Grignard C286418 "AYDPDSHXKOVOCO-UHFFFAOYSA-M"

 Success  registered route 151!

264 0 0 Amine_alkylation C214698 "TVYXXSMKKFSTDL-UHFFFAOYSA-N"

264 0 1 Reductive_amination C283626 "FROVXNDCAYFBQX-UHFFFAOYSA-N"

 Success  registered route 152!

268 0 0 Buchwald-Hartwig_amidation_with_amide-like_nucleophile C252325 "JWUDNWNUFKEQFE-UHFFFAOYSA-N"

268 0 1 Amidation C283631 "NQLFJQJMPSFBOA-UHFFFAOYSA-N"

268 0 2 Sulfonamide_Schotten-Baumann_with_amine_(intermolecular) C283636 "FQIXCHGUYRVQGX-UHFFFAOYSA-N"

268 0 3 Aromatic_bromination C286423 "OIODULHVUSOXGI-UHFFFAOYSA-N"

 Success  registered route 153!

271 0 0 Grignard_addition_to_carbonyl C254303 "HVXHFWAWXOENKE-UHFFFAOYSA-N"

271 0 1 Amidation C283640 "GYGNZTXINNQVEF-UHFFFAOYSA-N"

 Success  registered route 154!

273 0 0 Buchwald-Hartwig_amination C168335 "QYPHKTUDALALPC-UHFFFAOYSA-N"

273 0 1 Amidation C282999 "WLZWMDCXPZGGJR-UHFFFAOYSA-N"

273 0 2 Alpha_alkylation_of_ester/amide C283000 "AVBWDXQWYUBHBP-UHFFFAOYSA-N"

273 0 3 Amidation C276 "GNWVDSWMINQMLL-UHFFFAOYSA-N"

 Success  registered route 155!

274 0 0 Amidation C169562 "DOTHXRCBGJFSGT-UHFFFAOYSA-N"

274 0 1 Hydrogenation_of_pyridine C283646 "RGGUIHXXUSOYSL-UHFFFAOYSA-N"

 Warning  SMILES changed during compound registration: NC(=O)c1ccc(O)nc1 --> NC(=O)c1ccc(=O)[nH]c1!

 Success  registered route 156!

284 0 0 Amidation C276709 "ARBXKTTXCOPQPM-UHFFFAOYSA-N"

284 0 1 Grignard_addition_to_carbonyl C283653 "VGEOYVUWOOPOJH-UHFFFAOYSA-N"

 Success  registered route 157!

287 0 0 N-Ac_deprotection C277954 "PUPGQZFKQUNUEK-UHFFFAOYSA-N"

287 0 1 Beckmann_rearrangement C283658 "GKMDWLMQEMAFIW-UHFFFAOYSA-N"

287 0 2 Enolate_conjugate_addition C286426 "PDAPJGFKOMDYRJ-UHFFFAOYSA-N"

287 0 3 Buchwald-Hartwig_(thio)etherification C286427 "SRMSNXGUQYGLKZ-UHFFFAOYSA-N"

 Success  registered route 158!

288 0 0 Corey-House_synthesis_(intermolecular) C242679 "QOPZJBUCVFBGAX-UHFFFAOYSA-N"

288 0 1 Synthesis_of_organolithium C283659 "STTLBVCUDNXQRV-UHFFFAOYSA-N"

 Success  registered route 159!

295 0 0 Ester_amidation C197218 "WJNYPPPXBFUKQL-UHFFFAOYSA-N"

295 0 1 Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide C283667 "KKUZRRZLYZHFQO-UHFFFAOYSA-N"

295 0 2 Conjugate_addition_of_Grignard_(Gilman_reagents) C286431 "CEHFYYRFMUMBOF-UHFFFAOYSA-N"

295 0 3 Formation_of_Grignard C286433 "DCLOADSZJWOIOM-UHFFFAOYSA-M"

 Success  registered route 160!

296 0 0 Alpha_alkylation_of_ester/amide C230890 "AZEOFDDNIYRHDU-UHFFFAOYSA-N"

296 0 1 Ugi_reaction C283669 "IKRRCMKKFDFAEG-UHFFFAOYSA-N"

 Success  registered route 161!

297 0 0 Sp2-sp2_Suzuki_coupling C231412 "QUQJXZGKMPTGAK-UHFFFAOYSA-N"

297 0 1 Corey-House_synthesis_(intermolecular) C283675 "VZGXZFANIISPRR-UHFFFAOYSA-N"

297 0 2 Synthesis_of_organolithium C283677 "NGWGXNVKJTXFCT-UHFFFAOYSA-N"

 Success  registered route 162!

298 0 0 Alpha_alkylation_of_sulphones C255845 "CPWFSKJMEDRRBR-UHFFFAOYSA-N"

 Success  registered route 163!

299 0 0 Corey-House_synthesis_(intermolecular) C256490 "RPDFRSKJKOQCIT-UHFFFAOYSA-N"

 Success  registered route 164!

300 0 0 Sp3-sp2_Macmillan_coupling_with_bromide_(intermolecular) C256517 "QPUYECUOLPXSFR-UHFFFAOYSA-N"

 Success  registered route 165!

302 0 0 Sp2-sp2_Suzuki_coupling C256575 "POSUBGQGUWKMGE-UHFFFAOYSA-N"

302 0 1 Sp3-sp2_Suzuki_coupling C283699 "RIKJWLGFIOPLBT-UHFFFAOYSA-N"

 Success  registered route 166!

303 0 0 Alpha_alkylation_of_aldehyde C257314 "UXHKPKPTEJXYTA-UHFFFAOYSA-N"

303 0 1 Williamson_ether_synthesis C283702 "BCZWEZMYXXZQDC-UHFFFAOYSA-N"

303 0 2 Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide C286437 "QJWWHWZAOURPGD-UHFFFAOYSA-N"

 Success  registered route 167!

308 0 0 Hydrolysis_of_magnesium_alkylthiolate C151891 "AJHJYWCUIVFJRP-UHFFFAOYSA-N"

308 0 1 Synthesis_of_magnesium_alkylthiolate C283706 "YFHYSCCOSJMHFP-UHFFFAOYSA-N"

 Success  registered route 168!

309 0 0 Amidation C99664 "HFLHXSXUCRDIDV-UHFFFAOYSA-N"

 Success  registered route 169!

310 0 0 Amidation C48074 "XDBQWQWEVJPNBV-UHFFFAOYSA-N"

 Success  registered route 170!

311 0 0 Formation_of_urea_from_two_amines C47239 "QZMIVAQLNCUJAN-UHFFFAOYSA-N"

311 0 1 Amine_alkylation C283009 "WHVNYEXBDMPTBF-UHFFFAOYSA-N"

 Success  registered route 171!

312 0 0 Formation_of_urea_from_two_amines C50543 "CXUYUFRBAKGUHD-UHFFFAOYSA-N"

 Success  registered route 172!

313 0 0 Sulfonamide_Schotten-Baumann_with_amine_(intermolecular) C125028 "GKRPCXYDRCZNEJ-UHFFFAOYSA-N"

 Success  registered route 173!

314 0 0 Chan-Lam_coupling_of_amides,_sulfonamides,_and_imides C51269 "NHKSKEKGNRBSQB-UHFFFAOYSA-N"

 Success  registered route 174!

315 0 0 Amidation C118932 "RQGLZHKMFNDMSH-UHFFFAOYSA-N"

 Success  registered route 175!

316 0 0 Amidation C55900 "AUFDHAWKPJKIFW-UHFFFAOYSA-N"

 Success  registered route 176!

317 0 0 Amidation C132547 "KBKFCGYHNXKBGD-UHFFFAOYSA-N"

 Success  registered route 177!

318 0 0 Amidation C53753 "MPUTVVNRSHICME-UHFFFAOYSA-N"

 Success  registered route 178!

319 0 0 Amidation C53845 "IWAUSDKULMXZBG-UHFFFAOYSA-N"

 Success  registered route 179!

320 0 0 Amidation C50771 "DERWPRAMEWIASL-UHFFFAOYSA-N"

 Success  registered route 180!

321 0 0 Amidation C55108 "GCVSXZYUPXGABM-UHFFFAOYSA-N"

 Success  registered route 181!

322 0 0 Amidation C52055 "OOQQOYYILDTRKK-UHFFFAOYSA-N"

 Success  registered route 182!

323 0 0 N-nucleophilic_aromatic_substitution C48060 "SADILTYBWIPMCP-UHFFFAOYSA-N"

 Success  registered route 183!

324 0 0 Amidation C52315 "DRFIGHDMHNBPNI-UHFFFAOYSA-N"

 Success  registered route 184!

325 0 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C46014 "IASQNHULNRESLR-UHFFFAOYSA-N"

 Success  registered route 185!

326 0 0 Amidation C53040 "XDRXTMXRRKPSOB-UHFFFAOYSA-N"

 Success  registered route 186!

327 0 0 Amidation C114736 "PNWBUTYUCZZJJG-UHFFFAOYSA-N"

 Success  registered route 187!

328 0 0 Amidation C47019 "BMJHPSVXCNOHQF-UHFFFAOYSA-N"

 Success  registered route 188!

329 0 0 Chan-Lam_coupling_of_amides,_sulfonamides,_and_imides C96278 "NCVNEKNWZFVLLU-UHFFFAOYSA-N"

 Success  registered route 189!

330 0 0 Amidation C51690 "HIPQRAVJSVNPNW-UHFFFAOYSA-N"

 Success  registered route 190!

331 0 0 Amidation C46618 "VSXISTKWWYBVFB-UHFFFAOYSA-N"

 Success  registered route 191!

332 0 0 Amidation C47002 "RVJZPQWJVCMQJG-UHFFFAOYSA-N"

 Success  registered route 192!

333 0 0 Amidation C75387 "RVAWSFXUAFVMPF-UHFFFAOYSA-N"

 Success  registered route 193!

334 0 0 Formation_of_urea_from_two_amines C106576 "FQWFLXFNFAHVSP-UHFFFAOYSA-N"

 Success  registered route 194!

335 0 0 Amidation C48061 "ACFDSVWQCUCXCX-UHFFFAOYSA-N"

 Success  registered route 195!

336 0 0 Formation_of_urea_from_two_amines C51476 "AKYURMVRRSEXJK-UHFFFAOYSA-N"

337 0 0 Amidation C53713 "RJDKANFIVPITIR-UHFFFAOYSA-N"

 Success  registered route 197!

338 0 0 Amidation C66331 "IHLYYSVXTFTBPP-UHFFFAOYSA-N"

 Success  registered route 198!

339 0 0 Chan-Lam_coupling_(amination) C4093 "OMOCVUPRTIPABZ-UHFFFAOYSA-N"

 Success  registered route 199!

340 0 0 Amidation C13618 "LAWDOCROZLLCBL-UHFFFAOYSA-N"

 Success  registered route 200!

341 0 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C51896 "VPSJRYBKMAUUSC-UHFFFAOYSA-N"

 Success  registered route 201!

342 0 0 Amidation C53762 "UMSVOSGNJDZBKA-UHFFFAOYSA-N"

 Success  registered route 202!

343 0 0 Buchwald-Hartwig_(thio)etherification C77791 "DIUMSFGKZNZUAS-UHFFFAOYSA-N"

 Success  registered route 203!

344 0 0 Amidation C45975 "CEMUYZQUYWHICQ-UHFFFAOYSA-N"

 Success  registered route 204!

345 0 0 Ester_amidation C51448 "COFDIZZNQGQPRY-UHFFFAOYSA-N"

 Success  registered route 205!

346 0 0 Amidation C57322 "AKSNBUPFDFKHMM-UHFFFAOYSA-N"

 Success  registered route 206!

347 0 0 Amidation C61947 "AOQUYKRGVSCMIY-UHFFFAOYSA-N"

 Success  registered route 207!

348 0 0 Amidation C3735 "ZPJZDVARGNTQTH-UHFFFAOYSA-N"

 Success  registered route 208!

349 0 0 Amidation C41201 "PWNWGEJUGNEAPQ-UHFFFAOYSA-N"

 Success  registered route 209!

350 0 0 Ester_amidation C47635 "LAHXOKLNMJHBTG-UHFFFAOYSA-N"

 Success  registered route 210!

351 0 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C45979 "LLUOFVPUDREFGO-UHFFFAOYSA-N"

 Success  registered route 211!

352 0 0 Passerini_reaction C53411 "HLUHSVZNKBAJRE-UHFFFAOYSA-N"

 Success  registered route 212!

353 0 0 Amidation C65382 "MZDGATSJXWUBEN-UHFFFAOYSA-N"

 Success  registered route 213!

354 0 0 Amidation C52108 "AZNSWSRGOHBTSU-UHFFFAOYSA-N"

 Success  registered route 214!

355 0 0 Amidation C48415 "IHYLMDBZOJESMS-UHFFFAOYSA-N"

 Success  registered route 215!

356 0 0 Amidation C48493 "KGOROLBWDGQCPO-UHFFFAOYSA-N"

 Success  registered route 216!

357 0 0 Amidation C51536 "YSKAKYHCRXBUPZ-UHFFFAOYSA-N"

 Success  registered route 217!

358 0 0 Amidation C65392 "VJAJBTQOYAJDPL-UHFFFAOYSA-N"

 Success  registered route 218!

359 0 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C47082 "LUJUPDFZVKGRPH-UHFFFAOYSA-N"

 Success  registered route 219!

360 0 0 TEMPO_oxidation C31470 "GODMAJBOTXASKT-UHFFFAOYSA-N"

 Success  registered route 220!

361 0 0 Van_Leusen_imidazole_synthesis C6296 "UYOZDXASYOYYCF-UHFFFAOYSA-N"

 Success  registered route 221!

362 0 0 Sp2-sp2_Suzuki_coupling C58912 "WYHWZNDJHHPUFV-UHFFFAOYSA-N"

362 0 1 Minisci_reaction_with_carboxylic_acid_(intermolecular) C283762 "ZRYJXFULZYDOAZ-UHFFFAOYSA-N"

 Success  registered route 222!

363 0 0 Amidation C49901 "ARHWMQQRHMNSLN-UHFFFAOYSA-N"

 Success  registered route 223!

364 0 0 Amidation C50940 "GQSJCPRFXMQJKB-UHFFFAOYSA-N"

 Success  registered route 224!

365 0 0 Amidation C50851 "GEFPGABNNYEEAW-UHFFFAOYSA-N"

 Success  registered route 225!

366 0 0 Amidation C16361 "ZZPZYEPSKIPXIU-UHFFFAOYSA-N"

 Success  registered route 226!

367 0 0 Amidation C16361 "ZZPZYEPSKIPXIU-UHFFFAOYSA-N"

 Success  registered route 227!

368 0 0 Amidation C70596 "BQGWDOQDBRNDPW-UHFFFAOYSA-N"

 Success  registered route 228!

369 0 0 Amidation C53777 "VXPPOOOFALPUBZ-UHFFFAOYSA-N"

 Success  registered route 229!

370 0 0 Sulfonamide_Schotten-Baumann_with_amine_(intermolecular) C76574 "TZXZNVJKNDRZQE-UHFFFAOYSA-N"

 Success  registered route 230!

371 0 0 Reductive_amination C45878 "ZSXTWNYTZPYIOF-UHFFFAOYSA-N"

 Success  registered route 231!

372 0 0 Amidation C76291 "HLGWOCDYUXZSIL-UHFFFAOYSA-N"

 Success  registered route 232!

373 0 0 Amidation C79400 "SYIPTBSODVTYNX-UHFFFAOYSA-N"

 Success  registered route 233!

374 0 0 Formation_of_urea_from_two_amines C50246 "AGWJYAALTRFIFA-UHFFFAOYSA-N"

 Success  registered route 234!

375 0 0 Amidation C48099 "CYXFROYLOHDBPB-UHFFFAOYSA-N"

 Success  registered route 235!

376 0 0 Amidation C47038 "QXILYQDWBQFOGE-UHFFFAOYSA-N"

 Success  registered route 236!

377 0 0 Amidation C62872 "QYUCNRDAJOKRPK-UHFFFAOYSA-N"

 Success  registered route 237!

378 0 0 Ester_amidation C38721 "XOTFNADYVUYIDE-UHFFFAOYSA-N"

378 0 1 Amidation C283800 "WFTUUVOQVUBXFC-UHFFFAOYSA-N"

 Success  registered route 238!

379 0 0 Amine_alkylation C46503 "FQPQQAXCJVPZKB-UHFFFAOYSA-N"

 Success  registered route 239!

380 0 0 Buchwald-Hartwig_amination_with_aromatic_nh_intermolecular C58344 "OHHKZZFRRXZMSR-UHFFFAOYSA-N"

 Success  registered route 240!

381 0 0 Petasis-borono_Mannich_reaction C97404 "FZJDHRNIVCAVDC-UHFFFAOYSA-N"

 Success  registered route 241!

382 0 0 Amidation C48528 "GQPALOGPMKZAID-UHFFFAOYSA-N"

 Success  registered route 242!

383 0 0 Amidation C51900 "LDYJYHQEZNWGPU-UHFFFAOYSA-N"

 Success  registered route 243!

384 0 0 Amidation C96113 "KUFKNJXJTDVHJC-UHFFFAOYSA-N"

 Success  registered route 244!

385 0 0 Amidation C118923 "YFAQFICQNGNQSS-UHFFFAOYSA-N"

 Success  registered route 245!

386 0 0 Isocyanate_to_urea C78261 "XPFGRKQWKIHVAC-UHFFFAOYSA-N"

 Success  registered route 246!

387 0 0 Mitsunobu_aryl_ether_synthesis C64717 "SPKYROZOTIZKDR-UHFFFAOYSA-N"

 Success  registered route 247!

388 0 0 Amidation C78532 "DYSLDIFRQOYSOW-UHFFFAOYSA-N"

 Success  registered route 248!

389 0 0 Amidation C43009 "KPTSUQKOCKVBNL-UHFFFAOYSA-N"

 Success  registered route 249!

390 0 0 Formation_of_urea_from_two_amines C45769 "LHENNTRPFOOADT-UHFFFAOYSA-N"

 Success  registered route 250!

391 0 0 Amidation C48114 "DPEGMWUZRPHHNE-UHFFFAOYSA-N"

 Success  registered route 251!

392 0 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C50224 "JWOBBCBWIOGWLH-UHFFFAOYSA-N"

 Success  registered route 252!

393 0 0 Amidation C50761 "FTCITYYSQNDUFP-UHFFFAOYSA-N"

 Success  registered route 253!

394 0 0 Amidation C3682 "QWVLYQDYSGRLDZ-UHFFFAOYSA-N"

 Success  registered route 254!

395 0 0 Amidation C58974 "LHSJJHNLOFSIIV-UHFFFAOYSA-N"

 Success  registered route 255!

396 0 0 Amidation C55828 "CXKCEZSQRXABEZ-UHFFFAOYSA-N"

 Success  registered route 256!

397 0 0 Amine_alkylation C128372 "AEAKCWJGPKNEGI-UHFFFAOYSA-N"

 Success  registered route 257!

398 0 0 Alpha_alkylation_of_ketone C73290 "AAOYCWPUIVHARW-UHFFFAOYSA-N"

 Success  registered route 258!

399 0 0 Hydrogenation_of_pyridine C46480 "PYKGBZNJSJEWFO-UHFFFAOYSA-N"

 Success  registered route 259!

400 0 0 Reductive_amination C47320 "PWXDIHDWBIALIW-UHFFFAOYSA-N"

 Success  registered route 260!

401 0 0 Amidation C67457 "FUQCTTAKZLEMGE-UHFFFAOYSA-N"

 Success  registered route 261!

402 0 0 Amidation C46417 "MXEULFHAOAPIGP-UHFFFAOYSA-N"

 Success  registered route 262!

403 0 0 Amidation C46917 "ZLOLAODFQAPVFD-UHFFFAOYSA-N"

 Success  registered route 263!

404 0 0 Amidation C46631 "ZSCBHMTXZYVXEQ-UHFFFAOYSA-N"

 Success  registered route 264!

405 0 0 Petasis-borono_Mannich_reaction C50844 "KBLKPVYLXZHJGK-UHFFFAOYSA-N"

 Success  registered route 265!

406 0 0 Reductive_amination C68883 "DVJLCXBUKZNXHF-UHFFFAOYSA-N"

 Success  registered route 266!

 Success  registered route 267!

408 0 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C47965 "JCRRANDBLAFJJV-UHFFFAOYSA-N"

 Success  registered route 268!

409 0 0 Amidation C96564 "DANVHOXOMCKSFM-UHFFFAOYSA-N"

 Success  registered route 269!

410 0 0 Amidation C50577 "WQPLYSTUHBUNOX-UHFFFAOYSA-N"

 Success  registered route 270!

411 0 0 Minisci_reaction_with_carboxylic_acid_(intermolecular) C51842 "CVBHTHVPQGKGJL-UHFFFAOYSA-N"

 Success  registered route 271!

412 0 0 Reductive_amination C72837 "LHWDWDRIRYSRET-UHFFFAOYSA-N"

 Success  registered route 272!

413 0 0 N-nucleophilic_aromatic_substitution C59001 "FYTAAIVGKFAKKH-UHFFFAOYSA-N"

 Success  registered route 273!

414 0 0 Amidation C69067 "IOHXAAWNYVLFEF-UHFFFAOYSA-N"

 Success  registered route 274!

415 0 0 Amidation C135020 "HFDOTTQMGPTQDU-UHFFFAOYSA-N"

 Success  registered route 275!

416 0 0 Amidation C60938 "IAFIUIBPUCFPHK-UHFFFAOYSA-N"

 Success  registered route 276!

417 0 0 Formation_of_urea_from_two_amines C53746 "UKXGLWDFUDFURM-UHFFFAOYSA-N"

 Success  registered route 277!

418 0 0 Amidation C46989 "GUZPTPUPXMQGEW-UHFFFAOYSA-N"

 Success  registered route 278!

419 0 0 Amidation C77581 "QMWIEGHYOIRDQB-UHFFFAOYSA-N"

 Success  registered route 279!

420 0 0 Amidation C50934 "QHJYNEFJLIJZEI-UHFFFAOYSA-N"

 Success  registered route 280!

421 0 0 Amidation C134972 "LXFPHGKSVKIPAM-UHFFFAOYSA-N"

 Success  registered route 281!

422 0 0 Amidation C46563 "QTXYAPLSYSHZLH-UHFFFAOYSA-N"

 Success  registered route 282!

423 0 0 Amidation C45675 "UQXXRJNOVZBMSS-UHFFFAOYSA-N"

 Success  registered route 283!

424 0 0 Sp3-sp2_Suzuki_coupling C2648 "ISGNTNSLKCLYPY-UHFFFAOYSA-N"

 Success  registered route 284!

425 0 0 Amidation C45999 "OLVAHZCAPPDKML-UHFFFAOYSA-N"

 Success  registered route 285!

426 0 0 Amidation C46630 "BWJOVYDSIAZYNE-UHFFFAOYSA-N"

 Success  registered route 286!

427 0 0 Amidation C49327 "BJSRYGJAQHXCPG-UHFFFAOYSA-N"

 Success  registered route 287!

428 0 0 Amidation C67150 "FWAPTJLEEQMNPP-UHFFFAOYSA-N"

 Success  registered route 288!

429 0 0 Formation_of_urea_from_two_amines C63643 "LAVJEXPQSPEZFW-UHFFFAOYSA-N"

 Success  registered route 289!

430 0 0 Formation_of_urea_from_two_amines C49166 "QCQBHQXHEXHOGW-UHFFFAOYSA-N"

 Success  registered route 290!

431 0 0 Formation_of_urea_from_two_amines C65117 "WWDQZLGXDWUCRA-UHFFFAOYSA-N"

 Success  registered route 291!

432 0 0 Amidation C46587 "XILXUAMRBXUOIG-UHFFFAOYSA-N"

 Success  registered route 292!

433 0 0 Amidation C13655 "CUEVYSRYKCNYRY-UHFFFAOYSA-N"

 Success  registered route 293!

434 0 0 Amidation C56901 "KULRAFWNQJXNOH-UHFFFAOYSA-N"

 Success  registered route 294!

435 0 0 N-nucleophilic_aromatic_substitution C51495 "GFDFFRLXIZNDDL-UHFFFAOYSA-N"

 Success  registered route 295!

436 0 0 Amidation C102839 "XZIKUBYEVMCBKL-UHFFFAOYSA-N"

 Success  registered route 296!

437 0 0 Amidation C57140 "ZUHBPFRFPPEFBP-UHFFFAOYSA-N"

 Success  registered route 297!

438 0 0 Amidation C40538 "NPOXOZWYVHTEHK-UHFFFAOYSA-N"

 Success  registered route 298!

439 0 0 Amidation C50865 "FSKMWAXPTGYBAB-UHFFFAOYSA-N"

 Success  registered route 299!

440 0 0 Ugi_reaction_split C8079 "BGYVPCNSURXTSF-UHFFFAOYSA-N"

 Success  registered route 300!

441 0 0 Formation_of_sulfonamide_from_halide_-_Shavnya_reaction C51268 "IYQGGEDPMPIKFJ-UHFFFAOYSA-N"

 Success  registered route 301!

442 0 0 N-nucleophilic_aromatic_substitution C48106 "NVVHARBSTPILPF-UHFFFAOYSA-N"

 Success  registered route 302!

443 0 0 Ugi_reaction C98884 "GANHUCHPQYNYPW-UHFFFAOYSA-N"

 Success  registered route 303!

444 0 0 Amidation C53866 "LZSDVVWDNGTYCM-UHFFFAOYSA-N"

 Success  registered route 304!

445 0 0 Amidation C48513 "REJJTMAGDYDVGV-UHFFFAOYSA-N"

 Success  registered route 305!

446 0 0 Amidation C60642 "APTDDJHCLKZSQW-UHFFFAOYSA-N"

 Success  registered route 306!

447 0 0 Amidation C67126 "VBOWZCAKGFDBNA-UHFFFAOYSA-N"

 Success  registered route 307!

448 0 0 Amidation C28111 "XCWVUVAVUJWFCW-UHFFFAOYSA-N"

 Success  registered route 308!

449 0 0 Amidation C97354 "XFJSHQDMGLUATN-UHFFFAOYSA-N"

 Success  registered route 309!

450 0 0 Amidation C49991 "XMBXZMQOVGUTTG-UHFFFAOYSA-N"

 Success  registered route 310!

451 0 0 Amidation C48546 "QNLCPYNLKHRGGT-UHFFFAOYSA-N"

 Success  registered route 311!

452 0 0 Amidation C46492 "DPROWOJPCAHSLR-UHFFFAOYSA-N"

 Success  registered route 312!

453 0 0 Formation_of_urea_from_two_amines C46960 "HZQGVMFRCXKOBL-UHFFFAOYSA-N"

 Success  registered route 313!

454 0 0 Formation_of_urea_from_two_amines C48055 "NBCOLWIEDFDBPP-UHFFFAOYSA-N"

 Success  registered route 314!

455 0 0 Formation_of_urea_from_two_amines C48630 "ATBDAIGFBNCITP-UHFFFAOYSA-N"

 Success  registered route 315!

456 0 0 Amidation C41168 "RBXTZVLYSUIEGL-UHFFFAOYSA-N"

 Success  registered route 316!

457 0 0 Amidation C48056 "SXJFQBSZDASCMN-UHFFFAOYSA-N"

 Success  registered route 317!

458 0 0 Amidation C119620 "VYESCFQDWYETRW-UHFFFAOYSA-N"

 Success  registered route 318!

459 0 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C119723 "BUFNXCVHZNVGON-UHFFFAOYSA-N"

 Success  registered route 319!

460 0 0 Isocyanate_to_urea C66135 "HVAHNKDDJIROCW-UHFFFAOYSA-N"

 Success  registered route 320!

461 0 0 Pinner_reaction_(carboxylate_ester) C120944 "TVIVKSZHVBUWMY-UHFFFAOYSA-N"

 Success  registered route 321!

462 0 0 Ester_amidation C64811 "CFGXRPXLHNPYEB-UHFFFAOYSA-N"

 Success  registered route 322!

463 0 0 Petasis-borono_Mannich_reaction C52416 "CTFJRCJMDOHUDJ-UHFFFAOYSA-N"

 Success  registered route 323!

464 0 0 Amine_alkylation C52375 "PBWKBAOPCODYPW-UHFFFAOYSA-N"

 Success  registered route 324!

465 0 0 Amidation C104894 "RBNSWXUVCCJWGP-UHFFFAOYSA-N"

 Success  registered route 325!

466 0 0 Amidation C53750 "UDHNRVXHVXPDPQ-UHFFFAOYSA-N"

 Success  registered route 326!

467 0 0 Formation_of_sulfonamide_from_halide_-_Shavnya_reaction C52408 "QGEQCOIPUBEYKU-UHFFFAOYSA-N"

 Success  registered route 327!

468 0 0 Iodo_N-arylation C53625 "MRFSLWKYICIDAF-UHFFFAOYSA-N"

 Success  registered route 328!

469 0 0 Amidation C3809 "RPRHXEYBWVZIEC-UHFFFAOYSA-N"

 Success  registered route 329!

470 0 0 Amidation C48539 "CKCILQQJPFHCBG-UHFFFAOYSA-N"

 Success  registered route 330!

471 0 0 Amine_alkylation C51256 "DRJGGQZLWYEHNT-UHFFFAOYSA-N"

 Success  registered route 331!

472 0 0 Steglich_esterification C104497 "GNAHZGVSELLNGY-UHFFFAOYSA-N"

 Success  registered route 332!

473 0 0 Steglich_esterification C47021 "XBCUCSHTTYKLFQ-UHFFFAOYSA-N"

 Success  registered route 333!

474 0 0 Amidation C48652 "GOZNAOOIESXJOY-UHFFFAOYSA-N"

 Success  registered route 334!

475 0 0 Amidation C49171 "KQQACZGRTAQEIS-UHFFFAOYSA-N"

 Success  registered route 335!

476 0 0 Amidation C59004 "KUBMOMKAUGJXEF-UHFFFAOYSA-N"

 Success  registered route 336!

477 0 0 Amidation C7211 "MZJBBXTUYNVWJM-UHFFFAOYSA-N"

 Success  registered route 337!

478 0 0 N-nucleophilic_aromatic_substitution C27143 "HMQRCRGWWKHSOQ-UHFFFAOYSA-N"

 Success  registered route 338!

479 0 0 Amidation C122137 "CDHYUFIFKQHMBX-UHFFFAOYSA-N"

 Success  registered route 339!

480 0 0 Amidation C75326 "DXYSIYGLUVEQHU-UHFFFAOYSA-N"

 Success  registered route 340!

481 0 0 Amidation C74188 "LPMIQRKPJGOMRG-UHFFFAOYSA-N"

 Success  registered route 341!

482 0 0 Nucleophilic_substitution_with_thiol C55819 "VHVSAXROEBTQDV-UHFFFAOYSA-N"

 Success  registered route 342!

483 0 0 Amidation C65008 "HKLVJOPELRROKJ-UHFFFAOYSA-N"

 Success  registered route 343!

484 0 0 Amidation C14132 "YPDKDGPFUNQBCH-UHFFFAOYSA-N"

 Success  registered route 344!

485 0 0 Formation_of_urea_from_two_amines C106545 "XFLRGLNKSUBAIU-UHFFFAOYSA-N"

 Success  registered route 345!

486 0 0 Amidation C50569 "RILULXWKHGGBSE-UHFFFAOYSA-N"

 Success  registered route 346!

487 0 0 Amidation C124015 "XIOYKRXGPYNPFZ-UHFFFAOYSA-N"

 Success  registered route 347!

488 0 0 Reductive_amination C42918 "LTOUESXDKSJFOU-UHFFFAOYSA-N"

 Success  registered route 348!

489 0 0 Amidation C49748 "YZQNRVOHGUHPKI-UHFFFAOYSA-N"

 Success  registered route 349!

490 0 0 Formation_of_urea_from_two_amines C52583 "DLHJBIDRLSJSTJ-UHFFFAOYSA-N"

 Success  registered route 350!

491 0 0 Amine_alkylation C58943 "RVENREFGGYUNIA-UHFFFAOYSA-N"

492 0 0 Amine_alkylation C46025 "BVLLTLFJWFLOHJ-UHFFFAOYSA-N"

 Success  registered route 352!

493 0 0 Amidation C55754 "GMCQQOLNFQNWLY-UHFFFAOYSA-N"

 Success  registered route 353!

494 0 0 Amine_alkylation C56319 "HWMWQVREGFTJLC-UHFFFAOYSA-N"

 Success  registered route 354!

495 0 0 Amidation C49767 "MDKJRJCQKQXIAA-UHFFFAOYSA-N"

 Success  registered route 355!

496 0 0 Amidation C54984 "IYBHUXYKLJVDAB-UHFFFAOYSA-N"

 Success  registered route 356!

497 0 0 Formation_of_urea_from_two_amines C47045 "YCRGSBIGVVKPPN-UHFFFAOYSA-N"

 Success  registered route 357!

498 0 0 Amidation C50555 "GTAWTVGQTNAEFZ-UHFFFAOYSA-N"

 Success  registered route 358!

499 0 0 Amidation C57585 "LHYZZOLVXFMPSN-UHFFFAOYSA-N"

 Success  registered route 359!

500 0 0 Amidation C124666 "YPQHHFKDRTWIRH-UHFFFAOYSA-N"

 Success  registered route 360!

501 0 0 Amidation C45922 "SPNZKICKJJLOLD-UHFFFAOYSA-N"

 Success  registered route 361!

502 0 0 Formation_of_urea_from_two_amines C124674 "ARLQJSHPRHVDLE-UHFFFAOYSA-N"

 Success  registered route 362!

503 0 0 Amidation C124752 "YPSWQHNOQUDWBB-UHFFFAOYSA-N"

 Success  registered route 363!

504 0 0 Formation_of_urea_from_two_amines C46519 "PCOYOLXCWOQMAP-UHFFFAOYSA-N"

 Success  registered route 364!

505 0 0 Formation_of_urea_from_two_amines C46525 "KACSHWFKVMPBNN-UHFFFAOYSA-N"

 Success  registered route 365!

506 0 0 Ester_amidation C53709 "AEYMWTWOISXUPC-UHFFFAOYSA-N"

 Success  registered route 366!

507 0 0 Amidation C125044 "GXFRUHCYWOLZOD-UHFFFAOYSA-N"

 Success  registered route 367!

508 0 0 Amidation C39918 "FLOGMMPAFYOKFI-UHFFFAOYSA-N"

 Success  registered route 368!

509 0 0 Amine_alkylation C56328 "DWFKNXQXPRRFIK-UHFFFAOYSA-N"

 Success  registered route 369!

510 0 0 Nucleophilic_substitution_with_thiol C45746 "INIOVHDPBHGSSA-UHFFFAOYSA-N"

 Success  registered route 370!

511 0 0 Formation_of_sulfonamide_from_halide_-_Shavnya_reaction C52406 "SPHUOMUWTFJILN-UHFFFAOYSA-N"

 Success  registered route 371!

512 0 0 Nucleophilic_substitution_with_thiol C45737 "BYVLLCRZBAXVSG-UHFFFAOYSA-N"

 Success  registered route 372!

513 0 0 Chan-Lam_coupling_(amination) C63895 "WJNGKPOBVKGESA-UHFFFAOYSA-N"

 Success  registered route 373!

514 0 0 Isocyanate_to_urea C49222 "YTMNIWJWKYPQRC-UHFFFAOYSA-N"

 Success  registered route 374!

515 0 0 Amidation C124652 "HKXZWNGJYYWBSS-UHFFFAOYSA-N"

 Success  registered route 375!

516 0 0 N-Boc_deprotection C2619 "IKNFMHZKPYNCLN-UHFFFAOYSA-N"

 Success  registered route 376!

517 0 0 Amine_alkylation C46024 "GCNBWOGZRKAZBP-UHFFFAOYSA-N"

 Success  registered route 377!

518 0 0 Amidation C49904 "GEQKRUDQJJRSJX-UHFFFAOYSA-N"

 Success  registered route 378!

519 0 0 Amine_alkylation C65365 "KEVJLIOFDCEABV-UHFFFAOYSA-N"

 Success  registered route 379!

520 0 0 Amidation C47091 "FBFBYAKCUCMEEP-UHFFFAOYSA-N"

 Success  registered route 380!

521 0 0 Amidation C16352 "OUQAMUZFPAKLSU-UHFFFAOYSA-N"

 Success  registered route 381!

522 0 0 Amine_alkylation C46353 "RUAMWEYLOLJYGA-UHFFFAOYSA-N"

 Success  registered route 382!

523 0 0 Amidation C48069 "NZLKTHSNCGTXSD-UHFFFAOYSA-N"

 Success  registered route 383!

524 0 0 Amidation C54393 "RQFUKMGDFNPBCK-UHFFFAOYSA-N"

 Success  registered route 384!

525 0 0 Amidation C62954 "AKDZJBVQXJPRAV-UHFFFAOYSA-N"

 Success  registered route 385!

526 0 0 Amidation C62780 "ACNOULRBXOAPRM-UHFFFAOYSA-N"

 Success  registered route 386!

527 0 0 Ester_amidation C47626 "TVPOKXROJNSOOF-UHFFFAOYSA-N"

 Success  registered route 387!

528 0 0 Sulfonamide_Schotten-Baumann_with_amine_(intermolecular) C60696 "PBRDYGOIOPNLNB-UHFFFAOYSA-N"

 Success  registered route 388!

529 0 0 Amidation C48075 "FLFOERJJQTUYPD-UHFFFAOYSA-N"

 Success  registered route 389!

530 0 0 N-nucleophilic_aromatic_substitution C53748 "NVPORXZYZSHULI-UHFFFAOYSA-N"

 Success  registered route 390!

531 0 0 Reductive_amination C54541 "HGBPIRBOCLLQLU-UHFFFAOYSA-N"

 Success  registered route 391!

532 0 0 Alpha_alkylation_of_aldehyde C50895 "KXNWFIJPGUQQKJ-UHFFFAOYSA-N"

532 0 1 Appel_iodination C284127 "TYAKPATXGZHZAJ-UHFFFAOYSA-N"

 Success  registered route 392!

533 0 0 Formation_of_urea_from_two_amines C69436 "YQYGMTNHNASFKA-UHFFFAOYSA-N"

 Success  registered route 393!

534 0 0 Formation_of_urea_from_two_amines C46719 "SZOSSGYASKCMRR-UHFFFAOYSA-N"

 Success  registered route 394!

535 0 0 Sp3-sp2_Suzuki_coupling C7530 "KLDGENGYOLDCCH-UHFFFAOYSA-N"

 Success  registered route 395!

536 0 0 Amidation C9170 "UQSQEAQGOCUNCL-UHFFFAOYSA-N"

 Success  registered route 396!

537 0 0 Amidation C72020 "CPYSPBMOERNONI-UHFFFAOYSA-N"

 Success  registered route 397!

538 0 0 Amidation C76437 "JGPKGUGWSKQTMA-UHFFFAOYSA-N"

 Success  registered route 398!

539 0 0 Amine_alkylation C9559 "BERWHPCSSUZEII-UHFFFAOYSA-N"

 Success  registered route 399!

540 0 0 Steglich_esterification C45718 "BRPFDWXEIDBRLV-UHFFFAOYSA-N"

 Success  registered route 400!

541 0 0 Amine_alkylation C50994 "WQRDHQBSZVIGIO-UHFFFAOYSA-N"

 Success  registered route 401!

542 0 0 Amidation C55674 "OGJPIWQWEMAAMH-UHFFFAOYSA-N"

 Success  registered route 402!

543 0 0 Amidation C76407 "ROHRNSVGYBRSRF-UHFFFAOYSA-N"

 Success  registered route 403!

544 0 0 Amidation C59983 "XOUMUYAEIAMCIP-UHFFFAOYSA-N"

 Success  registered route 404!

545 0 0 Imidazole_C-2_alkylation C46656 "AMVABLYBMIDGRH-UHFFFAOYSA-N"

 Success  registered route 405!

546 0 0 Formation_of_urea_from_two_amines C50998 "WKBRMGXSMGHJIB-UHFFFAOYSA-N"

 Success  registered route 406!

547 0 0 Amidation C78609 "VRSHMDURHCTYSQ-UHFFFAOYSA-N"

 Success  registered route 407!

548 0 0 1,2,4-Oxadiazole_synthesis_(amidoxime_+_carboxylate) C46489 "SZIVMHZNNDPTLC-UHFFFAOYSA-N"

 Success  registered route 408!

549 0 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C47143 "FGSGQPZOSTVLEH-UHFFFAOYSA-N"

 Success  registered route 409!

550 0 0 Amidation C52296 "GKINGEPBNWSYJT-UHFFFAOYSA-N"

 Success  registered route 410!

551 0 0 Nucleophilic_substitution_with_thiol C45760 "YZUDVCSNWGWELH-UHFFFAOYSA-N"

 Success  registered route 411!

552 0 0 Formation_of_sulfonamide_from_halide_-_Shavnya_reaction C51171 "SBSIUJKZMODQOZ-UHFFFAOYSA-N"

 Success  registered route 412!

553 0 0 N-nucleophilic_aromatic_substitution C17161 "VJYRZHQTAWWYSA-UHFFFAOYSA-N"

 Success  registered route 413!

554 0 0 S-nucleophilic_aromatic_substitution C45943 "NAKUARJYTXIAKL-UHFFFAOYSA-N"

 Success  registered route 414!

555 0 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C95588 "HVSNCLWSDCNDJH-UHFFFAOYSA-N"

 Success  registered route 415!

556 0 0 Amidation C65555 "YJLJMKADNGNFEP-UHFFFAOYSA-N"

 Success  registered route 416!

557 0 0 Amidation C53759 "XUNSVHLTAIMYCN-UHFFFAOYSA-N"

 Success  registered route 417!

558 0 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C47450 "MSQPPJKTFQIHMR-UHFFFAOYSA-N"

 Success  registered route 418!

559 0 0 Amidation C72495 "QFWXRMWUAHTJTN-UHFFFAOYSA-N"

 Success  registered route 419!

560 0 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C52333 "KEJHVZLIZINKME-UHFFFAOYSA-N"

 Success  registered route 420!

561 0 0 Amidation C50277 "GSWNPYWEZMISHZ-UHFFFAOYSA-N"

 Success  registered route 421!

562 0 0 Amidation C28114 "IUKQROOWIYQEAX-UHFFFAOYSA-N"

 Success  registered route 422!

563 0 0 Amidation C45749 "CFQKQNUEMBXROS-UHFFFAOYSA-N"

 Success  registered route 423!

564 0 0 Buchwald-Hartwig_amination C45909 "DMMWSHAZVFYQCP-UHFFFAOYSA-N"

 Success  registered route 424!

565 0 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C46644 "ZMLNPERFMPNMTQ-UHFFFAOYSA-N"

 Success  registered route 425!

566 0 0 Amidation C50954 "BLIHSGRIXMRDOE-UHFFFAOYSA-N"

 Success  registered route 426!

567 0 0 Amidation C55684 "XPJXWZTUMKSLEF-UHFFFAOYSA-N"

 Success  registered route 427!

568 0 0 Amidation C50179 "JRWNVUPFKXEMMQ-UHFFFAOYSA-N"

 Success  registered route 428!

569 0 0 Reductive_amination C98152 "VZPBIZGIEVBAAL-UHFFFAOYSA-N"

 Success  registered route 429!

570 0 0 Amidation C47396 "YLTDZWFXEQMEQY-UHFFFAOYSA-N"

 Success  registered route 430!

571 0 0 Amidation C50784 "OZOCKCQNPSVVFB-UHFFFAOYSA-N"

 Success  registered route 431!

572 0 0 Amidation C46779 "JJWFKWAOMFMQRZ-UHFFFAOYSA-N"

 Success  registered route 432!

573 0 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C55076 "OHXVFTFJECSKFY-UHFFFAOYSA-N"

 Success  registered route 433!

574 0 0 Amidation C16370 "ABUSFKREGHFGSP-UHFFFAOYSA-N"

 Success  registered route 434!

575 0 0 Formation_of_urea_from_two_amines C46399 "NZLDTOKBIBVWEI-UHFFFAOYSA-N"

 Success  registered route 435!

576 0 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C53771 "TWONAIHJDMPRBM-UHFFFAOYSA-N"

 Success  registered route 436!

577 0 0 Amine_alkylation C47934 "AVYIYQMLMSVDAX-UHFFFAOYSA-N"

 Success  registered route 437!

578 0 0 Amidation C81434 "NHFWFEZEXIIBII-UHFFFAOYSA-N"

 Success  registered route 438!

579 0 0 Amidation C45810 "AWLHCXVUPILPTN-UHFFFAOYSA-N"

 Success  registered route 439!

580 0 0 Steglich_esterification C35473 "PLOYGMMNBYFGSF-UHFFFAOYSA-N"

 Success  registered route 440!

581 0 0 Amidation C101781 "ASBBGKVVIBZBJN-UHFFFAOYSA-N"

 Success  registered route 441!

582 0 0 Amine_alkylation C46470 "NEWYPLQNQDROOI-UHFFFAOYSA-N"

 Success  registered route 442!

583 0 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C47013 "FRZNABRJHVHFJE-UHFFFAOYSA-N"

 Success  registered route 443!

584 0 0 Alpha_alkylation_of_ester/amide C56915 "OTMGIRLBTFICTQ-UHFFFAOYSA-N"

 Success  registered route 444!

585 0 0 Amidation C40498 "NYRUPEKHZSORRF-UHFFFAOYSA-N"

 Success  registered route 445!

586 0 0 N-nucleophilic_aromatic_substitution C35439 "BAUHVGNDLBNYPF-UHFFFAOYSA-N"

 Success  registered route 446!

587 0 0 Amidation C26549 "QEUQYOFEBBDDHZ-UHFFFAOYSA-N"

 Success  registered route 447!

588 0 0 Reductive_amination C102808 "MZJWMOJDYRPWCV-UHFFFAOYSA-N"

 Success  registered route 448!

589 0 0 Amidation C51493 "PQANNCWYAKKWKR-UHFFFAOYSA-N"

 Success  registered route 449!

590 0 0 Formation_of_urea_from_two_amines C55892 "WDXPCDIQYNQRBP-UHFFFAOYSA-N"

 Success  registered route 450!

591 0 0 Amidation C46065 "WTVLMOGGYBHAKC-UHFFFAOYSA-N"

 Success  registered route 451!

592 0 0 Sulfonamide_Schotten-Baumann_with_amine_(intermolecular) C45987 "YTXBRSZQZDSVHR-UHFFFAOYSA-N"

 Success  registered route 452!

593 0 0 Amidation C51490 "MJMCOCNIQIOMAD-UHFFFAOYSA-N"

 Success  registered route 453!

594 0 0 Amidation C35612 "QUWCTZUWOPCIPH-UHFFFAOYSA-N"

 Success  registered route 454!

595 0 0 Amidation C21631 "AERCOVUKSAMYCJ-UHFFFAOYSA-N"

 Success  registered route 455!

596 0 0 Buchwald-Hartwig_amination C46544 "QFIAQCXWMHUYLP-UHFFFAOYSA-N"

 Success  registered route 456!

597 0 0 Amidation C54511 "AGNKHDPFSMAPGP-UHFFFAOYSA-N"

 Success  registered route 457!

598 0 0 Amidation C46596 "IGUBAEGLTUZHCE-UHFFFAOYSA-N"

 Success  registered route 458!

599 0 0 Amidation C99297 "UAGGKQWASMNBKS-UHFFFAOYSA-N"

 Success  registered route 459!

600 0 0 Amidation C79153 "ISLLNGYBDHENHK-UHFFFAOYSA-N"

 Success  registered route 460!

601 0 0 Formation_of_urea_from_two_amines C47020 "GXDXQSSPAOBTRI-UHFFFAOYSA-N"

 Success  registered route 461!

602 0 0 Amidation C54609 "YTDDXKFXAHOBOJ-UHFFFAOYSA-N"

 Success  registered route 462!

603 0 0 Amidation C46745 "CGTYQSSIZNKAKB-UHFFFAOYSA-N"

 Success  registered route 463!

604 0 0 Sp2-sp2_Suzuki_coupling C48173 "IHQQJGYNMPUAJX-UHFFFAOYSA-N"

 Success  registered route 464!

605 0 0 Amidation C50765 "STCJHBJZJQTPAK-UHFFFAOYSA-N"

 Success  registered route 465!

606 0 0 Amidation C45621 "FJYQDPPMQZVULE-UHFFFAOYSA-N"

 Success  registered route 466!

607 0 0 Amidation C73035 "BZZOYINXFCNSHF-UHFFFAOYSA-N"

 Success  registered route 467!

608 0 0 Sp3-sp2_Suzuki_coupling C48047 "BRBPGGIIQVBPSB-UHFFFAOYSA-N"

 Success  registered route 468!

609 0 0 Amidation C45868 "GUNFXNUZCJVVCQ-UHFFFAOYSA-N"

 Success  registered route 469!

610 0 0 Amidation C45401 "IYSNRKWEWIPQJO-UHFFFAOYSA-N"

 Success  registered route 470!

611 0 0 Alpha_alkylation_of_aldehyde C53933 "QATXJWMNVCBKJS-UHFFFAOYSA-N"

 Success  registered route 471!

612 0 0 Formation_of_urea_from_two_amines C71025 "GDWHZKUVFYWLOX-UHFFFAOYSA-N"

 Success  registered route 472!

613 0 0 Sp3-sp2_Suzuki_coupling C47050 "UUXRWAXHJKIKLF-UHFFFAOYSA-N"

613 0 1 Sulfonic_ester_Schotten-Baumann C284268 "IBXPKBWNMKBGJO-UHFFFAOYSA-N"

 Success  registered route 473!

614 0 0 1,2,4-Oxadiazole_synthesis_(amidoxime_+_carboxylate) C53958 "WCIIHXGCHJLLNO-UHFFFAOYSA-N"

 Success  registered route 474!

615 0 0 Amidation C56036 "RNMKDQJFKQUPLR-UHFFFAOYSA-N"

 Success  registered route 475!

616 0 0 Amidation C46686 "QYLPLGFXGKSQBO-UHFFFAOYSA-N"

617 0 0 Amidation C48529 "ADNXPKLKFSZSFL-UHFFFAOYSA-N"

 Success  registered route 477!

618 0 0 Formation_of_urea_from_two_amines C63712 "USNXQARUIFIATO-UHFFFAOYSA-N"

 Success  registered route 478!

619 0 0 Formation_of_urea_from_two_amines C70623 "XYEZCRBOLJWWSO-UHFFFAOYSA-N"

 Success  registered route 479!

620 0 0 Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide C97238 "INEPPSBQJWJDAN-UHFFFAOYSA-N"

 Success  registered route 480!

621 0 0 Formation_of_urea_from_two_amines C46913 "UDUDCRVNWVAVQA-UHFFFAOYSA-N"

 Success  registered route 481!

622 0 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C50199 "DRFSJOZQKRDYMQ-UHFFFAOYSA-N"

 Success  registered route 482!

623 0 0 Formation_of_urea_from_two_amines C46715 "DIRAOWPNSMQXKI-UHFFFAOYSA-N"

 Success  registered route 483!

624 0 0 Steglich_esterification C48752 "UKZBPLZISFOGHM-UHFFFAOYSA-N"

 Success  registered route 484!

625 0 0 Amidation C75046 "SBHQGIHIWSVJJD-UHFFFAOYSA-N"

 Success  registered route 485!

626 0 0 Amidation C75041 "CIXBAERDBPDAKY-UHFFFAOYSA-N"

 Success  registered route 486!

627 0 0 Amidation C32955 "FIQGWCSDZCNMCO-UHFFFAOYSA-N"

 Success  registered route 487!

628 0 0 Amidation C74534 "RVXODQUPALHEDR-UHFFFAOYSA-N"

 Success  registered route 488!

629 0 0 Formation_of_urea_from_two_amines C47226 "DLCSXKSRGUYCLO-UHFFFAOYSA-N"

629 0 1 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C284304 "NDNGDKGIWXANSY-UHFFFAOYSA-N"

 Success  registered route 489!

630 0 0 Amidation C22252 "IBDCOPOSACUADV-UHFFFAOYSA-N"

 Success  registered route 490!

631 0 0 Formation_of_sulfonamide_from_halide_-_Shavnya_reaction C51172 "GBIVHNMPUDCSBY-UHFFFAOYSA-N"

 Success  registered route 491!

632 0 0 Minisci_reaction_with_carboxylic_acid_(intermolecular) C54009 "XTXBBFCZAMJCJV-UHFFFAOYSA-N"

 Success  registered route 492!

633 0 0 Amidation C116664 "BESYEBIXTNPBCZ-UHFFFAOYSA-N"

 Success  registered route 493!

634 0 0 Amidation C68683 "IZLSOQIKOWDXOQ-UHFFFAOYSA-N"

 Success  registered route 494!

635 0 0 Amidation C50927 "ABTJDCJBWSBSRN-UHFFFAOYSA-N"

 Success  registered route 495!

636 0 0 Amidation C47059 "HZAWDDKMHSREJD-UHFFFAOYSA-N"

 Success  registered route 496!

637 0 0 Formation_of_sulfonamide_from_boronic_and_amine C72578 "SXFYONIWVSYCIM-UHFFFAOYSA-N"

 Success  registered route 497!

638 0 0 Amidation C50560 "ZSWDRRMBFQDNKX-UHFFFAOYSA-N"

 Success  registered route 498!

639 0 0 Amidation C69028 "YKKKROMSHYNZCM-UHFFFAOYSA-N"

 Success  registered route 499!

 Success  registered route 500!

641 0 0 N-Boc_deprotection C3758 "JNOYHGAZDBVHEM-UHFFFAOYSA-N"

 Success  registered route 501!

642 0 0 N-nucleophilic_aromatic_substitution C119126 "ILSBGNWDUMTPAG-UHFFFAOYSA-N"

 Success  registered route 502!

643 0 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C59009 "OHLKROUFFQSMCC-UHFFFAOYSA-N"

 Success  registered route 503!

644 0 0 Amidation C99744 "GYQUKRQTKVBWNS-UHFFFAOYSA-N"

 Success  registered route 504!

645 0 0 Amidation C50959 "YMLRBUYADBIVPV-UHFFFAOYSA-N"

 Success  registered route 505!

646 0 0 Amidation C45686 "OJGYGWNQLWVYCV-UHFFFAOYSA-N"

 Success  registered route 506!

647 0 0 Alpha_alkylation_of_ester/amide C46510 "YFUCQHARYKGGDT-UHFFFAOYSA-N"

 Success  registered route 507!

648 0 0 Amidation C17664 "ACSYWMFGDGOESG-UHFFFAOYSA-N"

 Success  registered route 508!

649 0 0 Amidation C18489 "VFKNZSCHZMQTED-UHFFFAOYSA-N"

 Success  registered route 509!

650 0 0 Amidation C46019 "SWXAVEIWNZULFS-UHFFFAOYSA-N"

 Success  registered route 510!

651 0 0 Amidation C46081 "CMXCFLAPBZHWHG-UHFFFAOYSA-N"

 Success  registered route 511!

652 0 0 Amidation C48684 "PRAKSTQMHOCJPE-UHFFFAOYSA-N"

 Success  registered route 512!

653 0 0 Stille_coupling C49548 "USFYQCKGTJDZSY-UHFFFAOYSA-N"

 Success  registered route 513!

654 0 0 Amidation C45698 "AZXXRKXZDHOYLM-UHFFFAOYSA-N"

 Success  registered route 514!

655 0 0 Formation_of_urea_from_two_amines C48641 "HWVWLXJFARWMTE-UHFFFAOYSA-N"

 Success  registered route 515!

656 0 0 Amidation C54290 "HQGYPUCPEKYMFA-UHFFFAOYSA-N"

 Success  registered route 516!

657 0 0 Amine_alkylation C46545 "NFJAZBLUEKNGGI-UHFFFAOYSA-N"

 Success  registered route 517!

658 0 0 Ester_amidation C45947 "IIPXDYCSPRLGJU-UHFFFAOYSA-N"

 Success  registered route 518!

659 0 0 Reductive_amination C46327 "UEVJLQLOPDVOAR-UHFFFAOYSA-N"

 Success  registered route 519!

660 0 0 Amidation C97204 "FNHYNFVWJDXWDE-UHFFFAOYSA-N"

 Success  registered route 520!

661 0 0 Amidation C49818 "OLDSNDJYHCNLFD-UHFFFAOYSA-N"

 Success  registered route 521!

662 0 0 Amidation C9529 "PEDGVMFOGXYVTC-UHFFFAOYSA-N"

 Success  registered route 522!

663 0 0 Ester_amidation C59022 "BFNJPRDSFVMZDA-UHFFFAOYSA-N"

 Success  registered route 523!

664 0 0 Amine_alkylation C48646 "LKENARBUOFSVNC-UHFFFAOYSA-N"

 Success  registered route 524!

665 0 0 Amidation C80825 "AQAKSQZHWPPYOI-UHFFFAOYSA-N"

 Success  registered route 525!

666 0 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C47453 "DIPNTWZPFZFZLY-UHFFFAOYSA-N"

 Success  registered route 526!

667 0 0 Amidation C105126 "JJKPNZIAVNEQFY-UHFFFAOYSA-N"

 Success  registered route 527!

668 0 0 Amidation C55396 "XQFDTTICYWSLGR-UHFFFAOYSA-N"

 Success  registered route 528!

669 0 0 Sulfonamide_Schotten-Baumann_with_amine_(intermolecular) C72721 "LYKXFHHASTVORN-UHFFFAOYSA-N"

 Success  registered route 529!

670 0 0 Buchwald-Hartwig_amination C45903 "QGVOJAWYYQCOKY-UHFFFAOYSA-N"

 Success  registered route 530!

671 0 0 Amidation C45756 "VOCNZKAZPJNZLB-UHFFFAOYSA-N"

 Success  registered route 531!

672 0 0 Amidation C129526 "JRIXZBVWMSAORN-UHFFFAOYSA-N"

 Success  registered route 532!

673 0 0 Amidation C129593 "KRFRNBXJSXYDDU-UHFFFAOYSA-N"

 Success  registered route 533!

674 0 0 Amine_alkylation C69074 "UJUZDCBLGJJXRQ-UHFFFAOYSA-N"

 Success  registered route 534!

675 0 0 Buchwald-Hartwig_(thio)etherification C51875 "UZTGHTCNTUSHGZ-UHFFFAOYSA-N"

 Success  registered route 535!

676 0 0 Amidation C74411 "BPSGCGHAXUTQSM-UHFFFAOYSA-N"

 Success  registered route 536!

677 0 0 N-nucleophilic_aromatic_substitution C50762 "OGTRECUNLRMNFU-UHFFFAOYSA-N"

 Success  registered route 537!

678 0 0 Amidation C66538 "ZIEZQKTWDSPKJB-UHFFFAOYSA-N"

 Success  registered route 538!

679 0 0 N-nucleophilic_aromatic_substitution C50711 "BVUAKSYIXAEYKA-UHFFFAOYSA-N"

 Success  registered route 539!

680 0 0 Reductive_amination C47371 "BYIBJOZHQLWVOG-UHFFFAOYSA-N"

 Success  registered route 540!

681 0 0 Amidation C75048 "DBYAVWKCAUZJRJ-UHFFFAOYSA-N"

 Success  registered route 541!

682 0 0 Amidation C51543 "DRKHZHCOCRWYTL-UHFFFAOYSA-N"

 Warning  SMILES changed during compound registration: c1cc(C2CCNCC2)[nH]n1 --> c1cc(C2CCNCC2)n[nH]1!

 Success  registered route 542!

683 0 0 Amidation C69262 "SOJMYQQECXDIRN-UHFFFAOYSA-N"

 Success  registered route 543!

684 0 0 Amidation C87625 "FUASHUQWJFTJQN-UHFFFAOYSA-N"

 Success  registered route 544!

685 0 0 Amidation C64592 "VAGNKVBSAUXXJB-UHFFFAOYSA-N"

 Success  registered route 545!

686 0 0 1,2,4-Oxadiazole_synthesis_(nitrile_+_carboxylic_acid) C29898 "BGICKWFMKMWXKW-UHFFFAOYSA-N"

 Success  registered route 546!

687 0 0 Amidation C107313 "RZWXIWQSDZYYOP-UHFFFAOYSA-N"

 Success  registered route 547!

688 0 0 Amine_alkylation C46497 "NHTIISPGTDJACN-UHFFFAOYSA-N"

 Success  registered route 548!

689 0 0 Amidation C45845 "MLATWPCEIWLAON-UHFFFAOYSA-N"

 Success  registered route 549!

690 0 0 Formation_of_urea_from_two_amines C45801 "FFOQKKOHSFRDDO-UHFFFAOYSA-N"

 Success  registered route 550!

691 0 0 Amidation C70091 "WCZFMVGDBUJSBO-UHFFFAOYSA-N"

 Success  registered route 551!

692 0 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C102932 "YBCNZGDJWJHKOC-UHFFFAOYSA-N"

 Success  registered route 552!

693 0 0 Amidation C48665 "CLFZGCHMMMECHQ-UHFFFAOYSA-N"

 Success  registered route 553!

694 0 0 Ugi_reaction C2016 "DPASSUYVTHZQDV-UHFFFAOYSA-N"

 Success  registered route 554!

695 0 0 Sp2-sp2_Suzuki_coupling C5573 "IIGFTWKBMUCFTB-UHFFFAOYSA-N"

 Success  registered route 555!

696 0 0 Amidation C65430 "DJBDVHCYEQULCD-UHFFFAOYSA-N"

 Warning  SMILES changed during compound registration: CC(NC(=O)c1cc[nH]n1)C1CNC1 --> CC(NC(=O)c1ccn[nH]1)C1CNC1!

 Success  registered route 556!

697 0 0 Amidation C47627 "CYCQGJXZRZHMOH-UHFFFAOYSA-N"

 Success  registered route 557!

698 0 0 Amine_alkylation C111024 "XAUYAWPMDBLCMB-UHFFFAOYSA-N"

 Success  registered route 558!

699 0 0 Sp2-sp2_Suzuki_coupling C55545 "DNVWCQWVHHGFQV-UHFFFAOYSA-N"

 Success  registered route 559!

700 0 0 Amidation C49927 "LQIMRROOJIHJNB-UHFFFAOYSA-N"

 Success  registered route 560!

701 0 0 Amidation C55679 "ATVGHXZGBSIHPD-UHFFFAOYSA-N"

 Success  registered route 561!

702 0 0 Amidation C76428 "SITKYFMZVGCCEF-UHFFFAOYSA-N"

 Success  registered route 562!

703 0 0 Formation_of_urea_from_two_amines C45694 "NGVCFPVLGXTFRC-UHFFFAOYSA-N"

 Success  registered route 563!

704 0 0 Reductive_amination C53636 "VXAIHVZBABPCQF-UHFFFAOYSA-N"

 Success  registered route 564!

705 0 0 Chan-Lam_coupling_of_amides,_sulfonamides,_and_imides C45663 "IOEZZLDHRHKNLW-UHFFFAOYSA-N"

 Success  registered route 565!

706 0 0 Van_Leusen_imidazole_synthesis C1851 "WHQNOBWFVDSYOK-UHFFFAOYSA-N"

 Success  registered route 566!

707 0 0 Amidation C8070 "QHQMGDZLEKICDZ-UHFFFAOYSA-N"

 Success  registered route 567!

708 0 0 Amidation C19827 "ORSASUAYDTUOGY-UHFFFAOYSA-N"

 Success  registered route 568!

709 0 0 Amidation C11207 "IZIDSOYGYYEPPV-UHFFFAOYSA-N"

 Success  registered route 569!

710 0 0 Chan-Lam_coupling_(amination) C6106 "DOUSOOUXCFRQSM-UHFFFAOYSA-N"

 Success  registered route 570!

711 0 0 Amidation C31645 "NWHFPHZJXUAAAQ-UHFFFAOYSA-N"

 Success  registered route 571!

712 0 0 Amine_alkylation C2541 "BKHKIOXROMQUPK-UHFFFAOYSA-N"

712 0 1 Riley_oxidation C284468 "PJMSOFLNCXFRFA-UHFFFAOYSA-N"

712 0 2 Amine_alkylation C286446 "CFBLNJCGKKWYNY-UHFFFAOYSA-N"

 Success  registered route 572!

713 0 0 Amidation C3778 "AGEDTVGYDAKPRV-UHFFFAOYSA-N"

 Success  registered route 573!

714 0 0 Alpha_alkylation_of_ester/amide C5948 "YJBQQPKNCOBFQV-UHFFFAOYSA-N"

715 0 0 Ester_amidation C29671 "NTHBIXDORUIWBD-UHFFFAOYSA-N"

 Success  registered route 575!

716 0 0 Buchwald-Hartwig_(thio)etherification C66949 "IKAMDUKMYVVAKK-UHFFFAOYSA-N"

 Success  registered route 576!

717 0 0 S-nucleophilic_aromatic_substitution C66955 "CMZOTFOSHDWTHE-UHFFFAOYSA-N"

 Success  registered route 577!

718 0 0 Sp2-sp2_Suzuki_coupling C131861 "VIWGUSXHUZQJLO-UHFFFAOYSA-N"

 Success  registered route 578!

719 0 0 Sulfonamide_Schotten-Baumann_with_amine_(intermolecular) C7634 "RXBXROWIEPMBRV-UHFFFAOYSA-N"

 Success  registered route 579!

720 0 0 Amine_alkylation C6248 "NXJYTRXEEROFOS-UHFFFAOYSA-N"

720 0 1 Nucleophilic_substitution_with_thiol C284493 "DIRVXUXHRISBNS-UHFFFAOYSA-N"

720 0 2 Minisci_reaction_with_carboxylic_acid_(intermolecular) C286450 "MQBUBQARWQGQJV-UHFFFAOYSA-N"

 Success  registered route 580!

721 0 0 Amidation C1120 "PCPXIHBDOBZPNO-UHFFFAOYSA-N"

 Success  registered route 581!

722 0 0 Petasis-borono_Mannich_reaction C686 "SAIOTEOVHAXKQN-UHFFFAOYSA-N"

 Success  registered route 582!

723 0 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C2396 "KQFUVIPQGHKRPL-UHFFFAOYSA-N"

 Success  registered route 583!

724 0 0 Ester_amidation C29678 "VOTQTKPUGDWATD-UHFFFAOYSA-N"

 Success  registered route 584!

725 0 0 Amidation C27712 "GDQVYSCIVDEKLE-UHFFFAOYSA-N"

 Success  registered route 585!

726 0 0 Chan-Lam_coupling_(amination) C6091 "COBZFPMMXCEFIL-UHFFFAOYSA-N"

 Success  registered route 586!

727 0 0 Amidation C13816 "YLJSCEDYXYHCFH-UHFFFAOYSA-N"

 Success  registered route 587!

728 0 0 Ester_amidation C29694 "OAMNIYGWLQGWFH-UHFFFAOYSA-N"

 Success  registered route 588!

729 0 0 Nucleophilic_aromatic_substitution_(methylsulfone) C6108 "SBOGVGGESDHHSA-UHFFFAOYSA-N"

 Success  registered route 589!

730 0 0 Amidation C32227 "AIHZEWPQJWAUAF-UHFFFAOYSA-N"

 Success  registered route 590!

731 0 0 Amidation C31798 "AYUAFHQJYXDAKG-UHFFFAOYSA-N"

 Success  registered route 591!

732 0 0 Amidation C41442 "MXKVMTZMLDJXBU-UHFFFAOYSA-N"

 Success  registered route 592!

733 0 0 Amidation C6060 "CBBQZDXGIJWOCE-UHFFFAOYSA-N"

 Success  registered route 593!

734 0 0 Formation_of_sulfonamide_from_halide_-_Shavnya_reaction C7599 "UXAXKRNZNZXPTI-UHFFFAOYSA-N"

 Success  registered route 594!

735 0 0 Amidation C8470 "XMYOBLGSEFSZPI-UHFFFAOYSA-N"

 Success  registered route 595!

736 0 0 Mitsunobu_aryl_ether_synthesis C8912 "QLWADYUBFZPSNX-UHFFFAOYSA-N"

 Success  registered route 596!

737 0 0 Amidation C525 "JORZCDFDZUSFGH-UHFFFAOYSA-N"

 Success  registered route 597!

738 0 0 Sp3-sp2_Suzuki_coupling C14093 "SINRWOHZHXCYHE-UHFFFAOYSA-N"

 Success  registered route 598!

739 0 0 Amidation C38436 "JICXCXXASDPJKV-UHFFFAOYSA-N"

 Success  registered route 599!

740 0 0 Amidation C10284 "DJZJZIVHKYRBPY-UHFFFAOYSA-N"

 Success  registered route 600!

741 0 0 Amidation C18032 "XZDJAODRDBHFTF-UHFFFAOYSA-N"

 Success  registered route 601!

742 0 0 Amidation C3775 "INAHVQSNTWKORJ-UHFFFAOYSA-N"

 Success  registered route 602!

743 0 0 Amidation C6013 "ZBXBLXXYJIHBMH-UHFFFAOYSA-N"

 Success  registered route 603!

744 0 0 N-Boc_deprotection C2609 "KGAKJVPCKUCLKV-UHFFFAOYSA-N"

 Success  registered route 604!

745 0 0 Amidation C6170 "MTBPSJNSQYHQEE-UHFFFAOYSA-N"

 Success  registered route 605!

746 0 0 Alpha_alkylation_of_ester/amide C14936 "TYVKHTBDVKDANR-UHFFFAOYSA-N"

 Success  registered route 606!

747 0 0 Sp2-sp2_Suzuki_coupling C43497 "FUNCVLSABIHRON-UHFFFAOYSA-N"

 Success  registered route 607!

748 0 0 Pinner_reaction_(carboxylate_ester) C5648 "HCFLACFMBGGTGN-UHFFFAOYSA-N"

 Success  registered route 608!

749 0 0 Amidation C3501 "YEVKEYTWDZTQPG-UHFFFAOYSA-N"

 Success  registered route 609!

750 0 0 N-nucleophilic_aromatic_substitution C86322 "HXGBIHXJNUTVEU-UHFFFAOYSA-N"

 Success  registered route 610!

751 0 0 Amidation C1402 "MEPCMNAIXFKGGU-UHFFFAOYSA-N"

 Success  registered route 611!

752 0 0 Amidation C7155 "JBBGRUAMKVJKBX-UHFFFAOYSA-N"

 Success  registered route 612!

753 0 0 Amidation C17682 "BVGBDOZXIVOWDC-UHFFFAOYSA-N"

 Success  registered route 613!

754 0 0 Benzylic_deprotonation-alkylation_(pyridine) C973 "UERDZVKTYWOYRH-UHFFFAOYSA-N"

 Success  registered route 614!

755 0 0 Amidation C27254 "BVTPDBRQZWYODH-UHFFFAOYSA-N"

 Success  registered route 615!

756 0 0 Amidation C137292 "VEAOSVDTZUAADO-UHFFFAOYSA-N"

 Success  registered route 616!

757 0 0 Amidation C7469 "ZJUWFSGBSHLZFO-UHFFFAOYSA-N"

 Success  registered route 617!

758 0 0 Alpha_alkylation_of_ester/amide C15823 "DPUSSHZYAUIWGW-UHFFFAOYSA-N"

 Success  registered route 618!

759 0 0 Sp3-sp2_Suzuki_coupling C6528 "IGFLHWNYLMXGMG-UHFFFAOYSA-N"

 Success  registered route 619!

760 0 0 Amidation C16512 "PGILFXQYSGPPJO-UHFFFAOYSA-N"

 Success  registered route 620!

761 0 0 Amidation C31046 "JBQKPGDVXBNGRB-UHFFFAOYSA-N"

 Success  registered route 621!

762 0 0 Amidation C16616 "IIPNYHKMPRUJNY-UHFFFAOYSA-N"

 Success  registered route 622!

763 0 0 Amidation C4708 "ISSFEYHUURQIMN-UHFFFAOYSA-N"

 Success  registered route 623!

764 0 0 Amidation C8425 "YIPVAMALDHWMTF-UHFFFAOYSA-N"

 Success  registered route 624!

765 0 0 Amidation C16607 "MLBVNWMSZZUEEK-UHFFFAOYSA-N"

 Success  registered route 625!

766 0 0 Amidation C94391 "GMNUJJZGAJDXFW-UHFFFAOYSA-N"

766 0 1 Amidation C284596 "BVMRIWAXTXVZJU-UHFFFAOYSA-N"

 Success  registered route 626!

767 0 0 Amidation C137405 "GKXYBOZHRPWQMF-UHFFFAOYSA-N"

 Success  registered route 627!

768 0 0 Imine_reduction_to_amine C6259 "BELIZRHOJQZKIU-UHFFFAOYSA-N"

 Success  registered route 628!

769 0 0 Amidation C137594 "UOUIWTUESXXDBU-UHFFFAOYSA-N"

 Success  registered route 629!

770 0 0 Sp3-sp2_Suzuki_coupling C1791 "RJKAJKWADMVNQR-UHFFFAOYSA-N"

 Success  registered route 630!

771 0 0 Corey-House_synthesis_(intermolecular) C20070 "CLRMICGDIZHILI-UHFFFAOYSA-N"

 Success  registered route 631!

772 0 0 Amidation C7166 "AVOIXSQDOULTDX-UHFFFAOYSA-N"

 Success  registered route 632!

773 0 0 Amidation C7163 "IZSOYUYGRQMQRH-UHFFFAOYSA-N"

 Success  registered route 633!

774 0 0 Amidation C25407 "ICJOJHQESJORQW-UHFFFAOYSA-N"

 Success  registered route 634!

775 0 0 Amidation C3425 "QLOQFBVXSCYUGU-UHFFFAOYSA-N"

 Success  registered route 635!

776 0 0 Formation_of_urea_from_two_amines C6688 "OKPCGXCBARQEEC-UHFFFAOYSA-N"

 Success  registered route 636!

777 0 0 Amine_alkylation C4801 "LGOSQMUDZURGMS-UHFFFAOYSA-N"

 Success  registered route 637!

778 0 0 Isocyanate_to_urea C12392 "ZQPQFOMHEKOXNL-UHFFFAOYSA-N"

 Success  registered route 638!

779 0 0 Alpha_alkylation_of_ketone C18178 "YSYAKSZYKZXPDR-UHFFFAOYSA-N"

 Success  registered route 639!

780 0 0 Amidation C7467 "UICBVSXZBKLTCN-UHFFFAOYSA-N"

 Success  registered route 640!

781 0 0 Ester_Schotten-Baumann C15058 "OHSAREOUZZCQAJ-UHFFFAOYSA-N"

 Success  registered route 641!

782 0 0 Amidation C6003 "NBQUOSUMIDGENX-UHFFFAOYSA-N"

 Success  registered route 642!

783 0 0 Isocyanate_to_urea C12390 "TVRSJPQUTNYHJL-UHFFFAOYSA-N"

 Success  registered route 643!

784 0 0 Alpha_alkylation_of_ketone C2421 "MZDOVACAPIIERT-UHFFFAOYSA-N"

 Success  registered route 644!

785 0 0 Amide_to_amine_reduction C7492 "GKUFWTQUJZVHEF-UHFFFAOYSA-N"

 Success  registered route 645!

786 0 0 Amidation C1335 "ASXOQFKVRDSSQV-UHFFFAOYSA-N"

 Success  registered route 646!

787 0 0 Amidation C4120 "SCEDCLAZUHAAQO-UHFFFAOYSA-N"

 Success  registered route 647!

788 0 0 N-nucleophilic_aromatic_substitution C733 "TVAYLIZZNFTQFK-UHFFFAOYSA-N"

 Success  registered route 648!

789 0 0 Amidation C8861 "MKTBAFXTCUWNBK-UHFFFAOYSA-N"

 Success  registered route 649!

790 0 0 Reductive_amination C20719 "XPVXHOUETPQGLE-UHFFFAOYSA-N"

 Success  registered route 650!

791 0 0 Amidation C92303 "OKTSLPRUODZUGE-UHFFFAOYSA-N"

 Success  registered route 651!

792 0 0 Formation_of_urea_from_two_amines C2911 "NCEQHOKEWKRXIV-UHFFFAOYSA-N"

 Success  registered route 652!

793 0 0 Sp3-sp2_Suzuki_coupling C1786 "JXWMKEUIJSXMCW-UHFFFAOYSA-N"

 Success  registered route 653!

794 0 0 Alpha_alkylation_of_ester/amide C11116 "WBRPYRDSULUSNM-UHFFFAOYSA-N"

 Success  registered route 654!

795 0 0 Amidation C8041 "NFLBITXMLRACJJ-UHFFFAOYSA-N"

 Success  registered route 655!

796 0 0 Amidation C12499 "BCDQTWFBHRJQBJ-UHFFFAOYSA-N"

 Success  registered route 656!

797 0 0 Amidation C8808 "SKSIURWSBHFBHM-UHFFFAOYSA-N"

 Success  registered route 657!

798 0 0 Amidation C13230 "MHHNFZZOJRSSDX-UHFFFAOYSA-N"

 Success  registered route 658!

799 0 0 Amidation C14131 "UGKZNMVPXYTRAP-UHFFFAOYSA-N"

 Success  registered route 659!

800 0 0 Amidation C137590 "OCOAFNKPMGWDGK-UHFFFAOYSA-N"

 Success  registered route 660!

801 0 0 Chan-Lam_coupling_(amination) C717 "NALJDFTWWSKAFR-UHFFFAOYSA-N"

 Success  registered route 661!

802 0 0 Amidation C2655 "KPRRPMPYWRBBFE-UHFFFAOYSA-N"

 Success  registered route 662!

803 0 0 Reductive_amination C24158 "NGTVSTSCMVXIID-UHFFFAOYSA-N"

 Success  registered route 663!

804 0 0 Reductive_amination C39011 "FVYPBJNBOMUKIB-UHFFFAOYSA-N"

 Success  registered route 664!

805 0 0 Amidation C5967 "LSUAPJGZXMGFQN-UHFFFAOYSA-N"

 Success  registered route 665!

806 0 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C6187 "FUFCTZFRZVSXTB-UHFFFAOYSA-N"

 Success  registered route 666!

807 0 0 Amidation C10379 "MRPNTPLWNNFLQF-UHFFFAOYSA-N"

 Success  registered route 667!

808 0 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C92873 "GMRFHKBAYYYVFF-UHFFFAOYSA-N"

 Success  registered route 668!

809 0 0 Sulfonamide_Schotten-Baumann_with_amine_(intermolecular) C82633 "OSQOBRFFSJVYOU-UHFFFAOYSA-N"

 Success  registered route 669!

810 0 0 N-Boc_deprotection C4764 "CJXLGMYFPUVARV-UHFFFAOYSA-N"

 Success  registered route 670!

811 0 0 Amidation C7520 "WVOIPXNGWQBXDQ-UHFFFAOYSA-N"

 Success  registered route 671!

812 0 0 Amine_alkylation C34336 "QJWWGHKEHQNEQY-UHFFFAOYSA-N"

 Success  registered route 672!

813 0 0 Mannich_reaction C18943 "YUJANCLQKWVXAZ-UHFFFAOYSA-N"

 Success  registered route 673!

814 0 0 Nucleophilic_substitution_with_thioamide C6038 "GOLAEVZHHBNYFC-UHFFFAOYSA-N"

 Success  registered route 674!

815 0 0 Amidation C2124 "IIGXHTIDEPJZDV-UHFFFAOYSA-N"

 Success  registered route 675!

816 0 0 Stille_coupling C11982 "FIVHXQGGXYYQJB-UHFFFAOYSA-N"

 Success  registered route 676!

817 0 0 Amidation C33638 "GZMCLAHOGOMNFO-UHFFFAOYSA-N"

817 0 1 Amidation C284716 "XYKWXTIJAVRDEW-UHFFFAOYSA-N"

 Success  registered route 677!

818 0 0 Formation_of_sulfonamide_from_boronic_and_amine C35059 "ZXIQETDVUZSVBJ-UHFFFAOYSA-N"

 Success  registered route 678!

819 0 0 Amidation C130294 "HVLXCUMSINBNKL-UHFFFAOYSA-N"

 Success  registered route 679!

820 0 0 Petasis-borono_Mannich_reaction C55269 "OORBTWFKCNWGNJ-UHFFFAOYSA-N"

 Success  registered route 680!

821 0 0 Amidation C3807 "ULRPMLDUMSAKFM-UHFFFAOYSA-N"

 Success  registered route 681!

822 0 0 Minisci_reaction_with_carboxylic_acid_(intermolecular) C1823 "WERCHVXXXMTJME-UHFFFAOYSA-N"

 Success  registered route 682!

823 0 0 Buchwald-Hartwig_amination C1169 "CGHAWODWSBOPHV-UHFFFAOYSA-N"

 Success  registered route 683!

824 0 0 Petasis-borono_Mannich_reaction C1803 "JTKBNXRWTLWVNM-UHFFFAOYSA-N"

 Success  registered route 684!

825 0 0 Amidation C21091 "UPVSFXPIZJMBGP-UHFFFAOYSA-N"

 Success  registered route 685!

826 0 0 Formation_of_urea_from_two_amines C8920 "GXLWWRPCSDKINQ-UHFFFAOYSA-N"

 Success  registered route 686!

827 0 0 N-Boc_deprotection C4746 "MHSGZEFYVKSBLF-UHFFFAOYSA-N"

 Success  registered route 687!

828 0 0 Amidation C20105 "ZUCKYOCXPYNNQW-UHFFFAOYSA-N"

 Success  registered route 688!

829 0 0 Sp3-sp2_Macmillan_coupling_with_bromide_(intermolecular) C18941 "GHTQJYVHMYLSOL-UHFFFAOYSA-N"

 Success  registered route 689!

830 0 0 N-nucleophilic_aromatic_substitution C18492 "IWXAZUGAFBIABQ-UHFFFAOYSA-N"

 Success  registered route 690!

831 0 0 Reductive_amination C5654 "MIJXJNKYRJUUNZ-UHFFFAOYSA-N"

 Success  registered route 691!

832 0 0 Formation_of_urea_from_two_amines C22202 "OBYODZPHMWOBDT-UHFFFAOYSA-N"

 Success  registered route 692!

833 0 0 Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide C6268 "YFEHDHGTUJUJKX-UHFFFAOYSA-N"

 Success  registered route 693!

834 0 0 Formation_of_urea_from_two_amines C129989 "ILKJWDJJINULLS-UHFFFAOYSA-N"

 Success  registered route 694!

835 0 0 Amidation C10831 "LAVULZBUGIJAIW-UHFFFAOYSA-N"

 Success  registered route 695!

836 0 0 Amidation C8973 "QEVCNVOOKXMKLD-UHFFFAOYSA-N"

 Success  registered route 696!

837 0 0 Amidation C85352 "QWJIGENMFCZKMW-UHFFFAOYSA-N"

 Success  registered route 697!

838 0 0 Amidation C94799 "UTSSZZOTMTVFDK-UHFFFAOYSA-N"

 Success  registered route 698!

839 0 0 Amidation C13838 "IZSCHRLXBICVLQ-UHFFFAOYSA-N"

 Success  registered route 699!

840 0 0 Amidation C1391 "RQFZEASXPNBDLI-UHFFFAOYSA-N"

 Success  registered route 700!

841 0 0 N-nucleophilic_aromatic_substitution C27720 "ADVKSLWFNRLRGX-UHFFFAOYSA-N"

 Success  registered route 701!

842 0 0 Amine_alkylation C798 "XNMOBDIPLKKDMN-UHFFFAOYSA-N"

 Success  registered route 702!

843 0 0 Amidation C36705 "ONRWVJVKMVEFCF-UHFFFAOYSA-N"

 Success  registered route 703!

844 0 0 Amidation C9079 "YGPKMENKUMLTBY-UHFFFAOYSA-N"

 Success  registered route 704!

845 0 0 Amidation C4820 "IVEXCVXFXPPGNY-UHFFFAOYSA-N"

 Success  registered route 705!

846 0 0 Petasis-borono_Mannich_reaction C15053 "GIUVSXLAIVLOML-UHFFFAOYSA-N"

 Success  registered route 706!

847 0 0 Buchwald-Hartwig_amination C1257 "DETFJAMYSPHHBK-UHFFFAOYSA-N"

 Success  registered route 707!

848 0 0 Sulfonamide_Schotten-Baumann_with_amine_(intermolecular) C15036 "LJZIXTIXXJIVMZ-UHFFFAOYSA-N"

 Success  registered route 708!

849 0 0 Amidation C7185 "KHYQSBBCZQEPEA-UHFFFAOYSA-N"

 Success  registered route 709!

850 0 0 Amidation C8165 "SEVSZWOINVGPQI-UHFFFAOYSA-N"

 Success  registered route 710!

851 0 0 Amidation C27907 "QYTMWYMZVFYJAW-UHFFFAOYSA-N"

 Success  registered route 711!

852 0 0 Amidation C10333 "MLNMURZXNDQHPB-UHFFFAOYSA-N"

 Success  registered route 712!

853 0 0 Amidation C87026 "CWSPXHPREHEYCE-UHFFFAOYSA-N"

 Success  registered route 713!

854 0 0 Amine_alkylation C5168 "DSRVXZMXCPNZDO-UHFFFAOYSA-N"

 Success  registered route 714!

855 0 0 1,2,4-Oxadiazole_synthesis_(nitrile_+_carboxylic_acid) C27906 "SGWHFDPWZAGZRG-UHFFFAOYSA-N"

 Success  registered route 715!

 Success  registered route 716!

857 0 0 Amidation C15351 "YWXZMUQGZGJALN-UHFFFAOYSA-N"

 Success  registered route 717!

858 0 0 Amidation C7605 "GHIJXTOSIYSZBD-UHFFFAOYSA-N"

 Success  registered route 718!

859 0 0 Alpha_alkylation_of_ester/amide C1328 "QEAIPLSLYLEHLE-UHFFFAOYSA-N"

 Success  registered route 719!

860 0 0 Amidation C13612 "NOLYSQFICWENKE-UHFFFAOYSA-N"

 Success  registered route 720!

861 0 0 Amidation C24648 "XEWCFUUENPDOSL-UHFFFAOYSA-N"

 Success  registered route 721!

862 0 0 Sp2-sp2_Suzuki_coupling C6282 "ORBZHPMIKIFVPF-UHFFFAOYSA-N"

 Success  registered route 722!

863 0 0 Amidation C3842 "PLIIAKFRJSUEBR-UHFFFAOYSA-N"

 Success  registered route 723!

864 0 0 Nucleophilic_substitution_with_thioamide C31893 "FKUJMGDPPLMJGR-UHFFFAOYSA-N"

 Success  registered route 724!

865 0 0 Chan-Lam_coupling_(amination) C2636 "VLTCJSKEHQAUTL-UHFFFAOYSA-N"

 Success  registered route 725!

866 0 0 Amidation C28383 "PVHTYTCVYUNLLL-UHFFFAOYSA-N"

 Success  registered route 726!

867 0 0 Amidation C7169 "YIILFKIQHWPXAG-UHFFFAOYSA-N"

 Success  registered route 727!

868 0 0 Sulfonamide_Schotten-Baumann_with_amine_(intermolecular) C7673 "FEWUTFMHYWVVGO-UHFFFAOYSA-N"

 Success  registered route 728!

869 0 0 Amidation C2652 "XANBFXMPGDEVBY-UHFFFAOYSA-N"

 Success  registered route 729!

870 0 0 Amidation C1318 "AXOVECJXLBLXBH-UHFFFAOYSA-N"

 Success  registered route 730!

871 0 0 Amidation C3826 "QENDPRIYXYIRHV-UHFFFAOYSA-N"

 Success  registered route 731!

872 0 0 Amidation C92775 "WYQDXWYIGKTVHX-UHFFFAOYSA-N"

 Success  registered route 732!

873 0 0 Amidation C9910 "AQHJQVUQKSJLJN-UHFFFAOYSA-N"

 Success  registered route 733!

874 0 0 Amine_alkylation C805 "QZNTZLREQHIPTH-UHFFFAOYSA-N"

 Success  registered route 734!

875 0 0 Petasis-borono_Mannich_reaction C4545 "JSYRTCNAAWDFHA-UHFFFAOYSA-N"

 Success  registered route 735!

876 0 0 Reductive_amination C88601 "GHUWQZDUXFABRG-UHFFFAOYSA-N"

 Success  registered route 736!

877 0 0 Formation_of_urea_from_two_amines C6181 "KPKROVRQPATTCI-UHFFFAOYSA-N"

 Success  registered route 737!

878 0 0 Amidation C38623 "KQFIZQJHMHSRJU-UHFFFAOYSA-N"

 Success  registered route 738!

879 0 0 Amidation C33929 "RQPYZWIDBNQYDN-UHFFFAOYSA-N"

 Success  registered route 739!

880 0 0 Amidation C5358 "PLKRCIBWWXFPQS-UHFFFAOYSA-N"

 Success  registered route 740!

881 0 0 Amidation C8052 "BYSVFNXGWBOSLW-UHFFFAOYSA-N"

 Success  registered route 741!

882 0 0 Amidation C8468 "RDBFNHFBDWYSQG-UHFFFAOYSA-N"

 Success  registered route 742!

883 0 0 Amidation C8923 "TZNQIOOJWDMLNH-UHFFFAOYSA-N"

 Success  registered route 743!

884 0 0 Amidation C28778 "IKGWEUPIBZYKCX-UHFFFAOYSA-N"

 Success  registered route 744!

885 0 0 Amidation C533 "CUBOAIJARPZGGJ-UHFFFAOYSA-N"

 Success  registered route 745!

886 0 0 Amidation C5691 "BWURFTTURAXDKM-UHFFFAOYSA-N"

 Success  registered route 746!

887 0 0 Formation_of_urea_from_two_amines C16890 "KTRXBMCRTROOIW-UHFFFAOYSA-N"

 Success  registered route 747!

888 0 0 Amidation C27893 "BZLSGPYVTJTSHN-UHFFFAOYSA-N"

 Success  registered route 748!

889 0 0 Amidation C93118 "OKCDMJXQKQAOBD-UHFFFAOYSA-N"

 Success  registered route 749!

890 0 0 Amidation C14951 "WNSGNWHGSWFAHB-UHFFFAOYSA-N"

 Success  registered route 750!

891 0 0 Amidation C31471 "HWNMIYOIZLOAOJ-UHFFFAOYSA-N"

 Success  registered route 751!

892 0 0 Amidation C4560 "BSZJDRPOJAAOSY-UHFFFAOYSA-N"

 Success  registered route 752!

893 0 0 Amidation C10821 "GPNVFMKKUMJBLG-UHFFFAOYSA-N"

 Success  registered route 753!

894 0 0 Carboxylic_acid_+_hydrazine_condensation C9575 "DDAYMZHBOWJNFK-UHFFFAOYSA-N"

 Success  registered route 754!

895 0 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C12439 "FKTAAXVJSFCNDC-UHFFFAOYSA-N"

 Success  registered route 755!

896 0 0 Amidation C6343 "MTFCVKLEKLKXNT-UHFFFAOYSA-N"

 Success  registered route 756!

897 0 0 Amidation C9132 "IXXWILBFBCPULP-UHFFFAOYSA-N"

 Success  registered route 757!

898 0 0 Sp3-sp2_Suzuki_coupling C8889 "UKIYNEQFJFUCIO-UHFFFAOYSA-N"

 Success  registered route 758!

899 0 0 Reductive_amination C875 "PLRNRTQFDDEAPK-UHFFFAOYSA-N"

 Success  registered route 759!

900 0 0 Amidation C12144 "WRGUXZFLVPHPPA-UHFFFAOYSA-N"

 Success  registered route 760!

901 0 0 Steglich_esterification C5288 "DCWKGBWLMWJEGU-UHFFFAOYSA-N"

 Success  registered route 761!

902 0 0 Alpha_alkylation_of_ketone C4645 "JHPLEUYNZYOKAC-UHFFFAOYSA-N"

 Success  registered route 762!

903 0 0 Amidation C3782 "QBKDTAGNELZKNO-UHFFFAOYSA-N"

 Success  registered route 763!

904 0 0 Ester_amidation C23517 "KKPJMJAAGWYOGV-UHFFFAOYSA-N"

 Success  registered route 764!

905 0 0 Amidation C34811 "UWXVEDCEWYGTRJ-UHFFFAOYSA-N"

 Success  registered route 765!

906 0 0 Amidation C15735 "HDCUDRUHFXHSNY-UHFFFAOYSA-N"

 Success  registered route 766!

907 0 0 Amidation C21158 "AJLXANOZRCJDLS-UHFFFAOYSA-N"

 Success  registered route 767!

908 0 0 Amidation C14078 "NBHXHSMIGQMUER-UHFFFAOYSA-N"

 Success  registered route 768!

909 0 0 Formation_of_urea_from_two_amines C84544 "FYRXYDPVISKWNM-UHFFFAOYSA-N"

 Success  registered route 769!

910 0 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C2400 "RAJZPRJBARPLQW-UHFFFAOYSA-N"

 Success  registered route 770!

911 0 0 Amine_alkylation C4528 "BGXAVSVRYXHJHI-UHFFFAOYSA-N"

 Success  registered route 771!

912 0 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C7891 "BVORABRUVNAGOD-UHFFFAOYSA-N"

912 0 1 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C284894 "MHLFHSYZIFIPEO-UHFFFAOYSA-N"

 Success  registered route 772!

913 0 0 Amidation C10535 "XJPJCIMCDCBUDM-UHFFFAOYSA-N"

 Success  registered route 773!

914 0 0 Amidation C27676 "UILMKCCWNFQJCT-UHFFFAOYSA-N"

 Success  registered route 774!

915 0 0 Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide C1811 "KQPUFQLGSXQISW-UHFFFAOYSA-N"

 Success  registered route 775!

916 0 0 Amine_alkylation C2390 "GRCPKGYTKXKWFK-UHFFFAOYSA-N"

 Success  registered route 776!

917 0 0 Amidation C1361 "AQILHIUWLDOOHJ-UHFFFAOYSA-N"

 Success  registered route 777!

918 0 0 TEMPO_oxidation C4701 "FINIGGNJPQFVOX-UHFFFAOYSA-N"

 Success  registered route 778!

919 0 0 Amidation C8168 "CTCJLPKYTZKXTA-UHFFFAOYSA-N"

 Success  registered route 779!

920 0 0 Amidation C1417 "DCZHFEWOJXEGST-UHFFFAOYSA-N"

 Success  registered route 780!

921 0 0 Reductive_amination C5378 "BPVACFSEVJXOJC-UHFFFAOYSA-N"

 Success  registered route 781!

922 0 0 Sp3-sp2_Suzuki_coupling C11486 "FXEFZOMVZBBFDP-UHFFFAOYSA-N"

 Success  registered route 782!

923 0 0 Amidation C26238 "YKUFSMANTRFFSS-UHFFFAOYSA-N"

 Success  registered route 783!

924 0 0 Alpha_alkylation_of_nitriles C19998 "HKXVWCTZHQLBNW-UHFFFAOYSA-N"

 Success  registered route 784!

925 0 0 Amidation C22516 "WUAFTAWKKQKQSG-UHFFFAOYSA-N"

 Success  registered route 785!

926 0 0 Amidation C12016 "XPWBZSZXWGFDON-UHFFFAOYSA-N"

 Success  registered route 786!

927 0 0 Amidation C94714 "JSVZKTIWBIRABG-UHFFFAOYSA-N"

 Success  registered route 787!

928 0 0 Formation_of_urea_from_two_amines C84541 "JYRQIYXJRADILA-UHFFFAOYSA-N"

 Success  registered route 788!

929 0 0 Amidation C82401 "CBVFQNPUAAYSLD-UHFFFAOYSA-N"

 Success  registered route 789!

930 0 0 Minisci_reaction_with_carboxylic_acid_(intermolecular) C7393 "XZMDXLGITMJJAR-UHFFFAOYSA-N"

 Success  registered route 790!

931 0 0 Amidation C21167 "NKBIUPWOQPIFKU-UHFFFAOYSA-N"

 Success  registered route 791!

932 0 0 Amidation C91081 "AJZMAQJSZWQBTD-UHFFFAOYSA-N"

 Success  registered route 792!

933 0 0 N-nucleophilic_aromatic_substitution C12411 "GOIIBLCLDRWXDI-UHFFFAOYSA-N"

 Success  registered route 793!

934 0 0 Amidation C1419 "BYXOCXSSHQOHSD-UHFFFAOYSA-N"

 Success  registered route 794!

935 0 0 Amidation C7147 "ZRXPCXKVGFOFRK-UHFFFAOYSA-N"

 Success  registered route 795!

936 0 0 N-Boc_deprotection C1877 "JUJYNCPRVMVRCV-UHFFFAOYSA-N"

 Success  registered route 796!

937 0 0 Amidation C10215 "FPIYKYLQFSMPTN-UHFFFAOYSA-N"

 Success  registered route 797!

938 0 0 Amidation C4291 "AJQNPQKWWJKQFB-UHFFFAOYSA-N"

 Success  registered route 798!

939 0 0 Amidation C9987 "MQHOJDGABPALRL-UHFFFAOYSA-N"

 Success  registered route 799!

940 0 0 Hydrogenation_of_pyridine C6051 "YDZVKAFTNJTLSL-UHFFFAOYSA-N"

 Success  registered route 800!

941 0 0 Amidation C8437 "HNEOZDURNOEMOY-UHFFFAOYSA-N"

 Success  registered route 801!

942 0 0 Amidation C9817 "QFOVZMCLJFNOLH-UHFFFAOYSA-N"

 Success  registered route 802!

943 0 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C4710 "SUDOFTVBCPEFQK-UHFFFAOYSA-N"

 Success  registered route 803!

944 0 0 Amidation C3516 "FIHUVLYGVBEHSM-UHFFFAOYSA-N"

 Success  registered route 804!

945 0 0 Amide_Schotten-Baumann_with_amine C15029 "OCFFTUGEJZIYTH-UHFFFAOYSA-N"

945 0 1 Carboxylic_acid_to_acid_chloride C284957 "QFZYRYDAWXHSFT-UHFFFAOYSA-N"

 Success  registered route 805!

946 0 0 Iodo_N-arylation C22809 "LDZSMRRPHYMGJB-UHFFFAOYSA-N"

 Success  registered route 806!

947 0 0 Amidation C36659 "BMGQAPYAWGCTSL-UHFFFAOYSA-N"

 Success  registered route 807!

948 0 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C2378 "ZWZHRYGYRLXIEQ-UHFFFAOYSA-N"

 Success  registered route 808!

949 0 0 Buchwald-Hartwig_amination C12945 "ZIPKJCBHPHJSDG-UHFFFAOYSA-N"

 Success  registered route 809!

950 0 0 Amidation C34425 "DKGPPHBODADFID-UHFFFAOYSA-N"

 Success  registered route 810!

951 0 0 Amidation C37776 "TXLFUDQYNGTYGY-UHFFFAOYSA-N"

 Success  registered route 811!

952 0 0 Alpha_alkylation_of_ester/amide C10783 "DXNJQCFHVKJTJF-UHFFFAOYSA-N"

 Success  registered route 812!

953 0 0 Amine_alkylation C2530 "GPGBQKMPCMYFLT-UHFFFAOYSA-N"

 Success  registered route 813!

954 0 0 Amidation C29365 "VMRRPEUPZRWAAJ-UHFFFAOYSA-N"

 Success  registered route 814!

955 0 0 Amidation C20158 "QVJOVVVVXHHADP-UHFFFAOYSA-N"

 Success  registered route 815!

956 0 0 Amidation C31914 "ULOXUOOKQMHPDW-UHFFFAOYSA-N"

 Success  registered route 816!

957 0 0 Formation_of_urea_from_two_amines C33243 "ZTMHRCWTNSPQGN-UHFFFAOYSA-N"

 Success  registered route 817!

958 0 0 Sonogashira_coupling C765 "GHIFOCYQWCGZBT-UHFFFAOYSA-N"

 Success  registered route 818!

959 0 0 Sp3-sp2_Macmillan_coupling_with_bromide_(intermolecular) C6116 "NUWLOKGYWJWIQU-UHFFFAOYSA-N"

959 0 1 Reductive_amination C284998 "ISCTUNGKIJAFGU-UHFFFAOYSA-N"

 Success  registered route 819!

960 0 0 Hydrolysis_of_enol_ether C10419 "VABKMYCWOFANPU-UHFFFAOYSA-N"

960 0 1 Buchwald-Hartwig_amination C285003 "LWUCWOSKKZJFLB-UHFFFAOYSA-N"

 Success  registered route 820!

961 0 0 Amidation C5954 "RTIJVGZLLDAVEL-UHFFFAOYSA-N"

 Success  registered route 821!

962 0 0 TEMPO_oxidation C4666 "NRPARTHTHRTTMK-UHFFFAOYSA-N"

 Success  registered route 822!

963 0 0 Amidation C4928 "FCRUNMPWXPNPMG-UHFFFAOYSA-N"

 Success  registered route 823!

964 0 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C5393 "GCDRJSAGWFOAHE-UHFFFAOYSA-N"

 Success  registered route 824!

965 0 0 Amidation C5359 "BPAGEGOWFQURHS-UHFFFAOYSA-N"

 Success  registered route 825!

966 0 0 Ketone_from_acid_chloride_(Gilman_reagent,_intermolecular) C2382 "OLHKVAHFSOVKNO-UHFFFAOYSA-N"

 Success  registered route 826!

967 0 0 Buchwald-Hartwig_(thio)etherification C14605 "RAHVMMANICHALQ-UHFFFAOYSA-N"

968 0 0 Sulfonamide_Schotten-Baumann_with_amine_(intermolecular) C2063 "ZGUIGBFPAXLLGR-UHFFFAOYSA-N"

 Success  registered route 828!

969 0 0 Amide_to_amine_reduction C9825 "VIDKADKMWCUVEQ-UHFFFAOYSA-N"

969 0 1 Amide_to_amine_reduction C285033 "RGHKQPJXRNNKMV-UHFFFAOYSA-N"

969 0 2 2,5-Pyrroledione_synthesis C286457 "KWUUIICWUMEAIL-UHFFFAOYSA-N"

 Success  registered route 829!

970 0 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C8882 "JPWQZFKBNRFGNF-UHFFFAOYSA-N"

 Success  registered route 830!

971 0 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C20148 "GPLKGJZEUOGKRW-UHFFFAOYSA-N"

 Success  registered route 831!

972 0 0 Sulfonamide_Schotten-Baumann_with_amine_(intermolecular) C7653 "NCZWCIZJDPQWNM-UHFFFAOYSA-N"

 Success  registered route 832!

973 0 0 Amidation C7524 "GLYWQGPQWRVUJF-UHFFFAOYSA-N"

 Success  registered route 833!

974 0 0 Hydrogenation_of_pyridine C8585 "BRFFCOVLYYYHTQ-UHFFFAOYSA-N"

 Warning  SMILES changed during compound registration: O=C1CNC(c2cccnc2)=N1 --> O=C1CN=C(c2cccnc2)N1!

 Success  registered route 834!

975 0 0 Amidation C32018 "KFBTYOFOIPCZQH-UHFFFAOYSA-N"

 Success  registered route 835!

976 0 0 Ozonolysis_(intermolecular) C18925 "VAWUEFSAMKXCBU-UHFFFAOYSA-N"

976 0 1 Sp2-sp2_Suzuki_coupling C285045 "DEGLXCLLMUGHBR-UHFFFAOYSA-N"

 Success  registered route 836!

977 0 0 Sp3-sp2_Macmillan_coupling_with_bromide_(intermolecular) C9548 "PVLRSSNEEAZVOH-UHFFFAOYSA-N"

 Success  registered route 837!

978 0 0 Amidation C7132 "ZYQQDEPLJNFLEF-UHFFFAOYSA-N"

 Success  registered route 838!

979 0 0 Stille_coupling C9539 "ZHAZHKPVEROFLH-UHFFFAOYSA-N"

 Success  registered route 839!

980 0 0 Ester_amidation C5945 "WKDSMLUYURMGRK-UHFFFAOYSA-N"

 Success  registered route 840!

981 0 0 Amidation C5642 "QHGGWPPDZUPZIG-UHFFFAOYSA-N"

 Success  registered route 841!

982 0 0 Hydroxy_to_fluoro C25792 "IMNXQIZMBRQERC-UHFFFAOYSA-N"

 Success  registered route 842!

983 0 0 Amidation C10832 "XNDSEHCZSDWHNY-UHFFFAOYSA-N"

 Success  registered route 843!

984 0 0 Amidation C32383 "YZSYVMJRAIIIQD-UHFFFAOYSA-N"

 Success  registered route 844!

985 0 0 Hydrogenation_of_benzene C20648 "ROOFZUAQKFMYKH-UHFFFAOYSA-N"

 Success  registered route 845!

986 0 0 Formation_of_urea_from_two_amines C10686 "OVGXOABIOXLLGL-UHFFFAOYSA-N"

 Success  registered route 846!

987 0 0 Amidation C1384 "BYDQDZLINGKUEV-UHFFFAOYSA-N"

 Success  registered route 847!

988 0 0 Amidation C7067 "WYVCMIYBKYUXJW-UHFFFAOYSA-N"

 Success  registered route 848!

989 0 0 Minisci_reaction_with_carboxylic_acid_(intermolecular) C14773 "MIZHWJKJFPMAHV-UHFFFAOYSA-N"

 Success  registered route 849!

990 0 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C9822 "OTKRQPFMRSSARE-UHFFFAOYSA-N"

 Success  registered route 850!

991 0 0 Amidation C1685 "DWCBDTDREZNSGU-UHFFFAOYSA-N"

 Success  registered route 851!

992 0 0 Nucleophilic_substitution_with_thiol C10527 "REXDXSHVJSWRIX-UHFFFAOYSA-N"

 Success  registered route 852!

993 0 0 Amidation C10854 "GTOHXODIXBECHG-UHFFFAOYSA-N"

 Success  registered route 853!

994 0 0 Sp2-sp2_Suzuki_coupling C4781 "JGHMMIULJFZDBA-UHFFFAOYSA-N"

 Success  registered route 854!

995 0 0 Reductive_amination C7499 "PUIPAYFHRQTOOJ-UHFFFAOYSA-N"

 Success  registered route 855!

996 0 0 Amine_alkylation C795 "JVDTWAMFTGWSKS-UHFFFAOYSA-N"

 Success  registered route 856!

997 0 0 Amidation C1406 "ZHEXKJJYJURADK-UHFFFAOYSA-N"

 Success  registered route 857!

998 0 0 Amidation C6064 "UEVNEQDSWATJMO-UHFFFAOYSA-N"

 Success  registered route 858!

999 0 0 Amidation C3900 "CKUSNPGQZQJLGY-UHFFFAOYSA-N"

 Success  registered route 859!

1000 0 0 Amidation C15654 "AQXSEQFJAMXZOT-UHFFFAOYSA-N"

 Success  registered route 860!

1001 0 0 Isocyanate_to_urea C10683 "FDTBFBNGCRTYIH-UHFFFAOYSA-N"

 Success  registered route 861!

1002 0 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C5363 "NPDDPCJWLVZMCA-UHFFFAOYSA-N"

 Success  registered route 862!

1003 0 0 Amidation C7819 "TVNFUCRFFLGUGI-UHFFFAOYSA-N"

 Success  registered route 863!

1004 0 0 Amidation C10847 "IERXOVUPWKOWSK-UHFFFAOYSA-N"

 Success  registered route 864!

1005 0 0 Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide C6286 "ANSXQAALPGNGJP-UHFFFAOYSA-N"

 Success  registered route 865!

1006 0 0 Amidation C11204 "FXORYDYYSQMRDK-UHFFFAOYSA-N"

 Success  registered route 866!

1007 0 0 Amidation C11605 "LCCXSDXPWBGFAI-UHFFFAOYSA-N"

 Success  registered route 867!

1008 0 0 Amidation C7529 "FFAXPTHKURGIBP-UHFFFAOYSA-N"

 Success  registered route 868!

1009 0 0 Chlorination_of_alcohol C23812 "AYNLZEGPVWLBPE-UHFFFAOYSA-N"

 Success  registered route 869!

1010 0 0 Sp3-sp2_Suzuki_coupling C6258 "KVNQCSIGNRPHHM-UHFFFAOYSA-N"

 Success  registered route 870!

1011 0 0 Amidation C39872 "KOQQXKYWQMMEBA-UHFFFAOYSA-N"

 Success  registered route 871!

1012 0 0 Amidation C40659 "UTNOHUVGODOWSF-UHFFFAOYSA-N"

 Success  registered route 872!

1013 0 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C32012 "PFPNMXGZZXVBGJ-UHFFFAOYSA-N"

 Success  registered route 873!

1014 0 0 Amidation C7104 "PHEZTEPOSWGUSQ-UHFFFAOYSA-N"

 Success  registered route 874!

1015 0 0 Amidation C17883 "PJDNNFWSTSASFT-UHFFFAOYSA-N"

 Success  registered route 875!

1016 0 0 Amidation C7839 "HJVFTZYOPBWDAT-UHFFFAOYSA-N"

 Success  registered route 876!

1017 0 0 Chan-Lam_coupling_of_amides,_sulfonamides,_and_imides C4080 "GSETXYYFSRYMOU-UHFFFAOYSA-N"

 Success  registered route 877!

1018 0 0 Amidation C9976 "YNVJQHLIXVUGMB-UHFFFAOYSA-N"

 Success  registered route 878!

1019 0 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C2897 "GZBXXUHFYNAKIR-UHFFFAOYSA-N"

 Success  registered route 879!

1020 0 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C18185 "ZVYACGZLRYTKSB-UHFFFAOYSA-N"

 Success  registered route 880!

1021 0 0 Buchwald-Hartwig_amination C12979 "DJUNTQQNFNJVRB-UHFFFAOYSA-N"

 Success  registered route 881!

1022 0 0 Amine_alkylation C2040 "NVQPTGDZIZQWGQ-UHFFFAOYSA-N"

 Success  registered route 882!

1023 0 0 Amidation C24830 "IJHPSABDUDUHER-UHFFFAOYSA-N"

 Success  registered route 883!

1024 0 0 Amidation C5962 "NVJZJVXTLOAEJS-UHFFFAOYSA-N"

 Success  registered route 884!

1025 0 0 Amidation C4100 "AYBAPWWBZFMAJL-UHFFFAOYSA-N"

 Success  registered route 885!

1026 0 0 Amidation C10784 "WRGJLDZMMZTWSM-UHFFFAOYSA-N"

 Success  registered route 886!

1027 0 0 Formation_of_urea_from_two_amines C1509 "PYHYHSZBLFIGJJ-UHFFFAOYSA-N"

 Success  registered route 887!

1028 0 0 Isocyanate_to_urea C5539 "JCTAJWPEQHCFMI-UHFFFAOYSA-N"

 Success  registered route 888!

1029 0 0 Alpha_alkylation_of_ketone C18173 "AYEOHXFBHHOWPD-UHFFFAOYSA-N"

 Success  registered route 889!

1030 0 0 Alpha_alkylation_of_nitriles C8145 "IFQJCHDGIKNYJR-UHFFFAOYSA-N"

 Success  registered route 890!

1031 0 0 Steglich_esterification C42149 "TZTAWMMMGCPPTP-UHFFFAOYSA-N"

 Success  registered route 891!

1032 0 0 Amidation C31998 "TZIRKKPJSKSKFV-UHFFFAOYSA-N"

 Success  registered route 892!

1033 0 0 Formation_of_sulfonamide_from_halide_-_Shavnya_reaction C7655 "OLNCYPXEOMYYNS-UHFFFAOYSA-N"

 Success  registered route 893!

1034 0 0 Nucleophilic_substitution_with_thiol C13648 "AJANJNXHNMDIHZ-UHFFFAOYSA-N"

 Success  registered route 894!

1035 0 0 Formation_of_urea_from_two_amines C40316 "JLLXGDVGXITSBH-UHFFFAOYSA-N"

 Success  registered route 895!

1036 0 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C5407 "DVLVUUCTVLQLBO-UHFFFAOYSA-N"

 Success  registered route 896!

1037 0 0 Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide C6050 "TWMBIPLWGSZODL-UHFFFAOYSA-N"

1037 0 1 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C285176 "IDXKCKSQAVSCTI-UHFFFAOYSA-N"

 Success  registered route 897!

1038 0 0 Sp3-sp2_Suzuki_coupling C1807 "ZGJPKOODEIMJSO-UHFFFAOYSA-N"

 Success  registered route 898!

1039 0 0 Amidation C11248 "WZIGSCUCYLFSGJ-UHFFFAOYSA-N"

 Success  registered route 899!

1040 0 0 Amidation C40319 "WFPMJUJXZODHSD-UHFFFAOYSA-N"

 Success  registered route 900!

1041 0 0 Amidation C3470 "FXGFNCCXOGIGTL-UHFFFAOYSA-N"

 Success  registered route 901!

1042 0 0 Amidation C4684 "UIVUJIQVOXNKGD-UHFFFAOYSA-N"

 Success  registered route 902!

1043 0 0 Amidation C12356 "RZWWAVWMGNUJKM-UHFFFAOYSA-N"

 Success  registered route 903!

1044 0 0 Amidation C30433 "ICXYMBBPUHNCID-UHFFFAOYSA-N"

 Success  registered route 904!

1045 0 0 Williamson_ether_synthesis C43016 "CYHXIECXBFJELE-UHFFFAOYSA-N"

 Success  registered route 905!

1046 0 0 Amidation C7182 "IBTBUYIARLWWHM-UHFFFAOYSA-N"

 Success  registered route 906!

1047 0 0 Amine_alkylation C5396 "WEQDPGNEWZPZRD-UHFFFAOYSA-N"

 Success  registered route 907!

1048 0 0 Alpha_alkylation_of_ketone C2416 "QLHWJOTYGUXPGV-UHFFFAOYSA-N"

 Success  registered route 908!

1049 0 0 N-nucleophilic_aromatic_substitution C7443 "KVIFGEJVMMIWBY-UHFFFAOYSA-N"

 Success  registered route 909!

1050 0 0 Amidation C12352 "OEOUTLNRPVGOPE-UHFFFAOYSA-N"

 Success  registered route 910!

1051 0 0 Formation_of_sulfonamide_from_halide_-_Shavnya_reaction C7587 "ZWKQUCJFDUBTGP-UHFFFAOYSA-N"

 Success  registered route 911!

1052 0 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C2409 "PFPJWHGWJHUTES-UHFFFAOYSA-N"

 Success  registered route 912!

1053 0 0 Amidation C8484 "YCCKCVPWORBAJK-UHFFFAOYSA-N"

 Success  registered route 913!

1054 0 0 Formation_of_sulfonamide_from_halide_-_Shavnya_reaction C498 "BVXIXHZBAAESKN-UHFFFAOYSA-N"

 Success  registered route 914!

1055 0 0 Alpha_alkylation_of_ketone C4670 "VLIIKHOBTSPATL-UHFFFAOYSA-N"

1055 0 1 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C285206 "HIGCZKCHXZQVHD-UHFFFAOYSA-N"

 Success  registered route 915!

1056 0 0 Amidation C1682 "WPHZCKRFPCKMPN-UHFFFAOYSA-N"

 Success  registered route 916!

1057 0 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C2617 "BFAIKMGDZZASRD-UHFFFAOYSA-N"

 Success  registered route 917!

1058 0 0 Amidation C26592 "ZHAMFANYGUBSHC-UHFFFAOYSA-N"

 Success  registered route 918!

1059 0 0 Amidation C8054 "IXMDEIPJYFZEHY-UHFFFAOYSA-N"

 Success  registered route 919!

1060 0 0 Amine_alkylation C5397 "ULBBXWVIXXPSOD-UHFFFAOYSA-N"

 Success  registered route 920!

1061 0 0 Amidation C21294 "UGSIBURWRIDDTK-UHFFFAOYSA-N"

 Success  registered route 921!

1062 0 0 Amidation C8866 "SATYTGVRESMOJT-UHFFFAOYSA-N"

 Success  registered route 922!

1063 0 0 Formation_of_1,3-dithiolanes C722 "AXNCOQBNSRCGQR-UHFFFAOYSA-N"

 Success  registered route 923!

1064 0 0 Formation_of_urea_from_two_amines C44440 "RVXGWTPTIOJIRD-UHFFFAOYSA-N"

 Success  registered route 924!

1065 0 0 Steglich_esterification C31867 "YZDMAFVUISHMFV-UHFFFAOYSA-N"

 Success  registered route 925!

1066 0 0 Amidation C8059 "OEOCKEJGVCIITQ-UHFFFAOYSA-N"

 Success  registered route 926!

1067 0 0 Amidation C1602 "WCJVNOFYGXYGFG-UHFFFAOYSA-N"

 Success  registered route 927!

1068 0 0 Alpha_alkylation_of_ketone C2407 "ZHKWVPSCOFOVKQ-UHFFFAOYSA-N"

 Success  registered route 928!

1069 0 0 Amidation C26601 "VUSCGEMVKVOGIF-UHFFFAOYSA-N"

 Success  registered route 929!

1070 0 0 Amidation C16455 "RMEDOQBOVLJYDX-UHFFFAOYSA-N"

 Success  registered route 930!

1071 0 0 Amidation C15985 "BPUIRSFWYLCZDK-UHFFFAOYSA-N"

 Success  registered route 931!

1072 0 0 Nucleophilic_substitution_with_thioamide C10627 "YFNRJWQADGKRAX-UHFFFAOYSA-N"

 Success  registered route 932!

1073 0 0 Nucleophilic_substitution_with_thioamide C31899 "JNIRJKWCZGUUML-UHFFFAOYSA-N"

 Success  registered route 933!

1074 0 0 Steglich_esterification C13918 "FZXVNLASEWYDBT-UHFFFAOYSA-N"

 Success  registered route 934!

1075 0 0 Amidation C30751 "ILEMUDAQJVYUBR-UHFFFAOYSA-N"

 Success  registered route 935!

1076 0 0 Amidation C2306 "KYJVTOFXJSRGMR-UHFFFAOYSA-N"

 Success  registered route 936!

1077 0 0 Ester_amidation C10439 "OOKCZDOQBFPXBA-UHFFFAOYSA-N"

 Success  registered route 937!

1078 0 0 Reductive_amination C82705 "IMAPXTOLBMFUCR-UHFFFAOYSA-N"

 Success  registered route 938!

1079 0 0 Steglich_esterification C678 "JMKABZRQVLZKMP-UHFFFAOYSA-N"

 Success  registered route 939!

1080 0 0 Amidation C22847 "UWKMOLXBPRPLBM-UHFFFAOYSA-N"

 Success  registered route 940!

1081 0 0 Amidation C9975 "QLSUFWUEOGJURT-UHFFFAOYSA-N"

 Success  registered route 941!

1082 0 0 Amidation C13863 "OOBPFSHUNCZUBY-UHFFFAOYSA-N"

 Success  registered route 942!

1083 0 0 Amidation C8416 "IEDUUXRRBWHCQW-UHFFFAOYSA-N"

 Success  registered route 943!

1084 0 0 Ester_amidation C6131 "LXVIPPHHTAYJIW-UHFFFAOYSA-N"

 Success  registered route 944!

1085 0 0 Amidation C1382 "VURFZHBQCFSQNK-UHFFFAOYSA-N"

 Success  registered route 945!

1086 0 0 Amidation C1401 "OEFMQFVOHCBHLP-UHFFFAOYSA-N"

 Success  registered route 946!

1087 0 0 Amidation C3788 "HEZOJSXHYOLCRB-UHFFFAOYSA-N"

 Success  registered route 947!

1088 0 0 Amidation C6658 "NFHSLKKDIQNRKX-UHFFFAOYSA-N"

 Success  registered route 948!

1089 0 0 Swern_oxidation C10400 "CMUPJBQGBXLKHY-UHFFFAOYSA-N"

 Success  registered route 949!

1090 0 0 Amidation C2073 "BNTNXENXQWHSKP-UHFFFAOYSA-N"

 Success  registered route 950!

1091 0 0 Amidation C28573 "QUJOMQBGHHSWRI-UHFFFAOYSA-N"

 Success  registered route 951!

1092 0 0 Petasis-borono_Mannich_reaction C1281 "GFYOTNKFYIETKD-UHFFFAOYSA-N"

1093 0 0 Amidation C15352 "LIVRICROYPTWRS-UHFFFAOYSA-N"

 Success  registered route 953!

1094 0 0 Buchwald-Hartwig_amination C6100 "ZUVLOAOUUWQFOU-UHFFFAOYSA-N"

 Success  registered route 954!

1095 0 0 Sp3-sp2_Suzuki_coupling C4756 "MSOXWHJHAGZIKH-UHFFFAOYSA-N"

 Success  registered route 955!

1096 0 0 Amidation C82527 "GHOYRUSNPCRDIR-UHFFFAOYSA-N"

 Success  registered route 956!

1097 0 0 Amidation C15476 "USRDLWXXPHNKBB-UHFFFAOYSA-N"

 Success  registered route 957!

1098 0 0 Amidation C10874 "ITCVEUCTWLRDPC-UHFFFAOYSA-N"

 Success  registered route 958!

1099 0 0 Amidation C5997 "BIBIWDDCLSQUGA-UHFFFAOYSA-N"

 Success  registered route 959!

1100 0 0 Amidation C899 "FZVASHCIYDDMFL-UHFFFAOYSA-N"

 Success  registered route 960!

1101 0 0 Amidation C6632 "XXCNYTHYAPNDQY-UHFFFAOYSA-N"

 Success  registered route 961!

1102 0 0 Hydrogenation_of_benzene C6093 "LEXQPYMCTMZRQM-UHFFFAOYSA-N"

 Success  registered route 962!

1103 0 0 Amidation C15402 "HGUKBOHHMVWXGD-UHFFFAOYSA-N"

 Success  registered route 963!

1104 0 0 Amidation C1603 "YUGVDPXJICVPLB-UHFFFAOYSA-N"

 Success  registered route 964!

1105 0 0 Amidation C3542 "OTENLVGMSKIYLZ-UHFFFAOYSA-N"

 Success  registered route 965!

1106 0 0 Amidation C1360 "QNCXQWQUBKXTSX-UHFFFAOYSA-N"

 Success  registered route 966!

1107 0 0 Amidation C947 "ZUUHCJUCTFFCMF-UHFFFAOYSA-N"

 Success  registered route 967!

1108 0 0 Amidation C83456 "YSMNEIYXJLPLOA-UHFFFAOYSA-N"

 Success  registered route 968!

1109 0 0 Passerini_reaction C20634 "YAKIUUAPXQUGEU-UHFFFAOYSA-N"

 Success  registered route 969!

1110 0 0 N-Cbz_deprotection C8146 "QNWXUKIQSJVNRS-UHFFFAOYSA-N"

1110 0 1 Sulfonamide_Schotten-Baumann_with_amine_(intermolecular) C285312 "VJERAOTVEUDKLK-UHFFFAOYSA-N"

 Success  registered route 970!

1111 0 0 Amidation C85390 "SAYPJXMWJADRCE-UHFFFAOYSA-N"

 Success  registered route 971!

1112 0 0 Amine_alkylation C5638 "MCFMRUUMBUBRGV-UHFFFAOYSA-N"

 Success  registered route 972!

1113 0 0 Sp3-sp2_Macmillan_coupling_with_chloride_(intermolecular) C14499 "BYVHTZLWXASNFG-UHFFFAOYSA-N"

1113 0 1 Reductive_amination C285323 "ZKMJIBYVKPHHQG-UHFFFAOYSA-N"

 Success  registered route 973!

1114 0 0 Alpha_alkylation_of_ester/amide C1305 "WPLGLYZQTMZENA-UHFFFAOYSA-N"

 Success  registered route 974!

1115 0 0 Amidation C39794 "MVAWIACTJXPSAP-UHFFFAOYSA-N"

 Success  registered route 975!

1116 0 0 Amidation C15069 "KNQXNDJGVDPOSN-UHFFFAOYSA-N"

 Success  registered route 976!

1117 0 0 Amidation C7115 "UGMVKJPKQZMZKU-UHFFFAOYSA-N"

 Success  registered route 977!

1118 0 0 Amidation C32415 "ROBQLCHSXQDWEG-UHFFFAOYSA-N"

 Success  registered route 978!

1119 0 0 Amidation C1142 "JWMDCIUJPJCIMA-UHFFFAOYSA-N"

 Success  registered route 979!

1120 0 0 Amidation C14910 "ZNTOHSLRMARLLO-UHFFFAOYSA-N"

 Success  registered route 980!

1121 0 0 Hydroxy_to_fluoro C2413 "YNRBPEHVWJFOKW-UHFFFAOYSA-N"

 Success  registered route 981!

1122 0 0 Amidation C8876 "ZGJROAZBUZCTHO-UHFFFAOYSA-N"

 Success  registered route 982!

1123 0 0 Amidation C4769 "URQCIPKMHTUWBP-UHFFFAOYSA-N"

 Success  registered route 983!

1124 0 0 Formation_of_sulfonamide_from_halide_-_Shavnya_reaction C7596 "HMFFHCKOIQTSMA-UHFFFAOYSA-N"

 Success  registered route 984!

1125 0 0 Mannich_reaction C3419 "OBYGXQCROQSNDR-UHFFFAOYSA-N"

 Success  registered route 985!

1126 0 0 Amidation C84716 "BGLQMBYCJQNPGY-UHFFFAOYSA-N"

 Success  registered route 986!

1127 0 0 Amidation C8426 "JRLTZXBVYPPMPH-UHFFFAOYSA-N"

 Success  registered route 987!

1128 0 0 Amidation C18433 "NDFBKSVVKUASCT-UHFFFAOYSA-N"

 Success  registered route 988!

1129 0 0 Amidation C2365 "AOQJBHHWKYZXFO-UHFFFAOYSA-N"

1129 0 1 Amidation C285353 "PATIEKXWSXORFG-UHFFFAOYSA-N"

 Success  registered route 989!

1130 0 0 Amidation C10575 "GFTCXYDTVIIUSE-UHFFFAOYSA-N"

 Success  registered route 990!

1131 0 0 Amidation C5151 "AKWDCTOUIAETMB-UHFFFAOYSA-N"

 Success  registered route 991!

1132 0 0 Amidation C35516 "ZCLPDSDKUWWASP-UHFFFAOYSA-N"

 Success  registered route 992!

1133 0 0 Amidation C79657 "DURBHPZRTCPDPC-UHFFFAOYSA-N"

 Success  registered route 993!

1134 0 0 Sp3-sp2_Macmillan_coupling_with_bromide_(intermolecular) C7455 "BUOXSSFHPANDGR-UHFFFAOYSA-N"

 Success  registered route 994!

1135 0 0 Sp2-sp2_Suzuki_coupling C82790 "WGPOVBVNNQSGMO-UHFFFAOYSA-N"

 Success  registered route 995!

1136 0 0 Petasis-borono_Mannich_reaction C5666 "UMKQGKPJZAJAOK-UHFFFAOYSA-N"

 Success  registered route 996!

1137 0 0 Amidation C1366 "AZDQXSSEMYQDTA-UHFFFAOYSA-N"

 Success  registered route 997!

1138 0 0 Amidation C14701 "DZZJAVFDEJKWKN-UHFFFAOYSA-N"

 Success  registered route 998!

1139 0 0 Amidation C5958 "JHIZANCYCGQYNV-UHFFFAOYSA-N"

 Success  registered route 999!

1140 0 0 Reductive_amination C41445 "TTZBCFDUPZCDLF-UHFFFAOYSA-N"

 Success  registered route 1000!

1141 0 0 Reductive_amination C9826 "TVKHXLKOZGSFPX-UHFFFAOYSA-N"

 Success  registered route 1001!

1142 0 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C6036 "JAFBAXAMVALFBL-UHFFFAOYSA-N"

 Success  registered route 1002!

1143 0 0 Amidation C1349 "FGJOWJHHEOWVGK-UHFFFAOYSA-N"

 Success  registered route 1003!

1144 0 0 Sp3-sp2_Suzuki_coupling C31965 "IHIYXEORUGHWBE-UHFFFAOYSA-N"

1144 0 1 Buchwald-Hartwig_amination C285380 "KPXXHGQJEWVWEJ-UHFFFAOYSA-N"

 Success  registered route 1004!

1145 0 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C2631 "MDGFSWJANWKXMW-UHFFFAOYSA-N"

 Success  registered route 1005!

1146 0 0 Amidation C9840 "BMFYZDOZZIDDSD-UHFFFAOYSA-N"

 Success  registered route 1006!

1147 0 0 Amidation C33915 "ZJMRYSAATNYSCO-UHFFFAOYSA-N"

 Success  registered route 1007!

1148 0 0 Amidation C1359 "REBHPYHCNJHMBG-UHFFFAOYSA-N"

 Success  registered route 1008!

1149 0 0 Sp3-sp2_Suzuki_coupling C12023 "BGTHUWNKRWKQLH-UHFFFAOYSA-N"

 Success  registered route 1009!

1150 0 0 Amidation C8031 "KPKZQXXJAPWOPZ-UHFFFAOYSA-N"

 Success  registered route 1010!

1151 0 0 Isocyanate_to_urea C43738 "OLOCMQZJQFEPLN-UHFFFAOYSA-N"

 Success  registered route 1011!

1152 0 0 Amidation C8874 "QEGXPACMNFTTCL-UHFFFAOYSA-N"

 Success  registered route 1012!

1153 0 0 Amidation C2344 "REDBGCCRMBTLLG-UHFFFAOYSA-N"

 Success  registered route 1013!

1154 0 0 Amidation C5444 "FCBNDCMPKDFMCI-UHFFFAOYSA-N"

 Success  registered route 1014!

1155 0 0 Amine_alkylation C8853 "HMWULAZTFKYULC-UHFFFAOYSA-N"

 Success  registered route 1015!

1156 0 0 Corey-House_synthesis_(intermolecular) C9904 "UCRHKGUMOXDCDY-UHFFFAOYSA-N"

1156 0 1 Synthesis_of_organolithium C285399 "QCPABZRJGHHWTP-UHFFFAOYSA-N"

1156 0 2 Reductive_amination C286470 "MFJCRFKYEWVDLA-UHFFFAOYSA-N"

 Success  registered route 1016!

1157 0 0 Sp3-sp2_Suzuki_coupling C3260 "WYESEHOBLJZBFR-UHFFFAOYSA-N"

 Success  registered route 1017!

1158 0 0 Sp3-sp2_Suzuki_coupling C3300 "ZSLFMECWUGWMJH-UHFFFAOYSA-N"

 Success  registered route 1018!

1159 0 0 Steglich_esterification C5645 "FDDRMMFQTUMLQU-UHFFFAOYSA-N"

 Success  registered route 1019!

1160 0 0 Amidation C2404 "MZHCZVDDNWLPPV-UHFFFAOYSA-N"

 Success  registered route 1020!

1161 0 0 Aziridine_+_amine_coupling C7461 "AIXXEJFHVOHRFJ-UHFFFAOYSA-N"

 Success  registered route 1021!

1162 0 0 N-nucleophilic_aromatic_substitution C712 "YOAMNICQXAJQJO-UHFFFAOYSA-N"

 Success  registered route 1022!

1163 0 0 Amidation C10704 "CYLXWSNDBHUDSS-UHFFFAOYSA-N"

 Success  registered route 1023!

1164 0 0 Amidation C16329 "YGPOMGOFWDKROT-UHFFFAOYSA-N"

 Warning  SMILES changed during compound registration: CC(NC(=O)c1cc[nH]n1)C1CNC1 --> CC(NC(=O)c1ccn[nH]1)C1CNC1!

 Success  registered route 1024!

1165 0 0 Amidation C29152 "RHLZBBZPBAUQBC-UHFFFAOYSA-N"

 Success  registered route 1025!

1166 0 0 Amidation C22223 "ZFTJJBVPUXZCMY-UHFFFAOYSA-N"

 Success  registered route 1026!

1167 0 0 Amidation C9207 "RHQJYRUFYUHRDN-UHFFFAOYSA-N"

 Success  registered route 1027!

1168 0 0 Formation_of_urea_from_two_amines C8906 "WSZYMCQJXAPKIF-UHFFFAOYSA-N"

 Success  registered route 1028!

1169 0 0 Sp3-sp2_Suzuki_coupling C2514 "OBMSQRRNSRJRBN-UHFFFAOYSA-N"

 Success  registered route 1029!

1170 0 0 Ester_amidation C1238 "GFCHJLUTXGTXAR-UHFFFAOYSA-N"

 Success  registered route 1030!

1171 0 0 Amidation C7825 "HWPXHJBEHCQNEL-UHFFFAOYSA-N"

 Success  registered route 1031!

1172 0 0 Amidation C934 "UQJVNWDNXJUWRQ-UHFFFAOYSA-N"

 Success  registered route 1032!

1173 0 0 Formation_of_urea_from_two_amines C1455 "ILAOIAQOAHWDBJ-UHFFFAOYSA-N"

 Success  registered route 1033!

1174 0 0 Minisci_reaction_with_carboxylic_acid_(intermolecular) C6276 "FOELTRWJVGYBGD-UHFFFAOYSA-N"

 Success  registered route 1034!

1175 0 0 Amidation C20940 "DRKPVRIBDAVVDE-UHFFFAOYSA-N"

 Success  registered route 1035!

1176 0 0 Amidation C6066 "VSZVJPLKYBCKOO-UHFFFAOYSA-N"

 Success  registered route 1036!

1177 0 0 Hydroxy_to_fluoro C10320 "BUCJQHMDCWUKLE-UHFFFAOYSA-N"

 Success  registered route 1037!

1178 0 0 Amidation C21077 "DCTJOWXNIBHWEL-UHFFFAOYSA-N"

 Success  registered route 1038!

1179 0 0 Amidation C13624 "ZQFYEICALXCDIF-UHFFFAOYSA-N"

 Success  registered route 1039!

1180 0 0 Amidation C1338 "SJYNETFQBPJTBE-UHFFFAOYSA-N"

 Success  registered route 1040!

1181 0 0 Amidation C8604 "RNMVOHQXDNXOGF-UHFFFAOYSA-N"

 Success  registered route 1041!

1182 0 0 Amidation C23130 "UGZOXRFYKLKGPI-UHFFFAOYSA-N"

 Success  registered route 1042!

1183 0 0 Sulfonamide_Schotten-Baumann_with_amine_(intermolecular) C7644 "FQPSGVBYUDGJAR-UHFFFAOYSA-N"

 Success  registered route 1043!

1184 0 0 Amidation C7170 "VYSLTJZGYMQXGZ-UHFFFAOYSA-N"

 Success  registered route 1044!

1185 0 0 Formation_of_sulfonamide_from_halide_-_Shavnya_reaction C7592 "XNDMHKZPZBSGFI-UHFFFAOYSA-N"

 Success  registered route 1045!

1186 0 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C7642 "JIBIHHYZANIHBI-UHFFFAOYSA-N"

 Success  registered route 1046!

1187 0 0 Alpha_alkylation_of_aldehyde C4693 "QLEQENYLQKJYBV-UHFFFAOYSA-N"

 Success  registered route 1047!

1188 0 0 Sp3-sp2_Macmillan_coupling_with_bromide_(intermolecular) C7229 "LUOQOSYKLXGGAL-UHFFFAOYSA-N"

 Success  registered route 1048!

1189 0 0 Amine_alkylation C8846 "VIZQUAMFAFOSLS-UHFFFAOYSA-N"

1189 0 1 Amine_alkylation C285467 "DBKAEENGVMWKAT-UHFFFAOYSA-N"

 Success  registered route 1049!

1190 0 0 Amidation C18151 "KSBHXPKVWQLEFJ-UHFFFAOYSA-N"

 Success  registered route 1050!

1191 0 0 Formation_of_sulfonamide_from_halide_-_Shavnya_reaction C12320 "YFCVSAJHUPTKJW-UHFFFAOYSA-N"

 Success  registered route 1051!

1192 0 0 Amidation C9783 "DCIDXVFUCNBFDV-UHFFFAOYSA-N"

 Success  registered route 1052!

1193 0 0 Amidation C9801 "JJTOBGQZAVXZPQ-UHFFFAOYSA-N"

 Success  registered route 1053!

1194 0 0 Amidation C8857 "XGCYOVHIYMBSNK-UHFFFAOYSA-N"

 Success  registered route 1054!

1195 0 0 Ester_amidation C8929 "GUENUKMUPWZNRC-UHFFFAOYSA-N"

 Success  registered route 1055!

1196 0 0 Ester_amidation C29686 "ADCBIDCUFYHYHT-UHFFFAOYSA-N"

 Success  registered route 1056!

1197 0 0 Nucleophilic_substitution_with_thioamide C6027 "HISKBNLAAGHDBQ-UHFFFAOYSA-N"

 Success  registered route 1057!

1198 0 0 Oxazole_synthesis C6510 "GKFRYZROBLFNAX-UHFFFAOYSA-N"

1198 0 1 Amidation C285486 "QBWDUEBTEMASIU-UHFFFAOYSA-N"

 Success  registered route 1058!

1199 0 0 Amidation C1399 "HXJSUAIOIMKJMI-UHFFFAOYSA-N"

 Success  registered route 1059!

1200 0 0 Amidation C21083 "YCXUBEVMZITSJB-UHFFFAOYSA-N"

 Success  registered route 1060!

1201 0 0 Pinner_reaction_(carboxylate_ester) C27042 "SRBFBJJNWAODEI-UHFFFAOYSA-N"

 Success  registered route 1061!

1202 0 0 Ester_amidation C28490 "FEMUIDDNNZKUSG-UHFFFAOYSA-N"

 Success  registered route 1062!

1203 0 0 Amidation C8760 "CTZSCWGDEJRQJB-UHFFFAOYSA-N"

 Success  registered route 1063!

1204 0 0 Amine_alkylation C2403 "BLPQLXCUNUOCSN-UHFFFAOYSA-N"

 Success  registered route 1064!

1205 0 0 Amidation C4570 "ZPPAONKPBQFBHG-UHFFFAOYSA-N"

 Success  registered route 1065!

1206 0 0 Amidation C25347 "VAYQUYQSWAUBAD-UHFFFAOYSA-N"

 Success  registered route 1066!

1207 0 0 Amine_alkylation C5169 "ZHYYBDZASCMDMP-UHFFFAOYSA-N"

 Success  registered route 1067!

1208 0 0 Amidation C20140 "KKLAVPWGXVYYKK-UHFFFAOYSA-N"

 Success  registered route 1068!

1209 0 0 Aziridine_+_amine_coupling C2474 "CCZWIXDZBGEKGT-UHFFFAOYSA-N"

 Success  registered route 1069!

1210 0 0 Hydroxy_to_fluoro C2410 "XHBNPKKACABHBA-UHFFFAOYSA-N"

 Success  registered route 1070!

1211 0 0 Amidation C10519 "FKANEGWUQJTCRE-UHFFFAOYSA-N"

1211 0 1 Amidation C285520 "HXEQNEMHAQXSFA-UHFFFAOYSA-N"

 Success  registered route 1071!

1212 0 0 Amidation C20970 "CPOAYBILPJRGSY-UHFFFAOYSA-N"

 Success  registered route 1072!

1213 0 0 Amidation C3863 "JTEJVNYAELMDNE-UHFFFAOYSA-N"

 Success  registered route 1073!

1214 0 0 Steglich_esterification C27189 "HASBCQSXHBUGKF-UHFFFAOYSA-N"

 Success  registered route 1074!

1215 0 0 Alpha_alkylation_of_ketone C21569 "VGRJTUCBCKJLAN-UHFFFAOYSA-N"

 Success  registered route 1075!

1216 0 0 Formation_of_urea_from_two_amines C1403 "AYFIZZAEOIDREF-UHFFFAOYSA-N"

 Success  registered route 1076!

1217 0 0 Alpha_alkylation_of_ester/amide C29720 "CLLVVLWRAOVKKD-UHFFFAOYSA-N"

 Success  registered route 1077!

1218 0 0 Amidation C7419 "NETFXXUKTZUOOD-UHFFFAOYSA-N"

 Success  registered route 1078!

1219 0 0 Amidation C8485 "AHRHQIZZBXAYPC-UHFFFAOYSA-N"

 Success  registered route 1079!

1220 0 0 Amidation C8952 "GQBDKUUPQMEZIN-UHFFFAOYSA-N"

 Success  registered route 1080!

1221 0 0 Nucleophilic_substitution_with_thiol C6034 "XLSHTFUPRUSZEF-UHFFFAOYSA-N"

 Success  registered route 1081!

1222 0 0 Nucleophilic_substitution_with_thiol C1132 "BGMXVHWUBCMRIH-UHFFFAOYSA-N"

 Success  registered route 1082!

1223 0 0 Amidation C29440 "MQWQJMQDCPGAHX-UHFFFAOYSA-N"

 Success  registered route 1083!

1224 0 0 Amidation C1414 "YASWEVOWOCSSRH-UHFFFAOYSA-N"

 Success  registered route 1084!

1225 0 0 Amidation C9982 "CDOCJOQYVNDDOB-UHFFFAOYSA-N"

 Success  registered route 1085!

1226 0 0 Amidation C7466 "CNXDKPPPZXXLRJ-UHFFFAOYSA-N"

 Success  registered route 1086!

1227 0 0 Alpha_alkylation_of_ketone C11231 "PZDAOJKGMJJGDC-UHFFFAOYSA-N"

 Success  registered route 1087!

1228 0 0 Amine_alkylation C8841 "RFEZRTLYXHCHBF-UHFFFAOYSA-N"

 Success  registered route 1088!

1229 0 0 Amidation C1386 "ZRDHPXNIJIQHOP-UHFFFAOYSA-N"

 Success  registered route 1089!

1230 0 0 Sulfonamide_Schotten-Baumann_with_amine_(intermolecular) C29031 "QFZBMJQUWWNYIL-UHFFFAOYSA-N"

 Success  registered route 1090!

1231 0 0 Formation_of_urea_from_two_amines C14594 "BDYCYAQORNKNIO-UHFFFAOYSA-N"

 Success  registered route 1091!

1232 0 0 Amidation C1304 "KVVWFFVCOKKVCV-UHFFFAOYSA-N"

 Success  registered route 1092!

1233 0 0 Nucleophilic_substitution_with_thiol C6773 "PIQMDRWGSNHVCK-UHFFFAOYSA-N"

1233 0 1 Petasis-borono_Mannich_reaction C285568 "UPJLNSAZIUXSAU-UHFFFAOYSA-N"

 Success  registered route 1093!

1234 0 0 Chan-Lam_coupling_(amination) C6812 "WZRAVWCMDRGDQR-UHFFFAOYSA-N"

 Success  registered route 1094!

1235 0 0 Heck_reaction_(intermolecular) C10650 "OHATYSATAWMYKE-UHFFFAOYSA-N"

1235 0 1 Stille_coupling C285575 "RYPTVXXUHNSBEA-UHFFFAOYSA-N"

 Success  registered route 1095!

1236 0 0 Amidation C1394 "WLNDFJQVFATSKU-UHFFFAOYSA-N"

 Success  registered route 1096!

1237 0 0 Sulfonamide_Schotten-Baumann_with_amine_(intermolecular) C7479 "FDJUGHGTFDESJB-UHFFFAOYSA-N"

 Success  registered route 1097!

1238 0 0 NHK_reaction C15051 "MHXYYYOIIYIRRP-UHFFFAOYSA-N"

 Success  registered route 1098!

1239 0 0 Amidation C13878 "QXBXKJNMGXBAQW-UHFFFAOYSA-N"

 Success  registered route 1099!

1240 0 0 Aziridine_+_amine_coupling C8132 "OHYSAQUMFUOGOB-UHFFFAOYSA-N"

 Success  registered route 1100!

1241 0 0 Amine_alkylation C6280 "VQRXHIVVUXYAFH-UHFFFAOYSA-N"

1241 0 1 Nucleophilic_substitution_with_thiol C285601 "ISHOOYIFRXQZPE-UHFFFAOYSA-N"

 Success  registered route 1101!

1242 0 0 Formation_of_sulfonamide_from_halide_-_Shavnya_reaction C9179 "TXZMGEIPDXEFES-UHFFFAOYSA-N"

 Success  registered route 1102!

1243 0 0 Carboxylic_acid_+_hydrazine_condensation C961 "CLKVTKUYRZLTQV-UHFFFAOYSA-N"

 Success  registered route 1103!

1244 0 0 Amidation C1002 "XZXXEYWXKJBZSC-UHFFFAOYSA-N"

 Success  registered route 1104!

1245 0 0 N-nucleophilic_aromatic_substitution C3919 "KMXPQZZEYXRUBR-UHFFFAOYSA-N"

 Success  registered route 1105!

1246 0 0 Stille_coupling C4175 "IMBLIAFPKKGXAI-UHFFFAOYSA-N"

 Success  registered route 1106!

1247 0 0 Amidation C35792 "ATECCOVAGPARCV-UHFFFAOYSA-N"

 Success  registered route 1107!

1248 0 0 Amidation C22039 "PYOGJXOXCOUBHM-UHFFFAOYSA-N"

 Success  registered route 1108!

1249 0 0 Appel_bromination C9393 "WYAUXRZNPDFNGB-UHFFFAOYSA-N"

 Success  registered route 1109!

1250 0 0 Amidation C28016 "VNNGVJKCEHEFDX-UHFFFAOYSA-N"

 Success  registered route 1110!

1251 0 0 Alpha_alkylation_of_ester/amide C4809 "LHBRDYHDWDKHLQ-UHFFFAOYSA-N"

 Success  registered route 1111!

1252 0 0 Amidation C21997 "FKUQYJCHXNTLRM-UHFFFAOYSA-N"

 Success  registered route 1112!

1253 0 0 Simmons-Smith_reaction C10158 "FJTKEURQIPWLEI-UHFFFAOYSA-N"

 Success  registered route 1113!

1254 0 0 Sp3-sp2_Suzuki_coupling C1799 "TYJWRLDKTXVLTC-UHFFFAOYSA-N"

 Success  registered route 1114!

1255 0 0 Amidation C8891 "GFQVOONUDCSYCR-UHFFFAOYSA-N"

 Success  registered route 1115!

1256 0 0 Heck_reaction_(intermolecular) C20946 "YQOYVOMTPHOFRP-UHFFFAOYSA-N"

 Success  registered route 1116!

1257 0 0 Sp3-sp2_Suzuki_coupling C1109 "XPBCDWNBSRTCDV-UHFFFAOYSA-N"

 Success  registered route 1117!

1258 0 0 Amine_alkylation C5394 "RYAINGBGWASFKK-UHFFFAOYSA-N"

 Success  registered route 1118!

1259 0 0 Amidation C21168 "FKMAEMGSWVNCKY-UHFFFAOYSA-N"

 Success  registered route 1119!

1260 0 0 Amidation C13661 "XFTRGEJLGGFFLL-UHFFFAOYSA-N"

 Success  registered route 1120!

1261 0 0 Aziridine_+_amine_coupling C2503 "ASMMGLVTGJDGEB-UHFFFAOYSA-N"

 Success  registered route 1121!

1262 0 0 Alpha_alkylation_of_ketone C8131 "VZVGFJIPTVRBAH-UHFFFAOYSA-N"

 Success  registered route 1122!

1263 0 0 Nucleophilic_substitution_with_thioamide C13681 "YQLMJTHUYFOGIH-UHFFFAOYSA-N"

 Success  registered route 1123!

1264 0 0 Amidation C34794 "VDTHFFGZXLSRON-UHFFFAOYSA-N"

 Success  registered route 1124!

1265 0 0 Amidation C33363 "WGYSJYZCOQJSGJ-UHFFFAOYSA-N"

 Success  registered route 1125!

1266 0 0 Amidation C5959 "ODTPIPWYWNRRDZ-UHFFFAOYSA-N"

 Success  registered route 1126!

1267 0 0 Amidation C13045 "BODYQHRQNOBDAC-UHFFFAOYSA-N"

 Success  registered route 1127!

1268 0 0 Amidation C2487 "LWUPXCRKWPNRJC-UHFFFAOYSA-N"

1268 0 1 N-nucleophilic_aromatic_substitution C285661 "DOWDYGPPUUTHQL-UHFFFAOYSA-N"

 Success  registered route 1128!

1269 0 0 Reductive_amination C82666 "GWGHKZDVFZVLKE-UHFFFAOYSA-N"

 Success  registered route 1129!

1270 0 0 Amidation C13636 "OORLBSFUVZGRGR-UHFFFAOYSA-N"

 Success  registered route 1130!

1271 0 0 Amidation C10690 "FCBYOGTWIGJNNJ-UHFFFAOYSA-N"

 Success  registered route 1131!

1272 0 0 Amine_alkylation C2123 "WUBOLPOQHKSMNV-UHFFFAOYSA-N"

 Success  registered route 1132!

1273 0 0 Formation_of_sulfonamide_from_halide_-_Shavnya_reaction C86181 "POMAHRVANROYCT-UHFFFAOYSA-N"

 Success  registered route 1133!

1275 0 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C5404 "JPQPMWWMNLJLFA-UHFFFAOYSA-N"

 Success  registered route 1134!

1276 0 0 Reductive_amination C82412 "UYZNFIDKOOLBFF-UHFFFAOYSA-N"

 Success  registered route 1135!

1277 0 0 Amide_Schotten-Baumann_with_amine C86222 "HZKRCMBVUHIKHS-UHFFFAOYSA-N"

1277 0 1 Carboxylic_acid_to_acid_chloride C285681 "HSNFKKGOEAEDEH-UHFFFAOYSA-N"

 Success  registered route 1136!

1278 0 0 Steglich_esterification C91439 "TYDVZPFYBLQFDI-UHFFFAOYSA-N"

 Success  registered route 1137!

1279 0 0 Amidation C17086 "MFVZOPZOZQGRRS-UHFFFAOYSA-N"

 Success  registered route 1138!

1280 0 0 Amidation C9566 "WQQLBSLYPKFCKZ-UHFFFAOYSA-N"

 Success  registered route 1139!

1281 0 0 N-nucleophilic_aromatic_substitution C15184 "UDMHBJKMQVXFEZ-UHFFFAOYSA-N"

 Success  registered route 1140!

1282 0 0 Nucleophilic_substitution_with_thiol C6035 "SXQLOIUOKJFCTE-UHFFFAOYSA-N"

 Success  registered route 1141!

1283 0 0 Baeyer-Villiger_oxidation C3119 "FGJMRRSNHUUVNO-UHFFFAOYSA-N"

 Success  registered route 1142!

1284 0 0 Amidation C10549 "QLCVGBHOPHCWJD-UHFFFAOYSA-N"

 Success  registered route 1143!

1285 0 0 Amidation C1375 "NWUVTHIOIUIXCU-UHFFFAOYSA-N"

 Success  registered route 1144!

1286 0 0 Amine_alkylation C759 "OLVLBHADGADCLT-UHFFFAOYSA-N"

 Success  registered route 1145!

1287 0 0 Amidation C7139 "NUBNQKVFZUNLSK-UHFFFAOYSA-N"

 Success  registered route 1146!

1288 0 0 Amidation C1883 "KCHUUQFYYOTEQS-UHFFFAOYSA-N"

 Success  registered route 1147!

1289 0 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C11851 "LLBDRWNYPBEFLX-UHFFFAOYSA-N"

 Success  registered route 1148!

1290 0 0 N-Boc_deprotection C6044 "ZSANGZPGNFVAPL-UHFFFAOYSA-N"

 Success  registered route 1149!

1291 0 0 Alpha_alkylation_of_aldehyde C15052 "HXNOWCAYKFJUHZ-UHFFFAOYSA-N"

 Success  registered route 1150!

1292 0 0 Amidation C4118 "JXTZNDLJXPZAEM-UHFFFAOYSA-N"

 Success  registered route 1151!

1293 0 0 Amidation C14136 "GLKOPRGBSIQCBP-UHFFFAOYSA-N"

 Success  registered route 1152!

1294 0 0 Sulfonamide_Schotten-Baumann_with_amine_(intermolecular) C40896 "NRWGAZDGIQPBJK-UHFFFAOYSA-N"

 Success  registered route 1153!

1295 0 0 Steglich_esterification C20308 "HJXNHEVQRCOAHH-UHFFFAOYSA-N"

 Success  registered route 1154!

1296 0 0 Amidation C11833 "KRQYBBCCQUVOQQ-UHFFFAOYSA-N"

 Success  registered route 1155!

1297 0 0 Sp3-sp2_Macmillan_coupling_with_chloride_(intermolecular) C40856 "DFDDAHMVJZQNIS-UHFFFAOYSA-N"

 Success  registered route 1156!

1298 0 0 Amidation C7141 "RPYFJMJVSOYEFT-UHFFFAOYSA-N"

 Success  registered route 1157!

1299 0 0 Amidation C1357 "IBUVLDQWYDBITO-UHFFFAOYSA-N"

 Success  registered route 1158!

1300 0 0 Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide C1814 "CFGUFSRARCDEJB-UHFFFAOYSA-N"

 Success  registered route 1159!

1301 0 0 N-nucleophilic_aromatic_substitution C540 "GYLBIGBYLJSRMM-UHFFFAOYSA-N"

 Success  registered route 1160!

1302 0 0 Amidation C16846 "VIUGNCAMDRTQJK-UHFFFAOYSA-N"

 Success  registered route 1161!

1303 0 0 Amidation C5949 "JSOLCRWBOHDHLA-UHFFFAOYSA-N"

 Success  registered route 1162!

1304 0 0 N-nucleophilic_aromatic_substitution C35886 "AFJPCOIBOPEZRQ-UHFFFAOYSA-N"

 Success  registered route 1163!

1305 0 0 Amidation C532 "SOLMNNBILPZOSX-UHFFFAOYSA-N"

 Success  registered route 1164!

1306 0 0 Amidation C15494 "YLJPPWLVJABBLI-UHFFFAOYSA-N"

 Success  registered route 1165!

1307 0 0 Amidation C15471 "CPAZNKHVDOFCMV-UHFFFAOYSA-N"

 Success  registered route 1166!

1308 0 0 Amidation C13067 "DRDOJMCYICGXFL-UHFFFAOYSA-N"

 Success  registered route 1167!

1309 0 0 Iodo_N-arylation C32616 "BIIVMCIDBUMVDU-UHFFFAOYSA-N"

 Success  registered route 1168!

1310 0 0 Hydrogenation_of_pyridine C787 "WOKNKIOABYEMDE-UHFFFAOYSA-N"

1310 0 1 Sp3-sp2_Macmillan_coupling_with_bromide_(intermolecular) C285749 "XSGQABMLMYVSMO-UHFFFAOYSA-N"

 Success  registered route 1169!

1311 0 0 Amidation C7188 "GYBDNCZJKSYHSE-UHFFFAOYSA-N"

 Success  registered route 1170!

1312 0 0 Amidation C11631 "QVLGSSQYZVYUGJ-UHFFFAOYSA-N"

 Success  registered route 1171!

1313 0 0 Amidation C10551 "CKCGJIQEJLLOHK-UHFFFAOYSA-N"

 Success  registered route 1172!

1314 0 0 Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide C91922 "VKCFWKQFXUVIIM-UHFFFAOYSA-N"

 Success  registered route 1173!

1315 0 0 Amidation C43172 "ZNJBUCCMBIUDOR-UHFFFAOYSA-N"

 Warning  SMILES changed during compound registration: NCc1c[nH]cn1 --> NCc1cnc[nH]1!

 Success  registered route 1174!

1316 0 0 Amidation C17988 "YDXIBDJDTVMVDS-UHFFFAOYSA-N"

 Success  registered route 1175!

1317 0 0 Amidation C16894 "NPIYBZYEPOASSM-UHFFFAOYSA-N"

 Success  registered route 1176!

1318 0 0 Reductive_amination C7512 "WKWSTPQELFYSBR-UHFFFAOYSA-N"

 Success  registered route 1177!

1319 0 0 Sp3-sp2_Suzuki_coupling C4805 "LZCWESDQKOJPRL-UHFFFAOYSA-N"

 Success  registered route 1178!

1320 0 0 Amidation C5313 "BSIJAQBIVQHURV-UHFFFAOYSA-N"

 Success  registered route 1179!

1321 0 0 Amidation C38131 "BRBJVKBLSPYJTQ-UHFFFAOYSA-N"

 Success  registered route 1180!

1322 0 0 Amidation C7149 "SBCUWSBVVFFXMM-UHFFFAOYSA-N"

 Success  registered route 1181!

1323 0 0 Alpha_alkylation_of_ketone C13570 "OSHPMDKWLAXVLW-UHFFFAOYSA-N"

 Success  registered route 1182!

1324 0 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C11216 "UNJDLWREQAMHBE-UHFFFAOYSA-N"

 Success  registered route 1183!

1325 0 0 Amine_alkylation C4766 "RFJGYVZIVNNSCI-UHFFFAOYSA-N"

 Success  registered route 1184!

1326 0 0 Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide C2044 "ZCDJYTCOFFVDFA-UHFFFAOYSA-N"

 Success  registered route 1185!

1327 0 0 Ester_amidation C7417 "UHCYCFVXMGQYLA-UHFFFAOYSA-N"

 Success  registered route 1186!

1328 0 0 Amine_alkylation C12946 "OMEWLDYIFBMQQV-UHFFFAOYSA-N"

 Success  registered route 1187!

1329 0 0 Amidation C25127 "VMVJFLKGCWCHKW-UHFFFAOYSA-N"

 Success  registered route 1188!

1330 0 0 Amidation C10845 "QHXZCCYDVDNOIS-UHFFFAOYSA-N"

 Success  registered route 1189!

1331 0 0 Amidation C23295 "UQGFVTTVRVRYFR-UHFFFAOYSA-N"

 Success  registered route 1190!

1332 0 0 Amidation C25702 "VLNCLLLQZBZMCZ-UHFFFAOYSA-N"

 Success  registered route 1191!

1333 0 0 Amidation C1719 "CQSLSCYKXAPOGE-UHFFFAOYSA-N"

 Success  registered route 1192!

1334 0 0 Sulfonamide_Schotten-Baumann_with_amine_(intermolecular) C7660 "NEEWPLZUMQNHBI-UHFFFAOYSA-N"

 Success  registered route 1193!

1335 0 0 Amine_alkylation C43550 "ZBXDTHJRDBKMNJ-UHFFFAOYSA-N"

 Success  registered route 1194!

1336 0 0 Aryl_halide_to_aniline C20907 "XNZBNQSOCXCBBB-UHFFFAOYSA-N"

 Success  registered route 1195!

1337 0 0 Amine_alkylation C760 "VJCYTBKJYKZSPV-UHFFFAOYSA-N"

 Success  registered route 1196!

1338 0 0 Alpha_alkylation_of_aldehyde C17612 "HUQKWYASCUHDLP-UHFFFAOYSA-N"

 Success  registered route 1197!

1339 0 0 Sp2-sp2_Negishi_coupling_(intermolecular) C6610 "QMSHCDDWKOOQIQ-UHFFFAOYSA-N"

 Success  registered route 1198!

1340 0 0 Ester_amidation C92920 "IZKZLQCBDVJIRW-UHFFFAOYSA-N"

 Success  registered route 1199!

1341 0 0 Amidation C28323 "XRCDSEZPXYCOLD-UHFFFAOYSA-N"

 Success  registered route 1200!

1342 0 0 Reductive_amination C92925 "DVPZBLCJPRLATH-UHFFFAOYSA-N"

 Success  registered route 1201!

1343 0 0 Alpha_alkylation_of_ketone C4658 "HWBLWNNWIGXBNO-UHFFFAOYSA-N"

 Success  registered route 1202!

1344 0 0 1,2,4-Oxadiazole_synthesis_(amidoxime_+_carboxylate) C18114 "UHISTFBIGPGRMK-UHFFFAOYSA-N"

 Success  registered route 1203!

1345 0 0 Amidation C22220 "LDOKSSWQCPKARK-UHFFFAOYSA-N"

 Success  registered route 1204!

1346 0 0 Amidation C13262 "ZKAJGRJFQFGLLL-UHFFFAOYSA-N"

 Success  registered route 1205!

1347 0 0 Nucleophilic_substitution_with_thiol C8064 "BNWUDFFUSWDMML-UHFFFAOYSA-N"

 Success  registered route 1206!

1348 0 0 Amidation C4774 "PYBOZBRLIMDYOY-UHFFFAOYSA-N"

 Success  registered route 1207!

1349 0 0 Amidation C5356 "TXUZFYUKGKNOMI-UHFFFAOYSA-N"

 Success  registered route 1208!

1350 0 0 Chan-Lam_coupling_of_amides,_sulfonamides,_and_imides C31916 "QUEIHHGXYURJMF-UHFFFAOYSA-N"

 Success  registered route 1209!

1351 0 0 Amine_alkylation C2616 "HPDGQSVLUHUNOU-UHFFFAOYSA-N"

1351 0 1 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C285838 "FHGAANVPENWOLF-UHFFFAOYSA-N"

 Success  registered route 1210!

1352 0 0 Amidation C13635 "DSHXVVHRVRWWBZ-UHFFFAOYSA-N"

 Success  registered route 1211!

1353 0 0 Amidation C22036 "IXOANNXJRWRLSD-UHFFFAOYSA-N"

 Success  registered route 1212!

1354 0 0 Nucleophilic_substitution_with_thiol C31930 "RBPJKPBEDYIOQL-UHFFFAOYSA-N"

 Success  registered route 1213!

1355 0 0 Amine_alkylation C2536 "OKSDMMSSFWTMDL-UHFFFAOYSA-N"

1355 0 1 Aromatic_bromination C285852 "KWMFJCDOMJZLBW-UHFFFAOYSA-N"

 Success  registered route 1214!

1356 0 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C5401 "MWSDBUDWLOMHAE-UHFFFAOYSA-N"

 Success  registered route 1215!

1357 0 0 Sp2-sp2_Suzuki_coupling C3732 "ZXOXPYYAVFDCDK-UHFFFAOYSA-N"

 Success  registered route 1216!

1358 0 0 Amidation C94229 "UGODLXNSYTXUEC-UHFFFAOYSA-N"

 Success  registered route 1217!

1359 0 0 Ozonolysis_(intermolecular) C8903 "UKLVECSDHSHYKS-UHFFFAOYSA-N"

1359 0 1 Sp2-sp2_Suzuki_coupling C285864 "GNTYQIHVJLKXLT-UHFFFAOYSA-N"

 Success  registered route 1218!

1360 0 0 Amidation C1353 "LOUAUNMHZDTLHZ-UHFFFAOYSA-N"

 Success  registered route 1219!

1361 0 0 Buchwald-Hartwig_amination C4546 "JCJVPBFEEQLMPB-UHFFFAOYSA-N"

 Success  registered route 1220!

1362 0 0 Formation_of_urea_from_two_amines C14073 "XGNYIJRUPNCYBP-UHFFFAOYSA-N"

 Success  registered route 1221!

1363 0 0 Van_Leusen_imidazole_synthesis C1841 "VEMKUJOKEUNKTH-UHFFFAOYSA-N"

 Success  registered route 1222!

1364 0 0 Amidation C6001 "WWTKBVZCSYFAEN-UHFFFAOYSA-N"

 Success  registered route 1223!

1365 0 0 Steglich_esterification C29374 "LVVJGEHAZDHVAF-UHFFFAOYSA-N"

 Success  registered route 1224!

1366 0 0 Amidation C87747 "VAVVBUAZZDYRRD-UHFFFAOYSA-N"

 Success  registered route 1225!

 Success  registered route 1226!

1368 0 0 Amidation C4572 "ATACZHSZICCATA-UHFFFAOYSA-N"

 Success  registered route 1227!

1369 0 0 Amidation C16798 "RRTBNFKCVDLBIR-UHFFFAOYSA-N"

 Success  registered route 1228!

1370 0 0 Formation_of_sulfonamide_from_halide_-_Shavnya_reaction C12436 "DUYGGZWMEYALFM-UHFFFAOYSA-N"

 Success  registered route 1229!

1371 0 0 Reductive_amination C15324 "IXLQNKZHEBQVQI-UHFFFAOYSA-N"

 Success  registered route 1230!

1372 0 0 Amidation C4102 "IQWZYMQRGQLZOU-UHFFFAOYSA-N"

 Success  registered route 1231!

1373 0 0 Amidation C3511 "GFAIQXCMYIWPBA-UHFFFAOYSA-N"

 Success  registered route 1232!

1374 0 0 Amidation C15369 "PFGLLURXEHPOCK-UHFFFAOYSA-N"

 Success  registered route 1233!

1375 0 0 Amidation C12140 "IFWHXWDSJNOWHX-UHFFFAOYSA-N"

 Success  registered route 1234!

1376 0 0 Amidation C5284 "ANGWTGNRJJVGJX-UHFFFAOYSA-N"

 Success  registered route 1235!

1377 0 0 Amidation C12512 "CNWCZZAACSBMEQ-UHFFFAOYSA-N"

 Success  registered route 1236!

1378 0 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C6122 "PRRYMKYLPMALBW-UHFFFAOYSA-N"

1378 0 1 Buchwald-Hartwig_amination C285890 "FTSWOMVJIXUQPN-UHFFFAOYSA-N"

 Success  registered route 1237!

1379 0 0 Sp3-sp2_Macmillan_coupling_with_bromide_(intermolecular) C9551 "TUJBPBYAHMFXCP-UHFFFAOYSA-N"

 Success  registered route 1238!

1380 0 0 Amidation C7845 "JDNYYFHSMGZRFL-UHFFFAOYSA-N"

 Success  registered route 1239!

1381 0 0 Ugi_reaction C1287 "QKDZKLODHGSJHY-UHFFFAOYSA-N"

 Success  registered route 1240!

1382 0 0 Aziridine_+_amine_coupling C9362 "JJHKJZKHZJQZCI-UHFFFAOYSA-N"

 Success  registered route 1241!

1383 0 0 Friedel-Crafts_acylation C10634 "TXAALMFVFUTAOP-UHFFFAOYSA-N"

1383 0 1 Carboxylic_acid_to_acid_chloride C285910 "TYVUQVYWGIYDHY-UHFFFAOYSA-N"

 Success  registered route 1242!

1384 0 0 Amidation C3504 "RWEBVRKWAUWERV-UHFFFAOYSA-N"

 Success  registered route 1243!

1385 0 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C9126 "SYHGTEQZJUIFDX-UHFFFAOYSA-N"

 Success  registered route 1244!

1386 0 0 Formation_of_urea_from_two_amines C3532 "RCYHJILZPFRWLW-UHFFFAOYSA-N"

 Success  registered route 1245!

1387 0 0 Amidation C20145 "GYZAOFILUIIAKQ-UHFFFAOYSA-N"

 Success  registered route 1246!

1388 0 0 N-Boc_deprotection C9376 "FWKKRHSZSZHMCS-UHFFFAOYSA-N"

 Success  registered route 1247!

1389 0 0 Amidation C6132 "DQQDJWRXBCMXIH-UHFFFAOYSA-N"

 Success  registered route 1248!

1390 0 0 Amidation C13629 "WQDYLJGBYWAYGW-UHFFFAOYSA-N"

 Success  registered route 1249!

1391 0 0 Amidation C7092 "JPZZIQFEUYXBCW-UHFFFAOYSA-N"

 Success  registered route 1250!

1392 0 0 Amidation C7116 "RTPIGKAAQCUSFW-UHFFFAOYSA-N"

 Success  registered route 1251!

1393 0 0 Amidation C20058 "JQBYUAVAPLZUQX-UHFFFAOYSA-N"

 Success  registered route 1252!

1394 0 0 Formation_of_urea_from_two_amines C6083 "SMFBGIJWOIHSTQ-UHFFFAOYSA-N"

 Success  registered route 1253!

1395 0 0 Amidation C27918 "IBVLOOXRGBJCHW-UHFFFAOYSA-N"

 Success  registered route 1254!

1396 0 0 Amidation C3827 "OJPVDAKSEAPTQE-UHFFFAOYSA-N"

 Success  registered route 1255!

1397 0 0 Amidation C4812 "VLOGXOWERDMVRP-UHFFFAOYSA-N"

 Success  registered route 1256!

1398 0 0 Hydrogenation_of_pyridine C2628 "NILYFVLXUNTUTG-UHFFFAOYSA-N"

 Success  registered route 1257!

1399 0 0 Amidation C4095 "MFZCMMKAORBXOZ-UHFFFAOYSA-N"

 Success  registered route 1258!

1400 0 0 Amidation C1613 "LQRJFVLGKSJEGN-UHFFFAOYSA-N"

 Success  registered route 1259!

1401 0 0 Carboxylic_acid_+_hydrazine_condensation C35844 "AWDDJZCLAJFCAI-UHFFFAOYSA-N"

 Success  registered route 1260!

1402 0 0 Alpha_alkylation_of_ketone C2388 "WCQICRGOXXDKIA-UHFFFAOYSA-N"

 Success  registered route 1261!

1403 0 0 Amine_alkylation C9590 "NSDGADWCIGGTNK-UHFFFAOYSA-N"

 Success  registered route 1262!

1404 0 0 Amidation C10829 "YVLAVJGZJRKIEO-UHFFFAOYSA-N"

 Success  registered route 1263!

1405 0 0 Amidation C8445 "NQGNDAMYFAXCMF-UHFFFAOYSA-N"

 Success  registered route 1264!

1406 0 0 Sp2-sp2_Suzuki_coupling C6095 "CJKOILGHLOVXNN-UHFFFAOYSA-N"

 Success  registered route 1265!

1407 0 0 Amidation C8457 "AEIDFRMVQVHORR-UHFFFAOYSA-N"

 Success  registered route 1266!

1408 0 0 Amidation C10574 "YHYKEJKTQQPYIL-UHFFFAOYSA-N"

 Success  registered route 1267!

1409 0 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C20144 "AOLCLQJMUNNQFC-UHFFFAOYSA-N"

 Success  registered route 1268!

1410 0 0 Amidation C9522 "NCZRZHLAOIEOQJ-UHFFFAOYSA-N"

 Success  registered route 1269!

1411 0 0 Amidation C3473 "FJKFFRDIVHDZAT-UHFFFAOYSA-N"

 Success  registered route 1270!

1412 0 0 Amidation C7045 "KGGJPHPTENSXJT-UHFFFAOYSA-N"

 Success  registered route 1271!

1413 0 0 Formation_of_urea_from_two_amines C10681 "LRTLCHQEZXDGPD-UHFFFAOYSA-N"

 Success  registered route 1272!

1414 0 0 Amidation C21624 "NXHRTCNOEDZCPH-UHFFFAOYSA-N"

 Success  registered route 1273!

1415 0 0 Amidation C7041 "SCPSUPJJEYGKII-UHFFFAOYSA-N"

 Success  registered route 1274!

1416 0 0 Sp3-sp2_Suzuki_coupling C758 "GITLVNUSBOZLGB-UHFFFAOYSA-N"

 Success  registered route 1275!

1417 0 0 Amidation C7140 "WMMQWHGSTLBODB-UHFFFAOYSA-N"

 Success  registered route 1276!

1418 0 0 Amidation C39173 "STBXFODHUIMPAQ-UHFFFAOYSA-N"

 Success  registered route 1277!

1419 0 0 Buchwald-Hartwig_amination C1192 "GIKLQBAMNJOQJI-UHFFFAOYSA-N"

 Success  registered route 1278!

1420 0 0 Amidation C4096 "ALNNKLRFJSRBFH-UHFFFAOYSA-N"

 Success  registered route 1279!

1421 0 0 Amidation C1392 "OLRBJBOVACWGSV-UHFFFAOYSA-N"

 Success  registered route 1280!

1422 0 0 Amidation C10571 "GEZPFGWIPNSGAO-UHFFFAOYSA-N"

 Success  registered route 1281!

1423 0 0 Chan-Lam_coupling_(amination) C736 "AJEUJXWLOADTKA-UHFFFAOYSA-N"

 Success  registered route 1282!

1424 0 0 Formation_of_carbamate_from_amine_and_alcohol C34673 "XHJOMYXOFNVJDG-UHFFFAOYSA-N"

 Success  registered route 1283!

1425 0 0 Amidation C1413 "DXSIWZMPELQDJX-UHFFFAOYSA-N"

 Success  registered route 1284!

1426 0 0 Amidation C29426 "PSEWAHCXXIBCFD-UHFFFAOYSA-N"

 Success  registered route 1285!

1427 0 0 Amidation C10567 "KRIKUQAZPILDPI-UHFFFAOYSA-N"

 Success  registered route 1286!

1428 0 0 N-nucleophilic_aromatic_substitution C4106 "UZZGPWHIXVWDFZ-UHFFFAOYSA-N"

 Success  registered route 1287!

1429 0 0 Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide C4752 "RGEDMRQLXNWHGH-UHFFFAOYSA-N"

 Success  registered route 1288!

1430 0 0 Sp2-sp2_Suzuki_coupling C31957 "ZLIGEXAOTFMWIY-UHFFFAOYSA-N"

 Success  registered route 1289!

1431 0 0 Amidation C5996 "SBMHKWRHORHXQA-UHFFFAOYSA-N"

 Success  registered route 1290!

1432 0 0 Amidation C1322 "CEMHLKLHGFCDOP-UHFFFAOYSA-N"

 Success  registered route 1291!

1433 0 0 Amidation C10869 "PXFWFYMNCCXQPY-UHFFFAOYSA-N"

 Success  registered route 1292!

1434 0 0 Alpha_alkylation_of_ketone C11184 "RWLBYOFXTWUWOG-UHFFFAOYSA-N"

 Success  registered route 1293!

1435 0 0 Amidation C36823 "BNFWVHFVEZCPPF-UHFFFAOYSA-N"

 Success  registered route 1294!

1436 0 0 Amidation C2081 "PLNOJQJYNMYLML-UHFFFAOYSA-N"

 Success  registered route 1295!

1437 0 0 Amidation C29673 "JMSLYWOGHLUQQG-UHFFFAOYSA-N"

 Success  registered route 1296!

1438 0 0 Amidation C12270 "JDXDXEWAEPMSSN-UHFFFAOYSA-N"

 Success  registered route 1297!

1439 0 0 Amidation C1311 "ZJOXVMDCMBYBRX-UHFFFAOYSA-N"

 Success  registered route 1298!

1440 0 0 Amidation C14060 "UWPFTRXOTWJPHV-UHFFFAOYSA-N"

 Success  registered route 1299!

1441 0 0 Amidation C1526 "KRMYACDXSNMVGI-UHFFFAOYSA-N"

 Success  registered route 1300!

1442 0 0 Buchwald-Hartwig_amination C6123 "CPIBTNTZBHUDNS-UHFFFAOYSA-N"

1442 0 1 Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_halide C285990 "OFFQZLYVSSIGTN-UHFFFAOYSA-N"

 Success  registered route 1301!

1443 0 0 Ester_amidation C29675 "VPRZTSOJFRBNDG-UHFFFAOYSA-N"

 Success  registered route 1302!

1444 0 0 Amidation C6021 "JKCAOPGWMBQAQI-UHFFFAOYSA-N"

 Success  registered route 1303!

1445 0 0 Amidation C33613 "PSPORJXVCMZQLN-UHFFFAOYSA-N"

 Success  registered route 1304!

1446 0 0 Amidation C29655 "KAWBAAHMUIIUOI-UHFFFAOYSA-N"

 Success  registered route 1305!

1447 0 0 Amine_alkylation C11209 "BTBDFXKRKUXPIR-UHFFFAOYSA-N"

 Success  registered route 1306!

1448 0 0 Amidation C21032 "LUVPXWSUDOENCR-UHFFFAOYSA-N"

 Success  registered route 1307!

1449 0 0 Amidation C29667 "SPUMQZRDWYQOSZ-UHFFFAOYSA-N"

 Success  registered route 1308!

1450 0 0 Amidation C3817 "MUQXCGYUEZQXBU-UHFFFAOYSA-N"

 Success  registered route 1309!

1451 0 0 Amidation C8878 "BRFFIYADVJLQLC-UHFFFAOYSA-N"

 Success  registered route 1310!

1452 0 0 Amidation C4256 "JEOYIGKKGPMNOF-UHFFFAOYSA-N"

 Success  registered route 1311!

1453 0 0 Formation_of_urea_from_two_amines C12403 "CVVQZKTUYHICCC-UHFFFAOYSA-N"

 Success  registered route 1312!

1454 0 0 Riley_oxidation C2479 "RAFCYCDJOWOOAS-UHFFFAOYSA-N"

 Success  registered route 1313!

1455 0 0 Amidation C22011 "VKVCIQZOMHUULA-UHFFFAOYSA-N"

 Success  registered route 1314!

1456 0 0 Amidation C11987 "JCQQJJVJANIEDC-UHFFFAOYSA-N"

 Success  registered route 1315!

1457 0 0 Amidation C1373 "HPZYIMYCTDBYEK-UHFFFAOYSA-N"

 Success  registered route 1316!

1458 0 0 Amidation C2418 "YKFCDWMBODQRLV-UHFFFAOYSA-N"

 Success  registered route 1317!

1459 0 0 Amidation C29842 "JTMLSSUHXRBMOA-UHFFFAOYSA-N"

 Success  registered route 1318!

1460 0 0 Amidation C11989 "LTXRWJYJSXHLHR-UHFFFAOYSA-N"

 Success  registered route 1319!

1461 0 0 Amidation C1418 "GSFKQOAHRINDLP-UHFFFAOYSA-N"

 Success  registered route 1320!

1462 0 0 Formation_of_urea_from_two_amines C5452 "ARNGBMWSRMXYCL-UHFFFAOYSA-N"

 Success  registered route 1321!

1463 0 0 Steglich_esterification C12012 "RTQXTGWAIMKSIN-UHFFFAOYSA-N"

 Success  registered route 1322!

1464 0 0 Minisci_reaction_with_carboxylic_acid_(intermolecular) C15060 "WTLZXJJEXLVAHW-UHFFFAOYSA-N"

 Success  registered route 1323!

1465 0 0 1,2,4-Oxadiazole_synthesis_(nitrile_+_carboxylic_acid) C39108 "NJZWNPRAQMACTE-UHFFFAOYSA-N"

 Success  registered route 1324!

1466 0 0 Hydroxy_to_fluoro C2375 "GOSRQBSVGZRPLI-UHFFFAOYSA-N"

 Success  registered route 1325!

1467 0 0 Amidation C9322 "GDXDBEIGTXDPSA-UHFFFAOYSA-N"

 Success  registered route 1326!

1468 0 0 Buchwald-Hartwig_(thio)etherification C2531 "LSKCKISVBNXGCT-UHFFFAOYSA-N"

1468 0 1 Aromatic_bromination C286041 "BLAICZPLIBDSAG-UHFFFAOYSA-N"

 Success  registered route 1327!

1469 0 0 Alpha_alkylation_of_sulphones C1446 "CQUDLYKHYNSNKN-UHFFFAOYSA-N"

 Success  registered route 1328!

1470 0 0 Corey-House_synthesis_(intermolecular) C5412 "ZMWSPLIMPYHVRD-UHFFFAOYSA-N"

1470 0 1 Synthesis_of_organolithium C285752 "AXVSKWDELMXCRM-UHFFFAOYSA-N"

 Success  registered route 1329!

1471 0 0 Amidation C6603 "GCAKZJRFFNZIMB-UHFFFAOYSA-N"

 Success  registered route 1330!

1472 0 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C7674 "FVNJSOWLEHGULL-UHFFFAOYSA-N"

 Success  registered route 1331!

1473 0 0 Amidation C872 "DCPARYBUYLWDFA-UHFFFAOYSA-N"

 Success  registered route 1332!

1474 0 0 Ethenyl_to_formyl C8144 "CZSVMTMCGSPTJV-UHFFFAOYSA-N"

1474 0 1 NHK_reaction C286050 "NKKWUZADGWNOMZ-UHFFFAOYSA-N"

 Success  registered route 1333!

1475 0 0 Amine_alkylation C8152 "CQGFXNLTTLLTME-UHFFFAOYSA-N"

 Success  registered route 1334!

1476 0 0 Amidation C83786 "YVEDCTAHRCLMTN-UHFFFAOYSA-N"

 Success  registered route 1335!

1477 0 0 Amidation C21087 "NLTCJEMUNHLQBH-UHFFFAOYSA-N"

 Warning  SMILES changed during compound registration: c1cc(C2CCNC2)[nH]n1 --> c1cc(C2CCNC2)n[nH]1!

 Success  registered route 1336!

1478 0 0 Alpha_alkylation_of_ketone C11213 "ABFQQZLULDEORM-UHFFFAOYSA-N"

 Success  registered route 1337!

1479 0 0 1,2,4-Oxadiazole_synthesis_(nitrile_+_carboxylic_acid) C936 "ADJXGRRNYYGIST-UHFFFAOYSA-N"

 Success  registered route 1338!

1480 0 0 Alpha_alkylation_of_ketone C9352 "NZCPRRIBNYPZPE-UHFFFAOYSA-N"

 Success  registered route 1339!

1481 0 0 Amidation C8035 "TYSPFWQJQMFSNU-UHFFFAOYSA-N"

 Success  registered route 1340!

1482 0 0 Pinner_reaction_(carboxylate_ester) C1447 "OMXQSZKGPNAOCE-UHFFFAOYSA-N"

 Success  registered route 1341!

1483 0 0 Formation_of_sulfonamide_from_halide_-_Shavnya_reaction C8159 "YKFFHGCNYWTCOY-UHFFFAOYSA-N"

 Success  registered route 1342!

1484 0 0 Sp3-sp2_Macmillan_coupling_with_bromide_(intermolecular) C7230 "OWOZFTOSAOYWMO-UHFFFAOYSA-N"

 Success  registered route 1343!

1485 0 0 Amidation C901 "DAXDOXZPNQGVDA-UHFFFAOYSA-N"

 Success  registered route 1344!

1486 0 0 Amidation C8486 "NNLIRPSRTSJYLQ-UHFFFAOYSA-N"

 Success  registered route 1345!

1487 0 0 Reductive_amination C53105 "WYTLJIODCWWXCM-UHFFFAOYSA-N"

 Success  registered route 1346!

1488 0 0 Amidation C5289 "UENQPBXXWCZQQQ-UHFFFAOYSA-N"

 Success  registered route 1347!

1489 0 0 Formation_of_urea_from_two_amines C1404 "NLXFVKOJESFEML-UHFFFAOYSA-N"

 Success  registered route 1348!

1490 0 0 Imine_formation C38598 "FHBGUWZYHVFIEX-UHFFFAOYSA-N"

 Success  registered route 1349!

1491 0 0 Sp3-sp2_Suzuki_coupling C25770 "FMCDEJOHQRDQTM-UHFFFAOYSA-N"

 Success  registered route 1350!

1492 0 0 Amidation C89709 "XRENEVZHQOBHPU-UHFFFAOYSA-N"

 Success  registered route 1351!

1493 0 0 Amidation C15998 "TUCJJOTTXFGEGV-UHFFFAOYSA-N"

 Success  registered route 1352!

1494 0 0 Imidazole_C-2_alkylation C2060 "BZGNUPUTGOBVRA-UHFFFAOYSA-N"

 Success  registered route 1353!

1495 0 0 Amidation C3768 "AHFGKFFBSVWUBY-UHFFFAOYSA-N"

 Success  registered route 1354!

1496 0 0 Alpha_alkylation_of_ketone C4665 "VSJBYJHPGLAONM-UHFFFAOYSA-N"

1496 0 1 Reductive_amination C286107 "GNIJFAKCVTUKKA-UHFFFAOYSA-N"

 Success  registered route 1355!

1497 0 0 Formation_of_urea_from_two_amines C10335 "OTLOOYMQZJZQNU-UHFFFAOYSA-N"

 Success  registered route 1356!

1498 0 0 Amidation C7181 "YQLHABXLGQDQAK-UHFFFAOYSA-N"

 Success  registered route 1357!

1499 0 0 Sulfonamide_Schotten-Baumann_with_amine_(intermolecular) C8160 "NPUASWGUMOGUOD-UHFFFAOYSA-N"

 Success  registered route 1358!

1500 0 0 Amidation C9219 "ZIEANTSEZNDOIT-UHFFFAOYSA-N"

 Success  registered route 1359!

1501 0 0 Amidation C7420 "SFWHGSYKQXAWJE-UHFFFAOYSA-N"

 Success  registered route 1360!

1502 0 0 Amidation C3796 "LCTNYMQLEGMDNQ-UHFFFAOYSA-N"

 Success  registered route 1361!

1503 0 0 Amidation C32214 "FYGXQHWPDXQZJW-UHFFFAOYSA-N"

 Success  registered route 1362!

1504 0 0 Reductive_amination C4724 "GMKJOMOIOGJQHB-UHFFFAOYSA-N"

 Success  registered route 1363!

1505 0 0 Amine_alkylation C2537 "SCARXBJLFBDDOC-UHFFFAOYSA-N"

1505 0 1 Aromatic_bromination C285852 "KWMFJCDOMJZLBW-UHFFFAOYSA-N"

 Success  registered route 1364!

1506 0 0 Amidation C684 "SZDLHMXCGWCAQL-UHFFFAOYSA-N"

 Success  registered route 1365!

1507 0 0 Amidation C4586 "RMNLILARQBZGID-UHFFFAOYSA-N"

 Success  registered route 1366!

1508 0 0 Amidation C4036 "YUUBMJABYAMHEQ-UHFFFAOYSA-N"

 Success  registered route 1367!

1509 0 0 Formation_of_sulfonamide_from_halide_-_Shavnya_reaction C7625 "KCJHWNBJYBCBFO-UHFFFAOYSA-N"

 Success  registered route 1368!

1510 0 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C8502 "RJQPPZGWNZQLTO-UHFFFAOYSA-N"

 Success  registered route 1369!

1511 0 0 Amidation C16768 "ALJLPWDQYMWXDZ-UHFFFAOYSA-N"

 Success  registered route 1370!

1512 0 0 Sulfonamide_Schotten-Baumann_with_amine_(intermolecular) C8155 "QQLANTWMZZICGE-UHFFFAOYSA-N"

 Success  registered route 1371!

1513 0 0 Alpha_alkylation_of_ketone C4732 "OVNCGQSYSSYBPO-UHFFFAOYSA-N"

 Success  registered route 1372!

1514 0 0 Sp2-sp2_Suzuki_coupling C3665 "GXLZMUSLZZNHNL-UHFFFAOYSA-N"

 Success  registered route 1373!

1515 0 0 Amidation C16361 "ZZPZYEPSKIPXIU-UHFFFAOYSA-N"

 Success  registered route 1374!

1516 0 0 Amidation C16361 "ZZPZYEPSKIPXIU-UHFFFAOYSA-N"

 Success  registered route 1375!

1517 0 0 Minisci_reaction_with_carboxylic_acid_(intermolecular) C2086 "SKVGOPZVGGOSKI-UHFFFAOYSA-N"

 Success  registered route 1376!

1518 0 0 Sp3-sp2_Suzuki_coupling C2091 "XNTLIZRLNRAQQY-UHFFFAOYSA-N"

1518 0 1 Sandmeyer_iodination C286153 "KVDVCOCXJVWCCY-UHFFFAOYSA-N"

 Success  registered route 1377!

1519 0 0 Aldol_addition_carbonyl C8142 "UZXQDRCHBFTVHG-UHFFFAOYSA-N"

 Success  registered route 1378!

,smiles,template,compound_set,hit1,hit2,hit3,hit4,hit5,hit6,hit7,...,route2_CAR,route2_non_CAR,route3,route3_names,route3_CAR,route3_non_CAR,route4,route4_names,route4_CAR,route4_non_CAR
0,O=C(Cc1cocn1)Nc1ccc2c(c1)C(F)CC2,A5666a,openbind_a71ev2a_c1_scaffolds,A5151a,A5512a,NaN,NaN,NaN,NaN,NaN,...,True,None,"[{'name': 'Ester_amidation', 'reactantSmiles':...",[Ester_amidation],True,None,[{'name': 'Sp3-sp2_Macmillan_coupling_alcohol_...,[Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_h...,False,[Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_h...
1,Cc1ccc(C(O)(C=O)NCc2cocn2)c2[nH]ccc12,A5666a,openbind_a71ev2a_c1_scaffolds,A0487a,A4940a,NaN,NaN,NaN,NaN,NaN,...,False,"[Grignard_addition_to_carbonyl, Formation_of_G...","[{'name': 'Reductive_amination', 'reactantSmil...","[Reductive_amination, Grignard_addition_to_car...",False,"[Grignard_addition_to_carbonyl, Formation_of_G...","[{'name': 'Amine_alkylation', 'reactantSmiles'...","[Amine_alkylation, Grignard_addition_to_carbon...",False,"[Amine_alkylation, Grignard_addition_to_carbon..."
2,COc1ccc(C(C)=O)cc1-c1n[nH]cc1CN,A5666a,openbind_a71ev2a_c1_scaffolds,A0501a,A4456a,NaN,NaN,NaN,NaN,NaN,...,False,[Sp2-sp2_Suzuki_coupling],"[{'name': 'Sp2-sp2_Suzuki_coupling', 'reactant...",[Sp2-sp2_Suzuki_coupling],False,[Sp2-sp2_Suzuki_coupling],"[{'name': 'Reductive_amination', 'reactantSmil...","[Reductive_amination, Sp2-sp2_Suzuki_coupling]",False,[Sp2-sp2_Suzuki_coupling]
3,CNNc1ccccc1-c1n[nH]c(C)c1CO,A5666a,openbind_a71ev2a_c1_scaffolds,A0501a,A4524a,NaN,NaN,NaN,NaN,NaN,...,False,"[Sp2-sp2_Suzuki_coupling, NHK_reaction, Amine_...","[{'name': 'Sp2-sp2_Suzuki_coupling', 'reactant...","[Sp2-sp2_Suzuki_coupling, Amine_alkylation]",False,"[Sp2-sp2_Suzuki_coupling, Amine_alkylation]","[{'name': 'Sp2-sp2_Suzuki_coupling', 'reactant...","[Sp2-sp2_Suzuki_coupling, Amine_alkylation]",False,"[Sp2-sp2_Suzuki_coupling, Amine_alkylation]"
4,CN1CCc2cc(F)c(OC(=O)N3CCCC(C(N)=O)C3)cc2C1CCOc...,A5666a,openbind_a71ev2a_c1_scaffolds,A0501b,A4214a,A4214b,NaN,NaN,NaN,NaN,...,False,[Formation_of_carbamate_from_amine_and_alcohol],"[{'name': 'Amine_alkylation', 'reactantSmiles'...","[Amine_alkylation, Williamson_ether_synthesis,...",False,"[Amine_alkylation, Formation_of_carbamate_from...",[{'name': 'Mitsunobu_reaction_with_amine_alcoh...,[Mitsunobu_reaction_with_amine_alcohol_and_thi...,False,[Formation_of_carbamate_from_amine_and_alcohol]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1515,O=C(NCCc1cc[nH]n1)c1ccnc(-n2ccnc2)c1,A3897a,openbind_a71ev2a_c1_scaffolds,A0556a,A3435a,NaN,NaN,NaN,NaN,NaN,...,True,None,"[{'name': 'Ester_amidation', 'reactantSmiles':...",[Ester_amidation],True,None,"[{'name': 'Ester_amidation', 'reactantSmiles':...",[Ester_amidation],True,None
1516,O=C(NCCc1cc[nH]n1)c1ccnc(-n2ccnc2)c1,A3897a,openbind_a71ev2a_c1_scaffolds,A0556a,A3435a,NaN,NaN,NaN,NaN,NaN,...,True,None,"[{'name': 'Ester_amidation', 'reactantSmiles':...",[Ester_amidation],True,None,"[{'name': 'Ester_amidation', 'reactantSmiles':...",[Ester_amidation],True,None
1517,C1CCC(c2nc3c([nH]2)CCCC3)NC1,A3897a,openbind_a71ev2a_c1_scaffolds,A3371a,A3706a,NaN,NaN,NaN,NaN,NaN,...,False,[Hydrogenation_of_pyridine],"[{'name': 'N-Tosyl_deprotection', 'reactantSmi...","[N-Tosyl_deprotection, Minisci_reaction_with_c...",False,[N-Tosyl_deprotection],"[{'name': 'N-Ac_deprotection', 'reactantSmiles...","[N-Ac_deprotection, Minisci_reaction_with_carb...",False,[N-Ac_deprotection]
1518,C1CC(c2nc3c([nH]2)CCSC3)CCN1,A3897a,openbind_a71ev2a_c1_scaffolds,A3371a,A3706a,NaN,NaN,NaN,NaN,NaN,...,False,[Robinson-Gabriel_imidazole_synthesis_(with_am...,[{'name': 'Sp3-sp2_Macmillan_coupling_alcohol_...,[Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_h...,False,[Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_h...,"[{'name': 'Sp3-sp2_Suzuki_coupling', 'reactant...","[Sp3-sp2_Suzuki_coupling, Sandmeyer_iodination]",False,"[Sp3-sp2_Suzuki_coupling, Sandmeyer_iodination]"
1519,CC(=O)CC(O)C1CCCNC1,A3897a,openbind_a71ev2a_c1_scaffolds,A0719a,A3509a,NaN,NaN,NaN,NaN,NaN,...,False,[Wacker-Tsuji_oxidation_(terminal_alkene)],"[{'name': 'Ethenyl_to_formyl', 'reactantSmiles...",[Ethenyl_to_formyl],False,[Ethenyl_to_formyl],"[{'name': 'N-Boc_deprotection', 'reactantSmile...",[N-Boc_deprotection],True,None

In [6]:
animal.db.prune_duplicate_routes()

#routes = 1378

products with duplicate routes = 1

compound 16361 has 4 duplicate routes

 Success  Deleted 3 duplicate routes!

{227, 1374, 1375}

In [7]:
cset = animal.poses(tag="openbind_a71ev2a_c1_scaffolds").compounds
cset.add_tag("openbind_a71ev2a_c1_scaffolds")

Tagged {C × 1517} w/ "openbind_a71ev2a_c1_scaffolds"

In [10]:
# recipe = hippo.Recipe.from_compounds(cset, use_routes=True, pick_cheapest=False, pick_first=True)
recipe = hippo.Recipe.from_json(animal.db, "cycle_01/syndirella/retrosynthesis/openbind_a71ev2a_c1_scaffolds.json")

 DISK  Reading cycle_01/syndirella/retrosynthesis/openbind_a71ev2a_c1_scaffolds.json...

Recipe was generated at: 2025-09-02 07:47:57.957165

reactants = {Ingredient × 1799}

intermediates = {Ingredient × 0}

products = {Ingredient × 1213}

reactions = {R × 1213}

compounds = {Ingredient × 0}

In [9]:
recipe.write_json("cycle_01/syndirella/retrosynthesis/openbind_a71ev2a_c1_scaffolds.json")

 Warning  NULL Quote: 1.00mg of C282913!

 Warning  NULL Quote: 7.00mg of C282914!

 Warning  NULL Quote: 3.00mg of C282932!

 Warning  NULL Quote: 3.00mg of C282943!

 Warning  NULL Quote: 1.00mg of C284721!

 Warning  NULL Quote: 1.00mg of C285203!

 Warning  NULL Quote: 1.00mg of C284534!

 Warning  NULL Quote: 1.00mg of C284535!

 Warning  NULL Quote: 2.00mg of C6241!

 Warning  NULL Quote: 1.00mg of C285742!

 Warning  NULL Quote: 1.00mg of C6221!

 Warning  NULL Quote: 1.00mg of C284850!

 Warning  NULL Quote: 2.00mg of C284749!

 Warning  NULL Quote: 3.00mg of C284554!

 Warning  NULL Quote: 1.00mg of C285253!

 Warning  NULL Quote: 1.00mg of C286127!

 Warning  NULL Quote: 1.00mg of C286128!

 Warning  NULL Quote: 7.00mg of C283111!

 Warning  NULL Quote: 2.00mg of C284486!

 Warning  NULL Quote: 1.00mg of C284497!

 Warning  NULL Quote: 5.00mg of C284654!

 Warning  NULL Quote: 1.00mg of C285410!

 Warning  NULL Quote: 3.00mg of C283978!

 Warning  NULL Quote: 3.00mg of C284678!

 Warning  NULL Quote: 1.00mg of C285221!

 Warning  NULL Quote: 2.00mg of C284655!

 Warning  NULL Quote: 15.00mg of C283065!

 Warning  NULL Quote: 2.00mg of C284993!

 Warning  NULL Quote: 2.00mg of C285390!

 Warning  NULL Quote: 4.00mg of C283760!

 Warning  NULL Quote: 1.00mg of C285705!

 Warning  NULL Quote: 1.00mg of C285099!

 Warning  NULL Quote: 1.00mg of C285802!

 Warning  NULL Quote: 1.00mg of C283228!

 Warning  NULL Quote: 2.00mg of C284504!

 Warning  NULL Quote: 4.00mg of C284510!

 Warning  NULL Quote: 1.00mg of C284771!

 Warning  NULL Quote: 2.00mg of C283759!

 Warning  NULL Quote: 1.00mg of C284833!

 Warning  NULL Quote: 1.00mg of C286048!

 Warning  NULL Quote: 1.00mg of C286049!

 Warning  NULL Quote: 1.00mg of C284871!

 Warning  NULL Quote: 1.00mg of C284872!

 Warning  NULL Quote: 2.00mg of C285290!

 Warning  NULL Quote: 1.00mg of C285291!

 Warning  NULL Quote: 1.00mg of C286085!

 Warning  NULL Quote: 1.00mg of C285327!

 Warning  NULL Quote: 2.00mg of C285427!

 Warning  NULL Quote: 2.00mg of C284799!

 Warning  NULL Quote: 1.00mg of C286067!

 Warning  NULL Quote: 2.00mg of C283799!

 Warning  NULL Quote: 1.00mg of C285303!

 Warning  NULL Quote: 1.00mg of C285611!

 Warning  NULL Quote: 1.00mg of C285612!

 Warning  NULL Quote: 1.00mg of C284565!

 Warning  NULL Quote: 1.00mg of C284566!

 Warning  NULL Quote: 1.00mg of C285614!

 Warning  NULL Quote: 1.00mg of C285615!

 Warning  NULL Quote: 5.00mg of C284257!

 Warning  NULL Quote: 1.00mg of C285644!

 Warning  NULL Quote: 1.00mg of C284495!

 Warning  NULL Quote: 1.00mg of C284496!

 Warning  NULL Quote: 2.00mg of C285187!

 Warning  NULL Quote: 1.00mg of C285542!

 Warning  NULL Quote: 2.00mg of C284930!

 Warning  NULL Quote: 1.00mg of C285334!

 Warning  NULL Quote: 1.00mg of C274784!

 Warning  NULL Quote: 2.00mg of C284735!

 Warning  NULL Quote: 1.00mg of C285962!

 Warning  NULL Quote: 1.00mg of C285423!

 Warning  NULL Quote: 1.00mg of C285424!

 Warning  NULL Quote: 8.00mg of C283965!

 Warning  NULL Quote: 1.00mg of C284785!

 Warning  NULL Quote: 1.00mg of C285276!

 Warning  NULL Quote: 1.00mg of C285277!

 Warning  NULL Quote: 4.00mg of C282920!

 Warning  NULL Quote: 1.00mg of C283042!

 Warning  NULL Quote: 1.00mg of C285901!

 Warning  NULL Quote: 1.00mg of C285902!

 Warning  NULL Quote: 5.00mg of C283314!

 Warning  NULL Quote: 1.00mg of C285567!

 Warning  NULL Quote: 2.00mg of C284046!

 Warning  NULL Quote: 1.00mg of C285326!

 Warning  NULL Quote: 2.00mg of C284016!

 Warning  NULL Quote: 4.00mg of C284302!

 Warning  NULL Quote: 1.00mg of C284827!

 Warning  NULL Quote: 6.00mg of C284054!

 Warning  NULL Quote: 4.00mg of C285378!

 Warning  NULL Quote: 1.00mg of C78!

 Warning  NULL Quote: 1.00mg of C284809!

 Warning  NULL Quote: 1.00mg of C284652!

 Warning  NULL Quote: 1.00mg of C285447!

 Warning  NULL Quote: 1.00mg of C285448!

 Warning  NULL Quote: 1.00mg of C285379!

 Warning  NULL Quote: 1.00mg of C285868!

 Warning  NULL Quote: 1.00mg of C285736!

 Warning  NULL Quote: 2.00mg of C284904!

 Warning  NULL Quote: 1.00mg of C285388!

 Warning  NULL Quote: 1.00mg of C285302!

 Warning  NULL Quote: 1.00mg of C284905!

 Warning  NULL Quote: 1.00mg of C285370!

 Warning  NULL Quote: 1.00mg of C286014!

 Warning  NULL Quote: 1.00mg of C286015!

 Warning  NULL Quote: 5.00mg of C283077!

 Warning  NULL Quote: 1.00mg of C285704!

 Warning  NULL Quote: 5.00mg of C284795!

 Warning  NULL Quote: 1.00mg of C285260!

 Warning  NULL Quote: 5.00mg of C283929!

 Warning  NULL Quote: 1.00mg of C285081!

 Warning  NULL Quote: 2.00mg of C284770!

 Warning  NULL Quote: 2.00mg of C285558!

 Warning  NULL Quote: 2.00mg of C284769!

 Warning  NULL Quote: 1.00mg of C285965!

 Warning  NULL Quote: 1.00mg of C285966!

 Warning  NULL Quote: 1.00mg of C285583!

 Warning  NULL Quote: 1.00mg of C285584!

 Warning  NULL Quote: 1.00mg of C285493!

 Warning  NULL Quote: 1.00mg of C285261!

 Warning  NULL Quote: 5.00mg of C283796!

 Warning  NULL Quote: 1.00mg of C284562!

 Warning  NULL Quote: 1.00mg of C285528!

 Warning  NULL Quote: 1.00mg of C286091!

 Warning  NULL Quote: 3.00mg of C284732!

 Warning  NULL Quote: 1.00mg of C285102!

 Warning  NULL Quote: 2.00mg of C282976!

 Warning  NULL Quote: 2.00mg of C284544!

 Warning  NULL Quote: 3.00mg of C284865!

 Warning  NULL Quote: 1.00mg of C284911!

 Warning  NULL Quote: 1.00mg of C284912!

 Warning  NULL Quote: 4.00mg of C284939!

 Warning  NULL Quote: 1.00mg of C286019!

 Warning  NULL Quote: 1.00mg of C284940!

 Warning  NULL Quote: 1.00mg of C1442!

 Warning  NULL Quote: 4.00mg of C283127!

 Warning  NULL Quote: 1.00mg of C286076!

 Warning  NULL Quote: 1.00mg of C286077!

 Warning  NULL Quote: 3.00mg of C284138!

 Warning  NULL Quote: 1.00mg of C285428!

 Warning  NULL Quote: 1.00mg of C285148!

 Warning  NULL Quote: 1.00mg of C285988!

 Warning  NULL Quote: 1.00mg of C285989!

 Warning  NULL Quote: 3.00mg of C283060!

 Warning  NULL Quote: 1.00mg of C285231!

 Warning  NULL Quote: 2.00mg of C283841!

 Warning  NULL Quote: 1.00mg of C285300!

 Warning  NULL Quote: 1.00mg of C285933!

 Warning  NULL Quote: 1.00mg of C285934!

 Warning  NULL Quote: 1.00mg of C285210!

 Warning  NULL Quote: 1.00mg of C285211!

 Warning  NULL Quote: 1.00mg of C285089!

 Warning  NULL Quote: 5.00mg of C285090!

 Warning  NULL Quote: 1.00mg of C285793!

 Warning  NULL Quote: 1.00mg of C284662!

 Warning  NULL Quote: 1.00mg of C284606!

 Warning  NULL Quote: 6.00mg of C283907!

 Warning  NULL Quote: 1.00mg of C285641!

 Warning  NULL Quote: 1.00mg of C284733!

 Warning  NULL Quote: 1.00mg of C284736!

 Warning  NULL Quote: 1.00mg of C285178!

 Warning  NULL Quote: 3.00mg of C284772!

 Warning  NULL Quote: 1.00mg of C284900!

 Warning  NULL Quote: 1.00mg of C285737!

 Warning  NULL Quote: 4.00mg of C283318!

 Warning  NULL Quote: 7.00mg of C283156!

 Warning  NULL Quote: 3.00mg of C283755!

 Warning  NULL Quote: 1.00mg of C285871!

 Warning  NULL Quote: 3.00mg of C284454!

 Warning  NULL Quote: 1.00mg of C284943!

 Warning  NULL Quote: 2.00mg of C285707!

 Warning  NULL Quote: 1.00mg of C285708!

 Warning  NULL Quote: 1.00mg of C283671!

 Warning  NULL Quote: 1.00mg of C284430!

 Warning  NULL Quote: 1.00mg of C284431!

 Warning  NULL Quote: 2.00mg of C285142!

 Warning  NULL Quote: 1.00mg of C285030!

 Warning  NULL Quote: 1.00mg of C285803!

 Warning  NULL Quote: 1.00mg of C286102!

 Warning  NULL Quote: 13.00mg of C283032!

 Warning  NULL Quote: 1.00mg of C285028!

 Warning  NULL Quote: 1.00mg of C285272!

 Warning  NULL Quote: 1.00mg of C285273!

 Warning  NULL Quote: 6.00mg of C284165!

 Warning  NULL Quote: 2.00mg of C285760!

 Warning  NULL Quote: 1.00mg of C1869!

 Warning  NULL Quote: 1.00mg of C285668!

 Warning  NULL Quote: 3.00mg of C284346!

 Warning  NULL Quote: 2.00mg of C284310!

 Warning  NULL Quote: 1.00mg of C285248!

 Warning  NULL Quote: 1.00mg of C285395!

 Warning  NULL Quote: 1.00mg of C285396!

 Warning  NULL Quote: 1.00mg of C286035!

 Warning  NULL Quote: 1.00mg of C284969!

 Warning  NULL Quote: 1.00mg of C284970!

 Warning  NULL Quote: 1.00mg of C285017!

 Warning  NULL Quote: 1.00mg of C285018!

 Warning  NULL Quote: 2.00mg of C284646!

 Warning  NULL Quote: 1.00mg of C283999!

 Warning  NULL Quote: 1.00mg of C284901!

 Warning  NULL Quote: 1.00mg of C284499!

 Warning  NULL Quote: 1.00mg of C284888!

 Warning  NULL Quote: 1.00mg of C285501!

 Warning  NULL Quote: 1.00mg of C285502!

 Warning  NULL Quote: 3.00mg of C283732!

 Warning  NULL Quote: 1.00mg of C285406!

 Warning  NULL Quote: 1.00mg of C285232!

 Warning  NULL Quote: 1.00mg of C285200!

 Warning  NULL Quote: 1.00mg of C285201!

 Warning  NULL Quote: 1.00mg of C285514!

 Warning  NULL Quote: 1.00mg of C285337!

 Warning  NULL Quote: 2.00mg of C282993!

 Warning  NULL Quote: 1.00mg of C285192!

 Warning  NULL Quote: 7.00mg of C284637!

 Warning  NULL Quote: 1.00mg of C286016!

 Warning  NULL Quote: 5.00mg of C283810!

 Warning  NULL Quote: 2.00mg of C284705!

 Warning  NULL Quote: 3.00mg of C285198!

 Warning  NULL Quote: 1.00mg of C286009!

 Warning  NULL Quote: 1.00mg of C285646!

 Warning  NULL Quote: 1.00mg of C285421!

 Warning  NULL Quote: 1.00mg of C285422!

 Warning  NULL Quote: 1.00mg of C284707!

 Warning  NULL Quote: 1.00mg of C284981!

 Warning  NULL Quote: 1.00mg of C284543!

 Warning  NULL Quote: 1.00mg of C285212!

 Warning  NULL Quote: 1.00mg of C284092!

 Warning  NULL Quote: 1.00mg of C6259!

 Warning  NULL Quote: 1.00mg of C285385!

 Warning  NULL Quote: 1.00mg of C284819!

 Warning  NULL Quote: 1.00mg of C283906!

 Warning  NULL Quote: 4.00mg of C283063!

 Warning  NULL Quote: 1.00mg of C284679!

 Warning  NULL Quote: 1.00mg of C284680!

 Warning  NULL Quote: 1.00mg of C285138!

 Warning  NULL Quote: 1.00mg of C284661!

 Warning  NULL Quote: 1.00mg of C285698!

 Warning  NULL Quote: 1.00mg of C285403!

 Warning  NULL Quote: 1.00mg of C285404!

 Warning  NULL Quote: 1.00mg of C285132!

 Warning  NULL Quote: 1.00mg of C285348!

 Warning  NULL Quote: 1.00mg of C284618!

 Warning  NULL Quote: 3.00mg of C284619!

 Warning  NULL Quote: 1.00mg of C285181!

 Warning  NULL Quote: 1.00mg of C285182!

 Warning  NULL Quote: 1.00mg of C285953!

 Warning  NULL Quote: 1.00mg of C285954!

 Warning  NULL Quote: 1.00mg of C284558!

 Warning  NULL Quote: 1.00mg of C284559!

 Warning  NULL Quote: 1.00mg of C285915!

 Warning  NULL Quote: 1.00mg of C285916!

 Warning  NULL Quote: 1.00mg of C284415!

 Warning  NULL Quote: 1.00mg of C285886!

 Warning  NULL Quote: 1.00mg of C284954!

 Warning  NULL Quote: 1.00mg of C284955!

 Warning  NULL Quote: 1.00mg of C285919!

 Warning  NULL Quote: 1.00mg of C285920!

 Warning  NULL Quote: 1.00mg of C285301!

 Warning  NULL Quote: 1.00mg of C286146!

 Warning  NULL Quote: 1.00mg of C286147!

 Warning  NULL Quote: 4.00mg of C283057!

 Warning  NULL Quote: 3.00mg of C283840!

 Warning  NULL Quote: 1.00mg of C285861!

 Warning  NULL Quote: 1.00mg of C283082!

 Warning  NULL Quote: 1.00mg of C283083!

 Warning  NULL Quote: 1.00mg of C284331!

 Warning  NULL Quote: 1.00mg of C286105!

 Warning  NULL Quote: 1.00mg of C286106!

 Warning  NULL Quote: 2.00mg of C283026!

 Warning  NULL Quote: 4.00mg of C284056!

 Warning  NULL Quote: 1.00mg of C284472!

 Warning  NULL Quote: 2.00mg of C284437!

 Warning  NULL Quote: 1.00mg of C285262!

 Warning  NULL Quote: 1.00mg of C285263!

 Warning  NULL Quote: 5.00mg of C283924!

 Warning  NULL Quote: 1.00mg of C286121!

 Warning  NULL Quote: 1.00mg of C284730!

 Warning  NULL Quote: 2.00mg of C284731!

 Warning  NULL Quote: 7.00mg of C283820!

 Warning  NULL Quote: 1.00mg of C283995!

 Warning  NULL Quote: 1.00mg of C286006!

 Warning  NULL Quote: 1.00mg of C284828!

 Warning  NULL Quote: 3.00mg of C283058!

 Warning  NULL Quote: 1.00mg of C284815!

 Warning  NULL Quote: 1.00mg of C284816!

 Warning  NULL Quote: 2.00mg of C283837!

 Warning  NULL Quote: 2.00mg of C284851!

 Warning  NULL Quote: 1.00mg of C285104!

 Warning  NULL Quote: 1.00mg of C285105!

 Warning  NULL Quote: 3.00mg of C283935!

 Warning  NULL Quote: 1.00mg of C285616!

 Warning  NULL Quote: 1.00mg of C286130!

 Warning  NULL Quote: 2.00mg of C283259!

 Warning  NULL Quote: 1.00mg of C285131!

 Warning  NULL Quote: 2.00mg of C283064!

 Warning  NULL Quote: 1.00mg of C285932!

 Warning  NULL Quote: 1.00mg of C285963!

 Warning  NULL Quote: 1.00mg of C285964!

 Warning  NULL Quote: 3.00mg of C284195!

 Warning  NULL Quote: 1.00mg of C285885!

 Warning  NULL Quote: 2.00mg of C284401!

 Warning  NULL Quote: 1.00mg of C285971!

 Warning  NULL Quote: 1.00mg of C285714!

 Warning  NULL Quote: 1.00mg of C285715!

 Warning  NULL Quote: 1.00mg of C1871!

 Warning  NULL Quote: 1.00mg of C284653!

 Warning  NULL Quote: 1.00mg of C285579!

 Warning  NULL Quote: 2.00mg of C285617!

 Warning  NULL Quote: 2.00mg of C285394!

 Warning  NULL Quote: 3.00mg of C284945!

 Warning  NULL Quote: 1.00mg of C284946!

 Warning  NULL Quote: 1.00mg of C284889!

 Warning  NULL Quote: 1.00mg of C284890!

 Warning  NULL Quote: 1.00mg of C284602!

 Warning  NULL Quote: 1.00mg of C284834!

 Warning  NULL Quote: 4.00mg of C284685!

 Warning  NULL Quote: 1.00mg of C285869!

 Warning  NULL Quote: 1.00mg of C284858!

 Warning  NULL Quote: 1.00mg of C284859!

 Warning  NULL Quote: 1.00mg of C285507!

 Warning  NULL Quote: 2.00mg of C285508!

 Warning  NULL Quote: 2.00mg of C285723!

 Warning  NULL Quote: 1.00mg of C285877!

 Warning  NULL Quote: 1.00mg of C286129!

 Warning  NULL Quote: 8.00mg of C283280!

 Warning  NULL Quote: 1.00mg of C284876!

 Warning  NULL Quote: 1.00mg of C285819!

 Warning  NULL Quote: 1.00mg of C285006!

 Warning  NULL Quote: 3.00mg of C284550!

 Warning  NULL Quote: 1.00mg of C285183!

 Warning  NULL Quote: 1.00mg of C285456!

 Warning  NULL Quote: 1.00mg of C284906!

 Warning  NULL Quote: 1.00mg of C284590!

 Warning  NULL Quote: 2.00mg of C284286!

 Warning  NULL Quote: 1.00mg of C285779!

 Warning  NULL Quote: 1.00mg of C286143!

 Warning  NULL Quote: 1.00mg of C284740!

 Warning  NULL Quote: 2.00mg of C284117!

 Warning  NULL Quote: 1.00mg of C285972!

 Warning  NULL Quote: 1.00mg of C285283!

 Warning  NULL Quote: 1.00mg of C285284!

 Warning  NULL Quote: 1.00mg of C284697!

 Warning  NULL Quote: 4.00mg of C284139!

 Warning  NULL Quote: 1.00mg of C285778!

 Warning  NULL Quote: 4.00mg of C284937!

 Warning  NULL Quote: 1.00mg of C285345!

 Warning  NULL Quote: 1.00mg of C285833!

 Warning  NULL Quote: 1.00mg of C285096!

 Warning  NULL Quote: 1.00mg of C285097!

 Warning  NULL Quote: 1.00mg of C284622!

 Warning  NULL Quote: 1.00mg of C285765!

 Warning  NULL Quote: 2.00mg of C285500!

 Warning  NULL Quote: 1.00mg of C285629!

 Warning  NULL Quote: 1.00mg of C285927!

 Warning  NULL Quote: 2.00mg of C284777!

 Warning  NULL Quote: 1.00mg of C284778!

 Warning  NULL Quote: 2.00mg of C285010!

 Warning  NULL Quote: 1.00mg of C285011!

 Warning  NULL Quote: 1.00mg of C285356!

 Warning  NULL Quote: 2.00mg of C283758!

 Warning  NULL Quote: 5.00mg of C284475!

 Warning  NULL Quote: 3.00mg of C284875!

 Warning  NULL Quote: 1.00mg of C284874!

 Warning  NULL Quote: 1.00mg of C286089!

 Warning  NULL Quote: 1.00mg of C286090!

 Warning  NULL Quote: 1.00mg of C285766!

 Warning  NULL Quote: 1.00mg of C285767!

 Warning  NULL Quote: 4.00mg of C284844!

 Warning  NULL Quote: 1.00mg of C285834!

 Warning  NULL Quote: 1.00mg of C284843!

 Warning  NULL Quote: 1.00mg of C285016!

 Warning  NULL Quote: 1.00mg of C285109!

 Warning  NULL Quote: 1.00mg of C284913!

 Warning  NULL Quote: 1.00mg of C285012!

 Warning  NULL Quote: 2.00mg of C284456!

 Warning  NULL Quote: 4.00mg of C284464!

 Warning  NULL Quote: 1.00mg of C285190!

 Warning  NULL Quote: 1.00mg of C285215!

 Warning  NULL Quote: 1.00mg of C285857!

 Warning  NULL Quote: 1.00mg of C285674!

 Warning  NULL Quote: 1.00mg of C285173!

 Warning  NULL Quote: 1.00mg of C285397!

 Warning  NULL Quote: 1.00mg of C285398!

 Warning  NULL Quote: 1.00mg of C286020!

 Warning  NULL Quote: 1.00mg of C286021!

 Warning  NULL Quote: 1.00mg of C285149!

 Warning  NULL Quote: 1.00mg of C285150!

 Warning  NULL Quote: 1.00mg of C284434!

 Warning  NULL Quote: 1.00mg of C284435!

 Warning  NULL Quote: 1.00mg of C12!

 Warning  NULL Quote: 1.00mg of C285321!

 Warning  NULL Quote: 3.00mg of C283921!

 Warning  NULL Quote: 1.00mg of C285062!

 Warning  NULL Quote: 1.00mg of C285405!

 Warning  NULL Quote: 1.00mg of C284555!

 Warning  NULL Quote: 1.00mg of C284750!

 Warning  NULL Quote: 1.00mg of C284751!

 Warning  NULL Quote: 2.00mg of C283722!

 Warning  NULL Quote: 1.00mg of C285367!

 Warning  NULL Quote: 2.00mg of C282925!

 Warning  NULL Quote: 1.00mg of C285059!

 Warning  NULL Quote: 1.00mg of C284473!

 Warning  NULL Quote: 1.00mg of C285740!

 Warning  NULL Quote: 13.00mg of C283068!

 Warning  NULL Quote: 2.00mg of C285373!

 Warning  NULL Quote: 1.00mg of C285146!

 Warning  NULL Quote: 1.00mg of C284684!

 Warning  NULL Quote: 9.00mg of C283835!

 Warning  NULL Quote: 1.00mg of C285485!

 Warning  NULL Quote: 1.00mg of C284644!

 Warning  NULL Quote: 1.00mg of C284542!

 Warning  NULL Quote: 2.00mg of C285996!

 Warning  NULL Quote: 1.00mg of C285482!

 Warning  NULL Quote: 2.00mg of C285483!

 Warning  NULL Quote: 2.00mg of C285538!

 Warning  NULL Quote: 1.00mg of C285695!

 Warning  NULL Quote: 1.00mg of C6035!

 Warning  NULL Quote: 1.00mg of C285377!

 Warning  NULL Quote: 1.00mg of C284709!

 Warning  NULL Quote: 1.00mg of C284710!

 Warning  NULL Quote: 1.00mg of C285711!

 Warning  NULL Quote: 1.00mg of C284949!

 Warning  NULL Quote: 2.00mg of C284519!

 Warning  NULL Quote: 1.00mg of C284520!

 Warning  NULL Quote: 2.00mg of C285053!

 Warning  NULL Quote: 3.00mg of C285103!

 Warning  NULL Quote: 1.00mg of C285437!

 Warning  NULL Quote: 3.00mg of C284232!

 Warning  NULL Quote: 1.00mg of C284503!

 Warning  NULL Quote: 1.00mg of C285294!

 Warning  NULL Quote: 1.00mg of C284505!

 Warning  NULL Quote: 1.00mg of C285946!

 Warning  NULL Quote: 1.00mg of C284512!

 Warning  NULL Quote: 1.00mg of C284325!

 Warning  NULL Quote: 1.00mg of C284511!

 Warning  NULL Quote: 1.00mg of C285258!

 Warning  NULL Quote: 1.00mg of C285259!

 Warning  NULL Quote: 1.00mg of C285923!

 Warning  NULL Quote: 4.00mg of C283930!

 Warning  NULL Quote: 4.00mg of C284698!

 Warning  NULL Quote: 1.00mg of C284686!

 Warning  NULL Quote: 1.00mg of C284687!

 Warning  NULL Quote: 1.00mg of C284601!

 Warning  NULL Quote: 1.00mg of C285876!

 Warning  NULL Quote: 1.00mg of C718!

 Warning  NULL Quote: 1.00mg of C284178!

 Warning  NULL Quote: 2.00mg of C284753!

 Warning  NULL Quote: 1.00mg of C285429!

 Warning  NULL Quote: 1.00mg of C284814!

 Warning  NULL Quote: 2.00mg of C284537!

 Warning  NULL Quote: 5.00mg of C283756!

 Warning  NULL Quote: 1.00mg of C284866!

 Warning  NULL Quote: 1.00mg of C284583!

 Warning  NULL Quote: 2.00mg of C284584!

 Warning  NULL Quote: 2.00mg of C283051!

 Warning  NULL Quote: 1.00mg of C286047!

 Warning  NULL Quote: 1.00mg of C285809!

 Warning  NULL Quote: 1.00mg of C285810!

 Warning  NULL Quote: 1.00mg of C285292!

 Warning  NULL Quote: 1.00mg of C285293!

 Warning  NULL Quote: 1.00mg of C285264!

 Warning  NULL Quote: 1.00mg of C285265!

 Warning  NULL Quote: 1.00mg of C284620!

 Warning  NULL Quote: 1.00mg of C284621!

 Warning  NULL Quote: 1.00mg of C285573!

 Warning  NULL Quote: 2.00mg of C285038!

 Warning  NULL Quote: 1.00mg of C285958!

 Warning  NULL Quote: 4.00mg of C284063!

 Warning  NULL Quote: 1.00mg of C285955!

 Warning  NULL Quote: 1.00mg of C284551!

 Warning  NULL Quote: 1.00mg of C285082!

 Warning  NULL Quote: 1.00mg of C5322!

 Warning  NULL Quote: 4.00mg of C284301!

 Warning  NULL Quote: 2.00mg of C284763!

 Warning  NULL Quote: 2.00mg of C285331!

 Warning  NULL Quote: 3.00mg of C284773!

 Warning  NULL Quote: 21.00mg of C283237!

 Warning  NULL Quote: 1.00mg of C285706!

 Warning  NULL Quote: 1.00mg of C285959!

 Warning  NULL Quote: 1.00mg of C285735!

 Warning  NULL Quote: 1.00mg of C284941!

 Warning  NULL Quote: 1.00mg of C284942!

 Warning  NULL Quote: 1.00mg of C285769!

 Warning  NULL Quote: 3.00mg of C7133!

 Warning  NULL Quote: 1.00mg of C284563!

 Warning  NULL Quote: 1.00mg of C284615!

 Warning  NULL Quote: 1.00mg of C284614!

 Warning  NULL Quote: 1.00mg of C284825!

 Warning  NULL Quote: 1.00mg of C285451!

 Warning  NULL Quote: 1.00mg of C286110!

 Warning  NULL Quote: 1.00mg of C285189!

 Warning  NULL Quote: 1.00mg of C284791!

 Warning  NULL Quote: 1.00mg of C285754!

 Warning  NULL Quote: 1.00mg of C284011!

 Warning  NULL Quote: 2.00mg of C284012!

 Warning  NULL Quote: 1.00mg of C285460!

 Warning  NULL Quote: 1.00mg of C285461!

 Warning  NULL Quote: 1.00mg of C286080!

 Warning  NULL Quote: 1.00mg of C286081!

 Warning  NULL Quote: 1.00mg of C284929!

 Warning  NULL Quote: 1.00mg of C285782!

 Warning  NULL Quote: 1.00mg of C285783!

 Warning  NULL Quote: 1.00mg of C285534!

 Warning  NULL Quote: 1.00mg of C285535!

 Warning  NULL Quote: 2.00mg of C284244!

 Warning  NULL Quote: 2.00mg of C284459!

 Warning  NULL Quote: 1.00mg of C285195!

 Warning  NULL Quote: 2.00mg of C285196!

 Warning  NULL Quote: 1.00mg of C285360!

 Warning  NULL Quote: 1.00mg of C285361!

 Warning  NULL Quote: 1.00mg of C285407!

 Warning  NULL Quote: 1.00mg of C285408!

 Warning  NULL Quote: 1.00mg of C285550!

 Warning  NULL Quote: 1.00mg of C284636!

 Warning  NULL Quote: 1.00mg of C284575!

 Warning  NULL Quote: 1.00mg of C284576!

 Warning  NULL Quote: 1.00mg of C285585!

 Warning  NULL Quote: 1.00mg of C285586!

 Warning  NULL Quote: 1.00mg of C284649!

 Warning  NULL Quote: 2.00mg of C285098!

 Warning  NULL Quote: 1.00mg of C285763!

 Warning  NULL Quote: 1.00mg of C285764!

 Warning  NULL Quote: 2.00mg of C284699!

 Warning  NULL Quote: 2.00mg of C285037!

 Warning  NULL Quote: 1.00mg of C285121!

 Warning  NULL Quote: 2.00mg of C283814!

 Warning  NULL Quote: 6.00mg of C284490!

 Warning  NULL Quote: 1.00mg of C285452!

 Warning  NULL Quote: 1.00mg of C284521!

 Warning  NULL Quote: 3.00mg of C7596!

 Warning  NULL Quote: 2.00mg of C284808!

 Warning  NULL Quote: 1.00mg of C286131!

 Warning  NULL Quote: 1.00mg of C286132!

 Warning  NULL Quote: 2.00mg of C284488!

 Warning  NULL Quote: 5.00mg of C284489!

 Warning  NULL Quote: 2.00mg of C285455!

 Warning  NULL Quote: 1.00mg of C285450!

 Warning  NULL Quote: 1.00mg of C285036!

 Warning  NULL Quote: 1.00mg of C285165!

 Warning  NULL Quote: 1.00mg of C285794!

 Warning  NULL Quote: 1.00mg of C284826!

 Warning  NULL Quote: 4.00mg of C283743!

 Warning  NULL Quote: 1.00mg of C285112!

 Warning  NULL Quote: 2.00mg of C285425!

 Warning  NULL Quote: 1.00mg of C285426!

 Warning  NULL Quote: 1.00mg of C285129!

 Warning  NULL Quote: 2.00mg of C285130!

 Warning  NULL Quote: 1.00mg of C285900!

 Warning  NULL Quote: 4.00mg of C284845!

 Warning  NULL Quote: 1.00mg of C284921!

 Warning  NULL Quote: 1.00mg of C286074!

 Warning  NULL Quote: 1.00mg of C286075!

 Warning  NULL Quote: 2.00mg of C284669!

 Warning  NULL Quote: 2.00mg of C284670!

 Warning  NULL Quote: 1.00mg of C284846!

 Warning  NULL Quote: 4.00mg of C284006!

 Warning  NULL Quote: 1.00mg of C285214!

 Warning  NULL Quote: 1.00mg of C285230!

 Warning  NULL Quote: 1.00mg of C285829!

 Warning  NULL Quote: 1.00mg of C285830!

 Warning  NULL Quote: 1.00mg of C284460!

 Warning  NULL Quote: 1.00mg of C283928!

 Warning  NULL Quote: 1.00mg of C285650!

 Warning  NULL Quote: 1.00mg of C285505!

 Warning  NULL Quote: 1.00mg of C285597!

 Warning  NULL Quote: 2.00mg of C283939!

 Warning  NULL Quote: 3.00mg of C284030!

 Warning  NULL Quote: 1.00mg of C285156!

 Warning  NULL Quote: 1.00mg of C285157!

 Warning  NULL Quote: 1.00mg of C286055!

 Warning  NULL Quote: 2.00mg of C286111!

 Warning  NULL Quote: 1.00mg of C286140!

 Warning  NULL Quote: 2.00mg of C286061!

 Warning  NULL Quote: 2.00mg of C284133!

 Warning  NULL Quote: 1.00mg of C284792!

 Warning  NULL Quote: 1.00mg of C284910!

 Warning  NULL Quote: 1.00mg of C284715!

 Warning  NULL Quote: 1.00mg of C285257!

 Warning  NULL Quote: 13.00mg of C284591!

 Warning  NULL Quote: 1.00mg of C284592!

 Warning  NULL Quote: 1.00mg of C285351!

 Warning  NULL Quote: 1.00mg of C284951!

 Warning  NULL Quote: 1.00mg of C285945!

 Warning  NULL Quote: 1.00mg of C285947!

 Warning  NULL Quote: 5.00mg of C284524!

 Warning  NULL Quote: 1.00mg of C284847!

 Warning  NULL Quote: 1.00mg of C284525!

 Warning  NULL Quote: 1.00mg of C285202!

 Warning  NULL Quote: 1.00mg of C285536!

 Warning  NULL Quote: 1.00mg of C286086!

 Warning  NULL Quote: 1.00mg of C286136!

 Warning  NULL Quote: 1.00mg of C286137!

 Warning  NULL Quote: 1.00mg of C14055!

 Warning  NULL Quote: 4.00mg of C284027!

 Warning  NULL Quote: 4.00mg of C284572!

 Warning  NULL Quote: 1.00mg of C284672!

 Warning  NULL Quote: 1.00mg of C284673!

 Warning  NULL Quote: 4.00mg of C283761!

 Warning  NULL Quote: 1.00mg of C285557!

 Warning  NULL Quote: 2.00mg of C284243!

 Warning  NULL Quote: 1.00mg of C285478!

 Warning  NULL Quote: 1.00mg of C284656!

 Warning  NULL Quote: 1.00mg of C284657!

 Warning  NULL Quote: 2.00mg of C283954!

 Warning  NULL Quote: 1.00mg of C285220!

 Warning  NULL Quote: 1.00mg of C285343!

 Warning  NULL Quote: 2.00mg of C285344!

 Warning  NULL Quote: 1.00mg of C286007!

 Warning  NULL Quote: 2.00mg of C284196!

 Warning  NULL Quote: 1.00mg of C285034!

 Warning  NULL Quote: 1.00mg of C284869!

 Warning  NULL Quote: 1.00mg of C284870!

 Warning  NULL Quote: 2.00mg of C284798!

 Warning  NULL Quote: 2.00mg of C284040!

 Warning  NULL Quote: 3.00mg of C284739!

 Warning  NULL Quote: 1.00mg of C284526!

 Warning  NULL Quote: 1.00mg of C284527!

 Warning  NULL Quote: 3.00mg of C284793!

 Warning  NULL Quote: 1.00mg of C284848!

 Warning  NULL Quote: 2.00mg of C284842!

 Warning  NULL Quote: 1.00mg of C285479!

 Warning  NULL Quote: 1.00mg of C285537!

 Warning  NULL Quote: 2.00mg of C284762!

 Warning  NULL Quote: 1.00mg of C284775!

 Warning  NULL Quote: 1.00mg of C284776!

 Warning  NULL Quote: 1.00mg of C285917!

 Warning  NULL Quote: 1.00mg of C285918!

 Warning  NULL Quote: 1.00mg of C284867!

 Warning  NULL Quote: 1.00mg of C284868!

 Warning  NULL Quote: 1.00mg of C284134!

 Warning  NULL Quote: 1.00mg of C285606!

 Warning  NULL Quote: 1.00mg of C285607!

 Warning  NULL Quote: 1.00mg of C285416!

 Warning  NULL Quote: 1.00mg of C286116!

 Warning  NULL Quote: 1.00mg of C286039!

 Warning  NULL Quote: 1.00mg of C286040!

 Warning  NULL Quote: 1.00mg of C286072!

 Warning  NULL Quote: 1.00mg of C285904!

 Warning  NULL Quote: 1.00mg of C285922!

 Warning  NULL Quote: 1.00mg of C285624!

 Warning  NULL Quote: 1.00mg of C1873!

 Warning  NULL Quote: 1.00mg of C285952!

 Warning  NULL Quote: 5.00mg of C283151!

 Warning  NULL Quote: 1.00mg of C284368!

 Warning  NULL Quote: 2.00mg of C284354!

 Warning  NULL Quote: 1.00mg of C285054!

 Warning  NULL Quote: 2.00mg of C283598!

 Warning  NULL Quote: 1.00mg of C285050!

 Warning  NULL Quote: 1.00mg of C285895!

 Warning  NULL Quote: 2.00mg of C283595!

 Warning  NULL Quote: 1.00mg of C285692!

 Warning  NULL Quote: 1.00mg of C285693!

 Warning  NULL Quote: 2.00mg of C284276!

 Warning  NULL Quote: 1.00mg of C284861!

 Warning  NULL Quote: 1.00mg of C285938!

 Warning  NULL Quote: 1.00mg of C285939!

 Warning  NULL Quote: 5.00mg of C282917!

 Warning  NULL Quote: 1.00mg of C285476!

 Warning  NULL Quote: 1.00mg of C285477!

 Warning  NULL Quote: 1.00mg of C284952!

 Warning  NULL Quote: 1.00mg of C284953!

 Warning  NULL Quote: 1.00mg of C285087!

 Warning  NULL Quote: 1.00mg of C285088!

 Warning  NULL Quote: 1.00mg of C285375!

 Warning  NULL Quote: 1.00mg of C285376!

 Warning  NULL Quote: 1.00mg of C285386!

 Warning  NULL Quote: 1.00mg of C284831!

 Warning  NULL Quote: 1.00mg of C284832!

 Warning  NULL Quote: 2.00mg of C284548!

 Warning  NULL Quote: 1.00mg of C285137!

 Warning  NULL Quote: 1.00mg of C285548!

 Warning  NULL Quote: 1.00mg of C285549!

 Warning  NULL Quote: 1.00mg of C284947!

 Warning  NULL Quote: 1.00mg of C284948!

 Warning  NULL Quote: 1.00mg of C10144!

 Warning  NULL Quote: 6.00mg of C283867!

 Warning  NULL Quote: 1.00mg of C284944!

 Warning  NULL Quote: 1.00mg of C285438!

 Warning  NULL Quote: 1.00mg of C284796!

 Warning  NULL Quote: 2.00mg of C284852!

 Warning  NULL Quote: 1.00mg of C284688!

 Warning  NULL Quote: 1.00mg of C284689!

 Warning  NULL Quote: 1.00mg of C285266!

 Warning  NULL Quote: 1.00mg of C285249!

 Warning  NULL Quote: 1.00mg of C285250!

 Warning  NULL Quote: 1.00mg of C285091!

 Warning  NULL Quote: 1.00mg of C285092!

 Warning  NULL Quote: 1.00mg of C284897!

 Warning  NULL Quote: 2.00mg of C65033!

 Warning  NULL Quote: 1.00mg of C285703!

 Warning  NULL Quote: 1.00mg of C285756!

 Warning  NULL Quote: 1.00mg of C22696!

 Warning  NULL Quote: 1.00mg of C5710!

 Warning  NULL Quote: 1.00mg of C285948!

 Warning  NULL Quote: 1.00mg of C285949!

 Warning  NULL Quote: 2.00mg of C283832!

 Warning  NULL Quote: 1.00mg of C285355!

 Warning  NULL Quote: 1.00mg of C285238!

 Warning  NULL Quote: 1.00mg of C285239!

 Warning  NULL Quote: 3.00mg of C285080!

 Warning  NULL Quote: 1.00mg of C285956!

 Warning  NULL Quote: 1.00mg of C285107!

 Warning  NULL Quote: 1.00mg of C285079!

 Warning  NULL Quote: 1.00mg of C285666!

 Warning  NULL Quote: 1.00mg of C285667!

 Warning  NULL Quote: 1.00mg of C285411!

 Warning  NULL Quote: 1.00mg of C284977!

 Warning  NULL Quote: 1.00mg of C284978!

 Warning  NULL Quote: 1.00mg of C285147!

 Warning  NULL Quote: 4.00mg of C284760!

 Warning  NULL Quote: 1.00mg of C284860!

 Warning  NULL Quote: 1.00mg of C285944!

 Warning  NULL Quote: 1.00mg of C284761!

 Warning  NULL Quote: 5.00mg of C283896!

 Warning  NULL Quote: 1.00mg of C285069!

 Warning  NULL Quote: 1.00mg of C285790!

 Warning  NULL Quote: 1.00mg of C285113!

 Warning  NULL Quote: 1.00mg of C285095!

 Warning  NULL Quote: 2.00mg of C284388!

 Warning  NULL Quote: 1.00mg of C285975!

 Warning  NULL Quote: 1.00mg of C285288!

 Warning  NULL Quote: 1.00mg of C285289!

 Warning  NULL Quote: 1.00mg of C284140!

 Warning  NULL Quote: 1.00mg of C284663!

 Warning  NULL Quote: 1.00mg of C285976!

 Warning  NULL Quote: 1.00mg of C285977!

 Warning  NULL Quote: 1.00mg of C285118!

 Warning  NULL Quote: 3.00mg of C283914!

 Warning  NULL Quote: 1.00mg of C284463!

 Warning  NULL Quote: 1.00mg of C285999!

 Warning  NULL Quote: 1.00mg of C286000!

 Warning  NULL Quote: 1.00mg of C286062!

 Warning  NULL Quote: 1.00mg of C285776!

 Warning  NULL Quote: 1.00mg of C285777!

 Warning  NULL Quote: 1.00mg of C285551!

 Warning  NULL Quote: 1.00mg of C285552!

 Warning  NULL Quote: 1.00mg of C285179!

 Warning  NULL Quote: 1.00mg of C284918!

 Warning  NULL Quote: 1.00mg of C285119!

 Warning  NULL Quote: 1.00mg of C285120!

 Warning  NULL Quote: 2.00mg of C284188!

 Warning  NULL Quote: 1.00mg of C285755!

 Warning  NULL Quote: 1.00mg of C285725!

 Warning  NULL Quote: 1.00mg of C285726!

 Warning  NULL Quote: 1.00mg of C285709!

 Warning  NULL Quote: 1.00mg of C285710!

 Warning  NULL Quote: 1.00mg of C284712!

 Warning  NULL Quote: 1.00mg of C284713!

 Warning  NULL Quote: 1.00mg of C286013!

 Warning  NULL Quote: 1.00mg of C286018!

 Warning  NULL Quote: 1.00mg of C286022!

 Warning  NULL Quote: 1.00mg of C284924!

 Warning  NULL Quote: 1.00mg of C285389!

 Warning  NULL Quote: 2.00mg of C284586!

 Warning  NULL Quote: 1.00mg of C285888!

 Warning  NULL Quote: 1.00mg of C284873!

 Warning  NULL Quote: 1.00mg of C285986!

 Warning  NULL Quote: 1.00mg of C285987!

 Warning  NULL Quote: 1.00mg of C285473!

 Warning  NULL Quote: 1.00mg of C285197!

 Warning  NULL Quote: 1.00mg of C285184!

 Warning  NULL Quote: 2.00mg of C284627!

 Warning  NULL Quote: 1.00mg of C284645!

 Warning  NULL Quote: 1.00mg of C284628!

 Warning  NULL Quote: 3.00mg of C284363!

 Warning  NULL Quote: 1.00mg of C286008!

 Warning  NULL Quote: 3.00mg of C284240!

 Warning  NULL Quote: 1.00mg of C284938!

 Warning  NULL Quote: 2.00mg of C284266!

 Warning  NULL Quote: 1.00mg of C285879!

 Warning  NULL Quote: 1.00mg of C284863!

 Warning  NULL Quote: 1.00mg of C284864!

 Warning  NULL Quote: 1.00mg of C46461!

 Warning  NULL Quote: 1.00mg of C284671!

 Warning  NULL Quote: 1.00mg of C285889!

 Warning  NULL Quote: 1.00mg of C284971!

 Warning  NULL Quote: 1.00mg of C284972!

 Warning  NULL Quote: 1.00mg of C285785!

 Warning  NULL Quote: 1.00mg of C285786!

 Warning  NULL Quote: 1.00mg of C285140!

 Warning  NULL Quote: 1.00mg of C285141!

 Warning  NULL Quote: 1.00mg of C285659!

 Warning  NULL Quote: 1.00mg of C285660!

 Warning  NULL Quote: 1.00mg of C285745!

 Warning  NULL Quote: 1.00mg of C284674!

 Warning  NULL Quote: 2.00mg of C284112!

 Warning  NULL Quote: 1.00mg of C285770!

 Warning  NULL Quote: 1.00mg of C285771!

 Warning  NULL Quote: 1.00mg of C284811!

 Warning  NULL Quote: 1.00mg of C283067!

 Warning  NULL Quote: 1.00mg of C285446!

 Warning  NULL Quote: 1.00mg of C285924!

 Warning  NULL Quote: 1.00mg of C285842!

 Warning  NULL Quote: 1.00mg of C285665!

 Warning  NULL Quote: 1.00mg of C285166!

 Warning  NULL Quote: 1.00mg of C285167!

 Warning  NULL Quote: 1.00mg of C283917!

 Warning  NULL Quote: 1.00mg of C6519!

 Warning  NULL Quote: 1.00mg of C285652!

 Warning  NULL Quote: 1.00mg of C285653!

 Warning  NULL Quote: 1.00mg of C284506!

 Warning  NULL Quote: 1.00mg of C284507!

 Warning  NULL Quote: 3.00mg of C284768!

 Warning  NULL Quote: 2.00mg of C284239!

 Warning  NULL Quote: 1.00mg of C285256!

 Warning  NULL Quote: 1.00mg of C285596!

 Warning  NULL Quote: 2.00mg of C285246!

 Warning  NULL Quote: 1.00mg of C285247!

 Warning  NULL Quote: 2.00mg of C285275!

 Warning  NULL Quote: 1.00mg of C285870!

 Warning  NULL Quote: 2.00mg of C284377!

 Warning  NULL Quote: 2.00mg of C284885!

 Warning  NULL Quote: 1.00mg of C284536!

 Warning  NULL Quote: 1.00mg of C284675!

 Warning  NULL Quote: 1.00mg of C284024!

 Warning  NULL Quote: 1.00mg of C285716!

 Warning  NULL Quote: 1.00mg of C285027!

 Warning  NULL Quote: 1.00mg of C285566!

 Warning  NULL Quote: 1.00mg of C285024!

 Warning  NULL Quote: 1.00mg of C285025!

 Warning  NULL Quote: 1.00mg of C285371!

 Warning  NULL Quote: 1.00mg of C285372!

 Warning  NULL Quote: 1.00mg of C285083!

 Warning  NULL Quote: 1.00mg of C285335!

 Warning  NULL Quote: 1.00mg of C285336!

 Warning  NULL Quote: 1.00mg of C14914!

 Warning  NULL Quote: 1.00mg of C284545!

 Warning  NULL Quote: 2.00mg of C284251!

 Warning  NULL Quote: 1.00mg of C284786!

 Warning  NULL Quote: 1.00mg of C284787!

 Warning  NULL Quote: 1.00mg of C285592!

 Warning  NULL Quote: 1.00mg of C285593!

 Warning  NULL Quote: 1.00mg of C285712!

 Warning  NULL Quote: 1.00mg of C284126!

 Warning  NULL Quote: 1.00mg of C284421!

 Warning  NULL Quote: 1.00mg of C284779!

 Warning  NULL Quote: 1.00mg of C284638!

 Warning  NULL Quote: 1.00mg of C284639!

 Warning  NULL Quote: 1.00mg of C286023!

 Warning  NULL Quote: 1.00mg of C285330!

 Warning  NULL Quote: 1.00mg of C285694!

 Warning  NULL Quote: 1.00mg of C285883!

 Warning  NULL Quote: 1.00mg of C285884!

 Warning  NULL Quote: 1.00mg of C284807!

 Warning  NULL Quote: 1.00mg of C285282!

 Warning  NULL Quote: 1.00mg of C285887!

 Warning  NULL Quote: 1.00mg of C285299!

 Warning  NULL Quote: 1.00mg of C285744!

 Warning  NULL Quote: 1.00mg of C285287!

 Warning  NULL Quote: 1.00mg of C285743!

 Warning  NULL Quote: 1.00mg of C285106!

 Warning  NULL Quote: 2.00mg of C284758!

 Warning  NULL Quote: 1.00mg of C284882!

 Warning  NULL Quote: 1.00mg of C284577!

 Warning  NULL Quote: 1.00mg of C284578!

 Warning  NULL Quote: 2.00mg of C284136!

 Warning  NULL Quote: 1.00mg of C285237!

 Warning  NULL Quote: 1.00mg of C283970!

 Warning  NULL Quote: 1.00mg of C286101!

 Warning  NULL Quote: 2.00mg of C95371!

 Warning  NULL Quote: 1.00mg of C285412!

 Warning  NULL Quote: 1.00mg of C284103!

 Warning  NULL Quote: 1.00mg of C283776!

 Warning  NULL Quote: 1.00mg of C283777!

 Warning  NULL Quote: 5.00mg of C283996!

 Warning  NULL Quote: 1.00mg of C284206!

 Warning  NULL Quote: 1.00mg of C285235!

 Warning  NULL Quote: 1.00mg of C285236!

 Warning  NULL Quote: 2.00mg of C283880!

 Warning  NULL Quote: 1.00mg of C284585!

 Warning  NULL Quote: 1.00mg of C284593!

 Warning  NULL Quote: 1.00mg of C284594!

 Warning  NULL Quote: 1.00mg of C284588!

 Warning  NULL Quote: 1.00mg of C284589!

 Warning  NULL Quote: 1.00mg of C286138!

 Warning  NULL Quote: 1.00mg of C286139!

 Warning  NULL Quote: 1.00mg of C285878!

 Warning  NULL Quote: 1.00mg of C285738!

 Warning  NULL Quote: 1.00mg of C285739!

 Warning  NULL Quote: 2.00mg of C284691!

 Warning  NULL Quote: 2.00mg of C284259!

 Warning  NULL Quote: 1.00mg of C285762!

 Warning  NULL Quote: 1.00mg of C285690!

 Warning  NULL Quote: 1.00mg of C285691!

 Warning  NULL Quote: 1.00mg of C48047!

 Warning  NULL Quote: 1.00mg of C285804!

 Warning  NULL Quote: 1.00mg of C284347!

 Warning  NULL Quote: 1.00mg of C284564!

 Warning  NULL Quote: 1.00mg of C285761!

 Warning  NULL Quote: 1.00mg of C284540!

 Warning  NULL Quote: 2.00mg of C284541!

 Warning  NULL Quote: 1.00mg of C285822!

 Warning  NULL Quote: 1.00mg of C285823!

 Warning  NULL Quote: 1.00mg of C285472!

 Warning  NULL Quote: 2.00mg of C18206!

 Warning  NULL Quote: 1.00mg of C285151!

 Warning  NULL Quote: 1.00mg of C284630!

 Warning  NULL Quote: 1.00mg of C285139!

 Warning  NULL Quote: 1.00mg of C285352!

 Warning  NULL Quote: 1.00mg of C6247!

 Warning  NULL Quote: 1.00mg of C284348!

 Warning  NULL Quote: 1.00mg of C284748!

 Warning  NULL Quote: 1.00mg of C284743!

 Warning  NULL Quote: 1.00mg of C284744!

 Warning  NULL Quote: 1.00mg of C284461!

 Warning  NULL Quote: 1.00mg of C284462!

 Warning  NULL Quote: 1.00mg of C284919!

 Warning  NULL Quote: 1.00mg of C285925!

 Warning  NULL Quote: 1.00mg of C285926!

 Warning  NULL Quote: 1.00mg of C284607!

 Warning  NULL Quote: 1.00mg of C284608!

 Warning  NULL Quote: 2.00mg of C284741!

 Warning  NULL Quote: 1.00mg of C284742!

 Warning  NULL Quote: 1.00mg of C285511!

 Warning  NULL Quote: 1.00mg of C285950!

 Warning  NULL Quote: 1.00mg of C285951!

 Warning  NULL Quote: 2.00mg of C284853!

 Warning  NULL Quote: 1.00mg of C285921!

 Warning  NULL Quote: 2.00mg of C284065!

 Warning  NULL Quote: 1.00mg of C285035!

 Warning  NULL Quote: 1.00mg of C284989!

 Warning  NULL Quote: 1.00mg of C285724!

 Warning  NULL Quote: 1.00mg of C285305!

 Warning  NULL Quote: 1.00mg of C285306!

 Warning  NULL Quote: 1.00mg of C285071!

 Warning  NULL Quote: 1.00mg of C284658!

 Warning  NULL Quote: 1.00mg of C285799!

 Warning  NULL Quote: 1.00mg of C285435!

 Warning  NULL Quote: 1.00mg of C285436!

 Warning  NULL Quote: 1.00mg of C283126!

 Warning  NULL Quote: 1.00mg of C285642!

 Warning  NULL Quote: 1.00mg of C284805!

 Warning  NULL Quote: 1.00mg of C284806!

 Warning  NULL Quote: 1.00mg of C284412!

 Warning  NULL Quote: 1.00mg of C286005!

 Warning  NULL Quote: 1.00mg of C4746!

 Warning  NULL Quote: 1.00mg of C285445!

 Warning  NULL Quote: 1.00mg of C285494!

 Warning  NULL Quote: 1.00mg of C4759!

 Warning  NULL Quote: 1.00mg of C4765!

 Warning  NULL Quote: 1.00mg of C284738!

 Warning  NULL Quote: 1.00mg of C284883!

 Warning  NULL Quote: 1.00mg of C284884!

 Warning  NULL Quote: 2.00mg of C284934!

 Warning  NULL Quote: 1.00mg of C284935!

 Warning  NULL Quote: 1.00mg of C285645!

 Warning  NULL Quote: 1.00mg of C285218!

 Warning  NULL Quote: 1.00mg of C285219!

 Warning  NULL Quote: 1.00mg of C285524!

 Warning  NULL Quote: 1.00mg of C285957!

 Warning  NULL Quote: 1.00mg of C284237!

 Warning  NULL Quote: 1.00mg of C284238!

 Warning  NULL Quote: 1.00mg of C285634!

 Warning  NULL Quote: 2.00mg of C285843!

 Warning  NULL Quote: 1.00mg of C286012!

 Warning  NULL Quote: 1.00mg of C285844!

 Warning  NULL Quote: 1.00mg of C285622!

 Warning  NULL Quote: 1.00mg of C285623!

 Warning  NULL Quote: 2.00mg of C284409!

 Warning  NULL Quote: 1.00mg of C284752!

 Warning  NULL Quote: 2.00mg of C285414!

 Warning  NULL Quote: 1.00mg of C285828!

 Warning  NULL Quote: 1.00mg of C285415!

 Warning  NULL Quote: 1.00mg of C284311!

 Warning  NULL Quote: 1.00mg of C284922!

 Warning  NULL Quote: 1.00mg of C284923!

 Warning  NULL Quote: 1.00mg of C284963!

 Warning  NULL Quote: 1.00mg of C284964!

 Warning  NULL Quote: 1.00mg of C285254!

 Warning  NULL Quote: 1.00mg of C285255!

 Warning  NULL Quote: 1.00mg of C285449!

 Warning  NULL Quote: 4.00mg of C283795!

 Warning  NULL Quote: 1.00mg of C284878!

 Warning  NULL Quote: 1.00mg of C284879!

 Warning  NULL Quote: 1.00mg of C285122!

 Warning  NULL Quote: 1.00mg of C284681!

 Warning  NULL Quote: 2.00mg of C284812!

 Warning  NULL Quote: 1.00mg of C284813!

 Warning  NULL Quote: 1.00mg of C285144!

 Warning  NULL Quote: 1.00mg of C285145!

 Warning  NULL Quote: 1.00mg of C285789!

 Warning  NULL Quote: 1.00mg of C285509!

 Warning  NULL Quote: 1.00mg of C284616!

 Warning  NULL Quote: 1.00mg of C284617!

 Warning  NULL Quote: 1.00mg of C285791!

 Warning  NULL Quote: 1.00mg of C285792!

 Warning  NULL Quote: 1.00mg of C285576!

 Warning  NULL Quote: 1.00mg of C286098!

 Warning  NULL Quote: 1.00mg of C285063!

 Warning  NULL Quote: 2.00mg of C284015!

 Warning  NULL Quote: 1.00mg of C284225!

 Warning  NULL Quote: 1.00mg of C285213!

 Warning  NULL Quote: 3.00mg of C283875!

 Warning  NULL Quote: 1.00mg of C285234!

 Warning  NULL Quote: 1.00mg of C285495!

 Warning  NULL Quote: 1.00mg of C285496!

 Warning  NULL Quote: 1.00mg of C284013!

 Warning  NULL Quote: 4.00mg of C284014!

 Warning  NULL Quote: 1.00mg of C285522!

 Warning  NULL Quote: 1.00mg of C285523!

 Warning  NULL Quote: 1.00mg of C284573!

 Warning  NULL Quote: 1.00mg of C284898!

 Warning  NULL Quote: 1.00mg of C284899!

 Warning  NULL Quote: 1.00mg of C284501!

 Warning  NULL Quote: 1.00mg of C284502!

 Warning  NULL Quote: 1.00mg of C1877!

 Warning  NULL Quote: 1.00mg of C25769!

 Warning  NULL Quote: 1.00mg of C284794!

 Warning  NULL Quote: 1.00mg of C285191!

 Warning  NULL Quote: 2.00mg of C285161!

 Warning  NULL Quote: 1.00mg of C285628!

 Warning  NULL Quote: 1.00mg of C283948!

 Warning  NULL Quote: 1.00mg of C283949!

 Warning  NULL Quote: 1.00mg of C284189!

 Warning  NULL Quote: 2.00mg of C284026!

 Warning  NULL Quote: 1.00mg of C285816!

 Warning  NULL Quote: 1.00mg of C284824!

 Warning  NULL Quote: 1.00mg of C285498!

 Warning  NULL Quote: 1.00mg of C285499!

 Warning  NULL Quote: 1.00mg of C285274!

 Warning  NULL Quote: 1.00mg of C11912!

 Warning  NULL Quote: 1.00mg of C284849!

 Warning  NULL Quote: 1.00mg of C285559!

 Warning  NULL Quote: 1.00mg of C285560!

 Warning  NULL Quote: 1.00mg of C285413!

 Warning  NULL Quote: 1.00mg of C284987!

 Warning  NULL Quote: 1.00mg of C284988!

 Warning  NULL Quote: 1.00mg of C285874!

 Warning  NULL Quote: 1.00mg of C285875!

 Warning  NULL Quote: 2.00mg of C283038!

 Warning  NULL Quote: 1.00mg of C285546!

 Warning  NULL Quote: 1.00mg of C285547!

 Warning  NULL Quote: 1.00mg of C285998!

 Warning  NULL Quote: 2.00mg of C285984!

 Warning  NULL Quote: 1.00mg of C284476!

 Warning  NULL Quote: 5.00mg of C284477!

 Warning  NULL Quote: 1.00mg of C285985!

 Warning  NULL Quote: 1.00mg of C285995!

 Warning  NULL Quote: 1.00mg of C284500!

 Warning  NULL Quote: 1.00mg of C285481!

 Warning  NULL Quote: 1.00mg of C284508!

 Warning  NULL Quote: 1.00mg of C285529!

 Warning  NULL Quote: 1.00mg of C285530!

 Warning  NULL Quote: 1.00mg of C10288!

 Warning  NULL Quote: 1.00mg of C286017!

 Warning  NULL Quote: 1.00mg of C284410!

 Warning  NULL Quote: 1.00mg of C284411!

 Warning  NULL Quote: 1.00mg of C285185!

 Warning  NULL Quote: 1.00mg of C285186!

 Warning  NULL Quote: 1.00mg of C22714!

 Warning  NULL Quote: 1.00mg of C284587!

 Warning  NULL Quote: 1.00mg of C283751!

 Warning  NULL Quote: 1.00mg of C284856!

 Warning  NULL Quote: 1.00mg of C284857!

 Warning  NULL Quote: 1.00mg of C284466!

 Warning  NULL Quote: 1.00mg of C284467!

 Warning  NULL Quote: 1.00mg of C284515!

 Warning  NULL Quote: 1.00mg of C284516!

 Warning  NULL Quote: 3.00mg of C283790!

 Warning  NULL Quote: 1.00mg of C285229!

 Warning  NULL Quote: 3.00mg of C284077!

 Warning  NULL Quote: 1.00mg of C284817!

 Warning  NULL Quote: 1.00mg of C285242!

 Warning  NULL Quote: 1.00mg of C285243!

 Warning  NULL Quote: 1.00mg of C284990!

 Warning  NULL Quote: 1.00mg of C285835!

 Warning  NULL Quote: 1.00mg of C285845!

 Warning  NULL Quote: 1.00mg of C285846!

 Warning  NULL Quote: 1.00mg of C285974!

 Warning  NULL Quote: 1.00mg of C285163!

 Warning  NULL Quote: 1.00mg of C285164!

 Warning  NULL Quote: 1.00mg of C285127!

 Warning  NULL Quote: 1.00mg of C285128!

 Warning  NULL Quote: 1.00mg of C285044!

 Warning  NULL Quote: 1.00mg of C286122!

 Warning  NULL Quote: 1.00mg of C286123!

 Warning  NULL Quote: 1.00mg of C284513!

 Warning  NULL Quote: 1.00mg of C284514!

 Warning  NULL Quote: 1.00mg of C285070!

 Warning  NULL Quote: 1.00mg of C285332!

 Warning  NULL Quote: 1.00mg of C285333!

 Warning  NULL Quote: 1.00mg of C285746!

 Warning  NULL Quote: 1.00mg of C285747!

 Warning  NULL Quote: 5.00mg of C283078!

 Warning  NULL Quote: 1.00mg of C284991!

 Warning  NULL Quote: 1.00mg of C284992!

 Warning  NULL Quote: 1.00mg of C285657!

 Warning  NULL Quote: 1.00mg of C285658!

 Warning  NULL Quote: 2.00mg of C284142!

 Warning  NULL Quote: 1.00mg of C285997!

 Warning  NULL Quote: 1.00mg of C285387!

 Warning  NULL Quote: 1.00mg of C284700!

 Warning  NULL Quote: 1.00mg of C284701!

 Warning  NULL Quote: 1.00mg of C284973!

 Warning  NULL Quote: 1.00mg of C284974!

 Warning  NULL Quote: 1.00mg of C284612!

 Warning  NULL Quote: 1.00mg of C285967!

 Warning  NULL Quote: 1.00mg of C73235!

 Warning  NULL Quote: 2.00mg of C283007!

 Warning  NULL Quote: 1.00mg of C284880!

 Warning  NULL Quote: 1.00mg of C284881!

 Warning  NULL Quote: 1.00mg of C4754!

 Warning  NULL Quote: 1.00mg of C284719!

 Warning  NULL Quote: 1.00mg of C284223!

 Warning  NULL Quote: 1.00mg of C284224!

 Warning  NULL Quote: 1.00mg of C284215!

 Warning  NULL Quote: 1.00mg of C284216!

 Warning  NULL Quote: 1.00mg of C285357!

 Warning  NULL Quote: 1.00mg of C284236!

 Warning  NULL Quote: 1.00mg of C285620!

 Warning  NULL Quote: 1.00mg of C285621!

 Warning  NULL Quote: 2.00mg of C283904!

 Warning  NULL Quote: 1.00mg of C285935!

 Warning  NULL Quote: 1.00mg of C285741!

 Warning  NULL Quote: 2.00mg of C284212!

 Warning  NULL Quote: 1.00mg of C284968!

 Warning  NULL Quote: 1.00mg of C284774!

 Warning  NULL Quote: 1.00mg of C285983!

 Warning  NULL Quote: 1.00mg of C284975!

 Warning  NULL Quote: 1.00mg of C284976!

 Warning  NULL Quote: 1.00mg of C285768!

 Warning  NULL Quote: 1.00mg of C284538!

 Warning  NULL Quote: 1.00mg of C284539!

 Warning  NULL Quote: 1.00mg of C286092!

 Warning  NULL Quote: 1.00mg of C284841!

 Warning  NULL Quote: 1.00mg of C284682!

 Warning  NULL Quote: 1.00mg of C284683!

 Warning  NULL Quote: 1.00mg of C286027!

 Warning  NULL Quote: 1.00mg of C285960!

 Warning  NULL Quote: 1.00mg of C285961!

 Warning  NULL Quote: 1.00mg of C285328!

 Warning  NULL Quote: 1.00mg of C285329!

 Warning  NULL Quote: 1.00mg of C285124!

 Warning  NULL Quote: 1.00mg of C285125!

 Warning  NULL Quote: 1.00mg of C284069!

 Warning  NULL Quote: 1.00mg of C284070!

 Warning  NULL Quote: 1.00mg of C285171!

 Warning  NULL Quote: 1.00mg of C285172!

 Warning  NULL Quote: 1.00mg of C285180!

 Warning  NULL Quote: 1.00mg of C284222!

 Warning  NULL Quote: 1.00mg of C283925!

 Warning  NULL Quote: 1.00mg of C3543!

 Warning  NULL Quote: 1.00mg of C285126!

 Warning  NULL Quote: 1.00mg of C285727!

 Warning  NULL Quote: 1.00mg of C285728!

 Warning  NULL Quote: 3.00mg of C283919!

 Warning  NULL Quote: 1.00mg of C285717!

 Warning  NULL Quote: 1.00mg of C283961!

 Warning  NULL Quote: 1.00mg of C283962!

 Warning  NULL Quote: 1.00mg of C283084!

 Warning  NULL Quote: 1.00mg of C283085!

 Warning  NULL Quote: 1.00mg of C284517!

 Warning  NULL Quote: 1.00mg of C284518!

 Warning  NULL Quote: 1.00mg of C282937!

 Warning  NULL Quote: 1.00mg of C285374!

 Warning  NULL Quote: 1.00mg of C285162!

 Warning  NULL Quote: 1.00mg of C284031!

 Warning  NULL Quote: 1.00mg of C283834!

 Warning  NULL Quote: 1.00mg of C285188!

 Warning  NULL Quote: 1.00mg of C285759!

 Warning  NULL Quote: 1.00mg of C284552!

 Warning  NULL Quote: 1.00mg of C284553!

 Warning  NULL Quote: 1.00mg of C285795!

 Warning  NULL Quote: 1.00mg of C285796!

 Warning  NULL Quote: 1.00mg of C285391!

 Warning  NULL Quote: 1.00mg of C285392!

 Warning  NULL Quote: 1.00mg of C285227!

 Warning  NULL Quote: 1.00mg of C285228!

 Warning  NULL Quote: 1.00mg of C284260!

 Warning  NULL Quote: 1.00mg of C284451!

 Warning  NULL Quote: 1.00mg of C284452!

 Warning  NULL Quote: 1.00mg of C283905!

 Warning  NULL Quote: 1.00mg of C284340!

 Warning  NULL Quote: 1.00mg of C284341!

 Warning  NULL Quote: 1.00mg of C284449!

 Warning  NULL Quote: 4.00mg of C283027!

 Warning  NULL Quote: 1.00mg of C284358!

 Warning  NULL Quote: 1.00mg of C284143!

 Warning  NULL Quote: 1.00mg of C284081!

 Warning  NULL Quote: 1.00mg of C284075!

 Warning  NULL Quote: 1.00mg of C284076!

 Warning  NULL Quote: 1.00mg of C284190!

 Warning  NULL Quote: 1.00mg of C284385!

 Warning  NULL Quote: 1.00mg of C284168!

 Warning  NULL Quote: 2.00mg of C283836!

 Warning  NULL Quote: 1.00mg of C284213!

 Warning  NULL Quote: 1.00mg of C284214!

 Warning  NULL Quote: 1.00mg of C284424!

 Warning  NULL Quote: 1.00mg of C284425!

 Warning  NULL Quote: 3.00mg of C284043!

 Warning  NULL Quote: 1.00mg of C284258!

 Warning  NULL Quote: 2.00mg of C283788!

 Warning  NULL Quote: 1.00mg of C283789!

 Warning  NULL Quote: 1.00mg of C284384!

 Warning  NULL Quote: 1.00mg of C284191!

 Warning  NULL Quote: 2.00mg of C284058!

 Warning  NULL Quote: 1.00mg of C284175!

 Warning  NULL Quote: 1.00mg of C284364!

 Warning  NULL Quote: 3.00mg of C45790!

 Warning  NULL Quote: 1.00mg of C283075!

 Warning  NULL Quote: 1.00mg of C283733!

 Warning  NULL Quote: 1.00mg of C284230!

 Warning  NULL Quote: 5.00mg of C283053!

 Warning  NULL Quote: 1.00mg of C283908!

 Warning  NULL Quote: 1.00mg of C2607!

 Warning  NULL Quote: 1.00mg of C283034!

 Warning  NULL Quote: 1.00mg of C284349!

 Warning  NULL Quote: 3.00mg of C284039!

 Warning  NULL Quote: 1.00mg of C284093!

 Warning  NULL Quote: 1.00mg of C284229!

 Warning  NULL Quote: 1.00mg of C284350!

 Warning  NULL Quote: 1.00mg of C284351!

 Warning  NULL Quote: 2.00mg of C284104!

 Warning  NULL Quote: 1.00mg of C284207!

 Warning  NULL Quote: 1.00mg of C283868!

 Warning  NULL Quote: 2.00mg of C284045!

 Warning  NULL Quote: 1.00mg of C283855!

 Warning  NULL Quote: 1.00mg of C284157!

 Warning  NULL Quote: 1.00mg of C284158!

 Warning  NULL Quote: 1.00mg of C283955!

 Warning  NULL Quote: 1.00mg of C283809!

 Warning  NULL Quote: 1.00mg of C284342!

 Warning  NULL Quote: 1.00mg of C284343!

 Warning  NULL Quote: 1.00mg of C284062!

 Warning  NULL Quote: 1.00mg of C284064!

 Warning  NULL Quote: 1.00mg of C284362!

 Warning  NULL Quote: 1.00mg of C2619!

 Warning  NULL Quote: 1.00mg of C283903!

 Warning  NULL Quote: 1.00mg of C283916!

 Warning  NULL Quote: 1.00mg of C284242!

 Warning  NULL Quote: 2.00mg of C283049!

 Warning  NULL Quote: 1.00mg of C283050!

 Warning  NULL Quote: 1.00mg of C283909!

 Warning  NULL Quote: 1.00mg of C283870!

 Warning  NULL Quote: 1.00mg of C284192!

 Warning  NULL Quote: 1.00mg of C284193!

 Warning  NULL Quote: 2.00mg of C6296!

 Warning  NULL Quote: 1.00mg of C284151!

 Warning  NULL Quote: 1.00mg of C284280!

 Warning  NULL Quote: 1.00mg of C284281!

 Warning  NULL Quote: 1.00mg of C284294!

 Warning  NULL Quote: 1.00mg of C284295!

 Warning  NULL Quote: 1.00mg of C284132!

 Warning  NULL Quote: 1.00mg of C284252!

 Warning  NULL Quote: 2.00mg of C284203!

 Warning  NULL Quote: 1.00mg of C284204!

 Warning  NULL Quote: 2.00mg of C283956!

 Warning  NULL Quote: 1.00mg of C284292!

 Warning  NULL Quote: 1.00mg of C283869!

 Warning  NULL Quote: 1.00mg of C283957!

 Warning  NULL Quote: 2.00mg of C283772!

 Warning  NULL Quote: 2.00mg of C283898!

 Warning  NULL Quote: 1.00mg of C283052!

 Warning  NULL Quote: 1.00mg of C182088!

 Warning  NULL Quote: 3.00mg of C284184!

 Warning  NULL Quote: 1.00mg of C283039!

 Warning  NULL Quote: 1.00mg of C283040!

 Warning  NULL Quote: 1.00mg of C284247!

 Warning  NULL Quote: 1.00mg of C284248!

 Warning  NULL Quote: 1.00mg of C284004!

 Warning  NULL Quote: 1.00mg of C284005!

 Warning  NULL Quote: 1.00mg of C283797!

 Warning  NULL Quote: 1.00mg of C283798!

 Warning  NULL Quote: 1.00mg of C284052!

 Warning  NULL Quote: 1.00mg of C284323!

 Warning  NULL Quote: 1.00mg of C283749!

 Warning  NULL Quote: 3.00mg of C283750!

 Warning  NULL Quote: 1.00mg of C284101!

 Warning  NULL Quote: 1.00mg of C284102!

 Warning  NULL Quote: 1.00mg of C284164!

 Warning  NULL Quote: 1.00mg of C283864!

 Warning  NULL Quote: 1.00mg of C283865!

 Warning  NULL Quote: 1.00mg of C284402!

 Warning  NULL Quote: 1.00mg of C284200!

 Warning  NULL Quote: 1.00mg of C284201!

 Warning  NULL Quote: 2.00mg of C284205!

 Warning  NULL Quote: 1.00mg of C284114!

 Warning  NULL Quote: 1.00mg of C284436!

 Warning  NULL Quote: 1.00mg of C283731!

 Warning  NULL Quote: 1.00mg of C284209!

 Warning  NULL Quote: 1.00mg of C283877!

 Warning  NULL Quote: 1.00mg of C283878!

 Warning  NULL Quote: 1.00mg of C283958!

 Warning  NULL Quote: 1.00mg of C283963!

 Warning  NULL Quote: 1.00mg of C283031!

 Warning  NULL Quote: 1.00mg of C284106!

 Warning  NULL Quote: 1.00mg of C284107!

 Warning  NULL Quote: 1.00mg of C283008!

 Warning  NULL Quote: 1.00mg of C284121!

 Warning  NULL Quote: 1.00mg of C284122!

 Warning  NULL Quote: 1.00mg of C283934!

 Warning  NULL Quote: 1.00mg of C48159!

 Warning  NULL Quote: 1.00mg of C284253!

 Warning  NULL Quote: 1.00mg of C283741!

 Warning  NULL Quote: 1.00mg of C283742!

 Warning  NULL Quote: 1.00mg of C283744!

 Warning  NULL Quote: 1.00mg of C283943!

 Warning  NULL Quote: 1.00mg of C283821!

 Warning  NULL Quote: 1.00mg of C284282!

 Warning  NULL Quote: 1.00mg of C283997!

 Warning  NULL Quote: 1.00mg of C283959!

 Warning  NULL Quote: 2.00mg of C283960!

 Warning  NULL Quote: 1.00mg of C284359!

 Warning  NULL Quote: 1.00mg of C284371!

 Warning  NULL Quote: 1.00mg of C284372!

 Warning  NULL Quote: 1.00mg of C284007!

 Warning  NULL Quote: 1.00mg of C284428!

 Warning  NULL Quote: 1.00mg of C284429!

 Warning  NULL Quote: 1.00mg of C284352!

 Warning  NULL Quote: 1.00mg of C284353!

 Warning  NULL Quote: 1.00mg of C284296!

 Warning  NULL Quote: 1.00mg of C284297!

 Warning  NULL Quote: 1.00mg of C5719!

 Warning  NULL Quote: 1.00mg of C283913!

 Warning  NULL Quote: 1.00mg of C284008!

 Warning  NULL Quote: 1.00mg of C284009!

 Warning  NULL Quote: 1.00mg of C284087!

 Warning  NULL Quote: 1.00mg of C284088!

 Warning  NULL Quote: 6.00mg of C283025!

 Warning  NULL Quote: 1.00mg of C283910!

 Warning  NULL Quote: 1.00mg of C284355!

 Warning  NULL Quote: 3.00mg of C283866!

 Warning  NULL Quote: 1.00mg of C284032!

 Warning  NULL Quote: 1.00mg of C284049!

 Warning  NULL Quote: 2.00mg of C283047!

 Warning  NULL Quote: 1.00mg of C284367!

 Warning  NULL Quote: 2.00mg of C283771!

 Warning  NULL Quote: 1.00mg of C284445!

 Warning  NULL Quote: 1.00mg of C284446!

 Warning  NULL Quote: 1.00mg of C283952!

 Warning  NULL Quote: 1.00mg of C283953!

 Warning  NULL Quote: 1.00mg of C284197!

 Warning  NULL Quote: 1.00mg of C284198!

 Warning  NULL Quote: 1.00mg of C284293!

 Warning  NULL Quote: 2.00mg of C5512!

 Warning  NULL Quote: 1.00mg of C283838!

 Warning  NULL Quote: 1.00mg of C283794!

 Warning  NULL Quote: 1.00mg of C284187!

 Warning  NULL Quote: 1.00mg of C283010!

 Warning  NULL Quote: 1.00mg of C283011!

 Warning  NULL Quote: 1.00mg of C284053!

 Warning  NULL Quote: 1.00mg of C284328!

 Warning  NULL Quote: 1.00mg of C1830!

 Warning  NULL Quote: 1.00mg of C283839!

 Warning  NULL Quote: 1.00mg of C284398!

 Warning  NULL Quote: 1.00mg of C284254!

 Warning  NULL Quote: 1.00mg of C284202!

 Warning  NULL Quote: 1.00mg of C283871!

 Warning  NULL Quote: 1.00mg of C283872!

 Warning  NULL Quote: 2.00mg of C283080!

 Warning  NULL Quote: 1.00mg of C283775!

 Warning  NULL Quote: 2.00mg of C283926!

 Warning  NULL Quote: 1.00mg of C283927!

 Warning  NULL Quote: 4.00mg of C283774!

 Warning  NULL Quote: 1.00mg of C284322!

 Warning  NULL Quote: 1.00mg of C283900!

 Warning  NULL Quote: 1.00mg of C283773!

 Warning  NULL Quote: 1.00mg of C284194!

 Warning  NULL Quote: 1.00mg of C284338!

 Warning  NULL Quote: 1.00mg of C284339!

 Warning  NULL Quote: 1.00mg of C3756!

 Warning  NULL Quote: 1.00mg of C284144!

 Warning  NULL Quote: 1.00mg of C284155!

 Warning  NULL Quote: 1.00mg of C284170!

 Warning  NULL Quote: 1.00mg of C284312!

 Warning  NULL Quote: 1.00mg of C283998!

 Warning  NULL Quote: 1.00mg of C283932!

 Warning  NULL Quote: 1.00mg of C283719!

 Warning  NULL Quote: 1.00mg of C283720!

 Warning  NULL Quote: 1.00mg of C283076!

 Warning  NULL Quote: 1.00mg of C283059!

 Warning  NULL Quote: 2.00mg of C284226!

 Warning  NULL Quote: 2.00mg of C283071!

 Warning  NULL Quote: 1.00mg of C283920!

 Warning  NULL Quote: 1.00mg of C283745!

 Warning  NULL Quote: 1.00mg of C283746!

 Warning  NULL Quote: 1.00mg of C3760!

 Warning  NULL Quote: 1.00mg of C284404!

 Warning  NULL Quote: 1.00mg of C283048!

 Warning  NULL Quote: 1.00mg of C283881!

 Warning  NULL Quote: 1.00mg of C283882!

 Warning  NULL Quote: 1.00mg of C284393!

 Warning  NULL Quote: 2.00mg of C283947!

 Warning  NULL Quote: 1.00mg of C284330!

 Warning  NULL Quote: 1.00mg of C283069!

 Warning  NULL Quote: 1.00mg of C283070!

 Warning  NULL Quote: 1.00mg of C283822!

 Warning  NULL Quote: 1.00mg of C283823!

 Warning  NULL Quote: 1.00mg of C283029!

 Warning  NULL Quote: 1.00mg of C283030!

 Warning  NULL Quote: 1.00mg of C17441!

 Warning  NULL Quote: 2.00mg of C283740!

 Warning  NULL Quote: 1.00mg of C284166!

 Warning  NULL Quote: 1.00mg of C284167!

 Warning  NULL Quote: 1.00mg of C5336!

 Warning  NULL Quote: 1.00mg of C283033!

 Warning  NULL Quote: 1.00mg of C284186!

 Warning  NULL Quote: 1.00mg of C5169!

 Warning  NULL Quote: 1.00mg of C283985!

 Warning  NULL Quote: 2.00mg of C283990!

 Warning  NULL Quote: 1.00mg of C284079!

 Warning  NULL Quote: 1.00mg of C283991!

 Warning  NULL Quote: 1.00mg of C7678!

 Warning  NULL Quote: 1.00mg of C283979!

 Warning  NULL Quote: 1.00mg of C284033!

 Warning  NULL Quote: 1.00mg of C284034!

 Warning  NULL Quote: 1.00mg of C283035!

 Warning  NULL Quote: 1.00mg of C283036!

 Warning  NULL Quote: 1.00mg of C286087!

 Warning  NULL Quote: 1.00mg of C286088!

 Warning  NULL Quote: 1.00mg of C283734!

 Warning  NULL Quote: 1.00mg of C283735!

 Warning  NULL Quote: 1.00mg of C283993!

 Warning  NULL Quote: 1.00mg of C283994!

 Warning  NULL Quote: 1.00mg of C284450!

 Warning  NULL Quote: 1.00mg of C284066!

 Warning  NULL Quote: 1.00mg of C4675!

 Warning  NULL Quote: 1.00mg of C283061!

 Warning  NULL Quote: 4.00mg of C2611!

 Warning  NULL Quote: 1.00mg of C283897!

 Warning  NULL Quote: 1.00mg of C284123!

 Warning  NULL Quote: 1.00mg of C283989!

 Warning  NULL Quote: 1.00mg of C283023!

 Warning  NULL Quote: 1.00mg of C284183!

 Warning  NULL Quote: 1.00mg of C283072!

 Warning  NULL Quote: 1.00mg of C284208!

 Warning  NULL Quote: 1.00mg of C283780!

 Warning  NULL Quote: 1.00mg of C283781!

 Warning  NULL Quote: 1.00mg of C53833!

 Warning  NULL Quote: 1.00mg of C283024!

 Warning  NULL Quote: 1.00mg of C283942!

 Warning  NULL Quote: 1.00mg of C284261!

 Warning  NULL Quote: 1.00mg of C284275!

 Warning  NULL Quote: 1.00mg of C3671!

 Warning  NULL Quote: 1.00mg of C284316!

 Warning  NULL Quote: 1.00mg of C284360!

 Warning  NULL Quote: 1.00mg of C284361!

 Warning  NULL Quote: 1.00mg of C284108!

 Warning  NULL Quote: 2.00mg of C284109!

 Warning  NULL Quote: 1.00mg of C284241!

 Warning  NULL Quote: 1.00mg of C284124!

 Warning  NULL Quote: 1.00mg of C284125!

 Warning  NULL Quote: 1.00mg of C284249!

 Warning  NULL Quote: 1.00mg of C284250!

 Warning  NULL Quote: 1.00mg of C284050!

 Warning  NULL Quote: 1.00mg of C284051!

 Warning  NULL Quote: 1.00mg of C7948!

 Warning  NULL Quote: 1.00mg of C283028!

 Warning  NULL Quote: 1.00mg of C284725!

 Warning  NULL Quote: 1.00mg of C284378!

 Warning  NULL Quote: 1.00mg of C284443!

 Warning  NULL Quote: 1.00mg of C284444!

 Warning  NULL Quote: 1.00mg of C284147!

 Warning  NULL Quote: 1.00mg of C284044!

 Warning  NULL Quote: 1.00mg of C284020!

 Warning  NULL Quote: 1.00mg of C284021!

 Warning  NULL Quote: 1.00mg of C283843!

 Warning  NULL Quote: 1.00mg of C283844!

 Warning  NULL Quote: 1.00mg of C284227!

 Warning  NULL Quote: 1.00mg of C284228!

 Warning  NULL Quote: 1.00mg of C283019!

 Warning  NULL Quote: 1.00mg of C283020!

 Warning  NULL Quote: 1.00mg of C284279!

 Warning  NULL Quote: 1.00mg of C284071!

 Warning  NULL Quote: 1.00mg of C284072!

 Warning  NULL Quote: 1.00mg of C283918!

 Warning  NULL Quote: 1.00mg of C284218!

 Warning  NULL Quote: 1.00mg of C284219!

 Warning  NULL Quote: 1.00mg of C283923!

 Warning  NULL Quote: 1.00mg of C283079!

 Warning  NULL Quote: 1.00mg of C284055!

 Warning  NULL Quote: 1.00mg of C283812!

 Warning  NULL Quote: 1.00mg of C283813!

 Warning  NULL Quote: 1.00mg of C284035!

 Warning  NULL Quote: 1.00mg of C284036!

 Warning  NULL Quote: 1.00mg of C283842!

 Warning  NULL Quote: 2.00mg of C1796!

 Warning  NULL Quote: 1.00mg of C283891!

 Warning  NULL Quote: 1.00mg of C284010!

 Warning  NULL Quote: 1.00mg of C284334!

 Warning  NULL Quote: 1.00mg of C284335!

 Warning  NULL Quote: 1.00mg of C284369!

 Warning  NULL Quote: 1.00mg of C284370!

 Warning  NULL Quote: 1.00mg of C284149!

 Warning  NULL Quote: 1.00mg of C284150!

 Warning  NULL Quote: 1.00mg of C283944!

 Warning  NULL Quote: 1.00mg of C283945!

 Warning  NULL Quote: 1.00mg of C284115!

 Warning  NULL Quote: 1.00mg of C284116!

 Warning  NULL Quote: 1.00mg of C283895!

 Warning  NULL Quote: 1.00mg of C283081!

 Warning  NULL Quote: 1.00mg of C284113!

 Warning  NULL Quote: 1.00mg of C6752!

 Warning  NULL Quote: 1.00mg of C284110!

 Warning  NULL Quote: 1.00mg of C284111!

 Warning  NULL Quote: 1.00mg of C283911!

 Warning  NULL Quote: 1.00mg of C283912!

 Warning  NULL Quote: 1.00mg of C284283!

 Warning  NULL Quote: 1.00mg of C284284!

 Warning  NULL Quote: 1.00mg of C284083!

 Warning  NULL Quote: 1.00mg of C284408!

 Warning  NULL Quote: 2.00mg of C283304!

 Warning  NULL Quote: 1.00mg of C283831!

 Warning  NULL Quote: 1.00mg of C283974!

 Warning  NULL Quote: 1.00mg of C283975!

 Warning  NULL Quote: 1.00mg of C284023!

 Warning  NULL Quote: 1.00mg of C283915!

 Warning  NULL Quote: 1.00mg of C284098!

 Warning  NULL Quote: 1.00mg of C284099!

 Warning  NULL Quote: 1.00mg of C283738!

 Warning  NULL Quote: 1.00mg of C283739!

 Warning  NULL Quote: 1.00mg of C283747!

 Warning  NULL Quote: 1.00mg of C283748!

 Warning  NULL Quote: 1.00mg of C284181!

 Warning  NULL Quote: 1.00mg of C284182!

 Warning  NULL Quote: 1.00mg of C283968!

 Warning  NULL Quote: 1.00mg of C283969!

 Warning  NULL Quote: 1.00mg of C283062!

 Warning  NULL Quote: 1.00mg of C284399!

 Warning  NULL Quote: 1.00mg of C284400!

 Warning  NULL Quote: 2.00mg of C284478!

 Warning  NULL Quote: 1.00mg of C284479!

 Warning  NULL Quote: 1.00mg of C284483!

 Warning  NULL Quote: 1.00mg of C283946!

 Warning  NULL Quote: 3.00mg of C283017!

 Warning  NULL Quote: 1.00mg of C284320!

 Warning  NULL Quote: 1.00mg of C284321!

 Warning  NULL Quote: 1.00mg of C283873!

 Warning  NULL Quote: 1.00mg of C283874!

 Warning  NULL Quote: 2.00mg of C284091!

 Warning  NULL Quote: 1.00mg of C284329!

 Warning  NULL Quote: 1.00mg of C283892!

 Warning  NULL Quote: 1.00mg of C284405!

 Warning  NULL Quote: 1.00mg of C284406!

 Warning  NULL Quote: 1.00mg of C284131!

 Warning  NULL Quote: 1.00mg of C284426!

 Warning  NULL Quote: 1.00mg of C283778!

 Warning  NULL Quote: 1.00mg of C283779!

 Warning  NULL Quote: 1.00mg of C284285!

 Warning  NULL Quote: 1.00mg of C284267!

 Warning  NULL Quote: 1.00mg of C284135!

 Warning  NULL Quote: 1.00mg of C284185!

 Warning  NULL Quote: 2.00mg of C283055!

 Warning  NULL Quote: 1.00mg of C284324!

 Warning  NULL Quote: 1.00mg of C284379!

 Warning  NULL Quote: 1.00mg of C283889!

 Warning  NULL Quote: 1.00mg of C283890!

 Warning  NULL Quote: 1.00mg of C284255!

 Warning  NULL Quote: 1.00mg of C284256!

 Warning  NULL Quote: 1.00mg of C283848!

 Warning  NULL Quote: 1.00mg of C283849!

 Warning  NULL Quote: 2.00mg of C3451!

 Warning  NULL Quote: 1.00mg of C284019!

 Warning  NULL Quote: 1.00mg of C284397!

 Warning  NULL Quote: 1.00mg of C284303!

 Warning  NULL Quote: 1.00mg of C284300!

 Warning  NULL Quote: 1.00mg of C284298!

 Warning  NULL Quote: 1.00mg of C284299!

 Warning  NULL Quote: 1.00mg of C284403!

 Warning  NULL Quote: 1.00mg of C284017!

 Warning  NULL Quote: 2.00mg of C284018!

 Warning  NULL Quote: 1.00mg of C283054!

 Warning  NULL Quote: 1.00mg of C283791!

 Warning  NULL Quote: 1.00mg of C9152!

 Warning  NULL Quote: 1.00mg of C284148!

 Warning  NULL Quote: 1.00mg of C284447!

 Warning  NULL Quote: 1.00mg of C284448!

 Warning  NULL Quote: 1.00mg of C284137!

 Warning  NULL Quote: 1.00mg of C283782!

 Warning  NULL Quote: 1.00mg of C283783!

 Warning  NULL Quote: 1.00mg of C77571!

 Warning  NULL Quote: 1.00mg of C283899!

 Warning  NULL Quote: 1.00mg of C283073!

 Warning  NULL Quote: 1.00mg of C283727!

 Warning  NULL Quote: 1.00mg of C283828!

 Warning  NULL Quote: 1.00mg of C283829!

 Warning  NULL Quote: 1.00mg of C283833!

 Warning  NULL Quote: 1.00mg of C284156!

 Warning  NULL Quote: 1.00mg of C284245!

 Warning  NULL Quote: 1.00mg of C284246!

 Warning  NULL Quote: 1.00mg of C283792!

 Warning  NULL Quote: 1.00mg of C283793!

 Warning  NULL Quote: 1.00mg of C285358!

 Warning  NULL Quote: 1.00mg of C285359!

 Warning  NULL Quote: 1.00mg of C284375!

 Warning  NULL Quote: 1.00mg of C284211!

 Warning  NULL Quote: 1.00mg of C284927!

 Warning  NULL Quote: 1.00mg of C284928!

 Warning  NULL Quote: 1.00mg of C285679!

 Warning  NULL Quote: 1.00mg of C285680!

 Warning  NULL Quote: 1.00mg of C285285!

 Warning  NULL Quote: 1.00mg of C285286!

 Warning  NULL Quote: 1.00mg of C284692!

 Warning  NULL Quote: 1.00mg of C285663!

 Warning  NULL Quote: 1.00mg of C285664!

 Warning  NULL Quote: 1.00mg of C285251!

 Warning  NULL Quote: 1.00mg of C285252!

 Warning  NULL Quote: 1.00mg of C285365!

 Warning  NULL Quote: 1.00mg of C285366!

 Warning  NULL Quote: 1.00mg of C285304!

 Warning  NULL Quote: 1.00mg of C286060!

 Warning  NULL Quote: 2.00mg of C284886!

 Warning  NULL Quote: 1.00mg of C284926!

 Warning  NULL Quote: 1.00mg of C284887!

 Warning  NULL Quote: 1.00mg of C8567!

 Warning  NULL Quote: 1.00mg of C285350!

 Warning  NULL Quote: 1.00mg of C284764!

 Warning  NULL Quote: 1.00mg of C284765!

 Warning  NULL Quote: 1.00mg of C285319!

 Warning  NULL Quote: 1.00mg of C285320!

 Warning  NULL Quote: 1.00mg of C283785!

 Warning  NULL Quote: 1.00mg of C285672!

 Warning  NULL Quote: 1.00mg of C284560!

 Warning  NULL Quote: 1.00mg of C284561!

 Warning  NULL Quote: 1.00mg of C284797!

 Warning  NULL Quote: 1.00mg of C284407!

 Warning  NULL Quote: 1.00mg of C284839!

 Warning  NULL Quote: 1.00mg of C284840!

 Warning  NULL Quote: 1.00mg of C286099!

 Warning  NULL Quote: 1.00mg of C286100!

 Warning  NULL Quote: 1.00mg of C284936!

 Warning  NULL Quote: 1.00mg of C285689!

 Warning  NULL Quote: 1.00mg of C285757!

 Warning  NULL Quote: 1.00mg of C284659!

 Warning  NULL Quote: 1.00mg of C284660!

 Warning  NULL Quote: 1.00mg of C284829!

 Warning  NULL Quote: 1.00mg of C284830!

 Warning  NULL Quote: 1.00mg of C283847!

 Warning  NULL Quote: 1.00mg of C284690!

 Warning  NULL Quote: 1.00mg of C285814!

 Warning  NULL Quote: 1.00mg of C285815!

 Warning  NULL Quote: 1.00mg of C285817!

 Warning  NULL Quote: 1.00mg of C285818!

 Warning  NULL Quote: 1.00mg of C284854!

 Warning  NULL Quote: 1.00mg of C284855!

 Warning  NULL Quote: 1.00mg of C285862!

 Warning  NULL Quote: 1.00mg of C285863!

 Warning  NULL Quote: 1.00mg of C284925!

 Warning  NULL Quote: 1.00mg of C284766!

 Warning  NULL Quote: 1.00mg of C284767!

 Warning  NULL Quote: 1.00mg of C284179!

 Warning  NULL Quote: 1.00mg of C284180!

 Warning  NULL Quote: 1.00mg of C283824!

 Warning  NULL Quote: 1.00mg of C283825!

 Warning  NULL Quote: 1.00mg of C283045!

 Warning  NULL Quote: 1.00mg of C283879!

 Warning  NULL Quote: 1.00mg of C284365!

 Warning  NULL Quote: 1.00mg of C284366!

 Warning  NULL Quote: 1.00mg of C284287!

 Warning  NULL Quote: 1.00mg of C283950!

 Warning  NULL Quote: 1.00mg of C283951!

 Warning  NULL Quote: 1.00mg of C283815!

 Warning  NULL Quote: 1.00mg of C283816!

 Warning  NULL Quote: 1.00mg of C1493!

 Warning  NULL Quote: 1.00mg of C284199!

 Warning  NULL Quote: 1.00mg of C283936!

 Warning  NULL Quote: 1.00mg of C283937!

 Warning  NULL Quote: 1.00mg of C283938!

 Warning  NULL Quote: 1.00mg of C282907!

 Warning  NULL Quote: 1.00mg of C283006!

 Warning  NULL Quote: 1.00mg of C284336!

 Warning  NULL Quote: 1.00mg of C284337!

 Warning  NULL Quote: 1.00mg of C284217!

 Warning  NULL Quote: 1.00mg of C12667!

 Warning  NULL Quote: 2.00mg of C284059!

 Warning  NULL Quote: 1.00mg of C283922!

 Warning  NULL Quote: 1.00mg of C102928!

 Warning  NULL Quote: 1.00mg of C284427!

 Warning  NULL Quote: 1.00mg of C284002!

 Warning  NULL Quote: 1.00mg of C284003!

 Warning  NULL Quote: 1.00mg of C283988!

 Warning  NULL Quote: 1.00mg of C284376!

 Warning  NULL Quote: 1.00mg of C284025!

 Warning  NULL Quote: 1.00mg of C283056!

 Warning  NULL Quote: 1.00mg of C284419!

 Warning  NULL Quote: 1.00mg of C284420!

 Warning  NULL Quote: 1.00mg of C284438!

 Warning  NULL Quote: 1.00mg of C284439!

 Warning  NULL Quote: 1.00mg of C283037!

 Warning  NULL Quote: 1.00mg of C284319!

 Warning  NULL Quote: 1.00mg of C283826!

 Warning  NULL Quote: 1.00mg of C283827!

 Warning  NULL Quote: 1.00mg of C283018!

 Warning  NULL Quote: 1.00mg of C284332!

 Warning  NULL Quote: 1.00mg of C284333!

 Warning  NULL Quote: 1.00mg of C283964!

 Warning  NULL Quote: 1.00mg of C283966!

 Warning  NULL Quote: 1.00mg of C283967!

 Warning  NULL Quote: 1.00mg of C120956!

 Warning  NULL Quote: 1.00mg of C284028!

 Warning  NULL Quote: 1.00mg of C284029!

 Warning  NULL Quote: 1.00mg of C283876!

 Warning  NULL Quote: 1.00mg of C284090!

 Warning  NULL Quote: 1.00mg of C284057!

 Warning  NULL Quote: 1.00mg of C284060!

 Warning  NULL Quote: 1.00mg of C284061!

 Warning  NULL Quote: 1.00mg of C283012!

 Warning  NULL Quote: 1.00mg of C283013!

 Warning  NULL Quote: 1.00mg of C284067!

 Warning  NULL Quote: 1.00mg of C284068!

 Warning  NULL Quote: 1.00mg of C12081!

 Warning  NULL Quote: 1.00mg of C283845!

 Warning  NULL Quote: 1.00mg of C284386!

 Warning  NULL Quote: 1.00mg of C284387!

 Warning  NULL Quote: 1.00mg of C284389!

 Warning  NULL Quote: 1.00mg of C284759!

 Warning  NULL Quote: 1.00mg of C284724!

 Warning  NULL Quote: 1.00mg of C284487!

 Warning  NULL Quote: 1.00mg of C283021!

 Warning  NULL Quote: 1.00mg of C283022!

 Warning  NULL Quote: 1.00mg of C283901!

 Warning  NULL Quote: 1.00mg of C283902!

 Warning  NULL Quote: 1.00mg of C283893!

 Warning  NULL Quote: 1.00mg of C283894!

 Warning  NULL Quote: 1.00mg of C283830!

 Warning  NULL Quote: 1.00mg of C284574!

 Warning  NULL Quote: 1.00mg of C284598!

 Warning  NULL Quote: 1.00mg of C284599!

 Warning  NULL Quote: 1.00mg of C284676!

 Warning  NULL Quote: 1.00mg of C284677!

 Warning  NULL Quote: 1.00mg of C284604!

 Warning  NULL Quote: 1.00mg of C284605!

 Warning  NULL Quote: 1.00mg of C282966!

 Warning  NULL Quote: 1.00mg of C283086!

 Warning  NULL Quote: 1.00mg of C283094!

 Warning  NULL Quote: 1.00mg of C283095!

 Warning  NULL Quote: 1.00mg of C283096!

 Warning  NULL Quote: 1.00mg of C283097!

 Warning  NULL Quote: 1.00mg of C282909!

 Warning  NULL Quote: 1.00mg of C282910!

 Warning  NULL Quote: 1.00mg of C283110!

 Warning  NULL Quote: 1.00mg of C282994!

 Warning  NULL Quote: 1.00mg of C282991!

 Warning  NULL Quote: 1.00mg of C282992!

 Warning  NULL Quote: 1.00mg of C282985!

 Warning  NULL Quote: 1.00mg of C282986!

 Warning  NULL Quote: 3.00mg of C202220!

 Warning  NULL Quote: 1.00mg of C282973!

 Warning  NULL Quote: 1.00mg of C283405!

 Warning  NULL Quote: 1.00mg of C283406!

 Warning  NULL Quote: 1.00mg of C282989!

 Warning  NULL Quote: 1.00mg of C283596!

 Warning  NULL Quote: 1.00mg of C282967!

 Warning  NULL Quote: 1.00mg of C283374!

 Warning  NULL Quote: 1.00mg of C283375!

 Warning  NULL Quote: 1.00mg of C283196!

 Warning  NULL Quote: 1.00mg of C283197!

 Warning  NULL Quote: 1.00mg of C282982!

 Warning  NULL Quote: 1.00mg of C282990!

 Warning  NULL Quote: 1.00mg of C282940!

 Warning  NULL Quote: 1.00mg of C282941!

 Warning  NULL Quote: 1.00mg of C282942!

 Warning  NULL Quote: 3.00mg of C282944!

 Warning  NULL Quote: 1.00mg of C282945!

 Warning  NULL Quote: 3.00mg of C282946!

 Warning  NULL Quote: 1.00mg of C282949!

 Warning  NULL Quote: 3.00mg of C282952!

 Warning  NULL Quote: 1.00mg of C282950!

 Warning  NULL Quote: 1.00mg of C282951!

 Warning  NULL Quote: 1.00mg of C282953!

 Warning  NULL Quote: 1.00mg of C282947!

 Warning  NULL Quote: 1.00mg of C282948!

 Warning  NULL Quote: 1.00mg of C282955!

 Warning  NULL Quote: 1.00mg of C197048!

 Warning  NULL Quote: 1.00mg of C282954!

 Warning  NULL Quote: 1.00mg of C282969!

 Warning  NULL Quote: 1.00mg of C282970!

 Warning  NULL Quote: 1.00mg of C283437!

 Warning  NULL Quote: 1.00mg of C283438!

 Warning  NULL Quote: 1.00mg of C189853!

 Warning  NULL Quote: 1.00mg of C283163!

 Warning  NULL Quote: 1.00mg of C283123!

 Warning  NULL Quote: 1.00mg of C283124!

 Warning  NULL Quote: 1.00mg of C283129!

 Warning  NULL Quote: 1.00mg of C283137!

 Warning  NULL Quote: 1.00mg of C283138!

 Warning  NULL Quote: 1.00mg of C41!

 Warning  NULL Quote: 1.00mg of C282919!

 Warning  NULL Quote: 1.00mg of C283158!

 Warning  NULL Quote: 1.00mg of C283159!

 Warning  NULL Quote: 1.00mg of C283160!

 Warning  NULL Quote: 1.00mg of C282926!

 Warning  NULL Quote: 1.00mg of C282927!

 Warning  NULL Quote: 1.00mg of C282928!

 Warning  NULL Quote: 1.00mg of C282929!

 Warning  NULL Quote: 1.00mg of C283172!

 Warning  NULL Quote: 1.00mg of C283173!

 Warning  NULL Quote: 1.00mg of C283185!

 Warning  NULL Quote: 1.00mg of C283186!

 Warning  NULL Quote: 1.00mg of C282956!

 Warning  NULL Quote: 1.00mg of C282957!

 Warning  NULL Quote: 1.00mg of C283684!

 Warning  NULL Quote: 1.00mg of C283685!

 Warning  NULL Quote: 1.00mg of C283688!

 Warning  NULL Quote: 1.00mg of C283689!

 Warning  NULL Quote: 1.00mg of C283696!

 Warning  NULL Quote: 1.00mg of C283381!

 Warning  NULL Quote: 1.00mg of C282965!

 Warning  NULL Quote: 1.00mg of C282964!

 Warning  NULL Quote: 1.00mg of C283198!

 Warning  NULL Quote: 1.00mg of C283199!

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/syndirella/retrosynthesis/openbind_a71ev2a_c1_scaffo
lds.json...

In [10]:
recipe.write_CAR_csv("cycle_01/syndirella/retrosynthesis/openbind_a71ev2a_c1_scaffolds.csv")

DEBUG: Querying database for routes

DEBUG: Assembling route dictionary

DEBUG: Checking availability

Output()

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/syndirella/retrosynthesis/openbind_a71ev2a_c1_scaffo
lds_1steps.csv...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/syndirella/retrosynthesis/openbind_a71ev2a_c1_scaffo
lds.csv...

,target-names,no-steps,concentration-required-mM,amount-required-uL,batch-tag,reactant-1-1,reactant-2-1,reaction-product-smiles-1,reaction-name-1,reaction-recipe-1,reaction-groupby-column-1,reactant-3-1,reactant-4-1
0,C139485,1,None,None,None,O=C(Cc1cocn1)Nc1ccc2c(c1)C(O)CC2,<NA>,O=C(Cc1cocn1)Nc1ccc2c(c1)C(F)CC2,Hydroxy_to_fluoro,None,None,<NA>,<NA>
1,C140978,1,None,None,None,NCc1c[nH]nc1Br,COc1ccc(C(C)=O)cc1B1OC(C)(C)C(C)(C)O1,COc1ccc(C(C)=O)cc1-c1n[nH]cc1CN,Sp2-sp2_Suzuki_coupling,None,None,<NA>,<NA>
2,C140988,1,None,None,None,Cc1[nH]nc(B2OC(C)(C)C(C)(C)O2)c1CO,CNNc1ccccc1Br,CNNc1ccccc1-c1n[nH]c(C)c1CO,Sp2-sp2_Suzuki_coupling,None,None,<NA>,<NA>
3,C141599,1,None,None,None,COC(=O)c1cc(C)ncc1Br,CNN,COC(=O)c1cc(C)ncc1N(C)N,N-nucleophilic_aromatic_substitution,None,None,<NA>,<NA>
4,C141610,1,None,None,None,CCNCc1ccc(O)cn1,CC=O,CCNCc1ccc(OC=O)cn1,Haloform_reaction,None,None,<NA>,<NA>
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1208,C8155,1,None,None,None,O=S(=O)(Cl)N1CCCCC1,CC=CC=CCN,CC=CC=CCNS(=O)(=O)N1CCCCC1,Sulfonamide_Schotten-Baumann_with_amine_(inter...,None,None,<NA>,<NA>
1209,C4732,1,None,None,None,CBr,CC(=O)C1=NCCC1,CCC(=O)C1=NCCC1,Alpha_alkylation_of_ketone,None,None,<NA>,<NA>
1210,C3665,1,None,None,None,O=S(=O)(Oc1ccncc1)C(F)(F)F,CC1(C)OB(c2ncco2)OC1(C)C,c1cc(-c2ncco2)ccn1,Sp2-sp2_Suzuki_coupling,None,None,<NA>,<NA>
1211,C2086,1,None,None,None,O=C(O)C1CCCCN1,c1nc2c([nH]1)CCCC2,C1CCC(c2nc3c([nH]2)CCCC3)NC1,Minisci_reaction_with_carboxylic_acid_(intermo...,None,None,<NA>,<NA>
1212,C8142,1,None,None,None,CC(C)=O,O=CC1CCCNC1,CC(=O)CC(O)C1CCCNC1,Aldol_addition_carbonyl,None,None,<NA>,<NA>

# Mocassin testing

In [14]:
pset = animal.poses(tag="openbind_a71ev2a_c1_scaffolds")

In [15]:
pose = pset[1]
print(pose.tags)
pose

['openbind_a71ev2a_c1_knitwork_pure', 'BulkDock Fragalysis export', 'fragmenstein_placed',
'openbind_a71ev2a_c1_scaffolds']

C48074->P944: "XDBQWQWEVJPNBV-UHFFFAOYSA-N"

In [20]:
calculate_mocassin_tversky(pose.inspirations.mols, pose.mol, alpha=0.9, beta=0.1)

(0.266, 0.479, 0.052)

In [17]:
(pose + pose.inspirations).draw()

In [23]:
pose.inspirations.names

['A0556a', 'A3579a']

In [ ]:
(pose + pose.inspirations).write_sdf("P944.sdf")

# Count raw merge smiles

In [12]:
import pandas as pd

In [13]:
df = pd.read_csv("cycle_01/fragmenstein/fragmenstein_bulkdock_input.csv")
print(len(df))
print(len(df.drop_duplicates(subset=["smiles"])))

306598

168303

In [14]:
df = pd.read_csv("cycle_01/knitwork/knitwork_pure.csv")
print(len(df))
print(len(df.drop_duplicates(subset=["smiles"])))

1616879

89045

In [15]:
df = pd.read_csv("cycle_01/knitwork/knitwork_impure.csv")
print(len(df))
print(len(df.drop_duplicates(subset=["smiles"])))

1870052

62735

# Export Scaffolds with PDBs

In [6]:
pset = animal.poses(tag="openbind_a71ev2a_c1_scaffolds")
pset

poses tagged "openbind_a71ev2a_c1_scaffolds": {P × 1518}

In [7]:
pset.to_fragalysis("cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds.sdf",
    method="openbind_a71ev2a_c1_scaffolds", 
    submitter_name="Max Winokan", 
    submitter_institution="DLS", 
    submitter_email="max.winokan@diamond.ac.uk",
    copy_reference_pdbs=True,
)

DEBUG: 1518 poses in set

DEBUG: 1518 remaining after skipping null reference

DEBUG: 1518 remaining after skipping null inspirations

#poses = 1518

DEBUG: querying...

Output()

DEBUG: adding inspiration column(s)

DEBUG: adding tag column

DEBUG: adding subsite column

out_path =
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds.sdf

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A5393a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A3579a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A1081b.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A3616b.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A0309a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A3568a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A3623a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A1778a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A3990a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A4418a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A3618a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A3181b.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A2972a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A2629a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A3371a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A4274b.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A4445b.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A3956a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A0486a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A3564a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A3435a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A4320a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A1105b.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A0239a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A5151a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A0487a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A0501a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A0501b.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A0514a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A0528a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A0228a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A0229b.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A0237a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A0351a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A0359a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A0365a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A0387a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A0437a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A0719a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A1140a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A3188a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A1346a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A3986a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A1445a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A2290a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A2293a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A2304a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A2513a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A2846a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A3066a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A3175a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A3176a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A3222a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A3264a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A3279a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A3280a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A3305a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A3306a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A3324a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A3587a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A3392a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A3410a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A3488a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A3509b.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A3510a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A3593a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A3706b.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A3522a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A3557b.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A3884a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A3890a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A4018a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A4031a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A4035b.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A4295a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A4303b.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A4836a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A4310a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A4311a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A4315a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A4351a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A4214b.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A4239a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A4386a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A4388a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A4403a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A4416a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A4421a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A4423a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A4426a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A4449a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A4456b.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A4490a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A4519a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A4541b.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A4546a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A4583b.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A4611a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A4644b.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A4669a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A4710a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A4735a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A4742a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A4742b.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A4745a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A4476a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A4748a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A4751a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A4752a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A4774a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A4794a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A4798a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A4806b.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A4809a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A4846a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A4847a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A4873a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A4882b.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A4885b.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A4895a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A4899a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A4926a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A4974a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A4977a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A4994a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A4998a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A5015b.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A5036a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A3884b.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A5065a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A5090a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A5203b.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A5210a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A5219b.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A5222a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A5249a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A5289b.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A5339a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A5359a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A5427a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A5460a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A5475b.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A5512a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A5525a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A5598b.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A5599a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A5604a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A4020a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A3694a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A3054a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A4563a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A4570a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A3706a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A5424b.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A1146a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A4943a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A3207a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A3895a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A4706a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A4321b.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A3920a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A4873b.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A4463a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A3223a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A3612a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A0717a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A4445a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A4526a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A4374a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A3436a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A3869a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A3868a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A4554a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A3849a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A3548a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A0473a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A3509a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A5425a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A4712a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A3986b.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A4715a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A5079a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A1775a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A4321a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A3616a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A3550a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A3201a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A4415a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A4331a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A4456a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A4308a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A4509a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A4237b.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A3858a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A4020b.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A4806a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A0428a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A3685a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A4877b.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A4029a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A3940a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A0354a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A0608a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A4368a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A3975a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A0875a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A4347a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A3194a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A4214a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A4786a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A0556a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A0497a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A0310a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A3897a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A5424a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A3417a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A4333a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A0926a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A5036b.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A4708a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A0525a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A5091a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A3634a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A4524a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A4874b.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A1776a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A0586a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A4943b.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A3485a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A4365a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A4586a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A5079b.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A4305a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A4032b.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A4365b.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A4350a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A3483a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A4874a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A4461a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A3186a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A4298a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A4707a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A4032a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A3546a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A3938a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A4336a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A4306a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A4035a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A4012a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A3480a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A5425b.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A4322a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A4237a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A4701a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A3942a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A3557a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A4031b.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A3229a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A4650a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A0528b.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A0341a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A4877a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A4855a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A4343b.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A3621a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A4746a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A5394a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A5394b.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A4374b.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A4012b.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A0269a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A4291a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A4274a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A4319a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A0541a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A1779a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A3581a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A4304a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A3178a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds/A3858b.pdb...

 DISK  Writing openbind_a71ev2a_c1_scaffolds_refs.zip...

[14:25:21] Molecule does not have explicit Hs. Consider calling AddHs()

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffolds.sdf...

,HIPPO Pose ID,smiles,inchikey,alias,HIPPO Compound ID,ROMol,energy_score,distance_score,inspiration_score,Energy,...,fragmenstein_outcome,fragmenstein_mode,fragmenstein_error,exports,tags,subsites,name,ref_mols,ref_pdb,_Name
0,810,O=S(=O)([C@H]1CCCN(c2ncco2)C1)N1CCc2ccccc21,HFLHXSXUCRDIDV-UHFFFAOYSA-N,None,99664,<rdkit.Chem.rdchem.Mol object at 0x7f510de4fa10>,-61.135087,0.997827,None,-36.665237,...,acceptable,expansion,,[/opt/xchem-fragalysis-2/maxwin/BulkDock/OUTPU...,"BulkDock Fragalysis export,fragmenstein_placed...",1 - Active Site,P810,"A3623a,A5393a",A5393a,P810
1,944,O=C1CCC[C@H](COc2cn[nH]c2)N1,XDBQWQWEVJPNBV-UHFFFAOYSA-N,None,48074,<rdkit.Chem.rdchem.Mol object at 0x7f510de4f7e0>,-33.561941,0.816180,None,15.240541,...,acceptable,expansion,,[/opt/xchem-fragalysis-2/maxwin/BulkDock/OUTPU...,"BulkDock Fragalysis export,fragmenstein_placed...",1 - Active Site,P944,"A3579a,A0556a",A3579a,P944
2,1410,O=C1N[C@@H](c2ccccc2F)CN1[C@H]1CCCNC1,QZMIVAQLNCUJAN-UHFFFAOYSA-N,None,47239,<rdkit.Chem.rdchem.Mol object at 0x7f510de4f650>,-37.001182,0.392140,None,-16.254994,...,acceptable,expansion,,[/opt/xchem-fragalysis-2/maxwin/BulkDock/OUTPU...,"BulkDock Fragalysis export,fragmenstein_placed...","1 - Active Site,17 - A1081/A/201/1",P1410,"A1081b,A3616b,A4873b,A4331a,A4706a",A1081b,P1410
3,1411,O=C1N[C@@H](c2ccccc2F)CN1[C@@H]1CCCNC1,CXUYUFRBAKGUHD-UHFFFAOYSA-N,None,50543,<rdkit.Chem.rdchem.Mol object at 0x7f510de4f740>,-41.067148,0.866832,None,-20.320961,...,acceptable,expansion,,[/opt/xchem-fragalysis-2/maxwin/BulkDock/OUTPU...,"BulkDock Fragalysis export,fragmenstein_placed...","1 - Active Site,17 - A1081/A/201/1",P1411,"A1081b,A3616b",A3616b,P1411
4,2537,Cc1[nH]cnc1S(=O)(=O)NCCn1ncc2ccccc21,GKRPCXYDRCZNEJ-UHFFFAOYSA-N,None,125028,<rdkit.Chem.rdchem.Mol object at 0x7f510de4fa60>,-389.344039,0.884244,None,57.462452,...,acceptable,expansion,,[/opt/xchem-fragalysis-2/maxwin/BulkDock/OUTPU...,"BulkDock Fragalysis export,fragmenstein_placed...",6 - A0486/A/147/1,P2537,"A0486a,A0309a",A0309a,P2537
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1513,494896,c1cc(-c2ncco2)ccn1,GXLZMUSLZZNHNL-UHFFFAOYSA-N,C3665-P182,3665,<rdkit.Chem.rdchem.Mol object at 0x7f510cb74d60>,-7.856933,0.835020,None,19.265044,...,acceptable,expansion,,[/opt/xchem-fragalysis-2/maxwin/BulkDock/OUTPU...,"BulkDock Fragalysis export,fragmenstein_placed...",1 - Active Site,C3665-P182,"A0556a,A3435a",A3435a,C3665-P182
1514,494946,O=C(NCCc1cc[nH]n1)c1ccnc(-n2ccnc2)c1,ZZPZYEPSKIPXIU-UHFFFAOYSA-N,C16361-P182,16361,<rdkit.Chem.rdchem.Mol object at 0x7f510cb74db0>,-16.710466,0.920213,None,55.214786,...,acceptable,expansion,,[/opt/xchem-fragalysis-2/maxwin/BulkDock/OUTPU...,"BulkDock Fragalysis export,fragmenstein_placed...",1 - Active Site,C16361-P182,"A0556a,A3435a",A3435a,C16361-P182
1515,495159,C1CC[C@H](c2nc3c([nH]2)CCCC3)NC1,SKVGOPZVGGOSKI-UHFFFAOYSA-N,C2086-P207,2086,<rdkit.Chem.rdchem.Mol object at 0x7f510cb74e00>,-31.681633,0.839814,None,14.625461,...,acceptable,expansion,,[/opt/xchem-fragalysis-2/maxwin/BulkDock/OUTPU...,"BulkDock Fragalysis export,fragmenstein_placed...",1 - Active Site,C2086-P207,"A3371a,A3706a",A3706a,C2086-P207
1516,495160,C1CC(c2nc3c([nH]2)CCSC3)CCN1,XNTLIZRLNRAQQY-UHFFFAOYSA-N,C2091-P207,2091,<rdkit.Chem.rdchem.Mol object at 0x7f510cb74e50>,-37.262883,0.751653,None,28.338127,...,acceptable,expansion,,[/opt/xchem-fragalysis-2/maxwin/BulkDock/OUTPU...,"BulkDock Fragalysis export,fragmenstein_placed...",1 - Active Site,C2091-P207,"A3371a,A3706a",A3706a,C2091-P207
1517,495323,CC(=O)C[C@H](O)[C@H]1CCCNC1,UZXQDRCHBFTVHG-UHFFFAOYSA-N,C8142-P190,8142,<rdkit.Chem.rdchem.Mol object at 0x7f510cb74ea0>,-21.596587,0.926577,None,24.450700,...,acceptable,expansion,,[/opt/xchem-fragalysis-2/maxwin/BulkDock/OUTPU...,"BulkDock Fragalysis export,fragmenstein_placed...",1 - Active Site,C8142-P190,"A0719a,A3509a",A3509a,C8142-P190

In [12]:
pset = recipe.products.poses(tag="openbind_a71ev2a_c1_scaffolds")
pset

{P × 1214}

In [13]:
pset.to_fragalysis("cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products.sdf",
    method="openbind_a71ev2a_c1_scaffold_products", 
    submitter_name="Max Winokan", 
    submitter_institution="DLS", 
    submitter_email="max.winokan@diamond.ac.uk",
    copy_reference_pdbs=True,
)

DEBUG: 1214 poses in set

DEBUG: 1214 remaining after skipping null reference

DEBUG: 1214 remaining after skipping null inspirations

#poses = 1214

DEBUG: querying...

Output()

DEBUG: adding inspiration column(s)

DEBUG: adding tag column

DEBUG: adding subsite column

out_path =
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products.sdf

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A5393
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A3579
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A3616
b.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A0309
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A3568
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A3623
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A1778
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A3990
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A4418
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A3618
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A3181
b.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A2972
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A2629
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A3371
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A4274
b.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A4445
b.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A3956
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A0486
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A1081
b.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A3564
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A3435
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A4320
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A1105
b.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A0239
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A5151
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A0501
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A0514
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A0228
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A0229
b.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A0237
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A0351
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A0359
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A0365
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A0437
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A0719
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A1140
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A2290
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A2293
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A2513
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A3176
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A3264
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A3306
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A3410
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A3488
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A3593
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A4018
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A4311
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A4416
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A4421
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A4449
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A4541
b.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A4583
b.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A4774
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A4809
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A5427
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A5460
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A4020
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A3694
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A3054
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A3706
b.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A4836
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A1445
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A4563
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A4570
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A3706
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A5424
b.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A1146
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A4943
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A3207
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A3895
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A4706
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A4321
b.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A3920
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A4873
b.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A4456
b.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A4463
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A3587
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A3223
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A3612
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A0717
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A4445
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A4526
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A4374
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A3436
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A3869
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A3868
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A4554
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A4351
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A3849
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A3548
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A0473
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A3509
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A5425
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A4712
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A3986
b.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A2304
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A4214
b.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A4715
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A5079
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A1775
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A4321
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A3616
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A3550
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A3201
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A4415
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A4331
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A4456
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A4308
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A4509
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A4237
b.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A2846
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A3858
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A4020
b.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A4806
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A0428
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A4994
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A3685
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A4877
b.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A0528
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A4029
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A4031
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A3940
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A0354
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A4873
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A0608
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A3986
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A4368
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A3975
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A0875
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A4347
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A4846
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A3194
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A4214
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A4786
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A0556
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A0497
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A4388
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A0310
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A3897
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A5424
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A3417
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A4333
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A0926
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A5036
b.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A4708
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A0525
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A5091
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A3634
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A4524
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A4874
b.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A1776
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A0586
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A4943
b.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A3485
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A4365
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A4586
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A5079
b.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A4305
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A4032
b.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A4365
b.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A4350
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A3509
b.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A3483
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A4874
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A4461
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A3186
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A4298
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A5036
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A4707
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A4742
b.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A4032
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A3938
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A4336
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A3510
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A4306
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A4035
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A4751
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A4012
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A3480
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A5425
b.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A4322
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A4237
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A4701
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A3557
b.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A3942
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A3557
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A4031
b.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A3229
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A4650
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A0528
b.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A3392
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A0341
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A4877
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A4855
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A4343
b.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A3621
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A4746
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A5394
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A5394
b.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A4374
b.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A4012
b.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A0269
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A4291
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A4035
b.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A4274
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A3222
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A4319
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A4794
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A0541
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A1779
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A3581
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A4304
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A3890
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A3178
a.pdb...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products/A3858
b.pdb...

 DISK  Writing openbind_a71ev2a_c1_scaffold_products_refs.zip...

[14:29:52] Molecule does not have explicit Hs. Consider calling AddHs()

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_01/bulkdock/openbind_a71ev2a_c1_scaffold_products.sdf..
.

,HIPPO Pose ID,smiles,inchikey,alias,HIPPO Compound ID,ROMol,energy_score,distance_score,inspiration_score,Energy,...,fragmenstein_outcome,fragmenstein_mode,fragmenstein_error,exports,tags,subsites,name,ref_mols,ref_pdb,_Name
0,810,O=S(=O)([C@H]1CCCN(c2ncco2)C1)N1CCc2ccccc21,HFLHXSXUCRDIDV-UHFFFAOYSA-N,None,99664,<rdkit.Chem.rdchem.Mol object at 0x7f50efb91990>,-61.135087,0.997827,None,-36.665237,...,acceptable,expansion,,[/opt/xchem-fragalysis-2/maxwin/BulkDock/OUTPU...,"BulkDock Fragalysis export,fragmenstein_placed...",1 - Active Site,P810,"A3623a,A5393a",A5393a,P810
1,944,O=C1CCC[C@H](COc2cn[nH]c2)N1,XDBQWQWEVJPNBV-UHFFFAOYSA-N,None,48074,<rdkit.Chem.rdchem.Mol object at 0x7f50efb91c60>,-33.561941,0.816180,None,15.240541,...,acceptable,expansion,,[/opt/xchem-fragalysis-2/maxwin/BulkDock/OUTPU...,"BulkDock Fragalysis export,fragmenstein_placed...",1 - Active Site,P944,"A3579a,A0556a",A3579a,P944
2,1411,O=C1N[C@@H](c2ccccc2F)CN1[C@@H]1CCCNC1,CXUYUFRBAKGUHD-UHFFFAOYSA-N,None,50543,<rdkit.Chem.rdchem.Mol object at 0x7f50efb91cb0>,-41.067148,0.866832,None,-20.320961,...,acceptable,expansion,,[/opt/xchem-fragalysis-2/maxwin/BulkDock/OUTPU...,"BulkDock Fragalysis export,fragmenstein_placed...","1 - Active Site,17 - A1081/A/201/1",P1411,"A1081b,A3616b",A3616b,P1411
3,2537,Cc1[nH]cnc1S(=O)(=O)NCCn1ncc2ccccc21,GKRPCXYDRCZNEJ-UHFFFAOYSA-N,None,125028,<rdkit.Chem.rdchem.Mol object at 0x7f50efb91d50>,-389.344039,0.884244,None,57.462452,...,acceptable,expansion,,[/opt/xchem-fragalysis-2/maxwin/BulkDock/OUTPU...,"BulkDock Fragalysis export,fragmenstein_placed...",6 - A0486/A/147/1,P2537,"A0486a,A0309a",A0309a,P2537
4,2540,C[C@H](NCCn1ncc2ccccc21)c1c[nH]cn1,NHKSKEKGNRBSQB-UHFFFAOYSA-N,None,51269,<rdkit.Chem.rdchem.Mol object at 0x7f50efb91d00>,-21.333070,0.839041,None,61.458548,...,acceptable,expansion,,[/opt/xchem-fragalysis-2/maxwin/BulkDock/OUTPU...,"BulkDock Fragalysis export,fragmenstein_placed...",6 - A0486/A/147/1,P2540,"A0486a,A0309a",A0309a,P2540
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1209,494742,CCC(=O)C1=NCCC1,OVNCGQSYSSYBPO-UHFFFAOYSA-N,C4732-P405,4732,<rdkit.Chem.rdchem.Mol object at 0x7f50efc50db0>,-26.358895,0.948248,None,30.147335,...,acceptable,expansion,,[/opt/xchem-fragalysis-2/maxwin/BulkDock/OUTPU...,"BulkDock Fragalysis export,fragmenstein_placed...",1 - Active Site,C4732-P405,"A4570a,A0875a",A4570a,C4732-P405
1210,494896,c1cc(-c2ncco2)ccn1,GXLZMUSLZZNHNL-UHFFFAOYSA-N,C3665-P182,3665,<rdkit.Chem.rdchem.Mol object at 0x7f50efc50e00>,-7.856933,0.835020,None,19.265044,...,acceptable,expansion,,[/opt/xchem-fragalysis-2/maxwin/BulkDock/OUTPU...,"BulkDock Fragalysis export,fragmenstein_placed...",1 - Active Site,C3665-P182,"A0556a,A3435a",A3435a,C3665-P182
1211,494946,O=C(NCCc1cc[nH]n1)c1ccnc(-n2ccnc2)c1,ZZPZYEPSKIPXIU-UHFFFAOYSA-N,C16361-P182,16361,<rdkit.Chem.rdchem.Mol object at 0x7f50efc50e50>,-16.710466,0.920213,None,55.214786,...,acceptable,expansion,,[/opt/xchem-fragalysis-2/maxwin/BulkDock/OUTPU...,"BulkDock Fragalysis export,fragmenstein_placed...",1 - Active Site,C16361-P182,"A0556a,A3435a",A3435a,C16361-P182
1212,495159,C1CC[C@H](c2nc3c([nH]2)CCCC3)NC1,SKVGOPZVGGOSKI-UHFFFAOYSA-N,C2086-P207,2086,<rdkit.Chem.rdchem.Mol object at 0x7f50efc50ea0>,-31.681633,0.839814,None,14.625461,...,acceptable,expansion,,[/opt/xchem-fragalysis-2/maxwin/BulkDock/OUTPU...,"BulkDock Fragalysis export,fragmenstein_placed...",1 - Active Site,C2086-P207,"A3371a,A3706a",A3706a,C2086-P207
1213,495323,CC(=O)C[C@H](O)[C@H]1CCCNC1,UZXQDRCHBFTVHG-UHFFFAOYSA-N,C8142-P190,8142,<rdkit.Chem.rdchem.Mol object at 0x7f50efc50ef0>,-21.596587,0.926577,None,24.450700,...,acceptable,expansion,,[/opt/xchem-fragalysis-2/maxwin/BulkDock/OUTPU...,"BulkDock Fragalysis export,fragmenstein_placed...",1 - Active Site,C8142-P190,"A0719a,A3509a",A3509a,C8142-P190

In [35]:
cset = animal.compounds(tag="openbind_a71ev2a_c1_scaffolds")
cset = cset - animal.compounds(tag="hits")
cset.write_smiles_csv("openbind_a71ev2a_c1_scaffold_smiles.csv")

 DISK  Writing openbind_a71ev2a_c1_scaffold_smiles.csv...

# Export for co-folding

In [6]:
pset = animal.poses(tag="openbind_a71ev2a_c1_scaffolds")
pset

poses tagged "openbind_a71ev2a_c1_scaffolds": {P × 1518}

In [32]:
sql = f"""
SELECT pose_id, pose_smiles, pose_reference FROM pose
WHERE pose_id IN {pset.str_ids}
"""

cursor = animal.db.execute(sql)

data = []
for pose_id, pose_smiles, pose_reference in cursor:
    data.append(dict(id=pose_id, smiles=pose_smiles, reference_id=pose_reference))
df = pd.DataFrame(data)

df = df.set_index("id")

df.head()

                                           smiles  reference_id
id
810   O=S(=O)([C@H]1CCCN(c2ncco2)C1)N1CCc2ccccc21           611
944                  O=C1CCC[C@H](COc2cn[nH]c2)N1           170
1410        O=C1N[C@@H](c2ccccc2F)CN1[C@H]1CCCNC1           100
1411       O=C1N[C@@H](c2ccccc2F)CN1[C@@H]1CCCNC1           197
2537         Cc1[nH]cnc1S(=O)(=O)NCCn1ncc2ccccc21            36

In [43]:
pattern = re.compile(r"^.*-x[0-9]{4}_([A-Z])_[0-9]*_v[0-9]*$")

def get_sequence(pose_id):
    p = animal.poses[pose_id]
    sys = p.protein_system
    if not sys:
        mrich.error("No protein system")
        return None

    match = pattern.match(p.metadata["observation_longname"])
    ligand_chain = match.group(1)

    try:
        chain = sys.get_chain(ligand_chain)
        return chain.sequence
    except:
        seqs = set()
        for chain in sys.chains:
            seq = chain.sequence
            seqs.add(seq)
        
        if len(seqs) > 1:
            mrich.warning("Multiple sequences!", p)
        
        return list(seqs)[0]

In [45]:
lookup = {}
for reference_id in mrich.track(set(df["reference_id"].values)):
    i = int(reference_id)
    lookup[i] = get_sequence(i)

Output()

Fatal Error: Chain with name E not found.

Fatal Error: Chain with name E not found.

Fatal Error: Chain with name F not found.

Fatal Error: Chain with name F not found.

Fatal Error: Chain with name E not found.

Fatal Error: Chain with name E not found.

Fatal Error: Chain with name D not found.

Fatal Error: Chain with name D not found.

Fatal Error: Chain with name E not found.

Fatal Error: Chain with name E not found.

Fatal Error: Chain with name D not found.

Fatal Error: Chain with name E not found.

Fatal Error: Chain with name D not found.

Fatal Error: Chain with name D not found.

In [46]:
df["sequence"] = df["reference_id"].apply(lambda x: lookup[x])

In [48]:
df = df.drop(columns=["reference_id"])
df.to_csv("openbind_a71ev2a_c1_scaffold_smiles_sequences.csv")