# OpenBind-HIPPO

- **Target: A71EV2A**
- **Cycle: 02**

## Imports

In [39]:
%load_ext autoreload
%autoreload 2
import hippo
import mrich
from mrich import print
from pathlib import Path
from os import environ
import shutil
import molparse as mp

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

# Config

In [40]:
target_name = "A71EV2A"
target_dir = Path(environ["BULK"]) / "TARGETS" / target_name
cycle_name = "cycle_02"
cycle_dir = Path(cycle_name)
aligned_dir = target_dir / "aligned_files"

## Animal

In [41]:
animal = hippo.HIPPO(target_name, target_dir / f"{target_name}.sqlite")
# animal = hippo.HIPPO(target_name, target_dir / f"{target_name}_testing.sqlite")#, copy_from=target_dir / f"{target_name}.sqlite")

 Creating HIPPO animal

name = A71EV2A

db_path = /opt/xchem-fragalysis-2/maxwin/BulkDock/TARGETS/A71EV2A/A71EV2A.sqlite

DEBUG: hippo.Database.__init__()

DEBUG: Database.path = /opt/xchem-fragalysis-2/maxwin/BulkDock/TARGETS/A71EV2A/A71EV2A.sqlite

DEBUG: hippo.Database.connect()

DEBUG: sqlite3.version='2.6.0'

 Success  Database connected @ /opt/xchem-fragalysis-2/maxwin/BulkDock/TARGETS/A71EV2A/A71EV2A.sqlite!

 Success  Initialised animal HIPPO("A71EV2A")!

## Syndirella inputs

Run syndirella on all ASAP structural hits, with self-referential inspiration

In [ ]:
hits = animal.poses(tag="hits")
hits

In [ ]:
hits.to_syndirella("cycle_02/syndirella/elabs/c2_elabs", separate=True)

## Load Syndirella Elabs

Check using below cells and then queue `c02b_load_elabs.py`

In [5]:
output_root = cycle_dir / "syndirella/elabs/"
files = list(output_root.glob("*/*-*-?/*to_hippo*"))
len(files)

334

In [6]:
print(files[0])

cycle_02/syndirella/elabs/c2_elabs_A4489b/UWGHAGSZEJRSBU-UHFFFAOYSA-N/UWGHAGSZEJRSBU-UHFFFAOYSA-N_25f427d90acd2eee5
458aadf6155c2db_to_hippo.pkl.gz

In [40]:
%%time
scaffold = animal.poses["A4489b"].compound
df = animal.add_syndirella_elabs(files[0], scaffold_compound=scaffold, dry_run=False)
df

╭──────────────────────────────────────────────────────────────────────────────╮
│ UWGHAGSZEJRSBU-UHFFFAOYSA-N_25f427d90acd2eee5458aadf6155c2db_to_hippo.pkl.gz │
╰──────────────────────────────────────────────────────────────────────────────╯

 DISK  Reading
cycle_02/syndirella/elabs/c2_elabs_A4489b/UWGHAGSZEJRSBU-UHFFFAOYSA-N/UWGHAGSZEJRSBU-UHFFFAOYSA-N_25f427d90acd2eee5
458aadf6155c2db_to_hippo.pkl.gz...

num_steps = 1

 Warning  Flags in DataFrame: {'one_of_multiple_products'}!

Filtering out 52 rows from step 1 due to one_of_multiple_products

#rows skipped due to null path_to_mol = 76

template_path =
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_02/syndirella/elabs/templates/A4489b_apo-desolv.pdb

reference = C199->P380: "A4489b"

#scaffold entries = 0

#elab entries = 476

DEBUG: Registering 2 compounds from column: 1_r1_smiles

 Warning  Inserted 0 new compounds!

DEBUG: Registering 86 compounds from column: 1_r2_smiles

 Warning  Inserted 0 new compounds!

DEBUG: Registering 476 compounds from column: 1_product_smiles

 Warning  Inserted 0 new compounds!

DEBUG: Registering reactions for step 1

 Warning  Can't insert reactions for missing scaffold!

 Warning  Skipped 476 existing reactions!

 Warning  All reactions are duplicates!

DEBUG: Registering scaffold relatonships for 1_r1_compound_id

 Warning  Can't insert scaffold relationships due to missing 1_r1_compound_id for all scaffold rows!

DEBUG: Registering scaffold relatonships for 1_r2_compound_id

 Warning  Can't insert scaffold relationships due to missing 1_r2_compound_id for all scaffold rows!

DEBUG: Registering scaffold relatonships for 1_product_compound_id

 Warning  Can't insert scaffold relationships due to missing 1_product_compound_id for all scaffold rows!

#poses !intra_geometry_pass = 225

#poses ∆∆G > 0.0 = 464

#poses comRMSD > 2.0 = 476

#acceptable poses = 0

 Warning  No valid poses!

CPU times: user 4.19 s, sys: 8.44 s, total: 12.6 s
Wall time: 1min 38s

## Check Elabs

In [8]:
animal.tags.summary()

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━┓
┃ tag                                         ┃ num_compounds ┃ num_poses ┃ num_posed_compounds ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━┩
│ BAD count                                   │ 0             │ 645       │ 457                 │
│ BulkDock Fragalysis export                  │ 0             │ 1749      │ 1145                │
│ C10 85percent analogue                      │ 31            │ 0         │ 0                   │
│ C10 90percent analogue                      │ 6             │ 0         │ 0                   │
│ C100 85percent analogue                     │ 32            │ 0         │ 0                   │
│ C101 85percent analogue                     │ 2             │ 0         │ 0                   │
│ C102 85percent analogue                     │ 5             │ 0         │ 0                   │
│ C103 85percent analogue                     │ 3             │ 0         │ 0                   │
│ C104 85percent analogue                     │ 19            │ 0         │ 0                   │
│ C105 85percent analogue                     │ 32            │ 0         │ 0                   │
│ C106 85percent analogue                     │ 24            │ 0         │ 0                   │
│ C107 85percent analogue                     │ 2             │ 0         │ 0                   │
│ C108 85percent analogue                     │ 3             │ 0         │ 0                   │
│ C109 85percent analogue                     │ 108           │ 0         │ 0                   │
│ C11 85percent analogue                      │ 11            │ 0         │ 0                   │
│ C11 90percent analogue                      │ 4             │ 0         │ 0                   │
│ C111 85percent analogue                     │ 15            │ 0         │ 0                   │
│ C112 85percent analogue                     │ 7             │ 0         │ 0                   │
│ C113 85percent analogue                     │ 4             │ 0         │ 0                   │
│ C114 85percent analogue                     │ 7             │ 0         │ 0                   │
│ C115 85percent analogue                     │ 129           │ 0         │ 0                   │
│ C116 85percent analogue                     │ 3             │ 0         │ 0                   │
│ C117 85percent analogue                     │ 5             │ 0         │ 0                   │
│ C119 85percent analogue                     │ 6             │ 0         │ 0                   │
│ C12 85percent analogue                      │ 38            │ 0         │ 0                   │
│ C12 90percent analogue                      │ 16            │ 0         │ 0                   │
│ C120 85percent analogue                     │ 2             │ 0         │ 0                   │
│ C121 85percent analogue                     │ 17            │ 0         │ 0                   │
│ C122 85percent analogue                     │ 7             │ 0         │ 0                   │
│ C123 85percent analogue                     │ 12            │ 0         │ 0                   │
│ C127 85percent analogue                     │ 3             │ 0         │ 0                   │
│ C128 85percent analogue                     │ 11            │ 0         │ 0                   │
│ C129 85percent analogue                     │ 26            │ 0         │ 0                   │
│ C13 85percent analogue                      │ 14            │ 0         │ 0                   │
│ C13 90percent analogue                      │ 2             │ 0         │ 0                   │
│ C132 85percent analogue                     │ 10            │ 0         │ 0                   │
│ C136 85percent analogue                     │ 2             │ 0         │ 0                   │
│ C137 85percent analogue                     │ 1             │ 0         │ 0                   │
│ C138 85percent analogue                     │ 100           │ 0         │ 0                   │
│ C139 85percent analogue                     │ 28            │ 0         │ 0                   │
│ C14 85percent analogue                      │ 64            │ 0         │ 0                   │
│ C14 90percent analogue                      │ 14            │ 0         │ 0                   │
│ C140 85percent analogue                     │ 1             │ 0         │ 0                   │
│ C141 85percent analogue                     │ 16            │ 0         │ 0                   │
│ C142 85percent analogue                     │ 1             │ 0         │ 0                   │
│ C143 85percent analogue                     │ 1             │ 0         │ 0                   │
│ C146 85percent analogue                     │ 24            │ 0         │ 0                   │
│ C147 85percent analogue                     │ 1             │ 0         │ 0                   │
│ C148 85percent analogue                     │ 16            │ 0         │ 0                   │
│ C149 85percent analogue                     │ 8             │ 0         │ 0                   │
│ C15 85percent analogue                      │ 56            │ 0         │ 0                   │
│ C15 90percent analogue                      │ 13            │ 0         │ 0                   │
│ C152 85percent analogue                     │ 4             │ 0         │ 0                   │
│ C153 85percent analogue                     │ 49            │ 0         │ 0                   │
│ C154 85percent analogue                     │ 76            │ 0         │ 0                   │
│ C155 85percent analogue                     │ 33            │ 0         │ 0                   │
│ C156 85percent analogue                     │ 42            │ 0         │ 0                   │
│ C158 85percent analogue                     │ 52            │ 0         │ 0                   │
│ C159 85percent analogue                     │ 106           │ 0         │ 0                   │
│ C16 85percent analogue                      │ 30            │ 0         │ 0                   │
│ C16 90percent analogue                      │ 1             │ 0         │ 0                   │
│ C160 85percent analogue                     │ 4             │ 0         │ 0                   │
│ C161 85percent analogue                     │ 49            │ 0         │ 0                   │
│ C162 85percent analogue                     │ 93            │ 0         │ 0                   │
│ C163 85percent analogue                     │ 75            │ 0         │ 0                   │
│ C164 85percent analogue                     │ 27            │ 0         │ 0                   │
│ C166 85percent analogue                     │ 33            │ 0         │ 0                   │
│ C167 85percent analogue                     │ 51            │ 0         │ 0                   │
│ C168 85percent analogue                     │ 3             │ 0         │ 0                   │
│ C169 85percent analogue                     │ 9             │ 0         │ 0                   │
│ C17 85percent analogue                      │ 2             │ 0         │ 0                   │
│ C170 85percent analogue                     │ 19            │ 0         │ 0                   │
│ C171 85percent analogue                     │ 80            │ 0         │ 0                   │
│ C172 85percent analogue                     │ 6             │ 0         │ 0                   │
│ C173 85percent analogue                     │ 6             │ 0         │ 0                   │
│ C174 85percent analogue                     │ 32            │ 0         │ 0                   │
│ C175 85percent analogue                     │ 60            │ 0         │ 0                   │
│ C177 85percent analogue                     │ 76            │ 0         │ 0                   │
│ C178 85percent analogue                     │ 160           │ 0         │ 0                   │
│ C179 85percent analogue                     │ 1             │ 0         │ 0                   │
│ C18 85percent analogue                      │ 24            │ 0         │ 0                   │
│ C18 90percent analogue                      │ 2             │ 0         │ 0                   │
│ C180 85percent analogue                     │ 34            │ 0         │ 0                   │
│ C181 85percent analogue                     │ 54            │ 0         │ 0                   │
│ C182 85percent analogue                     │ 26            │ 0         │ 0                   │
│ C183 85percent analogue                     │ 186           │ 0         │ 0                   │
│ C184 85percent analogue                     │ 34            │ 0         │ 0                   │
│ C185 85percent analogue                     │ 29            │ 0         │ 0                   │
│ C186 85percent analogue                     │ 17            │ 0         │ 0                   │
│ C187 85percent analogue                     │ 42            │ 0         │ 0                   │
│ C188 85percent analogue                     │ 47            │ 0         │ 0                   │
│ C189 85percent analogue                     │ 54            │ 0         │ 0                   │
│ C19 85percent analogue                      │ 1             │ 0         │ 0                   │
│ C190 85percent analogue                     │ 11            │ 0         │ 0                   │
│ C191 85percent analogue                     │ 8             │ 0         │ 0                   │
│ C192 85percent analogue                     │ 7             │ 0         │ 0                   │
│ C193 85percent analogue                     │ 14            │ 0         │ 0                   │
│ C194 85percent analogue                     │ 31            │ 0         │ 0                   │
│ C195 85percent analogue                     │ 45            │ 0         │ 0                   │
│ C196 85percent analogue                     │ 16            │ 0         │ 0                   │
│ C198 85percent analogue                     │ 36            │ 0         │ 0                   │
│ C199 85percent analogue                     │ 15            │ 0         │ 0                   │
│ C2 85percent analogue                       │ 2             │ 0         │ 0                   │
│ C20 85percent analogue                      │ 118           │ 0         │ 0                   │
│ C20 90percent analogue                      │ 7             │ 0         │ 0                   │
│ C200 85percent analogue                     │ 11            │ 0         │ 0                   │
│ C201 85percent analogue                     │ 38            │ 0         │ 0                   │
│ C202 85percent analogue                     │ 141           │ 0         │ 0                   │
│ C203 85percent analogue                     │ 87            │ 0         │ 0                   │
│ C204 85percent analogue                     │ 3             │ 0         │ 0                   │
│ C205 85percent analogue                     │ 7             │ 0         │ 0                   │
│ C206 85percent analogue                     │ 8             │ 0         │ 0                   │
│ C207 85percent analogue                     │ 4             │ 0         │ 0                   │
│ C209 85percent analogue                     │ 42            │ 0         │ 0                   │
│ C21 85percent analogue                      │ 3             │ 0         │ 0                   │
│ C210 85percent analogue                     │ 4             │ 0         │ 0                   │
│ C211 85percent analogue                     │ 26            │ 0         │ 0                   │
│ C212 85percent analogue                     │ 228           │ 0         │ 0                   │
│ C213 85percent analogue                     │ 26            │ 0         │ 0                   │
│ C214 85percent analogue                     │ 2             │ 0         │ 0                   │
│ C215 85percent analogue                     │ 9             │ 0         │ 0                   │
│ C218 85percent analogue                     │ 26            │ 0         │ 0                   │
│ C219 85percent analogue                     │ 14            │ 0         │ 0                   │
│ C22 85percent analogue                      │ 14            │ 0         │ 0                   │
│ C22 90percent analogue                      │ 1             │ 0         │ 0                   │
│ C221 85percent analogue                     │ 3             │ 0         │ 0                   │
│ C222 85percent analogue                     │ 30            │ 0         │ 0                   │
│ C223 85percent analogue                     │ 8             │ 0         │ 0                   │
│ C226 85percent analogue                     │ 1             │ 0         │ 0                   │
│ C227 85percent analogue                     │ 20            │ 0         │ 0                   │
│ C228 85percent analogue                     │ 1             │ 0         │ 0                   │
│ C229 85percent analogue                     │ 35            │ 0         │ 0                   │
│ C23 85percent analogue                      │ 15            │ 0         │ 0                   │
│ C23 90percent analogue                      │ 6             │ 0         │ 0                   │
│ C230 85percent analogue                     │ 10            │ 0         │ 0                   │
│ C231 85percent analogue                     │ 11            │ 0         │ 0                   │
│ C232 85percent analogue                     │ 1             │ 0         │ 0                   │
│ C233 85percent analogue                     │ 28            │ 0         │ 0                   │
│ C234 85percent analogue                     │ 7             │ 0         │ 0                   │
│ C235 85percent analogue                     │ 122           │ 0         │ 0                   │
│ C236 85percent analogue                     │ 110           │ 0         │ 0                   │
│ C237 85percent analogue                     │ 11            │ 0         │ 0                   │
│ C238 85percent analogue                     │ 184           │ 0         │ 0                   │
│ C239 85percent analogue                     │ 5             │ 0         │ 0                   │
│ C24 85percent analogue                      │ 67            │ 0         │ 0                   │
│ C24 90percent analogue                      │ 12            │ 0         │ 0                   │
│ C240 85percent analogue                     │ 56            │ 0         │ 0                   │
│ C241 85percent analogue                     │ 34            │ 0         │ 0                   │
│ C242 85percent analogue                     │ 9             │ 0         │ 0                   │
│ C243 85percent analogue                     │ 5             │ 0         │ 0                   │
│ C245 85percent analogue                     │ 20            │ 0         │ 0                   │
│ C246 85percent analogue                     │ 4             │ 0         │ 0                   │
│ C247 85percent analogue                     │ 41            │ 0         │ 0                   │
│ C248 85percent analogue                     │ 13            │ 0         │ 0                   │
│ C249 85percent analogue                     │ 24            │ 0         │ 0                   │
│ C25 85percent analogue                      │ 19            │ 0         │ 0                   │
│ C25 90percent analogue                      │ 4             │ 0         │ 0                   │
│ C250 85percent analogue                     │ 149           │ 0         │ 0                   │
│ C251 85percent analogue                     │ 3             │ 0         │ 0                   │
│ C252 85percent analogue                     │ 12            │ 0         │ 0                   │
│ C253 85percent analogue                     │ 175           │ 0         │ 0                   │
│ C254 85percent analogue                     │ 20            │ 0         │ 0                   │
│ C255 85percent analogue                     │ 20            │ 0         │ 0                   │
│ C256 85percent analogue                     │ 38            │ 0         │ 0                   │
│ C257 85percent analogue                     │ 34            │ 0         │ 0                   │
│ C258 85percent analogue                     │ 178           │ 0         │ 0                   │
│ C259 85percent analogue                     │ 33            │ 0         │ 0                   │
│ C26 85percent analogue                      │ 13            │ 0         │ 0                   │
│ C26 90percent analogue                      │ 3             │ 0         │ 0                   │
│ C261 85percent analogue                     │ 1             │ 0         │ 0                   │
│ C262 85percent analogue                     │ 9             │ 0         │ 0                   │
│ C263 85percent analogue                     │ 6             │ 0         │ 0                   │
│ C264 85percent analogue                     │ 3             │ 0         │ 0                   │
│ C265 85percent analogue                     │ 23            │ 0         │ 0                   │
│ C267 85percent analogue                     │ 101           │ 0         │ 0                   │
│ C268 85percent analogue                     │ 83            │ 0         │ 0                   │
│ C269 85percent analogue                     │ 1             │ 0         │ 0                   │
│ C27 85percent analogue                      │ 161           │ 0         │ 0                   │
│ C27 90percent analogue                      │ 24            │ 0         │ 0                   │
│ C270 85percent analogue                     │ 38            │ 0         │ 0                   │
│ C271 85percent analogue                     │ 9             │ 0         │ 0                   │
│ C272 85percent analogue                     │ 48            │ 0         │ 0                   │
│ C273 85percent analogue                     │ 12            │ 0         │ 0                   │
│ C276 85percent analogue                     │ 8             │ 0         │ 0                   │
│ C277 85percent analogue                     │ 22            │ 0         │ 0                   │
│ C278 85percent analogue                     │ 1             │ 0         │ 0                   │
│ C279 85percent analogue                     │ 7             │ 0         │ 0                   │
│ C28 85percent analogue                      │ 71            │ 0         │ 0                   │
│ C28 90percent analogue                      │ 11            │ 0         │ 0                   │
│ C280 85percent analogue                     │ 2             │ 0         │ 0                   │
│ C281 85percent analogue                     │ 59            │ 0         │ 0                   │
│ C283 85percent analogue                     │ 6             │ 0         │ 0                   │
│ C284 85percent analogue                     │ 11            │ 0         │ 0                   │
│ C285 85percent analogue                     │ 14            │ 0         │ 0                   │
│ C286 85percent analogue                     │ 1             │ 0         │ 0                   │
│ C287 85percent analogue                     │ 5             │ 0         │ 0                   │
│ C29 85percent analogue                      │ 90            │ 0         │ 0                   │
│ C29 90percent analogue                      │ 17            │ 0         │ 0                   │
│ C290 85percent analogue                     │ 3             │ 0         │ 0                   │
│ C291 85percent analogue                     │ 19            │ 0         │ 0                   │
│ C292 85percent analogue                     │ 2             │ 0         │ 0                   │

In [5]:
hit_elabs = animal.compounds(tag="openbind_a71ev2a_c2_elabs")
hit_elabs

compounds tagged openbind_a71ev2a_c2_elabs: {C × 90420}

In [6]:
hit_elab_poses = animal.poses(tag="openbind_a71ev2a_c2_elabs")
hit_elab_poses

poses tagged "openbind_a71ev2a_c2_elabs": {P × 56412}

In [7]:
elaborated_hits = hit_elabs.scaffolds
elaborated_hits

{C × 167}

In [11]:
posed_elabs = hit_elabs.poses.compounds
posed_elabs

{C × 29807}

In [15]:
hit_elabs.write_smiles_csv("cycle_02/syndirella/elabs/openbind_a71ev2a_c2_elabs.csv")

 DISK  Writing cycle_02/syndirella/elabs/openbind_a71ev2a_c2_elabs.csv...

# sb.sh --job-name 'a71ev2a_c02_elabs_export' /opt/xchem-fragalysis-2/maxwin/slurm/run_python.sh -m bulkdock export A71EV2A openbind_a71ev2a_c2_elabs --no-posebusters --best-by-compound --no-subsites --require-outcome False

sb.sh --job-name 'a71ev2a_interactions' /opt/xchem-fragalysis-2/maxwin/slurm/run_python.sh -m hippo calculate-interactions $BULK/TARGETS/A71EV2A/A71EV2A.sqlite

In [ ]:
hit_elab_poses.to_fragalysis("cycle_01/syndirella/elabs/openbind_a71ev2a_c2_elabs.sdf",
    method="openbind_a71ev2a_c2_elabs", 
    submitter_name="Max Winokan", 
    submitter_institution="DLS", 
    submitter_email="max.winokan@diamond.ac.uk",
    copy_reference_pdbs=True,
    metadata=False,
    tags=False,
    subsites=False,
)

## Routes to scaffolds

1. Export list of elaborated hits
2. Run syndirella just retro
3. Load routes back into HIPPO

In [22]:
elaborated_hit_poses = elaborated_hits.poses(tag="hits")
elaborated_hit_poses

{P × 247}

In [23]:
elaborated_hit_poses.to_syndirella("cycle_02/syndirella/retrosynthesis/openbind_a71ev2a_c2_elaborated_hits")

out_key = openbind_a71ev2a_c2_elaborated_hits

#poses = 247

DEBUG: querying...

Output()

DEBUG: adding inspiration column(s)

 Warning  247 poses have no reference. Setting to self!

['A5151a' 'A0451a' 'A0514a' 'A0514b' 'A0517a' 'A0525a' 'A0528a' 'A0528b'
 'A0540a' 'A0554b' 'A0554a' 'A0556a' 'A0566a' 'A0586a' 'A0269a' 'A0608a'
 'A0152a' 'A0152b' 'A0194a' 'A0237a' 'A0239a' 'A0354a' 'A0375a' 'A0375b'
 'A0375c' 'A0836a' 'A0836b' 'A0853a' 'A0863a' 'A0884a' 'A0911a' 'A1292a'
 'A1346a' 'A1775a' 'A2293a' 'A2304a' 'A2339a' 'A2454a' 'A2846a' 'A2972a'
 'A3066a' 'A3175a' 'A3176a' 'A3181a' 'A3181b' 'A3188a' 'A3189a' 'A3191a'
 'A3201a' 'A3207a' 'A3208a' 'A3210a' 'A3229a' 'A3280a' 'A3306a' 'A3581a'
 'A3371a' 'A3379a' 'A3403a' 'A3410a' 'A3419a' 'A3435a' 'A3436a' 'A3593a'
 'A3606a' 'A3521a' 'A3521b' 'A3548a' 'A3556a' 'A3571a' 'A3571b' 'A3575a'
 'A3849a' 'A3858a' 'A3858b' 'A3869a' 'A3883a' 'A3897a' 'A3901a' 'A3914a'
 'A3920a' 'A3936a' 'A3940a' 'A3942a' 'A3944a' 'A3954a' 'A3963a' 'A3963b'
 'A3968a' 'A3975a' 'A3986a' 'A3986b' 'A3989a' 'A3990a' 'A4028a' 'A4202a'
 'A4202b' 'A4290a' 'A4291a' 'A4317a' 'A4319a' 'A4321a' 'A4321b' 'A4331a'
 'A4331b' 'A4333a' 'A4334a' 'A4334b' 'A4341a' 'A4343a' 'A4343b' 'A4344a'
 'A4347a' 'A4350a' 'A4365a' 'A4365b' 'A4368a' 'A4372a' 'A4373a' 'A4380a'
 'A4381a' 'A4203a' 'A4207a' 'A4207b' 'A4209a' 'A4237a' 'A4237b' 'A4254a'
 'A4260a' 'A4283a' 'A4283b' 'A4386a' 'A4402a' 'A4423a' 'A4431a' 'A4445a'
 'A4445b' 'A4449a' 'A4449b' 'A4451a' 'A4451b' 'A4456a' 'A4456b' 'A4461a'
 'A4463a' 'A4467a' 'A4472a' 'A4476a' 'A4489a' 'A4489b' 'A4494a' 'A4510a'
 'A4514a' 'A4526a' 'A4528a' 'A4538a' 'A4544a' 'A4554a' 'A4559a' 'A4559b'
 'A4571a' 'A4575a' 'A4586a' 'A4606a' 'A4606b' 'A4608a' 'A4644a' 'A4644b'
 'A4650a' 'A4654a' 'A4669a' 'A4669b' 'A4670a' 'A4673a' 'A4673b' 'A4707a'
 'A4715a' 'A4735a' 'A4739a' 'A4742a' 'A4742b' 'A4752a' 'A4771a' 'A4777a'
 'A4778a' 'A4806a' 'A4806b' 'A4827a' 'A4827b' 'A4838a' 'A4845a' 'A4856a'
 'A4872a' 'A4877a' 'A4877b' 'A4882a' 'A4882b' 'A4883a' 'A4883b' 'A4885a'
 'A4885b' 'A4895a' 'A4895b' 'A4963a' 'A4963b' 'A4977a' 'A4977b' 'A4935a'
 'A4943a' 'A4943b' 'A4947a' 'A4959a' 'A4959b' 'A4992a' 'A5015a' 'A5015b'
 'A5039a' 'A5039b' 'A5079a' 'A5079b' 'A5081a' 'A5081b' 'A5104a' 'A5131a'
 'A5171a' 'A5171b' 'A5177a' 'A5200a' 'A5203a' 'A5203b' 'A5213a' 'A5213b'
 'A5247a' 'A5247b' 'A5255a' 'A5262a' 'A5262b' 'A5268a' 'A5289a' 'A5289b'
 'A5339a' 'A5339b' 'A5366a' 'A5366b' 'A5388a' 'A5598a' 'A5598b']

 Warning  247 poses have no inspirations. Setting to self!

['A5151a' 'A0451a' 'A0514a' 'A0514b' 'A0517a' 'A0525a' 'A0528a' 'A0528b'
 'A0540a' 'A0554b' 'A0554a' 'A0556a' 'A0566a' 'A0586a' 'A0269a' 'A0608a'
 'A0152a' 'A0152b' 'A0194a' 'A0237a' 'A0239a' 'A0354a' 'A0375a' 'A0375b'
 'A0375c' 'A0836a' 'A0836b' 'A0853a' 'A0863a' 'A0884a' 'A0911a' 'A1292a'
 'A1346a' 'A1775a' 'A2293a' 'A2304a' 'A2339a' 'A2454a' 'A2846a' 'A2972a'
 'A3066a' 'A3175a' 'A3176a' 'A3181a' 'A3181b' 'A3188a' 'A3189a' 'A3191a'
 'A3201a' 'A3207a' 'A3208a' 'A3210a' 'A3229a' 'A3280a' 'A3306a' 'A3581a'
 'A3371a' 'A3379a' 'A3403a' 'A3410a' 'A3419a' 'A3435a' 'A3436a' 'A3593a'
 'A3606a' 'A3521a' 'A3521b' 'A3548a' 'A3556a' 'A3571a' 'A3571b' 'A3575a'
 'A3849a' 'A3858a' 'A3858b' 'A3869a' 'A3883a' 'A3897a' 'A3901a' 'A3914a'
 'A3920a' 'A3936a' 'A3940a' 'A3942a' 'A3944a' 'A3954a' 'A3963a' 'A3963b'
 'A3968a' 'A3975a' 'A3986a' 'A3986b' 'A3989a' 'A3990a' 'A4028a' 'A4202a'
 'A4202b' 'A4290a' 'A4291a' 'A4317a' 'A4319a' 'A4321a' 'A4321b' 'A4331a'
 'A4331b' 'A4333a' 'A4334a' 'A4334b' 'A4341a' 'A4343a' 'A4343b' 'A4344a'
 'A4347a' 'A4350a' 'A4365a' 'A4365b' 'A4368a' 'A4372a' 'A4373a' 'A4380a'
 'A4381a' 'A4203a' 'A4207a' 'A4207b' 'A4209a' 'A4237a' 'A4237b' 'A4254a'
 'A4260a' 'A4283a' 'A4283b' 'A4386a' 'A4402a' 'A4423a' 'A4431a' 'A4445a'
 'A4445b' 'A4449a' 'A4449b' 'A4451a' 'A4451b' 'A4456a' 'A4456b' 'A4461a'
 'A4463a' 'A4467a' 'A4472a' 'A4476a' 'A4489a' 'A4489b' 'A4494a' 'A4510a'
 'A4514a' 'A4526a' 'A4528a' 'A4538a' 'A4544a' 'A4554a' 'A4559a' 'A4559b'
 'A4571a' 'A4575a' 'A4586a' 'A4606a' 'A4606b' 'A4608a' 'A4644a' 'A4644b'
 'A4650a' 'A4654a' 'A4669a' 'A4669b' 'A4670a' 'A4673a' 'A4673b' 'A4707a'
 'A4715a' 'A4735a' 'A4739a' 'A4742a' 'A4742b' 'A4752a' 'A4771a' 'A4777a'
 'A4778a' 'A4806a' 'A4806b' 'A4827a' 'A4827b' 'A4838a' 'A4845a' 'A4856a'
 'A4872a' 'A4877a' 'A4877b' 'A4882a' 'A4882b' 'A4883a' 'A4883b' 'A4885a'
 'A4885b' 'A4895a' 'A4895b' 'A4963a' 'A4963b' 'A4977a' 'A4977b' 'A4935a'
 'A4943a' 'A4943b' 'A4947a' 'A4959a' 'A4959b' 'A4992a' 'A5015a' 'A5015b'
 'A5039a' 'A5039b' 'A5079a' 'A5079b' 'A5081a' 'A5081b' 'A5104a' 'A5131a'
 'A5171a' 'A5171b' 'A5177a' 'A5200a' 'A5203a' 'A5203b' 'A5213a' 'A5213b'
 'A5247a' 'A5247b' 'A5255a' 'A5262a' 'A5262b' 'A5268a' 'A5289a' 'A5289b'
 'A5339a' 'A5339b' 'A5366a' 'A5366b' 'A5388a' 'A5598a' 'A5598b']

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A5151a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A0451a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A0514a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A0514b_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A0517a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A0525a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A0528a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A0528b_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A0540a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A0554b_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A0554a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A0556a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A0566a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A0586a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A0269a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A0608a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A0152a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A0152b_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A0194a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A0237a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A0239a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A0354a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A0375a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A0375b_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A0375c_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A0836a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A0836b_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A0853a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A0863a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A0884a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A0911a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A1292a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A1346a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A1775a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A2293a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A2304a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A2339a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A2454a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A2846a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A2972a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A3066a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A3175a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A3176a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A3181a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A3181b_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A3188a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A3189a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A3191a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A3201a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A3207a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A3208a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A3210a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A3229a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A3280a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A3306a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A3581a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A3371a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A3379a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A3403a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A3410a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A3419a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A3435a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A3436a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A3593a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A3606a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A3521a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A3521b_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A3548a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A3556a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A3571a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A3571b_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A3575a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A3849a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A3858a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A3858b_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A3869a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A3883a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A3897a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A3901a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A3914a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A3920a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A3936a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A3940a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A3942a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A3944a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A3954a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A3963a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A3963b_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A3968a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A3975a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A3986a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A3986b_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A3989a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A3990a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A4028a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A4202a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A4202b_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A4290a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A4291a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A4317a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A4319a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A4321a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A4321b_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A4331a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A4331b_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A4333a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A4334a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A4334b_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A4341a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A4343a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A4343b_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A4344a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A4347a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A4350a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A4365a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A4365b_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A4368a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A4372a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A4373a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A4380a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A4381a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A4203a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A4207a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A4207b_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A4209a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A4237a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A4237b_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A4254a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A4260a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A4283a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A4283b_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A4386a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A4402a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A4423a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A4431a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A4445a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A4445b_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A4449a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A4449b_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A4451a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A4451b_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A4456a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A4456b_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A4461a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A4463a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A4467a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A4472a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A4476a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A4489a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A4489b_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A4494a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A4510a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A4514a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A4526a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A4528a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A4538a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A4544a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A4554a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A4559a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A4559b_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A4571a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A4575a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A4586a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A4606a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A4606b_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A4608a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A4644a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A4644b_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A4650a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A4654a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A4669a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A4669b_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A4670a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A4673a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A4673b_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A4707a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A4715a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A4735a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A4739a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A4742a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A4742b_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A4752a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A4771a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A4777a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A4778a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A4806a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A4806b_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A4827a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A4827b_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A4838a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A4845a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A4856a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A4872a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A4877a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A4877b_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A4882a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A4882b_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A4883a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A4883b_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A4885a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A4885b_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A4895a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A4895b_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A4963a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A4963b_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A4977a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A4977b_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A4935a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A4943a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A4943b_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A4947a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A4959a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A4959b_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A4992a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A5015a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A5015b_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A5039a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A5039b_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A5079a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A5079b_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A5081a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A5081b_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A5104a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A5131a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A5171a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A5171b_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A5177a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A5200a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A5203a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A5203b_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A5213a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A5213b_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A5247a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A5247b_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A5255a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A5262a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A5262b_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A5268a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A5289a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A5289b_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A5339a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A5339b_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A5366a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A5366b_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A5388a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A5598a_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/templates/A5598b_apo-desolv.pdb...

 DISK  Writing cycle_02/syndirella/retrosynthesis/openbind_a71ev2a_c2_elaborated_hits_syndirella_input.csv...

DEBUG: querying...

Output()

 DISK  Writing
cycle_02/syndirella/retrosynthesis/openbind_a71ev2a_c2_elaborated_hits_syndirella_inspiration_hits.sdf...

,smiles,template,compound_set,hit1
id,,,,
4,NC(=O)[C@H]1CCCN(C(=O)Cc2cccc3c2SCC3)C1,A5151a,openbind_a71ev2a_c2_elaborated_hits,A5151a
6,CNC(=O)c1cn(C)c2ccccc12,A0451a,openbind_a71ev2a_c2_elaborated_hits,A0451a
15,COc1ccc2sc(N)nc2c1,A0514a,openbind_a71ev2a_c2_elaborated_hits,A0514a
16,COc1ccc2sc(N)nc2c1,A0514b,openbind_a71ev2a_c2_elaborated_hits,A0514b
19,CCn1cc(C(=O)NCc2ccc(F)cc2)cn1,A0517a,openbind_a71ev2a_c2_elaborated_hits,A0517a
...,...,...,...,...
606,CSc1ccc(Br)cc1CC(=O)N1C[C@@H](C(N)=O)CC[C@H]1C,A5366a,openbind_a71ev2a_c2_elaborated_hits,A5366a
607,CSc1ccc(Br)cc1CC(=O)N1C[C@@H](C(N)=O)CC[C@H]1C,A5366b,openbind_a71ev2a_c2_elaborated_hits,A5366b
609,CSc1ccc(Br)cc1CC(=O)N1CC[C@](O)(C(N)=O)C1,A5388a,openbind_a71ev2a_c2_elaborated_hits,A5388a
639,CSc1ccc(N2CCOCC2)cc1NC(=O)N1CCC[C@H](C(N)=O)C1,A5598a,openbind_a71ev2a_c2_elaborated_hits,A5598a
640,CSc1ccc(N2CCOCC2)cc1NC(=O)N1CCC[C@H](C(N)=O)C1,A5598b,openbind_a71ev2a_c2_elaborated_hits,A5598b

cd cycle_02/syndirella/retrosynthesis
sb --job-name "a71ev2a_c2_retro" --mem 16000 $HOME2/slurm/run_bash_with_conda.sh ../../../../scripts/run_syndirella_retro.sh

In [29]:
animal.add_syndirella_routes(
    "cycle_02/syndirella/retrosynthesis/justretroquery_openbind_a71ev2a_c2_elaborated_hits_syndirella_input.pkl.gz", 
    CAR_only=False,
    check_chemistry=False,
)

Output()

0 0 0 Amidation C4 "ASAP-0038158-001"

 Success  registered route 20380!

1 0 0 Amidation C6 "ASAP-0018935-002"

 Success  registered route 20381!

2 0 0 Amidation C6 "ASAP-0018935-002"

 Success  registered route 20382!

3 0 0 N-nucleophilic_aromatic_substitution C14 "Z1201620232"

 Success  registered route 20383!

4 0 0 N-nucleophilic_aromatic_substitution C14 "Z1201620232"

 Success  registered route 20384!

5 0 0 N-nucleophilic_aromatic_substitution C14 "Z1201620232"

 Success  registered route 20385!

6 0 0 N-nucleophilic_aromatic_substitution C14 "Z1201620232"

 Success  registered route 20386!

7 0 0 Amidation C16 "Z1203107138"

 Success  registered route 20387!

8 0 0 Williamson_ether_synthesis C17 "Z1216861874"

 Success  registered route 20388!

9 0 0 Mitsunobu_aryl_ether_synthesis C19 "Z1217960891"

 Success  registered route 20389!

10 0 0 Mitsunobu_aryl_ether_synthesis C19 "Z1217960891"

 Success  registered route 20390!

11 0 0 Mitsunobu_aryl_ether_synthesis C19 "Z1217960891"

 Success  registered route 20391!

12 0 0 Mitsunobu_aryl_ether_synthesis C19 "Z1217960891"

 Success  registered route 20392!

13 0 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C20 "ASAP-0018458-002"

 Success  registered route 20393!

14 0 0 Amidation C22 "Z1255459547"

 Success  registered route 20394!

15 0 0 Amidation C22 "Z1255459547"

 Success  registered route 20395!

16 0 0 Amidation C22 "Z1255459547"

 Success  registered route 20396!

17 0 0 Amidation C22 "Z1255459547"

 Success  registered route 20397!

18 0 0 Amidation C23 "Z1259207775"

 Success  registered route 20398!

19 0 0 Amidation C24 "ASAP-0019102-002"

 Success  registered route 20399!

20 0 0 Sulfonamide_synthesis_from_carboxylic_acid_and_amine C26 "ASAP-0018553-002"

 Success  registered route 20400!

21 0 0 Aziridine_+_amine_coupling C27 "ASAP-0030730-001"

 Success  registered route 20401!

22 0 0 Amidation C32 "ASAP-0030854-001"

 Success  registered route 20402!

23 0 0 Ester_amidation C34 "ASAP-0018549-002"

 Success  registered route 20403!

24 0 0 Ester_amidation C34 "ASAP-0018549-002"

 Success  registered route 20404!

25 0 0 Ester_amidation C34 "ASAP-0018549-002"

 Success  registered route 20405!

26 0 0 Ester_amidation C34 "ASAP-0018549-002"

 Success  registered route 20406!

27 0 0 Mitsunobu_reaction_with_amine_alcohol_and_thioalcohol C36 "ASAP-0019298-002"

 Success  registered route 20407!

28 0 0 Amidation C41 "ASAP-0018619-002"

 Success  registered route 20408!

29 0 0 Amidation C42 "Z438067480"

 Success  registered route 20409!

30 0 0 Amidation C47 "ASAP-0030819-001"

 Success  registered route 20410!

31 0 0 Isothiocyanate_to_thiourea C50 "ASAP-0018949-002"

 Success  registered route 20411!

32 0 0 Isothiocyanate_to_thiourea C50 "ASAP-0018949-002"

 Success  registered route 20412!

33 0 0 Isothiocyanate_to_thiourea C50 "ASAP-0018949-002"

 Success  registered route 20413!

34 0 0 Isothiocyanate_to_thiourea C50 "ASAP-0018949-002"

 Success  registered route 20414!

35 0 0 Isothiocyanate_to_thiourea C50 "ASAP-0018949-002"

 Success  registered route 20415!

36 0 0 Isothiocyanate_to_thiourea C50 "ASAP-0018949-002"

 Success  registered route 20416!

37 0 0 Isothiocyanate_to_thiourea C50 "ASAP-0018949-002"

 Success  registered route 20417!

38 0 0 Isothiocyanate_to_thiourea C50 "ASAP-0018949-002"

 Success  registered route 20418!

39 0 0 Isothiocyanate_to_thiourea C50 "ASAP-0018949-002"

 Success  registered route 20419!

40 0 0 Petasis-borono_Mannich_reaction C68 "Z2574937229"

 Success  registered route 20420!

41 0 0 Petasis-borono_Mannich_reaction C68 "Z2574937229"

 Success  registered route 20421!

42 0 0 Petasis-borono_Mannich_reaction C68 "Z2574937229"

 Success  registered route 20422!

43 0 0 Petasis-borono_Mannich_reaction C68 "Z2574937229"

 Success  registered route 20423!

44 0 0 Amidation C69 "ASAP-0018718-002"

 Success  registered route 20424!

45 0 0 Amidation C70 "Z55993012"

 Success  registered route 20425!

46 0 0 Amidation C72 "ASAP-0019110-002"

 Success  registered route 20426!

47 0 0 Amidation C72 "ASAP-0019110-002"

 Success  registered route 20427!

48 0 0 Chan-Lam_coupling_of_amides,_sulfonamides,_and_imides C73 "ASAP-0030697-001"

 Success  registered route 20428!

49 0 0 Buchwald-Hartwig_(thio)etherification C92 "ASAP-0018269-002"

 Success  registered route 20429!

50 0 0 Amidation C94 "ASAP-0016618-001"

 Success  registered route 20430!

51 0 0 Mitsunobu_aryl_ether_synthesis C96 "ASAP-0024999-003"

 Success  registered route 20431!

52 0 0 Amidation C101 "ASAP-0030249-001"

 Success  registered route 20432!

53 0 0 Amidation C102 "ASAP-0030304-001"

 Success  registered route 20433!

54 0 0 Amidation C103 "ASAP-0030497-001"

 Success  registered route 20434!

55 0 0 Amidation C72 "ASAP-0019110-002"

 Success  registered route 20435!

56 0 0 Amidation C72 "ASAP-0019110-002"

 Success  registered route 20436!

57 0 0 Amidation C107 "ASAP-0031281-001"

 Success  registered route 20437!

58 0 0 Amidation C108 "ASAP-0031631-001"

 Warning  SMILES changed during compound registration: NCc1c[nH]cn1 --> NCc1cnc[nH]1!

 Success  registered route 20438!

59 0 0 Amidation C6 "ASAP-0018935-002"

 Success  registered route 20439!

60 0 0 Amidation C6 "ASAP-0018935-002"

 Success  registered route 20440!

61 0 0 Amidation C110 "ASAP-0031591-001"

 Success  registered route 20441!

62 0 0 Amidation C111 "ASAP-0031604-001"

 Success  registered route 20442!

63 0 0 Amidation C114 "ASAP-0031733-001"

 Success  registered route 20443!

64 0 0 Amidation C114 "ASAP-0031733-001"

 Success  registered route 20444!

65 0 0 Amidation C114 "ASAP-0031733-001"

 Success  registered route 20445!

66 0 0 Amidation C114 "ASAP-0031733-001"

 Success  registered route 20446!

67 0 0 Amidation C116 "ASAP-0032784-001"

 Success  registered route 20447!

68 0 0 Amidation C116 "ASAP-0032784-001"

 Success  registered route 20448!

69 0 0 Amidation C116 "ASAP-0032784-001"

 Success  registered route 20449!

70 0 0 Amidation C116 "ASAP-0032784-001"

 Success  registered route 20450!

71 0 0 Amidation C116 "ASAP-0032784-001"

 Success  registered route 20451!

72 0 0 Amidation C116 "ASAP-0032784-001"

 Success  registered route 20452!

73 0 0 Amidation C117 "ASAP-0031848-001"

 Success  registered route 20453!

74 0 0 Amidation C120 "ASAP-0031772-001"

 Success  registered route 20454!

75 0 0 Amidation C120 "ASAP-0031772-001"

 Success  registered route 20455!

76 0 0 Amidation C120 "ASAP-0031772-001"

 Success  registered route 20456!

77 0 0 Amidation C121 "ASAP-0031919-001"

 Success  registered route 20457!

78 0 0 Amidation C122 "ASAP-0031936-001"

 Success  registered route 20458!

79 0 0 Amidation C123 "ASAP-0036334-001"

 Success  registered route 20459!

80 0 0 Amidation C129 "ASAP-0032741-001"

 Success  registered route 20460!

81 0 0 Amidation C129 "ASAP-0032741-001"

 Success  registered route 20461!

82 0 0 Amidation C133 "ASAP-0032058-001"

 Success  registered route 20462!

83 0 0 Amidation C136 "ASAP-0032003-001"

 Success  registered route 20463!

84 0 0 Amidation C139 "ASAP-0032461-001"

 Success  registered route 20464!

85 0 0 Amidation C142 "ASAP-0032051-001"

 Success  registered route 20465!

86 0 0 Amidation C143 "ASAP-0032067-001"

 Success  registered route 20466!

87 0 0 Amidation C143 "ASAP-0032067-001"

 Success  registered route 20467!

88 0 0 Amidation C145 "ASAP-0032079-001"

 Success  registered route 20468!

89 0 0 Amidation C147 "ASAP-0032204-001"

 Success  registered route 20469!

90 0 0 Amidation C149 "ASAP-0032226-001"

 Success  registered route 20470!

91 0 0 Amidation C150 "ASAP-0032228-001"

 Success  registered route 20471!

92 0 0 Amidation C151 "ASAP-0032179-001"

 Success  registered route 20472!

93 0 0 Amidation C143 "ASAP-0032067-001"

 Success  registered route 20473!

94 0 0 Amidation C143 "ASAP-0032067-001"

 Success  registered route 20474!

95 0 0 Amidation C160 "ASAP-0032503-001"

 Success  registered route 20475!

96 0 0 Amidation C172 "ASAP-0016726-001"

 Success  registered route 20476!

97 0 0 Amidation C172 "ASAP-0016726-001"

 Success  registered route 20477!

98 0 0 Amidation C129 "ASAP-0032741-001"

 Success  registered route 20478!

99 0 0 Amidation C129 "ASAP-0032741-001"

 Success  registered route 20479!

100 0 0 Amidation C176 "ASAP-0032647-001"

 Success  registered route 20480!

101 0 0 Amidation C180 "ASAP-0032676-001"

 Success  registered route 20481!

102 0 0 Amidation C180 "ASAP-0032676-001"

 Success  registered route 20482!

103 0 0 Amidation C180 "ASAP-0032676-001"

 Success  registered route 20483!

104 0 0 Amidation C180 "ASAP-0032676-001"

 Success  registered route 20484!

105 0 0 Amidation C181 "ASAP-0032627-001"

 Success  registered route 20485!

106 0 0 Amidation C120 "ASAP-0031772-001"

 Success  registered route 20486!

107 0 0 Amidation C120 "ASAP-0031772-001"

 Success  registered route 20487!

108 0 0 Amidation C182 "ASAP-0032724-001"

 Success  registered route 20488!

109 0 0 Amidation C182 "ASAP-0032724-001"

 Success  registered route 20489!

110 0 0 Amidation C182 "ASAP-0032724-001"

 Success  registered route 20490!

111 0 0 Amidation C182 "ASAP-0032724-001"

 Success  registered route 20491!

112 0 0 Amidation C120 "ASAP-0031772-001"

 Success  registered route 20492!

113 0 0 Amidation C120 "ASAP-0031772-001"

 Success  registered route 20493!

114 0 0 Amidation C185 "ASAP-0032816-001"

 Success  registered route 20494!

115 0 0 Amidation C129 "ASAP-0032741-001"

 Success  registered route 20495!

116 0 0 Amidation C189 "ASAP-0032798-001"

 Success  registered route 20496!

117 0 0 Amidation C116 "ASAP-0032784-001"

 Success  registered route 20497!

118 0 0 Amidation C116 "ASAP-0032784-001"

 Success  registered route 20498!

119 0 0 Amidation C116 "ASAP-0032784-001"

 Success  registered route 20499!

120 0 0 Amidation C120 "ASAP-0031772-001"

 Success  registered route 20500!

121 0 0 Amidation C120 "ASAP-0031772-001"

 Success  registered route 20501!

122 0 0 Amidation C120 "ASAP-0031772-001"

 Success  registered route 20502!

123 0 0 Amidation C191 "ASAP-0034437-001"

 Success  registered route 20503!

124 0 0 Amidation C195 "ASAP-0034412-001"

 Success  registered route 20504!

125 0 0 Amidation C182 "ASAP-0032724-001"

 Success  registered route 20505!

126 0 0 Amidation C182 "ASAP-0032724-001"

 Success  registered route 20506!

127 0 0 Amidation C196 "ASAP-0032502-001"

 Success  registered route 20507!

128 0 0 Amidation C197 "ASAP-0034455-001"

 Success  registered route 20508!

129 0 0 Amidation C199 "ASAP-0034475-001"

 Success  registered route 20509!

130 0 0 Amidation C199 "ASAP-0034475-001"

 Success  registered route 20510!

131 0 0 Amidation C199 "ASAP-0034475-001"

 Success  registered route 20511!

132 0 0 Amidation C199 "ASAP-0034475-001"

 Success  registered route 20512!

133 0 0 Amidation C199 "ASAP-0034475-001"

 Success  registered route 20513!

134 0 0 Amidation C199 "ASAP-0034475-001"

 Success  registered route 20514!

135 0 0 Amidation C199 "ASAP-0034475-001"

 Success  registered route 20515!

136 0 0 Amidation C199 "ASAP-0034475-001"

 Success  registered route 20516!

137 0 0 Amidation C200 "ASAP-0034451-001"

 Success  registered route 20517!

138 0 0 Amidation C201 "ASAP-0034492-001"

 Success  registered route 20518!

139 0 0 Amidation C204 "ASAP-0034383-001"

 Success  registered route 20519!

140 0 0 Amidation C204 "ASAP-0034383-001"

 Success  registered route 20520!

141 0 0 Amidation C204 "ASAP-0034383-001"

 Success  registered route 20521!

142 0 0 Amidation C204 "ASAP-0034383-001"

 Success  registered route 20522!

143 0 0 Amidation C205 "ASAP-0036452-001"

 Success  registered route 20523!

144 0 0 Amidation C205 "ASAP-0036452-001"

 Success  registered route 20524!

145 0 0 Amidation C206 "ASAP-0034420-001"

 Success  registered route 20525!

146 0 0 Amidation C213 "ASAP-0032665-001"

 Success  registered route 20526!

147 0 0 Amidation C215 "ASAP-0034411-001"

 Success  registered route 20527!

148 0 0 Amidation C215 "ASAP-0034411-001"

 Success  registered route 20528!

149 0 0 Amidation C215 "ASAP-0034411-001"

 Success  registered route 20529!

150 0 0 Amidation C215 "ASAP-0034411-001"

 Success  registered route 20530!

151 0 0 Amidation C216 "ASAP-0035411-001"

 Success  registered route 20531!

152 0 0 Amidation C217 "ASAP-0035364-001"

 Success  registered route 20532!

153 0 0 Amidation C232 "ASAP-0035363-001"

 Success  registered route 20533!

154 0 0 Amidation C233 "ASAP-0035366-001"

 Success  registered route 20534!

155 0 0 Amidation C235 "ASAP-0035368-001"

 Success  registered route 20535!

156 0 0 Amidation C235 "ASAP-0035368-001"

 Success  registered route 20536!

157 0 0 Amidation C235 "ASAP-0035368-001"

 Success  registered route 20537!

158 0 0 Amidation C235 "ASAP-0035368-001"

 Success  registered route 20538!

159 0 0 Amidation C238 "ASAP-0035378-001"

 Success  registered route 20539!

160 0 0 Amidation C238 "ASAP-0035378-001"

 Success  registered route 20540!

161 0 0 Amidation C238 "ASAP-0035378-001"

 Success  registered route 20541!

162 0 0 Amidation C238 "ASAP-0035378-001"

 Success  registered route 20542!

163 0 0 Amidation C239 "ASAP-0035302-001"

 Success  registered route 20543!

164 0 0 Amidation C240 "ASAP-0035316-001"

 Success  registered route 20544!

165 0 0 Amidation C240 "ASAP-0035316-001"

 Success  registered route 20545!

166 0 0 Amidation C240 "ASAP-0035316-001"

 Success  registered route 20546!

167 0 0 Amidation C240 "ASAP-0035316-001"

 Success  registered route 20547!

168 0 0 Amidation C242 "ASAP-0035361-001"

 Success  registered route 20548!

169 0 0 Amidation C244 "ASAP-0035371-001"

 Success  registered route 20549!

170 0 0 Amidation C244 "ASAP-0035371-001"

 Success  registered route 20550!

171 0 0 Amidation C244 "ASAP-0035371-001"

 Success  registered route 20551!

172 0 0 Amidation C244 "ASAP-0035371-001"

 Success  registered route 20552!

173 0 0 Amidation C245 "ASAP-0035346-001"

 Success  registered route 20553!

174 0 0 Amidation C120 "ASAP-0031772-001"

 Success  registered route 20554!

175 0 0 Amidation C120 "ASAP-0031772-001"

 Success  registered route 20555!

176 0 0 Amidation C120 "ASAP-0031772-001"

 Success  registered route 20556!

177 0 0 Amidation C247 "ASAP-0035326-001"

 Success  registered route 20557!

178 0 0 Amidation C249 "ASAP-0035370-001"

 Success  registered route 20558!

179 0 0 Amidation C249 "ASAP-0035370-001"

 Success  registered route 20559!

180 0 0 Amidation C249 "ASAP-0035370-001"

 Success  registered route 20560!

181 0 0 Amidation C249 "ASAP-0035370-001"

 Success  registered route 20561!

182 0 0 Amidation C250 "ASAP-0035335-001"

 Success  registered route 20562!

183 0 0 Amidation C251 "ASAP-0035287-001"

 Success  registered route 20563!

184 0 0 Amidation C252 "ASAP-0035431-001"

 Success  registered route 20564!

185 0 0 Amidation C254 "ASAP-0035430-001"

 Success  registered route 20565!

186 0 0 Amidation C255 "ASAP-0035293-001"

 Success  registered route 20566!

187 0 0 Amidation C256 "ASAP-0032793-001"

 Success  registered route 20567!

188 0 0 Amidation C257 "ASAP-0032772-001"

 Success  registered route 20568!

189 0 0 Amidation C257 "ASAP-0032772-001"

 Success  registered route 20569!

190 0 0 Amidation C257 "ASAP-0032772-001"

 Success  registered route 20570!

191 0 0 Amidation C257 "ASAP-0032772-001"

 Success  registered route 20571!

192 0 0 Amidation C182 "ASAP-0032724-001"

 Success  registered route 20572!

193 0 0 Amidation C182 "ASAP-0032724-001"

 Success  registered route 20573!

194 0 0 Amidation C259 "ASAP-0034497-001"

 Success  registered route 20574!

195 0 0 Amidation C259 "ASAP-0034497-001"

 Success  registered route 20575!

196 0 0 Amidation C259 "ASAP-0034497-001"

 Success  registered route 20576!

197 0 0 Amidation C259 "ASAP-0034497-001"

 Success  registered route 20577!

198 0 0 Amidation C261 "ASAP-0034447-001"

 Success  registered route 20578!

199 0 0 Amidation C262 "ASAP-0034462-001"

 Success  registered route 20579!

200 0 0 Amidation C264 "ASAP-0032613-001"

 Success  registered route 20580!

201 0 0 Amidation C264 "ASAP-0032613-001"

 Success  registered route 20581!

202 0 0 Amidation C264 "ASAP-0032613-001"

 Success  registered route 20582!

203 0 0 Amidation C264 "ASAP-0032613-001"

 Success  registered route 20583!

204 0 0 Amidation C265 "ASAP-0035410-001"

 Success  registered route 20584!

205 0 0 Carboxylic_acid_to_primary_amide C268 "ASAP-0036262-001"

 Success  registered route 20585!

206 0 0 Amidation C277 "ASAP-0036207-001"

 Success  registered route 20586!

207 0 0 Amidation C280 "ASAP-0035404-001"

 Success  registered route 20587!

208 0 0 Amidation C281 "ASAP-0032528-001"

 Success  registered route 20588!

209 0 0 Amidation C281 "ASAP-0032528-001"

 Success  registered route 20589!

210 0 0 Amidation C281 "ASAP-0032528-001"

 Success  registered route 20590!

211 0 0 Amidation C281 "ASAP-0032528-001"

 Success  registered route 20591!

212 0 0 Amidation C257 "ASAP-0032772-001"

 Success  registered route 20592!

213 0 0 Amidation C257 "ASAP-0032772-001"

 Success  registered route 20593!

214 0 0 Amidation C257 "ASAP-0032772-001"

 Success  registered route 20594!

215 0 0 Amidation C257 "ASAP-0032772-001"

 Success  registered route 20595!

216 0 0 Amidation C283 "ASAP-0034385-001"

 Success  registered route 20596!

217 0 0 Amidation C283 "ASAP-0034385-001"

 Success  registered route 20597!

218 0 0 Amidation C283 "ASAP-0034385-001"

 Success  registered route 20598!

219 0 0 Amidation C283 "ASAP-0034385-001"

 Success  registered route 20599!

220 0 0 Amidation C284 "ASAP-0034482-001"

 Success  registered route 20600!

221 0 0 Amidation C284 "ASAP-0034482-001"

 Success  registered route 20601!

222 0 0 Amidation C284 "ASAP-0034482-001"

 Success  registered route 20602!

223 0 0 Amidation C284 "ASAP-0034482-001"

 Success  registered route 20603!

224 0 0 Amidation C285 "ASAP-0035380-001"

 Success  registered route 20604!

225 0 0 Amidation C286 "ASAP-0035391-001"

 Success  registered route 20605!

226 0 0 Amidation C288 "ASAP-0036382-001"

 Success  registered route 20606!

227 0 0 Amidation C289 "ASAP-0036282-001"

 Success  registered route 20607!

228 0 0 Amidation C290 "ASAP-0036323-001"

 Success  registered route 20608!

229 0 0 Amidation C199 "ASAP-0034475-001"

 Success  registered route 20609!

230 0 0 Amidation C199 "ASAP-0034475-001"

 Success  registered route 20610!

231 0 0 Amidation C199 "ASAP-0034475-001"

 Success  registered route 20611!

232 0 0 Amidation C199 "ASAP-0034475-001"

 Success  registered route 20612!

233 0 0 Amidation C199 "ASAP-0034475-001"

 Success  registered route 20613!

234 0 0 Amidation C199 "ASAP-0034475-001"

 Success  registered route 20614!

235 0 0 Amidation C199 "ASAP-0034475-001"

 Success  registered route 20615!

236 0 0 Amidation C199 "ASAP-0034475-001"

 Success  registered route 20616!

237 0 0 Amidation C292 "ASAP-0036383-001"

 Success  registered route 20617!

238 0 0 Amidation C295 "ASAP-0036298-001"

 Success  registered route 20618!

239 0 0 Amidation C295 "ASAP-0036298-001"

 Success  registered route 20619!

240 0 0 Amidation C296 "ASAP-0036390-001"

 Success  registered route 20620!

241 0 0 Amidation C296 "ASAP-0036390-001"

 Success  registered route 20621!

242 0 0 Amidation C300 "ASAP-0036360-001"

 Success  registered route 20622!

243 0 0 Amidation C301 "ASAP-0036402-001"

 Success  registered route 20623!

244 0 0 Amidation C301 "ASAP-0036402-001"

 Success  registered route 20624!

245 0 0 Amidation C303 "ASAP-0036393-001"

 Success  registered route 20625!

246 0 0 Amidation C305 "ASAP-0036366-001"

 Success  registered route 20626!

247 0 0 Buchwald-Hartwig_amidation_with_amide-like_nucleophile C307 "ASAP-0036210-001"

 Success  registered route 20627!

248 0 0 Amidation C308 "ASAP-0036387-001"

 Success  registered route 20628!

249 0 0 Amidation C308 "ASAP-0036387-001"

 Success  registered route 20629!

250 0 0 Amidation C308 "ASAP-0036387-001"

 Success  registered route 20630!

251 0 0 Amidation C308 "ASAP-0036387-001"

 Success  registered route 20631!

252 0 0 Amidation C295 "ASAP-0036298-001"

 Success  registered route 20632!

253 0 0 Amidation C295 "ASAP-0036298-001"

 Success  registered route 20633!

254 0 0 Amidation C296 "ASAP-0036390-001"

 Success  registered route 20634!

255 0 0 Amidation C296 "ASAP-0036390-001"

 Success  registered route 20635!

256 0 0 Amidation C300 "ASAP-0036360-001"

 Success  registered route 20636!

257 0 0 Amidation C312 "ASAP-0036444-001"

 Success  registered route 20637!

258 0 0 Amidation C312 "ASAP-0036444-001"

 Success  registered route 20638!

259 0 0 Amidation C312 "ASAP-0036444-001"

 Success  registered route 20639!

260 0 0 Amidation C312 "ASAP-0036444-001"

 Success  registered route 20640!

261 0 0 Amidation C313 "ASAP-0036538-001"

 Success  registered route 20641!

262 0 0 Amidation C315 "ASAP-0036431-001"

 Success  registered route 20642!

263 0 0 Amidation C315 "ASAP-0036431-001"

 Success  registered route 20643!

264 0 0 Amidation C315 "ASAP-0036431-001"

 Success  registered route 20644!

265 0 0 Amidation C315 "ASAP-0036431-001"

 Success  registered route 20645!

266 0 0 Sp3-sp2_Suzuki_coupling C316 "ASAP-0036436-001"

 Success  registered route 20646!

267 0 0 Buchwald-Hartwig_amidation_with_amide-like_nucleophile C317 "ASAP-0036491-001"

 Success  registered route 20647!

268 0 0 Amidation C318 "ASAP-0036599-001"

 Success  registered route 20648!

269 0 0 Amidation C318 "ASAP-0036599-001"

 Success  registered route 20649!

270 0 0 Amidation C318 "ASAP-0036599-001"

 Success  registered route 20650!

271 0 0 Amidation C318 "ASAP-0036599-001"

 Success  registered route 20651!

272 0 0 Amidation C319 "ASAP-0036592-001"

 Success  registered route 20652!

273 0 0 Amidation C320 "ASAP-0036562-001"

 Success  registered route 20653!

274 0 0 Amidation C320 "ASAP-0036562-001"

 Success  registered route 20654!

275 0 0 Amidation C320 "ASAP-0036562-001"

 Success  registered route 20655!

276 0 0 Amidation C320 "ASAP-0036562-001"

 Success  registered route 20656!

277 0 0 Amidation C329 "ASAP-0036609-001"

 Success  registered route 20657!

278 0 0 S-nucleophilic_aromatic_substitution C333 "ASAP-0036643-001"

 Success  registered route 20658!

279 0 0 Amidation C337 "ASAP-0036805-001"

 Success  registered route 20659!

280 0 0 Amidation C339 "ASAP-0036816-001"

 Success  registered route 20660!

281 0 0 Amidation C340 "ASAP-0036791-001"

 Success  registered route 20661!

282 0 0 Amidation C340 "ASAP-0036791-001"

 Success  registered route 20662!

283 0 0 Amidation C340 "ASAP-0036791-001"

 Success  registered route 20663!

284 0 0 Amidation C340 "ASAP-0036791-001"

 Success  registered route 20664!

285 0 0 Amidation C345 "ASAP-0036788-001"

 Success  registered route 20665!

286 0 0 Amidation C347 "ASAP-0036830-001"

 Success  registered route 20666!

287 0 0 Amidation C349 "ASAP-0036726-001"

 Success  registered route 20667!

288 0 0 Amidation C349 "ASAP-0036726-001"

 Success  registered route 20668!

289 0 0 Amidation C355 "ASAP-0036755-001"

 Success  registered route 20669!

290 0 0 Amidation C355 "ASAP-0036755-001"

 Success  registered route 20670!

291 0 0 Amidation C355 "ASAP-0036755-001"

 Success  registered route 20671!

292 0 0 Amidation C355 "ASAP-0036755-001"

 Success  registered route 20672!

293 0 0 Alpha-arylation C360 "ASAP-0036645-001"

 Success  registered route 20673!

294 0 0 Alpha-arylation C360 "ASAP-0036645-001"

 Success  registered route 20674!

295 0 0 Alpha-arylation C360 "ASAP-0036645-001"

 Success  registered route 20675!

296 0 0 Alpha-arylation C360 "ASAP-0036645-001"

 Success  registered route 20676!

297 0 0 Amidation C205 "ASAP-0036452-001"

 Success  registered route 20677!

298 0 0 Amidation C205 "ASAP-0036452-001"

 Success  registered route 20678!

299 0 0 Amidation C366 "ASAP-0036474-001"

 Success  registered route 20679!

300 0 0 Amidation C370 "ASAP-0036545-001"

 Success  registered route 20680!

301 0 0 Amidation C301 "ASAP-0036402-001"

 Success  registered route 20681!

302 0 0 Amidation C301 "ASAP-0036402-001"

 Success  registered route 20682!

303 0 0 Amidation C372 "ASAP-0036525-001"

 Success  registered route 20683!

304 0 0 Amidation C372 "ASAP-0036525-001"

 Success  registered route 20684!

305 0 0 Amidation C372 "ASAP-0036525-001"

 Success  registered route 20685!

306 0 0 Amidation C372 "ASAP-0036525-001"

 Success  registered route 20686!

307 0 0 Amidation C374 "ASAP-0036446-001"

 Success  registered route 20687!

308 0 0 Amidation C374 "ASAP-0036446-001"

 Success  registered route 20688!

309 0 0 Amidation C374 "ASAP-0036446-001"

 Success  registered route 20689!

310 0 0 Amidation C374 "ASAP-0036446-001"

 Success  registered route 20690!

311 0 0 Buchwald-Hartwig_amidation_with_amide-like_nucleophile C375 "ASAP-0036475-001"

 Success  registered route 20691!

312 0 0 Buchwald-Hartwig_amidation_with_amide-like_nucleophile C375 "ASAP-0036475-001"

 Success  registered route 20692!

313 0 0 Buchwald-Hartwig_amidation_with_amide-like_nucleophile C375 "ASAP-0036475-001"

 Success  registered route 20693!

314 0 0 Buchwald-Hartwig_amidation_with_amide-like_nucleophile C375 "ASAP-0036475-001"

 Success  registered route 20694!

315 0 0 Amidation C376 "ASAP-0038232-001"

 Success  registered route 20695!

316 0 0 Amidation C376 "ASAP-0038232-001"

 Success  registered route 20696!

317 0 0 Amidation C376 "ASAP-0038232-001"

 Success  registered route 20697!

318 0 0 Amidation C376 "ASAP-0038232-001"

 Success  registered route 20698!

319 0 0 Amidation C378 "ASAP-0036303-001"

 Success  registered route 20699!

320 0 0 Amidation C378 "ASAP-0036303-001"

 Success  registered route 20700!

321 0 0 Amidation C378 "ASAP-0036303-001"

 Success  registered route 20701!

322 0 0 Amidation C378 "ASAP-0036303-001"

 Success  registered route 20702!

323 0 0 Amidation C387 "ASAP-0037730-001"

 Success  registered route 20703!

324 0 0 Amidation C387 "ASAP-0037730-001"

 Success  registered route 20704!

325 0 0 Amidation C387 "ASAP-0037730-001"

 Success  registered route 20705!

326 0 0 Amidation C387 "ASAP-0037730-001"

 Success  registered route 20706!

327 0 0 Buchwald-Hartwig_(thio)etherification C389 "ASAP-0037711-001"

 Success  registered route 20707!

328 0 0 Buchwald-Hartwig_(thio)etherification C389 "ASAP-0037711-001"

 Success  registered route 20708!

329 0 0 Buchwald-Hartwig_(thio)etherification C389 "ASAP-0037711-001"

 Success  registered route 20709!

330 0 0 Buchwald-Hartwig_(thio)etherification C389 "ASAP-0037711-001"

 Success  registered route 20710!

331 0 0 Amidation C392 "ASAP-0036626-001"

 Success  registered route 20711!

332 0 0 Amidation C340 "ASAP-0036791-001"

 Success  registered route 20712!

333 0 0 Amidation C340 "ASAP-0036791-001"

 Success  registered route 20713!

334 0 0 Amidation C340 "ASAP-0036791-001"

 Success  registered route 20714!

335 0 0 Amidation C340 "ASAP-0036791-001"

 Success  registered route 20715!

336 0 0 Carboxylic_acid_to_primary_amide C393 "ASAP-0037612-001"

 Success  registered route 20716!

337 0 0 S-nucleophilic_aromatic_substitution C396 "ASAP-0036437-001"

 Success  registered route 20717!

338 0 0 S-nucleophilic_aromatic_substitution C396 "ASAP-0036437-001"

 Success  registered route 20718!

339 0 0 S-nucleophilic_aromatic_substitution C396 "ASAP-0036437-001"

 Success  registered route 20719!

340 0 0 S-nucleophilic_aromatic_substitution C396 "ASAP-0036437-001"

 Success  registered route 20720!

341 0 0 Carboxylic_acid_to_primary_amide C397 "ASAP-0037807-001"

 Success  registered route 20721!

342 0 0 Alpha-arylation C400 "ASAP-0037772-001"

 Success  registered route 20722!

343 0 0 Alpha-arylation C400 "ASAP-0037772-001"

 Success  registered route 20723!

344 0 0 Alpha-arylation C400 "ASAP-0037772-001"

 Success  registered route 20724!

345 0 0 Alpha-arylation C400 "ASAP-0037772-001"

 Success  registered route 20725!

346 0 0 Alpha-arylation C404 "ASAP-0036740-001"

 Success  registered route 20726!

347 0 0 Alpha-arylation C404 "ASAP-0036740-001"

 Success  registered route 20727!

348 0 0 Alpha-arylation C404 "ASAP-0036740-001"

 Success  registered route 20728!

349 0 0 Alpha-arylation C404 "ASAP-0036740-001"

 Success  registered route 20729!

350 0 0 Amidation C407 "ASAP-0037793-001"

 Success  registered route 20730!

351 0 0 Amidation C407 "ASAP-0037793-001"

 Success  registered route 20731!

352 0 0 Amidation C407 "ASAP-0037793-001"

 Success  registered route 20732!

353 0 0 Amidation C407 "ASAP-0037793-001"

 Success  registered route 20733!

354 0 0 Amidation C408 "ASAP-0037792-001"

 Success  registered route 20734!

355 0 0 Amidation C408 "ASAP-0037792-001"

 Success  registered route 20735!

356 0 0 Amidation C408 "ASAP-0037792-001"

 Success  registered route 20736!

357 0 0 Amidation C408 "ASAP-0037792-001"

 Success  registered route 20737!

358 0 0 Amidation C376 "ASAP-0038232-001"

 Success  registered route 20738!

359 0 0 Amidation C376 "ASAP-0038232-001"

 Success  registered route 20739!

360 0 0 Amidation C376 "ASAP-0038232-001"

 Success  registered route 20740!

361 0 0 Amidation C413 "ASAP-0037789-001"

 Success  registered route 20741!

362 0 0 Amidation C414 "ASAP-0038203-001"

 Success  registered route 20742!

363 0 0 Amidation C414 "ASAP-0038203-001"

 Success  registered route 20743!

364 0 0 Amidation C414 "ASAP-0038203-001"

 Success  registered route 20744!

365 0 0 Amidation C414 "ASAP-0038203-001"

 Success  registered route 20745!

366 0 0 Amidation C413 "ASAP-0037789-001"

 Success  registered route 20746!

367 0 0 Amidation C376 "ASAP-0038232-001"

 Success  registered route 20747!

368 0 0 Amidation C376 "ASAP-0038232-001"

 Success  registered route 20748!

369 0 0 Amidation C376 "ASAP-0038232-001"

 Success  registered route 20749!

370 0 0 Amidation C416 "ASAP-0038260-001"

 Success  registered route 20750!

371 0 0 Amidation C416 "ASAP-0038260-001"

 Success  registered route 20751!

372 0 0 Amidation C416 "ASAP-0038260-001"

 Success  registered route 20752!

373 0 0 Amidation C416 "ASAP-0038260-001"

 Success  registered route 20753!

374 0 0 Alpha-arylation C418 "ASAP-0038418-001"

 Success  registered route 20754!

375 0 0 Alpha-arylation C418 "ASAP-0038418-001"

 Success  registered route 20755!

376 0 0 Alpha-arylation C418 "ASAP-0038418-001"

 Success  registered route 20756!

377 0 0 Alpha-arylation C418 "ASAP-0038418-001"

 Success  registered route 20757!

378 0 0 Amidation C423 "ASAP-0038442-001"

 Success  registered route 20758!

379 0 0 Amidation C423 "ASAP-0038442-001"

 Success  registered route 20759!

380 0 0 Amidation C423 "ASAP-0038442-001"

 Success  registered route 20760!

381 0 0 Amidation C423 "ASAP-0038442-001"

 Success  registered route 20761!

382 0 0 Amidation C425 "ASAP-0038432-001"

 Success  registered route 20762!

383 0 0 Amidation C426 "ASAP-0038424-001"

 Success  registered route 20763!

384 0 0 Amidation C426 "ASAP-0038424-001"

 Success  registered route 20764!

385 0 0 Amidation C426 "ASAP-0038424-001"

 Success  registered route 20765!

386 0 0 Amidation C426 "ASAP-0038424-001"

 Success  registered route 20766!

387 0 0 Amidation C376 "ASAP-0038232-001"

 Success  registered route 20767!

388 0 0 Amidation C376 "ASAP-0038232-001"

 Success  registered route 20768!

389 0 0 Amidation C376 "ASAP-0038232-001"

 Success  registered route 20769!

390 0 0 S-nucleophilic_aromatic_substitution C430 "ASAP-0038528-001"

 Success  registered route 20770!

391 0 0 S-nucleophilic_aromatic_substitution C430 "ASAP-0038528-001"

 Success  registered route 20771!

392 0 0 S-nucleophilic_aromatic_substitution C430 "ASAP-0038528-001"

 Success  registered route 20772!

393 0 0 S-nucleophilic_aromatic_substitution C430 "ASAP-0038528-001"

 Success  registered route 20773!

394 0 0 Amidation C423 "ASAP-0038442-001"

 Success  registered route 20774!

395 0 0 Amidation C423 "ASAP-0038442-001"

 Success  registered route 20775!

396 0 0 Amidation C423 "ASAP-0038442-001"

 Success  registered route 20776!

397 0 0 Amidation C423 "ASAP-0038442-001"

 Success  registered route 20777!

398 0 0 Amidation C423 "ASAP-0038442-001"

 Success  registered route 20778!

399 0 0 Amidation C423 "ASAP-0038442-001"

 Success  registered route 20779!

400 0 0 Amidation C423 "ASAP-0038442-001"

 Success  registered route 20780!

401 0 0 Amidation C423 "ASAP-0038442-001"

 Success  registered route 20781!

402 0 0 Amidation C434 "ASAP-0038677-001"

 Success  registered route 20782!

403 0 0 Buchwald-Hartwig_amination C454 "ASAP-0039147-001"

 Success  registered route 20783!

404 0 0 Buchwald-Hartwig_amination C454 "ASAP-0039147-001"

 Success  registered route 20784!

405 0 0 Buchwald-Hartwig_amination C454 "ASAP-0039147-001"

 Success  registered route 20785!

406 0 0 Buchwald-Hartwig_amination C454 "ASAP-0039147-001"

 Success  registered route 20786!

,smiles,template,compound_set,hit1,route0,route0_names,route0_CAR,route0_non_CAR,route1,route1_names,...,route2_CAR,route2_non_CAR,route3,route3_names,route3_CAR,route3_non_CAR,route4,route4_names,route4_CAR,route4_non_CAR
0,NC(=O)[C@H]1CCCN(C(=O)Cc2cccc3c2SCC3)C1,A5151a,openbind_a71ev2a_c2_elaborated_hits,A5151a,"[{'name': 'Amidation', 'reactantSmiles': ['O=C...",[Amidation],True,None,"[{'name': 'Alpha-arylation', 'reactantSmiles':...",[Alpha-arylation],...,False,[Alpha-arylation],"[{'name': 'Ester_amidation', 'reactantSmiles':...",[Ester_amidation],True,None,"[{'name': 'Ester_amidation', 'reactantSmiles':...",[Ester_amidation],True,None
1,CNC(=O)c1cn(C)c2ccccc12,A0451a,openbind_a71ev2a_c2_elaborated_hits,A0451a,"[{'name': 'Amidation', 'reactantSmiles': ['Cn1...",[Amidation],True,None,"[{'name': 'Amine_alkylation', 'reactantSmiles'...",[Amine_alkylation],...,False,"[Chan-Lam_coupling_of_amides,_sulfonamides,_an...",[{'name': 'Mitsunobu_reaction_with_aromatic_nh...,[Mitsunobu_reaction_with_aromatic_nh],False,[Mitsunobu_reaction_with_aromatic_nh],"[{'name': 'Amide_Schotten-Baumann_with_amine',...",[Amide_Schotten-Baumann_with_amine],True,None
2,CNC(=O)c1cn(C)c2ccccc12,A0451a,openbind_a71ev2a_c2_elaborated_hits,A0451a,"[{'name': 'Amidation', 'reactantSmiles': ['Cn1...",[Amidation],True,None,"[{'name': 'Amine_alkylation', 'reactantSmiles'...",[Amine_alkylation],...,False,"[Chan-Lam_coupling_of_amides,_sulfonamides,_an...",[{'name': 'Mitsunobu_reaction_with_aromatic_nh...,[Mitsunobu_reaction_with_aromatic_nh],False,[Mitsunobu_reaction_with_aromatic_nh],"[{'name': 'Amide_Schotten-Baumann_with_amine',...",[Amide_Schotten-Baumann_with_amine],True,None
3,COc1ccc2sc(N)nc2c1,A0514a,openbind_a71ev2a_c2_elaborated_hits,A0514a,[{'name': 'N-nucleophilic_aromatic_substitutio...,[N-nucleophilic_aromatic_substitution],True,None,[{'name': 'O-Nucleophilic_aromatic_substitutio...,[O-Nucleophilic_aromatic_substitution_(methyls...,...,True,None,[{'name': 'N-nucleophilic_aromatic_substitutio...,[N-nucleophilic_aromatic_substitution],True,None,[{'name': 'N-nucleophilic_aromatic_substitutio...,[N-nucleophilic_aromatic_substitution],True,None
4,COc1ccc2sc(N)nc2c1,A0514a,openbind_a71ev2a_c2_elaborated_hits,A0514a,[{'name': 'N-nucleophilic_aromatic_substitutio...,[N-nucleophilic_aromatic_substitution],True,None,[{'name': 'O-Nucleophilic_aromatic_substitutio...,[O-Nucleophilic_aromatic_substitution_(methyls...,...,True,None,[{'name': 'N-nucleophilic_aromatic_substitutio...,[N-nucleophilic_aromatic_substitution],True,None,[{'name': 'N-nucleophilic_aromatic_substitutio...,[N-nucleophilic_aromatic_substitution],True,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
402,CSc1ccc(Br)cc1CC(=O)N1CC[C@](O)(C(N)=O)C1,A5388a,openbind_a71ev2a_c2_elaborated_hits,A5388a,"[{'name': 'Amidation', 'reactantSmiles': ['NC(...",[Amidation],True,None,[{'name': 'S-nucleophilic_aromatic_substitutio...,[S-nucleophilic_aromatic_substitution],...,True,None,[{'name': 'S-nucleophilic_aromatic_substitutio...,[S-nucleophilic_aromatic_substitution],True,None,[{'name': 'Sp3-sp2_Macmillan_coupling_alcohol_...,[Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_h...,False,[Sp3-sp2_Macmillan_coupling_alcohol_and_aryl_h...
403,CSc1ccc(N2CCOCC2)cc1NC(=O)N1CCC[C@H](C(N)=O)C1,A5598a,openbind_a71ev2a_c2_elaborated_hits,A5598a,"[{'name': 'Buchwald-Hartwig_amination', 'react...",[Buchwald-Hartwig_amination],True,None,"[{'name': 'Buchwald-Hartwig_amination', 'react...",[Buchwald-Hartwig_amination],...,True,None,"[{'name': 'Iodo_N-arylation', 'reactantSmiles'...","[Iodo_N-arylation, Buchwald-Hartwig_amination]",True,None,[{'name': 'Mitsunobu_reaction_with_amine_alcoh...,[Mitsunobu_reaction_with_amine_alcohol_and_thi...,True,None
404,CSc1ccc(N2CCOCC2)cc1NC(=O)N1CCC[C@H](C(N)=O)C1,A5598a,openbind_a71ev2a_c2_elaborated_hits,A5598a,"[{'name': 'Buchwald-Hartwig_amination', 'react...",[Buchwald-Hartwig_amination],True,None,"[{'name': 'Buchwald-Hartwig_amination', 'react...",[Buchwald-Hartwig_amination],...,True,None,"[{'name': 'Iodo_N-arylation', 'reactantSmiles'...","[Iodo_N-arylation, Buchwald-Hartwig_amination]",True,None,"[{'name': 'Formation_of_urea_from_two_amines',...","[Formation_of_urea_from_two_amines, S-nucleoph...",True,None
405,CSc1ccc(N2CCOCC2)cc1NC(=O)N1CCC[C@H](C(N)=O)C1,A5598b,openbind_a71ev2a_c2_elaborated_hits,A5598b,"[{'name': 'Buchwald-Hartwig_amination', 'react...",[Buchwald-Hartwig_amination],True,None,"[{'name': 'Buchwald-Hartwig_amination', 'react...",[Buchwald-Hartwig_amination],...,True,None,"[{'name': 'Iodo_N-arylation', 'reactantSmiles'...","[Iodo_N-arylation, Buchwald-Hartwig_amination]",True,None,[{'name': 'Mitsunobu_reaction_with_amine_alcoh...,[Mitsunobu_reaction_with_amine_alcohol_and_thi...,True,None
406,CSc1ccc(N2CCOCC2)cc1NC(=O)N1CCC[C@H](C(N)=O)C1,A5598b,openbind_a71ev2a_c2_elaborated_hits,A5598b,"[{'name': 'Buchwald-Hartwig_amination', 'react...",[Buchwald-Hartwig_amination],True,None,"[{'name': 'Buchwald-Hartwig_amination', 'react...",[Buchwald-Hartwig_amination],...,True,None,"[{'name': 'Iodo_N-arylation', 'reactantSmiles'...","[Iodo_N-arylation, Buchwald-Hartwig_amination]",True,None,"[{'name': 'Formation_of_urea_from_two_amines',...","[Formation_of_urea_from_two_amines, S-nucleoph...",True,None

In [30]:
animal.db.prune_duplicate_routes()

#routes = 20231

products with duplicate routes = 65

compound 107 has 2 duplicate routes

compound 6 has 4 duplicate routes

compound 14 has 4 duplicate routes

compound 19 has 4 duplicate routes

compound 22 has 4 duplicate routes

compound 34 has 4 duplicate routes

compound 50 has 9 duplicate routes

compound 68 has 4 duplicate routes

compound 72 has 4 duplicate routes

compound 114 has 4 duplicate routes

compound 116 has 9 duplicate routes

compound 120 has 13 duplicate routes

compound 129 has 5 duplicate routes

compound 143 has 4 duplicate routes

compound 172 has 2 duplicate routes

compound 180 has 4 duplicate routes

compound 182 has 8 duplicate routes

compound 199 has 16 duplicate routes

compound 204 has 4 duplicate routes

compound 205 has 4 duplicate routes

compound 215 has 4 duplicate routes

compound 235 has 4 duplicate routes

compound 238 has 4 duplicate routes

compound 240 has 4 duplicate routes

compound 244 has 4 duplicate routes

compound 249 has 4 duplicate routes

compound 257 has 8 duplicate routes

compound 259 has 4 duplicate routes

compound 264 has 4 duplicate routes

compound 281 has 4 duplicate routes

compound 283 has 4 duplicate routes

compound 284 has 4 duplicate routes

compound 295 has 4 duplicate routes

compound 296 has 4 duplicate routes

compound 300 has 2 duplicate routes

compound 301 has 4 duplicate routes

compound 308 has 4 duplicate routes

compound 312 has 4 duplicate routes

compound 315 has 4 duplicate routes

compound 318 has 4 duplicate routes

compound 320 has 4 duplicate routes

compound 340 has 8 duplicate routes

compound 349 has 2 duplicate routes

compound 355 has 4 duplicate routes

compound 360 has 4 duplicate routes

compound 372 has 4 duplicate routes

compound 374 has 4 duplicate routes

compound 375 has 4 duplicate routes

compound 376 has 13 duplicate routes

compound 378 has 4 duplicate routes

compound 387 has 4 duplicate routes

compound 389 has 4 duplicate routes

compound 396 has 4 duplicate routes

compound 400 has 4 duplicate routes

compound 404 has 4 duplicate routes

compound 407 has 4 duplicate routes

compound 408 has 4 duplicate routes

compound 413 has 2 duplicate routes

compound 414 has 4 duplicate routes

compound 416 has 4 duplicate routes

compound 418 has 4 duplicate routes

compound 423 has 12 duplicate routes

compound 426 has 4 duplicate routes

compound 430 has 4 duplicate routes

compound 454 has 4 duplicate routes

 Success  Deleted 246 duplicate routes!

{20382,
 20384,
 20385,
 20386,
 20390,
 20391,
 20392,
 20395,
 20396,
 20397,
 20404,
 20405,
 20406,
 20412,
 20413,
 20414,
 20415,
 20416,
 20417,
 20418,
 20419,
 20421,
 20422,
 20423,
 20427,
 20435,
 20436,
 20437,
 20439,
 20440,
 20444,
 20445,
 20446,
 20448,
 20449,
 20450,
 20451,
 20452,
 20455,
 20456,
 20461,
 20467,
 20473,
 20474,
 20477,
 20478,
 20479,
 20482,
 20483,
 20484,
 20486,
 20487,
 20489,
 20490,
 20491,
 20492,
 20493,
 20495,
 20497,
 20498,
 20499,
 20500,
 20501,
 20502,
 20505,
 20506,
 20510,
 20511,
 20512,
 20513,
 20514,
 20515,
 20516,
 20520,
 20521,
 20522,
 20524,
 20528,
 20529,
 20530,
 20536,
 20537,
 20538,
 20540,
 20541,
 20542,
 20545,
 20546,
 20547,
 20550,
 20551,
 20552,
 20554,
 20555,
 20556,
 20559,
 20560,
 20561,
 20569,
 20570,
 20571,
 20572,
 20573,
 20575,
 20576,
 20577,
 20581,
 20582,
 20583,
 20589,
 20590,
 20591,
 20592,
 20593,
 20594,
 20595,
 20597,
 20598,
 20599,
 20601,
 20602,
 20603,
 20609,
 20610,
 20611,
 20612,
 20613,
 20614,
 20615,
 20616,
 20619,
 20621,
 20624,
 20629,
 20630,
 20631,
 20632,
 20633,
 20634,
 20635,
 20636,
 20638,
 20639,
 20640,
 20643,
 20644,
 20645,
 20649,
 20650,
 20651,
 20654,
 20655,
 20656,
 20662,
 20663,
 20664,
 20668,
 20670,
 20671,
 20672,
 20674,
 20675,
 20676,
 20677,
 20678,
 20681,
 20682,
 20684,
 20685,
 20686,
 20688,
 20689,
 20690,
 20692,
 20693,
 20694,
 20696,
 20697,
 20698,
 20700,
 20701,
 20702,
 20704,
 20705,
 20706,
 20708,
 20709,
 20710,
 20712,
 20713,
 20714,
 20715,
 20718,
 20719,
 20720,
 20723,
 20724,
 20725,
 20727,
 20728,
 20729,
 20731,
 20732,
 20733,
 20735,
 20736,
 20737,
 20738,
 20739,
 20740,
 20743,
 20744,
 20745,
 20746,
 20747,
 20748,
 20749,
 20751,
 20752,
 20753,
 20755,
 20756,
 20757,
 20759,
 20760,
 20761,
 20764,
 20765,
 20766,
 20767,
 20768,
 20769,
 20771,
 20772,
 20773,
 20774,
 20775,
 20776,
 20777,
 20778,
 20779,
 20780,
 20781,
 20784,
 20785,
 20786}

In [31]:
print(elaborated_hits)
hit_elab_routes = hippo.RouteSet.from_product_ids(animal.db, elaborated_hits.ids)
hit_elab_routes

{C × 167}

Output()

{Route × 167}

In [32]:
recipes = hippo.Recipe.from_compounds(elaborated_hits, use_routes=True, pick_cheapest=False)
len(recipes)

#compounds = 167

Output()

 Success  Found solution for compound=C4!

 Success  Found solution for compound=C6!

 Success  Found solution for compound=C14!

 Success  Found solution for compound=C16!

 Success  Found solution for compound=C17!

 Success  Found solution for compound=C19!

 Success  Found solution for compound=C20!

 Success  Found solution for compound=C22!

 Success  Found solution for compound=C23!

 Success  Found solution for compound=C24!

 Success  Found solution for compound=C26!

 Success  Found solution for compound=C27!

 Success  Found solution for compound=C32!

 Success  Found solution for compound=C34!

 Success  Found solution for compound=C36!

 Success  Found solution for compound=C41!

 Success  Found solution for compound=C42!

 Success  Found solution for compound=C47!

 Success  Found solution for compound=C50!

 Success  Found solution for compound=C68!

 Success  Found solution for compound=C69!

 Success  Found solution for compound=C70!

 Success  Found solution for compound=C72!

 Success  Found solution for compound=C73!

 Success  Found solution for compound=C92!

 Success  Found solution for compound=C94!

 Success  Found solution for compound=C96!

 Success  Found solution for compound=C101!

 Success  Found solution for compound=C102!

 Success  Found solution for compound=C103!

 Success  Found solution for compound=C107!

 Success  Found solution for compound=C108!

 Success  Found solution for compound=C110!

 Success  Found solution for compound=C111!

 Success  Found solution for compound=C114!

 Success  Found solution for compound=C116!

 Success  Found solution for compound=C117!

 Success  Found solution for compound=C120!

 Success  Found solution for compound=C121!

 Success  Found solution for compound=C122!

 Success  Found solution for compound=C123!

 Success  Found solution for compound=C129!

 Success  Found solution for compound=C133!

 Success  Found solution for compound=C136!

 Success  Found solution for compound=C139!

 Success  Found solution for compound=C142!

 Success  Found solution for compound=C143!

 Success  Found solution for compound=C145!

 Success  Found solution for compound=C147!

 Success  Found solution for compound=C149!

 Success  Found solution for compound=C150!

 Success  Found solution for compound=C151!

 Success  Found solution for compound=C160!

 Success  Found solution for compound=C172!

 Success  Found solution for compound=C176!

 Success  Found solution for compound=C180!

 Success  Found solution for compound=C181!

 Success  Found solution for compound=C182!

 Success  Found solution for compound=C185!

 Success  Found solution for compound=C189!

 Success  Found solution for compound=C191!

 Success  Found solution for compound=C195!

 Success  Found solution for compound=C196!

 Success  Found solution for compound=C197!

 Success  Found solution for compound=C199!

 Success  Found solution for compound=C200!

 Success  Found solution for compound=C201!

 Success  Found solution for compound=C204!

 Success  Found solution for compound=C205!

 Success  Found solution for compound=C206!

 Success  Found solution for compound=C213!

 Success  Found solution for compound=C215!

 Success  Found solution for compound=C216!

 Success  Found solution for compound=C217!

 Success  Found solution for compound=C232!

 Success  Found solution for compound=C233!

 Success  Found solution for compound=C235!

 Success  Found solution for compound=C238!

 Success  Found solution for compound=C239!

 Success  Found solution for compound=C240!

 Success  Found solution for compound=C242!

 Success  Found solution for compound=C244!

 Success  Found solution for compound=C245!

 Success  Found solution for compound=C247!

 Success  Found solution for compound=C249!

 Success  Found solution for compound=C250!

 Success  Found solution for compound=C251!

 Success  Found solution for compound=C252!

 Success  Found solution for compound=C254!

 Success  Found solution for compound=C255!

 Success  Found solution for compound=C256!

 Success  Found solution for compound=C257!

 Success  Found solution for compound=C259!

 Success  Found solution for compound=C261!

 Success  Found solution for compound=C262!

 Success  Found solution for compound=C264!

 Success  Found solution for compound=C265!

 Success  Found solution for compound=C268!

 Success  Found solution for compound=C277!

 Success  Found solution for compound=C280!

 Success  Found solution for compound=C281!

 Success  Found solution for compound=C283!

 Success  Found solution for compound=C284!

 Success  Found solution for compound=C285!

 Success  Found solution for compound=C286!

 Success  Found solution for compound=C288!

 Success  Found solution for compound=C289!

 Success  Found solution for compound=C290!

 Success  Found solution for compound=C292!

 Success  Found solution for compound=C295!

 Success  Found solution for compound=C296!

 Success  Found solution for compound=C300!

 Success  Found solution for compound=C301!

 Success  Found solution for compound=C303!

 Success  Found solution for compound=C305!

 Success  Found solution for compound=C307!

 Success  Found solution for compound=C308!

 Success  Found solution for compound=C312!

 Success  Found solution for compound=C313!

 Success  Found solution for compound=C315!

 Success  Found solution for compound=C316!

 Success  Found solution for compound=C317!

 Success  Found solution for compound=C318!

 Success  Found solution for compound=C319!

 Success  Found solution for compound=C320!

 Success  Found solution for compound=C329!

 Success  Found solution for compound=C333!

 Success  Found solution for compound=C337!

 Success  Found solution for compound=C339!

 Success  Found solution for compound=C340!

 Success  Found solution for compound=C345!

 Success  Found solution for compound=C347!

 Success  Found solution for compound=C349!

 Success  Found solution for compound=C355!

 Success  Found solution for compound=C360!

 Success  Found solution for compound=C366!

 Success  Found solution for compound=C370!

 Success  Found solution for compound=C372!

 Success  Found solution for compound=C374!

 Success  Found solution for compound=C375!

 Success  Found solution for compound=C376!

 Success  Found solution for compound=C378!

 Success  Found solution for compound=C387!

 Success  Found solution for compound=C389!

 Success  Found solution for compound=C392!

 Success  Found solution for compound=C393!

 Success  Found solution for compound=C396!

 Success  Found solution for compound=C397!

 Success  Found solution for compound=C400!

 Success  Found solution for compound=C404!

 Success  Found solution for compound=C407!

 Success  Found solution for compound=C408!

 Success  Found solution for compound=C413!

 Success  Found solution for compound=C414!

 Success  Found solution for compound=C416!

 Success  Found solution for compound=C418!

 Success  Found solution for compound=C423!

 Success  Found solution for compound=C425!

 Success  Found solution for compound=C426!

 Success  Found solution for compound=C430!

 Success  Found solution for compound=C434!

 Success  Found solution for compound=C454!

 Success  Found solution for compound=C18032!

 Success  Found solution for compound=C204781!

 Success  Found solution for compound=C205067!

 Success  Found solution for compound=C205775!

 Success  Found solution for compound=C266892!

Solving recipe combinations...

Output()

1

In [33]:
recipe = recipes[0]
recipe.write_json("cycle_02/syndirella/retrosynthesis/openbind_a71ev2a_c2_elaborated_hits_recipe.json")

 Warning  NULL Quote: 1.00mg of C375990!

 Warning  NULL Quote: 2.00mg of C282937!

 Warning  NULL Quote: 2.00mg of C327588!

 Warning  NULL Quote: 5.00mg of C282920!

 Warning  NULL Quote: 1.00mg of C443752!

 Warning  NULL Quote: 2.00mg of C443753!

 Warning  NULL Quote: 1.00mg of C443754!

 Warning  NULL Quote: 1.00mg of C357413!

 Warning  NULL Quote: 1.00mg of C443755!

 Warning  NULL Quote: 1.00mg of C443756!

 Warning  NULL Quote: 1.00mg of C283100!

 Warning  NULL Quote: 1.00mg of C443757!

 Warning  NULL Quote: 1.00mg of C443758!

 Warning  NULL Quote: 1.00mg of C443759!

 Warning  NULL Quote: 1.00mg of C283711!

 Warning  NULL Quote: 1.00mg of C443760!

 Warning  NULL Quote: 1.00mg of C284441!

 Warning  NULL Quote: 1.00mg of C443761!

 Warning  NULL Quote: 1.00mg of C283043!

 Warning  NULL Quote: 1.00mg of C443762!

 Warning  NULL Quote: 1.00mg of C443763!

 Warning  NULL Quote: 1.00mg of C443764!

 Warning  NULL Quote: 1.00mg of C282923!

 Warning  NULL Quote: 1.00mg of C443765!

 Warning  NULL Quote: 1.00mg of C443766!

 Warning  NULL Quote: 1.00mg of C443767!

 Warning  NULL Quote: 1.00mg of C282928!

 Warning  NULL Quote: 1.00mg of C443768!

 Warning  NULL Quote: 1.00mg of C284318!

 Warning  NULL Quote: 1.00mg of C443769!

 Warning  NULL Quote: 1.00mg of C443770!

 Warning  NULL Quote: 1.00mg of C9843!

 Warning  NULL Quote: 1.00mg of C443771!

 Warning  NULL Quote: 1.00mg of C283185!

 Warning  NULL Quote: 1.00mg of C443772!

 Warning  NULL Quote: 1.00mg of C283304!

 Warning  NULL Quote: 1.00mg of C339526!

 Warning  NULL Quote: 1.00mg of C443773!

 Warning  NULL Quote: 1.00mg of C422271!

 Warning  NULL Quote: 1.00mg of C429696!

 Warning  NULL Quote: 1.00mg of C443774!

 Warning  NULL Quote: 2.00mg of C347919!

 Warning  NULL Quote: 1.00mg of C443775!

 Warning  NULL Quote: 1.00mg of C443776!

 Warning  NULL Quote: 7.00mg of C338465!

 Warning  NULL Quote: 1.00mg of C443777!

 Warning  NULL Quote: 1.00mg of C443778!

 Warning  NULL Quote: 1.00mg of C443779!

 Warning  NULL Quote: 1.00mg of C379175!

 Warning  NULL Quote: 1.00mg of C347927!

 Warning  NULL Quote: 1.00mg of C401909!

 Warning  NULL Quote: 1.00mg of C268361!

 Warning  NULL Quote: 1.00mg of C327083!

 Warning  NULL Quote: 1.00mg of C327047!

 Warning  NULL Quote: 1.00mg of C327078!

 Warning  NULL Quote: 1.00mg of C443780!

 Warning  NULL Quote: 1.00mg of C443781!

 Warning  NULL Quote: 1.00mg of C327034!

 Warning  NULL Quote: 1.00mg of C390850!

 Warning  NULL Quote: 1.00mg of C367094!

 Warning  NULL Quote: 1.00mg of C443782!

 Warning  NULL Quote: 1.00mg of C325227!

 Warning  NULL Quote: 1.00mg of C425210!

 Warning  NULL Quote: 1.00mg of C443783!

 Warning  NULL Quote: 1.00mg of C329377!

 Warning  NULL Quote: 2.00mg of C327116!

 Warning  NULL Quote: 1.00mg of C319988!

 Warning  NULL Quote: 1.00mg of C315592!

 Warning  NULL Quote: 1.00mg of C425426!

 Warning  NULL Quote: 1.00mg of C364708!

 Warning  NULL Quote: 1.00mg of C327079!

 Warning  NULL Quote: 1.00mg of C319733!

 Warning  NULL Quote: 1.00mg of C322994!

 Warning  NULL Quote: 1.00mg of C443784!

 Warning  NULL Quote: 1.00mg of C443785!

 Warning  NULL Quote: 1.00mg of C427834!

 Warning  NULL Quote: 1.00mg of C392823!

 Warning  NULL Quote: 1.00mg of C323070!

 Warning  NULL Quote: 1.00mg of C443786!

 Warning  NULL Quote: 1.00mg of C327062!

 Warning  NULL Quote: 1.00mg of C323038!

 Warning  NULL Quote: 1.00mg of C443787!

 Warning  NULL Quote: 1.00mg of C327044!

 Warning  NULL Quote: 1.00mg of C347832!

 Warning  NULL Quote: 1.00mg of C323259!

 Warning  NULL Quote: 1.00mg of C327042!

 Warning  NULL Quote: 1.00mg of C443788!

 Warning  NULL Quote: 1.00mg of C322751!

 Warning  NULL Quote: 1.00mg of C322997!

 Warning  NULL Quote: 1.00mg of C317758!

 Warning  NULL Quote: 1.00mg of C443789!

 Warning  NULL Quote: 1.00mg of C443790!

 Warning  NULL Quote: 5.00mg of C315593!

 Warning  NULL Quote: 1.00mg of C354325!

 Warning  NULL Quote: 1.00mg of C323071!

 Warning  NULL Quote: 1.00mg of C443791!

 Warning  NULL Quote: 1.00mg of C391053!

 Warning  NULL Quote: 1.00mg of C430865!

 Warning  NULL Quote: 1.00mg of C326916!

 Warning  NULL Quote: 1.00mg of C368464!

 Warning  NULL Quote: 1.00mg of C315707!

 Warning  NULL Quote: 1.00mg of C326265!

 Warning  NULL Quote: 1.00mg of C443792!

 Warning  NULL Quote: 1.00mg of C443793!

 Warning  NULL Quote: 1.00mg of C429923!

 Warning  NULL Quote: 1.00mg of C315600!

 Warning  NULL Quote: 1.00mg of C431752!

 Warning  NULL Quote: 1.00mg of C370687!

 Warning  NULL Quote: 1.00mg of C374726!

 Warning  NULL Quote: 1.00mg of C317525!

 Warning  NULL Quote: 1.00mg of C437!

 Warning  NULL Quote: 1.00mg of C443794!

 Warning  NULL Quote: 1.00mg of C347681!

 Warning  NULL Quote: 1.00mg of C335905!

 Warning  NULL Quote: 1.00mg of C315590!

 Warning  NULL Quote: 1.00mg of C319871!

 Warning  NULL Quote: 2.00mg of C282996!

 Warning  NULL Quote: 1.00mg of C323997!

 Warning  NULL Quote: 1.00mg of C1850!

 Warning  NULL Quote: 1.00mg of C325342!

 Warning  NULL Quote: 1.00mg of C315591!

 Warning  NULL Quote: 1.00mg of C443795!

 Warning  NULL Quote: 1.00mg of C443796!

 Warning  NULL Quote: 1.00mg of C319869!

 Warning  NULL Quote: 1.00mg of C315587!

 Warning  NULL Quote: 1.00mg of C443797!

 Warning  NULL Quote: 1.00mg of C443798!

 Warning  NULL Quote: 1.00mg of C338230!

 Warning  NULL Quote: 1.00mg of C317408!

 Warning  NULL Quote: 1.00mg of C443799!

 Warning  NULL Quote: 1.00mg of C315407!

 Warning  NULL Quote: 1.00mg of C370571!

 Warning  NULL Quote: 1.00mg of C327143!

 Warning  NULL Quote: 1.00mg of C325538!

 Warning  NULL Quote: 1.00mg of C443800!

 Warning  NULL Quote: 1.00mg of C443801!

 Warning  NULL Quote: 1.00mg of C268936!

 Warning  NULL Quote: 1.00mg of C320104!

 Warning  NULL Quote: 1.00mg of C443802!

 Warning  NULL Quote: 1.00mg of C443803!

 Warning  NULL Quote: 1.00mg of C443804!

 Warning  NULL Quote: 1.00mg of C443805!

 Warning  NULL Quote: 1.00mg of C443806!

 Warning  NULL Quote: 1.00mg of C374785!

 Warning  NULL Quote: 1.00mg of C315424!

 Warning  NULL Quote: 1.00mg of C177561!

 Warning  NULL Quote: 1.00mg of C443807!

 Warning  NULL Quote: 1.00mg of C323291!

 Warning  NULL Quote: 1.00mg of C443808!

 Warning  NULL Quote: 1.00mg of C319845!

 Warning  NULL Quote: 1.00mg of C141!

 Warning  NULL Quote: 1.00mg of C329353!

 Warning  NULL Quote: 1.00mg of C182944!

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_02/syndirella/retrosynthesis/openbind_a71ev2a_c2_elabor
ated_hits_recipe.json...

In [34]:
recipe.write_CAR_csv("cycle_02/syndirella/retrosynthesis/openbind_a71ev2a_c2_elaborated_hits_recipe_CAR.csv")

DEBUG: Querying database for routes

DEBUG: Assembling route dictionary

DEBUG: Checking availability

Output()

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_02/syndirella/retrosynthesis/openbind_a71ev2a_c2_elabor
ated_hits_recipe_CAR_1steps.csv...

 DISK  Writing
/opt/xchem-fragalysis-2/maxwin/openbind-hippo/a71ev2a/cycle_02/syndirella/retrosynthesis/openbind_a71ev2a_c2_elabor
ated_hits_recipe_CAR.csv...

,target-names,no-steps,concentration-required-mM,amount-required-uL,batch-tag,reactant-1-1,reactant-2-1,reaction-product-smiles-1,reaction-name-1,reaction-recipe-1,reaction-groupby-column-1,reactant-3-1
0,C176,1,None,None,None,Cn1cc2c(CC(=O)O)cccc2n1,NC(=O)C1CCNC1,Cn1cc2c(CC(=O)N3CCC(C(N)=O)C3)cccc2n1,Amidation,None,None,<NA>
1,C180,1,None,None,None,NC(=O)C1CCCCNC1,COc1ccccc1CC(=O)O,COc1ccccc1CC(=O)N1CCCCC(C(N)=O)C1,Amidation,None,None,<NA>
2,C181,1,None,None,None,NC(=O)C1CCCNC1,COc1c(C#N)cccc1CC(=O)O,COc1c(C#N)cccc1CC(=O)N1CCCC(C(N)=O)C1,Amidation,None,None,<NA>
3,C182,1,None,None,None,NC(=O)C1CCCNC1,COc1cccc(Cl)c1CC(=O)O,COc1cccc(Cl)c1CC(=O)N1CCCC(C(N)=O)C1,Amidation,None,None,<NA>
4,C185,1,None,None,None,NC(=O)C1CCCNC1,COc1ccccc1C(OC)C(=O)O,COc1ccccc1C(OC)C(=O)N1CCCC(C(N)=O)C1,Amidation,None,None,<NA>
...,...,...,...,...,...,...,...,...,...,...,...,...
162,C149,1,None,None,None,NCCc1cocn1,Cn1nc(C(=O)O)c2ccccc2c1=O,Cn1nc(C(=O)NCCc2cocn2)c2ccccc2c1=O,Amidation,None,None,<NA>
163,C150,1,None,None,None,NCCc1cocn1,O=C(O)c1ccccc1,O=C(NCCc1cocn1)c1ccccc1,Amidation,None,None,<NA>
164,C151,1,None,None,None,NCCc1cocn1,Cn1ncc(C(=O)O)n1,Cn1ncc(C(=O)NCCc2cocn2)n1,Amidation,None,None,<NA>
165,C160,1,None,None,None,NC(=O)C1CCCNC1,Cn1ncc(-c2cc(Cl)cc(Cl)c2)c1CC(=O)O,Cn1ncc(-c2cc(Cl)cc(Cl)c2)c1CC(=O)N1CCCC(C(N)=O)C1,Amidation,None,None,<NA>
166,C172,1,None,None,None,O=C(O)C1(c2ccc(Cl)cc2Cl)CCOCC1,N#CC1CC(N)C1,N#CC1CC(NC(=O)C2(c3ccc(Cl)cc3Cl)CCOCC2)C1,Amidation,None,None,<NA>

In [35]:
recipe.write_reactant_csv("cycle_02/syndirella/retrosynthesis/openbind_a71ev2a_c2_elaborated_hits_recipe_reactants.csv")

DEBUG: Querying database for routes

DEBUG: Assembling route dictionary

DEBUG: Checking availability

 DISK  Writing cycle_02/syndirella/retrosynthesis/openbind_a71ev2a_c2_elaborated_hits_recipe_reactants.csv...

## Reactants needed for full elabs

1. Quote reactatns
1. Needs route enumeration first

In [37]:
bbdb = hippo.HIPPO("BB", "../../EnamineCatalogs/enamine_bb_hippo.sqlite")

 Creating HIPPO animal

name = BB

db_path = ../../EnamineCatalogs/enamine_bb_hippo.sqlite

DEBUG: hippo.Database.__init__()

DEBUG: Database.path = ../../EnamineCatalogs/enamine_bb_hippo.sqlite

DEBUG: hippo.Database.connect()

DEBUG: sqlite3.version='2.6.0'

 Success  Database connected @ ../../EnamineCatalogs/enamine_bb_hippo.sqlite!

 Success  Initialised animal HIPPO("BB")!

In [38]:
animal.quote_reactants(bbdb)

#compounds = 18391

Output()

 Warning  Isotope(s) in SMILES: [2H]c1c([2H])c([2H])c([CH]2C[CH]2N)c([2H])c1[2H]!

 Warning  Isotope(s) in SMILES: [2H]c1c([2H])c([2H])c([CH]2C[CH]2N)c([2H])c1[2H]!

 Warning  Isotope(s) in SMILES: [2H]c1c([2H])c([2H])c([CH]2C[CH]2N)c([2H])c1[2H]!

 Warning  Isotope(s) in SMILES: [2H]c1c([2H])c([2H])c([CH]2C[CH]2N)c([2H])c1[2H]!

 Warning  Isotope(s) in SMILES: [2H]c1c([2H])c([2H])c([CH]2C[CH]2N)c([2H])c1[2H]!

 Warning  Isotope(s) in SMILES: [2H]c1c([2H])c([2H])c([CH]2C[CH]2N)c([2H])c1[2H]!

 Warning  Isotope(s) in SMILES: [2H]c1c([2H])c([2H])c([CH]2C[CH]2N)c([2H])c1[2H]!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])c1cccc(Br)c1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])c1cccc(Br)c1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])c1cccc(Br)c1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])c1cccc(Br)c1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])c1cccc(Br)c1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])c1cccc(Br)c1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])c1cccc(Br)c1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])c1cccc(C(=O)O)c1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])c1cccc(C(=O)O)c1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])c1cccc(C(=O)O)c1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])c1cccc(C(=O)O)c1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])c1cccc(C(=O)O)c1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])c1cccc(C(=O)O)c1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])c1cccc(C(=O)O)c1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NCCO!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NCCO!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NCCO!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NCCO!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NCCO!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NCCO!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NCCO!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])n1cc(N)cn1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])n1cc(N)cn1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])n1cc(N)cn1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])n1cc(N)cn1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])n1cc(N)cn1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])n1cc(N)cn1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])n1cc(N)cn1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NN!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NN!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NN!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NN!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])OCC(=O)O!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])OCC(=O)O!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])OCC(=O)O!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])OCC(=O)O!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])OCC(=O)O!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])OCC(=O)O!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])OCC(=O)O!

 Warning  Isotope(s) in SMILES: [2H]c1ccc(C(=O)O)cc1!

 Warning  Isotope(s) in SMILES: [2H]c1ccc(C(=O)O)cc1!

 Warning  Isotope(s) in SMILES: [2H]c1ccc(C(=O)O)cc1!

 Warning  Isotope(s) in SMILES: [2H]c1ccc(C(=O)O)cc1!

 Warning  Isotope(s) in SMILES: [2H]c1ccc(C(=O)O)cc1!

 Warning  Isotope(s) in SMILES: [2H]c1ccc(C(=O)O)cc1!

 Warning  Isotope(s) in SMILES: [2H]c1ccc(C(=O)O)cc1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])OS(C)(=O)=O!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])OS(C)(=O)=O!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])OS(C)(=O)=O!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])OS(C)(=O)=O!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])OS(C)(=O)=O!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])OS(C)(=O)=O!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])OS(C)(=O)=O!

 Warning  Isotope(s) in SMILES: [2H]c1cccc(C(=O)O)c1!

 Warning  Isotope(s) in SMILES: [2H]c1cccc(C(=O)O)c1!

 Warning  Isotope(s) in SMILES: [2H]c1cccc(C(=O)O)c1!

 Warning  Isotope(s) in SMILES: [2H]c1cccc(C(=O)O)c1!

 Warning  Isotope(s) in SMILES: [2H]c1cccc(C(=O)O)c1!

 Warning  Isotope(s) in SMILES: [2H]c1cccc(C(=O)O)c1!

 Warning  Isotope(s) in SMILES: [2H]c1cccc(C(=O)O)c1!

 Warning  Isotope(s) in SMILES: [2H]C1([2H])NCC2CC21c1nc(C)no1!

 Warning  Isotope(s) in SMILES: [2H]C1([2H])NCC2CC21c1nc(C)no1!

 Warning  Isotope(s) in SMILES: [2H]C1([2H])NCC2CC21c1nc(C)no1!

 Warning  Isotope(s) in SMILES: [2H]C1([2H])NCC2CC21c1nc(C)no1!

 Warning  Isotope(s) in SMILES: [2H]C1([2H])NCC2CC21c1nc(C)no1!

 Warning  Isotope(s) in SMILES: [2H]C1([2H])NCC2CC21c1nc(C)no1!

 Warning  Isotope(s) in SMILES: [2H]C1([2H])NCC2CC21c1nc(C)no1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NCC!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NCC!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NCC!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NCC!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NCC!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NCC!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NCC!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NC(C)C!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NC(C)C!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NC(C)C!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NC(C)C!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NC(C)C!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NC(C)C!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NC(C)C!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NCCC!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NCCC!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NCCC!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NCCC!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NCCC!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NCCC!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NCCC!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NC1CC1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NC1CC1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NC1CC1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NC1CC1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NC1CC1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NC1CC1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NC1CC1!

 Warning  Isotope(s) in SMILES: [2H]C1([2H])C(F)(F)C12CCN2!

 Warning  Isotope(s) in SMILES: [2H]C1([2H])C(F)(F)C12CCN2!

 Warning  Isotope(s) in SMILES: [2H]C1([2H])C(F)(F)C12CCN2!

 Warning  Isotope(s) in SMILES: [2H]C1([2H])C(F)(F)C12CCN2!

 Warning  Isotope(s) in SMILES: [2H]C1([2H])C(F)(F)C12CCN2!

 Warning  Isotope(s) in SMILES: [2H]C1([2H])C(F)(F)C12CCN2!

 Warning  Isotope(s) in SMILES: [2H]C1([2H])C(F)(F)C12CCN2!

 Warning  Isotope(s) in SMILES: [2H]C1([2H])CC12CCN2!

 Warning  Isotope(s) in SMILES: [2H]C1([2H])CC12CCN2!

 Warning  Isotope(s) in SMILES: [2H]C1([2H])CC12CCN2!

 Warning  Isotope(s) in SMILES: [2H]C1([2H])CC12CCN2!

 Warning  Isotope(s) in SMILES: [2H]C1([2H])CC12CCN2!

 Warning  Isotope(s) in SMILES: [2H]C1([2H])CC12CCN2!

 Warning  Isotope(s) in SMILES: [2H]C1([2H])CC12CCN2!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])c1cccc(Br)c1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])c1cccc(Br)c1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])c1cccc(Br)c1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])c1cccc(Br)c1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])c1cccc(Br)c1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])c1cccc(Br)c1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NCCO!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NCCO!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NCCO!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NCCO!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NCCO!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NCCO!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NCCO!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])n1cc(N)cn1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])n1cc(N)cn1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])n1cc(N)cn1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])n1cc(N)cn1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])n1cc(N)cn1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])n1cc(N)cn1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])n1cc(N)cn1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])n1cc(N)cn1!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NN!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NN!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NN!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NN!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])NN!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])OCC(=O)O!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])OCC(=O)O!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])OCC(=O)O!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])OCC(=O)O!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])OCC(=O)O!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])OCC(=O)O!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])OCC(=O)O!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])OCC(=O)O!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])OS(C)(=O)=O!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])OS(C)(=O)=O!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])OS(C)(=O)=O!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])OS(C)(=O)=O!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])OS(C)(=O)=O!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])OS(C)(=O)=O!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])OS(C)(=O)=O!

 Warning  Isotope(s) in SMILES: [2H]C([2H])([2H])OS(C)(=O)=O!

#new quotes = 111344

#quoted_compounds = 17625

#unquoted_compounds = 766

sb --job-name "a71ev2a_c2_routes" $HOME2/slurm/run_python.sh c02d_routes.py

In [42]:
hit_elabs = animal.compounds(tag="openbind_a71ev2a_c2_elabs")
hit_elabs

compounds tagged openbind_a71ev2a_c2_elabs: {C × 90420}

In [43]:
routes = hippo.RouteSet.from_product_ids(animal.db, (hit_elabs.scaffolds + hit_elabs).ids)
routes

Output()

{Route × 85229}

In [44]:
routes.reactants

{C × 6872}

In [45]:
routes.reactants.write_smiles_csv("cycle_02/syndirella/elabs/openbind_a71ev2a_c2_elab_route_reactants.csv")

 DISK  Writing cycle_02/syndirella/elabs/openbind_a71ev2a_c2_elab_route_reactants.csv...

## Crystal Hit Analogues

Queue `c02c_hit_analogues.py`

In [16]:
animal.tags.summary()

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━┓
┃ tag                                         ┃ num_compounds ┃ num_poses ┃ num_posed_compounds ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━┩
│ BAD count                                   │ 0             │ 645       │ 457                 │
│ BulkDock Fragalysis export                  │ 0             │ 1749      │ 1145                │
│ C10 85percent analogue                      │ 31            │ 0         │ 0                   │
│ C10 90percent analogue                      │ 6             │ 0         │ 0                   │
│ C10 95percent analogue                      │ 1             │ 0         │ 0                   │
│ C100 85percent analogue                     │ 32            │ 0         │ 0                   │
│ C100 90percent analogue                     │ 8             │ 0         │ 0                   │
│ C100 95percent analogue                     │ 3             │ 0         │ 0                   │
│ C101 85percent analogue                     │ 2             │ 0         │ 0                   │
│ C102 85percent analogue                     │ 5             │ 0         │ 0                   │
│ C102 90percent analogue                     │ 2             │ 0         │ 0                   │
│ C103 85percent analogue                     │ 3             │ 0         │ 0                   │
│ C104 85percent analogue                     │ 19            │ 0         │ 0                   │
│ C104 90percent analogue                     │ 6             │ 0         │ 0                   │
│ C105 85percent analogue                     │ 32            │ 0         │ 0                   │
│ C105 90percent analogue                     │ 6             │ 0         │ 0                   │
│ C106 85percent analogue                     │ 24            │ 0         │ 0                   │
│ C106 90percent analogue                     │ 2             │ 0         │ 0                   │
│ C107 85percent analogue                     │ 2             │ 0         │ 0                   │
│ C108 85percent analogue                     │ 3             │ 0         │ 0                   │
│ C108 90percent analogue                     │ 2             │ 0         │ 0                   │
│ C109 85percent analogue                     │ 108           │ 0         │ 0                   │
│ C109 90percent analogue                     │ 3             │ 0         │ 0                   │
│ C11 85percent analogue                      │ 11            │ 0         │ 0                   │
│ C11 90percent analogue                      │ 4             │ 0         │ 0                   │
│ C11 95percent analogue                      │ 3             │ 0         │ 0                   │
│ C111 85percent analogue                     │ 15            │ 0         │ 0                   │
│ C111 90percent analogue                     │ 1             │ 0         │ 0                   │
│ C112 85percent analogue                     │ 7             │ 0         │ 0                   │
│ C113 85percent analogue                     │ 4             │ 0         │ 0                   │
│ C113 90percent analogue                     │ 1             │ 0         │ 0                   │
│ C114 85percent analogue                     │ 7             │ 0         │ 0                   │
│ C114 90percent analogue                     │ 2             │ 0         │ 0                   │
│ C115 85percent analogue                     │ 129           │ 0         │ 0                   │
│ C115 90percent analogue                     │ 8             │ 0         │ 0                   │
│ C116 85percent analogue                     │ 3             │ 0         │ 0                   │
│ C117 85percent analogue                     │ 5             │ 0         │ 0                   │
│ C117 90percent analogue                     │ 1             │ 0         │ 0                   │
│ C119 85percent analogue                     │ 6             │ 0         │ 0                   │
│ C12 85percent analogue                      │ 38            │ 0         │ 0                   │
│ C12 90percent analogue                      │ 16            │ 0         │ 0                   │
│ C12 95percent analogue                      │ 3             │ 0         │ 0                   │
│ C120 85percent analogue                     │ 2             │ 0         │ 0                   │
│ C121 85percent analogue                     │ 17            │ 0         │ 0                   │
│ C122 85percent analogue                     │ 7             │ 0         │ 0                   │
│ C123 85percent analogue                     │ 12            │ 0         │ 0                   │
│ C123 90percent analogue                     │ 3             │ 0         │ 0                   │
│ C127 85percent analogue                     │ 3             │ 0         │ 0                   │
│ C128 85percent analogue                     │ 11            │ 0         │ 0                   │
│ C128 90percent analogue                     │ 2             │ 0         │ 0                   │
│ C129 85percent analogue                     │ 26            │ 0         │ 0                   │
│ C129 90percent analogue                     │ 1             │ 0         │ 0                   │
│ C13 85percent analogue                      │ 14            │ 0         │ 0                   │
│ C13 90percent analogue                      │ 2             │ 0         │ 0                   │
│ C13 95percent analogue                      │ 1             │ 0         │ 0                   │
│ C132 85percent analogue                     │ 10            │ 0         │ 0                   │
│ C136 85percent analogue                     │ 2             │ 0         │ 0                   │
│ C136 90percent analogue                     │ 1             │ 0         │ 0                   │
│ C137 85percent analogue                     │ 1             │ 0         │ 0                   │
│ C138 85percent analogue                     │ 100           │ 0         │ 0                   │
│ C138 90percent analogue                     │ 11            │ 0         │ 0                   │
│ C139 85percent analogue                     │ 28            │ 0         │ 0                   │
│ C139 90percent analogue                     │ 4             │ 0         │ 0                   │
│ C14 85percent analogue                      │ 64            │ 0         │ 0                   │
│ C14 90percent analogue                      │ 14            │ 0         │ 0                   │
│ C14 95percent analogue                      │ 4             │ 0         │ 0                   │
│ C140 85percent analogue                     │ 1             │ 0         │ 0                   │
│ C141 85percent analogue                     │ 16            │ 0         │ 0                   │
│ C142 85percent analogue                     │ 1             │ 0         │ 0                   │
│ C143 85percent analogue                     │ 1             │ 0         │ 0                   │
│ C146 85percent analogue                     │ 24            │ 0         │ 0                   │
│ C146 90percent analogue                     │ 4             │ 0         │ 0                   │
│ C147 85percent analogue                     │ 1             │ 0         │ 0                   │
│ C148 85percent analogue                     │ 16            │ 0         │ 0                   │
│ C149 85percent analogue                     │ 8             │ 0         │ 0                   │
│ C15 85percent analogue                      │ 56            │ 0         │ 0                   │
│ C15 90percent analogue                      │ 13            │ 0         │ 0                   │
│ C15 95percent analogue                      │ 5             │ 0         │ 0                   │
│ C152 85percent analogue                     │ 4             │ 0         │ 0                   │
│ C152 90percent analogue                     │ 1             │ 0         │ 0                   │
│ C153 85percent analogue                     │ 49            │ 0         │ 0                   │
│ C153 90percent analogue                     │ 2             │ 0         │ 0                   │
│ C154 85percent analogue                     │ 76            │ 0         │ 0                   │
│ C155 85percent analogue                     │ 33            │ 0         │ 0                   │
│ C156 85percent analogue                     │ 42            │ 0         │ 0                   │
│ C156 90percent analogue                     │ 5             │ 0         │ 0                   │
│ C158 85percent analogue                     │ 52            │ 0         │ 0                   │
│ C158 90percent analogue                     │ 1             │ 0         │ 0                   │
│ C159 85percent analogue                     │ 106           │ 0         │ 0                   │
│ C159 90percent analogue                     │ 4             │ 0         │ 0                   │
│ C16 85percent analogue                      │ 30            │ 0         │ 0                   │
│ C16 90percent analogue                      │ 1             │ 0         │ 0                   │
│ C160 85percent analogue                     │ 4             │ 0         │ 0                   │
│ C161 85percent analogue                     │ 49            │ 0         │ 0                   │
│ C161 90percent analogue                     │ 3             │ 0         │ 0                   │
│ C162 85percent analogue                     │ 93            │ 0         │ 0                   │
│ C162 90percent analogue                     │ 6             │ 0         │ 0                   │
│ C163 85percent analogue                     │ 75            │ 0         │ 0                   │
│ C163 90percent analogue                     │ 4             │ 0         │ 0                   │
│ C164 85percent analogue                     │ 27            │ 0         │ 0                   │
│ C166 85percent analogue                     │ 33            │ 0         │ 0                   │
│ C166 90percent analogue                     │ 1             │ 0         │ 0                   │
│ C167 85percent analogue                     │ 51            │ 0         │ 0                   │
│ C167 90percent analogue                     │ 4             │ 0         │ 0                   │
│ C168 85percent analogue                     │ 3             │ 0         │ 0                   │
│ C169 85percent analogue                     │ 9             │ 0         │ 0                   │
│ C169 90percent analogue                     │ 1             │ 0         │ 0                   │
│ C17 85percent analogue                      │ 2             │ 0         │ 0                   │
│ C170 85percent analogue                     │ 19            │ 0         │ 0                   │
│ C170 90percent analogue                     │ 2             │ 0         │ 0                   │
│ C171 85percent analogue                     │ 80            │ 0         │ 0                   │
│ C171 90percent analogue                     │ 5             │ 0         │ 0                   │
│ C172 85percent analogue                     │ 6             │ 0         │ 0                   │
│ C173 85percent analogue                     │ 6             │ 0         │ 0                   │
│ C174 85percent analogue                     │ 32            │ 0         │ 0                   │
│ C174 90percent analogue                     │ 1             │ 0         │ 0                   │
│ C175 85percent analogue                     │ 60            │ 0         │ 0                   │
│ C175 90percent analogue                     │ 6             │ 0         │ 0                   │
│ C177 85percent analogue                     │ 76            │ 0         │ 0                   │
│ C177 90percent analogue                     │ 8             │ 0         │ 0                   │
│ C177 95percent analogue                     │ 1             │ 0         │ 0                   │
│ C178 85percent analogue                     │ 160           │ 0         │ 0                   │
│ C178 90percent analogue                     │ 8             │ 0         │ 0                   │
│ C179 85percent analogue                     │ 1             │ 0         │ 0                   │
│ C18 85percent analogue                      │ 24            │ 0         │ 0                   │
│ C18 90percent analogue                      │ 2             │ 0         │ 0                   │
│ C180 85percent analogue                     │ 34            │ 0         │ 0                   │
│ C180 90percent analogue                     │ 1             │ 0         │ 0                   │
│ C181 85percent analogue                     │ 54            │ 0         │ 0                   │
│ C181 90percent analogue                     │ 3             │ 0         │ 0                   │
│ C182 85percent analogue                     │ 26            │ 0         │ 0                   │
│ C182 90percent analogue                     │ 2             │ 0         │ 0                   │
│ C183 85percent analogue                     │ 186           │ 0         │ 0                   │
│ C183 90percent analogue                     │ 16            │ 0         │ 0                   │
│ C184 85percent analogue                     │ 34            │ 0         │ 0                   │
│ C184 90percent analogue                     │ 1             │ 0         │ 0                   │
│ C185 85percent analogue                     │ 29            │ 0         │ 0                   │
│ C185 90percent analogue                     │ 1             │ 0         │ 0                   │
│ C186 85percent analogue                     │ 17            │ 0         │ 0                   │
│ C187 85percent analogue                     │ 42            │ 0         │ 0                   │
│ C187 90percent analogue                     │ 1             │ 0         │ 0                   │
│ C188 85percent analogue                     │ 47            │ 0         │ 0                   │
│ C188 90percent analogue                     │ 5             │ 0         │ 0                   │
│ C188 95percent analogue                     │ 1             │ 0         │ 0                   │
│ C189 85percent analogue                     │ 54            │ 0         │ 0                   │
│ C189 90percent analogue                     │ 1             │ 0         │ 0                   │
│ C19 85percent analogue                      │ 1             │ 0         │ 0                   │
│ C190 85percent analogue                     │ 11            │ 0         │ 0                   │
│ C191 85percent analogue                     │ 8             │ 0         │ 0                   │
│ C191 90percent analogue                     │ 1             │ 0         │ 0                   │
│ C192 85percent analogue                     │ 7             │ 0         │ 0                   │
│ C193 85percent analogue                     │ 14            │ 0         │ 0                   │
│ C194 85percent analogue                     │ 31            │ 0         │ 0                   │
│ C195 85percent analogue                     │ 45            │ 0         │ 0                   │
│ C195 90percent analogue                     │ 2             │ 0         │ 0                   │
│ C196 85percent analogue                     │ 16            │ 0         │ 0                   │
│ C198 85percent analogue                     │ 36            │ 0         │ 0                   │
│ C198 90percent analogue                     │ 2             │ 0         │ 0                   │
│ C198 95percent analogue                     │ 1             │ 0         │ 0                   │
│ C199 85percent analogue                     │ 15            │ 0         │ 0                   │
│ C199 90percent analogue                     │ 1             │ 0         │ 0                   │
│ C2 85percent analogue                       │ 2             │ 0         │ 0                   │
│ C20 85percent analogue                      │ 118           │ 0         │ 0                   │
│ C20 90percent analogue                      │ 7             │ 0         │ 0                   │
│ C20 95percent analogue                      │ 1             │ 0         │ 0                   │
│ C200 85percent analogue                     │ 11            │ 0         │ 0                   │
│ C201 85percent analogue                     │ 38            │ 0         │ 0                   │
│ C201 90percent analogue                     │ 1             │ 0         │ 0                   │
│ C202 85percent analogue                     │ 141           │ 0         │ 0                   │
│ C202 90percent analogue                     │ 14            │ 0         │ 0                   │
│ C202 95percent analogue                     │ 1             │ 0         │ 0                   │
│ C203 85percent analogue                     │ 87            │ 0         │ 0                   │
│ C203 90percent analogue                     │ 7             │ 0         │ 0                   │
│ C204 85percent analogue                     │ 3             │ 0         │ 0                   │
│ C205 85percent analogue                     │ 7             │ 0         │ 0                   │
│ C206 85percent analogue                     │ 8             │ 0         │ 0                   │
│ C207 85percent analogue                     │ 4             │ 0         │ 0                   │
│ C209 85percent analogue                     │ 42            │ 0         │ 0                   │
│ C209 90percent analogue                     │ 3             │ 0         │ 0                   │
│ C21 85percent analogue                      │ 3             │ 0         │ 0                   │
│ C210 85percent analogue                     │ 4             │ 0         │ 0                   │
│ C211 85percent analogue                     │ 26            │ 0         │ 0                   │
│ C211 90percent analogue                     │ 1             │ 0         │ 0                   │
│ C212 85percent analogue                     │ 228           │ 0         │ 0                   │
│ C212 90percent analogue                     │ 16            │ 0         │ 0                   │
│ C213 85percent analogue                     │ 26            │ 0         │ 0                   │
│ C214 85percent analogue                     │ 2             │ 0         │ 0                   │
│ C215 85percent analogue                     │ 9             │ 0         │ 0                   │
│ C218 85percent analogue                     │ 26            │ 0         │ 0                   │
│ C219 85percent analogue                     │ 14            │ 0         │ 0                   │
│ C219 90percent analogue                     │ 1             │ 0         │ 0                   │
│ C22 85percent analogue                      │ 14            │ 0         │ 0                   │
│ C22 90percent analogue                      │ 1             │ 0         │ 0                   │
│ C221 85percent analogue                     │ 3             │ 0         │ 0                   │
│ C221 90percent analogue                     │ 1             │ 0         │ 0                   │
│ C222 85percent analogue                     │ 30            │ 0         │ 0                   │
│ C223 85percent analogue                     │ 8             │ 0         │ 0                   │
│ C226 85percent analogue                     │ 1             │ 0         │ 0                   │
│ C227 85percent analogue                     │ 20            │ 0         │ 0                   │
│ C228 85percent analogue                     │ 1             │ 0         │ 0                   │
│ C229 85percent analogue                     │ 35            │ 0         │ 0                   │

In [17]:
!mkdir cycle_02/analogues

In [18]:
animal.compounds(tag="openbind_a71ev2a_c2_hit_analogues_85percent").write_smiles_csv("cycle_02/analogues/openbind_a71ev2a_c2_hit_analogues_85percent.csv")

 DISK  Writing cycle_02/analogues/openbind_a71ev2a_c2_hit_analogues_85percent.csv...

In [19]:
animal.compounds(tag="openbind_a71ev2a_c2_hit_analogues_90percent").write_smiles_csv("cycle_02/analogues/openbind_a71ev2a_c2_hit_analogues_90percent.csv")

 DISK  Writing cycle_02/analogues/openbind_a71ev2a_c2_hit_analogues_90percent.csv...

In [20]:
animal.compounds(tag="openbind_a71ev2a_c2_hit_analogues_95percent").write_smiles_csv("cycle_02/analogues/openbind_a71ev2a_c2_hit_analogues_95percent.csv")

 DISK  Writing cycle_02/analogues/openbind_a71ev2a_c2_hit_analogues_95percent.csv...

## Fragment Superstructures